### ISSUE TITLE
Enable duplicate values

### ISSUE THREAD

**Issue by takacsot** [select2/select2#1002]
Feature idea:

It would be great to enable duplicate values when multiselect is enabled.

Scenario: having the input and I want to add custom DSL: example: `apple and dog and cat`.

Each of the words should be a token (`and` is a "reserved" word) what I could parse on server side. for this scenario I would need an option to enable duplicate tokens and keep the order of tokens.

thank you very much in advance

**Comment by kevin-brown** [comment]
This was fixed in 4.0, you should be able to use duplicate ids now and it should work relatively well.

**Comment by steverob** [comment]
@kevin-brown how do we use this option? Or can you let us know the commit that fixed this?

**Comment by kevin-brown** [comment]
It should work out of the box for a standard select.

http://jsbin.com/zarexequpu/1/

**Comment by bvbmedia** [comment]
It's clear to me that it is not working in the standard select. Try to add orange two times and it dissapears. :( http://jsbin.com/zarexequpu/1/

**Comment by cubitus81** [comment]
Hi, 

Using your example, how can I set the select2 to allow input like "Orange, Orange, Rose"?

Thank you for your help.

https://jsfiddle.net/cubitus81/p76fsgp9/1/

**Comment by versusnja** [comment]
@kevin-brown Could you please help us understand how to enter "Orange", "Apple", "Orange" using Select2 v.4.0? 
Currently Select2 quietly ignores duplicate input - closes the pulldown and does not add the new "Orange". Or when I choose from the dropdown it actually removes the previous "oragne", which is even worse.

I will appreciate your help.

**Comment by isabella317** [comment]
is there some answer for this ?

**Comment by wecreatedigital** [comment]
I would also like to know how to configure my select2 for duplicate values!

**Comment by cutemonster** [comment]
Yes, need this feature please

**Comment by ptheohar** [comment]
Me also. Let us know!

**Comment by agentdtf** [comment]
I need to know how to use this feature also.

**Comment by ptheohar** [comment]
It has been mentioned by kevin-brown [here](https://github.com/select2/select2/issues/3958) that this is possible only with extra code and not out of the box.

**Comment by axel-rutz** [comment]
It would really be helpful if some information or hint on that extra code could be linked. That lin to #3958 does not have any.

**Comment by axel-rutz** [comment]
Maybe here: https://github.com/select2/select2/issues/3341#issuecomment-101382547

**Comment by raoniz** [comment]
@kevin-brown Need this feature. Kindly guide on how to enable it as the default behavior is as stated by @versusnja :


> @kevin-brown Could you please help us understand how to enter "Orange", "Apple", "Orange" using Select2 v.4.0?
> Currently Select2 quietly ignores duplicate input - closes the pulldown and does not add the new "Orange". Or when I choose from the dropdown it actually removes the previous "oragne", which is even worse.
> 
> I will appreciate your help.

**Comment by RoniNiklas** [comment]
For a workaround, see NSDont's answer at https://stackoverflow.com/questions/14976099/select2-multiselect-duplicates-values

**Comment by jimhavrilla** [comment]
did this ever get added?  NSDont's answer does not work for me at all.  If I have a pre-populated list, I cannot reselect.  i feel like a simple class type that allows this optionally would be great.

**Comment by tresteam** [comment]
Hi all,
This would be a nice feature. Need it.
