### ISSUE TITLE
BUG Keyboard entry is not working on IOS (iPhone / Ipad) for multi-select inputs

### ISSUE THREAD

**Issue by atomgiant** [select2/select2#1018]
All of the multi-select inputs from the examples page are currently not working on IOS: http://ivaynberg.github.com/select2/

Any multi-select input that has one or more selected entries causes IOS to no longer allow you to enter data via the keyboard.  I suspect it has something to do with the select2-input not being selectable from IOS.

I've verified this on Select2 v3.3.1 and master as of 03/12/2013.

**Comment by leochzl** [comment]
Hello,

Maybe it's not the same problem, but with select2 4.0.X, I had the same bug for select multiple... On IOS (iPad or iPhone), when I click to the selector, the list open, keyboard appear but there is no character displaying when I click on the keyboard...

It comes from the CSS attribute "all: unset; " - I had to remove it
