### ISSUE TITLE
attribute "title" for option element

### ISSUE THREAD

**Issue by kodram** [select2/select2#1071]
attribute "title" for option element

Example:

``` html
<select>
  <option value="1" title="Germany">DE</option>
  <option value="2" title="United Kingdom">GB</option>
  <option value="3" title="United States">US</option>
</select>
```

http://jsfiddle.net/Nt5xv/

**Comment by pauldraper** [comment]
I don't see a reason not to support this by default in select2, since `title` works for vanilla `<select>` in most browsers.

In any case,

```javascript
function(item) {
    return $('<div>', {title: item.element[0].title}).text(item.text);
}
```

works for `formatResult`/`formatSelection`.
