### ISSUE TITLE
Going from select2 box to another requires two clicks

### ISSUE THREAD

**Issue by TheSisb** [select2/select2#1078]
If I'm focused on one select2 box and then click on the next one, my first click closes the options and my second click is what actually triggers the open on the next select box.
Tested on latest chrome.

I also have a select2 box with over 1000 entries, but it gets unbearable laggy in terms of highlighting entries and scrolling.  Is there any tweak I can do to make it perform better (other than infinite scrolling which requires some backend work)?

Thanks

**Comment by sangar82** [comment]
@dana-shalev any new with having to click twice to set the focus? I have same problem with version 4

**Comment by dvtan** [comment]
Select2 still has this problem out-of-the-box in 2019 lol

**Comment by jbcordina** [comment]
Found a working-but-maybe-not-best solution : 
```
$(document).ready(function () {
    $('body').on("select2:close", function () {
        $(document).on("mousedown touchstart click", function(e) {
            e.target.focus();
        });
    });
});
```

**Comment by tranhuuhien1990** [comment]
Select2 still has this problem out-of-the-box in end of 2020
