### ISSUE TITLE
The "resolve" width is getting calculated before templating is applied

### ISSUE THREAD

**Issue by shefik** [select2/select2#1079]
The "resolve" width is getting calculated before templating is applied - http://ivaynberg.github.com/select2/select2-latest.html#templating. As a result, the select menu may end up with an unwanted wrap. There should be an option to have the width calculated after any templating.

**Comment by derekm** [comment]
I think I'm seeing this problem in select2-4.0.0. "element" and "resolve" sizing options don't calculate width in a way that considers contributions from the templates (e.g., adding 28px wide icons to results).
