### ISSUE TITLE
Feature Request:  click on group to select all elements in group.

### ISSUE THREAD

**Issue by fingermark** [select2/select2#1087]
I love select2's group support.  It'd be nice to be able to click on a group name and select all elements in that group.  This should be configurable to enable or disable this feature.

**Comment by Mehrdad-Dadkhah** [comment]
not work with Select2 4.0.3

**Comment by edtownend** [comment]
Thought I'd leave my solution for version 3.x that selects all children of an optgroup, removing the optgroup header. The parent object must have an id property. Add it to the change event.

`function(event) {
        if (
            event.added &&
            event.added.children
        ) {
            var $select = $(this),
                data = $select.select2('data'),
                pos = event.val.indexOf( event.added.id ),
                children = data[pos].children;

            // remove parent
            data.splice(pos, 1);

            // add children of parent
            $.each(children, function(index, val) {
                data.push(val);
            });

            $select.select2('data', data);
        }
    };`
