### ISSUE TITLE
disabled is ignored in IE8 and IE9

### ISSUE THREAD

**Issue by phazei** [select2/select2#1104]
I tried my site on IE8/9 and the disabled fields are still work as if they weren't disabled.  In FF and Chrome they are disabled and setting .prop('disabled',true/false) toggles it, but in IE it has no effect.

Edit:
doing a trace it seems in IE,
el.bind("propertychange.select2 DOMAttrModified.select2", sync);
is triggered when disabling disabled, but not when enabling disabled.
eg
.prop('disabled', false) // event triggered
.prop('disabled', true) // event NOT triggered

**Comment by Cedoriku** [comment]
Hey everybody!
June 2015 and I re-up this thread!  cause unfortunately none of the answers given has worked for me :/

@ivaynberg "call $().select2("enabled", false) instead,..."
This throws me an error in IE9, saying 'enabled' is not a method of the object.

@cmcnulty for me, the plugin didn't work.

My solution was finally:

TO DISABLE:
// I keep the original code working with other browsers
$('#mySelect').prop("disabled", true);
$('#mySelect').val('');

/** FIX IE9 **/
if(navigator.userAgent.indexOf('MSIE 9') !== -1){
	$('#mySelect').select2("destroy");
	$('#mySelect').removeClass('select2'); // because I customized the original select for it to disappear when select2 was on
}


TO ENABLE BACK:
// Original code for other browsers not screwing my head off
$('#mySelect').prop("disabled", false);

/** FIX IE9 **/
if(navigator.userAgent.indexOf('MSIE 9') !== -1){
	$('#mySelect').addClass('select2');
	$('#mySelect').select2({/* options */});
}

**Comment by kevin-brown** [comment]
> This throws me an error in IE9, saying 'enabled' is not a method of the object.

Sounds like you are using 4.0.0, this thread is about the 3.x branch of Select2. If there is an issue in 4.0.0 (and a ticket doesn't exist for it), please create a new ticket with a jsbin/jsfiddle that reproduces the issue.

**Comment by Carobit** [comment]
I just faced this problem with IE9 too. I'm using select2 3.5.2. For me the best and easiest solution was to use the select2 enable(boolean) option. 
$('#myselect').select2("enable", true); to enable the element and $('#myselect').select2("enable", false); to disable it.

**Comment by mistaio** [comment]
Hi everyone!!

I tried this and it works on IE9...

$("#mySelect").prop('disabled', true);
if($.browser.msie) {
	$("#mySelect").select2({width:"230px"});
}

**Comment by qinershi** [comment]
Not in a very good way, but work, hope help, see https://github.com/select2/select2/blob/master/src/js/select2/core.js#L364

$('#select2').data('select2').trigger('disable', {})
$('#select2').data('select2').trigger('enable', {})

Select2 would have some APIs like below, but it warning https://github.com/select2/select2/blob/master/src/js/select2/core.js#L495

select2.enable();
select2.disable();
