### ISSUE TITLE
extend the original tags array after init

### ISSUE THREAD

**Issue by fxck** [select2/select2#1115]
How would I do this?

let's say my `tags` looks like this now 

``` javascript
[{id: 4, text: 'foo'}, {id: 5, text: 'bar'}]
```

and I wanted to extend it with `{id: 6, text: 'foo1'}`, AFTER the select2 was initialized...

So far I only managed to do it by destroying and reinitializing select2

**Comment by helpse** [comment]
And it's not working on current select2 4.0.0. Anyone knows how to make it work now?
