### ISSUE TITLE
select2('val', id) has no effect

### ISSUE THREAD

**Issue by chris-martin** [select2/select2#112]
## Example 1

``` js
$('<div/>')
    .appendTo('body')
    .select2({ data: [ { id: 1, text: 'One' }, { id: 2, text: 'Two' } ] })
    .select2('val', 2);
```

Expected: Adds a select2 to the body with options "One" and "Two", and selections option "Two".

Result: Adds a select2 to the body, but nothing is selected.
## Example 2

Context: http://ivaynberg.github.com/select2/ in the "Loading Array Data" sections

``` js
$('#e10').select2('val', 2)
```

Expected: Changes the value of the first select2 in that section to "duplicate".

Result: No effect.

**Comment by aqueeel** [comment]
@JacobEvelyn  It will be a great if you explain how you figured it out. People with same problem can end their search here.

Thanks for opening this issue.

**Comment by JacobEvelyn** [comment]
@aqueeel I honestly don't remember and no longer have access to this code, sorry!
