### ISSUE TITLE
select2 + bootstrap modal = weird scrolling

### ISSUE THREAD

**Issue by KidkArolis** [select2/select2#1147]
If the modal dialog doesn't fit into the viewport, the background page scrolls when select2 is opened. No idea why this would be happening.

http://jsfiddle.net/byJy8/1/

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.

**Comment by drekinov** [comment]
:+1: 

Still a problem with 4.0.0.beta3.
When bootstrap modal has a tabindex=-1,0,-2,... then select2 search input inside dropdown is not focusable.
Bootstrap's tabindex is required so `esc` can work and close modal with keyboard

**Comment by drekinov** [comment]
Well it is not really select2 issue.
When select2 should be inside modal then in version 4.0.0 it will work if 
`dropdownParent` is specified with jquery selector inside modal.
e.g.:

```javascript
$('.modal .select2').select2({dropdownParent: $('.modal')})
```

which loads dropdown container inside modal and not page body

**Comment by xcash** [comment]
@drekinov err.. not really. specifying `dropdownParent` will open the dropdown at the bottom of the modal.. :( it's still an issue using BS3.3.5

**Comment by kevin-brown** [comment]
This ticket is a duplicate of https://github.com/select2/select2/issues/600#issuecomment-102857595, which has a working fix (also mentioned earlier).
