### ISSUE TITLE
Dropdown becomes very small after cancelled search

### ISSUE THREAD

**Issue by inolil** [select2/select2#1170]
Hi,

I have a multiple select with attribute "width" = 300. The select2 works well with
$("#taskmanagerbundle_tasktype_requierements").select2({
                placeholder: "Select a required task",
                allowClear: true
              });

But when I perform a search without selecting any result (by clicking outside the field), the field becomes very small, almost the width of the scrollbar and then stays this way, making me impossible to read the options when I re-click on it.
![Capture-8](https://f.cloud.github.com/assets/1917264/361816/24f7b2b8-a1d4-11e2-85f1-3dccd67004e0.png)

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
