### ISSUE TITLE
selecting elements won't work, if a parent element with tabindex=-1 exists

### ISSUE THREAD

**Issue by ghost** [select2/select2#119]
this can easily be reproduced inside a jQuery dialog which is initialized with the attribute "tabindex=-1".

Selecting with Tab/Enter works fine, but clicking a list element will trigger the dialogs "focusin" event in FF & Chrome which results in canceling the dropdown before the onSelect-function is triggered.

setting tabindex=-1 on the ".select2-container" seems to resolve the problem

**Comment by duleorlovic** [comment]
I think this is still an issue.
Here is example https://jsfiddle.net/w9nqqhne/
