### ISSUE TITLE
DropDown Direction changes

### ISSUE THREAD

**Issue by jrohit** [select2/select2#1192]
I'm using multiselect option of select2 with ',' as a token tokenSeparators. Now when i select few choices then the direction of dropdown is changed. 

When i click, the dropdown is loaded in below direction, after selecting few choices, drop down loads in above direction. Again after selecting few choices, its loaded in below direction. Why is these random behavior shown by drop down.

**Comment by babarmashkoor** [comment]
Is there any resolution on that yet
