### ISSUE TITLE
tagging new option when attaching to a <select> element

### ISSUE THREAD

**Issue by uicestone** [select2/select2#1193]
I'm using select2 attaching to a &lt;select&gt; element. and I need a feature like "tagging" or createSearchChoice, which will add an &lt;option&gt; to &lt;select&gt; automatically.

or at least i need a callback when fired on no result select.

i've tried "formatNoMatches" but i cannot catch the noresult message click event or enter press event.

can anyone help me.

UPDATE:
i'm almost hacking select2 by writing the code below, which temporary solved my problem. could that be more neat?
<code>
                options.formatNoMatches=function(term){
                    var that=this;
                    this.element.data().select2.results.off('.addnewoption').on('click.addnewoption',function(){
                        that.element.append($('<option/>',{text:term,value:term,selected:'selected'})).trigger('change');
                    });
                    return 'add new label: '+term;
                };

</code>

**Comment by mmahalwy** [comment]
@ivaynberg any update on this on current/future versions

**Comment by kevin-brown** [comment]
@mmahalwy This was addressed in 4.0.0.
