### ISSUE TITLE
Data from database does not display in select2

### ISSUE THREAD

**Issue by del-zzz-ves** [select2/select2#1200]
When i try to load data into select2, it shows searching but nothing displays in select2.
pls find my code below

Html

<input type="hidden" id="appto" name="appto" class="styleform"/>

Jquery

$("#appto").select2({
     minimumInputLength:2,
     placeholder: "Select a Value",
     id: function(e) { return e.staffid; },

  ajax:{
        url: 'selecttwo.php',
        dataType:'json',
        quietMillis:100,
        allowClear: true,
        data:function(term, page){
                return{
            fname: term,
            page_limit: 10,
            page: page

```
            };
    }
    ,
    results: function (data, page) {

        var more=(page * 10) <  data.total;

   return{ 
        results: data.results.staffname, more:more };

     }   
    },
    formatResult:function(staffname){

     return "<div class='select2-user-result'>" + staffname.fname+ "</div>";
    },
    formatSelection:function(staffname){
        return staffname.fname;
    },
    initSelection:function(element, callback){
        var elementId=$(element).val();
        var elementtext=$(element).attr('data-init-text');
        callback({"staffid":elementId, "staffname":elementtext});

    }
    }); 
```

php
$q=(isset($_GET['fname'])?$_GET['fname']:NULL);
$limit=20;

```
$query="Select * From staffdetails 
    WHERE (FIRSTNAME LIKE '%$q%' OR SURNAME LIKE '%$q%')
    ORDER BY FIRSTNAME ASC 
    LIMIT $limit";
$result = $mysqli->query($query) or die('Problem preparing query');

if($result->num_rows>0)
        {
    while($row = $result-> fetch_assoc())
        {
        $staffid=$row["STAFFNUMBER"];
        $firstname=$row["FIRSTNAME"];
        $middlename=$row["MIDDLENAME"];
        $surname=$row["SURNAME"];

        if($middlename==="")
        {

       $answer[]=array("staffid"=>$staffid, "staffname"=>$firstname." ".$surname);

        }
        else
        {

         $answer[]=array("staffid"=>$staffid, "staffname"=>$firstname." ".$middlename." ".$surname);

        }
        }
```

}
else{
    //$answer[]=array("id"=>0,"text"=>'No results found..');
     $answer[]=array("staffid"=>0, "staffname"=>'No results found..');
    // $answer['results']=array(0,'No results found..');
}
$res= new stdClass();
$res->total=count($answer);
$res->results= $answer;
 echo json_encode($res);

**Comment by takunda91** [comment]
How did you resolve that, i am encountering the same problem, should i change the select2.min.js?
