### ISSUE TITLE
I want to set the focus to the next element, when pressing Enter key  

### ISSUE THREAD

**Issue by listen99** [select2/select2#1209]
first , focus is on the select element.
at this time, press Enter key , i want to set the focus to the next element.

Could you tell me how to code.

thank you very much.

**Comment by soledadtctvtn** [comment]
We cannot implement this on web-form, because web pages differ win-form absolutely. I dont agree with @akgargo code above, so that it prevent default behavior of html process page on browser!

**Comment by kabircse** [comment]
Best way to highlighting keyboard tab event in select2().

**Comment by sambsa** [comment]
I also have the same problem. I have a select2() drop-down and a input box. At first the focus will be on drop down so when the user hit Enter key the drop down will be opened. In onchange method of drop down I am adding focus to the text box using focus() method of jQuery. But it  is not focusing to text box, rather it focus to the drop down itself. What to do guys!!

**Comment by NatShaw** [comment]
Fixed: setTimeout(yourFocusFunction, 0);

**Comment by lbeckman-mdsol** [comment]
```
export class Select2Override extends Select2 {
  attachEventHandlers = (props) => {
    props.events.forEach((event) => {
      if (typeof props[event[1]] !== 'undefined') {
        if (event[0] === 'change.react-select2-wrapper') {
          const changeHandler = props[event[1]];
          this.el.on(event[0], (e) => {
            changeHandler(e);
            setTimeout(() => { e.target.focus(); }, 0);
          });
        } else {
          this.el.on(event[0], props[event[1]]);
        }
      }
    });
  };
}
```

**Comment by gopalakrishnach** [comment]
I am working on HTML5, Angular 4 application using Tyepscript. My problem is I am able to set focus to next cell when I press enter. But when I refresh/reload page it is not working. Here is my stackoverflow question. 

https://stackoverflow.com/questions/47949110/page-refresh-enter-arrow-keys-not-working-in-table-cells

**Comment by alexweissman** [comment]
Usage questions should be discussed on the [forums](https://forums.select2.org) instead.
