### ISSUE TITLE
Select2 search broken inside jQuery UI 1.10.x modal Dialog

### ISSUE THREAD

**Issue by UltCombo** [select2/select2#1246]
## [>> test case](http://jsbin.com/ipejup/17)

As per discussion with Scott Gonzalez [here](http://bugs.jqueryui.com/ticket/9271), since [Select2's dropdown is always appended directly to the document body](https://github.com/ivaynberg/select2/blob/da7dd51294b481fe201bb89b9bb80d397c4bd627/select2.js#L1164), it isn't registered as a [valid interaction target](https://github.com/jquery/jquery-ui/blob/master/ui/jquery.ui.dialog.js#L695) when inside of a modal Dialog.

Would it be desirable to add an option to set the container which the Select2 instance should be appended to? Similar to the jQuery UI's [z-index and stacking](http://wiki.jqueryui.com/w/page/12137737/Coding%20standards) coding standard, that is, allowing the user to set the container, and defaulting to the closest `.ui-front` ancestor falling back to the document's `body`.

This would take a fair bit of coding apart from setting the container, for instance, [this.body()](https://github.com/ivaynberg/select2/blob/da7dd51294b481fe201bb89b9bb80d397c4bd627/select2.js#L1163-L1164) would have to be refactored to the correct container, as well as accounting for the container offset instead of [body offset](https://github.com/ivaynberg/select2/blob/da7dd51294b481fe201bb89b9bb80d397c4bd627/select2.js#L1075-L1079).

I'm not sure whether this new `appendTo` feature would be welcome (though I believe this would be rather useful when dealing with other stacking context issues as well) nor whether jQuery UI interoperability is desirable, but in any case I can work on this patch if it is a desirable feature for the core or as an extension.

**Comment by kevin-brown** [comment]
With the upcoming release of 4.0, I've locked this thread. The solution for jQuery UI appears to have been found, and most of the recommendations in here will still work to fix the issue. You just need to change `.select2-drop` to `.select2-dropdown`.

I don't want to patch everyone's copy of jQuery UI from within Select2, as they opens up the door to trouble. Here is a modified copy of the snippet provided by @UltCombo, updated to work for 4.0.

    if ($.ui && $.ui.dialog && $.ui.dialog.prototype._allowInteraction) {
        var ui_dialog_interaction = $.ui.dialog.prototype._allowInteraction;
        $.ui.dialog.prototype._allowInteraction = function(e) {
            if ($(e.target).closest('.select2-dropdown').length) return true;
            return ui_dialog_interaction.apply(this, arguments);
        };
    }
