### ISSUE TITLE
placeholder and (ajax) initSelection

### ISSUE THREAD

**Issue by ouhouhsami** [select2/select2#1249]
Hi, 

I'm not really sure, but if I set a placeHolder and do an ajax initSelection, the callback of my initSelection seems to be triggered before the placeHolder is set, so the Select2 is not set with my initSelection value, but with the placeHolder.

Has anyone experience it ?

Regards

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.

**Comment by gertir** [comment]
Still not fixed in 4.0.3. You can't use placeholder and initSelection together.

I managed to fix this by deleting the placeholder. 
On the select add 2 attributes: data-value with the initial value and data-placeholder.
And edited the initSelection function:

		initSelection: function(element, callback) {
			var id = $(element).data("value");
			if (id !== "") {
				$.ajax("/ajax/GetDescriptionFromcode/?code=" + id, {
					dataType: "json"
				}).done(function(data) {callback(data.items[0]);});
			}
			else{
				callback({text: select2elm.data("placeholder")});
			}
		},
