### ISSUE TITLE
Changing Placeholder Dynamically

### ISSUE THREAD

**Issue by sgsmittal** [select2/select2#1250]
Hi ivyanberg,

I am using Select2.js in some project. and it is great to having this great plugin.

But I am trying to change its placeholder dynamically. But not able to do that. can you please help me out?

**Comment by Stefadesign** [comment]
Do you mind sharing?

**Comment by SgtOddball** [comment]
Highly unlikely since this was 3 years ago and so most likely for v3.5 or earlier.
