### ISSUE TITLE
Can't type in bootbox's modal

### ISSUE THREAD

**Issue by atans** [select2/select2#1278]
Run this demo: http://jsfiddle.net/atans/b5VZk/6/

Step 1: Click the select2 `Chrome: Cant't type now`
Step 2: blur
Step 1: Click the select2 again  `Firefox: Cant't type now`

Firefox 20, Chrome 26

**Comment by imuneer** [comment]
I had the same issue. It worked when `tabindex="-1"` was removed from bootstrap modal.
I found the solution from http://stackoverflow.com/a/18487440/375551

**Comment by Riokai** [comment]
@imuneer  It work for me.Thanks
