### ISSUE TITLE
Need stopPropagation()?

### ISSUE THREAD

**Issue by Daijobou** [select2/select2#1294]
Hi,

I have a popup with select2. If I click outside of my popup, the popup should close.
But now, I click on sugesstion popup of select2 and my popup close too.

$('html').click(function() { $('#my_popup').hide(); });

I would like when select2 have stopPropagation() and not send the click to html too. ;)

**Comment by vedmack** [comment]
How can a user tell select2 to kill the events and don't allow them to leave the container?
