### ISSUE TITLE
Multiple adding of items

### ISSUE THREAD

**Issue by Snogo** [select2/select2#1301]
Is it possible to add a specific item more than once? 

If I do
<code>
$("#special"+ id)
		 .on("change", function(e){
			 if (e.added != undefined) {
				 var i;
				specialarray.push(e.added);
			 }
}
}
</code>

it won't have any effect on the select2-box in which I added an item but only on the others which share the same data array at the moment, do I have to trigger something?

**Comment by kevin-brown** [comment]
This is not possible in 3.5.x because there are checks to make sure things are unique.

In 4.0 this is possible if you create the individual `<option></option>` tags, as Select2 associates the data with the element, not the id, at that point.
