### ISSUE TITLE
IE7 freeze, when opening select2 follow-up

### ISSUE THREAD

**Issue by glachowski** [select2/select2#1304]
Using IE7, when I open one of the select2 widgets in a table, browser freezes and crashes. It is happening with plain select2 initialization. This is a follow-up for issue #1206, after I discovered it is not actually connected with 'width' setting.

Please check out this JS bin http://jsbin.com/ihutet/14/

**Comment by DuncanFairley** [comment]
Hey we had this problem in IE7 (which I know isn't supported) and the above fixed it for us. Any way there could be a 3.4.4 for this so we can continue using bower? @ivaynberg
