### ISSUE TITLE
Cross-browser Keyboard tab support

### ISSUE THREAD

**Issue by hjelmeir** [select2/select2#132]
Keyboard tabbing does not work in Firefox, Safari, and Opera on Mac for the single custom select boxes. I am tabbing thru http://ivaynberg.github.com/select2/. It works in Chrome tho. 

A possible work around would be make the developer put a z-index on the select box trying to duplicate, then copy the z-index? (http://jamielottering.github.com/DropKick/ does has keyboard tabbing working). 

This working in every browser is very important to my client. Keyboard tabbing is very important! (not an enhancement, a requirement, if you are duplicating a select field it should work like a select field imo)

Using FF 12.0, Safari Version 5.1.7 (6534.57.2), Opera v12 on OS X 10.6.8

**Comment by akinhwan** [comment]
@hjelmeir @ivaynberg is keyboard tabbing something I have to enable? I'm not able to tab down the dropdown list

**Comment by hjelmeir** [comment]
@akinhwan This issue was from 7 years ago. I don't even remember making this bug. Please start a new issue.
