### ISSUE TITLE
Set value to empty no clear select2

### ISSUE THREAD

**Issue by vdyn** [select2/select2#1324]
When I do $("#selector").select2("val", "") (set an empty string) on a select2 based on a hidden input loading remote data it does not anything. It shoulds clear the input hidden value and show the placeholder. How I do it? How I clear the select2 componet (when it is based in a hidden input loading remote data) using a function? I saw the clear function inside the component's script, but it is not accesible.

**Comment by GauravKumar110** [comment]
Use this one. This will work perfectly fiine

$('.select2-container').select2('val', '');

**Comment by alexweissman** [comment]
Locking this issue, since it appears to be a support-related question rather than a bug or feature request.  See https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md.
