### ISSUE TITLE
Suggestion: Support provision of text key in options.callback

### ISSUE THREAD

**Issue by omidkrad** [select2/select2#1332]
`options.callback` in `query` and `ajax.results` functions expect as argument an object with `results`:

    options.callback({ results: data });

This is similar to the `data` constructor where it expects `{ results: data, text: key }` except that `options.callback` does not support specifying text key.

So I want to suggest that to be added so that we can specify text key for results passed to the callback, like:

    options.callback({ results: data, text: key });

Thanks

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
