### ISSUE TITLE
AJAX POST instead of GET

### ISSUE THREAD

**Issue by sc0ttkclark** [select2/select2#136]
Willing to help anywhere you need here, I'll try to patch and do a pull request if I'm able to this week.

Would really like to see the ability to set an option of whether to use GET or POST for the AJAX calls.

**Comment by alanleyva** [comment]
This is a very old post, but if someone there has this same issue here is a solution:

```javascript
  $(".select").select2({
      ajax: {
        method: "POST",
        // your other options
    });
```
