### ISSUE TITLE
Ajax data loading improvements

### ISSUE THREAD

**Issue by dwaligora** [select2/select2#1372]
Hi Guys,

All things suggested below refers to the ajax data improvements.

* *select2-post-no-matches* event after **formatNoMatches**:

```javascript

if (data.results.length === 0 && checkFormatter(opts.formatNoMatches, "formatNoMatches")) {
    render("<li class='select2-no-results'>" + opts.formatNoMatches(search.val()) + "</li>");
    var evt = $.Event("select2-post-no-matches", { val: search.val()});
    this.opts.element.trigger(evt);
    return;
}

```

why? Currently we might only change formatNoMatches rendered html but for instance when we would like to make some custom actions after that, like appearing button on which we would like trigger some events (i.e. click for displaying popup) than we have to make some workarounds like onclick (we lost possibility to easily triggering events on the dynamic DOM elements). Example: https://gist.github.com/walmen/82eab68e0aebdc67cb43

* second improvement refers to the search input. If you set **minimumInputLength: 0** than you can easily make ajax request for all available data, which really improve your app usability for end users, because they must not type any data, especially if they don't know any possible data name which could type (I heard from many clients that this is pretty anyoing!). Everything works like a charm now, but there is one problem. If you set this  **minimumInputLength: 0** than **serachInput** never appears (http://cl.ly/image/183R1K2c2e1d). If we add an option *showSearchField* and make some small code modification:

```javascript

//defaults
maximumInputLength: null,
maximumSelectionSize: 0,
showSearchField: false,
id: function (e) { return e.id; },

if (data.results.length === 0 && checkFormatter(opts.formatNoMatches, "formatNoMatches")) {
    render("<li class='select2-no-results'>" + opts.formatNoMatches(search.val()) + "</li>");
    if (opts.showSearchField) this.showSearch(true);
    var evt = $.Event("select2-post-no-matches", { val: search.val()});
    this.opts.element.trigger(evt);
    return;
}

````
than we'll receive more user friendly element http://cl.ly/image/3I35381B0g3h, which allow populating typed data to for example popup (by i.e. using event mentioned above) or adding them on the fly.

What do you think about? Does it make sense or I wanna introduce something which was introduced previously?

**Comment by kevin-brown** [comment]
These issues _should_ be fixed in Select2 4.0.

https://select2.github.io/
