### ISSUE TITLE
Select2 broken width JqueryUI

### ISSUE THREAD

**Issue by michelreyes** [select2/select2#1395]
hello, 
i use select2 (i test all version, since 2.2 until master)
i use jquery 1.9.1 (with and without migrate)
i use jqueryui lastest version

When i put a select2 on a jqueryui dialog and dropdown de select2 to search some option the input for search lose control (focus). I test , and test and retest in diferents new projects but always is the same result.

can you please help me?

sorry my english :{

**Comment by Ankush-Goyal** [comment]
Try editing the jquery.ui.js file. 
Just add $(selector).select2() in the widget function open and inside it just after this._trigger("open").
Its a workaround but should help.
