### ISSUE TITLE
Deep clone causes cloned select2 list to show up in top left corner.

### ISSUE THREAD

**Issue by brohiem** [select2/select2#1400]
The div with the list options is getting set to top & left 0.
![screenshot_6_9_13_12_03_am](https://f.cloud.github.com/assets/999907/628620/be3d8ee8-d0d7-11e2-9a3a-2affde23d803.png)

JS: 
$('.tab-pane.active form').clone(true, true).appendTo($(this));

Environment:
Mac 10.8.4.
Select2 3.4.0
JQuery 1.8.3 & 1.9.0
Chrome Version 28.0.1500.37 (Mac) & FF 22.0 (Mac)

**Comment by jamedranoa** [comment]
```javascript
jQuery.fn.cloneSelect2 =  function (withDataAndEvents,  deepWithDataAndEvents) {
  var $oldSelects2 = this.is('select') ? this : this.find('select');
  $oldSelects2.select2('destroy');
  var $clonedEl = this.clone(withDataAndEvents,  deepWithDataAndEvents);
  $oldSelects2.select2();
  $clonedEl.is('select') ? $clonedEl.select2() : $clonedEl.find('select').select2();
  return $clonedEl;
};
```
