### ISSUE TITLE
Clicked dom element in select2-selecting

### ISSUE THREAD

**Issue by AaronLS** [select2/select2#1403]
Would like to recommend including a reference to the element that received the click event if possible:

http://jsfiddle.net/q4rgE/2/

Use case for this would be something where you have some sort of preview popup for each item, and thus if the href or icon were clicked, you would preventDefault and then trigger some javascript to display that preview(in boostrap modal for example).  Problem is I can't determine what element was clicked and thus can't conditionally do preventDefault.

**Comment by kevin-brown** [comment]
This is possible to do by overriding the `resultsAdapter` with a decorator. Right now we might be passing it in for `select2:selecting` through the `originalEvent` attribute, which is a different way to get the DOM element (but not as consistent).

**Comment by hengsoheak** [comment]
Why I can't do this

  $('.city').select2({
    }).on("click",'select2-drop#btn_add', function(e) {
        console.log(e);
        var test = $(this)
        console.log(test);
    });
    $(".select2-drop").append('<input style="float: right;z-index: 20000;" class="btn btn-info btn-sm" id="btn_add" type="button" value="Add">');
