### ISSUE TITLE
When opening upwards the dropdown is slightly shifted to the left

### ISSUE THREAD

**Issue by nresimic** [select2/select2#1413]
![select2](https://f.cloud.github.com/assets/4548647/648884/99a650ac-d437-11e2-98e6-78635b580c83.png)

I attach image for you to see my problem.
When resize browser (on above expand) my select2 moves few pixels. 
Can you help me to resolve this?

**Comment by smajl** [comment]
@ivaynberg Reproduces here: http://jsfiddle.net/smajl/pvxb5cav/5/. Bug still occurs.

**Comment by demndik** [comment]
A bug exists. The example described @smajl
Please, help me decide: what should I do to make the opening up without a shift?
