### ISSUE TITLE
Tags with space at start

### ISSUE THREAD

**Issue by bogdan-nourescu** [select2/select2#1415]
If a tag starts with " "(space) and you try to remove it, it doesn't get removed.
How to reproduce:
1)http://ivaynberg.github.io/select2/
2) go to Tagging Support
3) insert " test"
4) delete "test"
5) test the value in the input. It still has the value " test" inside it.
![image](https://f.cloud.github.com/assets/4696503/653320/f7ed175e-d4d2-11e2-88b5-bf28006a1b98.png)

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
