### ISSUE TITLE
Open the drop down list permanently.

### ISSUE THREAD

**Issue by jrohit** [select2/select2#1416]
Is there any way to keep displaying the drop down list permanently. Right now when click on the input box then the list is displayed. i'd like to know if there is any way we can show the list permanently there.

**Comment by SherryHuangUS** [comment]
I use `$(elem).on("select2-close", function() {
        $(elem).select2("open");
    })`

**Comment by leoc** [comment]
@SherryHuangUS Have you found a way to keep the select2 open, while being able to focus other form elements on the page?

**Comment by DeathError** [comment]
A typo in the code. no hyphens and colons

> $(elem).on("select2-closing", function(e) {

`$('select').on('select2:select',function (evt) {// Do something});`

**Comment by DeathError** [comment]
` var list = $("#list").select2({
  closeOnSelect: false
 }).on("select2:closing", function(e) {
  e.preventDefault();
 }).on("select2:closed", function(e) {
  list.select2("open");
 });
 list.select2("open");`

**Comment by akhunduqji** [comment]
the reason behind this issue is the 'focus' event. when ever you select an item from list, it triggers the on 'focus' event which opens the list. to get rid of this issue just right the following straight forward code and it will go away!
                               **var $selectList = $('#selectLanguage').select2({
					closeOnSelect: false,
                                        containerCssClass: 'fake-css'
				});
                                $('.fake-css').unbind('focus');
				$selectList.on("select2:select", function (e) {
						$selectList("close");
				});}**
