### ISSUE TITLE
Provide installation instructions

### ISSUE THREAD

**Issue by thurn** [select2/select2#1419]
The Select2 "Download" link gives me a .zip file with a bunch of different files in it. I don't really see any explanation of what's going on here, though. Which files do I need to get the minimum functionality? What is a .js.template file? There are also several images. What file path does the library assume the images will be available at? What if my project is organized so that .js files are served out of a different directory than images? Is there a way to configure that?

Thus, my feature request is that the README provide a brief overview of how to get started using the library.

**Comment by kevin-brown** [comment]
Quick start instructions are now displayed on the main page of the documentation.

https://select2.github.io/
