### ISSUE TITLE
Is it possible to bind an event to 'Close' button (X button) appears when option selected?

### ISSUE THREAD

**Issue by arunkumarg** [select2/select2#1424]
I have implemented a filter using select2.js.  
When the option changes I am highlighting the content.   But when the selected option cleared using 'x' button, I need to reset the content with previous state.  

Can anyone suggest how to add event to 'x' button.

**Comment by 3zzy** [comment]
@ivaynberg I have the same issue (using the old plugin, can't update) and I tried this, but no luck:

```
$(window).load(function() {
    console.log('Window loaded');
    if ($('.select2-container-multi').length) {
        console.log('element exists') // fires
    }
    $('.select2-container-multi').on('click change', '.select2-search-choice-close', function(e) {
        console.log('test'); // doesn't fire
    });
});
```
