### ISSUE TITLE
Less (or other preprocessor) source code for CSS?

### ISSUE THREAD

**Issue by jonathanong** [select2/select2#143]
Do you use less or any preprocessor to format your source code? If not, do you mind if I create a pull request for one? I use Stylus, but since Twitter Bootstrap uses Less, you might want to use less instead. 

Main reason is that the base path for the static assets (gif and png) should be a (external) variable, so I can easily point it to my CDN. Plus, it'll make maintaining the file easier.

Thanks.

**Comment by kevin-brown** [comment]
We're using SASS in Select2 4.0.
