### ISSUE TITLE
Select2 in Tabs of  Bootstap Modal  doing AJAX Call , not working as expected

### ISSUE THREAD

**Issue by venblee** [select2/select2#1436]
I have Select2  inside a Bootstrap Tab , inside a Bootstrap Modal (Popup). Everything Looks and loads fine in the modal , the Select2  only accept one character and will display list that has the one character in them as expected , But when I click on it , to enter more characters it does not type new characters in textbox bellow  the select2 box or accept  anything in textbox at all.

![example2](https://f.cloud.github.com/assets/4137329/673193/ca50d564-d8ac-11e2-9ba0-59e983ef6e91.png)

It look like it lost focus or it class. I have ran this in VS 2012 with IE and Chrome with Dev Tools , not errors or warnings  

I am using the latest version of bootstrap and Select2. 

I have work from the following Examples , if you want to replicate 
http://techtoffee.blogspot.com/2013/03/select2-with-aspnet-mvc.html
http://twitter.github.io/bootstrap/javascript.html#modals
http://twitter.github.io/bootstrap/javascript.html#tabs

**Comment by bafi** [comment]
good job (Y)

**Comment by luochongfei** [comment]
这个问题困扰了我大半天，真心感谢ascyltos

**Comment by ggwebdev** [comment]
Thanks! save me too!!!

**Comment by easonCn** [comment]
Thanks!save me too!!!

**Comment by juanruben** [comment]
Thanks..

**Comment by kabeza** [comment]
I'm loading modal's content with ajax, and the content has a select2 field
When content loaded, I fire $("#sel_comercio").select2({ ... })
No luck yet, select2 field is frozen, disabled, not working

**Comment by nickylau82** [comment]
thanks!!!!! save me too!!!!

**Comment by IvoPereira** [comment]
I am having same issue as @kabeza. Have you ever found a solution for it?

**Comment by ggwebdev** [comment]
Not yet...

Att,

*Gabriel Glauber Neves*
Web Developer
61 8352-2212 - 9228-3090
Perfil no Linkedin <http://br.linkedin.com/pub/gabriel-glauber/6b/973/730>
Antes de imprimir pense no meio ambiente!


2015-12-29 13:19 GMT-02:00 Ivo Pereira <notifications@github.com>:

**Comment by kabeza** [comment]
@IvoPereira no, I had to replace select2 by common select field

**Comment by kevin-brown** [comment]
This ticket is a duplicate of https://github.com/select2/select2/issues/600#issuecomment-102857595, which has a working fix (also mentioned earlier).
