### ISSUE TITLE
Feature Request: Option to set height

### ISSUE THREAD

**Issue by jonathanong** [select2/select2#144]
For example, the "Loading Remote Data" examples only shows 2 results per page, which isn't very usable. Ideally, I want to be able to set a height and a max-height (ie half of the height of the browser).

Thanks!!

**Comment by rwitchell** [comment]
@ivaynberg : can you consider making this an option in the instantiation of the object? result-height: (string) which can be em or px .

**Comment by JacobEvelyn** [comment]
I just wrote a plugin to expand the dropdown to take up all available vertical space: https://github.com/panorama-ed/maximize-select2-height

@jonathanong using the `cushion` option with that plugin may be another way to get you what you want.

**Comment by rwitchell** [comment]
Thanks @JacobEvelyn - i've added your package to our app, and updated all of our select2 calls to then call your function. works well :). This should be standard within select2...

**Comment by JacobEvelyn** [comment]
Glad to hear it, @rwitchell!

**Comment by dperel** [comment]
@JacobEvelyn Is there any documentation on how to use this feature? When I call `$("#my-dropdown").select2().maximizeSelect2Height();` in my code, as per the original plugin's docs, I get an error saying that this is not a function.

**Comment by JacobEvelyn** [comment]
@dperel are you including the source code to the plugin (https://github.com/panorama-ed/maximize-select2-height) in your code? This isn't part of the select2 source, so it's not built-in by default.

**Comment by dlewand691** [comment]
This also worked for me:
```
$('#selectField').on('select2:open', function (e) {
  var container = $(this).select('select2-container');
  var position = container.offset().top;
  var availableHeight = $(window).height() - position - container.outerHeight();
  var bottomPadding = 50; // Set as needed
  $('ul.select2-results__options').css('max-height', (availableHeight - bottomPadding) + 'px');
});
```

**Comment by arsusbravo** [comment]
Is there any solution for this?
I manage to make the fixed position with this css
`.select2-container.select2-container--bootstrap4.select2-container--open { position: fixed !important; top: 100px !important; left: 0 !important; z-index:9 }
.select2-container--open .select2-dropdown--below { border-bottom: solid 1px #80bdff; border-bottom-left-radius: 0; border-bottom-right-radius: 0 }`

However, the height doesn't work. If I insert, for example, this
`.select2-results__options { max-height: 500px !important }`
Select2 doesn't work.. no options.. no error...
