### ISSUE TITLE
Select2 v3.4 width calculation changed

### ISSUE THREAD

**Issue by fayilt** [select2/select2#1471]
It seems that the way width of a select2 calculated has changed since version 3.2

I use a class on my inputs (x-large) that sets width to 210px. It worked well with Select2 3.2 and width of the div container (select2-container) wasn't overwritten and the class was copied to the div by select2.js.

The new version seems to copy the class, but it also sets inline width (149px in my case) which overrides the css width.

I quickly debugged it and it seems that it's because of this difference in initContainerWidth:

v3.2

<pre>
<code lang="javascript">
 if (this.opts.width === "resolve") {
// next check if css('width') can resolve a width that is percent based, this is sometimes possible
// when attached to input type=hidden or elements hidden via css
style = this.opts.element.css('width');
if (style.indexOf("%") > 0) return style;
// finally, fallback on the calculated width of the element
return (this.opts.element.outerWidth() === 0 ? 'auto' : this.opts.element.outerWidth() + 'px');
} 
return null;
</code>
</pre>

v3.4

<pre>
<code lang="javascript">
// next check if css('width') can resolve a width that is percent based, this is sometimes possible
 // when attached to input type=hidden or elements hidden via css
style = this.opts.element.css('width');
if (style && style.length > 0) return style;
if (this.opts.width === "resolve") {
    // finally, fallback on the calculated width of the element
    return (this.opts.element.outerWidth(false) === 0 ? 'auto' : this.opts.element.outerWidth(false) + 'px');
}

return null;
</code>
</pre>

The old version was getting element's width only if this.opts.width === "resolve". The new code does it outside of the if block. The value for my input is "copy". Any reason this logic was changed?

**Comment by kvikram1988** [comment]
Awesome. Thanks!!!
