### ISSUE TITLE
IE8: Right click-> Paste Doesn't trigger the select2 Open correctly

### ISSUE THREAD

**Issue by nmonje** [select2/select2#1473]
Steps to reproduce:

Open http://ivaynberg.github.io/select2/ in IE8
Navigate to "tagging support" example.
Right click the field and paste "asdf".
Observe that the select2 autocomplete doesn't have the option "asdf".
Without clearing it out, right click -> paste again.
The dropdown will now have the option "asdf." (should have "asdfasdf", which appears in the input.)

![Screen Shot](https://f.cloud.github.com/assets/141314/718615/91513844-df69-11e2-9805-4015652f18fb.png)

The same process works correctly in chrome.

Looks like IE8 triggers the "paste" event before actually updating the value.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
