### ISSUE TITLE
Tag can be selected multiple times if it contains comma

### ISSUE THREAD

**Issue by aL3xa** [select2/select2#1480]
The title is pretty self-explanatory. While the bug is pretty similar to #1064 and #1279, I think that it still ain't solved, so if you have a simple text field and try to add tag that contain commas, you can spend all night doing that...

``` javascript
$('#my_input').select2({
    tags: ['foo,bar', 'blah', 'buzz'],
    tokenSeparators: [',']
});
```

**Comment by faisalferoz** [comment]
@vrutberg +1
