### ISSUE TITLE
Options list detaches from input when page scrolled

### ISSUE THREAD

**Issue by Lightw3ight** [select2/select2#149]
I have a Select2 multi select box within a scrollable div (display:auto)

when i click on my Select2 multi select box, the options list comes up as expected, listing all available options
now if i use my mouse scroll wheel while my mouse is positioned away from the options list, my underlying content scrolls but my options list stays in place, becoming detached from the multi select list.

a possible fix could be to create an invisible div that takes up the whole page, positioned directly under the options list that could swallow the mouse wheel events?

I tried this by adding a line into the open function of Select2.js
$("<div/>").addClass("shield").appendTo(document.body);

and adding the following css class

.shield
{
    position:absolute;
    top:0px;
    right:0px;
    bottom:0px;
    left:0px;
    opacity:0;
    filter: alpha(opacity=0);
    background-color:White;
    z-index:998;
} 

obviously the div needs to be removed again but the concept worked (tested in chrome and ie)

**Comment by sambaheerathan** [comment]
If there is no requirement to view options while scrolling. we can disable the scroll when we are listing options

**Comment by fredericJos** [comment]
```
$select2.each(function initSelect2() {
        const $select = $(this);
        const $dropdownParent = $select.parents('.js-select-container');
        const dropdownParent = $dropdownParent.length ? $dropdownParent : $('body');

        $select.select2({
          minimumResultsForSearch: Infinity, // hide the search box
          templateResult: (data, container) => { // persist classes on option tags
            if (data.element) {
              $(container).addClass($(data.element).attr('class'));
            }
            return data.text;
          },
          dropdownParent,
        });
      });
```

**Comment by Jizziboy** [comment]
I am using Select2 4.0, 
My problem was that, when I was scrolling the page theSelect2 Options changes its positions too. 

I believe I found the problem changing this, on the original script from select2: 

$dropdown.css({
                    // position: 'fixed',
                    top: -999999,
                    "z-index": 1300
                });
Good Luck Guys!

**Comment by nickidotdk** [comment]
> I am using Select2 4.0.5
> My problem was that, when I was scrolling the page theSelect2 Options changes its positions too.
> 
> I believe I found the problem changing this, on the original script from select2:
> 
> $dropdown.css({
> // position: 'fixed',
> top: -999999,
> "z-index": 1300
> });
> Good Luck Guys!

Jizziboy - that fix is spot on!!! Thank you so much :)

**Comment by dylan-cork90** [comment]
> I've given up trying to get a one-fits-all solution for this. I've modified my general page script so that it hooks into the scroll() event and calls .select("close") on every item in there. It's kinda dirty, but it works.
> 
> I still think it's worth looking at whether the parent for the drop-down div could be optionally added to something other than the body. In ProLoser's case, it could be added to the foot of the position:fixed div, and would therefore not scroll with the rest of the content. In my case, it could be added to the end of the div that forms the tab panel body, and would therefore scroll when the document doesn't. It may not be perfect, and most people will never use it, but it might help to work around the occasional problem.





https://stylesheets.space/questions/navigate-down-the-page-until-you-reach-the-section-that-is-set-to-display-as-a-block
