### ISSUE TITLE
Select2 using multiple and minimumInputLength properties object has no method showSearch error occured

### ISSUE THREAD

**Issue by seyfside** [select2/select2#1510]
When I remove minimumInputLength everything is ok. But it is necessary working with remote data.

Uncaught TypeError: Object [object Object] has no method 'showSearch' select2.js:1516
clazz.updateResults select2.js:1516
clazz.opening select2.js:2521
clazz.open select2.js:1191
(anonymous function) select2.js:2439
(anonymous function) select2.js:623
jQuery.event.dispatch jquery-1.10.1.js:5116
elemData.handle jquery-1.10.1.js:4787

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.
