### ISSUE TITLE
Ability to hide "inputTooShort" message

### ISSUE THREAD

**Issue by Danita** [select2/select2#1511]
Hi! Great project, I'm loving it :smile_cat:

I need my input to show the autocomplete when at least 1 character has been entered (not on focus) and so I'm setting `minimumInputLength : 1`, but select2 shows a message that I "Please enter 1 more character".

I would love that message not to appear. I've tried:
- Setting `formatInputTooShort : function() {},`
- Setting `formatInputTooShort : function() {return false;},`
- Setting `formatInputTooShort : false,`
- Setting `formatInputTooShort : null,`

But all that I get is an empty message that still takes some space. Any ideas?

**Comment by davidrenne** [comment]
+1... come on!! please!

**Comment by remmel** [comment]
+1 maybe in the 4.0.1 ?

**Comment by redcloak** [comment]
+1

**Comment by kevin-brown** [comment]
Does returning a blank string for the message not work?

```js
language: {
  inputTooShort: function () { return ''; }
}
```

In 3.x that would be

```js
formatInputTooShort: function () { return ''; }
```

**Comment by redcloak** [comment]
>Does returning a blank string for the message not work?

Yes it will. But if we want to specify language other than english, we will need to edit localisation source file.

**Comment by pavellishin** [comment]
I believe this should be re-opened; setting the inputTooShort function to return a blank string still shows the dropdown - I would like for it to be gone altogether.

**Comment by voidale** [comment]
@pavellishin +1

**Comment by naimkhalifa** [comment]
+1

**Comment by fi5u** [comment]
+1

**Comment by althaus** [comment]
+1

**Comment by AlexeyKosov** [comment]
Why isn't it already implemented?

**Comment by jgerigmeyer** [comment]
This would still be a helpful feature (or at least adding more specific classes, as @althaus suggested). Any update on the possibility of adding this?

**Comment by cytsunny** [comment]
```
//v4 or later
language: {
  inputTooShort: function () { return ''; }
}

//before v4
formatInputTooShort: function () { return ''; }
```

The issue was closed with these command. While it do remove the warning text, this leaves an empty box there. I wonder if this should be marked as close with no ways to hide the box as well......

**Comment by LuisEsteban-Wasi** [comment]
//v4 or later
    language: {
      inputTooShort: function () { return ''; }
    }

    //before v4
    formatInputTooShort: function () { return ''; }

these commands only remove the text, the label still appears but now with without text. I think this issue should be reopened. I need remove this label.

**Comment by billynoah** [comment]
Workaround:

1) Set language to empty string as outlined by LuisEsteban-Wasi above.
2) Add the following CSS to target the empty `<li>` element (this works in v4, not sure what the selector would be for earlier versions)

```
.select2-results__option.select2-results__message:empty {
    display: none;
}
```

**Comment by cytsunny** [comment]
@billynoah 

This workaround only works if you want to hide all message box on all the select2 boxes in the page. (or maybe in the site if you are using one page app) We have to have a way to add class to that message box to really solves the problem using CSS.

Just to make sure this does not get marked as closed again due to this workaround.

**Comment by billynoah** [comment]
@cytsunny - no that's not true.  the selector only targets the message element *when it is empty* by using the `:empty` pseudo selector.  Anytime the element contains text content it will be displayed.  Try it.

**Comment by billynoah** [comment]
@cytsunny - no that's not true.  the selector only targets the message element *when it is empty* by using the `:empty` pseudo selector.  Anytime the element contains text content it will be displayed.  Try it.

**Comment by aavetis** [comment]
@billynoah if it fits.. i sits.

good for now, thanks!

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
