### ISSUE TITLE
Enter + Tab behaviour changes from jQuery 1.7.2 forward

### ISSUE THREAD

**Issue by leods92** [select2/select2#1523]
**Expected (works if jQuery 1.7.1 or older is used):**
You tab into a select2 select, select an item by using `enter`, press `tab` and then the next element is focused.

**What happens (if jQuery 1.7.2 or newer is used):**
You tab into a select2 select, select an item by pressing `enter`, press `tab` and an apparently invisible element is focused, then you press `tab` again and then you finally get into the next element.

Has anybody else noticed this buggy behaviour?
What could have possibly changed in jQuery?

**Comment by kevin-brown** [comment]
Given that the minimum jQuery is around 1.7.2 now, I don't think this is as much of an issue.
