### ISSUE TITLE
Ability to hide currently selected value in dropdown

### ISSUE THREAD

**Issue by srigi** [select2/select2#1538]
When dropdown is opened, items are rendered inside of `ul.select2-results`. Every single item is wrapped in `li.select2-result`, the one item that is hovered by mouse is `li.select2-result.select2-highlighted`.

I would really appreciate if there is also some other class added to currently selected item in this `ul.select2-results`. That way I can target it by CSS and hide that item.

**Comment by rahmathm1** [comment]
@kevin-brown  Is this working with list being fetched as ajax? thanks!

**Comment by kikonen** [comment]
It looks like just hiding elements using "display: none" doesn't remove  them from keyboard iteration; so arrow  up/down hits hidden elements, which are invisible.

**Comment by blazkovicz** [comment]
This issue was closed because of work in #2053 but that pull request was reverted, so the problem remains. Do authors of select2 4.0 intend to solve this isuue any time soon? I just updated select2 from 3.5 and discovered this annoing behaviour.

**Comment by djtarazona** [comment]
+1

Hiding with CSS isn't a good solution as the options are still in the keyboard iteration and someones the drop down appears empty with no explanation / message to the user.

**Comment by nhieu92** [comment]
Hi. I want to hide selected option. How to do that?

**Comment by belov91** [comment]
@nhieu92  +1

**Comment by guill3m** [comment]
> Select2 4.0 consistently marks selected objects, so you can now hide them through CSS

**Hiding options with CSS is not a good solution:** in fact, it is not a solution at all. As it has already been said if you try to navigate the options with the keyboard keys it will still cycle through the hidden options, which makes hiding the selected options with CSS an even a worse solution than leaving them there. So I would say this issue is not actually about _hiding_ but _removing_ the selected values from the dropdown.

> It's a new feature in 4.0.0 that was introduced largely for accessibility reasons.

@kevin-brown you mentioned that in #3850. Could you extend on those accessibility reasons please? I would like to understand your argument against this feature request but can't find anything that helps me understand it in the docs.

A couple of reasons to remove the already selected options from the dropdown:
-  In `select[multiple]` elements if there is several (maybe 10+) options and you have most of them selected, showing only the not selected ones helps the user to know what is not selected (the selected ones are already being shown anyway).  
- In `select[multiple]` elements to be able to quickly select several options (maybe even all of them) with the keyboard: space + enter + space + enter + ...

Being able to not show/disable the already selected options could make for a good UX improvement. What are the accessibility issues found with this behaviour? and, do they overweight that much the UX ones to not even wanting to add it as an option (disabled by default)?

**Comment by kevin-brown** [comment]
I'm aware that hiding the results through CSS isn't an ideal option, but there also isn't an option out there that solves all of the problems. That's why there isn't an option available in Select2 for hiding the results, and why I haven't locked this discussion with a recommended workaround. There isn't an optimal workaround.

> Could you extend on those accessibility reasons please?

Right now the only way to unselect arbitrary (other than the last) options using the keyboard is to type CTRL + SPACE when the result is highlighted. This is to command for toggling a result, so it will select or unselect the highlighted result depending on what state it was previously in. Screen readers should read out the state of the option (whether it is selected or not) as they move through the results list, which is usually important.

Without an alternate way to unselect arbitrary options using the keyboard, the UX problems caused by that far outweigh the UX annoyances that you currently have by showing the selected results.

**Comment by guill3m** [comment]
OK, I see your point, thanks for the reply. :)

**Comment by antitoxic** [comment]
@kevin-brown I understand your point of choosing the lesser evil. I don't think though that a popular plugin like select2 should include any of these problems. I understand how select2 is trying to keep functionality to minimum and let plugins do the rest but keyboard navigation is vital. That's not something for a plugin.

`3.5` had the feature to select items with the arrows. What decision led to removing this feature?

**Comment by pobing** [comment]
I use below css rule hide selected elements
```
.select2-results__option[aria-selected=true] {
	display: none;
}
```

**Comment by mahesh-ziffi** [comment]
Nice :+1:  Worked for me. Thanks a lot.

**Comment by devbhuwan** [comment]
I use below css rule inside head tag to hide selected elements.

```
<style>
 li[aria-selected=true] {
   display: none !important;
 }
</style>
```

**Comment by TwentyOneSolutions** [comment]
@devbhuwan that works for me, thanks!

**Comment by mobilutz** [comment]
I found a solution for my project. I use a plugin and decorate the `ResultList` with this (excerpt):
```coffee
  HideSelected::append = (decorated, data) ->
    data.results = _.reject(data.results, (element) ->
      element.selected
    )

    decorated.call(@, data)
```
This hides the selected elements completely from the dropdown and when all options are selected it shows `No results found` message.

**Comment by ayselafsar** [comment]
Hi @mobilutz Did you add it in processResults block? Could you give more information? 
Thanks

**Comment by mobilutz** [comment]
This is my setup.

Select 2 Plugin like this:
```javascript
$.fn.select2.amd.define("select2/hide_selected", [], function() {
  var HideSelected;
  HideSelected = function(decorated, $element, options, dataAdapter) {
    return decorated.call(this, $element, options, dataAdapter);
  };
  HideSelected.prototype.append = function(decorated, data) {
    data.results = _.reject(data.results, function(element) {
      return element.selected;
    });
    return decorated.call(this, data);
  };
  return HideSelected;
});
```

And then I have my own jQuery select2 function which just sets the resultsAdapter in the select2 options:

```javascript
(function($) {
  return $.fn.hiddenSelect2 = function(options) {
    var $elements;
    $elements = this;
    $.fn.select2.amd.require(['select2/utils', 'select2/results', 'select2/hide_selected'], function(Utils, ResultsList, HideSelected) {
      var ResultsAdapter, select2Options;
      ResultsAdapter = Utils.Decorate(ResultsList, HideSelected);
      select2Options = $.extend(true, options, {
        resultsAdapter: ResultsAdapter
      });
      return $elements.hiddenSelect2(select2Options);
    });
    return this;
  };
})(jQuery);
```

In my project the jQuery `hiddenSelect2` is a bit different and I did not check if this code really works. But you get the idea how I set it up.

**Comment by jophj** [comment]
That's my solution. It's not elegant as it should be but works. The selected elements are immediately hidden upon selection and are added to the dropdown when deselected.

```Javascript
$.fn.select2.amd.define("select2/customResultAdapter", ['select2/utils', 'select2/results'],
    function(Utils, ResultsList) {

      function getNotSelectedResults(self, data){
        var results = _.reject(data.results, function (element) {
          var selectedOptions = self.$element.select2('data');
          var selectedElement = _.find(selectedOptions, function(o){return o.id === element.id});
          return element.selected || selectedElement;
        });

        return {
          results: results
        };
      }

      var ResultAdapter = function(decorated, $element, options, dataAdapter) {
        return decorated.call(this, $element, options, dataAdapter);
      };

      ResultAdapter.prototype.append = function(decorated, data) {
        var self = this;

        if (!this.allData){
          this.allData = data;
        }

        var notSelected = getNotSelectedResults(self, this.allData);
        return decorated.call(this, notSelected);
      };

      ResultAdapter.prototype.bind = function(decorated, container, $container) {
        var self = this;

        container.on('select', function (data) {
          var notSelected = getNotSelectedResults(self, self.allData);
          self.clear();
          self.append(notSelected);
        });
        return decorated.call(this, container, $container);
      };

      return Utils.Decorate(ResultsList, ResultAdapter);
    }
  );
```
You can use it like this
```Javascript
var customAdapter = $.fn.select2.amd.require('select2/customResultAdapter');

  $element.select2({
    closeOnSelect: false,
    resultsAdapter: customAdapter
  })
```

**Comment by Wirone** [comment]
For those who don't use Underscore.js and want to use @jophj's solution, here's pure jQuery implementation of `getNotSelectedResults` function:

```
function getNotSelectedResults(self, data) {
    // Extract list of selected IDs for further usage
    var selectedIds = $.map(
        self.$element.select2('data'),
        function (element) {
            return element.id;
        }
    );

    return {
        results: $.grep(data.results, function (element) {
            return element.selected || (-1 !== $.inArray(element.id, selectedIds));
        }, true)
    };
}
```

I wonder why this is not part of Select2 core... :disappointed:

**Comment by Wirone** [comment]
Also, use `Utils.Extend()` instead of `Utils.Decorate()` because the latter unbinds `query` event so autocomplete does not work.

**Comment by legshooter** [comment]
Casting my +1 for this to be incorporated...

**Comment by joanebrown** [comment]
@Wirone I can't get it work. Y get the next error:

    Uncaught TypeError: Cannot read property 'select2' of undefined

in this line:

    var selectedIds = $.map( 
        self.$element.select2('data'),
        function (element) {
            return element.id;
        }    
    );

I use this code inside the configuration of my select2:

    resultsAdapter: getNotSelectedResults

Could you, please, give me some advice to get it work?

**Comment by joanebrown** [comment]
@legshooter Please, could you tell me how to implement this? I cant get it work...

**Comment by Wirone** [comment]
@joanebrown I ended up with:

```javascript
$.fn.select2.amd.define('select2/HideSelectedResultsAdapter', ['select2/utils', 'select2/results'],
    function (Utils, ResultsList) {
        var HideSelectedResultsAdapter = function(decorated, $element, options, dataAdapter) {
            return decorated.call(this, $element, options, dataAdapter);
        };

        HideSelectedResultsAdapter.prototype.append = function(decorated, data) {
            data.results = $.grep(data.results, function(element) {
                return element.selected;
            }, true);

            return decorated.call(this, data);
        };

        return Utils.Decorate(ResultsList, HideSelectedResultsAdapter);
    }
);

// USAGE
$('#elem').select2({
    resultsAdapter: $.fn.select2.amd.require('select2/HideSelectedResultsAdapter')
});
```

I took this from repo history, we dropped select2 there so I can't check it now. But it was working.

**Comment by joanebrown** [comment]
@Wirone Thanks for your reply, I tried your solution, but doesn't work for me (doesn't show any error, but still appear the selected results). What is your select2 version?

**Comment by Wirone** [comment]
@joanebrown we were using 4.0.3 back then.

**Comment by joanebrown** [comment]
@Wirone Strange... And a select2 with AJAX? I tried only with it and I can't get it work

**Comment by ayselafsar** [comment]
@joanebrown This is my approach, it only restricts ui in templateResult method. It works for me.
`const select2Options = {
        placeholder: 'Search Entry',
        allowClear: true,
        ajax: {
            transport(params, success, failure) {
                if (!params.data ||
                    !params.data.q) {
                    return;
                }

                // Retrieve search results from database and pass them to success callback
                const results = getResults();
                success(results);
            },
            processResults(searchResults) {
            	return {
                    results: searchResults,
                };
            },
            cache: true,
        },
        templateResult: function (entry) {
        	if (!entry) {
        		return;
        	}

    		// Do not diplay the entry if it is already present in selected entries
        	if (selectedEntries.indexOf(entry.id) > -1) {
        		return;
        	}

        	return $('<span>' + entry.text + '</span>');
        }
    };

// Get select2 element
const select2Element = $('#select2Entries');

// Initialize select2
select2Element.select2(select2Options);`

**Comment by ayselafsar** [comment]
@joanebrown You can eliminate selected entries in templateResult method of select2.

**Comment by Wirone** [comment]
@joanebrown I don't know if it works with Ajax, but here's the fiddle with working* adapter:

https://jsfiddle.net/Wirone/z94u71pg/

* _almost_, because probably there's a bug in Select2 which keeps `selected: true` property for all previously selected values. Since we used it with tokenizer it wasn't an issue, but in single select it causes all options to disappear one by one, when selecting them.

@kevin-brown ?

**Comment by Wirone** [comment]
@ivaynberg & @kevin-brown could you take a look at fiddle above and explain why Select2 keeps `selected: true` and how to fix this in order to get my adapter working?

**Comment by alexweissman** [comment]
With AJAX, it seems like you could use `templateResult` to return null for items that have already been selected.  See https://select2.org/dropdown.

**Comment by legshooter** [comment]
I eventually opted for:
```js
templateResult: function (state) {
    return state.selected ? null : state.text;
}
```
which seems to work great on `v4.0.5`.

**Comment by rehmat11872** [comment]
<select id="mapp_student" class="form-control" name="{{ class_stu.id }}" test="{{ students.id }}">

                                                     {% if mapping %}

                                                    {% for map in mapping  %}
                                                                                    {% if students.student.email == map.to_mapp.student.email  %}
                                                                                        <option value="{{ map.student_mapping.student.email }}" selected>{{ map.student_mapping.student.email }}</option>
                                                                                    {% else %}
                                                                                        <option value="">---------------</option>
                                                                                    {% endif %}
                            
                            
                            
                                                                                {% endfor %}
                                                                            {% else %}
                                                                                <option value="">---------------</option>
                                                                            {% endif %}
                            
                            
                            
                                                                            {% for student in class_stu.students.all %}
                            
                                                                                <option {% for mapp in mapping %} {% if map == students.student.email %} selected {% endif %}{% endfor %} value="{{student.student.email}}" id="stu_opt">{{student.student.email}}</option>
                                                                            {% endfor %}
                                                                        </select>

**Comment by rehmat11872** [comment]
$scope.changeFunction = function(status){
    if(status == "Cancelled"){
        /* code for hide or remove "Confirm" option */
    } else if(status == "Confirm"){
        /* code for hide or remove "Cancelled" option */
    }
}

**Comment by Kisioj** [comment]
I tried using `state.selected` but it's bugged and stays `true` on previously selected elements. I managed to make it to work like that:
```js
$(element).select2({
    templateResult: function (state) {
        if (state.element?.selected) {
            return;
        }
        return state.text;
    }
});
```
