### ISSUE TITLE
Blur event fires at the wrong time with newer versions of jQuery

### ISSUE THREAD

**Issue by KarlBishop** [select2/select2#1545]
The [select2 Events example](http://ivaynberg.github.io/select2/#events) shows that, after an option is selected, the select box will keep focus.

This works correctly [using jQuery 1.7.1](http://jsfiddle.net/KarlosSultana/KxL94/) (as in the select2 example)

But when [using jQuery 1.9.1](http://jsfiddle.net/KarlosSultana/s93vL/), for example, the blur event fires immediately after an option is selected, and so the select box loses focus at the wrong time

**Comment by elodie-adactive** [comment]
Did you fixed this ?
I also have this problem on touch screens. Basically, the blur event is received after touch and focus events on inputs. So the keyboard is closed immediatly. I'm on jQuery 2.1.4

**Comment by pedrofurtado** [comment]
Sorry, the `3.x` version is not maintained anymore. But feel free to fork the repo and fixes what you need.
