### ISSUE TITLE
focus() call on DOM element breaks drag-and-drop support on IE8

### ISSUE THREAD

**Issue by shepmaster** [select2/select2#1560]
If you enable jQueryUI sortable support as shown in the README, then perform a failed drag in IE8, you will no longer be able to sort the items. For a "failed drag", you can just move the item to where it is, or I like to drag out of the containing box. 

The failure is coming from the `focus` call at https://github.com/ivaynberg/select2/blob/master/select2.js#L2416

The specific message is

```
Can't move focus to the control because it is invisible,
not enabled, or of a type that does not accept the focus.
```

The following modified line seems to fix / work around the issue.

```javascript
$(_this.search[0]).focus();
```

I think that the jQuery implementation of `focus` ignores IE8's bogus exception.

I'd be more than happy to submit a pull request, but there are bunches of `focus` calls, so I'm not sure what all could be fixed. There's even another implementation of `focus` at https://github.com/ivaynberg/select2/blob/master/select2.js#L254.

Let me know how you'd like me to proceed.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
