### ISSUE TITLE
Select2 and select "display: none"

### ISSUE THREAD

**Issue by AlixBa** [select2/select2#1564]
Hi, 

I'm doing a website with some webpages rendered `<table>`. I use `<select>` as filters and these `<select>` can be displayed or not, depending on what condition the user choose to filter (field `like blabla`, field `between a` `and b`, etc.). 

With Select2 3.3.2 all the `<select>` are displayed by default. There is no impact of the CSS rule `display: none`.

Am I missing something ? Is there the possibility for Select2 to "follow" the display rule of the original `<select>` ?

http://jsfiddle.net/PFfU5/

Thanks,
Litz.

**Comment by mmp1368** [comment]
@AlixBa  you may forgot to link css document <code>select2.min.css</code> to top of your page.

**Comment by gate5th** [comment]
If anyone else is running into this problem, if you wrap the select element in it's own div you can apply the CSS rule display: none to the div and it works.
