### ISSUE TITLE
select2-drop-above: dropLeft is missing some px

### ISSUE THREAD

**Issue by DerDu** [select2/select2#1574]
In some situations `dropLeft` is not calculated correct. 

It somehow depends on viewport, padding and margin but yet i couldn't find out where it's broken.

_But a hint: If the dislocation occurs and i do a window resize, its gone._

Edit:
Please refer to comments

**Comment by jcaspian** [comment]
I'm sorry but I just had this exact issue for drop above. The situation is similar to DerDu's case. What I did to fix is adding a custom css .select2-drop { position:fixed }

I don't know if this is a real fix but just want to let you guys know.
