### ISSUE TITLE
size of options to display

### ISSUE THREAD

**Issue by fcops** [select2/select2#1575]
select2 doesn't use the size= in the select. How can I show more choices? By default it shows about 7.

**Comment by JacobEvelyn** [comment]
Late response, but if someone stumbles upon this thread with the same issue, I just wrote a plugin to expand Select2 dropdowns vertically where possible: https://github.com/panorama-ed/maximize-select2-height

**Comment by dlewand691** [comment]
This also worked for me:
```
$('#selectField').on('select2:open', function (e) {
  var container = $(this).select('select2-container');
  var position = container.offset().top;
  var availableHeight = $(window).height() - position - container.outerHeight();
  var bottomPadding = 50; // Set as needed
  $('ul.select2-results__options').css('max-height', (availableHeight - bottomPadding) + 'px');
});
```
