### ISSUE TITLE
Turbolinks: Object has no method 'select2' 

### ISSUE THREAD

**Issue by rylwin** [select2/select2#1582]
When using select2-rails with turbolinks, I see an error trying to use `.select2()` after a page is loaded with turbolinks (i.e., the first page load works fine, but the error always happens after clicking a link that causes the page to be loaded via turbolinks). The error is: 

``` js
Object [object Object] has no method 'select2' 
```

I've found that the following piece of code being executed on `page:load` prevents this error:

``` js
window.Select2 = undefined;
```

By unsetting the Select2 global, the select2 js constructs the `select2()` function again, preventing the error.

**Comment by bl4ckdu5t** [comment]
I moved my ```<script>``` to the ```<head>``` and that prevented the error but select2 still only displays when the page is visited from the address bar. It fails when addressed from a link till the page is refreshed or till I manually add in $('select').select2(); in the console

**Comment by sanjusoftware** [comment]
woo!! @rylwin this worked for me too!! thanks a lot

but what about all the benefits we were suppose to get by having the javascript actually being included at the end, faster pageload. I am loosing on them certainly. Is this a safe bet then?

**Comment by bl4ckdu5t** [comment]
@sanjusoftware It's a matter of rendering time. With JS in the head it delays the page rendering till all the scripts are loaded. Having the scripts at the head doesn't break your code, it just reduces your performance. A common and good example to explain this is a simple
```<script>alert("hello");</script>```
in a page with contents. Try loading in `<head>` and then try right before `</body>`
In my opinion, it is left on what you're willing to sacrifice. First load time speed over rest of web app survey (without turbolinks and script in head), or a slightly site-wide performance by not using turbolinks at all or moving to Express/Node for complete SPA feel.
