### ISSUE TITLE
Bootstrap 3 breaks layout

### ISSUE THREAD

**Issue by JonoB** [select2/select2#1588]
You get a box within a box

JSFiddle: http://jsfiddle.net/zXsSm/2/

**Comment by gandarez** [comment]
+1

**Comment by rwil02** [comment]
This worked for me:


.select2-container.form-control {
    height: auto !important;
    padding: 1px;
}

.form-control ul.select2-choices {
    border: 0;
    background-image: none;
    margin: 1px;
    padding: 1px;
}
.form-control.select2-container .select2-choice {
  height: 38px;
  line-height: 38px;
}
