### ISSUE TITLE
Release on NPM

### ISSUE THREAD

**Issue by andreypopp** [select2/select2#1592]
It would be nice to have select2 on npm to use with CommonJS browser bundlers such as browserify which is pretty popular today.

**Comment by feross** [comment]
The current owner of `select2` on npm is @chrisjbaik. Would you care to `npm owner add` Kevin so he can start publishing official versions to npm?

@kevin-brown what's your npm username?

**Comment by kevin-brown** [comment]
Until we get the wrappers working, I'm going to push off taking ownership (or doing something else, who knows) until I have spare time and have looked into how NPM works.

Until then, the unofficial releases work well, but they are still unofficial.
