### ISSUE TITLE
Duplicate call for the same page

### ISSUE THREAD

**Issue by korene77** [select2/select2#1610]
Hi,

I've encountered an issue which is not consistently happenning.
In some cases when using a query function with paging, select2 requests for the same page twice.
I was able to pin point the issue to the fact that "loadMoreIfNeeded" is called twice. Once from within the callback of the query function:
<code>
if (data.more === true && checkFormatter(opts.formatLoadMore, "formatLoadMore")) {
                    results.append("<li class='select2-more-results'>" + self.opts.escapeMarkup(opts.formatLoadMore(this.resultsPage)) + "</li>");
                    window.setTimeout(function() { self.loadMoreIfNeeded(); }, 10);
}
</code>
And the second time since a "scroll-debounced" event is fired by jQuery.
<code>
this.dropdown.on("scroll-debounced", resultsSelector, this.bind(this.loadMoreIfNeeded));
</code>

Since the "resultsPage" is only updated in the callback asynchronously (the update is done after the second call has been invoked), and same page is requested twice which causes an unwanted call to the server and duplication in the data.

I will appreciate it if you can look into it.

Thanks,
Eli Koren

**Comment by kevin-brown** [comment]
This should be fixed in 4.0, we now correctly debounce requests.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
