### ISSUE TITLE
Scroll offset by few pixel on open

### ISSUE THREAD

**Issue by calimero1000582** [select2/select2#1611]
Open the dropdown
Scroll down a page
Select an item
Reopen the dropdown

The highlighted item is not all visible
![image](http://i.imgur.com/S3tL00g.png)

By replacing the following line in the function ensureHighlightVisible:
```javascript
rb = results.offset().top + results.outerHeight(true);
```
by:
```javascript
rb = results.offset().top + results.outerHeight();
```

We can now see the higlighted item in full
![image](http://i.imgur.com/MaTop5h.png)

**Comment by kevin-brown** [comment]
This has been fixed in 4.0.
