### ISSUE TITLE
function on new tag creation

### ISSUE THREAD

**Issue by WilliamStam** [select2/select2#1618]
i currently have

    $(".tag-block").select2({
        tags           : tags,
        tokenSeparators: [","]
    });

tags is a json string

    var tags = ["z","y","1","new","rainwater","a","f","e","d","c","b","rain"];

I'm trying to get it to add any new tag created back to tags.. something like `tags.push(newtag)` i tried using `createSearchChoice` but it doesn't seem to do what i need

    $(".tag-block").select2({
        tags           : tags,
        tokenSeparators: [","],
        createSearchChoice:function(term){
            console.log(term);
        }
    });

outputs for every character inserted. basically a glorified onKeyUp. it also adds a "no matches found" block http://puu.sh/42C8S.png and it locks up the whole thing. without createSearchChoice it allows me to add new tags.

the console log outputs

    h
    he
    hel
    help

http://puu.sh/42Cdw.png

how would i go about "when a new tag is inserted that isn't in the 'tags' array it must call this function"

like a 

    onNewTag:function(tag){ 
        console.log(tag);
    }

my use case is i have a var of all the system tags. there are multiple tag places for various reasons.. any new tag inserted into any of the tag blocks should be available to the rest of the tag blocks immediately.

**Comment by kevin-brown** [comment]
You should be able to attach to the `change` event in order to detect when the new tag is added. You may want to add a custom tag-only property onto the data object in the `createTag` (previously `createSearchChoice`) function to identify it though.
