### ISSUE TITLE
Preventing on("click") propagation from Select2

### ISSUE THREAD

**Issue by EleventyOne** [select2/select2#1622]
This is in response to the original issue posted here: https://github.com/ivaynberg/select2/issues/1621

Since that was closed, I assume that I'm suppose to open a new issue. Apologies if that's not the case.

Anyhow, here is a jsfiddle that reproduces the issue: http://jsfiddle.net/fA6zp/2/

**Original message**:

I've got a select2 instance inside a div and if someone clicks on the select2 instance, I don't want the on("click") event to propagate up beyond the select2 (but I also don't want to prevent select2 from doing its own actions based on click events, obviously). I've taken a look through the docs and I have absolutely no idea where I'd even start for something like this.

Am I missing an easy solution here?

Thanks.

**Comment by phazei** [comment]
Hmm, I was actually just looking for the exact opposite of this.  Could it be modified to be an option?  My use case is a section on a form, if anyone clicks inside of it, I modify the page to reflect items in that section.  If someone clicks right on the select2, it doesn't trigger the click event.  Seems default behavior is to propagate up.
