### ISSUE TITLE
Tags with data-attribute

### ISSUE THREAD

**Issue by barryvdh** [select2/select2#1632]
Using a data-attribute works when I do something like this: `data-select2-tags='["a", "b", "c"]'
But when I call select2() without the tags function, it make the input a select dropdown, instead of a text field.
If I use both the tag option and the data-attribute, an error is thrown.
https://github.com/ivaynberg/select2/blob/master/select2.js#L909

Maybe just turn off the error and let the data-attribute overwrite the config? Or is there a way to enforce that behaviour?

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
