### ISSUE TITLE
could select2 give user a chance to stop ajax request?

### ISSUE THREAD

**Issue by windywany** [select2/select2#1637]
When we use ajax for query function, like:

``` js
$('#some input').select2({
      ajax:{ 
         data:function(term,page){
             if(/^[ab].*/.test(term)) return false;
             return {q:term,p:page};
          }
      }
    });
```

If the data call returns false or null and select2 can stop the ajax request, In my opinion, this will be very useful in some scenarios.

**Comment by voidale** [comment]
+1

**Comment by ps1x** [comment]
+1

**Comment by MoTai** [comment]
In my case, I want to prevent ajax request when search input box gets focused but input size is less than minimum input length.

**Comment by firebird631** [comment]
+1 this could be interesting to abort before running the ajax call.

**Comment by GrgDmr** [comment]
+1

**Comment by alexweissman** [comment]
Please refrain from submitting "+1" comments.  Simply click the 👍 on the top-level comment to show your interest in this issue.

**Comment by henkesn** [comment]
ajax.url also takes a function. It could be a solution to cancel the request on a falsy URL.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.

**Comment by hobin2017** [comment]
> In my case, I want to prevent ajax request when search input box gets focused but input size is less than minimum input length.

the `minimumInputLength` option may help

**Comment by hobin2017** [comment]
It would be great if there is an `beforeAjax` option which accepts a function. If this function returns true, new request is made. Otherwise, no request is made.

**Comment by m4gz** [comment]
It is so wiered i want to send query only after 4 length to avoid getting 10k results. Please add beforeAjax or make correct throw
