### ISSUE TITLE
Keeping a custom value (not available in the options of a select)

### ISSUE THREAD

**Issue by jlemale** [select2/select2#1638]
Hello,
So I have a select with 3 available products "a", "b", or "c"
But the user is typing "d" and instead of saying that its not available, and asking to pick a product in the above list. I would like to process that new value as a new product. And later then to add it to the available products.
is it possible ?
Thank you

**Comment by johnsona9** [comment]
Does this function still exist? I'm having a hard time locating it in the repo.
