### ISSUE TITLE
Multiselect width shrinks upon tag/option removal

### ISSUE THREAD

**Issue by kingIZZZY** [select2/select2#1642]
See title

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.

**Comment by MichaelSnowden** [comment]
I still have a similar (possibly the same) problem when using Bootstrap 4's `form-inline` and `form-group`.

To reproduce:

1.  Create a multiple select in a bootstrap 4 form-group, inside a form-inline, like this fiddle: [https://jsfiddle.net/eutrdwcn/](https://jsfiddle.net/eutrdwcn/). 
2. Type any letter in the field 

Now the field is really small and hard to use.

**Comment by mdesilvey** [comment]
I have the exact same problem as @MichaelSnowden, we have a requirement to use Bootstrap for our styling.  Makes for terrible user experience.

**Comment by t1a2l** [comment]
I have the same issue as @MichaelSnowden. Any fix for that? @kevin-brown
