### ISSUE TITLE
In Bootstrap 3 , when select2 is used on the modal it does not function properly

### ISSUE THREAD

**Issue by rohitdev** [select2/select2#1645]
Saw the previous issues reported https://github.com/ivaynberg/select2/issues/942

The issue is still open.

**Comment by ali2b** [comment]
I found a very simple solution for this problem.
just add this line in the onshown event for BootstrapDialog
$(".bootstrap-dialog").removeAttr("tabindex");

**Comment by FramnkRulez** [comment]
A word of warning to anyone who attempts the trick of overriding bootstrap's enforceFocus().  By doing this you will allow keyboard users to tab to controls outside of your bootstrap modal!  Another side effect is that you will no longer be able to set the initial focus to a form control on your modal.

**Comment by ekyna** [comment]
When a select2 is rendered in a modal, you must use the __dropdownParent__ option :
```javascript
$('#my-select').select2({
    dropdownParent: $('#my-modal')
});
```

**Comment by Uhelliton** [comment]
@ekyna nice!!!

**Comment by aman-raikwar** [comment]
it works for me too. thanks @ekyna

**Comment by P2YH** [comment]
@ekyna You save my life!

**Comment by alexweissman** [comment]
Locking because this issue has been solved and is well-documented in the official docs.
