### ISSUE TITLE
Select Multiple box not completely user-friendly

### ISSUE THREAD

**Issue by rickin-shah** [select2/select2#167]
For Select fields where the user is allowed to select only one option, there's a little search bar at the top to indicate to the user that he can filter options by typing in keywords. That search bar is missing from the 'select multiple' field, however. On top of that, it's not clear to users that select multiple fields are indeed select input fields at first glance. No arrow is there on the right side of the field indicating that the field can be 'opened' up to reveal selectable options. The user only knows that options can be selected once he clicks within the field to reveal its options. 

I understand this may have been a purposeful design decision in order to make select-multiple fields more distinctive from select-one fields. But my organization has actually made a decision to not use the select multiple field anymore in association with Select2 due to these very reasons. And I feel that by not using Select2 in this scenario means that we're missing out on a lot of the benefits that we get by using the library in the first place.

**Comment by binhwpo** [comment]
Thanks @svennerberg, your code work great. Except that I had to place this in order for the background to display correctly. But perhaps that's only my case.

**Comment by mimoriarty** [comment]
In today's version you only need to add to your css:

```
.select2-container--default .select2-selection--multiple:before {content: ' ';display: block;position: absolute;border-color: #888 transparent transparent transparent;border-style: solid;border-width: 5px 4px 0 4px;height: 0;right: 6px;margin-left: -4px;margin-top: -2px;top: 50%;width: 0;cursor: pointer}
```

**Comment by prograhammer** [comment]
I took the idea from @svennerberg and added a trick to fake the search box showing:

See this fiddle:
http://jsfiddle.net/T2Xe9/372/

```
.select2-container--default {
  .select2-selection--multiple {
    position: relative;

    &:before {
      content: ' ';
      display: block;
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      width: 18px;
      background: url('http://s13.postimg.org/561ktz86b/select2.png') 0 1px no-repeat;
    }
  }

  &.select2-container--open {
    .select2-selection--multiple:before {
      background-position: -18px 1px;
    }
    li.select2-search--inline {
      width: 99%;
      border: 1px solid #888;
      margin-top: 5px;
      padding-left: 2px;
    }
  }
}
```

**Comment by pfonsecamindbus** [comment]
Thanks!  @prograhammer

**Comment by hagen00** [comment]
The previous suggestions either didn't give both an up or down arrow, or, by using an image, didn't achieve exactly the same look (was pixellated). The following is working perfectly for me. 

```

 .select2-container--default .select2-selection--multiple:before {
	  content: ' ';
	  display: block;
	  position: absolute;
	  border-color: #888 transparent transparent transparent;
	  border-style: solid;
	  border-width: 5px 4px 0 4px;
	  height: 0;
	  right: 6px;
	  margin-left: -4px;
	  margin-top: -2px;top: 50%;
	  width: 0;cursor: pointer
  }
  
  .select2-container--open .select2-selection--multiple:before {
	content: ' ';
	display: block;
	position: absolute;
	border-color: transparent transparent #888 transparent;
        border-width: 0 4px 5px 4px;
	height: 0;
	right: 6px;
	margin-left: -4px;
	margin-top: -2px;top: 50%;
	width: 0;cursor: pointer
  }

```

**Comment by nivle** [comment]
Ehm multi select box arrow still has some weird issues

1) The down arrow doesn't show up
2) The placeholder doesn't show up initially
3) After selecting an item some weird white space is added to the right of the selected item
4) Definetly not user friendly, best would be if it looked like the single select box, had its own dedicated filter like the single select on dropdown.

Anyway, the whole multi select should be reworked...
