### ISSUE TITLE
Select2 scrolls to top when hovering over options after selecting parent option

### ISSUE THREAD

**Issue by dpgover** [select2/select2#1672]
I have a select2 (linked to a hidden input) with hierarchical data (as shown in this fiddle: http://jsfiddle.net/dpgover/AaaXM/ )

The user can choose any of the options (no matter if the option is a parent or a child node or the leaf of the select).

If the user choose one of the parents, all of its children disappear from the options (thats correct). But, if then the user try to select another option (in my configuration the select2 is multiple) the selection box scrolls to top when the user hovers over the options (only if that options are below of the selected one in the options list).

Because the problem is so difficult to explain, let me enumerate the steps so you can try it in the fiddle:
1. Open the select2 and select "Accesorios para Vehiculos" (sorry it's in spanish =( )
2. The select2 closes. Open it again. Scroll down (using the scrollbar or the mousewheel) without moving the mouse over the options.
3. Try to select any option.
4. Depending on how long you move the mouse, the scrolling div with the options starts to scroll up.

I'm sorry if I'm not clear. English is not my first language and the issue is very strange and difficult to explain.

Maybe my data tree is wrong, or I'm missing something in the configuration of the select2.

This is the config:
$('#relatedCategories').select2({
    placeholder: "",
    multiple: true,
    allowClear: true,
    closeOnSelect: false,
    width: '350px',
    data: treeData
});
/**\* See treeData in the fiddle ***/

If needed, ask for more info and I will try to clarify all that I can.

Thanks

**Comment by ShubhamSonawane** [comment]
@kevin-brown Still facing this issue in select2 4.0.3

**Comment by diyang** [comment]
@kevin-brown Still getting the same problem in select2 4.0.3

**Comment by catsalive** [comment]
I hacked in a solution on select2 4.0.0 if that helps:
line 829: Results.prototype.setClasses = function () {
should be: Results.prototype.setClasses = function (container) {

line 999: self.setClasses(); (this is in the select event)
should be: self.setClasses(container);

line 858: where it says "Check if there are any selected options" in the Result.prototype.setClasses function, wrap that whole if statement to trigger the mouseenter event inside another if statement:

if(!(container && container.isOpen() && self.options.get('multiple') && !self.options.get("closeOnSelect"))) {

did the trick for me (so far), not sure if it breaks anything else, but not having any problems yet

**Comment by catsalive** [comment]
Forgot the unselect:
line 1007~: self.setClasses(); (this is in the unselect event)
should be: self.setClasses(container);

**Comment by nasospsa** [comment]
Version: 4.0.3
Hey @catsalive I have the same problem. My current solution is a bit cleaner but still not good.

```
      var Adapter = function($element, options, dataAdapter) {
        Adapter.__super__.constructor.call(
          this, $element, options, dataAdapter
        );
      };
      /* eslint-disable new-cap */
      Utils.Extend(Adapter, Results);
      /* eslint-enable new-cap */
      Adapter.prototype.ensureHighlightVisible = function() {};
      return Adapter;
```

Then I set `Adapter` as a resultsAdapter option in initialization.

Now the reason for this ensureHighlightVisible is also used when the dropdown opens so you get scrolled to the first selected result.

The only way for this to happen is to disable (like what you have done in your code) only on the select and unselect events. (we may have to make a pull request for that one)

I hope it made sense :)

**Comment by ShubhamSonawane** [comment]
The workaround I found out for version 4.0.3 is to comment the "if.." loop at line 1261.. I don't know if there are any other effect of this but the scroll issue is resolved for sure.. Let me know if any other issues found due to this change.

if (currentIndex <= 2) {							//commented to avoid the scrolling issue
      this.$results.scrollTop(0);
    } else if (offsetDelta > this.$results.outerHeight() || offsetDelta < 0) {
      this.$results.scrollTop(nextOffset);
    }

**Comment by nasospsa** [comment]
I dont think the scroll is problematic by itself. I just think that  the "highlightFirstItem" should not run on the "select" or the "unselect" event.

The code is like this:
```
container.on('select', function () {
  if (!container.isOpen()) {
    return;
  }

  self.setClasses();
  self.highlightFirstItem();
});
```

I don't really find any reason to `highlightFirstItem` on the select event, we should just remove the line `self.highlightFirstItem();`

**Comment by ShubhamSonawane** [comment]
@nasospsa great..! that works.. :)

**Comment by bonesoul** [comment]
also happening to me even on 4.0.3

**Comment by ZuBB** [comment]
can confirm that solution suggested by @nasospsa does work!

**Comment by joelworsham** [comment]
If anyone wants to use the above solution but on the minified file, do a search in `select2.full.min.js` for `b.on("select",function(){b.isOpen()&&(d.setClasses(),d.highlightFirstItem()` and then remove exactly `,d.highlightFirstItem()`.

**Comment by yiannisdesp** [comment]
@nasospsa @joelworsham thanks!

**Comment by VoodooSV** [comment]
**@nasospsa @joelworsham** thanks a lot!
