### ISSUE TITLE
select2-focus event doesn't behave as expected

### ISSUE THREAD

**Issue by timbonicus** [select2/select2#1673]
Here's a simple JSFiddle to log select2-focus events to the console:
http://jsfiddle.net/timbonicus/L82GW/1/

* Click the Select2; select2-focus is fired as expected
* Click the input field to focus; select2-focus is fired on blur!
* Click the Select2 again; no select2-focus event is fired

**Comment by kevin-brown** [comment]
Closing this off due to a lack of activity.

If this is still an issue in the upcoming 4.0 release, feel free to reply back and we can determine if this needs to be reopened.
