### ISSUE TITLE
How to allow duplicate tags 

### ISSUE THREAD

**Issue by thyandrecardoso** [select2/select2#1674]
Hi, 
Select2 removes any tag that was selected by the user from the dropdown, not allowing them to select the same tag multiple times.
I have a use case where a user should be able to choose from a pre-defined list multiple tag values, while being able to insert duplicate values.
Here: 
- https://groups.google.com/forum/#!topic/select2/8JWTGtI4E9g

it is suggested to use CSS to "unhide" the results that were already selected.

So I used the "formatResultCssClass" function to add a class that forces any results to be shown. This maintains all the results on the dropdown, even after the user has select a given value.
Here is a fiddle:
- http://jsfiddle.net/6XdE7/1/

However, they are not selectable anymore!

Is there anyway to make select2 accept duplicate tags?

**Comment by elyasmv** [comment]
https://stackoverflow.com/a/68540536/8705204
