### ISSUE TITLE
How to change ajax.url after select2 initialization 

### ISSUE THREAD

**Issue by christophediprima** [select2/select2#1679]
All is in the title! I tried to call element.select2({ajax: {url: myNewUrl}}); but I loose all other options...

**Comment by hakdag** [comment]
I am also looking for a solution for this. I want to update url after I initialized the select2. In my case there is another drop down. Url of select2 must be updated when selection changes in first drop down.

**Comment by sodapopcan** [comment]
```
var someCondition
ajax: {
  url: function() {
    if (someCondition) {
      return '/api/1/someFile.json'
    } else {
      return '/api/1/someOtherFile.json'
    }
  }
}
```
