### ISSUE TITLE
Request "add" and "remove" methods for easier external value changes

### ISSUE THREAD

**Issue by louisameline** [select2/select2#1681]
Hi,

Correct me if I'm wrong but I've found no easy way to add/remove an item to/from an existing selection from the outside of select2. In my use case, clicking on pictures adds/removes people in the list.

What I do right now is : 

var ids = el.select2('val');
ids.push(newId);
el.select2('val', ids).trigger('change')

The item is added but the first problem is, this code does not trigger a nice "change" event like the one when you select an item from the dropdown list, which tells you what has been added with the "added" custom property. I bind on the "change" event to manage more things from there. To achieve consistency, I currently have to forge my "change" events myself with the same "val" and "added" properties as the ones generated by select2 : not a great idea.

The second problem is, there is no "select2-selecting" event triggered. The select2-selecting handler is used as a filter function to authorize some selections and not others, but this filter function is not applied on values submitted from outside select2.

In the end to solve this, I would be happy to see simple methods like these, that would trigger the same events and go through the same filters as a manual selection/removal from inside the select2 field : 

el.select2('add', newId);
el.select2('remove', oldId);

Also, an array of ids/objects could be provided to the methods instead, and I would expect the "change" event to be triggered once for each of them.

Anyway, thanks for the great work guys.

**Comment by kevin-brown** [comment]
Given the lack of :+1:'s on this ticket, I don't think it's going to be happening.

**Comment by louisameline** [comment]
About the lack of +1, I guess that few people build complex apps that try to get the best of the library. But I do have complex scenarios, and I wish select2 had methods for consistent manipulation.

But I understand that it would represent some work. I've looked at the source code to contribute and I was quickly discouraged by the mass of code. I would personnaly try to split it and make it more modular if I had time, maybe some day. Thank you anyway for your work.

**Comment by kevin-brown** [comment]
> I would personnaly try to split it and make it more modular if I had time, maybe some day.

4.0 is completely modular. :)

https://select2.github.io/

**Comment by louisameline** [comment]
Great, I'll definitely check it out, thanks :)
