### ISSUE TITLE
"not rounded" width for dropdown

### ISSUE THREAD

**Issue by sean0205** [select2/select2#1692]
Hi,

To make Select work perfectly on responsive layouts(e.g: Bootstrap 3.0) could you consider using "not rounded" width in positionDropdown function: 

Change:
width= this.container.outerWidth(false) 

To:
width = this.container[0].getBoundingClientRect().width

Othervise on Bootstrap grid system, the fluid select2 dropdowns width is a bit bigger than the container width.

Thanks

**Comment by alexweissman** [comment]
A PR for this appears to be submitted.  See #4738.
