### ISSUE TITLE
selectOnBlur shouldn't automatically highlight/select first element

### ISSUE THREAD

**Issue by onyxraven** [select2/select2#1698]
selectOnBlur should select the element the user chose and not default to the first one in the list on open.

This happens at https://github.com/ivaynberg/select2/blob/b4083330b329e2f2811c267a6dedda0d361abb50/select2.js#L1274 - this "selectHighlighted" line shouldn't be there by default, or there should at least be a way to disable this behavior.

**Comment by mahesh-ziffi** [comment]
Same Here :(

**Comment by kevin-brown** [comment]
This should have been fixed with Select 4.0.0 and the modified `selectOnClose` option.

**Comment by Mohit2611** [comment]
Is this issue resolved? I am still getting this error in Select 4.0.3 .

`$("#selectCourse").select2({
                            placeholder: "Course / Class",
                            tags: true,
                            allowClear: true,
                            selectOnBlur: true,
                            selectOnClose: true,
                            "language": {
                                "noResults": function () {
                                    return "";
                                }
                            }
                        `

**Comment by klesun** [comment]
Same here, issue still reproduces in 4.0.2
```html
<select id="someSelect" multiple="multiple">
    <option value="aaaaa">aaaaa</option>
    <option value="bbbbb">bbbbb</option>
    <option value="ccccc">ccccc</option>
</select>

<script>
    $('#someSelect').select2({closeOnSelect: false});
</script>
```
