### ISSUE TITLE
Setting initial values on load with Select2-Ajax

### ISSUE THREAD

**Issue by sunalive** [select2/select2#1700]
I have select2 controls set up with Ajax (have both single and multiple). I'm trying to have some values on page load but I'm not able to get this to work however. My code for select2 is given below:

```
function AjaxCombo(element, url, multival ){  // multival = true or false
  multival = multival || false;
  $(element).select2({
   minimumInputLength: 2,
   multiple: multival,
   separator: '|',
   ajax: {
     url: url,
     dataType: 'json',
     data: function (term, page) {
        var targetname = $(this).attr('name');
        var target = targetname.slice(targetname.indexOf("[")+1, targetname.indexOf("]"));
       return {
         targettype: "search",
         target: target,
         search: term
       };
     },
     results: function (data, page) {
       return { results: data };
     }
   }
 });
}
AjaxCombo(".ajaxselect", "includes/linkedcontrol.php", false);
AjaxCombo(".ajaxmultiselect", "includes/linkedcontrol.php", true);
```

The Ajax combo works fine, am having trouble only with the initial values load. I tried this code below but couldn't get it to work:

```
initSelection : function (element, callback) {
    var elementText = $(element).attr('data-initvalue');
    callback(elementText);
}
```

My HTML from php is returned as below :

```
<input name='header[country]' class='ajaxselect'  data-initvalue='[{"id":"US","name":"United States of America"}]' data-placeholder='Select Country' value='' />
```

I see that values are populated from php, only my jquery is having issues. My values in the control show up as `US | United States of America`. I guess I have edited the select2 source for getting this format as default without using format option.

Can you please help me achieve this?  Thanks for the great plugin.

**Comment by Stefadesign** [comment]
I have the same issue. I am trying to get value from ajax call on Select2  initiation not on focus/click. I can have it working on focus by setting "minimumInputLength:0"  however it requires user to click on container to trigger ajax. I need it pre-loaded when initiated. How do I get that working?

**Comment by OwenBannister** [comment]
For anyone else with this issue, I got it working with 
```
   // passed data-initvalue='[{"id":"US","name":"United States of America"}]'
    initSelection : function (element, callback) {
        var elementText = $(element).attr('data-initvalue');
        callback(JSON.parse(elementText));
    },
```
This missing step was parsing it to json
