### ISSUE TITLE
get attributes of the original <option>

### ISSUE THREAD

**Issue by inmarelibero** [select2/select2#171]
this is more a "how to" than an issue.

let's put I have a simple select:

``` html
<select id="sel">
    <option data-foo="bar">one</option>
    <option data-foo="bar">two</option>
    <option data-foo="bar">three</option>
</select>
```

and the plugin initialized in this way:

```
function format(item) {

    [here I'd like to get data-foo related to the item]

    return '<div class="item">' + item.text + '</div>';
}
$('#sel').select2({
    placeholder: "pick one",
    allowClear: true,
    formatResult: format,
});


```

is there any way to get the `data-foo` attribute of the original <option>? I had a look at the source code but I didn't get it. thanks

**Comment by qooob** [comment]
Could anyone help because I can't make select2 options, value to copy styles from <option> field.

Example

HTML: 

```HTML
<select name="dom" id="dom">
    <option value="14330869608527">test.ru</option>
    <option value="143309544520197" selected style="font-style:italic">sub.test.ru</option>
</select>
```

```JS
function format(style) {
	var originalOption = $(style.element);
	return originalOption.attr('style');
}

window.parent.$('select').select2({
	minimumResultsForSearch: 5,
	formatSelection: format
});
```

How do I make select2 text's, that is `italic` in original select's option, also `italic`? Any help, please?

**Comment by Eduardomendesc** [comment]
$('#mySelect2').select2({
  // ...
  templateSelection: function (data, container) {
    // Add custom attributes to the <option> tag for the selected option
    $(data.element).attr('data-custom-attribute', data.customValue);
    return data.text;
  }
});

// Retrieve custom attribute value of the first selected element
$('#mySelect2').find(':selected').data('custom-attribute');
