### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by trinzia** [select2/select2#1712]
I'd like to suggest a few UI style options.

1) Option to hide the search input:  I will use one script to style all select boxes on my site, but not every one of my selects requires a text-input search box.  I'm about to try to hide it with css.

2) Option to widen on click:  I am having difficulty creating a script to widen the search box when it is clicked.  The reason is that whenever I click it in Firefox/Chrome, to try to determine the ID which i should target, it is hidden.  I would like a little option that has a graceful fallback: Use JS to shrink the box on page load, then widen on click.  Or maybe you could tell me what class/ID to target for that.

3) Option for separate containers:  select2-search-choice and select2-search-field are in the same UL.  This will make it difficult for me to reposition the multi-select search choices using css.  I'd like to be able to place the choices above some search results.

I'm working on a site which filters a bunch of content, like Zappo's.  Ideally I'd like to be able to have several multi-selects all placing the choices into another container.  For now, I'm working around, but that would be nice long-term.  

4) Option to put the placeholder into html as data-placeholder.  This would be useful on sites with many select boxes, so I may store them in the html.

PS - Your script is working nicely with a Lucene search engine.  
Thanks so much. :)

**Comment by kevin-brown** [comment]
This should be possible in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
