### ISSUE TITLE
Typing on focus doesn't work in Chrome when using border-box

### ISSUE THREAD

**Issue by johnnyoshika** [select2/select2#1727]
I noticed a problem in Chrome when using Paul Irish's border-box technique: http://www.paulirish.com/2012/box-sizing-border-box-ftw/

If we apply a padding style on input elements, Selec2's keyboad no longer works properly in Chrome.  Typing while the Select2 element is in focus no longer does anything.  To test this behavior, here's a jsfiddle:

http://jsfiddle.net/DuDRs/1/

When the jsfiddle loads, hit 'tab' to focus the Select2 element.  Now try typing something.  Nothing happens.  It seems that the keyboard has no effect on focus of the Select2 element until the Select2 element is explicitly opened with the mouse.

This problem happens in Webkit only (Chrome and Safari).  Firefox and IE seems to be fine.

Interestingly, if I remove the border-box technique:
* { -moz-box-sizing: border-box; -webkit-box-sizing: border-box; box-sizing: border-box; }
then everything behaves properly.

Also interesting is that if I remove the "container" class, then everything behaves properly again.  Here's an example: http://jsfiddle.net/sfjEY/1/

Anyone know what's going on?  Is this something that can be fixed in Select2?

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
