### ISSUE TITLE
Select2 with tagging support - horisontally resize

### ISSUE THREAD

**Issue by hunpoto** [select2/select2#1737]
Hi! I would like to use tagging support, but I don't have enough space under the input. I would like then the basic input open up to the left, when I click it. Or when there is a lot of tags. Basically open (resize) it to down.

Same like this, just with tagging support: http://jsfiddle.net/acpFh/6/

How do I solve this?

Thanks a lot!

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
