### ISSUE TITLE
select2 doesn't close when clicking outside of the select2 container - broke after 3.4.1

### ISSUE THREAD

**Issue by fredmalone** [select2/select2#1745]
I created a very simple example at:  http://jsfiddle.net/fkmalone/2bqXa/
Note that I pointed it to a copy of select2.js and select2.css on my server.  However, the files are unchanged from what I downloaded.

Basically, when I upgraded from 3.4.1 to 3.4.3 whenever I click outside of the select2 container it doesn't close.  It did in 3.4.1.

**Comment by gmfaruk** [comment]
Add this code. this is work for me..

$(document).click(function() {
    $("#select").select2('close');
});
