### ISSUE TITLE
Can't focus the search field in a Boostrap modal

### ISSUE THREAD

**Issue by laurentdinclaux** [select2/select2#1749]
The search field seems to focus/blur continuously.

Here is a fiddle (using 3.4.1 thought a CDN) but I faced the same issues using the master branch:

http://jsfiddle.net/xRnCN/

**Comment by mcarlone** [comment]
@laurentdinclaux thank you for the hack.

My users expect to use esc. to cancel the modal, hope to see a fix in future releases for select2.

**Comment by JhonatanPereira** [comment]
Nothing yet?

**Comment by mvianello** [comment]
Nothing yet 2?

**Comment by frin** [comment]
The correct solution is to make select2 append its tags inside modal dialog: https://stackoverflow.com/a/33884094/917476
