### ISSUE TITLE
placeholder not visible when select2 is on a tab

### ISSUE THREAD

**Issue by tommytob** [select2/select2#1753]
We have implemeted the tabs of jquery-ui when the multiselect2 is on the visible tab placeholder is shown. When the multiselect2 is on a hidden tab the placeholder is not visible. The style of width of the search input is 0. When I click on the multiselect2 the search input gets the right width.

The this.getMaxSearchWidth() function causes the problem. because the this.selection.width() is 0.

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
