### ISSUE TITLE
closeOnSelect with createSearchChoice leaves text when item selected

### ISSUE THREAD

**Issue by davidgraca** [select2/select2#1758]
Hello,

I am trying to select multiple items with closeOnSelect: false and it works fine. The problem is if i write "test" per example and i select an item from the list the item is added but "test" is still on the textbox as a raw string. The same behavior doesn't exist if closeOnSelect: true,

After the multiple selection of items is there a way to close the list that i can control? The only way I found was to click anywhere on the webpage. I would like something like hitting enter or space would make the list close.

Thanks

Here is the code:

```javascript
$('#test2').select2({
    minimumInputLength: 3,
    multiple: true,
    closeOnSelect: false,
    placeholder: 'Search',
    ajax: {
        multiple: true,
        url: "my api",
        dataType: 'json',
        quietMillis: 300,
        data: function (term, page) {
            return {
                query: term,
                noOptions: false
            };
        },
        results: function (data, page) {
            lastResults = data.Suggestions;
            return { results: data.Suggestions };
        }
    },
    formatResult: function (suggestion) {
        var ret = "<div class='select2-user-result'>";
        if (suggestion.Value != undefined)
            ret += suggestion.Value;
        ret += "</div>";
        return ret;
    },
    formatSelection: function (suggestion) {
        var ret = "";
        if (suggestion.Value != undefined)
            ret += suggestion.Value;
        return ret;
    },
    createSearchChoice: function (term) {
        var text = term + (lastResults.some(function (r) { return r.Value == term }) ? "" : " (new)");
        return { Id: Math.floor(Math.random() * 10000), Value: text };
    },
    id: function (suggestion) {
        return suggestion.Id;
    }

});
```

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.

**Comment by jbuchan12** [comment]
For anyone still experiencing this in V4, i used this as a work around

            //On item selection changed
            .on('change',
                function(e) {
                    //Remove the trail query text to appears due to select 2 bug
                    var element = $('.select2-search--inline'); 
                    if (element != undefined && element.children()[0] != undefined) {
                        //remove the unwanted text
                        element.children()[0].value = '';
                    }

**Comment by fakeharxy** [comment]
Hi, just to say, this is still an issue in 4.0.6... about to see if I can get the above fix to work.

**Comment by picov** [comment]
Issue still present in latest 4.0.6-rc.1.
I use this walk around:

```
.on('select2:select',function (e) {
	if ($(this).next().find('.select2-selection--multiple').length!=0) { // only multiple select 
		var element = $(this).next().find('.select2-search__field');
		if (element !== undefined) {
			// Remove the unwanted text
			element.val('');
			// Trick to restore cursor editing position
			$(this).select2("close").select2("open");
			element.blur();
		}
	}
});
```

**Comment by SeventhCycle** [comment]
Hello,

Just to confirm, this bug still exists on 4.1.0-beta 1. You can see this in action here:

https://jsfiddle.net/jcgkr6e4/

@picov As a heads-up, your code introduces issues with mouse selection, so I added a block which checks to see if there's leftover text. I only clear the text if there's existing text here.

```
.on('select2:select',function (e) {
	if ($(this).next().find('.select2-selection--multiple').length!=0) { // only multiple select
		var element = $(this).next().find('.select2-search__field');
		if (element !== undefined) {
			// Remove the unwanted text
			if (element.val() != "")
			{
				element.val('');
				// Trick to restore cursor editing position
				$(this).select2("close").select2("open");
				element.blur();
				element.focus();
			}
		}
	}
});
```

**Comment by dani24gl** [comment]
Still looking for a permantent solution for this bug. For now the @SeventhCycle workaround worked for me

**Comment by SSheoran84** [comment]
We can use [clearSearchOnAdd]="true" to clear search ext
