### ISSUE TITLE
Avoid the space tokenization on copy paste

### ISSUE THREAD

**Issue by romainbessugesmeusy** [select2/select2#1759]
Hello, I am using the tagging method of Select2 to allow user to copy paste products SKUs from spreadcheets. I am facing an issue with some SKU that contain space character. When I copy from OpenOffice, Excel or Google Spreadsheets, the string content is pure CSV, with line breaks as row delimiter and tabs as field delimiters. 

I tried to override the tokens with ["\t", "\n"], but due to the use of an input[type=text], the line breaks are automatically turned into spaces by the browser. 

Is it possible to switch the input element to textarea or div[contenteditable] to avoid this behaviour ?

Thanks again for this awesome plugin, it's a dream came true.

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
