### ISSUE TITLE
Keyboard Typing/Matching Navigation with search off and a few items in list

### ISSUE THREAD

**Issue by gitout** [select2/select2#1781]
I had mentioned this in #162 which was closed, but I will mention it again.. I would love to see keyboard navigation matching/typing work in select2 when search is not active and there are only a few items in the list. I think this does matter. Think of the "power user" who uses the keyboard only. It would be nice to tab into the control, select the item via keyboard then tab off and move on. This is not rare, it's a common scenario. It's annoying when you are using the keyboard only and then have to switch to the mouse to select an item.

**Comment by antgonzales** [comment]
+1 for keyboard navigation when the search field is hidden.

**Comment by sengeezer** [comment]
I resolved this by also being friendly to our non-sighted and sight impaired users:
```
$('select').on('select2:open', function(ev) {
    // Hide search box from sighted users
    $('.select2-search--dropdown').css({
        'position': 'absolute',
        'left': '-10000px',
        'top': 'auto',
        'height': '1px',
         'width': '1px',
         'overflow': 'hidden'
    });
});
```
Credit for inspiration goes to [WebAIM](http://webaim.org/techniques/css/invisiblecontent/).
