### ISSUE TITLE
allowClear option with ajax load

### ISSUE THREAD

**Issue by kylemwhite** [select2/select2#1785]
I'm not sure if I'm misunderstanding or if my use case is just not possible right now. From what I can tell, it is not possible to have the allowClear icon on an S2 box that uses ajax because ajax requires an INPUT tag instead of a SELECT tag but the allowClear option requires a blank OPTION tag inside the SELECT tag.

Is there a way to use the ajax properties AND the allowClear option? If so, how? If not, then maybe this is a feature request.

Thanks.

**Comment by p29892p** [comment]
Can you tell me or paste an example of code to know how did you add placeholder for select2 ajax call @kylemwhite 

Thanks

**Comment by webdevilopers** [comment]
Was this issue related to **< 4.*** those days @kylemwhite ?

Here is an example with **4.0.3** using `<select>` and AJAX and `allowClear`:

```html
		$j("#customerId").select2({
			minimumInputLength: 2,
			placeholder: 'Alle',
			allowClear: true,
			ajax: {
				url: "/customer/autocomplete",
				dataType: 'json',
				delay: 400,
				processResults: function (data) {
					return {
						results: data
					};
				}
			}
		}).val('1').trigger('change');

		<select id="customerId" name="customerId" style="width: 300px;">
			<option value=""></option>
			<option value="1">Pre-selected Customer here</option>
		</select>
```
