### ISSUE TITLE
width property ignored when recreated in firefox 13.0.1

### ISSUE THREAD

**Issue by dafengche** [select2/select2#1788]
```
$("#maccverif_stn").select2({
  width: "150",
  multiple: true,
  placeholder: "Please select 1+ stations",
  data: function() {
    return {results: stations};
  }
});
```

works fine, then I do
      $('#maccverif_stn').select2("destroy").select2({
        width: "150",
        multiple: false,
        placeholder: "Please select a station",
        data: function() {
          return {results: stations};
        }
      });
in Firefox 13.0.1, the width property is ignored because the style is set to "display: inline; width: 150px;".

**Comment by cmfitch1** [comment]
I just bumped into this issue. Thanks for the workaround. Here's a jsfiddle that reproduces it:
https://jsfiddle.net/ydoq31rs/

**Comment by giladgray** [comment]
Another workaround is to pass the `containerCss` option as follows to override whatever Select2 is doing internally:

```
$el.select2({
  containerCss: {
    display: "block"
  }
});
```
