### ISSUE TITLE
Select2 results margin causes item's selected at end to overflow weird

### ISSUE THREAD

**Issue by carlsverre** [select2/select2#1793]
See: http://d.pr/i/B31i

This happens for me in chrome/firefox/safari on Mac OS X.  Not sure if it happens in every browser, but the cause is line 1391 in `ensureHighlightVisible()`.

```
            rb = results.offset().top + results.outerHeight(true);
```

If the outerHeight function is called without true as it's first argument the result looks like this: http://d.pr/i/n50n

(this happens as you are scrolling down with the arrow keys)

I propose removing the "true" from that function call.

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
