### ISSUE TITLE
Select2 Broken Event Firing on Second Select2 when loaded via AJAX to .html

### ISSUE THREAD

**Issue by koconder** [select2/select2#1800]
Im having an issue with select 2 where the second select 2 which is pulling the <option> from AJAX which is returning the HTML to replace.

The main issue seems to be the second select 2 'select' is not adding the selected atribute for some god forsaken reason... the console.log is not kicking in.

Also posted on stackoverflow: http://stackoverflow.com/questions/19408782/select-2-issue-with-on-change-event-not-firing-on-second-select

	function select2_format_flag(state) {
	    var originalOption = state.element;
	    if (!$(originalOption).data('iso')) return state.text;
	    return "<img class='flag' src='<?=$adtrafik_config['uri_assets']?>img/flag/" + $(originalOption).data('iso') + ".gif' /> " + state.text;
	}

	function select2_format_engine(state) {
	    var originalOption = state.element;
	    if (!$(originalOption).data('engine')) return state.text;
	    return "<img class='engine' src='<?=$adtrafik_config['uri_assets']?>img/img/engine/" + $(originalOption).data('engine') + ".png' /> " + state.text;
	}

	jQuery(document).ready(function () {
	    //API Path
	    var adtrafik_api = '<?=$adtrafik_config['
	    uri_post '].'
	    seo / report - regional / api / '?>';
	    //Select2
	    $('#go').attr('disabled', 'disabled');
	    $('#d_to').attr('disabled', 'disabled');
	    $('#d_from').attr('disabled', 'disabled');
	    //Init. Select2
	    $('#d_engine').select2({
	        placeholder: "Select Engine...",
	        allowClear: true,
	        width: 'resolve',
	        formatResult: select2_format_engine,
	        formatSelection: select2_format_engine
	    });
	    $("#d_market").select2({
	        width: 'resolve',
	        formatResult: select2_format_flag,
	        formatSelection: select2_format_flag
	    });
	    $('#go').click(function (event) {
	        event.preventDefault();
	        var d_from = $('#d_from').val();
	        var d_to = $('#d_to').val();
	        var data_key_engine = $("#d_engine option:selected").attr('data-engine').toLowerCase();
	        var engineid = data_key_engine;
	        //var engineid = data_key_market + '-' + data_key_engine;
	        <? php
	        if (isset($uri_page[2])) { ?>
	                window.location.href = '<?php echo $adtrafik_config['
	            uri_post '].'
	            seo / report - regional / overview / '; ?>' + engineid + '/' + d_from + '/' + d_to + '/'; <? php
	        } else { ?>
	                window.location.href = '<?php echo $adtrafik_config['
	            uri_post '].'
	            seo / report - regional / '.$uri_page[2].' / '; ?>' + engineid + '/' + d_from + '/' + d_to + '/'; <? php
	        } ?>
	    });
	    //Add Formatter and AJAX to Market
	    $('#d_market').change(function () {
	        var id = $('#d_market').val();
	        var dataString = 'type=nav&call=d_engine&d_market=' + id;
	        var data_key_market = $("#d_market option:selected").attr('data-iso').toLowerCase();
	        $.ajax({
	            type: 'GET',
	            url: adtrafik_api,
	            data: dataString,
	            cache: false,
	            success: function (html) {
	                $('#d_engine').select2('enable');
	                $('#d_engine').html(html);
	            }
	        });
	    });
	    $('#d_market').change(function () {
	        console.log('i changed');
	    });
	    $('#d_engine').change(function () {
	        console.log('i changed too....');
	    });
	    //END this crap!
	});

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
