### ISSUE TITLE
Compatibility issue with Placeholder Enhanced 1.6.6

### ISSUE THREAD

**Issue by Codermar** [select2/select2#1802]
I found a compatibility issue when using jQuery Placeholder Enhanced 1.6.6. I was getting: TypeError: i.push is not a function ...;if(q(g,b.id(i))){a.push(i),f.splice(h,1);break}}d(a)}:a.noop})}),b},

A simple fix is to ensure the val is an array before
if (!$.isArray(val)) { val = []; } // JGA Fix: ensure val is an array so the push below can happen.

Would this break something else?

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
