### ISSUE TITLE
initSelection object/array support

### ISSUE THREAD

**Issue by Nytrm** [select2/select2#1813]
When multiple is set to false does it only allow a single object in the callback ?
Why not allow a array and get the element at position 0 if it exists.

works when multiple is set to true
initSelection: function(element, callback) {
var selected = ["0","1"]
callback(selected);
}

fails when multiple is set to false
initSelection: function(element, callback) {
var selected = ["0"]
callback()selected;
}
works then using an object
initSelection: function(element, callback) {
var selected = {"0"}
callback(selected);
}

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
