### ISSUE TITLE
The first empty option is removed if no placeholder is specified

### ISSUE THREAD

**Issue by corinnaerin** [select2/select2#1824]
If the first option in the select has a blank value and blank text, and no placeholderOption or placeholder is specified in any way, then the first option is not displayed in the select2 results. This is because placeholderOption returns the first option if it's blank, which means getPlaceholder returns an empty string as the placeholder. `opts.query` removes the placeholder option if there is one and the placeholder is undefined - but not if the placeholder is an empty string. This is a simple fix to check that the placeholder's length is greater than 0. 

old version:

    // ignore the placeholder option if there is one
    if (this.getPlaceholder() !== undefined && children.length > 0) {
        placeholderOption = this.getPlaceholderOption();
        if (placeholderOption) {
            children=children.not(placeholderOption);
        }
    }

new version:

    // ignore the placeholder option if there is one
    var placeholder = this.getPlaceholder();
    if (placeholder && placeholder.length > 0 && children.length > 0) {
        placeholderOption = this.getPlaceholderOption();
        if (placeholderOption) {
            children=children.not(placeholderOption);
        }
    }

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
