### ISSUE TITLE
Scrollbar Positioning Incorrect in Firefox when Reopening

### ISSUE THREAD

**Issue by BaconSoap** [select2/select2#1828]
In Firefox, the scrollbar inside the select2 component doesn't behave properly when reopening it after having scrolled.

1. Open the [demo site](http://ivaynberg.github.io/select2/) in Firefox.
2. Open the first select2 control, then scroll inside it all the way to the bottom.
3. Click outside of the control, closing the control.
4. Open the control again. The list is reset (you see the top of it), but the scrollbar is positioned at the bottom.

![Example](https://f.cloud.github.com/assets/77809/1382626/061aa570-3b31-11e3-8a47-0a7addeb7615.PNG)

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
