### ISSUE TITLE
Copy text when it's set read-only

### ISSUE THREAD

**Issue by Leftyx** [select2/select2#1832]
I know it might seem a silly request but I've got a form with loads of fields set read-only.
A regular text field can allows me to copy the text in it but select2 doesn't.

Thanks.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
