### ISSUE TITLE
Drop Down Issue in Jquery Select2 plug in 3.4.3

### ISSUE THREAD

**Issue by 29snehal** [select2/select2#1834]
![select2 plug in](https://f.cloud.github.com/assets/5763217/1397186/1a3c8c2a-3c81-11e3-8995-a61be94b9963.PNG)

Drop Down Issue in Jquery Select2 plug in 3.4.3 -- Select one option from Drop Down, again click on space bar + enter.

System selecting already selected option

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
