### ISSUE TITLE
Invalid regular expression using complex select id

### ISSUE THREAD

**Issue by eusonlito** [select2/select2#1841]
I have this code:

``` html
<select id="options_values[code][estado-de-conservacion]" class="form-control select2" name="options_values[code]">
    <option value="afbc57bd3b0a">Nuevo garantía</option>
    <option value="402ab66290b2">Nuevo sin uso</option>
    <option value="c0199cb4befb">Marcas y roces propios del uso</option>
    <option value="8ba7c0b63a94">Piezas muy deterioradas o rotas</option>
</select>
```

And when I click in select to expand, works well but any other click more in any page element return a javascript error:

```
Uncaught SyntaxError: Invalid regular expression: /(^|\.)s2id_options_values[code][estado-de-conservacion](\.|$)/: Range out of order in character class
```

The problem seems to be in "-" sign, because other select with same structure but without "-" are working well.

``` html
<select id="options_values[code][estado]" class="form-control select2" name="options_values[code]">
    <option value="afbc57bd3b0a">Nuevo garantía</option>
    <option value="402ab66290b2">Nuevo sin uso</option>
    <option value="c0199cb4befb">Marcas y roces propios del uso</option>
    <option value="8ba7c0b63a94">Piezas muy deterioradas o rotas</option>
</select>
```

Here a JSFiddle example http://jsfiddle.net/nzt7g/1/

**Comment by lukedanielson** [comment]
Was this ever solved?  Getting the same error when I have dashes in my input's name parameter.  remove them and it works just fine.

Using 4.0.0-rc.2

**Comment by ghprod** [comment]
same with me here ..

using uuid as key and got error

**Comment by kevin-brown** [comment]
@lukedanielson @ghprod This ticket was for Select2 3.x. If the issue has come back in Select2 4.x, can you create a new ticket referencing this issue (preferably with a jsbin showing the issue)?

**Comment by ghprod** [comment]
@kevin-brown oopss Sorry ... :+1:
