### ISSUE TITLE
How to make a always visible item?

### ISSUE THREAD

**Issue by mllamazares** [select2/select2#1843]
I have a Select2 loaded with all the users, and I want to add a item on the top which contains the text `Add friend +`. 
I'm trying to find the way to make it visible independently on what the user types.
Is there any feature to do it? Do you have any idea, tip or advice?

**Comment by svivian** [comment]
@ivaynberg is this option still available in v4? I don't see it in the new docs, I tried to use it based on the v3.5 docs but it's not working (not showing the extra option). Has it been replace with another method?

**Comment by kevin-brown** [comment]
This is now called `createTag` in 4.0.0 and required the `tags` option to also be enabled.

**Comment by svivian** [comment]
Thanks, but using tags is not what I want to do. I've been looking at doing this a different way - adding an extra option manually (i.e. in the HTML) and using the `matcher` option to keep it always shown. This is working, but I am now essentially replicating select2's functionality besides this one exception. Is there a way to call the default matcher function? i.e. replace `defaultMatcher` below:

	matcher: function(params, data) {
		// my custom option
		if (data.id == 9999) {
			return data;
		}

		// call the default matcher here
		return defaultMatcher(params, data);
	}
