### ISSUE TITLE
select2('data') will not be updated if a user clicked on X

### ISSUE THREAD

**Issue by tirana** [select2/select2#1848]
Open the "Programmatic Access" example
1. click on "Set to California and Massachusetts using data"
2. click on "Alert selected value using data" that should return 2 values
3. click on X to remove "Massachusetts"
4. click on "Alert selected value using data"

Expected: Selected value is: [{"id":"CA","text":"California"}]
Actual: Selected value is: [{"id":"CA","text":"California"},{"id":"MA","text":"Massachusetts"}]

Note: select('val') returns correct 1 item.

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.
