### ISSUE TITLE
Page Up/Down keys do not scroll options

### ISSUE THREAD

**Issue by samrueby** [select2/select2#1851]
When Select2 is expanded, the keyboard Page Up/Down keys should be moving the highlighted item up/down by some reasonable amount, i.e. 8 items. Currently, these keys do not function at all.

**Comment by kevin-brown** [comment]
Clearing this off of the milestone for 4.0 but I still am hoping to get it implemented, just not right now.

**Comment by Stadly** [comment]
+1

**Comment by ztane** [comment]
Please, this is a really annoying usability problem.

**Comment by alexweissman** [comment]
I'd say this is fairly low-priority, since Select2 is centered primarily around it's ability to filter results via search.  However, it is still a valid feature request and I'd be happy to review a PR that implements this.

**Comment by adql** [comment]
I work with a system that uses select2 where filtering still results in pretty long lists. Yes, this is an annoying usability problem, especially when filtering still leaves you with the options of: 1. even more filtering (a lot of typing, potential typos); 2. traveling the list with the arrow keys (annoying); 3. reaching for the mouse (say no more).

But it doesn't end up with the usability issue.
> Select2 was designed to be a replacement for the standard `<select>` box that is displayed by the browser. By default it supports all options and operations that are available in a standard select box, but with added flexibility.

([Basic usage](https://select2.org/getting-started/basic-usage))

... which shorty after continues to demonstrate that it's just not true. Being able to jump down and up the list with the `Page Down`/`Up` keys is a basic feature of the elementary `select` element, mirroring operating-system UI. For an end user accustomed to working with the keyboard it provokes a feeling that something got stolen away, that some "hack" eliminated basic interface for a fancy overlay.

(And I assume the "added flexibility" relates to the developer.)
