### ISSUE TITLE
Add formatted string support.

### ISSUE THREAD

**Issue by tucson-tom** [select2/select2#1860]
This is going to be a weird request and I realize the request is outside the general scope of the project (i.e. a 'select' replacement).

Take a standard 'input type=text' field and a format string.  As the user types, select2 could do two things:  Display a dropdown select field containing options for each position AND restrict typing to allowed areas.  A format string could be:  "%1:%2 %3".  Placeholders might be ['Hour', 'Min', 'Period'].  And an array of values (or callbacks) would be supplied for each section of the string being constructed containing the allowed values - e.g. [['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], ['00', '15', '30', '45'], ['am', 'pm']].

Doing the above would be a fantastic time picker replacement but would be powerful enough that I would find all sorts of nifty uses for it (already have a couple of others in mind) where constructing formatted strings for a single field using select2 would make my life easier instead of having to place a zillion widgets all over the screen and having to load/save each individual data value separately.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
