### ISSUE TITLE
IE9 Search Result Updating Speed

### ISSUE THREAD

**Issue by fredmalone** [select2/select2#1867]
I noticed that in IE9 there is a delay when typing or backspacing in the search box when I have 140+ items in the select box and each item is 20+ characters in length.  In Chrome and Firefox there is no delay.  Backspacing is even worse than typing.  There is a noticable delay in refreshing the results and the search term box.

The underlying object is a select control.  Any thoughts on how to improve the searching in IE?

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
