### ISSUE TITLE
Select2 search text box focus

### ISSUE THREAD

**Issue by bachi2706** [select2/select2#1868]
Hi, How to remove search text box default focus when we click on the drop down.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.

**Comment by jmessmer** [comment]
I would like to see this fix...I just started using select2 and on mobile, I am using a simple drop down with no search and the keyboard pops up when click in the drop down.  I would like to see a ng-if instead of a ng-show when search is not enabled.....thanks

**Comment by princeofnaxos** [comment]
My workaround:

     // a fix for tablets and smartphones to prevent the keyboard from 
appearing when opening the select dropdown. Hopefully, select2 will get 
fixed for this in the future.
     if ($('body').attr('data-viewport-x') <= 1024) {
         $('.select2-input').parent().remove()
         $('.select2-focusser').remove()
     }


With best regards,

Edwin Boersma

*Fasterminds*
/A Marketing Company./
www.fasterminds.com <http://www.fasterminds.com>

Phone: +46 (709) 726431

Webpage: www.fasterminds.com <http://www.fasterminds.com>
Email: edwin.boersma@fasterminds.com <mailto:edwin.boersma@fasterminds.com>

This communication is intended for the person or entity to which it is 
addressed and may be confidential. Any review, re-transmission or 
dissemination is prohibited. If you received this transmission in error, 
please contact the sender then delete this message.

This email has been virus checked by the latest virus checking software, 
however, we advise you to carry out your own virus check as we cannot 
accept liability for any damage sustained as a result of any software 
viruses.
