### ISSUE TITLE
Anyone ever see this before? No dropdown is generated and only the spinning gif is displayed

### ISSUE THREAD

**Issue by stevewaffles** [select2/select2#1870]
I'm passing in a json string to populate the dropdown

![image](https://f.cloud.github.com/assets/2625357/1459404/6d9c6a7a-43d4-11e3-8928-6e1adcc0902f.png)

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
