### ISSUE TITLE
maximumSelectionSize is broken in 3.4.4

### ISSUE THREAD

**Issue by gregjopa** [select2/select2#1871]
The maximumSelectionSize property appears to be broken in 3.4.4. To reproduce this bug complete the following steps:
1. Go to the Maximum Selection Size demo here: http://ivaynberg.github.io/select2/index.html
2. Choose 3 options and you see the "You can only select 3 items" message as expected
3. Unselect one of the options and you still see the message "You can only select 3 items". This is the bug since the limit should not apply when only two items are selected.

This bug does not occur on 3.4.3

**Comment by jaider** [comment]
@gregjopa I wonder if there any workaround for this? I am using a legacy system and I cannot just upgrade to 3.4.5 because it may break other code.
