### ISSUE TITLE
Strange behavior with select2 and google map api

### ISSUE THREAD

**Issue by soulraven** [select2/select2#1875]
i have integrated select2 on google map UI, using "google.maps.ControlPosition",
the problem is that when i click on the select2 element, no mater what element, the google map restarts. is a strange behavior and i don't understand why.
ANyone encounter this behavior?

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
