### ISSUE TITLE
Bug: Open dropdown list snaps back to top if first several options are disabled when hovering over first enabled option

### ISSUE THREAD

**Issue by bsmithwick** [select2/select2#1879]
Steps to reproduce:
- create a dropdown list with enough disabled options at the top of the list that no enabled options are visible when the dropdown list is opened
- using a scrollwheel, scroll down the list far enough to reveal some enabled options (but at this point your mouse should still be over one of the disabled options)
- drag the mouse down until it crosses over the first enabled option

Expected behavior:
- nothing happens

Actual behavior:
- we are snapped back to the top of the list

Here's a jsfiddle demonstrating the problem:  http://jsfiddle.net/7JaZb/

It's a little tricky to reproduce, so if you need a screencast or more details, please let me know.  

This _doesn't_ appear to happen if the first option is enabled, even if enough subsequent options are disabled to push the rest of the enabled options off the bottom of the visible part of the list when it's initially opened.

Only hovering over the very first enabled option causes this to happen.  Scrolling down the list using the scrollbar, then moving your mouse up from the bottom of the list, works OK until you hit the topmost enabled option.

The net result is that it's not possible to select the topmost enabled option with the mouse when this happens.  You _can_ still get to it by typing to filter the list, so you're not totally blocked, but it's close.

**Comment by NewLIST** [comment]
See this solution. It works without hacking the control.
https://github.com/select2/select2/issues/1513

**Comment by richrout** [comment]
Is anyone still seeing the bug in 4.0.3? I am getting it with a multiple selection.
If I select something, scroll down, select something else, it appears to scroll back up to where I selected the first thing. 
@NewLIST your solution helped. I did have to modify it a bit; different methods of input (keyboard, etc) didn't always populate the events...

```js
var scrollTop;

// Scroll fix - https://github.com/select2/select2/issues/1513
this.selectElement.on("select2:selecting select2:unselecting", (event: any) => {
  if (event.params.args.originalEvent) {
    scrollTop = $(event.params.args.originalEvent.delegateTarget)
      .prop('scrollTop');
  }
}).on("select2:select select2:unselect", (event: any) => {
  if (event.params.originalEvent) {
    $(event.params.originalEvent.delegateTarget)
      .prop('scrollTop', scrollTop);
  }
});
```

**Comment by shawty** [comment]
I'm not seeing this specific bug, but I am seeing a similar thing.

If I have a select with objects say:

    {id: 1. name: "Peter"}
    {id: 2. name: "John"}
    {id: 3. name: "Paul"}
    {id: 4. name: "Mary"}

And a local class property say

    selectedName = 3;

When the form loads, it will show "Paul" in the drop down, but as soon as I change it, the bound value in the select value changes to the correctly selected value, but the text in the drop down snaps back to the first in the list "Peter"

adding a text box above the select and binding it to the same value as the select shows that the value in there persists correctly EG: 2 if I select john, but the select will always show "Peter", this also works the other way too.

If I change the value in the text box, the value changes but the select stays stuck on the first item in the list.
