### ISSUE TITLE
Handle ajax results like local results

### ISSUE THREAD

**Issue by tavlima** [select2/select2#1884]
Why not allow "options.results", in ajax setup, to return something like

```javascript
{
  results: [
    {id:1, name:'Red'},
    {id:2, name:'Blue'}],
  more:true,
  text:'name'
}
```
?

Any specific reason for not handling both data sources, as far as possible, the same way? I would not like to bend my API to my front-end, having to add another attribute just to be able to use the 'default' select2 behavior (which served me pretty well when testing with static data).

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
