### ISSUE TITLE
resolveContainerWidth ignores max-width and min-width

### ISSUE THREAD

**Issue by L-K-M** [select2/select2#1886]
To make dropdowns behave responsively on mobile devices, I often set styles like "max-width:300px;width:100%". This prevents the dropdown from becoming too wide, but also prevents it from breaking out of the viewport on mobile devices.

However, none of select2's "width" parameters work with this kind of style declaration. Looking at resolveContainerWidth(), it seems that select2 can only set the plain "width" CSS attributes.

It would be fantastic if this could be enhanced to take other width attributes into account.

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
