### ISSUE TITLE
adding possibility to hide the search box

### ISSUE THREAD

**Issue by inmarelibero** [select2/select2#189]
the possibility to hide the search box in instantiation phase could be useful, something like:

```
$(function() {
    $('#select_id').select2({
        placeholder: "Select one...",
        allowClear: true,
        showSearchBox: false
    });
});
```

for example when you have a small amount of choices to choose among, and searching is not very useful.

another situation is the one I'm in:
I want to display a tree of categories as choice list, with indentation. everything works fine also with searching, but when I filter the choices matching a subcategory I'd like to display the matching result but also the parent categories. Because this would be too complicate, I decided to hide the search box by

```
.select2-drop {
    .select2-search { display: none }
}
```

but having the possibility to disable the search box in the javascript may be a good thing

**Comment by TheWitness** [comment]
Opened select2/select2#6462 implementing this as first-class `dropdownSearch` / `selectionSearch` options (adapter composition, no new adapter classes), with tests and docs. Linking here since this issue was part of the history that shaped the design.

**Comment by TheWitness** [comment]
Opened select2/select2#6462 implementing this as first-class `dropdownSearch` / `selectionSearch` options (adapter composition, no new adapter classes), with tests and docs. Linking here since this issue was part of the history that shaped the design.
