### ISSUE TITLE
Context and full information not available in ajax results function

### ISSUE THREAD

**Issue by kageurufu** [select2/select2#1893]
$("#search-field").select2({
        ajax: {
            url: '/some/search/api',
            data: function(term, page, context) {
                //context is undefined here? Am i misreading the docs
                return {term: term}
            },
            results: function(data, page, context) {
                //same thing
                data.unshift({
                    'id': 'advanced search',
                    'url': '/search/results?term=' + context.term, //or something
                    'text': 'Advanced search results'
                });
                return {results: data};
            }
        }
    })

I'm mainly looking for a way to access the current search term in the results function, and I was thinking this context object that gets passed around would work.

If that wouldnt, feature request to add access to search term in the ajax.results function please :)

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
