### ISSUE TITLE
class enabled functionality

### ISSUE THREAD

**Issue by digitect** [select2/select2#1895]
I would like some functionality to be enabled if a certain class is added to the select element. For example: if I add the class "select2-allowClear", this specific select2 box would have allowClear set to true.
In this way it is easy to create select2 objects with slightly different behaviour.
My current solution is to set the class to "select2" (clear not allowed) or  "select2nill" (clear allowed). However, this results in a lot of overlap in the initialization code:

	// make the first option with class="placeholder" empty and set data-placeholder
	$(".select2 option.placeholder, .select2nill option.placeholder").empty();
	$(".select2, .select2nill").each(function(i, obj) {
		var title = $(obj).attr("title");
		$(obj).attr("data-placeholder", title);
	});
	$(".select2").select2({
		width : "copy",
		dropdownAutoWidth : true,
	});

	$(".select2nill").select2({
		width : "copy",
		dropdownAutoWidth : true,
		allowClear : true,
	});

Or is there any other way to add additional configuration options after the initial initialization of the select2 boxes?

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
