### ISSUE TITLE
Select2 data not updated when multi-select choice removed

### ISSUE THREAD

**Issue by timbonicus** [select2/select2#1901]
The .select2('data') function returns the data on current selections. With 3.4.4, I'm finding that data that's been removed by a .select2-search-choice-remove trigger is also returned.

The select2-search-choice elements are not removed, but faded out and remain in the DOM. The multi 'data' function returns:

```
return this.selection
     .find(".select2-search-choice")
     .map(...
```

Which picks up the non-visible removed choices. Either the removed choices should be truly removed from the DOM, or the selector for this find call needs to use ".select2-search-choice:visible".

**Comment by pedrofurtado** [comment]
@timbonicus The version 3.x is not maintained anymore. But if this bug still occurs in 4.x version, feel free to reopen the issue and report to us a JSFiddle example simulating this scenario.
