### ISSUE TITLE
select2 on delete of all the option opens the dropdown list at right hand side

### ISSUE THREAD

**Issue by thak123** [select2/select2#1905]
I am using select 2 for multiple tags selection and when i use the backspace key for deleting all the tags the option drop down is shown at the left hand side of browser and when i click on it ,it throws error "Uncaught TypeError: Cannot read property 'opts' of undefined"

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
