### ISSUE TITLE
Double selection when using rapid selection

### ISSUE THREAD

**Issue by nbuytaert1** [select2/select2#1906]
Values are selected twice when trying to select all options in the select list by holding down the enter button.

Select2 version 3.4.5
http://jsfiddle.net/RfmXv/

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
