### ISSUE TITLE
select2 ``select2-selecting`` event is NOT fired on iOS

### ISSUE THREAD

**Issue by voronianski** [select2/select2#1911]
```javascript
var $select = $('.account-select');
$select.on('select2-selecting', function (e) {
   debugger; // didn't call on ios :(
});
```

**Comment by kevin-brown** [comment]
This should be fixed in 4.0 and earlier versions of Select2.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
