### ISSUE TITLE
Unwanted behaviour: .select2-focusser get focus when selecting an option

### ISSUE THREAD

**Issue by princeofnaxos** [select2/select2#1915]
This hidden input field gets focus when selecting an option, causing the keyboard to appear on tablets and smartphones. This behaviour is not desirable. Please prevent this in a later version.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
