### ISSUE TITLE
Knockout 3.0 Binding

### ISSUE THREAD

**Issue by phinett** [select2/select2#1916]
There seems to be an issue with the custom binding for knockout 3.0, on the multi-select demo when using knockout 3.0 it says 'no matches found' twice underneath the input entry field.

How would I correct this?

**Comment by kevin-brown** [comment]
At this point this ticket is pretty old, and Knockout has reached 3.4.0. It works pretty well with Select2 4.0.

I'm going to close off this ticket because it's out of date.
