### ISSUE TITLE
Percent based width, multi-select and placeholder

### ISSUE THREAD

**Issue by conradfr** [select2/select2#192]
It seems that when a multi-value select uses a percent based width and has a placeholder, the input (.select2-input) size is miscalculated (too short), which entails :

1/ the placeholder is truncated
2/ when no choice is selected, the dropdown is only trigger when the click is done on the input. Clicking outside it triggers a "no matches found" message.

It took me two days to pin it down, I hope I'm correct.

**Comment by alenb** [comment]
Hi all,

I'm still seeing placeholder text being cut-off, here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/659296/13376679/61c4d320-de16-11e5-880f-945e4c675357.png)

Setting the `width` to `100%` for the element via CSS fixes it, but I'm not sure what repercussions this has on anything else.

**HTML:**
```
<select class="filter-commission-type" multiple="multiple"><option></option></select>
```

**JS:**
```
$search.find('.filter-commission-type').select2({
        theme: 'bootstrap',
        placeholder: 'Commission Type',
        data: data
});
```
