### ISSUE TITLE
chaging placeholder value (undefined) to be null

### ISSUE THREAD

**Issue by SebaVDP** [select2/select2#1927]
http://jsfiddle.net/2NJ8b/

When I clear the value, I receive "undefined" as value.

Is it possible to get "null" instead.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
