### ISSUE TITLE
Support filtering by <optgroup>?

### ISSUE THREAD

**Issue by crittermike** [select2/select2#193]
Is there currently a way for me to set up filtering based on the <optgroup> of the items? So, for example, if the select looks like this:

```
Dogs <- optgroup
    Lab
    Beagle
    Pug
Cats <- optgroup
    Tabby
    Scottish Fold
```

...then the user could type "Dogs" and have the three dogs visible? Is this possible with some extension of the API on my part?

**Comment by jammy-git** [comment]
Thank you to @rodnaph. Very useful matcher.
