### ISSUE TITLE
Feature request: Select2 download builder

### ISSUE THREAD

**Issue by frankie-loves-jesus** [select2/select2#1930]
### Feature request

A download builder featuring modular Select2 components so that users only need to include the bits and pieces they need, similar to the jQuery Mobile Download Builder:

http://jquerymobile.com/download-builder/

**Comment by kevin-brown** [comment]
I'm going to drop this from the 4.0 milestone, as it is not a blocker for releasing.

I'm also going to close this off for now, as we do not have any plans in the immediate future to support a custom download builder in the form that you are looking for. If anyone is interested in implementing one, we are open to pull requests. I can also reopen this ticket when the time comes around if any questions come up.
