### ISSUE TITLE
Problem when unhiding a selected li

### ISSUE THREAD

**Issue by oozrafa** [select2/select2#1931]
I have a long complicated hierarchy for my multiselect and because of this I don't want selected options to be hidden in the dropdown. But when the selected options aren't hidden (via css), then hovering over them sends the cursor back to the top of the list and I am unable to scroll through the rest of the options

```css
.select2-results .select2-selected{
	display: block;
	background: #ffff88;
}

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
