### ISSUE TITLE
Always use options.tags internally to preserve reference. 

### ISSUE THREAD

**Issue by ProLoser** [select2/select2#1932]
I know a lot of people who will pass options to the plugin and then later update the tags property of the options object. 

Instead of having:

var tags = options.tags;

You can just always refer to the options property.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
