### ISSUE TITLE
Double clicking on a component with Placeholder issue in Chrome

### ISSUE THREAD

**Issue by EyadAWork** [select2/select2#1945]
If you have a component with a placeholder defined and you double click on the placeholder in Chrome, it will select all the text and it won't unselect...  This can be seen on the demo page as well:  Try double clicking inside the one under the Placeholders section

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.

**Comment by EyadAWork** [comment]
Thanks Kevin. I think we can put this to rest as it isn't a blocking issue
