### ISSUE TITLE
Android 2.3 Keyboard not hide

### ISSUE THREAD

**Issue by wafcio** [select2/select2#1952]
I tested tags with select2 input on iOS and keyboard hide after choose tag from dropdown list. On Android 2.3 after write second tag keyboard doesn't hide, even after redirect to other page, I still see keyboard and can't turn off keyboard.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
