### ISSUE TITLE
Feature request: Callback to control which result in the drop down is initially highlighted.

### ISSUE THREAD

**Issue by percontation** [select2/select2#1955]
select2 currently uses either the current value of the element, or the first selectable result in the drop down as the result to be highlighted initially (i.e. before the user has scrolled / arrow-keyed / otherwise changed the highlight). I'd like an option to choose which result is initially highlighted.

The obvious way to implement this is via a user-supplied function that receives the same inputs as sortResults, and returns the (index of?) the result that should be initially highlighted. This function should run after sortResults, so that it may take the sorted order into account when choosing the results.

A less obvious way to implement this is allowing user functions to add a 'highlight=true' property to results. This would allow an initial highlight to be selected at the same time as querying or sorting, which may be more convenient and performant.

My use case for this is to have "best match" highlighted by default, without having to change the order of the results are presented in.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
