### ISSUE TITLE
Use select2 css without select2 function

### ISSUE THREAD

**Issue by stixpunk** [select2/select2#1960]
Is there any option to init select2 without functions?

For example this situation - I have form with inputs and selects. Most of them use select2 but for example text input to enter email have no use for select2 and I need same design for this input.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
