### ISSUE TITLE
Reset multi-value select

### ISSUE THREAD

**Issue by ghost** [select2/select2#1967]
How can I reset all selections from selectbox with multiple options when I click on reset button in form?

I try this: $('select').select2('data', null); but this works only for single-value selectbox (without multiple attribute).

**Comment by fabi0w** [comment]
```
$("#selectMultiple").select2('destroy');
$("#selectMultiple").html("<option></option>");
$("#selectMultiple").select2();	
```

**Comment by robertserch** [comment]
you saved my life :3
