### ISSUE TITLE
Overlapping with SVG z-index issues

### ISSUE THREAD

**Issue by mihailescu2m** [select2/select2#1969]
I am using select2 + charts done via SVG with dynamic tooltips. The tooltip is contained in a SVG rect, and sometimes overlaps the select2 element.
When this happens, the select2 box is on top of the tooltip. SVG elements can't be assigned z-index (Z index in SVG is defined by the order the elements appear in the document). 
Is there a way to have the tooltip on top of the select2 element? (w/o select2, the tooltip is correctly displayed on top the the HTML select element).

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
