### ISSUE TITLE
Unable to make selection of option after changing the text key

### ISSUE THREAD

**Issue by ritheshkrishnan** [select2/select2#1973]
Hello Ivayn,

I am trying to integrate Select2 into my project. However, when attempted to change the text key (as i didn't had the text property in model), It stopped me from selecting items.  Please find the code which i have used in the plunk : http://plnkr.co/edit/PUasTm6FE3mVF0fZTvO2

This code is a modified version of tutorial found.

Rithesh

**Comment by pedrofurtado** [comment]
Sorry, the `3.x` version is not maintained anymore. But feel free to fork the repo and fixes what you need.
