### ISSUE TITLE
Req. ― Web Component / Polymer widget

### ISSUE THREAD

**Issue by ghost** [select2/select2#1974]
A Polymer widget would be nice. Here's an example of such a widget:

[https://github.com/zenorocha/gplus-button](https://github.com/zenorocha/gplus-button)

It just makes it easier to place in a page. Adding the JS / CSS / and relevant init() boilerplate is time consuming.

**Comment by pironim** [comment]
I think it would be really nice to add mibamur example or just a link to the README

**Comment by kolarski** [comment]
https://github.com/kolarski/select2-wrapper

**Comment by gaurav21r** [comment]
@kevin-brown Maybe you should evaluate these and add to README? Webcomponentisation is definitely a good use case for select2.
