### ISSUE TITLE
You can't search for items by typing on Ipad when select2 pluging used on a page in an iframe

### ISSUE THREAD

**Issue by ersingencturk** [select2/select2#1976]
check this for a reproduce: http://jsfiddle.net/ersin/R49sw/

1) open above page on an ipad/iphone
2) try to use example under "the basic" by typing a state , you can't type with keyboard.

**Comment by pedrofurtado** [comment]
The version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
