### ISSUE TITLE
Update select options based on another form field via ajax

### ISSUE THREAD

**Issue by cviebrock** [select2/select2#1986]
I know this has sort of been covered in some other issues, but the solution I'm using seems a bit convoluted.

If I have, say, a group of radio buttons, I'd like to change the list of options in my Select2 dropdown based on the checked value.

```js
// initialize an "empty" dropdown

$('input[name="dropdown"]').select2({
	data: [],
	minimumResultsForSearch: -1, // Hide the search field
	formatNoMatches: function() { return 'Select the type first.' } // friendlier message
});


// look for changes on the the radios and adjust dropdown accordingly

$('input[name="type"]:radio').on('change', function(e)
{
	var type = $(this).val();
	$.post("/lookup/options", {q: type}, function(results)
	{
		$('input[name="dropdown"]').select2({
			data: function() { return results; },
			minimumResultsForSearch: -1,  // Still don't need the search field
			width: '100%', // Keep select box same width regardless of options
		});
	});
});
```

Am I doing this the Right Way&trade;?

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
