### ISSUE TITLE
Can I show the selected item at the top instead of the bottom?

### ISSUE THREAD

**Issue by styfle** [select2/select2#1989]
It appears that select2 always renders the selected item at the bottom of the viewport upon opening a dropdown with many items.

For example, "The Basics" has all the states as items. Select "New York" in both the native <select> and the select2 dropdown. Now compare when opening each one.

![select](https://f.cloud.github.com/assets/229881/1784836/1f95e35e-68d9-11e3-83f3-353852c32004.png)

![select2](https://f.cloud.github.com/assets/229881/1784837/2191a738-68d9-11e3-9a9e-1c4fbdbad67d.png)

The native select will keep the viewport the same when you open as it looked when it was closed. This is probably not possible with select2 since options might change between opening and closing. It would be nice to at least set this as a configurable option so that the selected item is always in the middle or the top.

Is this already possible? If not, consider this a feature request :+1:

**Comment by ollb** [comment]
Without the hack:

```javascript
.on('select2-open', function () {
    var viewport = $('#select2-drop .select2-results');
    if( this.selectedIndex > 0) {
        var li = viewport.children()[this.selectedIndex -1];
        viewport.scrollTop($(li).position().top + viewport.scrollTop());
    }
});
```
It would be handy to have this behaviour as an option.
