### ISSUE TITLE
how to see changelog for a previous release?

### ISSUE THREAD

**Issue by lanterndev** [select2/select2#1990]
I want to upgrade from (say) 3.4.3 to 3.4.5. At the moment, http://ivaynberg.github.io/select2/ shows me what changed from 3.4.4 to 3.4.5, but not what changed from 3.4.3 to 3.4.4, and after a few minutes of looking around, I still can't find that info. I did find https://github.com/ivaynberg/select2/issues?milestone=14&state=closed but that's not quite the same thing.

**Comment by zaantar** [comment]
I second that, a complete changelog would be very, very, very nice to have. Could we please reopen this...?

**Comment by kevin-brown** [comment]
As of Select2 4.0, the release notes are stored on GitHub.

https://github.com/select2/select2/releases

**Comment by zaantar** [comment]
Great, thanks a lot!
