### ISSUE TITLE
change event is fired first time only when using ajax with custom id

### ISSUE THREAD

**Issue by xbrabec** [select2/select2#2005]
When I load data using Ajax and also specify different id then the default id, then the change event is triggered on first selection only. Any subsequent selections do not trigger change event.

Here is an example demonstrating this behavior:

http://plnkr.co/edit/Jh1k0KxWE0JtrVupxGFv?p=preview

First select2 is using ajax and default id - works fine
Second select2 is using ajax and non default id - works one time only

Honza

**Comment by pedrofurtado** [comment]
@xbrabec The version 3.x is not maintained anymore. But if this bug still occurs in 4.x version, feel free to reopen the issue and report to us a JSFiddle example simulating this scenario.
