### ISSUE TITLE
Search support for optgroup label in a select dropdown

### ISSUE THREAD

**Issue by narayanpai** [select2/select2#2007]
Is there a way, where I can make the search to match the keywords for even the optgroup label. For E.g Finance

```
<select>
               <optgroup label="Finance">
                   <option value="NV">Nevada</option>
                   <option value="OR">Oregon</option>
                   <option value="WA">Washington</option>
               </optgroup>
</select>
```

**Comment by mikeliz89** [comment]
Something has changed.. there are no more 3 parameters for matcher in 4.0.0.beta-3 version. I can't get this to work and do not find a good example of how to use the custom matcher function now

**Comment by qcaron** [comment]
Yep, it changed to *matcher (params, data)*. You can view the code of the default matcher in [select2.js](https://github.com/select2/select2/blob/54154c3df6b7e2f59dc76b663f230f9b773397f2/dist/js/select2.js#L4488).
If anyone has a custom matcher for optgroup I am interested ;)

**Comment by kevin-brown** [comment]
Just a heads up, you can still use the old matchers, as long as you use the wrapper function for them.

Our example uses it, mainly because it's easier to work with (but less powerful).

```js
$.fn.select2.amd.require(['select2/compat/matcher'], function (oldMatcher) {
  $(".js-example-matcher-start").select2({
    matcher: oldMatcher(matchStart)
  })
});
```

Where you would replace `matchStart` with the matcher function provided by @paulcredmond.

```js
function alt (term, text, data) {
    var o = "";
    if ( "undefined"  != typeof data.element.attr("alt") ) {
        o = data.element.attr("alt");
    }
    return text.toUpperCase().indexOf(term.toUpperCase())>=0 || o.toUpperCase().indexOf(term.toUpperCase())>=0;
}

$.fn.select2.amd.require(['select2/compat/matcher'], function (oldMatcher) {
  $(".js-example-matcher-start").select2({
    matcher: oldMatcher(matchAlt)
  })
});
```

**Comment by vorujov** [comment]
According to the sample matcher function on https://select2.github.io/options.html#matcher you can use the function shown below.

    matcher: function(params, data) {
			if ($.trim(params.term) === '') {
				return data;
			}
			 
			if (
				data.text.toUpperCase().indexOf(params.term.toUpperCase()) > -1 ||
				$(data.element).attr("alt").toUpperCase().indexOf(params.term.toUpperCase()) > -1
			){
				var modifiedData = $.extend({}, data, true);

			 	return modifiedData;
			}
			 
			return null;
	   	}

**Comment by keliix06** [comment]
This was perfect for me. The one thing I got hung up on is that my optgroup also needed to have alt set, otherwise it was choking out on `$(data.element).attr("alt")`.

**Comment by BernardBoakye** [comment]
how do I implement this when I am using an array data instead of option group?

**Comment by dylanvb0** [comment]
If you are looking to search by optgroup and individual options, you can use the following based on the snippet given by @vorujov 

```
matcher: function(params, data) {
	if (typeof params.term === 'undefined'){
	    return data;
	}
	if (data.text.toUpperCase().indexOf(params.term.toUpperCase()) > -1 ||
            $(data.element).attr("alt").toUpperCase().indexOf(params.term.toUpperCase()) > -1
	 ){
	    var modifiedData = $.extend({}, data, true);
	    return modifiedData;
	 }
	 var modifiedData = $.extend(modifiedData, data, true);
	 var currChildrenArray = [];
	$.each(data.children, function(index, elem){
	        if(elem.text.toUpperCase().indexOf(params.term.toUpperCase()) > -1){
		       currChildrenArray.push(elem);
	         }
	  });
	if(currChildrenArray.length > 0){
		modifiedData.children = currChildrenArray;
		return modifiedData;
	}
	return null;
}
```

**Comment by BernardBoakye** [comment]
thanks

**Comment by mahdiafzal** [comment]
when use
`if (data.text.indexOf(params.term) > -1 || $(data.element).data("titlecompany").indexOf(params.term) > -1){ var modifiedData = $.extend({}, data, true); return modifiedData; }`
error:

> Cannot read property 'indexOf' of undefined

why!!?
