### ISSUE TITLE
selecting existing options or adding new ones dynamically

### ISSUE THREAD

**Issue by rev42** [select2/select2#201]
I would like to display a select dropdown list where people can select one value or create new ones dynamically.

The answer is almost there thanks to this issue (#1) but if I change "multiple" to "false", I cannot select existing entries anymore.
I can a JS error : Could not convert JavaScript argument arg 0 [nsIDOMDocumentFragment.appendChild]

Please see this jsfiddle : http://jsfiddle.net/pHSdP/1/

Is there a solution for this issue?

**Comment by duranmla** [comment]
:+1:

**Comment by hlashish** [comment]
Hi all

i checked both the mentioned links- : http://jsfiddle.net/pHSdP/1/, http://jsfiddle.net/pHSdP/2/

but both are not working can you please make them correct or provide me the link of correct working code

Please revert ASAP
Thanks In Advance

**Comment by rev42** [comment]
I guess this is the working version but it's deprecated as it is using Select 2.1.0 (https://jsfiddle.net/duavco7h/16/)
