### ISSUE TITLE
Multiple select shouldn't trigger multiple select2-blur event

### ISSUE THREAD

**Issue by wyuenho** [select2/select2#2011]
Under multiple select, as of version 3.4.5, the `blur` event handler is attached on the input box inside the `ul.select2-choices > li.select2-search-field`, which will emit a blur event _before any action_ that opens up the drop down menu, which results in the `select2-blur` event being triggered multiple times while the select2 widget is active and enabled.

This behavior is completely inconsistent with single select mode, which will only trigger `select2-blur` when the focus is off the entire select2 widget. Multiple select should behave the same way.

Tested under Chrome 31 and Firefox 26.

P.S. I'm not even sure how to fix this, there are no tests!

PP.S. `this.opened()` will always be false inside the blur handler. What gives?

PPP.S. There are a number of undocumented methods and events. Should probably document them?

**Comment by pedrofurtado** [comment]
The issue is related to 3.x version, but the version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
