### ISSUE TITLE
Cursor moves to second line when user press backspace to delete tag

### ISSUE THREAD

**Issue by motiprajapati** [select2/select2#2019]
This does happen for select2 having tag support. 

When user does enter long value and then tries to delete newly created tag, the cursor moves to second line.

It can be replicated on example page http://ivaynberg.github.io/select2/#tags
Steps to replicate:
1) Go to 'Tagging Support' example
2) Type 'This is very long value to test delete'
3) Press enter (this will create and select tag with above text)
4) now try to delete this tag by backspace key.
5) Issue occurs as it is in attached file.
![select2_delete_issue](https://f.cloud.github.com/assets/2048017/1862191/808f22ee-77cd-11e3-8335-0dfd16cda7b5.PNG)

**Comment by kevin-brown** [comment]
Should be fixed in 4.0.0.
