### ISSUE TITLE
Keep select list open but clear the typed filter/tag after selection

### ISSUE THREAD

**Issue by mlncn** [select2/select2#2031]
This may, i hope, be a support request.  The behavior i'm looking for is present in both its parts, just not at the same time.

I'm using tags, multiple true.  If i type something, the list pops up and filters, and if i click something from the list, what i've typed disappears.  Perfect!

We would like to keep the select list open all the time, though, and can do this by setting CloseOnSelect to False.  Great— but now when i select something from the list, what i've typed to filter is still there.

Is there some way to make what i type clear when selecting from the list, but keep the dropdown open?

Thanks greatly for any help and for the great Select2!

**Comment by sirNemanjapro** [comment]
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages.
GitHub Status — @githubstatus

**Comment by alexweissman** [comment]
I think @kevin-brown misunderstood what this issue was getting at.  There is a newer issue open at #4698, which confirms that this is indeed a bug.
