### ISSUE TITLE
suppressing 'default' events like focusout etc. from dropdown DOM elements

### ISSUE THREAD

**Issue by mrft** [select2/select2#2033]
Could you look into suppressing the 'default' events (especially the ones that are bubbling) fired from the elements that are 'somewhere else in the DOM', like the ones used to display the dropdown.

I am thinking specifically about focusout, since I've ran into a 'hard to solve' issue with this.

Let's say you want some container (maybe a form or a div) to do something when it is out-of-focus, then you could detect on any 'bubbled up' focusout event if the newly focused element is not any of the container's children. If not, you know the focus has shifted to OUTSIDE the container.
This will not work now, since any click on one of the items in the dropdown, actually (as a consequence of how select2 is implemented) will trigger this event, but the newly focused element is outside the container.
I don't think these events should be triggered when clicking inside the dropdown, since the user wants to see the whole select2 as one single element, and it should ideally behave as such, even if it isn't.

(inspired by http://marc.codewisp.com/2013/01/18/detecting-blur-child-elements-jquery/)

**Comment by Mad-Chemist** [comment]
Would love to know how to use this feature.. Can't find it documented anywhere and I'm currently running into a propagation issue.
