### ISSUE TITLE
Select2 doesn't work with Avgrund popin

### ISSUE THREAD

**Issue by lofromfar** [select2/select2#2034]
Hi there,

I try to implement select2 into a modal (Avgrund) but the element stays empty when clicking into it. I've tried to put it out of the modal and it works perfectly.
I haven't got any error message in the console... Can't figure out why.

Does someone know this issue ?
Thanks in advance...

Lo

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
