### ISSUE TITLE
Option to disable remove confirmation for tags

### ISSUE THREAD

**Issue by amyth** [select2/select2#2035]
I am looking for a way to disable the remove confirmation for tags. Currently when I am using `select2` with tags options set to `true`, I have to press the `backspace` key twice to remove a tag item, Is there a way instead of making the selection on first `backspace` press and remove on second, to simply remove the tag item on first `backspace` ?

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
