### ISSUE TITLE
Dynamically disable options or refresh the list based on changes to select.

### ISSUE THREAD

**Issue by phazei** [select2/select2#2047]
This issue seems to have broken standard select box functionality of how to deal with selected items, that are disabled.
http://jsfiddle.net/DdhL5/

I have some dynamic select lists, user can continually keep adding them.  When an option is selected in one, it's disabled in all the select boxes.

In a normal select box, say with options "red, green, blue" .  If you select "green", then disable & hide green, green is actually still selected, which is the functionality I'm looking for.

In version 3.3.2, I used JS to disable the options I wanted, and then did a  .select2("destroy" ).select2() to refresh all the select boxes.  That worked great.  But I noticed in 3.4.5&6, when I reinitialize it, even though "green" was selected, when it's initialized the selection is removed since the "green" option is disabled.  In order to maintain standard select box functionality, it should keep "green" as selected even if it doesn't appear in the list.

I was trying to see if I could resolve the issue with some type of .select2("refresh") option or something, though I couldn't seem to find that, or a way to dynamically disable an option without destroying and recreating select 2.

Any ideas on a workaround till this is fixed?  I can't even use initSelection since it's attached to a select box...

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.

**Comment by hems** [comment]
@kevin-brown calling .select2() on a list in order to update options status seems somehow inefficient on my app /=

It takes about 16ms to go through all my options, but 150ms for all the .select2() happen.

Perhaps there is a way of just enabling/disabling an specific option on a select2 item instead of going through all of them?

**Comment by AmitDubey735** [comment]
there is no way to hide option in select2 and show it again.

**Comment by coffeduong** [comment]
Hi, in my case I foreach options and use addClass and removeClass. My css class .no_show{display: none !important;}

**Comment by redayoub** [comment]
@kevin-brown are you planning to fix this soon?
