### ISSUE TITLE
Option to set dropdown height to dynamic based on available space

### ISSUE THREAD

**Issue by bostondevin** [select2/select2#2071]
I'd like the height of the dropdown to be 100% of the available space that is below it. This should be dynamic so it changes depending on the placement of the select2 or browser resolution. Adding a dropdownClass does me no good here.

**Comment by tomsommer** [comment]
+1

**Comment by JacobEvelyn** [comment]
I agree that this would be nice to handle directly from within Select2, but I just wrote a plugin that does exactly this: https://github.com/panorama-ed/maximize-select2-height

**Comment by elmart** [comment]
:+1:
