### ISSUE TITLE
bootstrap css

### ISSUE THREAD

**Issue by browner12** [select2/select2#2072]
I'm in the `select2-bootstrap.css` file and there's a bunch of selectors for `.form-control`, which is a BS3 class name. and then at the bottom there are selectors for `.control-group` which are a BS2 naming convention. To me it seems like we have half of a solution for each version of BS. This became evident to me when the styling of my default inputs in BS2 weren't really fixed to look like BS.  If people agree, I'd be happy to help clean this up, more-so on the BS2 side of things.  Maybe 2 files, `select2-bootstrap2.css` and `select2-bootstrap3.css`

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
