### ISSUE TITLE
Null body offset error

### ISSUE THREAD

**Issue by davidbeers** [select2/select2#2074]
Hello!

I'm encountering a sporadic but persistent error that has the unfortunate effect of preventing the select2-drop-mask from handling mouse events, causing the entire page to be unresponsive to the mouse. The error is due to some code that assumes that this.body().offset() is not null, which is not guaranteed:

Around line 1225 of the current select2.js we find this:

            // fix positioning when body has an offset and is not position: static
            if (this.body().css('position') !== 'static') {
                bodyOffset = this.body().offset();
                dropTop -= bodyOffset.top;
                dropLeft -= bodyOffset.left;
            }

If bodyOffset is null (the body does not have an offset) things go badly.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.

**Comment by jeetendraprasad18** [comment]
on mouse click event  The error is raised at following line:
dropTop -= bodyOffset.top; //  of

Unhandled exception at line 1162, column 17 in http://localhost:59139/Scripts/plugins/select2/select2.js
0x800a138f - JavaScript runtime error: Unable to get property 'top' of undefined or null reference

please help me how to fix this issue
