### ISSUE TITLE
Option to remove calculated widths completely

### ISSUE THREAD

**Issue by the8472** [select2/select2#208]
For responsive layouts it might be useful to simply remove the calculated widths from the elements and style the select2 elements through css files/constraining them simply through the dynamic width of the parent element.

The problem with javascript-calculated element styles is that you always have to add !important to your stylesheets to override them.

**Comment by ChazyTheBest** [comment]
What happened to this? Any way to do this? My styles from stylesheets are getting overwritten by the inline styles and I don't want to use `!important`.

**Comment by bubach** [comment]
Why is this closed?  An option is just that. An option. Should be a no brainer to let people turn off calculations and do styling without `!important`.

**Comment by alexweissman** [comment]
Is this still an issue in v4?

**Comment by the8472** [comment]
From the demo on https://select2.org/i18n#diacritics
You can see that it still uses inline styles.

![width](https://user-images.githubusercontent.com/1065730/32026816-223e5a7a-b9e6-11e7-818d-0f3da6089b5f.png)

**Comment by alexweissman** [comment]
Calculated widths are the only time that Select2 uses inline styles, right?

**Comment by the8472** [comment]
At least the only ones I have noticed and had problems with. If they can be turned off that issue would be fixed for me.

**Comment by hmelis** [comment]
If you initialise like this:
```
$(element).select2({
  width: null
});
```
you won't have the inline styles which is also much better if you want to have a stricter CSP.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.

**Comment by nad2000** [comment]
Hi guys! I ran into this issue. Is there any way to suppress the calculation of the width?

![image](https://user-images.githubusercontent.com/177266/82333303-ab3e7800-9a3a-11ea-9c36-1d9a5d7f6b44.png)
