### ISSUE TITLE
will it compatible with css Zoom in future?

### ISSUE THREAD

**Issue by Se0ng11** [select2/select2#2082]
Currently now setting zoom in css will cause the alignmen tto run off, will it be able to cater it in future?

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.

**Comment by m1chuang** [comment]
:+1:

**Comment by MrGorki** [comment]
👍

**Comment by MrGorki** [comment]
👍

**Comment by ssarnecki** [comment]
👍

**Comment by duy205711** [comment]
:+1:

**Comment by PlippiePlop** [comment]
👍

**Comment by michelleWongso** [comment]
👍
