### ISSUE TITLE
Scroll Bar not visible

### ISSUE THREAD

**Issue by mashware** [select2/select2#2085]
Sorry for my English. 
In chrome OS X does not display the inner scroll bar when there are many elements
![sin ttulo-1](https://f.cloud.github.com/assets/828091/2017123/1cf91ba6-87f2-11e3-98d4-4c2567fb7f4b.jpg)

**Comment by drevicko** [comment]
fwiw: if you start scrolling the dropdown, the scroll bar does appear on osx.

And this behaviour osx-wide, not just from the browser.
