### ISSUE TITLE
Select2 and jQueryUI

### ISSUE THREAD

**Issue by dstarh** [select2/select2#2087]
We have a site that still uses an old version of jQueryUI (1.5.2) along with jQuery 1.9.1 (we use jquery migrate 1.2.) to be able to get UI and 1.9.1 to play nicely together).  On a few pages we use select2 which works just fine.  However, we're now tasked with combining all of our javascript through a rails like (wro4j in this case) asset pipeline which creates a single javascript file to be delivered.  Before this UI 1.5.2 and select2 never co-existed however when UI 1.5.2 is loaded along side select2 the results are puzzling - http://note.io/1d8qoLi .  The select2 dropdown (ajax search mode) works however it doesn't get styled properly.  The select-search div is still off the screen and hidden.  When the page loads it looks as if it's stuck in a disabled state http://note.io/1d8roPi

Here is a jsfiddle showing the issue http://jsfiddle.net/kCnR6/1/ . If you look in the console you'll see there are no errors and it's still making the ajax calls as you type so it only appears to be presentation issues.  In our app init-selected items still work as well.   Any suggestions on how we can mitigate the apparent conflict between UI and Select2 would be appreciated.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
