### ISSUE TITLE
How to use translate ? (RESOLVED)

### ISSUE THREAD

**Issue by mbagiella** [select2/select2#2094]
Hi,
You put many language for select2, but how to use it ?
I would like to translate my select2 in french ?
select2_locale_fr
How to do it ?
Thanks for all

**Comment by hello-code** [comment]
Where is select2_locale_fr?
I am using select2 4.0.

**Comment by kevin-brown** [comment]
In 4.0 the translations are provided in `dist/18n/fr.js`.

**Comment by hello-code** [comment]
Thanks kevin-brown!
I found that not use select2.js but select2.full.js .
