### ISSUE TITLE
Close on select issue

### ISSUE THREAD

**Issue by Kopych** [select2/select2#2101]
Hello. I use this great plugin for multiple selects with ajax autocomplete. And i need to keep select box open after option selection to allow fast selection of multiple options. I created 2 jsfiddles without ajax for example. Here http://jsfiddle.net/fJ8px/6/ i can type 'op' for example and hit enter muliple times rapidly. After that i have 2 duplicate options selected 
![issue_3 4 5](https://f.cloud.github.com/assets/1318195/2085751/dac280a6-8e4a-11e3-83c3-fa76dfcf645a.png)
Besides this, value of the "test" field is '0' (duplicates selected options, not values!) and removing one of the duplicate options clears the value completely.
Here http://jsfiddle.net/WjZsz/16/ I'm using 3.4.0 version and everything is OK width closeOnSelect, but i got "Uncaught TypeError: Object [object Object] has no method 'showSearch' " in my console
![issue_3 4 0](https://f.cloud.github.com/assets/1318195/2085764/3ccfce84-8e4b-11e3-8dac-ac39b0a28a76.png)
Is there any way to fix this issue without rolling back to 3.4.0? And if rolling back is necessary, how can I get rid of 'showSearch' error?

Thank you.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
