### ISSUE TITLE
How to modify widget state

### ISSUE THREAD

**Issue by colemanw** [select2/select2#2109]
Maybe I'm just too used to jQuery UI but I can't figure out how to modify the state of this widget. For example if I want to change the placeholder text.
Calling `$(element).select2({placeholder: 'foo'})` does not work as expected (at least not as I was expecting). Instead of changing that one setting it completely reinitializes the widget. The same thing happens when you do `$(element).select2()` (all settings are lost).
Am I missing something obvious?

**Comment by kevin-brown** [comment]
Merged into https://github.com/select2/select2/issues/2830#issuecomment-74971872.
