### ISSUE TITLE
Ability to change the data without destroy/recreate a select2 input

### ISSUE THREAD

**Issue by ggregoire** [select2/select2#2115]
Hi @ivaynberg!

Is it possible to change the data of a select2 input (not the selection but the whole data array)?

```
$input.select2({
    data: myData,
    width: '300px',
    placeholder: GLO_LANG_SELECT,
    // others properties
}).on('change', function (e) {
    add(e.val);
}).on('others events' ...
```

Then

```
$input.select2().data = myNewData;
```

It will be very helpful!

**Comment by kevin-brown** [comment]
Merged into https://github.com/select2/select2/issues/2830#issuecomment-74971872.
