### ISSUE TITLE
Malformed style attribute causes successful init but with empty "options"

### ISSUE THREAD

**Issue by incredimike** [select2/select2#2119]
Ran into an issue with something like the code below.

```
<div class="subset">
<select multiple name="foo" id="foo" style="width:100max-width:400px;">
<option value="all">All</option>
<option value="second">Second</option>
...
</select>
</div>
```

As you can see, the inline style in malformed. When initializing the select2 with this inline style, the init completed "successfully" with no error message. Unfortunately, it also initialized without copying the original select (#foo) options over. I am sure the data was missing -- and not just hidden -- and I even had another developer check for me.

I can appreciate that you can't allow for all cases, but I think your (very robust) width functions need to spit out an error in a case where a valid width is not found.

Perhaps you need to check the "match" variable (around line 1823) to ensure it's actually a number.

I hope this makes sense!

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
