### ISSUE TITLE
Drop-up Select events are Lagging

### ISSUE THREAD

**Issue by pagegwood** [select2/select2#2121]
I'm using version 3.4.5 with Bootstrap3.1. Select2 dropdowns that are towards the bottom of the page and turned into dropups are very laggy. These dropups open, but it takes a second for it to acknowledge mouseover events. 

Is there a way to disable the dropup/auto positioning?

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
