### ISSUE TITLE
List opening after removing last option

### ISSUE THREAD

**Issue by toy** [select2/select2#2122]
Given there is a select2 enhanced multi select box where there is one value selected. 
When I want to resubmit form with nothing selected, I click backspace twice (to select and remove option) and tap enter.
But as the list is opened after removing last choice, tapping enter selects first option instead of submitting the form. This is not the case when there are selected options left.
Is this intentional?
Lines causing this are following: [L2626-L2628](https://github.com/ivaynberg/select2/blob/0636e42cbc5520f1b37f032a404c3e521b0eda3d/select2.js#L2626-L2628) and this can be fixed by not calling `open()` if backspace was pressed.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
