### ISSUE TITLE
IE11 Metro mode focus

### ISSUE THREAD

**Issue by Eugeny** [select2/select2#2131]
When opening a select2 on IE11 in Metro mode with touch input, virtual keyboard is triggered, which somehow causes focus to move, which in turn causes the select2 to close/disappear.

Let me know if I can do more testing to debug this issue!

**Comment by damienborgniet** [comment]
Is there a way to fix the problem when using 3.4.8 (or 3.5.2) ?

**Comment by pedrofurtado** [comment]
The issue is related to 3.x version, but the version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
