### ISSUE TITLE
Select2 Disable/Enable issue in Firefox

### ISSUE THREAD

**Issue by RahulSingh-MDS** [select2/select2#2132]
Hi, 
I am using multiselect select2 control along with knockout.js. 
The select2 remains disabled in firefox when I am using an attr {disabled} binding on it 

code:
 ```html
<select multiple="true" class="input-select2-tasks" data-bind="options: $root.approverRoles, optionsText: 'name', optionsValue:'id', selectedOptions: roleIds, select2: { lockSelection: $root.islevelRoleLocked}, event: {'change': $root.onRolesChange}, attr: {'disabled': $root.selectedTask().status() >= 2 }" disabled ></select>
```

This works fine in chrome & IE 9+ but does not enable select2 control in firefox even when $root.selectedTask().status() >= 2 returns true.Also I have tried using enable binding instead.

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.0 and I think more recent versions of 3.5.x.
