### ISSUE TITLE
Allow default when clicking on container

### ISSUE THREAD

**Issue by rupurt** [select2/select2#2139]
We're trying to customize select2 so that it generates tags with a link. To achieve this we have overridden the MultiSelect2#addSelectedChoice prototype to render an `<a href>` instead of a `<div>`.

This was relatively trivial, however we are now running into a problem where the container [prevents the default behavior of all clicks](https://github.com/ivaynberg/select2/blob/master/select2.js#L735). What is the purpose of that line? We removed it and the plugin still seems to work fine.

**Comment by pedrofurtado** [comment]
The version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
