### ISSUE TITLE
Pre-populate first "page" of results

### ISSUE THREAD

**Issue by nurikabe** [select2/select2#2144]
I was hoping to be able to do something like this:

```
$('#widget').select2({
    minimumInputLength: 0,
    data: [{'id': 1, 'text': 'blah'}, ...]
    ajax: {
        url: 'someurl'
    ...
```

Where data would specify the first "page" of results in an infinitely scrolling Select2 widget.  I assume that the data function defined in the ajax constructor overrides this data array however.

Is there any way to pre-poplate default results such that the widget doesn't "start over" with no results every time it is opened?

**Comment by pedrofurtado** [comment]
send a jsfiddle example
