### ISSUE TITLE
jquery validation plugin and select2

### ISSUE THREAD

**Issue by chillenious** [select2/select2#215]
It seems jquery validation plugin and select2 don't work together well. In particular, I was trying to make a text field turned into a multi-select required. Tried several things, including checking the selected index, but it looks like select2 changes attributes that jquery validator relies. I found a workaround, but as this seems to be a very broadly used lib, might be nice to support it.

**Comment by Godrules500** [comment]
I found a very nice way to implement this for me. Below I add the following validator default to my master page.  What this does is, for everything that contains this custom class "selectList", it forces it to validate it, while still ignoring all other hidden fields.

If you ignore all hidden fields, things that you do not want to be validated are validated, so this only validates things that contain the selectList class. Just be sure to add the class "selectList" to your select2 select list.

$.validator.setDefaults({ ignore: ":not(.selectList)" });

if ($('form').valid())
   {
       //do stuff
   }
else
{
      $("form").validate().showErrors();
}

**Comment by shefaleeComplitech** [comment]
Hi ..
I am using cofffee script for bootstrap validation.

  $("#traveler_sign_up").bootstrapValidator
    live: 'enabled'

    feedbackIcons:
      valid: 'glyphicon glyphicon-ok',
      invalid: 'glyphicon glyphicon-remove',
      validating: 'glyphicon glyphicon-refresh'

    ignore:  null
    fields:
    # Validation for email
      "traveller[first_name]":
        message: 'Please enter first name'
        validators:
          notEmpty:
            message: 'Please enter first name'

      "traveller[event_type_ids][]":
        message: 'Please select interested events'
        validators:
          notEmpty:
            message: "Please select atleast one procedure.."


And here I have used select 2 for event_type_ids . But validations are not working for select 2 . also I have tried ignore: ' ' also. But that also not worked for me.

**Comment by ketanharsodaibl** [comment]
# just need to add excluded:'disabled', in your bootstrap validator.
```
$('form').bootstrapValidator({
excluded: ':disabled',
});
```
[https://jsfiddle.net/vol7ron/Lvx6ru4j/](url)
