### ISSUE TITLE
select2 inside bootstrap.modal

### ISSUE THREAD

**Issue by n0n0n0** [select2/select2#2152]
If I placed select2 (with loading data via ajax) inside div, which after using as bootstrap.modal() then after click on select2, input, where I must type symbols for search in select2, is not active. I cant type anything in that input. On same page select2 not inside modal() div working normal. Checked in latest mozilla and chrome.

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/600.

**Comment by danirzv** [comment]
modal closes if you hold down mouse click on select2 and drag mouse to opened dropdown then release.
it did not fix with removing `tabindex`
please inform if there is any fix

**Comment by inferno7291** [comment]
@danirzv https://github.com/select2/select2/issues/3388#issuecomment-383667214

**Comment by danirzv** [comment]
> @danirzv [#3388 (comment)](https://github.com/select2/select2/issues/3388#issuecomment-383667214)

I've fixed it with using option dropdownParent as blow
`$('#FooSelect2').select2({
          dropdownParent: $('#BarModal > div > div')});`
