### ISSUE TITLE
What would be the best way to expand functionality so the "no matches fund" opens a dialog to add a new item?

### ISSUE THREAD

**Issue by stefek99** [select2/select2#2155]
Someone asked on StackOverflow: http://stackoverflow.com/questions/19715458/extend-jquery-select2-with-a-data-creation-field?rq=1

I actually have a similar requirement:
![screen shot 2014-02-28 at 17 57 55](https://f.cloud.github.com/assets/249703/2296687/e330c3d8-a0a1-11e3-8d3e-4502d388c532.png)

At this point I would like to display dialog and allow user to create new entries.

I'm pretty sure this is a fairly generic requirement - can you please:
- give me link to right place in docs: http://ivaynberg.github.io/select2/
- give me a link to a plugin that does it
- name an event that is published when mask is clicked *select2-drop-mask*

Any other suggestions - many thanks for that! :)

Michal

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
