### ISSUE TITLE
Tab Key unexpected behavior

### ISSUE THREAD

**Issue by skibulk** [select2/select2#2158]
Tabbing through form fields is an easy way to enter data using only a keyboard. Clicking on a field will open the dropdown, but tabbing into a field does not open it. Wouldn't it make sense to open the field in case the user wants to fill that field?

Also, when a no-default select2 form field is open, the top option is always selected. While clicking out of the field will not select the option, tabbing out of the select2 field will always cause an option to be selected. This behavior is inconsistent with standard html form behavior. The expected behavior after tab is to select an option only if the user has entered text or used the arrow keys to manually select an option.

**Comment by StefanKern** [comment]
what is the status on that. Here it says closed and #1698 is closed to, with thumbs up as last coments but without a solution. The current version of select doesn't currently doesn't support tab navigation.

I found this soltion with a google search: http://stackoverflow.com/questions/20989458/select2-open-dropdown-on-focus

**Comment by kevin-brown** [comment]
> and #1698 is closed to

That ticket still appears to be open.

> The current version of select doesn't currently doesn't support tab navigation.

I'm not entirely sure what you mean here, keyboard access should be fully supported in Select2.

**Comment by StefanKern** [comment]
Thanks for the quick answer. Well #1698 has closed standing on the end of the thread and this has „kevin-brown closed this on 22 Mar 2014" standing right above my comment. So I assumed both where closed.

What I want to solve is: I have an input field and underneath it, a select2 dropdown. Now when I select the input and click tab, the select2 dropdown is correctly focused, however, the select2 dropdown isn't open (only by clicking space). I just found out that this is the default html behavior, however it can be changed like in this example: http://jsfiddle.net/PpTeF/1/ . However this doesn't work with a select2 element

How can I get a select2 element to open, when it is selected with tab?

**Comment by StefanKern** [comment]
In the end I solved it with the following code:

''' javascript
            $('#XXX').select2().on("select2:close", function (e) {
                $('#NEXT').focus(); // focust the next element when the select2 is closed 
            });

            $('body').on('#container', '.select2', function () {
                $('#XXX').select2('open');   // open 
            });
'''

**Comment by kabircse** [comment]
Best way to highlighting keyboard tab event in select2().

**Comment by sirNemanjapro** [comment]
Are there any updates to this? In order to prevent default highlight of the first element, or at least an option to disable highlight on open.
