### ISSUE TITLE
Placeholder on select2 highlight won't go away

### ISSUE THREAD

**Issue by cloudybrain** [select2/select2#2171]
When you have a placeholder (either select2's attrb or html5 attrb) on your select2 control, and you double click, a highlight goes on top of it. When you try to lose focus, the highlight still doesn't go away.

I tested this on google chrome on my own site and the demo site:

http://ivaynberg.github.io/select2/

Go to placeholders

double click the dropbox repeatedly until a blue box highlights the text. Click out. Highlighted text is still there.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
