### ISSUE TITLE
Select2 dropdown inside Bootstrap dropdown: IE8+ issue

### ISSUE THREAD

**Issue by prajan55** [select2/select2#2173]
I am using both bootstrap3 and latest select2 v3.4.5 in my recent project. I keep the select2 dropdown inside the bootstrap menu. 

In IE8 & above, on clicking the select2 dropdown, it hides the bootstrap dropdown-menu at the background although I have set stopPropagation to bootstrap dropdown.

I found that this issue is only with the select 2 versions 3.3.2 & above. I tried the same code with with select 2 versions 3.3.1 and it just works fine !!

The working UI using v3.3.1:
http://jsfiddle.net/7GFS7/show

The failed UI using v3.4.5:
http://jsfiddle.net/7GFS7/1/show/

Any help appreciated.

**Comment by eSPiYa** [comment]
Can we re-open this? I updated @mkurz 's code using version 4.0.4 then it happens again: http://jsfiddle.net/a5dcwrvx/1/
