### ISSUE TITLE
Dropdown moving on Microsoft Surface Tablet

### ISSUE THREAD

**Issue by jonsprague0000** [select2/select2#2174]
On a regular Surface RT or Surface Pro tablet, when I click a dropdown that has a search box the dropdown opens and the keyboard opens.  When the keyboard opens the dropdown shifts/moves to another location on the screen.  Sometimes the dropdown only moves slightly while other times the dropdown moves significantly to a completely different area of the screen.

**Comment by kevin-brown** [comment]
Closing this off due to a lack of activity.

If this is still an issue in the upcoming 4.0 release, feel free to reply back and we can determine if this needs to be reopened.

**Comment by rezix** [comment]
Hello. 
This problem is unfortunately still at version 3.5.2 & 4.0... Windows 8 Tablet..
When the keyboard opens then changes the position of the dropdown to a different location...

![select2](https://cloud.githubusercontent.com/assets/7523882/7407864/92fb1ffc-ef16-11e4-92db-19816b427c59.JPG)
