### ISSUE TITLE
can write on input search in jquery mobile popup

### ISSUE THREAD

**Issue by akumagio** [select2/select2#2177]
HI

in jquery mobile popups... i cant write on search input.

This is the Jsfiddle example: http://jsfiddle.net/Q35Em/
Please help

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.

**Comment by backlashs** [comment]
Is there a fix for this issue? Still present in current 4.0.0 build

**Comment by pedrofurtado** [comment]
@backlashs PRs are welcome, if you have some workaround :+1:
