### ISSUE TITLE
Select2 issue with Knockout 3.1

### ISSUE THREAD

**Issue by norbiu** [select2/select2#2180]
I noticed that when I use KO's 'valueAllowUnset: true' with Select2, the default value is not visible in the select box. However, when I click on the select, the correct value is highlighted.

http://jsfiddle.net/LgXcb/

Try removing ', select2: {}' from the above fiddle to see how it should work.

Any ideas on what's causing this issue? Does it have to do with the select2 custom binding function I'm using for Knockout?

**Comment by kevin-brown** [comment]
At this point this ticket is pretty old, and Knockout has reached 3.4.0. It works pretty well with Select2 4.0.

I'm going to close off this ticket because it's out of date.

**Comment by atilkan** [comment]
> At this point this ticket is pretty old, and Knockout has reached 3.4.0. It works pretty well with Select2 4.0.
> 
> I'm going to close off this ticket because it's out of date.

Nope, I have these versions and it still doesn't work.
