### ISSUE TITLE
Bug chrome scroll with multiselect and formatResult

### ISSUE THREAD

**Issue by Jeremias-Tecnom** [select2/select2#2182]
Hi,
I have a selec 2 with multiselect and formatResult.
It works ok, but when the page loads, the select is at the bottom of the page, and when I click it , a huge margin appears between the input and the results.
Here is the image:

![image](https://f.cloud.github.com/assets/6661155/2399549/bd220a32-a9ff-11e3-8dee-4b8cbed1f0b3.png)

When I scroll down the page it works ok.

As what ive seen, in single selects there is a fix inside select2 code, but there is no fix for multiselect option.

Thanks in advance.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
