### ISSUE TITLE
Submit after pressing Enter

### ISSUE THREAD

**Issue by ETuds** [select2/select2#2185]
Hi, i just wanted to know how can i make the form submit upon pressing enter in my key board, i just made a form that has select2 (multi select|) for my search box and when i press enter it just selects the highlighted value and when i press enter again it just search again. i wanted to submit it after selecting. 

i also limit the maximum selection to 1,

Thanks

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/1456.
