### ISSUE TITLE
destroy broken on selections with length > 1

### ISSUE THREAD

**Issue by AlexGalays** [select2/select2#2187]
destroy() will only work for the first element of a JQuery selection:

http://jsfiddle.net/LUsMb/2404/

I believe because destroy() returns nothing (undefined) and the each loop ends abruptly.

Cheers.

**Comment by mh-nichts** [comment]
I'm having this exact same issue (only the first select of the list is destroyed) with v4.0.0.

Here is a test case (destroy after 3 seconds) : 
http://codepen.io/mh-nichts/pen/JdXbdm

Tested on Windows 7 : Firefox 37, Chrome 42, IE 11.

**Comment by kevin-brown** [comment]
@mh-nichts Can you create a new ticket for 4.0 so we can get it fixed?

Thanks.
