### ISSUE TITLE
Jumps to parent item when mousing over disabled items

### ISSUE THREAD

**Issue by ovalek** [select2/select2#2189]
Similar problem to #733.
http://jsfiddle.net/4P4BZ/3/
Items at the bottom are disabled and the last item is enabled.

Versions: select2 3.4.5
jQuery 1.10.1, 1.10.2
Mozilla Firefox 27.0.1
Google Chrome 33.0.1750.149
system Linux 3.13.6-200.fc20.x86_64.

**Comment by BorisKozo** [comment]
@kevin-brown Is there going to be a fix for this in the 3.x line? I am having the same issue and I am not going to upgrade to 4.x soon. 

It seems that many have that issue, could you please shed some light on when this behavior is needed (https://github.com/select2/select2/blob/stable/3.5/select2.js#L1697)?

**Comment by abhilashlr** [comment]
Has this been fixed in any of the select-2 **3.5.x** versions? Tried 3.5.2 and 3.5.4 - it doesn't seem to work.
