### ISSUE TITLE
Difference in trailing whitespace handling between version 3.3.2 and 3.4.5 

### ISSUE THREAD

**Issue by petedmarsh** [select2/select2#2190]
I'm using select2 with the `tags` and `multiple` and `separator` options. I explicitly want to be able to add tags that have trailing whitespace. 

Have a look at the following JSFiddles:

3.3.2:

http://jsfiddle.net/GLcvb/1/

3.4.5:

http://jsfiddle.net/Bf6XB/1/

In both cases when you remove the "A" and "B" tags you'll see `"A "` and `"B "` is the value of the `event.removed.text` attribute . Now, add a new tag: `"C "`. If you remove this tag then select2 3.3.2 will include the trailing space in `event.removed.text` whereas select2 3.4.5 will not (i.e. 3.3.2 will have `"C "` and 3.4.5 will have `"C"`).

Ideally I would like select2 3.4.5 to behave as 3.3.2 in this case - is it a true bug and not a deliberate change in behaviour?

**Comment by kevin-brown** [comment]
This should be fixed in 3.5.2.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
