### ISSUE TITLE
Reacting to external is not working.

### ISSUE THREAD

**Issue by RoelDeveloper** [select2/select2#2192]
Hello,

Not sure if this is because I don't have skills enough, but for some reason the following thing doesnt work;

		$.ajax({
			type: "POST",
			url: "request.php",
			data: data + postData,
			datatype: 'json',
			async: false,
			success: function(dataArray){ 
					$(".select2").val(dataArray).trigger("change");
				}
		});

The code is running succesful, but the tags are not getting rendered as selected, the inputbox becomes empty, the value of dataArray is = ["19","20","21","22"]
When I put this value ( ["19","20","21","22"] ) as plain text inside the val() it works correctly, but if I put the array inside of it , it doesnt work for some reason..
Someone know how to fix this?

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.
