### ISSUE TITLE
matcher parameters

### ISSUE THREAD

**Issue by travislward** [select2/select2#2201]
current implementation:
matcher: function(term, text) {...  },

please change to 
matcher: function(term, item) {
  ...
 // call text(item) inside matcher.
 // will require change to text function like...
 // text = function (item) { return text = isObject ? this.text : this; };
}

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
