### ISSUE TITLE
Can i use delegate() instead of on() to handle events

### ISSUE THREAD

**Issue by eslam-mahmoud** [select2/select2#2209]
I'm using jQuery 1.6 and i don't have on() function to handle events when i tried to handle the events using delegate() nothing happens

$("#selectAddress").select2({
      placeholder: "Search by: City",
      allowClear: true
});
$( "body" ).delegate( "#selectAddress", "select2-opening", function() {
      console.log("opening"); 
});

Thanks.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.

**Comment by Lindsayanng** [comment]
Would need this as well
