### ISSUE TITLE
Init dropdown with a set of pre-fetched options?

### ISSUE THREAD

**Issue by tflorac** [select2/select2#2212]
Hi,
I use Select2 on an hidden input, using the "query" attribute to fetch items matching entered text. Everything works fine.
But when the user clicks on the dropdown button, I need to immediately display a set of suggestions, based on currently selected value, before he starts to type any character; when required characters count (defined by "minimumInputLength" option) will have been entered, new fetched items will replace these suggestions normally...
What's the way to handle such use case?

Best regards,
Thierry

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
