### ISSUE TITLE
Triggering ajax lookup after enter key, not minimum length!

### ISSUE THREAD

**Issue by mkdizajn** [select2/select2#2213]
I have ajax service that returns results to control, but I can't seem to find solution to trigger ajax search differently.

Now there is a setting to some minimumInputLength, but I need to circumvent that event and only if user enters some custom length text + enter key to send ajax request..

I don't know if that is possible to acheve with select2 and if there is some code snippet that I can check ..

cheers,

**Comment by kevin-brown** [comment]
Closing this off due to a lack of activity.

If this is still an issue in the upcoming 4.0 release, feel free to reply back and we can determine if this needs to be reopened.

**Comment by jayantgoyal15** [comment]
hi All,
I'm facing the same issue. is it resolved? if yes, is there some code snippet that I can check.

Thanks..
