### ISSUE TITLE
Dropdown auto width doesn't detect right window edge

### ISSUE THREAD

**Issue by MonkeyJamboree** [select2/select2#2214]
Hello. When a select or input is near the right side and dropdownAutoWidth is set to true, select2 does not account for the window's width.

A JSFiddle reproducing the issue: http://jsfiddle.net/JELEF/

Hopefully this is an easy(ish) fix.

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.

If it is not fixed, please add a :+1: to the ticket to bring it to our attention. Please also include an example that we can test to verify that it is not actually working.

**Comment by oliveiracdz** [comment]
It seems not working in 4.0.3 too. =/
Here is the updated JSFiddle: http://jsfiddle.net/401dmrhk/
Any workaround?

Thanks!

**Comment by capqueen** [comment]
not working too
