### ISSUE TITLE
Input history overlaps select2

### ISSUE THREAD

**Issue by sebastianwestberg** [select2/select2#2217]
![select2-bug](https://cloud.githubusercontent.com/assets/4223277/2551898/97c59e20-b693-11e3-992e-d90f3cdc968d.jpg)

Please see this jsbin: http://jsbin.com/koveguka/1/edit
You need to have input history for the name value "search" for it to be reproduced in this example.

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
