### ISSUE TITLE
tabindex chain is broken when selecting a value with keyboard

### ISSUE THREAD

**Issue by sebdavid** [select2/select2#2223]
Hello,

The following problem occurs with 3.4.6, it was OK with 3.4.5. Maybe is it linked to "#2176 Fix Focus war with modals" ?

I have a form with some input, and a select in the middle. No tabindex attribute are specified on the elements. By using the "Enter" or "tab" key, I select a value in the select element. Then it seems that tabindex is reset, because the following element in the form doesn't get the focus : the tabindex chain is broken. This also occurs when setting tabindex attributes on the form elements.

With 3.4.5, it was fine : when  the value was selected in the select with the Enter key (or tab), then taping tab set the focus to the next form element.

Thanks for your answers,
Sébastien.

**Comment by userrails** [comment]
I am still having same issue :(
