### ISSUE TITLE
Select Widths for Bootstrap Form Layouts

### ISSUE THREAD

**Issue by natashawylie** [select2/select2#2240]
Hi there,

I'm using bootstrap 3 and wish to use the Select2 basic select field. However, the select field doesn't match the form-group column width e.g.

```
<div class="form-group">
    <label for="region" class="col-sm-3 control-label">Company Region</label>
    <div class="col-sm-9">
        <select id="region">
            <option value="1">First Region</option>
            <option value="2">Another Region</option>
            <option value="3">Last Region</option>
    </select>
    </div>
</div>
```

So I've included the following (along with the bootstrap css and js):

```
<link href="/css/select2.css" rel="stylesheet"/>
<link href="/css/select2-bootstrap.css" rel="stylesheet"/>
<script src="/js/select2.min.js"></script>
```

I've had a look at your documentation and the only reference you have made to responsive design is for the percentage widths (http://ivaynberg.github.io/select2/#responsive). This means that I would have to work out the percentage widths for each col width, I would have expected this to be included as part of the select2-bootstrap.css.

If you could let me know whether this will be resolved soon that would be great otherwise I'm going to have to spend some time doing it myself.

Many thanks,

Natasha

**Comment by nsbassi** [comment]
Initialising it with `width: '100%'` will let it pick width of the parent element and maintain responsiveness too.
