### ISSUE TITLE
jQuery dialog button event issue on .select2-results click using formatNoMatches

### ISSUE THREAD

**Issue by ghost** [select2/select2#2242]
Gents,

I run under an issue with asp.net button postback inside a user control outside of updatepanel called using _doPostback function which works on second click only.

Before posting this question I tried different ways but without success, the last one is to define the dialog by using:

``` js
$('.select2-results').click(function () {
           var dlg = $('#NewUserPanel').dialog({
                modal: true,
                width: 320,
                autoOpen: true,
                minHeight: 10,
                minWidth: 10,
                buttons: {
                    ok: function () {
                        $('#btnAddNew').click();
                    }
                },
                open: function (type, data) { $(this).parent().appendTo($('form'));}
           });
                      return false;
        })
```

**Comment by pedrofurtado** [comment]
The issue is related to 3.x version, but the version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
