### ISSUE TITLE
allowclear 'x' Not selectable on Mobile

### ISSUE THREAD

**Issue by kimardenmiller** [select2/select2#2248]
Can't select the 'x' on mobile. That said, the object is quite small:

![image](https://cloud.githubusercontent.com/assets/2165336/2636771/850891a2-be95-11e3-8b39-018f9bf08954.png)

I seem to be able to change some of the CSS, but not the size of the object.
```
select2-container {
  .select2-choice {
       . . .
    abbr {
      right: 13px;
    }
    @media (max-width: $grid-float-breakpoint-max) {
      abbr {
          right: 5px;
        }
    }
}
```
Any way to enlarge the 'x' or insert different content that one can control?

**Comment by kevin-brown** [comment]
This issue was definitely fixed in Select2 4.0, as we added a much larger hit box for the "clear" icon to accommodate touch screens,
