### ISSUE TITLE
Ability to reload a select2 dropdown

### ISSUE THREAD

**Issue by KieranP** [select2/select2#2250]
Use case:

``` javascript
$('#country').change(function() {
  $('#region').replace(....); // updates regions based on country
  $('#region').select2('reload');
});
```

Currently, I need to `select('destroy')` and then reinitialise the selector with the same options, which works, but this gets a bit messy (having two calls all around the place).

(ideally it would detect and reload changes automatically, but the above would work find instead)

**Comment by CTAPbIuMABP** [comment]
imagine i have two selects of the same type

```html
<select id="s2">
<option value="en">English</option>
<option value="fr">French</option>
<option value="de">German</option>
<select>

<select id="s2">
<option value="en">English</option>
<option value="fr">French</option>
<option value="de">German</option>
<select>
```

it would be great to have ability to do like this

```js
var s1 = $("#s1"), s2 = $("#s2");

function refresh (e) {
    s2.find("option")
        .filter(function(){ return this.value === e.params.data.id; }).prop({disabled:true}).end()
        .filter(":enabled:first").prop({selected:true}).end()
    .end()
    .select2("refresh");
}

s2.select2();
s1.select2()
    .on("select2:select", refresh)
    .on("select2:init", refresh);
```

**Comment by kybishop** [comment]
@CTAPbIuMABP as Kevin Brown said, you can already do this via `$('#my-select).trigger('change');`

**Comment by sashaaro** [comment]
`
var select2Instance = $select.data('select2');
var resetOptions = select2Instance.options.options;
$select.select2('destroy').select2(resetOptions)
`

**Comment by fuadJustMe** [comment]
My select return to normal select(not a combo box) after I add $('#my-select).trigger('change'); to the code,

**Comment by 3lue** [comment]
Any update? I'm still experiencing this issue and need the fix.

**Comment by petrosmm** [comment]
> ```
> var select2Instance = $select.data('select2');
> var resetOptions = select2Instance.options.options;
> $select.select2('destroy').select2(resetOptions)
> ```
I wrote a similar one based on @sashaaro 's, if you have multiple select2's on the same page... 
```
    $("select.select2").each(function () {
        var self = $(this);
        var select2Instance = self.data("select2");
        var resetOptions = select2Instance.options.options;
        self.select2("destroy")
            .select2(resetOptions);
    });
```
