### ISSUE TITLE
3.4.6 - Auto generated ids have an extra backslash

### ISSUE THREAD

**Issue by SalmanAwan** [select2/select2#2251]
Auto generated ids have an extra backslash in them if original select has a dash '-' in its id.

the regular expression used in replace between version 3.4.5 and 3.4.6 differs by addition of \\- which seem to be adding extra slash in ids i.e.

id="s2id_currency\\-select"
 Vs.
id="s2id_currency-select"

wouldn't be a problem if our automated tests were not relying on these ids, and this version is required to incorporate a recent fix.

**Comment by kevin-brown** [comment]
I'm going to close this off because this was fixed in Select2 4.0.0 and it's fully escaped in 4.0.2.
