### ISSUE TITLE
Clicking submit button on form before tag registered clears input

### ISSUE THREAD

**Issue by noctivityinc** [select2/select2#2262]
We are having a major user problem.  We use select2 for autocomplete or email addresses.  Many of our users are entering email addresses that arent in their directory.  After they enter the email address they do not click tab or enter or trigger the blur event, they simply try to click the SUBMIT button on the form.

Unfortunately this triggers the close event which, for some reason, is clearing the input leading to massive confusion.  How can we change the close event to add any current input (for tags) as a tag instead of clearing it?

**Comment by kevin-brown** [comment]
Closing this off due to a lack of activity.

If this is still an issue in the upcoming 4.0 release, feel free to reply back and we can determine if this needs to be reopened.
