### ISSUE TITLE
loading selected values in lazy-appearing (lazy Loading)

### ISSUE THREAD

**Issue by Insira** [select2/select2#2263]
Hi all,

I am using the select2 combo with lazy-appearing (http://ivaynberg.github.io/select2/#infinite). I have implemented the initSelection to populate the id and text values of the initial item. This works fine when my selected value is available in the 1st page of the combo results. But consider a scenario where the current selected value is not available in the 1st page of the combo results. how to do load the remainder of the data (combo results) so that when i expand the combo the value appears selected in the combo results.

Thank you
Insira

**Comment by kevin-brown** [comment]
Select2 4.0.0 handles this now automatically based on matching ids or the selected property.
