### ISSUE TITLE
closeOnSelect = false does not work when minimumInputLength > 0

### ISSUE THREAD

**Issue by shiznit013** [select2/select2#2264]
The dropdown will close on select.  I have created a [jsfiddle](http://jsfiddle.net/7Nt7U/1/) to demonstrate the behavior.

This worked in 3.4.5.  I believe (although have not confirmed), that this may have been broken by pull request https://github.com/ivaynberg/select2/pull/1940

**Comment by AtomStar** [comment]
This does not work in v4.0 beta2. @snichini fix is for v3.5. I did the following hack on lines 3384-3388 in v4, which seems to work:
``` javascript      
       Dropdown.prototype._onSelect = function () {
            if (this.options.options.closeOnSelect == false)
                return;
            this.trigger('close');
        };
```

**Comment by kevin-brown** [comment]
@AtomStar If you want to roll that up into a decorator, it'd save me the time of adding it back myself. It shouldn't take too long and you can use https://github.com/select2/select2/pull/2914 as an example for adding in the option.

I was planning on adding it back for 4.0, but haven't had the time.

**Comment by amamf** [comment]
The above fix provided by snichini doesn't work for me (3.5.2). It works for the first item only, when I select the second item the search results get closed. I came up with a different solution that works for me. The idea is not to update search results if they shouldn't be closed on select: 
```javascript
           // keep track of the search's value before it gets cleared
            this.nextSearchTerm = this.opts.nextSearchTerm(data, this.search.val());

            this.clearSearch();

            if (this.select || !this.opts.closeOnSelect) this.postprocessResults(data, false, this.opts.closeOnSelect===true);

            if (this.opts.closeOnSelect) {
                this.updateResults();
                this.close();
                this.search.width(10);
            } else { ...
```

**Comment by AlexRocks** [comment]
If you do not want to hack the select2 3.5 code then following work ('select2-selecting' event launch before close event so we can manually close/open):
`$("#category_id").on("select2-selecting", function(e) {
                e.preventDefault();
//This one upload from remote server some additional info
                    uploadSubCats(e.val).then(function(res) {
//After that we can make decision close or not close dropdown
                        if (res.status == "ok") {
                            if (res.data === 0) {
                                $('#category_id').select2("val", val);
                                $('#category_id').select2("close");                                
                            } else {
                                $('#category_id').select2({"data": res.data});
                                $('#category_id').select2("open");
                            }
                        }
                    });                                    
            });`

**Comment by joergrech** [comment]
@AlexRocks Can you clarify what "uploadSubCats" is doing? Your code itself is not working as this method is missing.

**Comment by spycom** [comment]
@AlexRocks Thanks a lot, your code helped me to finish this fix
`$("#object-select").on("select2-selecting", function(e) {
                e.preventDefault();
                var target = $(this);
                handleSelection(e, target);
            });

            function handleSelection(e, target){
                
                e.preventDefault();
                
                var data = target.select2('data');
                data.push({
                            'id': e.object.id,
                            'text': e.object.text
                        });

                target.select2('data', data);
                target.select2("open");
            } `

**Comment by burakcakirel** [comment]
Thank you @spycom 
Our legacy code is still using select2 v3.x so your piece of code saved us. Also, I want to add one line to your fix.
After that:
`target.select2("open");`
Put this line:
`target.select2("positionDropdown");`
With doing this, the result dropdown's position will adjust as the input's position

**Comment by pedrofurtado** [comment]
The issue is related to 3.x version, but the version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
