### ISSUE TITLE
Emulate the width logic of a native select exactly

### ISSUE THREAD

**Issue by rulatir** [select2/select2#2269]
A native dropdown single select without specified width automatically assumes such width that the widest option's text can be displayed without truncation, and the widget's width doesn't change regardless of which option is currently selected. In particular, the widget sizes itself to be able to completely show the widest option even if that option is not initially selected.

For select2 to be a good, minimum-effort drop-in replacement for a native select, it should do **exactly** the same when instantiated without any width-related options on a dropdown single select without specified width.

Currently select2 just assumes the width of the currently selected option.

**Comment by kevin-brown** [comment]
Closing this off due to a lack of activity.

If this is still an issue in the upcoming 4.0 release, feel free to reply back and we can determine if this needs to be reopened.
