### ISSUE TITLE
Adding new selections in between existing selections

### ISSUE THREAD

**Issue by dandv** [select2/select2#2283]
Is there a way to add a tag between two existing tags? The [multi-select demo](http://ivaynberg.github.io/select2/#multi) only allows adding tags after the already entered tags.

StackOverflow lets one add tags anywhere among the existing tags:

![image](https://cloud.githubusercontent.com/assets/33569/2701360/c36d6c26-c41f-11e3-93cd-b793d67bafca.png)

Tag order may be significant, e.g. for assigning decreasing weights to tags - the tag that was entered first is the most important, the next one is less important, and so on.

**Comment by alexweissman** [comment]
The author of this issue appears to have confused "tagging" with "multi-select".

At any rate, this is now being discussed more extensively in #3106.
