### ISSUE TITLE
Enhancement: Use CSS Arrows for Easier Theming

### ISSUE THREAD

**Issue by justbeez** [select2/select2#2294]
We regularly find ourselves having to create additional images to handle things like color changes to the default theme (for example, to indicate validation errors or add hover styles for consistency with other custom elements).

Changing the CSS to use `:before` or `:after` pseudo elements and CSS arrows/triangles would make the plugin easier to skin, and could eliminate some of the extra elements in the current markup.  For example this could be done like so (after removing the current styles on `.select2-arrow b`):

```
.select2-container .select2-choice .select2-arrow:before {
    content: "";
    position: absolute;
    top: 50%;
    left: 50%;
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 5px 4px 0 4px;
    border-color: #888888 transparent transparent transparent;
    margin-left: -4px;
    margin-top: -2px;
}
```

And then a hover state would be as simple as setting the following:

```
.select2-container:hover .select2-arrow:before {
    border-color: #333333 transparent transparent transparent;
}
```

If there's any aversion to the pseudo elements, the same could be done without them (using the existing `b` tag)—they're just a nice way of removing non-semantic markup.

**Comment by kevin-brown** [comment]
This has been done in Select2 4.0.

**Comment by wx2228** [comment]
so how can i remove the original arrow element? @kevin-brown
