### ISSUE TITLE
Dropdown Menu Doesn't Stay Open, Should Open Up, Not Down

### ISSUE THREAD

**Issue by jackerman09** [select2/select2#2299]
When the bottom of the options box extends below the browser window, the options block does not stay open when clicked unless your mouse happens to be hovering over the box's scroll bar. If you click in the middle of the dropdown menu, it just snaps back up immediately, selecting whatever your house happens to have been hovering over.

You can see what I am talking about here: http://what-key-am-i-in.herokuapp.com/ and click on the 'fretBoard' link, then try to change the dropdown showing keys (lower left dropdown menu) with the bottom of your browser window only slightly below where the menu is.

Shouldn't the menu open upwards instead? Thanks!

**Comment by CaptainMisery** [comment]
I know this is a closed issue, but your fix didn't actually fix it for me. It worked fine in IE8+, but not in Chrome or Firefox. I had to add some browser detection and update a few lines in the positionDropdown function:
if (above) {
    if (navigator.browserInfo.browser != 'IE' && navigator.browserInfo.browser != 'MSIE')
        dropTop = offset.top - dropHeight - 45;
    else
        dropTop = offset.top - dropHeight;
    this.container.addClass("select2-drop-above");
    $dropdown.addClass("select2-drop-above");
}

**Comment by townegr** [comment]
Now that we're on version ~> 4.0.1, have we arrived to a solution for this issue? Should I create a new issue since this appears to be recurring.

**Comment by danfox** [comment]
I have the same problem on chrome, the dropdown opens above the selector and disappears immediately...

**Comment by jhardin293** [comment]
Having the same issue on all browsers when the browser window is shorter than the browser height.

**Comment by jhardin293** [comment]
I found the solution to my problem. I set margin-top to 50px on the .select2-container  
Removing the margin allowed the dropdown to stay open.
