### ISSUE TITLE
Optgroup disabled property is not supported

### ISSUE THREAD

**Issue by Knordy** [select2/select2#2306]
When an 'optgroup' is disabled it should also disable all the 'option' in that 'optgroup' (http://www.w3.org/wiki/HTML/Elements/optgroup).

Currently this is not supported in Select2 version 3.4.6. A disabled 'optgroup' looks like an enabled 'optgroup' and options in a disabled 'optgroup' can still be selected:

http://jsfiddle.net/swMBL/

**Comment by Knordy** [comment]
I've updated the jsfiddle, because the referenced js/css weren't available anymore. Also it's still not working in version 3.5.2. As you can see in the fiddle, United Kingdom is not selectable because this option is disabled. But the options below the disabled optgroup Oceania are still selectable, but shouldn't be.

New Fiddle for version 3.4.6: http://jsfiddle.net/swMBL/1/
New fiddle for version 3.5.2: http://jsfiddle.net/swMBL/2/

**Comment by kevin-brown** [comment]
This appears to still be an issue in 4.0: http://jsfiddle.net/swMBL/4/

**Comment by kevin-brown** [comment]
I'm going to merge this ticket into https://github.com/select2/select2/issues/3347.
