### ISSUE TITLE
Select2 does not respond to .focus() or clicking the label

### ISSUE THREAD

**Issue by clime** [select2/select2#2311]
http://jsfiddle.net/p8eTe/2/. Input gets no focus when clicking on label and it even jumps to the top of page (cannot be seen in the fiddle atm).

Related to: https://github.com/ivaynberg/select2/issues/198

**Comment by kquinbar** [comment]
I am experiencing this same issue where $("#select2Input").select2("focus"); stopped working once I tried upgrading to v4 of select2. will this get fixed in the next revision? seems like its kind of an important piece of functionality. the extension code someone showed above didn't seem to work for me, but maybe I implemented it wrong.

**Comment by ncolomer** [comment]
Please add this feature :+1:

**Comment by King2500** [comment]
:+1:

**Comment by babwar** [comment]
With v4 yout can just do :

$('.select2').select2({}).focus(function () { $(this).select2('open'); });

**Comment by RobertDiebels** [comment]
@babwar I tried your suggestion in v4. But I get a "query function not defined" error.

**Comment by billbarsch** [comment]
I try this:

$('.select2').select2({}).focus(function () { $(this).select2('open'); });

and now $("myselect2").focus(); is working
but I think it can be a default feature no???

**Comment by dcruz** [comment]
+1 for core behavior.

It impacts negatively the usability and accessibility of the select.
That's a interaction regression comparing to baseline <select> and Select2 should provide strictly better interaction.

**Comment by huoxito** [comment]
So far this has been working for me:

```js
$('select').addClass('select2-offscreen').show()
```

it pretty much reverts https://github.com/select2/select2/commit/db7cd1b373f9a2a743a68ce32cc59dc8fc899eb8

**Comment by mgomma** [comment]
still exit even with version 4

**Comment by marquez20** [comment]
(remove tabindex="-1" from modal) Bootstrap
`
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Panel</h3>
  </div>
  <div class="modal-body" style="max-height: 800px">
`
To 

`
<div id="myModal" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Panel</h3>
  </div>
  <div class="modal-body" style="max-height: 800px">
`

**Comment by marquez20** [comment]
(remove tabindex="-1" from modal) bootstrap

`<div id="myModal" class="modal hide fade" tabindex="-1"`
to
`<div id="myModal" class="modal hide fade" role="dialog"`

**Comment by Pablo-Araya** [comment]
I'm getting the same error
Input gets no focus when clicking select2 and it even jumps to the top of page.....

I have read a lot of info but even that I tried lot of code fixes, the problem persists

**Comment by mjlabe** [comment]
I got it to work with this:

```
$('.my_class').click(function () {
    $('.select2-search__field').focus()
});
```

**Comment by Abhinanddas** [comment]
`$("#my_id").select2('open');`

This worked for me.

**Comment by friek108** [comment]
I had to do something like this.. 

    setTimeout(function(){
        $("#mySelect").select2('open');
        $('.select2-search__field').focus();
    },0); // if 0 doesn't work, try a bigger value

**Comment by Cartman34** [comment]
On my project, with Select2 4.1.0-rc.0 from npm, I am also unable to get the input focused.
Even by console, but this is working with any other fields.

By removing many attributes, I am able to get focused via console if I click anywhere on the dropdown before but I am unable to get it working in a programmatic way and I didn't find any reason.

I am testing on Chrome and I am using a botostrap theme. (but select2 component is directly in page, **not** in a modal)

**Comment by iprastha** [comment]
It seems jQuery 3.6.0 broke the autofocus, testing it with 3.5.1 works

> On my project, with Select2 4.1.0-rc.0 from npm, I am also unable to get the input focused.
> Even by console, but this is working with any other fields.
> 
> By removing many attributes, I am able to get focused via console if I click anywhere on the dropdown before but I am unable to get it working in a programmatic way and I didn't find any reason.
> 
> I am testing on Chrome and I am using a botostrap theme. (but select2 component is directly in page, **not** in a modal)

**Comment by tiaan-lg** [comment]
Is there any update on how to fix this, without reverting to jQuery 3.5.1 ?

**Comment by AYColumbia** [comment]
I'm having the same issue.  No matter what I try, once the dropdown is open, whether manually or programmatically, I can't get focus in the input field so the user can type in the search.  This a big problem that needs to be resolved.  I have 4.0.13 and it does have "self.$search.trigger('focus');" in the code but it doesn't work.  Am using jQuery 3.6.0 and none of the above suggestions have worked for me.

**Comment by mayconpaivac** [comment]
i'm using by id and it has worked well for me


```
window.jQuery(document).on('select2:open', e => {
  const id = e.target.id;
  const target = document.querySelector(`[aria-controls=select2-${id}-results]`);
  target.focus();
});
```
