### ISSUE TITLE
positive minimumResultsForSeach does not apply when there is zero or only one option with empty value

### ISSUE THREAD

**Issue by clime** [select2/select2#2312]
http://jsfiddle.net/7gK2h/2/

markup:
```
<select>
    <option></option>
</select>
```

js:
```
$('select').select2({
    minimumResultsForSearch: 10
});
```

Searchbar is shown in this case.

**Comment by kevin-brown** [comment]
Closing this off due to a lack of activity.

If this is still an issue in the upcoming 4.0 release, feel free to reply back and we can determine if this needs to be reopened.
