### ISSUE TITLE
Typehead is not working with a Ajax requested data (tags). Unable to create new tags.

### ISSUE THREAD

**Issue by sharuman** [select2/select2#2321]
Hi people. This is my first comment on this great project. Forgive me if I made any mistake :)
I successfully made a connection to my DB in order to load tags from it through an Ajax connection. Here is the code:

``` js
$("#e12").select2({
    //tags:[{id:0,text:'Apricot'},{id:1,text:'Banana'},{id:2,text:'Cherry'},{id:3,text:'Dates'},{id:4,text:'Grape'}],
    tags: true,
    maximumSelectionSize: 9,
    tokenSeparators: [",", " "],
    ajax: {
                url: "tags-populate.php",
                dataType: 'json',
                tags: function (term, page) {
                  return {
                    tags: term
                  };
          },
          results: function (data, page) {
            return { results: data };
          }
      }
});
```

The request (output) should be correct (see the image):
 ![json encoding](https://cloud.githubusercontent.com/assets/7173038/2808344/885ef894-cd24-11e3-8e22-e43f6b5fab15.JPG)

Here is the HTML code:

``` html
<div class="list-group">
   <div class="list-group-box tags">
    <div class="title">Keywords</div><hr>
         <div id="e12" class="tags-input"></div>
    </div>
</div>
```

Now let's face the problems:
1. When I start typing the typehead effect does not work: after typing "Acer" the tag "Acer" should be at the top of the dropdown list but it does not happen. "Acer" doesn't move from it's default "position" in the tags list. Hope this screenshot will help to understand what I'm trying to explain: 
   ![tags-typehead](https://cloud.githubusercontent.com/assets/7173038/2808395/a906c582-cd28-11e3-91ff-942d89eea922.JPG)
2. I'm not able to insert new tags which are not in the drop.down list: "Note that when tagging is enabled the user can select from pre-existing tags or <b>create a new tag by picking the first choice which is what the user has typed into the search box so far</b>." I think this issue is related somehow with my first problem. The tokenSeparators are not working: if I try to force the inclusion of a new tag ending it with a comma (,) it's not recognized.

Thank you for your patience.

**Comment by pgksunilkumar** [comment]
please add a jsfiddle we can easily understand

**Comment by alexweissman** [comment]
Will link back to @kevin-brown's explanation in the documentation.
