### ISSUE TITLE
formatResult ignores DOM modifications

### ISSUE THREAD

**Issue by norabor** [select2/select2#2323]
According to the spec of formatResult

> The implementation may choose to append elements directly to the provided container > object, or return a single value and have it automatically appended.

This doesn't work any more as it now must return a single value or the container is not appended.
This change was introduced

https://github.com/ivaynberg/select2/commit/701e84ea213c91f0faf6f9d8f313fef2310c88eb

Any code that actually modifies the container DOM simply doesn't work any more. All inner HTML is forced to be replaced and the node-var is not accessible in my custom formatResult function. So I don't know how to append to the dom in other ways.
Of course it's easy to change my functions to return the dom modifications as html, but this change breaks a few of my projects.

**Comment by kevin-brown** [comment]
Should be fixed in 4.0.0.
