### ISSUE TITLE
Events are not being properly cleaned up on AbstractSelect2.close

### ISSUE THREAD

**Issue by redbmk** [select2/select2#2331]
There are still some issues with `containerEventName` (see issue #2324). Having an escaped dash in an event name does not generate a valid namespace. Basically, it will bind the event and ignore the namespace, so when you try to unbind on destroy it will never get unbound. Try this code, for example: `$(document).on("click.abc\\-def", function () { alert("Click") }).off("click.abc\\-def");`

Also, try a string like `"abc\\[def\\]"`. The error is simply being masked because it now fails silently to bind to the namespace, but still binds to the click (or other) event. Now that the code is cleaning itself up for memory leaks (see #2313) you will run into an error if you've opened select2 and then destroyed an element.

**Comment by pedrofurtado** [comment]
The version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
