### ISSUE TITLE
Select 2 autocomplete not work for dynamic added select element

### ISSUE THREAD

**Issue by vish02chouhan** [select2/select2#2336]
I have the following ajax query which get HTML. This html has a select element having an Id ddlPage.

``` js
$.ajax({
    type: "GET",
    url: "/Settings/GetEfinanceInterfaceSettingLookups",
    //data: arr,
    success: function (data) {
        $("#eFinanceInterfaceModelForm").append(data);
        AfterLookUpLoad();
    },
    error: function (error) {
        alert(error);
    }
});

   function AfterLookUpLoad() {

        $("#ddlPage").select2({
            placeholder: "Select Type(Screen)",
            allowClear: true

        });
}
```

But its autocomplete not works because when i open the select list i am not able to focus on the text box for typing.
![select2bug](https://cloud.githubusercontent.com/assets/5634838/2851907/213f4726-d126-11e3-87c4-1d62c83704e5.png)

**Comment by vermaboys** [comment]
See this link https://github.com/vermaboys/select2-autocomplete-laravel5.4

**Comment by muneeb706** [comment]
> Thanks a lot , the new version work perfectly for me...

How did you resolve the issue? I am experiencing same issue in newer version (4.0.12) as well.
