### ISSUE TITLE
Function/option to filter out events

### ISSUE THREAD

**Issue by kevin-brown** [select2/select2#2345]
Given that a lot of the issues that are opened could be fixed by letter an event bubble up that can be caught, it might be useful if we allow that to happen.  It was suggested somewhere to do it using a function which can selectively determine if the event should bubble or not, which would allow users to override the function and filter out only the events they need to.

Related tickets: https://github.com/ivaynberg/select2/issues/1456 https://github.com/ivaynberg/select2/issues/1908 https://github.com/ivaynberg/select2/pull/1845 https://github.com/ivaynberg/select2/issues/1820 https://github.com/ivaynberg/select2/issues/2166

**Comment by Mad-Chemist** [comment]
Can you provide some documentation for this?  I've spent all morning trying to track it down on your site and have been unsuccessful with that and guessing at the implementation.
