### ISSUE TITLE
Unable to update select2 option data list after initial load

### ISSUE THREAD

**Issue by phazei** [select2/select2#2348]
I have a data array I'm using to initialize the select2 box, but I'm trying to figure out how to load additional options after it's been loading.  The array I'm loading at first is similar to this:
[{id:0,text:'enhancement',extra:object},{id:1,text:'bug',extra:object}]
And on the onchange event, I use all the data in the extra object.

I need to be able to replace and/or add to that data array and I can't seem to find a function for it.  The closest I saw was createSearchChoice, but that seems to only be for tagging and can't be dynamically added to the list.

EDIT:
I traced everything trying to figure out where I could do something.  I found opts.data.
If I create a select2 element, then do like so:

```
sdata = $('.select2').data('select2');
sdata.opts.data.push({id:99,text:"new option",extra:{}});
```

It does seem to work in creating a new option to the list that's selectable.  Is there a better way?  And are there any problems doing it that way would cause?

**Comment by tlginn** [comment]
I am having the same issue.  The data array that I passed to the plugin is updated via reference as kevin-brown stated. However the <ul class="select2-results_options"> element does not have <li>s added or removed to reflect changes to the array.

**Comment by hybridwebdev** [comment]
@phazei Seriously dude, you are my freaking hero. I'm necroing this thread, don't even care. 6 hours of torture, hair pulling and googling/trial and error and your solution worked for me. 

heres what I ended up with: 

[code]
	$("tr[data-name='venue_ticket_select_section']").on('change',"input", function(){
      
 		var select_section = $(this).val();
	
		rowdata = $("tr[data-name='venue_ticket_select_row'] input").data('select2');

		rowdata.opts.data.push({id:99,text:"shithead"});

	});
[/code]

**Comment by aspot** [comment]
@hybridwebdev this doesn't seem to work with Select2 v4... can you confirm you weren't using v4?

I get "Uncaught TypeError: Cannot read property 'data' of undefined" for the rowdata object.

**Comment by hybridwebdev** [comment]
Yes, I was using the newest version of select2. At a cursory glance, it looks like you might have the wrong syntax. Do a console.log($(select-elemnt).data('select2')); And report back what comes up.
