### ISSUE TITLE
Select 2 lost focus when use in long modal popup

### ISSUE THREAD

**Issue by vishyagnik2186** [select2/select2#2349]
Its works fine in simple web page and short modal , but if size of modal increase it does not work...it lost focus.
![select2js in long modal](https://cloud.githubusercontent.com/assets/7511661/2902685/9037e9aa-d5e8-11e3-9725-7d5a80e7cb12.png)

**Comment by egraumann** [comment]
hi Julienh, if I would want to use $.fn.modal.Constructor.prototype.enforceFocus = function () {};, where would I put this? I encounter weird problems here where the select field jumps out of the modal window after typing in some stuff, depending on whether browser cache is enabled or disabled (chrome)
