### ISSUE TITLE
Firefox issue :Select2 control not clear when click on other reset button on form,when press f5 button it again popup the selected value

### ISSUE THREAD

**Issue by sangad** [select2/select2#2357]
Step to follow :
1. Select value in dropdown
2. click on reset button it clear selected value.
3. press F5 ,it again popup value
4. I am registering all javascript on code behind
![untitled](https://cloud.githubusercontent.com/assets/7540389/2935451/9531013e-d80f-11e3-9c83-d6a8c993b969.png)

**Comment by kevin-brown** [comment]
Closing this off due to a lack of activity.

If this is still an issue in the upcoming 4.0 release, feel free to reply back and we can determine if this needs to be reopened.
