### ISSUE TITLE
formatSelection has no way of accessing parent optgroup when using ajax

### ISSUE THREAD

**Issue by raveren** [select2/select2#2362]
When using `formatSelection` on a typical `<select>` with optgroups, you are able to access the `optGroup` of the selected option via `item.element`, but if you are using ajax, the first parameter to the `formatSelection` function is the item that ajax fetched - verbatim.

I want to prepend the name of the parent element to the chosen value - and there's no obvious non-hacky way to do it.

**Comment by kevin-brown** [comment]
Closing this off due to a lack of activity.

If this is still an issue in the upcoming 4.0 release, feel free to reply back and we can determine if this needs to be reopened.
