### ISSUE TITLE
On Chrome mobile dropdown closes right after opening

### ISSUE THREAD

**Issue by andres-k** [select2/select2#2368]
Chrome version: 34.0.1847.114
Android: 4.1.2
Select2: Version: 3.4.8 Timestamp: Thu May  1 09:50:32 EDT 2014

When clicking on select2 input the dropdown opens and instantly closes. Doesn't happen when double-tapping or making a sort of "swipey" motion.

**Comment by LikeBtn** [comment]
The following does work for me:

	$(document).on('touchcancel', '.select2-chosen', function(e) {
		var field = $(e.target);
		field.trigger('touchstart');
		return field.trigger('touchend');
	});

**Comment by javirescalvo** [comment]
Any updates on this problem?
Still happening on last version.
