### ISSUE TITLE
navigation on latest visible item

### ISSUE THREAD

**Issue by firebird631** [select2/select2#2369]
Hi,

I've an issue on Firefox 29 and Chromium 34 (I don't know on others versions) when I navigate using the keyboard (down key) or hover with the mouse to the latest VISIBLE element on the list. The scrollbar is down to makes appear the full height of the element (simple text), but it is not like on the upper behavior (hover first visible element). Its only a minor view issue.

**Comment by kevin-brown** [comment]
Closing this off due to a lack of activity.

If this is still an issue in the upcoming 4.0 release, feel free to reply back and we can determine if this needs to be reopened.
