### ISSUE TITLE
"Force" user to select at least 2 (or more) options

### ISSUE THREAD

**Issue by kabeza** [select2/select2#2370]
When validating select2 through jQuery validation, parsley and others, one can set select2 field as required, and it works. This forces user to select an option, but:

When working with multiple="multiple" select2 fields, I need sometimes to force user to choose at least 2 or more options

Is there any way to force user to select at least X items (more than 1) for select2 fields with multiple="multiple"? Same as maximumSelectionSize but inverse

I was thinking about val() method and doing a custom validation routine that checks (how?) at some moment the quantity of chosen items in a select2 field...

Thanks for any guidance

**Comment by satyavh** [comment]
+1

**Comment by kabeza** [comment]
thanks @satyavh will try it

**Comment by alexweissman** [comment]
This appears to be a usage question, rather than a bug report or feature request.  Please see our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Usage questions should be discussed on the [forums](https://forums.select2.org) instead.
