### ISSUE TITLE
clicking anywhere beside select2 container does not loose focus

### ISSUE THREAD

**Issue by banco2** [select2/select2#2372]
Hi, I am trying to retain the placeholder after click and I manage to do that, however when after clicking the textbox/select2 container and I click anywhere beside the textbox/container the letter "A" from "Add Filter +" stays behind. It only goes away when I clicked twice outside. Is there any way to force the focus out of that textbox or any other solution to preven that "A" From appearing? Thanks in advance for the help.
The bug can be seen here- http://jsfiddle.net/Vj48m/

**Comment by kevin-brown** [comment]
This issue was fixed in Select2 4.0, which now uses native placeholders and attempts to properly size it.
