### ISSUE TITLE
Selection box appears over the NavBar for longer forms

### ISSUE THREAD

**Issue by drpain** [select2/select2#2379]
Hi There,

Browser: Chrome V34, Firefox V29

I am having an issue where I have quite long forms with a Fixed-Top Navbar. When scrolling down the form the item appears above the Navbar. 

I tried increasing the the z-index of the navbar. 
I tried removing the relative style in select2.css, which works. But then when selecting an item the entire page jumps to the top.

Has anyone come across this issue, and a solution? Or do you know which part of the JS is responsible for bouncing the page to the top?

Kind Regards,
Rudi

**Comment by kevin-brown** [comment]
Closing this off due to a lack of activity.

If this is still an issue in the upcoming 4.0 release, feel free to reply back and we can determine if this needs to be reopened.
