### ISSUE TITLE
The German character "ß" breaks underlining of matches

### ISSUE THREAD

**Issue by tf-jbo** [select2/select2#2380]
Hi all,
We recently had the problem that select2 would wrongly highlight text in the list of matches. In this case we used it for addresses, which, in Germany, often contain the word "Straße". After a bit of fiddling around I found out that select2 applies .toUpperCase() to both the available items, as well as the search term entered by the user. Since "ß".toUpperCase() results in "SS" this somewhat breaks the markMatch() function, causing it to wrongly calculate the substring for the match.

I created a jsfiddle to show the Problem: http://jsfiddle.net/qSs5x/

I locally "fixed" the problem by replacing the use of toUpperCase() with toLowerCase(), but I'm not sure if this will cause problems with other characters.

Best regards
Jan

**Comment by pedrofurtado** [comment]
The version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
