### ISSUE TITLE
How can i add to select2 with ajax, preload data without request to server

### ISSUE THREAD

**Issue by Victori0us** [select2/select2#2383]
Thank you for nice library. It's great. But i have a question.
Add to select2 with ajax preload data ( [{id: 1, text: "one"}, {id: 2, text: "two"},...] ). Need activate ajax only on search, but on focus after load page in select2 dropdown would be shown only preload data.

**Comment by ashwinbalaguru** [comment]
@kevin-brown  
can u please give an example on how we can pre populate the select2 field in case of editing a record.

as per your comment on initSelection, i tried setting values to a hidden field, but it didn't work.  Can u please give an example on the same.

**Comment by alexweissman** [comment]
As of Select2 v4, `initSelection` is deprecated.  The current, preferred way to do this is described in https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2.
