### ISSUE TITLE
Separate select2-highlighted in two states: highlighted and selected

### ISSUE THREAD

**Issue by jhuesos** [select2/select2#2407]
IMHO select2 should separate the highlighted state in two: highlighted and currently selected. Having both sharing the same one it might be confusing for the user.

To explain the issue let me put a very simple scenario:
- lets say the user opens the dropdown and selects Alaska
- Then the user opens the dropdown again. In that moment Alaska is still the highlighted one because is the one the user selected before.

![select2-selected](https://cloud.githubusercontent.com/assets/339609/3084372/4e2de3fe-e4f5-11e3-9b01-3d9da8bf0855.png)

- Let's say now the user hover over other item: now alaska is not longer highlighted and now the other option is.
- Since highlight and selected share the same state, it might seem now that California is the new selected one.

![select2-highlight-selected-issue](https://cloud.githubusercontent.com/assets/339609/3084371/4e27c834-e4f5-11e3-90f6-f45cdbd64fe2.png)

- User might click out of the dropdown and Alaska would still be the selected option.

IMO, selected options should always have a specific CSS class like: select2-selected, and highlighted will be only used when hovering/navigating using keyboard

**Comment by kevin-brown** [comment]
Closing this off due to a lack of activity.

If this is still an issue in the upcoming 4.0 release, feel free to reply back and we can determine if this needs to be reopened.
