### ISSUE TITLE
Multiple empty spans with select2-hidden-accessible appended to body

### ISSUE THREAD

**Issue by boughtonp** [select2/select2#2412]
Every select2 instance is creating an empty span in the body, resulting in a whole bunch of these:

```
<span class="select2-hidden-accessible" role="status" aria-live="polite"></span>
```

It looks like the culprit is https://github.com/ivaynberg/select2/blob/master/select2.js#L685

```
        this.liveRegion = $("<span>", {
                role: "status",
                "aria-live": "polite"
            })
            .addClass("select2-hidden-accessible")
            .appendTo(document.body);
```

It's not entirely clear when it is used, but the noise could be reduced with any of:
    \* part of the .select2-container for each select2
    \* have a single top-level tag that all select2 elements share
    \* only be created when they are needed (i.e. when non-empty)

**Comment by lboquillon** [comment]
@izharaazmi thanks

**Comment by kabirpust** [comment]
After selecting type and garage, When the user will click on stock field, ther previously selected value will be put on the clicked stock, But my code gives me the same as first and second times
Please check my fiddle where is my mistake, First one is ok, But when I select the second one, it gives me the first data as output, but why ?

Demo http://jsfiddle.net/kabircse/kzgvcsyk/

**Comment by monikaja** [comment]
I fix that with this code:

            if($(".select2-hidden-accessible").length){
                this.liveRegion = $(".select2-hidden-accessible");
            }
            else{
                this.liveRegion = $("<span>", {
                    role: "status",
                    "aria-live": "polite"
                })
                    .addClass("select2-hidden-accessible")
                    .appendTo(document.body);
            }

instead of this:

            this.liveRegion = $("<span>", {
                role: "status",
                "aria-live": "polite"
            })
                .addClass("select2-hidden-accessible")
                .appendTo(document.body);

**Comment by maximo72** [comment]
+1

**Comment by ppsandoval** [comment]
saf
