### ISSUE TITLE
Can I call select2 after AJAX call?

### ISSUE THREAD

**Issue by don-odyssey** [select2/select2#2413]
Hi,

I am using an AJAX call to create my <SELECT id="lstDest"> drop-down list. AFter executing the AJAX call, I issue the code:

``` js
$(document).ready(function() { $("#lstDest").select2(); });
```

The <select> does not display,. instead, nothing shows. Looking at the source code, the select2 code looks present but for some reason, it is either hiding the code or the HTML is broken and not displaying.

Any examples of using this widget with AJAX?

**Comment by bagratzakaryan** [comment]
Hi to all I use select2 plugin after ajax call ( I open my modal content after ajax call and init select2 plugin), in this case, my select2 search field doesn't work.
How can I fix this bug?

![capture](https://user-images.githubusercontent.com/19146467/34374672-c35f1cdc-eafb-11e7-8ce7-69cf1ac22206.PNG)

I can't focus input field.
