### ISSUE TITLE
Dragging elements on the drag and drop breaks keyboard input in some cases

### ISSUE THREAD

**Issue by pkabra2** [select2/select2#2418]
Dragging an element from the drag and drop in some situations breaks being able to type with the keyboard. eg. Dragging an element into a corner or to an edge and releasing causes the input to no longer allow keyboard typing.

You can still add elements but it breaks keyboard input.

This can be tested the select2 drag and drop sorting example at http://ivaynberg.github.io/select2/ just drag an element on the top row up or on the bottom row down (drag "black" down to the bottom edge), then try typing.

**Comment by pedrofurtado** [comment]
The version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
