### ISSUE TITLE
Setting title attribute to inputs

### ISSUE THREAD

**Issue by anmccall85** [select2/select2#2419]
For WCAG 2 level A compliance, every text input needs either a label or a title. Can you add a way to set the title of the input elements that select2 uses?

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
