### ISSUE TITLE
Show childs if parent match

### ISSUE THREAD

**Issue by mavci** [select2/select2#2424]
Hi,

I have lot of parent and lot of child options. I want to show childs too if parent option match. An example;

* Fruits
   * Apple
   * Banana
   * Cherry
   * ...
* Vegetables
   * Tomatoes
   * Patato
   * ...
* ...

When I type fruit, I want to see apple, banana and cherry too. How can I do this?

Thanks in advance.

**Comment by kevin-brown** [comment]
This behaviour can now be controlled in Select2 4.0 through the use of a custom matcher which returns all of the options under the parent, instead of just the parent or just the matching child options.
