### ISSUE TITLE
Allowing dynamic elements in selected entries

### ISSUE THREAD

**Issue by Hexasoft** [select2/select2#2426]
Hello,
I have a specific need: using "multiple" selection, I need to add some checkboxes into the selected elements, so that for each selected entry it is possible to allow user to select some specific stuff (or not).
This can be achieved by giving a formatSelection() function, which adds the needed HTML code (input tags...).

The problem is that "normal" events are grabbed by select2 which prevent (for example) checkboxes to work as they should.

I managed to remove this problem by commenting the line 293:
```diff
    function killEvent(event) {
-        event.preventDefault();
+       //event.preventDefault();
        event.stopPropagation();
    }
```
It is fine for my dedicated purpose, but it is maybe not the best way. Whatever I can't find problems generated by this change.

You may consider adding this feature (allowing dynamic HTML stuff inside selected elements) - probably in a better  way than I did, at least as an option or in suitable cases (may not be useful without "multiple" for example).

**Comment by kevin-brown** [comment]
This is now possible in Select2 4.0 because events are no longer killed. So the event will propagate as expected, and the default actions are no longer being prevented.
