### ISSUE TITLE
Preload Data & Ajax Support 

### ISSUE THREAD

**Issue by carlhussey** [select2/select2#2427]
I use select2 to allow a user to select multiple employees from an ajax request.

Once saved, if they ever come back to the tool I need to pre-populate the fields with the employees they selected prior.

I have completed this however when putting an Ajax function in there as well, it doesn't  work. The presets are the only options in the select and it wont let me use the external data source as well.

Is there a way to accomplish this?

**Comment by dflock** [comment]
+1

**Comment by pettechbytes** [comment]
This was almost 3 years ago.  In an update, it was possible to "initialize" the select with values, but then in a recent update, that feature was broken.  The following code used to work for me but now does not:

```
var employeeList = $.parseJSON(expenseDetailRow.IncludedEmployees);
$('#expenseEmployeeList').select2().val(employeeList).trigger('change');
```

There are multiple posts on StackOverflow regarding this change.  Any possibility of reverting back to the previous version so this functionality works again?

**Comment by alexweissman** [comment]
For the moment, the best way to achieve this is by [retrieving the individual items and adding them as new options](https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2).
