### ISSUE TITLE
Generated <ul> and <li> flow elements are not valid HTML when Select2 is used inside of a <p>

### ISSUE THREAD

**Issue by coreyworrell** [select2/select2#2428]
A common practice is to place form fields within paragraph tags.

``` html
<p>
  <label for="select">Something</label>
  <select class="select2" id="select">
    ...
  </select>
</p>
```

When select2 is setup on the select, it inserts a `div` element as the container, which isn't a valid child element for `p`. I don't see any reason this couldn't be replaced with a `span` element or similar to follow how a normal `select` behaves.

**Comment by kevin-brown** [comment]
`<ul>` and `<li>` are required for the results to be semantically correct, and should work fine within a `<p>` element.

In 4.0.0 we've replaced the `<div>` elements with `<span>` elements, and now Select2 appears to work well within a `<p>` element.

**Comment by coreyworrell** [comment]
@kevin-brown Semantics don't really apply when you're breaking valid HTML. Putting a `<ul>` inside of a paragraph tag will not work, you will end up with an empty paragraph before the `<ul>`. See here under "Tag Omission": https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p

**Comment by kevin-brown** [comment]
You meant under "Permitted content", which is where I noticed a few minutes ago that I was wrong about `<ul>` being valid in a `<p>` tag.

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content

This mainly affects the multiple selection container (when a `<p>` is wrapping it), although it also isn't valid in a `<span>` which is an issue for the results dropdown.

**Comment by coreyworrell** [comment]
Well yes, that is correct too. But what I was pointing out is that a paragraph will terminate/close if a `ul` tag is found before the closing paragraph tag. So anything generated by Select2 needs to be phrasing content. CSS can style it as block content though. And aria tags can be added if you want semantics and accessibility.

**Comment by akinhwan** [comment]
is there a reference somewhere describing why select2 uses ul elements with nested lis instead of a select tag with options?
