### ISSUE TITLE
input.select2-input still has focus after closing the dropdown

### ISSUE THREAD

**Issue by ghost** [select2/select2#2433]
1. Visit http://ivaynberg.github.io/select2/#events.
2. Open the report type dropdown, but don't select an option.
3. Click once anywhere on the page, but not on the dropdown itself.
4. Type the letter `b`.

You'll notice that the report type dropdown is re-opened and the results are filtered to only include the `bug` option. You have to click twice to forcibly remove focus from the input field.

Using the example from Step 1 and watching the events that are printed, you'll noticed that the `focus` event is fired after the `close` event is triggered.

I've traced the bug to `SingleSelect2.close()`. It is called by the callback for the `mousedown touchstart click` events on `mask`. `this.opts.shouldFocusInput()` returns `true` which applies the focus to `input.select2-input`.

The impact of this bug is noticed when trying to add shortcut keys to your application. Consider a scenario where `f` opens the dropdown (By default, `esc` closes the dropdown.). A user hits `f` and the dropdown opens. The user hits `esc` and the dropdown closes. The user hits `f` again and the dropdown opens with the options filtered by `f`.

**Comment by cguillemette** [comment]
@glevine-sugarcrm It behaves normally, if you click again at 200px away then the focus should be lost. If you don't expect that you could remove the focus using the .blur().

This issue be closed.
