### ISSUE TITLE
Bug - getting selected values from multiple select box throws exception

### ISSUE THREAD

**Issue by mperdeck** [select2/select2#2458]
On your page
http://ivaynberg.github.io/select2/
under heading
Programmatic Access

When I select
California
Oregon
Washington
in the second select box and then click the "Alert selected value using data" button, there is a JavaScript exception
Uncaught TypeError: Converting circular structure to JSON
at
(index):766

I am using Google Chrome.

By the way, I love select2, very impressive and useful!

**Comment by kevin-brown** [comment]
I'm closing this ticket off because of inactivity. By the looks of it, this issue was more than likely fixed in the latest version of Select2.
