### ISSUE TITLE
Licensing / WordPress compatibility

### ISSUE THREAD

**Issue by helenhousandi** [select2/select2#2468]
Howdy,

I'm currently investigating potential helper libraries for selections for WordPress (I am a committer and the current release lead for 4.0). Another regular contributor (@ericandrewlewis) submitted a [pull request](https://github.com/ivaynberg/select2/pull/464) quite some time ago switching the licensing from Apache to dual-licensed GPL v2 and Apache. While technically this may be okay, ideally it would be GPL v2+ as opposed to v2 or possibly even just MIT, dropping the dual license entirely. I'm not sure if you have a specific reason for choosing Apache originally, so I'm curious as to thoughts on licensing here. I am by no means a software license expert, but I feel that this is an important thing to figure out.

Also, as a project committed to backwards compatibility, we take great care in third party library inclusion, and really strive to do work both upstream and downstream. We can open a separate thread for this if you'd like, but also curious as to your thoughts about playing together as open source projects.

Thanks!

**Comment by kevin-brown** [comment]
Select2 4.0.0-beta.2 is out and we're expecting a final release by the end of this month.

https://select2.github.io/

The switch to the MIT license is complete. I'm going to close off this ticket now that it's been finished.
