### ISSUE TITLE
IE10 - Unable to get property 'attr' of undefined or null reference

### ISSUE THREAD

**Issue by Willyham** [select2/select2#2469]
In IE10, `this.container` is null when `syncCssClasses` is called by the sync method in monitorSource:

```
syncCssClasses(this.container, this.opts.element, this.opts.adaptContainerCssClass);
```

Which causes the error at this line:

```
classes = dest.attr("class");
```

**Comment by pankajparkar** [comment]
Just Update:

 Seems like this issue has been fixed in Version: 3.5.2 (on Sat Nov  1 14:43:36 EDT 2014) release

Reference link https://cdnjs.cloudflare.com/ajax/libs/select2/3.5.2/select2.min.js
