### ISSUE TITLE
formatSelection/formatResult container modifications

### ISSUE THREAD

**Issue by athlan** [select2/select2#2477]
The `formatSelection` and `formatResult` does not provide proper `container` object, you can modify. Simple example:

```
var formatSelection = function(obj, container, query) {
    container.attr('data-test', 'abc')
    container.on('click', function() {
      console.log('clicked!')
    })

    console.log(container, container.html())
    return obj.context_title
  }

$('.select2multiple').select2({
        multiple: true,
        formatSelection: formatSelection,
        formatResult: formatSelection
      })
```

When you click the added `<div>` element, no log on the console appears. What is more, no data attribute is added into `<div>` container into DOM.

Is it bug?

**Comment by simran92** [comment]
You can modify the wrapping LI, instead of the container. Here's my solution:

criteriaElem = $('[name=segment_criteria]').select2({
    tags: function(){
        return !!window.segmentTags ? window.segmentTags : true
    },
    formatSelection: function(tag, container, query) {
        container.parent().data('select2-tag', tag).attr('onclick', 'select2TagClicked(this);');
        return tag.text;
    }
});
