### ISSUE TITLE
Select2 Dropdown Tabindex is not working

### ISSUE THREAD

**Issue by manojuit** [select2/select2#2480]
Hi All,

I am using select2 drop down. there i have given tabindex sequentially but by default first time is working later if i select any value in dropdown after that if i press tab then it's not working. it's changing tabindex as -1 but i have given like 1.2.3...etc. i tested in firefox browser under information  display tabindex here we can see changed tabindex as -1.  
Example:
  From Dropdown => tabindex 1
  To Dropdown  => tabindex 2
  Date Dropdown => tabindex 3
  Submit  Button => tabindex 4

if i press the Tab I want the output like From => To => Date => Submit
Please let me know if any code changes is required to fix above issues

Here is my code
http://jsfiddle.net/97x2q/2

**Comment by ova2** [comment]
I can not set "tabindex" on Select2 too. There are no option for that. Are there maybe any JS workarounds for setting "tabindex"?

**Comment by ova2** [comment]
Found a workaround:

```javascript
$this.select2({
    ...
});

$('#select2-#<id of native select>-container').prop('tabindex', tabindex);
```

**Comment by sdhull** [comment]
Yeah +1

Tabbing through a form should continue to work without having to additionally somehow set tabindex after select2 initializes.

Obviously (IMO) it should take the `tabindex` set on the input/select element for which it's taking responsibility. But minimally it shouldn't default tabindex to 0, because it breaks tabbing through forms.

http://jsfiddle.net/0we6azds/ -- this should just work without special tabindex code, if you ask me.

**Comment by sdhull** [comment]
Seriously is no one else irritated by this? Tabbing through my reg form no longer works. IMO this should be highest priority. I tried my hand at fixing it briefly but all I managed to do was completely break select2.

**Comment by BlaM** [comment]
Any solutions? I need to modify the tabindex during runtime of a page - but whatever I do, select2 (3.x) does not seem to care.

**Comment by pklauzinski** [comment]
Same issue here.. even calling .focus() explicitly on a select2 input element doesn't work.

**Comment by stephenconnolly** [comment]
@kevin-brown I'm experiencing this issue as well. I did a quick test with the latest release (3.5.4) and I noticed it hasn't been fixed. I'm just checking to see if its on your radar for future releases ? 

I'll try the work around for the moment.

Thanks for the plugin, we've used it all over our site and its worked very well. This is the first issue we've come across.

**Comment by naderghanbari** [comment]
The same here, any updates on this?

**Comment by manovraresoft** [comment]
Still having issues with this. SUPER frustrating.

**Comment by userrails** [comment]
I am still having same issue :(

**Comment by cloudcaptain** [comment]
Any updates?  Any workarounds?

**Comment by SgtOddball** [comment]
If it's v3.5 then @kevin-brown has stated before, all development on v3.5 has stopped. If it's still an issue on v4 then it's probably a good idea to raise a fresh ticket on v4.

**Comment by ryanjbonnell** [comment]
This behavior may be related to #4384

**Comment by metalocator** [comment]
This is still an issue in 4.  We specify a tabindex to the raw HTML for the various form fields and the tab behavior in both chrome and FF is to skip over the select2.  It's breaking accessibility for us, which means we have to drop the library if it's not addressed.

**Comment by manovraresoft** [comment]
Still waiting...  

I have had to move to a different version of jquery select box but it is not friendly with mobile.  I have been forced to choose between mobile friendly and accessibility.  Accessibility is the law!

**Comment by rugabarbo** [comment]
I use https://github.com/peledies/select2-tab-fix to solve this problem.

**Comment by bgth** [comment]
Please try and check if it works:
`// add tabindex dynamically
    var tabindex = 1;
	$('input,select').each(function() {

	  if (this.type != "hidden") {

	    $(this).attr("tabindex", tabindex);
	    tabindex++;
	  }
	});

	// https://stackoverflow.com/a/50535297/2782670
    $(document).on('focus', '.select2', function (e) {
        if (e.originalEvent) {
            var s2element = $(this).siblings('select');
            s2element.select2('open');
            // Set focus back to select2 element on closing.
            s2element.on('select2:closing', function (e) {
                s2element.select2('focus');
            });
        }
    });`

**Comment by manovraresoft** [comment]
Thank you, I will take a look at this code fix

**Comment by floppyTop** [comment]
Has there been any further work or discussion around this? Seems like a pretty high-priority issue.

**Comment by OmidAhmadyani** [comment]
focus it after select it!

    $('.select2').on('select2:select', function (e) {
    $(this).focus();
    });

for your code replace .select2-offscreen with  my .select2.

S F My English!

**Comment by akoSalman** [comment]
Use [my extension package](https://github.com/akoSalman/select2-tab-fix) to `select2` and every thing goes fine.

**Comment by stewest** [comment]
Seeing this issue still with latest Select2 4.1.0-rc.0
