### ISSUE TITLE
handling keydown keyCode 229

### ISSUE THREAD

**Issue by hitosu** [select2/select2#2482]
Recent versions of Chrome (prob. affects all WebKit based browsers) started to send keydown events with keyCode == 229 before every standard keyboard event.
This leads, for example, to the following unexpected behaivors:
- pressing ENTER on empty search field selects first element from the list
- BACKSPACE not deleting previous tags in multiple selection

Temporary fixed by adding the following line
`if (e.keyCode == 229) { killEvent(e); return; }`
at the beginning of this function:
`this.search.on("keydown", this.bind(function (e) {`

**Comment by zhoou** [comment]
After testing， i found that “keyCode= 229” is generally appear in document.onkeydown function, and not appear in document.onkeyup , so, we can determine whether document.onkeydown is null in document.onkeyup function, if it's null, then re-registration the document.onkeydown function, and the problem not appear yet.
```
function keyControl (e) {
 // coding...
}
document.onkeyup = function(){
    if(document.onkeydown === null) {
         document.onkeydown = keyControl()
    }
}
document.onkeydown = keyControl()
```
