### ISSUE TITLE
Open native Select on mobile

### ISSUE THREAD

**Issue by marcelabomfim** [select2/select2#2487]
I need to open the native select in Mobile. 
I tried: 

``` javascript
$("#mySelect").on("select2-opening", function() { 
    openNativeSelect($('#mySelect'));
    return false;
});

function openNativeSelect(elem) {
    if (document.createEvent) {
        var e = document.createEvent("MouseEvents");
        e.initMouseEvent("mousedown", true, true, window, 0, 0, 0, 0, 0, false, false, false, false, 0, null);
        elem[0].dispatchEvent(e);
    } else if (element.fireEvent) {
        elem[0].fireEvent("onmousedown");
    }
}
```

but still opens the select2

**Comment by antgonzales** [comment]
@kevin-brown why not allow developers the option?

**Comment by kevin-brown** [comment]
> why not allow developers the option?

This is not a feature that will land in the core, and there are a few reasons behind it

- **Select2 jQuery events** - The standard `<select>` does not provide any ways for us to relay our `select2:` prefixes jQuery events, so these would suddenly break on mobile devices.
- **Remote data sets** - A standard `<select>` doesn't allow for it to be connected to a remote endpoint. So we wouldn't be able to allow this to happen when working with AJAX, which would create a broken user experience.
- **Consistency** - With Select2, we are trying to create a consistent experience across all platforms. Allowing this in the core would go against that.

Now, this doesn't mean that it's not possible for developers to implement this on their own. It just means that developers have to make the decision to do this, knowing that Select2 won't work the same across all platforms.
