### ISSUE TITLE
Make select2 accessible (add Aria roles)

### ISSUE THREAD

**Issue by koleary** [select2/select2#2499]
There is an issue in the Drupal 8 queue to add chosen to Drupal core and select2 was proposed as an alternative. The blocker to both of these libraries is that they are not accessible.

There is a really good example of how this can be done here:
http://cookiecrook.com/test/aria/multiselect/listbox.html
Here's the javascript: http://cookiecrook.com/test/aria/multiselect/js/aria.js

This maps closely to the basic select functionality. It looks pretty simple to implement using the listbox and multiselectable Aria properties
http://www.w3.org/TR/wai-aria/roles#listbox
http://www.w3.org/TR/wai-aria/states_and_properties#aria-multiselectable

I would make a patch myself but I'm not so hot at js.

**Comment by mgifford** [comment]
Hey @kevin-brown - hope that 4.0 is coming along well.  

I haven't actually used Orca.  Android's TalkBack is also an option.  

It's probably more useful though to see if you can get either of these working through Wine:
http://www.nvaccess.org/
http://www.chromevox.com/

Or just run them natively in Windows.  

If this is a good time to test, do let us know. We can probably find someone to do some initial testing.  Even just with http://wave.webaim.org/

**Comment by kevin-brown** [comment]
Closing this off as I believe Select2 is now at a decent state for accessibility, where it is further ahead that Select2 3.5.x and more closely matches native implementations of a select box.

If there are any accessibility issues that are discovered in 4.0, feel free to create a new ticket or pull request and we can work them out.
