### ISSUE TITLE
Search input field losses focus in IE when clicking scroll

### ISSUE THREAD

**Issue by nucleardoom1** [select2/select2#2503]
The problem is that clicking in a scrollbar in IE will enforce that the search input field loses focus while in FireFox and Chrome it does not. If you drag the scrollbar in IE and than drag the mouse to your left on a search result it is not possible to use the arrow keys up and down straight away.

Reproducera the problem:
1. Make sure the search input field has focus
2. Move the mouse to the result scrollbar and click it (click and release)
3. The search input field no longer has focus in at least IE 8 to IE 11 but works in FireFox and Chrome

Discussions regarding the problem:
http://www.dynamicdrive.com/forums/showthread.php?19311-Cursor-focus-getting-lost-in-IE-Please-help
http://stackoverflow.com/questions/2284541/form-input-loses-focus-on-scroll-bar-click-in-ie

Workaround:
If you click the scrollbar twice the search input field will again get its focus or implement the that the search field gets its focus back after the stopPropagation is done (fixes the IE problem even if it is not nice)

``` js
this.dropdown.on("click mouseup mousedown touchstart touchend focusin", 
$.proxy(function(e) {
    e.stopPropagation();
    if(e.originalEvent && e.originalEvent.srcElement && e.originalEvent.srcElement.id === 'select2-drop') {
        if (this.opts.shouldFocusInput(this)) {
            this.focusSearch()
        }
    }
}, this));
```

**Comment by alexweissman** [comment]
Is this problem still occurring in 4.0.6-rc.1?

**Comment by sameerperception** [comment]
is there any fix available now for this issue ?

**Comment by pedrofurtado** [comment]
The issue is related to 3.x version, but the version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
