### ISSUE TITLE
ajax + data

### ISSUE THREAD

**Issue by mihdan** [select2/select2#2520]
I have select2 implementation as follows:

``` js
$('#id').select2({
    allowClear: true,
    closeOnSelect: true,
    minimumInputLength: 2,
    ajax: {
        url: moysport.ajaxurl,
        dataType: 'json',
        data: function (term, page) {
            return { q: term, action: 'autocomplete_city' };
        },
        results: function (data, page) {
            return {results: data.results};
        }
    },
});
$('#$id').select2('data', {id: -2, text: 'default value 1'});
$('#$id').select2('data', {id: -1, text: 'default value 2'});
```

Can't set two default value via using AJAX

I want to do like this:

Variant 1 - http://clip2net.com/s/itqCxr
Variant 2 - http://clip2net.com/s/itqBKx

**Comment by alexweissman** [comment]
As of Select2 v4, the preferred way to prepopulate remotely-sourced Select2 controls is described here: https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2
