### ISSUE TITLE
Select2 doesn't work with Cloned <select>

### ISSUE THREAD

**Issue by zerowebcorp** [select2/select2#2522]
Hi
I have observed that select2 doesn't work with a cloned <select> tag.

For example, I have a select tag with two options

``` html
<select class="select">
<option>1</option>
<option>2</option>
</select>
<a href="#" id="click">Duplicate</a>
```

And then I have the jQuery code

``` javascript
$(".select").select2();
```

This works fine, however what I am trying to do is to duplicate the drop down using jquery 

``` javascript
clone()
```

``` javascript
$(function(){
     $("#click").click(function(){
          var newelement = $(".select").clone();
          $("body").append(newelement);
     }); 
});

```

The thing is that, it duplicates the html/css styles but the drop down is not working. 
I understand that this is because select2 convert the <select> tag to more html/css code. 
But is there any way I can get this cloned select tags work?

Do you know any workaround for this ?

**Comment by JagadishMeghwal** [comment]
Infact this solves the problem of initialization of select2 but after cloning I can't change the selection of previous dropdowns

**Comment by pankajphp007** [comment]
Its working but when i changed an option change event not working
