### ISSUE TITLE
Autocomplete by Ajax

### ISSUE THREAD

**Issue by diazknel** [select2/select2#2538]
Hi there 
I'm using the autocompletamiento in using ajax and receive this error "Option 'ajax' is not allowed for Select2 When attached to a <select> element", I read that you need to put a hidden field with the same id of the select field, and did returns me the same error. Can you help me? 
I am using ajax to connect to a file which returns me json. 
Thank you

**Comment by aayush26** [comment]
Is it specific to only select2 v3.x or Should we also use input element instead of select in select2 v4.x while implementing auto-complete with ajax?
