### ISSUE TITLE
Case sensitive equal function

### ISSUE THREAD

**Issue by nishantkagrawal** [select2/select2#2544]
I am using select2 with angular. Here is a situation:

I load the  array from an xml. When I load the array the values are 
Alabama
Alaska
Arizona...

The user selects one of the value and saves. Before saving "Alabama" might get converted to "ALABAMA". When the user comes back to the screen, select2 doesnt auto select "Alabama", as it is case sensitive. Note that we have around 200 different products and each developer might do their processing before saving. So we do not have a standard that we can enforce.

I checked that if I change in "equal" function of select2 then the issue is resolved. Is there any better way to get it done? If not, then can equal function of select2 be modified so that we can use github for the latest update instead of maintaining our own version?

I am currently using Version: 3.4.6 Timestamp: Sat Mar 22 22:30:15 EDT 2014

**Comment by kevin-brown** [comment]
This should have been corrected in Select2 4.0.
