### ISSUE TITLE
Choose language init option

### ISSUE THREAD

**Issue by loostro** [select2/select2#2558]
Right now, to translate select2 you have to include the right locale JS file.

It would be useful if we could load ALL locale files, and control which language is used with initialisation option. This way we could have two select2 widgets (on the same page) with diffrent languages.

Also (optional) it would be nice, if we could change the language after the initialisation.

**Comment by kevin-brown** [comment]
Closing this off as you can actually do this using the new `language` option, just include the short code (or `select2/i18n/[short code]`) to use it.

**Comment by Lutex** [comment]
I can not make the language you want to run.
I am loading the scripts as reported, but not capture the words translated.


<script src="plugins/select2/select2.full.min.js" type="text/javascript"></script>
<script src="plugins/select2/i18n/pt-BR.js" type="text/javascript"></script>

Any suggestions of what I can do?
Thanks.

**Comment by Lutex** [comment]
I can not make the language you want to run.
I am loading the scripts as reported, but not capture the words translated.

    
    <script src="plugins/select2/select2.full.min.js" type="text/javascript"></script>
    <script src="plugins/select2/i18n/pt-BR.js" type="text/javascript"></script>

Any suggestions of what I can do?

**Comment by hdwills** [comment]
@Lutex set default language:
```
<script>
  $('.my-select').select2({
    language: 'pt-BR'
  })
</script>
```

**Comment by yanikore** [comment]
```
$.fn.select2.defaults.set("language", "nl");
```
