### ISSUE TITLE
Change the default text for search

### ISSUE THREAD

**Issue by nixon1333** [select2/select2#2561]
![2014-07-25_1807](https://cloud.githubusercontent.com/assets/1893934/3701640/f0862566-13f4-11e4-8738-ab74a41b922f.png)

Please check the added image. I want to checnga the text "Please enter 2 more character" to RANDOM TEXT or our desired text. Is their any way to solve this?

Thanks,
Nixon

**Comment by gilbertosanchezglobal** [comment]
Like @kevin-brown says, just include `formatInputTooShort` in the select2 config. If you want to assign a static text, you can do something like this:

`$( "#select2" )`
`.select2({`
`     formatInputTooShort: "Please add more text"`
`});`

Now, if you want to insert text that vary, depending some rules, you can do the next:

`function input_length()`
`{`
`     var length = $( `.select2-search-field` ).find( `input` ).val().length;`
`     if( length < 6 )`
`     {`
`          if( length == 5 )`
`          {`
`               return "One character left.";`
`          }`
`          else`
`          {`
`               return "Add " + ( 6 - length ) + " characters.";`
`          }`
`     }`
`}`

`$( "#select2" )`
`.select2({`
`     formatInputTooShort: function ( args )`
`     {`
`          return input_length();`
`     }`
`});`

The function will be executed every time you write something on the input.

**Comment by agengdp** [comment]
@gilbertosanchezglobal formatInputTooShort is not working on version 4.0

You can try this on version 4.0 or higher

```
$("#select2").select2({
	minimumInputLength: 1,
  language: {
  	inputTooShort: function() {
  		return 'Please Add More Text';
  	}
  }
});
```
