### ISSUE TITLE
Scrolling on iOS 7 when touch event starts over select2 element

### ISSUE THREAD

**Issue by chrisys** [select2/select2#2562]
I am having an issue where I have a lot of select2 (8 or so) elements one beneath each other. On the mobile layout of my site they are basically full width and so I have found that if I try to scroll past the elements the touch event instead of starting the scroll opens the menu. 

It can be reproduced on the example page if you try to scroll and the first point of touch is over a select2 element. Tested using an iPhone 5S, and Xcode simulator using iPad/iPhone devices.

**Comment by kevin-brown** [comment]
This issue should have been corrected in the latest version of Select2.
