### ISSUE TITLE
Ready event

### ISSUE THREAD

**Issue by RomeroMsk** [select2/select2#2572]
I can't find if there is an event, fired right after Select2 is attached to input/select (rendered).
I need to hide parent div after Select2 is rendered, because if I'm hiding it on document ready the input will be invisible while Select2 is running on it - in this case width will be calculated wrong and placeholder text will look cutted after showing parent div:
![image](https://cloud.githubusercontent.com/assets/4639951/3747328/044772b8-17cd-11e4-9b1c-7334100e7e77.png)

**Comment by KuenzelIT** [comment]
I also need this kind of event. Is there some progression since the last question?

**Comment by wojtas** [comment]
Bump. I also need such an event, in order to attach the tooltip plugin to the select2 instance.

**Comment by kevin-brown** [comment]
Select2 doesn't have any delay between initialization and rendering, so immediately after initializing Select2 you can trigger your own custom event for this.

```js
$("select").select2();
$("select").trigger("select2-is-ready");
```

It'd make more sense to add this event if there was a rendering step that wasn't immediate.

**Comment by alexweissman** [comment]
There are other open issues specifically about the placeholder width problem on hidden elements.  Please continue the discussion there.
