### ISSUE TITLE
debugging or scrolling window selects wrong option

### ISSUE THREAD

**Issue by terraswat** [select2/select2#2590]
While debugging in chrome, it selects the wrong element. I stepped through the code a bit & the problem is that it's ignoring the values in the DOM event, and is instead scanning the DOM to find which one is highlighted. This creates a race condition between the click event & when select2 determines the new state. If anything makes the screen scroll in between, the wrong element is highlighted.

I suspect this may be a problem w/o debugging, too, if the screen real estate is short.

**Comment by kevin-brown** [comment]
This issue should have been fixed in the latest version of Select2.
