### ISSUE TITLE
Disable autoselect with selectOnBlur if no text typed

### ISSUE THREAD

**Issue by HugoHeneault** [select2/select2#2612]
I use select2 with selectOnBlur. 

If user click my select and blur without choosing anything, it selects the first option. 

The behaviour I expect is to select text the user type, but if the user doesn't type anything, to do nothing. 

Adding a new category 
![Example](http://g.recordit.co/Kja3idV28f.gif)

And wanting to select nothing :
![Example](http://g.recordit.co/xmFOw8vRLG.gif)

Here is my configuration:

````
$(this).select2({
            maximumSelectionSize: 1,
            tags: ['One', 'Two', 'Three'],
            selectOnBlur: true
});
````

How can I do that ?

**Comment by kevin-brown** [comment]
This issue should have been fixed in 4.0.
