### ISSUE TITLE
Select2 breaks when Firebug opened

### ISSUE THREAD

**Issue by nxtpl** [select2/select2#2614]
Select2 control stops working when I open the Firebug panel in Firefox Nightly 34. The problem exists since few versions, so it may become serious when nightly goes into stable release.

**Comment by himel-ceps** [comment]
The issue opened Aug, 2014 but no solution ... it still happening ...

**Comment by piotr-cz** [comment]
Issue is stil unresolved in v4.0.1 and v4.0.2.

- on windows machine FF 45.0.2 installation it's ok,
- on linux with FF 45.0.1 and all extensions disabled is not, no output on console.
  Strange thing is that [examples](https://select2.github.io/examples.html) are working fine.

**Comment by kevin-brown** [comment]
> I was able to narrow this issue down to the use of the "firequery" plugin for firebug.

Does anyone see this issue without the "firequery" plugin?

**Comment by piotr-cz** [comment]
yeah, we have this issue without _firequery_ plugin installed and with disabled all FF extensions
