### ISSUE TITLE
Have a select2-closing event

### ISSUE THREAD

**Issue by red-0ne** [select2/select2#2619]
It would be great if just like select2-opening, we could execute code before dropdown is closed.

**Comment by pgifford** [comment]
This is in 4.0.  The events are:

* `select2:opening`
* `select2:open`
* `select2:closing`
* `select2:close`

**Comment by kevin-brown** [comment]
Looks like I forgot to close this earlier, but yes this is now done in 4.0.0 as `select2:closing`.
