### ISSUE TITLE
Unable to prevent virtual keyboard on mobile for multiple select

### ISSUE THREAD

**Issue by shorstki** [select2/select2#2627]
Property minimumResultsForSearch: -1 don't work on multiple select.
WIth standard selects it works fine.

**Comment by kevin-brown** [comment]
Merging into https://github.com/select2/select2/issues/1541.

**Comment by francescopapini** [comment]
$(document).on('touchend', function(){
      $(".select2-search, .select2-focusser").remove();
    })

will prevent keyboard from showing on multiple select
