### ISSUE TITLE
Remote select2('close') using API causes chosing highlighted option

### ISSUE THREAD

**Issue by shorstki** [select2/select2#2633]
It's **easy to repeat**:
1. Prepare a button with .`select2('close')` callout.
2. Turn on emulating mobile device in Chrome.
3. Select anything from multiselect dropdown (maybe same issue is in standard select).
4. Next, when it is selected and first element from the list is active after selection, use the close button.
Voila, active element was added to selected (choices). Despite the close button was clicked, not the option from list.

Same happens when you scroll on mobile device - when scrolling started on option, it is active (this shouldn't act like that - I assume that it's ontouchstart instead standard click or at least ontouchend), then you just close drop-down by prepared button and active goes to choices...

TL:DR: API 'close' should behave as ESC key but it works like ENTER is pressed.

**EDIT: I've found that commenting line 771**
```javascript
this.dropdown.on('click', this.bind(function (event) {
    if (this._touchEvent) {
        this._touchEvent = false;
        // this.selectHighlighted();
    }
}));
```
**Solves the problem.** Can't really figure it out what comment above is explaining
> // Waiting for a click event on touch devices to select option and hide dropdown
> // otherwise click will be triggered on an underlying element

But select2 works fine without this "feature" which causes the problem. I'm not creating pull request because I don't know why this code was added. In my local version I removed it (as the 'ontouchstart' events for much better user experience).

**Comment by kevin-brown** [comment]
This should now only happen if the `selectOnClose` (`selectOnBlur` in older versions) option is enabled.
