### ISSUE TITLE
Pressing tab when in select with dropdown active will select a value instead of silently navigating to next element

### ISSUE THREAD

**Issue by Slotos** [select2/select2#2637]
Steps to reproduce:

- visit: http://ivaynberg.github.io/select2/index.html#multi
- click on input field for Multi-Value Select Boxes example
- press tab

Expectation: selection moves to next element, selection stays empty, dropdown gets removed

Reality: selection moves to next element, top item gets selected, dropdown gets removed

**Comment by dandv** [comment]
:+1: on the UX proposed by @Slotos. This is how many popular systems do tag autocompletion: VanillaForums, Pinboard.in etc.

**Comment by kevin-brown** [comment]
I should mention that this has been fixed in Select2 4.0.0, the value is no longer selected by default and the dropdown is just closed. If you have `selectOnClose: true` set, then it will select it (because the dropdown closes).

**Comment by adrien-be** [comment]
@kevin-brown is correct, see a live demo of the fix on https://jsfiddle.net/t2t6shmn/
