### ISSUE TITLE
Relatively-sized hidden input placeholder text cutoff

### ISSUE THREAD

**Issue by hadronzoo** [select2/select2#264]
Relatively-sized hidden input placeholder text is cutoff until an option is selected. Setting the width of the select2 search field input after `select2` is called on the element fixes this issue: `$('.select2-search-field input').css('width', '100%')`. This only occurs on hidden input elements, not select elements.

**Comment by karstenpackmohr** [comment]
Thx for the idea. For me it worked with  `$('.select2-search__field').css('width', '100%');`

**Comment by kevineger** [comment]
Thanks for posting your answer. Preloading the css width worked great for me!

**Comment by ShudhPandit** [comment]
The jsfiddle

https://jsfiddle.net/shudhpandit/0h0qwtor/

Os: Windows 7
Browser: Chrome latest.
