### ISSUE TITLE
Can we override the default behavior where selected items (in multiselect mode) are removed?

### ISSUE THREAD

**Issue by vincent-polite** [select2/select2#2645]
Instead of removing the choices from the drop down on selection, I am interested in disabling/greying out the options that have already been chosen.

For example, in a States example:

Pacific Northwest
  * California
  * Nevada
  * Oregon

If I select California, I'd still want to see the complete list:

Pacific Northwest
  * California
  * Nevada 
  * Oregon

But with California greyed out or decorated in some customizable way.

I was wondering if select2 supports this or if you can consider a workaround to the default method of removing items from the drop down list?

Thank you,

Vincent

**Comment by tomhorvat** [comment]
I see that in 4.0 the selected item shows in list. Is there an option via parameters to change default behaviour?

I would like my tags enabled multiselect to remove selected items, just like it was in v3.

**Comment by betatester07** [comment]
Bump. I would really appreciate to be able to remove / hide selected items in 4.0.

Currently I am hiding them with CSS, but selection with keyboard is unusable because it assumes that elements hidden with display:none are still there.

**Comment by Frederic2003** [comment]
Nice feature to get indeed - I also notice that if you select again the tag, SELECT2-4 will remove it from the list..
