### ISSUE TITLE
select2 won't bind to ids with underscores

### ISSUE THREAD

**Issue by maurice-schleussinger** [select2/select2#2664]
As the title says: Select2 3.5.1 won't bind itself to any id which contains an underscore. Is this intended behaviour?

**Comment by M4urice** [comment]
Can somebody check if this is still relevant? I don't have the needed setup right now.

**Comment by pedrofurtado** [comment]
Sorry, the `3.x` version is not maintained anymore. But feel free to fork the repo and fixes what you need. But if this bug still appears in 4.x version, reopen the issue and send us a JSFiddle example simulating this scenario. PR's are welcome too. We can help much more with a example code :+1:
