### ISSUE TITLE
format result like a table/grid

### ISSUE THREAD

**Issue by baurez** [select2/select2#270]
Hello,

I would like to show the result list like a gridview... a table with multicolumn value...

I can do that with a FORMAT like this: <table><tr><td>Value1</td><td>value2</td></tr></table>

But mys column aren't aligned...they don't have the same width...

I could set the witdh attribute... but if a value is bigger than this value...the cells increase...and misalignment...

There is an easy way to do this ?

And if I would set in the header of result a first line with the name of each column, how could I do this ?

Thanks :)

**Comment by johndoefromhere** [comment]
@kevin-brown Hello, it looks like @trebuchetty 's solution stopped working.

https://jsfiddle.net/76amkyfo/

**Comment by trebuchetty** [comment]
Can you elaborate? The jsfiddle you provided isn't relevant.

**Comment by johndoefromhere** [comment]
@trebuchetty It looks like `format2` function is not called at all (no output in console).

It'd mean that options formatResult and formatSelection do not work in 4.0.1.

**Comment by wdog** [comment]
They are now in version **4.*** `templateResult` and `templateSelection`
