### ISSUE TITLE
Pasting multiple values into Select2 without createSearchChoice

### ISSUE THREAD

**Issue by TrevorBurnham** [select2/select2#2705]
If you create a Select2 widget with `tags` and no `createSearchChoice`, then you can paste multiple values with ease:

http://codepen.io/TrevorBurnham/pen/coeJv (paste "Angels,Demons,")

But if you create a Select2 widget with `data` and no `createSearchChoice`, the same paste will not work, and the values must be entered one at a time:

http://codepen.io/TrevorBurnham/pen/lcbsj

There's a fairly simple way to make pasting work here: Provide a `createSearchChoice` function that tells Select2 how to read each of the tokenized values in a non-tagging context, e.g. by iterating through the `data` options and returning the first one whose `text` matches `term`. I'd like to see Select2 do this by default, just as it provides a default `createSearchChoice` function when you use `tags`: https://github.com/ivaynberg/select2/blob/c5c42eaf72d55e7b802b7efc9a5a6b192a88647d/select2.js#L1058-L1060

**Comment by dc-artemis** [comment]
+1 on this request

**Comment by kevin-brown** [comment]
This has been greatly changed in 4.0.0 and now tokenization works as expected in this case.
