### ISSUE TITLE
Add option for preventing flipping the dropdown upward

### ISSUE THREAD

**Issue by powmedia** [select2/select2#2710]
In some cases (e.g. when using on mobile) it can be a better experience to restrict the dropdown from going upwards.  However the best way I've seen of doing this so far involves changing a couple of lines of code within the select2 source - see kei's answer here:

http://stackoverflow.com/questions/19983601/prevent-select2-from-flipping-the-dropdown-upward

It would be great if there was a config option to do this.

**Comment by alexington** [comment]
Hi, I would still love to see this as an option.  It seems to be a feature that gets requested fairly frequently.  Any chance this might be revisited now that 4.0 is out?

**Comment by JacobEvelyn** [comment]
Same here!

**Comment by axelrigaud** [comment]
me too!

**Comment by joakimkm** [comment]
Same here!

**Comment by amustaine** [comment]
+1

**Comment by aivaras-b** [comment]
+1

**Comment by sentiasa** [comment]
+1

**Comment by aleksandrakurek** [comment]
+1

**Comment by ilibilibom** [comment]
+1

**Comment by alexweissman** [comment]
@ilibilibom there is a 👍 option that you can use to "upvote" issues/feature requests on the top comment.  Please use that instead of adding a "+1" comment.

**Comment by alexweissman** [comment]
There is an open PR for this feature: #4618.  We can consider this for inclusion at some point.

**Comment by andreivictor** [comment]
I had the same need and I couldn't wait till this PR is merged, so I've moved the code from this PR into an extension, that overrides the original plugin function which handles the dropdown positioning.
The following code should be placed after the plugin's main file:
https://jsfiddle.net/byxj73ov/

**Comment by alexweissman** [comment]
@andreivictor you should post community mods to the [forums](https://forums.select2.org/c/ecosystem).  They will get lost here.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
