### ISSUE TITLE
Tab Incorrect Behaviour

### ISSUE THREAD

**Issue by pete-experimenter** [select2/select2#2718]
* Open a native select from http://jsfiddle.net/me3bo81p/,
* Press Tab.

The select closes but still has focus. The next Tab move focus to the next element.
However, for select2 the first tab moves the focus to the next element, which I believe is wrong.

Could this be fixed?

**Comment by rywall** [comment]
@kevin-brown I think this is fixed?

**Comment by kevin-brown** [comment]
Yup, looks like it.

Select2 now matches what Webkit does by default (just close the dropdown if it's open).
