### ISSUE TITLE
idSuffix for select/option replacement

### ISSUE THREAD

**Issue by straeger** [select2/select2#2727]
Hello,

I have currently an issue with replacement of a <select> <option> element, 
I need a possibility  to customize the generation of the idSuffix for the generated 
```<ul "select2-results-[counter]"> <li>```  which the user interacts with.

In initContainer ( https://github.com/ivaynberg/select2/blob/master/select2.js#L2084 ) the function nextUid which uses the counter function ( https://github.com/ivaynberg/select2/blob/master/select2.js#L105 ) is used to generate the id for the replacement. 

The Problem with the generated ID is that in our dynamic generated UI which gets UI Unit testet we can not be sure that it is always the same. So if the ID can not be found the unit test will fail.

Are there any outstanding features requests planned regarding this issue?

**Comment by kevin-brown** [comment]
This issue has been fixed in later versions of Select2. The id is now generated using a consistent format based on whatever unique values Select2 can latch on to.
