### ISSUE TITLE
Placeholder styling?

### ISSUE THREAD

**Issue by jesperlandberg** [select2/select2#2738]
Is there any way to set css styles of select placeholders? It works on my "non select2" -selects/inputs but not in the ones using select2.

**Comment by CFXd** [comment]
In response to the original issue, I'm still finding it impossible to style the select2 placeholder without affecting the other values.

Two years later, has anyone managed to figure this out or should I pursue another JS library for select styling?

**Comment by kevin-brown** [comment]
In Select2 4.0...

For a single select, the text is in a span with the class `.select2-selection__placeholder`.

For multiple selects, you can override the [browser placeholder on the search box](http://stackoverflow.com/q/2610497/359284).
