### ISSUE TITLE
dropdownAutoWidth : true - selected option is not after initialize

### ISSUE THREAD

**Issue by santaclaus21** [select2/select2#2741]
I'm doing standard initialize on select (with selected options). 
$("select.select2").select2();

In that way, selected options are choosen, but, when I'm trying to initialize in this way...
$("select.select2").select2({dropdownAutoWidth : true});

So, I can't use that option, instead I have to use: select2({dropdownCssClass : 'bigdrop'}) with specified width to get wornking selected="selected"

**Comment by pascalBokBok** [comment]
according to this stackoverflow you have to quote true. However it's working fine for me now without - perhaps some changes. http://stackoverflow.com/questions/20951363/select2-dropdown-auto-width-not-working-properly

**Comment by Glideh** [comment]
This doesn't seem to work at all since version 4.
My workaround is for now:
```javascript
$("select.select2").data('select2').dropdown.$dropdown.addClass('bigdrop');
```

_For the record_
```css
.bigdrop {
    width: 250px !important;
}
```

However I can see the `dropdownAutoWidth` related code still there in this version.
This shouldn't be too hard to fix, is it ? (Maybe I could make a PR)
