### ISSUE TITLE
formatNoMatches doesn't allow mouse actions or href

### ISSUE THREAD

**Issue by abusedmedia** [select2/select2#276]
By using select2 component, I would like to render a custom no-matches message with a href link (e.g. 'add new' with a modal or something).

Unfortunately select2 kills every custom mouse action.

Any workaround?

Thanks for this awesome component!

Fabio

**Comment by aashanand** [comment]
+1

**Comment by kevin-brown** [comment]
Closing this off as this is fixed in 4.0.0.

**Comment by bluebinary** [comment]
If anyone is currently stuck using version 2 or 3 of Select2, you can always make a small change to the library itself, for example, modify select2.js, changing the line:

`this.dropdown.on("click", killEvent);`

To the following:

`if(typeof(this.opts.dropdownClickHander) == "function") { this.dropdown.on("click", this.opts.dropdownClickHander); } else { this.dropdown.on("click", killEvent); }`

Then when you initialize an instance of the Select2 library, just add a `dropdownClickHandler: function(event) {...}` callback to the initialization options hash. This will allow you to capture clicks in the drop-down when they are not captured by the library itself (for example when a user clicks on a matching option 'lozenge' element). With the custom event handler callback for for `this.dropdown` element, you can of course choose how to respond to the event according to your own needs, for example by performing some logic first, then calling `event.stopPropagation()` and/or `event.preventDefault()`.

This one-line change to the library code (around line 742 of select2.js for version 3.5.1 of the library, similar locations for other versions), worked well in our case, and may be of help to others who for whatever reason are still reliant on older versions of the library.
