### ISSUE TITLE
Is it possible to set visible rows count

### ISSUE THREAD

**Issue by indapublic** [select2/select2#2762]
Hello!
I have 8 rows in select. But select2 is displaying 7 rows with scroll. Is it possible to increase visible rows count? I cannot find it option in documentation

**Comment by JacobEvelyn** [comment]
I just wrote a plugin to dynamically increase the number vertical size of the dropdown to be able to see more rows without knowing the exact height for a CSS solution: https://github.com/panorama-ed/maximize-select2-height
