### ISSUE TITLE
Newline when item is selected

### ISSUE THREAD

**Issue by sbosman1** [select2/select2#2764]
Hello,

When an item is selected it's automatcally streches the textbox with an extra line instead of stay on the same height, when the size is fixed specified: see example: http://jsfiddle.net/g332c2ru/9/

is this a issue? because when an item is selected and it's to long we don't want a new line is created. I tried with css to create an solution but nothing worked. 

greetings,

Sander

**Comment by transputec** [comment]
have you found the resolution of this issue..

**Comment by Apostropher** [comment]
I'm experiencing the same problem. Is there a known resolution?
