### ISSUE TITLE
3.5.2 Initial Select + Key Navigation Broken With "closeOnSelect : false" 

### ISSUE THREAD

**Issue by pete-experimenter** [select2/select2#2783]
**Steps to Reproduce**
1. Go to http://jsfiddle.net/EHzcc/360/.
2. Click on the select.
3. The first element is not selected and down arrow navigation key does not work, i.e. the first item in the drop down is not selected on the key press.
![image](https://cloud.githubusercontent.com/assets/6091200/4878392/daf2aaac-630a-11e4-9feb-d75270cd4382.png)

3.5.1 version http://jsfiddle.net/EHzcc/361/ works as expected.
![image](https://cloud.githubusercontent.com/assets/6091200/4878400/fc38dbc8-630a-11e4-96cc-4cbaff4a5e6e.png)

**Other Features Broken From the Previou Version**
* Type in a value, so that only one suggestion available in the dropdown, press tab. In the previous version this would select the single item. 
In the above 2 jsfiddles that would mean typing "b" in the select and pressing Tab. 

**Browsers Tested**
* Win Chrome 38.0.2125.111
* Win Firefox 33.0.2

**Comment by hgpb** [comment]
I updated the issue with the correct includes to version 3.5.4.
http://jsfiddle.net/EHzcc/667/

I understand this is a closed issue now, however is there a workaround ?

**Comment by hgpb** [comment]
Ok I found line 3351 of select2.js and updated to:

if (this.highlight() == -1 && noHighlightUpdate !== false){
    self.highlight(0);
}
