### ISSUE TITLE
Allow to add new values when no match is found

### ISSUE THREAD

**Issue by pjfsilva** [select2/select2#2787]
I don't know if this is already possible (from docs doesn't seem so) or if this fits the purpose of select2 but here's my "feature request":

Taking the basic example I would like to be able to type a new value like "France" that doesn't match anything and fill the input with that value. Currently that value is discarded.

The usability reasoning behind this is that my user could be in a hurry filling the form and just wants to type something like "the state north of california" and save that value. At a later stages he can review the input and alter it to a correct state name. Still, sometimes it's useful to get the autocomplete/list of known values to be faster to select some of those values, so the user really requires both behaviors. 

The only change that needs to be done is just to allow for unknown values to be entered, instead of discarding them.

**Comment by theunexpected1** [comment]
+1 for this.
This feature was there in the earlier versions ( as per http://stackoverflow.com/a/14945143/1079817 )
Can this be re-opened, or is there a way to achieve this?

**Comment by kevin-brown** [comment]
> This feature was there in the earlier versions

It's still there, check the answer beneath it.

http://stackoverflow.com/a/30021059/359284

**Comment by theunexpected1** [comment]
Thanks for your quick response, @kevin-brown, that's correct. You had even answered the same earlier, my bad - Tagging feature it is.
Cheers, and thanks for this plugin!
