### ISSUE TITLE
Using multiple returns no matches found on second selection

### ISSUE THREAD

**Issue by dyardyGIT** [select2/select2#2799]
Select2 works find with my ajax source when multiple=false.
If multiple is set to true and using custom query the 2nd search returns the data from an ajax method correctly but the select2 control returns no matches found.
I know there were matches returned but the control says no matches.

Once i get the results from the ajax call i pass in via qurey.callback(results: $.parseJson(results)}); but still the control doesn't recognize this second search.

My code looks like following...ideas?

``` html
<input type="hidden" class="typeahead" id="txtCountry" title="">
```

```
$("#txtCountry").select2({
        placeholder: 'Select',
        allowClear: true,
        multiple:true,
        minimumInputLength: 3,
        id: function(e) { return e; },
        query: function(query){                
            self = this;
                $.ajax({
                    global: false,
                    type: 'POST',
                    url: personUrl,
                    contentType: 'application/json',
                    dataType: 'json',
                    data: getData(query.term, 'lastName'),
                    success: function(results) {                            
                        query.callback({ results: $.parseJSON(results) });
                    },
                    error: function(jqXHR, textStatus) { alert(textStatus); }
                });
        }
```

**Comment by pappgergely** [comment]
I've just had the very same problem, and found out that I didn't fill out the value attributes of the <option> elements (they were the same), so select2 thought that after the first one was selected, all the others were selected too.

**Comment by kevin-brown** [comment]
@pappgergely If you can answer any of the questions in https://github.com/select2/select2/issues/2799#issuecomment-67666391 that would be useful.

**Comment by pappgergely** [comment]
@kevin-brown Here you are:
* Steps to reproduce the issue: Create a <select multiple></select> element with <option>s within it. All the options should have empty value attributes.
* It's not a bug, but a developer oversight (in my opinion)
* Browser & OS: Mac OSX + Chrome latest, Firefox latest; browser behaviour was the same.
* Versions: Select2 3.5.2 and jQuery 1.9.0

**Comment by kevin-brown** [comment]
@pappgergely That looks like the issue described in https://github.com/select2/select2/issues/1002, which was fixed in 4.0.

I'm not sure if that is the same issue as the original problem reported by @dyardyGIT.

**Comment by tutNichts** [comment]
@pappgergely @kevin-brown @dyardyGIT @samthomson Did you already found a fix for this problem?

**Comment by samthomson** [comment]
Sadly not, used a different plugin that I could extend myself.

**Comment by tutNichts** [comment]
@samthomson Okay, which plugins are you using now?

**Comment by reinhardholl** [comment]
I know this might be an old issue, but I had a similar problem and it turns out that all my "id" fields were the same. Once I gave unique Id's the problem went away.

**Comment by alexweissman** [comment]
We now have more thorough documentation on the data format that Select2 expects: https://select2.org/data-sources/formats

**Comment by Muirski2992** [comment]
@reinhardholl How can I buy you a beer my friend?! Thanks for posting, this saved me from a lethal headache!
