### ISSUE TITLE
Item is not selectable from autocomplete

### ISSUE THREAD

**Issue by mg-arrow** [select2/select2#2800]
I am using aucomplete with ajax code in order to populate the date for the select2 plugin.

I am using verion 3.5.2 and local html page for testing.

I type the part number and ajax call brings the products from the service via json and populates properly in the dropdown.

Unfortunately, items are not selectable, In fact event select2-selecting is not firing at all.

See screenshot attached.

![screenshot](https://cloud.githubusercontent.com/assets/8698512/4999205/7d9892ba-699d-11e4-8dbc-d1d301a27cc0.JPG)

Why would I get this behavior ? Is it related to json data coming from web service ?

regards

Mikhail

**Comment by peterbe** [comment]
I have the same problem. I use select2 3.4.5 and I thought upgrading would help but I doubt that since you use 3.5.2.

**Comment by kevin-brown** [comment]
We can't do much without a test page. There are a lot of variables here that we need to isolate, and it's difficult to do when it's only not working for a select few people.

If you can build out a jsfiddle (use the echo url) or link to a page where it doesn't work, then we can start working towards figuring out what is wrong.

**Comment by shoaibshakeel381** [comment]
i'm having the same issue. Previously i couldn't type in search box either. But after removing `tabindex` from modal div. Now i can type into it. But i can't select items by clicking on them. They are not clickable.

**Comment by pedrofurtado** [comment]
Sorry, the `3.x` version is not maintained anymore. But feel free to fork the repo and fixes what you need.
