### ISSUE TITLE
Small fix needed when control destroyed.

### ISSUE THREAD

**Issue by jamesDin** [select2/select2#2804]
Hi there and thank you for this cool control :-)
I love this control, it has strong API and written very good.  I managed to use this control to do my need in dynamic ways and for that I use "destroy()" method which works great.
One small fix would be very helpful:

The problem is when the server takes couple seconds to respond and the dropdown closed and opened again by the user.  All works good except one place in code which fails and it's because I destroyed and created a new dropdown based on ajax results.

I used: Version: 3.5.2 Timestamp: Sat Nov  1 14:43:36 EDT 2014.
Please check line 1787:

```
if (!this.opened()) {
    this.search.removeClass("select2-active");
    return;
}
```

Checking "opened()" method:

```
opened: function () {
    return (this.container) ? this.container.hasClass("select2-dropdown-open") : false;
}
```

You see the check if "this.container" exist? somehow (and it's good) you do the test because it might not be there. Same thing about this line 1788 - "this.search" might be null and that's exactly my problem.
Since in the next line you do "return;", all is perfect just that small crash.

Just please change this line 1788 (it will not ruin anything :-)):

```
 //this.search.removeClass("select2-active");
 if (this.search) { this.search.removeClass("select2-active"); }
```

Just to make sure "this.search" is still an exist because sometimes it's not at this code of line.

Thanks alot :-)

**Comment by pedrofurtado** [comment]
Sorry, the `3.x` version is not maintained anymore. But feel free to fork the repo and fixes what you need.
