### ISSUE TITLE
Select focus failing second time in Chrome

### ISSUE THREAD

**Issue by dnohr** [select2/select2#2805]
Hi,

I'm having some issues with the select2 dropdown in Chrome.
- First time after page load the focus works great when opening the dropdown
- Second time there is no focus in the input field from the same dropdown

I was trying to debug it with checking the select2 events, first time opening the dropdown it shows it correct by firering the "focus" and then "open" event. Second time it doesn't show the "focus" event, only "open" and then mysterious "focus" when closing the dropdown.

I was trying different hacks, but didn't seems to work. I have two drop downs on the page with around 160 options each. I'm populating the drop down first and then adding on the select2 functionality to the select tag. It works great in Safari and mobile browsers including Chrome for iPad.

Any suggestions?

Thanks.

**Comment by naderghanbari** [comment]
We're having exactly the same problem. Appreciate if anyone can help.

**Comment by Jafu** [comment]
Just in case somebody else still has the problem. We applied a css-animation-rule on the `<input>` element:

`transition: all 300ms`

Removing or specifying the properties explicitly, in our case `transition: background-image 300ms, box-shadow 300ms, color 300ms,background-color 300ms,border-color 300ms;`, fixed the focus problem.

I don't know which property exactly caused this issue. But its none of which we cared for.

**Comment by tureey** [comment]
@Jafu I have the same problem and I couldnt fix it... Have you find another solution?

**Comment by pedrofurtado** [comment]
Sorry, the `3.x` version is not maintained anymore. But feel free to fork the repo and fixes what you need. But if this bug still appears in 4.x version, reopen the issue and send us a JSFiddle example simulating this scenario. PR's are welcome too :+1:
