### ISSUE TITLE
"More results" problem with "abort()" ajax request.

### ISSUE THREAD

**Issue by jamesDin** [select2/select2#2806]
Hi again,

If you set a delay of 3 seconds for example in the server-side for ajax request, scrolling down to get another "More" request and scroll up and down again, it will "abort()" previous request and set a new one.
After that "abort()" logic, here is the bug I see, line 1660:

```
 self.opts.populateResults.call(this, results, data.results, {term: term, page: page, context:context});
```

data.results is undefined.  And here is the object actually after abort():

```
 data: {
      errorThrown: "abort",
      hasError: true,
      jqXHR: Object,
      textStatus: "abort",
      __proto__: Object 
 }
```

From this moment, it crashed on 'length' in line - 947:

```
 for (i = 0, l = results.length; i < l; i = i + 1) { ... }
```

since "result" is undefined.

If I'm scrolling down, and waiting for "more data" to come, it works but if I scroll up and down again, it crash.  I hope I explained it good :-)

Here is my fix (line 1657 --> add " || data.hasError"):

```
 // ignore a response if the select2 has been closed before it was received
 //if (!self.opened()) return;
 if (!self.opened() || data.hasError) return;

 self.opts.populateResults.call(this, results, data.results, {term: term, page: page, context:context});
```

Big thanks for your help.

**Comment by pedrofurtado** [comment]
@jamesDin The version 3.x is not maintained anymore. But if this bug still occurs in 4.x version, feel free to reopen the issue and report to us a JSFiddle example simulating this scenario.
