### ISSUE TITLE
jquery(selector,opener.document) doesn't work

### ISSUE THREAD

**Issue by lalunalu** [select2/select2#2814]
`jquery(selector,opener.document).select2("data",...)` doesn't work
while
`opener.document.jquery(selector).select2("data",...)` does work

when opening a window using javascript

same goes for the val option

any other jquery function works fine

**Comment by pedrofurtado** [comment]
The issue is related to 3.x version, but the version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
