### ISSUE TITLE
How to access data attribute of selected option on change event

### ISSUE THREAD

**Issue by amt925** [select2/select2#2827]
I'm looking to grab a data attribute on the change event. What is the recommended way to access that?
I saw this https://github.com/ivaynberg/select2/issues/2658 but I'm just not getting it.

``` html
<select class="form-control" name="product" id="product">
    <option></option>
    <option value="123" data-product-name="first">Test 1</option>
    <option value="456" data-product-name="second">Test 2</option>
    <option value="789" data-product-name="third">Test 3</option>
</select>
```

``` javascript
 $('#product').select2()
    .on('change', function(e) {
        if (e.added) {
            console.log(e.added.element.data('product-name')); // undefined                
        }
 });
```

Any help would be appreciated! Thanks!

**Comment by mellat** [comment]
I am trying this solution but getting :` TypeError: e.added is undefined`

**Comment by Tagirijus** [comment]
Had the same problem. Try `e.target.value` instead. Worked for me.

**Comment by Sohail-Ansari** [comment]
$('#autofill').select2({
			placeholder: 'Cari...',
			 minimumInputLength: 2,			 
			ajax: {
			  url: 'http://127.0.0.1:8000/filler',
			  dataType: 'json',
			  delay: 250,
			  processResults: function (data) {				  
				return {
				  results:  $.map(data, function (item) {
					return {
					  name: item.descriptions,
					  text: item.tagnames,
					  id: item.id
					}
				  })
				  
				};
			  },
			  cache: true
			}
		  });

we can access 'id' and 'text' from results, what to do to access any third key-value like 'descriptions'. I can successfully access 'text' via `e.target.value`, but getting no clues of accessing 'descriptions'.

**Comment by engacs** [comment]
var $eventSelect = $("#autofill");
            $eventSelect.select2({
           // minimumInputLength: 1,
            ajax: {
                url: site.base_url + "/suggestions",
                dataType: 'json',
                quietMillis: 15,
                data: function (term, page) {
                    return {
                        term: term,
                    };
                },
                results: function (data, page) {
                    if (data.results != null) {
                        return {results: data.results};
                    } else {
                        return {results: [{id: '', text: 'No Match Found'}]};
                    }
                }
            }
        });
        $eventSelect.on("change", function (e) {
            console.log(e.added.text);
            
            });
