### ISSUE TITLE
Select2 popup doesn't close when inside iframe

### ISSUE THREAD

**Issue by betonetotbo** [select2/select2#2840]
- Create a HTML named main.html
- Put 2 iframes
- iframe 1, put a html with an input
- iframe 2, put a select2
- run main.html
- click to open select2 
- leave select2 open and try to click in the input at the other iframe
- you will not able to click on it to begin typing.

Here is the example:
- using select2 3.5.2

https://drive.google.com/file/d/0B5YSKbzALc3fdzRDSkh2TlZZNEk/view?usp=sharing

I suspect the problem is comming from

initContainer function, this is the code:

```
  this.search.on("blur", this.bind(function(e) {
            // a workaround for chrome to keep the search field focussed when the scroll bar is used to scroll the dropdown.
            // without this the search field loses focus which is annoying
            if (document.activeElement === this.body.get(0)) {
                window.setTimeout(this.bind(function() {
                    if (this.opened()) {
                        this.search.focus();
                    }
                }), 0);
            }
        }));
```

**Comment by huang-x-h** [comment]
Does this issue has any plan? We have the same problem, the iframe content is third-party, so do not in the same domain. Now, we use `$(window).blur` to close all `select2` component.

**Comment by alexweissman** [comment]
Since #4608 has an actual working demonstration of the problem (a Google Drive link containing a zip file of code is **not acceptable**), I'm going to close this and leave #4608 open as the canonical issue.
