### ISSUE TITLE
Docs for createTag

### ISSUE THREAD

**Issue by bryanaka** [select2/select2#2843]
in this example: http://ivaynberg.github.io/select2/#code_e11

`createSearchChoice` has a second argument that is the matches to the input given to select2 (matches that are not being created on the fly)

But in the documentation, it does not provide any kind of information that this argument is provided to the function. Is this intentional, or can I assume it is safe to rely upon that argument being there?

**Comment by SKozar** [comment]
I have such task to create choices if not found on server side. It isn't impossible to create it by myself. But it would be great if you will bring this option back.

**Comment by almogdesign** [comment]
Is createSearchChoice supported in version 4?

**Comment by kevin-brown** [comment]
As noted both [here](http://stackoverflow.com/a/30021059/359284), [here](http://stackoverflow.com/a/30019966/359284), and the [release notes](https://github.com/select2/select2/releases/tag/4.0.0-beta.2), `createSearchChoice` was renamed to `createTag` in 4.0.

**Comment by almogdesign** [comment]
@kevin-brown thanks, quick feedback the release notes are a bit hidden I was on the main site. Might be a good idea to post a link on the main page

**Comment by kreintjes** [comment]
Also, the createSearchChoicePosition/createTagPosition seems to be removed: #3420

**Comment by alexweissman** [comment]
Documentation for `createTag` is now available here: https://select2.org/tagging#tag-properties
