### ISSUE TITLE
Need an additional custom class to select2-container 

### ISSUE THREAD

**Issue by justin-johnn** [select2/select2#285]
We need an additional custom class to select2-container container to easily override the inner classes styles.

Like 

```
$("#e2").select2({
customClass: "Myselectbox",
});
```

So that corresponding container will formed as 

```
<div class="Myselectbox select2-container select2-container-multi">
```

So that I can override an inner classes like `.Myselectbox .select2-choices` in CSS.

Generally this will  help to override the `textbox`(ul.select2-choices) style.

**Comment by imlunek** [comment]
I am using `version 4.0.2`. And on using `containerCssClass` it adds class to `select2-selection`. I guess the class is supposed to be added to the main wrapper `select2-container`.

**Comment by Wilwarin** [comment]
The issue @imlunek mentioned still persists in 4.0.3. Is it intentional?

**Comment by imlunek** [comment]
The `containerCssClass` thing seems to work properly with stable version.

**Comment by Wilwarin** [comment]
@imlunek is there a way to add css class to the `select2-container` element? the `containerCssClass` adds the class to `select2-selection`

**Comment by mrlevitas** [comment]
same issue

**Comment by berkandirim** [comment]
If you're using data attributes:

```
        $('[data-container-css-class]').each(function() {
           var className = $(this).attr('data-container-css-class');
           var container = $(this).next('.select2-container');
           container.addClass(className);
           container.find('.select2-selection').removeClass(className);
        });
```

**Comment by lucasumberto** [comment]
Is there any difference between containerCssClass and dropdownCssClass?
For me it looks like a bug.. 
Please fix the containerCssClass if it's realy doing the same thing as dropdownCssClass!
doing it with js is so ugly...

**Comment by pranavk** [comment]
Facing the same problem; using containerCssClass adds the class to select2-selection, not select2-container <span>.

**Comment by andrejpavlovic** [comment]
This will do the trick:
```javascript
$('select').select2().data('select2').$dropdown.addClass('my-container');
```

**Comment by alexweissman** [comment]
> add class to the main wrapper select2-container

Since this appears to be a fairly common request, I'm going to reopen this as a feature/documentation request.

**Comment by ojathelonius** [comment]
@andrejpavlovic you **should not** call `.select2()` before chaining it with `.data('select2').$dropdown` as this causes issues with default select2 events.

e.g., calling `$('select').select2()` in an event handler on a single select with `allowClear = true` will prevent the empty option to be removed from the dropdown list, and the clear icon won't be displayed either.

**Comment by 10w042** [comment]
> @imlunek is there a way to add css class to the select2-container element? the containerCssClass adds the class to select2-selection

In case anyone was wondering, there's hacky approach to do this, requires using the `theme` option.

```js
$('my-select').select2({
    theme: 'default your-container-class'
});
```

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:

**Comment by yourtallness** [comment]
I understand the requirement in principle, however it did end up working better on the selection than on the container, at least for me.

I got weird behaviour when styling the container, e.g. giving it button styles and clicking on it would highlight the internal selection element instead of the whole button.

Whereas if I styled the selection as a button the behaviour was as expected.

**Comment by pankajkrravi** [comment]
Hi everyone i need help
Currently search in dropdown textbox is based on name , i want tomake it search based on id nad name both: 
![Screenshot from 2020-06-18 11-54-52](https://user-images.githubusercontent.com/38873221/84987889-a6b2cf80-b15e-11ea-9e45-ed862f537a5a.png)

**Comment by ialarmedalien** [comment]
@pedrofurtado This issue should be reopened -- like others above, I'm having to do all sorts of horrible tacky css workarounds due to an inability to style the base container. I've put in a PR for adding a class to the container.

**Comment by kevin-brown** [comment]
Locking this as resolved, not because we added a new option to Select2 to support this but because the current official stance is that we will not be adding a native option for this. We have started to remove some of these extra options because they start to add up over time, so we're continuing to not add this one since it's an edge case that people have managed to work around as-needed.
