### ISSUE TITLE
Clearing value using .select2('val', '') missing non-breaking space in .select2-chosen element

### ISSUE THREAD

**Issue by JeroenvdV** [select2/select2#2850]
When a new container is created, the .select2-chosen span element contains &#160;, a non-breaking space. This helps the container not collapse into a tiny sliver. But when a value is chosen, and later cleared using the $element.select2('val', '') or ('val', null) functions, it is missing this non-breaking space which causes problems. I can add the nbsp manually but it should be done automatically.

**Comment by kevin-brown** [comment]
This has been fixed in 4.0.0.
