### ISSUE TITLE
Remove ajax call debouncing (make optional?) for infinite scroll and empty query term

### ISSUE THREAD

**Issue by AlexanderLeonov** [select2/select2#2857]
Hi!

I propose to remove debouncing for cases in subject.

In case of loading next page of data for infinite scroll I don't see what we are waiting for because user didn't actually change anything in search conditions.

As for empty term... It's not so simple as first case. In my project we have two sources of data for select2: 1) let's call it local client data (quite rarely read from secondary service and cached on client); and 2) data from "main" ajax call against **not empty** user's query term (call to that service with an empty query will return an error so this is completely meaningless). So, when user initially opens dropdown he will always see only local data but in this scenario debouncing of transport function call will just delay appearing local data which actually is available instantly. This is what I propose to change. Hope I explained it clear enough.

**Comment by kevin-brown** [comment]
This should be fixed in 4.0.0.
