### ISSUE TITLE
Documentation bug in "Loading Remote Data" section

### ISSUE THREAD

**Issue by flyingL123** [select2/select2#2863]
I think there is a small typo in the documentation here:  http://ivaynberg.github.io/select2/

I'm referring to the "Loading Remote Data" section within the notes for the initSelection function.

It states "...using its formatResult renderer", but I think it should say "formatSelection renderer" instead.

**Comment by kevin-brown** [comment]
Yes, it probably should say that.

I'm going to close this off though, as it will eventually get fixed if we ever roll another 3.5.x release.
