### ISSUE TITLE
Issue with Select2 inside a pop-up

### ISSUE THREAD

**Issue by Anuvind** [select2/select2#2873]
Hey, the plugin looks great on the website. I have used the plugin inside a pop-up which show/hide based on jQuery clicks on an anchor.
The issue is I need to close the pop-up when user clicks anywhere in the body except the pop-up.
I have written the below code to achieve the same.

```
jQuery(document).mouseup(function(e) {
    if(jQuery(e.target).closest('.callback-details').length == 0) {         
        $('.callback-details').slideUp('500ms');            
     }       
});
```

The structure of select2 generates outside of my pop-up during run time. Therefore the pop-up is getting closed even when the user clicks select2 box inside the pop-up. 
Any suggestions for this issue?

**Comment by mediastuttgart** [comment]
Hi, is there any documentation on how to use the `AttachContainer module`? I've included the full version of select2, but i can't get this working. I'm having the select2 elements inside a popup(magnific-popup), but due to some reasons the search input can not be focused. It will work when using `dropdownParent`to attach the dropdown somewhere else, but then the position css of the dropdown is incorrect.

**Comment by kevin-brown** [comment]
Here's a jsfiddle that shows how to decorate the `dropdownAdapter` with the `AttachContainer` decorator.

http://jsbin.com/yisetuhuji/2/edit?html,js,output

I've also included the `DropdownSearch` decorator in there considering how commonly used it is.

**Comment by jaredevantabor** [comment]
Thanks @kevin-brown, this is super helpful. Follow up question: Is there a way to implement your example without the ```DropdownSearch``` decorator? When I try to do it, I get the following errors on the console: 
```
Uncaught TypeError: undefined is not a function select2.full.js:4855 
S2.define.Select2._bindAdapters select2.full.js:4748 
S2.define.Select2 select2.full.js:5794 (anonymous function)
```

**Comment by brunoDegaspare** [comment]
@kevin-brown Thank you very much for sharing this!

**Comment by andreyvolokitin** [comment]
> In 4.0, you can use the AttachContainer module to attach the dropdown to the parent container, but keep in mind that **this prevents things like dropping up** 

@kevin-brown, is this still the case? And if so, how hard it will be to fix this?
