### ISSUE TITLE
select2 4.0 - dropdownCssClass option not working

### ISSUE THREAD

**Issue by santaclaus21** [select2/select2#2879]
It looks like dropdownCssClass: "bigdrop" option not workin in 4.0 (?). It was working fine in 3.5.x

**Comment by artknight** [comment]
is this fixed?

**Comment by kevin-brown** [comment]
Not yet, but we are planning on adding a compatibility module for the CSS options before the final first release candidate goes out.

**Comment by kevin-brown** [comment]
Scratch that, we are no longer planning on adding these options by default due to time constraints. This can easily be done by creating a decorator for the `dropdownAdapter` that overrides the `render` method.

**Comment by jelhan** [comment]
Is there any example how to write a decorator for an adapter in select2 4.0?

**Comment by jelhan** [comment]
@kevin-brown I didn't figured out yet how decorators are working. But I was implement support for `adaptDropdownCssClass` behavior by templateResult option: http://jsbin.com/bucawidomi/4/edit What is the benefit of using a decorator therefore?

**Comment by kevin-brown** [comment]
@jelhan for those wanting to change the background color of the option, for instance.

Reopening this as I might as well build a quick set of compatibility modules.

**Comment by fk** [comment]
Yay! :+1:

**Comment by ghprod** [comment]
any update for this?

i've got error `No select2/compat/dropdownCss` when using option `dropdownCssClass`

Thanks

**Comment by kevin-brown** [comment]
> i've got error No select2/compat/dropdownCss when using option dropdownCssClass

This is only available if you are using the full build of Select2 (`select2.full.js`).

**Comment by ghprod** [comment]
@kevin-brown Thanks for your info :+1:

**Comment by johnsona9** [comment]
I am having an issue with the containerCssClass. I'm trying to apply the select2-skins from https://github.com/themepixels/select2-skins. The dropdownCssClass works perfectly, however the containerCssClass does not get applied.

**Comment by Bakudan** [comment]
@johnsona9 Same issue, did you find any solution ?

**Comment by kevin-brown** [comment]
@johnsona9 [select2-skins](http://ui.themepixels.com/select2-skins/) is _old and outdated_, it is designed for Select2 3.x and is not guaranteed to work for newer versions (4.0.0 and up).

The fact that it might _partially_ work with newer versions is impressive, but it's not a bug in Select2.

**Comment by johnsona9** [comment]
@Bakudan no I never found a solution to this issue and it sounds like there isn't one from what @kevin-brown said.

**Comment by togakangaroo** [comment]
Of note, the jsbin @jelhan posted above is not working. [Here is a working version](http://jsbin.com/xaqorujeqa/1/edit?html,css,js,output)

**Comment by togakangaroo** [comment]
So here's the issue - I have some css that needs to be applied to the select itself. I can apply it to the container, but when the select is open the select is removed from the in-place dom and appended to the body. Previously I was using `dropdownCssClass` to tag this so that I could apply css to it. Now I no longer have this .... Using `templateResult` isn't really an option since...well...this marker class needs to go on the select container, *not* on the individual results.

Frustratingly, I don't even see a full list of all options anywhere in the documentation, just a FAQ style guide, but no full list

**Comment by jdomenechb** [comment]
Just commenting for people like @togakangaroo that stricly need that option that I could solve my particular problem by using:

> var keySelect = $("select#keywords").select2();
> keySelect.data('select2').$dropdown.addClass("hidden");

**Comment by togakangaroo** [comment]
Ok, so I had to use the `select2.full` version which allowed `dropdownCssClass` to work. Then I had to update a bunch of my css and js because apparently all the classnames had changed

**Comment by palluri542** [comment]
How do you use full version through bower?

**Comment by marcin86mak** [comment]
You should use the `select2.full.min.js` script and it will not be a problem there. The problem only occurs when you use `select2.js`

**Comment by callamwilliams** [comment]
Just use a data attribute and the theme option

```html
<select name="" data-error="error">
```

```js
$(element).select2({
  theme: element.dataset.error && 'select2-container--error',
});
```

**Comment by paddotk** [comment]
Anything that works on the _expanded dropdown that is appended to the end of the <body>_? It looks like we can't apply any css to dropdowns on a specific page. All I need is a simple classname applied to a dropdown.
I tried using that dropdownAdapter but since there is virtually no documentation I can't figure it out.

**Comment by ekr3peeK** [comment]
I tought, that it is only me, who finds these adapters and decorators very very hard to use, and manage. But reading the comments I figured, that this is basically a general issue. I think that asking the end user that in case he wants to add a simple class to a dropdown created by the plugin, he should write a complete adapter and/or several decorators, is preposterous.

I get that developing this way is more easier for someone who is fammiliar in this system, but as this is a plugin intended for other users, this should have very quick customization options. It's a good thing to give full control with these adapters, but for basic usages (like adding a class to something that the plugin creates, at least for a top level element for crying out loud) should be much much more simple.

After wasting around 20 hours playing around to achieve my desired end result design wise, I think I rather give up, and roll out my own selection plugin, which basically won't be able to do as much as this one, but at least it will be easy to manage... very disappointed.

**Comment by peteruithoven** [comment]
This really should be documented on: https://select2.org/configuration/options-api

**Comment by david-fiaty** [comment]
I totally understand the frustration here. However, putting the select in a parent container should solve most CSS/JS targeting issues, if not all of them. Great plugin, and thanks for keeping it free.

**Comment by gjoerg-wis** [comment]
Just dropping a snippet that could save some of you a lot of time:
goal: enable select2 + place it in same container + add a class

`  $('select.select2-searchable').each((i, el) => {
        $(el).select2({
            dropdownParent: $(el).parent(),
        })
            .data('select2').$selection.addClass("some-classes");
    });`

**Comment by nhung-le** [comment]
> So here's the issue - I have some css that needs to be applied to the select itself. I can apply it to the container, but when the select is open the select is removed from the in-place dom and appended to the body. Previously I was using dropdownCssClass to tag this so that I could apply css to it. Now I no longer have this .... Using templateResult isn't really an option since...well...this marker class needs to go on the select container, not on the individual results.
> Frustratingly, I don't even see a full list of all options anywhere in the documentation, just a FAQ style guide, but no full list


regarding @togakangaroo's issue
I think you can do for the container by passing the second argument in `templateResult` here is my code:

```
templateResult: function (value, container) {
            $(container).addClass('border'); // update container contain the result aka outer div 
            return value.text;
            
        }
````
