### ISSUE TITLE
could select2 support polymer?

### ISSUE THREAD

**Issue by Colstuwjx** [select2/select2#2888]
As Polymer offered a way to reuse web component, could select2 integrate with [ polymer ](https://www.polymer-project.org)?
Just something likes paper-select2 which use materials design style and support select2 features.

I still cannot find a element like select2, and wishes select2 give a support.
Thks.

**Comment by kevin-brown** [comment]
You're free to create a plugin/theme which integrates Select2 better with Polymer, but there are no plans to integrate it into the core right now.
