### ISSUE TITLE
GitHub Pages site getting 404

### ISSUE THREAD

**Issue by hlfcoding** [select2/select2#2895]
![screen shot](https://cloud.githubusercontent.com/assets/100884/5620600/52daa264-94e2-11e4-9a1d-e43e4a50a572.png)

Also, bonus points to anyone who creates a user-contributed Dash docset, so docs can be read offline.

**Comment by ivaynberg** [comment]
the repository is moving to an organization, the new site can be found under http://select2.github.io/

not sure why the branch with a redirect has not kicked in yet where the old site used to be...

**Comment by hlfcoding** [comment]
:+1:

**Comment by nikmartin** [comment]
I got that 404 and all the blood rushed out of my head! :cold_sweat:

**Comment by kevin-brown** [comment]
This should be fixed, it appears as though the redirects are now working. We're in the process of making slight changes to both of the documentation pages to reflect the transfer.
