### ISSUE TITLE
Search field does not receive focus when it appears upon dropdown

### ISSUE THREAD

**Issue by szgeri** [select2/select2#2900]
When you click on a select2, the dropdown list appears but the focus is not placed on the search input field.

If the problem can be fixed with the new adapter things, an example would be nice.
I also tried to fix it with attaching to the "open" event but was unable to figure out how to attach a function to the events of the v4 select2.

**Comment by sagiro** [comment]
This still doesn't focus on iPhone safari/chrome browsers. Any workaround?
