### ISSUE TITLE
Support for RequireJS 4.0.0 Beta 1

### ISSUE THREAD

**Issue by dixso** [select2/select2#2905]
Hi,
In the next beta could you support for RequireJS?
Thanks!

**Comment by kevin-brown** [comment]
Select2 will automatically define itself as [the named module `jquery.select2`](https://github.com/select2/select2/blob/e76460a392a46184aed976123a49130b784ec611/dist/js/select2.amd.js#L4135) (similar to jQuery which uses `jquery`). If you follow the [RequireJS instructions on how to make jQuery work](http://requirejs.org/docs/jquery.html), they should work for Select2 as well. You should most likely be using the `select2.amd.js` file in this case, as it will not include the AMD loader that Select2 includes by default.

The other option is to point to the `src/js` directory, which is what Select2 uses to build the `select2.js` files. Keep in mind that there is currently [an open ticket](https://github.com/select2/select2/issues/2899) about translations not 100% working when doing this.

**Comment by jzabroski** [comment]
@kevin-brown  None of these solutions seem to work for TypeScript projects. I am banging my head against the wall trying to get a simple TypeScript project to work with select2.

Also, where is `select2.amd.js`?  Did you rename it?  I searched for it everywhere and can't find it.

Apologies if I am missing something obvious.

**Comment by jzabroski** [comment]
@kevin-brown  I figured this out - and I may have come up with a decent solution to the i18n problem.  Will try to describe my solution in the translation ticket, as it may be cleaner than what people currently do using 86b4a5d8e20cf666d7de523df77f1977ba1dad9c

**Comment by nise** [comment]
The question still remains: Where is that select2.amd.js? 

All I get Error: No define call for jquery.select2
http://requirejs.org/docs/errors.html#nodefine when I am including it together with jquery.

**Comment by roberttolton** [comment]
@jzabroski @nise Did you guys find out where the mythical select2.amd.js file is? The documentation seems to assume a level of missing knowledge..!
