### ISSUE TITLE
Focus on search field is not working with regular config.

### ISSUE THREAD

**Issue by yahyaerturan** [select2/select2#2906]
With Bootstrap 3.2.0, I am using the following data and configuration. Works fine but it does not auto focus in search field.

```html
<div class="form-group">
  <label for="id_menu" class="col-sm-2 control-label">Menu Options</label>
    <div class="col-sm-10">
      <select name="id_menu" id="id_menu" class="menu_options form-control">
        <option value="1" selected="selected">Main Menu</option>
        <option value="2">Top Menu</option>
        <option value="3">System Menu</option>
      </select>
    </div><!--/.col-sm-10 -->
</div><!--/.form-group -->
```
```javascript
$(".menu_options").select2(});
```

**Comment by kevin-brown** [comment]
This has been fixed in 4.0.0-beta.2, which is currently unreleased. You can pull the current code from the `select2-ng` branch ([here's a zip](https://github.com/select2/select2/archive/select2-ng.zip)) or wait a few days for it to be released.
