### ISSUE TITLE
select2-ng dropdown cause scrolling when it's positioning

### ISSUE THREAD

**Issue by summeragain** [select2/select2#2908]
When the body perfectly fit the viewport height, the dropdown causes page scrolling before it's position is calculated. 
Source: https://github.com/select2/select2/blob/select2-ng/src/js/select2/dropdown/attachBody.js#L81

Demo: http://plnkr.co/edit/dbLkCuhly9291I1Yop2s?p=preview
Scrollbar moves the select2 container before calculation of dropdown position, and then returns the container to normal location.
![image](https://cloud.githubusercontent.com/assets/5406251/5691850/a3852c3e-98e3-11e4-9ea8-34f2ff039fc5.png)

**Comment by kevin-brown** [comment]
It appears to be an issue only when the dropdown is opened for the first time.
