### ISSUE TITLE
minimumInputLength causing drawing error when dropdown expands upwards

### ISSUE THREAD

**Issue by szgeri** [select2/select2#2910]
Position your select2 to the bottom of the screen to make it expand upwards.

If you set "minimumInputLength" (to 1 or greater), start typing, the dropdown appears upwards, showing the matching items. Press backspace to clear the search field. The items disappear but the search field will remain where it was.

![enter1ormorecharacters](https://cloud.githubusercontent.com/assets/2463548/5695748/338034c8-99b1-11e4-8136-8eae65a10a4a.jpg)

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And **what version of Select2**?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/ivaynberg/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by szgeri** [comment]
The new beta3 fixes this bug, thank you.
