### ISSUE TITLE
Select2 single dropdown list doesn't work in firefox 35 or firefox 34.0.5

### ISSUE THREAD

**Issue by zigy42** [select2/select2#2921]
See stackoverflow question for details.

http://stackoverflow.com/questions/27932134/select2-js-for-single-dropdown-broken-in-firefox

**Comment by kevin-brown** [comment]
Does it work here?

https://select2.github.io/examples.html

Otherwise it doesn't appear to be a bug, it's a usage question.

**Comment by zigy42** [comment]
it does work there, so I'll post about it in usage. thanks.
