### ISSUE TITLE
Class 'app\controllers\Query' not found

### ISSUE THREAD

**Issue by RGTimothy** [select2/select2#2923]
when i use select2, there was an error : "Class 'app\controllers\Query' not found".

**Comment by kevin-brown** [comment]
This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

https://github.com/kartik-v/yii2-widget-select2
https://github.com/tonybolzan/yii-select2

[ml]: https://github.com/ivaynberg/select2#mailing-list

**Comment by abdulmanan7** [comment]
you must mention namespace like this 
$query = new \yii\db\Query;
instead of $query = new Query;
