### ISSUE TITLE
Optgroups are not selectable in v4.0

### ISSUE THREAD

**Issue by choxnox** [select2/select2#2924]
In the previous version (v3.5.2) it was possible to select groups in the hierarchical data if we gave it proper `id` value, but that appears to be impossible in v4.0. Are there any plans to port this feature?

**Comment by kevin-brown** [comment]
I'm going to try, though it's going to mean creating a custom `<option>` tag on the fly for the optgroup if it has the `id` key.

**Comment by kevin-brown** [comment]
I wasn't able to get this done. As it breaks from the standard functionality of a `<select>` in a way that cannot be replicated, I would recommend handling it on your own with a new option that can be selected for the entire group.
