### ISSUE TITLE
select2 4.0 - theme

### ISSUE THREAD

**Issue by santaclaus21** [select2/select2#2927]
Classic (3.5.x) theme should be default to preserve compability. Changing themes by css are also a bit slowly (in case of more instances on 1 page), so better way can be replace css file for default view.

**Comment by kevin-brown** [comment]
We still package the classic theme now in Select2 4.0, [as noted on the examples page](https://select2.github.io/examples.html#themes), it just isn't the default. If you use the latest development version of Select2 (the `select2-ng` branch) or wait for the next release (`4.0.0-rc.1` most likely), you can set it as the default in your JavaScript.

```js
$.fn.select2.defaults.set('theme', 'classic');
```
