### ISSUE TITLE
select2 4.0 - simply way to clone select

### ISSUE THREAD

**Issue by santaclaus21** [select2/select2#2928]
In case of 3.5.x the best way to clone select2 is $('.select2').destroy(); and then clone and $('.select2').select2(); 

Im using select2 sometimes ~40 times on single page and I have to use clone.. In that case destroy all and cloning is not fast.. 

So maybe there will be a simplest way to clone select2 (4.0) - preserving options and selected item?

**Comment by kevin-brown** [comment]
```js
$select.select2('destroy').clone().select2();
```
is still the recommended way to clone Select2 without having to worry about other elements or event handlers getting in the way.

**Comment by hengsoheak** [comment]
I have the same issue with select2 version 2

   if($(this).is('.glyphicon-plus')) {

            var tbodycopy = $(this).closest('#mbody');

            var get_clones = tbodycopy.clone();
            get_clones.children().find('select').select2();
            var selectors = get_clones.find('tr td a.glyphicon-plus')
            if(selectors.hasClass('glyphicon-plus')){
                selectors.removeClass('glyphicon-plus');
                selectors.addClass('glyphicon-minus');
            }
            $(get_clones).insertAfter(tbodycopy);
        }
After clone I will get tow selection one can select another one can not select.

**Comment by WindelOira** [comment]
This works for me :

`function addRepeaterField() {
	    var ul= $('ul'),
	    	li= $('ul li:last-of-type');

	    li.find('.is-select2').select2('destroy');
	    var cloned = li.clone();  

	    ul.append(cloned);

	    $.each($('.is-select2'), function(a) {
	    	$(this).removeAttr('data-select2-id').select2();
	    });
	}`

Hope this helps :)

**Comment by AlekseyEgoshin** [comment]
I use this code for clone one select item.
`$(document).ready(function()
        {
            var Count = 1;

            // Находим все блоки select, затем уничтожаем у них select2 и все атрибуты, которые плагин прививает
            $(".entry").children("select").select2({});
            $(".btn-add").click(function () {
                $(".entry")
                    .children("select").each(function () {
                        $(this)
                    // call destroy to revert the changes made by Select2
                        .select2("destroy")
                        .removeAttr('data-live-search')
                        .removeAttr('data-select2-id')
                        .removeAttr('aria-hidden')
                        .removeAttr('tabindex');
                });
            });


            $(document).on('click', '.btn-add', function(e)
            {

                // Клонируем все элементы строки и вставляем их в конец формы
                var controlForm = $('.controls fieldset:first-child'),
                    currentEntry = $(this).parents('.entry:first'),
                    newEntry = $(currentEntry.clone(true)).appendTo(controlForm);

                newEntry.find('input').val('');
                controlForm.find('.entry:not(:last) .btn-add')
                    .removeClass('btn-add').addClass('btn-remove')
                    .html('<div id="rectangle"></div>');

                //  Присоединяем ко всем элементам select плагин select2
                $(".entry").children("select").each(function () {
                    $(this).select2({ });
                });

            }).on('click', '.btn-remove', function(e)
            {

                $(this).parents('.entry:first').remove();

                //  Присоединяем ко всем элементам select плагин select2
                $(".entry").children("select").each(function () {
                    $(this).select2({});
                });
                return false;
            });

        });`

But right now I have a problem - this code doesnt work if cloning 2 items and i don't know what i need to do for solving this problem.
Some ideas?

**Comment by rovercarlosb** [comment]
@AlekseyEgoshin This solution its´ work for me! Thansk..

**Comment by minkzsingh** [comment]
> $.each($('.is-select2'), function(a) {
> $(this).removeAttr('data-select2-id').select2();
> });

This Solution IS Perfect.
Thanku So much

**Comment by JagadishMeghwal** [comment]
> > var ul= (′ul′),li=('ul li:last-of-type');
> 
> > li.find('.is-select2').select2('destroy');
> > var cloned = li.clone();
> 
> > ul.append(cloned);
> > $.each($('.is-select2'), function(a) {
> > $(this).removeAttr('data-select2-id').select2();
> > });
> 
> This Solution IS Perfect. Thanku So much @WindelOira

This solution works but I am unable to change the selection of previous dropdowns or if I change the previous dropdowns then I cannot change the current dropdowns
