### ISSUE TITLE
How can i get all values of select2 from jquery? 

### ISSUE THREAD

**Issue by RGTimothy** [select2/select2#2929]
This is my code using select2 Yii2
<pre>
echo Select2::widget([
        'model' => $model,
        'attribute' => 'state',
        'data' => $data,
        'options' => [
            'placeholder' => 'Select a state ...',
            'multiple'=>true,
        ],
    ]);
</pre>
Then how can i get all of its values from jquery ($(id/class?).....;)?
Thank you.

**Comment by kevin-brown** [comment]
This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

`$element.val()` should help you though, it will give you the selected options.

[ml]: https://github.com/ivaynberg/select2#mailing-list

**Comment by RGTimothy** [comment]
ok then if i used the officially Select2, how can i get the text of its textbox value with jquery?

**Comment by kevin-brown** [comment]
> how can i get the text of its textbox value with jquery?

Do you mean the search box? Or do you mean [the text of the selected option](https://github.com/select2/select2/issues/2938)?

**Comment by RGTimothy** [comment]
yes i mean the text of the selected option values. how can i get that?

**Comment by c941010623** [comment]
i can't get my selected text
i can get the val use $("#List").select2().val();
but i want get my selected text
how can i do it ??

**Comment by dkotov** [comment]
Try this:
```js
$('#List').select2('data');
```

It will return selected option withh all related information including text

**Comment by Ishwar-Gorad** [comment]
var myTest = new Array();
myTest = $("#List").val() 
myTest array  contains all values of select2. id of List

**Comment by iffakhry** [comment]
thanks @kevin-brown,
but how can I get the text in the search box?

**Comment by junaid18404** [comment]
This is the way you can do it.

```
$(".search-query").select2({
                allowClear: true,                                                          
            }).on("select2:select", function (e) {
                console.log(e.params.data); //
            });
```
e.params.data will give you all the attributes of the selected option.

**Comment by emresaracoglu** [comment]
> 
> 
> This is the way you can do it.
> 
> ```
> $(".search-query").select2({
>                 allowClear: true,                                                          
>             }).on("select2:select", function (e) {
>                 console.log(e.params.data); //
>             });
> ```
> 
> **e.params.data** will give you all the attributes of the selected option.
> Also you have to set the text attribute of your select2 tag equal to the text you are showing in option.
> 
> ```
> <select class="search-query">
>       <option text="your-text">your-text</option>
> </select>
> ```

Thank you but can I change the JSON keys while printing the data?

For example, the keys in the generated JSON data are: "id", "select", "text" and "`newTag`"

Can I change these keys?
