### ISSUE TITLE
'choice-selected' is not fired 

### ISSUE THREAD

**Issue by Untit1ed** [select2/select2#2932]
After upgrading to version: 3.5.2 I noticed that 'choice-selected' event is not triggered after a click event on a tag. Was it replaced by something else?

**Comment by kevin-brown** [comment]
[It _should_ still be fired.](https://github.com/select2/select2/blob/89b2e3fa81159b992510b54efb9fe811e73c51ce/select2.js#L2693)

Keep in mind that this event is undocumented and has **not** been migrated to Select2 4.0.

**Comment by Untit1ed** [comment]
I understand that it's undocumented, but I'm worried about broken functionality of an existing code.
Anyways, it doesn't work as it used to in previous version:
3.5.2 - http://jsfiddle.net/z533pmux/1/ (broken)
3.5.1 - http://jsfiddle.net/z533pmux/2/ (works)

**Comment by kevin-brown** [comment]
I'm not exactly sure why it's not being triggered, but I'm also not in a huge rush to fix it with 4.0 coming up. If you figure out why it's not being triggered for mouse events, feel free to submit a pull request with the fix.

**Comment by AStoker** [comment]
Is there an equivalent behavior in 4.0?
