### ISSUE TITLE
Uncaught Error: No select2/i18n/en-US

### ISSUE THREAD

**Issue by Xcellere** [select2/select2#2934]
Loading 'select2.js', and I'm getting the following error. Loaded the 'dist' folder, so the i18n directory is present:

![error](https://cloud.githubusercontent.com/assets/6492910/5790321/6646aafa-9e47-11e4-8889-79fce969b192.jpg)

**Comment by kevin-brown** [comment]
Looks like we need to handle fallbacks better, probably by converting `en-US` to `["en-US", "en"]` and ignoring any missing ones.

A temporary fix for this would be to change the `lang` attribute (wherever it is) to `en`, or setting the `lang` attribute to `en` on a parent element of the select (probably the table's container, in this case).

**Comment by Xcellere** [comment]
Thank you Kevin.

**Comment by Sammaye** [comment]
Has this been released in the main branch yet? It is causing like 200 odd warnings in FF for me, I updated just this morning

**Comment by kevin-brown** [comment]
@Sammaye Errors or warnings?

_Side note: There should probably be a debug option that determines whether or not to display warnings._

**Comment by Sammaye** [comment]
Select2: The lanugage file for "select2/i18n/en-US" could not be automatically loaded. A fallback will be used instead.

on line 4400 unminified

**Comment by hello-code** [comment]
I still do not know how to use i18n...
So I put this In every page ：
```javascript
 $("#PostId").select2({
          language: {
            inputTooLong:function(e){var t=e.input.length-e.maximum;return"Bitte "+t+" Zeichen weniger eingeben"},
            inputTooShort:function(e){var t=e.minimum-e.input.length;return"Bitte "+t+" Zeichen mehr eingeben"},
            loadingMore:function(){return"Lade mehr Ergebnisse…"},
            maximumSelected:function(e){var t="Sie können nur "+e.maximum+" Eintr";return e.maximum===1?t+="ag":t+="äge",t+=" auswählen",t},
            noResults:function(){return"Keine Übereinstimmungen gefunden"},
            searching:function(){return"Suche…"}
            }
 })

```

**Comment by kvnkkk** [comment]
pls give a solution. i did every thing .still doesnt work. i get the same error
