### ISSUE TITLE
4.0.0 BUG

### ISSUE THREAD

**Issue by c941010623** [select2/select2#2937]
in bootstrap 3.X.X please fix

Because use in modal will not show

and in ipad(modal) and android(modal) all not work

**Comment by flip111** [comment]
@c941010623 not really the most descriptive error message ever. I would just close this issue if it was my repo.

**Comment by kevin-brown** [comment]
I'm assuming this is a duplicate of https://github.com/select2/select2/issues/2936 given that you mentioned "android" and "iphone".

**Comment by c941010623** [comment]
in pc it will not work

use in bootstrap 3.3.x and it in the modal('show')

can't select anything
