### ISSUE TITLE
how can get select2 4.0.x data=>text

### ISSUE THREAD

**Issue by c941010623** [select2/select2#2938]
i can get .val() => ["data"]
but i want get the text
how can i do ?

**Comment by c941010623** [comment]
i can't get my selected text
i can get the val use $("#List").select2().val();
but i want get my selected text
how can i do it ??

**Comment by FamilyMan** [comment]
Just access the object as normal, as though it weren't a select2 object.

$("#List").text()

**Comment by FamilyMan** [comment]
$('#List).select2('data')[0].text;

**Comment by davidhbigelow** [comment]
+1
