### ISSUE TITLE
Consider using UMD instead of just AMD

### ISSUE THREAD

**Issue by raulferras** [select2/select2#2945]
Given the broad list of tools out there (requirejs, browserify, webpack,..), defining the jQuery plugin just as an AMD module limits some of us.
I'm using `webpack` which currently does not support bundle packs (more than one module defined in a single file) as select2 4.x seems to be.

Please consider using [UMD](https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js) (or something similar to this) module definition so it can be used with more tools:

```
(function (factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['jquery'], factory);
    } else if (typeof exports === 'object') {
        // Node/CommonJS
        factory(require('jquery'));
    } else {
        // Browser globals
        factory(jQuery);
    }
}(function ($) {
    $.fn.jqueryPluginCommonJs = function () {};
}));
```

This way we can use select2 those who prefer a CommonJS definition for example.

**Comment by anthonator** [comment]
:+1:

**Comment by kenaniah** [comment]
Would love to see a patch release for this as I'm currently trying to migrate everything to webpack.
