### ISSUE TITLE
jQuery noConflict compatibility

### ISSUE THREAD

**Issue by timothy-h** [select2/select2#2947]
The last line, where $.fn.select2.amd is declared, should be jQuery.fn.select2.amd to avoid breakage when jQuery is in [noConflict mode] (http://api.jquery.com/jquery.noconflict/). Beta 2 has broken on me when using Wordpress's local copy of jQuery, which is in noConflict mode by default.

**Comment by arkytn** [comment]
Running into the same problem trying to adapt v4.0 to WordPress. Multiple instances where noConflict breaks. Examples

select2.js line 1754
    this.dict = $.extend({}, translation.all(), this.dict);
line 3707
    var $container = $('<span></span>');
line 3386
    var $dropdown = $(
line 3439
    var $search = $(

and I gave up. Pretty much wherever you had anunwrapped standalone $
