### ISSUE TITLE
Select2 dropdown not according to width

### ISSUE THREAD

**Issue by nizam27391** [select2/select2#2949]
![select2-problwm](https://cloud.githubusercontent.com/assets/6505952/5813720/1b26e6de-a0bd-11e4-98a9-5ee8aa881fc6.PNG)

As seen above, the dropdown width does not follow the above parent. For above parent, I set the style='wdith:98%' to make it responsive.

I've seen many answers to set dropdownAutoWidth to true or false, but this is not working.

So I guess this is an issue regarding its css / js.

**Comment by kevin-brown** [comment]
Ah, I completely forgot about the dropdown width as far as percentages go! I believe right now it just copies the width, which definitely wont work for anything other than pixels.

**Comment by mateuszf** [comment]
![](http://i.imgur.com/WhF54Ta.png)
I have similar issue when using option width set to "style" (4.0 beta2).
>"style"	 Copies the value of the width style attribute set on the source element.

Original select has width set in css to 200px. Select2 container is 412px (content size), but the dropdown is 12px.
Event if "style" option copies width only if it's set directly in the element, then dropdown should at least get calculated to the select2 container size.

**Comment by smzchaudary** [comment]
@kevin-brown - another symptom of this, that I have seen with a multi-select, is that after a selection, the multi-select/search box's width changes to be the drop-down's width. When the box is emptied, the width changes back to the original width, as described by @nizam27391 - I can create a jsfiddle if you need an example.

**Comment by kevin-brown** [comment]
@smzchaudary Unfortunately the issue there is unrelated to the original issue. Tables are dynamic, and the browser will pick a width for the columns based on what it thinks will display best. We have this issue in older versions of Select2...

http://plnkr.co/edit/c1t3QCmElWtKHEwvNa7F

And it's not something that can be fixed unless your original `<select>` is not responsive.

---

As far as the original issue. It appears that the dropdown _is have the width set_, but it's clearly not what it is supposed to be. I'll look into it more later.

**Comment by ova2** [comment]
I have the same issue. My native select element has width:100%. The problem is in the method Select2.prototype._resolveWidth(...). The call $element.outerWidth(false) return simple 100 and the return value is return elementWidth + 'px'; So I always have 100px für dropdown.

```javascript
Select2.prototype._resolveWidth = function ($element, method) {
    var WIDTH = /^width:(([-+]?([0-9]*\.)?[0-9]+)(px|em|ex|%|in|cm|mm|pt|pc))/i;

    if (method == 'resolve') {
      var styleWidth = this._resolveWidth($element, 'style');

      if (styleWidth != null) {
        return styleWidth;
      }

      return this._resolveWidth($element, 'element');
    }

    if (method == 'element') {
      var elementWidth = $element.outerWidth(false);

      if (elementWidth <= 0) {
        return 'auto';
      }

      return elementWidth + 'px';
    }
...
```

**Comment by ova2** [comment]
I overlooked your last commit https://github.com/select2/select2/commit/9906b2f434a6438d26ec8463ae0f3afa87b07343 I will test this commit. Thanks.

**Comment by ova2** [comment]
Cool, it works now! Thanks a lot!
