### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by hendrixback** [select2/select2#2950]
I have updated to Beta 2 (was using beta 1) and know I am getting this!

    $('#OccurrencesWorkers').select2({
        placeholder: "Search for Worker",
        ajax: {
            url: '/HS/OccurrencesJSON.php?type=OccurrencesWorkers',
            delay: 250,
            dataType: 'json',
            data: function (params) {
                    var queryParameters = {
                        q: params.term
                    }
                    return queryParameters;
                }
        }
    }); 

JSON

        $qry = $conn->prepare("SELECT 	 PersonalNumber AS id,
                                         CONCAT(PersonalNumber,' - ',name) AS text
                                FROM	 tblinjured INNER JOIN tblsap
                                ON       tblinjured.PersonalNumber = tblsap.SAP
                                WHERE    CONCAT(PersonalNumber,' - ',name) LIKE :term
                                GROUP BY PersonalNumber 
                                ORDER BY PersonalNumber");

        $qry->bindvalue(':term','%'.$_GET["q"].'%',PDO::PARAM_STR);
     
        $qry -> execute();

        $OccurrencesWorkers = $qry->fetchAll(PDO::FETCH_ASSOC);

        print json_encode($OccurrencesWorkers, JSON_NUMERIC_CHECK);

HTML

select id="OccurrencesWorkers" name="OccurrencesWorkers" style="width: 100%"></select

**Comment by kevin-brown** [comment]
What browser are you using? And did this issue just arrive in Beta 2 (meaning it worked in Beta 1)?

**Comment by hendrixback** [comment]
Yes, it worked on beta 1. I am using google Chrome

**Comment by hendrixback** [comment]
<select id="OccurrencesWorkers" name="OccurrencesWorkers" style="width: 100%"></select>

This is the select tag i am using

**Comment by kevin-brown** [comment]
Can you provide the traceback that Chrome prints in the console? And use the non-minified version (`select2.js`) as well, so we can trace what line it is being triggered on.

**Comment by hendrixback** [comment]
![image](https://cloud.githubusercontent.com/assets/10588520/5822295/b7a71b70-a0ca-11e4-8cb7-6f394661996a.png)

**Comment by kevin-brown** [comment]
Your issue appears to be happening because you are not returning an object with the key `results` containing the list of objects. You can do this in your PHP backend, or in the `processResults` function [like we do in the GitHub example](https://select2.github.io/examples.html#data-ajax).

**Comment by hendrixback** [comment]
Thank you for the response.
But I am returning a json array with an id and a text. The same way I did in version 4 Beta 1.
Is this the correct way?

**Comment by kevin-brown** [comment]
Before Beta 2 was released we switched to requiring the `results` objects, which was previously required for 3.5.2.

https://github.com/select2/select2/commit/05cbaf7bf7951a04f967637521e2f2e1777d1b8c

**Comment by hendrixback** [comment]
Kevin is still does not work
What is the structures of the expected select2 results?

**Comment by hendrixback** [comment]
Ok, it's already working.

The problem was on the JSON output.

**Comment by AlexBuitrago** [comment]
@hendrixback as you solved it?

**Comment by jimmydumalang** [comment]
how you solved it.. i have the same problem

i have the return like this :+1: 
{"items":[{"id":111,"text":"Deiyai (Deliyai)"},{"id":112,"text":"Deli Serdang"},{"id":113,"text":"Demak"},{"id":114,"text":"Denpasar"},{"id":115,"text":"Depok"},{"id":122,"text":"Ende"},{"id":323,"text":"Padang Sidempuan"},{"id":331,"text":"Pandeglang"},{"id":408,"text":"Sidenreng Rappang\/Rapang"}]}

and the jquery like this:

$(".select2-city-ajax").select2({
        minimumInputLength: 0,
        allowClear: true,
      ajax: {
        url: "{{ URL::to('admin/setting/city/select2'); }}",
        type: "get",
        dataType: 'json',
        data: function (params) {
          return {
            q: params.term // search term
          };
        },
        results: function (data) {
          return {
            results: data.items
          };
        },
        cache: true
      }
    });

please help
