### ISSUE TITLE
selectOnClose: Error

### ISSUE THREAD

**Issue by anilastrio** [select2/select2#2953]
Tried as you suggested in https://github.com/select2/select2/issues/2951.
I get the below error and the dropdown stops working.

> select2.js:3805 Uncaught TypeError: undefined is not a function

Info: as you can see, I am using select2.js

Thanks

**Comment by kevin-brown** [comment]
I can't figure out what version of Select2 you are using.

[Beta 1](https://github.com/select2/select2/blob/4.0.0-beta.1/dist/js/select2.js#L3805) [Beta 2](https://github.com/select2/select2/blob/4.0.0-beta.2dist/js/select2.js#L3805) [Latest](https://github.com/select2/select2/blob/select2-ng/dist/js/select2.js#L3805)

Can you include the traceback for the error so we can see the call chain that is triggering the error?

**Comment by anilastrio** [comment]
I am using the latest - branch "select2-ng".
I am not sure how to pass you the traceback error as i am new in coding. But here is the error from the console log.
```javascript
 Uncaught TypeError: undefined is not a function	select2.js:3805 
 SelectOnClose._handleSelectOnClose					select2.js:524 
 (anonymous function)								select2.js:3800 
 (anonymous function)								select2.js:567 
 Observable.invoke									select2.js:557 
 Observable.trigger									select2.js:4698 
 Select2.trigger									select2.js:4728 
 Select2.close 										select2.js:4854 
 $.fn.select2 										select2.js:1206 
 (anonymous function) 								jquery.min.js:2 
 m.extend.each 									jquery.min.js:2 
 m.fn.m.each 										select2.js:1197 
 (anonymous function)								jquery.min.js:3 
 m.event.dispatch 									jquery.min.js:3 
 r.handle 											jquery.min.js:3
```
The setting for the element:
```javascript
			$('#amenities').select2({
				selectOnClose: true,
				dir: "<?php right_to_left(); ?>",
				language: "<?php echo $get_site_lang; ?>",
				tags:true,
				tokenSeparators: [","]
			});
```

**Comment by kevin-brown** [comment]
It looks like we are decorating the `dropdownAdapter` instead of the `resultsAdapter`. This will be fixed by the next beta release.
