### ISSUE TITLE
select2:unselecting doesn't work

### ISSUE THREAD

**Issue by and7ey** [select2/select2#2954]
In accordance with the release notes (https://github.com/select2/select2/releases) `select2-clearing` is replaced with `select2:unselecting`, but it is never fired - http://jsfiddle.net/and7ey/p2uyc1ej/. So, currently there is no way with 4.0.0-beta2 to capture `clearing` event (when allowClear is true).

**Comment by kevin-brown** [comment]
It looks like [we don't actually trigger the `unselecting` event](https://github.com/select2/select2/blob/0fe54b6d3be21023248ed6fefd9e51984e03bd64/src/js/select2/selection/allowClear.js), so that will be fixed for the next pre-release (beta 3).

**Comment by and7ey** [comment]
`select2:unselect` also is not triggered.

**Comment by mateuszf** [comment]
`select2:unselect` works fine in my case. I'm using 4.0.0-beta2
