### ISSUE TITLE
Dropdown closes when scrolling outside select2-dropdown

### ISSUE THREAD

**Issue by bemky** [select2/select2#2956]
To replicate, click select2, and scroll outside of dropdown, dropdown closes.

This might be intended behavior, but I don't believe it is expected behavior. We had enough complaints in our testing we had to downgrade back to 3.5.2, where the select-dropdown does not close on page scroll.

**Comment by bemky** [comment]
Thanks for the quick response and fix! You guys rock!

**Comment by ashwinig2048** [comment]
its not closing, how to fix it
