### ISSUE TITLE
Select2 4.0.0 Beta 2 not working in modal popup

### ISSUE THREAD

**Issue by sanjaicybro** [select2/select2#2958]
Hi,
I have been using select2 3.5.2 and recently updated to the latest version 4.0.0 Beta 2. It has been noted for me that the latest version is not supporting in modal popup which comes. Can anyone please suggest if there is any solution for this. Temporally I have moved back to the previous version itself.

**Comment by w-diesel** [comment]
I faced with the same bug, using Jquery 11.1 and Jquery-UI 10.4.
Select's element did not opens up a list of options (however select2 works with manual method .select2("open") in a modal window)

**Comment by kevin-brown** [comment]
Can someone create a jsbin/plunkr that demonstrates the issue(s)? It's difficult to test this for me as we don't use modals anywhere.

**Comment by w-diesel** [comment]
http://plnkr.co/edit/GPQTa1aaRJNn1cuz5kos?p=preview

Select2 4.0 works in Firefox, but it seems that selection menu is hidden behind modal-window.

**Comment by kevin-brown** [comment]
It appears to be a `z-index` issue (which is unfortunate).

![broken](https://i.imgur.com/D8Jr6we.png)

Bumping the z-index of the dropdown to `101` solved it here:

![fixed](https://i.imgur.com/uWjztPU.png)

I need to find out what the Bootstrap z-index for the modals is, and then I'll push a fix.

**Comment by w-diesel** [comment]
.modal-dialog {
...
    z-index: 1050;
}

**Comment by w-diesel** [comment]
Changing the z-index helped to show select2 element in front of modal window, but still there is a issue with select2 element's search function in modal window.

**Comment by kevin-brown** [comment]
> but still there is a issue with select2 element's search function in modal window.

I have a feeling this is related to the modal taking the focus back. I'll have to do some more testing to figure out what combination of event blocking and modal patching fixes it.

The issue sounds _exactly like_ https://github.com/select2/select2/issues/1246, so at least we have a starting place.

**Comment by w-diesel** [comment]
I'm quickly read the thread, and i want to notice that everything works with select2 ver. 3.5.1 (if it helps)

**Comment by kevin-brown** [comment]
The solution still appears to work, though it needed a slight modification. I've posted an updated snippet in https://github.com/select2/select2/issues/1246#issuecomment-71710835 for future visitors to use.
