### ISSUE TITLE
select2:unselect doesn't work properly

### ISSUE THREAD

**Issue by and7ey** [select2/select2#2959]
(since the previous issue [where I've said in the comments about not working `unselect` event] has been closed, opening a new issue)

Here is the demo - http://jsfiddle.net/and7ey/p2uyc1ej/1/

Do the following to repeat the problem:
1) choose the value from dropdown by mouse click;
2) click on the cross sign with mouse (please note: allowClear is true).
Expected result - `select2:unselect` should be triggered. But it doesn't happen. Even if you do additional step:
3) click on the arrow to hide dropdown.

But, if you press Enter at the search field with empty value, then it is triggered, but (!) the chosen before value remains chosen.

Tested on OSX 10.10.1, Google Chrome 39.0.2171.95 (64-bit) and Safari 8.0.2 (10600.2.5).

**Comment by kevin-brown** [comment]
This was fixed in https://github.com/select2/select2/commit/d81886e5def277df52e8510d97ae9aedadf0cf90, you can expect to see it working in 4.0.0-beta.3.

http://jsfiddle.net/p2uyc1ej/2/

**Comment by kevin-brown** [comment]
> But, if you press Enter at the search field with empty value, then it is triggered, but (!) the chosen before value remains chosen.

Ah, right. Because it is trying to remove the already selected value... even though it can't. This is a bug, reopening this for now.
