### ISSUE TITLE
On AJAX request 'Searching' is always showing

### ISSUE THREAD

**Issue by hendrixback** [select2/select2#2960]
I have a select2 that receives data via AJAX call. On old versions, when I clicked the select2 the drop down appear with the results. Now I have to type in order for the result to appear. And even then the searching keeps there.´

![image](https://cloud.githubusercontent.com/assets/10588520/5855790/faa1e6a2-a233-11e4-9a5e-c12995cb234a.png)

If I type something in turns into this.

![image](https://cloud.githubusercontent.com/assets/10588520/5855786/efbd6a86-a233-11e4-90b0-3150f41dff87.png)

**Comment by kevin-brown** [comment]
Are you able to reproduce this issue on the example in the documentation?

https://select2.github.io/examples.html#data-ajax

And are any errors being triggered in the console that might help us trace this issue?

**Comment by hendrixback** [comment]
There are no errors triggered on the console. When I click the select2 the searching appear. Then I have to insert something to have the options displayed. No minimum input is declared!

**Comment by kevin-brown** [comment]
Unfortunately without any additional information there isn't much I can do about this. It hasn't been reported by others, so I think it might be an issue in your code.
