### ISSUE TITLE
Update packagist.org

### ISSUE THREAD

**Issue by runephilosof** [select2/select2#2964]
Packagist.org is pointing at  https://github.com/ivaynberg/select2.git, which makes composer semi-fail.

```
  - Installing ivaynberg/select2 (3.5.2)
    Downloading: connection...    Failed to download ivaynberg/select2 from dist: The "https://api.github.com/repos/ivaynberg/select2/zipball/6633cda9061d9fc65075dd140c63f9a6adbcbd72" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing ivaynberg/select2 (3.5.2)
    Cloning 6633cda9061d9fc65075dd140c63f9a6adbcbd72
```

It would be nicer, if that first try would go through (the second try requires authentication).
So if you could point packagist to https://github.com/select2/select2 instead of  https://github.com/ivaynberg/select2.git that would fix it.

**Comment by kevin-brown** [comment]
We don't have control of the package on packagist.org and I honestly have no idea how I would go about updating it.

**Comment by runephilosof** [comment]
How about creating a new account for select2/select2 on packagist.
It doesn't matter if the old one remains wrong.

On 28. jan. 2015 00.34.54 CET, Kevin Brown <notifications@github.com> wrote:
>We don't have control of the package on packagist.org and I honestly
>have no idea how I would go about updating it.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/select2/select2/issues/2964#issuecomment-71751873

-- 
Mvh
Rune Schjellerup Philosof

**Comment by ade72** [comment]
Also cannot install any of the branches using packagist / composer....

**Comment by kevin-brown** [comment]
The package should be up on Packagist now, and it has been set to automatically update.
