### ISSUE TITLE
Calling the results callback multiple times resets keyboard selection

### ISSUE THREAD

**Issue by brendanheywood** [select2/select2#2966]
I have a use case where I want to return some data very fast, potentially from the network but not necessarily, and then do a more expensive query to return more data, or even progressively update the data over time. ie I want to be able to call the query.callback multiple times.

Another use case: say I have a chat selector for who is online, and the dropdown updates in real time as people come and go.

The callback works but if in the meantime I have made a keyboard selection, it is then reset when the new data comes in, even if the new data set still contains the result which was selected.

I've made a minimal test case here which just slowly updates the callback every 2 seconds with mostly overlapping data:
http://codepen.io/brendanheywood/pen/pvwZwK
- [ ] What I'd expect is that if the current selected item is also present in the new result set then reselect it
- [ ] Where the current item isn't in the new results set, a simple solution would be to reset the selection, but perhaps a slightly better process could be to walk 'up' through the old results until you find an item that is also in the new set, then select it

**Comment by brendanheywood** [comment]
Also note that this bug crops up even in simpler user cases without multiple callbacks per query.

Lets say I type in a search for 'dog' slowly over a slow network and it does an ajax call after each keystroke. So we have 3 network requests in flight for '?q=d', '?q=do', and '?q=dog'.

Lets say the first 2 have arrived and I see the desired item 'dogmatic' a couple items down so I press down, down, down to select it, and then just before I press enter to choose it, the 3rd network request arrives, resets the dropdown and my selection, then I press enter and depending on what options were passed in I will have either chosen nothing, or some other random item instead of what I wanted.

**Comment by alexweissman** [comment]
Discussed more thoroughly in #4854.
