### ISSUE TITLE
Issue with --data-ajax--url and jquery 1.11.2

### ISSUE THREAD

**Issue by loic** [select2/select2#2969]
`--data-ajax--url` is ignored while the deprecated `--data-ajax-url` work.

http://jsbin.com/wotamodeco/1 demonstrates the issue.

**Comment by kevin-brown** [comment]
Just following up on this some more based on conversations on IRC.

This appears to be a difference in how jQuery 1.x and 2.x parse the data attributes. I've created two jsbins that clearly reproduce the differences.

1.x: http://jsbin.com/zudohezome/1/edit?html,js,output
2.x: http://jsbin.com/zudohezome/2/edit?html,js,output

**Comment by kevin-brown** [comment]
I added a note to the documentation about this in https://github.com/select2/select2/commit/caeb0ec9b775baf1b91cad859a2954d720d3af20, but unfortunately it does not look like the fix will be released for jQuery any time soon. As there is not much that we can do, aside from preferring `dataset` when possible, I'm going to close this off once I implement the `dataset` check.

That will still mean that it still won't work in older browsers (IE 11 and below), but there isn't much that we can do about it.

**Comment by 304NotModified** [comment]
I think there should be a workaround for this (with attributes). Or is it there already?

**Comment by onokazu** [comment]
jquery has already closed the issue, so can we say that the issue here is also resolved?
https://github.com/jquery/jquery/issues/2070

**Comment by kevin-brown** [comment]
This is still an issue with jQuery 1.x and was not fixed in the recent 1.11.3 release.

http://jsbin.com/midenufoqa/1/edit?html,js,output

It is still fixed in the jQuery 2.x line and upcoming 3.x line.

**Comment by 304NotModified** [comment]
Can't we have an alternative syntax to get it working with jquery 1.x?
