### ISSUE TITLE
Default ajaxOptions.data

### ISSUE THREAD

**Issue by loic** [select2/select2#2970]
Right now it's necessary to write a custom `data` method to get the remote ajax call to work at all (e.g. `data: function(params) { return { q: params.term }; }`)

It'd be great to ship with a default.

**Comment by CTAPbIuMABP** [comment]
:+1:

**Comment by kevin-brown** [comment]
Fixed in https://github.com/select2/select2/commit/4c563a3d068d66a30bb949fe4abd71f7402dc53e.
