### ISSUE TITLE
Built-in match with the Levenshtein Distance usage

### ISSUE THREAD

**Issue by and7ey** [select2/select2#2971]
It would be nice to have built-in matcher with the Levenshtein Distance usage (http://stackoverflow.com/q/11919065/359284), understand that it could be implemented now with customer matcher (btw, documentation is missing  - https://select2.github.io/options.html#matcher), but looking for built-in functionality.

**Comment by kevin-brown** [comment]
While this is something I'd love to see done, I don't think it will end up landing in the core. There's quite a bit of complexity to it and I think it deserves to be a third-party package, but we can gladly link to it as an alternative `matcher`/`sorter` function.

> btw, documentation is missing

The documentation will be there later when we roll 4.0.0-beta.3 out.
