### ISSUE TITLE
select2.js mobile & tablet support 

### ISSUE THREAD

**Issue by adrien-be** [select2/select2#2972]
What's the mobile & tablet support of select2.js ?

I could not find any official statement.

Thanks in advance.

ps. I also created the relevant question on SO, see http://stackoverflow.com/questions/28152676/select2-js-mobile-tablet-support

**Comment by kevin-brown** [comment]
Select2 3.5.x should work well in all of the latest mobile devices. It's used in many large websites and we've appeared to have ironed out many of the old issues.

Select2 4.0.0 has not yet been released, but Beta 3 has been tested to work with Android devices without any real issues. We don't have any iOS devices to test on, but more than likely they work well on iOS as well.

**Comment by Taroxx** [comment]
select2 3.5.2 does not work properly on mobile devices. Tested on various Android versions and iPhone5.

**Comment by timersys** [comment]
Any official announcement now that 4.0.3 is the latest version ? It's fully supporting touch devices ?

**Comment by Taroxx** [comment]
Yes, this version is more stable. Tested on Android 6.0.1 and iPhone 6.
