### ISSUE TITLE
Already created select2 changed to multiple=true with a blank option results in blank selection being shown

### ISSUE THREAD

**Issue by Maowse** [select2/select2#2973]
I have an issue where I have created a select component with single-selection, but need to change this to multiple selection in some cases only.

I've tested this with a simple case, where I set the options for the select as a default array. I create a basic select component with an id of "test" and then in the document.ready function, I call the following:

    $("#test").attr('multiple', true);
    $("#test").select2();

This causes a blank option to be shown in the select2 field:

![image](https://cloud.githubusercontent.com/assets/9093806/5905612/3d680952-a55f-11e4-813a-89e6f5d47dd4.png)

In order to remove this blank selected option, I must then call:

    $("#test").select2('data', null);

As far as I was able to tell, there was no other way for me to get the "blank" selection to NOT be shown by default.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/ivaynberg/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/
