### ISSUE TITLE
Missing .stopPropagation() when navigating by keys

### ISSUE THREAD

**Issue by ova2** [select2/select2#2974]
I've found a bug in Select2 4.0-beta

Assume, Select2 is placed within a form with a command (submit) button. You can navigate by arrow keys down and up in the dropdown. If you now press the Enter key, the form will be submitted. This is a default behavior in browsers when user hits Enter. Select2 has ```evt.preventDefault();``` for all keys in ```this.on('keypress', function (evt) {...}```, but this is not enough. You have also to add ```evt.stopPropagation();```. I've added ```evt.stopPropagation();``` after all ```evt.preventDefault();``` and the problem was gone. Can you consider the fix for the final 4.0 release please? Thanks.

**Comment by ova2** [comment]
This is how keypress callback looks like

```javascript
    this.on('keypress', function (evt) {
      var key = evt.which;

      if (self.isOpen()) {
        if (key === KEYS.ENTER) {
          self.trigger('results:select');

          evt.preventDefault();
          evt.stopPropagation();
        } else if (key === KEYS.UP) {
          self.trigger('results:previous');

          evt.preventDefault();
          evt.stopPropagation();
        } else if (key === KEYS.DOWN) {
          self.trigger('results:next');

          evt.preventDefault();
          evt.stopPropagation();
        } else if (key === KEYS.ESC || key === KEYS.TAB) {
          self.close();

          evt.preventDefault();
          evt.stopPropagation();
        }
      } else {
        if (key === KEYS.ENTER || key === KEYS.SPACE ||
            ((key === KEYS.DOWN || key === KEYS.UP) && evt.altKey)) {
          self.open();

          evt.preventDefault();
          evt.stopPropagation();
        }
      }
    });
  };
```

By the way, you already had evt.stopPropagation() for other events, but it was missing for keypress.

Could you fix this bug for the upcoming 4.0 final release? Thanks a lot for your effort!

**Comment by kevin-brown** [comment]
We specifically removed this for most cases with the intention of adding in a module/option later that would allow for the events to be stopped at different levels.

That is still our intention, and the modules will be available when 4.0.0-rc.1 is released.

**Comment by ova2** [comment]
Ah, good to know. Thanks!
Am 30.01.2015 15:17 schrieb "Kevin Brown" <notifications@github.com>:

**Comment by ova2** [comment]
First, thanks for the quick fix. Is it only available in the full version? How to activate this behavior? Automatically or per option?

**Comment by Mad-Chemist** [comment]
+1 I am struggling right now while trying to find documentation to actually use this 4.0 feature.  We need to stop propagation but there is no documentation around this feature / change.
