### ISSUE TITLE
Dropdown list remain in one place, while select2 element could be moved. (Modal/ S2 4.0.0 beta2)

### ISSUE THREAD

**Issue by w-diesel** [select2/select2#2975]
When modal window have a scroll and you try to click on a lowest Select2 element, then dropdown list remain in place while modal window's content can be scrolled.
(4.0.0 beta2)

http://plnkr.co/edit/TmiPc1HNAva2TZNfFaEt?p=preview 
(Click on **line5** Select2 element and scroll up)

This issue is related to the #2958

**Comment by kevin-brown** [comment]
This should actually be related to https://github.com/select2/select2/issues/2961, and was fixed in https://github.com/select2/select2/commit/64885513742e9cb649baac34657ace9082ce68d3.

**Comment by kevin-brown** [comment]
Nevermind, looks like this is a different issue.
