### ISSUE TITLE
Broken overflow on fixed width.

### ISSUE THREAD

**Issue by Soullivaneuh** [select2/select2#2984]
If select2 input has a limited with, the value overflow is broken as you can see on the following screenshot:

![select2_overflow](https://cloud.githubusercontent.com/assets/1698357/5942353/42b628c6-a717-11e4-8de9-dfcebdbc4615.jpg)

I use the following code to instanciate select2:

```js
select.select2({
    width: '100%',
    placeholder: ' ',
    dropdownAutoWidth: true,
    minimumResultsForSearch: 10,
    allowClear: allowClearEnabled
});
```

Don't know how to fix this issue, any idea?

Thanks.

**Comment by xmikew** [comment]
I'm using `4.0.0b3`.

Whenever I selected a very long text, the overflow was not hidden like you describe. I had to add the following css to hide it:

```
.select2-selection--single {
  overflow: hidden;
  text-overflow: ellipse;
}
```

disclaimer: I'm a select2 neophyte.

**Comment by kevin-brown** [comment]
Adding `whitespace: nowrap` to `..select2-selection__rendered` (for single only) fixed the issue.

![image](https://cloud.githubusercontent.com/assets/1991850/6115544/48a1f2a4-b074-11e4-9f76-dc7c90d51976.png)

**Comment by mikeliz89** [comment]
It works. Thanks. Sorry about the duplicate

**Comment by Soullivaneuh** [comment]
I'm sorry but this issue is not completly fixed:

![select2_broken_clear](https://cloud.githubusercontent.com/assets/1698357/6464494/cc57e318-c1ba-11e4-8c5e-afa0707c7bb4.png)

As you can see, the clear label is broken.

I'm using select2 `4.0.0-rc.1`

**Comment by kevin-brown** [comment]
@Soullivaneuh That issue is slightly different and is being tracked in https://github.com/select2/select2/issues/3089.

**Comment by dickieirwin** [comment]
I think the whitespace: nowrap is causing issue on mobile

So if you add a width: 50% style in-line to the parent container, the control will  will respect that width up until the control is less than the in-line style width of the option text, in this case < 50% of the option width

![select2-nowrap-1](https://cloud.githubusercontent.com/assets/5124035/6514729/77a5b3fa-c3e9-11e4-8f38-0a3b58a98dd7.JPG)

![select2-nowrap-2](https://cloud.githubusercontent.com/assets/5124035/6514749/b4eea5fa-c3e9-11e4-83a7-af5fa967b4f2.JPG)

**Comment by flickervale** [comment]
I have same trouble with you, then I found a way to fix it. 

in view, I wrote this,
`<select class="select2" data-width="100%" multiple id="xref" name="xref[]"></select>`

then in js, I wrote this
`$("#xref").select2({ 
    containerCssClass: 'wrap' });`

and add css in select2 css like this:
`.wrap.select2-selection--multiple { height: 100% }`
`.select2-container .wrap.select2-selection--multiple 
.select2-selection__rendered li { word-wrap: break-word; text-overflow: inherit; white-space: normal !important }`


hope this will help you ^^
