### ISSUE TITLE
TypeError: undefined is not a function (evaluating '$(b)')

### ISSUE THREAD

**Issue by shefik** [select2/select2#2985]
The following error is thrown in the browser console, when you select an option:

TypeError: undefined is not a function (evaluating '$(b)')

Using Select 2 version 4.0 beta3.

**Comment by kevin-brown** [comment]
Can you include the full traceback for this error?

And, does this happen in the examples? If it doesn't happen in the examples, can you link to a jsbin/plnkr or an external website where we can test this?

**Comment by shefik** [comment]
Safari 8.0.3:

[Error] TypeError: undefined is not a function (evaluating '$(b)')
	hasScroll (select2.min.js, line 1)
	(anonymous function) (jquery-1.11.1.min.js, line 2)
	grep (jquery-1.11.1.min.js, line 2)
	w (jquery-1.11.1.min.js, line 2)
	filter (jquery-1.11.1.min.js, line 2)
	_detachPositioningHandler (select2.min.js, line 2)
	(anonymous function) (select2.min.js, line 1)
	(anonymous function) (select2.min.js, line 2)
	invoke (select2.min.js, line 1)
	trigger (select2.min.js, line 1)
	trigger (select2.min.js, line 2)
	(anonymous function) (select2.min.js, line 2)
	invoke (select2.min.js, line 1)
	trigger (select2.min.js, line 1)
	_onUnSelect (select2.min.js, line 2)
	(anonymous function) (select2.min.js, line 2)
	invoke (select2.min.js, line 1)
	trigger (select2.min.js, line 1)
	trigger (select2.min.js, line 2)
	(anonymous function) (select2.min.js, line 2)
	invoke (select2.min.js, line 1)
	trigger (select2.min.js, line 1)
	(anonymous function) (select2.min.js, line 1)
	dispatch (jquery-1.11.1.min.js, line 3)
	handle (jquery-1.11.1.min.js, line 3)
