### ISSUE TITLE
"allowClear" is not working

### ISSUE THREAD

**Issue by shefik** [select2/select2#2989]
When "allowClear" is enabled to "true", clicking the "x" does not work, and it does not clear the selected option.

Using Select2 version 4.0 beta3.

**Comment by kevin-brown** [comment]
Are you able to reproduce this on the examples page in the documentation?

https://select2.github.io/examples.html

If it works there, can you create a jsbin that reproduces the issue you are seeing?

**Comment by shefik** [comment]
It does work at https://select2.github.io/examples.html.

**Comment by kevin-brown** [comment]
This may be related to a few jQuery 1.x compatibility bugs that have come up recently.

Can you create a jsbin/plnkr that reproduces the issue with jQuery 1.11.1?

**Comment by kevin-brown** [comment]
After a bit of testing with 1.x today to resolve a different issue, I can not reproduce the issue that you are encountering.
