### ISSUE TITLE
escapeMarkup option missing

### ISSUE THREAD

**Issue by ova2** [select2/select2#2990]
Select2 3.5.x has the option ```escapeMarkup```. It is mssing in the last Select2 4.0 beta. How to escape HTML in ```templateResult``` and ```templateSelection```?

**Comment by ova2** [comment]
I wanted to say - I don' need the HTML escaping and wrote

```javascript
escapeMarkup: function (m) {return m;}
```

but it doesn't work because ```escapeMarkup``` is not a valid option in Select2 4.0

**Comment by andrewshadura** [comment]
Let me add to this. We have the following code:
```js
                escapeMarkup: function(m){
                    // don't escape our custom placeholder
                    if(m.substr(0,29) == '<i class="icon-database"></i>'){
                        return m;
                    }

                    return Select2.util.escapeMarkup(m);
                },
```
This doesn't work with Select2 4.x, because there's no Select2 object anymore. How do I implement this?

**Comment by andrewshadura** [comment]
Oh. I somehow missed that. Thanks for your help!

**Comment by guilliamxavier** [comment]
For the record, I found another way to access the default `escapeMarkup` function:

```js
jQuery.fn.select2.defaults.defaults.escapeMarkup(yourMarkup)
```

Thanks to [this](https://github.com/select2/select2/blob/4.0.3/src/js/select2/defaults.js#L360) and [that](https://github.com/select2/select2/blob/4.0.3/src/js/jquery.select2.js#L53)
