### ISSUE TITLE
select2 not working properly

### ISSUE THREAD

**Issue by Hiieu** [select2/select2#2991]
http://fiddle.jshell.net/121mrcmy/

![Image](http://i.imgur.com/BAyKm2P.png)

**Comment by kevin-brown** [comment]
The copy of the CSS that you were including was not correctly linked to CloudFlare. You appeared to be missing the protocol (`https`) and that was causing the errors.

I've updated your jsfiddle with the correct url: http://fiddle.jshell.net/121mrcmy/1/
