### ISSUE TITLE
formatRepo not included for brevity in documentation broken.

### ISSUE THREAD

**Issue by ftrotter** [select2/select2#2993]
Look in sourcecode does not work. No such function.

Just in general, "look in the sourcecode" should never be included in any documentation. 

If I was capable of looking in the sourcecode. I would not need the documentation. I use the documentation so that I dont have to look in the sourcecode. 

Perhaps.. and I am just saying.. "brevity" should not be the primary goal of your documentation. Perhaps you should go with "clarity". Which this experience is clearly not.

-FT

**Comment by jonahgreenthal** [comment]
Look at line 1034 of the source to https://select2.github.io/examples.html. The function provided for `templateResult` is an example of what `formatRepo` would be.

**Comment by ftrotter** [comment]
Thank you, but telling me where to look in the source is not the problem. 

The problem is that I have to look in the sourcecode at all.

**Comment by kevin-brown** [comment]
> No such function.

Looks like I forgot to break it out into a function.

> The problem is that I have to look in the sourcecode at all.

The example could would expand to be considerably more than it currently is if we chose to include them. This used to not be an issue when we had a templating example (as they was easier to look at), but the examples do not have one at the moment.
