### ISSUE TITLE
Firefox Mobile: Search Field (with and without ajax) does nothing

### ISSUE THREAD

**Issue by dominikzogg** [select2/select2#2997]
I can search within Chrome (Android) but it i try it within Firefox (Android) i get the search mask on click, be able to enter chars, but it sees, like they get completely ignored. Any idea?

Android 5.0.2, FF 35.0

**Comment by kevin-brown** [comment]
I can reproduce this for the search input, only when entering searchable characters. If you hit "enter", it will select the highlighted input.

Interestingly, the back button doesn't try to remove the last option in a multiple select.

**Comment by dominikzogg** [comment]
@kevin-brown cause i need to type (using ajax)

**Comment by kevin-brown** [comment]
Still debugging this issue, hoping to track down exactly why it is happening before the final release of 4.0.

**Comment by dominikzogg** [comment]
@kevin-brown cool, thx

**Comment by dominikzogg** [comment]
@kevin-brown thank you
