### ISSUE TITLE
Disabled select2 element catch all mouse events in IE11

### ISSUE THREAD

**Issue by akvasov** [select2/select2#3003]
Hi. For example, you have disabled select2 element on your page. When you enter mouse on select2 and try to scroll page, page stopped scrolling, but in Chrome page scrolling normally.

**Comment by kevin-brown** [comment]
This is something that is going to be very difficult for me to test, as I do not have access to IE11.

- Does this happen in older versions of Select2 when they are disabled? http://select2.github.io/select2/#disabled
- Does this happen in older versions of IE? Which ones?
- Does this happen in Firefox? What version?

**Comment by akvasov** [comment]
I can check only current version select2 in different brousers. 
I checked in Firefox v35 (last version), it is work correctly. In Chrome v40(last version) it is work correctly also. But in IE11 (last version) it catch mouse events.

**Comment by kolen** [comment]
Discovered that IE has problems with scrolling when mouse pointer is on element with ``block`` or ``inline-block`` display, ``disabled`` attribute and ``overflow: hidden``.

Example that causes this behavior:
http://jsfiddle.net/puno7z9b/

Wrapping ``overflow: hidden`` element inside ``disabled`` element causes this too:
http://jsfiddle.net/5cp7bojk/2/

It seems that select2 removes ``disabled`` attribute from DOM when it replaces ``<select>`` with its element tree, so everything works good. But in our project it interfered with Angular that adds ``disabled`` back. 

I don't think it's bug of select2.

**Comment by kolen** [comment]
Actually problem is in angular-ui ui-select angular-ui/ui-select#726.

**Comment by kevin-brown** [comment]
> It seems that select2 removes disabled attribute from DOM when it replaces <select> with its element tree, so everything works good.

Select2 just hides the original select, it doesn't alter it in any special way.

> Actually problem is in angular-ui ui-select angular-ui/ui-select#726.

Fun fact: ui-select doesn't actually use Select2, it just uses the CSS.
