### ISSUE TITLE
Select2 inside Bootstrap Modal does not size properly and search does not work

### ISSUE THREAD

**Issue by yanickrochon** [select2/select2#3007]
Having the following HTML

```html
<form id="frmFoo" ...>
  <div class="form-group">
    <label for="txtFoo" class="col-sm-2 control-label">Foo Field :</label>
      <div class="col-sm-6">
        <select id="txtFoo" class="form-control" placeholder="Foo Value"></select>
      </div>
    </div>
  </div>
</form>
```

will not display the `<select>` element's width properly as the `form-control` class is completely ignored when generating the widget's UI.

### ** Edit **

Also, there are other discrepancies with Bootstrap's UI, such as the focus' borders, that are not respected and cause inconsistent UI.

**Comment by yanickrochon** [comment]
A little clarification for this issue; the `<form>` is being loading inside a Bootstrap Modal dialog (thus hidden at load time) and the element's width is undefined.

**Comment by yanickrochon** [comment]
For some reason, the search `<input>` does not receive focus, too. It is impossible to search anything. I'm not sure why that is at the moment.

**Comment by kevin-brown** [comment]
This is related to the same issue over at https://github.com/harvesthq/chosen/issues/92.

Do you know if this was a regression from past versions of Select2?

**Comment by yanickrochon** [comment]
No, it does not. However, with the comments, it gave me an hint and I realized that the dropdown is appended to the `<body>` element, which is under the modal`s screen; in short, Bootstrap prevents any `<input>` element outside of the modal from acquiring focus. Moving the dropdown to the modal element works. I'm changing the title and this issue :)

**Comment by yanickrochon** [comment]
The solution is to document `dropdownParent` for the dropdown input search issue. As for the width, I'm not sure what would be the proper way (I have not dug into the sources much since the last major release).

**Comment by kevin-brown** [comment]
> The solution is to document `dropdownParent`

It just hit me that this is already documented.

https://select2.github.io/options.html#dropdownParent

The Bootstrap issue is pretty well documented at https://github.com/select2/select2/issues/600.
