### ISSUE TITLE
Using localization and RequireJS

### ISSUE THREAD

**Issue by yanickrochon** [select2/select2#3014]
I am using Uglify to reduce the amount of request the application makes to the server and, since Select2 needs to require some language files (but not all), I merge and compress everything under a single `select2-localized.min.js` file.

However, doing 

```js
$('#select2').select2({
  language: 'fr'
});
```

for example does not work (even though the language *has been* defined) and fail with `Uncaught Error: Module name "select2/i18n/fr" has not been loaded yet for context: _. Use require([])`.

Performing a **manual `require`**, giving the defined name `select2/i18n/fr` does not work either, and fail when attempting to load a file that does not exist.

I cannot set the locale as a dependency, and I need to repeat this process (initializing Select2 widgets) at various places in the application.

Explicitly loading all Select2 files in the HTML is counter productive as everything else is defined and loaded from a JS file, setting up `require.config`

Any help appreciated, I have spent far too much time on this already.

**Comment by kevin-brown** [comment]
I would highly recommend checking out the `amdBase` and `amdLanguageBase` options if your RequireJS paths are predictable and consistent.

https://select2.github.io/options.html#amd

This can be set globally using the Select2 defaults.

https://select2.github.io/options.html#defaults

**Comment by jochenberger** [comment]
I can't seem to get this to work with 4.0.0 either. Even if I configure `amdBase` and `amdLanguageBase` correctly and use Select2 within a RequireJS environment, it still tries to load the language modules with Almond.

**Comment by yanickrochon** [comment]
I dropped this attempt and reverted by to my ugly "hacked" solution and 3.5.
