### ISSUE TITLE
Add `closeOnSelect` option

### ISSUE THREAD

**Issue by kevin-brown** [select2/select2#3017]
We should bring back the `closeOnSelect` option and have it set to just call `preventDefault` on the `closing` events. This will also mean that we need to adjust the system to handle close events being prevented, which includes updating the state of the results dropdown when it happens.

**Comment by ova2** [comment]
closeOnSelect was very usefull feature allowing selection of multiple items at once. Looking forward to see this feature in the upcoming release.
