### ISSUE TITLE
x appearing while typing in a multiselect

### ISSUE THREAD

**Issue by ivangfr** [select2/select2#3018]
Hi,

I’m facing the following problem that can be seen on this link: http://jsfiddle.net/begxubn0/

In fact I’m using a select with multiple=“multiple“ atribute.
It’s appearing a **x** when I type.
When I type my first option, the **x** appears at the final of the input.
Then, typing the second option, it appears next to the word been typed.

Is it a bug? How can I fix it?

Thanks!

**Comment by kevin-brown** [comment]
Does this happen in browsers other than Chrome? It sounds like the "clear" button that Chrome provides, which I thought we had hidden.

**Comment by ivangfr** [comment]
In Firefox it's ok.
But, it happens in Chrome and Safari browsers.

Firefox
![captura de tela 2015-02-07 as 18 09 56](https://cloud.githubusercontent.com/assets/10564548/6093212/94c0a3f0-aef4-11e4-94d3-12ab37cf9702.png)


Chrome
![captura de tela 2015-02-07 as 18 06 27](https://cloud.githubusercontent.com/assets/10564548/6093200/4e453e68-aef4-11e4-864c-6ae4e8b690f2.png)

Safari
![captura de tela 2015-02-07 as 18 07 21](https://cloud.githubusercontent.com/assets/10564548/6093203/55e9f8d4-aef4-11e4-88ad-a30827389c87.png)

Thanks
