### ISSUE TITLE
Placeholder not showing, with templateSelection:

### ISSUE THREAD

**Issue by goranata** [select2/select2#3023]
I've just noticed, that when I include:

templateSelection: function (res) {
	return res.name || res.id;
}

the placeholder is not showing. I'm using it to load the data from external JSON file with a search parameter.

**Comment by kevin-brown** [comment]
The placeholder is templated as well. It's passed in as a standard object, in the form of

```json
{
  "id": "",
  "text": "<Whatever your placeholder is set to>"
}
```

Considering this is the same format as the initially selected options, you should make sure that your templating function can fall back to the `text` key. Even better, you should [re-map your `name` key to `text` in `processResponse](https://select2.github.io/announcements-4.0.html#changed-id).

**Comment by goranata** [comment]
Yes yes, I've had templated the palceholder well, but I was using name, instead of text in the json data.
Solutions works fine.
Thanks

**Comment by fquintanilla** [comment]
How do you templated the placeholder? Any detail example please.

**Comment by scottx** [comment]
For those like me who were looking for a way to make a placeholder when using templateSelection, the correct option for Select2 v4.0.3 is:
```
placeholder: {
      "id": "",
      "name": "Whatever your placeholder is set to"
},
```

**Comment by vhanahrni** [comment]
The default placeholder has no id so you can achieve with below code :
```javascript
function formatSelection(result) {
     if(!result.id) {
          // return `text` for placeholder
          return "<div><b>" + result.text + "</b></div>";
     }
     else {
          return "<div><b>" + result.name + "</b></div>";
     }
 }
