### ISSUE TITLE
Using a function as data

### ISSUE THREAD

**Issue by phissionmailed** [select2/select2#3026]
I've been trying for a while to get a Select2 4.0.0 bound to a function.  In my scenario, I two Select2 depend on a third.  I already have the later hooked to an AJAX call.  I am loading this Select2 and also handling the select event.  In the select event I make an AJAX call to the server and obtain the items for the other two Select2.  I'm trying to set those two Select2 to functions so their items are refreshed when the user select items from the first.

As a test, I made a very simple page with the following item

``` html
<select id="yearsList" style="width:100%;"></select>
```

In my document ready function I have the following instruction

``` js
$("#yearsList").select2({
  data: function () {
    return {results: [{ id: "2000", text: "2000" }, { id: "2001", text: "2001" }] };
  }
});
```

The select gets configured and is shown with Select2 theme, but no data is shown.

Is a function still supported as data for a Select2 4.0.0?  Or should I make a custom provider with the new version?

**Comment by phissionmailed** [comment]
For the records, as a workaround, what I did was make the AJAX call place the items in variables and destroy/init both Select2 to force them reload their information from those variables.

Not the best solution, but it works for now.

Great component by the way.  Keep up the great work!

**Comment by kevin-brown** [comment]
I'm either going to roll this fix into the `query` compatibility module or leave it out for the 4.0 release.

In either case, this can be accomplished through a custom data adapter which is recommended now.

**Comment by phissionmailed** [comment]
I've been looking at the adapters and how they should work and can't find any clear documentation that explains exactly how they work and how they should be coded.

Is there some kind of verbose documentation that explains how exactly these adapters should be used?

**Comment by kevin-brown** [comment]
After trying to do this with a fallback to the `query` method, I've decided to drop support for this entirely.

More detailed (and easier to understand) documentation is coming in the future.

**Comment by incorvia** [comment]
I'm new to select2 and I tend to agree with @phissionmailed, here.. either the documentation needs to improve or a simple option that takes a function + callback should be supported (I prefer the second).. This is how twitter typeahead works and I'm up and running in a few minutes there.. I've spent an hour here trying to figure out how in coffeescript I can create class that acts as my data adapter, have it inherit from the selectionAdapater.. and set that as the dataAdapter for my select2 binding.. I think that should work but haven't succeeded yet..

**Comment by incorvia** [comment]
Actually I apologize, I was using select2-rails which is not using 4.0 and I was attempting to use the docs for 4.0, no wonder nothing worked :-|

**Comment by alexweissman** [comment]
The need to document custom adapters is already covered in #3166.
