### ISSUE TITLE
Add support for jQuery themes

### ISSUE THREAD

**Issue by ova2** [select2/select2#3027]
What is about the support of jQuery Themeroller? I think this pull request did it https://github.com/select2/select2/pull/2519

Popular web libraries uses jQuery Themeroller for styling components / widgets, ...

**Comment by ova2** [comment]
By the way, I would split one big CSS file in two smaller: one for layout and one for theming settings. Maybe select2.layout.css and select2.skin.css or select2.css and select2.skin.css?

**Comment by kevin-brown** [comment]
In theory this should be possible in Select2 4.0, because it brings in direct support for custom themes. It won't happen in the core though, but we would entertain the idea of endorsing a third-party theme (like we did with the [Bootstrap theme](https://github.com/select2/select2-bootstrap-theme)).
