### ISSUE TITLE
Website: CSS link examples lack 'rel="stylesheet"' attributes.

### ISSUE THREAD

**Issue by JerseyMilker** [select2/select2#3032]
CSS link examples on website lack 'rel="stylesheet"' attributes...
http://puu.sh/fKDRv/e9d9fbbdc4.png
http://puu.sh/fKEbL/177cf0d1a8.png

**Comment by kevin-brown** [comment]
Thanks to everyone who caught this! It's a duplicate of https://github.com/select2/select2/issues/3020, which has already been fixed in the next docs build.

**Comment by JerseyMilker** [comment]
Ahh I searched for an open issue, maybe you already closed it.  Thanks though!
