### ISSUE TITLE
require users to select from result in tagging

### ISSUE THREAD

**Issue by Jrizzi1** [select2/select2#3037]
I am using select2 4.0.0 beta 3, and I am trying to implement tags with an ajax source. Is there a way to force users to choose from the result list? I am typing for instance "be" , which returns a result list filtered by the letters "be",  i can then arrow through and select once highlighted...but if i just press enter, it creates a new tag called "be", even though its not an option returned from ajax

**Comment by JasperTey** [comment]
I suspect you have `tags` set to true. You need to instead set `multiple` to true, and not use the tags option at all.

**Comment by kevin-brown** [comment]
> I suspect you have tags set to true. You need to instead set multiple to true, and not use the tags option at all.

Sounds like the issue. Closing...
