### ISSUE TITLE
$(element).val not working

### ISSUE THREAD

**Issue by hempel** [select2/select2#3039]
Hey all,

trying out the current beta (beta3) is resulting in a few problems. 
When trying to set a new value with $('#myForm').find('select[name=mySelect]').val(90) nothing happens. Trying the deprecated way ($('#myForm').find('select[name=mySelect]').select2('val', 90)) is working but also raising a notice that it's deprecated.

Can someone confirm this behaviour?

Best regards

**Comment by kevin-brown** [comment]
You most likely need to call `.trigger("change")` on the element, in order to Select2 (and the rest of the world) to know that you have changed the value.

`.select2('val')` does this automatically, and I realize now that the warning doesn't mention it.

**Comment by hempel** [comment]
Works like a charme. Thank you! :)

-closed-
