### ISSUE TITLE
select2 singlequote in dropdownlilst

### ISSUE THREAD

**Issue by jaggubhaik** [select2/select2#3047]
in Select2 dropdownlist, if an option contains singlequote it is displaying as & quot; instead of ',
what needs to be done,thanks in advance

**Comment by kevin-brown** [comment]
Select2 should be automatically escaping single quotes, which is to prevent XSS injection. The escaped entities _should_ display as you are expecting, and it does in my testing.

Can you create a jsfiddle/jsbin (or link to a page) that reproduces your issue?

**Comment by jaggubhaik** [comment]
Sorry there is an issue in my code not in select2 s
