### ISSUE TITLE
Scrolling outside select on mobile closes select

### ISSUE THREAD

**Issue by edu2004eu** [select2/select2#3048]
While the select is open, if you scroll anywhere outside the select, the select is closed.

In more technical details, the `dragstart` and/or `dragend` events are not handled on `#select2-drop-mask`, as far as I can tell. They need to be ignored.

Not sure what the policy is on mobile support, but this would be a nice fix. I think jQuery does support both events listed above, so there's no need for additional dependencies.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/ivaynberg/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by edu2004eu** [comment]
- What steps can be used to reproduce the issue?
Open any select2 while on an Android tablet (haven't tested with iOS); scroll the main page (not the contents of the select)
- What is the bug and what is the expected outcome?
The select2 closes. It shouldn't close.
- What browser(s) and Operating System have you tested with?
Android (have tested with 4.2, but should be reproduceable with any version at least up to 4.2), and both with the native Android browser and Google Chrome for Android.
- Does the bug happen consistently across all tested browsers?
Yes
- What version of jQuery are you using? And what version of Select2?
jQuery 1.10.2 / Select2 3.4.5
- Are you using Select2 with other plugins?
No, it's just Bootstrap + Select2, nothing else.

**Comment by kevin-brown** [comment]
> Select2 3.4.5

This _should have_ been fixed in recent releases of Select2. Select2 3.4.5 is around 1.5 years old and no longer maintainer.

If this is still an issue in recent releases, I can reopen this (or find the duplicate).

**Comment by edu2004eu** [comment]
It's still present in the latest stable build, `3.5.2` (http://jsfiddle.net/ah64hr3c/5/).

**Comment by edu2004eu** [comment]
I patched this by removing the `touchstart` event from line 1412 in `select2.js`. I'm pretty sure it served some purpose, but it seems to work for what I want to do.
