### ISSUE TITLE
Create Search Choice without using Data parameter

### ISSUE THREAD

**Issue by mateioprea** [select2/select2#3049]
Hello, 

Momentarily you can't use createSearchChoice function without "data" parameter on select2. It will result in an error ( if data is empty ): Cannot read property 'toUpperCase' of undefined. 

I think it will be nice if you could createSearchChoice without using the data parameter in select2(), or with data being empty.

**Comment by rw251** [comment]
I can't reproduce this - can you provide the version of select2 that you're using and perhaps a short snippet of code?

**Comment by alexweissman** [comment]
Some related issues:

#693
#2406
#2463
#4668

Unfortunately without more information to reproduce, this issue must be closed.
