### ISSUE TITLE
[v4] Missing usability / functionality when focused

### ISSUE THREAD

**Issue by tuurbo** [select2/select2#3053]
In select2 v3, when the select2 element is focused(not open) you could begin typing to open the dropdown to filter through the list or use the arrow keys to move through the list. That doesn't seem to exist for v4. Is there plans to add this to v4?

**Comment by kevin-brown** [comment]
Part of this is related to https://github.com/select2/select2/issues/3036, where we fixed the auto-focus issue for multiple selects.

But the previous functionality of allowing characters to open the dropdown was not transferred, as it's incredibly difficult (nearly impossible) to correctly transfer the typed characters correctly.

**Comment by tuurbo** [comment]
Here's an ugly fix that I'm using for now. It's not perfect, but I'm putting this here if it helps someone.

https://gist.github.com/tuurbo/ab2c7c5ab765725e0402

**Comment by kevin-brown** [comment]
Closed in https://github.com/select2/select2/issues/3036.

**Comment by cornernote** [comment]
@tuurbo Thanks!  That's exactly what I was looking for.

One small issue, when I use the keypad it enters the wrong character, I found the answer here:
http://stackoverflow.com/a/5630990/599477

Subtract 48 from the keycode, eg:
```
var character = String.fromCharCode(e.keyCode - 48);
```
