### ISSUE TITLE
Setting value programatically to an AJAX Select2

### ISSUE THREAD

**Issue by phissionmailed** [select2/select2#3057]
I have a Select2 with AJAX that is working perfect, but for the fact that I cannot set a value using javascript.  I do not refer to an initial value.  The Select2 is shown initially without a value and this is expected.  The control also loads the data from AJAX correctly and the user can select one of the options.

The problem is that the user can interact with the page in different ways, of which one gives me information to place in Select2; thus, I need to select a value into this Select2 that is usually loaded with AJAX.

I tried this
`$("#list").select2('data',{id:"itemid",text:"item text"});`

But this gives me an error "Function expected" in IE and "oject is not a function" in FireFox.

The error seems to be found in select2.full.min.js, instruction `return d[b](e)`.

I also tried the "val" function, but I know that only works when selecting an item by its ID, rather than add a new selected item.

**Comment by phissionmailed** [comment]
As a workaround, I manipulated the SELECT directly.
`$("#list").empty().append('<option value="id">text</option>').val('id').trigger('change');`
Select2 follows suit accepting the new item as the selected one and showing it to the user.

**Comment by kevin-brown** [comment]
The correct way to add new items to Select2, selected or not, is to append `<option>` tags to the original element. In the case of selections (`<option selected>`), you always have to trigger `change` afterwards so Select2 and other components detect that there was a change in the value.

I'm planning on updating the documentation and warning message to mention this.

**Comment by matosconsulting** [comment]
@phissionmailed, thank you so much for that. I've been fighting this issue for weeks and every bit of discussion I could find on this had me trying to use something along the lines of $('element').select2('data');

My issue was similar to yours, except I'm working with an ajax tagged multiple select which may or may not contain contain initial values.

Here is what I came up with (this is part of an ajax submit function):
````
            // Callback handler that will be called on success
            request.done(function (response, textStatus, jqXHR) {
                $('#modalAddPerson').modal('hide');
                // append the new option
                $("#composers").append('<option value="' + response.id + '">' + response.text + '</option>');
                
                // get a list of selected values if any - or create an empty array
                var selectedValues = $("#composers").val();
                if (selectedValues == null) {
                    selectedValues = new Array();
                }
                selectedValues.push(response.id);   // add the newly created option to the list of selected items
                $("#composers").val(selectedValues).trigger('change');   // have select2 do it's thing
            });
````

**Comment by phissionmailed** [comment]
That looks good Matos.  As Kevin pointed out, if you want to change the items in the SELECT after Select2 has been created you only need to manipulate the OPTIONs inside the SELECT and trigger the CHANGE event.

Select2 will react to the changes and update accordingly.

This is not a workaround and should always be the way to go.

**Comment by anupalusoft** [comment]
What if am using it on `<input>` Plugin gives me error if i use it on `<select>`
Error in console: 
`'ajax' is not allowed for Select2 when attached to a <select>`

Is it that now select2 AJAX would not work on `<select>` elements ?

**Comment by kevin-brown** [comment]
> Is it that now select2 AJAX would not work on <select> elements ?

You appear to be using an older version of Select2. Select2 4.0.0 and up support AJAX on a `<select>` element.

**Comment by anupalusoft** [comment]
Yes it was old. Now i added the new plugin in my code. But it is throwing this error:
`Uncaught Error: No select2/compat/inputData`
What causes it?

**Comment by anupalusoft** [comment]
It was due to using it on input element. Fixed. Thanks for informing.

**Comment by nnacin** [comment]
I am helping myself with phissionmailed's answer for adding new values, but if I added values manually and then ran the code that will insert some values programatically, the values I added before are gone - I only end up with those I added programatically.

Thanks for the advice.

**Comment by westonplatter** [comment]
@kahwee thanks for the suggestion. That fixed it.

**Comment by BinWu1989** [comment]
@matosconsulting I tried your example , anyway , the select input shows noting , could you show me you r full code ? thanks

**Comment by nguyenmanhdzung** [comment]
Thank you for this.
After some try, the select box still empty, I though it's not working for me but I've found that function **templateSelection** cause the problem.
My first function is:
```
templateSelection: function (author) {
            if (author.id != null) field.authorId = author.id; //not important here
            return author.name;  //my ajax response data has name property, it worked with normal selection
}
```
I changed it to `return author.text` and it worked with manually create `<option>` element but the select box is empty when do search and select with the box. I changed it once more time to become:

```
templateSelection: function (author) {
            if (author.id != null) field.authorId = author.id;
            if (author.name!=undefined) return author.name;
            return author.text;
}
```

When create `<option>` element manually, the object passed to this function has `text` property but when you get it from ajax request, maybe it don't have `text` property. I think we can map the response list to a list with objects contains `text` but I chose to modify the **templateSelection** because we don't need to create another array every time, is it right?

**Comment by moparlakci** [comment]
Thanks!!

**Comment by andreidiaconescu** [comment]
hello,
a problem would be that i do not know when to add the new option, because the event select2-loaded does not seem to exist in latest version of select 2.
Can you please let me know in what way i can know the moment when data has finished loading from remote, and has finished setting up, so i can add a new option to it ?

Thank you.

**Comment by alexweissman** [comment]
@andreidiaconescu have you searched the open issues?  Seems like something that should probably have been discussed by now.

**Comment by lukney** [comment]
hello!am using ajax search box method am getting suggestions but when i want to pass those selected element that not possible only enter as-search element only sending,selected one is not passing..

**Comment by ngankt2** [comment]
hope too can help you

option:
ajax, multi
with <input type="hidden" data-selected="[{"id":"5b0536335675a4a387260fe2","text":"doctruyen.tv"},{"id":"5b06355d5675a4a386060a73","text":"Landmark Tower 105"}]"/>

`var selected = $(selector).attr('data-selected');
    $(selector).select2({
        placeholder: 'text',
        multiple: true,
        ajax: {
            url: link_api,
            dataType: 'json',
            data: function (term, page) {
                return {
                    q: term,
                };
            },
            results: function (data, page) {
                return {results: data.data};
            },
        },

    }).select2('data', eval(selected));`

**Comment by phuongnm153** [comment]
@ngankt2 your code use version 3.x
this problem is ver >= 4.x

**Comment by chhorvon** [comment]
```
$contact_referral = Table::select([
                                        'id',
                                        DB::raw("CONCAT(salutation,' ',firstname,' ',lastname) as name")
                                    ])
                                    ->where('id', $query_update->referral)
                                    ->pluck('name', 'id')
                                    ->toArray();


{!! Form::select('referral', isset($contact_referral)?$contact_referral:[], null, [
                                        'class' => 'form-control', 
                                        'id' => 'referral',
                                        'style' => 'width:100%',
                                    ]) !!}
```

**Comment by mediaceh** [comment]
> As a workaround, I manipulated the SELECT directly.
> `$("#list").empty().append('<option value="id">text</option>').val('id').trigger('change');`
> Select2 follows suit accepting the new item as the selected one and showing it to the user.
> 
> Would be this the recommendation or is something else supposed to be the correct answer?

Is's worked only if value == 'id'
