### ISSUE TITLE
issue on iPad

### ISSUE THREAD

**Issue by suriyagp** [select2/select2#3060]
the select2 is not working if it is placed inside a iframe and in iPad. But works fine on the desk top. what is the reason for this? will it fixable???

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/ivaynberg/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by suriyagp** [comment]
use select2 component and put that intoa ifram and use it through the iPad
i was unable to type on the select2 box
browser safari on ipad
That problem is only with the iPad it works fine on the PC and android tablets
Jquery 1.7.1
select2 alone is not working

**Comment by kevin-brown** [comment]
Appears to be a known issue.

https://github.com/select2/select2/issues/1976
