### ISSUE TITLE
createTag event is fired on every keypress

### ISSUE THREAD

**Issue by harrygr** [select2/select2#3063]
If I have an instance of Select2 with `tags` set to true I might want to trigger an event every time a new option is added to the `<select>`, (for instance, persist the new option over ajax). As I understand it the `createTag` (previously `createSearchChoice`?) event exists for this purpose. 

However, it seems that the callback assigned to `createTag` is called for every character entered rather that just once for each new tag.

This can be seen in action in this fiddle: http://jsfiddle.net/3qkgagwk/1/ 

Is this expected behaviour or is it a bug?

**Comment by kevin-brown** [comment]
The `createTag` method is called to get the new tag that should be added to the top of the list. The returned object is what generated the result, and it is called every time the data is queried.

If you want to determine when the tag is actually selected, I would hook into the `select2:selected` DOM event, and listen to see if the data object passed back exists in the database already.

Here's an example fiddle: http://jsfiddle.net/3qkgagwk/2/
