### ISSUE TITLE
Scrolling past end of dropdown starts scrolling background

### ISSUE THREAD

**Issue by jiaweihli** [select2/select2#3068]
http://jsfiddle.net/byJy8/82/

This isn't the behavior on the docs page: https://select2.github.io/select2/

**Comment by jiaweihli** [comment]
Firefox doesn't appear to have this issue, only Chrome does.  Is this a known bug?

**Comment by kevin-brown** [comment]
We have built-in support for [jQuery mousewheel](https://github.com/jquery/jquery-mousewheel/), which is included by default in full builds in 4.0, which is supposed to prevent the background scrolling when it is included on the page.
