### ISSUE TITLE
Display Saved Tags using select2-rails

### ISSUE THREAD

**Issue by boyfunky** [select2/select2#3070]
Can someone explain how i am supposed to get and display already selected and saved tags with this new code? 
$.fn.select2.amd.require(
['select2/data/array', 'select2/utils'],
function (ArrayData, Utils) {
  function CustomData ($element, options) {
    CustomData.__super__.constructor.call(this, $element, options);
     var data = {
      results: []
    };
  }

  Utils.Extend(CustomData, ArrayData);

  CustomData.prototype.query = function (params, callback) {
   

    for (var i = 1; i < 5; i++) {
      var s = "";

      for (var j = 0; j < i; j++) {
        s = s + params.term;
      }

      data.results.push({
        id: params.term + i,
        text: s
      });
    }

    callback(data);
  };

  $("#select").select2({
    dataAdapter: CustomData
  });
}

Reading the Select 2.4.0 documentation, it says query function has been deprecated for this function but I dont know how it is supposed to work. I have a this select code 
<%= select("learning_article", :tag_list, Tag.all.map(&:name), {}, {class: "js-example-tags", :"data-tags" => "true", :multiple => "true" }) %>

It saves the tags but then it doesnt display the selected tags.

**Comment by kevin-brown** [comment]
[select2-rails does not currently support 4.0.](https://github.com/argerim/select2-rails/issues/109)

**Comment by boyfunky** [comment]
So how would it work if it  is in select2 3.5.2?
