### ISSUE TITLE
cannot bind on select2-search-choice-close

### ISSUE THREAD

**Issue by msaxbury** [select2/select2#3073]
I am trying to bind a click event to the select2-search-choice-close x on selected values but Chrome returns undefined.

Here is my html:
`<div id="Products">`
 `<div class="select2-container select2-container-multi" id="s2id_byVapptProduct">`
 ` <ul class="select2-choices">`
   `<li class="select2-search-choice">`
    `<div>Product Name</div>`
    `<a href="#" class="select2-search-choice-close"></a>`
   `</li>`   
`...   `
`</div>`

My jquery code is:
jQuery('ul').on('click', '.select2-search-choice-close', function(e){
console.log("FINALLY");
console.log(jQuery(this).next().html());
});

Nothing gets written to the console. I can change to the div instead of the close class and my console shows FINALLY, but the .next().html is blank, no errors, nothing.

Why can't I bind on the close X?

**Comment by msaxbury** [comment]
Yes my jquery is within document.ready function.
I am using jquery 1.11.1
I am using select2 3.5.0
The html above is the select2 container, I am using a hidden input with multiple: true and ajax to dynamically populate the drop down when clicking into it. All that works fine, functionally it works fine. If I click the X to an item added in the input it removes it. I want to key off the click event though and do some thing else on the page.

**Comment by kevin-brown** [comment]
Select2 3.5.x stops the propagation of most events out of the container, so this is most likely what your issue is.

Select2 4.0 does not do this.
