### ISSUE TITLE
Android browser [Multiple select boxes] cannot remove the selected option

### ISSUE THREAD

**Issue by alvin0618** [select2/select2#3075]
Multiple select boxes works fine on desktop (chrome, safari, firefox, IE). When I test on mobile device (Android browser), I managed to remove all the option after selected however the only option cannot be removed is the 2nd option - Hawaii, please refer to the https://select2.github.io/examples.html and run on mobile device (Android browser).

Android Version - 4.4.2

**Comment by kevin-brown** [comment]
I just tested this out on the Android emulator ([Thanks Sauce Labs!](https://saucelabs.com/tests/d2a8f85899364bbe9a26c9c6277e4b53)) and I was able to reproduce the issue. I can't reproduce it on Android Chrome in 5.0 or the stock browser in 4.2.

As you can see in the recording, I struggled to get to the event section to figure out what events were being triggered. My guess is that this is going to be the key to solving the issue, figuring out what events are being triggered (and which ones shouldn't be).

**Comment by Hlsgs** [comment]
I can confirm this on android 4.4.2 stock browser. 
No matter what you select first, when unselecting an item the first option gets selected. Practically, it becomes impossible to unselect the first option.

**Comment by ricardoisc** [comment]
+1

**Comment by ricardoisc** [comment]
For some reason, the android browser adds the first option as selected. Fortunately, this first option is not present in the "unselecting" event, so we can do this as a workaround (which also closes keyboard on mobile):
        	```
$("#myautocompleter").on("select2:unselecting", function (e) { 
    $(this).data('predeleted', $(this).select2('data'));
});
$("#myautocompleter").on("select2:unselect", function (e) { 
    var new_data = [];
    new_data$.each($(this).data('predeleted'), function (key, value) {
        if (value['id'] != e.params.data.id) { 
            new_data.push(value['id']);
        }
    });
    setTimeout(function() {
        elem.select2('close');
        elem.val([]).trigger("change");
        elem.val(new_data).trigger("change");
    }, 1);
});
```

**Comment by Loadmaster** [comment]
I notice the same thing happening (release 4.0.3, using FireFox and Chrome desktop browsers, with multiple and tags enabled). No matter what options are selected or unselected, the first `<option>` of the `<select>` element is always marked as `selected='selected'`, even if it is unselected and not shown in the tags area. So when the page posts back to the server, it always sees the first item as a selected choice.

**Comment by kevin-brown** [comment]
@Loadmaster That sounds like a different issue, any chance you can break that out into a separate ticket?

**Comment by Loadmaster** [comment]
@kevin-brown Yep, see #4406.
