### ISSUE TITLE
XSS injecting with 4.0.0.beta3

### ISSUE THREAD

**Issue by riev** [select2/select2#3079]
When write or paste javascript code into the select2 input, it is being fired off.

I'm using just the tags option and I've tried in both beta3 and beta2. I downloaded the version of the script from the examples page and that version doesn't have this issue.

**Comment by kevin-brown** [comment]
> I downloaded the version of the script from the examples page and that version doesn't have this issue.

So it's something that has been fixed in the latest branch.

Most likely it's related to the `escapeMarkup` option which was added at some point recently.
