### ISSUE TITLE
When typing tag names, autocomplete forgets to kick in

### ISSUE THREAD

**Issue by szgeri** [select2/select2#3081]
At the "Multiple select boxes" example, Type "Haw", press Enter. "Hawaii" tag added.
Now type "ala" for Alaska. No autocomplete, no dropdown. That is the main bug I found but I kept going.

If you press enter at this point, the dropdown appears with "Hawaii" selected. If you press Enter again, the Hawaii tag you entered before disappears and only the "ala" text will remain.

Press Enter again on the selected "Hawaii" option, "Alaska" will be selected but instead of adding "Alaska" as a new tag, select2 goes into a state when it stops caring about the keyboard. It looses focus.

**Comment by kevin-brown** [comment]
General key binding issues are being dealt with in https://github.com/select2/select2/issues/3036.

I'd recommend adding your comments there, including the behavior path that you are expecting (and what you are currently seeing).
