### ISSUE TITLE
Problem when select2 placed at bottom navbar (bootstrap 3 latest) and float right.

### ISSUE THREAD

**Issue by fourteenmeister** [select2/select2#3082]
Actually that's an example - http://jsfiddle.net/rx525wp7/3/ (float: left problem is gone, but I need it float: right).
If navBar fixed to top http://jsfiddle.net/rx525wp7/4/ - no problem.

**Comment by kevin-brown** [comment]
Still an issue in 4.0, probably related to the scrollbar.

http://jsfiddle.net/v8exsuvu/

I think there is a a duplicate issue somewhere about this.

**Comment by kevin-brown** [comment]
This issue was fixed in Select2 4.0.3.

http://jsfiddle.net/v8exsuvu/5/
