### ISSUE TITLE
Broken focus on multiple autocomplete widget after picking a choice

### ISSUE THREAD

**Issue by loic** [select2/select2#3084]
This is a regression caused by 3d013020aee3a0c590f5fdcdbf0440c001d2171c.

How to reproduce:

1. Locate the "Multiple select boxes" example.
2. Start typing and pick a choice.
3. Type again but choices aren't displayed anymore.

When using a remote API, ajax calls are still made for every key input, but choices are just never displayed.

**Comment by kevin-brown** [comment]
Rolling this into https://github.com/select2/select2/issues/3036 actually, as that appears to be the current master issue for key binding issues.
