### ISSUE TITLE
How to change style of options.

### ISSUE THREAD

**Issue by bhalke** [select2/select2#3085]
I need to show option data like a card(block element with two lines of data) first line age name second line year and score. 

Example of option card :::
[age , name
Year , score
]
[age , name
Year , score
]
[age , name
Year , score
]

**Comment by kevin-brown** [comment]
I'd recommend looking into [the templating options](https://select2.github.io/examples.html#templating). You can find a more advanced [example in the AJAX search](https://select2.github.io/examples.html#data-ajax), which uses the Bootstrap grid.
