### ISSUE TITLE
Infinite scroll not fetching more pages when scrollbar isn't visible

### ISSUE THREAD

**Issue by firedog** [select2/select2#3088]
I am trying some things out with select2 4.0.0 (select2-ng branch as of feb 26 2015) where I'm fetching items over AJAX and noticed that when the page size is small enough to fit all items from a page in the dropdown viewport (i.e. no vertical scrollbar is shown in the dropdown) then select2 won't fetch any more pages apart from the first one. As soon as the page size is increased so that the scrollbar is shown everything works as it's supposed to.

Tested in Mozilla Firefox 36.0

This is the select2() function I'm using. (sorry, no public API available)

``` javascript

// in document ready...

// A page size of 5 items breaks the functionality in my case, 6 items is ok!
var pageSize = 6;

$drivers.select2({
    placeholder: { id: '-1', text: 'Select a driver' },
    ajax: {
        url: "http://localhost:52765/api/drivers",
        dataType: 'json',
        delay: 250,
        data: function (params) {
            return {
                search: params.term, // search term
                pageNumber: params.page || 1,
                pageSize: pageSize
            };
        },
        processResults: function (data, params) {
            var ph = data.paginationHeader;
            params.page = ph.currentPage;

            var results = [];
            $.each(data.items, function (key, value) {
                console.log(value);
                results.push({ id: value.driverId, text: value.surname + ", " + value.firstnames });
            });
            return {
                results: results,
                pagination: {
                    more: (ph.currentPage * ph.itemsPerPage) < ph.totalItems
                }
            };
        },
        cache: true,
        transport: function (params, success, failure) {
            var extractPaginationHeader = function (json, status, xhr) {
                return {
                    items: json,
                    paginationHeader: JSON.parse(xhr.getResponseHeader('X-Pagination'))
                };
            };

            var $request = $.ajax(params);

            $request.then(extractPaginationHeader).then(success);
            $request.fail(failure);

            return $request;
        }
    },
    escapeMarkup: function (markup) { return markup; },
    minimumInputLength: 0
});

```

**Comment by kevin-brown** [comment]
Does this work at all in 3.5.x? I'm not sure how I'd go about fixing it if it doesn't.

**Comment by firedog** [comment]
I have tried this scenario in 3.5.2 and it seems that someone was aware of this problem because it "sort-of" works! What happens is that select2 3.5.2 will fetch two pages of information right from the start if the page size is set to 6 items or less (i.e. two AJAX requests are issued, one for page no 1 immediately followed by another one for page no 2). Subsequent fetches (pages 3 and up) are done one-by-one. 

As soon as I set page size to 7 items or more only one page is retrieved at a time.

**Comment by alexweissman** [comment]
It would appear that this is still a problem in 4.0.3.  However, I don't see any duplicate requests occurring.  It would seem that rather, select2 fails to make the request for the next page at all when the height of the result set is less than the maximum height.

Here is a [modified version of the example in the docs](https://codepen.io/alexweissman/pen/jLyKGO), with the page size artificially set to `1`.

**Comment by nburwell** [comment]
I just ran into this issue with 4.0.5 and a small page size (5).. where it was working before our upgrade (presumably because of the two ajax requests that firedog mentioned.  We are working around it by using a larger page size but this seems like a corner case that should definitely be resolved!

**Comment by trasher** [comment]
This is still an issue; a PR has been opened; but no news on it:
https://github.com/select2/select2/pull/3888

**Comment by alexweissman** [comment]
Thanks for linking to the PR!

**Comment by joepetrakovich** [comment]
It is still an issue. Easy to recreate too.  Just set your page size to 1 and it will not load trigger any more ajax requests.  The workaround is to use a large enough page size.

**Comment by yeganehaym** [comment]
it's still exists
i'm using the latest version
when i returns a few records, vertical scrollbar is hidden and doesn't load more records
but when returns lots of records, vertical scrollbars exists and loads more data by scrolling
