### ISSUE TITLE
Broken allowClear on fixed width

### ISSUE THREAD

**Issue by bsv9** [select2/select2#3089]
If select2 input has a limited with, the value allowClear is broken as you can see on the following screenshots:

with long text string
![Alt text](https://monosnap.com/file/lUpo1sZgF8jdCtVqjo5Kr8g6bNt13i.png)
with short text string
![Alt text](https://monosnap.com/file/pjTx8oqNW0wXzLuxkUGRfpYg0ogk9Z.png)

http://jsfiddle.net/bhzz6twr/3/

patch from issue #2984 applied

**Comment by kevin-brown** [comment]
Demo test case for reproducing the issue: http://jsfiddle.net/bhzz6twr/4/
