### ISSUE TITLE
the select style with !important

### ISSUE THREAD

**Issue by afattahi54** [select2/select2#3092]
It seems that the style of select box with !important will not copy correctly  

Below:

``` javascript
<select id="e18" style="width:50% !important;" >
```

Will be converted to

``` javascript
<select id="e18" style="width: 30% ! important; display: none;">
AND
<span style="width: 30%;"  class="select2 select2-container select2-container--default">
```

As you can see there is space between ! and important in hidden select 
Also the generated select2-container does not include !important.
I am using version 4 beta !

**Comment by kevin-brown** [comment]
This is an issue with the [regex for getting the width](https://github.com/select2/select2/blob/d3c887286d1515910944361d8a6cbf647fc2ec1b/src/js/select2/core.js#L117) but it's not a high priority for me at the moment.
