### ISSUE TITLE
Broken allowClear in Firefox 36 (works in chrome)

### ISSUE THREAD

**Issue by jersingh** [select2/select2#3094]
Don't know if this is related to #3089 and apologize if a duplicate, but allowClear option on select2 4 demo page displays "x" underneath control in FF 36.

This on the State placeholder so length not an issue I believe.

Looks fine in Chrome 40. Behavior the same in both Ubuntu and Windows browsers.

![selection_004](https://cloud.githubusercontent.com/assets/63162/6457282/c2de1c38-c130-11e4-9e51-db67a1d18ab3.png)

**Comment by kevin-brown** [comment]
Confirmed in Firefox 36.

**Comment by jersingh** [comment]
Unfortunately no. I've used older versions of the 3.5.x branch on other projects, but yesterday was my first attempt to use the 4.0 beta.

**Comment by cebola2** [comment]
I noticed the same and reverted to 4.0beta3. The problem disappeared (Firefox 36 for Linux Mint).

**Comment by kevin-brown** [comment]
> I noticed the same and reverted to 4.0beta3. The problem disappeared (Firefox 36 for Linux Mint).

Thanks for confirming that, it gives us a starting point to look at when determining when this stopped working.

**Comment by kevin-brown** [comment]
Confirmed that this was fixed in https://github.com/select2/select2/commit/e3d7cd2d6952fc4412e953f2b749ede316e70dc5.
