### ISSUE TITLE
Dealing with HTML characters

### ISSUE THREAD

**Issue by Sammaye** [select2/select2#3096]
In some selects I have characters like `<`.

The old select2 used to successfully handle these but the new version  of select2 seems to just HTML entity encode them `&lt;` and leave them there to display like that without brining them back to `<`

**Comment by kevin-brown** [comment]
It sounds like Select2 might be double-encoding the data, as it _should_ only be doing it once (when it displays it).

Can you create a jsbin/jsfiddle that reproduces the issue?

**Comment by Sammaye** [comment]
Here's one: https://jsfiddle.net/jLz8mjob/ it shows how it is seemingly doubel encoding

**Comment by Sammaye** [comment]
Oh correction it does, it just can't do code highlighting right, so if you force a < instead of &lt; you will see it

**Comment by rodogir** [comment]
For comparison Version 3 works as expected:
Version 4: http://jsfiddle.net/ok0c5bdm/1/
Version 3: http://jsfiddle.net/drv777h4/2/

**Comment by kevin-brown** [comment]
Making https://github.com/select2/select2/issues/3115 the issue for dealing with this.
