### ISSUE TITLE
Select2 does not take width of original element in new version

### ISSUE THREAD

**Issue by Sammaye** [select2/select2#3097]
I am using bootstrap and replacing some form elements with select2 but I have found that while using form-control (which is 100% width) it is clipping the width at 100px.

**Comment by mjesuele** [comment]
I'm having the same problem using 4.0.0 with Bootstrap in a Meteor project. The width is applied as an inline style to the select2 span element.

**Comment by matiazar** [comment]
same for me... if the select2 is on a visible tab when the page loads, it gets 100% width but when the tab is not active when you enter the page, and you activate this tab, the select2 only has 100px with.

thanks in advance

**Comment by alfredobarron** [comment]
same problem

**Comment by alfredobarron** [comment]
Solved commenting at line:
4927      // return elementWidth + 'px';

**Comment by rebendajirijr** [comment]
same problem here, when using select2 inside bootstrap 3 modal, width of the control is not 100%. Only manual setting of style="width:100%;" to original <select> element works.

**Comment by martinvzlaa** [comment]
.select2-container {
            width: 100% !important;
            padding: 0;
        }

the most recomended option I found is override this class and put these values and load after all styles on master page or layout page

**Comment by alexweissman** [comment]
This is discussed in more detail in #3278.
