### ISSUE TITLE
Select2 is no longer responsive

### ISSUE THREAD

**Issue by Sammaye** [select2/select2#3098]
Select2 is working on a base px width that is no longer responsive

**Comment by kevin-brown** [comment]
[Seems to accept percent widths fairly well](https://select2.github.io/examples.html#responsive). Please create a jsbin that reproduces the issue if this isn't the case.

**Comment by Sammaye** [comment]
Don't the input go off the page when you resize that demo page? They ddin't
used to since the old select2 could inheirt the percentage of its parent.

**Comment by Sammaye** [comment]
Oh sorry I see now, it acepts it directly on. The default .select2() seems
to not be responsive, does that mean it needs to have percentage width set
for everyone?
