### ISSUE TITLE
select2 4.0 - selection__choice longer than select2-container

### ISSUE THREAD

**Issue by santaclaus21** [select2/select2#3102]
In 4.0 when I'm using long names for options - li.selection__choice are longer than .select2-container. Looks bad.

![image](https://cloud.githubusercontent.com/assets/1121662/6468903/ca1da6be-c1d8-11e4-924e-dad0232b20fa.png)

**Comment by kevin-brown** [comment]
Can you create a jsbin that reproduces this? I thought I tested it, but I may have missed it.

**Comment by santaclaus21** [comment]
Here you are http://jsbin.com/pisejuleko/1/edit?html,output

**Comment by alexweissman** [comment]
Discussion of this issue is continued in #4585.
