### ISSUE TITLE
select2('data') doesn't actually work

### ISSUE THREAD

**Issue by kevin-brown** [select2/select2#3104]
This is because the data adapter is being set by `this.data = new X();`, which is overriding the method that we have created.

As this method exists for backwards compatibility purposes, I think we're going to be better off just renaming the property that the data adapter uses.

**Comment by apank** [comment]
If data does not return anything how else can you get the value of the selected option?

**Comment by Knoxvillekm** [comment]
Cannot read property 'current' of undefined with last commit.
this.dataAdpater is undefined

**Comment by kevin-brown** [comment]
While I'm at it, I might as well add some tests to actually verify this works.

**Comment by apank** [comment]
Thanks, would you be able to provide an example as well.

To get data now I'm just targeting the original select element on change.

$('#selectElement').val();
