### ISSUE TITLE
inputData

### ISSUE THREAD

**Issue by CTAPbIuMABP** [select2/select2#3105]
this line 

https://github.com/select2/select2/blob/956ac46dab3acb94af487bfa201595ec16c8bab3/src/js/select2/options.js#L16

throws error in requirejs

**Comment by kevin-brown** [comment]
There's an issue with the AMD build, we're aware of it and are tracking it in https://github.com/select2/select2/issues/2946.

**Comment by CTAPbIuMABP** [comment]
i know
i just mean last beta was working in the way i described in #2946 but rc is not working at all
