### ISSUE TITLE
select2 with ajax loads the data correctly, but i can not hover or click on the options populated from server

### ISSUE THREAD

**Issue by ajinkyas** [select2/select2#3108]
I am using select2 4.0.0-rc.1 build in a web application in chrome

**Comment by kevin-brown** [comment]
Sounds like you are missing the `id` property on the returned objects.

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/ivaynberg/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by gbouthenot** [comment]
Yeah.
I had the same problem and juste wasted half an hour.

Why this "id" is mandatory, it doesn't seem to documented on the website
Is there a way to either:
- automatically add that id
- use another attribute (I would like to use "uid" or even "_id"

Is this planned ?

Thank you !

**Comment by ajinkyas** [comment]
Yes, Id was the issue. Thank you! :)
