### ISSUE TITLE
select2 4.0.0rc1 event data

### ISSUE THREAD

**Issue by gbouthenot** [select2/select2#3110]
When watching event "change" (I also tried "add", "update", or "selection:update")
The provided jQuery Event object does not provide information about the added/removed selection.

On select2-v3, the "change" event had the "added" attribute, in v4-0.0.rc1, that does not seem to be provided anymore.

Thankfully.

**Comment by kevin-brown** [comment]
You might be looking for the `select2:select` and `select2:unselect` events which includes the data object in the `data` attribute.

**Comment by gbouthenot** [comment]
Thank you very much !
The selected data is actually in the jQuery Event object, inside the params property.
