### ISSUE TITLE
maximumSelectionSize not working in 4.0rc1

### ISSUE THREAD

**Issue by mheptinstall** [select2/select2#3112]
When setting a value for maximumSelectionSize in 4.0rc1 no message is displayed when the limit is reached and you are able to continue making selections.

Switched CDN to use 3.5.2 and works fine.

**Comment by kevin-brown** [comment]
Works on the documentation pages, so most likely it's actually working.

https://select2.github.io/examples.html#multiple-max

You'd need to create a jsbin that reproduces the issue in order to help us figure out where the issue is.

**Comment by mheptinstall** [comment]
The examples are either running off a different version or I'm doing something wrong.

http://jsbin.com/mepipapeto/1/edit?output

**Comment by numbers1311407** [comment]
The option is `maximumSelectionLength`, not `maximumSelectionSize`.

**Comment by mheptinstall** [comment]
The examples page uses `maximumSelectionLength` but the documentation pages specifiy `maximumSelectionSize`

**Comment by numbers1311407** [comment]
That's the examples page for v3.5.2, not v4.0.0-rc1
