### ISSUE TITLE
XHTML-encoded characters not decoded properly in option title

### ISSUE THREAD

**Issue by 0x30** [select2/select2#3115]
DataAdapter is using the XHTML-encoded characters, e.g. &amp, as they are for option text:

![image](https://cloud.githubusercontent.com/assets/11318396/6529533/fa07534e-c3ee-11e4-89e7-34231d64311a.png)

**Comment by kevin-brown** [comment]
This has to do with how Select2 will automatically escape characters to prevent XSS.

You can disable this by making `escapeMarkup` a no-op

```js
escapeMarkup: function (text) {
  return text;
}
```

This still needs to be documented though.

**Comment by rodogir** [comment]
It seems that the behavior has changed with Version 4. I created two examples that show the issue:

Version 4: http://jsfiddle.net/ok0c5bdm/1/
Version 3: http://jsfiddle.net/drv777h4/2/

**Comment by 0x30** [comment]
Duplicate of #3096

**Comment by 0x30** [comment]
might need to replace `html()` with `text()` [here](https://github.com/select2/select2/blob/fff04c3f0c096b9e0fdea7ae80b4f8ecef1c961c/src/js/select2/data/select.js#L208) to avoid double-encoding.
