### ISSUE TITLE
Force showing dropdown-container always above or below

### ISSUE THREAD

**Issue by ifthenelse** [select2/select2#3121]
As far as I know, there's no option which cover this.
Since it can't be just achieved via css customization, the only way is to intercept the opening of the select and the reposition the dropdown-container manually, but It's definitely not the best solution.
Any chance to see it in the upcoming v4.x?

**Comment by mh-nichts** [comment]
I would also be interested by this feature !

**Comment by leonardomdr** [comment]
I did this in Select2 3.5.2 to force the container to start above instead of below the search box.

In select2.js you search for "positionDropdown: function() {" and change to "positionDropdown: function(forceAbove) {"

In the same function, after the var settings, paste this code:
```javascript
forceAbove = typeof forceAbove !== 'undefined' ? forceAbove : false;
if (forceAbove) {
    enoughRoomAbove = true;
    enoughRoomBelow = false;
}
```

After that, to force your select2 to show above, use this

```javascript
.on("select2-open", function() { 
    $(this).select2('positionDropdown', true);
});

**Comment by apaulo** [comment]
There is a very simpler way to implement a forceAbove:

1) In select2.js search for "positionDropdown: function()";
2) at the var settings change 
`aboveNow = $dropdown.hasClass("select2-drop-above")`
to
`aboveNow = this.opts.forceabove || $dropdown.hasClass("select2-drop-above")`

3) Now you can setup select2 with option
`forceabove = true`

**Comment by ganholete** [comment]
Same question

**Comment by tirdadc** [comment]
I was considering switching from Chosen to Select2, but I was surprised to see that this was something you couldn't control, and worse, it would be inconsistent: depending on the contents of the dropdown, it alternates between above and below.

**Comment by oslnx** [comment]
```
<a id="country" data-type="select2" data-pk="1" data-select-search="true" data-value="0" data-original-title="Todos">Todos</a>

    $('#country').editable({
        pk: 1,
        name: 'country',
        savenochange: true,
        defaultValue: '0',
        mode: 'inline',
        emptytext: 'Todos',
        source: '/?json=countries',
        showbuttons: false,
        select2: {
            width: 200,
        }
    });
    $('#country').on('hidden', function(e, reason) {
        $(this).trigger('click');
    });
    $('#country').trigger('click');

SOURCE JSON: [{"id":"0","text":"Todos"},{"id":"BR","text":"Brazil"},{"id":"MX","text":"Mexico"}]

```

![opera_FFwkGC2iIU](https://user-images.githubusercontent.com/1692710/59158078-56a12780-8a8b-11e9-83ce-e76266603dd2.png)
![opera_uAp0a8epci](https://user-images.githubusercontent.com/1692710/59158079-5739be00-8a8b-11e9-93f6-08deda9c7b57.png)

**Comment by hassanrazmy** [comment]
It looks like making the bottom value auto forcefully in CSS can also do the trick. I used the following code and it is kind of working for me fine.
`
.my_select_picker_trigger.dropup .dropdown-menu {
    bottom: auto !important;
}
`

**Comment by aurovrata** [comment]
following @apaulo solution...
> There is a simpler way to implement a "forceabove" param:
> 
>     1. In select2.js search for "positionDropdown: function()";
> 
>     2. at the var settings change
>        `aboveNow = $dropdown.hasClass("select2-drop-above")`
>        to
>        `aboveNow = this.opts.forceabove || $dropdown.hasClass("select2-drop-above")`
> 
>     3. Now you can setup select2 with option
>        `forceabove = true`

in the latest version, you want to use

`this.options.get('forceabove')`

**Comment by mehulvardiya** [comment]
<img width="309" alt="dropdown" src="https://github.com/user-attachments/assets/b78dc7d7-efe0-4d02-929e-fc2d937fc97e">
 my site proper working but 2-3days Iface issue that is select2 dropdown I want open dropdown below or above
