### ISSUE TITLE
Programmatic Access Example never initiates select2

### ISSUE THREAD

**Issue by Jrizzi1** [select2/select2#3123]
I am trying to follow the example documentation for programmatic access to multi value, and having some issues example never initiates the select2 on the js-example-programmatic-multi

I was initially thinking the line should read 
```javascript
var $exampleMulti = $(".js-example-programmatic-multi").select2();
```
But I wasnt able to get that to work

current docs show:
```javascript
var $example = $(".js-example-programmatic");
var $exampleMulti = $(".js-example-programmatic-multi");
 
$(".js-programmatic-set-val").on("click", function () { $example.val("CA").trigger("change"); });
 
$(".js-programmatic-open").on("click", function () { $example.select2("open"); });
$(".js-programmatic-close").on("click", function () { $example.select2("close"); });
 
$(".js-programmatic-init").on("click", function () { $example.select2(); });
$(".js-programmatic-destroy").on("click", function () { $example.select2("destroy"); });
 
$(".js-programmatic-multi-set-val").on("click", function () { $exampleMulti.val(["CA", "AL"]).trigger("change"); });
$(".js-programmatic-multi-clear").on("click", function () { $exampleMulti.val(null).trigger("change"); });

```

where is select2 ever initialized for js-example-programmatic-multi ?

**Comment by kevin-brown** [comment]
We initialize most of the selects on the page at the very bottom.

It's assumed that once you hit that point, you've seen enough of them being initialized that we can skip it.

**Comment by Jrizzi1** [comment]
I'm not sure why you wouldn't want the examples to be full fledged examples that can stand alone, but ok , thanks for the quick reply
