### ISSUE TITLE
Different behavior when multiple attribute is dynamically added

### ISSUE THREAD

**Issue by juangarias** [select2/select2#3124]
I found that Select2 automatically draws first option as selected in multiple select control, but only if I dynamically add the multiple="multiple" attribute.
If this attr is in the HTML code, It works fine.

Is this a bug?

http://jsfiddle.net/r5py21hL/2/

**Comment by kevin-brown** [comment]
This isn't an issue with Select2, it's how your browser handles the change. I've updated your fiddle to automatically alert the selected value.

http://jsfiddle.net/r5py21hL/4/

As you can see, the issue happens before Select2 gets to it.

When you create a `<select>` with `<option>` tags, the first one is automatically selected if none of the others are. So when you change it to a multiple select, the first tag, which was already selected, is displayed as a selected tag by Select2.
