### ISSUE TITLE
After changing the selected option, scrolling is not re-enabled

### ISSUE THREAD

**Issue by quatrano** [select2/select2#3125]
This library does an amazing job of dealing with a "select" element within a scrolling region - when the element is focused, the region scrolls so that the element is fully visible.  Next, scrolling the region is disabled so that the options stay aligned with the element.

When I click on an option, scrolling is re-enabled.  When I blur the element, scrolling is enabled.  However, when I use my keyboard (ie: enter) to select an option, scrolling is never re-enabled.

The work around (from the user perspective) is to focus and blur the element again.  As an external developer I could create some event handler that re-enables scrolling in this case, but it would be ideal if this could be fixed internally.  Should be a one-liner, I just don't know where to look.  Thanks!

**Comment by kevin-brown** [comment]
I _think_ I understand the steps you are taking, but I'd rather clarify first so I don't later report that it can't be reproduced.

Can you give me a list of step-by-step instructions so I can verify that this is a bug?

**Comment by quatrano** [comment]
Thanks for the quick response!

Version:
4.0.0-rc.1

Setup:
Place a select element within a scrolling region.  Scrolling region = Outer element has a max-height and overflow:scroll, the inner element has a height greater than the max-height of the outer element.

1. Focus the select element by clicking on it.  (dropdown appears, first option is blue)
2. Press the enter key, selecting the first option.

Notice that the scrolling region no longer scrolls.

**Comment by quatrano** [comment]
Ok.  I investigated further and it seems to be unrelated to the enter button.  This happens if you change the selected option.  So change step 2 to:

2. Select an option other than the one that is currently selected.

This makes me think that the bug could be related to something we're doing while handling the change event (eg: re-rendering the template).  I did verify that this doesn't exist with version 3.5.2 (6633cda9061d9fc65075dd140c63f9a6adbcbd72)

**Comment by kevin-brown** [comment]
I cannot reproduce this issue. After selecting an option, any scroll blockers put in place by Select2 are removed and I am able to scroll.

This is the test case I used: http://jsbin.com/yiretujome/1/edit

Ubuntu 14.0, Chrome 40.

**Comment by braznaavtrav** [comment]
+1 Also experiencing this. @quatrano were you able to fix this or figure out what was going on?

**Comment by braznaavtrav** [comment]
To give more context around what is happening for me, I have a multi select box, if you select an option, the scroll blockers set in place by select2 seem to not be removed. After doing this, if you click the select to open the dropdown and then click anywhere else on the page to close it, the scroll blockers are removed. Any ideas?

**Comment by kevin-brown** [comment]
@braznaavtrav This was closed off as I was not able to reproduce the issue at the following jsbin.

http://jsbin.com/yiretujome/1/edit

If you are able to reproduce it there, can you answer the following questions

- What OS and Browser are you using?
- What steps (an exact list so we can reproduce it) are you following to reproduce the issue?

If you can't reproduce it there, it would be useful if you could link us to a jsfiddle/jsbin (or external page) where this issue can be reproduced.

**Comment by quatrano** [comment]
@braznaavtrav sorry for the delay, just revisiting this issue now.

So in the case that scroll blockers are not removed, [here's the offending line](https://github.com/select2/select2/blob/4.0.0-rc.2/src/js/select2/dropdown/attachBody.js#L110):

```
$watchers.off(scrollEvent);
```

The $watchers selection contains no elements, and therefore the scroll blockers aren't removed.

It's empty because this.$container is no longer in the DOM.  I know because the following snippet returns true in the success case, and false in the failure case (when executed in the scope of the line referenced above):
```
$.contains(document, this.$container[0])
```

So what's happening in our case is that we're inadvertently removing that element from the DOM, and select2 can't find the places where it attached the scroll-blocking event handler.  We're using Marionette and we're re-rendering the view that contains the dropdown.  My solution is to modify the DOM procedurally rather than relying on a template and render() call.

This must have worked differently in version 3.5.2... So I guess it's not a "bug", but @kevin-brown could you look into how this used to work (maybe clear the scroll blockers before firing the change event?)

**Comment by wbercx** [comment]
Ran into the same issue just now. We are also using Marionette and re-rendering the view containing the dropdown. By the time the browser gets to `$watchers.off(scrollEvent);`, as mentioned by @quatrano , the view has already re-rendered and `$watchers` works out to be empty. I guess we are just going to have to work around that.

As a side note, unrelated to this issue, I am not even sure what `scrollEvent` is actually supposed to refer to. The definition is: `var scrollEvent = 'scroll.select2.' + container.id;` For me, that always comes out as 'scroll.select2.undefined', but whatever it does seems to work anyway.

The reason why it is `undefined`, if you look at [line 104](https://github.com/select2/select2/blob/4.0.0-rc.2/src/js/select2/dropdown/attachBody.js#L104), you see that this function accepts `container` as its first parameter. When the function gets called, that actually appears to be a blank function. If I check the `arguments` to see what was actually passed on to the function, the actual `container` is argument number two.

If I change line 104 to be `AttachBody.prototype._detachPositioningHandler = function (fn, container) {`, now all of a sudden `container.id` is not undefined anymore. It does not affect the original issue though.

**Comment by kevin-brown** [comment]
Unfortunately I'm still hitting the issue where I can't reproduce this, which means I can't write a test to ensure a fix works.

Deferring back to https://github.com/select2/select2/issues/3125#issuecomment-87104722, if anyone can create a jsbin where this can be reproduced, that'd be awesome.

> @kevin-brown could you look into how this used to work (maybe clear the scroll blockers before firing the change event?)

It used to work by having a mask in the background, which implicitly blocked any and all interaction with the world outside of the Select2 dropdown.

**Comment by P0rnflake** [comment]
For me, this is still an issue in 4.0.1.

I have written a test case in jsfiddle, please see http://jsfiddle.net/pdvtkyfv/5/ .

In my case the test fails when the name attribute of the select box is part of a fildset, e.g. ```options[test]```. It seams like Jquery .on and .off cannot handle event ID's with specific caracters, so the created scroll event in ```AttachBody.prototype._attachPositioningHandler``` (f.e. "scroll.select2.select2-options[test]-gg") will not be properly detatched by ```AttachBody.prototype._detachPositioningHandler```.

As of the documentation of JQuery "Event names should only contain alphanumerics, underscore, and colon characters." (see http://api.jquery.com/on/#event-names).

Is there something against normalizing the event id before at-/detaching, and remove the brackets and other stuff?

In my opinion this issue should be handled as Major Bug, because this is a valid name attribute for a form element (@see https://www.w3.org/TR/html5/forms.html#attr-fe-name).

**Comment by kevin-brown** [comment]
Thanks for the jsfiddle, @P0rnflake. I was finally able to reproduce the issue and confirm that this is a duplicate of https://github.com/select2/select2/issues/3618.

**Comment by EABCenter** [comment]
Just an added note.  I ran into a similar issue to this and found a solution/work around, so I thought I would share.  

In my case, I was destroying/reloading Select2 while the pulldown was open; in a boot strap modal. When it is open, it hijacks the scrollbars of the parent/modal, to prevent alignment issues.  The problem is that it doesn't relinquish that control upon destruction.  

As soon as I realized what was happening, I was able to solve the issue by triggering a close, which lets go of the scroll bars, before destroying/reinitializing the plugin.  Hopefully this helps others.

**Comment by brassard** [comment]
As an FYI on this issue, the original issue can be solved by triggering reloads on the `select2:select` event and NOT on the `<select>` element's `change` event. When the reload is triggered on change, the elements are destroyed before select2 can issue a `close` event, which removes the scroll watchers from the parent elements.

Hopefully this helps someone.

**Comment by HellOfADeveloper** [comment]
I was also running into this problem.

I figured out, it happens when the identifier of the Event contains $ sign(s).

So I got this workaround (or fix) working for me...

var containerId = container.id.replace(new RegExp(/\$/, 'g'), "_");
var scrollEvent = 'scroll.select2.' + containerId;
var resizeEvent = 'resize.select2.' + containerId;
var orientationEvent = 'orientationchange.select2.' + containerId;

**Comment by ThePasko** [comment]
@kevin-brown this is still a problem.

The problem can be tracked down to this selector:
`var $watchers = this.$container.parents().filter(Utils.hasScroll);`
in both `_attachPositioningHandler()` and `_detachPositioningHandler()` functions.

This selector is not guarantied to select the same elements in case something changes on the page meanwhile. That way some event listeners are not removed.

Example:
1. User opens select2 dropdown -> `_attachPositioningHandler()` is fired and listeners are attached with `$watchers.on()` to elements that fulfill condition `Utils.hasScroll`
2. App refreshes page content of a div and now this div no longer has a scrollbar
3. User closes select2 dropdown -> `_detachPositioningHandler()` is fired and listeners are detached with `$watchers.off()` from elements that fulfill condition `Utils.hasScroll`. Div from step 2 is omitted and listener stays active.

**Comment by larza79** [comment]
@kevin-brown, we're using v4.0.3 and I have just confirmed this is a problem for us aswell. We're using a select2 to refresh a list of checkboxes, and because of this change in DOM, the $watchers array is one short when turning the listeners off.  I see this issue is closed, any chance it being repopened, or is there another issue somewhere?

**Comment by juanpscotto** [comment]
Hi, any news of this?? I'm having the same error, using v4.0.3 @kevin-brown

**Comment by Nelofie** [comment]
I found a solution here at [#4236](https://github.com/select2/select2/issues/4236)
@mahadoang 's comment. 
I'm using v4.0.3.

**Comment by Zdend** [comment]
@mahadoang's fix works indeed but unfortunately it's still not merged in v4.0.3 @kevin-brown 
In my case select2 blocks scrolling when it's inside of Bootstrap modal.

        $watchers.on(scrollEvent, function (ev) {
            var position = $(this).data('select2-scroll-position');
            if($(this).find('.select2-container--open').size() > 0) {
                $(this).scrollTop(position.y);
            }
        });

**Comment by autra** [comment]
@kevin-brown I have the same problem using select2 with yadcf (so datatables). Fixed it by using solution described in #4236.

**Comment by kevalbhatt** [comment]
@kevin-brown I am facing same issue, but my use case is different. 

Please find steps to reproduce this issue.

1 .Will do ajax on change of select2 (in my given example change select2 value)
2 . On success of ajax, will create html element in bootstrap modal. and at that time scroll is stooped.

Example ::  https://jsfiddle.net/kevalbhatt18/s7ttxdby/9/
Version of Select2 ::  https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js

Please let me know if need more clarification on it.

**Comment by Rolandkuku** [comment]
The following injects the fix using select2's internal require.

```
$.fn.select2.amd.require(["select2/dropdown/attachBody", "select2/utils"], (AttachBody, Utils) => {
    AttachBody.prototype._attachPositioningHandler = function (decorated, container) {
        var self = this;
        var scrollEvent = "scroll.select2." + container.id;
        var resizeEvent = "resize.select2." + container.id;
        var orientationEvent = "orientationchange.select2." + container.id;
        var $watchers = this.$container.parents().filter(Utils.hasScroll);
        $watchers.each(function () {
            $(this).data("select2-scroll-position", {
                x: $(this).scrollLeft(),
                y: $(this).scrollTop()
            });
        });
        $watchers.on(scrollEvent, function (ev) {
            var position = $(this).data("select2-scroll-position");
            $(self).scrollTop(position.y); // patch: this => self
        });
        $(window).on(scrollEvent + " " + resizeEvent + " " + orientationEvent,
            function (e) {
                self._positionDropdown();
                self._resizeDropdown();
            }
        );
    };
});
```

**Comment by rakshitkumarcse** [comment]
@kevin-brown @quatrano 
Is there any update on this issue? Or perhaps a workaround?
I use select2 in my website and this is a major issue for me.
I would be really glad if you could take out some time to respond.
Thanks!

**Comment by erjakhar96** [comment]
all you need to do
change in select2.js

isssue

       $watchers.on(scrollEvent, function (ev) {
             var position = Utils.GetData(this, 'select2-scroll-position');
             $(this).scrollTop(position.y);
     });

after fixed
          $watchers.on(scrollEvent, function (ev) {
			var position = $(this).data('select2-scroll-position');
			if($(this).find('.select2-container--open').size()>0)
			{
				$(this).scrollTop(position.y);
			}
		});

**Comment by chrisberry1** [comment]
confirmed the issue in latest version 4.0.13. but why hasn't the issue been fixed after being reported over 4 years ago? i used erjakhar96's solution.

**Comment by Jelmer7** [comment]
@kevin-brown This issue should be re-opened since it is still a present problem.
@erjakhar96 's solution works correct except instead of using `.size()` use `.length`
```
$watchers.on(scrollEvent, function (ev) {
  var position = $(this).data('select2-scroll-position');
  if($(this).find('.select2-container--open').length > 0)
  {
    $(this).scrollTop(position.y);
  }
});
```

**Comment by vinayinnoctive** [comment]
I am also facing similar issue. Using v4.0.2
In my case,
the issue is **not occurring after selecting** an option (via mouse / keyboard), **but after clearing existing selection**
```
$('select').select2({
    allowClear: true
});
```

**Comment by samadanc** [comment]
@wbercx I am also using marionette views. There's 2 problems I am facing:
- The scrolling is all weird. I have footers in my view and because the scrolling is all screwed, the select2s go behind the footers and are inaccessible.
- I am using select2 on a dynamic form which adds more fields (select2s) depending on the options chosen. But this is not possible because each time I call render() on a marionette view, all the select2s go empty.

**Comment by Dwingloo** [comment]
This is still an issue to our day, i ran into it today with same context, trying to re-open a modal containing select2 after change option in it.
 Jelmer7 already provided the solution, i tried it and edited the main js and re-minified which is something i hate to do on npm vendors, may fixed it on next release please?

**Comment by arthurmmedeiros** [comment]
> The following injects the fix using select2's internal require.
> 
> ```
> $.fn.select2.amd.require(["select2/dropdown/attachBody", "select2/utils"], (AttachBody, Utils) => {
>     AttachBody.prototype._attachPositioningHandler = function (decorated, container) {
>         var self = this;
>         var scrollEvent = "scroll.select2." + container.id;
>         var resizeEvent = "resize.select2." + container.id;
>         var orientationEvent = "orientationchange.select2." + container.id;
>         var $watchers = this.$container.parents().filter(Utils.hasScroll);
>         $watchers.each(function () {
>             $(this).data("select2-scroll-position", {
>                 x: $(this).scrollLeft(),
>                 y: $(this).scrollTop()
>             });
>         });
>         $watchers.on(scrollEvent, function (ev) {
>             var position = $(this).data("select2-scroll-position");
>             $(self).scrollTop(position.y); // patch: this => self
>         });
>         $(window).on(scrollEvent + " " + resizeEvent + " " + orientationEvent,
>             function (e) {
>                 self._positionDropdown();
>                 self._resizeDropdown();
>             }
>         );
>     };
> });
> ```

@Rolandkuku 's answer solved my case, but caused another issue. Now, when select2 is open and I scroll the background, the select2 element follows the position of the scroll. How could I keep it in it's correct position when scrolling?

**Comment by JeLLek1** [comment]
@arthurmmedeiros change option `dropdownParent` to something inside modal.
`el.select2({
	dropdownParent: el.parent()
});`

**Comment by Tonygolf** [comment]
Hello folks,
First thanks a lot to the guy who made this select2 plugin, very nice work.
I am in the same situation than you and for me that's only in a specific situation, i've made a video about that here : https://gestius.com/select2.mp4

It happen only in datatable in the other place no problem. I'm using 4.1.0-beta.1 since today but problem also appear on 3.0.5 (or something like this...). In the video I show when it works, when it bug and my code. I've tried all the solution I found. If I can help tell me, I hope a solution will be found.
Regards,

**Comment by Bernard-Murphy** [comment]
> all you need to do
> change in select2.js
> 
> isssue
> 
> ```
>    $watchers.on(scrollEvent, function (ev) {
>          var position = Utils.GetData(this, 'select2-scroll-position');
>          $(this).scrollTop(position.y);
>  });
> ```
> 
> after fixed
> 
> ```
>            $watchers.on(scrollEvent, function (ev) {
> 		var position = $(this).data('select2-scroll-position');
> 		if($(this).find('.select2-container--open').size()>0)
> 		{
> 			$(this).scrollTop(position.y);
> 		}
> 	});
> ```

Thank you sir! I faced a similar issue developing a React application that had a lot of automatically generated select2 dropdowns. It does indeed appear that the select2 freezes the scrolling and does not give it back in some situations.

**Comment by JocelynDelalande** [comment]
I can confirm bug as of 4.0.13 ; and that @arthurmmedeiros workaround works.

**Comment by joaf123** [comment]
# I recently encountered this bug running Bootstrap 3.4.7 and Select2 4.0.0. 

I have a modal window with a select2 element initialized with the dropdownParent option to fix the bug where the select dropdown ends up behind the modal window. 
When the "#RegKjoperDetaljerPanel" div is made visible, the modal ends up overflowing. And the scroll is blocked.

### Here is my HTML:
```html
<div class="modal inmodal" data-backdrop="static" id="NyKjoperVindu" tabindex="-1" role="dialog" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" runat="server" id="Button2"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title spraak" id="H2" runat="server">Registrer ny kjøper</h4>
            </div>
           
            <div class="modal-body">

                <div class="form-group">
                    <div id="NyKjoeperSokIbox" class="ibox float-e-margins">


                        <div class="ibox-title">
                            <span id="NyKjoeperSokSpan" class="spraak label label-info pull-right">Søk</span>
                            <h5 id="NyKjoeperSokHeading" class="spraak">Søk etter ny kjøper</h5>
                        </div>


                        <div class="ibox-content">
                            <div class="row">
                                <div class="form-group">

                                    <!-- Select2 Element -->
                                    <div id="SelectParent" class="col-md-3">
                                        <label id="NyKjoeperSokLandSpan" class="spraak" style="padding-left: 0px !important;">Land</label>
                                        <select id="NyKjoperSokLandSelect" class="form-control">
                                            <option value="">Velg Land</option>
                                        </select>
                                    </div>

                                    <div class="col-sm-3">
                                        <label id="NyKjoeperSokPersOrgNrSpan" class="spraak" style="padding-left: 0px !important;">Fødselsnr./Orgnr</label>
                                        <input id="NyKjoeperSokPersOrgNrInput"  type="text" value="" class="form-control" />
                                    </div>

                                    <div class="col-sm-3">
                                        <label id="NyKjoeperSokNavnSpan" class="spraak" style="padding-left: 0px !important;">Fornavn/Selskapsnavn</label>
                                        <input id="NyKjoeperSokNavnInput" type="text" value="" class="form-control" />
                                    </div>

                                    <div class="col-sm-3">
                                        <label id="NyKjoeperSokEtternavnSpan" class="spraak" style="padding-left: 0px !important;">Etternavn</label>
                                        <input id="NyKjoeperSokEtternavnInput" type="text" value="" class="form-control" />
                                    </div>

                                </div>

                                <div class="form-group">
                                    <div class="col-sm-10 m-t-md">
                                        <div class="alert alert-warning" style="display:none" id="RegKjoperWarningDIV">
                                            <p id="RegKjoperWarningPar" runat="server" style="text-align: left"></p>
                                        </div>
                                        <div class="alert alert-danger" style="display:none" id="RegKjoperDangerDIV">
                                            <p id="RegKjoperDangerPar" runat="server" style="text-align: left"></p>
                                        </div>
                                        <div class="alert alert-success" style="display:none" id="RegKjoperSuccessDIV">
                                            <p id="RegKjoperSuccessPar" runat="server" style="text-align: left"></p>
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <input id="NyKjoeperSokBtn" readonly="true" onclick="RegKjoperSok();" type="button" value="Søk" class="btn btn-primary m-t-md pull-right" />
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="hr-line-dashed"></div>

                <div class="form-group" id="RegKjoperDetaljerPanel" style="display:none;">
                    <!-- A bunch of elements here that make the modal overflow when this div is made visible -->
                </div>
            </div>
        </div>
    </div>
</div>
```

### Here's my JavaScript:
```javascript
function RegKjoperSok() {
    $.ajax({
        type: "POST",
        url: "../********/Masse-Overdragelse.aspx/KjoperSokRutine",
        contentType: "application/json; charset=utf-8",
        dataType: "json",

        success: function (resultat) {
                $("#NyKjoperSokLandSelect").select2({disabled:true}).prop("readonly", true);
                $("#RegKjoperDetaljerPanel, #NyKjoeperSokFooter").show();
            } 
        }
    });
}

// Init Select when modal window is shown.
$("#NyKjoperVindu").on('shown.bs.modal', function () {
    if (!($('#NyKjoperSokLandSelect').hasClass("select2-hidden-accessible"))) {
        $("#NyKjoperSokLandSelect").select2({
            dropdownParent: $(".modal.inmodal.in")
        });
    }
});
```

### To fix this problem, what I did was unbind the modal window from the 'scroll.select2' event with 
```javascript
jQuery("#ModalSelector").off('scroll.select2');
```

### So my new JavaScript with fix would be:
```javascript
function RegKjoperSok() {
    $.ajax({
        type: "POST",
        url: "../********/Masse-Overdragelse.aspx/KjoperSokRutine",
        contentType: "application/json; charset=utf-8",
        dataType: "json",

        success: function (resultat) {
                // This is where i make a bunch of hidden elements in the modal visible which causes an overflow.
                $("#NyKjoperSokLandSelect").select2({disabled:true}).prop("readonly", true);
                // Before i make the div causing an overflow visible, ill unbind the scroll.select2 event:
                $("#NyKjoperVindu").off('scroll.select2');
                // There has to be a better place to put this unbinding but this worked for me and I really needed a quick solution.
                $("#RegKjoperDetaljerPanel, #NyKjoeperSokFooter").show();
            } 
        }
    });
}
```

Hope this helps out someone struggling with this awfully anoying bug!

**Comment by StuffOfInterest** [comment]
It is too bad the issue here appears to still be present.  I'm seeing this issue in a React component which works similar to a Bootstrap modal.  The component contains a button that when clicked shows a div which contains a cascade of select lists (all wired into Select2).  If one is changed the one below is reinitialized as it needs to pull in a set of records based on the value selected above it.  The select lists use AJAX data loading with search and infinite scroll.  When one needs to be updated the original is taken down with "`.select2('destroy')`" and then reinitialized with "`.select2(options)`".  The destroy operations can take place in the React functions of either "`componentDidUpdate()`" or "`componentWillUnmount()`".

As soon as "`.select2('destroy');`", the page will no longer vertically scroll.

I've tried the fixed described above including:
* Changing the parent
* Call "off" for scroll before destroying
* The prototype hook into "_attachPositioningHandler"

None worked.

This is happening with version 4.0.3 of Select2 and version 16.10.2 of React.

**Comment by txeto90** [comment]
Hello, I have this issue on Angular 13. Can somebody help me? I'm using 4.1.0 version and scroll is freezed when I delete an option of multiple select.
Thanks.

**Comment by instantdynamic** [comment]
> Hello, I have this issue on Angular 13. Can somebody help me? I'm using 4.1.0 version and scroll is freezed when I delete an option of multiple select. Thanks.

I also had this problem - I made ajax resuest after change select, and scroll was frozen when an option of multiple select was deleted. I added  .select2('open').select2('close') after changing and it helped
