### ISSUE TITLE
Loading remote data freezes after a few loads

### ISSUE THREAD

**Issue by gazMac2** [select2/select2#3129]
Hi,
I have noted that in both 3.X and 4 that if you call remote data, everything works fine, but loading more data crashes the select box after just a few reloads.

You can try yourself on the Loading remote data example on the example page. Just put in the value "1" and try scrolling down to load more results.

In my case I can't get past 11 loads without it freezing and just displaying "Loading More Results". 

Tested on both Firefox 36.0.1 and IE 11.

(Just to note that I can get 11 re-loads with FF but only 8 with IE, so I wonder if it's a memory thing?)

Thanks,
Gary

**Comment by kevin-brown** [comment]
> (Just to note that I can get 11 re-loads with FF but only 8 with IE, so I wonder if it's a memory thing?)

Possibly.

Unfortunately without a test case to work with, there isn't much that can be done to debug the issue.

**Comment by gazMac2** [comment]
Hi Kevin,

The Loading Remote Data example on the https://select2.github.io/examples.html page works as a test case.

What I have found from my own testing is that the number of times you can reload data depends on the number of records you bring back. For example, if you bring back 100 records, you can reload it 10 times and if you bring back 200 records, you can only reload it 5 times.

It looks a bit like we hit a limit in the number of rows we can have in the select box when loading remotely (or hit a memory ceiling).

All the best,
Gary

**Comment by gazMac2** [comment]
Actually, this may be more of an exception handling thing when dealing with remote data!

When I pass a set of data that I am in control of and I know is clean, then it works as it should. However if there is some improperly formatted JSON, it causes this freeze, probably becasue it is not receiving data.

 I.e when I had it connected to a messy database and brought back some blank rows that gave the following PHP error, I witnessed the same freezing of the Select2 box.
[10-Mar-2015 12:15:21] PHP Warning:  json_encode() [<a href='function.json-encode'>function.json-encode</a>]: Invalid UTF-8 sequence in argument in FILEPATH
