### ISSUE TITLE
Multi-value select box - clicking remove opens selections

### ISSUE THREAD

**Issue by Jrizzi1** [select2/select2#3132]
To replicate:
using the Multi-select example or programmatic multi-select, add any selection, then click the remove (select2-selection__choice__remove) 

Notice that on removal it always reopens the available selections, this did not occur in builds 3.5.xx, it simply removed the selection

**Comment by greggulrajani** [comment]
**bump** related https://github.com/select2/select2/issues/3209

**Comment by kevin-brown** [comment]
Merged into https://github.com/select2/select2/issues/3209.
