### ISSUE TITLE
select2-container on WordPress customizer

### ISSUE THREAD

**Issue by maimairel** [select2/select2#3133]
When using select2 in WordPress customizer, the select2-container falls behind the wrapper element of the customizer that has a z-index of 500000, so it's not visible unless I change the z-index. What's the best solution to fix this? Should I just add a z-index via CSS?

Thank you!

**Comment by kevin-brown** [comment]
> that has a z-index of 50000

And _this_ is why we previously had a z-index that was incredibly high.

> What's the best solution to fix this?

Save everyone who relies on `z-index` some trouble, get them to lower it.

> Should I just add a z-index via CSS?

That's a reasonable solution for now.
