### ISSUE TITLE
4.0.0-rc.1 How can I get selected object (remote data)

### ISSUE THREAD

**Issue by prophe05** [select2/select2#3136]
How can I get selected object with select2? Not only the text using $('#myid').val() but js object???
$('#myid').select2("data") not work, I use ajax to retrieve data.

**Comment by kevin-brown** [comment]
You can either use the latest master or wait a few days for `rc.2` which includes the fixed `select2('data')`.

**Comment by prophe05** [comment]
Ok, thank you!

**Comment by prophe05** [comment]
$('#myid').select2("data") works fine, but has a bug while JSON serialization in chrom.
var obj = $('#myid').select2("data")[0], obj provide a lot of additional fields (like _resultId, disabled, element etc.). And when I try to serialize it to json in chrom like JSON.stringify(obj) I have an exception:

TypeError: Converting circular structure to JSON

If some one really need additional fields in obj you can move all additional info in one field and selected object into another, for example context and item. 

So,  var a = $('#myid').select2("data")[0] .item is valid. And it is very simple to serialize it and send to server.

**Comment by kevin-brown** [comment]
The circular structure comes from how Chrome (and Chrome specifically) handles jQuery elements - it also serializes their internal data.

You can avoid this issue by just deleting the `element` property from the object that is returned.

**Comment by prophe05** [comment]
Yes, I know this. I do like you propose now. But I also have to delete all additional fields (it specific of server method). So my js code looks ugly and  tricky...
