### ISSUE TITLE
4.0.0 rc1 : translation not working

### ISSUE THREAD

**Issue by qcaron** [select2/select2#3137]
Hi guys,

I downloaded the first release candidate for version 4 but I could not manage to make translation working. I tried the following for both French and Spanish without success:

First, I import javascript files as follow:
```
<script src="path/to/select2/dist/js/select2.min.js"></script>
<script src="path/to/select2/dist/js/i18n/fr.js"></script>
```

Then I apply options on my select as follow:

```javascript
$("#my-select").select2({
    maximumSelectionLength: 3,
    language: "fr",
});
```

My console shows no error. The same goes using select2.js instead of select2.min.js.

Thanks!
Quentin

**Comment by kevin-brown** [comment]
I cannot reproduce the issue you are seeing.

Here is the test case I used: http://jsbin.com/vononirehu/1/edit

**Comment by qcaron** [comment]
Okay maybe I should have added a bit more details here. Anyway, your explanation is a bit elusive to me.

Please check out that JS Bin and let me know if you see some French when you try to select a second option: http://jsbin.com/bugawebiqa/1/

Cheers

**Comment by kevin-brown** [comment]
The issue is that `maximumSelected` [is misspelled in the French locale](https://github.com/select2/select2/blob/e3d7cd2d6952fc4412e953f2b749ede316e70dc5/src/js/select2/i18n/fr.js#L29).

**Comment by qcaron** [comment]
You're right! There are 15 languages with the same spelling error (according to GitHub search results). I will fork and ask for pull request.

Thanks for your time!
