### ISSUE TITLE
When the select2-container is off the visible area, wrong options are selected

### ISSUE THREAD

**Issue by brunorios1** [select2/select2#3138]
Hi,

When I scroll the page and the select2-container is off the browser visible area, wrong options are selected when clicked.

It's easier to reproduce when we have a select2-results with high max-height or with max-height: none;

It's almost impossible to select the options that are in the bottom of the list.

Examples:

Max-height none: https://jsfiddle.net/bg5es49k/
Max-height 1000px: https://jsfiddle.net/bg5es49k/1/

Try to select Option 16, you'll get Option ~6.
Try to select Option 21, you'll get Option ~10.

Tested on a 1366x768 monitor.

How can I avoid this behaviour?

Thanks!

**Comment by kevin-brown** [comment]
Try Select2 4.0, there were quite a few bugs in how the highlighting worked that should have been fixed.

**Comment by brunorios1** [comment]
Hi @kevin-brown,

It´s really fixed: https://jsfiddle.net/x2c5s7e1/

Thanks for the feedback and for this great plugin.
