### ISSUE TITLE
can't delete selected data on hidden select (BUG)

### ISSUE THREAD

**Issue by JawaJava** [select2/select2#3140]
is my problem, that bug i'think...

![5](https://cloud.githubusercontent.com/assets/7752753/6620718/dd079b3a-c904-11e4-9d05-b4275c59e52e.png)

**Comment by kevin-brown** [comment]
You can still unselect options without any issues in Select2 4.0. What you're seeing here is that Select2 does not set the `selected` attribute on the HTML `<option>`.
