### ISSUE TITLE
Loading remote data and selected

### ISSUE THREAD

**Issue by Knoxvillekm** [select2/select2#3148]
Remote data contains only not selected options and don't work deselect on select this option again.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/ivaynberg/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by Knoxvillekm** [comment]
This bug present in example "Loading remote data", select some repo and then find it again. And this option not selected ().
When use multiple: this option after second selecting must be removed from selected.

**Comment by Knoxvillekm** [comment]
With ajax: Deselect don't work with any event (mouseup, enter, ctrl+space, etc).
Without ajax: Deselect don't work with enter.

**Comment by kevin-brown** [comment]
Reopening this while I build out an example for multiple selects that can be used for testing.

**Comment by kreintjes** [comment]
I believe I am having a similar issue. When you have a multiple select, you can click a selected option again to deselect it. However, when loading remote data using the ajax option, this does not work. The dropdown closes, but the option isn't removed from the set of selected options.

I think if you set multiple="multiple" the remote data select example on the examples page (https://select2.github.io/examples.html), you can reproduce this problem. The tags example (which doesn't use remote data) does not have this problem.

**Comment by chaimann** [comment]
+1
also just checked - `select2:unselect` event seems to be fired, not deselecting an option though

**Comment by chaimann** [comment]
@kevin-brown i think i've found the reason

```javascript
 SelectAdapter.prototype.unselect = function (data) {
    var self = this;
    ...
    ...
    ...
    this.current(function (currentData) {
      var val = [];

      for (var d = 0; d < currentData.length; d++) {
        id = currentData[d].id;

        if (id !== data.id && val.indexOf(id) === -1) {
          val.push(id);
        }
      }

      self.$element.val(val);

      self.$element.trigger('change');
    });
  };
```

Notice line 
``` javascript
if (id !== data.id && val.indexOf(id) === -1) {
```

In my case `id` is `"37"` - a string, and `data.id` is `37` - an integer; thus actually it will never omit deselected id, and will always push it to the resulting values array.

If i change `!==` to `!=` then unselect works as expected.

**Comment by victorelec14** [comment]
On remote Ajax the 'selected' option dont go ( with groups) : 

`json:
{"results":[{"text":"User","children":[{"id":37,"text":"Victor","selected":true},{"id":153,"text":"Manuel","selected":false}]},{"text":"Support","children":[{"id":39,"text":"Robert","selected":true},{"id":36,"text":"Rudolf","selected":false},{"id":202,"text":"Claus","selected":false}]}]}`
