### ISSUE TITLE
Separate widths

### ISSUE THREAD

**Issue by Karmalakas** [select2/select2#3150]
4.0.0-rc1 can't figure out how to set separate widths for input and dropdown. In v3.5 it was easy by adding a class to dropdown and styling in CSS. Actually I can't figure out even how to change input width through CSS. Now I'm just adding `style="width: ...px"` to `<select>` tag

**Comment by cocowalla** [comment]
+1 Need to be able to specify separate width for the dropdown, so it can be wider than the width of the input

**Comment by cocowalla** [comment]
+1 need to be able to specify a width for the dropdown, separate from the width of the input, typically to make the dropdown wider. Ideally you would be able to specify a percentage, e.g. 150%.

I can change the width of the dropdown using:

```
.select2-container--open .select2-dropdown {
    width: 300px !important
}
```
But this doesn't work with percentages
