### ISSUE TITLE
Support blur and focus events

### ISSUE THREAD

**Issue by VD17593** [select2/select2#3152]
In previosus versions I used blur this way: 

    $eventSelect.on("select2-blur", function(e) {...});

On the last version apparently the syntax has changed, but still I can't get it right:

    $eventSelect.on("select2:blur", function (e) { ... });

**Comment by kevin-brown** [comment]
This wasn't migrated over to 4.0 as we are looking to trigger the native `focus` and `blur` events instead of making our own.

**Comment by StoicLoofah** [comment]
Chiming in to say that this would be a great addition! This is unfortunately a blocker for us to move from 3.5 to 4

**Comment by kevin-brown** [comment]
Merging this into https://github.com/select2/select2/issues/1908#issuecomment-76546178. If you are interested in adding support, feel free to open a pull request or hop in the IRC channel/mailing list for some help.

**Comment by kquinbar** [comment]
so is there no workaround to support the blur event as described or will support be coming anytime soon?

I also had something similar where I need to know when select2 loses focus
$eventSelect.on("select2-blur", function (e) { ... });

**Comment by kevin-brown** [comment]
> so is there no workaround to support the blur event as described

Correct.

> will support be coming anytime soon?

Aiming for 4.0.1, that all depends on when a patch/pull request ends up landing.

**Comment by samholmes** [comment]
So in summary, is there a workaround for focus and/or blur events?

**Comment by kquinbar** [comment]
correct, according to Kevin there is no workaround for either.

**Comment by samholmes** [comment]
@kquinbar Then why is this issue closed?

**Comment by kquinbar** [comment]
its been merged into issue #1908

**Comment by kevin-brown** [comment]
Discussion about the `focus` and `blur` events should be put in https://github.com/select2/select2/issues/1908.
