### ISSUE TITLE
Multiple selection not working properly on mobile devices

### ISSUE THREAD

**Issue by sommerfn** [select2/select2#3162]
Hi,

we tried using a select2 with multiple selection, but found that it doesn't behave like it should on mobile devices (a Nexus 9 and a Samsung S3 were used for testing):
- after selecting an item in the menu or typing something, the keyboard isn't collapsed automatically
- especially on smartphones (but also on tablets), it is very difficult to deselect already selected items via the small "x" symbol because it is just too small. Maybe allowing deselecting by just tipping the selected item again (outside of the dropdown menu) would be better here

We used select2 4.0 for testing. Aside from the multiple select boxes, everything seems to work quite neatly compared to the 3.5 version.

**Comment by alexweissman** [comment]
These issues are discussed in more detail in #4425.
