### ISSUE TITLE
Bug destroying select2

### ISSUE THREAD

**Issue by murzid** [select2/select2#3173]
I have a selectbox called "condition", i want to control another selectbox with "condition" value. So after "condition" is selected, then another selectbox appear. 

But when i change again the "condition" value or clear the selected value, output selectbox still appear (can't auto hide). It's not select2, but normal <select>. And after that "condition" can't be cleared.

This is the sample fiddle :
http://jsfiddle.net/murzid/hrLu8az9/1/

**Comment by vedmack** [comment]
Same here

While the following code 
`$(someSelector).select2("destroy").select2(columnObj.select_type_options);`
was working in 3.5 **it fail** in 4.0.0-rc.2 with the error `Uncaught TypeError: Cannot read property 'destroy' of undefined`

**Comment by kevin-brown** [comment]
@murzid I can't reproduce your issue, but I'm also not totally sure what it is.

`select2:unselect` is only triggered when the "x" is clicked, which is correctly destroying the select boxes. The `change` event is triggered whenever the value changes.

I don't want to silence the fact that `select2("destroy")` is being called on an element without Select2, as something feels wrong there. Though I do see that Select2 3.x didn't do anything, so I might reduce this down to a warning when `select2()` is called on an element where it hasn't been initialized.

**Comment by ederbond** [comment]
Same problem here.

**Comment by lxlneo** [comment]
Same problem here.@4.0.2
