### ISSUE TITLE
Selection opens slowly on Android 4.1 

### ISSUE THREAD

**Issue by VD17593** [select2/select2#3174]
With version 4, opening the selection box on Android 4.1 (and downwards) takes about 5 seconds.
Is there a way to speed this up?

Tried with the basic : 

```
$(".js-example-basic-single").select2();
```

**Comment by Igloczek** [comment]
I have same problem, but only select with larger number of options (like country select) and search input.

**Comment by pedrofurtado** [comment]
https://github.com/select2/select2/issues/3854
