### ISSUE TITLE
AMD environment - do not use $ for jQuery

### ISSUE THREAD

**Issue by centi** [select2/select2#3175]
At the very end of the javascript file, there is a line, which holds the AMD module references on jQuery function. But it wrongly uses `$` instead of `jQuery` keyword and ends with `$ is undefined` error:

`$.fn.select2.amd = S2;`

But the factory uses `jQuery` keyword for the loaded dependency. So the line should look like this?

`jQuery.fn.select2.amd = S2;`

**Comment by kevin-brown** [comment]
Fixed on master, only place we did it.
