### ISSUE TITLE
Loading array data

### ISSUE THREAD

**Issue by Souldjinn** [select2/select2#3176]
[Documentation](https://select2.github.io/examples.html#data-array) states that you can pass an array through the data option with a select element.  If you try to use .select2(data:data) on a select element you will get an error telling you the option is not usable on a select element.

**Comment by behcet-li** [comment]
@Souldjinn Try ```$('element).select2({ data: data })```. Notice the brackets.

**Comment by Souldjinn** [comment]
@behcet-li I ended up using an <input> instead. Thanks though.

**Comment by kevin-brown** [comment]
It only works on a `<select>` element in 4.0.0. Use `<input type="text" />` in 3.5.2.
