### ISSUE TITLE
Allow for a identifiying class option within the container adapter or whatever

### ISSUE THREAD

**Issue by Sammaye** [select2/select2#3182]
I added my own CSS theme for some of my selects but since the default attachment of the container is on body end it is hard to style the results in there.

Would be good if an identifying class could be added so it could be picked out.

**Comment by kevin-brown** [comment]
If you set a custom theme, a class will be appended to the containers wrapping both the selection and the dropdown called `select2-container--[theme]` (`select2-container--default` for the default) which can be used for styling.

If you look at the first line of the theme files, [you'll see that is how we are namespacing themes](https://github.com/select2/select2/blob/9318980651e5bf471c412834139a03bf5de54f94/src/scss/theme/default/layout.scss#L1).

**Comment by Sammaye** [comment]
Awesome, I saw that but was unsure if it would fully fit the job
