### ISSUE TITLE
No focus when typing selection

### ISSUE THREAD

**Issue by VD17593** [select2/select2#3187]
Starting with a selected item. When, to change the selection, the user starts typing, the selection moves to the end of the list and no active selection is displayed.

With the default examples, first select 'Wyoming', and then type 'a'.

Previously (and what is expected) the first item of the selection is visible and focused.
On the v4, the selection moves to the end of the list without any selection.

Previously:
![previous_v3_](https://cloud.githubusercontent.com/assets/5879012/6798328/49e6cacc-d20c-11e4-8732-f415414ecbb9.png)

On v4:
![actual_v4](https://cloud.githubusercontent.com/assets/5879012/6798358/91b03ec4-d20c-11e4-9649-35ea603dddbc.PNG)

**Comment by alexweissman** [comment]
I can't seem to replicate this on the new site (v4.0.6-rc.1) - this may have been resolved as part of some of the recent fixes for other focus-related issues.
