### ISSUE TITLE
data-* attributes not all working

### ISSUE THREAD

**Issue by Karmalakas** [select2/select2#3189]
Didn't have enough time to check them all, but `templateResult` definitely doesn't work. I have

```
function doSomeStuff() {
    console.log('stuff');
}
```

and I have `<select class="select2" style="width: 400px" data-ajax--url="/url" data-placeholder="Select" data-template-result="doSomeStuff">`. I get `Uncaught TypeError: string is not a function`. I believe it can be fixed using `window[templateResult]` or something like that.

**Comment by sn3p** [comment]
What version are you using?

In v3.5.2 `minimumResultsForSearch ` (`data-minimum-results-for-search`) doesn't work either (https://github.com/select2/select2/issues/3199)

**Comment by Karmalakas** [comment]
Sorry, forgot to mention. v4.0.0-rc2
I think it's just that a string is being called as a function without any checking

**Comment by kevin-brown** [comment]
The `data-*` attributes are designed to be used for "simple" options, like enabling tags or setting the minimum input length for searches.

Detecting if an option should be a function and automatically calling that is too much "magic" for my tastes, and I can't think of a clean and flexible way of doing it.

**Comment by Soullivaneuh** [comment]
@kevin-brown Any chance to have a workaround?

I have a project with global select2 init with only data-attribute options...

**Comment by Soullivaneuh** [comment]
My workaround (in coffeescript):

```coffee
# Select2
select2Config =
  width: '100%'
startSelect2 = (jqElem) ->
  config = select2Config

  templateResult = jqElem.data 's2-template-result'
  if templateResult?
    config.templateResult = window[templateResult]

  jqElem.select2 config

$('.select2').each ->
  startSelect2 $(this)
$(document).arrive 'select.select2', ->
  startSelect2 $(this)
```

In a nutshell, prepend all "function" options with `s2-` and assign them manually on select2 configuration.

Note: This work for function without scope (`window[templateResult]`). For more advanced configuration, please see: http://stackoverflow.com/a/359910/1731473
