### ISSUE TITLE
Allow the term to be referenced in `language.noResults`

### ISSUE THREAD

**Issue by psnma** [select2/select2#3190]
Hi, I'm using select2 4.0.0 and trying to show modified "no results", but doesn't work:

``` js
$('#id_categoria').select2(
    {
        placeholder:'Selecione',
        minimumInputLength: 2, 
        noResults: function(term) {
             return "No results found. Add <b>" + term + "</b>?";
        }
    }
);
```

**Comment by kevin-brown** [comment]
You need to put `noResults` under the `language` key.

```js
$('#id_categoria').select2(
    {
        placeholder:'Selecione',
        minimumInputLength: 2, 
        language: {
             noResults: function(term) {
                 return "No results found. Add <b>" + term + "</b>?";
            }
        }
    }
);
```

**Comment by SAFIII** [comment]
I have the same problem, and I found my answer in this link

https://groups.google.com/forum/#!topic/select2/WUbL1hcNByU

**Comment by SAFIII** [comment]
You should be able to use `language: 'es'` to specify the language, but you have to make sure to include the language file in the page before you initialize Select2 (but after you include Select2). Select2 cannot automatically load files, unless you are in a strict AMD environment using an AMD loader (you aren't), so you still have to include them on the page.

**Comment by emir** [comment]
In this scenario how do you get term? I am currently getting an undefined. Is there any solution for passing term under the noResults?

**Comment by daninfpj** [comment]
`term` is `undefined` in 4.0.3

The way I got it to work is using the `event` var

`event.target.value`

**Comment by dariospadoni** [comment]
@daninfpj will you please explain how? `event.target.value` is not actually set with `term` when noResults is fired.

**Comment by daninfpj** [comment]
I'm just doing something like this, using 4.0.3:

```javascript
$('#select').select2(
    {
        language: {
             noResults: function(term) {
                 console.log(term);
                 console.log(event.target);
                 console.log(event.target.value);
            }
        }
    }
);
```

`term` is `undefined`
`event.target` is the select2 search field (`input.select2-search__field`)

**Comment by dariospadoni** [comment]
Ok, it looks different to me, maybe because I'm using ajax to fetch the options to show; in my case `event.target` it's a `XMLHttpRequest` object.

**Comment by wpemvikas** [comment]
how to pass this reference in 
noResults: function(){
}

**Comment by wpemvikas** [comment]
$(".skill_id").select2({
    placeholder: "Select your skills",
    context: this,
    language: {
        noResults: function() {
            return "<a href='javascript:void(0)' class='custom-skill-with-work'>Click to add above skill</a>";
        },
    },
    escapeMarkup: function(markup) {
        return markup;
    },
});
$(document).on("click", ".custom-skill-with-work", function () {
    $(this).closest('.custom-skills-with-work-section').css({ display: "block" })
});

the problen is that i can not target custom-skills-with-work-section class by using this how to solve this

**Comment by BBLopez** [comment]
I did this and it's working :) I hope it can help.

I store the search term in an external variable which is updated on every `keyup` event as long as the target is a select2 search input. Then, in the `noResults` callback of select2 I get the value of that variable to print the term.

![image](https://user-images.githubusercontent.com/37807811/158988577-bf5afaf0-a363-4db8-8505-33c7d20981a4.png)

```javascript
language: {
   noResults: () => {
       return htmlToElem(
           `<span class="d-inline-flex w-100 justify-content-between align-content-center">
               <span class="text-muted">No se ha encontrado el autor "${this.currentSelect2Search}".</span>
               <button type="button" class="btn btn-default btn-sm"><i class="fas fa-plus fa-sm"></i> Añadir nuevo autor</button>
           </span>`
       );
  }
}

document.addEventListener('keyup', (e) => {
   const target = e.target.closest('.select2-search__field');

   if (target) {
      this.currentSelect2Search = target.value;
   }
});
```

**Comment by eladavron** [comment]
An easier way to do this without adding your own event listener is:

```js
language: {
    noResults: () => {
        var term = $('#select').data("select2").selection.$search.val();
        return htmlToElem(
            `<span class="d-inline-flex w-100 justify-content-between align-content-center">
            <span class="text-muted">No se ha encontrado el autor "${term}".</span>
            <button type="button" class="btn btn-default btn-sm"><i class="fas fa-plus fa-sm"></i> Añadir nuevo autor</button>
            </span>`
        );
   }
}
```
