### ISSUE TITLE
blur the select2 once the selection is complete

### ISSUE THREAD

**Issue by suriyagp** [select2/select2#3193]
want to loss the fouc from the select2 box once the selection is completed.

**Comment by datafunk** [comment]
pretty simple, just add

    document.activeElement.blur();

**Comment by kevin-brown** [comment]
Specifically, do this on the `select2:select` event.

```js
$("select").on("select2:select", function () {
  $("select").blur();
});
```

**Comment by suriyagp** [comment]
is the select event available in the previous version of select2??

**Comment by kevin-brown** [comment]
@suriyagp I believe it's available at the `select2-selecting` event and it triggers slightly earlier than the current `select2:select` event.
