### ISSUE TITLE
Selection doesn't change height when using closeOnSelect: false

### ISSUE THREAD

**Issue by Knoxvillekm** [select2/select2#3194]
with closeOnSelect: false

Input heigth changed but result(dropdown) stay at one position.

http://jsfiddle.net/Knoxvillekm/mmkgue1c/

**Comment by Julie95** [comment]
I have the same issue. Here is a working fiddle : http://jsfiddle.net/dmctjeu0/

**Comment by alexweissman** [comment]
This conversation is continued in #4377.
