### ISSUE TITLE
How to sort by text in select2?

### ISSUE THREAD

**Issue by kumaroswal** [select2/select2#3195]
I am on version 4.0.0-rc2
My list from the database is coming unsorted.
Do we have an attribute in select2 to sort these alphabetically by their display value.

**Comment by zac156** [comment]
Anyone got a response to this question? I am struggling with the same issue. Seems that sortedResults could have been previously used in an older version but not anymore?

Thanks

**Comment by kumaroswal** [comment]
I guess you just need to update to the stable version of 4.0 now. That should take care of it.

**Comment by kevin-brown** [comment]
Select2 also provides the `sorter` option which can be used to sort results. It was previously called `sortResults` (I think?) and behaved slightly differently.

**Comment by fabienheureux** [comment]
hi @kevin-brown, I'm trying to get my <option> sorted by text (and not by value), but I can't find any documentation about `sorter` option.

Found this thread about previous version sorting: http://stackoverflow.com/questions/24520524/select2-jquery-plugin-is-there-a-way-to-sort-a-list-of-tags-alphabetically

**Comment by Chealer** [comment]
This can be achieved using the following option:
```
					sorter: function(data) {
						return data.sort(function (a, b) {
							if (a.text > b.text) {
									return 1;
								}
								if (a.text < b.text) {
									return -1;
								}
								return 0;
							});
						}
```
