### ISSUE TITLE
configuring/overwriting minimumResultsForSearch via data attributes

### ISSUE THREAD

**Issue by sn3p** [select2/select2#3199]
I'm trying to configure (overwrite) the `minimumResultsForSearch` option via data-attributes, but this doesn't work:

```html
<select data-minimum-results-for-search="Infinity">
```
Also tried `data-minimumResultsForSearch` (camelCase and lowercase).

Setting it via javascript works as aspected:
```javascript
$('select').select2({ minimumResultsForSearch: Infinity });
```
[JSFiddle](http://jsfiddle.net/sn3p/5pgvuncs/)

It seem to be working in [v4.0.0-rc.2](https://github.com/select2/select2/releases/tag/4.0.0-rc.2) but I'm still using v3.5.2 ([select2-rails](https://github.com/argerim/select2-rails) isn't updated yet).

Is this a known issue? Is there a workaround?

**Comment by kevin-brown** [comment]
`data-*` attribute support for most options is new in 4.0.0.

**Comment by razvanioan** [comment]
If somebody still wants to configure any option using `data` attribute (even for older versions of select2) you can use the following solution:

* configure any custom `data` attribute (but not used by select2 itself) using semicolon separated list of options (key:value), exactly like [UIkit v3](https://github.com/uikit/uikit/tree/develop/src/js) framework does for it's components options, something like:
```html
<select data-options="minimumResultsForSearch:Infinity; param: hehe; float : 45.34">...</select>
```
* parse the `data-options` string and build options object (detecting numbers as well)
```javascript
$("select").each(function (idx, select) {
  var options = $(select).data("options");

  if (options) {
    options = options.split(/\s*;\s*/).reduce(function (a, c) {
      c = c.split(/\s*:\s*/);

      a[c[0]] = isNaN(c[1]) ? c[1] : (parseInt(c[1], 10) == c[1] ? parseInt(c[1], 10) : parseFloat(c[1]));
      
      return a;
    }, {});

    $(select).select2(options);
  } else {
    $(select).select2();
  }
}
```
