### ISSUE TITLE
"require is not defined"

### ISSUE THREAD

**Issue by TekTimmy** [select2/select2#3201]
Hi! First I wanna drop a big THANKS for developing select2 !! I really appreciate it !
I downloaded select2 version 4.0-rc2 and just included the "select2.js" and "select2.css" from the dist subfolders. I get the error message "require is not defined"...

In the announcements you mention the new "AMD-based build system" which might be cool for the people using it but is require.js now a requirement?

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/pull/3192, it's really just a namespacing issue and only affects those using a hidden input.

**Comment by gdolphy** [comment]
I had the same message "require is not defined". Check that you have <select></select> and not <input/>

**Comment by helenburns** [comment]
As of installing today, version 4.0.3 from the CDN and with an absolutely standard combo box and no hidden input I'm getting this exact error and it won't work. What am I doing wrong?
