### ISSUE TITLE
ipad support?

### ISSUE THREAD

**Issue by donthebike** [select2/select2#3204]
Select2 does seem to work on many different devices but not on ipad.
Is it possible to get it working on ipad as well?

**Comment by kevin-brown** [comment]
This is pretty vague, what "doesn't work"?

**Comment by donthebike** [comment]
You are right, that was too vague.
More precisely, scrolling in the Select2 dropdown on Ipad caused some trouble.
At first sight scrolling in the dropdown made the whole page scroll, but after some further testing it seems that one can indeed scroll the dropdown if you do it carefully and at the right position (which would be great if this could be relaxed somehow so that scrolling becomes easier for everyone.
Strictly speaking this is not a bug, more a comment.

**Comment by alexweissman** [comment]
I believe this issue is already discussed in other open issues more thoroughly.
