### ISSUE TITLE
jQuery noConflict compatibility

### ISSUE THREAD

**Issue by patrykkopycinski** [select2/select2#3205]
Hey, 

i just tried to use select 4.0.0-rc2 with wordpress and i got error that cannot read 'fn' property for undefined

$.fn.select2.amd = S2;

Wordpress using noConflict mode of jquery and '$' isn't available, only jQuery. It's possible to make it working with jQuery instead of $?

**Comment by kevin-brown** [comment]
Fixed in https://github.com/select2/select2/commit/1f62eb67e89b5b72e9aa91586c5c22d76ffc7ed9.
