### ISSUE TITLE
Android Chrome issues

### ISSUE THREAD

**Issue by davidrenne** [select2/select2#3208]
Can anyone help me determine how to make my website work on android phone?

http://ec2-54-146-16-163.compute-1.amazonaws.com

I replaced the .min version with .full so you can see all the code.

Basically my implementation used the github search example with some CSS and javascript mods.

I basically have one problem narrowed down to this.resizeSearch().  I noticed that android phone without my 5000px test will turn on and off the keyboard like crazy.  But with the 5000px, the user has more of a chance of clicking inside the textbox.   With the original code the .select2-search__field input box is too small and causes even more toggling on and off of the keyboard.  There was a commit to the old version of select2 made on April 3rd 2014 which tried to fix these kind of keyboard issues.

Usually a double click is best to get the keyboard to stay.  Search for something like "dav" and inspect the returned DJS.  I am calling a redirect function on the entire div row.  But on mobile, it seems like only clicking the small image will redirect like it does on desktop.  I suspect my issue with that is select2 closing before the click registers.

I have been banging my head on a wall with these mobile issues.  Luckily safari on iPhone works fine.  

If anyone can spend some time looking at how I implemented this and what I am doing wrong most of the code is here:

http://ec2-54-146-16-163.compute-1.amazonaws.com/static/djsweb/js/app.js

search_bind_and_resize function.

Thank you (anyone) so much for your time!  Hopefully this example helps find a bug in my code or select2.  It's funny because the keyboard works fine on android galaxy S4 on your examples with the github search.

I hope you like my website, feel free to listen to some tracks for helping me with my code error on android.  Dont use the emulator in chrome debugger, you have to use a real android to see it.  Hopefully I can push to production djs.com if I can get this fixed, otherwise it is going to take me a day or two of work to implement a new search bar with a competing open source library.

**Comment by kevin-brown** [comment]
Might as well note that Select2 appears to be working on the latest Android 5.x as well as the latest 4.x.
