### ISSUE TITLE
Input size with bootstrap

### ISSUE THREAD

**Issue by mazing** [select2/select2#3212]
When I add class `form-control` with bootstrap, select2 resizes the input field's size after the javascript is loaded.

Can I somehow stick to the size given by bootstrap?

**Comment by kevin-brown** [comment]
I'm not sure what you mean, Select2 should try to use the width of the original element, which includes the CSS classes.

In the documentation we use `form-control` there as well, and the width doesn't appear to be changing after Select2 initializes the container.

**Comment by kenny-evitt** [comment]
I'm not sure what the original reporter meant by this but I've noticed that the *height* of my Select2 `select` element is *smaller* than my other Bootstrap form controls. Let me know if you want me to create a new issue.

**Comment by kenny-evitt** [comment]
I'm using Bootstrap 3.0.3. Adding the following to my CSS fixes this:

```
.select2-container .select2-selection--single { height: 34px; }
```

*select2.min.css* seems to be setting `height` to 28 px instead.

**Comment by kevin-brown** [comment]
@kenny-evitt you may be interested in the Bootstrap theme

https://select2.github.io/select2-bootstrap-theme/

As far as the original issue, I'm going to close it off considering there has been no response for almost a year.

**Comment by kenny-evitt** [comment]
@kevin-brown Thanks
