### ISSUE TITLE
Placeholder is selectable in 4.0.0

### ISSUE THREAD

**Issue by versum** [select2/select2#3216]
If you double-click on a placeholder, the text is selected (eg. https://select2.github.io/examples.html, Placeholders).
Tested in Chrome, Safari and Firefox on Mac OS X.

Easiest solution would be to disable selectability in css using `user-select: none` but this would not work in every browser.

**Comment by alexweissman** [comment]
I can no longer reproduce this in the [new docs](https://select2.org/placeholders).
