### ISSUE TITLE
select2 focus not playing nice with animation css in FF

### ISSUE THREAD

**Issue by tlshaheen** [select2/select2#3225]
I'm using `Select2 4.0.0-rc.2`, the full version, with `Bootstrap 3.2.0`, on latest Firefox (36).

After implementing #2873, I finally got select2 to display the dropdown inside of a Bootstrap Modal. However, it seems there is a general [animate.css](http://daneden.me/animate) file that I am loading in that prevents the dropdown from appearing on the first click. If you take a look at my jsfddle, http://jsfiddle.net/uL39ew77/, you'll see you have to click twice inside of the select2 input box before the dropdown appears.

If you remove the animate.css file, like in http://jsfiddle.net/uL39ew77/1/, you can see that the select2 implementation works as expected.

I've narrowed down the issue to the `fadeInUp` class added to the modal parent, `<div class="modal animated fadeInUp" id="optionsbox" tabindex="-1" role="dialog" aria-hidden="true">`. If you remove that class, you can see it functions normally: http://jsfiddle.net/uL39ew77/2/

To get around this issue, I've tried watching for `focus` on the select2 element, but it seems that the `select2:focus` event has gone away in 4.0? 

What with `fadeInUp` is causing a problem with select2? Can it be fixed in a new version select2, or is there a way for me to listen to a focus event that I can manually open the dropdown then, bypassing the issue?

**Comment by kevin-brown** [comment]
I'm going to look into this in a little, but it doesn't appear to be happening in Chrome.

**Comment by tlshaheen** [comment]
@kevin-brown Thanks. I tried Chrome and Safari on OS X, and IE9+ and they all worked as well. Looks like just a Firefox thing, on both OS X and Windows 7.
