### ISSUE TITLE
Select2 4.0.0 spinner icon

### ISSUE THREAD

**Issue by ashipma** [select2/select2#3227]
I am currently using Select2 3.5.2 and have a select element configured using a remote data source. When the user searches, a spinner icon is displayed at the end of the search box.

I just looked at Select2 4.0.0-rc.2 and noticed it does not have that same loading icon. Instead, it adds a new row that says "Searching..." to the top of the search results. This does get the point across that a search is in progress, but it also is somewhat jarring to the user as the search results will be moved down one row while the "Searching..." is displayed and then the search results move back up once the search completes. If the searching is fairly fast, then this row will be added and removed several times causing the search results to move up and down.

So my question is, is there any way to configure the Select2 element to use a spinner icon just like the older version of Select2 did?

Thank you for your help.

**Comment by fk** [comment]
+1

**Comment by nogdacosta** [comment]
+1

**Comment by fk** [comment]
As stated by @kevin-brown in https://github.com/select2/select2/issues/781#issuecomment-123077506, v4 "dropped the old spinner gif while removing external image dependencies from Select2".

Rather unstructured thoughts on the issue raised here:

 * v4 should set a CSS class like `.select2-container--loading` to `.select2-container` (and probably also to the dropdown container/its "Searching …" message/option) to provide a "styling hook" for the loading state of the Select2 widget; this way, users could add their own background image via CSS. As far as I can see it currently does not do this – can you confirm this @kevin-brown?
 * We could of course embed the loading image in the CSS, but this just moves the problem – the GIF – jagged edges/no real transparency and it of course would only work on a certain range of background colors, etc.
 * We want to support IE8, which rules out [SVG](http://codepen.io/aurer/pen/jEGbA) – but maybe we're okay with that … (btw., just stumbled upon this [JSFiddle](http://jsfiddle.net/MadLittleMods/qmdabvn1/) which deals with an IE8 fallback)
 * For projects dealing with IE8, I still frequently use [spin.js](https://fgnass.github.io/spin.js/) – maybe we could offer a sort of integration.

**Comment by ashipma** [comment]
Another thing you could do if you are okay with using CSS3 is to implement the spinner using CSS3 animation. This way there is no image dependency and no need to worry about the background color as it will work fine with any background color. Here is a sample loader class that might look good if you set the color to the correct color.

.select2-loader {
	display: inline-block;
	z-index: 2000;
	width: 14px;
	height: 14px;
	border: solid 2px transparent;
	border-top-color: #29d;
	border-left-color: #29d;
	border-radius: 14px;
	-webkit-animation: pace-spinner 400ms linear infinite;
	-moz-animation: pace-spinner 400ms linear infinite;
	-ms-animation: pace-spinner 400ms linear infinite;
	-o-animation: pace-spinner 400ms linear infinite;
	animation: pace-spinner 400ms linear infinite;
	-webkit-pointer-events: none;
	pointer-events: none;
	-webkit-user-select: none;
	-moz-user-select: none;
	user-select: none;
}

**Comment by rreynier** [comment]
+1 

I really think this should be something we can configure out of the box!  Thanks for all your hard work though, pretty awesome plugin.

**Comment by PowerKiKi** [comment]
As a workaround (or permanent solution), this allow to add a spinner beside the loading texts:

```css

.select2-results__option.loading-results,
.select2-results__option.select2-results__option--load-more {
    background-image: url('/images/loading.gif');
    background-repeat: no-repeat;
    padding-left: 35px;
    background-position: 10px 50%;
}
```

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.

**Comment by osirion** [comment]
No progress on this? From a UX perspective, having a 'Searching...' option that pops up - then 'pops down' (causing a list to shift if its already pre-populated), is really annoying.
 - List has 'A', 'B', 'C' as an option, 
 - User clicks the select2, 
 - List becomes 'Searching...', 'A', 'B', 'C'
 - User tries to click 'B', but as he does, list becomes 'A','B','C' again and he instead clicks 'C'
