### ISSUE TITLE
Responsive dropdown positioned incorrectly after resize

### ISSUE THREAD

**Issue by cyberbit** [select2/select2#3228]
I'm using a responsive Bootstrap layout with several Select2 boxes. I've achieved a fairly good result with a combination of `form-control` and inline styling on the `select` elements. I noticed a problem with the dropdown being positioned incorrectly after a container resize.

Fiddle: http://jsfiddle.net/rdch5pdb/2/

Expected:
![image](https://cloud.githubusercontent.com/assets/7350183/6972562/31ed25ca-d94a-11e4-95cd-b315a8120013.png)
1. Open a dropdown.
2. Close the dropdown.
3. Open another dropdown.
4. Resize.

Bug:
![image](https://cloud.githubusercontent.com/assets/7350183/6972590/6c2e270c-d94a-11e4-9e48-ab68c2588af4.png)
1. Open a dropdown.
2. Open another dropdown. This should cause the first one to close.
3. Resize.

Interestingly, typing in the search field fixes it until you resize again. Navigating using the arrows does not.

I've only tested in Chrome as that's all I have access to at the moment. The fiddle is using jQuery 1.10.1, Select2 4.0.0-rc.2, and Bootstrap 3.3.4.

**Comment by kevin-brown** [comment]
I can't get this to happen consistently, but I have seen it happen.

**Comment by telvin** [comment]
It happens when the content gets bigger and the vertical scroll appears, it will produce this layout issue.
