### ISSUE TITLE
Bad performance when using data array

### ISSUE THREAD

**Issue by megahallon** [select2/select2#3230]
Recent changes made using data array very slow. As mentioned in the comment on commit b9b55ce the change from push to add on jquery arrays is the reason for the performance drop. When using push I can easily use an array of 5000 elements, with add it takes so long time I can't even be bothered to wait for it. I am using the jQuery included in the select2 archive (2.1.0).

**Comment by kevin-brown** [comment]
We may want to do some version detecting to handle 1.7 differently than everything else, as that is the only supported version of jQuery that we support which doesn't support passing an array to `.append`.
