### ISSUE TITLE
Having this issue Select2 v4 and Bootstrap 3.3.4

### ISSUE THREAD

**Issue by Doopin** [select2/select2#3232]
This is the code here
https://gist.github.com/Doopin/d639d045f6985b671f05

![capture33](https://cloud.githubusercontent.com/assets/10206793/6992908/2e0821c6-dada-11e4-97e1-dee6c40f15c6.PNG)

CSS heigth does not work here

**Comment by kevin-brown** [comment]
Select2 4.0.0 does not currently provide a Bootstrap theme, but we are looking for someone who is interested in supporting a theme that would be bundled in the core builds for Select2.

**Comment by Doopin** [comment]
Ok...
Anyway I found a way. Overwrite some CSS classes and it is solved.
For those who may have the same problem there, look here. https://gist.github.com/Doopin/74817920a3847c198332
But it is better to put that CSS declaration in another file loaded after Select2 css file. It will just overide those delaration so you can keep update your plugin without having a problem

Better to put that in

**Comment by alfredobarron** [comment]
Update it works best
https://gist.github.com/alfredobarron/24570de1cd123c7e518c

**Comment by Doopin** [comment]
Great!
Thanks
