### ISSUE TITLE
may be select2 value problem ? Could you help me?

### ISSUE THREAD

**Issue by kabirpust** [select2/select2#3233]
After selecting type and garage, When the user will click on stock field, ther previously selected value will be put on the clicked stock, But my code gives me the same as first and second times
Please check my fiddle where is my mistake, First one is ok, But when I select the second one, it gives me the first data as output, but why ?

Demo http://jsfiddle.net/kabircse/kzgvcsyk/

**Comment by kevin-brown** [comment]
You are using Select2 3.2. If you want an idea of how old it is, and why I'm not even going to burn some time supporting it, here is the time stamp at the top of the JS file.

```
Version: 3.2 Timestamp: Mon Sep 10 10:38:04 PDT 2012
```

That's right, 2.5 years ago.

----

You are going to need to reduce your test case down to the simplest failing case, and please stop hijacking other tickets on here to get help. Let's stick to the original one that you created.

https://github.com/select2/select2/issues/3231#issuecomment-89593398
