### ISSUE TITLE
No support for jQuery.noConflict

### ISSUE THREAD

**Issue by DeniR** [select2/select2#3234]
Error in code `return $.fn.select2.amd=`
There must be jQuery instread of $, because jQuery can have another variable name after noConflict, like `var $j = jQuery.noConflict(); `

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/pull/3192, fixed in https://github.com/select2/select2/commit/da1ec4e02865f3b23d7634eba509e3438d4ab874.
