### ISSUE TITLE
Dropdown

### ISSUE THREAD

**Issue by kirankumar8500** [select2/select2#3235]
in drop down selection if i select one option and assign.that option is  not visible to next time selection
in the drop down selection

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

**Comment by kirankumar8500** [comment]
in drop down selection employees names same(ex:jerry,jerry). first time i select jerry assigned some work to him then after next time work assign i required to hide drop down already work assigned person
