### ISSUE TITLE
Add class to displayMessage (4.0)

### ISSUE THREAD

**Issue by snarkq** [select2/select2#3237]
I would like to style the message displayed, ex: Please enter 1 or more characters, separately from the rest of the results

https://github.com/select2/select2/blob/master/dist/js/select2.js#L776

from

```
var $message = $(
  '<li role="treeitem" class="select2-results__option"></li>'
);
```

to

```
var $message = $(
  '<li role="treeitem" class="select2-results__option select2-results__message"></li>'
);
```

Thanks!

**Comment by alexweissman** [comment]
I believe this all should be handled in `templateResult`.  See https://select2.org/dropdown#built-in-escaping:

> Anything rendered in the results is templated. This includes results such as the "Searching..." and "Loading more..." text which will periodically be displayed, which allows you to add more advanced formatting to these automatically generated options. You must ensure that your templating functions can support them.

Would be good if we had some more specific documentation for this, though.
