### ISSUE TITLE
templateResult does not create needed [aria-selected] attributes (4.0)

### ISSUE THREAD

**Issue by snarkq** [select2/select2#3238]
When I use a custom templateResult function I get lists containing elements like:

 `<li class="select2-results__option" role="treeitem">`

Without the custom templateResult function I get lists like this:

` <li class="select2-results__option" role="treeitem" aria-selected="false">`

Much of the actual functionality seems to require a selection of [aria-selected] to differentiate between the options and other placeholder <li> elements, so unfortunately the custom formatter does not seem to work. 

Any suggestions on workarounds?

**Comment by kevin-brown** [comment]
I can't reproduce this, we're going to need a jsbin/jsfiddle that reproduces the issue.

The templating example (along with the AJAX one) doesn't have this issue: https://select2.github.io/examples.html#templating

It also doesn't make sense considering the `aria-selected` attributes are [applied at a different time](https://github.com/select2/select2/blob/f3f1b31958fa585fadfe2eada3449826ce48224e/src/js/select2/results.js#L112-L117) than the templating methods.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/ivaynberg/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by snarkq** [comment]
Hi Kevin, thanks for getting back so soon. I'll work on a JSFiddle. I was able to get around the issue by moving back to the 'id' and 'text' attributes as opposed to trying to roll with something else, I assume this is somehow involved.

**Comment by kevin-brown** [comment]
Not using the `id` attribute would cause the `aria-selected` attribute to not be set.

https://select2.github.io/announcements-4.0.html#changed-id

**Comment by snarkq** [comment]
Makes sense. Exactly what I ended up doing. Thanks for following up

- Patrick
