### ISSUE TITLE
Difference in [tab] keydown behaviour between 3.5.2 and 4.0.0.rc-2 on tagging support

### ISSUE THREAD

**Issue by danielhall** [select2/select2#3241]
We're trying to implement version 4 of select2 in our site and we've been having problems with the way the control handles the keydown event of the tab key.

Looking at the "Tagging Support" section of the version 3.5.2 docs (http://select2.github.io/select2/), if you enter a random word into the field such as 'test123' and press tab, the word will be tagged, and focus will me moved to the next element in the DOM. This is the behaviour I am trying to reproduce in version 4.

If you however take a look at the same section in the version 4 docs (https://select2.github.io/examples.html), enter the same 'test123' and press tab, the 'test123' gets deleted and the focus remains on the same element. 

Would you consider this a bug or is this behaviour intended? I have reproduced this in Internet Explorer 11 and Chrome.

Thanks

**Comment by kevin-brown** [comment]
If you use `tags: true` in combination with `selectOnClose: true`, it should behave how you are expecting.

**Comment by danielhall** [comment]
Hi Kevin

Thanks for the tip.

Do you have any examples of the usage of `selectOnClose` in JSFiddle or similar?
I'm getting the following error in Chrome and Firefox when I tab out of the field. Obviously as this is a release candidate, I wanted to make sure it was my code causing the issue and not yours.

```
too much recursion
push.apply(results, slice.call(context.getElementsByClassName(m), 0));
http://localhost:9999/Scripts/Library/jquery-1.9.1.js
Line 3948
```
