### ISSUE TITLE
Select2 version 4 with only one dynamic option not selectable

### ISSUE THREAD

**Issue by afattahi54** [select2/select2#3242]
Consider a select box which is empty at first time.
After an event ONE option will be added to it. 
The problem is that the select 2 shows the option but does not allow user to select it.
( I could not find select 2 CDN so I can put jsfiddel here.

```javascript
<select id="sample">
</select>
<button id="clickeMe">click me</button>
```

```javascript
<script type="text/javascript">
$("#clickeMe").click(function (){
    $("#sample").html("<option value=1>sample option</option>");
})
</script>
```

If I add two options 
```javascript
    $("#sample").html("<option value=1>sample option</option>  <option value=2>sample option 2</option>");

```
Then 
1- First option is not selectable
2- I can select second option
3- After selecting second option I will be able to select first option

I find that the generated select 2 has the aria-selected="true" option set. This cause the select 2  not allowing user to select option

**Comment by nickfaughey** [comment]
After appending 1 or more `<option>` elements to the `<select>`, you need to trigger the `change` event to let everything (including Select2) know that the DOM has been updated:

    $("#sample").trigger("change");

**Comment by kevin-brown** [comment]
Closing this off because it sounds like you weren't triggering `change` (somehow missed this earlier).

Select2 has the `selected` property set because the browser will select the first `<option>` by default.
