### ISSUE TITLE
"Loading remote data" demo hits Github API limits after a few seconds of testing

### ISSUE THREAD

**Issue by WoLpH** [select2/select2#3244]
Not sure how many requests the library sends or how low the Github limits are, but within a few seconds the demo stops working for me. Perhaps it should use more agressive rate limiting or an API which has a higher limit.

Link: https://select2.github.io/examples.html

**Comment by kevin-brown** [comment]
Looks like we might want to migrate the old notice over from the 3.5.2 docs: https://select2.github.io/select2/#ajax

> If this example stops working, you have most likely reached the usage limit for the GitHub Search API of 5 requests per minute. Please wait a few minutes and try again.

It's a rolling throttle of around 10 requests. It's low, but it beats the 10k per day per token that we used to hit in a few hours when using the Rotten Tomatoes API.
