### ISSUE TITLE
How to show confirm box before removing tag from select2?

### ISSUE THREAD

**Issue by kesavankrishnan** [select2/select2#3245]
How to show confirm box before removing tag from select2?
![selection_197](https://cloud.githubusercontent.com/assets/8515018/7039984/7374163e-dde6-11e4-9095-e1dadfb377c6.png)
am using "select2-removing" its show confirm box but tags removed

**Comment by alexweissman** [comment]
I believe this will be possible in 4.0.6, with the new `clear` event introduced in #5058:

> When user clears the select, value is now cleared before `unselect` event is emitted (fixes #5049). If the event is cancelled, the original value will be restored.
