### ISSUE TITLE
Enable/Disable does not work in IE8/9/10

### ISSUE THREAD

**Issue by ruiwei** [select2/select2#3246]
On Example (https://select2.github.io/examples.html) > Disabled mode

Click on button "Enable" works.
Click on button "Disable", it does not work.

**Comment by axar** [comment]
doesn't work on ie10 also.

**Comment by kevin-brown** [comment]
I can't reproduce this in IE 11 or Edge, but I think I was able to reproduce it at the time using IE 9.

**Comment by holmes2136** [comment]
doesn't work on ie9 , too .

**Comment by ilkeryilmaz** [comment]
```javascript 
// change action disable
$('.custom-select').select2()
.on("change", function(e) {
       $('.custom-select').prop("disabled", true).select2(); //call select2
})

// disable alternative
$('.custom-select').prop("disabled", true).select2(); //call select2

**Comment by evil-shrike** [comment]
Is there any news on this? 
Disabling isn't working in IE8/IE9/IE10.

**Comment by evil-shrike** [comment]
In IE9/IE10 there are no Mutation Observers support. So mutation events are being used. Especially `DOMAttrModified`. But adding property `disabled` for a HTMLElement doesn't fire any mutation event in IE :(
Here's a test case:
```
<script>
    require(['jquery'], function($) {
    	var $el = $("#cbDisabled");
    	$el.on("DOMAttrModified DOMAttributeNameChanged DOMCharacterDataModified DOMElementNameChanged DOMNodeInserted DOMNodeInsertedIntoDocument DOMNodeRemoved DOMNodeRemovedFromDocument DOMSubtreeModified",
    		function (ev) {
    			alert(ev.type);
    		});
		var disabled = false;
    	$("#btnAdd").on("click", function () {
    		disabled = !disabled;
    		$el.prop("disabled", disabled);
    	});
    });
</script>
</head>
<body>
	<p><input type="checkbox" id="cbDisabled"><label for="cbDisabled">Disabled</label></p>
	<button id="btnAdd">Toggle disabled</button>
</body>
```
When we click for the first time the checkbox will be disabled and no event happens. Next click removes `disabled` attribute and we'll see two events (DOMAttrModified, DOMSubtreeModified).


BTW:
In browser with no Mutation Observers support the method `_syncAttributes` is subscribed on `DOMAttrModified` Mutation event. The method logic handle changing "disabled" attribute but there're no checks for attribute name so it executes on every change of all attributes. 

```
  Select2.prototype._syncAttributes = function () {
    this.options.set('disabled', this.$element.prop('disabled'));

    if (this.options.get('disabled')) {
      if (this.isOpen()) {
        this.close();
      }

      this.trigger('disable', {});
    } else {
      this.trigger('enable', {});
    }
  };
```

**Comment by evil-shrike** [comment]
@kevin-brown 
>I can't reproduce this in IE 11 or Edge, but I think I was able to reproduce it at the time using IE 9.
You can easily reproduce the bug in IE11 by enabling emulation of IE10 in devtools.

If you're not going to fix select2 behavior in <IE11 then please update compatibility info in README. Currently it's misleading as it states >=IE8 support. Actually select2 works correctly only in IE11.

I can't see any way how it can be fixed in IE with continue using of mutation events. They simply ignored for disabled elements.  Only only setting disable attr/prop is ignored but event any other attr/prop is ignored for disabled elements. 
So the only way I see is to allow user code to set disabled property explicitly (as it was in 3.x):
`select2.disabled(true)`

**Comment by evil-shrike** [comment]
Also it makes no sense in `Select2._registerDomEvents` to use 
`attachEvent` and `DOMAttrModified` event at all. As they are only being used for tracking disabled attribute in IE8/IE9-IE10. In IE11 we have MutationObserver.
