### ISSUE TITLE
custom dataAdapter with minimuminputlength

### ISSUE THREAD

**Issue by Yoshuag11** [select2/select2#3249]
Hi guys! could some one help me with an example of how implement this?

When I add the key "minimuminputlength" after implement a custom dataAdapter it doesn't work. So far I know that it is caused because one has to manually implement decorators every time you use a custom dataAdapter.
A snippet of my code:
    $("#select").select2({
        dataAdapter: CustomData, // the following code is never triggered
        placeholder: 'Input name...',
        minimumInputLength: 3,
        tags: tags,
        tokenSeparators: [",", " "]
    });
Thanks in advance.

**Comment by wbercx** [comment]
Don't know if you still need this, but have a look at: http://stackoverflow.com/questions/30631024/add-decorator-to-data-adapter-in-select2-version-4-x
