### ISSUE TITLE
Open on mouseover / hover

### ISSUE THREAD

**Issue by shaunmorrison** [select2/select2#3250]
Hi

Just wondering if there is a way to open the select item when hovering instead of clicking? I can't attach a standard hover and then fire the open event as the select and the dropdown don't have a shared parent container element (meaning I'd mouseout when trying to select an item from the dropdown). 

Many thanks, 
Shaun

**Comment by SergioGregorutti** [comment]
Someone know how to do this?

**Comment by alexweissman** [comment]
This appears to be a usage question, rather than a bug report or feature request.  Please see our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Usage questions should be discussed on the [forums](https://forums.select2.org) instead.
