### ISSUE TITLE
How to stop typing when maximumSelectionLength is reached?

### ISSUE THREAD

**Issue by boubou1030** [select2/select2#3254]
I'm using select2 4.0. Can we set the constraint that users can not type in any character when the maximumSelectionLength is reached? Thanks.

**Comment by kevin-brown** [comment]
I think we previously set a `maxlength` attribute on the search box which would accomplish what you are looking for.

Though it doesn't trigger the message below if it's used, which is something we never really figured out how to work around.

**Comment by ttucker** [comment]
I'd really like to see maxlength implemented! I assumed (fail) upon reading the docs, that the standard  way of limiting input lengths would be enforced.

@kevin-brown is there any way to not show the message and get that maxlength attribute added by using a custom adapter with select2 4.0? I'm really not sure how I would go about this but need that behavior! Any help you could provide would be appreciated.
