### ISSUE TITLE
Avoid being selected again while the selected value number is typed in 

### ISSUE THREAD

**Issue by boubou1030** [select2/select2#3255]
I'm using select2 4.0. The page will read pre-selected item from server and appear in , <option value="1" selected="selected">Select2</option>. But when I want to tag something new, if I type in "1"  (the number corresponds to the item value in select option), this item would be selected again (and be canceled), but somehow I want to tag this number "1" instead of this item. I'm wondering how to avoid it? Or which is caused by my bug? Thanks.

**Comment by alexweissman** [comment]
This seems to be the same bug covered by #3681.
