### ISSUE TITLE
select2 option to not include search string in results

### ISSUE THREAD

**Issue by borovez** [select2/select2#3259]
I would like to remove the search 'term' from appearing in the search result list.

![d24fdd312720e8a3d3c74fbbde6819fe](https://cloud.githubusercontent.com/assets/1531030/7128878/92d0f5a8-e226-11e4-99f3-81841384d315.png)

How can I do this? Is there an option for this built in?

**Comment by kevin-brown** [comment]
Do you mean removing the first term (the exact match)? You can control how search results are matched using the `matcher` option.

Or removing it from every result (so it only displays the suffix)? That'd require some magic in the results adapter, but could probably be hacked with a custom `sorter` being passed in.

**Comment by borovez** [comment]
No, I just simply dont want to include the search string in the results from ajax. That list of results is populated by ajax. When I typed "tes" in the search, it appends "tes" as the first result, I do not want it to do this.

Here is the code for the select2:

```
    select.select2({
      minimumInputLength: 2,
      tags: [],
      placeholder: "Search for a member",
      ajax: {
          url: "./php/testing/module/contact-drop-module/php/user-name-search.php",
          dataType: 'json',
          type: "POST",
          async: false,
          quietMillis: 50,
          data: function (term) {
              return {
                  'term': term.term //search term
              };
          },
          error: function(data){
            alert("ERROR");
          },
          processResults: function (data) {
              return {
                  results: $.map(data.users, function(index, val) {
                      return {
                          id: index,
                          text: index,
                          name: index,
                          slug: index
                      }
                  })
              };
          }
      }
    });

    $(".search-contact").select2("val", "");
```

**Comment by kevin-brown** [comment]
> When I typed "tes" in the search, it appends "tes" as the first result

This is because you are using the `tags` option. It doesn't sound like you actually need it.

**Comment by borovez** [comment]
Nope that is not the problem... I set tags:"false" and it is still appending the search string to the search results. Do you understand what I am asking?

As I type "tes" (search string), it gets appended to the list as "tes", I do not want it to append the search string, I only want it to display the actual results from ajax....

**Comment by kevin-brown** [comment]
`tags:"false"` doesn't actually disable tags, as `"false"` is [truthy](http://www.sitepoint.com/javascript-truthy-falsy/) in JavaScript.

```js
> var x = "false";
> !x
< false
> !!x
< true
```

Try setting `tags: false` (note the missing quotes) or just don't include it in your options. The `tags` option will, by default, put the string entered as a search term into the results in the first position. If you do not want this, don't use `tags`.

**Comment by borovez** [comment]
I just tried this suggestion but it didnt change anything. tags: false,
On Apr 14, 2015 7:08 PM, Kevin Brown <notifications@github.com> wrote:tags:"false" doesn't actually disable tags, as "false" is truthy in JavaScript.

> var x = "false";
> !x
< false
> !!x
< true

Try setting tags: false (note the missing quotes) or just don't include it in your options. The tags option will, by default, put the string entered as a search term into the results in the first position. If you do not want this, don't use tags.

**Comment by abo-elleef** [comment]
you should remove the tags as option when calling selec2
check the docs 
https://select2.github.io/options.html#tags
