### ISSUE TITLE
Multiple SELECT with remote URL resets existing tags

### ISSUE THREAD

**Issue by lubosdz** [select2/select2#3261]
When loading tags via remote URL in dropdown with multiple items, it:

* initializes correctly previously entered tags
* but it resets all tags when I try to add new tag. For example there were already 2 tags, maximumSlectionLength = 4, so entering 3rd tag will reset tags 1 and 2. Then I must enter again 1 and 2 tag and add 3rd + 4th. 

Since we use custom initialization, I am not sure whether the script has something wrong. Here is our code:

PHP part - just convert list of interest IDs into JSON:
~~~
// e.g. model->interests = [6003324056771, 6003257632086];
$batch = [];
foreach($model->interests as $interestId){
	$batch[] = [
		'relative_url' => 'v2.3/'.$interestId,
		'method' => 'GET',
	];
}
$batch = json_encode($batch);
~~~

And javascript part with SELECT2:
~~~
// we are loading multiple tagged facebook interests via ajax remote URL
$("#interests").select2({
	multiple: true,
	minimumInputLength: 2,
	maximumSelectionLength : 4,
	placeholder : 'Type first characters, e.g. music',
	ajax: {
	  url: "https://graph.facebook.com/v2.3/search",
	  dataType: "json",
	  delay: 500,
	  data: function (params) {
			return {
				q: params.term, // search term
				type : "adinterest",
				access_token : "__________"
			};
	  },
	  processResults: function (response, params) {
		return {
			results: $.map(response.data, function (item) {
				return {
					id: item.id,
					text: item.name
				}
			})
		}
	 },
	  cache: true
	},
	initSelection : function(element, callback){
		// parse multiple options
		var ids = params = [], id;
		$(element).find('option').each(function(){
			id = $(this).text();
			if(/^\\d+$/.test(id)){
				ids.push(id);
			}
		});
		if (ids.length > 0) {
			// load all IDs in a single batch request
			params = {
				access_token : '_______',
				batch : '{$batch}'
			};
			return $.ajax({
				url: "https://graph.facebook.com/",
				dataType: "json",
				method: "POST",
				data: params
			}).done(function(response){
				if(response!==undefined && response.length){
					var items = [], item = {};
					for(var i in response){
						item = $.parseJSON(response[i]['body']);
						if(item && item.id!==undefined){
                                                        // OK, set loaded interest title
							items.push({
								id: item.id,
								text: item.name
							});
						}
					}
					callback(items);
				}
			});
		}else{
			// we must set empty array to allow inserting characters
			callback([]);
		}
	}
})
~~~

* Is there any error in the code please? If not, I assume there is a bug because resetting previous tags should not happen.
* also after inicialization of previous tags, when I try to remove any single tag, it removes all tags.
* and last issue I noticed - if no results are returned from remote URL and therefore no listing is shown, pressing key UP throws JS error "f.offset(...) is undefined" in `...seenter");var g=c.$results.offset().top,h=f.offset().top,i=c.$results.scrollTop(....`.

Used lib version was 4 RC2.

**Comment by schakko** [comment]
I assume I stumbled upon the sample problem. I was able to workaround this behavior by calling .select2() two times. The order is important:

            var data = [ id: 1, text: "Text" ];
            var baseUrl = "/api/search";

            // see https://github.com/select2/select2/issues/3261
            // the initial data must be assigned at initialization
            $(".src-skills").select2({
                data: data ? data : [],
            });

            // by calling select2 a second time, the AJAX backend is initialized and the initial data is kept.
            // changing the order of both .select2 calls or merging them in one statement results breaks the whole thing:
            // either the select box is not initialized with the data (initSelection does although not work) or all initial
            // tags will be removed when a new tag is selected from the AJAX response
            $(".src-skills").select2({
                // enable tag support
                tags: true,
                // define AJAX
                ajax: {
                    url: function () {
                        // dynamically build endpoint URL
                        var r = baseUrl + "?scope=type";

                        if ($(".src-type").val() == 'graduation') {
                            r += "&type=graduation";
                        } else {
                            r += "&type=skill";
                        }

                        return r;
                    },
                    data: function (params) {
                        return {
                            q: params.term
                        }
                    },
                    processResults: function (data) {
                        var polishedData = $.map(data, function (qualification, idx) {
                            return {id: qualification.id, text: qualification.name};
                        });

                        return {
                            results: polishedData
                        };
                    }
                },
            });

**Comment by kevin-brown** [comment]
The original reported issue was using `initSelection`, which has a bug right now when the selections are changed and the initial data didn't originally line up (search for the ticket). The second comment was a separate issue, completely unrelated, where the data wasn't being initialized at all.

**Comment by SensitiveLab** [comment]
And so...
I has same behavior when using array initialisation with initSelection.
Is there a workaround ? or I miss something ?

Thx
