### ISSUE TITLE
Redraw the dropdown menu before displaying on open

### ISSUE THREAD

**Issue by foxontherock** [select2/select2#3262]
When using ajax, it seems that select2 4.0 RC2 is not removing data already selected automatically.

So, we did it in the processResult event, we do not return already selected data in the results array.

But, the "ul-li" is displayed with the last resultset (with the old selected item), then a few milliseconds later, it is "refreshed" with new data.  So, our selected item is not in the list, but we see it a little bit.

We "fixed" it by adding this, in the "data" ajax event:
$('ul.select2-results__options li').remove(); 

So, we do not see the "old" li before they are refreshed.
I think that you should redraw the ul-li before showing it.
Thank you

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
