### ISSUE TITLE
select the highlighted option on close

### ISSUE THREAD

**Issue by roopunk** [select2/select2#3265]
So my requirement is that when a user presses tab, whatever option was highlighted in the dropdown should get selected. Basically tab should work the same as enter. 
From the documentation, I figured I needed to use Adapter ResultsAdapter with decorator : SelectOnClose. I know what decorators are, but I don't know how to use decorators in this select2.

**Comment by kevin-brown** [comment]
`selectOnClose: true` should work by default, without any special adapters.

**Comment by jonahgreenthal** [comment]
Is it correct that this is not expected to work in 4.0 RC2 because of #3169?

**Comment by roopunk** [comment]
Yeah its not working by just adding selectOnClose : true option in the 4.0.0-rc.2 release which I am using.
Because of delivery deadlines in my project, I had to go into the unminified source code and add KEY.TAB to the keyboard events which select an option. But this was for my special requirement. 
So yeah, the selectOnClose option needs to be looked into I guess.

**Comment by meechanism** [comment]
For what it's worth, `selectOnClose` will select an option on any type of close, including escaping and clicking out. It might not be the behavior you desire regardless.
