### ISSUE TITLE
Extend Select2 drop down with a tree view

### ISSUE THREAD

**Issue by ghost** [select2/select2#3269]
Allowing for a tree structure with multi-select would be tremendously valuable for many use cases. Numerous Select2 users would be grateful as evident in the [Google Group](https://groups.google.com/d/msg/select2/S0b-JJJIFYY/Sh4PTwmx4zgJ).

In many usage scenario's Select2's reliance on search for larger sets of values does not cut it. For one the term to search for might be unclear to the user or worse exist multiple times under different parent items, furthermore it does not work in multi-select scenarios for structured data, i.e., user wants to filter a product list by product (sub)categories.

**Comment by dbldots** [comment]
+1

**Comment by rms230** [comment]
+!

**Comment by SkylerBloodAT** [comment]
+1

**Comment by mr-dxdy** [comment]
+1

**Comment by mnabialek** [comment]
+1

**Comment by cxxyjsj** [comment]
+1

**Comment by nikos90** [comment]
+1

**Comment by ilizunov** [comment]
+1

**Comment by mestaritonttu** [comment]
Anyone wanting this **right now** might look into using this: https://github.com/SE7ENSKY/jquery-select7

**Comment by jerefrer** [comment]
+1

**Comment by seamusic** [comment]
+1

**Comment by wanglian** [comment]
+1

**Comment by bvizureanu** [comment]
+1

**Comment by nickpierpoint** [comment]
+1

**Comment by spencerflagg** [comment]
+1

**Comment by IncM** [comment]
+1

**Comment by bmrpatel** [comment]
+1

**Comment by konstantin-web-premium** [comment]
+1

**Comment by warmhug** [comment]
+1

**Comment by Sufir** [comment]
+1

**Comment by dgambin** [comment]
+1

**Comment by fabiomaggio** [comment]
+1

**Comment by fabiomaggio** [comment]
+1

**Comment by cyberbobjr** [comment]
+1

**Comment by wolfheart** [comment]
+1

**Comment by warmhug** [comment]
try react version TreeSelect. https://github.com/react-component/tree-select

**Comment by deancsmith** [comment]
+1

**Comment by bamburillo** [comment]
+1

**Comment by newerton** [comment]
:+1:

**Comment by jpastel** [comment]
+1

**Comment by th0r** [comment]
Guys, do you plan to implement this?
@kevin-brown

**Comment by littlemju** [comment]
+1

**Comment by kevin-brown** [comment]
> Guys, do you plan to implement this?

Eventually? Yes. It would be as a separate results adapter and definitely wouldn't be in the light build of Select2.

It's not on the roadmap though, but if anyone is interested in creating the adapter we will gladly link to it from the documentation.

**Comment by uiliw** [comment]
+1

**Comment by uiliw** [comment]
Best example to follow is this one made with angularjs, http://codepen.io/chrishanson/pen/nqcGA

**Comment by ilakkuvan** [comment]
+1

**Comment by cornernote** [comment]
+1

**Comment by metel68** [comment]
+1

**Comment by xujingbao** [comment]
+1 👀

**Comment by benedikt-voigt** [comment]
+1

**Comment by abaranzano** [comment]
+1

**Comment by Jokeby** [comment]
+1

**Comment by mestaritonttu** [comment]
Guys, Santa just brought us a little something: https://github.com/maliming/select2-treeview

**Comment by lonlie** [comment]
Hi guys, This is my solution, Hope it's useful.
[https://github.com/lonlie/select2tree](https://github.com/lonlie/select2tree)

**Comment by dustapplications** [comment]
@lonlie Your plugin looks promising. Kindly improve documentation and translate it in English please so everyone can enjoy it. Thanks

**Comment by lonlie** [comment]
@dustapplications 

> DariaPlotnikova help me do that. She added instructions in English and Russian for select2tree.

**Comment by fryg123** [comment]
+1

**Comment by hiryu85** [comment]
+1

**Comment by fasatron** [comment]
+1

**Comment by jilpi** [comment]
+1

**Comment by Enapiuz** [comment]
+1

**Comment by marcelogarbin** [comment]
+1

**Comment by dairton** [comment]
+1

**Comment by rajitha-bandara** [comment]
+1

**Comment by alexweissman** [comment]
Please refrain from submitting "+1" comments, everyone.  To show your interest, simply click the 👍 button on the top-level comment.

**Comment by clivezhg** [comment]
I also faced this issue in my projects.
And I implemented one, your can check if it's suitable for you.
It's here: [https://github.com/clivezhg/select2-to-tree](url)

**Comment by clivezhg** [comment]
I also faced this issue in my projects.
And I implemented an extension, your can check if my approach is suitable for you.
It's here: https://github.com/clivezhg/select2-to-tree

**Comment by clivezhg** [comment]
I also faced this issue in my projects.
And I implemented an extension, you can check if my approach is suitable for you.
It's here: https://github.com/clivezhg/select2-to-tree

**Comment by charlmert** [comment]
I created a tree view based on google drives tree navigation, when you move a document into a folder. Hope it can be of use to someone else;
http://charl.faceclues.co.za/select2gtree/

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:

**Comment by wmkDev** [comment]
I was in need of this feature and made my custom implementation of @lonlie version, maybe its useful for someone:

https://jsfiddle.net/kikoDev/6vmzqbn9/

**Comment by mariela21180** [comment]
> I also faced this issue in my projects.
> And I implemented an extension, you can check if my approach is suitable for you.
> It's here: https://github.com/clivezhg/select2-to-tree

@clivezhg this is a great solution! thanks!

The only thing that I couldn't sove with your extension is that the parent items remains visible when using the multiple+search options. Image example using your documentation array demo: 
![image](https://user-images.githubusercontent.com/3533830/102910609-99ea9d80-4459-11eb-9845-25453498c72a.png)

Could you please tell me if it's possible to force that?
