### ISSUE TITLE
IE8 not firing disabled property event

### ISSUE THREAD

**Issue by norabor** [select2/select2#3271]
I found no way to disable a select2 (4 rc2) via javascript.
prop("disabled", true)
doesn't work (it also doesn't work on the standard examples page).

It seems I'm even incapable of manually triggering that "onpropertychange" event handler.

**Comment by bezdna** [comment]
and safary(5.1.7) for windows to
doesn't work (it also doesn't work on the standard examples page).

**Comment by kjprice** [comment]
I am not sure how we are triggering the "disable" event for select2 but using [jQuery.propHooks](https://github.com/jquery/jquery/blob/c752a5030bc00eb5b45dea9c28963f824a5c4f44/src/attributes/prop.js#L42) seems like the way to go.

Adding this anywhere `select2` is used seems to clear up the IE issue:

```
jQuery.propHooks.disabled = {
  set: function (el, value) {
    var instance = jQuery(el).data('select2');
    if (!instance) {
      return;
    }
    if (value === true) {
      instance.trigger('disable');
    }
    else {
      instance.trigger('enable');
    }
  }
};
```

Unfortunately I am getting a PhantomJS library error when trying to run QUnit tests and so will be unable to create a PR, but hopefully this can help get us in the right direction. Let me know how else I can help here. Thanks @kevin-brown!

**Comment by evil-shrike** [comment]
See #3246

**Comment by alexweissman** [comment]
Please continue discussion of this issue in #3246.
