### ISSUE TITLE
4.0 Theme Documentation Does Not Exist

### ISSUE THREAD

**Issue by jjanusch** [select2/select2#3272]
On the Examples page of the 4.0 Documentation, there is a section for [Themes](http://select2.github.io/examples.html#themes) that links to the [Options](http://select2.github.io/options.html#theme) page, presumably to describe that functionality in greater detail. However, there is no Themes section on the Options page, the link takes you to a non-existent anchor, and there is only a single mention of themes at all (in passing about setting default options).

**Comment by nazrhyn** [comment]
:+1:

**Comment by clemorphy** [comment]
I would really appreciate some documentation for the `theme` option too

**Comment by alexweissman** [comment]
There is documentation for basic usage [here](https://select2.org/appearance#themes), but a theme authoring guide would be helpful - if someone wants to contribute to that.

**Comment by jjanusch** [comment]
The documentation was completely redone a while ago and is much, much improved now. This is definitely able to be closed now

**Comment by Pezhvak** [comment]
5 years is passed and yet there is nothing on documentation specifying how to create a new theme:
https://select2.org/appearance
