### ISSUE TITLE
Format an entry by modifying the node itself

### ISSUE THREAD

**Issue by serggusak** [select2/select2#3274]
If 'node.append(label)' was outside of the if, it would allow formatting the node itself in the formatResult callback as an alternative to returning an html string.

formatted=opts.formatResult(result, label, query, self.opts.escapeMarkup);
if (formatted!==undefined) {
      label.html(formatted);
- ```
  node.append(label);
  ```
  
  }
-    node.append(label);

**Comment by alexweissman** [comment]
New features will not be added to 3.5.x.
