### ISSUE TITLE
Add option to set dropdown width

### ISSUE THREAD

**Issue by am0d** [select2/select2#328]
I'd love to have an option to set the width of the dropdown to a different width than the input element.

I have some selects where the container can only be so wide, but there is much more room for the dropdown, and so I'd love to have the dropdown expand to show longer text better.

Another option for this would be to have the dropdown resize itself as wide as necessary rather than squashing the text into multiple lines.

**Comment by maheshKDS** [comment]
Use this style you can adjust width and height

.SumoSelect > .CaptionCont {
            position: relative;
            min-height: 32px;
            min-width: 242px;
            background-color: #fff;
            border-radius: 2px;
            margin: 0;
            border: 1px solid #e5e5e5;
        }
