### ISSUE TITLE
ajax choice selection issue/bug (3.5.2)

### ISSUE THREAD

**Issue by franckl** [select2/select2#3284]
My select2 component is used to edit an antennID and I have the following code to get a list of existing unique antenna IDs. The user can create a new choice if it passes a regex in createSearchChoice or he can reselect his current antenna ID (but not the other existing IDs that are disabled in the ajax return function).

This is what happens when I have too many IDs:
![image](http://fat.gfycat.com/BleakSpicyFrenchbulldog.gif) http://www.gfycat.com/BleakSpicyFrenchbulldog#
As you can see I cannot re-select the current ID if I have to scroll. I have no idea how to debug this...
 
        $('#antID').select2({
            placeholder: 'Unique antenna ID',
            allowClear: true,
            multiple: false,
            quietMillis: 100, //play with this value to improve performances
            createSearchChoice: function (term, data) {
                if (checkForAlphaNumericDashUnderscore.test(term) === true) {
                    if ($(data).filter(function () {
                            return this.text.localeCompare(term) === 0;
                        }).length === 0) {
                        return {id: term, text: term};
                    }
                }
            },
            formatNoMatches: 'Alphanumeric and "-" only',
            maximumInputLength: 18,
            ajax: {
                url: '/antennaID',
                dataType: 'json',
                data: function (term, page) {
                    return {
                        search: term
                    };
                },
                results: function (data, page) {
                    for (var i = 0; i < data.length; i++) {
                        if (data[i].text !== tempAntID) { //Disable all but the current antennaID
                            data[i].disabled = true;
                        }
                    }
                    return {
                        results: data
                    };
                }
            },
            formatAjaxError: 'Loading failed'
        });

**Comment by kevin-brown** [comment]
I'm pretty sure this is actually a known issue that was fixed in 4.0.0.

**Comment by franckl** [comment]
Hi Kevin,
Would it be possible to fix it in the 3.x branch ? I can't use the 4.0 for production yet and the migration will be long (I use up to 15 select2 components interacting live).
Thanks
