### ISSUE TITLE
Custom theme

### ISSUE THREAD

**Issue by farhan687** [select2/select2#3285]
How can I create custom theme for select2?
In previous version I can create my custom theme with the options of
1) containerCssClass and
2) dropdownCssClass
is there any way to customize the look of select2?

**Comment by kevin-brown** [comment]
These two options were added back on the latest master and will be available in the 4.0.0 release that happens later today.

https://github.com/select2/select2/commit/f3f1b31958fa585fadfe2eada3449826ce48224e

Though it is more recommended to create an actual theme (using the `theme` option for it), as that was you don't risk theme issues if we need to change anything in the default one.
