### ISSUE TITLE
How to clear selected vlaue of single/Multiselected dropdown

### ISSUE THREAD

**Issue by yatinPatel13490** [select2/select2#3289]
Hello,

I implement the code when first dropdown value is changed than other the depended  dropdown list will automatically change. but I face one problem on that  the selected value is not unseleceted (the default value or how to set the first value of that dropdown).

please guide me on this issue.

**Comment by alexweissman** [comment]
See https://select2.org/programmatic-control/add-select-clear-items#clearing-selections.
