### ISSUE TITLE
Typeerror: when using language for 4.0 rc2

### ISSUE THREAD

**Issue by look416** [select2/select2#3293]
Whenever I am trying to use language option in 4.0 rc2, to manually change the empty result text. The console will output error
TypeError: b is not a function
in line
select2.min.js:1:7340

my code is as following:
```javascript
$('#books').select2({
                placeholder: "--Select One--",
                language:{
                    noMatches: function(term){
                        console.log(term);
                        return " heloo";
                    }
                }
            }).change(function(e){
                $('#form').formValidation('revalidateField', 'books');
            });
````

**Comment by kevin-brown** [comment]
Try using the 4.0.0 release, we only added the ability to include _some_ (not all) keys in `language` recently.
