### ISSUE TITLE
Multi-selects with data-placeholder attribute opens on load in IE 10-11

### ISSUE THREAD

**Issue by NicolajKN** [select2/select2#3295]
There seems to be a weird bug that only happens when the data-placeholder attribute is used on multi-selects. I've only observed this bug in IE 10-11. IE 9 and other browsers seems to behave appropriately. 

The select opens on load and refuses to close until an option/tag is selected.

**Comment by kevin-brown** [comment]
I've definitely seen a ticket for this before (it seems familiar) and I'm always open to reviewing a pull request that fixes it.

**Comment by kevin-brown** [comment]
Merged with https://github.com/select2/select2/issues/3300.
