### ISSUE TITLE
Select2 dropdown size mismatch because of jQuery floating point issue

### ISSUE THREAD

**Issue by MojoJojo** [select2/select2#3296]
Hi,

This refers to version 3.5.2 of Select2 plugin. When used in a responsive design such as bootstrap, there are instance when the width of the dropdown is slightly smaller than than the parent Input/Select box. When the browser window is resized or tested with other resolutions, sometimes the dropdown is exactly the same size and parent control and sometimes it is not. Check the right edge of textbox in screenshot.
Upon further investigation, it seems like the method used to calculate the width of dropdown is the culprit:
In method positionDropdown, line 1237:
width = container.outerWidth(false)

It turns out that jQuery outerWidth method only returns integer value and ignores fractional values which is causing the above issue. Replacing the above with:

var rect = $(this.container)[0].getBoundingClientRect();
var width= rect.right - rect.left;

fixes the issue.
![screenshot 2015-04-28 23 22 56](https://cloud.githubusercontent.com/assets/7907416/7380685/8f5b70dc-edfd-11e4-985f-39195ae9f916.png)

**Comment by falsefalse** [comment]
@mdumic this explains our filters `.5px` mismatch situation.
![image](https://cloud.githubusercontent.com/assets/38544/9119316/be24f986-3c7e-11e5-998b-edd850e2f7e0.png)

Yeah, `getBoundingClientRect` with a fallback to `$.width` is a way to go.

**Comment by alexweissman** [comment]
This is the same issue as #1692, just manifested in 3.x.
