### ISSUE TITLE
Wrong .select2-search__field width right after item is deleted by backspace button

### ISSUE THREAD

**Issue by vedmant** [select2/select2#3297]
Right after i press delete (backspace) button it sets .select2-search__field to 0.75em and visible only one character http://screencast.com/t/kAQNuyX0yf  http://screencast.com/t/ZGZe9n4jMd , when I press button second time it sets right width http://screencast.com/t/yGhfV8RxmT

**Comment by nazrhyn** [comment]
:+1:

Here's a GIF showing the bug. The key I'm pressing to remove is backspace.

![thinselect2](https://cloud.githubusercontent.com/assets/1672405/7414421/9a22a8e0-ef20-11e4-8b84-0ece09df3d9f.gif)

**Comment by rrhyne** [comment]
I'm seeing this problem with the placeholder text as well. To repro, enter a long place holder text over 15 characters.

temporary solution is to set select2-search__field width to 100%

**Comment by kevin-brown** [comment]
> I'm seeing this problem with the placeholder text as well. To repro, enter a long place holder text over 15 characters.

Sounds like a totally different issue, might want to open a ticket with a jsfiddle about it.

**Comment by thejae** [comment]
Actually setting width to 100% works quite well. There doesn't seem to have any nasty side effect either.

```css
.select2-container--default .select2-search--inline .select2-search__field{
  width: 100% !important;
}
```

 :+1: @rrhyne
