### ISSUE TITLE
Reinitializing Select2 with `data` should remove old options

### ISSUE THREAD

**Issue by PeterMozesMerl** [select2/select2#3298]
http://codepen.io/anon/pen/WvbVXE

Expected behaviour: Clicking on a button should add 2 options. It should remove existing options.

Current behaviour: Clicking on both buttons will add 4 options in total. Options aren’t removed. Additional clicking won’t change anything.

In case this is the normal behaviour, how can one replace the options without using the ajax search function? Version 3.x supports this.

**Comment by SAprelov** [comment]
+1

**Comment by jp7carlos** [comment]
+1

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
