### ISSUE TITLE
multiple select in AJAX mode?

### ISSUE THREAD

**Issue by jaequery** [select2/select2#33]
hi, i have a multiple select dropdown that i want to populate using ajax. your examples however only indicates just a single selects for the ajax, although I see you do have it for others. is this something that can be supported soon?

**Comment by henvy** [comment]
<input type="text" multiple="" class="js-example-basic-multiple">
It won't work
but:
<input type="text" class="js-example-basic-multiple"> and add multiple:true
It is worked
thanks ivaynberg

**Comment by henvy** [comment]
input type="text" multiple=""
input type="text"

**Comment by rvazquezglez** [comment]
If you are using select2 > 4.0 the input fields wont work, it should be a select https://stackoverflow.com/a/33210771/1195507
