### ISSUE TITLE
IE breaks when using a multiple select with a placeholder

### ISSUE THREAD

**Issue by masfoobar** [select2/select2#3300]
I am new to using Select2. I do not see this bug listed so apologies if one is already created.

I consider this a high priority bug as IE11 is a modern browser. (I do not see a priority option on this page so assume github does not support such feature?)

This bug appears in the following browsers: -
IE11 (real)
IE10 (from IE11 compatibility mode)

IE9 and earlier (from IE11 compatibility mode) does not appear to have this bug.

Firstly, you can replicate this bug simply by going to https://select2.github.io/examples.html. Go to the Placeholders section, This is the 3rd section after 'The basics' and 'Multiple select boxes'.
In IE11, simply click on the multiple select box. This is the box underneath the comment about the Placeholders.js polyfill. Now click outside the select box to lose focus.... It forces itself back into the select box.

One of the few ways to stop the items from popping up is to select an item in the list. However, once you have deleted all items (so there is nothing left) -- your back to the problem.

I believe this provides enough information to replicate the problem. Of course, if you have any further questions -- please feel free to shout!

Edit: -- It looks like this issue is tied to using the placeholder in a multiselect.. For example, the multi select in the 'Programmatic access' section, which does not use a placeholder, appears to be working fine.

M

**Comment by kevin-brown** [comment]
> I am new to using Select2. I do not see this bug listed so apologies if one is already created.

This is _definitely_ the third ticket I've seen about this, but this is the best explanation so far (so ti's going to live).

I currently am not using Windows (so I can't easily test this), but I'll gladly review a pull request that fixes this issue.

**Comment by jjanusch** [comment]
@kevin-brown You're probably already aware, but MS has virtual machines for each version of IE available. It's not as convenient as using Windows directly, but it does allow you to test on it. 

https://www.modern.ie

**Comment by green-arrow** [comment]
Any progress on this issue?

**Comment by kevin-brown** [comment]
@green-arrow Still need to do testing with this, it's been a busy last two weeks.

A screencast may be useful in confirming this by the way, just in case I can't reproduce it on my own.

**Comment by green-arrow** [comment]
@kevin-brown anything in particular you want to see in the screencast?

**Comment by sgaertner** [comment]
I've encountered the same issue with IE10. When clicking outside of the opened drop-down to close it, handleSearch is called in IE10, triggered by an input event (4.0.0 line 1850). This input event isn't triggered e.g. in Firefox. handleSearch causes the drop-down to be reopened.

Seems to be caused by http://stackoverflow.com/questions/18389732/changing-placeholder-triggers-input-event-in-ie-10

**Comment by kevin-brown** [comment]
Good news, I was finally able to get on a system with IE and reproduce this issue.

Now I just need to find out why it's happening...

**Comment by philltrue** [comment]
I managed to find the offending line in select2.full.js
```
this.$selection.on('keyup.search input', '.select2-search--inline',
        function (evt) {
      self.handleSearch(evt);
    });
```
Roughly line 1849 in Search.prototype.bind. Comment out self.handleSearch(evt) and this problem goes away. (I have search disabled however so this change may cause other issues)

Kevin if you're having trouble finding an system with IE, perhaps download the free virtual machines?
http://dev.modern.ie/tools/vms/

Hope that helps.

**Comment by kevin-brown** [comment]
Yesterday a few patches landed that might have fixed this issue. I spent a decent amount of time fixing the focus wars that would happen in multiple selects, and I have a feeling that was related to this issue.

If someone wants to test out the latest master, that would help determine if this is still an issue.

**Comment by teknull** [comment]
I'm sorry to troll on this thread, but thank you for sharing the IE virtual machines.  I've been looking for a way to Browser test my apps on my MacBook.  This is excellent!

**Comment by philltrue** [comment]
Hey Kevin,
I downloaded the latest select2-full.js and tried and didn't have any luck.

In the code you've added:
```
var key = evt.which;
```
Which is coming up as undefined in IE 11 when this bug occurs, adding in a 
```
if(key == undefined) return;
```
Causes the issue to go away, but again, I have absolutely no idea about the internals of select2 so no idea what issues this might cause.

Hope that helps in some way.

**Comment by tylik1** [comment]
@philltrue Thanks this patch fixed the bug! Tested in IE 11.
Haven't encountered any other bugs on IE and other browsers. Probably I've missed something, but this is for sure better than removing placeholder in multiselect.

**Comment by jemes** [comment]
@philltrue That fixed it too ! Thank you for the patch. Waiting for an official update though please devs :)

**Comment by srweal** [comment]
I'm not so sure that fixes the problem. I've put the lines 

`var key = evt.which;`
`if (key == undefined) return;`

But now I can't type into the select2 control and have it filter my options. Anyone else seeing this effect of the patch?

**Comment by tylik1** [comment]
@srweal  Unfortunately the same bug. I would like to offer a little different solution. I digged a little bit and found out that 'input' event is causing such behavior in IE. So my solution includes checking if browser is IE and disabling 'input' event. I know that the solution is NOT ideal, and probably typing in windows mobile will not trigger filtering the select, but hope it's better than nothing:

//Check if browser is IE
var isIE = (function msieversion() {
    var ua = window.navigator.userAgent.toLowerCase();
    if (ua.indexOf("msie") > 0 || ua.indexOf("trident") > 0 || ua.indexOf("edge") > 0) {
        return true;
    }

    else {
        return false;
    }

}());
// If browser is IE, do not attach input event

var input_event = !isIE ? 'input' : '';
if (!isIE) {
    this.$selection.on('input', '.select2-search--inline', function (evt) {
// Unbind the duplicated `keyup` event
        self.$selection.off('keyup.search');
    });
}


this.$selection.on('keyup.search ' + input_event, '.select2-search--inline',

//Rest of the code stays untouched

**Comment by molily** [comment]
> ua.indexOf("edge") > 0

FYI, the problem does not occur on Edge in my tests with Windows 10 Pro Insider Preview Build 10162 on https://select2.github.io/examples.html and http://codepen.io/molily/pen/JdvjNZ

**Comment by tylik1** [comment]
@molily  Thanks! Removed that line.

**Comment by kevin-brown** [comment]
So, just to confirm some things and perhaps get a solution prepared.

The issue is that in IE, the `input` event doesn't carry the key pressed (`evt.which`/`evt.key`/`evt.keyCode`), unlike other browsers?

**Comment by jancbeck** [comment]
One of my clients just notified me of a bug and I could confirm that this issue is the origin. I'm waiting for a fix to come and meanwhile disable multiple select like so:

```js
var isIE11 = !!navigator.userAgent.match(/Trident.*rv\:11\./),
	select2options = {
		multiple: isIE11 ? false : true
	};
	$('.widget_seminare_filter select').select2(select2options);

**Comment by digitaldonkey** [comment]
Confirming philltrue's patch (https://github.com/select2/select2/issues/3300#issuecomment-114304535) working. (jancbeck is a workaround, the fix is above)

**Comment by joshdevries** [comment]
The issue is entirely the result of the placeholder when used in IE, even on your website, when a placeholder is involved on a multi select, it fails to close.

If you remove the placeholder it works perfectly fine.

**Comment by dmdm22** [comment]
Applied philltrue's patch, which truly fixes the dropdown ... but this also breaks search on multiple selects (tagged input with inline search). 

Any typing will not search the dropdown anymore, cause no key on event no matter which key pressed, so function will always return.

Guess the issue might better be fixed somewhere on setting the placeholder.

Only working solution for me now is not to use placeholders on multiple selects.

**Comment by scashin133** [comment]
I'm guessing this is caused by IE11 triggering an input event on focus when it has a placeholder, which is a known issue. https://connect.microsoft.com/IE/feedback/details/885747/ie-11-fires-the-input-event-when-a-input-field-with-placeholder-is-focused

**Comment by TravnikovRN** [comment]
Hi, in my project i got the same problem. I clone 'master' and tried all the fixes from this topic but no one helped. Disable multiseleсt to IE is not acceptable

**Comment by xthiago** [comment]
If you can't disable multiselect, you can remove the placeholder. This fix the issue on IE10 e IE11 for me.

I write the follow workaround to add and remove placeholder manually in these browsers.

```javascript
var myPlaceholder = 'My placeholder';
var isIE10 = !!navigator.userAgent.match(/MSIE 10/i);
var isIE11 = !!navigator.userAgent.match(/Trident.*rv\:11\./);
var myPlaceholder = 'My placeholder';

$('#input').select2({            
    multiple: true,
    placeholder: isIE11 || isIE10 ? '' : myPlaceholder,
    /* others options.. */
});

if (isIE11 || isIE10) {

    jQuery('.select2-search__field').attr('value', myPlaceholder);

    $(document).click(function(event) {
        if($(event.target).closest('.select2').length == 0 && $(event.target).closest('.select2-container').length == 0) {
            $('.select2-search__field').blur();
            jQuery('.select2-search__field').attr('value', myPlaceholder);
        } else {
            jQuery('.select2-search__field').attr('value', '');
        }
    });

}
```

**Comment by juanrmn** [comment]
@xthiago Thanks! That works fine for me too!

**Comment by Alxdhere** [comment]
Bug with multiselect reproduce on select2 site in IE10:
![Bug](http://alxd.it-dept.ru/download/select2-bug-ie10.png)

**Comment by Moter8** [comment]
@xthiago Good try, but that only shows either a single char or nothing at all for me -- on IE11.

Screen recording of it: https://imgrush.com/1RtBy6GXGLxy

The "Auswahl löschen" button is bound to:

```js
$(".button-clear").on("click", function () { $mySelect.val(null).trigger("change"); });
```
but apparently only on the second click it sets the placeholder again.

**Comment by Moter8** [comment]
To get the placeholder show up on Pageload, after setting up select2 and the buttons, I do

```js
<script>
    $mySelect.val(null).trigger("change");
</script>
```
which works alright. But the issue of having to clear twice to get the placeholder persists.

**Comment by Miw0** [comment]
The bug still exists for me in 4.0.0 but also in the master branch :(

**Comment by Moter8** [comment]
I can confirm it fixed the issue for me. Had to manually build though,
obviously.

2015-08-25 9:08 GMT+02:00 Michael Worm <notifications@github.com>:

**Comment by Eckankar** [comment]
66ae2ad doesn't quite fix the issue for me. It looks like the fix contains a race condition, so the `input.search` event is triggered before it is unbound by the `input.searchcheck` event.

I verified this by adding 

    var msie = document.documentMode;
    if (msie && msie <= 11 && evt.type === 'input') {
      self.$selection.off('input.search input.searchcheck');
      return;
    }

to the second (i.e. `input.search`) input event, which successfully stopped the bug on my end.

**Comment by kevin-brown** [comment]
I'm going to reopen this while we're waiting for a patch to fix the race condition.

**Comment by netatoo** [comment]
66ae2ad + @Eckankar is solution were solving the problem for me with multiple[placeholder] input on IE 10+

Is it possible to know when it is planned to integrate this patch to the master? 4.0.1? Thanks

**Comment by kevin-brown** [comment]
> Is it possible to know when it is planned to integrate this patch to the master? 4.0.1? Thanks

It will be in there for the 4.0.1-rc.1 that is coming soon (I've got a note about it). It can be put on master even sooner if someone creates a pull request that adds it.

**Comment by jarthod** [comment]
Hi, I spend quite some time debugging this also and found all the issues mentioned in this ticket. I then tried master which fixes a lot of them and I am left with the auto open issue caused by the race condition when removing the "input" event handler on IE (the second handler is still called).

I currently monkey patched it that way:
```javascript
$.fn.select2.amd.require(['select2/selection/search'], function (Search) {
  var oldBind = Search.prototype.bind;
  Search.prototype.bind = function () {
      oldBind.apply(this, arguments);
      var msie = document.documentMode;
      if (msie && msie <= 11) {
          this.$selection.off('input.search input.searchcheck');
      }
  };
});
```

This code simply unbinds the event at initialization instead of on first event, so there is no race condition. It's not a beautiful fix though, maybe we should simply not bind "input" at all on IE.

**Comment by madbriller** [comment]
Here is more information pertaining to this issue:
http://www.carsonshold.com/2013/12/js-bug-ie-10-and-11-oninput-event-with-placeholder-set/

I found success with replacing the evt.which check before handleSearch is called:
```
function (evt) {
    if (self.$search.val().length === 0) {
        return false;
    }
    self.handleSearch(evt);
```
This change also maintained the search functionality. 

The part I find really weird is that console.log(evt) shows evt.which to be undefined in Chrome too, but it didn't seem to throw any errors?

**Comment by Stuey2** [comment]
Another fix - seems to do everything, with minimal changes to the Select2 code. Search and everything works well. Just modify the `Search.prototype.handleSearch` method as below. It's on line ~1870

    var lastSearchInput = "";
    Search.prototype.handleSearch = function () {
      this.resizeSearch();
      function isEmptyOrSpaces(str) {
      	return str === null || str.match(/^ *$/) !== null;
      }
        
      if (!this._keyUpPrevented) {
        var input = this.$search.val();
        if (!isEmptyOrSpaces(lastSearchInput) || !isEmptyOrSpaces(input)) {
      	  lastSearchInput = input;
      		this.trigger('query', {
      			term: input
      		});
      	}
      }
      
      this._keyUpPrevented = false;
    };

**Comment by sirNemanjapro** [comment]
IE10 and IE11 problem still exits.

**Comment by videsignz** [comment]
If you add a placeholder on the search input when the drop down is attached to the container, it breaks. You can no longer close the drop down unless you choose a selection.

**Comment by videsignz** [comment]
For those of you having issues when the dropdown is attached to the container, I did a quick fix for only adding a placeholder to the search if its not IE.  On line 3835, right below the search html, I added...

```js
	// Temp Patch Start
    var msie = document.documentMode;
    var disableInputEvents = msie && msie <= 11;
	
	if(!disableInputEvents){
		$search.find('input').attr('placeholder', 'Search');		
	}
	// Temp Patch Finish
```
Not the best fix as it doesn't target the core problem, but it works for now.

**Comment by Curtisdhi** [comment]
This issue was closed, but the issue still occurs. Tested with select2 4.0.3

**Comment by jacquibo** [comment]
Agree with @Curtisdhi still getting this issue in 4.0.3 :(

**Comment by lalwanikamal165** [comment]
It the issue is fixed?

**Comment by alexweissman** [comment]
I'll reopen this for now.  Not sure if it's related to #4860?

**Comment by hasi94** [comment]
is this bug fix ?

**Comment by SrujanaPhani** [comment]
The issue still exists in IE-11 !

**Comment by dimitarbikov** [comment]
Few years late to the show, but the issue seems to be still there.
Can anyone confirm, or should I look into my own code?
