### ISSUE TITLE
Uncaught Error: No select2/compat/containerCss - containerCssClass

### ISSUE THREAD

**Issue by lerox** [select2/select2#3302]
Hi,

I'm trying to set the class containerCssClass like in: http://stackoverflow.com/a/15029054 but it doesn't work.

In my console i got:

Uncaught Error: No select2/compat/containerCss (Line 209 of select2.js)

Can someone help me? I need to set the class that already exists in the input field.

Thanks

Select2 4.0.0

**Comment by kevin-brown** [comment]
You must use the full version of Select2 (`select2.full.js`) in order to support the `containerCssClass` option.

**Comment by lerox** [comment]
Thanks, 

I will try!

**Comment by lerox** [comment]
@kevin-brown +1

Thanks a lot!

**Comment by palluri542** [comment]
How do you install full version from bower?

**Comment by sparkdevelopment** [comment]
Perhaps this could be added to the error message? Would have saved me 30 minutes!

**Comment by alex051186** [comment]
> You must use the full version of Select2 (`select2.full.js`) in order to support the `containerCssClass` option.

Thanks a lot

**Comment by kadsyy** [comment]
> You must use the full version of Select2 (`select2.full.js`) in order to support the `containerCssClass` option.

Would be helpful if it stated in the documentation which options requires select.full.js and which one are not.
