### ISSUE TITLE
Dropdown body is positioned incorrectly when dropdownParent isn't statically positioned

### ISSUE THREAD

**Issue by nchen63** [select2/select2#3303]
Steps to reproduce:
1. navigate to http://jsfiddle.net/Leppndoo/
2. click on dropdown

issue: the dropdown body does not appear below the control. 

The control is located at top:100px;left:100px but the dropdown body is located at top:228px;left:200px

**Comment by nchen63** [comment]
```<body>
    <div style="height:500px; width:500px; overflow:auto; display:block; background-color:red"> 
            <span class="asdf" style="height:3000px; display:block; left:100px;top:100px;position:relative">
                <select class="js-example-basic-single">
                      <option value="AL">Alabama</option>
                      <option value="WY">Wyoming</option>
                </select>
            </span>
    </div>
</body>
```

```
$(document).ready(function () {
    var parentElement = $(".asdf");
    $(".js-example-basic-single").select2({
                dropdownParent: parentElement
            });
    
});
```

**Comment by MilosR** [comment]
The problem is because one of, or more, parent containers have position other than static (relative, absolute), and in script dropdown top & left values are calculated with regard to document body.

Line 124 of attachBody.js
    var offset = this.$container.offset();

**Comment by kevin-brown** [comment]
_This is probably why Select2 3.5 was special casing static positioning..._

If we can find a way that works for determining the offset which doesn't require special casing, that'd be awesome. But I might be willing to review a pull request that does handle special casing, as long as we can get tests alongside of it.

**Comment by wesgarland** [comment]
I had the same issue, but MilosR's fix did not work for me.  It moved the dropdown position to the top left of the parent container, which is not correct.  I am trying to insert my stuff pretty deep into the document, to play nice with a bunch of existing code.

Unfortunately, I am not a jQuery guy so my fix is clunky, but it appears to work for my case, on Firefox-latest and Chrome-latest.  I appended this to the end of AttachBody.prototype._positionDropDown, right after the call to this.$dropdownContainer.css:

    var rect = this.$dropdownParent.getBoundingClientRect();
    this.$dropdown[0].style.left = -rect.left + "px";
    this.$dropdown[0].style.top = -rect.top + "px";

That's line 4095 of select2.full.js for version 4.0.0.

**Comment by afattahi54** [comment]
May be this help ;)
Removing the scroll bar of parent div, cause the div drop down shown in different
![Uploading 12.png…]()
![Uploading 13.png…]()
![Uploading 14.png…]()

**Comment by afattahi54** [comment]
May be this help ;)
Removing the scroll bar of parent div, cause the div drop down shown in different

![12](https://cloud.githubusercontent.com/assets/5003703/8427310/8795e418-1f2b-11e5-8d0d-c6cdebd975db.png)
![13](https://cloud.githubusercontent.com/assets/5003703/8427311/87d9a4f0-1f2b-11e5-991c-8f482350105a.png)
![14](https://cloud.githubusercontent.com/assets/5003703/8427312/88070e90-1f2b-11e5-8d08-3b6fe31f0993.png)

**Comment by JustasKuizinas** [comment]
If parent has positin relative, dropdown is positioned incorectly

**Comment by afattahi54** [comment]
May be this could also help.
When the firebug is open, the select2 shows a gap, while if the firebug is closed, the select2 position is displayed fine.
![untitled](https://cloud.githubusercontent.com/assets/5003703/9191268/657e557c-4014-11e5-84f0-61b067f8f6d6.png)

**Comment by jBernz** [comment]
// Fix positioning with static parents
    if (this.$dropdownParent[0].style.position !== 'static') {
      var parentOffset = this.$dropdownParent.offset();

      css.top -= parentOffset.top;
      css.left -= parentOffset.left;
    }

These are lines I found in select2.js.

Think it makes more sense to say  if (this.$dropdownParent[0].style.position **==** 'static')

And when I use equality it fixes this problem.

**Comment by kevin-brown** [comment]
@jBernz The issue that came from those lines are going to be in the upcoming 4.0.2-rc.1 release, and the eventual 4.0.2 release. You can use the `master` branch for now, there are no more code changes coming in before the release candidate.

**Comment by tlartaud** [comment]
@kevin-brown I was facing the same issue since a long time. I can confirm that the master branch fixes this issue. However, as I am fetching my scripts with bower, I need to use the github url until the 4.0.2 get released to be able to use the fixed version.

```
  "dependencies": {
    "jquery": "*",
    "modernizr": "*",
    "bootstrap": "*",
    "select2": "git@github.com:select2/select2.git#master",
  }
```

Thanks a lot.

**Comment by alexweissman** [comment]
For those struggling with this issue, and not using Bower, you can find the commit that fixed this problem here: https://github.com/select2/select2/commit/e260860789db87c68ed2889895c76a22e94dbce1

**Comment by minlare** [comment]
Commit [e260860](https://github.com/select2/select2/commit/e260860789db87c68ed2889895c76a22e94dbce1) does not fix the issue for me.
https://jsfiddle.net/minlare/nggt64a6/ - open the select2 dropdown and scroll the viewport.

**Comment by remmel** [comment]
In 4.0.2 in bower + running _ bower update_ command:
```
{
  "dependencies": {
    "select2": "4.0.2"
  }
}
```

**Comment by Loadmaster** [comment]
I had a related issue (v 4.0.2) with the drop-down div not being repositioned whenever the tag list area changes size (i.e., when a tag is added or removed from the list when the user selected/deselects a choice). I set options `tags:true` to enable tagging, and set `closeOnSelect:false` to keep the drop-down open after a select/deselect action.

I found a work-around by catching the `"change"` event and forcing a resize of the drop-down element.
```
// Force drop-down list to resize upon select/unselect
select2Elem.on("change",
    function(evt) {
        select2Elem.resize();
    }
);
```
Details are on StackOverflow at [http://stackoverflow.com/questions/37198185](http://stackoverflow.com/questions/37198185).

**Comment by kevin-brown** [comment]
https://github.com/select2/select2/commit/ecdc41663508f0a5ea242fe249aa5a9a3a741ba6 should have finally fixed this issue in 4.0.3, so I would highly recommend upgrading to it if you have not already.

**Comment by firebird631** [comment]
I'm using 4.0.3 and I've the issue. The problem appears the first time I open the dropdown, if I close it and open it a second time it has a correct position. If I search for results, and they exists, then the next dropdown position (after close and reopen) will be up by the height of by previous results.

In others words, if there is not results, top position should be ok, if there is one result, the next open will show the dropdown with a top - height_of_a_result, and this become top - num_results*height_of_a_result.

**Comment by tlartaud** [comment]
@kevin-brown 4.0.3 fixed the related issue for me. The dropdown is now showing on the top of the field if the field is displayed on the really bottom of the screen. Thanks a lot for that fix.

**Comment by LuuchoRocha** [comment]
I think this still present on 4.0.3
https://github.com/select2/select2/issues/4526

**Comment by vol7ron** [comment]
@LuuchoRocha confirmed.

**Comment by pablo-pacheco** [comment]
same problem here on 4.0.3

**Comment by pablo-pacheco** [comment]
I'm doing an ugly hack to solve this but it's working:

```
jQuery('.element').select2();
jQuery('.element').select2('open');
jQuery('.element').select2('close');
```

**Comment by arvinhubert** [comment]
anybody fixed this problem?

**Comment by LuuchoRocha** [comment]
@arvinhubert check this https://github.com/select2/select2/issues/4614#issuecomment-251277428

**Comment by arvinhubert** [comment]
@LuuchoRocha thanks sir but I solved it already :)

**Comment by zhanchengkun** [comment]
666@LuuchoRocha

**Comment by mmunozha** [comment]
I solved the issue updating line 4261 
From: 
```javascript
bottom: $window.scrollTop() + $window.height()
```
To:
```javascript
bottom: $window.scrollTop() + window.innerHeight
```

The complete block would look something like:
```javascript
    var viewport = {
      top: $window.scrollTop(),
      bottom: $window.scrollTop() + window.innerHeight
    };
```

**Comment by dudv** [comment]
I'm also experiencing the same issue as @firebird631 described. Anybody knows how to fix it?

**Comment by jpic** [comment]
@dudv did @mmunozha's suggestion work for you ?

**Comment by bvacchiano** [comment]
@nchen63's solution worked for me. I use the bootstrap theme for select2 and was having the same  problems as the OP (specifically on _IE10_ with the select2 being positioned at a different location on the webpage than where the select2 element was located). Here's my example code for anyone that needs it.

**JS**
```
 $(document).ready(function () {
            var parentElement = $("#locationCodesParent");
            $("#locationCodesSelect2").select2({
                placeholder: "Select Location Type",
                theme: "bootstrap",
                dropdownParent: parentElement,
                width: null //select2 to take on width of parent
            });
 });
```
**HTML**
```
 <div id="locationCodesParent" class="col-lg-4 col-md-4 col-sm-4">
     <select id="locationCodesSelect2">
         <option value="">-Select-</option>
         <option value="096">ABANDONED BUILDING</option>
         <option value="095A">AIRCRAFT</option>
         <option value="095J">AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA</option>
         <option value="095I">AIRPORT BUILDING NON-TERMINAL - SECURE AREA</option>
    </select>
  </div>
```

**Comment by johnarnfield** [comment]
@jpic - I can confirm that @mmunozha's solution does not work for the ajax issue

**Comment by azhararmar** [comment]
When dropdown position was misaligned, I noticed that It automatically realigned if I scroll, hence what I did was I added 1px scroll on opening the dropdown, this may be a dirty hack, but actually worked in my case.

Here is what I did

```
$('.select2-ajax-zipcode').on('select2:open', function (e) {
    var y = $(window).scrollTop();
    $(window).scrollTop(y + 1);
});
```

**Comment by kateno** [comment]
In my case the problem is triggered only when I have the Select2 inside a Modal (Bootstrap Modals) AND the main page was scrolled (not at top) at the moment of opening the modal, so the longer the scroll, the longer the gap between controller and dropdown.

I fixed it doing this:
`var scrollFix = 0;
      if($(".modal.fade.in").length){ //Check if there's an open modal
          scrollFix=$(window).scrollTop();
      }
    container.top = offset.top;
    container.bottom = offset.top + container.height - scrollFix; //substract the scroll when modal is open`
Originally was: 
` container.top = offset.top;
    container.bottom = offset.top + container.height;`

**Comment by aleixfabra** [comment]
Adding `dropdownParent: parentElement` worked for me!

**Comment by almeidaalex** [comment]
@aleixfabra, it's worked for me too, I've a modal thats closes with outside click, when you double click on select2's search box, it closes modal, after apply modal as parentElement this misbehaviour has stopped

**Comment by harrisjones** [comment]
Since I was initializing my select2 elements using a common class instead of an id, I didn't always know what 'parentElement' was. I ended up initializing my selects inside of a $.each(), and then setting $(this).parent() as the dropdownParent. Haven't had any problems so far...fingers crossed 😁 

`
$('#myModal .select2').each(function() {
  var $p = $(this).parent();
  $(this).select2({
    dropdownParent: $p
  });
});
`

**Comment by vinothsmart** [comment]
$('#myModal .select2').each(function() {  
  var $p = $(this).parent();  
  $(this).select2({  
    dropdownParent: $p  
  });  
});

This is Worked for me

**Comment by jalberromano1980** [comment]
Hello friends! I'm having a similar problem, but it's with the data-plugin switchery ... It's not working ... Would anyone know how to do it?

**Comment by zdimaz** [comment]
Add a     position: relative; to parent )))))))

**Comment by kasraebrahimi** [comment]
setTimeout(function() {
            $('#target-select').select2('open');
}, 1); !!

**Comment by KentPatrickSL** [comment]
> Since I was initializing my select2 elements using a common class instead of an id, I didn't always know what 'parentElement' was. I ended up initializing my selects inside of a .each(),andthensetting(this).parent() as the dropdownParent.
> 
> ```
> $('#myModal .select2').each(function() {  
>   var $p = $(this).parent();  
>   $(this).select2({  
>     dropdownParent: $p  
>   });  
> });
> ```

This was the perfect answer for my perfect scroll issue where if I had select2 elements further down the page the dropdown would attempt to display in a negative position even after attempting to point the parent at different locations (like the scroll-content wrapper etc).

**Comment by annv-ltv** [comment]
Thank @harrisjones
