### ISSUE TITLE
Clear button appears under long text when using allowClear

### ISSUE THREAD

**Issue by cersos** [select2/select2#3306]
I am using Firefox version 31.5 (limited due to corporate policy).

If the text of the selected item is wider than the input field, the little x seems to be behind the text and cannot be clicked to clear the contents.  It simply drops the selection box down as if I had clicked anywhere on the selection.

I do have a width set.

This works fine in IE 11.

![2015-05-02_9-03-33](https://cloud.githubusercontent.com/assets/12209819/7441181/70bccdf6-f0aa-11e4-9974-83395a93f874.jpg)

**Comment by jccounihan** [comment]
+1. 

Tested with Select2 V4 from CDNJS.

Works in IE 11.0.9600.17728.
Does not work in Chrome 42.0.2311.135 (Official Build) or Firefox 31.

Fiddle to demonstrate the issue: http://jsfiddle.net/crazyJ/0m4a5cLz/

It appears to be because the "x" for the clear is a nested span element under the text.

**Comment by kevin-brown** [comment]
Reproduced this in Chrome, pull requests are always appreciated.

**Comment by yuhongwei1122** [comment]
I have the same problem.....How to solve it . The reason is " It appears to be because the "x" for the clear is a nested span element under the text."。

**Comment by omggga** [comment]
You can solve it by adding to ".select2-selection__clear" absolute position and right direction, but there may be a different crossbrowser errors.
http://jsfiddle.net/0m4a5cLz/3/

**Comment by njakobsen** [comment]
It looks like the problem is caused by the overflowing text covering the clear button because it declared lower down in the DOM. The clear button can be made to render over top of the ellipses simply by making it position:relative.

**Comment by sushain97** [comment]
+1

Does not work in Chrome 43.0.2357.130.
Works in Safari 8.0.6.

**Comment by SPodjasek** [comment]
@fk PR fixes this issue also on FF v40. There are still some minor layout problems in FF (text ellipsis still goes below clear symbol), but it works.

Chrome 39.0.2171.95:
![zaznaczenie_947](https://cloud.githubusercontent.com/assets/3293161/9954306/3cf0d1a6-5de8-11e5-892b-a898b0a7e535.png)

Firefox 40.0.3:
![zaznaczenie_948](https://cloud.githubusercontent.com/assets/3293161/9954314/51e404de-5de8-11e5-99da-72eae650cd4b.png)

**Comment by githubjeka** [comment]
@SPodjasek thanks
