### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by embee8** [select2/select2#3308]
Hi there,

https://select2.github.io/examples.html says the following with regards to loading remote data:

``` javascript
data: function (params) {
      return {
        q: params.term, // search term
        page: params.page
      };
    },
```

Because the params.page variable is not set on the first query, this should be:

``` javascript
data: function (params) {
      return {
        q: params.term, // search term
        page: params.page || 1
      };
    },
```

**Comment by alexweissman** [comment]
What if we're just setting the default value in `processResults`?  See https://select2.org/data-sources/ajax

>Because the params.page variable is not set on the first query

I kind of wonder if this is something that should be handled internally by Select2 itself.

**Comment by alexweissman** [comment]
Ok, I have added this to the documentation for now: https://select2.org/data-sources/ajax#pagination
