### ISSUE TITLE
Select2 4.0 not working with Parsleyjs

### ISSUE THREAD

**Issue by almogdesign** [select2/select2#3309]
Just upgraded from 3.5 to 4.0 and I'm noticing that my parsely validation is not working anymore 

Here is my code 

```html
<select style="width: 75%" id="blocks" name="blocks" data-parsley-group="step1" required>
    <option></option>
</select>
```

**Comment by kevin-brown** [comment]
Can you try to reproduce this in a jsbin/jsfiddle for us?

**Comment by almogdesign** [comment]
It pretty straight forward the the required message never shows up? I think this is due to the input field which is no longer part of 4.0

**Comment by almogdesign** [comment]
I got it working, was an issue to a change event. Just need to fix the style now

**Comment by Jivebunny** [comment]
@AlmogRnD Can you enlighten me on how you fixed this? Running into the same issue.
