### ISSUE TITLE
autocomplete=off is ignore by Chrome

### ISSUE THREAD

**Issue by ncri** [select2/select2#3313]
Haven't tested other browsers yet, but my chrome offers an autocomplete for my select2 search field despite it having `autocomplete=off`. Really annoying. Any idea how to fix this?

**Comment by ncri** [comment]
See this: https://code.google.com/p/chromium/issues/detail?id=468153

I worked around it with this code (coffeescript):

    setTimeout ->
      $('input.select2-input').attr('autocomplete', "xxxxxxxxxxx")
    , 1000

**Comment by kevin-brown** [comment]
Closing this off because it's a browser issue, and it's difficult to work around browsers which do not conform to the specification.
