### ISSUE TITLE
Select2 4.0.0 does not port CSS classes from original input

### ISSUE THREAD

**Issue by lllopo** [select2/select2#3314]
Select2 does not port css classes from the original input, neither allows setting css classes explicitly. This hinders seriously the ability to style the element when specific class name are required, like for example scaling the element with Bootstrap input sizing classes input-lg, input-sm etc.

**Comment by kevin-brown** [comment]
You need to use the full build and `containerCss: 'all'` now as noted in https://github.com/select2/select2/commit/f3f1b31958fa585fadfe2eada3449826ce48224e.

**Comment by lllopo** [comment]
Yes, I'm aware of that, but (correct me if I'm wrong) as far as I understand, those are mostly for transitional backward compatibility and at some point they will be gone probably. So, if that's the case - this far from a stable solution of the issue.
