### ISSUE TITLE
Slow select

### ISSUE THREAD

**Issue by Shkarbatov** [select2/select2#3317]
I use select2 v.4.0. When there are a lot of native select elements (~3000), a drop-down list appears with a significant delay, especially on tablet PCs. Is there any way to inform a user about loading?

Or how I can make it more quickly?

Thank you for your consideration on this matter.

**Comment by sahanDissanayake** [comment]
:+1:  Came here to report the exact problem, This time my issue is that I have around 800 multi select element and the dropdown take like 200ms to dropdown and also the typing feels so sluggish.

Any thoughts would be great

**Comment by kevin-brown** [comment]
A jsfiddle would be great, so we can use it as a base test for making improvements.

**Comment by sahanDissanayake** [comment]
@kevin-brown Please see this fiddle http://jsfiddle.net/4ad7A/93/

Hope you can see the delay

**Comment by jakeNiemiec** [comment]
Still an issue in 2017.

**Comment by alexweissman** [comment]
There are many open issues related to performance already: https://github.com/select2/select2/labels/performance

In particular, #4407 seems to have more discussion of the issue.
