### ISSUE TITLE
second select don't work on resize

### ISSUE THREAD

**Issue by ghost** [select2/select2#3319]
1. create two select2 items
2. Open first select and do nothing(must be opened) and then open second select. Try resize window
   Actual result: second select didn't resize
   Expected: i think it must be resized 

example here
http://jsbin.com/qimitusapa/1/edit?html,css,js,output

**Comment by ravin000** [comment]
If it can help
when initiated second select2, previous is visible and then call "close" event for previous and delete events for second also.
I think better will be first of all delete previous and then showDropdown for second
