### ISSUE TITLE
Bootstrap Modal Closes When Select Is Made

### ISSUE THREAD

**Issue by joshdevries** [select2/select2#3321]
I am having an issues with select2 version 4 when using Select2 in a modal.

Every time a Select2 drop down is selected when inside a modal, the modal closes and the contents within the selected drop down remain on the page.

Its almost like the modal looses focus.

After this happens, there is no way of removing the left over contents from the page.
![capture](https://cloud.githubusercontent.com/assets/5933765/7502859/071e8612-f40d-11e4-8255-a9ca15915a7e.PNG)

Is this a known issue?

Any help would be greatly appreciated.

**Comment by kevin-brown** [comment]
https://github.com/select2/select2/issues/942#issuecomment-77673177 and https://github.com/select2/select2/issues/2152#issuecomment-38366258 should solve the problem, it sounds like Bootstrap is closing the modal because it has lost the focus.
