### ISSUE TITLE
Token seperators don't fire select events

### ISSUE THREAD

**Issue by stretch4x4** [select2/select2#3325]
In version 4.0.0 when adding new tags using token separators (eg , " ") the change event is being fired but not the select2:select event.
Adding a new tag using enter instead does however fire this event so I think this is a bug.
An example can be found here: https://jsfiddle.net/u0xja2wx/

**Comment by kevin-brown** [comment]
This is because the tokenizer is triggering the `select` event directly instead of using Select2's internal event system.

https://github.com/select2/select2/blob/ac1680d81dcc60009c5d0fe0dd52e70bc065c140/src/js/select2/data/tokenizer.js#L25

**Comment by stretch4x4** [comment]
Cool thanks for the heads up I will see if I can come up with a fix in the next few days

**Comment by ncolomer** [comment]
:+1:
