### ISSUE TITLE
Limiting the number of selections example points to the wrong option

### ISSUE THREAD

**Issue by stretch4x4** [select2/select2#3326]
The v4.0.0 documentation has conflicting information in the Limiting the number of selections section.
The example correctly shows the attribute as **maximumSelectionLength**, however the descriptive text shows the attributes as **maxSelectionLength** which is highlighted in red.
![maxselectionlength](https://cloud.githubusercontent.com/assets/12271094/7516078/ebcfa0ae-f50f-11e4-9920-1a817836df32.PNG)
I thought this feature didn't work with tags but I think I must have used the wrong attribute as when trying to reproduce it it does now work.
Hopefully this example can be updated.

**Comment by kevin-brown** [comment]
Fixed in https://github.com/select2/select2/pull/3454.
