### ISSUE TITLE
Need help in adding tags in select 2 from any other input on page

### ISSUE THREAD

**Issue by saifabbasi** [select2/select2#3328]
Hello!
@Kartik V Thanks for the great widget!

I am using yiur widget with multiple option, it creates tags as i continue select from drop down, how ever i have a grid on page with a button from which i want to add grid's record id and text to be added as a tag in your widget as a tag, let me know any possiblity, i am trying like this, with no luck.
//grid's action column button
'attribute' => 'Action',
'format' => 'raw',
'value' => function ($model) {
return Html::button('Add', [ 'class' => 'btn btn-primary', 'onclick' => 'addSelectedChoice({"id":"'.$model->id.'","text":"'.$model->word.'"})' ]);

i know this function is called inside container, how can i call this function from my button, for now i get a not defined error.

thanks

**Comment by kevin-brown** [comment]
This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

https://github.com/kartik-v/yii2-widgets
https://disqus.com/home/discussion/krajee/yii_select2_widget_kartik/

[ml]: https://github.com/ivaynberg/select2#mailing-list
