### ISSUE TITLE
No longer able to search directly on focus without click

### ISSUE THREAD

**Issue by maarten00** [select2/select2#3329]
In 3.x I was able to tab to a select2 field and directly start typing, you can try it out here:
http://select2.github.io/select2/

In 4.0 this is is no longer possible. You have to click an item or press enter before being able to search. This is a downgrade and I don't see it anywhere in the release notes, so probably a bug. 
Proof that it no longer works can be found by trying here: https://select2.github.io/examples.html

**Comment by kevin-brown** [comment]
Duplicate, explained at https://github.com/select2/select2/issues/3279#issuecomment-96450069.
