### ISSUE TITLE
Ajax load with minimumResultsForSearch set high still shows search

### ISSUE THREAD

**Issue by cadriel** [select2/select2#333]
When using the ajax parameter with minimumResultsForSearch set high (I want to disable search...) - upon the first click of select2, the search field appears.

Once the first result set is loaded - the search box disappears. From this point on, the search box doesn't show up again - which is expected behaviour.

Can the search box be defaulted to hidden?

**Comment by noamyg** [comment]
Hey, still getting this issue in 2018 :-)
The search box is appearing for a brief second, and disappears once AJAX call is returning a result.

```

    $('#mySelect2').select2({
      minimumResultsForSearch: -1,
      ajax: {
        data: function (params) {
          var query = {
            filterQuery: params.term
          }
          return query;
        },
        url: function(){
          return that.picklistUrl
        },
        processResults: function (data, params) {
          return {
              results: $.map(data.coll, function(obj) {
                  return {id: obj.Id, text: obj.Name};
              },
            ),
          }
        },
        dataType: 'json'
      },
      width: "100%" 
    });
```
