### ISSUE TITLE
[v4] Not updating set data 

### ISSUE THREAD

**Issue by almogdesign** [select2/select2#3330]
I just upgraded to version 4 and now my set data is not working 

I'm doing the following 

Init
```javascript 
$("#fertilizer").select2({
    data: listToLoad,
    placeholder: mf('pleaseSelectFertilizer',"please select fertilizer")
 }).on('change', function (e) {
    var concentration = $("#fertilizer").select2('data')[0].concentration;
    $("#typesOfConcentration").text(concentration);
    $("#typesOfConcentrationDiv").removeClass("hide");
});
```

```javascript
var fertilizer = $("#orders").select2('data')[0].fertilizer;
var fertilizerId = $("#orders").select2('data')[0].id;
var concentration = $("#orders").select2('data')[0].concentration;
$("#fertilizer").select2("data", {id: fertilizerId, text:fertilizer});
```

**Comment by kevin-brown** [comment]
As noted in the [release notes](https://github.com/select2/select2/releases/tag/4.0.0-rc.1) ([twice actually](https://github.com/select2/select2/releases/tag/4.0.0-beta.1)), `.select2("data")` is read-only now. This will actually trigger a warning if you put Select2 into debug mode (setting the option `debug` to `true`).

In your case, you don't need to use `.select2('data')` at all. You appear to only be using it so you can re-map `fertilizer` to `text`, which should be done _way before the option is selected_. [The `id` and `text` properties are required](https://select2.github.io/announcements-4.0.html#changed-id) and it doesn't take much to re-map them before passing `data` to Select2.

```js
var listToLoad = $.map(listToLoad, function (obj) {
  obj.text = obj.text || obj.fertilizer;
 
  return obj;
});

$("#fertilizer").select2({
    data: listToLoad,
    placeholder: mf('pleaseSelectFertilizer',"please select fertilizer")
 }).on('change', function (e) {
    var concentration = $("#fertilizer").select2('data')[0].concentration;
    $("#typesOfConcentration").text(concentration);
    $("#typesOfConcentrationDiv").removeClass("hide");
});
```

For everyone else who actually used `.select2('data')`, you should be able to use `.val()` now and just pass in the `id` that needs to be set. If you need to select an option which doesn't actually exist, you can just create the `<option>` for it (like you would in a standard `<select>`) ahead of time.
