### ISSUE TITLE
Tabbing to a multiselect doesn't automatically open the dropdown and allow typing.

### ISSUE THREAD

**Issue by philipwalton** [select2/select2#3331]
In 3.5.2 I could tab to through a form and the multiselect fields would automatically be in focus with the cursor in the input and the dropdown open. Now I have to press the spacebar or click it with my mouse to achieve the same. I don't know if this is intentional, but it wasn't very intuitive to me.

**Comment by kevin-brown** [comment]
Duplicate, explained at https://github.com/select2/select2/issues/3279#issuecomment-96450069.
