### ISSUE TITLE
Focus is lost when the change event is triggered

### ISSUE THREAD

**Issue by stretch4x4** [select2/select2#3332]
If a change event is triggered while a select2 has focus, the focus is lost meaning if a user was typing while the backend sent an update their typing will be lost and they will have to select the input again.
Example: https://jsfiddle.net/u0xja2wx/2/
If you enter a new tag and hit enter focus will be lost, comment out the change event and you can continue adding tags after you hit enter.
I believe this can be resolved in the Search.update function by checking if the search box has focus and restoring it at the end of the function if it did.

```js
var had_focus = this.$search.is(':focus');
// ...
if (had_focus) {
  this.$search.focus();
}
```

**Comment by chanchalkariwala** [comment]
Can you be more specific? 
This change would be in Search.prototype.update?

**Comment by stretch4x4** [comment]
Gday,




Yeah that is the general idea.




I submitted a pull request which should show you what I did:

https://github.com/stretch4x4/select2/commit/852715eccdc3f29435cab203e9a852e0e6706e2c




Hope that helps

**Comment by chanchalkariwala** [comment]
Yep, that worked! Thanks!
