### ISSUE TITLE
val of input on unselecting is empty before calculate width

### ISSUE THREAD

**Issue by Alxdhere** [select2/select2#3333]
select2 4.0 multiselect. Try edit tag by backspace, tag is removed and input with tag text is visible, but width of input = 0.75. Find error in line: var minimumWidth = this.$search.val().length + 1; evaluate with this.$search.val() = ''!
Temporary fix this bug by this code: $('#{id}').parent().find('input.select2-search__field').val(e.params.args.data.text); on event 'select2:unselecting'. But this is not good.
Please, fix this bug in source code.

**Comment by kevin-brown** [comment]
There is a duplicate of this somewhere, I'll close this off once I find it.

**Comment by rywall** [comment]
Dup of #3297

**Comment by kevin-brown** [comment]
> Dup of #3297

Thanks.
