### ISSUE TITLE
select class copy to span

### ISSUE THREAD

**Issue by Alxdhere** [select2/select2#3334]
I don't understand, class of select must be copied to span or not? For example, select with class 'form-control', but span have not class 'form-control' after $(...).select2();. Source code of Select2.prototype.render = function () { ... } have not functions to copy class from select.
Is this bug or feature?
P.S. Can't use select2-bootstrap.css without copy class.

**Comment by kevin-brown** [comment]
The recommended Bootstrap theme for 4.0.0 was created by @fk and is available at https://fk.github.io/select2-bootstrap-theme/.

> For example, select with class 'form-control', but span have not class 'form-control' after $(...).select2();.

You can have Select2 copy all of the classes over using `dropdownCssClass: ':all:'` and `containerCssClass: ':all:'` which are both undocumented but were added in https://github.com/select2/select2/commit/f3f1b31958fa585fadfe2eada3449826ce48224e.

> P.S. Can't use select2-bootstrap.css without copy class.

select2-bootstrap.css is no longer bundled with Select2 as of 4.0.0.

**Comment by Alxdhere** [comment]
Thanks!
