### ISSUE TITLE
Title attribute is set even though it wasn't present in the original <select>

### ISSUE THREAD

**Issue by lopis** [select2/select2#3336]
In my case, I'm using bootstrap's tooltip in every element with a title attribute. I found out that select2 adds a title to itself, seemingly using the default value of the original `<select>`. In consequence, all my select2s elements now unexpectedly popup a bootstrap tooltip on focus. I've been trying to figure out a way around this, but I might make a pull request with an option "title: false" in the plugin edit.

**Comment by kevin-brown** [comment]
There is at least two other duplicate tickets for this, I'll point you towards them when I find it.

**Comment by lopis** [comment]
Thanks, I searched but couldn't find any.

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/3158.
