### ISSUE TITLE
Add support back for locked options

### ISSUE THREAD

**Issue by pjclas** [select2/select2#3339]
Perhaps I am just confused about how to do this with the new select2, but I can't find a way to lock options like we could previously using the locked:true property.

**Comment by pjclas** [comment]
Is this support going to be added back?

**Comment by kevin-brown** [comment]
@pjclas Still deciding, it's not as high of a priority as other regressions.

**Comment by hez** [comment]
:+1:

**Comment by helloyou2012** [comment]
Expected this feature :+1:

**Comment by darbula** [comment]
:+1:

**Comment by Martii** [comment]
+1

**Comment by sjosen** [comment]
+1
Important feature IMO

**Comment by kb00k** [comment]
:+1:

**Comment by ybozhko** [comment]
:+1: very important for me as well. Just started updating from 3.5.x and realised that locked option is no longer there :cry:

**Comment by lagunawebdesign** [comment]
+1:
I'v been trying with data pass and select option attribute 'locked' but without any reslts. It should be automagic with option 'disabled'

**Comment by dszyrowski** [comment]
+1 would love to be able to use this feature in 4.0!

**Comment by TianqiZhang** [comment]
+1

**Comment by furqanaziz** [comment]
+1 Strongly Needed.

**Comment by NaWer** [comment]
+1
I need this :)

**Comment by NaWer** [comment]
+1
I need this :)

Current (dirty) hack :
```
/**
 * Fix unselecting select2 issue
 * Source : https://github.com/select2/select2/issues/3320
 *
 * Restore locked option
 * Issue : https://github.com/select2/select2/issues/3339
 */
$(document).on("select2:unselecting", 'select:not([multiple])', function (e)
{
	e.preventDefault();
	if ($(e.params.args.data.element).attr('locked'))
		return false;
	$(this).val('').trigger("change");
	$(this).select2('val', '');
});
$(document).on("select2:selecting", 'select:not([multiple])', function (e)
{
	if ($(e.target).find(":selected").attr('locked'))
		return false;
});
$(document).on('select2:unselecting', 'select[multiple]', function(e)
{
	$(e.target).data('unselecting', true);
	if ($(e.params.args.data.element).attr('locked'))
		return false;

}).on('select2:open', function(e)
{
	var $target = $(e.target);
	if ($target.data('unselecting'))
	{
		$target.removeData('unselecting');
		$target.select2('close');
	}
});
```

**Comment by TianqiZhang** [comment]
+1 really need this

**Comment by jymbob** [comment]
+1 blocker to migration here.
Also putting something in the 'deprecations' section of the docs would have saved me (and potentially others) a lot of time.

**Comment by kevin-brown** [comment]
For what it's worth, this didn't make the cut initially because it's not natively supported by `<select>` boxes. With that being said, you should be able to add support for this through an adapter (or by catching the events and rejecting them).

**Comment by ryakoviv** [comment]
Chekc my solution on stackoverflow https://stackoverflow.com/a/48111387/7413612

**Comment by nickitatkach** [comment]
+1

**Comment by Martii** [comment]
Still looking for this. This dep hasn't been migrated on our end as it's security related to keep the lock ability in.

**Comment by Martii** [comment]
\*ahem\*

**Comment by kevin-brown** [comment]
This still remains on the backlog as a low priority item. Given the current focus in fixing bugs, I would not expect this to be added natively any time soon.

**Comment by etipton** [comment]
Just noting that I'd find this very useful as well

**Comment by Martii** [comment]
:(

---

For those of you using the confused reaction the bot closed this issue as stale which means I'm disappointed.

**Comment by PoojaDevram** [comment]
+1 Need this option.

**Comment by francisco-laborda-lenio** [comment]
+1, please consider prioritizing this :)

**Comment by smileBeda** [comment]
+1 it makes no sense to remove this feature. Would be great to have it back.

**Comment by Gildedter** [comment]
> Check my solution on stackoverflow https://stackoverflow.com/a/48111387/7413612

Only works when its on markup, I have an array data  source, I can't apply your fix, please help...

Edit 1: I fixed it
```
// on api data get
const isSelected = item.id === data.id;
const mapped = {
id: item.id,
text: item.name,
selected: isSelected,
locked: isSelected,
};

// event bind after select2 init
$("#mySelect").on('select2:unselecting', function (e) {
  if (e.params.args.data.locked) {
    e.preventDefault(); // stops default behavior of unselect button click
  }
});
```
my only issue now is, I don't know how to hide the 'x' button appended on the selections

**Comment by mmokross** [comment]
Please bring that option back! 👍 It's really necessary!

**Comment by jonaul** [comment]
Bring that option back please!!!!! It is useful and it was already developed in version 3.5. Why remove it?
