### ISSUE TITLE
formatSelectionTooBig missing in 4.0?

### ISSUE THREAD

**Issue by pjclas** [select2/select2#3340]
Is there a ways to override the default text when a user has reached their max selectable options for a multi-select box?

**Comment by kevin-brown** [comment]
Noted in [the release notes](https://github.com/select2/select2/releases/tag/4.0.0-beta.1), the formatters were moved to the `language` option.

```js
{
  language: {
    maximumSelected: function () {
      return 'You can't select any more.';
    }
  }
}
```
