### ISSUE TITLE
`templateResult` when searching

### ISSUE THREAD

**Issue by browner12** [select2/select2#3342]
upon upgrading to v4, when I was doing remote data select boxes, i kept getting an undefined while I was typing my search, and waiting for results. after removing my custom selection templating, i figured out this was the "searching" text that is shown while waiting for results. after hunting through the source code on the example page, I found this conditional check

``` javascript
function formatRepo (repo) {
    if (repo.loading) return repo.text;
```

IMHO, the loading/searching is not really a part of your results, and shouldn't be formatted according to my custom function. ideally the package would display the 'Searching...' text for me, and then display my templated results when they are found.

while i think it would be best to work this way, if the current implementation is the intended way to work, i think it would be very beneficial to put a note in the templating section, to include this conditional check in any custom templating, so other users don't run in the confusing "undefined" that I ran into.

**Comment by derekm** [comment]
While you're improving templating docs, notice that the "templateSelection" function signature is documented twice (under "Customizing the display of results"): https://select2.github.io/options.html#templating

**Comment by alexweissman** [comment]
This is now explained in the new docs: https://select2.org/dropdown#built-in-escaping
