### ISSUE TITLE
minimumInputLength message is not hidden until results are returned

### ISSUE THREAD

**Issue by Alxdhere** [select2/select2#3343]
There are help message like "Please enter 3 or more characters" for minimumInputLength=3. This is good. But if enter more than 3 characters, message not hide or not changes and show "Please enter 1 or more characters". Why? Is this bug?
![help message](http://alxd.it-dept.ru/images/select2-bug-02.png)

**Comment by kevin-brown** [comment]
What version of Select2? And can you reproduce this in a jsfiddle or link to a page where it can be checked out?

**Comment by Alxdhere** [comment]
select2 4.0.0
Difficult reproduce code in jsfiddle with ajax request. I use yii extension to create select2:
```php
$this->widget('ext.AlxdSelect2.AlxdSelect2', array(
        'name'=>'Organization[search]',
        'value'=>'',
        'data'=>array(),
        'htmlOptions'=>array(
            'class'=>'form-control',
            'select2Options'=>array(
                'language'=>Yii::app()->language,
                'placeholder'=>Yii::t('Organization','Search'),
                'ajax'=>array(
                    'url'=>Yii::app()->createUrl('organization/searchcriteria', array('organization_id'=>$organization->id)),
                    'dataType'=>'json',
                    'delay'=>250,
                    'data'=>"js:function(params) {return {term: params.term, page: params.page, pagesize: 10};}",
                    'processResults'=>"js:function(data, params) {
                        var more = true,
                            terms = params.term.split(':'),
                            items = data.items;
                        if (terms.length == 1)
                            items.splice(0,0,{id: 'Custom:0', text: params.term, type: 'Custom'});
                        else
                            items.splice(0,0,{id: 'Custom:0', text: terms[1], type: 'Custom', attribute: terms[0].trim()});
                        return {results: items, more: more};
                    }"
                ),
                'minimumInputLength'=>3,
                'multiple'=>true,
                'openOnEnter'=>false,
                'templateSelection'=>'js:templateSelection',
                'templateResult'=>'js:templateResult',
                'theme'=>'bootstrap'
            )
        ),
    ));
```
May be this code help you.

**Comment by Zxurian** [comment]
This is also demonstrated by the AJAX remote example on the select2 examples page. Typing more than one character triggers the "Searching..." message to display, but does not get rid of the "Please enter 1 more character" message.

**Comment by nickmccally** [comment]
Kevin, the issue is resolved for me in IE but for some reason in chrome it is still showing the "please enter 1 more character"

**Comment by nickmccally** [comment]
Update - Kevin have you recompiled the package? I made the manual changes but downloading the package from github does not have the updates.

**Comment by kevin-brown** [comment]
> Kevin have you recompiled the package?

Nope, you're going to need to do that yourself if you want to get the changes before the next release.

**Comment by moorthysmart** [comment]
formatInputTooShort: function (term, minimumInputLength) {
        return ""; 
      },
used this instead 


  AJS.$($selectId).auiSelect2({
    	placeholder: "Search User",
    	minimumInputLength: 1,
      multiple: true,
      separator: ',',
      formatInputTooShort: function (term, minimumInputLength) {
        return ""; 
      },
