### ISSUE TITLE
closeOnBlur

### ISSUE THREAD

**Issue by alimoosavi15** [select2/select2#3344]
Add the option closeOnBlur similar to closeOnSelect to prevent default closing on blur.

**Comment by kevin-brown** [comment]
You can call `preventDefault` on `select2:closing` if you are interested in preventing Select2 from closing by default. For UX reasons, this won't be integrated in the Select2 core.

**Comment by alimoosavi15** [comment]
Thanks for the reply. I tried that but it will prevent all closings including closing after choosing options. Do you have a solution to preventDefault on blur only ? the closing event object doesn't seem to have information about the original event.
