### ISSUE TITLE
CSS overrides for WordPress

### ISSUE THREAD

**Issue by bseddon** [select2/select2#3345]
This plugin is a really great way to present list selections.  However when used in the WordPress backend there are CSS conflicts which makes the presentation of the input line not as clean as users see on your examples page.  There are seven style changes needed and center on the searchfield.

I will be happy to share the changes I have made in case they will be helpful to others who, in turn, may be able show me how to improve them.  These CSS examples may be useful to other people who are trying to use select2 in the admin side of a WordPress plugin.

**Comment by kevin-brown** [comment]
> However when used in the WordPress backend there are CSS conflicts which makes the presentation of the input line not as clean as users see on your examples page.

Do you have some screenshots that you might be able to provide?

> I will be happy to share the changes I have made in case they will be helpful to others who, in turn, may be able show me how to improve them.

That would be great, we might be able to integrate some of them into the standard reset CSS that Select2 uses.

**Comment by bseddon** [comment]
Here's an image to illustrate the issue.  You can see how it is supposed to appear based on the default select2 styling.  Then how select2 can appear in WordPress with just a few styling tweaks.  Finally, how select2 is presented in WordPress without any style overrides.

![image](https://cloud.githubusercontent.com/assets/1221824/7591461/e51b22c4-f8c5-11e4-919e-af43cc1dfe61.png)

The style conflicts occur with definitions in ./wp-admin/css/common.css (this is a standard path in WordPress hosted site).

You can see the WordPress styling gives the searchfield a shadow.  It also obscures the caret because the standard select2 searchfield width of 0.75em is taken up with padding specified by WordPress.  Finally the field is styled to occupy the smallest space it possibly can.  In a WordPress backend select2 is going to be used in a WordPress metabox or WPList table where it can expect to be allowed to occupy the available horizontal space.

Here are my modifications to the select2 styling.  You will see that I've used !important in several places.  I recognize this is undesirable.  With some time to learn more about the plugin or to workout style selectors that provide more specificity than the WordPress selectors it may be possible to remove the reliance on !important.  For example,, the important directive is used on .select2-container style because the plugin sets an explicit width on the element.  Maybe this style can be passed as a parameter.  My learning about select2 is not yet sufficiently advanced to know if this is possible.

In any case, in my view the most important change is the one to the styling of the search field.
`
.select2-container {
	width: 100% !important;
}

.select2-selection--multiple {
	border-color: #ddd !important;
}

.select2-container--default .select2-selection--multiple {
    height: auto;
}

.select2-selection__rendered {
	line-height: 1.8em !important;
	font-size: 15px !important;
}

.select2-selection__rendered {
  margin-bottom: -5px !important;
}
  
input[type="search"].select2-search__field {
	border: 0px;
	box-shadow: inset 0 0px 2px rgba( 0, 0, 0, 0 );
	padding: 5px 0 0 0;
	-webkit-box-shadow: inset 0 0px 2px rgba( 0, 0, 0, 0 );
	-webkit-appearance: searchfield;
	width: auto !important;
}
