### ISSUE TITLE
Image not showing on selected option

### ISSUE THREAD

**Issue by cracea** [select2/select2#3351]
Hello .
The option image is not shown when selected .
Is there any options i have missed ?

http://static.md/68cfcb316cd5426f630839899108fede#
http://static.md/ead0b417fecea59ceda6c47a900264af#

  $(".class").select2({
    minimumResultsForSearch: Infinity,
    templateResult: formatState,
    formatSelection: formatState
  });  

 
Thank you .

**Comment by kevin-brown** [comment]
`templateSelection`, not `formatSelection`.
