### ISSUE TITLE
4.0.0: How to set initial values in selec2 (ajax, multiple) with possibility to remove it

### ISSUE THREAD

**Issue by prophe05** [select2/select2#3353]
When I set initial value with custom data adapter (extends AjaxAdapter) all looks pretty well, but then I can't to remove this initial value.

Try to delete, add new items...    http://jsfiddle.net/jgu02xLk/4/

**Comment by prophe05** [comment]
My solution is to extend current and unselect methods of super class. When user unselect item remove it from initial values array...

http://jsfiddle.net/jgu02xLk/7/

**Comment by kevin-brown** [comment]
> When I set initial value with custom data adapter (extends AjaxAdapter) all looks pretty well, but then I can't to remove this initial value.

The issue there is that with `current`, you are supposed to return the _currently selected values_. You were always returning the same array, so the options never appeared to be removed. The [`initSelection` compatibility decorator](https://github.com/select2/select2/blob/dd9af6893450bbb054ca79546a16bb18198f3e88/src/js/select2/compat/initSelection.js) shows how we only use `initSelection` on the first call to `current`, and then rely on the original adapter for the rest.
