### ISSUE TITLE
select2 buzz in IE10

### ISSUE THREAD

**Issue by Alxdhere** [select2/select2#3356]
select2 4.0.0
Form with few inputs. Two inputs are select2 4.0.0 with ajax data and multiselect. Open form in Chrome - all ok! Open this form in IE 10 and form is buzz. Focus in first select2, but must be in simple first input. Focused select2 show search result and I can't focus out from it. Can't select other input on form. I can only close browser tab with this form.
To understand this bug you need a video!

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/3257 and probably another ticket.

> To understand this bug you need a video!

It's true!

**Comment by Alxdhere** [comment]
I capture a [video](http://alxd.it-dept.ru/download/select2-bug-ie10.mp4) for you!
There are not this bug in IE11.
Hope this help.

**Comment by Alxdhere** [comment]
Bug with multiselect reproduce on select2 site in IE10:
![Bug](http://alxd.it-dept.ru/download/select2-bug-ie10.png)
