### ISSUE TITLE
Init_options documentation was written with malice

### ISSUE THREAD

**Issue by Nekmo** [select2/select2#3358]
I wear an hour trying to figure out why this is not working*:

    def init_options(self):
        self.options['createSearchChoice'] = 'Your_js_function'

* http://django-select2.readthedocs.org/en/latest/ref_widgets.html#django_select2.widgets.Select2Mixin.init_options

This documentation is a lie. According to that, putting a function in that way should work. In fact, in order for the function to work, you must put it this way:

        def init_options(self):
            self.options['createSearchChoice'] = '*START*Your_js_function*END*'

createSearchChoice should always be a function. In the example, a string is returned.

Sorry, I have the crystal ball in the workshop to read the Select2 documentation.

**Comment by kevin-brown** [comment]
This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

https://github.com/applegrew/django-select2

[ml]: https://github.com/ivaynberg/select2#mailing-list

**Comment by Nekmo** [comment]
Sorry, I was wrong window.
