### ISSUE TITLE
Using tabs as tokenSeparators for tags 

### ISSUE THREAD

**Issue by doctorallen** [select2/select2#3359]
I've tried so many different things to try and get select2 to allow for the tab key as a token separator to start a new tag, to no avail. Does anyone know how to do this?

**Comment by mofman** [comment]
+1

**Comment by Kaldrax** [comment]
+1
Right now Tab even deletes the input which really sucks.

**Comment by Hemanth089** [comment]
+1

**Comment by superKalo** [comment]
+1
Would be very useful!

**Comment by doctorallen** [comment]
I hate to mention this here, but for those of you that need this feature, you may want to look at [selectize](https://brianreavis.github.io/selectize.js/).

**Comment by althaus** [comment]
+1

**Comment by grantgeorge** [comment]
+1

**Comment by simsketch** [comment]
+1

**Comment by sampatbadhe** [comment]
:+1:

**Comment by sanosay** [comment]
(Y)

**Comment by andreasba** [comment]
Hello there,

I really like select2 to thanks a lot for the great work @kevin-brown !

Now I am a bit confused about the status of this issue - is it closed and resolved or just closed? It would be great to have a solution to this.

Thanks
Andreas

**Comment by rycwilson** [comment]
+1

**Comment by griesi007** [comment]
+1

**Comment by gbeauvoir** [comment]
+1
Add also ENTER key press

**Comment by bbotella** [comment]
+1

**Comment by Atyz** [comment]
+1

**Comment by kcivey** [comment]
:+1:

**Comment by anhtuank7c** [comment]
:+1:

**Comment by cireficc** [comment]
👍

**Comment by knightq** [comment]
👍 Any new?

**Comment by davilious** [comment]
I sent a pull request a few weeks ago, I don't know yet whether or not it will be included in future versions. For those of you interested, here the [PR](https://github.com/select2/select2/pull/4325)

**Comment by carldanley** [comment]
:+1:

**Comment by LuciusCaesar** [comment]
+1

**Comment by bkroeker** [comment]
+1

**Comment by DiesIrae** [comment]
And Enter, pleeease! :-)

**Comment by jaketoolson** [comment]
Just found this, hoping its still relevant.

**Comment by jransegnola** [comment]
+1 to this.

Was just trying to find my own way around this.

**Comment by jeremy-hunter** [comment]
kevin-brown's solution worked for me:
https://github.com/select2/select2/pull/4325#issuecomment-229234605
selectOnClose creates the tag on both tab and enter

**Comment by pptyasar** [comment]
+1

**Comment by alexweissman** [comment]
Everyone, please avoid any additional "+1" comments.  Simply click the 👍 on the first comment.

The issue here is that `tab` is typically used to change element focus in an HTML form.  This would have to be implemented as a configurable option, rather than a default behavior.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:

**Comment by stahor** [comment]
@pedrofurtado potentially this can fix an issue https://github.com/select2/select2/pull/4795

**Comment by denodster** [comment]
@pedrofurtado @stahor I've finished the changes at #4795 and I hope someone can take a look soon, its a really old PR so I'm trying to make some noise around it in the hope that it gets noticed.

**Comment by GigaMick** [comment]
I'd really like the "return" key to create a new tag too.
