### ISSUE TITLE
select2 in firefox In the script no response

### ISSUE THREAD

**Issue by ccefeg** [select2/select2#3360]
In firefox,one-time init select2 too much ,It can cause the script no response.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/ivaynberg/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by ccefeg** [comment]
OK,Thank you.
* In the process of loading the initial page in.
* The bug is the page caton, suspended animation and the expected outcome is init the page successfully, no caton or feign death.
* The System is windows 7(64bit) and This only happened in Firefox(37),Others such as chrome, IE (9+) is normal.
* The jQuery version is 1.11.1 and the Select2 version is 4.0.0-rc.2.
* The use of other plugins, but I have only tested select2, the bug is still happen.

**Comment by ccefeg** [comment]
Do you find this bug?

**Comment by kevin-brown** [comment]
@ccefeg Nope, we weren't able to reproduce this.

If you can build out a jsbin/jsfiddle that reproduces this issue with 4.0.0 or the latest master, that would be useful.

**Comment by ccefeg** [comment]
This URL is the example
http://jsfiddle.net/ccefeg/tpfh4gmw/2/

**Comment by alexweissman** [comment]
Not really sure what the problem is here.
