### ISSUE TITLE
Accessing element from the ajax.data callback function

### ISSUE THREAD

**Issue by SilverFire** [select2/select2#3361]
Using Select2 v.3.5, ajax.data callback function had `this`, pointing to the element, so i was able to get it's properties. In Select2 v.4, `this` points to the ajax configuration object, so I have no access to the element.

This does not work anymore:

```js
$('select').select2({
  ajax: {
    url: 'example.com',
    data: function (param) {
      console.log(param, this);
      return {results: {
        q: param.term,
        module: $(this).data('module')
      }};
    }
  }
});
```

You can see it on the [jsbin](http://jsbin.com/cuzaxe/6/)

How can I access element from `ajax.data` callback function?

**Comment by penihel** [comment]
I have the same problem

**Comment by penihel** [comment]
I did this temporarily workaround:

```javascript
var opts = {
  element: $('#s1'),
  ajax: {
    url: 'example.com',
    data: function (param) {
      console.log(param, this);
      return {results: {
        q: param.term,
        module: $(this).element.data('module')
      }};
    }
  }
};
$('#s1').select2(opts);
```

See the aditional line **"element: $('#s1'),"**

**Comment by SilverFire** [comment]
I have tried this before I posted this issue. I use Select2 as a part of my plugin. The element contains the options storeage, instance of which is stored in `data`. 

If I use this crutch, the recursive link relation appears: the element has a config, which points back on the element with config and so on. This breaks a deep copy of the element with jQuery `$.extend`, which is called when plugin initializes.

Don't remember exec line, but it's [here](https://github.com/select2/select2/blob/a993ed9ca9b2d47804f2ac4dec3358b88e54dca7/src/js/select2/options.js#L94) or [here](https://github.com/select2/select2/blob/a993ed9ca9b2d47804f2ac4dec3358b88e54dca7/src/js/jquery.select2.js#L20)

**Comment by penihel** [comment]
Fixing...
```javascript
var opts = {
  ajax: {
    url: 'example.com',
    element: $('#s1'),
    data: function (param) {
      console.log(param, this);
      return {results: {
        q: param.term,
        module: $(this.element).data('module')
      }};
    }
  }
};
$('#s1').select2(opts);
```

**Comment by kevin-brown** [comment]
I wouldn't mind seeing a pull request coming in that fixes this regression. We used to `.call` it [with `this` set to the element](https://github.com/select2/select2/blob/2eea4a486a8d3d34c87cf53cb3a69fb7aa21ff48/select2.js#L425), which [should work just well in Select2 4.0.0](https://github.com/select2/select2/blob/bd6148e39f753ed2880f674a90b42ffe446b893a/src/js/select2/data/ajax.js#L64).

The same should be done to `ajax.url` as well.

**Comment by SilverFire** [comment]
@kevin-brown Ok, I'll send a pull-request.

> Fairly certain it's the second one you referenced. We clone the options so there aren't issues when Select2 is initialized on multiple elements at once.
[Here](http://jsbin.com/cuzaxe/8/) is an example, when deep copy gives a JS error `Maximum call stack size exceeded`.

**Comment by SilverFire** [comment]
@kevin-brown pull request #3410

**Comment by SilverFire** [comment]
@kevin-brown ready to merge

**Comment by SilverFire** [comment]
:up:
