### ISSUE TITLE
Unable to assign a placeholder for the search field

### ISSUE THREAD

**Issue by maxwellj** [select2/select2#3362]
There is a option to add a placeholder for the select field but not for the search field.
It would be nice to be able to have a option to add a placeholder for the 'search' input field.

**Comment by njakobsen** [comment]
+1

**Comment by KevinSchuck** [comment]
+1

**Comment by ttucker** [comment]
+100! Is that possible?

**Comment by austencm** [comment]
+1

**Comment by npapazian** [comment]
+1

**Comment by emielroelofsen** [comment]
+1

**Comment by ohenrik** [comment]
+1

**Comment by nistic** [comment]
+1

**Comment by FutureKode** [comment]
+1

**Comment by StephaneJuban** [comment]
+1

**Comment by chivorotkiv** [comment]
+1.

Btw. While it's not implemented I'm using following workaround:

```js
selectElement.on('select2-open', function() {
    $('.select2-input').attr('placeholder', 'Start typing to find');
});
selectElement.on("select2-close", function() {
    $('.select2-input').attr('placeholder', null);
});
```

**Comment by KevP** [comment]
+1

**Comment by caseahr** [comment]
The reason this would be quite useful is that if I am filtering the list on multiple properties (e.g., name OR phone number OR email) I could add a placeholder to help the user -- "_Search by customer name, phone number, or email_"

**Comment by orioljd** [comment]
@KevP I used your solution but if I had a multiple select too the text "S" of "Search..." appears on it

**Comment by hoffmanilya** [comment]
+1

**Comment by vinothjayaraman** [comment]
+1

**Comment by librisius** [comment]
+1

**Comment by Mattomanka** [comment]
+1

**Comment by dylankerr-bis** [comment]
There seems to be an un-documented option (at least in version 3.5.4) called searchInputPlaceholder that provides this functionality.

**Comment by seltix5** [comment]
The option searchInputPlaceholder no longer work on the current version :(

**Comment by martinkrcho** [comment]
Is there a plan to put this option back in. It would be handy.

**Comment by andreivictor** [comment]
I've created a small extension in order to implement 'searchInputPlaceholder' option.
The code and demo is available here:
http://jsfiddle.net/bvja1ktv/

**Comment by alexweissman** [comment]
This is great!  Would you be willing to set this up in a dedicated repo?

**Comment by andreivictor** [comment]
@alexweissman, I've created a small repository for this extension:
https://github.com/andreivictor/select2-searchInputPlaceholder

**Comment by alexweissman** [comment]
Nice!  Looks good.  You should also be able to use the new "topics" feature to label your repo with "select2" as well.

**Comment by KyleMit** [comment]
@KevP / @orioljd  - Two Notes
1. This will set the placeholder for *all* controls as soon as one is opened. Probably fine, but it's an odd place to add that kind of initialization for everything inside of the handler for a specific one.

2. More importantly this breaks in most versions of IE if you need to support them per #3300 & #3257

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:
