### ISSUE TITLE
Select2 v4 is not responsive at all and thus breaks every variable-width layout

### ISSUE THREAD

**Issue by cerlestes** [select2/select2#3363]
**Abstract**
The newest version of Select2 sets a fixed width on its container. This breaks about every page its used on in every browser when resizing the parent element(s), even the official example page:
![Example](http://i.imgur.com/QkAIqvF.png)

**Steps to reproduce**
  1. Open page with variable width and Select2
  2. Resize browser window
  3. Select2 container remains at old fixed width

**Possible solution**
EDIT: Set the default value for the 'width' option to NULL in order to prevent Select2 from applying a fixed width to the container by default. This is neither needed nor wanted in most cases.
~~Remove the _resolveWidth() method all together and have the Select2 container retain its ```width:auto;``` value. There's no need for setting an arbitrary width to an element that does not require one. 
Optionally set the container to ```display:block;``` by default, so it scales to full width.~~

**Comment by cerlestes** [comment]
See #3370

**Comment by cerlestes** [comment]
See #3371 for a pull-request.

**Comment by kevin-brown** [comment]
Merging into https://github.com/select2/select2/issues/3278.

**Comment by joetidee** [comment]
This is still hapenign in v4.0.3

**Comment by liamrathke** [comment]
Happening for me in v4.0.6 as well
