### ISSUE TITLE
AjaxAdapter incorrectly calls ArrayAdapter.__super__.constructor

### ISSUE THREAD

**Issue by vyrotek** [select2/select2#3365]
https://github.com/select2/select2/blob/master/src/js/select2/data/ajax.js

Line 13 here seems to incorrectly call "**ArrayAdapter**.__ super __ .constructor". 
It should instead call "**AjaxAdapter**.__ super __ .constructor".

Otherwise you cannot initialize the dropdown it with the data option.

**Comment by kevin-brown** [comment]
Want to create a pull request for this? I'm fairly certain this won't make a noticeable difference, because Select2 pulls the results using AJAX instead of from `data`, but it is still a (lower priority) issue.

**Comment by vyrotek** [comment]
We are trying to upgrade from a much older version of Select2 and we need to be able to pre-set a selected option on load of the page via javascript. If the user wants to change what the selected option is then those options are loaded via the ajax call once it is expanded.

Currently our page is only aware of the "ID" value of the option that needs to be selected (e.g User.ID).  In our current code we are able to make Select2 perform an ajax "query" given only that ID and it is able to retrieve the full option object containing "Text" value (e.g. User.Name) and have it be the default selected option. This was done using the now deprecated *initSelection* function.

We're exploring our options but we don't think we can do this in v4.0 without the *data* option being available. We are also not able to pre-set the options using an html option element because we also need to add custom data values on each option. It doesn't look like anything we add to the option html via data-* attributes are accessible when change events are fired.

This is actually blocking us right now so we had to write our own adapter. I will see what I can do.

**Comment by penihel** [comment]
I have exactly the same problem. See #3116

**Comment by vyrotek** [comment]
Indeed! Your [last comment](https://github.com/select2/select2/issues/3116#issuecomment-102119431) expressed the exact scenario we're also trying to solve. It used to be so simple!

**Comment by vyrotek** [comment]
Pull request submitted #3375

**Comment by kevin-brown** [comment]
Closed by https://github.com/select2/select2/pull/3375.

**Comment by penihel** [comment]
See http://jsfiddle.net/s8s2ho28/17/
