### ISSUE TITLE
dropdown position is not updated correctly when multiselect closeOnSelect : false   

### ISSUE THREAD

**Issue by inieves** [select2/select2#3373]
For a multiselect... when several options are selected, the multiselect must sometimes vertically expand to 2 or more rows.  When the multiselect expands to be more than one row, the position of the dropdown (which has not yet closed, because closeOnSelect:false) is not updated.  Because the position has not updated, the dropdown starts to cover the list of selected options.

Here is a super simple example.  Try this out yourself.
Just select a bunch of options to make the multiselect itself expand, and notice that the dropdown only updates _after_ your scroll around outside the multiselect.

```
<html>
    <head>
        <link href="http://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
        <script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
    </head>

    <body>
        <select class="js-example-basic-multiple" multiple="multiple" style="width: 400px;">
            <option value="AL1">Alabama 12345</option>
            <option value="AL2">Alabama 12345</option>
            <option value="AL3">Alabama 12345</option>
            <option value="AL4">Alabama 12345</option>
            <option value="AL5">Alabama 12345</option>
            <option value="AL6">Alabama 12345</option>
            <option value="AL7">Alabama 12345</option>
            <option value="AL8">Alabama 12345</option>
        </select>   
        <script>
            $(".js-example-basic-multiple").select2({closeOnSelect: false});
        </script>
    </body>
</html>
```

**Comment by kevin-brown** [comment]
This has to do with the fact that the `close` event is not triggered, and we don't position the container on the `select`/`unselect` event.

You can also reproduce this issue by selecting the option while having the CTRL key held, as that behaves the same way as `closeOnSelect: false`.

**Comment by inieves** [comment]
is there a workaround that I could easily implement in the JS?

**Comment by yukulelix** [comment]
@inieves I did it this way, disabling the option closeOnSelect!
Hope it helps !
```javascript
$select.on("select2:select", function (e) {
    $select.select2("open");
});
```

**Comment by inieves** [comment]
Awesome Félix!! I will try this tonight or tomorrow!

-ian

**Comment by tanloverluke** [comment]
this works great thanks, but in my case this workaround only works when closeOnSelect is NOT set to false.

**Comment by aillusions** [comment]
In our case we using 'select2:close' event so closing and opening each time did not work well..
So solution was firing window scroll event after each selection, which eventually makes select2 re-render itself with correct location

```
$select.on("select2:select", function (e) {
     $(window).scroll();
});
```

**Comment by alexweissman** [comment]
Please continue discussion of this issue in #4377.
