### ISSUE TITLE
select2 minimuminputlength doesn't work with input tag

### ISSUE THREAD

**Issue by eabrahamyan** [select2/select2#3374]
I'm using select2 v4 full version. In my select2 options I have 
<input class="selec2"/>
select2: { data:myData,minimuminputlength:2} and it still shows all the records.

It works fine when with <select> tag. in my case I can't use select tag because i use third party plugin that uses select2 with input tag.

thank you in advance

**Comment by kevin-brown** [comment]
Can you create a jsfiddle that reproduces this?

**Comment by eabrahamyan** [comment]
https://jsfiddle.net/4g0c6Lae/

**Comment by kevin-brown** [comment]
Yup, looks like the issue is that Select2 applies the compatibility decorator for `<input />` too late, so the `MinimumInputLength` decorator never actually gets triggered.

**Comment by lacco** [comment]
It's a pitty that this is not working for `<input>`, as the performance is much better than use normal `<select>`. That is why I monkey-patched some code to be able to limit the number of results:

```
  maxResults = 200

  inputData = $.fn.select2.amd.require('select2/compat/inputData')

  oldQuery = inputData::query
  inputData::query = (decorated, params, callback) ->
    newCallback = (data) -> callback({ results: data.results.slice(0, maxResults) })
    oldQuery.call(this, decorated, params, newCallback)
```

Of course, I would prefer using `minimuminputlength`, but for my application this patch is worth the perfomance gain...
