### ISSUE TITLE
data is not working

### ISSUE THREAD

**Issue by ajkosh** [select2/select2#3378]
this code is giving me undefined data
     var theID = $(this).select2('data').id;
alert(theID);
it is showing undefined

**Comment by penihel** [comment]
this method was deprecated in version 4
use:
```javascript
var theID = $(this).val();
```

**Comment by snichini** [comment]
to see the error while working with the 4.0.
Use the debug option
```javascript
$(this).select2({debug:true});
```
In the console you will see the warning / debug log of all your select2

**Comment by kevin-brown** [comment]
You appear to be only trying to get the selected value (which is the `id`), so you're better off using `.val()` like you would with a standard `<select>`.

> this method was deprecated in version 4

While it's true that this was deprecated in 4.0.0, it is only deprecated if you are _setting the data_ using `.select2('data', newData)`.

> this code is giving me undefined data

The return value of `select2('data')` was changed in 4.0.0, so now it returns a list of selected options, giving a consistent return value across both single and multiple selects.

**Comment by ajkosh** [comment]
@penihel @kevin-brown @snichini  one more error is coming i dont not why it is comming,is it bug or not?
i attached screenshot.
when i select something from select2 and remove selected element and again selecting then i m getting this error.
![screenshot from 2015-05-26 09 59 39](https://cloud.githubusercontent.com/assets/8582472/7805339/f9d0b99a-038d-11e5-8685-1b4dbe695e7f.png)

**Comment by kevin-brown** [comment]
> is it bug or not?

Possibly, but there isn't much that can be done without seeing the full traceback there. And possibly a list of step-by-step instructions for reproducing it on the examples page.
