### ISSUE TITLE
Select2 and FastClick incompatibility

### ISSUE THREAD

**Issue by ibarral** [select2/select2#3381]
Hello,

Is there any way to make it work with Select2 4.0.0?

I've read that I need to wrap every selection item on a "needsclick" class, but I don't know how to make it work.

Thanks!

**Comment by kevin-brown** [comment]
Merging this into https://github.com/select2/select2/issues/3222.

**Comment by rlau89** [comment]
Do not use fastclick with select2, it stops the ability to select any items or close when selecting other areas
