### ISSUE TITLE
Z-index issue

### ISSUE THREAD

**Issue by sshadow2** [select2/select2#3388]
I have a select2 dropdown in a popup modal that has an explicitly set z-index of 5000. 
in select2 v4, the select2-container that wraps the select2-dropdown is injected as the last element of the body tag and flows with the normal page layering. I have to manually set the z-index of select2-container to 5000. Otherwise, the dropdown appears behind the modal.

I didn't need this for v3. Adding a currentStyles/getComputedStyles function should make this automated.

**Comment by kevin-brown** [comment]
Part of this was because the z-indexes in Select2 3.x were _incredibly high_. Like higher than everything else on the page, and 99% of components out there.

**Comment by jeessy2** [comment]
so, It's can't be change?

**Comment by kevin-brown** [comment]
You can manually override this in your CSS

```css
.select2-dropdown {
  z-index: 9001;
}
```

**Comment by Agimovel** [comment]
Hi guys, but theres a problem with above solution: if you have 2 modals opened, the fields of first modal will appear over the current modal.

It will also create some problems, if you scroll fields and use navbar, it will appear over navbar. 

Is there any other way? For example, detect current modal and only apply this css to the openned modal?

**Comment by Agimovel** [comment]
The solution: 

.select2-container--open{
        z-index:9999999         
    }

**Comment by anibabbar** [comment]
@Agimovel  !! Works Perfectly !! 

Thanks

**Comment by mvkanha** [comment]
Remove tabindex from modal

**Comment by mahdisys** [comment]
trigger the select list when it's open it is a great solution .
I have two element using the select2 an I don't want to change both z-index .
thanks save alot of time.
