### ISSUE TITLE
Events not being removed on destroy

### ISSUE THREAD

**Issue by JGuymer** [select2/select2#3390]
Hi

I have a senario where i need to create a new select when a button is pressed and destroy it when its updated. The change fires a call to the server via the .on("select2:select"..... 

if i toggle the button a number twice the event fires twice, three times and so on

to get round it ive added the following to get round it for now

   $('#taskdetails_taskfor').select2().unbind();
   $('#taskdetails_taskfor').select2('destroy');

Cheers

James

**Comment by kevin-brown** [comment]
It sounds like you are saying that `select2:` prefixed events are not removed when Select2 is destroyed. This would make sense, because Select2 doesn't not bind these events (it only triggers them), so Select2 will not unbind them.

**Comment by tyburczyk** [comment]
'change' event is also not unbinded

**Comment by kevin-brown** [comment]
@tyburczyk the event should be unbound [on this line, after calling `select2('destroy')`](https://github.com/select2/select2/blob/bc1996417041d9b6131bd8c2ba911984c7b6f2d9/src/js/select2/core.js#L507) because it is registered under the `select2` namespace.
