### ISSUE TITLE
select2:unselect fires when selecting the same value in dropdown

### ISSUE THREAD

**Issue by JGuymer** [select2/select2#3391]
Hi 

Im using select2 v4 in multiple mode with ajax call. on selecting a  value from the dropdown will cause the select2 to hide(this is by design). If then click the button that creates a select 2 tags list for me to edit, click into the text box and select the "same value" then the select2:unselect is fired and it removes my first tag. 

Im not sure if this is by design or a bug. 

Cheers

James

**Comment by snichini** [comment]
I think it's a wanted behavior.
Maybe an option to enable / disabled this feature would be nice

Like 
```javascript
$(this).select2({
unselect:false
});
```

**Comment by kevin-brown** [comment]
> Im not sure if this is by design or a bug.

This is by design, mostly for accessibility reasons but also because Select2 visually styles already-selected elements.
