### ISSUE TITLE
Tag Support

### ISSUE THREAD

**Issue by levisk** [select2/select2#3392]
I would like to add 'tags' through user input, but it needs to obey a certain criteria.
In the case i developed, the user must place the text in this format 99/99 ( day / month )

It works ok if the user only press 'Enter' to add in the list, but if he uses "," and the text doesnt meet the criteria.. i can't Cancel.

There is the example:
http://jsfiddle.net/3qkgagwk/24/

You can type the condition and see it working.
To reproduce the problem just press "," it looks like he will add something no matter what.

I've tried to remove the  "else" condition, but it gives a javascript error.

Thanks in advance.

**Comment by kevin-brown** [comment]
Two things

1. You should return `null`, not `false`, when you don't want the tag to show up.
2. There appears to be a bug in the tokenizer where it does not respect this.
