### ISSUE TITLE
$(...).select2('val') returns inconsistant results

### ISSUE THREAD

**Issue by InstanceOfMichael** [select2/select2#3393]
I ran these commands one after the other, no code is modifying these objects.

![select2valbug](https://cloud.githubusercontent.com/assets/4094542/7756675/80fdf02e-ffc2-11e4-96f6-b912a75478bd.PNG)

```
// package.json
  "name": "select2-bootstrap-css",
  "version": "1.4.6",
```

It seems to work fine if I used ``.val()`` from the beginning. Seems to be plenty of workaround here.

**Comment by kevin-brown** [comment]
Select2 provides a `.select2('val')` method which in 3.x mapped to a custom method for retrieivng the value, but in 4.0 just maps to jQuery's `.val()` method. Any inconsistencies that come from it are either a jQuery problem or a result of Select2 not being initialized in the first place.

**Usually you want to use jQuery's `.val()` instead.**

----

The first three calls looks like you are calling Select2 on an element which hasn't actually been initialized. While [this should trigger a warning](https://github.com/select2/select2/blob/fdb2b6aaf2265e356611f14e81be3f8b4b080d7c/src/js/jquery.select2.js#L29-L34), stranger things have happened.

The fourth call initializes Select2 and [calls `.val()`](https://api.jquery.com/val/) as provided by jQuery. The fifth call again calls `.val()`. The sixth call routes to Select2's `val`, which [really just calls `.val()`](https://github.com/select2/select2/blob/fdb2b6aaf2265e356611f14e81be3f8b4b080d7c/src/js/select2/core.js#L459).
