### ISSUE TITLE
Dynamically changing data

### ISSUE THREAD

**Issue by BenjaminHorn** [select2/select2#3396]
I try to change dynamically the data:
http://emberjs.jsbin.com/hakixomaze/7/edit

It seems to work if the number of items grows (Add3 -> Add2 -> Add1) but not in other way.
Removing items, from the options does not work?

**Comment by penihel** [comment]
Heed empty the select tag before remake the select2 plugin


$('#add3').click(function(){
  sel.empty();
  sel.select2({data:data3});
});

**Comment by BenjaminHorn** [comment]
thanks
