### ISSUE TITLE
Cmd (meta) Key in Select 2 4.0

### ISSUE THREAD

**Issue by snichini** [select2/select2#3400]
Hello,

I see that in the 4.0 you're able to maintain the ctrl key while selecting multiple values and the toggle menu stays opened.

In OSX if you click left + ctrl  key holded, the right context menu appears.

If you add the metaKey event for the same behavior it would be great for OSX users.
While pressing the cmd key and left click it works.

I add this by replacing:

``` javascript
// Don't close if the control key is being held
                    if (originalEvent && originalEvent.ctrlKey) {
                        return;
                    }
```

BY

``` javascript
// Don't close if the control key is being held
                    if (originalEvent && (originalEvent.ctrlKey || originalEvent.metaKey)) {
                        return;
                    }
```

AND 

``` javascript
else if ((key === KEYS.SPACE && evt.ctrlKey)) {
```

BY 

``` javascript
else if ((key === KEYS.SPACE && (evt.ctrlKey || evt.metaKey))) {
```

hope this can be in the next version

**Comment by kevin-brown** [comment]
Pull requests are always appreciated.

**Comment by snichini** [comment]
@kevin-brown  yes I know. I didn't have the time to do it.i'm in a rush right now
