### ISSUE TITLE
tagging issue with angular version > 1.2.18

### ISSUE THREAD

**Issue by thlgrant** [select2/select2#3401]
tagging works as expected (first multiple select) Angular 1.2.18:
http://plnkr.co/edit/STzBbCIBgHxfYCY8qpfL?p=preview
![tagworks](https://cloud.githubusercontent.com/assets/5322574/7774305/267f0de6-00a2-11e5-8a9d-0a78aec6334a.PNG)

tagging does not work as expected (first multiple select) Angular 1.3.15
http://plnkr.co/edit/KAZjUQn4S6xKcyAIoxfD?p=preview
![tagbroken](https://cloud.githubusercontent.com/assets/5322574/7774310/320d7062-00a2-11e5-8903-c738497fcd05.PNG)

Using an angular version greater than 1.2.18 breaks the tagging functionality

**Comment by kevin-brown** [comment]
[ui-select is not Select2, it just has a Select2 theme.](https://github.com/angular-ui/ui-select)
