### ISSUE TITLE
Not able to set data programmatically on select2 ajax control

### ISSUE THREAD

**Issue by sunalive** [select2/select2#3403]
I'm using 3.5.2 and have a select2 ajax control for my website which uses the old textbox based control.  I'm trying to populate the info from an iframe in another div but that does not happen.  I get and push the info successfully to the parent textbox but the select2 control does not refresh with that info.  The details of what I'm doing is in this link.  http://stackoverflow.com/questions/28004771/access-parent-select2-control-element-from-iframe-and-set-its-value. 

Do you see what's going wrong?

**Comment by pedrofurtado** [comment]
The issue is related to 3.x version, but the version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
