### ISSUE TITLE
createTag not only at tag type

### ISSUE THREAD

**Issue by kfreiman** [select2/select2#3404]
disapear  createSearchChoice's behavior at dropdown. CreateTag create new item only with tags: true options.

**Comment by kevin-brown** [comment]
This is intentional. There is no difference between `createSearchChoice` (3.x) and `tags` + `createTag` (4.x).

`createSearchChoice` previously just allowed for a custom option to be added based on the term, which was directly tied into tags (and previously implied `tags: []`).
