### ISSUE TITLE
Prevent users from creating new tags

### ISSUE THREAD

**Issue by albert28** [select2/select2#3407]
Is it possible to prevent users from creating new tags? I didn't find any method to do that.

**Comment by kevin-brown** [comment]
Don't set the `tags` option. Users should only be able to create tags when that option is enabled.

Unless you're looking for something more specific, like only preventing it sometimes, in which case you can return `undefined` from the `createTag` function (which is what returns the data object for the tag) in those situations.

**Comment by albert28** [comment]
Well, I would like to keep the tags option, but I would like to prevent users from creating new tags, so they can only check the default values. I tried doing that with the createTag function, but it didn't work.

> $("#languages-template").select2({
                tags: newMyTags,
                createTag: function(params) {
                    return undefined;
                }});
