### ISSUE TITLE
AttachContainer usage

### ISSUE THREAD

**Issue by molily** [select2/select2#3411]
Hello! I’d like to create a reusable component based on Select2 that decorates the dropdown adapter with AttachContainer. I still want to be able to use options like multiple, minimumResultsForSearch, closeOnSelect etc. So I need to reuse the logic that adds all necessary decorators depending on the options.

My current solution is to copy this chunk of code into my component
https://github.com/select2/select2/blob/4.0.0/src/js/select2/defaults.js#L145-L185
and change one line of code in it (AttachBody vs. AttachContainer).
https://github.com/select2/select2/blob/4.0.0/src/js/select2/defaults.js#L183

This seems tedious, I’d rather reuse the code from Select2, but I don’t see a way to use that function without committing to the AttachBody decorator as well. Any ideas how to simplify this on my side or in the Select2 codebase?

Thanks for your library and thanks for your time. :smiley:

**Comment by molily** [comment]
How about making AttachBody/AttachContainer configurable? This would make this common task easier.

**Comment by skeptic35** [comment]
+1 from me for the suggestion to make this configurable. The current way of getting Select2 to use ```AttachContainer``` is an absolute PITA - excuse my French (and really not very well documented, if you ask me).

**Comment by DiogoDoreto** [comment]
+1 for having an option.

I had to copy all those lines as well just because search wasn't working inside a modal. And there is the fact that is not a best practice to import inner files of a library.

**Comment by videsignz** [comment]
This really needs to be addressed in a simple manner. A simple option to attach to itself would be best. Something like...

```js
$('select').select2({
  dropdownParent: "self"
});
```

**Comment by SvyatoslavPozhydaev** [comment]
`
$.fn.select2.amd.define("CreateAttachContainerDropdownAdapter", [
    "select2/utils",
    "select2/dropdown",
    "select2/dropdown/attachBody",
    "select2/dropdown/attachContainer",
    "select2/dropdown/search",
    "select2/dropdown/minimumResultsForSearch",
    "select2/dropdown/closeOnSelect",
  ],
  function(Utils, Dropdown, AttachBody, AttachContainer, DropdownSearch, MinimumResultsForSearch, CloseOnSelect) {
    return function (_options) {
      var options = $.extend(true, {}, $.fn.select2.defaults.defaults, _options);
      var adapter = null;
      if (options.dropdownAdapter == null) {
        if (options.multiple) {
          adapter = Dropdown;
        } else {
          adapter = Utils.Decorate(Dropdown, DropdownSearch);
        }

        if (options.minimumResultsForSearch !== 0) {
          adapter = Utils.Decorate(
            adapter,
            MinimumResultsForSearch
          );
        }

        if (options.closeOnSelect) {
          adapter = Utils.Decorate(
            adapter,
            CloseOnSelect
          );
        }

        if (
          options.dropdownCssClass != null ||
          options.dropdownCss != null ||
          options.adaptDropdownCssClass != null
        ) {
          var DropdownCSS = require(options.amdBase + 'compat/dropdownCss');

          adapter = Utils.Decorate(
            adapter,
            DropdownCSS
          );
        }

        adapter = Utils.Decorate(
          adapter,
          AttachContainer
        );
      }
      return adapter;
    }
  }
);

var selectOptions = {
   ...  // your options
}

selectOptions.dropdownAdapter = $.fn.select2.amd.require('CreateAttachContainerDropdownAdapter')(selectOptions);

$(select).select2(selectOptions);
`
