### ISSUE TITLE
[4.0] destroy broken on selections with length > 1

### ISSUE THREAD

**Issue by mh-nichts** [select2/select2#3413]
Only the first select of the list is destroyed (similar issue #2187 but for v4.0).

Here is a test case (destroy after 3 seconds) :
http://codepen.io/mh-nichts/pen/JdXbdm

Tested on Windows 7 : Firefox 37, Chrome 42, IE 11.

**Comment by pquentin** [comment]
I was affected by the issue too, and I fixed it locally, hence the pull request.

**Comment by santaclaus21** [comment]
$orginalRow.find("select.select2").select2("destroy").end().clone();

4.03: There is an error while calling on non select2 object. It was working fine in version 3.5.
