### ISSUE TITLE
Problem with Chrome , do not understand what's going on

### ISSUE THREAD

**Issue by widesys** [select2/select2#3414]
From one moment to another I started having problems in my application, to change the value of any select2, an error explodes in chrome screen.
I did a test on the sample page of select2 and the same error occurs.
I tested it on other computers with the same version of chrome and different version, select and chrome work well, there is no error, can anyone help me.

Uninstalled Chrome, Disable AntiVirus but do not know what to do.
![ohhhh](https://cloud.githubusercontent.com/assets/3837934/7844084/5944a2f0-0484-11e5-893b-36509a1ef7b1.png)

Watch the video: https://drive.google.com/file/d/0B_wm3oMH9DipQkJmWk9lTEFjNm8/view?usp=sharing
Thanks All

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/
