### ISSUE TITLE
createSearchChoicePosition removed in select2 4.0 withour replacement

### ISSUE THREAD

**Issue by kreintjes** [select2/select2#3420]
I know the createSearchChoice option is replaced by the createTag option in select2 4.0. However, the old createSearchChoicePosition option seems to be completely removed without replacement (createTagPosition does not work).

Am I correct and if so, any plans on restoring this option?

**Comment by kevin-brown** [comment]
This is exposed as [the internal `insertTag` method](https://github.com/select2/select2/blob/bd6148e39f753ed2880f674a90b42ffe446b893a/src/js/select2/data/tags.js#L100-L102) on the tags decorator, but it is not yet exposed through the options when initialzing Select2.

**Comment by kreintjes** [comment]
Thanks for the quick reply. So for now it is not possible to override it yet, but it will be in the (near) future?
