### ISSUE TITLE
support for seajs

### ISSUE THREAD

**Issue by LiXunGuan** [select2/select2#3421]
Hi,will next version support seajs?

**Comment by kevin-brown** [comment]
It should _probably_ already support it. If it isn't supported, you are going to need to reply back with some error logs so we can try to find a common ground to work from.

**Comment by LiXunGuan** [comment]
@kevin-brown code ```if (typeof define === 'function' && define.amd) ``` delete  ```&& define.amd```

**Comment by kevin-brown** [comment]
@LiXunGuan Is there any documentation for seajs that explains why that is required?

We are using the standard UMD header, which should work for 99% of use cases.

**Comment by LiXunGuan** [comment]
@kevin-brown [Seajs](https://github.com/seajs/seajs)
UMD standard can't support CMD standard. 
``if (typeof define === 'function' && define.amd)``  change
```if (typeof define === 'function' && define.amd && define.cmd)```

**Comment by kevin-brown** [comment]
I've never heard of `define.cmd` being a thing, and our `define` call only supports AMD (not the CMD through AMD syntax).

**Comment by LiXunGuan** [comment]
@kevin-brown 
```
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['jquery'], factory);
  }else if (typeof define === 'function' && define.cmd){
  // for Seajs 
    define(function(require, exports, module){
        factory(require('jquery'));
    });
  } else if (typeof exports === 'object') {
    // Node/CommonJS
    factory(require('jquery'));
  } else {
    // Browser globals
    factory(jQuery);
  }
```
