### ISSUE TITLE
Template & format issue

### ISSUE THREAD

**Issue by mistergreen** [select2/select2#3423]
Am I the only one having this issue? I have the latest bootstrap 3 and select 2 (4.0).
The format callbacks doesn't even get called when I put in an alert or console.log
  
        function formatResult(item) {
          if(!item.id) {
            // return `text` for optgroup
            return item.text;
          }
          // return item template
          return '<i>' + item.text + '</i>';
        }

        function formatSelection(item) {
          // return selection template
          return '<b>' + item.text + '</b>';
        }

        $('select').select2({
	        // Specify format function for dropdown item
          	formatResult: formatResult,
          	// Specify format function for selected item
          	formatSelection: formatSelection
        });

**Comment by mistergreen** [comment]
Ah, I found the announcement. I changed formatResult to templateResult, formatSelection to templateSelection but the html doesn't render/format, the selections return literal text '<i>Alaska</i>'.

**Comment by kevin-brown** [comment]
Unfortunately without a jsbin or jsfiddle that reproduces this issue, it's nearly impossible to figure out what is wrong.

**Comment by keithslater** [comment]
I'm having this same problem. Switched to templateResult and templateSelection and it is not rendering the html, instead it is just displaying the html.

**Comment by javichuteck** [comment]
I solved this problem.

Add this:
				escapeMarkup: function(m) {
					return m;
				}

Andh HTML is rendering

**Comment by imp-gino** [comment]
from https://select2.github.io/options.html

>The templateSelection function should return a string containing the text to be displayed, or an object (such as a jQuery object) that contains the data that should be displayed.

>Strings are assumed to contain only text and will be passed through the escapeMarkup function, which strips any HTML markup.

>Anything else will be passed directly to jQuery.fn.append and will be handled directly by jQuery. Any markup, such as HTML, returned will not be escaped and it is up to you to escape any malicious input provided by users.

**Comment by minlare** [comment]
Alternatively, I solved the issue by returning html:

`templateResult: function(data){`
`    return $('<span>').html(data).append($('<i>').html(data.something));`
`}`


Stated in Utils.escapeMarkup:

`// Do not try to escape the markup if it's not a string`
`    if (typeof markup !== 'string') {`
`      return markup;`
`    }`
