### ISSUE TITLE
Possible trigger query bug

### ISSUE THREAD

**Issue by andrewblake1** [select2/select2#3424]
I think this is a bug - could be just me of course. Am trying to trigger ajax load on a select2 element as per Kevin Brown answer on https://groups.google.com/forum/#!topic/select2/TOh3T0yqYr4.

If I click the element it works fine - just thought I would mention. Use case hide if 1, error message on 0 and all good to select if > 1.

Where $this is my selected jquery element:

If I use `$this.select2('trigger', 'query', {});` I get no errors but no ajax request.

If I use `$this.select2('trigger', 'query');` I get Uncaught TypeError: Cannot read property 'term' of undefined on line 3758 of select2.full.js because query is not defined in 

```
container.on('results:all', function (params) {
      if (params.query.term == null || params.query.term === '') {
```

Apologies, I have been unable to debug further as the code is a little above me still.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by andrewblake1** [comment]
Close it if you like - I will just perform ajax request directly and count results. I haven't closed myself as I still suspect it may be a bug that could trip someone else one day.

Had hoped that triggering query would populate something that I could then count in complete callback or something to keep my code to a minimum.

FYI, as per above request:
Chrome Version 43.0.2357.65 (64-bit), test file extract from your examples hence versions as per that.
Basically have had no success programatically triggering query as described previously.

```
<head>
    <base href="https://select2.github.io/">
    <script type="text/javascript" src="vendor/js/jquery.min.js"></script>
    <script type="text/javascript" src="dist/js/select2.full.js"></script>
    <script type="text/javascript" src="vendor/js/bootstrap.min.js"></script>
    <link href="vendor/css/bootstrap.min.css" type="text/css" rel="stylesheet" />
    <link href="dist/css/select2.min.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <select class="bug form-control"></select>

    <script type="text/javascript">
        $(".bug").select2({
            ajax: {
                url: "https://api.github.com/search/repositories?q=h",
                dataType: 'json',
                 processResults: function (data) { return { results: data.items }; }
            },
            templateResult: function (repo) { return repo.full_name; }
        });

//        $(".bug").select2('trigger', 'query');

    </script>
</body>
```
when click in the select box, ajax occurs as expected.
If uncomment the trigger line, the browser console shows error. If add data function to ajax that deals with undefined param.term then bug just shifts as you will see by error in browser debugger console.

Would expect the query to occur same as when focus in on the select box with no text - which works fine.

I havn't tested on different browsers - though doubt it is browser specific.

No major, can get around it with ajax myself. Thanks for your great work with this plugin.

Perhaps there is some options I should be specifying that makes it work?

**Comment by kevin-brown** [comment]
Looking back at the original post, I think the line that triggered me to ask for more information was

>  I get no errors but no ajax request.

You didn't specify what errors were being triggered, and I suspected you were dealing with a hidden input (which has a known bug with AJAX).

---

When querying for results, the query object (which can be empty, `{}`) is not optional, which explains the errors from the second line of code.

**Comment by andrewblake1** [comment]
Just double checking you realise that with an empty object query isn't triggered - thats the problem - I think it should.

I just altered the example - without the empty object it is now triggering query but errors - which you have already answered but thought I would fix my example anyway - needed data key in ajax object.

**Comment by devvmh** [comment]
Sorry for resurrecting this thread but... I have a similar error. I have a huge website with lots of different select2 calls all over the place. On upgrading to select2 4.x, I have had serious trouble even triggering AJAX (e.g. I type into the input field, but no AJAX request is sent)

If my issue is related to this one, I could post more details here. Otherwise I'll be trying to summarize the vast universe of strange configuration that might have to do with my problem into an issue tomorrow...

**Comment by andrewblake1** [comment]
@devvmh - different issue I think. This issue is to do with programmatically attempting to trigger the ajax call on the select2 in order to count the returned options for app specific purpose as opposed to what you have raised which seems like the normal operation isn't working for you due to a config issue. All works fine with select2 v4 under normal circumstances with ajax.
