### ISSUE TITLE
error if i m hiding select2 from  page

### ISSUE THREAD

**Issue by ajkosh** [select2/select2#3426]
i have select on user page and it is on create page if user is updating after create then i m hiding select2,then it is giving me this error and below is attachment,
i m not hiding select2 exactly ,i have php if condition where it is not showing if user is on update.
old version was working good ,no issue but this is giving me error.

![error](https://cloud.githubusercontent.com/assets/8582472/7897112/dec810a4-06ed-11e5-8291-627b4ec7a457.png)

**Comment by kevin-brown** [comment]
If you look at the first error, I think it makes it clear what the issue is.

> The `select2('data')` method was called on an element that is not using Select2.

You can't use `select2('data')` without calling `select2()` first.

**Comment by ajkosh** [comment]
@kevin-brown then how to use select2 call can u help me
