### ISSUE TITLE
error when i m selecting option from select2 and remove

### ISSUE THREAD

**Issue by ajkosh** [select2/select2#3427]
when i select option from select2 and remove select option and again i try to select any option from select2 it is giving me below attachment error.
![screenshot from 2015-05-30 17 06 26](https://cloud.githubusercontent.com/assets/8582472/7897133/c8e1c52c-06ee-11e5-9ad0-56a3363494de.png)

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by ajkosh** [comment]
@kevin-brown If select2 have some options when u select one option,if u remove selected option from select2 then again select any option then this error is coming
I m using jquery 2.1.4
In all browser I m facing problem.
My question is how to all was working good in old version of select2,I have problem with #3426 also

**Comment by ajkosh** [comment]
I m using datepicker with this and more select2.
I m using Ubuntu 14
