### ISSUE TITLE
Hidden select is displayed when select2ing

### ISSUE THREAD

**Issue by Prismapanda** [select2/select2#3430]
Concerning select2 4.0.0:

If a select is initially hidden (e.g. style="display:none"), it will show up when select2 is applied.
See http://jsfiddle.net/su014pea/ for an example.

In select2 3.5.2 the select box stayed invisible. I like the idea of select2 being a drop-in replacement for plain old select boxes, so essential css properties should get copied to the created select2 root element (like the width does).

**Comment by kevin-brown** [comment]
Can't reproduce this in Chrome 43 (latest) on Windows 8.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by Prismapanda** [comment]
Ok, thougt the fiddle would do the best, but in detail:

- What steps can be used to reproduce the issue?
  1. Create a `<select`> Element with an style or css class, which makes the select invisible (e.g. style="display:none")
  2. Apply $.select2 without options

- What is the bug and what is the expected outcome?
  - The originally hidden select box gets visible after applying $.select2, which breaks the ability to hide select boxes by css

- What browser(s) and Operating System have you tested with?
  - Tested with Chrome 43 and Firefox 38 ond Windows 7

- Does the bug happen consistently across all tested browsers?
  - Yes.

- What version of jQuery are you using? And what version of Select2?
  - The affected version of select2 is 4.0.0.
  - The JQuery version makes no difference; 1.10.0, 1.11.0, 2.1.3 is all the same
  - When switching to select2 3.5.2 the select box stays hidden (as expected)

- Are you using Select2 with other plugins?
  - No, see the fiddle.

Sorry for not testing the master branch, but my time is limited and the essential js Files hasn't changed for a month so I didn't expect a fix there. I updated the fiddle for clarification: http://jsfiddle.net/su014pea/1/

**Comment by kevin-brown** [comment]
I think I _completely_ misunderstood what the issue was here. The issue isn't that the `<select>` is displaying after calling `.select2()`, the issue is that Select2 is displaying even though the original select was hidden.

As Select2 no longer synchronizes CSS classes and the inline `style` attribute, you are going to have to use the full builds and the old `containerCss` option.

```js
$('#select2').select2({
    containerCss: function (element) {
        var style = $(element)[0].style;
        return {
            display: style.display
        };
    }
});
```

https://jsfiddle.net/su014pea/2/

**Comment by Prismapanda** [comment]
Well, then there seems to be a bug in the compat module.

The style attribute gets applied not to the container (as the option says), but to the inner selection, which makes the container getting empty, but still claiming the width (cause the container is still visible).

see https://jsfiddle.net/su014pea/3/ where text after the select is not displayed as expected.

**Comment by santaclaus21** [comment]
I've got the same problem. How about my dirty hack? It's working for me [4.0.3]

`select[style*="display: none"] + .select2 { display: none; }`

**Comment by aonurdemir** [comment]
I selectively initialized "select" tags like $("select").not("[style*='display:none']").select2({
        tags: true,
        tokenSeparators: [',', ' '],
    }); 
to solve the problem. Indeed, prevented the problem.

**Comment by rsimancas** [comment]
thanks @santaclaus21 it works!!!
