### ISSUE TITLE
Error when preventing 'select2:opening' event

### ISSUE THREAD

**Issue by deje1011** [select2/select2#3431]
First of all, thank you for this plugin! I did not completely cotton up to the new API, yet but all in all it works great and is very flexible. 

However I get an error when I try to prevent the dropdown from opening or closing, 
```
uiSelectElement.one('select2:opening', function(e){
    e.preventDefault();
});
``` 
Error : Uncaught TypeError: Cannot set property 'prevented' of undefined

```
  Select2.prototype.trigger = function (name, args) {
    var actualTrigger = Select2.__super__.trigger;
    var preTriggerMap = {
      'open': 'opening',
      'close': 'closing',
      'select': 'selecting',
      'unselect': 'unselecting'
    };

    if (name in preTriggerMap) {
      var preTriggerName = preTriggerMap[name];
      var preTriggerArgs = {
        prevented: false,
        name: name,
        args: args
      };

      actualTrigger.call(this, preTriggerName, preTriggerArgs);

      if (preTriggerArgs.prevented) {
        args.prevented = true; // this is where the error occurs 

        return;
      }
    }

    actualTrigger.call(this, name, args);
  };
```
Line 5161  (I´m using version 4.0)

It seems like there are no arguments passed when triggering the open / close events. 

Thanks in advance, 
Jesse

**Comment by kevin-brown** [comment]
Part of the issue here is that we do not provide in a blank object (`{}`) if one wasn't passed in originally.

**Comment by althaus** [comment]
@kevin-brown Is it possible to release all the current fixes as 4.0.1 and move the open issues to 4.0.2?

**Comment by MusikAnimal** [comment]
For anyone still on Select 4.0.0, you could alternatively use CSS to disable opening/closing Select2:
```
.select2-selection {
  pointer-events: none;
}

.select2-selection__choice {
  pointer-events: visible;
}
```
All browsers and IE10+

**Comment by MusikAnimal** [comment]
For anyone still on Select 4.0.0, you could alternatively use CSS to disable opening/closing Select2:
```
.select2-selection {
  border-radius: 4px !important;
  pointer-events: none;
}

.select2-selection__choice__remove {
  pointer-events: visible;
}

.select2-dropdown--below {
  display: none;
}
```
Super hacky but it works, all browsers and IE11+
