### ISSUE TITLE
No focus on label click

### ISSUE THREAD

**Issue by RomeroMsk** [select2/select2#3436]
Very old problem, since one of 3.x releases.
When you click on label with appropriate `for` attribute, Select2 will not receive a focus.
Related issue: #2311, but it's labeled as `3.x`.

**Comment by RomeroMsk** [comment]
Also noticed that Select2 is not focusing when traversing inputs by `Tab` key. Has this problem the same roots or I need to open separate issue?

**Comment by patrickbrouwers** [comment]
Having the same issue with 4.x.

What I want to achieve is when user hits `Tab` and lands on a select2 box, they can immediately start typing without having to click on the element.

**Comment by kevin-brown** [comment]
Merging this into https://github.com/select2/select2/issues/2311, which I've just retagged to include 4.x.

The tab issue sounds unrelated, I'd recommend creating a new ticket (with a jsbin/jsfiddle) about it.

**Comment by RomeroMsk** [comment]
> The tab issue sounds unrelated, I'd recommend creating a new ticket (with a jsbin/jsfiddle) about it.

Can not reproduce it now on jsfiddle. Will check my code and open an issue if problem still exists. Thanks.
