### ISSUE TITLE
How can I override the format of the current value of the select2 field?

### ISSUE THREAD

**Issue by mrueegg** [select2/select2#3438]
Hi,

I have a select2 field with a list of values, but I need to make sure that when the framework I'm using tries to read the value from the select2 field, that it looks different than the normal list of values (i.e., I want to yield the keys of the select2 field comma-separated instead of the list of selected keys). So instead of 

$('#my-select2-field').val() => ["key1", "key2"]

I want

$('#my-select2-field').val() => "key1,key2"

Is this possible with select2?

Thanks,
Michael

**Comment by wilsont** [comment]
It can be done in Javascript , try this 

$("#my-select2-field").val().join()

**Comment by mrueegg** [comment]
Thanks, but it is not me that is calling val(), but instead the framework. So I have to somehow override the internal value of the select2 DOM node...

**Comment by wilsont** [comment]
For this case you may consider to change the standard implementation of this function...

Select2.prototype.val = function (args) {
    if (this.options.get('debug') && window.console && console.warn) {
      console.warn(
        'Select2: The `select2("val")` method has been deprecated and will be' +
        ' removed in later Select2 versions. Use $element.val() instead.'
      );
    }

    if (args == null || args.length === 0) {
      return this.$element.val();
    }

    var newVal = args[0];

    if ($.isArray(newVal)) {
      newVal = $.map(newVal, function (obj) {
        return obj.toString();
      });
    }

    this.$element.val(newVal).trigger('change');
  };

**Comment by mrueegg** [comment]
Thanks a lot! Do you know why I'm getting 

Uncaught TypeError: Cannot set property 'val' of undefined

when accessing Select2.prototype.val?

**Comment by kevin-brown** [comment]
It sounds like you want to connect Select2 to a `<input type="text" />` instead of a `<select>`.
