### ISSUE TITLE
Select2 and Ajax pagination breaks

### ISSUE THREAD

**Issue by teknull** [select2/select2#3444]
I posted this on StackOverflow today [Stackoverflow question](http://stackoverflow.com/questions/30684187/select2-breaks-with-ajax-jquery-on-pagination) but I wanted to see if there was a known issue with Ajax pagination with `select2` of some sort.  If you want me to keep this on Stack, I'm ok with that but I figured I might be able to get a fresh pair of eyes on this.

**Comment by kevin-brown** [comment]
It sounds like you are hitting issues with [turbolinks](https://github.com/rails/turbolinks), I'd recommend looking into [jquery.turbolinks](https://github.com/kossnocorp/jquery.turbolinks).

**Comment by teknull** [comment]
If agree with you but this app is Rails 3.2.21 and am not using turbolinks gem.

**Comment by teknull** [comment]
To work around the problem I came up with this UJS and put it in my view's `index.js.erb` file.

````
   $("select").select2({
        placeholder: "Select One",
        allowClear: true
  }); init();
````
So basically on each Ajax call it re-inits select2.  Kind of a hack, but so far it's working great for me.
