### ISSUE TITLE
containerCssClass :all: vs. :all

### ISSUE THREAD

**Issue by molily** [select2/select2#3446]
I’ve found a small inconsistency I can’t explain:

https://github.com/select2/select2/blob/master/src/js/select2/compat/containerCss.js#L24-L25

```javascript
if (containerCssClass.indexOf(':all:') !== -1) {
      containerCssClass = containerCssClass.replace(':all', '');
```

Shouldn’t it be `.replace(':all:', '')`? Currently a stray “:” remains in the class list. For example, if I configure

```
containerCssClass: ':all: hello-world'
```

and the `select` element has `my-class-a my-class-b`, the container classes are

```
select2-selection select2-selection--multiple my-class-a my-class-b : hello-world
```

The colon isn’t harmful AFAICS but it’s superfluous, isn’t it? ;)

Thanks.

**Comment by kevin-brown** [comment]
It's supposed to be `:all`, as noted in the original commit: https://github.com/select2/select2/commit/f3f1b31958fa585fadfe2eada3449826ce48224e

A pull request would be greatly appreciated to fix the typo.
