### ISSUE TITLE
No 's2id_' added to rendered objects when calling select2() by classname.

### ISSUE THREAD

**Issue by webivation** [select2/select2#3447]
My HTML:

```
<select id='selectbox_2' multiple='multiple' class='select2_sortable' style='width: 350px;'></select>
```

My JQuery:

```
$(document).ready(function () {
        $('.select2_sortable').select2({
            tags: true
        });
    });
```

The rendered HTML:

```
<span class="select2 select2-container select2-container--default select2-container--below" dir="ltr" style="width: 350px;">
    <span class="selection">
        <span class="select2-selection select2-selection--multiple" role="combobox" aria-autocomplete="list" aria-haspopup="true" aria-expanded="false" tabindex="0">
            <ul class="select2-selection__rendered ui-sortable">
                <li class="select2-search select2-search--inline ui-sortable-handle">
                     <input class="select2-search__field" type="search" tabindex="-1" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" role="textbox" placeholder="" style="width: 0.75em;">
                 </li>
            </ul>
        </span>
    </span>
    <span class="dropdown-wrapper" aria-hidden="true"></span>
</span>
```

As you can see, by accessing it via a class instead of an ID, the resulting s2id_[MY SELECT ID] isn't being added anywhere... making it impossible to access those controls/values directly for a single select2 on a page with multiple select2 instances.

(Select2 Version 4.0.0)

**Comment by kevin-brown** [comment]
This isn't specific to initializing Select2 by a class, the problem is actually that Select2 isn't setting that many unique ids.

`s2id_` wasn't documented anywhere, and the newer ids start with `select2-` (also not documented anywhere). Single selects (as of this moment) have an id of `select2-[auto-generated id]-container` added to the selection container, but that's pretty much it.

**Comment by webivation** [comment]
Yeah, I pulled the s2id_ from reading the generated source of 3.5.2's example page:
http://select2.github.io/select2/

I haven't used any singles, so hadn't noticed any behavior there.

**Comment by webivation** [comment]
As a temporary work around for this I've build the following function.  Unfortunately the event that fires after the load is complete has apparently also been removed, making this have to run globally in the window loaded (to be sure the rendering has finished) and a little less 'certain' than I'd prefer, but it seem to do alright for now.

```
$(window).on('load',function() {
        $('.select2_sortable').each(function() {
            var baseId = $(this).attr('id');
            $(this).next('.select2').find('ul:first').attr('id', 'select2_rendered_' + baseId);
        })
    });
```
