### ISSUE TITLE
Select2 on clear does not change input element value NOR fire change event

### ISSUE THREAD

**Issue by kartik-v** [select2/select2#3452]
On clearing a value (when `allowClear`) is true... the base `select` element value is not changed (shows the old value) - NOR is the change event triggered.

**Comment by kevin-brown** [comment]
Must have missed this ticket, but I can't seem to reproduce the issue.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by kartik-v** [comment]
Actually my mistake in describing - the `change` event does fire... but it does after the `select2:unselect`. 

This was more related to issue #3320 when the select2 does not close on clearing. 

Was trying to trap the value of the input after `select2:unselect` and not after a normal `change`. It shows the old value. But i need it similar to what happens after `select2:select`. Currently I do not have a method to do this... and need to rely on `change`.

**Comment by andreasbernhard** [comment]
Can confirm the issue, occurs at least when ajax is used. allowClear has only visual effect, form element (select) isn't changed in any way. @kartik-v  Any solution / workaround yet?

What steps can be used to reproduce the issue? allowClear in combination with ajax
What is the bug and what is the expected outcome? allowClear has no effect on form value
What browser(s) and Operating System have you tested with? Windos 8.1, Chrome 45
Does the bug happen consistently across all tested browsers? yes
What version of jQuery are you using? 2.1.4 And what version of Select2? 4.0.0
Are you using Select2 with other plugins? No

**Comment by andreasbernhard** [comment]
@kartik-v Had the same problem (in a complex ajax & pagination scenario) but I've just missed to add the placeholder option like <option value=''></option>

**Comment by kartik-v** [comment]
@andreasbernhard I feel the solution is that on clear the input val must be cleared and the `change` event must be triggered before `select2:unselect`.

**Comment by alexweissman** [comment]
Please continue discussion in #3320.
