### ISSUE TITLE
how to trigger event on focus and blur

### ISSUE THREAD

**Issue by cornernote** [select2/select2#3457]
It seems that in the 4.x releases the focus and blur events have been removed.  I assume this is because there is another way to hook into these events, but I can't find any documentation on this.

Can anyone give me a kick in the right direction as to how I handle focus and blur events?

Thanks.

**Comment by kevin-brown** [comment]
Merging this into https://github.com/select2/select2/issues/1908, it's a duplicate of https://github.com/select2/select2/issues/3152.
