### ISSUE TITLE
Pasting does not create the tags

### ISSUE THREAD

**Issue by janscas** [select2/select2#3458]
Pasting a string like "marc,edward,jorge" does not create the tags.

```js
$('#tagSelector').select2({
   tags: true,
   tokenSeparators: [','],
   multiple: true
});
```

Fiddle here:

http://jsfiddle.net/2wpjptuh/

Any idea on how to solve this?

**Comment by kevin-brown** [comment]
It looks like the tags are being processed, but the options are not actually being created.

**Comment by ericsaboia** [comment]
Same issue here. Any workaround for now?

**Comment by Mobyman** [comment]
And wut?..

**Comment by jaewun** [comment]
Would love a fix to this. Cheers.

**Comment by benir** [comment]
How progress in fixing this bug?

**Comment by sandermarechal** [comment]
I am suffering from the same problem and I am trying to debug it. It seems a problem with SelectAdapter.prototype.current. This only returns the currently selected options from the actual select element. But if you paste in multiple tags then it processes all the tags first, and then updates the select box with the new tags. That means that when you paste `A,B,C` then, when B is processed, A still has not been properly selected and SelectAdapter.prototype.current does not return it (but it should).

**Comment by sandermarechal** [comment]
@kevin-brown Any progress on this? I'm a bit out of my depth here and I cannot fix it myself.

**Comment by kevin-brown** [comment]
@sandermarechal This is on my list of things to review more in depth. Right now I haven't been able to do any extensive testing to confirm your findings, but it sounds what you're seeing may be the issue.

**Comment by Decagon** [comment]
Issue still occurs in 4.0.1-rc.1

**Comment by Decagon** [comment]
When using Select2 4.0.1-rc.1: http://jsfiddle.net/2wpjptuh/
- pasting tags with token separators, including token separators at the beginning and ending of the string, causes no tags to appear. It is not possible to recover the tags through the GUI.
- when the token separator is at the beginning of the string, the last tag will appear but will be cut off, only showing the last half of the last letter in the tag. Un-focusing the search will show most of the first letter. Pressing delete will cause the entire last tag to appear, with the last character deleted.

When using Select2 4.0.0: http://jsfiddle.net/2wpjptuh/9/
- only the last tag would appear when pasting a string with token separators, but no token separators at the beginning or end.
- if token separators are at the beginning and/or the end, the entire text will be shown but won't be converted into tags.

**Comment by LucasArruda** [comment]
I'm having the same problem here. I have huge lists, so pasting would be lot easier than typing all.

I have found this http://stackoverflow.com/questions/17197223/is-it-possible-to-paste-a-list-to-a-select2-field-and-match-each-item-in-the-lis and this http://stackoverflow.com/questions/16611458/convert-select2-input-to-tokens , but related only to 3.2 and 3.5.

I've tried to implement something similar but it seems that `Tokenizer.prototype.query` is being called anyways.

**Comment by eberzosa** [comment]
Hi, I had the same problem and after investigating a while I managed to fix it. It is kind of a dirty fix but it works for me and it's more than enough to be able to use copy/paste while this is fix properly.

Attached is the select2.txt (please change the extension to js as it was the only way of uploading it) with the fix, note that it is version 4.0.0. Search for "Hack" in the code to see what was done to fix it. Hopefully it will help Kevin to see where is the problem and fix it properly.

Cheers,
Enrique

[select2.txt](https://github.com/select2/select2/files/123578/select2.txt)

**Comment by eberzosa** [comment]
Please, remember to handle multiple separators together, I also had an issue when separators are comma and white space and users pasted something like: "paste1, paste2, paste3". Checking if the 'part' is empty was enough to fix it (it is not in the code I attached).
Cheers

**Comment by ronschi** [comment]
Doesn't work here - reopen please.

Tried pasting with a@de.de,b@de.de,c@de.de (separator should be "," )

**Comment by tribulant** [comment]
It seems like the pasting of comma separated tags into Select2 doesn't work when the data is not available so just add an empty data object and then it works. It worked for me.

**Comment by kevin-brown** [comment]
> Doesn't work here - reopen please.

This should be fixed on the current master branch, which will be a part of the upcoming 4.0.3 release.

**Comment by spyninja** [comment]
On @eberzosa solution, I faced a problem when adding a new selection with a comma using the select2 tokenizer.

Fixed it by adding `if(data != null)` right above the `data.selected = true;` in line 2966 and now it works fine.

Hope it is helpful for someone else, too.

**Comment by srikanthsubramanian** [comment]
Trying to paste multiple comma separated items in a basic select2 implementation with `tokenSeparators` and `createTag` specified. The last item in the list is never tokenized. It remains as an input string and disappears when moved out of focus of the select2. Is this a bug ? If so, can anyone suggest an alternative ?

**Comment by spyninja** [comment]
@srikanthsubramanian Could you paste your javascript console log?

**Comment by srikanthsubramanian** [comment]
@spyninja I am not seeing any error on the console. I have tried the same on the select2 examples page in the [automatic tokenization section](https://select2.github.io/examples.html#tokenizer). I just tried to add certain cities separated by commas and the last item is never tokenized or tagged. On blur of the element, the last untagged item clears from the input.

**Comment by spyninja** [comment]
@srikanthsubramanian If you are using @eberzosa solution and my fix you could probably overcome that issue. Are you using the default select2 script? If so, I think there are some problems on that when pasting values if I remember well. Hope this helps a bit.

**Comment by srikanthsubramanian** [comment]
@spyninja I am using the latest version, 4.0.3 which has the fix for the copy paste issue as mentioned by the owner. 

Also another issue I am having trouble with is, if I have a token/tag added like 'Vice President' and then I try add 'President' to the same select2 as tags, then the second one is not tokenized on tab or enter, since the dropdown always highlights the existing tag 'Vice President'. The same works on using comma, since it is a tokenSepartor as mentioned by me.

**Comment by spyninja** [comment]
@srikanthsubramanian I think that this pretty hacky solution will help you to get the last value:

[hacky_select2_paste.txt](https://github.com/select2/select2/files/416254/hacky_select2_paste.txt)

**Comment by janscas** [comment]
As this is not fixed in the current release please... reopen

**Comment by renemarty** [comment]
This is my solution, change select2.js:
at line 355
```
if (typeof ctrl.items == "undefined")
    ctrl.items=[];
```

```
at line 667
if (ctrl.items[ctrl.activeIndex])
   item = ctrl.items[ctrl.activeIndex];
```

**Comment by iStyx** [comment]
Solution for 4.0.1 version:

Note: There _should_ be empty `data` parameter

```js
$('#my-select').data('select2').dataAdapter.$search.val("tag1,tag2,").trigger("input");
```

**Comment by markrlondon** [comment]
This problem stlill exists in the select2 examples page in the automatic tokenization section.   So is it really fixed?

**Comment by chrilehner** [comment]
in my case when I paste a list (e.g. A,B,C) the tags are created except for the last item C
is this the desired behaviour?

**Comment by mrp14** [comment]
@chrilehner I did it listening to `onpaste` event on select2's text input (`.select2-search__field`). In the callback, i get clipboard content, append to it a tag separator, set it as the input value and trigger the keyup event.

That's not the cleanest solution ever imagined but at least it is working without modifying the library.

For example (I used arrive.js here to watch for DOM changes)

```javascript
$(document).arrive('.select2-search__field', {fireOnAttributesModification: true, existing: true}, function () {
	$(this).attr('onpaste', 'handleSelect2Paste.apply(this, arguments);');
});
```

Notice that I set event listener using the inline onpaste property : if I did it programmatically, my event listener would get removed by select2 as soon as I select an element or add a tag.

```javascript
window.handleSelect2Paste = function(e){
	var separator = ' ';
	//get clipboard content in a cross-browser way
	var pastedText = '';
	if (window.clipboardData && window.clipboardData.getData) {
		pastedText = window.clipboardData.getData('Text');
	} else if (e.clipboardData && e.clipboardData.getData) {
		pastedText = e.clipboardData.getData('text/plain');
	}
	//stop propagation : we will trigger keyup manually
	e.preventDefault();
	e.stopPropagation();
	//append tag separator to clipboard content and trigger keyup 
	$(this).val(pastedText + separator).trigger('keyup');
};
```
