### ISSUE TITLE
Select box  not displayed properly in safari

### ISSUE THREAD

**Issue by pranav2410** [select2/select2#3459]
hi,
i'm using select2 4.x
In safari select box is not displayed properly
refer: http://jsfiddle.net/8mnhgq1L/1/  - open this link in safari
i got a solution for this 
on your examples page bootstrap takes care of  it
but i'm not using bootstrap so the select box is not displayed properly in safari
adding this in css  .select-search__field{-webkit -appearance : textfield;}  does the trick

**Comment by pranav2410** [comment]
when can we expect 4.0.1 release ?

**Comment by kevin-brown** [comment]
> when can we expect 4.0.1 release ?

When the [4.0.1 milestone](https://github.com/select2/select2/milestones/4.0.1) closes. We're going to roll a [3.5.3 release](https://github.com/select2/select2/milestones/3.5.3) first.

**Comment by istng** [comment]
This is still a problem on dropdown options and search input, I fixed it with:
```
    .select2-container .select2-dropdown,
    .select2.select2-container,
    .select2-search--dropdown .select2-search__field {
      -webkit-appearance: none !important;

      font-family: sans-serif;
      font-weight: regular;
      -webkit-font-smoothing: antialised;
      font-size: 18px;
    }
```
