### ISSUE TITLE
Publish version 4.0.0 to npm

### ISSUE THREAD

**Issue by pgilad** [select2/select2#3461]
Currently latest version in npm is `3.5.2-browserify`. Can the latest version be published to npm as well?

**Comment by kevin-brown** [comment]
Current @chrisjbaik handles NPM releases, as they manage the select2 package on NPM. If you can push up the latest version, that'd be awesome @chrisjbaik.

With the release of 4.0.0, we should no longer require a special browserified version.

**Comment by lukestephenson** [comment]
:+1: I need this as well.

**Comment by chrisjbaik** [comment]
@kevin-brown added you as an owner. Sorry about the trouble!

**Comment by kevin-brown** [comment]
Thanks @chrisjbaik, just I just pushed up the latest release.

/cc @lukestephenson @pgilad @mondalaci @leider

**Comment by leider** [comment]
Hooray! \o/
