### ISSUE TITLE
Update inline width of `.select2-search__field` on `window.onresize`

### ISSUE THREAD

**Issue by fk** [select2/select2#3462]
In context of working on the [select2-bootstrap-theme](https://github.com/select2/select2-bootstrap-theme), I'm trying to figure out how to best support the usage of Select2 in a responsive/fluid layout context. For now, my approach was setting `width` to `null` (please reference the conversation in https://github.com/select2/select2-bootstrap-theme/issues/2) – while I'm unsure wether this is the best way to go, I really would like to avoid setting an inline style to the original `select` element as [described in the documentation](https://select2.github.io/examples.html#responsive).

While trying to figure out things, I stumbled upon the `.select2-search__field` inline width not being updated on `window.onresize`. Consider the following use case – reproduceable on https://select2.github.io/select2-bootstrap-theme/, and as it seems only happening with `width` set to `null`:

Starting with a screen width of ~900px, Select2 sets an inline style defining a `width` of `718px` matching the original element's width to `.select2-search__field`:
![image](https://cloud.githubusercontent.com/assets/21834/8086447/bbb4fac2-0f95-11e5-9fb8-d86da7eed134.png)

After resizing the screen to ~1080px, causing the parent container to change its size, this width isn't updated, causing the RTL placeholder to disappear into the hidden overflow of `.select2-selection__rendered`:
![image](https://cloud.githubusercontent.com/assets/21834/8086992/b707b5d4-0f98-11e5-8cbe-b0c350386fbc.png)

The same is happening if I initialize the [Responsive design](https://select2.github.io/examples.html#responsive) multi select example with a placeholder – albeit the problem is not as visible because it not being a RTL `select`:
![image](https://cloud.githubusercontent.com/assets/21834/8087407/f062fa26-0f9a-11e5-94f7-cea59ae36cc0.png)

**Comment by kevin-brown** [comment]
I'm just going to flag this as being related to https://github.com/select2/select2/issues/3278, as Select2 is not totally responsive by default.

**Comment by fk** [comment]
:thumbsup:

**Comment by Cashewz** [comment]
I use this set of css rules to fix the problem with Select2 multi-selects:

```
.select2-selection--multiple .select2-search--inline:first-child {
    width: 100%;

    .select2-search__field {
        width: 100% !important;
    }
}
```
