### ISSUE TITLE
`Change` event not firing

### ISSUE THREAD

**Issue by kbariotis** [select2/select2#3468]
Running Select2 3.5.2 on a project of mine, I've noticed that change event is not firing at all. 

While testing the [examples](https://select2.github.io/examples.html#events) that even there the console is not writing anything.

Could it be a bug?
Thx

**Comment by kevin-brown** [comment]
Event appear to be firing in [the 3.5.2 examples](https://select2.github.io/select2/#events).

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by kbariotis** [comment]
Yes it seems like I rushed to post it. Sorry.
