### ISSUE TITLE
documentation for templating does not include templateSelection option

### ISSUE THREAD

**Issue by Jrizzi1** [select2/select2#3470]
The example for templating only shows the usage of templateResult, and it took me a bit to figure out that I needed to use templateSelection, because the example uses templateSelection, but the code snippet does not include templateSelection

the example should probably read (because that's what code the example is running)
```javascript
$(".js-example-templating").select2({
  templateResult: formatState,
  templateSelection: formatState
});
```
anyways, thought maybe it would save someone else some time

**Comment by theatrain** [comment]
In the doco, the templateResult isn't mentioned on the options page. The following is displayed twice:

Key: templateSelection
Value: A function taking a selection object

The second instance should reference templateResult
