### ISSUE TITLE
Select2 multiple not removing selected options from drop down when selected if they contain certain chars in IE11 (ex. é)

### ISSUE THREAD

**Issue by wilkmit** [select2/select2#3475]
Select2 multiple not removing selected options from drop down when selected if they contain certain chars in IE11 (ex. é)

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by wilkmit** [comment]
Sorry I am using an out of date version. I will look into it further.
