### ISSUE TITLE
Select not clickable on mobile devices

### ISSUE THREAD

**Issue by warreb1** [select2/select2#3478]
Tried it on iPads, iPhones & several Android phones. The select2 doesn't open when clicking/tapping on the element. Is this a known issue? I have a testversion up on www.lhwauto.com
It's the normal standard implementation of Select2, nothing fancy.

**Comment by kevin-brown** [comment]
Can you reproduce the issue on the documentation website?

http://select2.github.io/examples.html

**Comment by warreb1** [comment]
@kevin-brown That seems to work well. Is it possible when customizing the select in CSS this issue occurs?

**Comment by kevin-brown** [comment]
Just confirmed on an iPhone and Android 5.1, sounds like it might be an issue on your side.

It's unlikely that it's the CSS, maybe you have some (click/mousedown/mouseup) event handler that is picking up Select2's events?

**Comment by warreb1** [comment]
@kevin-brown It seems like the Fastclick library is causing these problems. (https://github.com/ftlabs/fastclick -> library to delete the 300ms gap on mobile OS'es). Any idea to make the clickevent on the select more important than the fast click default click event? (thx for the help)

**Comment by kevin-brown** [comment]
> It seems like the Fastclick library is causing these problems.

Sounds like a duplicate of https://github.com/select2/select2/issues/3381.
