### ISSUE TITLE
select2 doesn't work with FancyBox

### ISSUE THREAD

**Issue by jherman** [select2/select2#3482]
I have this jsfiddle here:

http://jsfiddle.net/ej7hr909/7/

Everything seems to be working fine outside of FancyBox, but when you get the popup, you can see the select element is rendered however nothing appears in the dropdown.  Any advice?  Thanks!

**Comment by jherman** [comment]
Nevermind.  Need to use the DropdownAdapter option with 'AttachBody'

**Comment by rorc** [comment]
Fancybox wrap z-index more than select2-dropdown
