### ISSUE TITLE
Setting attribute "data-placeholder--text" overrides placeholder on all selects

### ISSUE THREAD

**Issue by fkranenburg** [select2/select2#3485]
When defining a default placeholder, I expect to be able to override it with custom attributes. I initialize the control like this:

```js
$(".select2control").select2({
        placeholder: {
          id: "-1",
          text: "--Select something (default placeholder)--"
        },
});
```

When I set the attribute `data-placeholder--text` on one of all selects on the page, it will globally replace all placeholders of all selects. 

Please see this fiddle to see what happens
https://jsfiddle.net/2xt0ohvv/

**Comment by fkranenburg** [comment]
While checking out the source code, I found out only empty option tags should be used in my case. Got it working for now this way. I'm not sure if I should close this issue. 
See this fiddle:
https://jsfiddle.net/nd4q2r2s/

**Comment by kevin-brown** [comment]
I'm pretty sure this is an issue with sharing references to the options that are passed in. And while switching to a blank option for a placeholder is an option for now, this is actually a bug.
