### ISSUE TITLE
select2 4.0: Being avaialble to focus on a field for tagging is essential

### ISSUE THREAD

**Issue by aruizca** [select2/select2#3491]
Not sure why it has been removed in 4.0 because it was impecably implemented in 3.5.x, where doing something like this would work:
```
$("#tags").select2('focus');
```
and the the options are displayed as soon as you start typing
now with 4.0 I can only use do:
```
$("#tags").select2('open')
```
which in my particular use case is suboptimal because it hides important info when loaded.

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/2311.
