### ISSUE TITLE
Open menu closes as soon as input field is tapped on iPad.

### ISSUE THREAD

**Issue by apokryfos** [select2/select2#3493]
I have the following (rather strange) issue specific to iPad.
I have a select element near the bottom of the page on my site. The problem I am facing is with iPad's virtual keyboard. When I click on the select and then click on the input field to start typing, the keyboard pops up, shifting the page slightly. Then the popup closes having selected the option which was at the location when the tap occured after the screen had been shifted. There are some ways to get around this (i.e. tapping the element before having scrolled down all the way or starting to scroll in the dropdown to  activate the input this way). However it would be nice if there was a way to get around this particular issue. I believe it has to do with the ghost click event firing at the place where the tap occured after the screen has been shifted and I have tried to use FastClick to prevent the ghost click from happening but that seems to also break the addon. 

The way I have gotten around this was via:

``` javascript
$object.on("select2:open", function () {        
    $(this).data("select2").$dropdown.on("touchstart", "input", function (e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
    });
    $object.on("select2:closing", function () {        
        $(this).data("select2").$dropdown.off("touchstart","input"); //Not sure if this is necessary
    });
    return true;
});
```

but I am sure this is just an invitation for things to break in other ways.

**Comment by kevin-brown** [comment]
Sounds like it might be related to https://github.com/select2/select2/issues/3107 or https://github.com/select2/select2/issues/3204, though it might be a fastclick issue?

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/ivaynberg/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by apokryfos** [comment]
The issue is very subtle. 
To reproduce the selector must be near the bottom of the screen, but not completely. This would cause the iPad soft keyboard to shift the page up (as to make room for itself while maintaining the focused element in the viewport) but this shift should not be by much.

What happens is the following. I tap on the drop-down and it appears normally. The input is not focused at this point. When I tap on the input field to begin a search the following seems to be happening:
1. The tap forces the input field to gain focus.
2. The soft keyboard is triggered and pops up in the screen.
3. The soft keyboard forces the rest of the page to be shifted up.
4. A click seems to be triggered at the location on the screen where the tap has occurred. 
5. The click seems to be triggering a selection on the element which is at that position. However this element is no longer the input field but rather an option of the drop-down. 
6. The option which is now at the location where the tap occurs is selected and the drop-down is closed. 

This is only occurring on Safari (latest) for iPad Air and yes it happens consistently (or used to happen before the workaround was in place). 

The version of jQuery being used is 1.8.3 with Select2 4.0.0.

I have tried to use the FastClick plugin to see if it would resolve the problem (as it appeared to be a tap triggering a click kind of problem) however I have found that FastClick prevents Select2 from working altogether on iPad and have since stopped using it.

**Comment by damienalexandre** [comment]
I can confirm this issue on Mobile Safari 8 (iOS 8.2) on iPhone 6S and Select2 4.0.1.

If the Select2 is at the top of the screen, it works fine, 
if it is at the bottom:

- virtual keyboard closes as soon as opened when I want to type something
- selection of existing option does not select anything
