### ISSUE TITLE
Destroy doesn't remove events from selector.

### ISSUE THREAD

**Issue by gregkaczan** [select2/select2#35]
On the example page:
1. $("#e1").data("events"); //{ change=[1]}
2. $("#e1").select2("destroy"); 
3. $("#e1").data("events"); //{ change=[1]}
4. $("#e1").select2(); 
5. $("#e1").data("events"); //{ change=[2]}

**Comment by HeberLZ** [comment]
I'm currently having this same issue, where bound events don't get removed when the destroy method is called
