### ISSUE TITLE
select2:open event firing twice

### ISSUE THREAD

**Issue by Invis1ble** [select2/select2#3503]
Hello. I think it is not normal, that `select2:open` event firing twice when I open the `select` element.
Please check out fiddle: http://jsfiddle.net/qav390mp/

**Comment by Invis1ble** [comment]
Moreover, `select2:opening` firing twice too. Here is a demo http://jsfiddle.net/yb1c2jam/

**Comment by kevin-brown** [comment]
You can reproduce this on the demo page: https://select2.github.io/examples.html#events

**Comment by rockshandy** [comment]
I've just noticed this as well (select2:open firing twice).
