### ISSUE TITLE
Hitting backspace on select element showing the previous search results in case when delay in ajax call specified

### ISSUE THREAD

**Issue by prate3k** [select2/select2#3512]
In case when ajax options are specified and user tries to search an element, once user gets the suggestion list if he clicks backspace continuously, until search text becomes empty string "", still it shows the suggestion list for the last character removed using backspace.

This is happening only when ajax option with some delay ( in my case 250ms) is specified. Its not cancelling the previous ajax call, when the search text becomes empty and populate the list with search results.

JS code : 

``` js
$("target_elem_id").select2({
  minimumInputLength : 1,
  ajax : {
    url : "some-url.json",
    dataType : 'json',
    delay : 250,
    data : function(params) {
      return {
          name : params.term,
          maxResults : 5
      };
    }
  }
});
```

Steps to reproduce : 
1> Type in some character say "new", so that is shows suggestion list : 

![search_with_text](https://cloud.githubusercontent.com/assets/4700266/8299542/c88394dc-1997-11e5-887a-642cfa72e3f8.PNG)

2> Remove the complete search text by hitting backspace continuously : 

![empty_search](https://cloud.githubusercontent.com/assets/4700266/8299547/ea17640c-1997-11e5-8b17-cf2fb897f08f.PNG)

The above suggestion list is same as the suggestion list shown when we type character "n" : 

![with_search_text](https://cloud.githubusercontent.com/assets/4700266/8299561/2f2f6cce-1998-11e5-9663-deedfbee4ef9.PNG)

It means the previous ajax call was in progress and in between we emptied search text, and it populated suggestion list with search results received in last ajax call.

**Comment by maykSVK** [comment]
I am experiencing exactly the same problem. Watching network communication I was able to see, that after last letter beeing removed it sends two requests, but the empty char query and then query with last letter (even though input is already empty). This is causing problems with filtering and I supose it's a bug. Is there any progress with this case?

**Comment by arirangz** [comment]
+1

**Comment by jimbogit** [comment]
+1 - it happens on your example page too.  please fix

**Comment by GTCrais** [comment]
I have the same issue.

Temporary fix - in your `processResults` method check for term's existence:

    processResults: function (data) {
        // ...

	let term = $("#your_selector").data('select2').$dropdown.find("input").val();

        if (!term) {
            return { results: [] };
        }

        // ...
							
    }

**Comment by kevin-brown** [comment]
In theory, all we need to do is cancel the request when a `results:message` rolls on through (since that triggers the render).

**Comment by kevin-brown** [comment]
This can still be confirmed on the examples site on the AJAX page.

https://select2.org/data-sources/ajax

**Comment by jgbishop** [comment]
I still see this issue with 4.0.13, for whatever that's worth. Hopefully stale-bot will reopen it.

**Comment by ju-Skinner** [comment]
This is still a known issue. Dealing with it as of today 6.15.2021

**Comment by bsienn-khan** [comment]
Seriously, no reply from maintainers and this is still a bug in 2025

**Comment by jonahgreenthal** [comment]
As a practical matter, this project has no maintainers. @kevin-brown occasionally shows up, but, to be blunt, hasn't done anything in years.

**Comment by bsienn-khan** [comment]
Yeah, select2 is very good on it's own, but there are quirks like this. problem is no one cares to even reply back.
Was fun to use till lasted. Seems time to move on.
