### ISSUE TITLE
maximumSelectionLength is overridden by other configuration options

### ISSUE THREAD

**Issue by fkranenburg** [select2/select2#3514]
The property "maximumSelectionLength" does not work when "closeOnSelect" is set to false. I can select more items without any effective limit.

Check out this fiddle where both situations are shown.
http://jsfiddle.net/f9jszen1/

**Comment by sparkhee93** [comment]
Is there a way to work around this bug?

**Comment by jmiguel-localvox** [comment]
I'm also having this issue.

**Comment by Candyffm** [comment]
Here is a workaround (depending on your exact needs). Enable closeOnSelect and let the select2 dropdown reopen automatically each time the selection has changed:
`
       var poiCatSelection = $('#poi_cats');
`

	poiCatSelection
		.select2({
			multiple               : true,
			closeOnSelect          : true,
			maximumSelectionLength : 3})
		.on('select2:selecting', function(){
			setTimeout(function() {
               poiCatSelection.select2('open');
    	    }, 0);
		});
`

**Comment by grunmin** [comment]
@Candyffm not really a perfect solution, because container would flash and options' position  may change

**Comment by alexweissman** [comment]
@mayashavin has identified that this is an issue with a few other configuration options as well.  From her issue (#4900):

Some of the following fields will override `maximumSelectionLength`:
1. `query`
2. `tokenSeperators`
3. `closeOnSelect` (set it to false with cause `maximumSelectionLength`) not working.

Libraries
- jQuery version:1.11.1
- Select2 version: 4.0.3

Browsers: Google Chrome
Operating System: Windows/Mac OS

Investigation: The dataAdapter prototypes get decorated with methods when maximumSelectionLength first, and with tokenSeperators later. Unfortunately, they both have same method name "query", and one will override the other in dataAdapter respectively.

Demo: https://jsfiddle.net/dpnminh/76shLmt2/

**Comment by RedaMakhchan** [comment]
Having same issue fireFox 65

**Comment by fkranenburg** [comment]
Yes. This issue is closed but not fixed.

**Comment by RedaMakhchan** [comment]
Ok I found a workarround for this with little Js on select2.

We need to know that **maximumSelectionLength** is only not allowing user to open the dropdown, it doesn't limit the select inside dropdown if the dropdown kept opened with **closeOnSelect**.


So as a workarround I just added a listener on my select2 and dispatch a close once it attempts the value of limit :

I used this two options on my select 2 :
`
                closeOnSelect          : false,
                maximumSelectionLength: 3
`

And I added a condition on it change event : 
`
$('#appbundle_member_bachlormajors').on('select2:select', function (e) {
                if($(this).select2('data').length >= 3){
                    $(this).select2("close");
                }
            });`

**Comment by JacobLuckhardt** [comment]
I found a solution that worked for me. #5533

**Comment by nileio** [comment]
until there is a merge of bug fix as @RedaMakhchan mentioned , his solution works perfectly. I made small mod to even pick the value automatically in solution here, so all you have to do now is configure as usual & copy paste the code here changing the element id..

The solution code below forces the dropdown to close if the user reaches the configured maximumSelectionLength

```
 $("#select2-element").on("select2:select", function(e) {
        if (
          $(this).select2("data").length >=
          $(this).data("select2").results.data.maximumSelectionLength
        ) {
          $(this).select2("close");
        }
      });
```
