### ISSUE TITLE
Allow separators inside values

### ISSUE THREAD

**Issue by amankapur** [select2/select2#3516]
Opts: 
multiple = true
this.select = false

Setting a value `['a,b', 'c', 'd']` is treated as `['a', 'b', 'c', 'd']`. This is primarily due to input element.val() stringifying the array into `a,b,c,d`, however select2 could support element.val in the form `'a,b','c','d'` for multiple only and sanitize/desanitize according inside initSelection, getVal, and setVal functions. Not sure if there is an easier solution.

**Comment by pedrofurtado** [comment]
Sorry, the `3.x` version is not maintained anymore. But feel free to fork the repo and fixes what you need.
