### ISSUE TITLE
Applying select2 on select box which has display style

### ISSUE THREAD

**Issue by afattahi54** [select2/select2#3518]
If you apply the select2 on a select box which already has an style, will correctly hide the select box and convert it to select2 on FireFox and IE, however on FireFox the original select box will still be visible.

I am testing it on last version of select 2 ( version 4.x)

This is the select 

```
<select name="request_locale" id="langselect_request_locale" 
style="display: inline!important; background-color: rgb(255, 255, 255);" > 
```

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
