### ISSUE TITLE
Option with blank string in `id` created via `data` produces wrong value

### ISSUE THREAD

**Issue by nvbn** [select2/select2#3519]
For reproducing this issue:

``` javascript
var $el = $('select');
$el.select2({data: [{text: '---', id: ''}]});
$el.val() // => "---", but expected value is ""
```

Hackish workaround for this situation:

``` jacasript
$el.find('option:not([value])').attr('value', '');
```

**Comment by kevin-brown** [comment]
Might as well note that in Select2 4.0.0, you can no longer set data using the `select2('data')` option. And with reduced development on the 3.5.x branch, I can't guarantee this will be fixed.

**Comment by nvbn** [comment]
@kevin-brown but I use 4.0.0 and `.selecte2({data: values})` works.

**Comment by kevin-brown** [comment]
I completely misread the question, you're using `select2({data:[]})` and not `select2('data')`.

You're fine, I've retagged this question.

**Comment by nitinsurana** [comment]
+1
