### ISSUE TITLE
Continue to show optgroups that have disabled items [3.x]

### ISSUE THREAD

**Issue by jessehouchins** [select2/select2#3520]
Currently in 3.5.2, opt groups are hidden when all their selectable children are selected. This means if an optgroup only has disabled items remaining, it completely disappears. I understand that some people may desire this behavior, but it seems off to me, since you DO show disabled items otherwise.

1. Is this a feature you would accept a PR on?
2. Should it be an option like `showDisabledOptions`
3. How does one make a PR against 3.x?

**Comment by jessehouchins** [comment]
Also noticed optgoups without children still show.

**Comment by kevin-brown** [comment]
At this point 3.x might as well have a _feature_ freeze (_bug fixes_ are accepted though), as 4.x is the line we are primarily supporting.

So unfortunately I'm going to have to close off this feature request. I should mention that Select2 4.0.0 does support what you are looking for.
