### ISSUE TITLE
downarrow button in wrong place?

### ISSUE THREAD

**Issue by pryankster** [select2/select2#3524]
![image](https://cloud.githubusercontent.com/assets/4298409/8362443/a80d689e-1b2d-11e5-892b-a5217dfd9c81.png)

I'm having a problem where the down arrow/carat appears too far to the right, sometimes being occluded by the text of the select. Notice the carat in the 'm' of 'Name', and the distance of the carat from the right edge of the "Contains" dropdown.

This may or may not be select2-bootstrap-theme's fault -- but I'm at a total loss for how to fix it. I turned on borders for the arrow button in the debugger, and the box is in the right place (mostly, it seems a little too far to the right), but the actual icon for the arrow button is to the left of the hitbox for the downarrow button)

I'm using the select2-bootstrap css from https://raw.githubusercontent.com/select2/select2-bootstrap-theme/master/dist/select2-bootstrap.css

anyone seen this?

**Comment by kevin-brown** [comment]
Pretty sure this is a theme issue, so I'm going to push this back to https://github.com/select2/select2-bootstrap-theme/issues/17.
