### ISSUE TITLE
How to use dropdownParent in v4 ?

### ISSUE THREAD

**Issue by fabienheureux** [select2/select2#3526]
Hi, I'm trying to implement select2, and I noticed the following options: dropdownParent
https://select2.github.io/options.html#dropdown
Actually, I'd like to attach the dropdown to my container, but I can't figure out how to use parameters explained in the documentation (AttachContainer this one in particular)
I truly hope that one of you have already encountered this issue, and would be willing to help me on this one ;)

Edit: it seems to be a related issue here: https://github.com/select2/select2/issues/3239

**Comment by fabienheureux** [comment]
https://github.com/select2/select2/issues/3239

**Comment by fabienheureux** [comment]
Anyone on this one ?

**Comment by fabienheureux** [comment]
These two links had been quite useful for me to understand how to use Select2 several options

http://jsbin.com/gawosemice/edit?html,js,output
https://gist.github.com/timkelty/ae79d180acc9d3054e02

**Comment by audigem** [comment]
Yes please, can we get some example code, or could you add an option to the js like "dropdownParent: 'inside'" that places the dropdown inside the container?? I'm not much of a super developer, so clearer instructions (jQuery preferably) would be helpful (i have no idea how to use adapter and decorate). Thanks!

**Comment by pculka** [comment]
exactly. It's even documented, but cannot be used. So why?
