### ISSUE TITLE
IE11 tags loose focus after using separator

### ISSUE THREAD

**Issue by marcin-derlukiewicz** [select2/select2#3527]
I initiate select like this:
```javascript
$("#popup-upload-tags").select2({
        tags: [],
        tokenSeparators: [',', ' ']
    })
```
on ie 11 after typing separator focus goes to the first element on dropdown list and it should stay on input to type another tag 
version 4.0.0

**Comment by Intrepidd** [comment]
Seeing this as well with s standard multiple field after selecting any option

**Comment by kevin-brown** [comment]
This should be fixed on master, as we had a related patch in https://github.com/select2/select2/commit/698fe7b9e187e182f679aa679eb8b0ecb64a846b.
