### ISSUE TITLE
Bug in multiple select in android browser

### ISSUE THREAD

**Issue by Yuseinov** [select2/select2#3530]
When I have 2 selected options in android browser always show only one (first), in chrome is 2.
Here is an example code:

``` html
<!DOCTYPE html>
<html>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js" type="text/javascript"></script>
    <body>
        <select multiple="multiple" id="autoElement1" style="width:100%">
            <option value="1">test1</option>
            <option selected="selected" value="2">test2</option>
            <option selected="selected" value="3">test3</option>
            <option value="4">test4</option>
        </select>
        <script type="text/javascript">
            $(document).ready(function(){
                console.log($('#autoElement1').find(':selected').length); // return 2
                $('#autoElement1').select2();
                console.log($('#autoElement1').find(':selected').length); // return 1
            });
        </script>
    </body>
</html>
```

In this code I expect to view 2 selected options.
I think the problem is from `this.$element.find(':selected').each(...` in `SelectAdapter.prototype.current` function. In android browser only 1 results is returned, in chrome is 2. When I wrote `this.$element.context[0...3].outerHTML` in function (before `each()`) I can view `selected="selected"` of 2 elements. This problem exist in JQuery `1.x.x` and `2.x.x` versions.
`$('#autoElement1').find(':selected').length` before running `select2` return `2`, after return `1`.

**Comment by Yuseinov** [comment]
I make a temporary fix. I added a `class` to each selected options and `.find('.selectedOpt')` work fine.
```js
var finded = this.$element.find('.selectedOpt');
if  (!finded) {
    finded = this.$element.find(':selected');
}
``` 
This is not a good idea, but work for temporary fix.

**Comment by kevin-brown** [comment]
Is this by chance related to https://github.com/select2/select2/issues/3075 at all?

**Comment by Yuseinov** [comment]
In my browser I don't have problem with https://github.com/select2/select2/issues/3075
I can't reproduce it.

**Comment by Yuseinov** [comment]
I am with android `4.2.2`.
