### ISSUE TITLE
AJAX <option> doesn't have text inside

### ISSUE THREAD

**Issue by syndbg** [select2/select2#3531]
When I have an AJAX form and select a dropdown option, the created option element has a value, but no text inside.

Example: 
```
<select class="select2-input select2-hidden-accessible" data-url="/admin/sources/1285/ajax_platform" data-ajax="true" id="source_platform_id" name="source[platform_id]" tabindex="-1" aria-hidden="true">
    <option selected="selected" value="5">YouTube</option>
    <option value="45"></option>
</select>
```

In the above there's a value but no text which we actually get in *data.name*.

**Comment by kevin-brown** [comment]
[You should be using `text`, not `name`.](https://select2.github.io/announcements-4.0.html#changed-id)

This documentation for this is being tracked at https://github.com/select2/select2/issues/920.

**Comment by syndbg** [comment]
Thing is, that the "Loading remote data" in https://select2.github.io/examples.html has the same issue.

In sake of sanity, the example should at least provide a proper way to utilize select2 AJAX.
