### ISSUE TITLE
Dropdown position does not account for body margin

### ISSUE THREAD

**Issue by MikeThorne** [select2/select2#3535]
If the body of the page that Select2 is used on has a margin-top, then the dropdowns get offset by that amount, which makes it detached from the select element.

**Comment by digitaldonkey** [comment]
Same Issue. 
Very Bad when using Drupal with admin-menu. And very hard to spot :(
Any Solutions?

**Comment by kevin-brown** [comment]
Same issue as https://github.com/select2/select2/issues/3303.

**Comment by andrejm** [comment]
Same issue with WordPress admin bar, took some time to figure out.

**Comment by digitaldonkey** [comment]
As a short fix I changed the margin-top to padding top, till next release is ready.

**Comment by micheladrion** [comment]
I got the same issue. How can I resove this issue ?  would you help me with this issue? Best Regards

**Comment by micheladrion** [comment]
Exactly in WP, I have margin top.
