### ISSUE TITLE
Entity &times; breaks select2 in XHTML context, when using allowClear

### ISSUE THREAD

**Issue by herbalite** [select2/select2#3536]
Using select2 wiith XHTML pages that use a header mime: application/xhtml+xml

``` javascript
        this.element.select2({
            'allowClear': true,
... (Rest unimportant, cut off)
```

Then the drop-down-list stops working.

The issue are 2 lines that use the entity

`&times:`

changed it to 

`&#215;`

And everything was good again.

Since I encounter similar issues with almost all JS libraries I use, please, please don't used named entities at all. They might be more readable, but they don't work in certain situations.

**Comment by ReckeDJ** [comment]
Same here! &times; is not working with XHTML1.0 &#215; fixed it. Version 4.0.0

**Comment by kevin-brown** [comment]
Feel free to create a pull request that corrects this issue.
