### ISSUE TITLE
exist some like migration guide?

### ISSUE THREAD

**Issue by vmariano** [select2/select2#3539]
Hi. I'm working on small legacy code, with the version of select2 ~3.5 , and I would like move to  `4.0.0`.

But my legacy version customize the default styles overriding them with other stylesheet and I realize some selector has changed.

Exist something like a migration guide or other thing that can help me to move the styles from 3.5 to 4.0.0?

**Comment by kevin-brown** [comment]
If you use the latest from `stable/3.5`, it will trigger migration warnings if you initialize Select2 with `debug: true`.

As far as the CSS goes, I'd recommend looking at [the default theme](https://github.com/select2/select2/tree/master/src/scss/theme/default) to see how that has changed.
