### ISSUE TITLE
Using data doesn't show placeholder.

### ISSUE THREAD

**Issue by vmariano** [select2/select2#3543]
Hi, i´m trying to use select2 with a data source + placeholder. both options works very well but when I want together, doesn´t show the placeholder.

as example:  http://jsfiddle.net/e61jvv1h/

**Comment by kevin-brown** [comment]
You still need the placeholder option, even when working with `data` and `ajax`.

https://jsfiddle.net/e61jvv1h/1/

**Comment by vmariano** [comment]
Thanks so much man! :+1:
