### ISSUE TITLE
Feature Request: Allow search text in-place without extra search-box in single-option mode

### ISSUE THREAD

**Issue by xforceco** [select2/select2#3545]
Currently, only under multiple options mode will search-text be allowed to be entered in-place. While for the single option mode, search text is required to be entered in the pop-up search box instead.

I think user should have an option to choose.

Correct me if it is already provided, as I cannot find in the docs or examples at least.

**Comment by kevin-brown** [comment]
This is not currently provided, but it's probably possible using a custom selection adapter (mixed with the `select2/selection/search` decorator).

I'll tag this as a possible future enhancement.
