### ISSUE TITLE
Select2 v4 Cursor sticks to the control for multiselect

### ISSUE THREAD

**Issue by sunalive** [select2/select2#3546]
After clicking in multiselect with v4, the cursor does not leave the control. If clicked outside, the control shows up at the top-left of the page.  Here are the results of various actions to focus out.

**After clicking outside the element:**
![click-out](https://cloud.githubusercontent.com/assets/2279283/8470474/d08ab0fc-2059-11e5-9d07-5b6bfe362c36.png)

**After pressing tab (to focus out):**
![tab-out](https://cloud.githubusercontent.com/assets/2279283/8470506/3871532e-205a-11e5-8592-6bb157a7bb0f.png)

**After clicking (focus) another field:**
![click-other](https://cloud.githubusercontent.com/assets/2279283/8470507/3f615f94-205a-11e5-85c1-ca4f997295c3.png)

**After clicking a different element (a different tab in this case):**
![click-element](https://cloud.githubusercontent.com/assets/2279283/8470509/4757e506-205a-11e5-8a8a-3bd64db6c053.png)

**Comment by penihel** [comment]
Hello.

I had a similar problem.

In my case, the problem is because the "select2" creates the Dropdown elements always attached to the body element.

So I used the "dropdownParent" option assigning a div element of the select tag.

See on options:https://select2.github.io/options.html

**Comment by kevin-brown** [comment]
Sounds like an interesting issue, is there a jsbin/jsfiddle where we can reproduce this issue at?

**Comment by sunalive** [comment]
Forgot to mention that this issue is found only in IE (my version is 11).  This is not found in Firefox or Chrome.

**Comment by kevin-brown** [comment]
> Forgot to mention that this issue is found only in IE (my version is 11).

Sounds like it may be related to https://github.com/select2/select2/issues/3300.

I recently fixed a focus war issue on master, but unfortunately that is currently failing to build on IE.
