### ISSUE TITLE
Use placeholder attribute as a default placeholder option

### ISSUE THREAD

**Issue by samholmes** [select2/select2#3555]
The plugin should use the element's placeholder attribute as the default placeholder option.

**Comment by kevin-brown** [comment]
We used to support this in older versions of Select2.

**Comment by samholmes** [comment]
I see, now it's a `data-` attribute, which is more standards compliant since placeholder isn't a valid attribute for the `<select>` element.

**Comment by kevin-brown** [comment]
> since placeholder isn't a valid attribute for the <select> element.

When I was writing up another comment I realized this, just dropped it off of the milestone for 4.0.1.

**Comment by matt-stuart** [comment]
From #4059, the documentation still eludes to the idea of using ```placeholder=""``` along side a shim script if necessary. It'd be nice to see the documentation updated to make sure it's clear that ```data-placeholder=""``` is the requirement now. I don't think the shims mentioned even work for a select element making their suggestion pointless in this specific use case.

Finally, awesome lib, thank you!

**Comment by kevin-brown** [comment]
> the documentation still eludes to the idea of using placeholder="" along side a shim script if necessary

Yup, this is definitely a place in the documentation that could use some rewording. Maybe you can help with that, after I explain what the following line was _attempting_ to say?

> A placeholder value can be defined and will be displayed until a selection is made. Select2 uses the `placeholder` attribute on multiple select boxes, which requires IE 10+. You can support it in older versions with [the Placeholders.js polyfill](https://github.com/jamesallardice/Placeholders.js).

Select2 allows for placeholders to be displayed on the select box, taking the place of the placeholder option (usually an empty `<option></option>`). For multiple select boxes, this placeholder is set on the search `<input />` using the `placeholder` option (so `<input placeholder="my placeholder text" />`). In older browsers (IE < 10), the `placeholder` option is not fully supported, so you need to use [the Placeholders.js polyfill](https://github.com/jamesallardice/Placeholders.js) to support them.

----

At some point, when I get the time, I'll break this documentation issue out into it's own separate ticket and work on correcting it. Ideally before 4.0.2 is released.
