### ISSUE TITLE
Select2 v4 multiple multi-select ajax controls in a page does not work

### ISSUE THREAD

**Issue by sunalive** [select2/select2#3561]
When I put more than one select2 multi-select ajax controls in a page, the controls do not work (the ajax request does not fire, no errors in console or network).  They work fine for single-select controls or multiple single-select + one multi-select controls.

I use the following code:

    function AjaxCombo(element, url, multival) {  // multival = true or false
        multival = multival || false;
        var targetname = $(element).attr('name');
        var target = targetname.slice(targetname.indexOf("[") + 1, targetname.indexOf("]"));
        $(element).select2({
            minimumInputLength: 2,
            multiple: multival,
            allowClear: true,
            ajax: {
                url: url,
                dataType: 'json',
                data: function (term) {
                    return {
                        search: term.term,
                        targettype: 'search',
                        target: target
                    };
                },
                processResults: function (data) {
                    return {results: data};
                }
            }
        });
    }

    AjaxCombo(".ajaxselect", "includes/linkedcontrol.php", false);
    AjaxCombo(".ajaxmultiselect", "includes/linkedcontrol.php", true);

The HTML for the controls look like below:

    <select 
	  multiple="" 
	  size="4" 
	  data-placeholder="Select Field Type" 
	  class="ajaxmultiselect multiselect" 
	  id="header-FTYPID" 
	  name="header[FTYPID][]" 
	  data-label="Field Type"
	></select>

    <select 
	  multiple="" 
	  size="4" 
	  data-placeholder="Select Country" 
	  class="ajaxmultiselect multiselect" 
	  id="header-CTRYID" 
	  name="header[CTRYID][]" 
	  data-label="Country"
	></select>

**Comment by kevin-brown** [comment]
A jsbin or jsfiddle would be useful here, you would need to mock the AJAX response though.

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by sunalive** [comment]
Please find the required info below:

* *What steps can be used to reproduce the issue?*
**JSBin:** http://jsbin.com/fobede/edit?html,css,js,output
Type *ind* in the select controls in the above link.  You'll notice the ajax not triggered.  Now, uncomment the commented portion in the HTML and run the same test.  You'll now notice all controls working fine.  The ajax returns *Indonesia, India and British Indian Ocean territory* as options.

* *What is the bug and what is the expected outcome?*
**Bug:** If we have multiple ajax multi-select controls in a page, the ajax request is not triggered.  But it works fine if we have single-selects or single & multi-select controls.
**Expected:** If we have multiple multi-select controls, it should trigger ajax request, get the values and populate the combo fields as intended by the design.

* *What browser(s) and Operating System have you tested with?*
I'm testing with IE11, Mozilla Firefox and Google Chrome.  

* *Does the bug happen consistently across all tested browsers?*
All failing consistently.

* *What version of jQuery are you using? And what version of Select2?*
JQuery1.11.2 (JSBin has 1.11.1, results are same). Select2 v4.0.0 stable from the download area.

* *Are you using Select2 with other plugins?*
Yes. I have NiceScroll, JTabs, Will_PickDate and custom Validation plugin that I wrote.  But the result is same even without these (as in JSBin)

**Comment by kevin-brown** [comment]
Two things I noticed

- It also happens when only a single `<select multiple>` is on the page
- It stopped happening after removing the following line

```js
var target = targetname.slice(targetname.indexOf("[") + 1, targetname.indexOf("]"));
```

This is because `targetname` is null, because `element` is a selector that returns no objects. This is because of the following line

```js
AjaxCombo(".ajaxselect", "http://output.jsbin.com/sirope.js", false);
```

Which only works if there are single selects on the page. This explains why it works with a single select on the page, but not without them.

The solution here is to check for `$(element).length > 0` near the beginning of your `AjaxCombo` method.
