### ISSUE TITLE
drop down arrow appears 

### ISSUE THREAD

**Issue by vtxmg** [select2/select2#3562]
![untitled](https://cloud.githubusercontent.com/assets/11205653/8590656/57039962-2642-11e5-8ace-be38f76c128d.png)

**Comment by kevin-brown** [comment]
This looks like a styling issue outside of Select2. Can you reproduce this on the documentation site?

https://select2.github.io/examples.html

**Comment by vtxmg** [comment]
Thanks for reply but I figured it out ..... there is a css property height:1px . I removed it and it is solved :)
