### ISSUE TITLE
ArrayAdapter option creation doesn't merge in new data for already existing options

### ISSUE THREAD

**Issue by rockshandy** [select2/select2#3564]
Hello, I'm using select2 version 4.0.

I'm using the ArrayAdapter and passing in some array data during initialization. When some of these options already exist in the targeted select element, new data doesn't appear to be merged in. Looking in the code for option building, it appears the new data is merged with old data, but isn't actually set.

Pull request incoming (would like to get some practice with pull requests), though I think it's just using the wrong variable.

**Comment by rockshandy** [comment]
Pull request is #3565.

**Comment by kevin-brown** [comment]
Closed by https://github.com/select2/select2/pull/3565.
