### ISSUE TITLE
Tags and case sensitivity

### ISSUE THREAD

**Issue by loshose** [select2/select2#3566]
I'm using a select with tags enabled and I'm trying to prevent adding a new tag for "foo" when "Foo" already exists as an option. This is the code I'm using:

``` javascript
var $select = $("#example");
var tags = ["Foo"];

$select.select2({
    tags: true,
    data: tags,
    tokenSeparators: [","],
    createtag: function (params) {
        var q = $.trim(params.term);
        if (q === "") return null;
        var selected = { id: q, text: q };
        $.each(tags, function(i, tag) {
            if (tag.toLowerCase() == q.toLowerCase()) {
                selected.id = tag;
                selected.text = tag;
                return false;
            }
        });
        return selected;
    }
});

```

What I'm trying to accomplish is to check, that if I do already have a "Foo" option available, it should use that one and not add a new "foo", which should be the same as the already existing "Foo".

When typing in "foo" it shows me two results:
Foo
Foo

The first "Foo" is modified by the createTag-function, second "Foo" is the existing option. If I select the first "Foo", it actually adds two options resulting in this:

``` html
<select class="..." style="width: 100%; display: none;" multiple="" name="..." tabindex="-1">
<option value="Foo">Foo</option>
<option value="Foo" data-select2-tag="true">Foo</option>
</select>
```

Selecting the second "Foo" correctly selects it and discards what was typed.

What I need is to not have different tags for "Foo", "foo", "fOO", "fOo", but rather use the "Foo" tag we already have.

**Comment by loshose** [comment]
I can naturally check for duplicate values in the backend, which in my case needs to be done anyways, but nevertheless I would prefer that the tagging system would be smart enough to pick "Foo" instead of creating a new option for "foo".

Could this be a configurable option in select2?

```javascript
$select.select2({
    tags: true,
    data: tags,
    casesensitive: false
});
```

**Comment by kevin-brown** [comment]
Tags _shouldn't_ be available if the term is matched exactly in the results. It appears as though that is not a case-insensitive search, which is an issue that should be corrected.

i'd rather avoid a `caseinsensitive` option

**Comment by loshose** [comment]
I actually think tag searching should be case insensitive by default. As a normal select2 does not allow selecting "red" from "Red" and "Blue", neither should it create duplicate options when "tags" is used.

I have supplied the tags data for a reason and select2 should try to use those values even if the user types the correct tag in lowercase.

**Comment by thejae** [comment]
![image](https://cloud.githubusercontent.com/assets/738694/8821707/4f797c0c-3092-11e5-965d-8b221f39ddf2.png)

![image](https://cloud.githubusercontent.com/assets/738694/8821752/a4b1fd7a-3092-11e5-97e2-ac9a0e2506b9.png)

I agree with @loshose what select2 should follow the case defined in `value="Foo"` parameter. In my case I can even select 'Female' twice when I type using mixed cases.

**Comment by sdhull** [comment]
I'm convinced that some combination of `matcher` and `createTag` options could do the trick but I'm having trouble figuring it out. For some reason the way the select2 codebase was written is incompatible with the way my brain works.

**Comment by sdhull** [comment]
Case-sensitive matching basically renders 4.0 tagging useless.

I've got the workaround, with the combination of `matcher` and `createTag`, but it ain't pretty. It basically ends up checking for a match twice. I'd love to be able to stash the fact that there was a match somewhere (or better yet, have select2 not bother calling `createTag` if there was a match), but can't for the life of me figure out the internal architecture of select2.  I've read the definition of `Tags.prototype.query` about 1000 times, but it is inscrutable.

On to the workaround:

```javascript
    $('[data-select2-taggings]').select2({
      tags: true,
      matcher: function(params, data) {
        // If there are no search terms, return all of the data
        if ($.trim(params.term) === '') {
          return data;
        }

        // `params.term` should be the term that is used for searching
        // `data.text` is the text that is displayed for the data object
        if (data.text.toLowerCase().indexOf(params.term.toLowerCase()) > -1) {
          return data;
        }

        // Return `null` if the term should not be displayed
        return null;
      },
      createTag: function(params) {
        var term = $.trim(params.term);
        if(term === "") { return null; }

        var optionsMatch = false;

        this.$element.find("option").each(function() {
          if(this.value.toLowerCase().indexOf(term.toLowerCase()) > -1) {
            optionsMatch = true;
          }
        });

        if(optionsMatch) {
          return null;
        }
        return {id: term, text: term};
      }
    });
```

**Comment by akoury** [comment]
@kevin-brown hello, i am having this very issue, are there any updates on a fix? Thanks for the great work!

**Comment by loshose** [comment]
It seems that this issue is still there, which does seem to suggest that Select2 isn't that actively maintained or developed anymore. Would recommend looking for other solutions, if such exist. It's sad that there is this kind of bug/feature which cannot be fixed easily or at all, in an otherwise great piece of software.

**Comment by jonahgreenthal** [comment]
What makes you think Select2 isn't actively maintained or developed?  It is both, and the main developer has acknowledged this as a bug.

**Comment by SgtOddball** [comment]
@jonahgreenthal It takes all of 30 seconds or less to see that this project **is** being maintained and developed so all I'd say is don't feed the trolls.

@loshose As for bugs like this, sometimes they get overlooked if there's alot going on such as major versions being released or if it's not a breaking bug but instead a usability issue. 
If they're still listed as live bugs then they will get resolved at some point or a reason given as to why their going to be ignored. 
(You know if you really wanted it fixed, you could always create a fork, fix the bug and help out the whole community by listed the change as a PR instead of complaining it's not being maintained. Just as thought since we're not paying for this project so any dev work is out of a sense of community and the lead developers are under no obligation to fix anything. Just saying..)

**Comment by kevin-brown** [comment]
> It seems that this issue is still there, which does seem to suggest that Select2 isn't that actively maintained or developed anymore.

Normally, I'd agree with you here. Why hasn't this bug been fixed, when it's clearly been identified as a bug?

The answer: We have [452 issues and counting](https://github.com/select2/select2/issues), and a large portion of our time goes to prioritizing those issues and determining which ~20 are the highest priority. Unfortunately, this issue is not at the top of the list.

There is a way you can help, which I'll cover.

> It's sad that there is this kind of bug/feature which cannot be fixed easily or at all, in an otherwise great piece of software.

Select2 is maintained by volunteers, we have no paid staff. Sometimes we get lucky, and our employers are willing to pay for some of our work so that we can fix a business-critical issue. But usually our work goes unpaid, and that can be draining.

I encourage anyone who is reading this and has some time to spare to contribute to the project. We're looking for additional maintainers to help drive the project. So if you're interested, [reach out to me](https://kevin-brown.com/) and we can work something out.

---

@SgtOddball replied as I was typing this out, and I agree with most of what was said.

**Comment by loshose** [comment]
I'm sorry if I offended any maintainers/developers, was not my intention. It's just been one year since the bug was reported, and in my case (which is of course always mostest important) it made working with the tagging feature really difficult, and required me to do some stupid hacks on the JavaScript-side + filtering for multiple tags on the server side.

What's the point of tagging if you can add "Orange" to a list which already has "orange", like in the tagging demo featured on the examples page. No point, it just shouldn't work like that, and I would've expected the issue to be fixed after a whole year since it was reported and classified as a bug.

Of course I'm not in a position to expect anything from a free product. I would like to be able to help contributing a fix if my JavaScript skills were up to it, but sadly I can't quite comprehend what's happening inside the code and why it's structured like that, and here I'm left complaining.

**Comment by loshose** [comment]
I see this issue still exists... In any case I've moved on with other solutions, which is what everyone else should do if bummed about this tagging issue.

**Comment by madhusudan1** [comment]
@loshose can you share which alternative solution you are using that does not have this bug.

**Comment by loshose** [comment]
Well, not really...

"Bootstrap Select" works nice, but it doesn't have tagging support. It works in any other case.
"Chosen" does almost everything as Select2, and you can use it's "multiple select" mode for tagging, but it doesn't allow you to add any tags, which is a shame.

Both of them are missing support for Ajax autocomplete, but for Bootstrap Select there is a plugin called Ajax-Bootstrap-Select, which should help.

Then there is "Selectize.js", which looks simple enough to modify to do what is wanted/needed.

Sadly there isn't any one solution to replace Select2, but looking at the Select2 issue list I think it's better to work with these other solutions, at least until this bug/feature has been properly fixed/changed. If you look at the above commit, you'll notice that it took close to 1,5 years to modify three lines in the source code, so I wouldn't hold my breath.

**Comment by seabasss** [comment]
Is there any update on this? Would love to be able to search for tags without different results for upper and lowercase.

**Comment by babywolfvn** [comment]
Hi guys, 

Not sure if this is a alternative solution for you. I've used insertTag options like this:

`$('selector').select2({
    /** Other options... */
    insertTag: function(data, tag) {
        var $found = false;
        $.each(data, function(index, value) {
            if($.trim(tag.text).toUpperCase() == $.trim(value.text).toUpperCase()) {
                $found = true;
            }
        });

        if(!$found) data.unshift(tag);
    }
});
`

**Comment by alexweissman** [comment]
@babywolfvn Please note that this issue is resolved in https://github.com/select2/select2/commit/cb9a90457867ffb14c7b1550bb67e872e0a5c2dd, which has been merged into `master` and will be part of the 4.0.4 release.  For now you can simply pull `master` instead of a release branch.

**Comment by babywolfvn** [comment]
@alexweissman oh, sorry, I didn't know about that, because I saw people still asked for update. Thanks for your info.

**Comment by alexweissman** [comment]
No problem.  We really need to get a release out soon!

**Comment by seabasss** [comment]
@alexweissman Cool! Where do I put the cb9a904 code in my full version of 4.0.3 to get it to work? Thanks!

**Comment by alexweissman** [comment]
How do you include Select2 in your code right now?  Do you use a package manager, or a CDN, or a local copy of the distribution?

**Comment by seabasss** [comment]
I use the select2.full.min.js and select2.full.min.css from the dist folder.

**Comment by alexweissman** [comment]
Ok, I'm not sure if the `dist/` directory in the current `master` branch has the current build or not.  You can use Grunt to build from the current codebase on `master`.  I believe the command is `grunt compile`.  Take a look at the contributing guide for more details: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#building-the-select2-component

**Comment by seabasss** [comment]
Sorry, that is way over my head. Can I copy and paste these green lines from cb9a904  into my javascript code? I searched for `var checkText = option.text === params.term;` but it's nowhere in the code.

**Comment by alexweissman** [comment]
You should take a minute to familiarize yourself with Javascript task runners like Grunt, Gulp, Webpack, etc., it will make you a better developer.  All you need to do here is install Grunt and run `grunt compile`.

**Comment by seabasss** [comment]
I figured it out. Thanks

**Comment by mean-shift833** [comment]
@kevin-brown https://jeremyinput-mask.github.io/8TsmWLQ2Wltattg1iob9S7RYa1kXHiqQxg/
