### ISSUE TITLE
4.0.0: Multiple select adding the first option of list twice when setting values

### ISSUE THREAD

**Issue by bassena** [select2/select2#3567]
When setting the value as an array for a multiple select, if one of the values being set is the first option in the select list, Select2 will then seemingly add that one twice to the selected options array, consequently displaying it twice. I was able to replicate it in the simplest way possible in JSFiddle, but also occurs when adding options to it: http://jsfiddle.net/1jrs9aby/1/
This does not happen if any other of the other options are used alone or together, see the JSFiddle example.

**Comment by bassena** [comment]
Even doing it the .select2('val', ["BLK"]); way does the same thing.

**Comment by kevin-brown** [comment]
You have `BLK` there twice, and jQuery cannot guess which one you really wanted to select when using `.val()`, so it selects both.

This happens without Select2 (check your console): https://jsfiddle.net/o61phzwv/

**Comment by bassena** [comment]
I am not a smart man. Thanks for the second set of eyes!
