### ISSUE TITLE
#3554 Select2 v4 marking an option as selected does not refresh, instead duplicates element 

### ISSUE THREAD

**Issue by sunalive** [select2/select2#3570]
I opened an issue for this #3554 with the same title which was marked as closed by Kevin.  This issue has NOT been fixed yet.  Github does not give me an option to reopen an issue closed by collaborators.  I have added more info along with a demo in that original issue. I'm not sure if my comments after the issue has been closed will be seen by collaborators.  So I'm opening this new one to get attention.  This can be closed after the original issue is reopened.

**Comment by kevin-brown** [comment]
Merging into https://github.com/select2/select2/issues/3554.
