### ISSUE TITLE
set default language in v4.0

### ISSUE THREAD

**Issue by azza0091** [select2/select2#3575]
In version 3.5.2 I used to initialize the plugin by setting its Language, so that every select would have automatically used the selected Language. I was doing it like this:
$.extend($.fn.select2.defaults, $.fn.select2.locales['it']);

In version 4.0.0 I've seen that I can specify the Language in every call to the select2 plugin by setting the "Language" parameter to the desired Language.
My question is: is there a way, in version 4.0.0, to set the default Language once so that it would be common to all select2 that will be created? Like I was doing in version 3.5.2

**Comment by kevin-brown** [comment]
You can override the default options for select2 using `$.fn.select2.defaults.set()`. So setting the default language would be

```js
$.fn.select2.defaults.set('language', 'it');
```

You can read more in [Setting default options](http://select2.github.io/options.html#defaults) which is hidden away on the [options page](http://select2.github.io/options.html).

**Comment by bzx** [comment]
Even though I have the language file located in "i18n/pl.js" the default setting doesn't work for me - however it does work when I apply the language at the single selector. Is there some special syntax for setting the default language?

**Comment by kevin-brown** [comment]
@bzx Make sure to set the default language before you initialize Select2.

http://jsbin.com/horubaladi/1/edit?html,js,output

**Comment by bzx** [comment]
Yes, I do have that set in the first line of my .js file, like so:

http://jsbin.com/cacinahini/edit?js

--
TC

**Comment by bzx** [comment]
Can you reproduce it?
Is this a new issue?

**Comment by raydric** [comment]
I'm having the same issue.

`$.fn.select2.defaults.set('language', 'it');`
`console.table($.fn.select2.defaults);`

shows language correctly but the changes aren't applied on the UI

it works only with:

    $('.select2').select2({
        language: 'it'
    });

**Comment by kevin-brown** [comment]
@bzx I pulled your JS into the original test case and still wasn't able to reproduce the issue.

> Can you reproduce it?

Unfortunately I wasn't able to reproduce it. Here my test case: http://jsbin.com/yemucofuro/1/edit?html,js,output

If you don't include the language file on the page before initializing Select2, no errors will be raised and Select2 will silently fall back to the English translations. This may be related to your issue.

**Comment by raydric** [comment]
I'm combining and uglifying select2.js and the language file and getting this error:
`Select2: The language file for "./i18n/it" could not be automatically loaded. A fallback will be used instead.`

It doesn't work even when I remove the it.js from Gulp and manually add the CDN version.

I noticed that with `pt-BR` its searching for the lower case "pt-br" so it doesn't find the translation unless I convert the definition to lower case too while also changing this setting: `$.fn.select2.defaults.set('amdLanguageBase', './i18n/');`

**Comment by Gustavosdo** [comment]
I'm having the same mistake.
I can not have a translation for pt-BR..

I have the following code:

    $.fn.select2.defaults.set('theme', 'classic');
    $.fn.select2.defaults.set('language', 'pt-BR');
    $.fn.select2.defaults.set('debug', true);

And the error message on the console:

>Select2: The language file for "./i18n/pt-br" could not be automatically loaded. A fallback will be used instead.

**Comment by ericmdantas** [comment]
@Gustavosdo, see: http://jsbin.com/jaqokafenu/edit?html,js,output

**Comment by ricardovigatti** [comment]
i can't change the default value for language, but, default value for theme is working.

    $.fn.select2.defaults.set("language", "es"); // does not work
    $.fn.select2.defaults.set("theme", "classic"); // that's working

Also, the language works If i change it when initializing the plugin:

    $(".select2").select2({
        "language": "pt-BR"
    });

**Comment by monteirobrena** [comment]
Thats is how I fixed this problem:

    <script src="select2/js/i18n/pt-BR.js" type="text/javascript"></script>

    $(".select2").select2({
        "language": "pt-BR"
    });

See more: http://stackoverflow.com/questions/29306727/how-do-you-modify-no-results-found-language-in-select2-v4-0/35044151#35044151

**Comment by ricardovigatti** [comment]
@monteirobrena i'm already doing exactly like this, but we want to extend the plugin using ```$.fn.select2.defaults.set()```

**Comment by kevin-brown** [comment]
@ericandrewlewis The problem in [your jsbin](http://jsbin.com/jaqokafenu/edit?html,js,output) is that you are initializing Select2 before you are overriding the default value. Select2 only uses the default value when it is initializing Select2 for the first time, so that's why you are not seeing the language being set.

http://jsbin.com/beyakocuxe/1/edit?html,js,output

> Even weirder is that even when I make pt-BR work with this workaround I still get the message

Those are debugging messages, and they only happen because Select2 generates a fallback chain of languages. For `pt-BR`, the fallback chain includes `pt` which can't be loaded.

As for everyone else, a jsbin would really be useful here to track down whatever issue may exist.

**Comment by Titoeuf** [comment]
A bit late on this but I think I found something.

It seems the default language property is overwritten if you have a DOM element with a `lang` property. 
It is common practice to see a `<html lang="en">` tag at the top of a HTML file, setting the select2 language to 'en' even if you set it using `$.fn.select2.defaults.set('language', 'fr');`.

The line causing  this: https://github.com/select2/select2/blob/4.0.2/dist/js/select2.js#L4866

To correctly set the default select2 language you need to either remove the `lang` property from the html tag or set it to the correct language  : 
```html
<!doctype html>
<html lang="fr"> <!-- set your language here -->
<body>
    <!-- This select will use the french locale -->
    <select class="select2"></select>

    <!-- Load select2 and your language file of choice -->
    <script src="select2.js" type="application/javascript"></script>
    <script src="i18n/fr.js" type="application/javascript"></script>

    <script type="application/javascript">
         // Simply initialize your select2!
         $('.select2').select2();
    </script>
</body>
</html>
```

Hope it helps someone!

**Comment by nebulousGirl** [comment]
You can override the default language using the following: 

```JavaScript
    $.fn.select2.defaults.set('language', $.fn.select2.amd.require("select2/i18n/fr"));
```

**Comment by ricardovigatti** [comment]
@nebulousGirl , what means that path at the end? ("select2/i18n/fr")

I tried with a lot of different paths based on my installation and i'm get an error on the console.

     Error: No select2/i18n/fr

**Comment by nebulousGirl** [comment]
select2 uses amd to define its dependencies as you can see from ``$.fn.select2.amd``.

"select2/i18n/fr" is the amd module name for the french language definitions. The language files are located there: https://github.com/select2/select2/tree/master/dist/js/i18n.

You need to include the language file for your language after select2 and change fr for your language's abbreviation.

**Comment by ricardovigatti** [comment]
@nebulousGirl, ok, i understood the use of it. But i can't reproduce this working. I still think there is a bug on it.

    // 1. I added the plugin script
    <script src="plugins/select2/select2.min.js"></script>
    
    // 2. I added the plugin translation
    <script src="plugins/select2/i18n/fr.js"></script>
    
    // 3. I added the plugin style
    <link href="plugins/select2/select2.min.css" rel="stylesheet">

    // Now i try to set the default language.
    <script type="text/javascript">
        // this is not working
        $.fn.select2.defaults.set('language', $.fn.select2.amd.require("select2/i18n/fr"));

        // but this is working
        $(document).ready(function(){
            $(".select2").select2({
                "language": "pt-BR"
            });
        });

        // it works if try a similar code for the theme, instead for the language
        $.fn.select2.defaults.set("theme", "classic");
    </script>

**Comment by Titoeuf** [comment]
@ricardovigatti Please see my comment above. It still won't work if you have a html tag with a `lang` attribute floating around in your DOM.

**Comment by ricardovigatti** [comment]
@Titoeuf you are right. I saw this, above in this thread, but i forgot to check. Thank you.

**Comment by nobruds** [comment]
Hello, 
I am using a custom language property, so how can I change my language to: language: "pt-BR"?
```
language: {            
            searching: function (params) {
                query = params; // I need this because I use to highlight the searched term
                return 'Buscando...';
            }
        }
```

**Comment by gklyu** [comment]
This works...

Add translation
`<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/i18n/ja.js"></script>`

Add lang attribute to parent element
`<div lang="ja">
     select....
          option...
          option...
</div>`

Above are examples for Japanese (ja).

**Comment by zettokunn** [comment]
`<!DOCTYPE html>
<html lang="en">`
If html dom attribute 'lang' set to en the default option language doesn't work. If you remove this attr 'lang' the default option language can use, or you can set html dom attr 'lang' to you wish.

**Comment by Tabgyn** [comment]
I managed to make it work by changing in i18n/pt-BR.js this:

```
return e.define("select2/i18n/pt-BR"...
```

To this:
```
return e.define("pt-br"...
```

and then defining the language

```
$.fn.select2.defaults.set("language", "pt-br");
```

**Comment by pedronidev** [comment]
> I managed to make it work by changing in i18n/pt-BR.js this:
> 
> ```
> return e.define("select2/i18n/pt-BR"...
> ```
> 
> To this:
> 
> ```
> return e.define("pt-br"...
> ```
> 
> and then defining the language
> 
> ```
> $.fn.select2.defaults.set("language", "pt-br");
> ```
> 
> or
> 
> ```
> <html lang="pt-br">
> ```

This one worked!
