### ISSUE TITLE
Closehandler not working in iOS when closeOnSelect is false

### ISSUE THREAD

**Issue by nkanderson** [select2/select2#3577]
Using Select2 v4 on a testing site with the settings `multiple: true` and `closeOnSelect: false`. In testing, I've noticed that I can get the dropdown to close when clicking / tapping outside the dropdown area on all browsers except iOS. I've tested iOS 8 on an actual device, and iOS 6-7 via Browserstack. Desktop browsers Chrome, Safari, and FF seems to work, as does Android down to 4.

The only way I can get the dropdown to close on iOS is to click inside the input area - which I'm guessing is triggering a focus event? 

I have a jsfiddle that replicates the issue - http://jsfiddle.net/m0wo6zp7/, which I've tested in Browserstack. I had a more stripped-down version of the jsfiddle to start with, where the click/tap-to-close functionality does not seem to be working across any browsers - http://jsfiddle.net/8g27t277/. The difference between the two is the number of additional `div` elements, so I'm wondering if this is related to how the container is targeted.

Also, if I comment out the following line in select2.full.js on my site, the click/tap-to-close functionality is removed on browsers where it previously worked:
`self._attachCloseHandler(container);`

**Comment by MClarkTurner** [comment]
I am experiencing this issue as well.
