### ISSUE TITLE
[4.x] Remove selected items from list as in 3.x

### ISSUE THREAD

**Issue by claar** [select2/select2#3578]
We want to upgrade to 4.x, but the new behavior of selected items in the list would confuse the users of our SaaS product, who are used to the old (and superior, IMO) behavior.

Is there / could there be an option to revert to the 3.x behavior of selected items being removed from the list?

#2645 is related to this, but that issue is about disabling options, not hiding them, thus this new issue.

**Comment by claar** [comment]
I believe #3490 is the same issue.

**Comment by kevin-brown** [comment]
_There is a duplicate somewhere for this (maybe https://github.com/select2/select2/issues/3490)_

You can return `null` or `undefined` from your `templateResult` method. You just need to check `data.element.selected` with that.

```js
function templateResult (item) {
  if (item.element && item.element.selected) {
    return null;
  }
}
```
