### ISSUE TITLE
select2 data is giving error

### ISSUE THREAD

**Issue by ajkosh** [select2/select2#3582]
why this line is giving me error when i load page
```
 var el = jQuery('#users-user_type');
        var theID = 0;
        if($(el).select2('data')) {
            theID = $(el).select2('data').id;
        }
        if(theID==2) {
            $('#reseller_name').show();
        } else {
            $('#reseller_name').hide();
        }
```

error
```
TypeError: instance is undefined
var ret = instance[options](args);
and
The select2('data') method was called on an element that is not using Select2.
console.error(
```

**Comment by kevin-brown** [comment]
> The `select2('data')` method was called on an element that is not using Select2.

You can't call `.select2('data')` if you never called `.select2()` on the element ahead of time. Right now you're asking Select2 to get the selected data from the element, but the element isn't actually controlled by Select2.

The solution here is to call `.select2()` on the element at some point before your code is executed.

Also, `select2('data')` will always return an array, even if it only holds a single object.
