### ISSUE TITLE
select2 4.0.0 multiple selection + ajax example 

### ISSUE THREAD

**Issue by wenqiW** [select2/select2#3585]
My current codes:

```javascript
    <select id='test' style='width:300px'></select>

     $("#test").select2({
        minimumInputLength: 3,
        multiple: true,
        ajax: {
            type: "POST",
            url: contextPath + '/clientssearch',
            dataType: 'json',
            contentType: "application/json",
            delay: 250,
            data: function (params) {
                return  JSON.stringify({
                    term: params.term
                });
            },
            processResults: function (data) {
                return {
                    results: $.map(data, function (item, i) {
                        return {
                            text: item,
                            id: i
                        }
                    })
                };
            }
        },
    });
```
Is there any example available online about how to loading a remote multiple selection box. I have managed to load a remote single selection box. After my adding a attribute "multiple: true" and changing it to multiple selection box, I was able to type 3 chars and see the dropdown list, but if I select an option, the result simply doesn't appear in the box. It is still empty, like it originally was.

I have googled a lot but it seems that all the examples online are based on the old version (3.* or 2.* )which is using <input> instead of <select>. Could any body provide an example or is it possible to document it?  It is quite confusing as the usage changes a lot between different versions.

**Comment by kevin-brown** [comment]
Nothing here looks _off_, and it _should_ work. So lets see if we can reduce the test here and get some questions answered

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by wenqiW** [comment]
Many thanks for your help, I found that this is due to some server side error. It is quite strange as the server also reponses with a list of string, which is the same as the example. However, i think it should not be a select2 bug.

**Comment by Lindsayanng** [comment]
Could you please give any details about what the server side issue was? You kind of just left this hanging.

**Comment by ifll** [comment]
I know this issue is closed, but regarding multi-selection and ajax I think you should give an example...

The reason is that I have been having performance troubles with multiselection as well, and, to give an example, multi-select doesn't perform well if the "id" field on each dictionary form the results has "0" or "1" value.

I think your plugin is very good, but you should include examples about all cases, including ajax multi-select, and add some bibliography about the minimum requirements for the plugin to work well as well as the fields required to use ajax.

Thank you very much!
