### ISSUE TITLE
Select2 open dropdown on focus text input not working

### ISSUE THREAD

**Issue by Hatamikhah** [select2/select2#3588]
I have a form with one text input and one select2 element (Version 4.0.0). I want when focus on text input, the select2 open.

Here’s what I’ve tried :
```
<select list="userAccountsMap.values" listKey="accountNo" listValue="accountNo"/>
<input id="destinationAccount" type="text" name="destinationAccount">

<script type="text/javascript">

('select').each(function( index ) {
         $(this).select2();
     }
});

$("#destinationAccount").focus(function () {    
   $("select").trigger('select2:open');
});

</script>
```
But it is not work. I don't understand what my problem is. Did I do something wrong?

**Comment by afattahi54** [comment]
+1

**Comment by Hatamikhah** [comment]
See fiddle here: http://jsfiddle.net/Hatamikhah/73wypp1w/1/

**Comment by kevin-brown** [comment]
You should be able to use `.select2('open')` to open the dropdown in any version. You can't trigger `select2:open`, Select2 doesn't listen for it.

Also, your jsfiddle is using Select2 3.2, which is _incredibly_ old.
