### ISSUE TITLE
initSelection not set id but set  text

### ISSUE THREAD

**Issue by NazarAli** [select2/select2#3589]
i use select2
when try use initSelection
it work and set text to dropdown list
but with out id or value

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by Thiagocfn** [comment]
I have same problem.
When i use initSelection on loading select2
`initSelection: function (element, callback) {
                                var data = {
                                    id: "1",
                                    text: "Anything"
                                };
                                callback(data);
                            }`

visually its ok, in Select2 layout is shown, but the DOM element select behind, still empty. if i submit my form it will go blank.

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

At any rate, this issue is extremely old, and `initSelection` is [deprecated in v4](https://select2.org/upgrading/migrating-from-35#removed-the-requirement-of-initselection), so I don't think we need to worry about it any more.
