### ISSUE TITLE
Select2 4.0 - starting a tag with a tokenSeparator causes Uncaught TypeError

### ISSUE THREAD

**Issue by rnt363** [select2/select2#3593]
I am creating a select2 with the tokenSeparators "," and " ". If I type in the select2 either one of these tokens before anything else (aka only spaces) I get the following error in the console:
Uncaught TypeError: Cannot read property 'id' of null
In addition, after this happens tags can't be created anymore. 
Steps to reproduce:
create a select2 with tokenSeparators: [" "]
click on select2
type a space or two (should see error in console)
now try to type a different character, like 'a'
press space again, the 'a' will not turn into a tag. 

Suggestions: If there is no content before the tokenSeparator, that key press should just be ignored.

**Comment by kevin-brown** [comment]
This is related to https://github.com/select2/select2/pull/3591, which has a temporary fix.
