### ISSUE TITLE
If all options of optgroup is disabled nothings gets displayed

### ISSUE THREAD

**Issue by Thamaraiselvam** [select2/select2#3596]
If all options of optgroup is disabled nothings gets displayed in that particular group if anyone is enabled then it shows all the options.

**Comment by Thamaraiselvam** [comment]
https://jsfiddle.net/thamaraiselvam/swMBL/5/

see here Europe is not shown because all or disabled . i want to show those . how can i ?

**Comment by kevin-brown** [comment]
This is a limitation of Select2 3.5.x and below, it doesn't display the optgroup if nothing within it can be selected. This has been fixed in Select2 4.0.0.

https://jsfiddle.net/swMBL/6/
