### ISSUE TITLE
'id' and 'text' property might be configurable

### ISSUE THREAD

**Issue by aartek** [select2/select2#3598]
It seems that already response data must contains `id` and `text` properties (is it documented somewhere?). I think it would be great if user could define name of equivalents of `id` and `text` properties. e.g

    select2({
      idPropertyName: 'key',
      textPropertyName: 'name'
    });

I know currently we can add this properties in `processResults`, but we have to do it for all results and imo it's completely unnecessary operation.

**Comment by kevin-brown** [comment]
This was previously allowed, but it created _tons_ of edge cases that I'd rather not spend time dealing with.

https://select2.github.io/announcements-4.0.html#changed-id

> is it documented somewhere?

It will be soon. https://github.com/select2/select2/issues/920
