### ISSUE TITLE
Documentation example has an error

### ISSUE THREAD

**Issue by starsinmypockets** [select2/select2#3607]
In the documentation at https://select2.github.io/announcements-4.0.html, the following snippet has an error:

    var $element = $('select').select2(); // the select element you are working with
 
    var $request = $.ajax({
      url: '/my/remote/source' // wherever your data is actually coming from
    });
 
    $request.then(function (data) {
      // This assumes that the data comes back as an array of data objects
      // The idea is that you are using the same callback as the old `initSelection`
 
      for (var d = 0; d < data.length; d++) {
        var item = data[d];
 
        // Create the DOM option that is pre-selected by default
        var option = new Option(data.text, data.id, true, true);
 
        // Append it to the select
        $element.append(option);
      }
 
      // Update the selected options that are displayed
      $element.trigger('change');
    });

The line with var option = new Option... should read:

        var option = new Option(item.text, item.id, true, true);

**Comment by kevin-brown** [comment]
This was fixed in https://github.com/select2/select2/pull/3547.

In the near future I'll be pushing a docs update which will include this.
