### ISSUE TITLE
[aria-selected=true] trigger self close

### ISSUE THREAD

**Issue by prakarangs** [select2/select2#3608]
Hi there,
Thank you for great plugin first of all.
However, I have try to use select2 with options of multiple checkboxes inside.
I set closeOnSelect to false to prevent self close.
However, when i click on option that has [aria-selected=true] it will toggle close anyway.
So i have to commented out self.trigger('close') in js file.
Is there a better way to fix this?

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/
