### ISSUE TITLE
Search term is cleared when the field is clicked

### ISSUE THREAD

**Issue by RobertDiebels** [select2/select2#3609]
Hi guys/gals,

Select 2 removes any search term on focus events instead of focus-out events.

**What steps can be used to reproduce the issue?** ( https://jsfiddle.net/wr5jf16z/1/ , courtesy of  @scashin133 ).
- Open the fiddle
- Click the select2 input field.
- Enter a search term.
- Click on the field again to hide the dropdown list.
- The search term has disappeared.

**What is the bug and what is the expected outcome?**
The search term(s) disappear when clicking on the field where you are entering the search term.
I would expect that the search terms disappear on a focus-out event and not when the input field is getting a re-focus.

**What browser(s) and Operating System have you tested with?**
- Chome 54.0.2840.99 m (Windows 10)
- Edge 38.14393.0.0 (Windows 10)
- FireFox Nightly 51.0a1 (Windows 10)

**Does the bug happen consistently across all tested browsers?**
Yes.

**What version of jQuery are you using? And what version of Select2?**
- Select2 4.0.3
- Jquery 2.1

**Are you using Select2 with other plugins?**
No.

Greetings, Robert.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by scashin133** [comment]
I believe this issue was introduced with https://github.com/select2/select2/commit/f5593e12e41da5b4f7ffa470f2b8cdb102f884a2#diff-5afae3614c66ac049e92bf263a7d939e 

If you include a value in the array that is already included on the page from an option it will override the selected attribute to be false rather than true. 

I made a jsfiddle to demonstrate: http://jsfiddle.net/wr5jf16z/

**Comment by RobertDiebels** [comment]
@kevin-brown , @scashin133 accurately reproduces the issue in the jsfiddle he provided. I've adjusted the issue description to meet your information requirements.
