### ISSUE TITLE
DropDown Box Detaches from Selection Box on Mobile Scroll

### ISSUE THREAD

**Issue by MClarkTurner** [select2/select2#3612]
As evidenced by this plunk (http://plnkr.co/edit/bKvGp6?p=info), when viewed through Chrome's mobile emulator, when you have a web page that extends far enough that a horizontal scroll bar is generated then the process of opening a drop down box generates an error. The scrolling of the screen causes the dropdown box to begin sliding away from the selection box as if the dropdown component had become a "fixed" element. 

One would think that simply closing the dropdown box on scroll and re-opening on click would resolve this but unfortunately the incorrect location is derived from offset values and so the dropdown box will always open in the detached space.

![scroll-mobile-select2](https://cloud.githubusercontent.com/assets/13486891/8880680/781f81ac-3208-11e5-8f97-3946de4761e9.png)

I have had success re-creating this on Mobile Nexus 7. I had to double click to zoom the screen first before I could scroll

**Comment by kevin-brown** [comment]
I wasn't able to reproduce this issue in the Chrome emulator in the plunk that was provided.

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by MClarkTurner** [comment]
What steps can be used to reproduce the issue?
**1. Open the provided Plunk in Chrome**
**2. View the Plunk preview in a detached window**
**3. Open the developer console and the "emulator" window**
![emulator section](https://cloud.githubusercontent.com/assets/13486891/8904704/c25e83c0-342f-11e5-9d15-78f1be454409.png)
**4. Set the model to "Google Nexus 7" (this seems to happen on all mobile device emulations but I have the most success with this one)
5. Double click the white space (this should cause the screen to zoom slightly)
6. Click a selection box in order for the drop down menu to display
7. Scroll the screen by clicking the white space and moving (as you would move a screen on a mobile device)
RESULT: The Drop down box detaches from the selection box**


What is the bug and what is the expected outcome?
**The Drop down box detaches from the section box when you scroll using a mobile device or mobile emulator in Chrome.**

What browser(s) and Operating System have you tested with?
**I am able to reproduce this bug in Chrome on an Android Nexus 7 Tablet and in the Chrome mobile emulator on my Windows 7 Desktop.**

Does the bug happen consistently across all tested browsers?
**Thus far I have only been able to reproduce the bug on Chrome.**

What version of jQuery are you using? And what version of Select2?
**I am using jQuery 2.1.3 and Select2 4.0.0**

Are you using Select2 with other plugins?
**No**

**Comment by chickenwing** [comment]
Having the same problem...

**Comment by cagintopkaya** [comment]
same here.

**Comment by MrGorki** [comment]
same here

**Comment by damian-kociuba** [comment]
same here

**Comment by rameshvishnoi90904** [comment]
Any fix for this?
