### ISSUE TITLE
Publish 4 version via NuGet

### ISSUE THREAD

**Issue by mikalai-ramashka** [select2/select2#3615]

**Comment by kevin-brown** [comment]
We do not control the [Select2 package on NuGet](https://www.nuget.org/packages/Select2.js/), that's handled by @splattne.

**Comment by splattne** [comment]
Sorry for the delay. I've published 4.0.0 as NuGet package right now.

**Comment by mikalai-ramashka** [comment]
Thanks!

2015-07-26 20:01 GMT+03:00 Stefan Plattner <notifications@github.com>:
