### ISSUE TITLE
ajax.templateSelection() is called twice for every selection event

### ISSUE THREAD

**Issue by renehamburger** [select2/select2#3616]
This can be reproduced with the ajax example given at https://select2.github.io/examples.html and a breakpoint in `formatRepoSelection()`.

**Comment by francescomeloni** [comment]
someone can suggest a workaround for this bug?

**Comment by pjryan126** [comment]
My suggested workaround:

```
var bool = true; // boolean switch to handle select2 bug
function templateSelection(selection) {
     bool = !bool;
     if (bool == true) {
          // format and return formatted selection here
     }
}
```

**Comment by smoothlikejazz** [comment]
Love this Library, I also ran into this; So in revisiting and looking through the code there is an event called "selection:update"; the listener is registered twice, 
Once in  SingleSelection.prototype.bind and again in BaseSelection.prototype.bind
```
container.on('selection:update', function (params) {
      self.update(params.data);
});
```
Now since its registered in the Base prototype method it should be safe to remove the second binding from the SingleSelection.prototype.bind method. 

In testing by removing the second binding it will only fire once as you would expect in the ajax case. I am not sure of the Ramifications of doing this though, maybe author can chime in.

**Comment by kevin-brown** [comment]
@smoothlikejazz That should only need to be registered once, and I don't believe the ordering matters.

Feel free to submit a pull request which drops it from the SingleSelection.

**Comment by smoothlikejazz** [comment]
Okay great thanks @kevin-brown will do

**Comment by joanebrown** [comment]
@smoothlikejazz  Hi! I still have this problem with the Select2 4.0.3. Your PR is not merged? In my case, the `templateSelection` its called four times...

*BTW, who knows what's the diferrence between "select2.full" and "select2"?*

Regards!!!

**Comment by joanebrown** [comment]
@kevin-brown There is any date for the 4.1.0 release? There are some workaround for this problem until the new release isnt yet ready?

**Comment by CodyBrouwers** [comment]
I am getting `templateSelection` called four times as well. Removing this listener brings it down to twice at least but is it going to get merged soon?

**Comment by Angelo8828** [comment]
+1 here. Experiencing the same problem.

**Comment by Angelo8828** [comment]
As a workaround for this bug. My work is like this.

`
// DECLARE A DELIMITER VARIABLE
var delimiter = 1;

$('select').select2({

........

templateResult: function (data) {
delimiter = 1;
....... // FORMATTING OF SEARCH QUERY RESULTS
},
templateSelection: function (data) {

if(delimiter == 1){
....... // ONLY PROCESS THE DATA HERE
}

delimiter++;
}
}):`

I know it is a very bad code but this bug report is already 2 years old and it seems that our contributors has difficulties in solving the error and it is understandable given that Select2 is one of the most complex jQuery plugins around. Better to keep my website working than to wait for fix.

**Comment by newmandani** [comment]
+1 Firing 8 times. I'll try to preserve this with logical value inverting first time to execute inside `templateSelection`  function.

**Comment by ahabunreal** [comment]
I'm having the same problem from inside jquery modal/dialog overlay. 2x and 4x times stuff is calling, this makes select2 pretty useless. I'm using latest 4.0.5 ..

anyone working to fix this problem?

**Comment by alexweissman** [comment]
It looks like @kevin-brown already gave his blessing for the change made in #4306, so I will add that to the 4.0.6 milestone.

**Comment by alexweissman** [comment]
The fix (#4306) has been merged into `develop` for 4.0.6 release.

**Comment by mz-devbo** [comment]
> +1 Firing 8 times. I'll try to preserve this with logical value inverting first time to execute inside `templateSelection` function.
> 
> **UPD**: I've removed my `function` out of `templateSelection` and put it out to the external `select2:select` event.
> 
> ```
> $("#select2exampl").on('select2:select', function(selection){
> 
>         addPassengerAJAX( selection.params.data.code );
> });
> ```
> 
> This works for me and do not execute several times. It is happening because `templateSelection` holds not only `select2:select` action I think.

This is the right way, thank you!

**Comment by rabih9780** [comment]
I am still having this problem with the latest version of select2. any hints on how i can fix this?

**Comment by Codename2200** [comment]
I'm having this issue right now. I'm using: Select2 4.1.0-beta.1

**Comment by ahabunreal** [comment]
> I'm having this issue right now. I'm using: Select2 4.1.0-beta.1

Yep.. still seeing it to..

**Comment by estebansa19** [comment]
Solution of @newmandani is working fine, thanks!
