### ISSUE TITLE
Refresh Select2 without triggering change event

### ISSUE THREAD

**Issue by omggga** [select2/select2#3620]
In Select2 v4 documentation recommended to reset select by setting value to empty value and triggering event.
```
$('#id').val('').trigger('change')
```
But how to reset dropdown select to placeholder without triggering change event and replacing tons of dom elements? Something like
```
$('#id').select2('refresh')
```

**Comment by chinyeelee** [comment]
I second this issue, I tried upgrading from 3.5.1, but run into the issue where because change events trigger is required to refresh select2, (and select2("val", null); function automatically trigger the change too), it trigger a flood of unwanted cascading actions which originally were meant to detect user made changes. This feature was previously available.

> "triggerChange (optional)	boolean	Whether or not a change event should be triggered. false by default."

If someone could look into this it would be great.

**Comment by chinyeelee** [comment]
This appear to be an undocumented feature. I found the answer on stackoverflow, use `'change.select2'`

    $docInput.val(null).trigger('change.select2');

http://stackoverflow.com/a/31856728/2234426

**Comment by kevin-brown** [comment]
I might just document the `change.select2` event as the recommended way to handle this.

**Comment by smajl** [comment]
Oh my, this finally solved my implementation problems with select2 4.0.x into angular! Wow, should have known about this sooner. `change.select2` FTW!

**Comment by BallisticPain** [comment]
@smajl Are you making a library or just directly integrating?

**Comment by smajl** [comment]
@BallisticPain It was a direct integration into very custom angular component. It used select2 adapter system nicely and added a lot of new functionality atop of select2 lib. But I'm not on that project anymore and not owner of that code, sorry. :)

**Comment by krishna950** [comment]
> This appear to be an undocumented feature. I found the answer on stackoverflow, use `'change.select2'`
> 
> ```
> $docInput.val(null).trigger('change.select2');
> ```
> 
> http://stackoverflow.com/q/17819709/359284#31856728

thanks a lot.. saved my lots of hours and my already built project. thank you

**Comment by nivle** [comment]
@kevin-brown 
$docInput.val(null).trigger('change.select2');
doesn't work on my selects, 
for me it still triggers the onchange events that the user is supposed to trigger, running any methods that are called on the onchange event.

**Comment by pfalomorblab** [comment]
Please update the docs https://select2.org/programmatic-control/add-select-clear-items
