### ISSUE TITLE
Select2 can't show by default selected values in multiselect

### ISSUE THREAD

**Issue by ranazee** [select2/select2#3626]
Select2 multi select pre define selected value not show but when i open drop down i can see them selected kindly guide me regarding this issue or maybe i am doing something wrong

**Comment by maltitco** [comment]
Paste the code what you have, without it no one is able to check.

**Comment by ranazee** [comment]
if(ArrayData[i]['tag_default']==1)
             {
                $('#selectTags').append('<option selected="selected" value='+ArrayData[i]["tag_id"]+'_'+name+'>'+ArrayData[i]["tag_name"]+'</option>');
             //$('#selectTags').select2().select2('val',ArrayData[i]["tag_id"]+'_'+ArrayData[i]["tag_name"]);
                }
             else
             {
                $('#selectTags').append("<option value="+ArrayData[i]['tag_id']+"_"+name+">"+ArrayData[i]['tag_name']+"</option>")
             }

![select2-selected value](https://cloud.githubusercontent.com/assets/78499/8978256/eb7a07f2-36b9-11e5-941d-730b0b14a5c7.png)

you can see first tag is selected

**Comment by ranazee** [comment]
figure out this :)

var tags=[];
 for(var i=0; i < count; i++)
            {
             var name=ArrayData[i]["tag_name"].split(' ').join('_');
             if(ArrayData[i]['tag_default']==1)
             {
                tags[i]=ArrayData[i]['tag_id'] + "_" + name;
                $('#selectTags').append('<option id="abc" selected="selected" value='+ArrayData[i]["tag_id"]+'_'+name+'>'+ArrayData[i]["tag_name"]+'</option>');
             //$('#selectTags').select2().select2('val',ArrayData[i]["tag_id"]+'_'+ArrayData[i]["tag_name"]);
                }
             else
             {
                $('#selectTags').append("<option value="+ArrayData[i]['tag_id']+"_"+name+">"+ArrayData[i]['tag_name']+"</option>")
             }

        } $('#selectTags').val(tags).trigger("change");

thanks for your participate @maltitco
