### ISSUE TITLE
Can I change the options' background-color with the newest edition?

### ISSUE THREAD

**Issue by Acebee** [select2/select2#3628]
I want the options's background-color to inherit from the original options which i have set .Can I achieve that ?

**Comment by kevin-brown** [comment]
Support for this was added in https://github.com/select2/select2/pull/3324, it will be available in 4.0.1.

**Comment by alin-rosu** [comment]
Does this work now? I tried the way that Sagaio tried here https://github.com/select2/select2/issues/4483 but this is not working for me.
Do you have a tutorial, documentation about this?
