### ISSUE TITLE
Reset button doesn't affect select2 selected option

### ISSUE THREAD

**Issue by SCIF** [select2/select2#363]
If load form, change selected item via select2 and later click input[type=reset] then <select> reset selected option but select2 doesn't affect.

**Comment by kevin-brown** [comment]
We've decided to push this off for the 4.0 milestone for now, as it is pretty low priority and there are ways to work around the issue.

**Comment by mindeffects** [comment]
I don't know wether this is a "good" solution, but I do my changes to the underlaying select HTML-element, like `$('#title').prop('selectedIndex',0);` and then just call `$('select').select2();` once again. This might be quite a big canon, but it works. ;-)

I would love to see a "refresh/update" method in 4.0!!!

**Comment by ve3** [comment]
Yes, reset button does not work. Without placeholder, allowClear will never work and .select2('data', {}) not work neither.

Another problem placeholder also remove all my option value="".

Please make clear button from allowClear to work without placeholder. Just show blank select box placeholder.

**Comment by joelbarker2011** [comment]
:+1: Upvoting to fix this issue.

In my case I'm using ajax, so the above workarounds don't work: either the select2 is not reset, or it is reset but the ajax functionality is killed.

Even a well-documented workaround (in the README, preferably) would be better than nothing. Other than this issue, select2 is showing great promise at making my life easier.

**Comment by HernanOrtiz** [comment]
This was my quick solution:

```
$("button[type='reset']").on("click", function(event){
		event.preventDefault();
		var myForm = $(this).closest('form').get(0);
		myForm.reset();
		$("select", myForm).each(
			function () {
				$(this).select2('val',$(this).find('option:selected').val())
			}
		);
	});
```

**Comment by SalmanAwan** [comment]
Definitely need this. Till then this ugly hack worked for me:

```
$('#selectElement').empty();               // DOM select element on which select2 is initialized
$('#parentOfSelectElement').find('#select2-selectProvider-container').html(
	'<span class="select2-selection__placeholder">' + <placeholderText> +'</span>');
```

**Comment by rig1** [comment]
This works for me.. 
$("select.select2").select2('data', {}); // clear out values selected
$("select.select2").select2({ allowClear: true }); // re-init to show default status

Thanks @yabdab

**Comment by vleango** [comment]
Contributing the solution that worked for me.

Every time I tried to reset with `$('#select_id').select2('data', null);` it would never work unless I did it in the browser. I only got it to work if I added the reset to a `setTimeout`

However, I did finally get it to work when I did this:

```
$('#select_id').select2('val', null);
$('#select_id').attr('value', '');
```

Note: Select2 v3.5.4

**Comment by hansspiess** [comment]
resetting the (multi)select to its initially (maybe not blank) value has to take [`defaultSelected`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement) into account ([credits](http://stackoverflow.com/a/16913242/6234391)):
```
    $('myResetButton').on('click', function() {
        $('mySelect2Element).find('option').prop('selected', function() {
            return this.defaultSelected;
        });
        $('mySelect2Element).trigger('change.select2');
    });
```

**Comment by Aleksandr-ru** [comment]
another idea based on previous comment. when initializing select2
```
$(".select2").select2().closest('form').on('reset', function(){
			$(this).find('.select2 option').prop('selected', function(){ return this.defaultSelected; });
			$(this).find('.select2').trigger('change.select2');
		});
```

**Comment by ttv20** [comment]
on the last version (4) this work:
`$('select').val('').trigger('change');`
[https://stackoverflow.com/a/39938343/5214120](https://stackoverflow.com/a/39938343/5214120)

**Comment by jnandritsilavo** [comment]
User this code into your js file : 
```
$('.sgl').val('1');
 $('.sgl').trigger('change');
```
