### ISSUE TITLE
data-* attributes should be in lowercase

### ISSUE THREAD

**Issue by sgomez** [select2/select2#3630]
According the [HTML5 standard](http://www.w3.org/TR/2011/WD-html5-20110525/elements.html#embedding-custom-non-visible-data-with-the-data-attributes):

> "A custom data attribute is an attribute in no namespace whose name starts with the string "data-", has at least one character after the hyphen, is XML-compatible, and contains no characters in the range U+0041 to U+005A (LATIN CAPITAL LETTER A to LATIN CAPITAL LETTER Z).

> Note: All attributes on HTML elements in HTML documents get ASCII-lowercased automatically, so the restriction on ASCII uppercase letters doesn't affect such documents."

So, when I try to get the attributes with jQuery:

```
$('#upload_file_anon_tags').data('tokenseparators')
"[',']"
$('#upload_file_anon_tags').data('tokenSeparators')
undefined
```

This cause problems with some frameworks (like Symfony) because they always write the data-* attributes in lowercase (as the standard says). And, when the data attribute is on lowercase, select2 can't read it.

**Comment by kevin-brown** [comment]
You're right, they are supposed to be in lowercase. I just realized [the examples page](http://select2.github.io/options.html) doesn't cover how `camelCase` options should be written out. Select2 follows the [HTML5 `dataset` standard](https://html.spec.whatwg.org/multipage/dom.html#dom-dataset), so `camelCase` attributes (as written in JS) are represented in `hyphen-case` in an attribute.

This means that the `tokenSeparators` is represented as `data-token-separators` (not `data-tokenseparators`) on the HTML element, and can be retrieved using `.data('tokenSeparators')` which falls in-line with `.dataset` [and the jQuery documentation](https://api.jquery.com/data/#data-html5).

I'm going to leave this ticket open until the documentation is clarified or a better duplicate target comes along.

**Comment by Briareos17** [comment]
How to pass array as value of data-token-separators?
