### ISSUE TITLE
Select2 v4 in Tagging mode opens the dropdown when removing an item.

### ISSUE THREAD

**Issue by glenpike** [select2/select2#3632]
When removing selected items in tagging mode, the dropdown view is opened.  This is different from behaviour in Select2 3.5.

To reproduce, look at examples "Tagging Support" for v4.
1. Add some tags.
2. Click the "x" to remove a tag.
3. The dropdown list of available tags is opened.

Compare with v3.5.2 examples.

Desired behaviour - don't open the dropdown view.

Workaround: 
Bind to the "select2:unselect" event and close the dropdown after a timeout.  This is rather kludgy, but works

```
$('.select2').select2({
    tags: true
});
$('.select2').on('select2:unselect', function() {
    setTimeout(function() {
        this.$('.select2').select2('close');
    }, 100);
});
```

**Comment by kevin-brown** [comment]
It looks like https://github.com/select2/select2/issues/3209 is the duplicate target for this, though I swear I saw another workaround in another duplicate.
