### ISSUE TITLE
"multiple" tagging option not working with 4.0 with ajax data 

### ISSUE THREAD

**Issue by Lindsayanng** [select2/select2#3634]
I have found that if you are using the most recent 4.0 version of Select2 the multiple select "tags" do not appear when you select options even though they are being selected and added to the hidden fields in the DOM in the .select2-hidden-accessible class they do now get appended to the visible part of the dom as `<li class=select2-selection__choice">` in the .select2-selection__rendered ul. 

You can see this in action here: 
http://jsfiddle.net/lindsayanng/khez3uoz/

I am using the base of your AJAX example and the versions from the CDN of the script. 

Would love to know your thoughts as I am totally stuck here. 

**What steps can be used to reproduce the issue?**
Setup the "ajax" example but add the mutliple: true parameter

**What is the bug and what is the expected outcome?**
The selected items do not appear in the text box as expected with all "multiple" examples

**What browser(s) and Operating System have you tested with?**
Chrome Version 44.0.2403.125 (64-bit)
Safari 8.0.6

**Does the bug happen consistently across all tested browsers?**
Consistent across the two browsers tested

**What version of jQuery are you using? And what version of Select2?**
Select2 4.0 and jQuery 1.7.2

**Are you using Select2 with other plugins?**
No. Was able to replicate in a jsfiddle without any added stuff loaded.

**Comment by kevin-brown** [comment]
Thanks for the well-formed bug report! :+1: 

I was able to reproduce the issue in your jsfiddle, and everything looked fine in the JavaScript. The issue was in the HTML, because you are trying to attach Select2 to a `<div>` instead of a `<select>`. A `<div>` cannot, by default, store a value which can be later transmitted to a server.

After switching to a `<select>`, the issue fixed itself.

https://jsfiddle.net/khez3uoz/5/

**Comment by Lindsayanng** [comment]
Ah ok then! The strange thing was that it worked with the old version of Select2.js but not the new version. 

I believe that there are some docs or some examples floating around the net somewhere that suggest that you must use an element that is NOT a `<select>` in order to make multiple select work with ajax. I believe that may have been for the previous version, but it might be of note to include that the element MUST be a `<select>` when using the newest version. 

Also, is there some type of aggregated list of differences between the version 3.X and 4.0 in terms of requirements to make the bare minimum work? I think something like that could be of help for people like me who are wading through docs and StackExchange questions/answers so we know what to watch out for? 

I am considering writing up a quick tutorial on this myself anyways just because the info was so difficult to find. Any info you can provide me with for the tutorial in regards to what worked in 3.X that doesn't work in 4.0 would be hugely helpful.
