### ISSUE TITLE
Search term is deleted with angular

### ISSUE THREAD

**Issue by tester211** [select2/select2#3638]
I'm trying to use "nextSearchTerm" function and it looks like it is deleted after the second selection.
In this example: http://jsfiddle.net/0mobgbqr/1/ after clicking on "f", the list is filtered but after choosing a value twice, it is deleted. 
In addition, the text term is deleted after the selections.

**Comment by kevin-brown** [comment]
This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

https://github.com/angular-ui/ui-select

[ml]: https://github.com/ivaynberg/select2#mailing-list
