### ISSUE TITLE
How select2 appends the 'select2-container' that holds 'select2-dropdown' can be problematic

### ISSUE THREAD

**Issue by Lindsayanng** [select2/select2#3639]
While integrating select2 in to a UI where select2 would exist inside of a modal window I found a few small issues relating to the HTML structure of select2 and how it adds the contents of the drop down to the DOM. 

When a select2 field is initiated and results are displayed it appears that select2 appends a new <span> element to the very bottom of the DOM before the closing `<body>` tag. Typically this is not entirely problematic however it does seem that it could be tidier. The issue is most apparent when looking at the results of a query when a select2 input exists inside of a modal window (example here: http://jsfiddle.net/lindsayanng/khez3uoz/ ). 

I feel that the markup for the drop down element should be appended either right before the .dropdown-wrapper `<span>` or somewhere inside of or immediately after the main .select2 `<span>` 

This would just keep the related DOM elements all in a realistic place within the DOM and having looked briefly under the hood, I do not see a reason why they must be added before the closing `</body>` tag. 

Again, this is not a bug but simply a thought I had while working with this. Would love to know your thoughts. 

**example using most recent version of select2 from the CDN (4.0) and current jQuery versions and FancyBox. Fancybox included just for illustrative purposes. This would be apparent with any modal script.

**Comment by kevin-brown** [comment]
The main reason for putting Select2 at the bottom of the DOM is to avoid z-index battles and to avoid containers with `overflow: hidden` set.

> I feel that the markup for the drop down element should be appended either right before the .dropdown-wrapper <span>

We have a custom `DropdownContainer` decorator for those who want to do this.

> or immediately after the main .select2 <span>

We also allow the `dropdownParent` to be specified, though this currently has issues in non-static containers.

**Comment by XorOwl** [comment]
To anyone else coming along to try and fix a similar source problem, the above isn't valid anymore. Google has likely lead you here, and if your problem is anything like what we had, your problem is likely to do with the dropdownParent you've defined. We were defining a parent that was wrong, and that lead to strange issues where the dropdown was attached. 
If not, at least i can tell you that DropdownContainer doesn't appear to be a thing anymore. 

Be well, wanderers
