### ISSUE TITLE
Android + select2 v3.4.5 dropdown wrong position

### ISSUE THREAD

**Issue by klierik** [select2/select2#3641]
Good day.
We found a bug with select2 plugin in mobile device.
Device: Samsung Galaxy S4, Android 4.4.2, Chrome;
Bug: http://www.screencast.com/t/TWVqKvUgb

As you see after click on select Browser showing keyboard and select dropdown disappear.

Also checked on iPhone 5s — it's fine. Is it possible to fix it via update to 4.0 version?

Thanks

**Comment by kevin-brown** [comment]
The dropdown should be positioned properly in Chrome in Select2 4.0.0.

Unfortunately we no longer support Select2 3.4.5.

**Comment by erreai** [comment]
I have the same problem but in Android 5.+
