### ISSUE TITLE
npmignore

### ISSUE THREAD

**Issue by TrySound** [select2/select2#3642]
Hi! Add please  `vendor`, `tests` and `docs` to npmignore. Node packages should be small as it possible too.

**Comment by kevin-brown** [comment]
Hi @TrySound,

Unfortunately I'm not familiar enough with NPM as I wish I was, so I'm not sure what else should be excluded from the NPM distributions. If possible, would you be able to create a pull request which creates a npmignore file with all of the extra, unneeded files included?

**Comment by TrySound** [comment]
@kevin-brown  Done
