### ISSUE TITLE
Issue with tags, single selects, and AJAX

### ISSUE THREAD

**Issue by tlshaheen** [select2/select2#3646]
I'm using Select2 4.0.0 (from the cdnjs) and jQuery 2.1.3. The JSFiddle showing my issue is here: http://jsfiddle.net/67L177Lj/1/ I've tested in the latest FF and Chrome on Mac OS X.

When using a single select `<select id="myselect2" name="somename"></select>`, `tags: true` and AJAX search, I'm unable to select the first custom tag.

Open the JSFiddle, and start typing a search term. Since the ajax always returns an empty set for the demo, click your search term to create the tag. The Select2 dropdown will close, but the tag is not selected. If you inspect the element you'll see that the tag elements have been created, but it's not selected. If you then open Select2 again (without re-loading the page), and search for the same term, it will now properly select the tag.

This looks like a bug to me. What can I do to work around this and have the tag be selected the first time?

Here is the Javascript:

```
$(function() {
    $.fn.select2.amd.require([
        "select2/utils",
        "select2/dropdown",
        "select2/dropdown/attachContainer",
        "select2/dropdown/search"
    ], function (Utils, DropdownAdapter, AttachContainer, DropdownSearch) {
        var CustomAdapter = Utils.Decorate(
            Utils.Decorate(
                DropdownAdapter,
                DropdownSearch
            ),
            AttachContainer
        );
        var selectoptions = {
            tags: true,
            width: '100%',
            minimumInputLength: 2
        };
        selectoptions.dropdownAdapter = CustomAdapter;

        selectoptions.ajax = {
            url: '',
            dataType: 'json',
            delay: 250,
            data: function (params) {
                var formdata = {};
                formdata.q = params.term;
                formdata.page = params.page;
                return formdata;
            },
            processResults: function (data, page) {
                return { results: [] };
            },
            cache: true
        };

        $("#myselect2").select2(selectoptions);
    });
});
```

**Comment by tlshaheen** [comment]
Is this perhaps related to #3169?

**Comment by tlshaheen** [comment]
The workaround I'm using currently that seems to be working ok is adding this listener outside of the adapter, but its not my favorite solution:
````
$('#myselect2').on('select2:close', function(e) {
    var $me = $(this);
    var $tag = $me.find('option[data-select2-tag]');
    //We only want to select this tag if its the only tag there
    if ($tag && $tag.length && $me.find('option').length === 1) {
        $me.val($tag.attr('value'));
        $me.trigger('change');
        //Do stuff with $me.val()
    }
});
````

**Comment by kesha-antonov** [comment]
Experiencing the same

**Comment by kesha-antonov** [comment]
@tlshaheen, your fix works! Thanks! And thanks for the awesome library! :bomb:

**Comment by alexweissman** [comment]
I'm almost certain that this is the same issue described in #4842.
