### ISSUE TITLE
data with children does not allow select

### ISSUE THREAD

**Issue by leandrogehlen** [select2/select2#3647]
In version 3.5.x the selection controller was defined by id attribute.
when exists the attribute id then the selection was allowed

in version 4 this does not is possible
https://github.com/select2/select2/blob/master/src/js/select2/results.js#L183

This functionality will be removed?

```js
$('select') .select2({            
    data: [
        {id: 1, text: 'Test 1'},
        {id: 2, text: 'Test 2'},
        {id: 3, text: 'Test 3', children: [
            {id: 4, text: 'Test 3.1'}
        ]
    }],            
})
```

**Comment by kevin-brown** [comment]
This is a breaking change in 4.0.0 that is explained in https://github.com/select2/select2/issues/520#issuecomment-103703792.

**Comment by leandrogehlen** [comment]
This means, in this version, does not possible to select parent in hierachical data?

**Comment by kevin-brown** [comment]
Correct. As mentioned in https://github.com/select2/select2/issues/520#issuecomment-103703792, the best solution here to make it work all around is to use an `<option>` instead of an `<optgroup>` (basically don't nest it under `children`) and style it like a group heading.
