### ISSUE TITLE
Issue in polish translation [4.0.0]

### ISSUE THREAD

**Issue by lelek16** [select2/select2#3648]
In polish translation, I found a small typo:

```javascript
maximumSelected: function(e) {
    return "Możesz zaznaczyć tylko " + e.maximum + " " + n(e.maxiumum, t)
},
```

``` n(e.maxiumum, t)``` should be ``` n(e.maximum, t)```

**Comment by kevin-brown** [comment]
Thanks for the report!

This was corrected in https://github.com/select2/select2/commit/74bb22939a333770fc30166034104a32e77a1e81 and will be available in 4.0.1.
