### ISSUE TITLE
Adding dynamic tags does not work

### ISSUE THREAD

**Issue by francoispluchino** [select2/select2#3655]
#### For `4.0` branch.

When you use the methods `val(<data>)` or `select2('val', <data>)` with the options `multiple=true` and `tags=true`, The selection displayed contains only the values of the existing select options, without including the new tags.

**HTML:**
```html
<select id="mydropdown" multiple="multiple" >
  <option value="VAL1">Value 1</option>
  <option value="VAL2" selected="selected">Value 2</option>
  <option value="VAL3">Value 3</option>
</select>
```
**JS:**
```js
$('#mydropdown').select2({
  tags: true,
  tokenSeparators: [","]
});

$('#mydropdown').val(["VAL3", "New tag"]).trigger("change");
```

However, if you created a new tag via the dropdown, and that you delete this tag, The `.val()` method does work (because the `option` still exists in the `select`).

Is it normal that the `val` method does not create the `option` in the `select`?

**Comment by kevin-brown** [comment]
http://stackoverflow.com/q/29058625/359284

> Is it normal that the val method does not create the option in the select?

Yes, this is because the option that you are trying to set the value to does not actually exist.

**Comment by francoispluchino** [comment]
Thanks for the link, but I already used an equivalent solution. I rephrase my previous question: why are we forced to add manually the option?

If the tags are activated, the update of Select2 should automatically create this option.

**Comment by kevin-brown** [comment]
It's important to note that [the `.val()` method](https://api.jquery.com/val/) is created/controlled by jQuery, not Select2. We don't have the ability to overload the `.val` method and handle setting the value a different way.

> why are we forced to add manually the option?

We are forced to manually add the option because jQuery will not automatically create it for you.

We _did the equivalent of this in the past_ with `.select2('val', data)`, but this was removed because **explicit is better than implicit** in this case. People are used to setting the value of a `<select>` using `.val()`, and Select2 aims to be a replacement for `<select>` boxes. So in the latest version (4.0.0), changes were made that brought Select2 back to its roots as a `<select>` box replacement. One of the changes happened to be that setting the value of a standard `<select>` to something invalid results in it being _ignored_.

**Comment by francoispluchino** [comment]
It's obvious that we should not override the `.val()` method. So much for me, I just find that the value passed to the `selection:update` event (and so in the `change.select2` event) contains only the values matched with the options.

Indeed, in this case, my proposal is not possible. But perhaps it would be easier and faster to have an helper for add a new tag directly in JS, because the implementation already exists (creating the option with the good attributes,etc...).

Thank you for your great component.

**Comment by clockwiseq** [comment]
When I manually add an option to the select, I need to include a custom data attribute.  How is that done?  When I use AJAX to get the items, this works fine:

```
processResults: function (data) {
    return {
        results: $.map(data, function (obj) {
            return { 
                id: obj.Id, 
                text: obj.LastName + ', ' + obj.FirstName, 
                company: obj.Company 
            };
        })
    };
}
```

But I need to load these results back into the select2 as tags upon load and I can't get the extra data property (company) added:

```
$.each(dtlPatients, function (index, patient) {
    $('#PatientListControl').select2().append('<option value="' + patient.Id 
           + '" data-company="' + patient.Company + '">' + patient.Name + '</option>');
});

$('#PatientListControl').val(selpatlist).trigger('change');
```

**Comment by alexweissman** [comment]
@clockwiseq please open this as a new issue.

**Comment by clockwiseq** [comment]
@alexweissman: [Issue Created](https://github.com/select2/select2/issues/5036)

**Comment by carvajalluis** [comment]
Hello @kevin-brown,

> We did the equivalent of this in the past with .select2('val', data), but this was removed because explicit is better than implicit in this case.

what was the implicit part of it ? may be the naming was not correctly?  the previous function created the option while jquery one does not maybe we should call it addOption  or something more meaningful to it, we could keep setting value as it is right now with jquery and you add a new method for appending options.

As it is right now I am experiencing a buggy UX, I need to have tags and dynamical tag creation working together as it was 

![image](https://user-images.githubusercontent.com/674024/36226795-7b3b6dd8-1194-11e8-8d37-695315d5e87c.png)
 the upper select sets some tags on the later as they are been selected, besides that someone can create their own "subjects" regardless of selected "template". now I get handwritten tags only work before any is pushed in by the code

**Comment by sh6210** [comment]
In my case, i'm using select2 v3.4.5.

All I had to write, 

> `$("#category_tags").val(`${autoTaggingText}`).trigger("change")`

here `#category_tags` is my target element.
