### ISSUE TITLE
Multiple select dropdown downkey navigation is not properly coming

### ISSUE THREAD

**Issue by mkmms** [select2/select2#3673]
if we do not want to show selected option in drop down list, we need to give style 
.select2-results__option[aria-selected=true] {
  display: none;
}
But, after using this style

if i select first 4 to 5 options then if i go for next option from keyboard(enter key) it is focusing one by one whatever elements we have changed to display:none(.select2-results__option[aria-selected=true])

because of this issue i have to press down key multiple number of times to focus the options left in the drop down.

**Comment by alexweissman** [comment]
See the discussion in https://github.com/select2/select2/issues/4105#issuecomment-211665303.
