### ISSUE TITLE
Setting the value in javascript

### ISSUE THREAD

**Issue by bryanes335** [select2/select2#3688]
I have a select2, and I am curious how I should be setting the value in js.

A -- this works -- $("#usergroup").val("bryanm").trigger("change");
B -- this works -- $("#usergroup").select2("val","bryanm");

However -- the Renamed Methods under 4.0.0 Beta 1 states that:
.select2("val", [value]) -> .val([value])

So -- does this mean I should simply do this?
$("#usergroup").val("bryanm");

BUT -- this does not update the display (unless you trigger the change).

So, I'm just curious if this is a bug, or if I should just use method A or B above.

**Comment by kevin-brown** [comment]
You should be using method A.

This is something we have better documentation for, which you'll most likely see in the near future.

**Comment by bryanes335** [comment]
Thanks Kevin.  Love the plugin by the way.
