### ISSUE TITLE
Invalid code in 3.5.3. Crashes with Can't find variable: opts

### ISSUE THREAD

**Issue by jeteve** [select2/select2#3694]
Line 2748, in function data: function(value){ ... }

opts is not defined. You probably mean this.opts ?

**Comment by mani-zenefits** [comment]
Any idea when can we expect the fix for this to be released?

**Comment by alexlafroscia** [comment]
@kevin-brown Will you be fixing this and releasing `3.5.3`? Or will this have to wait until someone else claims responsibility for anything else on `3.X`?

**Comment by kevin-brown** [comment]
@alexlafroscia Given that this was my fault, I'm going to handle releasing Select2 3.5.4. Hopefully it will happen this weekend, at which point I'll be handing over the reigns to the first person who offers.

**Comment by alexlafroscia** [comment]
Cool, thanks @kevin-brown :)

**Comment by binarious** [comment]
I'm getting `tags is not defined` since 3.5.3. Version 3.5.2 works. Seems similar.

**Comment by bardware** [comment]
`tags is not defined` seems to be fixed in current head #3695
https://github.com/select2/select2/commit/2b8cbde7eb46b34c270664c98b9ab115361b990e

**Comment by kevin-brown** [comment]
Fixed in https://github.com/select2/select2/commit/a7e8f2bfade064245a442c0245453cb0f6fdc57f.
