### ISSUE TITLE
Tags are broken in 3.5.3

### ISSUE THREAD

**Issue by kevin-brown** [select2/select2#3695]
Noticed this right after the release last night.

**Comment by grabcode** [comment]
+1

**Comment by Noodlewitt** [comment]
Also having problems with this in 4.0 - 
here's a fiddle:
http://jsfiddle.net/Noodlewitt/k1gLagmg/1/

**Comment by kevin-brown** [comment]
@Noodlewitt 4.0 and 3.5.x are completely different beats (different code bases as well).

If you're having an issue in 4.0.0, it's preferred if you create a new ticket about it.

**Comment by tzellman** [comment]
I believe this will fix the broken tags. #3705
