### ISSUE TITLE
autofocus isn't supported

### ISSUE THREAD

**Issue by alvarotrigo** [select2/select2#3696]
The select box when in auto-focus doesn't have any different style than when its not in auto-focus.
This might create confusion in the users.

[Reproduction online](http://jsfiddle.net/mJEZK/13/)

Not only that, but it also doesn't seem to work at all in Firefox. By neither using the `autofocus` attribute or calling the `focus` function.

Using the arrow keys won't change the selection.

**Comment by kevin-brown** [comment]
You should notice that the original (now hidden) `<select>` is being focused instead of Select2.

**Comment by arturoribes** [comment]
As of version 4.0.0 I did the following modifications:

In _registerEvents function, for autofocus:

              this.on('focus', function () {
                  self.$container.addClass('select2-container--focus');

                  // ADDED: auto opening on focus
                  if (!self.$container.hasClass('select2-container--disabled') && !self.isOpen()) {
                      self.open();
                  }
              });

In this.on('keypress'), to use tab correctly

            else if (key === KEYS.TAB) {
                          // ADDED: use tab to select and then jump to next field 
                          self.trigger('results:select');

                      }

**Comment by bangzek** [comment]
One workaround is:
`$("[autofocus] + .select2 .select2-selection").focus();`

**Comment by pedrofurtado** [comment]
The solution provided by @arturoribes works great in select2 4.0.3.
@kevin-brown Is possible to include him solution in the next version of select2?

**Comment by pedrofurtado** [comment]
@kevin-brown Any news about this issue? The solution provided by @arturoribes (https://github.com/select2/select2/issues/3696#issuecomment-152150121) seems to be a simple and functional fix.

**Comment by pedrofurtado** [comment]
@kevin-brown @alexweissman Any news about this issue?

**Comment by alexweissman** [comment]
Is there an open pull request?  I don't know much about autofocus.

**Comment by marcioJesus** [comment]
@kevin-brown @alexweissman Any news about this issue?

**Comment by pedrofurtado** [comment]
@arturoribes @alvarotrigo PR merged, in next release this change will be available for all users :tada:
