### ISSUE TITLE
select2 AJAX JSON problems :(?¿?¿

### ISSUE THREAD

**Issue by 1304654** [select2/select2#3699]
I'm having so much trouble bringing ajax data. As you enter the text you do not select the correct row me, but if I can select with the mouse. You know the problem? It may be a bug?
![prueba](https://cloud.githubusercontent.com/assets/2886820/9395112/b764af6a-478c-11e5-8492-4cba0bd53dfa.png)

**Comment by kevin-brown** [comment]
Let's keep this to the mailing list.

https://groups.google.com/forum/#!topic/select2/2zjXigvurSY
