### ISSUE TITLE
Knockout 3 custom handler?

### ISSUE THREAD

**Issue by Trapulo** [select2/select2#3704]
Any plan to have an official, or at least "well done", custom binding handler for Select2 v. 4 and Knockout?

thanks

**Comment by kevin-brown** [comment]
We more or less don't have any "official" integrations between Select2 and other plugins ([x-editable being an exception](https://github.com/select2/x-editable)).

If you do find an integration, feel free to create a pull request that adds it to https://github.com/select2/select2#integrations
