### ISSUE TITLE
Scrolling outside an active select2 in an absolutely positioned element in 4.0 causes 'shimmering' in Safari

### ISSUE THREAD

**Issue by BenDTU** [select2/select2#3706]
For context - our site uses a fixed topbar with a 'content' div below it, which is absolutely positioned. We're currently upgrading to 4.0 and found the following:

http://jsfiddle.net/yr7fL439/

If you try that link in OSX Safari and try scrolling down, it'll 'shimmer', like it's trying to scroll down with momentum but isn't able to. This doesn't happen in 3.5:

http://jsfiddle.net/kgr4mk00/

**Comment by kevin-brown** [comment]
I might as well note that I can't reproduce this in Chrome on Linux or Windows. But that makes sense, as this probably has something to do with Safari's smooth animated scrolling on OS X.

In 3.5 we used a background mask and didn't really pay much attention to scrolling except for repositioning the dropdown. A change was made in 4.0 where we stop all scrolling of parent elements to avoid issues with fixed position content, like modals.
