### ISSUE TITLE
Select2 4.4 data-allowClear

### ISSUE THREAD

**Issue by koren88** [select2/select2#3709]
Hello

Do select2 4.0 support declaring allowClear in data attribute. 
In documentation says that all configuration can be configure through data-* attribute, but when i use data-allowClear="true it doesnt do nothing.

https://select2.github.io/options.html#data-attributes

**Comment by iamwebdesigner** [comment]
Try also: `data-allow-clear="true"`, not sure it would help.

**Comment by koren88** [comment]
I tried adding data-allow-clear="true" and it works now. Thank you.

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/3630.
