### ISSUE TITLE
Problem with auto-scrolling the last active element on the list

### ISSUE THREAD

**Issue by lstypka** [select2/select2#3710]
There is problem with auto-scrolling highlighted element for list with infinite scroll (select2-more-results). The problem occurs when I try to select last element which is not disabled, but below there are disabled items.
Registered behavior:
![2015-08-26 17h10_55](https://cloud.githubusercontent.com/assets/1587788/9498061/435604f8-4c18-11e5-86e4-b2eea185b9de.gif)

**Comment by kevin-brown** [comment]
This is directly related to https://github.com/select2/select2/issues/1879 and isn't something I have plans to fix in the 3.5.x branch.

The highlight handling is _pretty nasty_ there and it's handled in a different way in 4.0.0.
