### ISSUE TITLE
Paste tags with newlines, use textarea as search input?

### ISSUE THREAD

**Issue by sandermarechal** [select2/select2#3712]
Is it possible to be able to paste tags into the search box that are separated by newlines, so the tags themselves can contain spaces? It seems that, because an `<input type="text" />` is used, that newlines are converted to spaces before they arrive at the tokenizer function. Is it possible to use a `<textarea>` as search box instead, so that newlines are preserved?

**Comment by denodster** [comment]
I am running into this problem as well, I'll see if its possible to devise a patch.

**Comment by denodster** [comment]
Work is occurring on the PR

**Comment by denodster** [comment]
Blah, this is still a bug.
