### ISSUE TITLE
Select2 Onchange event triggered while applying data manually(how to suppress this)

### ISSUE THREAD

**Issue by jaggu3017** [select2/select2#3714]
Previously I am using select2 3.3.2, in that while applying data through this syntax, 
jQuery('#elementId').select2('data', {"id":1,"text": "some value"}, true);
It is not triggering that elements onchange event.
I upgraded to 3.5.1, now its triggering the onchange event.
If the change is intentional, is there any way to suppress that onchange event by passing a parameter to select2?
Thanks in advance.

**Comment by kevin-brown** [comment]
Just for reference, 3.3.2 was released on May 9, 2013 and is pretty far out of the support cycle. 3.5.1 also isn't the latest release in the 3.5.x line, I'd recommend 3.5.2.

The `select2('data')` method supports a `triggerChange` argument as the third parameter, and you're passing in `true` so it does trigger the `change` event.

Try passing in `false`.
