### ISSUE TITLE
Array data is ignored when the html `select` contains `option`s 

### ISSUE THREAD

**Issue by dira** [select2/select2#3715]
Demo: http://jsfiddle.net/4bb6tn1m/16/

Test case:
* apply `select2` with `data` and `templateResult`
* `destroy` the select2
* apply again `select2` with the same `data` and `templateResult`

Expected result: to have the same options in the select.
Actual result: the data parameter is ignored and the text of the html options is taken into account. The options have some 'undefined' content.

I think the root cause is that the array data parameter is ignored when the html `select` already contains `option`s.

jQuery 2.1.3, Select2 4.0.0-rc2

**Comment by kevin-brown** [comment]
This is still an issue with the released version of Select2 4.0.0 (you might need to update).

https://jsfiddle.net/4bb6tn1m/17/

And this will be fixed when 4.0.1 is released.

https://jsfiddle.net/4bb6tn1m/18/

This was fixed in https://github.com/select2/select2/pull/3565.
