### ISSUE TITLE
Wrong dependancy name for jquery-mousewheel

### ISSUE THREAD

**Issue by venimus** [select2/select2#3725]
Npm package name is set to `jquery.mousewheel` instead of `jquery-mousewheel`

https://www.npmjs.com/package/jquery-mousewheel

**Comment by venimus** [comment]
Sorry, seems there are 2 different packages 
https://www.npmjs.com/package/jquery.mousewheel
my bad

**Comment by kevin-brown** [comment]
Uhp, this is actually going to be an issue in the future.

We should be using `jquery-mousewheel` as the dependency name instead of `jquery.mousewheel`.
