### ISSUE TITLE
Change DropdownAdapter

### ISSUE THREAD

**Issue by brunoDegaspare** [select2/select2#3726]
How can I disable the dropabove behaviour?

"When the dropdown is attached to the body, you are not limited to just displaying the dropdown below the container. Select2 will display above the container if there is not enough space below the container, but there is enough space above it. You are also not limited to displaying the dropdown within the parent container, which means Select2 will render correctly inside of modals and other small containers."

How can I change this behaviour? I want the dropdown to always display bellow.

**Comment by brunoDegaspare** [comment]
Ok I found a solution in case someone else is looking to achieve this. In 4.0, you can use the AttachContainer module to attach the dropdown to the parent container. - ref: https://github.com/select2/select2/issues/2873

Example: http://jsfiddle.net/brunodd/jEADR/2009/

**Comment by fetis** [comment]
The problem with this solution is that it places dropdown inside wrapper container and if you have special style requirement (as I had in my case) it'll be difficult to make it work.

So alternative solution is use `attachBody` adapter as mentioned here, but patch its `_positionDropdown` function that it always think, it's openning below. Just change
```
        var enoughRoomAbove = false;
        var enoughRoomBelow = true;
```
and it's done

Can we rename this topic in 'Always open dropdown below'?
