### ISSUE TITLE
maximumSelectionLength not respected when using ajax

### ISSUE THREAD

**Issue by dincho** [select2/select2#3727]
Setting maximumSelectionLength has no effect when using ajax object/config.

Example: http://jsfiddle.net/o1je0988/3/
Enter: ```1```, ```space```, ```2```, ```space```, ```3```, ```space```
Expected select values: 1,2
Actual Result: 1,2,3

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/select2/select2/issues/3449.

**Comment by dincho** [comment]
Are you sure? It DOES work without ajax: {} for me.
