### ISSUE TITLE
Documentation of v4 should get better

### ISSUE THREAD

**Issue by meridius** [select2/select2#3729]
There are a lot of things missing in the documentation - events for example. This is making things unnecessary difficult for both old and new users.

**Comment by kevin-brown** [comment]
Thanks for creating a ticket about this, we actually have [quite a few tickets](https://github.com/select2/select2/labels/documentation) about improving the documentation.

We're in the process of reworking the documentation (see https://github.com/select2/select2/pull/3724 and the `docs-faq` branch) so it's more user friendly. If you know of a specific area (such as events) which definitely needs to be covered, feel free to comment on https://github.com/select2/select2/pull/3724 or submit a pull request against the `docs-faq` branch.
