### ISSUE TITLE
Problem with EscapeMarkup in Select2 (3.5.x)

### ISSUE THREAD

**Issue by Daijobou** [select2/select2#3732]
Is here a little bugfix for this problem or I do something wrong?

See https://jsfiddle.net/247pju9p/1/

Input "s" in selectbox and you wil see damaged HTML in search results.

**Comment by kevin-brown** [comment]
The issue is that the method we use for underlining the search term in results does not work well when the search term is found within the HTML. You can get around this by disabling result marking within `formatResult`.

https://jsfiddle.net/247pju9p/2/

**Comment by Daijobou** [comment]
Sorry, but thats is not a solution. Its a bug in two ways.

https://jsfiddle.net/247pju9p/3/

I have change the text in option to "xxx". Now press "s" and you will get the first option als result. But in "Option 1 XXX" there is no "S" included. This is still a bug, please re-open this ticket.
