### ISSUE TITLE
Select2 looks awkward when used in bootstrap form

### ISSUE THREAD

**Issue by PandaWhisperer** [select2/select2#3736]
I'm trying to use select2 (4.0.0) in a bootstrap app. However, the styling comes out looking rather awkward. The dropdown uses a darker border with now shadow and is slightly shorter than the bootstrap form controls, which makes it look out of place. 

##### Without select2
<img width="577" alt="screen shot 2015-09-03 at 3 50 04 pm" src="https://cloud.githubusercontent.com/assets/749244/9672890/8714c3d2-5253-11e5-819a-8e9d82fef4d4.png">

##### With select2
<img width="573" alt="screen shot 2015-09-03 at 3 50 13 pm" src="https://cloud.githubusercontent.com/assets/749244/9672891/891d656c-5253-11e5-8682-371e6d2bc97e.png">

Improper alignment, control looks out of place. :grimacing:

**Comment by kevin-brown** [comment]
Luckily we have a Bootstrap theme for those using Bootstrap.

https://github.com/select2/select2-bootstrap-theme

The built-in classic theme also doesn't look that bad with Bootstrap.

**Comment by PandaWhisperer** [comment]
Thanks @kevin-brown :+1:
