### ISSUE TITLE
select 2 version 4 i18n

### ISSUE THREAD

**Issue by afattahi54** [select2/select2#3741]
In a multi lingual site we used to import select2.and its locale in the site. as below:

    <script type="text/javascript" src="/js/lib/select2.min.js"></script>
    <script type="text/javascript" src="/js/lib/i18n/${locale}.js"></script>

${locale} will be replace at the server, so for "fa" language we will have 

    <script type="text/javascript" src="/js/lib/i18n/fa.js"></script>

And for "ar" we will have

    <script type="text/javascript" src="/js/lib/i18n/ar.js"></script>

It worked fine for version 3.5. 
But it is not working for version 4.0 any more. Any comments ?!

**Comment by kevin-brown** [comment]
Select2 no longer sets the default language when you import the language file. But you can do that in your global setup file (before Select2 is initialized) by including

```js
$.fn.select2.defaults.set('language', '${locale}');
```

Which will set the default language for all Select2 instances created after setting it.

**Comment by afattahi54** [comment]
Thanks I find a very hacky way. ....  I opened the language files changed the

    return e.define("select2/i18n/fa"....

to


     return e.define("en" ....

and as before it works by just importing the required language file
