### ISSUE TITLE
Question: how do you clear the dropdown results after each tag/token add?

### ISSUE THREAD

**Issue by u01jmg3** [select2/select2#3743]
I am pulling in data from a remote source and am finding after choosing one tag/token and then proceeding to type in a new term (search is now based on the tag/token already chosen plus the new search term), I see the results of the first search before the results of the second search appear in the dropdown.

Is there any way to clear the dropdown after selecting a tag/token?

**Comment by althaus** [comment]
You can just hide the alreay chosen options through CSS:

```
    .select2-results__option[aria-selected="true"] {
        /* Hide selected options from dropdown */
        display: none;
    }
```

**Comment by alexweissman** [comment]
A symptom of this is discussed in more detail in #4854.
