### ISSUE TITLE
select 2 version change defalult location and file name of languages

### ISSUE THREAD

**Issue by afattahi54** [select2/select2#3746]
We are using select2 with other jquery plugins and because of some conflicts with other plugins, we need to change the default path of select languages files.

As I found we need to have this structure for a select2 plugin version 4.

```javascript
   +js
       select2.js
       + i18n
            fa.js
            zh_CN.js
```

Is it possible that I change the "default folder" of translation folder and the translation files "names"
(The i18n root should be set to "js/" the file names change to select2_messages-fa_IR.js)

```javascript
   +js
       select2.js
       select2_messages-fa_IR.js
       select2_messages-zh_CZ.js
``` 
I find amdLanguageBase property but I am not using AMD in the project.

**Comment by kevin-brown** [comment]
The translation files (once they are compiled) should not be affected by renames or having their location moved. The default structure is only a recommendation, as long as the files are being included on the page before Select2 is initialized you shouldn't have any issues.

**Comment by afattahi54** [comment]
Thanks, there is a hard coded path in translation files as:

    return e.define("select2/i18n/fa"

Should it be changed ?!

**Comment by afattahi54** [comment]
Thanks, But I try below with no luck:
1- Renamed the select2/lib/js/fa.js to select2/lib/js/fa_IR.js
2-Copy the fa_IR.js to my js folders as below:

        <script type="text/javascript" src="/js/lib/select2.min.js"></script>
	<script type="text/javascript" src="/js/lib/select2_messages_fa_IR.js"></script>
	
And set the language default as:

    $.fn.select2.defaults.set('language', 'fa_IR');

But I still see only English messages. The message file is loaded.

**Comment by afattahi54** [comment]
There is a hard coded path in select2 messages should it be changed ?!

    e.define("select2/i18n/fa",[] .....
