### ISSUE TITLE
`.select2-selection__clear` not used?

### ISSUE THREAD

**Issue by meowsus** [select2/select2#3749]
I was creating a theme from the "classic" theme and saw references to `.select2-selection__clear` in the CSS and JS, but couldn't figure out when it appeared. Is this a relic from a past release or is this selector supposed to be in the codebase still?

**Comment by kevin-brown** [comment]
This selector is used for the "x" that appears when you are using `allowClear`. You can find some references to it in the [`AlowClear` decorator](https://github.com/select2/select2/blob/ea074af14ca601fe2c58d349ec46d8bd72dd27c4/src/js/select2/selection/allowClear.js).

**Comment by meowsus** [comment]
Oh, duh! Thanks @kevin-brown!
