### ISSUE TITLE
Preserving order of chosen options.

### ISSUE THREAD

**Issue by meowsus** [select2/select2#3750]
I couldn't find anything about this in the documentation, but consider a select box with the following options:

- Option 1
- Option 2
- Option 3

By default if I choose Option 3, then Option 2, then Option 1 the display of the options remains Option 1, Option2, then Option 3. 

Is there a way to preserve the chosen order? Or will I need to extend the code to get this functionality?

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/select2/select2/issues/3106. You can find some possible solutions at https://github.com/select2/select2/issues/3106#issuecomment-77988110.
