### ISSUE TITLE
select2 width in Chrome

### ISSUE THREAD

**Issue by abstractOwl** [select2/select2#3752]
In Chrome and Internet Explorer, the second select2 dropdown is rendered with `width: auto` even though both selects use the same "mySelect" class. They do, however, render perfectly in Firefox.

http://jsfiddle.net/rnoy6mcc/3/

**Comment by tbgcrew** [comment]
Similar/Same as https://github.com/select2/select2/issues/3748 ?

Although noting the browser difference is interesting!

**Comment by tbgcrew** [comment]
Confirmed not the same issue as #3748
As noted by OP, issue occurs in Chrome but not FF
Issue #3748 occurs in both FF and Chrome

**Comment by kevin-brown** [comment]
Browsers typically can't determine the width of an element that is not on the page, and that's why you are seeing the `width: auto` being set. Select2 will set this if it can't determine a width to use.
