### ISSUE TITLE
Scrolling quickly with paginated ajax requests, stalls

### ISSUE THREAD

**Issue by SlyDave** [select2/select2#3758]
If you configure select2 to load additional options via ajax, then scroll through the list quickly as it loads, it will stall and display the "Loading more results..." text, but nothing happens.

Scrolling back up a fair bit then back down again sometimes, allows it to continue..

This can be reproduced on the select2 example page: https://select2.github.io/examples.html for the demo 'Loading more results…'.

It appears to always do this when it hits page 10.

If you enter "test" into the Loading remote data example, then using the mousewheel keep scrolling and scrolling, it will stop after the 10th ajax call, (at the time of test, this always should "liip/LippFunctionalTestBundle" as the last results then displayed the "loading more results..." text and nothing happens...

![image](https://cloud.githubusercontent.com/assets/1842611/9787074/52cb2d28-57b7-11e5-91a5-19224a51ba92.png)

**Comment by SlyDave** [comment]
What information do you need?

**Comment by kevin-brown** [comment]
Looks like I forgot to leave a comment earlier.

I need a test case that doesn't rely on GitHub's API. The reason why it consistently fails on page 11 is because that's when GitHub is blocking you for too many requests within the sliding two minute window. You can confirm this by checking the network console and watching the 403 consistently come in.

**Comment by SlyDave** [comment]
This doesn't appear to always be case

We first discovered this issue with our own data sources, But as I am unable to grant you access to that data, I reproduced it using the examples.

I can get the example to do what you've show with the 403's but I can also get it to do simply stop.

Below are some screens of a test I put together from our datasource and the network graph. I don't know what is going on, but there is something wrong - maybe it's select2, maybe it's the server - but unfortunately there is no information available and what I'm seeing is that select2 is no longer making requests.

This time it stopped after 20, repeated testing today shows it stopping at 10 or 20, which seems odd.
![image](https://cloud.githubusercontent.com/assets/1842611/9871489/ecfd4ef8-5b8b-11e5-9c7f-0bed5400fe45.png)

The network graph for this request:
![image](https://cloud.githubusercontent.com/assets/1842611/9871558/710c1dd2-5b8c-11e5-83c0-ad718ea55a56.png)

I've reproduced this in FF and Chrome.

**Comment by adrenalinkin** [comment]
@kevin-brown Hello Kevin, I think I found steps to reproduce bug, which described by @SlyDave.
I faced the problem with "loading more results..." today.

http://jsfiddle.net/adrenalinkin/ufjLjpLc

**Comment by erwinyusrizal** [comment]
I think the problem is bcos select2 trigger ajax using the scrollbar, for example if perpage = 5 the scrollbar doesnt appear since its not reach the `max-height: 200px`

```
.select2-container--default .select2-results>.select2-results__options {
    max-height: 200px;
    overflow-y: auto;
}
```
