### ISSUE TITLE
Select2 does not abort AJAX call with maximumInputLength is triggered

### ISSUE THREAD

**Issue by SlyDave** [select2/select2#3759]
If you set a MaximumInputLength and have your select2 configured to load more results.

It is possible to type in more chars than the MaximumInputLength, you'll see the "please delete x chars" message flash up, but when the load more results are returned it will replace the delete message. 

This mostly occurs when you've got a slow delay set on an ajax call, when a result is returned it replaces the drop down with the results, without checking to see if the user has typed chars beyond the limit.

To reproduce, take the select2 example for Load Remote Data, and add a maximumInputLength to it, then provide more chars than the maximumInputLength, but doing so in such a way, at least 1 request is made for remote data before hitting the maximumInputLength limit.

![image](https://cloud.githubusercontent.com/assets/1842611/9787278/4e93e946-57b9-11e5-840f-72e6da0ae3fe.png)
![image](https://cloud.githubusercontent.com/assets/1842611/9787282/59e0a816-57b9-11e5-9dff-4943f509474f.png)

**Comment by alexweissman** [comment]
This is likely caused by the same bug causing #3512.
