### ISSUE TITLE
Get the element appended from the change event?

### ISSUE THREAD

**Issue by catfive** [select2/select2#376]
I hunted through the attributes in the change event object for a way to get the actual <div> that's appended to the choices list, but could only find the selected <option>. Did I miss it?

I'm changing the full (looong) text of the options down to a shorthand version on select.

Currently I'm achieving this with a full-text search using .contains(), but that seems rather wasteful.

**Comment by alexweissman** [comment]
Seems to be an issue from v3 - in v4 this can be done as documented in https://select2.org/programmatic-control/events#event-data
