### ISSUE TITLE
Allow override of strings at init 4.0.0

### ISSUE THREAD

**Issue by SlyDave** [select2/select2#3760]
Like with placeholder, we need the ability to provide the text for loadingMore, no Results, searching etc. at init.

This is needed to allow different select2 elements to have different text for these strings so they are contextually correct for their usage. Using the language system to do this would be incorrect (and also a vast amount of work). Instead we want deliver the translated contextual version of the text to the select2 initialisation, this was possible in select2.3 via the Select2 3.x allowed for formatSearching, formatLoadMore - String containing "Loading more results…" message, or
Function used to render the message. etc.

````
$('#test').select2({
	placeholder: 'Please select an option...', // This works

	// These don't
	formatLoadMore: 'TESTING LOAD MORE',
	formatNoResults: 'TESTING NOTHING FOUND',
	formatSearching: 'TESTING SEARCHING',
````

**Comment by kevin-brown** [comment]
These were moved into the `language` section of options, as they are actually related to localization. You can find out how these were mapped in the 4.0.0-beta.1 release notes.

https://github.com/select2/select2/releases/tag/4.0.0-beta.1

**Comment by SlyDave** [comment]
Thanks for the quick response :+1:
