### ISSUE TITLE
Activate formatResult when user hasn't typed yet

### ISSUE THREAD

**Issue by ydgiannp** [select2/select2#3761]
I'm trying to add new item dynamically from FormatResult & FormatNoMatches via select2. It runs well, but there is 1 problem. I want to show 'add new item' row when user hasn't typed the input yet, so user wouldn't be confused to add new item when they click the dropdown.
Here is my code: 

``` js
$(".select2-single").select2({
    createSearchChoice:function(term, data) {
      data_modal=term;
      term = $.trim(term);
      var Dterm = term.charAt(0) + term.substr(1);
      if ($(data).filter(function() {
          return (this.text.localeCompare(Dterm) === 0);
      }).length === 0) {
          return {id:term, text: Dterm, isNew: true};
      }
    },
    formatResult: function(term) {
      if (term.isNew){
        return "+ "+term.text;
      }
      else {
        return term.text;
      }
    },
    formatResultCssClass: function (data, container) {
      if(data.isNew){
        return "select-2";   
      } 
    },    
    formatNoMatches: function(term) {
      return "<div><a href='#' id='newTerm' onClick='show_modal();'>+ Add New </a></div>";
    }
  });
```

does anything have a reference or advice regarding this problem? thank you

**Comment by alexweissman** [comment]
In Select2 v4, this can be handled with [tagging](https://select2.org/tagging).  You may use [`insertTag`](https://select2.org/tagging#customizing-tag-placement-in-the-dropdown) to place the "create new" option at the end of the results list, rather than the beginning, to avoid confusion.
