### ISSUE TITLE
Select2 should not make an ajax call if the search params hasn't changed.

### ISSUE THREAD

**Issue by SlyDave** [select2/select2#3763]
If you open a select2 element which has been configured for remote data, it will do an initial search with no search term. If you close the select2 element, then open it again, it will repeat the search.  Even though the search term hasn't changed, so the results won't be any different.

I guess it is possible to modify the query handler to check for this, but surely this should be default behaviour? (not to search if the conditions haven't changed)

**Comment by kevin-brown** [comment]
> I guess it is possible to modify the query handler to check for this

That's the intended fix, for those who can't have the extra query go on through.

> surely this should be default behaviour? (not to search if the conditions haven't changed)

We don't cache any requests in order to avoid situations where people are working with data that _can't be cached at all_, which is common in some areas.

**Comment by SlyDave** [comment]
:/ This does mean the default behaviour of select2 is non-optimal and developers needs to pretty much always do additional work to make the component because functional in a production environment.

There really ought to be a cacheAdapter that can be switched off for those needing no caching at all.
