### ISSUE TITLE
Option to display remaining number of remote items to display

### ISSUE THREAD

**Issue by SlyDave** [select2/select2#3765]
To allow for pagination to work smoothly select2 needs to know the total number of elements available via the remote datasource.

As such, it should be possible for select2 to display a footer at the bottom of the dropdown showing how many additional options are available. If you have infinite scrolling configured. A footer is an idea location to show the "loading more results" text too, and the total number can reduce as more options are loaded.

e.g.: Similar to this (our own custom component we are looking to replace with select2)
![image](https://cloud.githubusercontent.com/assets/1842611/9848570/3a3469c0-5ada-11e5-8f3f-fd0947b1eaf8.png)

I don't believe this is currently possible with templating as it'll make the dropdown part a selectable option?

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:
