### ISSUE TITLE
Tag not displayed when selected

### ISSUE THREAD

**Issue by mguinness** [select2/select2#3766]
I had an issue when using the tagging feature in conjuction with ajax data.  If you use the example below (with the second select), when creating a tag and selecting it in the dropdown it isn't displayed nor is the select event fired - even though the selected value is correct.

Doing the same with the first select it behaves as expected.  This was tested under Windows using IE 11 and Chrome 46.  The only difference is the omission of the empty option.

To me it seems unnecessary to have an empty option, but if it's required for whatever reason is it possible that Select2 can create it dynamically (or maybe throw an error) when initializing?

``` javascript
<!DOCTYPE html>
<html>
<head>
    <link href="//select2.github.io/dist/css/select2.min.css" type="text/css" rel="stylesheet">
    <style>
        select { width: 250px; }
    </style>
    <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="//select2.github.io/dist/js/select2.full.js"></script>
</head>
<body>
    <h4>Tag select does work</h4>
    <select data-placeholder="Select text">
        <option></option>
    </select>

    <h4>Tag select does not work</h4>
    <select data-placeholder="Select text"></select>
</body>
</html>

<script type="text/javascript">
    $('select').select2({
        tags: true,
        allowClear: true,
        minimumInputLength: 1,
        ajax: {
            url: 'https://api.github.com/search/repositories',
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    q: params.term,
                    page: params.page
                };
            },
            processResults: function (data) {
                return {
                    results: $.map(data.items, function (o) {
                        return { id: o.id, text: o.full_name };
                    })
                };
            }
        }
    });
    $('select').on('select2:select', function () {
        console.log('on select: ' + $(this).val());
    });
    $('select').on('select2:close', function () {
        console.log('on close: ' + $(this).val());
    });
</script>
```

**Comment by kevin-brown** [comment]
It sounds like this might be a bug, but I'd need to do some more testing to confirm that.

> To me it seems unnecessary to have an empty option, but if it's required for whatever reason is it possible that Select2 can create it dynamically (or maybe throw an error) when initializing?

You might find the following comment (and the ticket about it) relevant and useful: https://github.com/select2/select2/issues/3553#issuecomment-119772829
Basically the issue can't be automatically detected and it's not possible to automatically correct it.

**Comment by alexweissman** [comment]
This problem is discussed more thoroughly in #4842.
