### ISSUE TITLE
compatibility issues with jschr/bootstrap-modal

### ISSUE THREAD

**Issue by joelmora** [select2/select2#3771]
Hi! I think there is a proble related with z-index property on select2 plugin, when you use it with bootstrap-modal plugin select2 stays on the bottom of the modal

Here is the [Issue](https://github.com/jschr/bootstrap-modal/issues/280?_pjax=%23js-repo-pjax-container)

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by joelmora** [comment]
>* What steps can be used to reproduce the issue?

https://jsfiddle.net/cz1c0j6j/


>*What is the bug and what is the expected outcome?

select not showing on top of the modal (neither the first modal nor the second)


>*What browser(s) and Operating System have you tested with?

Firefox (40.0.3) and chrome (45.0.2454.85)


>*Does the bug happen consistently across all tested browsers?

Yes


>* What version of jQuery are you using? And what version of Select2?

jQuery 2.1.3 and select2 4.0.0


>* Are you using Select2 with other plugins?

Yes, with bootstrap-modal (2.2.6)





What I did to solve temporary the issue was adding this lines

```javascript
var zindexModal = $('.modal-scrollable:last').css('z-index');

      if(typeof zindexModal != 'undefined'){
          this.$dropdown.css('z-index', zindexModal)
      }
```

to the

```javascript
AttachBody.prototype._positionDropdown = function() {}
```

is not a clean solution but I had to do it in order to solve it

**Comment by kevin-brown** [comment]
This is a CSS problem that Select2 can't automatically detect on its own. The z-index by default is set to 1051, which is just enough to override a standard Bootstrap modal without causing too many extra issues.

The modal plugin you are using is setting a higher z-index, so the Select2 dropdown is showing behind it. You can override the dropdown's z-index with CSS as described in https://github.com/select2/select2/issues/3388#issuecomment-128700782.
