### ISSUE TITLE
Can not change inputTooShort

### ISSUE THREAD

**Issue by Thereisnobugs** [select2/select2#3776]
In select2 4 can not change message only for inputTooShort .

**Comment by kevin-brown** [comment]
You should be able to override it with `language.inputTooShort`.

https://github.com/select2/select2/releases/tag/4.0.0-beta.1

**Comment by Thereisnobugs** [comment]
Ok. I'm understant it, but i need to use select2 Internationalization 
```
options = {
    language: 'ru',
    ...
}
```
and rewrite only one message inputTooShort for all languages. Languges can be changed by user.
