### ISSUE TITLE
AllowClear decorator throws exception when no placeholder is specified

### ISSUE THREAD

**Issue by SPodjasek** [select2/select2#3781]
There is no null check on `placeholder` property, so if you do clear select2 without `placeholder` set an `this.placeholder is undefined` exception is thrown:

[selection/allowClear.js](https://github.com/select2/select2/blob/master/src/js/select2/selection/allowClear.js#L61)
```javascript
    this.$element.val(this.placeholder.id).trigger('change');
```

Or maybe `placeholder` was meant to be required in combination with `allowClear: true`

**Comment by kevin-brown** [comment]
This was handled in https://github.com/select2/select2/issues/3016, `placeholder` is meant to be required with `allowClear: true` for now.
