### ISSUE TITLE
Uncaught Error: Option 'ajax' is not allowed for Select2 when attached to a <select> element.

### ISSUE THREAD

**Issue by MrVibe** [select2/select2#3783]
Even with Select2 4.0.0 we're seeing this error. As per the announcement we're no longer adding the input element.

html : 
<select class="select2"></select>

javascript :
 $('.select2').select2({
        minimumInputLength:2,
        placeholder: $(this).attr('data-placeholder'),
        ajax: {.....

Update : 
Still works with &lt;input type="hidden" class="select2" />

Is the documentation correct ? or am I missing something ?

p.s: select2 was installed today via bower

**Comment by MrVibe** [comment]
Ok.. marking this as resolved.
There was an older version of select2 which was was conflicting here.
Resolved.

**Comment by suraj04081993** [comment]
Refer this link for more information- http://itfrustration.in/jquery-select2-ajax/

**Comment by arjunkesava** [comment]
The above link was dead! (http://itfrustration.in/jquery-select2-ajax/)
Please give another example

**Comment by satalways** [comment]
Above link is spammer I think.
