### ISSUE TITLE
"Selective" download?

### ISSUE THREAD

**Issue by SRGOM** [select2/select2#3784]
I realize that this is really hard to do, and am not counting on this to ever happen but throwing it out there anyway- Is it possible to have a downloader that allows one to selectively download what features one needs. For example, if someone wants to only use pre-populated select and multi-select boxes with no plugins. Would that reduce the size of library?

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/select2/select2/issues/1930#issuecomment-73377586.
