### ISSUE TITLE
select2.github.io Download Link confusing. Suggesting New Link

### ISSUE THREAD

**Issue by gshiftlabs-mwinger** [select2/select2#3785]
When I look at the select2.github.io page, the download link at the top has "Version 4.0.0" underneath, however it takes me to the github Releases page.

The confusing part about that is that the download link does not point to a *specific* release. Thus, as of writing this, two releases have been pushed for 3.5.x to add compatibility for migrating up to version 4, and it took a bit of looking around to realize that version 4.0.0 release was just lower in the list because it was made earlier.

My suggestion is to point the download link directly at the release it is intended to be shown with to avoid this issue.

**Comment by kevin-brown** [comment]
I'm actually going to close this off as this shouldn't be an issue after we push the 4.0.1-rc.1 release later today.
