### ISSUE TITLE
Synchronize CSS changes between <select> and Select2

### ISSUE THREAD

**Issue by Cristallix** [select2/select2#3790]
Hello,

I'm trying your wonderful plug-in and I am really impressed. I am working with some ajax and I have to show and hide my select dynamically. When I am using in jQuery .hide() and .show() on my `<select>` the style isn't applied on select2.

I am missing something or maybe do you have an alternative to this?

Thank you for your help!

**Comment by kevin-brown** [comment]
This is because CSS changes are not synchronized from the original `<select>` to Select2. This might be a regression from 3.5.x, and this might be a duplicate of an existing ticket.

**Comment by Cristallix** [comment]
Also, how about media query? Right now you don't handle them, right?

I had to add this to make them working with my css :

>.select2 {
>	width: 100% !important;
>}

**Comment by Naeemo** [comment]
maybe try to synchronize the width change first, my layout can go wrong with a single scroll bar showing up.Inside the initialization process, the original width was set to select2, how about reset this when window.resize triggered?
