### ISSUE TITLE
Select2 4.0.0 Tag - the New Value Is Lost When User Clicks Away

### ISSUE THREAD

**Issue by superKalo** [select2/select2#3791]
Hello,

I am having a usability issue with Select2 4.0.0 and the field for tagging. Here is an example: http://jsfiddle.net/superKalo/vc0zLmLs/
1. I add a new tag, and I hit Enter or any of the token separators (", " or " ") - all good.
2. I add a new tag, but then I just click away somewhere else in the form - my value is lost :(

Is there any solution to this one in Select2 4.0.0?

Thanks!
Kalo.

**Comment by dmdm22** [comment]
Hi,

the parameter you need is 'selectOnClose'. Just set this to true.

If set to true and you need the select to work in IE you should also set 'closeOnSelect' to false, otherwise you will get an endless loop .. as said, IE only.

Greetings

**Comment by superKalo** [comment]
Hello,

I ended up adding 'selectOnClose' set to true plus additionally 'closeOnSelect' set to false [to escape from the infinite loop issue](https://github.com/select2/select2/issues/3169#issuecomment-97297464).

Here is the final solution: http://jsfiddle.net/superKalo/vc0zLmLs/

Thank you @dmdm22 !
Greetings!

**Comment by kirame09** [comment]
@superKalo : Your solution work fine but also has an issue, It will not close when mouseclick or enter, You need to doubleclick or double enter which is not working as usual. ..

**Comment by superKalo** [comment]
@kirame09 yes, you're right there are a few bugs, hopefully in the next version of the plugin they will be resolved. That's the best I could find. I guess there's nothing left beside to [join the contributors](https://github.com/select2/select2/graphs/contributors) and try to resolve them :)
