### ISSUE TITLE
Can select2 be compatible with Zepto?

### ISSUE THREAD

**Issue by futurist** [select2/select2#3792]
In mobile project there's a need to using Zepto in stead of jQuery. I'm trying to edit source code to make it compatible with Zepto but still there're some issues, is it possible to make it work, or can you make a branch for Zepto?

> Place holder lost when using Zepto:
> ![aaa](https://cloud.githubusercontent.com/assets/159167/10088810/28907a0a-6350-11e5-90c0-f7f86463f363.png)

**Comment by kevin-brown** [comment]
Ideally, this could be done in the same code base with a few small changes. I'd rather see us find Zepto-compatible methods (also supported by jQuery) rather than polyfill jQuery methods for Zepto.

**Comment by pedrofurtado** [comment]
Sorry, the `3.x` version is not maintained anymore. But fell free to fork the repo and fixes what you need.
