### ISSUE TITLE
English i18n module cannot be changed...

### ISSUE THREAD

**Issue by bensampaio** [select2/select2#3796]
I want to use my own translations instead of the ones available in select2. I was able to accomplish this for every language except English.

I have the following JS file:

select2.mylang.js (ES6)

``` js
jQuery.fn.select2.amd.define("select2/i18n/en", [], () => {
    return {
        errorLoading() {
            return 'Test';
        },
        inputTooLong(args) {
            return 'Test';
        },
        inputTooShort(args) {
            return 'Test';
        },
        loadingMore() {
            return 'Test';
        },
        maximumSelected(args) {
            return 'Test';
        },
        noResults() {
            return 'Test';
        },
        searching() {
            return 'Test';
        }
    }
});
```

And I'm including this file in the page after select2, as follows:

``` html
<script type="text/javascript" src="/path/to/select2.full.js"></script>
<script type="text/javascript" src="/path/to/select2.mylang.js"></script>
```

If I replace `en` for `nl` everything works as expected but if I use `en` it just ignores my translations. Am I doing something wrong or is this a problem with select2?

Thank you!

**Comment by alexweissman** [comment]
See the discussion in #3799.
