### ISSUE TITLE
Select2 Seachbox doesnt open in Internet Explorer compatibility mode

### ISSUE THREAD

**Issue by chandoos** [select2/select2#3797]
Select2 Seachbox doesnt open in Internet Explorer compatibility mode and it doesnt throw any errors in the console as well. I could see the select box but it doesnt even open and not even able to  see search box. The same code is working fine in IE without compatibility mode or chrome. This issue is specific to the select box within Jquery ui dialogue box. Otherwise its working fine.

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).
