### ISSUE TITLE
Overriding noResults and other language strings

### ISSUE THREAD

**Issue by qaharmdz** [select2/select2#3799]
With 4.0.0-rc2 I can use this

```
if (jQuery().select2) {
    $.extend($.fn.select2.defaults.defaults.language, {
        noResults: function() { return 'No results found (Test)'; }
    });
}
```

But it's not work anymore at 4.0.0 stable. 
Setting default options at https://select2.github.io/options.html doesn't have any clue to change default message.

Any help or hint is appreciated, thanks

**Comment by piotr-cz** [comment]
I have to confirm that setting custom language strings doesn't work in v4.0.0.
Using documented method:

```js
jQuery.fn.select2.defaults.set('language--noResults', function() { return 'test'; })
```

the Options object is altered, but Select2 somehow doesn't have any effect (generic options are still  effective).

By the way: at this moment using this method, whole `language` object is being overwritten, I believe there should be used a deep copy option in [`jQuery.extend`](http://api.jquery.com/jQuery.extend/) in the [`defaults.js`](https://github.com/select2/select2/blob/4.0.1-rc.1/src/js/select2/defaults.js#L390) file to overwrite just specific language string(s).

My workaround is to set the language string during init, as described here #3190

**Comment by nebulousGirl** [comment]
You can override the default language values using the following: 

```JavaScript
    $.fn.select2.defaults.set('language', $.fn.select2.amd.require("select2/i18n/fr"));
```

**Comment by smuuf** [comment]
I have my object with language strings (*functions that return strings*) available in my current scope. How it is not possible to simply set it as a default language "object"?

Why should I have to require some external language file, which I don't have? *(I have the object right "here".)*

**Comment by jpic** [comment]
Have you tried something amongst the lines of the above suggestion ?

     $.fn.select2.defaults.set('language', yourObject)

**Comment by smuuf** [comment]
Yes, that what i have had before I noticed it didn't work. :/

```js
$.fn.select2.defaults.set('language', {
	errorLoading: function () {
		return "ERROR_LOADING";
	},
	inputTooLong: function (args) {
		return "INPUT_TOO_LONG";
	},
	inputTooShort: function (args) {
		return "INPUT_TOO_SHORT";
	},
	loadingMore: function () {
		return "LOADING_MORE";
	},
	maximumSelected: function (args) {
		return "MAX_SELECTED";
	},
	noResults: function () {
		return "NO_RESULTS";
	},
	searching: function () {
		return "SEARCHING";
	}
});

// Initialize Select2 globally (except those that are supposed to be standalone).
$('select').not('.standalone').select2();
```

Does this:

![image](https://cloud.githubusercontent.com/assets/6860713/21766449/f490543a-d66e-11e6-83d2-fda84197a537.png)

Select2 version: `Select2 4.0.0`

**Comment by jpic** [comment]
FTR this is also an issue in DAL https://github.com/yourlabs/django-autocomplete-light/pull/746

**Comment by diogolr** [comment]
https://github.com/select2/select2/issues/3799#issuecomment-271272381

Works for me, with a little bit of adjustment on initialization. I think you should use ``$('select'):not( 'standalone').select2();``.

Here's my code:

```javascript
// Based on {% static %}/select2/js/i18n/pt-BR.js
$.fn.select2.defaults.set( 'language', {
    errorLoading: function(){
        return "<span class='text-warning'><b>Os resultados não puderam ser carregados.</b></span>"
    },
    inputTooLong: function( e ){
        var t = e.input.length - e.maximum;

        n = "Apague " + t + " caracter";

        return t != 1 && ( n += "es" ), n
    },
    inputTooShort: function( e ){
        var t = e.minimum - e.input.length;

        n = "Digite " + t + " ou mais caracteres";

        return n
    },
    loadingMore: function(){
        return "Carregando mais resultados…"
    },
    maximumSelected: function( e ){
        var t = "Você só pode selecionar " + e.maximum + " ite";

        return e.maximum == 1 ? t += "m" : t += "ns", t
    },
    noResults: function(){
        return "<span class='text-danger'><b>Nenhum resultado encontrado<b></span>"
    },
    searching: function(){
        return "<span><i class='fa fa-spin fa-spinner'></i> Buscando…</span>"
    }
});

$( "select:not([ajax-url])" ).select2({
    placeholder: 'Selecione a(s) opção(ões)...',
});
```

**Comment by iFlash** [comment]
Maybe I am blind, but has anybody come up with a proper solution to this?

I want to change the "Searching..." message dynamically, but it will not change the wording on select2 init. If I only change the language (using the language files), that works fine, but how can I set the language AND then change single messages (like the Searching... message) dynamically during init?

I tried 
... language: { locale: "de", searching: "test" } ...

but that did not do the trick. Any help highly appreciated.

**Comment by doncatnip** [comment]
I have the same issue and none of the suggested workarounds work. If I try to override via JavaScript, I've got the same result as smuuf - nothing changes.

**Comment by pkbarbiedoll** [comment]
doncatnip, same here. 

user **aeksco** had a nice suggestion in #4088:  https://github.com/select2/select2/issues/4088#issuecomment-216992575

**Comment by MXTcomunica** [comment]
I have the same issue described in https://github.com/select2/select2/issues/3799#issuecomment-354763980

What is the proper way to use a provided language, e.g:
https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/i18n/it.js

and THEN override only a language option with a custom one, keeping all the other untouched?

**Comment by kareem** [comment]
Is there an accepted way of overriding the noResults text?  I really like this solution proposed here: https://github.com/select2/select2/issues/4088#issuecomment-216992575
