### ISSUE TITLE
Setting minimumInputLength is ignored

### ISSUE THREAD

**Issue by daFish** [select2/select2#38]
I'm using select2 with an AJAX-provider. To prevent empty calls to retrieve the whole list I set the minimumInputLength to 1 but it seems this setting is not recognized when the call is made.

Is this intentionally made or a bug?

**Comment by dtruel** [comment]
i did the exact same thing!  It seems like it would make sense to put it in the ajax settings, as I'm not sure you would use it if all the data was already loaded.

**Comment by twf-nikhila** [comment]
I did the same thing :( and wasted my 30 Mins trying to figure it out.

**Comment by alexweissman** [comment]
So, `minimumInputLength` applies to all data sources, not just AJAX.  It is _most commonly_ used with AJAX data sources, but it can be used with other data sources as well.

**Comment by hartator** [comment]
Come accros the same issue, it's actually a bit confusing in the documentation. Making a PR.

**Comment by rizkyarlin** [comment]
Hi @hartator, they haven't change the docs yet. https://select2.org/data-sources/ajax
