### ISSUE TITLE
Give list of public events in the doc

### ISSUE THREAD

**Issue by joshkpeterson** [select2/select2#3806]
Would be good to know what events one can easily listen for, without having to dig into the source. Doc currently states only:

>All public events are relayed using the jQuery event system, and they are triggered on the <select> element that Select2 is attached to. You can attach to them using the .on method provided by jQuery.

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/select2/select2/pull/3734 which was handled in https://github.com/select2/select2/pull/3724 and will be live... soon.
