### ISSUE TITLE
Lost text when click to edit

### ISSUE THREAD

**Issue by hieunguyentrung** [select2/select2#3808]
Hi. Im using lastest Select2, enable tag mode. While Im typing a new tag, i want use mouse to focus to this text (still not Enter yet), but the text gone. Could you guys helpe me keep text when focus mouse to that?

**Comment by ivanmcgregor** [comment]
I too find it bad for usability that the input is deleted and the dropdown closed when one tries to click into their written text (i.e. to correct spelling). This is **very** counterintuitive.
