### ISSUE TITLE
X (clear) button not clickable if select input width is smaller than option text

### ISSUE THREAD

**Issue by syndbg** [select2/select2#3809]
Reproducible in: http://jsfiddle.net/jEADR/2169/

Scenario:

* Select `Alabama` from input
* Click the X (clear) button
* Verify it works. Good!
* Now select `Long` from input
* Try clicking the X (clear) button
* Verify it does not work.

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/select2/select2/issues/3306.
