### ISSUE TITLE
Select2 4.0.0 -  iOS show keyboard on open

### ISSUE THREAD

**Issue by zrc210** [select2/select2#3814]
Apologies if this is a duplicate, but I can't seem to find a similar issue.

We are experiencing an issue with select2 controls on a remote data backed select2, with a `minimumInputLength: 1`.

Essentially, on iOS 9.0.0+ devices (Safari), select2 selects don't `focus` on the search text input field. This has a side effect of having the user tap twice on on the select2 element - once to open the control, once to focus on the input field.

This can easily be seen with iOS devices, as well as the iOS simulator in Xcode with https://select2.github.io/examples.html.

I have tried naive solutions such as triggering on `select2:open` events, and doing a focus on `.select2-search__field`, but that also hasn't been fruitful. Also tried listening to `touchstart` events, but also, that did not seem to put us on the track for a solution.

One thing that I did notice was that `select2:open` event was being triggered twice, but is likely unrelated to this issue.

**Comment by smzchaudary** [comment]
So, testing with the iOS simulator, and having the developer console open for safari shows that opening the select2 does set the focus on:

```
<input class="select2-search__field" type="search" tabindex="0" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" role="textbox">
```

**Comment by smzchaudary** [comment]
So, this is getting stranger - If I record the timeline of clicking the select2 element, the keyboard shows up on the first click.

**Comment by smzchaudary** [comment]
Some more information - this seems to only be an issue with the single select. With the multiselect, the keyboard shows up after the first click.

**Comment by estevaolucas** [comment]
+1. The same problem is happening for me.

**Comment by smzchaudary** [comment]
We have temporarily mitigated the issue by running the latest `select2.js` and `select2.css` from master and, running the application as a [Web Application](https://developer.apple.com/library/mac/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html).

In this configuration, the virtual keyboard does appear on single select open.

Just putting this out there in case anyone else is in a pinch - it would be nice if we could fix this for applications running within safari as well/

**Comment by Poolaidman** [comment]
I had the same issue and the following code worked for me

`<script>
$(".select2-container").click(function(){
  $('.select2-search__field').trigger('focus');
});
</script>`

Now in ios the keyboard pops up when you click the select box once

**Comment by e11en** [comment]
+1
Solution of Jeff-P fixed it for me.

**Comment by puglyfe** [comment]
just to elaborate on @Jeff-P solution..

in iOS, focus must be triggered by a user-initiated event to open the keyboard, so it can't be attached to one of the select2 events (eg 'select2:open', etc).

this is what i ended up going with:
```
$('.select2-container').click(function (e) {
  $(e.currentTarget).prev('select').data('select2').$dropdown.find('.select2-search__field').focus();
});
```

**Comment by philippkeller** [comment]
After wrestling with this for some hours I came up with this (which is a mix of different solutions I found on the web):

```js
  // on first focus (bubbles up to document), open the menu
  $(document).on('focus', '.select2-selection.select2-selection--single', function (e) {
    $('.select2-search__field').trigger('focus');
  });

  // steal focus during close - only capture once and stop propogation
  $('select.select2').on('select2:closing', function (e) {
    $(e.target).data("select2").$selection.one('focus focusin', function (e) {
      e.stopPropagation();
    });
  });
```

**Comment by valdemarus21** [comment]
> After wrestling with this for some hours I came up with this (which is a mix of different solutions I found on the web):
> 
> ```js
>   // on first focus (bubbles up to document), open the menu
>   $(document).on('focus', '.select2-selection.select2-selection--single', function (e) {
>     $('.select2-search__field').trigger('focus');
>   });
> 
>   // steal focus during close - only capture once and stop propogation
>   $('select.select2').on('select2:closing', function (e) {
>     $(e.target).data("select2").$selection.one('focus focusin', function (e) {
>       e.stopPropagation();
>     });
>   });
> ```

thank , its work for me on select ^4.1.0-rc.0 and jQuery v3.7.0

**Comment by RhyuM** [comment]
Thank you! This solution is working perfectly for me with jQuery v3.7.0.

**Comment by RhyuM** [comment]
> After wrestling with this for some hours I came up with this (which is a mix of different solutions I found on the web):
> 
> ```js
>   // on first focus (bubbles up to document), open the menu
>   $(document).on('focus', '.select2-selection.select2-selection--single', function (e) {
>     $('.select2-search__field').trigger('focus');
>   });
> 
>   // steal focus during close - only capture once and stop propogation
>   $('select.select2').on('select2:closing', function (e) {
>     $(e.target).data("select2").$selection.one('focus focusin', function (e) {
>       e.stopPropagation();
>     });
>   });
> ```

Thank you! This solution is working perfectly for me with jQuery v3.7.1
