### ISSUE TITLE
Get class from source <input> into select2-container

### ISSUE THREAD

**Issue by GeistZero** [select2/select2#3815]
Hello everybody.
I met following: any class of source input will be "copied" to select2-container. This is very usefull when I want to style different instances of inputs - if you want to style select2 alike bootstrap do (for example using classes *-xs, *-lg ).
But there is some exception/issue: classes names starting with "select2" are not copied.

Kind regards.

**Comment by alexweissman** [comment]
In 3.x you can use the `syncCssClasses` setting.  For 4.x, this issue is discussed in #3790.
