### ISSUE TITLE
Select2 4.4 data-allowClear not overriding options set when initializing Select2

### ISSUE THREAD

**Issue by ederbond** [select2/select2#3826]
In Select2 4.4 documentation, it says that dat-* attributes overrides initialization options.
However even if your html element have the data-allow-clear = 'false' 

<select id="xxx" name="xxx" data-allow-clear="False" >

if you set {allowClear=true} on the inicialization, ex:

$('select').select2({ allowClear: true });

it will ignore the data-* attribute set on the element (the x button will apear on the control);

**Comment by ederbond** [comment]
Just realize the problem was that on my HTML select element the False keyword was starting in uppercase. But select2 seems to understand only lowercase to the value attribute of data-allow-clear = 'false'. It would be nice if select2 could understand bolth values 'false' and 'False'

**Comment by kevin-brown** [comment]
> It would be nice if select2 could understand bolth values 'false' and 'False'

The `data-` attribute parsing is done by jQuery, which tries its best to determine the actual value of the attribute (which comes in as a string). We don't have control over what gets mapped to `false` and what doesn't.
