### ISSUE TITLE
predefined options for ajax select2

### ISSUE THREAD

**Issue by Fivell** [select2/select2#3828]
Hello, I have next html

``` html
<select class="change_item_dropdown_ajax form-control" id="item_id" name="item_id" onchange="updateData(this, this.value, 16)" >
<optgroup label="System Data">
  <option value="17">Test</option>
  <option selected="selected" value="18">System</option>
</optgroup>
</select>
```

``` js
    $(".change_item_dropdown_ajax").select2({
        ajax: {
            url: "get_user_items",
            dataType: 'json',
            delay: 250,
            theme: "classic",
            data: function (params) {
                return {
                    q: { name_contains: params.term } // search term
                };
            },
            processResults: function (data) {
                return {
                    results: data
                };
            },
            cache: true
        },
        allowClear: true,
        placeholder: '--- Please select item ---',
        minimumInputLength: 1
    });
```

I want to make possibility for customer to see some default system options with items `<optgroup label="System Data">`, but also add ability to make search ajax queries by his own items.

However after binding select2 it doesn't show `<optgroup label="System Data">...</optgroup>`,  
select2 options are empty and it only displays hint "Please enter 1 or more characters".

It's not even clear if it is possible to do, thanks

SO Question http://stackoverflow.com/questions/33080739/select2-default-options-with-ajax

**Comment by Fivell** [comment]
#684 , is quite similar but for older version

**Comment by powderflask** [comment]
+1
My use case:  the select initially lists "recently viewed" items - the user should be able to select from these items without searching (this will be about 50% of cases).  If the desired item is not in this "recently viewed" list of options, the user starts typing a search term to trigger the AJAX call and load the search results.

However, as soon as I add the ajax option to select2, the initial data options provided in the underlying select widget are no longer displayed.

**Comment by powderflask** [comment]
Just noticed:  the initial / default list of options are also not displayed when you explicitly specify minimumInputLength (even if the ajax option is not specified).

**Comment by govorov** [comment]
I created custom adapter extended from AjaxAdapter with defaultResults option, which will be used instead of ajax call results, if query length shorter than minimumInputLength. 
Here it is: https://gist.github.com/govorov/3ee75f54170735153349b0a430581195
Hope it will help you.
@kevin-brown What about to incude this feature into basic AjaxAdapter?

**Comment by jamescgibson** [comment]
@govorov Could you provide an example of how to use your adapter?

**Comment by govorov** [comment]
I have a custom widget based on Select2, that allows user to select city (Russian and Ukraine in my case, so I'm sorry for only russian screenshots in advance, but hope it's still clear what's going on on them). Here is the gist with comments (coffeescript): https://gist.github.com/govorov/274a8aac5fb910472ff1d0022f32f53e
And some screenshots:
Default top-population cities, when there is no input:
![screenshot_20160618_195033](https://cloud.githubusercontent.com/assets/6274882/16172295/c3cd317a-3596-11e6-9129-cca3d673df55.png)
Response result, when input is provided:
![screenshot_20160618_195051](https://cloud.githubusercontent.com/assets/6274882/16172296/c8352100-3596-11e6-8daf-a01cda939a05.png)

**Comment by exige81** [comment]
+1  Being able to display an initial default list rendered from unselected `<options>` would be very nice functionality to have.

**Comment by minlare** [comment]
+1

**Comment by andreyvolokitin** [comment]
It also strange as [documentation](https://select2.github.io/examples.html#data-ajax) states that you can provide default selections with ajax by putting actual options in the select: 

> If you need to provide default selections, you just need to include an option for each selection that contains the value and text that should be displayed.

**Comment by amnwebmaster** [comment]
+1

**Comment by abdallahmaali** [comment]
+1

**Comment by ryandavs** [comment]
May I know the status of this issue or if there's already a plan where in the roadmap this issue will be addressed?

**Comment by decodekult** [comment]
I would also be interested on a native solution for this. As pointed out above, the docs suggest that initial values can be set with native HTML options, and that results untrue in case you use an AJAX data provider.

**Comment by Demyan112rv** [comment]
+1

**Comment by fredericoregateiro** [comment]
👍

**Comment by s0By** [comment]
I'm interested in solution as well

**Comment by abecks** [comment]
+1

**Comment by govorov** [comment]
@kevin-brown what about the issue? It is open more than a year :)

**Comment by podorozhny** [comment]
+1

**Comment by vadlat** [comment]
+1

**Comment by baronvertigovongrahamthesecondofsealand** [comment]
So, this was closed... was it implemented? Any resolution at all? What?

**Comment by abecks** [comment]
I've heard [selectize](https://selectize.github.io/selectize.js/) can do this properly.

**Comment by Alagaesia93** [comment]
+1

**Comment by sarahkemp** [comment]
+1

**Comment by Spongman** [comment]
hello?

**Comment by fsteinbauer** [comment]
+1

**Comment by jfcsantos** [comment]
+1

**Comment by nuryagdym** [comment]
+1

**Comment by merik** [comment]
It works. Documentation:

> If you need to provide default selections, you just need to include an option for each selection that contains the value and text that should be displayed.

This is important: **selected="selected"** for each option you want to preload.

Here is my working code:

**HTML:**
```
<select class="form-control select2-multiple" style="width: 100%;" name="test[]" multiple="multiple">
    <option value="1" selected="selected">Option 1</option>
    <option value="2" selected="selected">Option 2</option>
</select>
```

**JS:**
```javascript
$input.select2({'theme':'bootstrap','ajax':{ .... });
```
**Result:**
![screen shot 2017-08-03 at 15 32 45](https://user-images.githubusercontent.com/352675/28924163-09e202ea-7861-11e7-8665-5f0a82c20053.png)

**Comment by fsteinbauer** [comment]
@merik Thank you for your effort, but in this issue, a method to prefill options before the first ajax call is searched.

**Comment by alexweissman** [comment]
@fsteinbauer this is now documented in https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2

**Comment by Rockstar04** [comment]
That does not address the intial issue, which is to allow a list of selected AND un-selected options the user can select from before using the AJAX search to find their selection.

**Comment by alexweissman** [comment]
Alright, well, the original issue did not make that very clear.  This issue comes across as a "fix mah codez" type of issue, rather than a formal feature request or bug fix with a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example.

So you're saying that this issue boils down to the ability to have preselected options?  I believe there are several issues/PRs specifically about this already.

**Comment by Rockstar04** [comment]
That's fine, and maybe I was just seeing that in the initial issue because that's what I was trying to accomplish. Could you reference them or point me to the other issues requesting this sort of thing?

**Comment by alexweissman** [comment]
>  allow a list of selected AND un-selected options the user can select from before using the AJAX search to find their selection.

I'm doing exactly this in my own application that uses Select2, without any problems and as described in the documentation.  I populate the selected options initially in my server-rendered DOM:

```
<select name="institutions[]" class="form-control select2" type="text" multiple="multiple" data-placeholder="Please select an institution">
{% for institution in student.institutions %}
    <option value="{{institution.id}}" selected>{{institution.slug}}</option>
{% endfor %}
</select>
```

and then initialize Select2 on this control, with an AJAX data source:

```
// Institution select
form.find("select[name='institutions[]']").select2({
    ajax: {
        url: site.uri.public + "/api/institutions",
        dataType: "json",
        delay: 250,
        data: function (params) {
            return {
                filters: {
                    name : params.term
                },
                page: params.page || 0,
                size: params.size || 10
            };
        },
        processResults: function (data, params) {
            var suggestions = [];
            // Process the data into dropdown options
            if (data && data.rows) {
                jQuery.each(data.rows, function(idx, row) {
                    row.text = row.slug;
                    suggestions.push(row);
                });
            }

            params.page = params.page || 0;
            params.size = params.size || 10;

            return {
                results: suggestions,
                pagination: {
                    more: (params.page * params.size) < data.count_filtered
                }
            };
        }
    },
    width: '100%',
    templateResult: function(item) {
        // Display institution name as tag option
        return $("<div>" + item.name + "</div>");
    },
    cache: true
});
```

Is this the same as your use case?  If so, could you please post your code to the forums, and we can discuss it there?

**Comment by Rockstar04** [comment]
Disclaimer: This is the functionality that I am asking for, I am unable to confirm if this is what the original issue is specifically asking for.

``` html
    <div class="form-group">
        <label for="book">Book *</label>
        <select id="book" class="select2-books form-control" name="book" required>
            <optionx></option>
            <option value="1">Recent Book #1</option>
            <option value="2">Recent Book #2</option>
            <option value="3">Recent Book #3</option>
            <option value="4">Recent Book #4</option>
        </select>
    </div>
```

``` javascript
$(".select2-books").select2({
    ajax: {
        url: public_url + "/api/book/search",
        dataType: 'json',
        delay: 250,
        data: function(params) {
            return {
                q: params.term,
                page: params.page
            };
        },
        processResults: function(data, params) {
            params.page = params.page || 1;
            return {
                results: data.items,
                pagination: {
                    more: (params.page * 30) < data.total_count
                }
            };
        },
        cache: true
    },
    escapeMarkup: function(markup) {
        return markup;
    },
    minimumInputLength: 3,
    placeholder: 'Select a Book...',
    instructions: 'To find a book, search the <strong>Book\'s Title</strong>, <strong>ISBN</strong>, or <strong>Authors</strong>',
});
```

## Result
`Recent Book #1` is preselected (even though there is a blank option first that should be selected by default)
![select2collapsed](https://user-images.githubusercontent.com/641721/33036428-f312c5c0-cdf3-11e7-8565-18d58e8300d5.png)

Preset options to not display when element is selected
![select2expanded](https://user-images.githubusercontent.com/641721/33036436-f712d066-cdf3-11e7-864f-81f57e4b108f.png)

## Desired

When selected the preset options are displayed first. These would be what we expect the user will select, followed by a search box in case we didnt provide the correct preset options. (I messed up the image below in Photoshop, options obviously should be 1, 2, 3, 4)

![select2desired](https://user-images.githubusercontent.com/641721/33036518-3a7bb44e-cdf4-11e7-9f16-2db7798cb0b0.png)

**Comment by geoff-maddock** [comment]
> Disclaimer: This is the functionality that I am asking for, I am unable to confirm if this is what the original issue is specifically asking for.
> 
> ```
>     <div class="form-group">
>         <label for="book">Book *</label>
>         <select id="book" class="select2-books form-control" name="book" required>
>             <optionx></option>
>             <option value="1">Recent Book #1</option>
>             <option value="2">Recent Book #2</option>
>             <option value="3">Recent Book #3</option>
>             <option value="4">Recent Book #4</option>
>         </select>
>     </div>
> ```
> 
> ```js
> $(".select2-books").select2({
>     ajax: {
>         url: public_url + "/api/book/search",
>         dataType: 'json',
>         delay: 250,
>         data: function(params) {
>             return {
>                 q: params.term,
>                 page: params.page
>             };
>         },
>         processResults: function(data, params) {
>             params.page = params.page || 1;
>             return {
>                 results: data.items,
>                 pagination: {
>                     more: (params.page * 30) < data.total_count
>                 }
>             };
>         },
>         cache: true
>     },
>     escapeMarkup: function(markup) {
>         return markup;
>     },
>     minimumInputLength: 3,
>     placeholder: 'Select a Book...',
>     instructions: 'To find a book, search the <strong>Book\'s Title</strong>, <strong>ISBN</strong>, or <strong>Authors</strong>',
> });
> ```
> 
> ## Result
> `Recent Book #1` is preselected (even though there is a blank option first that should be selected by default)
> ![select2collapsed](https://user-images.githubusercontent.com/641721/33036428-f312c5c0-cdf3-11e7-8565-18d58e8300d5.png)
> 
> Preset options to not display when element is selected
> ![select2expanded](https://user-images.githubusercontent.com/641721/33036436-f712d066-cdf3-11e7-864f-81f57e4b108f.png)
> 
> ## Desired
> When selected the preset options are displayed first. These would be what we expect the user will select, followed by a search box in case we didnt provide the correct preset options. (I messed up the image below in Photoshop, options obviously should be 1, 2, 3, 4)
> 
> ![select2desired](https://user-images.githubusercontent.com/641721/33036518-3a7bb44e-cdf4-11e7-9f16-2db7798cb0b0.png)

Did you ever come up with an adequate solution @Rockstar04 ?  I'm looking to do the same thing.

**Comment by Rockstar04** [comment]
@geoff-maddock I do not believe I did. We also had to stop using Select2 entirely because of accessibility issues.

**Comment by ajjn** [comment]
Hey, I was looking also looking for a solution and actually you can do it if you can access the backend. 
You need, however to remove the  minimumInputLength: 3 option so that the query is made to backend. Make the check at backend and send empty list back if query term's length is less than three. Then at processResults add after the first line:
```
if (page == 1) {
  $(".select2-books").find('option').each(function (i, e) {
     var object = {id: e.value, text: e.text};
     if ($.inArray(object, data.items) == -1)
       data.items.push(object);
     });
}
```
This will then add the initial options to the data list. At least worked for me and solved the problem. You have to think harder if you don't have the access to the backend and want to limit the first query to be sent only after typing three characters.

**Comment by mpryvkin** [comment]
Wrote a post titled [Predefined options for Select2 control using remote data source](https://www.gyrocode.com/articles/predefined-options-for-select2-control-using-remote-data-source/) that demonstrates [solution](https://github.com/select2/select2/issues/3828#issuecomment-226952766) suggested by @govorov above.

**Comment by Arjunmrt31** [comment]
I have updated extended adapter created by @govorov  As it will not displaying predefined options untill search is performed and also not working for pagination. 

`$.fn.select2.amd.define('select2/data/extended-ajax', ['./ajax', './tags', '../utils', 'module', 'jquery'], function (AjaxAdapter, Tags, Utils, module, $) {

    function ExtendedAjaxAdapter($element, options) {
        //we need explicitly process minimumInputLength value 
        //to decide should we use AjaxAdapter or return defaultResults,
        //so it is impossible to use MinimumLength decorator here
        this.minimumInputLength = options.get('minimumInputLength');
        this.defaultResults = options.get('defaultResults');

        ExtendedAjaxAdapter.__super__.constructor.call(this, $element, options);
    }

    Utils.Extend(ExtendedAjaxAdapter, AjaxAdapter);

    //override original query function to support default results
    var originQuery = AjaxAdapter.prototype.query;

    ExtendedAjaxAdapter.prototype.query = function (params, callback) {
        var defaultResults = (typeof this.defaultResults == 'function') ? this.defaultResults.call(this) : this.defaultResults;
        if ((defaultResults && defaultResults.length) && (!params.term || params.term.length < this.minimumInputLength) && (params._type && params._type == 'query')) {
            var data = { results: defaultResults };
            var processedResults = this.processResults(data, params);
            callback(processedResults);
        }
        else  {
            originQuery.call(this, params, callback);
        }
    };

    if (module.config().tags) {
        return Utils.Decorate(ExtendedAjaxAdapter, Tags);
    } else {
        return ExtendedAjaxAdapter;
    }
 });`
