### ISSUE TITLE
allowClear remove issue

### ISSUE THREAD

**Issue by zlaja1983** [select2/select2#3830]
Having an issue when select2 is passed allowClear and placeholder options and when the user removes an item. I'm seeing thick border after an item is removed and the control does not get focus.
![screen shot 2015-10-13 at 9 51 13 am](https://cloud.githubusercontent.com/assets/7635374/10458018/c9920c6c-7196-11e5-9e92-a66e728e4e49.png)

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
