### ISSUE TITLE
select2 breaks with django-pipeline

### ISSUE THREAD

**Issue by karolyi** [select2/select2#3839]
Hi.

you have the same error as awesome-bootstrap-checkbox has mentioned [here](https://github.com/flatlogic/awesome-bootstrap-checkbox/issues/48).

Please fix it, as it breaks https://github.com/cyberdelia/django-pipeline/issues/302, I have to manually exclude your `docs` folder in order to get it to compile my assets.

Cheers

**Comment by raghumadhavan** [comment]
@karolyi Issue seems to be open for a while, please validate if its still an issue.

**Comment by karolyi** [comment]
@raghumadhavan I solved the issue differently since I had no time to wait for an external solution, linking it here for others who bump into the same issue.

https://github.com/jazzband/django-pipeline/issues/484#issuecomment-170656271
