### ISSUE TITLE
Getting only last selected option at multi select using PHP

### ISSUE THREAD

**Issue by ahmadsayeed3** [select2/select2#3843]
i am trying to get selected values at multi select control but its only get last selected option.

<select type="select" multiple="multiple" class=" select2 form-control  "  name="cat">
	<option  value="Man">Man</option>
	<option value="Woman">Woman</option>
	<option value="Couple (Man &amp; Woman)">Couple (Man &amp; Woman)</option>
	<option value="Couple (Man &amp; Man)">Couple (Man &amp; Man)</option>
	<option value="Couple (Woman &amp; Woman)">Couple (Woman &amp; Woman)</option>
</select>

PHP
$this->input->post('cat');
i won't get other value but last one, anyone here who may guide me to solve this

**Comment by ahmadsayeed3** [comment]
Found a alternate solution

<select type="select" multiple="multiple" class=" select2 form-control  "  name="interestedOption">
	<option  value="Man">Man</option>
	<option value="Woman">Woman</option>
	<option value="Couple (Man &amp; Woman)">Couple (Man &amp; Woman)</option>
	<option value="Couple (Man &amp; Man)">Couple (Man &amp; Man)</option>
	<option value="Couple (Woman &amp; Woman)">Couple (Woman &amp; Woman)</option>
</select>

<input type="text" id="interested"  name="interested" />
<button id="reg" name="reg" class="btn btn-default  button">Create</button>
<script>
/*select2 not working properly when took input: alternate solution*/
		  $("#reg").click(function(){
				alert($('#interestedOption').val());
				$('#interested').val($('#interestedOption').val());
		   });
</script>

**Comment by ahmadsayeed3** [comment]
it won't create issue when use html multiselect but when i use select2 js liabrary it only select last selected option.
 it would be better, if only use php,

**Comment by tronhammer** [comment]
I just solved this problem. It was due to my select entity form name not having brackets, which flags it as an array to PHP. E.g.
<select name="items[]">

**Comment by kevin-brown** [comment]
Unfortunately this issue is pretty specific to PHP, but it's [also fairly well documented](http://stackoverflow.com/q/2407284/359284), so I don't think we're going to add a note about it in the Select2 documentation. If more bug reports roll in about it, we might reconsider that decision.
