### ISSUE TITLE
Look like bootstrap dropdown option for single selection select2

### ISSUE THREAD

**Issue by Hemanth089** [select2/select2#3844]
Hi,

Can you guys add support to look the select2 box similar to bootstrap dropdown for single selection select2 box?

I just removed the border for select2 and added border and border radius for dropdown box class in select2 css. Its nearly similar to bootstrap dropdown. But only issue is the down and up arrow next to the selected item moved to the right. Pl have a look at the attached image. 

![capture image](https://cloud.githubusercontent.com/assets/7092837/10557431/6cd2c1a6-74ca-11e5-91dc-8e84a5c29849.png)

Is there any changes that I can apply to move the arrow next to the selected Item?

**Comment by kevin-brown** [comment]
There is a Bootstrap theme available for Select2 that makes it look like a standard `<select>`: https://github.com/select2/select2-bootstrap-theme
