### ISSUE TITLE
select2 without jQuery

### ISSUE THREAD

**Issue by dnohr** [select2/select2#3846]
Hi,

I'm a big fan of select2, but is trying to avoid jQuery, since I don't needs it's massive amount of functionality. Is there any thoughts on making a plain JS version without jQuery as dependency?

Thanks.

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/select2/select2/issues/3652.

**Comment by alvarotrigo** [comment]
I had the same problem.
I really prefer not to load jQuery just for a single component. 

I found Choices, which seems to be quite a good replacement without jQuery! :) (At least for my use case with single select boxes) 
https://joshuajohnson.co.uk/Choices/

**Comment by ivkan** [comment]
I am trying to transfer Select2 to TypeScript without dependencies. The project is located [here](https://github.com/ivkan/ts-select2).

**Comment by acflint** [comment]
> I had the same problem. I really prefer not to load jQuery just for a single component.
> 
> I found Choices, which seems to be quite a good replacement without jQuery! :) (At least for my use case with single select boxes) https://joshuajohnson.co.uk/Choices/

That link is broken. You can find Choices at https://github.com/Choices-js/Choices now.

**Comment by ghost** [comment]
@acflint @alvarotrigo 

Thank you, since select2 still depends on jquery "even in 2022", the suggestion with choices was what I was looking for.

**Comment by crstauf** [comment]
Note that Choices does not appear to be maintained any longer. 😞

**Comment by rixx** [comment]
A new maintainer has been found and seems very active, so Choices is an okay choice :drum: again.
