### ISSUE TITLE
duplicate tags created between HTML <option>s  and "tags" array

### ISSUE THREAD

**Issue by alanngnet** [select2/select2#3847]
When the HTML specifies which tags have previously been selected (for example, in server-side database-driven HTML), Select2 (v. 4.0.0) fails to recognize that those tags match existing members of the "tags" array specified in the JQuery invocation of the Select2 instance. Therefore the dropdown shows duplicate entries. Instead the dropdown should only show the remaining members of the "tags" array that have not previously been selected.
   
Demonstration: http://jsfiddle.net/alanng/zg1paLsj/

**Comment by kevin-brown** [comment]
Passing an array into `tags` is no longer the recommended way to pre-initialize things. You should instead use a combination of `data` and `tags`.

https://jsfiddle.net/r7cop362/
