### ISSUE TITLE
Performance issue with big data comparing to 3.5.2

### ISSUE THREAD

**Issue by choxnox** [select2/select2#3854]
It appears there is a bug in v4.0.0 causing performance issue which doesn't exist in v3.5.2. Take a look at these two examples:

[Select v3.5.2](http://jsfiddle.net/choxnox/6kxLjrL7/) and [Select v4.0.0](http://jsfiddle.net/choxnox/v18tLc17/1/)

The first example (v3.5.2) prints the following in my browser's console:

```
Preparing data: 0.00ms
Preparing Select2: 16.00ms
```

The second example (v4.0.0.) prints the following in my browser's console:

```
Preparing data: 0.00ms
Preparing Select2: 1437.00ms
```

**Comment by kevin-brown** [comment]
In Select2 3.5.x and below, Select2 stored the array data from `data` in memory and then processed the nodes on the fly in order to determine matches.

In Select2 4.0.0 and above, Select2 will convert the incoming data in `data` to the `<option>` and `<optgroup>` elements that it would normally represent, and then it will insert them into the DOM. This allows Select2 to handle searching and matching efficiently, but it comes at the cost of speed when initializing Select2.

All of this happens in [`ArrayAdapter.prototype.convertToOptions`](https://github.com/select2/select2/blob/6be96cfaa175448ef70b978648de7d6cb5822e89/src/js/select2/data/array.js#L30-L76), which isn't the most efficient method out there. Pull requests that improve the performance of this method are encouraged.

**Comment by Decagon** [comment]
This data was collected using Google Chrome 42 on Linux using Select2 4.0.0, 4.0.1-rc.1 and jQuery 3.0.0-alpha1 and 2.3.1. Data from Select2 3.5.x will be added soon.

| jQuery version | Select2 version | "Preparing Data" (avg ms) | "Preparing Select2" (avg ms) | JSFiddle Link |
|----------------|-----------------|---------------------------|------------------------------|---------------------------------|
| 3.0.0-alpha1 | 4.0.1-rc.1 | 5.521 += 1.136 | 802.5 += 51.78 | http://jsfiddle.net/v18tLc17/2/ |
| 3.0.0-alpha1 | 4.0.0 | 5.653 += 1.159 | 818.4 += 37.68 | http://jsfiddle.net/v18tLc17/4/ |
| 2.1.3 | 4.0.1-rc.1 | 8.725 += 7.238 | 1006 + 28.2 | http://jsfiddle.net/v18tLc17/5/ |
| 2.1.3 | 4.0.0 | 11.51 += 11.07 | 1021 += 68.32 | http://jsfiddle.net/v18tLc17/3/ |

It appeared that jQuery 3.0.0-alpha1 was able to offer a x1.25 speedup during the "Preparing Select2" phase. jQuery Edge was able to offer a very small improvement over the 3.0.0-alpha1 speedup but wasn't included. It seems like jQuery methods might be a cause of the problem.

**Comment by yehudahkay** [comment]
I just dropped select2 into a project. The dropdown has 15,000 options. I try:

```
this.$('.select2').select2({
                            minimumInputLength: 3,
                            data: this.model.get('answers').toJSON(),
                            width: '100%',
                            multiple: true
                        })
```
With 3.5.4 this works. With 4.0.3 it doesn't.

**Comment by jakeNiemiec** [comment]
This is still an issue.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:

**Comment by pedrofurtado** [comment]
We are planning versions to fix this bugs. But there a lot of issues without details, demos and every kind of information that let us able to help. There are many issues, but few pull requests. And a little number of people working actively on this project. So, we have to make priorities. I invite you to create a PR @jakeNiemiec , it will help us a lot. I will glad to review and approve if it is ok.

**Comment by jakeNiemiec** [comment]
> But there a lot of issues without details, demos and every kind of information that let us able to help.

Which one of those is missing here? You closed a bunch of issues with demos, issues that were confirmed bugs, and issues that were referenced by open PRs.

You are doing more damage than good. 

`less issues != better tool`
