### ISSUE TITLE
Placeholders removed when going back on Safari for iPhone

### ISSUE THREAD

**Issue by juankiz** [select2/select2#3855]
When you press the back button or make a back gesture on Safari on iPhone and that page has a select2 object the placeholders disappear. I'm using the placeholder attribute to set the content.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by Decagon** [comment]
I was unable to reproduce this bug in 4.0.1-rc.1 on Safari on iOS 9.1.

The steps that I tried to reproduce the issue by going to https://select2.github.io/examples.html and scrolling down to the placeholder example:
- swiping from left to right, but keep half of the page on screen (not selecting anything)
- select the placeholder text, and then swipe from left to right
- select the placeholder text, deselect it, choose a value, remove the value, swipe left to right
- select an option from the dropdown, delete it then swipe
- swiping multiple times for each instance.
