### ISSUE TITLE
Implementing scroll scope

### ISSUE THREAD

**Issue by chrisalcantara** [select2/select2#3856]
I think it would be cool to include [scroll scope](http://eiskis.net/scroll-scope/) to this. Might have to use the CDN, but it would nice to keep the dropdown list from moving the entire window page.

**Comment by kevin-brown** [comment]
Select2 supports [jQuery Mouse Wheel](https://github.com/jquery/jquery-mousewheel) for this within the core. As long as it's included within the page when Select2 is initialized, Select2 will prevent the page from scrolling when Select2 is scrolled.
