### ISSUE TITLE
token multiple append existing tags

### ISSUE THREAD

**Issue by mmplisskin** [select2/select2#3857]
Trying to render existing tags into the tag field for a rails edit action from a hidden field. The tag field populates but if a new tag is added all others are deleted.

```
$( "#event_tag_list" ).select2({
  createSearchChoice: function() { return null; },
  tokenSeparators: [',', ' '],
})

var hidden_tags = $('#hidden-tags').html()
var A = hidden_tags.split(",")

for (var i = 0; i < A.length; i++){
  string = A[i]
  var str = string.replace(/[\W_]+/g," ")
  var resultString = "<li class='select2-selection__choice' title=" + str +
  "><span class='select2-selection__choice__remove' role='presentation'>x</span>" + str + " </li>"
  $('.select2-selection__rendered').append(resultString)
}
```

input field
```
<%= f.select :tag_list, options_for_select(options_for_tags), {}, { multiple: true, :style => "width:450px;"}%>
```

It could be possible that this is the wrong approach but we want to limit user input to available tags

**Comment by mmplisskin** [comment]
Swapped it out for chosen and it worked instantly... 

```
$( "#event_tag_list" ).chosen()
```

```
<%= f.collection_select :tag_list, options_for_tags, :name, :name,{},{multiple: true, :style => "width:450px;"} %>
```

**Comment by kevin-brown** [comment]
If you can reproduce this within a jsfiddle (so removing Rails from the equation), that would be useful and could allow us to track down the specific issue.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/
