### ISSUE TITLE
Select2 allowClear not working with dynamic dropdown list

### ISSUE THREAD

**Issue by awaisdar001** [select2/select2#3858]
HTML
-
```
<select id="id_city">
    <option></option>
    <option>First option</option>
    <option>Second option</option>
</select>
<select id="id_city2">
    <option></option>
</select>
```

JS
-
```
var city_node = $("#id_city");
function safeAjaxFindCities(data, city_node) {
    $.ajax({
        url: window.app.find_cities,
        type: "POST",
        data: data,
        success: function (response, textStatus, jqXHR) {
            city_node.find('option').remove();
            city_node.select2({
                data: response.items,
                allowClear: true,
                placeholder: "Select any value",
                width: '100%'
            }).trigger('change');

        }
    });
}
```

When the new results are fetched, and appended to the element and select2 is called. I click cross to clear the value of city,  i get the following error.

```
Uncaught TypeError: Cannot read property 'toString' of null
```

Location of error
```
c.prototype.setClasses = function() {
            var b = this;
            this.data.current(function(c) {
                var d = a.map(c, function(a) {
                    return a.id.toString() <======================== HERE IT IS
                }
                )
                  , e = b.$results.find(".select2-results__option[aria-selected]");
                e.each(function() {
                    var b = a(this)
                      , c = a.data(this, "data");
                    null  != c.id && d.indexOf(c.id.toString()) > -1 ? b.attr("aria-selected", "true") : b.attr("aria-selected", "false")
                }
                );
```

VERSION
-
``` @license almond 0.2.9 Copyright (c) 2011-2014, The Dojo Foundation All Rights Reserved.```

**Comment by kevin-brown** [comment]
In `city_node.find('option').remove();` you are removing the placeholder option. I suspect the error message is actually completely unrelated, but it may not be. Next time I'd recommend pulling the error from the non-minified version of Select2.

**Comment by sukhwinderkaur1389** [comment]
**I am getting the same error :

JS**

jQuery(".ajax_select").each(function() {

        var option_id = $(this).attr('option_id');
        var id = $(this).attr('id');

        jQuery("#"+id).select2({
            allowClear: true,
            ajax: {
                url : "/form-builder/get-options?option_id="+option_id,
                dataType: 'json'
            },
            delay: 250 ,
            data: function (params) {
                console.log(params);
              var query = {
                search: params.term,
                page: params.page || 1,
                option_id: option_id
              }
              return query;
            },
            placeholder: 'Type to search',
            minimumInputLength: 1,
            cache: true
        });
    });


-----------------------------------------------------------------------------------------------------------------------------
select2.min.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'toString')
    at select2.min.js:2:7364
    at Array.map (<anonymous>)
    at select2.min.js:2:7336
    at n.current (select2.min.js:2:34511)
    at s.setClasses (select2.min.js:2:7308)
    at o.<anonymous> (select2.min.js:2:9997)
    at e.invoke (select2.min.js:2:3881)
    at e.trigger (select2.min.js:2:3700)
    at o.trigger (select2.min.js:2:66940)
    at o.<anonymous> (select2.min.js:2:65281)
