### ISSUE TITLE
Limiting the number of selections does not work using CTRL

### ISSUE THREAD

**Issue by FredericoSFerreira** [select2/select2#3860]
The maximum number of selection does not work when you use the CTRL key to perform the multiple selection

**Comment by Decagon** [comment]
:+1:

What browser/OS have you tested this bug with? Since this is an older bug, does the newest version of select (4.0.1-rc.1 at the time of this writing) work?

**Comment by kevin-brown** [comment]
You can reproduce this in 4.0.1-rc.1 by looking at the examples page.

https://select2.github.io/examples.html#multiple-max

This is because the maximum selection limit is enforced whenever the dropdown is opened, instead of when the selection is made.

**Comment by urkle** [comment]
This issue still happens in the latest 4.x release (new URL to page showing the issue https://select2.org/selections#limiting-the-number-of-selections )

**Comment by urkle** [comment]
This is still occurring in the latest code.

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/select2/select2/issues/3514.
