### ISSUE TITLE
Ajax request is not caching

### ISSUE THREAD

**Issue by stephenbe** [select2/select2#3862]
![ajax-cache](https://cloud.githubusercontent.com/assets/3018441/10668586/ff69cbb6-78aa-11e5-8cb3-c59a64f7d133.png)

select 4.0.0

This test comes from the demo. I highlighted both request that are identical. As you can see here both are loading 15.1kb in the size column. The second request for "angular" should be cached because I already searched for it.

Chrome 43.0.2357.65, Windows 7

Thanks!

**Comment by kevin-brown** [comment]
We can't guarantee that the response from a server will be the same if duplicate requests are made, and as a result we can't cache this within the core.

We can (and do) tell jQuery to not cache-bust, and hope that the server/browser will send cache-related headers to reduce the amount of work that is done within these duplicate requests.

You can extend the `AjaxAdapter` data adapter to cache on your own though.

**Comment by igorsantos07** [comment]
That seems like a decent explanation - cache is requested to jQuery and the server should provide the correct headers. 
However @kevin-brown, as pointed on the dup, there is a `cache` option in the docs; this behaviour should be explained there and it should be set as deprecated as well, so others like us won't fall in the same misunderstanding :)

**Comment by mkoch42** [comment]
@kevn-brown Is there an example of extending the AjaxAdapter to cache the results of ajax?

Thanks for the great plugin.
