### ISSUE TITLE
Default value with no results message

### ISSUE THREAD

**Issue by morrow95** [select2/select2#3863]
Using remote data... when there are no results returned I am showing a message saying so using an id=0.  In the actual select I am listing my default value and in the js I specify that default value as the placeholder.

The issue.  When searching and no results are found the 'no result' message is shown from my remote data as it should, BUT, if the user clicks this result it removes the value for the select.

html with value/name of stephen.exe : 
```
<select id="vedit-filter" name="settings[filter]" class="form-control">
	<option value="stephen.exe" selected="">stephen.exe</option>
</select>
<input id="filter_default" type="hidden" name="settings[original]" value="stephen.exe"/>
```

js : 
```
var default_filter = $("#filter_default").val();
		
$("#vedit-filter").select2({
	placeholder: {
		id: default_filter, // or whatever the placeholder value is
		text: default_filter // the text to display as the placeholder
	},
...
```

remote data when no results are found.  You must return an array or else it errors : 
```
// 0 results send a message back to say so.
$ajax_result['results'][] = array(
	'id' => 0,
	'text' => 'No results found...'
);
```

Now checking the form values you can see what happens.

Upon load of the page it is correct : CORRECT
settings%5Bfilter%5D=stephen.exe&settings%5Boriginal%5D=stephen.exe

Searching and setting to another value : CORRECT
settings%5Bfilter%5D=richard.exe&settings%5Boriginal%5D=stephen.exe

Clearing the current value (shows stephen.exe default in the box) : CORRECT
settings%5Bfilter%5D=stephen.exe&settings%5Boriginal%5D=stephen.exe

Searching and clicking on the 'No results found...' (shows stephen.exe default in the box) : WRONG
settings%5Boriginal%5D=stephen.exe

So, how can I still 'return' a no results message when there are no remote data results, YET still keep the placeholder acting correctly?  When they click on the 'no results' the input box reverts back to the default of stephen.exe, but the form value is lost.

**Comment by morrow95** [comment]
Been playing around this more... I found that if I do : 
```
    placeholder: {
        id: 0, // or whatever the placeholder value is
        text: default_filter // the text to display as the placeholder
    },
```
then everything works as it should, but I also noticed when there are no search results it returns 'No results found' which means it is not using the data I return.  I guess my question now is... what is the correct way to return a dataset without any results because apparently this isn't the way to do it as it shows this as a selectable option rather than the system 'No results found' message which cannot be clicked : 
```
    $ajax_result['results'][] = array(
    	'id' => 0,
    	'text' => 'No results found...',
    );
```

**Comment by morrow95** [comment]
and further info... while my previous post 'works'... the exact same code does not work inside a BS3 modal.  When I use the X to clear it should default to my placeholder and while the text shows correctly the form value is gone just as my original problem.  Any ideas here?  It makes no sense to me this would work within a page, but not in a modal.

Note that I had to use `$.fn.modal.Constructor.prototype.enforceFocus = $.noop;` for using this in the modal or else it wouldn't even function properly in the first place.

**Comment by morrow95** [comment]
Figured this out.  Everything I've always seen about the remote data says to always return an id/text pair, but when there are no results if you only send a text message back it prevents the option from being selected and also displays that message instead of the default.  With that change I can properly set both the id/text for the placeholder in my js to my default selection and there are no issues.

I would still like to know if this is the correct way to return results for remote data though when there are none... if you send back an empty array select2 will error out... the work around is only send the text back without the id, but this overwrites the default 'no result' message.

html
```
<select id="vedit-filter" name="settings[filter]" class="form-control select2" style="width: 100%">
	<option value="<?php echo htmlspecialchars($result['filter'], ENT_QUOTES, 'UTF-8'); ?>" selected="selected"><?php echo htmlspecialchars($result['filter'], ENT_QUOTES, 'UTF-8'); ?></option>
</select>
<input id="filter_default" type="hidden" name="settings[original]" value="<?php echo htmlspecialchars($result['filter'], ENT_QUOTES, 'UTF-8'); ?>"/>
```

js
```
var default_filter = $("#filter_default").val();
placeholder: {
	id: default_filter, // or whatever the placeholder value is
	text: default_filter // the text to display as the placeholder
},
allowClear: true,
...
```

remote data return when empty
```
// 0 results send a message back to say so.
$ajax_result['results'][] = array(
	//'id' => 0, //do not send the id
	'text' => 'No results found...',
);

$ajax_result['total'] = 0;
```

**Comment by MrVibe** [comment]
Facing the same issue, any ideas on how to achieve this in Select2  4.x version ?
