### ISSUE TITLE
Error:Option 'data' is not allowed for Select2 when attached to a <select> element

### ISSUE THREAD

**Issue by zhangwei900808** [select2/select2#3867]
I add select2.js in my page,but it error when I run it 
eg:
 var data2= [{ id: 0, text: 'enhancement' },
            { id: 1, text: 'bug' },
            { id: 2, text: 'duplicate' },
            { id: 3, text: 'invalid' },
            { id: 4, text: 'wontfix' }];
        $('.js-example-data-array').select2({
            theme: "classic",
            data:data2
        });

**Comment by kevin-brown** [comment]
You are using an older version of Select2 (3.5.x or lower). Only Select2 4.0.0 allows using a `<select>` with all options, before that you need to use an `<input type="text" />`.

**Comment by zhangwei900808** [comment]
Thank you

**Comment by ejlocop** [comment]
Hi @kevin-brown, im using minified version 4.0.1 but still gives me the error above.

![image](https://cloud.githubusercontent.com/assets/12082880/12603127/cc66db32-c4ea-11e5-8add-48cb0c123d4f.png)

btw. i used select2 on my other select with static options. it works fine. 
but when i try to use it for the other Select, and the contents are dynamic.
it now gives me this error. 

![image](https://cloud.githubusercontent.com/assets/12082880/12603174/30b6360a-c4eb-11e5-95da-614dd952e6f1.png)

here's my codes.
```html
<select name="property_type[]" multiple='multiple' autocomplete="off" id="property_type" class="form-control">
<option></option>
</select>
```
```javascript
        $('#property_type').select2({
          placeholder: 'wtf',
          data : [{id:1,text:'1'},{id:2,text:'2'},{id:3,text:'3'}]
        });
```
i'm using select2 along with bootstrap flat-ui

**Comment by suraj04081993** [comment]
Refer this link for more information - http://itfrustration.in/jquery-select2-ajax/

**Comment by shawe** [comment]
> Refer this link for more information - http://itfrustration.in/jquery-select2-ajax/

External link is died.

**Comment by dangkhoagms** [comment]
> You are using an older version of Select2 (3.5.x or lower). Only Select2 4.0.0 allows using a `<select>` with all options, before that you need to use an `<input type="text" />`.

Thank you
