### ISSUE TITLE
Pressing enter to select while loading data over AJAX selects from last result set

### ISSUE THREAD

**Issue by Eckankar** [select2/select2#3871]
Imagine the following scenario:

You have a name field, which is a select2 backed by AJAX. The user types `Richard`, and 3 results are displayed to him:
- Richard Branson
- Richard Gere
- Richard Stallman

The user wants "Richard Stallman", so he types ` S` (making the typed text `Richard S`), and presses <kbd>Enter</kbd> while the results are loading.

Since the user typed something that would make the search term unique, he would expect "Richard Stallman" to be selected. Instead he gets "Richard Branson", as he was the top result in the previous search.

---

Without having looked too hard into whether this has any adverse effects (hence why I don't send a pull request), I believe this behavior could be accomplished with the following changes:
### In [core.js](https://github.com/select2/select2/blob/master/src/js/select2/core.js):
- Add extra data to [enter key handler](https://github.com/select2/select2/blob/master/src/js/select2/core.js#L306), to mark that the selection is done using keyboard:

``` diff
         } else if (key === KEYS.ENTER) {
-           self.trigger('results:select', {});
+           self.trigger('results:select', { fromKeypress: true });

           evt.preventDefault();
         } else if ((key === KEYS.SPACE && evt.ctrlKey)) {
```
### In [results.js](https://github.com/select2/select2/blob/8ad8f200ba8c9429d636453b8ee3bcf593e8c87a/src/js/select2/results.js):
- [The handler for the query event](https://github.com/select2/select2/blob/8ad8f200ba8c9429d636453b8ee3bcf593e8c87a/src/js/select2/results.js#L258) stores that the results are currently loading:

``` diff
     container.on('query', function (params) {
       self.hideMessages();
       self.showLoading(params);
+      self.isLoading = true;
     });

  });
```
- Have [the handler for the selection event](https://github.com/select2/select2/blob/8ad8f200ba8c9429d636453b8ee3bcf593e8c87a/src/js/select2/results.js#L305) defer selecting while a query is loading:

``` diff
-    container.on('results:select', function () {
+    container.on('results:select', function (params) {
       var $highlighted = self.getHighlightedResults();

       if ($highlighted.length === 0) {
         return;
       }
+
+      if (self.isLoading && params && params.fromKeypress) {
+        self.selectOnLoad = true;
+        return;
+      }

       var data = $highlighted.data('data');
```
- [When the results are set](https://github.com/select2/select2/blob/8ad8f200ba8c9429d636453b8ee3bcf593e8c87a/src/js/select2/results.js#L241), trigger selection if it has been deferred:

``` diff
     container.on('results:all', function (params) {
       self.clear();
       self.append(params.data);
+      self.isLoading = false;

       if (container.isOpen()) {
         self.setClasses();
       }
+
+      if (self.selectOnLoad) {
+        self.selectOnLoad = false;
+        self.trigger('results:select', {});
+      }
     });
```

**Comment by alexweissman** [comment]
This appears to be one of a number of issues about the behavior of search while waiting for an AJAX request to complete.

**Comment by alexweissman** [comment]
Discussed more thoroughly in #4854.
