### ISSUE TITLE
Original <select> element does not hide after .select2() if it has appearance: none;

### ISSUE THREAD

**Issue by sintro** [select2/select2#3873]
I have <select> tags with CSS rules:

```
-webkit-appearance: none;
-moz-appearance: none;
appearance: none;
```

After applying select2() to it, the original <select> stays unhidden on top of created combobox. If I delete this rules, everything is OK. Does anybody have same issue?

**Comment by Decagon** [comment]
If you're trying to hide the element, `display: none` might be what you're looking for, since *-appearance: none just removes the changes that the element receives from how the browser decides to style it using internal styles, nothing to do with select2.
