### ISSUE TITLE
How to create a new list of options (data)?

### ISSUE THREAD

**Issue by gaurav21r** [select2/select2#3877]
I'm initializing Select2 like this 
```js
var data = 
      [
        { id: 0, text: 'enhancement' }, 
        { id: 1, text: 'bug' }, 
      ];
 
  $(".js-example-data-array").select2({
    data: data
  })
```

Then When I do this
```js
$(".js-example-data-array").select2({
      data: [
        { id: 5, text: 'New Delhi' }, 
        { id: 6, text: 'New York' }
      ]
    })
```
I expect Select2 to be populated with just **New Delhi** and **New York**. Instead it now ***shows 4 options!!!*** The earlier ones are not **cleared**.

Here's the fiddle:
http://jsbin.com/muhevuqahi/edit?html,js,output

Is this a bug? If not, how do I re-populate the list of `options / data` for Select2?

I tried searching the issues in the repo but couldn't find the same issue. Some people have asked for something close but I couldn't find any exact reproduction of this raw requirement. Other issues seem to have some other requirements mixed in!

**Comment by kevin-brown** [comment]
This is definitely a duplicate, but in my quick search I wasn't able to find the right keywords.

> Is this a bug?

Nope, this is the intended behaviour of the `data` option. When Select2 is initialized with `data`, it converts the array of data objects into `<option>` elements that it can use.

So when you reinitialize it, it creates a second set of `<option>` elements.

> If not, how do I re-populate the list of options / data for Select2?

You can clear out the existing options by calling `.empty()` on your original select.

```js
$("select").empty();
```

Note that this will reset any existing selections, which may not be what you were looking for.
