### ISSUE TITLE
How do I stop select2 from auto-selecting the first option in a multiselect?

### ISSUE THREAD

**Issue by lindasoakes0** [select2/select2#3878]
I am using a multiselect with a predefined set of options. For some reason, the first one always gets selected by default.

Here's a fiddle: http://jsfiddle.net/o020bybb/1/

Any thoughts?

**Comment by Eckankar** [comment]
The select itself also needd to be a multi-select:

```html
<select class="js-data-example-ajax" multiple="multiple">
...
</select>
```

**Comment by lindasoakes0** [comment]
@Eckankar that does the trick! Thanks!
