### ISSUE TITLE
Cannot deselect items in grouped multiple select when data ids are not strings

### ISSUE THREAD

**Issue by Jivings** [select2/select2#3882]
On a multi-select, if the ID's of data items are a number, then it is impossible to deselect. I believe [this is the offending code](https://github.com/select2/select2/blob/8ad8f200ba8c9429d636453b8ee3bcf593e8c87a/src/js/select2/data/select.js#L93) in which the `id` is represented internally as a string, but a number in `data.id`.

**Comment by Jivings** [comment]
[Demo here][1]. Narrowed the issue down to only multiple selects which are grouped.

[1]: http://codepen.io/Jivings/pen/RWJPVE

**Comment by Jivings** [comment]
Fixed by making sure the comparison is always done on strings.

**Comment by Jivings** [comment]
Still an issue.

**Comment by song712** [comment]
can confirm still an issue.
