### ISSUE TITLE
css / js correction for 'loading more results...'

### ISSUE THREAD

**Issue by morrow95** [select2/select2#3889]
When using ajax to load remote results with paging the "Loading more results..." message is shown when going to the next page of results.

At the moment the results are as : 
```
...
<li class="select2-results__option" role="treeitem" aria-selected="false">some result</li>
<li class="option load-more" role="treeitem">Loading more results…</li>
```

Either the js needs edited so the class is changed to 'select2-results__option' or there needs to be additional css in the stylesheet so this li is formatted properly.  Using the BS theme I added the following so it displays properly with the rest of the results, but you can make this whatever you want : 

```
.select2-container--bootstrap .option.load-more{padding:6px;}
```

**Comment by kevin-brown** [comment]
This is actually a bug, as `option` should have been switched to `select2--results__option` a while back.

**Comment by ekstro** [comment]
Maybe you can also add aria-disabled="true" ?

```
<li class="select2-results__option load-more" role="treeitem" aria-disabled="true"></li>
```

**Comment by kevin-brown** [comment]
This was fixed in https://github.com/select2/select2/commit/c53b2dcf11f28d8106a7b7684f503be7cda0b6a1.

**Comment by morrow95** [comment]
:+1:  nice!
