### ISSUE TITLE
params.page undefined when = 1

### ISSUE THREAD

**Issue by morrow95** [select2/select2#3890]
When using ajax to return remote results params.page is undefined for page = 1.  Only when page = 2 or greater is the value set.  I don't know if there is a specific reason for this or not, but it had me stuck for a little bit trying to figure out why `page` wasn't being posted for use in my script for results.  In the meantime I fixed this with the following, but I think it would make sense to  always send this value rather than leave it undefined when < 2.

```
ajax: {
    dataType: 'json',
    delay: 500,
    type: 'post',
    url: '/get_results.php',
    data: function (params) {
        return {
            term: params.term, // search term
            page: params.page || 1, //page number
            page_limit: 25, // page size
        };
    },
    processResults: function (data, page) {
        return {
            results: data.results,
            pagination: {
                more: data.more
            }
        };
    }
}
```

**Comment by Decagon** [comment]
Try https://github.com/Decagon/select2/pull/1 and let us know if that works.

**Comment by alexweissman** [comment]
I agree, this seems like a sensible improvement to the pagination system.
