### ISSUE TITLE
The ajax:cache=true option does nothing. 

### ISSUE THREAD

**Issue by chumakoff** [select2/select2#3893]
What does the ajax:cache option for ? Requests with the same parameters are sent every time again.

```javascript
  $(#my_select).select2({
    ajax: {
      cache: true,
      url: '/my_url.json',
      processResults: function(data) {
        return {
          results: data
        };
      }
    }
```

**Comment by kevin-brown** [comment]
The `ajax.cache` option is handled through jQuery. It controls whether or not a cache-busting token is appended to the url.

You can find more information in [the documentation for `jQuery.ajax`](https://api.jquery.com/jquery.ajax/).
