### ISSUE TITLE
Can't select any item from autocomplete list (select 2 v.4.0.0)

### ISSUE THREAD

**Issue by adrian7** [select2/select2#3896]
I'm using select2 to fill a list of options via ajax inside a bootstrap modal (bootstrap v3.3.5 ).  

The input works and the list fills with the expected results, and I am even able to hover over individual ones, however I am not able to select - clicking on them does not trigger any event: 

![untitled](https://cloud.githubusercontent.com/assets/225180/10889261/dec830aa-8188-11e5-9e96-3ed0d0ad3b69.png)

**Comment by adrian7** [comment]
The issue was the id function inside `ajax: { ... }` was returning null, and the fallback `item.id` was undefined also.

**Comment by jicihome** [comment]
Hi! How did you solve this?
