### ISSUE TITLE
4.0 - does not work in vertically scrolling BS modals (.modal-open .modal{overflow-y: auto;})

### ISSUE THREAD

**Issue by morrow95** [select2/select2#3897]
Been going nuts for a few days trying to figure this one out.  I have 4.0 working fine in BS 3.3.5 modals, BUT ONLY when they do not vertically scroll.  In other words if the modal's height is larger than the viewing area and needs to scroll then select2 no longer works (there is no cursor for the search).

BS applies the following css by default to an opened modal to allow for modals which need to scroll : 

```
.modal-open .modal {
    overflow-x: hidden;
    overflow-y: auto;
}
```

The `overflow-y: auto;` is what allows the vertical scrolling, however, this also prevents select2 from working when the modal indeed needs to scroll.  Changing this to `overflow-y: hidden;` and select2 works perfectly fine again yet this prevents scrolling of the entire modal.

I have created a jsfiddle to demonstrate this at http://jsfiddle.net/r18vtjs4/1/ with a ton of lines after the select in the modal to ensure you need to scroll the modal vertically in your window.

What can be done to rectify this?

EDIT : I just tested in different browsers... works in Edge, IE 11, latest Chrome, latest Opera.  DOES NOT work in latest Firefox.

**Comment by morrow95** [comment]
Nobody else experiencing this?  I'm not saying this is a bug with s2 necessarily, but would like to figure out a workaround in the meantime that doesn't involve `$.fn.modal.Constructor.prototype.enforceFocus = $.noop;` if possible.

**Comment by prasathmani** [comment]
Same here. I have multi select2 inside BS modal.
not able to vertically scroll the modal popup. for me it is not working in latest major browsers.

**Comment by Gauthamchander** [comment]
Im Facing the same issue. Unable to scroll inside .modal-open when we select the dropdown

**Comment by ioxFR** [comment]
Hi everybody,

i got an issue in modal in microsoft sharepoint app cross all browser.
After openning select2 field, the scrollbar of my modal not work anymore.
I don't know if it's exactly the same issue but here is the solution.
After some investigation i found part of select2 code who causing problem:
select2.full.js line 4212
$watchers.on(scrollEvent, function(ev){
var position = $(this).data('select2-scroll-position');
$(this).scrollTop(position.y);
});

I commented these lines and working fine for me. Please try and let us know!
