### ISSUE TITLE
Search loses focus with jQuery 1.7.2 on IE10+

### ISSUE THREAD

**Issue by charettes** [select2/select2#3898]
https://jsfiddle.net/njLko7mw/

The issue is fixed with jQuery 1.8.3. Maybe this version should simply be documented as the minimum required?

**Comment by Decagon** [comment]
I am able to reproduce this error in Edge 20.10240.16384.0 using jQuery 1.7.2, but it appears to work correctly using jQuery 1.8.3.

To reproduce this error you have to enter in a letter in the search box. The search box will loose focus, and you have to refocus it in order to type another letter.

**Comment by charettes** [comment]
Thanks for completing my report @Decagon!

**Comment by Decagon** [comment]
In 4.0.1-rc.1, this bug has been fixed, even with jQuery 1.7.2.

Example: https://jsfiddle.net/njLko7mw/1/

**Comment by charettes** [comment]
Awesome, I guess this should be marked as fixed then.

**Comment by Decagon** [comment]
I didn't test it on IE 10 yet, so it technically might not work. Testing now.

**Comment by Decagon** [comment]
After testing, Select2 4.0.1-rc.1 on IE 10 does not exhibit this bug.

**Comment by kevin-brown** [comment]
Closing this as the issue was fixed at some point.
