### ISSUE TITLE
Material Theme

### ISSUE THREAD

**Issue by jamesdixon** [select2/select2#3899]
@kevin-brown I saw you mention in another thread something about a Material theme. Any update on this? Is there a branch I could contribute to?

Thanks!

**Comment by kevin-brown** [comment]
The project is still not yet released _(grumbles)_, so the theme has not yet been open sourced. If someone else creates a theme before then, I'll probably just roll our changes into that one.

I'm going to roll this ticket into https://github.com/select2/select2/issues/3957 until then.

**Comment by flip111** [comment]
The material design theme is pretty specific. Unlikely that it can just be merged into some other css theme.

I spend a couple of hours trying to make a material design theme, the experience was really painful. For the moment i rolled it back to the default theme so now i have a control that doesn't fit with the rest.

For material design i use the [bootstrap-material-design](https://github.com/FezVrasta/bootstrap-material-design) css.

The particular pain points were:
1. Unclear what is the purpose of structure of html are. For example if i wanted to change a background i had to try 3 elements in the tree until i found the one where a background property responds to (= visible change on the screen).
2. The material design css is very complex so i like to re-use the same classes, for that i would have to overwrite internals of select2 in javascript and i didn't know how to do that.
3. There was still active CSS from select2 which the theme has to proactively disable. IMO it would be better if a theme was 100% of the CSS and then use scss files import to a common part.
4. The options that can be passed related to css are not explained.

This is so painful that i'm considering to write a select2 replacement myself. While this might be more hours of work it would be more enjoyable. Right now i'm pulling in 70kb of select2 + jQuery compat. Get some great features but also some things that are just very hard.
