### ISSUE TITLE
select2_locale_de.js:7 Uncaught TypeError: Cannot read property  'locales' of undefined

### ISSUE THREAD

**Issue by meivin123** [select2/select2#3900]
Hello, one of my visitors cant se the select2 field because of the following error:
```
Unexpected end of input select2_locale_de.js:7 Uncaught TypeError: Cannot read property 
'locales' of undefined
```

The page is a small webapp for only this one visitor and worked for one year without problems, but now this error occurs.

He is using Chrome with the newest Version, and I have the newest Version too but dont get the error.
So is there a solution for this?
Why does this error only occurs when the visitors loads the page?

**Comment by kevin-brown** [comment]
This sounds like you are using translation files for Select2 that are not the same version as Select2 itself. If you're using a newer version of Select2, you need to upgrade your translation files.
