### ISSUE TITLE
jQuery Validation Plugin doesn't validate on selection changes.

### ISSUE THREAD

**Issue by berniegp** [select2/select2#3901]
The validation waits until you first try to submit the form, then it validates everything at once. After this, it will detect changes to individual fields and will validate these as they change. This lets you know sooner if the field now validates correctly.

The problem is that the validation plugin listens to `focusin`, `focusout`, `keyup` and `click` events which Select2 doesn't trigger.

This is essentially the same issue as #259. It seems that the code which fixed it by triggering a `click` event on selection change was removed in Select 2 v4.0.0.

I believe `SelectAdapter.prototype.select` in `src/js/select2/data/select.js` is where the `change` event is triggered and perhaps where a a click event should also be triggered.

**Comment by morrow95** [comment]
I had a little trouble when switching to 4.0 as well as there are some changes needed.  You just need to validate on change of the select2 element.  Also, you will need to copy/remove the error classes to the dropdown as needed as they are separate from the actual select input.  I included both below : 

```
$("#yourselectelement").select2({
	allowClear: true,
        multiple: false,
        tags: true,
        ...other settings,
	},
	ajax: {
            ...
	}
}).on("change", function (e) {
	$(this).valid(); //jquery validation script validate on change
}).on("select2:open", function() { //correct validation classes (has=*)
    if ($(this).parents("[class*='has-']").length) { //copies the classes
        var classNames = $(this).parents("[class*='has-']")[0].className.split(/\s+/);

        for (var i = 0; i < classNames.length; ++i) {
            if (classNames[i].match("has-")) {
                $("body > .select2-container").addClass(classNames[i]);
            }
        }
    } else { //removes any existing classes
		$("body > .select2-container").removeClass (function (index, css) {
		    return (css.match (/(^|\s)has-\S+/g) || []).join(' ');
		});            
    }
});
```

**Comment by berniegp** [comment]
Thanks for your help @morrow95! That change listener is a really easy quick fix.

Since I already configured my jquery validate plugin to add the validation state classes to `form-group` elements for Bootstrap integration, I didn't need that part but I'm sure it can help others.

In any case, I think this issue is still valid since this is a regression compared to 3.x which had better compatibility built-in.

**Comment by morrow95** [comment]
Actually you do need the second part because the dropdown will not get the same validation classes applied.  If you are changing the color of the border for example only the 'input box' will change and not the dropdown border.

**Comment by berniegp** [comment]
Ah indeed! It's a matter of taste though as I don't require the dropdown itself to have a different styling based on the validation state.

**Comment by AmaliDeveloper** [comment]
You get the solution in this tutorial [Link](https://youtu.be/pCpXG52LNEY)

**Comment by jcagarcia** [comment]
Any new about this issue?
