### ISSUE TITLE
Bad inline layout at certain width with select multiple

### ISSUE THREAD

**Issue by alxndrsn** [select2/select2#3906]
# Config

Version: 4.0.0
# Demo

<img width="475" alt="screen shot 2015-11-05 at 17 15 40" src="https://cloud.githubusercontent.com/assets/191496/10974138/e7e2338e-83e0-11e5-9a29-dfe39264ac21.png">
# Steps to recreate
1. open select2 _Examples_ at https://select2.github.io/examples.html
2. scroll down to _Multiple select boxes_ example
3. execute `$(".js-example-basic-multiple").select2({ allowClear: true });` in js console
4. select _Alaska_ and then _Hawaii_
5. right-click on _Hawaii_, and choose _Inspect Element_
6. select the `<li>` element for _Hawaii_ in _Inspector_/_Elements_ debug tab
7. for the selected element, set `width: 249px`
8. observe weird layout
# Notes

This example may seem contrived, but will happen IRL if content lengths are correct, e.g.:

<img width="693" alt="screen shot 2015-11-05 at 14 06 43" src="https://cloud.githubusercontent.com/assets/191496/10974183/1658b30a-83e1-11e5-9be8-56f33652af1e.png">

**Comment by kevin-brown** [comment]
This has to do with how we place the "clear" button (as the first element), and how we never really designed it to be used with a multiple select (but it "works").

**Comment by RobertDiebels** [comment]
https://github.com/select2/select2/issues/4470 has a fix for this.
