### ISSUE TITLE
Add data-subtext to selected value

### ISSUE THREAD

**Issue by imHakanArslan** [select2/select2#3907]
It would be great to have the subtext follow the value into the currently selected and display like it does in the dropdown.
![screenshot 2015-08-06 09 53 50](https://cloud.githubusercontent.com/assets/374136/10993505/00c1f76c-8478-11e5-8523-997a5e74c5f3.png)

**Comment by kevin-brown** [comment]
This can be done using a custom callback for `templateResult`.

https://select2.github.io/examples.html#templating
