### ISSUE TITLE
Select2's guide?

### ISSUE THREAD

**Issue by phuwin** [select2/select2#3909]
Hi,

I am new to Select2. There is no complete guide/ tutorial for this plugin. I think the example is not enough.

For example, in this [issue](https://github.com/select2/select2/issues/1002), Kevin mentioned: 

> This was fixed in 4.0, you should be able to use duplicate ids now and it should work relatively well. 

But I couldn't find any documentation about it?
Another thing I want to know is how I manipulate `data` key. In a stackoverflow [question](http://stackoverflow.com/questions/31431197/select2-how-to-prevent-tags-sorting), this is a piece of an answer:

```
 var names = [{"id":"1","name":"Adair,James"}
             , {"id":"2","name":"Anderson,Peter"}
             , {"id":"3","name":"Armstrong,Ryan"}]

    $("#e10_2").select2({
            data:{ results: names, text: 'name' },
            formatSelection: format,
            formatResult: format                        
    });

```

Where I can find the documentation about the `results` and `text`keys?

**Comment by phuwin** [comment]
Hi Kevin, can you show me how to disable duplicate item check? I really need it now.<br>
Keep good work!

**Comment by kevin-brown** [comment]
I might as well mention that documentation is something that we can always improve on, and we do have a new documentation site being cooked up for 4.0.1. Until the release candidate is finalized, it's not going to be publicly visible (but the code is in the `docs` folder of the master branch).

> can you show me how to disable duplicate item check?

There's a difference between _allowing duplicate ids_ and _allowing items to be selected multiple times_. Previously Select2 would not allow any `<option>` tags which shared the same `value` (internally called the `id`) to be selected multiple times, so a situation like the following would not be allowed.

```html
<select>
  <option value="1">1</option>
  <option value="!">One</option>
  <option value="2">2</option>
</select>
```

As Select2 would only allow you to select "1" or "One", but not both.

**Comment by phuwin** [comment]
Thanks a lot.
Cheers!

**Comment by markstos** [comment]
It seems that `formatResults` should be mentioned on the [options page](http://select2.github.io/options.html#backwards-compatibility). It is listed neither in the main "options" section, nor in the "deprecated" section. It seems it should appear there in one or the other sections.

**Comment by alexweissman** [comment]
I hope that our new docs on data sources (see https://select2.org/data-sources/formats) covers this adequately.  If you have suggestions for further improving this chapter, please open a new issue.
