### ISSUE TITLE
The html code for fetching css for Select2 is missing

### ISSUE THREAD

**Issue by KangYoosam** [select2/select2#3910]
http://select2.github.io/

On this page, section of Using Select2 from a CDN, the html code ```<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />```
should be like below.

```<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />```

**Comment by kevin-brown** [comment]
Thanks for creating a ticket about this!

After looking at the proposed changes, I can't quite figure out what change you are suggesting. The location of the CSS file on cdnjs hasn't changed at all, and the HTML doesn't look that much different. The `type="text/css"` is optional as of HTML 5, and there is no need to have `rel="stylesheet"` twice.

I may have missed something though, in which case feel free to correct me and point it out.
