### ISSUE TITLE
auto trigger change

### ISSUE THREAD

**Issue by joomlaA1** [select2/select2#3914]
when change a field value
currently:
$("#id").val("newVal").trigger("change");

could it be auto(no need for me to type .trigger("change") to reflect change):
$("#id").val("newVal");

thanks

**Comment by kevin-brown** [comment]
Select2 does not control the `.val()` method, so it has to detect changes based on the standard `change` event that browsers will trigger when the value has changed. We have no interest in patching it to trigger the event either, as that would cause far more issues.
