### ISSUE TITLE
allowClear option cross renders over select option label (in specific case)

### ISSUE THREAD

**Issue by mlukaszewski** [select2/select2#3916]
![select2_bug](https://cloud.githubusercontent.com/assets/4126151/11060867/32f61b22-87a3-11e5-9e17-97f5b4070f05.png)

As you see if all labels has same length and max len is no more than 10 chars a cross is rendered over label.

For longer labels all looks fine

![select2_bug_2](https://cloud.githubusercontent.com/assets/4126151/11060873/3bea86c8-87a3-11e5-9cdb-f957b85f01ac.png)

v. 4.0.0, 4.0.1-rc.1

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
