### ISSUE TITLE
Scroll into view dynamically added and selected option

### ISSUE THREAD

**Issue by ErtugKaya** [select2/select2#3923]
If you add options to a select with js and change it's value, selected item won't scroll into view at first. Please take a look at the fiddle:

http://jsfiddle.net/0e38edu8/

Clicking on select, selected item won't scroll into view, unless you close and reopen it. Any workaround for this?

HTML

```
<select id="mySelect"></select>
```

JS

```
for (var i = 0; i < 100; i++) {
    $('#mySelect').append($('<option>', {
        value: i,
        text: i
    }));
};
$("#mySelect").select2({width: 100});
$("#mySelect").val("95").trigger("change");
```

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
