### ISSUE TITLE
Clear & postback moves search-list

### ISSUE THREAD

**Issue by manijak** [select2/select2#3928]
I came accross a weird error in the component. I use select2 in a ASP.net WebForms solution. Where we are using asp:DropDownlists. 

I have 2 dropdowns, both select2 wrapped, and they are populated in codebehind. When selecting a value in dropdown1, it populates dropdown2. This is done in a postback. So every time the selectedindex is changed it triggers the population of the next dropdown. This works just fine. 

But when pressing the clear icon in the select2 dropdown, it opens the dropdown search-list. As soon as I start typing something, the dropdown search-list moves to  x:0 y:0 in the browser (top left corner). And it won't go away until you select something :) Even if you do select a value it is not applied and you have to do it again. 

This only happens when pressing the Clear icon while the dropdownlist is attached to a postback event. Otherwise it works.

Running the 4.0.1 Release Candidate 1 with jquery 2.1.1.

**Comment by Decagon** [comment]
Could you provide the rendered ASP.net WebForms code that causes this error?

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
