### ISSUE TITLE
Using select2 dropdown list in a table with dynamically added rows.

### ISSUE THREAD

**Issue by abstractindia** [select2/select2#3929]
Hi, I am having a table in which the second row is having some form fields. One of the cell is having a select2 dropdown list. I need to add rows dynamically as per the users need, I have placed add a row and delete row buttons which adds and deletes the additional rows respectively. When I add a row by clicking the add row, the new row is created with the dropdown list but it is not working. I mean to say clicking on the dropdown list do nothing in the newly added row. This is my javascript that adds and removes the row.

    <script language="javascript">
        function addRow(tableID) {
 
            var table = document.getElementById(tableID);
 
            var rowCount = table.rows.length;
            var row = table.insertRow(rowCount);
 
            var colCount = table.rows[0].cells.length;
 
            for(var i=0; i<colCount; i++) {
 
                var newcell = row.insertCell(i);
 
                newcell.innerHTML = table.rows[2].cells[i].innerHTML;
                
            }
        }
 
        function deleteRow(tableID) {
            try {
            var table = document.getElementById(tableID);
            var rowCount = table.rows.length;
 
            for(var i=0; i<rowCount; i++) {
                var row = table.rows[i];
                var chkbox = row.cells[0].childNodes[0];
                if(null != chkbox && true == chkbox.checked) {
                    if(rowCount <= 2) {
                        alert("Cannot delete all the rows.");
                        break;
                    }
                    table.deleteRow(i);
                    rowCount--;
                    i--;
                }
 
 
            }
            }catch(e) {
                alert(e);
            }
        }
 
    </script>

**Comment by kevin-brown** [comment]
You are going to need to destroy Select2 before you clone the row, and then reinitialize Select2 after the new row is inserted into the DOM. It's not (easily) possible to clone Select2, along with the event bindings, when Select2 is initialized already.

**Comment by srikanthdevasani** [comment]
can You please tell me how to destroy Select2

**Comment by srikanthdevasani** [comment]
> 
> 
> You are going to need to destroy Select2 before you clone the row, and then reinitialize Select2 after the new row is inserted into the DOM. It's not (easily) possible to clone Select2, along with the event bindings, when Select2 is initialized already.

can You please tell me how to destroy Select2
