### ISSUE TITLE
Multiple selection as a list - without input

### ISSUE THREAD

**Issue by gcacars** [select2/select2#3941]
Hello. I search over the web and I didn`t found any option in select2 and any plugin that works like a list with multiple selection.
Any way to do this in select2? With a suspense list, marks and search?
![select](https://cloud.githubusercontent.com/assets/1190940/11219028/3f86979e-8d3f-11e5-930d-eb9eac7672c8.PNG)
Thanks.

**Comment by kevin-brown** [comment]
Select2 is designed to work as a dropdown, and as a result there are no built-in options that will embed the dropdown beneath (or as a replacement for) the selection box.
