### ISSUE TITLE
Consider refactoring `src/scss` structure to improve theming capabilities

### ISSUE THREAD

**Issue by designorant** [select2/select2#3947]
I like the idea of having a separate `src/scss/theme` directory for custom themes but the base styles contain some very specific properties that are somewhat restricting if one prefers to make the style of select boxes to be inherited from or shared with their non-select2 versions.

In other words I'd like to see the base SCSS as basic and flexible as possible with all fixed values set in specific themes. The reason behind that is that I like to keep the files provided by the package untouched for easy upgrades, and fiddling with them defeats the idea of pulling them from the package, and somewhat conflicts with the idea of having themes.

This might be an edge case but I'd be more than happy to refactor the files in a PR at some point.

Any feedback would be very welcomed.

Additionally, I've found out that `box-sizing: content-box;` works much better than `border-box` in forms, particularly with `<select>` elements sharing styles with `<input>`.

`// TODO: Insert a CodePen showing vertical alignment differences in between the two.`

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:
