### ISSUE TITLE
Technical documentation

### ISSUE THREAD

**Issue by ghost** [select2/select2#3948]
Besides the examples, I think it's necessary to describe each option of the plugin.
For me, this is more important than setting examples for each case.

Something like [selectize docs](https://github.com/brianreavis/selectize.js/tree/master/docs), a table with each available option and what it does.

**Comment by Hacktivista** [comment]
+1 for this, we don't have even a map of options and events in order to guide us :( not a good thing

**Comment by kevin-brown** [comment]
Note that [the old options page](http://select2.github.io/options-old.html) has descriptions of _some of_ the options, so that may be helpful while we're waiting on better documentation to arrive.

**Comment by jaimz22** [comment]
This really should be made at some point, 4.x is REALLY hard to work with because the documentation seems to be geared toward non-technical users... as if there were any. It really seems more like the owners manual to a piece of hardware and less than documentation of software.

**Comment by jgbishop** [comment]
I propose adding a _Reference_ section to the documentation, with corresponding pages (or sub-sections) covering the various options, events, etc. I need to set up a Linux VM (the Jekyll stuff used in this package's documentation is Windows-hostile), but I would be happy to start this effort.

**Comment by jgbishop** [comment]
I've started work on adding a Reference section to the documentation. Anyone looking to assist with this is welcome to join: [jgbishop/select2 at ref-wip](https://github.com/jgbishop/select2/tree/ref-wip)

**Comment by alexweissman** [comment]
This is done.  You can find it here: https://select2.org/configuration/options-api
