### ISSUE TITLE
Data attributes on ajax call

### ISSUE THREAD

**Issue by jaecSolutions** [select2/select2#3952]
Hi, 
I try to add a data-attribute on my option tag on a ajax call but I can't.

        processResults: function (data) { 
           return {
              results: $.map(data, function (item) {
                    return {
                        text: item.text,
                        'data-tag': item.anotherValue,
                        id: item.id
                    };
                })
            };
          },

**Comment by kevin-brown** [comment]
If you're dealing with AJAX, you have full control over the data objects. So you don't need to include `data-` in front of things, the names will be included just like `id` and `text` normally are.
