### ISSUE TITLE
Select2 trigger "select2:select"

### ISSUE THREAD

**Issue by kzweb** [select2/select2#3954]
I have a script that does the following code:

```javascript
select2input.on('select2:select', function(e, e2) {
            if (e.params !== undefined && e.params.data !== undefined) {
                div.html(e.params.data.unidade_medida_txt);
                anotherinput.val(FloatField.format(e.params.data.valor_compra)).trigger('change');
            }
        });
```

I need to manually call "select2: select" and pass the data "e.params", how do?

Something like:

```javascript
select2input.trigger('select2:select', ...pass params...);
```

Thank you.

**Comment by kevin-brown** [comment]
You can look into [the `select2/selection/eventRelay` decorator](https://github.com/select2/select2/blob/7e2ade09652f66f3a70787f6f0e2918d171a6dcb/src/js/select2/selection/eventRelay.js#L29-L31) for how Select2 triggers events internally.

**Comment by invious** [comment]
Ok I still don't understand, `$myselect.trigger('whatgoeshere')` ?

**Comment by invious** [comment]
The whole internet is talking about calling `trigger('change')` but when I call trigger change, it doesn't call my 

```
on('select2:select', function (e) {
                // var data = e.params.data;
                callback(e)
            });
```

Which is why i'l like to be able to trigger that callback

**Comment by bgiesbrecht** [comment]
Hey @invious, I found this thread while struggling with this myself.

Calling val and then change does not seem to trigger the select2:select, you have to fire it yourself. The doc for this is [here](https://github.com/select2/docs/blob/master/pages/12.programmatic-control/04.events/docs.md).

This is how I did it:
```
// Construct my data to select
var data = {
  "id": my_val
};

// Set the value
$("#foo").val(my_val);

// Change the select2 control to update it visually
// (does not fire select2:select)
$("#foo").trigger("change");

// Manually fire the event with my data
// This DOES fire select2:select.
$('#foo').trigger({
    type: 'select2:select',
    params: {
        data: 
    }
});

```
HTH

**Comment by dwasyl** [comment]
@kevin-brown I know this is an old ticket, but I found it having the same problem, `trigger('change')` doesn't fire a select2:select event. I tried @bgiesbrecht's suggested code, but haven't found it to work.

Shouldn't 'change' also fire a select? Or is there a better manual way to trigger the select2:select?

**Comment by michaelvickersuk** [comment]
Chaining `trigger('change')` with `trigger('select2:select')` allowed me to successfully call my select2:select event.

```js
$('#mySelect2')
   .val(1)
   .trigger('change')
   .trigger('select2:select');
```

**Comment by riccardobianconi** [comment]
Since I use `select2:select` event to get the selected value and select2 set this value inside `e.params.data.id` I set a value like this:

    $('#mySelect2')
        .val(selectedValue)
        .trigger('change')
        .trigger({
            type: 'select2:select',
            params: {
                data: {
                    id: selectedValue
                }
            }
         });
