### ISSUE TITLE
Flat Design theme for Select2

### ISSUE THREAD

**Issue by techhysahil** [select2/select2#3957]
somedays back i was looking for plugin which can select multiple values and load data remotely. I got this one and save my life. But i was looking for Flat design theme for this which i get from somewhere which was like broken, i mean not complete Flat Theme. Also it had lot of design bug which i had to fix.

Now i had build nice Flat design theme for this, if you like to include it in here. I would love to do because it will help others too in future.

**Comment by schrepfler** [comment]
Sharing is caring, PR away :)

**Comment by techhysahil** [comment]
"PR away". What is that??

**Comment by techhysahil** [comment]
Sorry but i am confused here. You want to send Pull request or not?

**Comment by schrepfler** [comment]
You said you've built a flat design theme, so I've suggested you to share it by submitting a PR. That is the standard approach to contribute to open source code bases.

**Comment by techdragon** [comment]
@techhysahil - I'll translate it to 'standard' english. "Sharing is good. Please send the pull request, we would be happy to have it."

**Comment by techhysahil** [comment]
Also created demo link for quick preview
http://codepen.io/techhysahil/pen/qbrqWG
