### ISSUE TITLE
Internet Explorer: Multiselect inline-search moves upwards after first tag

### ISSUE THREAD

**Issue by ivanmcgregor** [select2/select2#3960]
Upon selecting the first entry that gets added as a tag the search field is somehow moved upwards, destroying the Design. Happens in IE with Edge, as well as compatibility mode for 10 and 9. 

See the "h" in the search area: 
![ie bug](https://cloud.githubusercontent.com/assets/13334936/11394177/ca241bb8-9363-11e5-9ffd-f5a77ef86103.png)

Example from [https://select2.github.io/examples.html#placeholders](https://select2.github.io/examples.html#placeholders)

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
