### ISSUE TITLE
Very long search inputs push selections out of view

### ISSUE THREAD

**Issue by ivanmcgregor** [select2/select2#3961]
When I do have some Tags in my multiselect and then add a long text, the tags are being pushed out of the visible area. Instead I would expect the input to change to a textarea and if necessary force a break into the next line. 

I do consider this more an improvement than a bug, as this is probably a rare occurrence out in the wild

Following a collage of what can be observed: 
- entering a long text
  ![long search 1](https://cloud.githubusercontent.com/assets/13334936/11395281/64e5fba2-936a-11e5-9caa-68d65bd4c4d5.png)
- tags are being pushed out
  ![long search 2](https://cloud.githubusercontent.com/assets/13334936/11395283/6b98d992-936a-11e5-8137-ac7724aa431f.png)
- tags are now out of sight
  ![long search 3](https://cloud.githubusercontent.com/assets/13334936/11395284/6d79b628-936a-11e5-89f6-e22e102a97da.png)
- clicking outside of the span. Notice how the height remains at 2 columns and the tags are still cut off to the left
  ![long search 4](https://cloud.githubusercontent.com/assets/13334936/11395286/6f0aa7c2-936a-11e5-8f30-9c31a3a2ba98.png)
- upon clicking in the tags are still hidden
  ![long search 4 5](https://cloud.githubusercontent.com/assets/13334936/11395335/b42bb350-936a-11e5-94bb-5c0876e41b9b.png)
- only when typing again, everything is rendered again and displayed correctly
  ![long search 5](https://cloud.githubusercontent.com/assets/13334936/11395287/707b7636-936a-11e5-974f-23c4758f619c.png)

**Comment by Fcatalao** [comment]
Hello. I have an identical problem that you can try on Select2 demos.
When I use the ability to insert more than one option by text inserted mannualy, if that text lenght is bigger than HALF of the width of the select2 , after inserting (clicking ENTER), it goes to a new line, making my entry ''disappear to upside". If i click on any char key it starts the input after my already entered text in the same line (so it revert the line break).

So i'm using the ability to insert ONLY one option manually, and that option sometimes will be longer than half of the width. How can I make it to do not create a line break after entering my entry only if it's bigger than half of the width?

Example:
With a entered text less than half:
https://ibb.co/dDiZm5

With a entered text bigger than half:
https://ibb.co/jxn5tk

With a entered text bigger than half and after that, insert a text we can see the ''cursor'' goes to the front and bring back a single line entry:
https://ibb.co/npwn65
