### ISSUE TITLE
Image of dropdown stays after closing the dropdown in chrome

### ISSUE THREAD

**Issue by hasanfkhan** [select2/select2#3968]
I am observing a weird behavior in chrome recently. When I try to close the select2 dropdown, a part of the image of the dropdown still remains. Any ideas as to what might be causing it and any possible solutions to this problem?
![select2chromeissue](https://cloud.githubusercontent.com/assets/8572613/11455111/3c3fadea-966e-11e5-9c9c-3602864454de.jpg)

**Comment by hasanfkhan** [comment]
This issue is specific to chrome. I have tested it on Internet Explorer and Microsoft Edge and everything works fine on both of those browsers. I have been using select2 in web applications and have been testing it since two years on chrome and never had this issue before. I am just observing this recently.

**Comment by kevin-brown** [comment]
I'm not able to reproduce this on the [documentation website](https://select2.github.io/examples.html). Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by hasanfkhan** [comment]
I am getting the issue only with multilevel dropdown only (hovering over first-level dropdown options opens an associated dropdown showing sub-options) and that too on chrome.

![select2multilevel](https://cloud.githubusercontent.com/assets/8572613/11460137/d2cc1a42-9708-11e5-9838-483c2c09b152.jpg)

I have tested with Windows 10 (Chrome, Edge and IE). Other users have tested with Chrome on Windows 7. The issue is only happening in Chrome and that too since recently.

I am using Jquery 1.8.2. and have tested on Select2 - 3.5.4. I am using bootstrap besides Select2.

**Comment by hasanfkhan** [comment]
After further testing it seems like the issue is happening if the second level menu option has a large text.

**Comment by kevin-brown** [comment]
That multilevel dropdown is _definitely not_ Select2, it doesn't line up with any of the standard themes. Note that it also has a horizontal scrollbar, something with Select2 avoids whenever possible.

The dropdown beneath it is Select2 though.
