### ISSUE TITLE
Open event fires twice

### ISSUE THREAD

**Issue by PCMener** [select2/select2#3971]
select2:open event firing twice when I open the select element. Select2:opening event have the same problem.

It seems like previous issue #3503 but it still remaining on 4.0.1.

**Comment by kevin-brown** [comment]
I am not able to reproduce this [on the documentation website](https://select2.github.io/examples.html#events).

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by PCMener** [comment]
Sorry for the inconvenience, i found an error in my code which disturb select2:open event. 
I'll close the ticket.
