### ISSUE TITLE
Matcher error

### ISSUE THREAD

**Issue by nickmccally** [select2/select2#3973]
When using 4.0.1 and matcher, I get the following error:

Uncaught TypeError: elem.hasAttribute is not a function. Tested with jQuery 1.11.2 and 2.1.4

Here is a sample of the code:

            function matchStart (term, text) {
		  if ($.trim(term).length >= 5) {
			return true;
		  }

		  return false;
		}
		$.fn.select2.amd.require(['select2/compat/matcher'], function (oldMatcher) {
		$(this).select2({
			
			
			
			ajax: {
			
			  url: path + "EMS/getAssocData/getAssocDynamic/",
			  dataType: 'json',
			  delay: 100,
			  
			  data: function (params) {
				
				return {
					
					EMS_Asscoiate_Lookup: params.term, type: type,
	
				};
			  },
			  processResults: function (data, params) {
				// parse the results into the format expected by Select2
				// since we are using custom formatting functions we do not need to
				// alter the remote JSON data, except to indicate that infinite
				// scrolling can be used
			   

				return {
				  results: data.items,
				 
				};
			  },
			  cache: true
			},
			matcher: oldMatcher(matchStart),
			escapeMarkup: function (markup) { return markup; },
			minimumInputLength: minInput,
			templateResult: format,
			templateSelection: formatSelection,
			placeholder: 'Search by name'
			
		  
		})
		});

**Comment by thijstriemstra** [comment]
Also getting this error.

**Comment by thijstriemstra** [comment]
Managed to fix this by declaring an `element` var that points to `$(this)` **outside** the require call, e.g.:

```javascript
var element = $(this);
requirejs(['select2'], function(select2) {
    element.select2({ // etc....
});
```

Safe to close this ticket as user error I think.

**Comment by kevin-brown** [comment]
> Safe to close this ticket as user error I think.

Yup, didn't notice that in the original code. The value of `this` was changed.
