### ISSUE TITLE
Better documentation for the tags option

### ISSUE THREAD

**Issue by mechanicious** [select2/select2#3974]
Which pseudo-class and method is responsible for "refreshing" Select2 using the corresponding `select` DOM-element? I would like to add an option in _real-time_ to the `select` DOM-element, make Select2 refresh itself and use `Search::trigger('query',...)` to execute the search query. I am working on **dynamic options** for this plugin.

**Comment by mechanicious** [comment]
I've just solved it, here's a preview of the new feature:
![dynamic input preview](http://i.imgur.com/luKXS3F.gif)

**Comment by kevin-brown** [comment]
This sounds like you were looking for the `tags` option, which works in a single select, but I can't tell. Your example looks very close to (if not exactly like) how tagging works.

> do you have a constructor for data.results objects used in Results::append?

Select2 expects the standard result objects to be returned, you can find examples of how native DOM elements are converted in the documentation: http://select2.github.io/options.html#how-are-option-and-optgroup-tags-serialized-into-data-objects

**Comment by mechanicious** [comment]
Thank you for your reply. In regard to your comment about `tags`' behaviour, your for the most part right except it's not a tag, it's a `dynamic option` which is a totally different feature I call `dynamic option` which has a somewhat different behaviour, and has it's own place and future in the project which is totally independent from the `tags` feature.

As for the `constructor` I was looking for a method which takes `HTMLOptionElement` and outputs a `result` as in `data.results`.

**Comment by kevin-brown** [comment]
> It has a somewhat different behaviour

Any chance you can clarify what the different behaviour is that you are looking for?

> As for the constructor I was looking for a method which takes HTMLOptionElement and outputs a result as in data.results.

Select2 internally uses [`SelectAdapter.item`](https://github.com/select2/select2/blob/bc1996417041d9b6131bd8c2ba911984c7b6f2d9/src/js/select2/data/select.js#L200-L244) for converting a `HTMLOptionElement` (wrapped with jQuery) to a data object. Note that while it's _unlikely to change_, it's not yet stabilized as a public API.

**Comment by mechanicious** [comment]
Any chance you can clarify what the different behaviour is that you are
looking for?

I am not sure whether you've seen the GIF I've included in one of my
previous responses . A `dynamic option` is an option which
is automatically created by the plugin based on user's input `if user has
enabled it and if the user's input matches no available options`; the
`dynamic option` feature replaces the default behaviour in a situation when
`the user's input matches no available options`.

**Comment by mechanicious** [comment]
Any chance you can clarify what the different behaviour is that you are looking for?

I am not sure whether you've seen the GIF I've included in one of my previous responses. A `dynamic option` is an option which is automatically created by the plugin based on user's input `if user has enabled it and if the user's input matches no available options`; the `dynamic option` feature replaces the default behaviour in a situation when `the user's input matches no available options`.

**Comment by mechanicious** [comment]
Any chance you can clarify what the different behaviour is that you are looking for?

I am not sure whether you've seen the GIF I've included in one of my previous responses. A `dynamic option` is an option which is automatically created by the plugin based on user's input `if user has enabled the support for it and if the user's input matches no available options`; the `dynamic option` feature replaces the default behaviour in a situation when `the user's input matches no available options`.

**Comment by kevin-brown** [comment]
So the difference between what you are looking for and `tags: true` when applied to a single select is that you only want the user-created option to display when there are no other options displayed in the results? Right now setting `tags: true` will display the option when there is no exact match available.

You can find a demo of `tags: true` with a single select at this jsbin: http://jsbin.com/xacixeceqo/1/edit?html,js,output

**Comment by mechanicious** [comment]
A misunderstanding has occurred, due to the terminology and the incomplete documentation. From your documentation I've assumed that the `tags` option automatically triggers tokenization – which is not true. Your JS-bin example exactly shows the behaviour I was looking for – I went all the trouble to creating it myself though. Thanks for your input.

**Comment by mechanicious** [comment]
A misunderstanding has occurred, due to the mistake in documentation. From the documentation I've assumed that the `tags` option automatically triggers behaviour as in [tagging](https://select2.github.io/examples.html#tags). Your JS bin example uses exactly the same code (so it seems) as [tagging](https://select2.github.io/examples.html#tags) in docs but produces a different behaviour. Most likely is [tagging](https://select2.github.io/examples.html#tags) a duplicate example of [tokenization](https://select2.github.io/examples.html#tokenizer).

**Comment by mechanicious** [comment]
A misunderstanding has occurred. I wouldn't expect the behaviour of a single-option select from what the docs show for a multiple select. I would recommend you to add an additional example for a single-option with `tags` enabled. Your jsbin example is exactly what I was looking for. Thanks for your input.

**Comment by alexweissman** [comment]
@mechanicious I agree with you, `tags` is a misnomer for this feature.  I've tried to mitigate the confusion by referring it to as [Dynamic option creation](https://select2.org/tagging) in the documentation, but unfortunately we're stuck with the `tags` identifier until the next major version.

At the very least, the docs recognize these as two distinct features now.  Is there anything else in this issue that still needs to be addressed?

**Comment by mechanicious** [comment]
> ...mitigate the confusion by referring it to as Dynamic option creation in the documentation...

I think you've hit a home run. Hope it works out; fingers crossed.

**Comment by alexweissman** [comment]
Yay!
