### ISSUE TITLE
Doubled tags problem

### ISSUE THREAD

**Issue by nabidefacto** [select2/select2#3975]
Hello,

I found one bug with tags. 
If you try to type-in the same tag, that've already been added, it removes both tags. 
You can try it here: https://select2.github.io/examples.html

But, in version 3.5.3 works ok: http://select2.github.io/select2/

Thank you

**Comment by mechanicious** [comment]
Strongly connected with #3951, although they don't mention them about disappearing tags.

**Comment by kevin-brown** [comment]
Closing this as a duplicate of https://github.com/select2/select2/issues/3951.
