### ISSUE TITLE
Can't delete all items

### ISSUE THREAD

**Issue by jbezdicek** [select2/select2#3981]
Hello, the problem is, when I delete all items simply the form will behave like I wouldn't do ANY change. I can delete items in multiselect one by one, but when I delete ALL of them, simply nothing will happen. Any ideas ? :/

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by jbezdicek** [comment]
I've selected few items and saved it. Then I've unselected ALL items, but nothing happens ... like I wouldn't do a single change. Simply if you leave that multiselect blank (when you previously had values selected there) nothing would happen.
Expected outcome is just removing all selected items, problem is, that my form still sends the values of items that were selected BEFORE I removed them.
I tested it on two computers (Windows 7 and Windows 10) with all possible browsers like chrome, firefox, IE, edge, opera. And yes, that bug happens everywhere. 
jQuery we're using is 1.8.2 and Select2 is something about 3.0.8 or something like that, anyways problem persists even when I tried to replace it with up-to-date Select2. And I'm not using any other plugins than jQuery, Select2, Datetimepicker and lightbox. Thanks for the anwer.

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
