### ISSUE TITLE
Cannot set selected items

### ISSUE THREAD

**Issue by rohan-deshpande** [select2/select2#3983]
Okay so this is quite puzzling to me. Look at the following code

    var selected = selectedAsString.split(', ');

    console.log(options.indexOf(selected[0])); // this is > -1
    console.log(options.indexOf(selected[1])); // this is also > -1

    $select2.select2('data', selected);
    console.log(selected); // logs the correct array
    console.log($select2.select2('data')); // logs an empty array

I don't really understand why this is happening, my options are simply arrays of strings, fyi my methods for updating the select2 input on change work fine.

**Comment by rohan-deshpande** [comment]
Another example

    var selected = [{id:1,text:'one'}, {id:2,text:'two'}];
    
    $select2.select2({data:[{id:1,text:'one'}, {id:2,text:'two'}, {id:3,text:'three'}], minimumInputLength:3});
    $select2.select2('data', selected);
    
    console.log($select2.select2('data')); // logs an empty array

**Comment by kevin-brown** [comment]
Note that in Select2 4.0.0, you can no longer set the internal data using `select2('data', data_array)`. You never specified your version, so that may have been the issue.

It may have also been because you are setting the data to individual ids, instead of using `.val()`.
