### ISSUE TITLE
placeholder not working with ajax option

### ISSUE THREAD

**Issue by developingo** [select2/select2#3986]
I've tried two ways of doing this, the first one, described in the following fiddle, with a select input with an empty option:

http://jsfiddle.net/aqrzL2sd/2/

And the second one, with a hidden input as suggested in select2 github issues (see browser console for this):

http://jsfiddle.net/t89ddnuo/1/

But no one works, the placeholder is not showing. What am I doing wrong?

**Comment by developingo** [comment]
It seems like the `templateSelection` function overrides the placeholder

http://jsfiddle.net/aqrzL2sd/3/

**Comment by kevin-brown** [comment]
> It seems like the templateSelection function overrides the placeholder

Correct, the placeholder is templated. This is why you should always include a fallback to `item.text`, because most other Select2-displayed messages are also templated.
