### ISSUE TITLE
Results from sorter is an array of bool values, and does not contain actual data

### ISSUE THREAD

**Issue by anepher** [select2/select2#3996]
I switch to the new version and I found out the the sorter function implemented is not working anymore. The function crash when trying to access text value from a result item (a.text.toLowerCase()).
![select2sorter](https://cloud.githubusercontent.com/assets/11735027/11623849/49a1bd96-9cd8-11e5-9d01-4a1077502151.png)
Please can you tell how I can implement the sort on the newer version?

**Comment by kevin-brown** [comment]
The `sorter` method should return a new list of the results, all of them being sorted the way that they should appear. And the input for it should be the list of results that are about to be displayed, as returned from the local data source or a remote one.

In any case, I can't reproduce this issue locally.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by anepher** [comment]
- I  have added "select 2" control to the page where I want to have access to the sorter, I am using the drop down from the page
- Current behavior: If I use the sorter it receive in the results an array of bools instead of an array of objects with properties like text. 
- Expected behavior:  In the sorter it should be passed a list o objects from where I can access the text of the item.
- Operating system Windows 8.1
- Browser: Chrome: Version 47.0.2526.73 m
- The problem occurs every time
- J Query version:  2.1.4
- Select2 version: 4.0.1
- I am using select2 with bower components that came with a theme that I bought
I personally believe here is the problem, I think the person who created the theme has some code that change select2, there are a lot of JS files and some are only minified and I cannot check right now but I think that is why the results list is altered.
Thank you for your response, I think this issue can be closed

**Comment by alexweissman** [comment]
There is an open request to document `sorter` in #4694.
