### ISSUE TITLE
Select2 crashes Chrome (time out)

### ISSUE THREAD

**Issue by diogocezar** [select2/select2#3999]
When i try to configure select2 in chrome. The window crashes.

Chrome version: 47.0.2526.73 m

Works fine on Firefox.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by kevin-brown** [comment]
Didn't mean to close this earlier, so I'll tag it as a duplicate of https://github.com/select2/select2/issues/4002.
