### ISSUE TITLE
Add event for ajax request completed

### ISSUE THREAD

**Issue by mitch3182** [select2/select2#4000]
I want to add some changes to result's container after ajax loaded to `<ul>`.
Will it be right way to add "data-loaded" relay event?

example: 

``` js
var relayEvents = [
      'open', 'opening',
      'close', 'closing',
      'select', 'selecting',
      'unselect', 'unselecting',
      'data-loaded', 'data-loaded',
    ];
```

and

``` js
    this.$results.append($options);
    this.trigger('data-loaded');
```

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
