### ISSUE TITLE
Select2 crash Chrome (time out)

### ISSUE THREAD

**Issue by diogocezar** [select2/select2#4002]
Hey there, i'm sorry by my last topic without informations, let's do it in the right way:

What steps can be used to reproduce the issue?

I'm using Select2 in (https://almsaeedstudio.com/preview) AdminLTE.

Just using all versions and plugins that comes with the package.

What is the bug and what is the expected outcome?

The bug is simple, when you try to configure select2 in multiple selects, like:

$("select").select2();

The chrome executes some kind of infinite loop, until crashes the current page.

What browser(s) and Operating System have you tested with?

Chrome version: 47.0.2526.73 m
OS: Windows 10.

Does the bug happen consistently across all tested browsers?

No, this bug happens only on Chrome.

What version of jQuery are you using? And what version of Select2?

JQuery : jQuery v2.1.4
Select2 : 4.0.0 

Are you using Select2 with other plugins?

Yes, all plugins in AdminLTE.

**Comment by kevin-brown** [comment]
I'm assuming the page where you are seeing this is https://almsaeedstudio.com/themes/AdminLTE/pages/forms/advanced.html, as that appears to be the only page using Select2. It's not crashing for me in 47.0.2526.73 (same version, same OS), so I'm not sure what is up.

**Comment by diogocezar** [comment]
In this sample works with me too, but when i have my selects the chrome crashes after n number of select2 that i configure.

**Comment by kevin-brown** [comment]
Without a test case where we can reproduce this problem, it's going to be nearly impossible for us to fix the issue that may be causing it. If you can create a jsbin/jsfiddle that consistently shows the page crashing with Select2 being loaded, we can look into why it is happening.

**Comment by diogocezar** [comment]
Ok, let's try it:

http://bancario.padariajoia.com.br/admin/dashboard

Login: guest@diogocezar.com
Pass: 123

And chrome stops.

**Comment by kevin-brown** [comment]
I wasn't able to reproduce the issue there, and there only appears to be 5 Select2 instances loaded on the page.

Here's what I see: https://i.imgur.com/hW83RXc.png

**Comment by diogocezar** [comment]
I understand, there is a lot of things to reproduce, but... the page loaded fully there?

**Comment by diogocezar** [comment]
Well, searching somethings, i found this:

https://productforums.google.com/forum/#!topic/chrome/pw7WCcw-YYQ

Probabily it's a temporary bug, that happens only on updates of windows 10.

**Comment by gpguerra** [comment]
Diogo i'm having the same problem, after this last chrome update.
But I found out what was causing the problem. 

Do you use some bank software security? I was having problem with de Gas Tecnologia security software from Banco do Brasil. 

I removed it and the bug vanished.

**Comment by diogocezar** [comment]
Thanks a lot man, really was that :dancer:

I will disable select2 until Chrome, or Windows or Gas update.

Please, if you solve that, notify us

**Comment by acazsouza** [comment]
I removed the Gas Tecnologia plugins and it keeps crashing on chrome win 8.

Then i decide to debug the code.
In my case what is causing this issue was these line in the select2 css:

user-select: none;

I just commented this and chrome stop crash.

**Comment by diogocezar** [comment]
Not worked here :/ still crashing.

**Comment by GBraL** [comment]
Hi to all,

After upgrade the BB plugin of Gas Tecnologia the select2 start crashing the chrome but in FF this not it happens.

Anyone have a solution?

**Comment by diogocezar** [comment]
Nothing yet :(

**Comment by MaikeAlame** [comment]
Hi everybody,

about Gas Tecnologia plugins, if you commented "user-select: none;" don't forgive to comment too the "webkit-user-select: none".

**Comment by GBraL** [comment]
I changed all but not work with me.

**Comment by acazsouza** [comment]
There more than 1 css entry with theses properties in select2 plugin css.

"user-select: none;
-webkit-user-select: none;"

Verify the rest of your css.

**Comment by GBraL** [comment]
I changed all entry but not work.

**Comment by diogocezar** [comment]
Same here :/

**Comment by BenBezac** [comment]
Hi having the same problem on my site, anyone having some news plz ?

**Comment by kevin-brown** [comment]
This is unfortunately still something which I can't reproduce, and there doesn't appear to be a known fix to the problem.

**Comment by MaikeAlame** [comment]
Hi, Like @GBraL says,

The BB plugin of Gas Tecnologia has generating this issue for me, maybe others plugins. See in private mode on browser if the error appears or try to disable extensions too. Good luck.

**Comment by BenBezac** [comment]
Thx for the answer.

I don't use Gas Tecnologia.

@kevin-brown : Well at the office there are some machines on which the site works and some others it doesn't.
I don't know why. Try lots of things. Chrome version is the same on all devices. I tried without any chrome extension and as well in private mode, still crashing on the same computer...

**Comment by anrananran** [comment]
nooooooooo,  my issue is more strange because the crash only happend when i add some new DOM tags in the HTML document

**Comment by anrananran** [comment]
After testing I found to be due to a certain element‘s style(display: inline-block), if the page uses the select2,  (I guess) may lead to the chrome rendering engine can not work correctly.
the solution is to find out the element that cause this problem, and then delete the element's inline-block style! I have two previous projects met this problem which has been resolved through this approach,  hope to be helpful
