### ISSUE TITLE
Matcher not working properly

### ISSUE THREAD

**Issue by donpro2** [select2/select2#4004]
Hi,

The matcher function used to only return matches that began with the search term. Unfortunately , this has been changed to text that contains the text string and my application no longer functions the way it was designed.

The example code here: https://select2.github.io/examples.html
is not working. Can you please add the original function back (call it something else).

Thanks / Don

**Comment by kevin-brown** [comment]
I'm going to push this to the mailing list, didn't notice this ticket before making my last reply.

https://groups.google.com/forum/#!topic/select2/z7ahNUPvj3E
