### ISSUE TITLE
Call createTag only if tag effective gets added to the selection

### ISSUE THREAD

**Issue by TiMESPLiNTER** [select2/select2#4005]
The function `createTag` gets called now and then if I wait after some keystrokes. Actually I have never added a new tag to my selection.

Probably I just typed something get no matches and like to control the word I've typed for some mistakes and during this time `createTag` gets called and adds the tag to the options. IMO the new tag should only be created if I put the none existing tag into the selection (by clicking on it or hint enter).

I had to "abuse" the `select2:select` event ([see this issue](https://github.com/select2/select2/issues/3063)) to check if a newly created tag was added to the selection and fire an AJAX call to persist it. But in this event I can't modify the option (set the ID from database). So there's no chance to persist new tags on effectively selecting them.

**Comment by kevin-brown** [comment]
`createTag` is responsible for _creating the data object for the tag_, not for _creating the tag server-side_. You must listen for the `select2:select` event to determine if the tag was selected and whether or not it exists in your database.

So I wouldn't call what you are currently doing a hack, that's the expected flow when working with remote responses. As far as updating the option locally, you _might_ be able to directly set the `id` on the data object passed in through the event, or modify the `value` of the `<option>` passed in as `data.element`.
