### ISSUE TITLE
Merge options under <optgroup> when possible

### ISSUE THREAD

**Issue by StevenLiekens** [select2/select2#4010]
I have a grouped select2 list that uses pagination to load 30 list items at a time. Each `<optgroup>` contains one or more `<option>` list items.

Feature request: an option group can cross the boundary of 30 items. When this happens, groups with the same labels at the page boundaries should be merged.
## Example

optgroup `group 1` contains 31 options, AJAX page size is 30.
### AJAX Page 1

``` js
{
  "results" : [
    { 
      "text" : "group 1"
      "children" : [
        {
          "id" : "item1"
          "text" : "first item"
        },
        {
          "id" : "item2"
          "text" : "second item"
        },
        // items 3 to 29 omitted for brevity
        {
          "id" : "item30"
          "text" : "thirtied item"
        }
      ]
    }
  ]
  "pagination" : {
    "more" : true
  }
}
```
### AJAX Page 2

``` js
{
  "results" : [
    { 
      "text" : "group 1"
      "children" : [
        {
          "id" : "item31"
          "text" : "thirty-first item"
        }
      ]
    }
  ]
  "pagination" : {
    "more" : false
  }
}
```
### Expected result

The code should recognize that page 2 should be merged with page 1 instead of appended, because the group header is the same.

``` html
<optgroup label="group 1">
    <option value="item1">first item</option>
    <option value="item2">second item</option>
    <!--  items 3 to 29 omitted for brevity -->
    <option value="item30">thirtied item</option>
    <option value="item31">thirty-first item</option>
</optgroup>
```
### Actual result

``` html
<optgroup label="group 1">
    <option value="item1">first item</option>
    <option value="item2">second item</option>
    <!--  items 3 to 29 omitted for brevity -->
    <option value="item30">thirtied item</option>
</optgroup>
<optgroup label="group 1">
    <option value="item31">thirty-first item</option>
</optgroup>
```

**Comment by muhammadarshad** [comment]
I have fixed this issue and fork here https://github.com/muhammadarshad/select2
i do not know how to push on main project

**Comment by SandovalDanilo** [comment]
Any chance to update the main project to implement this feature?

**Comment by alexweissman** [comment]
@muhammadarshad or someone needs to [submit a pull request](https://help.github.com/articles/creating-a-pull-request/) before this can be considered.

**Comment by bastian-schur** [comment]
@muhammadarshad Can you create a pull request? Its not so difficult, but it would be nice to have this fix in the project.

Is the problem fixed in 4.0?

**Comment by muhammadarshad** [comment]
I think i have created one, but let me check again

**Comment by muhammadarshad** [comment]
Pull request link https://github.com/select2/select2/pull/4026

**Comment by alexxxxkkk** [comment]
Are any changes to this?

**Comment by kevin-brown** [comment]
Reopening this for a stale cycle to see if there is any continued interest in seeing this implemented. It is not high on our list of features and has the potential for unintended side effects, but we're willing to entertain pull requests that implement it.

**Comment by StevenLiekens** [comment]
I'm not currently using select2 in any of my active work, but I'd like to add that only the last optgroup in page 1 and the first optgroup in page 2 should be merged. Merging optgroups that are higher up in the list would cause list items to jump around during scrolling.

**Comment by md5** [comment]
It seems like the goal here should not be to merge `<optgroup>` elements in general (which is what the PR does), but specifically to merge them across page boundaries (which is what the original issue looks to be about).

I believe this can be done relatively easily if an assumption is made that two adjacent `optgroup` elements will not be sent with the same `label`. This may not be a safe assumption to make in general, but I would think that it's the most common case.

It seems like it should be assumed that the server side will provide a stable, consistent ordering of results and their grouping.

Without this change, paginating a grouped list can only be done if the groups are never broken across pages. This can be done with variable page sizes, assuming none of the groups are too large relative to the total option count, but that quickly becomes inefficient in the face of filtered query results.

**Comment by asandri-mmo** [comment]
I disabled pagination from server side to work optgroup correctly

**Comment by Discartyptics** [comment]
This is a feature I'd love to have, since I deal with a lot of data and sometimes that data is grouped.

For anybody else finding this thread via Google, here's a small example of how I was able to achieve a similar feature. This code manipulates the returned server data, replacing "duplicate" groups with their children. (Alternatively, you could also send the "latestGroup" variable to the server and check the group on the server-level.)

Feel free to use however you want, no credit needed.

```
let latestGroup;
$(dropdown).select2({
    ...
    ajax: {
        ...
        processResults: (data,params) => {
            const oldResults = data["results"];
            let newResults;
            if (oldResults.length > 0) {
                if (latestGroup !== undefined) {
                    newResults = [];
                    Array.from(oldResults).forEach(result => {
                        if (result["children"] !== undefined && result["text"].trim().toUpperCase() === latestGroup.trim().toUpperCase()) {
                            Array.from(result["children"]).forEach(child => {
                                newResults.push(child);
                            });
                        } else {
                            newResults.push(result);
                        }
                    });
                } else {
                    newResults = oldResults;
                }
                Array.from(oldResults).forEach(result => {
                    if (result["children"] !== undefined) {
                        latestGroup = result["text"];
                    } 
                });
            } else {
                newResults = oldResults;
            }
            return {
                results: newResults,
                ...
            };    
        }
    }
});

**Comment by Tab10id** [comment]
> It seems like the goal here should not be to merge `<optgroup>` elements in general (which is what the PR does), but specifically to merge them across page boundaries (which is what the original issue looks to be about).
> 
> I believe this can be done relatively easily if an assumption is made that two adjacent `optgroup` elements will not be sent with the same `label`. This may not be a safe assumption to make in general, but I would think that it's the most common case.
> 
> It seems like it should be assumed that the server side will provide a stable, consistent ordering of results and their grouping.
> 
> Without this change, paginating a grouped list can only be done if the groups are never broken across pages. This can be done with variable page sizes, assuming none of the groups are too large relative to the total option count, but that quickly becomes inefficient in the face of filtered query results.

It also can be solved by changing data format for example for second page answer can be presented like this:
```json
{
  "results" : [
    { 
      "text" : "group 1",
      "append_last_group" : true,
      "children" : [
        {
          "id" : "item31"
          "text" : "thirty-first item"
        }
      ]
    }
  ]
  "pagination" : {
    "more" : false
  }
}
```
or
```json
{
  "results" : [
    { 
      "text" : "group 1",
      "children" : [
        {
          "id" : "item31"
          "text" : "thirty-first item"
        }
      ]
    }
  ]
  "pagination" : {
    "more" : false,
    "append_last_group" : true
  }
}
```
In this case we don't need any assumptions because we can solve it by any side or backend or frontend.
Of course it make pagination feature much more difficult but for now we have only three bad solutions for this problem:
* removing optgroup for next page (wrong placement for nested options and in result wrong indentation of group elements)
* disable pagination for optgroups (can be solved only with access to backend and can produce performance problems for BIG groups)
* use empty label for same optgroup (create empty optgroup that still little visible in current select2 version).

For now we use third solution because we can't disable pagination and empty optgroup looks better than not groupped elements.

**Comment by Zigreal** [comment]
> For now we use third solution because we can't disable pagination and empty optgroup looks better than not groupped elements.

I like the third solution! I encourage the community to discuss this idea. Looks like the best option we have=)

**Comment by Zigreal** [comment]
The task was created in 2015, it's time to deal with it, colleagues)

**Comment by sadiqueilyas** [comment]
> I have a grouped select2 list that uses pagination to load 30 list items at a time. Each `<optgroup>` contains one or more `<option>` list items.
> 
> Feature request: an option group can cross the boundary of 30 items. When this happens, groups with the same labels at the page boundaries should be merged.
> 
> ## Example
> optgroup `group 1` contains 31 options, AJAX page size is 30.
> 
> ### AJAX Page 1
> ```js
> {
>   "results" : [
>     { 
>       "text" : "group 1"
>       "children" : [
>         {
>           "id" : "item1"
>           "text" : "first item"
>         },
>         {
>           "id" : "item2"
>           "text" : "second item"
>         },
>         // items 3 to 29 omitted for brevity
>         {
>           "id" : "item30"
>           "text" : "thirtied item"
>         }
>       ]
>     }
>   ]
>   "pagination" : {
>     "more" : true
>   }
> }
> ```
> 
> ### AJAX Page 2
> ```js
> {
>   "results" : [
>     { 
>       "text" : "group 1"
>       "children" : [
>         {
>           "id" : "item31"
>           "text" : "thirty-first item"
>         }
>       ]
>     }
>   ]
>   "pagination" : {
>     "more" : false
>   }
> }
> ```
> 
> ### Expected result
> The code should recognize that page 2 should be merged with page 1 instead of appended, because the group header is the same.
> 
> ```
> <optgroup label="group 1">
>     <option value="item1">first item</option>
>     <option value="item2">second item</option>
>     
>     <option value="item30">thirtied item</option>
>     <option value="item31">thirty-first item</option>
> </optgroup>
> ```
> 
> ### Actual result
> ```
> <optgroup label="group 1">
>     <option value="item1">first item</option>
>     <option value="item2">second item</option>
>     
>     <option value="item30">thirtied item</option>
> </optgroup>
> <optgroup label="group 1">
>     <option value="item31">thirty-first item</option>
> </optgroup>
> ```

Do we have a solution for this ?

Is this feature implememented in select2?

**Comment by gamesover** [comment]
Any solution yet? I met the exact the same issue for version 3.5.
The max pagination size is 10. But our children contains 11 items.

If below way
The page 1 API return `{text: category name, children: 10 items}`
If page 2 API returns `{text: category name, children: 1 item}`
The frontend will show 2 duplicated group name

if page 2 API returns `{item data}` directly, the last item in frontend will not show under group name

How to resolve it?

**Comment by esteban-lamanna** [comment]
Why is this issue closed?
I am facing the same problem as sliekens.
