### ISSUE TITLE
Change value or name with jquery after loading select2

### ISSUE THREAD

**Issue by GithubBjorn** [select2/select2#4011]
I cannot change a option value or name, with Jquery after i have loaded select2.

```
$('#mySelect').select2();
$(document).find('option[value="change me"]').text('Changed');
```

If i swap places with this two lines it works fine.
But in my project i cannot do this.

**Comment by kevin-brown** [comment]
Select2 will cache the value and text within an `<option>` after the dropdown is opened for the first time. This is mostly for performance reasons, as these don't change that often.

You can clear the cache by calling

```js
$().removeData('data');
```

On the jQuery element that you change the value/text of.

**Comment by kevin-brown** [comment]
I'm actually going to reopen this and mark it as a documentation issue, as this is going to become a common issue in the future.
