### ISSUE TITLE
Select2 4.0.1 Tags, Select On Close Issues

### ISSUE THREAD

**Issue by abstractcoder** [select2/select2#4012]
I'm using Select2 with a multiple select box, with tags and selectOnClose enabled. I'm running into these  issues.

Unable to delete the last selected item by clicking the x or by using the backspace key. This seems to be caused by enabling selectOnClose. The dropdown appears and closes when deleting a tag, which selects the item that has been deleted, re-selecting it.

Occasionally when editing a tag, whether by clicking on it or backspacing into it, the tag is duplicated. This is sporadic, and seems to be caused by enabling selectOnClose.

Unable to use arrows keys to bring up dropdown after adding a tag. This seems to be caused by enabling tags.

It's not possible to select an item in the list that is already selected, in order to un-select it. This seems to be caused by enabling selectOnClose.

Here is code that reproduces these issues http://jsfiddle.net/abstractcoder/mpwa9p57/

**Comment by devinfd** [comment]
I am experiencing exactly these same issues. In particular the "Unable to delete the last selected item by clicking the x or by using the backspace key" issue. Basically its not possible to remove all the tags if selectOnClose is true.

**Comment by dmdm22** [comment]
This fix for another issue (prevent dropdown from open on remove item) seems to fix the remove last item issue too:

`.on("select2:unselect", function (evt) {
if (!evt.params.originalEvent) {
   return;
}
   evt.params.originalEvent.stopPropagation();
}`

hope this helps ..
