### ISSUE TITLE
iOS Next/Previous Input Issue

### ISSUE THREAD

**Issue by abstractcoder** [select2/select2#4013]
I'm using Select 2 4.0.1. On iOS, with the Select2 input selected, using the Next/Previous buttons in the upper right hand corner of the keyboard properly moves to the next or previous input, but the Select2 dropdown doesn't close.

You can recreate this issue by visiting this link on an iOS device http://jsfiddle.net/abstractcoder/mpwa9p57/2/ , selecting the Select2 input, and tapping the next input button. The next input will gain focus but the Select2 dropdown will remain open and cover it up.

**Comment by kevin-brown** [comment]
I do not have an iOS device to test this with, but I suspect this has to do with the fact that we don't listen to the `blur` event, and iOS doesn't trigger the events that we are listening to for closing the dropdown.

**Comment by hachichaud** [comment]
@kevin-brown I'm having this issue (select2 not closing on iOS when tapping outside)
I tried with the examples from the website and it doesn't work either.
Note that it works in chrome simulator but not on a real iOS device.
Doesn't work for sure on iphone 6 with iOS 9
Do you have a recommendation or idea on how to fix this ?

**Comment by Landen13** [comment]
Will this be fixed soon?

**Comment by alexweissman** [comment]
#4536 claims to fix this, just needs some additional work before it can be merged.

**Comment by dham84** [comment]
@kevin-brown I'm having this issue with iOS devices. The fix committed in #4536 seems to solve the issue for me, too bad the PR was never fixed by the author of the issue.
Any plans on adding this fix soon?
Thanks!

**Comment by avnir** [comment]
@kevin-brown would this fix also fix the Done button on iOS devices? Currently clicking Done (the Done option is all the way on the right of the side of the keyboard, on the same line as the Prev / Next options).

Thank you

**Comment by avnir** [comment]
Hi @kevin-brown is there anything I can help you with on the iOS Next/Previous & Done Input issue, if you need help testing these on iOS or anything else, please don't hesitate to let me know.

Tested #4536 and that's only fixing the issue when users tap on the background or some other element on the page but that's not addressing the Next/Prev/Done Inputs.

Could really use the fix to this issue.

Thanks for your time and hard work
