### ISSUE TITLE
select2 not auto-focus after tabbing

### ISSUE THREAD

**Issue by phamvuau** [select2/select2#4015]
I'm using select2 3.5.4 to create tagging feature for my project. When I tab to select an item in the dropdown list, the select2 will not focus on the input box but focus to the next element instead. Is there any option to archive the behaviour of auto-focusing after tab? Currently I have to use "killEvent(e);" at the line 2974 to make the auto-focus work.

**Comment by pedrofurtado** [comment]
Sorry, the `3.x` version is not maintained anymore. But fell free to fork the repo and fixes what you need.
