### ISSUE TITLE
Tag cannot be selected, but existing options can

### ISSUE THREAD

**Issue by nyxz** [select2/select2#4017]
I'm using the ajax to load the data + the *tags* option enabled so the user can add values. Here is the setup: http://plnkr.co/edit/CrP5r0I4X7LcTQZB7oXy?p=preview 

I have custom *createTag* function in order to append " (new)" to the tag if it is not found in the returned result.

The thing is the tag doesn't get selected the first time if it is new. Say in the provided setup I input "baz" I will get the suggestion "baz (new)" and then if I select it nothing happens - the select stays empty. Then I open the selection again I get the list of existing values and select one of them. Then reenter the "baz" again and select the "baz (new)" it gets selected in the box. What I would expect is the new value to get selected the first time.

**Comment by kevin-brown** [comment]
I suspect this has to do with the fact that you aren't including an `<option>` for the placeholder, which can cause any number of strange, inconsistent errors. When I include the empty `<option>` for the placeholder, I can't reproduce the issue at all.

**Comment by nyxz** [comment]
Including the empty <option> does help! Didn't know I should add it. Thanks a lot!
