### ISSUE TITLE
Matcher compatibility issue

### ISSUE THREAD

**Issue by donpro2** [select2/select2#4018]
Hi,

Since the matcher parameter has changed how it works, I am using the compatibility code so that it works similar to 3,5x.

Intermittently, the select2 does not bind to the select object and I get the following JS error:

Error: ReferenceError: matchStart is not defined

I have added the matchStart function to a separate JS file which I load after the <head> tag each time a page is loaded.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by donpro2** [comment]
Thanks but I found the error; it was not an issue with the Select2 library.
