### ISSUE TITLE
How to prevent special characters in select2? 

### ISSUE THREAD

**Issue by sampatbadhe** [select2/select2#4023]
I wanted to prevent `[ ]!@#$%^&*(){}` this characters to entered in select2 to add as custom tag.

Is there any way to Prevent special characters to be entered in select2?

**Comment by kevin-brown** [comment]
You can override the default behaviour of creating tags for everything by overriding `createTag` to return `null` when the tag cannot be created.

I'm going to leave this ticket open so I remember to actually document that option.

**Comment by sampatbadhe** [comment]
:+1: 
Thanks @kevin-brown

**Comment by kevin-brown** [comment]
This has been documented in https://select2.org/tagging#constraining-tag-creation so I'm dropping this from the milestone.
