### ISSUE TITLE
createSearchChoice replacement (createTag) doesn't seem to work with single-choice selects

### ISSUE THREAD

**Issue by melinath** [select2/select2#4029]
I'm trying to have a searchable single-choice select that allows people to enter arbitrary content if there's no match, but I can't find a way to make this work. Since the documentation is so scattered, it's possible I'm missing something? Or maybe this is a bug.

Select2 version: 4.0.1-rc.1

**Comment by kevin-brown** [comment]
`createTag` should work if you have tags enabled (set `tags: true` during initialization). If this doesn't solve the issue, reply back and I can reopen this ticket.

Note that `tags` was not required in Select2 3.5.x, even though it actually should have been,

**Comment by melinath** [comment]
Adding tags: true does not fix my problem, no. Tags.prototype.query isn't even being run.

I've worked around this problem using the following monkeypatch:

```
        var DIACRITICS = $.fn.select2.amd.require('select2/diacritics');
        var stripDiacritics = function stripDiacritics (text) {
            // Used 'uni range + named function' from http://jsperf.com/diacritics/18
            function match(a) {
                return DIACRITICS[a] || a;
            }

            return text.replace(/[^\u0000-\u007E]/g, match);
        }

        // override InputData.query & InputData.current because GRAH
        var InputData = $.fn.select2.amd.require('select2/compat/inputData');
        InputData.prototype.query = function (_, params, callback) {
            var results = [];

            var termSeen = false,
                term = params.term ? params.term : this.$element.val();

            for (var d = 0; d < this._currentData.length; d++) {
                var data = this._currentData[d];

                var matches = this.matches(params, data);

                if (matches !== null) {
                    results.push(matches);

                    if (stripDiacritics(data.text).toUpperCase() === stripDiacritics(term).toUpperCase()) {
                        termSeen = true;
                    }
                }
            }

            if (!termSeen) {
                results = [{id: term, text: term, selected: true}].concat(results);
            }

            callback({
                results: results
            });
        };

        InputData.prototype.current = function (_, callback) {
            var value = this.$element.val(),
                data;

            for (var d = 0; d < this._currentData.length; d++) {
                data = this._currentData[d];

                if (value === data.text) {
                    callback([data]);
                    return;
                }
            }

            data = {id: value, text: value, selected: true};

            callback([data]);
        };
```

**Comment by kevin-brown** [comment]
Note that it's [a known issue](https://github.com/select2/select2/issues/3294) that `<input />` tags are not properly supported, we're aiming for [improved support in 4.1.0](https://github.com/select2/select2/issues/3722).

**Comment by cklab** [comment]
I see this problem (new tag in a single select not selected) using a `<select>` and AJAX. Seems to work w/o AJAX. See: https://jsfiddle.net/8emxb49o/

Any suggestions?

**Comment by kevin-brown** [comment]
> Any suggestions?

This looks like a separate bug, can you create a new ticket about it?

**Comment by cklab** [comment]
Since that post, I've come across issue #4017 , suggesting to add an empty `<option>` tag. This seems to solve the issue: https://jsfiddle.net/8emxb49o/1/

I take it this is a case of missing documentation rather than a bug?

**Comment by kevin-brown** [comment]
> I take it this is a case of missing documentation rather than a bug?

That ticket required a blank option because it used `placeholder`, which requires it. There's actually now a ticket for your issue at https://github.com/select2/select2/issues/4104, it appears that someone else ran into the problem.
