### ISSUE TITLE
Odd behaviour in Firefox on MAC

### ISSUE THREAD

**Issue by donpro2** [select2/select2#4033]
Hi,

I have noticed this behavior on a mac when using Firefox; is there a minimum version of the browser that supports select2?

See the attached image. I select the Destination drop-down and start to type in the search box.

![firefoxmac](https://cloud.githubusercontent.com/assets/7718345/11858279/2368d58a-a42e-11e5-80a3-9d61c7e50998.png)

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by donpro2** [comment]
1. What steps can be used to reproduce the issue?
Choose a dropdown option.  Select using enter. The input box for select2 is displaced towards the top-left part of the screen (see screenshot above)

2. What is the bug and what is the expected outcome?
See the answer to (1). The expected outcome is the input box for select2 not to be displaced

3. What browser(s) and Operating System have you tested with?
The displacement issue occurs for the MAC Yosemite in Firefox 36.0

4. What version of jQuery are you using? And what version of Select2?
jQuery: 1.4.2
Select2: 4.01

5. Are you using Select2 with other plugins
http://sourceforge.net/projects/sarissa
http://stefangabos.ro/jquery/zebra-datepicker
http://kyleschaeffer.com/development/lightbox-jquery-css

**Comment by alexweissman** [comment]
This issue has been discussed elsewhere, and is solved by using `dropdownParent`.  See https://select2.org/dropdown#dropdown-placement
