### ISSUE TITLE
Programatically changing the value Ajax Select2 does not update visually

### ISSUE THREAD

**Issue by Glutnix** [select2/select2#4034]
https://jsfiddle.net/Glutnix/ut6xLnuq/

If I have a working AJAX select box, and I can pick options from the response, but try to change the value of the select2 programmatically, the value changes but select2 does not show the label.

**Comment by kevin-brown** [comment]
`select2('data')` is no longer a setter in Select2 4.0.0, so that call is doing nothing.

The issue is that your templating methods are not falling back to `text` if `email` is not specified. The data objects being passed in should have the text of the `<option>` tag in the `text` property.

**Comment by Glutnix** [comment]
Aha! Thanks so much! [Working Fiddle](https://jsfiddle.net/Glutnix/7990vbtu/)

Okay, so the issue here is documentation. That wasn't exactly well documented anywhere.
