### ISSUE TITLE
Switching language at runtime.

### ISSUE THREAD

**Issue by crystalbyte** [select2/select2#4038]
Hey,

I am currently working on a localized single page application using angular2.
Is there a way to switch the language of select2 without reinitializing the control ?
Any help would be greatly appreciated.

Alex

**Comment by kevin-brown** [comment]
Select2 does not support the ability to change options dynamically, so it is not possible to change the language without reinitializing Select2.

This is a duplicate of https://github.com/select2/select2/issues/2830#issuecomment-74971872.

**Comment by crystalbyte** [comment]
Thanks, is there anything we need to take care of before reinitializing the control, any cleanup ?

**Comment by kevin-brown** [comment]
You can cleanly destroy Select2 by calling `select2('destroy')`. You likely won't see any issues from there unless you are using the `data` option, which will recreate the options.
