### ISSUE TITLE
Npm lacks some versions

### ISSUE THREAD

**Issue by RobertDiebels** [select2/select2#4040]
I wanted to update from 3.5.1 to 3.5.4 but 3.5.4 is not in the npm version list. This is the complete list when viewing the versions of select 2 on NPM.

[ '3.4.3',
  '3.4.5',
  '3.5.1-browserify',
  '3.5.1-browserify-fix',
  '3.5.1',
  '3.5.2-browserify',
  '4.0.0',
  '4.0.1' ]

Could you update the versions for npm?

**Comment by kevin-brown** [comment]
NPM was not officially supported by Select2 until 4.0.0 (that's when I was finally given access), so as a result only Select2 4.0.0 and up are guaranteed to be on NPM.

I honestly have no idea what would be required to push the other ones up (and maybe even browserify them) if I wanted to.

**Comment by RobertDiebels** [comment]
@kevin-brown Ah that's a shame. I'll just migrate to 4.0.1.  Thanks for the reply though!

**Comment by RobertDiebels** [comment]
@kevin-brown I'll close the issue (unless there are plans to add some versions to NPM, can always re-open).

**Comment by guiwoda** [comment]
@kevin-brown is there any chance to push, at least the 3.5.x tags?
I'm migrating an old project from bower to npm, and I don't want to change the code, I just need to download the exact same version.

Thanks!

**Comment by toxaq** [comment]
Same as @guiwoda the last in the 3.5 series would make bower to npm migrations less of a headache.

**Comment by yurikilian** [comment]
Same here

**Comment by antennaio** [comment]
Same here, it would be great to have the last versions in the 3.5 series on NPM.
