### ISSUE TITLE
Multiselect unselect by ENTER

### ISSUE THREAD

**Issue by babielvs** [select2/select2#4048]
You can tab-navigate to a multiselect and select items by pressing Enter, but you can´t unselect the item by pressing Enter again.

https://select2.github.io/examples.html#multiple
Version: 4.0.1-rc.1

**Comment by kevin-brown** [comment]
This used to happen, but it ended up creating odd and non-intuitive behaviour when using the enter key. You could completely clear a multiselect by holding the enter key, which is definitely not what anyone expects.

See the following commit and ticket for more information on why we no longer unselect on enter.

- https://github.com/select2/select2/commit/017c20109471fa5b835603faf5dc37f7c2c2ea45
- https://github.com/select2/select2/issues/3036

**Comment by babielvs** [comment]
Thank you for quick response, most of our Government customers expect this behavior, because this is important for the accessibility test (at least in Germany). Well anyway thanks for your reply.

**Comment by sebpet** [comment]
@babielvs Have you found a solution for unselecting by Enter with select2 v4.0.x ?
