### ISSUE TITLE
Very rapid keyboard interaction can "crash" a Select2 field

### ISSUE THREAD

**Issue by mcavalletto** [select2/select2#4049]
When typing very quickly in a select2 search field, it is possible to get "stuck" with a Select2 instance that has "Searching..." visible at the top of the select list but is no longer responsive.

A JavaScript stack trace (below) shows that the exception occurs when setClasses is called from within handleSearch, but there is no data defined for the visible result option.

Eg, in a page containing a single select2 instance, when this problem has been triggered, this expression evaluates to undefined:
  `$.data( $('.select2-results__option[aria-selected]').get(0), 'data' )`

Once this problem is triggered, it seems impossible to recover -- you can type into the search field, but the result list never updates and clicking on the result options has no effect other than logging additional exceptions to the console.

If there are other Select2 instances on the same page, they are unaffected and continue to function normally.

This doesn't happen in typical usage, but I was specifically testing the response to very rapid keyboard interaction to confirm that a problem our users had reported with Chosen.js was not present with Select2.js -- thankfully it isn't, but I did accidentally discover this other problem along the way.

Expected behavior: no combination of keystrokes should cause the select2 instance to get permanently stuck.

Seen in a multi-select instance; unknown whether it also affects single-selects.

First seen on our custom application pages, using Select2 4.0.1, jQuery 1.9.1.

Reproduced on the Select2 examples page, using Select2 4.0.1, jQuery 1.11.2.
  https://select2.github.io/examples.html#multiple

Reproduced by tabbing/clicking into the example for "Multiple select boxes" and then repeatedly hitting the "a" and "tab" keys in very rapid succession to start and interrupt searching. It can take a a couple of minutes / a few hundred key strokes to trigger the problem, but sometimes it happens sooner.

Seen in Safari 9.0.2 on Mac OS 10.9.5; unknown whether it also affects other browsers.

Browser console JavaScript stack trace:

```
[Error] TypeError: undefined is not an object (evaluating 'item.id')  select2.full.js:862
(anonymous function) select2.full.js:861
each jquery.min.js:125
each jquery.min.js:26
(anonymous function) select2.full.js:855
current select2.full.js:3020
setClasses select2.full.js:847
(anonymous function) select2.full.js:1029
invoke select2.full.js:622
trigger select2.full.js:612
trigger select2.full.js:5320
(anonymous function) select2.full.js:5215
invoke select2.full.js:622
trigger select2.full.js:612
trigger select2.full.js:5320
(anonymous function) select2.full.js:5170
invoke select2.full.js:622
trigger select2.full.js:616
handleSearch select2.full.js:1986
(anonymous function) select2.full.js:579
(anonymous function) select2.full.js:1943
dispatch jquery.min.js:337
handle jquery.min.js:207:662
```

**Comment by crebbo** [comment]
I seem to be getting this also
