### ISSUE TITLE
Responsive width examples on 4.0 examples page don't work

### ISSUE THREAD

**Issue by mcavalletto** [select2/select2#4050]
The examples of "Responsive design" on the 4.0 examples page do not work:
  https://select2.github.io/examples.html#responsive

There are two examples there, one with a `<select>` of `style="width: 50%"` and the other at `75%`. 

The associated text indicates the Select2 boxes should appear at the same percentage widths.

However, they both appear full width, with the corresponding `select2-container` divs having `style="width: 100%"`.

Same results seen in Safari 9.0.2, Chrome 47.0.2526.106, and Firefox 43.0.3, all on Mac OS X 10.9.5.

**Comment by kevin-brown** [comment]
As noted in https://github.com/select2/select2/commit/63d531a9c0ab51f05327492a56f3245777762b45, this was just a documentation issue and was not actually a bug in how Select2 handles parsing of the `style` tag.
