### ISSUE TITLE
Not able to select element with id 0

### ISSUE THREAD

**Issue by AnirudhaGohokar** [select2/select2#4052]
Am not able to select element which has an id set as 0.
Though am able to select elements with id > 0
Here's a [jsfiddle](http://jsfiddle.net/mdb13b5d/) for reference. 

I think its being being used to show "Searching" element which is by default disabled. Can this be changed?

**Comment by kevin-brown** [comment]
This has to do with your id being `0` and not `"0"` (notice the quote difference). Converting the id to a string fixes the issue.

https://jsfiddle.net/mdb13b5d/1/

This has to do with how Select2 compares ids in non-local results, and the fact that a standard `<select>` expects all ids to be strings.

**Comment by AnirudhaGohokar** [comment]
Thanks Kevin..
This has resolved the issue.

**Comment by kevin-brown** [comment]
I'm going to keep this open as a documentation issue, as this question has come up in the past.
