### ISSUE TITLE
Select2 v3.5 jquery show() issue

### ISSUE THREAD

**Issue by delta1186** [select2/select2#4053]
I would recommend using .css("display", "") on lines 877 and 844 instead of .show().  The show method adds a display:block to the select2-container which is being done to remove the display:none that is added by the .hide that is called in a few direction places.

![capture](https://cloud.githubusercontent.com/assets/421307/12051122/73163f64-aec4-11e5-8840-c4e76c9380d8.PNG)

The display:block on the select2-container does not play nice with using the select2-bootstrap.css and input-groups.  The .input-group use a display:table layout and so when the inline display:block is added it causes the div to overflow other divs.

**Comment by pedrofurtado** [comment]
Sorry, the `3.x` version is not maintained anymore. But fell free to fork the repo and fixes what you need.
