### ISSUE TITLE
Selection dropdown does not disappear after selection on iPhone 6

### ISSUE THREAD

**Issue by lukepolo** [select2/select2#4056]
When you select a dropdown it does not disspear

![image](https://cloud.githubusercontent.com/assets/2066668/12065301/c7b6b632-afa2-11e5-99ad-eb11d9e8905c.png)

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by lukepolo** [comment]
It cannot be reproduced on the examples page. Im going to assume its an issue with what we are doing with it, ill report back when I find the issue.

**Comment by jason69** [comment]
Hi, I experience the same on Chrome on an android device.
I am using ajax to retrieve data.
1) Click on the select field
2) Enter data
3) Wait for ajax completion
4) Select an option in the select field
5) *** Select should close with the selected value *** but remain in position
6) I have to click an other time on the option to make it close

Please note that on desktop side (Chrome or firefox) it works perfectly. The bug is on mobile device only.

Here is the markup:
<select required id="tier2" name="tier2">
</select>

$('#tier2').select2({
			placeholder: "Enter name",
			minimumInputLength: 3,
			ajax: {
				url: "myAjaxUrl",
				dataType: "json",
			    delay: 250,
			    data: function (params) {
			      return {
			        q: params.term,
			        page: params.page
			      };
			    },
			    processResults: function (data, page) {
			      return {
			        results: data.items
			      };
			    },
			    cache: true,
			},
});

**Comment by jason69** [comment]
NB: this is 100% reproductible on the demo page, in the "Loading remote data' section

**Comment by lukepolo** [comment]
Thanks for finding it how its reproducible

**Comment by kevin-brown** [comment]
Is this only an issue in the AJAX example on the examples page? I'm trying to narrow the scope for this ticket as much as possible, so I can try to figure out what might be wrong.

**Comment by jason69** [comment]
Hi,
this seems to happens only on AJAX example...

**Comment by lukepolo** [comment]
Yes, it seems to be only when ajax is used.

**Comment by redmile** [comment]
Hello :)
Is there a workaround to temporarily solve this problem? Or a way to disable select2 on mobile devices? Thank You in advance

**Comment by jason69** [comment]
Hi,
can you remove "needs information" tag?
or do you need additionnal feedback?
But as it is reproductible on example page, I guess it should be enough...
