### ISSUE TITLE
The dropdown displace problem

### ISSUE THREAD

**Issue by livem** [select2/select2#4058]
By default, Select2 will attach the dropdown to the end of the body and will absolutely position it to appear below the selection container.

When **body** has the css property : 
```css
body {
    margin-left: 25px;
}
```
 the problem blew:

![dropdown](https://cloud.githubusercontent.com/assets/2949746/12088342/3c00385e-b315-11e5-9e73-63e89ad14569.png)

**I do not want to modify the body css**, what can I do for this ?

select2 version : **select2-4.0.1**
Browser : **Chrome 43.0.2357.134**

Thanks for your time.:smile:

**Comment by livem** [comment]
Same as  #3970

**Comment by kevin-brown** [comment]
This is a known problem that is fixed in the upcoming 4.0.2-rc.1, https://github.com/select2/select2/issues/3970.

**Comment by andregoncalvesdev** [comment]
change the margin to padding.
