### ISSUE TITLE
Dropdown not closing when using custom adapter

### ISSUE THREAD

**Issue by Badestrand** [select2/select2#4063]
Hey

I created my box with

```
$('select').select2()
```

. To style the dropdown, I specified `containerCssClass` in the options,

```
*$('select').select2({
    containerCssClass: 'select2-side-services-phone-time'
});
```

but the dropdown does not receive the class for some reason, also the console shows no error. Next try was to change the dropdown attachment to the container instead of the body which was really a hassle

```
$.fn.select2.amd.require([
    "select2/utils",
    "select2/dropdown",
    "select2/dropdown/attachContainer"
], function (Utils, DropdownAdapter, AttachContainer) {
    $('select').select2({
        dropdownAdapter: Utils.Decorate(DropdownAdapter, AttachContainer)
    });
});
```

. The dropdown now is created in place and I can style it accordingly but it does not close anymore. Not with the escape key, not when losing focus, not when chosing an item. Adding the option `closeOnSelect: true` did not help as well.

Any idea what I am doing wrong?

**Comment by kevin-brown** [comment]
`containerCssClass` is for the selection container. It sounds like you are looking for `dropdownCssClass`.

**Comment by Badestrand** [comment]
Thank you very much, that works! Stupid mistake...

But do you have an idea about the container not closing in the latter example?

**Comment by kevin-brown** [comment]
I'm going to re-focus this ticket on the second issue. It'd be useful if you could reproduce the issue in a jsbin or jsfiddle, as that would remove any external variables.

**Comment by Badestrand** [comment]
Unstyled, but does (not) work as expected ;) https://jsbin.com/duqoxagufa/edit?html,output

**Comment by kevin-brown** [comment]
So, I completely forgot that `closeOnSelect` is an option, and as a result you need the decorator for it as well.

https://jsbin.com/xayecomasi/1/edit?html,output

Still isn't working as expected with the `CloseOnSelect` decorator.

**Comment by digitalsounds** [comment]
I've managed to make this work using the following code:

`$.fn.select2.amd.require([
            "select2/utils",
            "select2/dropdown",
            "select2/dropdown/attachContainer",
            "select2/dropdown/search",
            "select2/dropdown/closeOnSelect"
        ], function (Utils, DropdownAdapter, AttachContainer, DropdownSearch, CloseOnSelect) {
            MyCustomAdapter = Utils.Decorate(
                Utils.Decorate(
                    Utils.Decorate(
                        DropdownAdapter,
                        DropdownSearch
                    ),
                    AttachContainer
                ),
                CloseOnSelect
            );
            
            $('select').select2({
                dropdownAdapter: MyCustomAdapter
            });
        });`

**Comment by videsignz** [comment]
@digitalsounds Dude, you are a life saver. I was just struggling with the closeOnSelect being attached to the container. It would work as is but I would lose the search decorator, or vice versa depending on the order I would call them.

Here is my final setup, with your helper code...notice the select initialization is separate for more portability.

```js
$.fn.select2.amd.define('select2/customDropdownAdapter', [
  "select2/utils",
  "select2/dropdown",  
  "select2/dropdown/closeOnSelect",
  "select2/dropdown/attachContainer",
  "select2/dropdown/search",
], function (Utils, DropdownAdapter, CloseOnSelect, AttachContainer, DropdownSearch) {
	
	var CustomAdapter = Utils.Decorate(		
		Utils.Decorate(
			Utils.Decorate(
			DropdownAdapter,
			DropdownSearch	
			),
			AttachContainer			
		),
		CloseOnSelect
	);
    
	return CustomAdapter; 
 
});

var CustomAdapter = $.fn.select2.amd.require('select2/customDropdownAdapter');

$('select').select2({
	dropdownAdapter: CustomAdapter
}); 
```

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:

**Comment by H-L** [comment]
I had some issues as well when adding too much decorators in Utils.Decorator().

e.g. If you want to have custom rendered element inside the dropdown and both `MinimumResultsForSearch` and `CloseOnSelect` working correctly, you have to use Utils.Decorator() for each decorator :

```js
$.fn.select2.amd.require("DropdownWithHeader", [
        "select2/utils",
        "select2/dropdown",
        "select2/dropdown/search",
        "select2/dropdown/minimumResultsForSearch",
        "select2/dropdown/closeOnSelect",
        "select2/dropdown/attachBody",
        "select2/dropdown/attachContainer",
    ],
    function(Utils, Dropdown, Search, MinimumResultsForSearch, CloseOnSelect, AttachBody, AttachContainer) {
        let dropDownWithSearch = Utils.Decorate(Dropdown, Search, AttachBody);

        let dropDownWithHeader = Utils.Decorate(dropDownWithSearch, AttachContainer);

        dropDownWithHeader.prototype.render = function () {
            let $container = $('<span></span>');
            let $dropdown = dropDownWithSearch.prototype.render.call(this);
            let headerTitle = this.options.options.headerTitle ? this.options.options.headerTitle : "Select an option";

            let $header = $('<span class="select2-custom-header">' +
                        '<span class="select2-custom-header__title">'+ headerTitle +'</span>' +
                        '<span class="select2-custom-header__close"></span>' +
                        '</span>');

            $dropdown.prepend($header);
            $container.append($dropdown);

            this.$dropdownContainer = $container;

            return $container;
        };
        // CloseOnSelect will not work
        // dropDownWithHeader = Utils.Decorate(dropDownWithHeader, MinimumResultsForSearch, CloseOnSelect);

        // MinimumResultsForSearch will not work
        // dropDownWithHeader = Utils.Decorate(dropDownWithHeader, CloseOnSelect, MinimumResultsForSearch);

        // CloseOnSelect and MinimumResultsForSearch will both work 
        dropDownWithHeader = Utils.Decorate(dropDownWithHeader, MinimumResultsForSearch);
        dropDownWithHeader = Utils.Decorate(dropDownWithHeader, CloseOnSelect);
        return dropDownWithHeader;
    }
);
```
Idk if I have to report it as a bug, since it seems to work implementing decorators one by one 🤔
