### ISSUE TITLE
Uncaught Error: No select2/compat/inputData

### ISSUE THREAD

**Issue by Bsheghembe** [select2/select2#4064]
Get the above error every time I try to load select 2 on my site

**Comment by kevin-brown** [comment]
[You need to use the full build of Select2.](http://stackoverflow.com/q/30235909/359284#30238790)

**Comment by gitanupam** [comment]
Thanks - using the full version worked for me.

For the standard (non-full) version, the doc says `This is the build that most people should be using for Select2. It includes the most commonly used features.`

but I am just trying to use a simple multiple select box. So wanted to check if multiple select box can be used only with the full build?
