### ISSUE TITLE
Certain Android Devices firing "keyup input" event on dropdown selection

### ISSUE THREAD

**Issue by sellds4** [select2/select2#4065]
"keyup input" event fires causing "Searching" to appear for a brief moment prior to the click on the selected item is fired.  Due to this, the item ABOVE the one being clicked is selected because "Searching" pushes the items down.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by sellds4** [comment]
##### What steps can be used to reproduce the issue?
Set up a select2 box with remote data. View dropdown on an Android device.  When clicking on an item in the dropdown list, the item above the item touched (clicked) is selected per the above reasons.

##### What is the bug and what is the expected outcome?
Wrong item is selected, item above item that is clicked.

##### What browser(s) and Operating System have you tested with?
Bug has been viewed on Android 6.0.1 (Nexus), Android 5.1.1 (Samsung)

##### Does the bug happen consistently across all tested browsers?
No, other Android 5.1.1 have not shown the bug.

##### What version of jQuery are you using? And what version of Select2?
JQuery v2.1.3, Select2 v4.0.1

##### Are you using Select2 with other plugins?
None with the dropdown

**Comment by kevin-brown** [comment]
I'm assuming this is happening in Chrome on these devices?

And does it happen on the [examples page](https://select2.github.io/examples.html)?

**Comment by sellds4** [comment]
Yes, on Chrome.  Happens on the examples page, but not every time.

**Comment by sellds4** [comment]
Just an FYI, I viewed it on a Samsung Galaxy S6 with 5.1.1

**Comment by jason69** [comment]
This happens to me too, on an android device, and I think it is related to #4056

**Comment by jasminallaire** [comment]
This bug seem to be only if the auto-completion is activate on the android device. If you deactivate this feature it works fine...

**Comment by kevin-brown** [comment]
This appears to be a duplicate of https://github.com/select2/select2/issues/5457.
