### ISSUE TITLE
Changing search text value dynamically shows correct text  in search option but when selecting the option its taking the old option text.This is of type select2 remote data source

### ISSUE THREAD

**Issue by prafulla-samal** [select2/select2#4071]
its in Select2 4.0.0 version.
1. Search “123”
2. Backend returns “{id:’123’,value:”this is 123”}”;
3. Anything else in the app (not in the search page) updates the db
4. Now search “123”
5. It shows “123: ‘this is new 123’”
6. But when we click on this option
7. The text that appears in select2 remains “this is 123”

This is because select2 adds <option>s to the select and if something which matches the an old selected value it’s simply shown with old optionText instead of creating a new <option> everytime a search-result is selected.

**Comment by MrBreZe** [comment]
i came across this issue today in my project, a very confusing issue. i can reproduce it with these 7 steps.
