### ISSUE TITLE
Search box width is insufficient for full-width characters (such as Chinese)

### ISSUE THREAD

**Issue by zhujun24** [select2/select2#4074]
[Tagging support](http://select2.github.io/examples.html#tags)

when input.value.length increase, the input.width increase **0.75em** per input.value.length, if we input a   **half-width character**, the width is **less than 0.75em**, and input a **full-width character**,the width is **more than 0.75em**, so it cause a style problem **input.width is not equal to input.value width**

And I think [jQuery-autoGrowInput](https://github.com/Pixabay/jQuery-autoGrowInput) is a good solution

**Comment by eddieklc** [comment]
input.width is CSS property of width of an element in pixels.
input.value.lenght is the number of characters in the input field.

I can't see how are those two connected, thus, what's the issue here?

**Comment by zhujun24** [comment]
In [Tagging support](http://select2.github.io/examples.html#tags)
When type character in this input, this width is **(input.value.length + 1) * 0.75em**, for example:
input.value is empty, it has a min-width 0.75em
![86394c93-f668-4126-97d4-084940ac98b4](https://cloud.githubusercontent.com/assets/7301773/12232575/cdc44174-b89a-11e5-9bb2-d4af8ad843f6.png)
type some half-width character
![27db0af2-fa8a-4c74-83d3-c9774da8dbfe](https://cloud.githubusercontent.com/assets/7301773/12232602/fbe15fce-b89a-11e5-9b94-de9370b6438a.png)
type some full-width character
![4e5b39e2-d69a-4d11-829d-307d8f14d539](https://cloud.githubusercontent.com/assets/7301773/12232615/081ad194-b89b-11e5-8704-4fe69b42d6af.png)
I think it must be a function to set input.width according to input.value, just like (input.value.length + 1) * 0.75em, But we can find that the calculated width isn't equal to input.value display width by review element.

**Comment by eddieklc** [comment]
Yes it is equal and that has nothing to do with "half-width" characters.

By the formula (input.value.length + 1) * 0.75em, in your first example you have
(111111).length = 6, (6+1)*0,75 = 5,25
and in second example
(xxxx).length = 6, (4+1)*0,75 = 3,75 (xxxx is for your characters that i don't have on my keyboard)
so the function works well.

**Comment by zhujun24** [comment]
for "half-width" characters, calculated width is large than input.value display width, when type more  "half-width" characters, the difference is more and more large

for "full-width" characters, calculated width is less than input.value display width, when type more  "full-width" characters, the difference is more and more large

I think 0.75em is width than a "half-width" character width, and  0.75em is narrow than a "full-width" character width, you can type some Chinese character to test it! 

You can copy it: 你好，欢迎讨论这个问题

**Comment by eddieklc** [comment]
Well, potentially I see the resolution to your problem: try using pixels instead of ems :)

**Comment by zhujun24** [comment]
You can see here [jQuery-autoGrowInput](https://github.com/Pixabay/jQuery-autoGrowInput)
and i try it here [My Demo](https://github.com/zhujun24/select/blob/select2/input.html)
Whatever "half-width" character or "full-width" character, the width is always exactly

**Comment by eddieklc** [comment]
Take a look at this baby ;)
https://goodies.pixabay.com/jquery/auto-grow-input/jquery.auto-grow-input.js

**Comment by zhujun24** [comment]
I have simplify it like this :)

    var inputAutoWidth = function (input, restWidth) {
        var input = $(input);
        var span = $('<span/>').css({
            display: 'none',
            fontSize: input.css('fontSize'),
            fontFamily: input.css('fontFamily')
        }).appendTo('body');
        span.html(input.val().replace(/&/g, '&amp;').replace(/\s/g, '&nbsp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'));
        input.width(span.width() + (restWidth || 0));
        span.remove();
    };

**Comment by eddieklc** [comment]
Does it work now?

**Comment by zhujun24** [comment]
[Click Here](https://github.com/zhujun24/select/blob/select2/input.html)

**Comment by kevin-brown** [comment]
This is the expected behaviour, and it has to do with Select2 assuming that most of the time people will be typing in half-width characters. It starts to fail when people are consistently entering full-width characters.

I'd rather not have to size the text every time a new character is entered, as that ends up having sizing issues if there are different fonts used around the website (which is why we use `em` instead of `px` here).

**Comment by zhujun24** [comment]
I think copy input value to a element, and set them have same fonts style, It will guarantee that search box width match the character width exactly.

**Comment by kevin-brown** [comment]
Leaving this open for another stale cycle. Maybe there's a way to count the number of full-width characters and do a more intelligent estimate on the width of the search box?
