### ISSUE TITLE
How select2 4.x get the select value?? 

### ISSUE THREAD

**Issue by Joannzhou** [select2/select2#4080]
I saw the on-line doc Programmatic Access, it can get the selected value, but the version of the source code is 3.5.3, I download the lateset version 4.0.1, it has no function name of "val", Why???

**Comment by kevin-brown** [comment]
You should be able to get the value by using the [`.val()` method](https://api.jquery.com/val/) provided by jQuery.

https://select2.github.io/examples.html#programmatic
