### ISSUE TITLE
arrow keys don't change selection when tabbing to an input

### ISSUE THREAD

**Issue by phazei** [select2/select2#4081]
As can be seen at http://select2.github.io/examples.html

When tabbing through the screen to the first select box that doesn't have select2, you can then hit up/down and cycle through the options.  If you tab to the second one, the first on the page that has select2, up and down while it's focused only scrolls the page up and down.  It should open the option list and let you key through it.

On multiple select boxes tabbing and using the arrows opens the option list.

**Comment by phazei** [comment]
Closing as duplicate of https://github.com/select2/select2/issues/3472

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/select2/select2/issues/3472. Multiple selects don't have a preexisting key binding for the arrow keys, so we are currently making it open the dropdown. Single selections do though.
