### ISSUE TITLE
4.0.1 Archive contains old code

### ISSUE THREAD

**Issue by jBernz** [select2/select2#4082]
This issue started with me running into the positioning bug with nonstatic dropdown parents. However I realized this was fixed in the 4.0.1 patch. When I download the latest version with bower from https://github.com/ivaynberg/select2/archive/4.0.1.tar.gz the code still has the bug. The line I'm using to determine it is out of date is in attachbody.js.

What is 

     // For statically positoned elements, we need to get the element
     // that is determining the offset
        if ($offsetParent.css('position') === 'static') {
          $offsetParent = $offsetParent.offsetParent();

in the current repo is still     

    // Fix positioning with static parents
        if (this.$dropdownParent[0].style.position !== 'static') {
          var parentOffset = this.$dropdownParent.offset();

when I download.

**Comment by kevin-brown** [comment]
The issue you were seeing was only partially fixed in the 4.0.1 update. The archive is based on the 4.0.1 tag, which doesn't reflect the state of the `master` branch (used for development).
