### ISSUE TITLE
If no results are found the loading message is not removed

### ISSUE THREAD

**Issue by WilsonChiang** [select2/select2#4085]
When doing a search, if no results are found, the loading message is not removed.

![Example]
(https://i.gyazo.com/18bda203efcda312319173e4ce3195c6.png)

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by WilsonChiang** [comment]
What steps can be used to reproduce the issue?
Type a search term with no possible results. The loading more message will display despite it having fully loaded.

What is the bug and what is the expected outcome?
The "Loading More" text appears even if no results are found or all results have been loaded.

What browser(s) and Operating System have you tested with?
Tested this in OSX El Capitan, Chrome/Firefox

Does the bug happen consistently across all tested browsers?
Yes

What version of jQuery are you using? And what version of Select2?
Latest Select2 + jQuery 2.1.4

Are you using Select2 with other plugins?
Ember: 2.2.0, Ember Data: 2.3.1
