### ISSUE TITLE
Remove item bug

### ISSUE THREAD

**Issue by alexpts** [select2/select2#4090]
First click to `.select2-selection__choice__remove` not remove selected item. Second click remove item.
First click set prop "selected" to false in `InputData.prototype.unselect `. Second click remove item.

Example for reproduce: http://codepen.io/alexpts/pen/QyOyWm

It reproduce only `input` element. `Select` element work good.

OS: macos 10.11.2
Browser: chrome 47/ firefox 43
Select2 ver: 4
jQuery ver: 2

**Comment by kevin-brown** [comment]
Also merging this one into https://github.com/select2/select2/issues/3722.
