### ISSUE TITLE
Search box within select2 not working in Firefox

### ISSUE THREAD

**Issue by luisapuyen** [select2/select2#4091]
I've noticed that the select2 inputs are not working correctly in Firefox (OS: Linux). The select2 search box is not writable despite it's not specified as disabled nor readonly.

No problem with Chrome though.

You can check it out here in the code where we have this problem:
https://jsfiddle.net/luis_apuyen/9f3t5b5g/

In order to see it, open any of these tabs: 
1- "pedidos" / "presupuestos" / "albaranes" / "facturas", 
2- next click on "agregar", and a modal pops up, 
3- check the select input below "Transportistas", and the second to last. Both work in Chrome, but you won't be able to type anything in FF.

**Comment by kevin-brown** [comment]
This sounds like an issue with Bootstrap's modal stealing focus away.

Check out https://github.com/select2/select2/issues/600#issuecomment-102857595 for an easy fix.

**Comment by acarlstein** [comment]
I am having the same issue; however, I don't see an explanation related with the Bootstrap's modal stealing the focus away or how to solve it. Not sure why this issue was closed.

**Comment by theumar98** [comment]
**only remove tabindex="" from model**
<div id="stack1" class="modal fade" tabindex="" role="dialog" aria-hidden="true" data-focus-on="input:first">

**remove tabindex=""**
<div id="stack1" class="modal fade" role="dialog" aria-hidden="true" data-focus-on="input:first">

**Comment by alexweissman** [comment]
You should just be able to set `dropdownParent`: https://select2.org/troubleshooting/common-problems

**Comment by v10lador** [comment]
Check if your Jquery is the lastest and do the same for your select2.
i change my jquery to the 3.4.1 and it worked.

**Comment by kamleshwebtech** [comment]
> **only remove tabindex="" from model** div id="stack1" class="modal fade" tabindex="" role="dialog" aria-hidden="true" data-focus-on="input:first"
> 
> **remove tabindex=""** div id="stack1" class="modal fade" role="dialog" aria-hidden="true" data-focus-on="input:first"

Not worked in Firefox.
