### ISSUE TITLE
Multiple level optgroup.

### ISSUE THREAD

**Issue by dainis1994** [select2/select2#4098]
Hello!
Is it possible to create multiple level optgroup with select2?

**Comment by leandrogehlen** [comment]
related  #3866

**Comment by kevin-brown** [comment]
Yes, they are allowed. But you need to use AJAX to guarantee it.

See https://github.com/select2/select2/issues/3866 for issues with doing it using local data.

**Comment by leandrogehlen** [comment]
Following the links below, this doesn't possible
http://stackoverflow.com/questions/1037732/nesting-optgroups-in-a-dropdownlist-select
https://www.w3.org/TR/html401/interact/forms.html#h-17.6
