### ISSUE TITLE
Change position of dropdown results in DOM

### ISSUE THREAD

**Issue by babeuloula** [select2/select2#4102]
Hello, 

Is-it possible to append the dropdown results after the select2 and not in the body ?
I use bootstrap and it's hard to stylise the theme.

![capture](https://cloud.githubusercontent.com/assets/4849233/12475715/18a4c60a-c025-11e5-8af7-054cf90fe8cd.PNG)

Thanks

**Comment by kevin-brown** [comment]
Select2 has an optional `AttachContainer` decorator that does exactly what you are looking for.

_Unfortunately_ there is a bug with it that you're going to need to track with https://github.com/select2/select2/issues/4063. If you wrap your `<select>` with a `<span>`/`<div>`, you can also use the `dropdownParent` option to get (roughly) the same effect.
