### ISSUE TITLE
Fails to completely remove suggestion in tags mode

### ISSUE THREAD

**Issue by zxwild** [select2/select2#4104]
I found a bug which appears in tags mode, here is the example, it's quite easy
https://jsfiddle.net/xwild/ra3rsqpw/
1. click on this select2 instance
2. you'll see "No results found"
3. type "Test" and you'll see "Test" as only select dropdown item
4. press "backspace" until all of this will be removed
5. you'll see the strange letter "T", but input is empty
6. repeat with string "A new test"
7. when you'll remove this string, you'll see again "T" (not "A", and not expected "No results found" :)

**Comment by zxwild** [comment]
Actually I found how to solve it just after a posting this issue.
It's needed to add an empty <option> to select, and all is ok.
But it's a wrong behavior in general, and I think It should be fixed in the plugin

https://jsfiddle.net/xwild/ra3rsqpw/4/

**Comment by kevin-brown** [comment]
This is a bug involving how Select2 removes the automatically generated `<option>` elements for custom tags. The empty option only fixes the issue because it forces Select2 to redraw the results and remove the tag option.
