### ISSUE TITLE
Multiple select (checkboxes and/or toggleStates)

### ISSUE THREAD

**Issue by danjme** [select2/select2#411]
Is there any intention to incorporate a standard multiple select drop down with checkboxes / toggle states at any point? - Specifically like this -> http://www.erichynds.com/jquery/jquery-ui-multiselect-widget/

It would be nice to have as a core option without hacking around the formatting with injected checkboxes and custom event handlers to catch the behaviours needed with the current select2 library.

Cheers,
- D

**Comment by homer2** [comment]
Has this enhancement been implemented? I'm looking at Version 4.0.0-beta.3 and I don't see it.

**Comment by kevin-brown** [comment]
This is possible to do now by either styling selected options (`[aria-selected=true]`) or overriding the `resultsAdapter` and adding some more logic when rendering the results.

**Comment by dipti-s** [comment]
Has this enhancement been implemented? Can anyone tell how to use this enhancement.

**Comment by wasikuss** [comment]
Hi, take a look into this: http://jsfiddle.net/wasikuss/cg1zr4zd/
I know that functions called from `onSelect` won't work properly, but it is ok for simple usage :)

I'm going to finish this and make fully compatible plugin that adds new functions without altering default behaviour.

**Comment by Bruddles** [comment]
@kevin-brown are there any examples of overriding the resultsAdapter? I've looked in the Docs and the Forum but i can't see anything.

**Comment by alexandernst** [comment]
If this is still a thing, can this issue get reopened? And if not, can you clearly say so?

**Comment by kevin-brown** [comment]
Looks like you can get half way there without a custom adapter by just overriding the template for results.

http://jsbin.com/wezudobake/1/

**Comment by alexandernst** [comment]
Nice, but it would be great if we could get some extra features as

* grouping (category1 with some sub-elements, category2 with some sub-elements, etc..)
* selecting multiple sub-elements with a single click on their parent (group)
* (un)expanding groups (show/hide all sub-elements in a group)

Basically, something like [this](http://i.stack.imgur.com/tRtme.jpg)

**Comment by homer2** [comment]
@kevin-brown, in your example of overriding the template, if CloseOnSelect is set to false, clicking outside of the checkbox will select the item but not check the checkbox. 
http://jsbin.com/tifuzikimo/edit?html,js,output

Also, the templateSelection is still tag based. That is fine for a few items, but when dozens of items are selected it could be too much. Showing a summary instead would be nice, like "21 of 100 selected".

erichynds jquery-ui-multiselect-widget takes this idea a step further by showing either the selected items or the summary based on the number of item selected: "Alabama, Florida, Georgia" or "48 of 50 selected"

Anyway, I think @wasikuss's [example](http://jsfiddle.net/wasikuss/cg1zr4zd/) is the kind of functionality were looking for.

**Comment by PlippiePlop** [comment]
@homer2 the example from @wasikuss is a nice example but is not going to work on multiple select boxes on the page selected by a class. The code needs some alteration for multiple select boxes.

**Comment by wasikuss** [comment]
@PlippiePlop,
It also work on class-selected elements

http://jsfiddle.net/wasikuss/gx93rwnk/

**Comment by PlippiePlop** [comment]
@wasikuss  ah I see what I did wrong. Thank you for the insight ;)

**Comment by zlatevbg** [comment]
+1

**Comment by tomsommer** [comment]
+1

**Comment by fernandoluizao** [comment]
+1

Any news on this?

**Comment by nxtpl** [comment]
+1
Please integrate the checkboxes into main version, the tags are useless with lots of elements selected

**Comment by wzrigui** [comment]
+1

**Comment by claudioredi** [comment]
+1

**Comment by alexandernst** [comment]
For anyone coming here from google and/or interested, check https://github.com/alexandernst/angular-multi-select for a good multi select.

**Comment by stephenbe** [comment]
For anyone that would want a simple CSS solution to this : 
http://codepen.io/stephenbe/pen/zBrzYP

Just change the background color to a background image of a checkbox.

Cheers

**Comment by atomical** [comment]
@wasikuss did you ever make a plugin for this?

**Comment by wasikuss** [comment]
Ok, I see more and more ppl need that plugin. I will post link to plugin when it's done ( 2 - 3days ).

**Comment by kuz30** [comment]
+1, tags are not needed in every case. Moreover, fast group selection is desired too.

**Comment by nickwuk** [comment]
+1

**Comment by wasikuss** [comment]
https://github.com/wasikuss/select2-multi-checkboxes
Please try and feel free to report any bugs/features.

Cheers

**Comment by floriandotorg** [comment]
+1

**Comment by nickwuk** [comment]
I tried copying the fiddle from https://jsfiddle.net/wasikuss/gx93rwnk/ but it did not work because my fiddle account was using jQuery 1.9.1, once I added jQuery 1.10.1 as an external resource it worked fine.

**Comment by nickwuk** [comment]
Is it possible to have the search facility with multiple selection?

**Comment by nickwuk** [comment]
The select2 that I'm converting to multi-select includes an up/down arrow on the far right, a magnifying glass search icon on the far right in the search input box, and a scrollbar on the right of the dropdown.
![select2-with-search](https://cloud.githubusercontent.com/assets/7723418/21653960/6e33c30c-d2ab-11e6-8ed4-7e54ebe51277.jpg)

Is it possible to incorporate these three styles into the third 'select2-original' option please?

**Comment by wasikuss** [comment]
just remove line 44 in [select2.multi-checkboxes.js](https://github.com/wasikuss/select2-multi-checkboxes/blob/master/select2.multi-checkboxes.js) ;)

**Comment by nickwuk** [comment]
Setting minimumResultsForSearch: 0 shows the search box for the first 2 dropdowns which is nice, thank you. However it doesn't change the 3rd option where the selected names appear at the top. There seems to be a search box there without border, it would be great if the border, magnifying glass image, up/down arrow, and vertical scroll could be incorporated into the 3rd layout option.

**Comment by zenzei** [comment]
Hi @wasikuss , was checking your plugin and it's almost what I need but i see it's working with select2 3.5.2. Did your ever upgrade the code to v4?
Thanks in advance,

**Comment by zakamik** [comment]
This issue is closed- has it been implemented already?

**Comment by vasilp** [comment]
Great,
This was what I was looking for also.

@zakamik Yes, repo is here:
https://github.com/wasikuss/select2-multi-checkboxes

**Comment by WillemOpperman** [comment]
For those who are still looking for a solution, have a look at my fiddle.

I have used a couple of fiddles posted about the question and combined it all into 1

Not perfect, but it works. 

https://jsfiddle.net/Lkkm2L48/7/

**Comment by PlippiePlop** [comment]
@WillemOpperman  works great, but only issue that it does not work when you have multiple selects on the screen. it should work with multiple selects on class or id base. See [https://jsfiddle.net/nzfhkfuk/2](https://jsfiddle.net/nzfhkfuk/2)

**Comment by gridphp** [comment]
@WillemOpperman looks good except it always jumps to first selection each time you select.

**Comment by frzsombor** [comment]
@kevin-brown @alexweissman I still think this shouldn't be closed, and should be implemented officially. The [select2-multi-checkboxes](https://github.com/wasikuss/select2-multi-checkboxes) has [issues](https://github.com/wasikuss/select2-multi-checkboxes/issues), and dev is not responding. So basically this is still unsolved after years, which is so sad, because select2-multi-checkboxes almost solved this issue perfectly with only ~70 lines of code. Anyway, thanks for trying to keep the project alive!

**Comment by wasikuss** [comment]
sorry for late response but it is already done. This time properly - less ugly hacks that previously broke partially select2 API.

https://github.com/wasikuss/select2-multi-checkboxes/tree/amd

**Comment by mota57** [comment]
so the feature was requested but the  case was close to use select2?

**Comment by nguaman** [comment]
+1 !

**Comment by muhammedkaraoglu** [comment]
That's how I solved this problem.

https://jsfiddle.net/akwud47t/1/

**Comment by jainpatel25** [comment]
in Select2 Drawer when we add Data from a ajaxcall that time we not ablet to unselect option from dropdown that are selected we have to unselect it from a search field.
so how can i unselect it from a dropdown in ajax call load data
