### ISSUE TITLE
Nuget in visual studio does not include he new version 4.0.0.1 FULL

### ISSUE THREAD

**Issue by mikerosol** [select2/select2#4114]
Please add this backward compatible version - otherwise, we can't manage upgrades with nuget.

**Comment by kevin-brown** [comment]
Select2.js on NuGet is unofficial (not that it's a bad thing) and is managed by @splattne. They are the only one who could possibly add the full build of Select2 to the release.

**Comment by McPhale** [comment]
The current version of the nuget package doesn't include select2.full.js either, just FYI.
