### ISSUE TITLE
Event results:next/previous select item even if disabled.

### ISSUE THREAD

**Issue by phazei** [select2/select2#4116]
I noticed from it's use here
https://github.com/select2/select2/issues/3472#issuecomment-174081802

**Comment by kevin-brown** [comment]
I can't reproduce it at https://select2.github.io/examples.html#disabled-results.

---


Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by phazei** [comment]
Sorry, I realized the issue was with the jQuery selecting the next/prior option without checking if it was disabled.
