### ISSUE TITLE
Ajax passed data with the same id but updated text is not updated.

### ISSUE THREAD

**Issue by OttoPus** [select2/select2#4121]
**What steps can be used to reproduce the issue?**
- Just type a new value that the ajax processor returns as _not found in database_, with a placeholder _id_ (eg: "custom_request"), like "bomb".
  The _data_ array returned to the select2 is: ['id'] => 'custom_request' ; ['text'] => 'bomb'
- Type a new value instead of the old one, that returns the same placeholder _id_ "custom_request", but with a new text, like "dabomb".
  At this point, the _data_ array returned to the select2 is: ['id'] => 'custom_request' ; ['text'] => 'dabomb'
- You select it from the list, but the text is not updated (in the gif I tried another value ("what") with the same result: "bomb" remains selected.

A gif of the issue:
![select2bug](https://cloud.githubusercontent.com/assets/5780010/12529530/99c7f144-c1ba-11e5-8ba6-a45d32a3d306.gif)

**What is the bug and what is the expected outcome?**
I'm expecting the text to be updated (ajax processor correctly passes new text values to the select2)

**What browser(s) and Operating System have you tested with?**
Windows 7 sp1 64bit, google chrome and firefox

**Does the bug happen consistently across all tested browsers?**
Yes

**What version of jQuery are you using? And what version of Select2?**
I'm using jQuery 2.1.4 and Select2 4.0.1

**Are you using Select2 with other plugins?**
jQuery UI Datepicker is loaded in the same page

**Comment by leizard** [comment]
+1 I have the same issue
