### ISSUE TITLE
4.0 - initialize with tag not in data list

### ISSUE THREAD

**Issue by nilssolanki** [select2/select2#4126]
The following description comes from a [stackoverflow post](http://stackoverflow.com/questions/32232359/select2-4-0-initialize-with-tag-not-in-data-list) (not mine, but it describes the issue quite well):

I have a multiple select Select2 (v4.0) item initialized as such:

    $('select#testselect2').select2({
        multiple: true,
        tags: true
    });

There is no data source, it's completely dependent on the user entering their own multiple values. They can enter user-defined values and save back to the DB, no problem.

When retrieving from the DB, though, I'm unable to set the Select2's value to contain the user-defined values. I've tried using **$(...).val(arrayObject).trigger('change')** to no avail. I've been unable to find another solution in the documentation. 

If I define some options in the select element, then use the **val** method above with an array containing some values defined as options AND values *not* defined in options, it will only display the option values and not the "tag" ones.
For example, this select:

    <select id="testselect2" multiple="multiple">
		<option value="1">1</option>
		<option value="2">2</option>
		<option value="3">3</option>
	</select>

and this code:

    $('select#testselect2').val(['1','2','5']).trigger('change');

...will produce "1" and "2" as the selected values.

How do I set the Select2's selected values to entries that are not in the options / data source?

**Comment by kevin-brown** [comment]
Select2, like a standard `<select>` cannot map a value to the full object that it represents. As a result, you need the `<option>` tag in the DOM before Select2 (and a standard `<select>`) can actually select and display it.

You can read more in the documentation: [How can I set the initially selected options when using AJAX?](https://select2.github.io/options.html#how-can-i-set-the-initially-selected-options-when-using-ajax)

**Comment by nilssolanki** [comment]
Just to be sure I understand you: For every custom tag I need to create an extra `<option>` in the list, if the data comes from the server? But I don't need to do that if the user creates a new tag on the fly (or does select2 create the `<option>` automatically)?

**Comment by jswxwxf** [comment]
I have the same issue, is there a way to resolve this?

**Comment by alexweissman** [comment]
This is now covered in the documentation: https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2
