### ISSUE TITLE
Multiselect issue when the key has a leading 0

### ISSUE THREAD

**Issue by sl-fedegiust** [select2/select2#4133]
Hi,

I've been facing the following issue

I've got two options on a multiselect, one of them with key 100 and the other with key 0100.

The plugin seems to be interpreting the keys as numeric, so it thinks 100 and 0100 are the same. Because whenever I select one, the other one gets selected automatically.

Is there a way to force the keys to be interpreted as Strings ?

Thanks

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by sl-fedegiust** [comment]
What steps can be used to reproduce the issue?

As described above already

The list of values contain items with keys

`<option value="0100">ABC</option>`
`<option value="100">ABC 2</option>`

What is the bug and what is the expected outcome?

I'm using the multiselect, and whenever I select only item "0100" it automatically selects both 0100 and 100 instead of just the 0100. Same the other way around.

Expected outcome is if I select 0100 only to select 0100 and not both.

What browser(s) and Operating System have you tested with?

Chrome on both OS X & Windows

Does the bug happen consistently across all tested browsers?

Yes

Can you reproduce this issue on the examples page?

What version of jQuery are you using? And what version of Select2?
Latest, both

Are you using Select2 with other plugins?
No

**Comment by kevin-brown** [comment]
I can't reproduce this error in a jsbin, using the options and steps that you've described.

http://jsbin.com/vamawokego/1/edit?html,js,output

I could _maybe_ understand this bug existing if you were using an external data source or maybe a data array, but I can't reproduce the issue using `<option>` tags.

Select2 4.0.1
Chrome 48 on Windows 10

**Comment by alexweissman** [comment]
Select2 [treats `id`s as strings](https://select2.org/data-sources/formats#automatic-string-casting), so this shouldn't be happening.

At any rate, without a working jsbin that demonstrates this problem, we cannot address it further.
