### ISSUE TITLE
More Search options than title

### ISSUE THREAD

**Issue by johnvanhulsen** [select2/select2#4136]
Hi all,

Is it possible to add more search sources? I've an object with the regular title and some extra fields e.g. company. I use the template option to show all things in a good layout, but when I use the search option, only the title will gave results. Is it possible to let my select also search for the company?

**Comment by kevin-brown** [comment]
Select2 exposes the `matcher` option which allows you to customize how results are selected, it sounds like what you are looking for.

https://select2.github.io/examples.html#matcher
