### ISSUE TITLE
Disable search to make normal dropdown

### ISSUE THREAD

**Issue by norab** [select2/select2#414]
How Can I hide search to make another classic dropdown?

**Comment by ArsooCh** [comment]
Hello, you can disable search option by using this line in initialization code
```
$("#js-example-basic-hide-search").select2({
    minimumResultsForSearch: Infinity
});
```
Here is written in documentation https://select2.org/searching

**Comment by mokhtasatxyz** [comment]
This is for a time when the tool type is a single select
But in a multi-select mode, it should be more technical
Because the property is not defined in the script for this
