### ISSUE TITLE
Loading remote data with minimumInputLength = 0 shows old data in Searching... page

### ISSUE THREAD

**Issue by atsawin** [select2/select2#4141]
I use ajax to load remote data with `minimumInputLength = 0`. When click drop down for the first time, Select2 show _Searching..._ and replace it with data from remote. However, when click drop down for second time, Select2 show _Searching..._ along with old data and replace both of them with data from remote.

When use `minimumInputLength` > 0, this problem will not occur because it will show _Please enter 1 or more characters._

Steps to create problem:
1. Open http://jsfiddle.net/utg0swy7/1/
2. Open drop down, enter search text (the text will be prepend with 'a' because GitHub API requires search string.)
3. Close drop down.
4. Open drop down again, it will show Searching... along with old result from 2. above and in split second, will show new search result.

Optional.
5. Change `minimumInputLength` to 1 (or any value larger than 0) and rerun the page.
6. Try stop 2, 3 and 4 above. It will not show old result.

**Comment by atsawin** [comment]
It seems that instead of prepending $results with $loading, just replace innerHtml of $results with $loading can solve the problem. Here's patch file against v4.0.2.
```
--- a/select2.js	2016-03-09 08:33:38.000000000 +0700
+++ b/select2.js	2016-05-04 10:38:22.605348402 +0700
@@ -896,7 +896,7 @@
     var $loading = this.option(loading);
     $loading.className += ' loading-results';
 
-    this.$results.prepend($loading);
+    this.$results.html($loading);
   };
 
   Results.prototype.hideLoading = function () {
```

**Comment by alexweissman** [comment]
This issue is discussed in more detail in #4854.  Basically, Select2 isn't aware that a new AJAX request has been fired until after the request is complete and the response is received.

Please discuss this further in #4854.
