### ISSUE TITLE
Multiple select2 prevents form submit on enter from other input

### ISSUE THREAD

**Issue by ephommaphavanh** [select2/select2#4142]
Hi, I have a form with a simple input and a select2 input like so : http://codepen.io/anon/pen/QyBxwE

1. Pressing enter inside the first input should submit the form (in this case, redirect to a 404 page).
For some reason, the multiple select2 input prevents the form submit. If I remove the `select2` class or the `multiple: true` attribute, the first input behaves normally.

1. Tested on Mac OS X Yosemite on Safari, Chrome and Firefox

1. Happens consistently on all browsers

1. I'm using jQuery 2.1.3 and select2 4.0.1

1. No other plugin used

**Comment by kevin-brown** [comment]
For later reference, this had to do with the lack of submit button on the form.

http://stackoverflow.com/q/35159330/359284

Didn't realize this was cross posted until a few minutes ago (when it was closed).
