### ISSUE TITLE
The scrollTo parent when highlighting children can make it impossible to scroll down

### ISSUE THREAD

**Issue by tzellman** [select2/select2#4143]
See this fiddle for an example (using 3.5.2) https://jsfiddle.net/shfs7s8e/3/

I made a change in my fork here: https://github.com/tzellman/select2/commit/1d45ed0b38e195ce4b4ba873fa96edea70584b32

Fiddle showing the fix in action: https://jsfiddle.net/22rzn48g/3/

**Comment by pedrofurtado** [comment]
@tzellman The version 3.x is not maintained anymore. But if this bug still occurs in 4.x version, feel free to reopen the issue and report to us a JSFiddle example simulating this scenario.
