### ISSUE TITLE
"Selectable" option groups or work around?

### ISSUE THREAD

**Issue by mokross** [select2/select2#4149]
Is possible to mark option groups to be selectable too? Or exists a work around for that?

Using the first example I want the user to be able to select either a country or the time zone.
- Filtering should result on both on optgroup-level and option-level.
- The selectable values should be organized in the same way as the optgroup supports, thus always showing the time zone to the country.

![select2-optgroup](https://cloud.githubusercontent.com/assets/11661364/12814170/546d7a2e-cb3d-11e5-96ab-681e109a3495.png)

```
<html>
<head>
<script type="text/javascript" src="https://select2.github.io/vendor/js/jquery.min.js"></script>
<link href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css" rel="stylesheet" />
<script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.js"></script>
</head>
<body>
<label>Please select <b>either</b> a time zone <b>or</b> a country:</label>
<select style="width: 95%">
  <optgroup value="ATZ" label="Alaskan/Hawaiian Time Zone">
    <option value="AK">Alaska</option>
    <option value="HI">Hawaii</option>
  </optgroup>
  <optgroup value="PTZ" label="Pacific Time Zone">
    <option value="CA">California</option>
    <option value="NV">Nevada</option>
    <option value="OR">Oregon</option>
  </optgroup>
  <optgroup value="MTZ" label="Mountain Time Zone">
    <option value="AZ">Arizona</option>
    <option value="CO">Colorado</option>
    <option value="ID">Idaho</option>
    <option value="MT">Montana</option>
  </optgroup>
  <optgroup value="CTZ" label="Central Time Zone">
    <option value="AL">Alabama</option>
    <option value="AR">Arkansas</option>
    <option value="IL">Illinois</option>
    <option value="IA">Iowa</option>
  </optgroup>
  <optgroup value="ETZ" label="Eastern Time Zone">
    <option value="CT">Connecticut</option>
    <option value="DE">Delaware</option>
    <option value="FL">Florida</option>
    <option value="GA">Georgia</option>
    <option value="IN">Indiana</option>
  </optgroup>
</select>
<script type="text/javascript">
$(document).ready(function() {
  $("select").select2();
});
</script>
</body>
</html>
```

**Comment by kevin-brown** [comment]
> Is possible to mark option groups to be selectable too?

[Nope.](https://select2.github.io/options.html#can-optgroup-tags-be-made-selectable)

> Or exists a work around for that?

[Yes.](http://stackoverflow.com/q/30820215/359284)

This is a limitation on standard `<select>` boxes that we can't overcome in Select2. But you can at least work around it.

**Comment by MaitriSejpal** [comment]
**Yes this is possible** 
First give id to your select
for example 
<select style="width: 95%" id="selectgroup">
and then add class to your optgroup
like   <optgroup value="ATZ" label="Alaskan/Hawaiian Time Zone" class="select2-result-selectable">
and then add this
$('#selectgroup').select2({
               
            }).on('select2-selecting', function (e) {
                debugger;
                var $select = $(this);
                if (e.val == undefined) {
                    e.preventDefault();
                    var childIds = $.map(e.choice.children, function (child) {
                        return child.id;
                    });
                    $select.select2('val', $select.select2('val').concat(childIds));
                    $select.select2('close');
               }
            });

**Comment by jith** [comment]
Working Demo
[http://jsfiddle.net/jith/dyezumhq/8/](url)

**Comment by jith** [comment]
Check this
[http://jsfiddle.net/jith/dyezumhq/8/](url)

**Comment by jith** [comment]
Check this
http://jsfiddle.net/jith/dyezumhq/8/

**Comment by jith** [comment]
Check this
http://jsfiddle.net/jith/ah5mng8k/
