### ISSUE TITLE
Insert html into the filter area.

### ISSUE THREAD

**Issue by alexpantyukhin** [select2/select2#4152]
Hi!
Now I have a task to append some html (div with additional filter) into the filter area. Unfotrunally I couldn't find some options which allowed it.
Is there way to do it? Or would it be implemented?

**Comment by kevin-brown** [comment]
This can be implemented with a custom selection adapter that overrides the `render` method.

For an example of a decorator that overrides the `render` method, you can see [the search adapter](https://github.com/select2/select2/blob/a126b53b4c90fac33b5d855894647cd8bcac3558/src/js/select2/selection/search.js#L10-L27). If you're looking for actual documentation, you can follow https://github.com/select2/select2/issues/3166 and related tickets.
