### ISSUE TITLE
unable to set initial values in tags with data source v4

### ISSUE THREAD

**Issue by longestdrive** [select2/select2#4157]
I've ugraded from 3.5 and am unable to set initial values for a tags field.

My HTML has been created as follows:
``

```
<select class="tagsinput" multiple="multiple" name="tags[]">
    <option value="">Enter tags for the article</option>
    <option value="3" selected="selected">test</option>
</select>
```

I then have a data object which I use to initialise select2. The data object is obtained via ajax. Here's my code.

```
$.ajax({
            type: 'GET',
            url: '/articles/tags',
            dataType: 'json',
            cache: false,
            success: function(data) {
                initTagsSelect(data);
            }
        });
```

Then initialise the select2 as follows:

```
function initTagsSelect(data) {
            $('.tagsinput').select2({
                theme: "bootstrap",
                data: data,
                minimumInputLength: 2,
                tags: true,
                tokenSeparators: [','],

            });
```

However when select2 then initialises the existing entries no longer exist. When I look at the html in chrome I can see the additional options have been appended to my original ones but my original ones are no longer `selected`. 

Is this a bug or am I missing a step?

Do I have to revert to a previous version?

This appears in both 4.0.0 ad 4.0.1

Thanks

**Comment by kevin-brown** [comment]
Does this issue happen on the latest master (4.0.2-rc.1)? Can you isolate it and reproduce it in a jsbin?

**Comment by longestdrive** [comment]
Hi
Where can I access the version 4.0.2-rc-1 I could only see the version 4.0.1-rc.1 in the repository.

Used that version and same problem.

If I initiate select2 without the data it does show the initially selected values, place the data back it doesnt.

I created a jsbin here with the data object I obtain via ajax. https://jsbin.com/lupafan/edit?html,js,output


Is the data object correctly formatted?

Thanks

**Comment by alexweissman** [comment]
It would appear that, when I upgrade your example code to use Select2 4.0.3, the problem no longer occurs.
