### ISSUE TITLE
Broken references in the docs.

### ISSUE THREAD

**Issue by Eraldo** [select2/select2#4160]
There are some files referenced by the docs' css files which do not exist!

If I try to use this library with [whitenoise](https://pypi.python.org/pypi/whitenoise) it errors out because of missing references.

Example: 
```
The CSS file 'autocomplete_light/vendor/select2/docs/vendor/css/font-awesome.min.css' references a file which could not be found:
         autocomplete_light/vendor/select2/docs/vendor/fonts/fontawesome-webfont.eot
```

Another example:
```
The CSS file 'autocomplete_light/vendor/select2/docs/vendor/css/bootstrap.min.css' references a file which could not be found:
autocomplete_light/vendor/select2/docs/vendor/fonts/glyphicons-halflings-regular.eot
```

Please look into this since it disables other packages to fully include select2 as a dependency.
(Example: [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light))

Regards,
Eraldo

**Comment by kevin-brown** [comment]
The first one (`fontawesome-webfont.eot`) doesn't make sense, the file [should _definitely_ be there](https://github.com/select2/select2/tree/a126b53b4c90fac33b5d855894647cd8bcac3558/docs/vendor/fonts).

The second one (`glyphicons-halflings-regular.eot`) is definitely missing, and we can drop the styles that refer to it.
