### ISSUE TITLE
tags mode avoid new tags

### ISSUE THREAD

**Issue by antonioaltamura** [select2/select2#4164]
Hi, I want to avoid new tags, the user have to select one option and that's it, how can I do it?

I have to say the tags options are poor documentated :)

I found this but it doesn't work with the new version I guess
http://jsfiddle.net/XQ8Fw/

**Comment by kevin-brown** [comment]
> I want to avoid new tags

The whole purpose of the `tags` option is to allow new options to be suggested.

> the user have to select one option and that's it

You might be looking for the `maximumSelectionLength` option.
https://select2.github.io/examples.html#multiple-max

**Comment by alfredopacino** [comment]
> The whole purpose of the tags option is to allow new options to be suggested.

Well actually I'm not totally agree with that see how much jquery plugins uses tags but not necessarily allows new tags (tokenfield, tokenize, tagsinput..)
I explained here what's my purpose:
https://github.com/select2/select2/issues/4163
My form will have select2 with plain text and select2 with tags, but NEVER I have to allow free text or tags (I have to be sure those value are stored in db first, with a form indeed). Any help with this would be very appreciated :)

**Comment by alexweissman** [comment]
"Tagging" and "multi-select" are two distinct features.  This has now been clarified in the documentation: https://select2.org/tagging

I agree, the old documentation was confusing and seemed to conflate these two concepts.
