### ISSUE TITLE
Select2 init -> destroy -> init, Keeps data from initial init

### ISSUE THREAD

**Issue by dementic** [select2/select2#4170]
So,
im trying to destroy a select2 and remove some options.
for some reason, the initial data is kept and the secondary ignored.

you can see the issue in this JSFiddle:

http://jsfiddle.net/a6tedrg3/38/

**Comment by kevin-brown** [comment]
https://select2.github.io/options.html#why-are-option-tags-being-created

This is a duplicate https://github.com/select2/select2/issues/3666.

**Comment by dementic** [comment]
Great, thanks. i missed that.
