### ISSUE TITLE
Uncaught TypeError: Cannot read property 'query' of null

### ISSUE THREAD

**Issue by hipertracker** [select2/select2#4171]
I have no idea why I get the exceptions **"Uncaught TypeError: Cannot read property 'query' of null"** when I click on _x_ to clear Select2 values. 

Here is my KnockoutJS v2.2.0 custom binding to Select2  v4.0.1: http://codepen.io/hipertracker/pen/mVLojK

**Comment by hipertracker** [comment]
Well, I found a workaround. My snippet has been updated

**Comment by witalobenicio** [comment]
How did you solved this issue?

**Comment by lephleg** [comment]
Also interested in this using jQuery..
