### ISSUE TITLE
Not working for dynamically inserted elements

### ISSUE THREAD

**Issue by efusionsoft** [select2/select2#4175]
Is it possible to make this working for dynamically (using Jquery and not ajax ) elements?

Basically, using JQuery I would add a new row with a select element and want to bind that new element with the select2.

<img width="590" alt="capture" src="https://cloud.githubusercontent.com/assets/5202874/12959680/81b0c390-d05d-11e5-9d8c-7b7160b9c446.PNG">

**Comment by efusionsoft** [comment]
It was not difficult to make it work:

```
/*Bind select to the newly created country selectbox*/
$("#country"+next).select2({
   placeholder: "Select a country",
   allowClear: true,
   data: data
}); 
```

**Comment by gruol** [comment]
setTimeout(function(){
    $('.select2').select2();
  }, 100);
use this when adding new row

**Comment by fyfster** [comment]
Check if when you copy the new country select element you keep the element id. If so you must delete the id
