### ISSUE TITLE
span.select2-container width:1px

### ISSUE THREAD

**Issue by antonioaltamura** [select2/select2#4176]
Hi,
WHAT am I trying to do:
my form have some fields dinamically added.
the js code below is part of a click handler of a button "add field".
This field just created in DOM with  $(wrapper).append() needs clearly a select2 init.

I'm facing the issue in select appended, after the select2 initalization is rendered with span.select2-container with width=1px.
but it's a bit tricky to reproduce:
this is my code (simple as possible):
- var wrapper is a DOM reference
- targetnode is a jquery object that refers to a DOM element that contains a select2 element.
- obiouvsly JCore.randomString() returns an alphanumeric random string of 5 char.

```
var d = JCore.randomString(5)
$(wrapper).append('<div data-identifier="'+d+'">'+targetnode.html()+'<a href="#" class="remove_field btn ">Remove</a></div>')
$('[data-identifier='+d+'] select[data-select]').select2({...})
```

in the code below you can see a <select> already initialized with select2.
I removed the select2 spans to avoid a spans duplication too.

targetnode.html( ) content:
https://www.diigo.com/item/image/51ynl/gkaw
(sorry about the image but im not sure there is a way to post html code here :) )

This is the result html code
https://www.diigo.com/file/image/rercsrdzdadqbbpaazcbooocrd/res.jpg

(ps: not sure how I messed up the github editor)

**Comment by pauletienney** [comment]
+1
I have the same problem : dynamicly generated <select>. When I reinit select2 on all select, the old ones become 1px wide.

**Comment by johnmerced** [comment]
I'm facing the same issue - any known workaround?

**Comment by nbelley** [comment]
Same issue. I'm also using bootstrap theme.

 Workaround for me has been to overwrite and make the width important in my own css file:

`.select2-container--bootstrap {
    width: 100% !important;
}`

**Comment by javedKhanCurofy** [comment]
Alternate Solution:

$(document).ready(function() { 
    $("#myselect").select2({ width: '100%' });           
});
