### ISSUE TITLE
how to make Select2 multi append

### ISSUE THREAD

**Issue by vandyvicario** [select2/select2#4181]
sorry,im nubbie

in https://select2.github.io/select2-bootstrap-theme/4.0.0.html,
i see option Select2 multi append, that said we can do it if we add .select2-bootstrap-append to input-group wrap. i use v4.0.1

the question:
i cant find .input-group in select2.css

heres my code:
```
<link href="css/select2.min.css" rel="stylesheet">
<link href="css/select2.css" rel="stylesheet">
<link href="css/select2-bootstrap.css" rel="stylesheet">
```

`<select class="form-control tags" multiple="multiple" style="width: 100%;">
<option value="AL">Alabama</option>
<option value="AK">Alaska</option>
	<option value="AZ">Arizona</option>
	<option value="AR">Arkansas</option>
	<option value="CA">California</option>
	<option value="CO">Colorado</option>
	<option value="CT">Connecticut</option>
	<option value="DE">Delaware</option>
	<option value="DC">District Of Columbia</option>
 </select>`

`<script>
    	$(".tags").select2({
    		allowClear: true
    	});
    </script>`

`<script src="js/select2.min.js"></script>`
please be gentle, thanks

**Comment by kevin-brown** [comment]
It should be defined in `select2-bootstrap.css` and `bootstrap.css`.

Issues with the Bootstrap theme should be reported at the downstream repository.

https://github.com/select2/select2-bootstrap-theme
