### ISSUE TITLE
Clicking in some areas of select highlights all following elements in page (Firefox)

### ISSUE THREAD

**Issue by agilare** [select2/select2#4186]
In my Firefox 44, often, clicks in the select2, highlights all following elements in page (see image)
![select2-firefox-highlight](https://cloud.githubusercontent.com/assets/8960215/13007726/7398fa44-d192-11e5-833b-9491bdee9017.jpg)
, which can be confusing for users.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by agilare** [comment]
> Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?
> 
>     What steps can be used to reproduce the issue?

Visiting the Examples page https://select2.github.io/examples.html 

>     What is the bug and what is the expected outcome?

Clicking in some areas of the select2 highlights all following elements

>     What browser(s) and Operating System have you tested with?

Firefox 44 (Windows 7)

>     Does the bug happen consistently across all tested browsers?

Not in Chrome (48), IE (11) or Opera (tested in Windows)

>     Can you reproduce this issue on the examples page?

Yes, look at printscreen in my first comment

>     What version of jQuery are you using? And what version of Select2?
>     Are you using Select2 with other plugins?

examples page

**Comment by agilare** [comment]
Problem reproduced also in Firefox 33 (Mac) but not in Firefox Developer Edition 46 (Windows 7)

**Comment by OctoberJemini** [comment]
+1
Reproduced in Firefox 47.0 (Windows 10).

**Comment by SgtOddball** [comment]
I will admit I've seen this option alot on firefire (from 43 onwards) but I always assumed I was just missing the correct area to click on. 

As an observation, if you click on any of the elements inside of the drop down (text or the down arrow), this doesn't happen. It only happens if you click on whitespace outside of the text (it pretty much always happens if you have a placeholder text and then set the width to 100%, now click to the right of the place holder text and it should trigger it).

**Comment by lutol** [comment]
I notice this in my case too (ubuntu, FF 47). When it can be fixed? This bug excludes from using it.

**Comment by DevHermit** [comment]
My solution (use closest "container" div as dropdownParent):
`$('.select2').each(function(){
    $(this).select2({dropdownParent: $(this).closest('div')});
});`

By default dropdownParent is body element.
You can also create other element next to select and use it as dropdownParent. I didn't check how it works with "z-indexed" elements.
