### ISSUE TITLE
allowGroupClick in ajax

### ISSUE THREAD

**Issue by alfredopacino** [select2/select2#4188]
Hi, I'm not clear how can I accomplish a grouped select using an ajax source in select2 v4
(note the json source is mine, so I can change the structure if I need)

**Comment by alfredopacino** [comment]
still on with this problem :/

**Comment by kevin-brown** [comment]
This is not possible using groups (`children` in JSON) or `<optgroup>` tags (what they actually generate). You can work around it with CSS, but it's a limitation in a standard `<select>` that we can't get around in the Select2 core.

https://select2.github.io/options.html#can-optgroup-tags-be-made-selectable
