### ISSUE TITLE
Ajax call on empty input

### ISSUE THREAD

**Issue by blaaat** [select2/select2#4191]
I want to suggest the following change in data/ajax.js line 91. 
`if (this.ajaxOptions.delay && params.term !== '') {
`

params.term is undefined when empty. So I would like to change this to: 
`if (this.ajaxOptions.delay && params.term !== undefined && params.term !== '') {
`

So an empty search field loads initial results fast as soon as an user opens the select2 box without addition delay. The params.term !== '' seems to have this intention as well.

**Comment by WilsonChiang** [comment]
Shouldn't actually check on an empty string I believe.

See:
https://github.com/select2/select2/pull/4202
