### ISSUE TITLE
Focus then press ctrl+enter still prompt

### ISSUE THREAD

**Issue by HKsAdad** [select2/select2#4199]
It didn't show the selection dialog in 3.5.2 if ctrl or cmd key is on hold while pressing enter. Tested in "Examples" pages on both 3.5.2 and 4.0.1 with Firefox 43.0.1.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by HKsAdad** [comment]
> Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?
> 
>     What steps can be used to reproduce the issue?
Grant focus to the select2 element (Either click it or use Tab)

>     What is the bug and what is the expected outcome?
Not supposed to open by pressing Enter while holding Ctrl/Cmd

>     What browser(s) and Operating System have you tested with?
Windows 7, Firefox 43.0.1

>     Does the bug happen consistently across all tested browsers?
Yes

>     Can you reproduce this issue on the examples page?
Yes, in 3.5.2 page is working as expected by not opening but not 4.0.1.

>     What version of jQuery are you using? And what version of Select2?
1.11.3

>     Are you using Select2 with other plugins?
No

> 
> The contributing guide contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it. The creation of an isolated test case would also be useful.

Select2 4 reintroduced this as #836 / #1425 fixed the issue in the past.

**Comment by alexweissman** [comment]
I'm not sure where the idea that <kbd>Ctl</kbd>+<kbd>Enter</kbd> should submit the form comes from, but it does seem to be something that has been done before.

At any rate, [this post](https://ux.stackexchange.com/questions/4136/usability-of-ctrl-enter-submitting-of-forms) suggests that it is generally a bad idea from a UX point of view:

> I would say you're making a couple key mistakes by suggesting form submission be accomplished by CTRL + enter.

> - This will not work for all OS.  Enter is universal, while CTRL is not.
> - This breaks the rule of meeting expectations and takes control out of the user's hands.  One of the main reasons for clicking specific buttons or graphics to submit forms is that of intention.  A user may not intend to use enter to submit and combining keys on different OS's is already problematic.

> Forcing a user to click a properly labeled UI component ensures they are telling the system they want to submit the form instead of doing so accidently or, gawd forbid, not being able to do it at all.
