### ISSUE TITLE
Document how to stop the propagation of events

### ISSUE THREAD

**Issue by elmart** [select2/select2#4206]
Hi, I've just had a look, but I've found no way to prevent keyup event from bubbling out of select2 dropdown. Can anybody point me in the right direction, please? Thanks.

**Comment by Mad-Chemist** [comment]
+1
In the 4.0 release everyone is pointing to a "StopPropagation" module but there is no documentation around how to implement and use that module.  I am in a similar boat and need to prevent event bubbling.

**Comment by pedrofurtado** [comment]
The issue is related to 3.x version, but the version 3.x is not maintained anymore. But if this bug occurs in 4.x version, please reopen the issue and send us a JSFiddle example code or a PR.
