### ISSUE TITLE
Empty object being passed to url function (loading remote data)

### ISSUE THREAD

**Issue by duduklein** [select2/select2#4213]
## Steps to reproduce the issue

When using the ajax remote load function, I saw at the source code that the `url` parameter could receive a function and the arguments would be this.$element and params:
In `AjaxAdapter.prototype.query`, we have:
```
if (typeof options.url === 'function') {
      options.url = options.url.call(this.$element, params);
    }
```

My function is called, but the first parameter is an empty object.

## Expected behavior and actual behavior

If you use coffescript, this is the code that is producing this behavior:
```
class LoadSelectAjax 

        constructor: ->

            $(".select2").select2
                ajax:
                    url: @get_url
                    dataType: 'json'
                    processResults: (data, params) =>
                        return {
                            results: data.content,
                        }
                    minimumInputLength: 1
                    minimumResultsForSearch: Infinity


        get_url: ($element, params) =>
            return $element.data("url")
```
I get the error: `Uncaught TypeError: $element.data is not a function` and when I print `$element', I get an empty object: `Object {}`

I was expecting to have my jquery select element [<select name="..." class="select2" data-url="/my-url/"> ... </select>]
        
## Environment
I'm on Chrome 48.0.2564.116 (64-bit), Ubuntu 14.04
Select2: 4.0.2-rc.1
jquery: 2.1.4

Am I doing or expecting something wrong?
Thanks in advance

**Comment by kevin-brown** [comment]
When you use `.call` on a function in JavaScript, the first argument is the `this` reference. So in your `url` option, you can use `this` to refer to the JavaScript element where Select2 was initialized.

```coffeescript
get_url: (params) ->
  return this.data('url')
```

I'm going to leave this open as something which needs to be documented, as there is no documentation on `ajax.url` at the moment.

**Comment by duduklein** [comment]
Thanks for your quick response. I did not know it. I works perfectly!
