### ISSUE TITLE
select2 mutlipe select in multiple places

### ISSUE THREAD

**Issue by RVP04** [select2/select2#4215]
I have country, state, city fetching in ajax. I use select2 for party and concern form entry. 
3 selectbox with id countryid, stateid,cityid 

i am using this in various forms but only one form only correctly showing select2 all forms normal select is coming and also jquery throwing an error. 

please help me

**Comment by alexweissman** [comment]
This appears to be a usage question, rather than a bug report or feature request.  Please see our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Usage questions should be discussed on the [forums](https://forums.select2.org) instead.
