### ISSUE TITLE
Custom Matcher (oldMatcher) does not work on AJAX Remote Data

### ISSUE THREAD

**Issue by darthtaco** [select2/select2#4216]
Hi -- thanks for your work on this.  I enjoy using it.

It appears the matcher is never called when using select2 with remote ajax data.  See the [JSBin located here](https://jsbin.com/qabituhuca/edit?html,js,output), where I took the remote data example from the examples page and wrapped it using documented matcher backwards compatibility technique.  Note: For simplicity, I trimmed the `formatRepo` method simply to display the repository name rather than all the other stuff.

Entering in the search text "ght", I would expect that a search done in this manner would limit the results to only repositories beginning with "ght". However, the first repository returned is [AerialX/PSL1GHT](https://github.com/AerialX/PSL1GHT), and others that do not begin with "ght".

Windows 7
Google Chrome 48
Select2 4.0.1
JQuery 2.2.1

Hope that helps!

**Comment by rakeen** [comment]
Here's an additional [demo](http://plnkr.co/edit/svhkAD4iipuEUrD0w7B8?p=preview).

![select2](https://cloud.githubusercontent.com/assets/10359412/20893818/4dd6e18c-bb3d-11e6-990b-13fcf350b804.gif)

While typing anything I would expect it to cap the suggestions that only matches our term. And also matching results should come first in the order. Instead it shows every thing in that is in the data-result array.

**Comment by bonesoul** [comment]
i have the same problem.

**Comment by bonesoul** [comment]
any updates on this?

**Comment by legreco** [comment]
I have the same problem too. Did you solve this?

**Comment by bonesoul** [comment]
no basically you are fucked.

**Comment by alexweissman** [comment]
For the moment, `matcher` will only support local data sources.  This has been clarified in the documentation: https://select2.org/searching#customizing-how-results-are-matched

**Comment by sadeqhatami** [comment]
I have same problem in angular 5 , i solved my problem with this code 
```
<select2 (valueChanged)="Changed($event,KeyPress())"></select2>
  KeyPress() {
    var keynum = 0;
    var e: any = window.event;

    if (e) { // IE                    
      keynum = e.keyCode;
    } else if (e.which) { // Netscape/Firefox/Opera                   
      keynum = e.which;
    }

    return keynum
  }

  Changed(e: any, keyNum: number) {

    //if option not choose with enter key or e is undefined 
    if ((keyNum && keyNum != 13) && (!e.data || !e.data[0] || !e.data[0].selected)) return

    //data is choosed 
    if (e.data.length > 0) {
        //do something

    }
  }
```
