### ISSUE TITLE
Documentation for Bootstrap modals

### ISSUE THREAD

**Issue by chipco** [select2/select2#4217]
## Steps to reproduce the issue
1. Open the modal in this fiddle http://jsfiddle.net/81sr8v4h/2/
2. Click the select input to open the options
3. Try to input something in the search
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox

Operating System
- [x] Windows

**Comment by chipco** [comment]
`$.fn.modal.Constructor.prototype.enforceFocus = $.noop;` wasn't a solution for me since it messes tabbing between inputs.

Attaching select2 dropdown to the modal frame seems to work fine for me: http://jsfiddle.net/81sr8v4h/4/

**Comment by mukesh011** [comment]
This issue is also reproducible with any kind of modal popup. I am using knockout modal popup.

**Comment by boiawang** [comment]
@chipco  thanks.

**Comment by kevin-brown** [comment]
I've updated the locked message at https://github.com/select2/select2/issues/600#issuecomment-102857595 to mention `dropdownParent`.

I'm leaving this ticket open because this is something which needs to be documented, as people commonly use Bootstrap with Select2.

**Comment by daza110** [comment]
As per my comment on another thread (https://github.com/select2/select2/issues/4218#issuecomment-213393499) this JS fiddle does not work when scrolling down the modal.
The "$.fn.modal.Constructor.prototype.enforceFocus = $.noop;" fix doent work at all for me

**Comment by vnt** [comment]
I have the same problem!!

**Comment by wadleo** [comment]
I just solved this now, removed the tabindex='-1' on the modal (<div id="myModal" class="modal fade" tabindex='-1' role="dialog" aria-labelledby='myModalLabel' aria-hidden='true'>)

**Comment by FramnkRulez** [comment]
Attaching the dropdown to the modal frame is the best way to solve this problem.  Overriding bootstrap's enforceFocus() function or removing tabindex='-1' will break the keyboard tabbing on bootstrap modal forms.

**Comment by alexweissman** [comment]
This might be a good candidate for a "troubleshooting" or "common problems" section.

**Comment by alexweissman** [comment]
This is now documented at https://select2.org/troubleshooting/common-problems.
