### ISSUE TITLE
4.0.1 select remains opened after closing modal with escape

### ISSUE THREAD

**Issue by chipco** [select2/select2#4218]
## Steps to reproduce the issue
1. Open the modal in this fiddle http://jsfiddle.net/81sr8v4h/3/
2. Click the select input to open the options
3. Press Escape on the keyboard
## Expected behavior and actual behavior

When I follow those steps, the select2 window remains on the screen

I was expecting select2 to disappear with the modal.
## Environment

Browsers
- [x ] Google Chrome
- [x ] Mozilla Firefox

Operating System
- [x ] Windows

**Comment by lpcanh** [comment]
Can you try remove tabindex='-1' on modal.
also check more about Select2 in bootstrap modal #600

**Comment by chipco** [comment]
I've read several pages about the issues with select2 in modal. Removing `tabindex='-1'` makes it work; I've also tested with adding `$.fn.modal.Constructor.prototype.enforceFocus = $.noop;`. But this breaks tabing between inputs in the modal. Atm I'm experimenting with attaching select2 dropdown to the select parent instead of the body.

**Comment by chipco** [comment]
Attaching to the modal frame seems to work fine for me: http://jsfiddle.net/81sr8v4h/4/

**Comment by lpcanh** [comment]
Cool. it's good option.

**Comment by daza110** [comment]
Your JS Fiddle works if you do not scroll down, if you scroll down so that the select2 in the modal is literally just in display, the positioning is wrong. see screen shots
![screenshot-jsfiddle net 2016-04-22 12-55-15](https://cloud.githubusercontent.com/assets/11670005/14740806/915efa1e-0889-11e6-92e8-d9561a9c30d9.png)
![screenshot-jsfiddle net 2016-04-22 12-54-20](https://cloud.githubusercontent.com/assets/11670005/14740807/9172e9e8-0889-11e6-959a-3e344c3f2724.png)

**Comment by daza110** [comment]
@chipco, @kevin-brown, I have managed to get a working fix within a modal for my systems. I have a function that I call to initiate the Select2, and all I have done is added in something for then the select2 is opened.

I would appreciate your comments and thoughts. This seems to work perfectly in a modal now including scrolling.

JS function is `function BSSelect(fieldId)
{
	var attach = '',
		parent = jQuery('#'+fieldId).closest('.modal');
	if(parent.length)
	{
		attach = jQuery('#'+fieldId).closest('div');
	}
	jQuery('#'+fieldId).select2({
		dropdownParent: attach,
	}).on("select2:open", function(e)
	{
		var DDCont = jQuery('.select2-dropdown').parent().closest('.select2-container'),
			DD = jQuery('.select2-dropdown');
		DDCont.addClass('fixtobottom');
		setTimeout(function()
		{
			var	DDHeight = DDCont[0].scrollHeight,
				SelectLoc = jQuery('#'+fieldId).offset().top,
				viewheight = jQuery('.modal')[0].offsetHeight;
			if(DDHeight + 50 + SelectLoc > viewheight)
			{
				DDCont.removeClass('fixtobottom').css('top',parseFloat(-DDHeight));
				DD.addClass('select2-dropdown--above').removeClass('select2-dropdown--below');
			}
			else
			{
				DD.removeClass('select2-dropdown--above').addClass('select2-dropdown--below');
			}
		},50);
	});
}`

**Comment by alexweissman** [comment]
As per the [fiddle](http://jsfiddle.net/81sr8v4h/4/), it appears that `dropdownParent` is indeed the best option.  See https://select2.org/troubleshooting/common-problems for details.
