### ISSUE TITLE
select2 v4.0.2 (and earlier) on explorer "Error: Member not found."

### ISSUE THREAD

**Issue by hananivry** [select2/select2#4221]
Hi,

I use component select2 on explorer 8+.
When I enter "multiple: true" I get error message "Error: Member not found." - he didn't find placeholder object.
To solve the problem suggested I add "meta http-equiv="X-UA-Compatible" content="IE=edge"" in head tag on html page.
The problem was resolved, but created other problems.
I used ReportingServices (ReportingViewer) and that creates a problem in report (CSS).
Are there any other solutions?

Thanks,

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
