### ISSUE TITLE
Enforce list-style: none on rendered options

### ISSUE THREAD

**Issue by jpic** [select2/select2#4225]
## Steps to reproduce the issue

This bug happens with this CSS:

    ul li { list-style-type: square; }

## Expected behavior and actual behavior

Actual result:
![2016-03-01-202350_371x51_scrot](https://cloud.githubusercontent.com/assets/94636/13440391/1705c690-dff2-11e5-992a-2637b3c8e5cd.png)

Expected result: no black squares.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

## Isolating the problem

It's present in Django admin.

**Comment by melinath** [comment]
Just ran into this as well.
