### ISSUE TITLE
Dropdown popup shifts to left and right due to the present of vertical scrollbar on Google Chrome

### ISSUE THREAD

**Issue by vothai-son** [select2/select2#4230]
## Steps to reproduce the issue

It happens in one of our internal projects. So, I am sorry I don't have the screenshot, and I cannot reproduce it a fiddle or a codepen.

Here are the steps.
- We have a page with "overflow-y: auto" css rule. There are several select2 comboboxes on the page.
- At first, vertical scrollbar is hidden (i.e page height does not exceed window height)
- Click on the comboxes near the bottom of the page.
- And your code runs like this:
  - Calculate the position to display the dropdown popup and create css rules.
  - Apply the css rules to the dropdown to make it visible.

The problem is, after the dropdown shows up below the textbox, the page height exceeds window height, and vertical scrollbar appears. That makes the whole page shifts to the left, and the dropdown appears to be shifted to the right.

And it does not stop there. Select2 knows that there is not enough room for the dropdown, so it move the dropdown up above the textbox. It runs the sequence again:
- Calculate the position to display the dropdown popup and create css rules.
- Apply the css rules to the dropdown to make it visible.

As you might guess, this time the dropdown will be shifted to the left. And that is the final position users see on the page.

We have two ways to fix this issue:
1. Set "overflow-y: visible". My boss doesn't like it.
2. Put this at the end of `AttachBody.prototype._positionDropdown`

```
    css.left = offset = this.$container.offset().left;
    this.$dropdownContainer.css(css);
```

It is like, show the dropdown, then recalculate the position, then re-apply css to show the dropdown again.
I just post the issue here, hope you guys has a better solution. There is always a better solution (someone said that ^^)

Thanks and Cheers,

Browsers
- [x] Google Chrome

Operating System
- [x] Windows

Libraries
- jQuery version: v2.1.3
- Select2 version: v4.0.2-rc.1

**Comment by kevin-brown** [comment]
> I cannot reproduce it a fiddle or a codepen

This is usually a major indicator that there is something else at play, though I'll entertain the idea that it can be solved in a general way within Select2.

If I (or someone else) get the time to, I'll try to see if I can reproduce this issue in isolation. Otherwise I'm going to end up closing this as being a bug that can't be reproduced.

**Comment by vothai-son** [comment]
Sorry, I didn't explain myself very well.
If you want to see it in action, here is what you can do (surprisingly easy):

- Goto your pretty example page (here: https://select2.github.io/examples.html)
(please use Chrome)
- Open any one of those select2 comboboxes you see on the page.
- Carefully open Dev Tool
- Carefully paste it into the console and carefully  hit enter: ```$('html').css('overflow-y', 'hidden')``` (this is one way to simulate the behavior when the page height is shorten to the point vertical scrollbar disappears).

- Carefully observe.

Hope you can see what I see.
![This is it](https://copy.com/sQTNGvv1T2fwQ3WJ/2016-03-11_0-15-05.png)

Happy coding,

**Comment by alexweissman** [comment]
I was able to make _something_ happen by following the steps outlined above:

![screen shot 2017-12-09 at 1 27 59 pm](https://user-images.githubusercontent.com/5004534/33798366-018ec658-dce5-11e7-95f5-cc421604c9d1.png)

But it corrects the width once I close my browser console.

**Comment by kevin-brown** [comment]
I can reproduce this bug with the instructions given, which is good enough for me to confirm this as an actual bug.

> But it corrects the width once I close my browser console.

This is because we resize Select2 when the browser window resizes, which occurs when you close your browser console.

**Comment by kevin-brown** [comment]
I'm willing to review pull requests if anyone wants to send one in to fix this.

**Comment by kevin-brown** [comment]
So, browsers don't appear to have an event that is triggered when the scrollbar appears or disappears. So without constantly polling for changes (which is a bad idea), I'm not sure there is a way to detect this and fix the issue.

https://stackoverflow.com/q/2175992/359284

I'll give this the 60 day bump for Stale but I suspect this will auto close if nobody else can find a way to detect when the scrollbar appears or disappears.
