### ISSUE TITLE
select2 onchange event not emitted after using zone.js

### ISSUE THREAD

**Issue by gergaczd** [select2/select2#4231]
## Steps to reproduce the issue
1. Add change event listeners to a select (like element.addEventListener('change', ...), onchange="", and jquery .on('change') function)
2. Use zone.js on the page (for example using angular2 on the existing site)
3. Use select2 on a select
4. Change value of the select2 by interaction
## Expected behavior and actual behavior

The use case is that I add tree event handler for change each of them are different:
- with addEventListener
- with onchange attribute property
- with jquery .on() function
1. case - use select2 and zone.js: only jquery event emitted
2. case - use select2 only: only jquery and onchange emitted
3. case - use only zone.js: all of them emitted

I expect that onchange should be  working in the 1. case, I know that zone.js monkey-patching the events, so maybe both of the library is responsible for this issue.
I created a jsbin example for this bug (1. case): https://jsbin.com/quletutemo
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 2.2.1
- Select2 version: 4.0.2-rc.1
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/quletutemo/1/edit?html,output)

**Comment by kevin-brown** [comment]
Select2 uses jQuery to trigger the `change` event, which is most likely why you don't see the `addEventHandler` being called. I'm not sure why using zone.js with Select2 suddenly kills the `onchange` attribute.

**Comment by alexweissman** [comment]
Select2 v4 does not support native change events - see the detailed explanation in #1908.
