### ISSUE TITLE
Selection never shows up when using Ajax

### ISSUE THREAD

**Issue by siemandelc** [select2/select2#4233]
Release version (Select 4.0.1)

HTML
`<select id="search_customers" style="width: 300px;"></select>`

Javascript:

```
$("#search_customers").select2({
                multiple: false,
                allowClear: true,
                ajax: {
                    url: "@Url.Action("SearchCustomers", "Home")",
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {                            
                            id: params.term, // search term
                        };
                    },
                    processResults: function (data, params) {
                        return { results: data } // Data is a List<T> of id an text
                    },
                }
            });
```

The dropdown works, and I can see my records, however, when I click on one of the options the box closes, and the selected record isn't shown. My box looks like this

![capture](https://cloud.githubusercontent.com/assets/1727967/13538859/79901eb0-e212-11e5-89e9-37931779bb7e.PNG)

I've tried everything I can think of. The issue appears in all browsers. The data being return is a list of id/text pairs.

Controller code

```
var customers = this.service.SearchCustomers(id).Select(x => new { id = x.CustomerID, text = x.CustomerName }).ToList();

return Json(customers, JsonRequestBehavior.AllowGet);
```

**Comment by siemandelc** [comment]
It turns out the ID number was returning "0 4567", and the leading space/spaces in some cases were causing the error. Modifying my c# code to this

`var customers = this.service.SearchCustomers(id).Select(x => new { id = x.CustomerID.Trim(), text = x.CustomerName }).ToList();`

fixed the issue.

**Comment by alexweissman** [comment]
This appears to be a usage question, rather than a bug report or feature request.  Please see our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Usage questions should be discussed on the [forums](https://forums.select2.org) instead.
