### ISSUE TITLE
Multiselect with initial values is not showing any text for the selected elements

### ISSUE THREAD

**Issue by triynko** [select2/select2#4239]
I have a multiselect select field with two options, both of which are selected.  When I initialize select2 for an ajax data source, the selected values show up in the box, but they have no text.  Upon inspection in chrome, I can see that the both the text and value were picked up, but instead of the text being put inside the appropriate tags, it's set as the "title" attribute of the appropriate tag.  This is bizarre.  It simply does not work as described, and it's costing me a lot of time.

**Comment by triynko** [comment]
I figured out what the problem was.  By default, the options are read and turned into objects with an "id" and "text" property.  The custom format I'm receiving from the server uses a "username" property instead of ID.  I had to change my format function to return data.username || data.text, and that fixed it.  It feels like a design flaw, however, since I'm re-defining a behavior.   Instead of defining a function that maps a value from a datasource, why isn't there just a property to redefine the default name?  That way it's read from the server with that name, and the default option reader would assign the option text to that name as well, eliminating the need for the function.  DataTables does this for redefining their row id field.

**Comment by hmonglee** [comment]
I have the same issue, you save me @triynko :)

**Comment by kevin-brown** [comment]
> By default, the options are read and turned into objects with an "id" and "text" property. The custom format I'm receiving from the server uses a "username" property instead of ID.

https://select2.github.io/options.html#my-objects-dont-use-id-for-their-unique-identifiers-what-can-i
https://select2.github.io/options.html#my-objects-use-a-property-other-than-text-for-the-text-that-nee

> why isn't there just a property to redefine the default name?

Select2 previously allowed this, through the use of an `id` function/option which did the mapping. In 4.0, a decision was made to standardize everything to use `id` and `text` instead of referring to custom mapping functions.

**Comment by sproutient** [comment]
Thanks @triynko
