### ISSUE TITLE
Programmatically change to the next option

### ISSUE THREAD

**Issue by phrozen755** [select2/select2#4242]
## Prerequisites

- [Y ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [Y ] The issue still exists against the latest `master` branch of Select2
- [Y ] I have attempted to find the simplest possible steps to reproduce the issue
- [ N] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.$('.select2 option:selected').next().attr('selected', 'selected'); 

## Expected behavior and actual behavior

This should change the drop down to the next option in it's list. It does not.

## Environment

Browsers

- [Y ] Google Chrome

Operating System

- [Y ] Mac OS X

Libraries

- jQuery version: 2.2.1
- Select2 version: 4.0.2-rc.1

## Isolating the problem
- [ Y] The bug happens consistently across all tested browsers
- [ Y] This bug happens when using Select2 without other pluigns

**Comment by phrozen755** [comment]
I need coffee. Clearly.

If anyone is wondering how to do this, fire the above code but also you'll need to hit .change() on your select after.

**Comment by kevin-brown** [comment]
Note that this is documented at

https://select2.github.io/options.html#what-events-does-select2-listen-for

I'd also recommend using `prop('selected', true)` over `attr('selected')`.

**Comment by webdevbrian** [comment]
+1 for the mention of `prop('selected', true)` over attr selected. The latter being quite buggy I've noticed in my uses in the few past days. Thanks for the mention @kevin-brown. I wish I had the link but I think I saw on StackE some guy answering with `attr(selected)`.

That's all I had, wanted to make a mention of definitely using `prop('selected', true)`.
