### ISSUE TITLE
Original select being updated with new option but not marked as selected

### ISSUE THREAD

**Issue by duduklein** [select2/select2#4244]
I'm using select2 version 4.0.2 rc1.

I'm using select2 with remote data loading. Initially (when my page loads), my select only contains the selected item if something is already selected. otherwise, it's empty.

I then use the remote loading via ajax, which works very well and I can select my desired option. When I look into the "real" select, the new option selected in included, but it's not marked as selected, so my "real" select, still has the first option as "selected". 

It seems to be that the issue is in the method `ArrayAdapter.prototype.select`. The `data` it receives comes from the loaded select, so it does not contain the "selected" info and it seems that it should be added here. Something like this:

```
ArrayAdapter.prototype.select = function (data) {
    // NOT SURE HOW YOU HANDLE THE CASE WHERE THE SELECTED OPTION ALREADY EXISTS 
    var $option = this.$element.find('option').filter(function (i, elm) {
      return elm.value == data.id.toString();
    });

    if ($option.length === 0) {
      data.selected = true // ADDED LINE 
      $option = this.option(data);

      this.addOptions($option);
    }

    ArrayAdapter.__super__.select.call(this, data);
  };
```

Thanks

ps: the cdn link to the version 4.0.2 gives a 404 at the moment: https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/js/select2.js

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/select2/select2/issues/3366.

I'm leaving this ticket open because I just noticed that this isn't documented anywhere, but it's a common thing that people notice.

**Comment by alexweissman** [comment]
I've documented this here for now: https://select2.org/programmatic-control/retrieving-selections

Still not sure if this is something that should be fixed?

**Comment by zardilior** [comment]
The problem with not being able to bind easily as the selected option is not updated, is different from obtaining data from selections. Not even the value is bindable by usual methods, I will manually add a change function but it should be updated by default

**Comment by zardilior** [comment]
:(

**Comment by zardilior** [comment]
Stale but still a problem

**Comment by chrisharrisonkiwi** [comment]
Stale but STILL a problem

**Comment by emnik** [comment]
$('#selectStd').on('select2:select', function (e) {
  var data = e.params.data;
  console.log('Selected:', data);
  var id = String(data.id);
  var text = String(data.text);

  $(this).find('option').remove(); // Remove any other option
  var newOption = new Option(text, id, true, true);
  $(this).append(newOption).trigger('change');
});

this is what works for me! If I don't remove the other options it doesn't show the selected one after the first trigger!

hope this helps someone. I've  struggled a lot with this...
