### ISSUE TITLE
formatInputTooShort property not working

### ISSUE THREAD

**Issue by sei-dmorda** [select2/select2#4252]
Hi folks,

I'm having an issue getting the formatInputTooShort property to work in the 4.x version of Select 2. It seems to work in the 3.x version, but not the latest. I've created two fiddles to demonstrate the issue.

**Works with 3.2**
https://jsfiddle.net/dmorda/t9hravbg/1/

**Doesn't work with 4.0.2**
https://jsfiddle.net/dmorda/fhLw0fyf/2/

Known issue or am I doing something wrong maybe?

**Comment by kevin-brown** [comment]
Internationalization is one of the many things that changed in Select2 4.0.0.

https://github.com/select2/select2/releases/tag/4.0.0-beta.1

You can now specify it using `language.inputTooShort`.

https://jsfiddle.net/86t7term/
