### ISSUE TITLE
Single select apparently not working for most Android devices

### ISSUE THREAD

**Issue by m9n** [select2/select2#4257]
I've been using the Pods Framework for WordPress, which I understand uses Select2 for its autocomplete fields.  I've filed a bug report there, but I'm guessing this is more likely to be a Select2 bug, so just adding a heads-up here too.

https://github.com/pods-framework/pods/issues/3450

Because I'm not developing directly with Select2, it's difficult for me to test or give you a lot of extra information.  Of course, feel free to close this if it's unhelpful or inappropriate.

**Comment by kevin-brown** [comment]
Pods is using an _ancient_ version of Select2, [here is the timestamp for it](https://github.com/pods-framework/pods/blob/dde459f59321827049a466a2df4d656688989790/ui/js/select2/select2.css#L2).

Luckily they do have a ticket open for upgrading: https://github.com/pods-framework/pods/issues/2592.
