### ISSUE TITLE
Avast Detecting Pt-BR.js as Virus

### ISSUE THREAD

**Issue by jonathangoncalves** [select2/select2#4263]
Hello!
I'm using the Select2 (4.0.0) and when I entered in i18n folder, the Avast! Antivirus detected the pt-BR.js file as a Trojan (Other:Malware-gen [Trj]).
I sent a feedback to Avast! saying that it's a false positive and I wanted to letting you aware.

_(s.f.m.b.e.)_

**Comment by mmbizdaq** [comment]
Thanks. Same problem here... only just started. Thanks for contacting Avast.

**Comment by kevin-brown** [comment]
Interesting, does this happen on [3.5.4](https://github.com/select2/select2/blob/170c88460ac69639b57dfa03cfea0dadbf3c2bad/select2_locale_pt-BR.js) or [4.0.2](https://github.com/select2/select2/blob/6844be777b0fe9af1d2b9a8f6051b7eb7d532247/dist/js/i18n/pt-BR.js)?

**Comment by jonathangoncalves** [comment]
In my case was in Select2 **4.0.0**.

Avast Program Version: 11.1.2253
Avast Virus Definition Version: 160322-0
