### ISSUE TITLE
Cannot programmatically select an item in 4.0.2 (works in 4.0.0)

### ISSUE THREAD

**Issue by abrindam** [select2/select2#4264]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Create a select2 dropdown with multiple items, e.g "foo", "bar", and "baz". First item "foo" should be selected.
2. Attempt to programmatically select "bar" via the following code:
   `$(".dropdown").select2("val", "bar")`
## Expected behavior and actual behavior

Expected behavior: "bar" option should become selected.

Actual behavior: nothing happens
## Environment

Browsers
Tested on Google Chrome, Mac OS X and Firefox, Windows.

Libraries
- jQuery version: 1.8.2
- Select2 version: 4.0.2
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)
## Additional Information

Does NOT happen with exact same setup and Select2 4.0.0.

I took a first look and what is happening and this appears to be regression caused by the fix for #3413 in 4.0.1. As part of this change, the root `select2` function (in `jquery.select2.js`) had an `each` block added. Inside the code that was wrapped, the magic `arguments` variable was being used. As a result of the wrapping, `arguments` now refers to the `each` callback function, not the outer `select2` method, and therefore arguments are passed incorrectly to the `val` function.

Based on this analysis, it would seem this could have a wide effect across any method that is invoked in string form (`select2("foo", "bar")` as opposed to `select2({foo: "bar"})`). So the issue could possibly be more serious than indicated by title.

**Comment by SimonStefan** [comment]
I had the same issue. It seems that somebody removed the deprecated way [1] a bit too early.

use `$(".dropdown").val("bar").trigger("change");`

[1] https://select2.github.io/announcements-4.0.html#removed-methods

**Comment by rhymes** [comment]
I can't use trigger("change") because I have two selects synchronized, that would result in a stack error.

I ended up doing this:

```
var text = $thisSelect.find('option:selected').text();
$otherSelect.parent().find('.select2-selection__rendered').text(text).attr('title', text);
```

**Comment by kevin-brown** [comment]
I still need to look into why this is happening, and probably add a test or two. The `select2('val')` method will only be around for 4.0.3, it'll be dropped completely in 4.1.0.

> I can't use trigger("change") because I have two selects synchronized, that would result in a stack error.

https://select2.github.io/options.html#can-i-trigger-an-event-other-than-change-to-notify-select2-of-c

**Comment by rhymes** [comment]
@kevin-brown thanks!

**Comment by ChazyTheBest** [comment]
I'm having a similar problem but in my case is with dynamic lists. It's working with static lists. For the dynamic lists the actual behavior is weird, sometimes sets the placeholder and the value and sometimes does not set nothing... I'm reinitializing select2 and using `trigger("change");`

http://stackoverflow.com/questions/36802059/select2-set-value-of-dynamic-list

**Comment by elvispt** [comment]
Hi @kevin-brown 

I had this issue, and found out the problem:
![image](https://cloud.githubusercontent.com/assets/988967/18745316/a0ea061a-80b9-11e6-860a-b607f001ee48.png)

"GE" is the value to be set, but then newVal gets only the first char, due to `args[0]`.
This code probably expected a array of arguments, or to use the arguments variable.
I ended overriding the method, replacing this:
```js
var newVal = args[0];
```
with:
```js
var newVal = args;
```

By the way, this also helps when setting values that are numbers.

Here is a fiddle with the change:
http://jsfiddle.net/epestana/3xbt5mpf/


Hope it helps.

**Comment by alexweissman** [comment]
@elvispt if you have found the problem, you should submit a pull request!  Fixes in comments like this are likely to get buried.
