### ISSUE TITLE
Incorrect version of node listed in CONTRIBUTING.md?

### ISSUE THREAD

**Issue by nicogreenarry** [select2/select2#4268]
Does select2 really still prefer node version 0.10? Or is the CONTRIBUTING.md file just not updated? That [document states](https://github.com/select2/select2/blob/master/CONTRIBUTING.md#installing-development-dependencies):

> Select2 can be built and developed on any system which supports Node.js. The preferred Node.js version is 0.10, but 0.12 and later versions can be used without any noticeable issues. You can download Node.js at their website.

**Comment by kevin-brown** [comment]
[0.12 to 4.2](https://github.com/nodejs/LTS#lts_schedule) was a pretty large jump for Node to make, didn't realize that happened.

Select2 is compiled and released with Node 0.10/0.12 (depending on who does it, and when), and we haven't tested it on newer versions of Node yet.

**Comment by nickbarry** [comment]
OK, thanks for the heads up! Yeah, there was a big leap when they merged io.js back into Node. The node site says:

> Releases 1.x through 3.x were called "io.js" as they were part of the io.js fork. As of Node.js 4.0.0 the former release lines of io.js converged with Node.js 0.12.x into unified Node.js releases.

Then in the last six months they worked their way from version 4.0.0 through 5.9.1.

**Comment by kevin-brown** [comment]
I'm going to reopen this while we wait to find out if Select2 can be built on newer versions of Node.
