### ISSUE TITLE
Unexpected initial behaviour

### ISSUE THREAD

**Issue by RobertDiebels** [select2/select2#4274]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Initalize any select element with select2 (with or without placeholder)
2. Click the button.

## Expected behavior and actual behavior

When I follow those steps, I see...

### After step 1
That select2 loads up a value for the select element which has not been selected nor assigned as the initial value. I have added a regular select element and it seems that this is default HTML behaviour.
However it is not what I expect from select2 (nor HTML in our context, which is a form, to be honest).

That select2 does not show any placeholder for a regular select-element. The "multiple" version shows the behaviour that I would expect. As it shows in the console that the value that is extracted is "null".

I was expecting...

### After step 1
That select2 would load empty.
We do some validation on forms to check if required fields are not empty. If the value of select2 would be extracted it would show that it is not empty, eventhough the user has not assigned the value they want.
Accidently submitting the form when default values are loaded would mean that the user submits data they do not want to submit.

That the placeholders would be visible.

### After step 2
That using $("select").select({placeholder:"something"}); would be applied to all select elements. This does not happen.

If this was a design choice (to follow the regular html, which is very understandable) I would propose that an option is provided to leave the value empty by default.

If I've made any wrong assumptions please correct me.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.1.4
- Select2 version: 4.0.2

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html) (Inital values seems to be the same, however the placeholders seem to work.)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](http://jsbin.com/baxuvaboce/1/edit?html,console,output)

**Comment by kevin-brown** [comment]
https://select2.github.io/options.html#my-first-option-is-being-displayed-instead-of-my-placeholder

If you search for "placeholder option" in this ticket tracker, you'll find a few threads which have some detailed explanations for why we can't avoid the blank option for the placeholder.

**Comment by RobertDiebels** [comment]
@kevin-brown Thank you for the feedback! I did not realize that this was required for the placeholder to work properly. Thank you!
