### ISSUE TITLE
Invalid US-ASCII character "\xC2" when building docs

### ISSUE THREAD

**Issue by apit** [select2/select2#4277]
## Steps to reproduce the issue

`grunt docs`
## What i see

```
Conversion error: Jekyll::Converters::Scss encountered an error while converting '/css/s2-docs.scss':
Invalid US-ASCII character "\xC2" on line 21
```

```
pcregrep --color='auto' -n "[\x80-\xFF]" docs/_sass/*
docs/_sass/_footer.scss:21:      content: "��";
```
## Environment

master branch 120672d
osx 10.11.4

**Comment by apit** [comment]
fix this issue simply by using equiv ascii char, '.'

**Comment by kevin-brown** [comment]
The docs should be built using UTF-8 (on *nix) or Windows-1252 (on Windows). This is something we may need to document in `docs/README.md`.

**Comment by alexweissman** [comment]
The old docs have been removed and replaced with https://github.com/select2/docs, so I am closing this issue.
