### ISSUE TITLE
(Feature) Setting disabled option as a value does not show the value as diabled (multiple)

### ISSUE THREAD

**Issue by RobertDiebels** [select2/select2#4279]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Create a select element and some options of which one is disabled.
2. Initialize select2 on the element.
3. Set the values to contain the disabled option.
## Expected behavior and actual behavior

When I follow those steps, I see...

That the values are being selected and shown.

I was expecting...

To have a way to differentiate between which value is a disabled one and which is not.
In this case it would be nice to have a class on the li-element representing the option, that shows that the corresponding option has been disabled.

If take a look at this url: http://jsbin.com/ludamalepi/edit?html,output

I would expect that the tag (the li ) would have something like a border, or be grayed out. Or that I can customize it by altering the CSS associated with a disabled value (li ).
### Reasoning

The reason we would like to do this is because we use select2 in forms where data that was previously avaible, could have been removed. So when we have stored a value that has been removed elsewhere, we feed select2 with data and mark the data that has been removed/marked inactive/temporarily disabled as disabled.

However it might have been that the value has not been removed/marked on purpose. So the user needs to know that this value has been removed by viewing the tags in the field. Not just in the dropdown.

I realize that the disabled values are not provided when I call .val() (which is expected). However, due to the fact that the disabled value may have been temporarily disabled or not purposely marked inactive we need to give feedback about this to the user (they need to know that the value they submit will not be submitted if it has been disabled elsewhere).

I hope this makes sense. If not, I will be happy to clarify.
## Environment

Browsers
- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 2.1.4
- Select2 version: 4.0.2
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](http://jsbin.com/ludamalepi/edit?html,output)

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/select2/select2/issues/3347.

**Comment by RobertDiebels** [comment]
@kevin-brown I'm sorry but I don't see how the two issues are "duplicates". My problem is with setting a value that has been disabled and marking it as a disabled item in the field itself. So you do show the item, it just isn't retrieved when you get the values. 

The issue you linked has a different set of properties (as far as I can see). I would love to contribute some code in order to get this into select2 (we use it quite extensively).

However that would mean that you would have to mark it as an open bug and not a duplicate. Again, I might be missing something but the two issues seem unrelated in their purpose. Maybe the underlying problem is similar but the purpose is not. 

Also, I would like to thank you for your efforts maintaining this library :).

**Comment by kevin-brown** [comment]
I'm going to temporarily reopen this ticket pending a closer look at what's trying to be achieved.

**Comment by RobertDiebels** [comment]
@kevin-brown Maybe this will help clarify things a bit.

Say I've got this dataArray: 

```
data: [
{text: "Some text", id: 0},
{text: "Some text", id: 1, disabled: true },
{text: "Some text", id: 2 },
{text: "Some text", id: 3, disabled: true }
]
```

If we provide select2 with two values of which one is disabled with `.val(["0","1"]).change();` we can see the two corresponding tags in the multiple (which is what we want!). However we are not able to discern which tag has been disabled and which has not.

I've created a jsbin to further illustrate my point: http://jsbin.com/yafesuxoji/edit?html,output

So what would be awesome is if the disabled tag (representing the disabled value) either got a class showing that it has been disabled something like: ".select2-disabled-tag". Or any other means of tracing whether it has been disabled or not. Maybe something like and id that references the value id it started with. In my examle it could be something like `id="select2_value_id_1"` or something of the sort.

Just as long as we can show our users that the tag was previously select but now no longer exists or has been disabled.

In our case it would specifically be about setting a value that does not exist in the data. So you could even think about a class that just marks it as a value that does not exist in the dataArray.
It would be the responsibility of a select2 user (not the end-user) to assess whether the value they are inserting is actually in the data or not before inserting. 
Select2 would only have to show that the the value that has been given to it does not exist in the data (or has been marked as disabled).

If this is something you would rather not do we can always insert the missing data into the dataArray and mark them as disabled.

In either case we need to know if the value select2 shows has been disabled (or no longer exists) just by looking at the tag. 

Again I'd be happy to create a pull request with a possible solution but the community would have to mark this feature request as desirable.

I believe there is a use case for it (as my employer has one).
