### ISSUE TITLE
Jquery mobile filterable selects 

### ISSUE THREAD

**Issue by xenoborg007** [select2/select2#4283]
So we have a new release, which is a complete rewrite and yet mobile / touch UI still hasn't been addressed. The only real reason to use select2 and its competitors is for the search function and yet that feature is still abysmal and impossible to use on touch devices.

I am currently in the process of trying to force switch to jquery mobiles custom select boxes when on mobile devices, which is a stupid workaround to what should be a standard feature for Select2.

Can we get what jquery mobile has functionality wise in a future Select2 preferably sooner rather than later.
http://demos.jquerymobile.com/1.4.5/selectmenu-custom-filter/

**Comment by alexweissman** [comment]
There are a number of issues already open about reported problems with the virtual keyboard on mobile devices.  See https://github.com/select2/select2/issues?q=is%3Aissue+is%3Aopen+label%3A%22mobile%3A+iOS%22
