### ISSUE TITLE
Consider using tether.js for positioning the dropdown

### ISSUE THREAD

**Issue by 719media** [select2/select2#4285]
Bootstrap 4 is using tether.js for tooltip/etc. positioning. This plugin is extremely versatile and well developed.

http://github.hubspot.com/tether/

I think select2 could offload the positioning process to such a library.

**Comment by kevin-brown** [comment]
I'd _love to_, but we can't

http://github.hubspot.com/tether/overview/why_we_dont_support_ie_8/

Select2 still supports IE 8.
