### ISSUE TITLE
Uncaught TypeError: m.css is not a function in V4.0.2

### ISSUE THREAD

**Issue by e11en** [select2/select2#4289]
I upgraded from 4.0.1-rc.1 to 4.0.2 but now I get the following error : 
##### Uncaught TypeError: m.css is not a function @ select2.min.js:2
It happens on all browsers and OS's, I've got jQuery v1.11.3.

This is my code to call the select2:
```
var $brandSelector = $('#brand').select2({
        ajax: {
            url: function(params){
                return '/api/brands';
            },
            dataType: 'json',
            delay: 250,
            processResults: function (data, params) {
                var select2Data = $.map(data, function (obj) {
                    obj.text = obj.name;
                    delete obj.name;
                    return obj;
                });
                return {
                    results: select2Data
                };
            },
            cache: false
        },
        language: appLocale,
        escapeMarkup: function (markup) { return markup; },
        placeholder: '{{trans('main.brand')}}',
        minimumInputLength: 1,
        dropdownParent: "#compareTab",
        templateResult: formatBrands,
        templateSelection: formatBrandSelection
    });
```

Did I do something wrong?
Thanks in advance!

**Comment by kevin-brown** [comment]
If you could get us the stack trace that is triggered when you are using the non-minified build of Select2. The stack trace for the minified build is pretty much useless, because it hides pretty much all of the debugging information.

My _guess_ is that you need to pass in `dropdownParent` as `dropdownParent: $('#compareTab')`, because Select2 is most likely expecting the parent to be a jQuery/DOM object.

**Comment by e11en** [comment]
Indeed it was the <code>dropdownParent</code>, thanks for the help.

For any other people here is the stack trace any way.
```
Uncaught TypeError: $offsetParent.css is not a function       select2.js:4211

AttachBody._positionDropdown	@	select2.js:4211
(anonymous function)	@	select2.js:580
AttachBody._showDropdown	@	select2.js:4263
(anonymous function)	@	select2.js:580
(anonymous function)	@	select2.js:4066
Observable.invoke	@	select2.js:623
Observable.trigger	@	select2.js:613
Select2.trigger	@	select2.js:5331
(anonymous function)	@	select2.js:5226
Observable.invoke	@	select2.js:623
Observable.trigger	@	select2.js:613
Select2.trigger	@	select2.js:5331
Select2.open	@	select2.js:5351
Select2.toggleDropdown	@	select2.js:5342
(anonymous function)	@	select2.js:5169
Observable.invoke	@	select2.js:623
Observable.trigger	@	select2.js:613
(anonymous function)	@	select2.js:1487
m.event.dispatch	@	jquery.js:4
r.handle	@	jquery.js:4
```

**Comment by ngoduykhanh** [comment]
Hi @e11en , how did you solve this problem?

**Comment by gabn88** [comment]
Does this mean that it cannot be given as a data-* attribute in the HTML? :(

**Comment by natecox** [comment]
@gabn88 were you able to find out if we can still give this as a data attribute?

**Comment by orioljd** [comment]
I tried to use as data attribute and gives this error

**Comment by truongngoctuan** [comment]
If you want to make data attribute work, you need to update data-dropdown-parent to jquery object.
Like this:
```javascript
            if (rawOptions.dropdownParent) {
                $elt.data("dropdown-parent", $(rawOptions.dropdownParent))
            }
```
because the function `Options.prototype.fromElement` will go through all data atttributes and add this data attr back, even though we specified in the option.

**Comment by alexweissman** [comment]
Is `dropdownParent` the only configuration setting that has this problem?

**Comment by renatodeleao** [comment]
Still having the problem using `dropdownParent` as `data-attr` (`data-dropdown-parent`). Solved by using a custom attribute name, and checking on initialization

```html
<--! note don't use data-dropdown-parent -->
<select data-select2 data-select2-dd-container="#myContainer" >
```
```javascript
$('[data-select2]').each(function() {
  var $this = $(this);
  // [1]
  var ddParent = $( $this.data('select2-dd-container') || document.body )
  $this.select2({
    minimumResultsForSearch: 4,
    dropdownParent: ddParent
  });
});
```

```shell
macOS High Sierra 10.13.4
select2 v4.0.3
```

**Comment by tamim-ikbal** [comment]
> If you could get us the stack trace that is triggered when you are using the non-minified build of Select2. The stack trace for the minified build is pretty much useless, because it hides pretty much all of the debugging information.
> 
> My _guess_ is that you need to pass in `dropdownParent` as `dropdownParent: $('#compareTab')`, because Select2 is most likely expecting the parent to be a jQuery/DOM object.

Thanks a lot
