### ISSUE TITLE
Make Multi-Select to show dropdown on mouse down rather mouse click

### ISSUE THREAD

**Issue by robert-kc-liu** [select2/select2#4295]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Mouse down on a multi-select box
## Expected behavior and actual behavior

When I follow those steps, I see no drop-down.

I was expecting drop-down to show on mouse down so the behaviour is the same as Single-Select.
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System
- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

Libraries
- jQuery version:
- Select2 version: 3.5.2
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
This appears to be the same problem described in #4642.
