### ISSUE TITLE
Documentation for `matcher` option

### ISSUE THREAD

**Issue by daslicht** [select2/select2#4296]
Hi, 
I am using select2 to autocomplete a List of Countries. Is there a way to restrict search results to the start of the word ? This makes it more clear:
![](http://i.imgur.com/CICQoeS.png)
If I type `Ger` I want all hits which starts, well... with Ger

Is there an option for this please?

**Comment by daslicht** [comment]
https://select2.github.io/examples.html#matcher

**Comment by daslicht** [comment]
I just saw that the matcher changed from 3 to versuion 4.

Where do I find  an example of the following matcher written for version 4 without compat mode please:
```https://select2.github.io/examples.html#matcher```

**Comment by RomainLanz** [comment]
How can we achieve that without using AMD require style?

**Comment by fetis** [comment]
I came across the same question and after digging into the code the answer is next:

New matcher function accepts 2 arguments, boths are object
`matcherFunc (params, data)`

`params.term`  contains search text
`data` is object search against to. `data.text` is display text.

If term matches the text, return **all** data object. If not return `null`.
I hope it helps

**Comment by alexweissman** [comment]
This is done.  See the new documentation site: https://select2.org/searching#customizing-how-results-are-matched
