### ISSUE TITLE
select2 with a button on its side

### ISSUE THREAD

**Issue by joomlaA1** [select2/select2#4299]
can we have an option for select2 that would make it  look like this:
http://v4-alpha.getbootstrap.com/components/input-group/#button-addons

wherein the input element there would be replaced by a select2 element

i would use it as a filtering search button (i would pop up a modal with many filters available)

thanks

**Comment by kevin-brown** [comment]
You may be interested in the [Bootstrap theme](https://select2.github.io/select2-bootstrap-theme/).

**Comment by joomlaA1** [comment]
thanks

now i'm using bootstrap theme
and bootstrap 3.6 and select2 4

it's good

but after i resize the browser to some smaller width

![dfff](https://cloud.githubusercontent.com/assets/13029902/14632824/389db6a6-064d-11e6-8bfd-3078de0cfbb4.png)


is it inevitable

**Comment by joomlaA1** [comment]
can i also concern about this... (do you think maybe this is bootstrap 3.6 fault...?)

![edddd](https://cloud.githubusercontent.com/assets/13029902/14632853/5de36c30-064d-11e6-994d-229a45eefc67.png)

in 3.5, input is fine,... enough space for the placeholder text

in 3.6 there is this white square that blocks most of the input field... thanks...
