### ISSUE TITLE
Form fields disappear when select2 dropdown is clicked

### ISSUE THREAD

**Issue by Kunal92GitHub** [select2/select2#4300]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue

## Steps to reproduce the issue

1. Click on a page to open a popover(in lightbox view)
2. The popover contains a select2 dropdown(alongwith other input fields)
3. Click the select2 dropdown

## Expected behavior and actual behavior

When I follow those steps, I see 'The remaining form fields(other than select2)  disappear.'

Before Click - 

![image](https://cloud.githubusercontent.com/assets/18418322/14457972/e91f1dda-00cb-11e6-9a50-e7efeb5c1a94.png)

After Click -
![image](https://cloud.githubusercontent.com/assets/18418322/14457897/7c0d621a-00cb-11e6-9f8f-060b38a660c1.png)

I was expecting 'The remaining form fields to stay'.

## Environment : Jboss server.

Browsers
- [ ] Internet Explorer (Version 11.0.29)

Operating System

- [ ] Windows - 7 Enterprise

Libraries

- jQuery version: 1.8.2
- Select2 version: 3.4.2

## Isolating the problem

- [ ] The bug happens only on IE(version 11) browsers

**Comment by kevin-brown** [comment]
> Select2 version: 3.4.2

This version of Select2 is no longer supported. It was [released on August 12, 2013](https://github.com/select2/select2/releases/tag/3.4.2) and is **severely out of date**.

I would highly recommend upgrading to Select2 3.5.4 or 4.0.2 if possible.
