### ISSUE TITLE
Multiselect progmatic population of data does not appear to work in 4.0.2

### ISSUE THREAD

**Issue by abascueomni** [select2/select2#4302]
I have been attempting to upgrade my organization from 3.5.2 to 4.0.2 and while frustrating have been experiencing good progress until I ran into this issue. We prepopulate some of our multiselectable select boxes and seem to be unable to do this now in 4.0.2. 
The line of code that allows us to do this looks like this;
`$("#e1").select2('data',[{id:"Am",text:"Amalapuram"}]);`
Here is a jsfiddle running on 3.5.2 http://jsfiddle.net/k2w59LLr/4/ 
which is able to pre-populate the data for the select box and here is that same multiselect running on 4.0.2 but not populating progmatically. 
http://jsfiddle.net/k2w59LLr/5/

Perhaps as I am young I just haven't found the right way to do this but after talking to my coworker who is much more experienced than I am we could not come up with a solution. I searched the issues and google to try to find a way to do this and failed. He suggested I open a ticket in hopes of either a fix or someone more experienced than I being able to provide a solution.

Thanks!

**Comment by kevin-brown** [comment]
`.select2('data')` is read-only in Select2 4.0. You can no longer modify the internal data for Select2 by passing in custom data objects using it.

Instead you should be creating the `<option>` tags manually, and marking them as selected. Select2 will pick these up (trigger `change` if needed) and it will have the same effect.

http://stackoverflow.com/q/30150341/359284
