### ISSUE TITLE
select2 v4 - defaulting to placeholder upon init

### ISSUE THREAD

**Issue by temuri416** [select2/select2#4305]
Hi,

select2 defaults to first available option, even when combo's value is NULL or its selectedIndex property is -1. Instead, I'd expect to see its placeholder.

```
<select id="el" style="width:300px">
    <option value="1">United States</option>
    <option value="2">Canada</option>
</select>

<script>

$('#el').val(null); // Or set selectedIndex to -1.

$('#el').select2({
    allowClear: true,
    placeholder: '(select...)'
});
</script>
```

As a result, select2 is rendered as:

![image](https://cloud.githubusercontent.com/assets/3987203/14504942/f2160d86-0184-11e6-99c6-0878f4d4c17d.png)

However, I expect it to look as:

![image](https://cloud.githubusercontent.com/assets/3987203/14505037/6a2fc078-0185-11e6-950d-a8ef1727443a.png)

It seems that there is no way to force select2 to default to placeholder value (i.e. do not render first available option when combo has no value).

StackOverflow link: [http://stackoverflow.com/questions/36606622/select2-how-can-i-init-and-default-to-placeholder-when-no-value-is-selected](url)

Thanks!

**Comment by kevin-brown** [comment]
https://select2.github.io/options.html#my-first-option-is-being-displayed-instead-of-my-placeholder

There is no way for Select2 to detect that the placeholder is shown if you don't have a placeholder option. The first option is automatically selected by the browser, Select2 is just reflecting this fact.
