### ISSUE TITLE
$(this).data() not working for select2 element under ajax data

### ISSUE THREAD

**Issue by anupalusoft** [select2/select2#4308]
Hi,

Now updated the the latest version 4.0.0 and having problem to access the data attributes of select element. Before in previous version is was working fine.

HTML code:
`<select name="cause_id" class="form-control select_cause" data-type="1"></select>`
Here is my jQuery code:

    $(".select_cause").select2({ 
            placeholder: "Search reason...",
            allowClear: true,
            width: "off",
            delay: 250,
            minimumInputLength: 1,
            ajax: {
                url: baseUrl + '/Causes/selectSearch',
                dataType: 'json',
                data: function(params) {
                    return {
                        term: params.term,
                        type: $(this).data('type')
                    };
                },
                processResults: function (data, page) {
                    return { results: data };
                }
            }
        });

It return undefined on `type: $(this).data('type')`.

**Comment by kevin-brown** [comment]
> latest version 4.0.0

4.0.0 isn't the latest version, 4.0.2 is. This distinction is important because this bug was fixed in https://github.com/select2/select2/commit/3037b933e271a51b52e77ca55936e503c7467a81, which landed in 4.0.1.

**Comment by anupalusoft** [comment]
@kevin-brown Thanks :+1:
