### ISSUE TITLE
Duplicate FAQ entry

### ISSUE THREAD

**Issue by guettli** [select2/select2#4313]
The FAQ contains the same topic twice:

https://select2.github.io/options.html#how-many-levels-of-nesting-are-allowed

https://select2.github.io/options.html#how-many-levels-of-nesting-can-there-be

**Comment by kevin-brown** [comment]
This is intentional, because of how nested objects for a standard `<select>` and data objects are specified it might not be clear that both of them have the same limitation. One of them is imposed by the HTML specification, and the other is (mostly) imposed by us.

**Comment by alexweissman** [comment]
I believe I've clarified this in our new docs: https://select2.org/options#dropdown-option-groups
