### ISSUE TITLE
404 errors in Google search console

### ISSUE THREAD

**Issue by goldweb** [select2/select2#4314]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question
- [x] I have attempted to find the simplest possible steps to reproduce the issue, but no result.

## Steps to reproduce the issue

1. Google bot scanning some page of my website.
2. Detecting 404 errors mainly related to select2 js plugin.

**404 url errors like:**

- someUrl/dropdown/selectOnClose
- someUrl/selection/search
- someUrl/data/maximumSelectionLength
- someUrl/data/maximumSelectionLength
- someUrl/data/maximumSelectionLength
- someUrl/select
- someUrl/selection/eventRelay
- someUrl/dropdown/closeOnSelect
- someUrl/selection/placeholder
- someUrl/selection/search
- someUrl/selection/single
- someUrl/selection/multiple
- someUrl/selection/allowClear
- someUrl/select2/defaults
- someUrl/select2/core/
- etc...

I have writed to google today too, so no answer yet.

**Maybe some guys, was have similar issues?**

## Environment
Google search console
Operating System
Google bot logic

- jQuery version: jquery-2.1.4
- Select2 version: Select2 4.0.2-rc.1
- Using templating, from underscore.
- All javascript logic is not in separeted js files, but pulled directly into html source into script tag.

## Isolating the problem

- [x] This bug happens on every page of my website(for google bot).
- [x] When I testing, the bug not happens consistently across all tested browsers.
- [x] I can not reproduce this bug in js bin. Website is little secret.

**Comment by goldweb** [comment]
I think this is not select2 problem. So closing this.

**Comment by kevin-brown** [comment]
For some reason Google is interpreting the internal Select2 module paths as external modules, and is trying to load them. This is a bit strange considering no code exists to resolve the internal paths to external files, and we don't package any map files which would possibly cause this.

This isn't something Select2 can solve, this is a Google Search Console issue.

**Comment by goldweb** [comment]
So. how we must reacting on this? Somehow contact with google support? Or is some other way?

**Comment by kevin-brown** [comment]
> So. how we must reacting on this?

Ignoring it is always an option. Assuming you are doing nothing strange, these should be 404 errors _in theory_ rather than _in reality_.

If more people start to see similar errors, then we can start pooling together reports and we might be able to come up with a fix on Select2's side. Until then, there is honestly nothing that Select2 can do here.

**Comment by goldweb** [comment]
Okay, so will be waiting for news.

**Comment by rrbairar** [comment]
Any update on this? Please help in this.
