### ISSUE TITLE
hidden option navigation with keys

### ISSUE THREAD

**Issue by 719media** [select2/select2#4316]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Instantiate a select2 on a multiple select input. Create a css rule to hide selected options, such as:
``
.select2-results__option[aria-selected=true] {
  display:none;
}
``
2. select a few options
3. notice that the arrow key navigation still treats the hidden options as "there"

## Expected behavior and actual behavior

Arrow key movement should not be affected by hidden options

**Comment by 719media** [comment]
I made a comment on #4105 about this same issue and decided to make a new issue about it

**Comment by kevin-brown** [comment]
I'm going to merge this back into https://github.com/select2/select2/issues/4105. Select2 requires that options are still in the keyboard navigation, even if they are hidden, in order to maintain accessibility.
