### ISSUE TITLE
Select2 shows hidden and disabled options

### ISSUE THREAD

**Issue by chrisspen** [select2/select2#4317]
If you hide or disable an option and then trigger a change event, select2 still shows and allows you to select the option. This breaks its compatibility with the default select box.

**Comment by kevin-brown** [comment]
This is a duplicate of https://github.com/select2/select2/issues/3347.

**Comment by dkwebtec** [comment]
#3347 is just about disabled options

Select2 still shows hidden options (display:none on original <option>)
