### ISSUE TITLE
Select2 translation issue

### ISSUE THREAD

**Issue by Schlogen** [select2/select2#4321]
I can't reproduct this bug in a JSbin or on the examples page, however any help in understanding why would be appreciated. Must be something with my environment.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Initialize a select2 dropdown with ajax and no translation settings
2. View the loading text after entering data in the search box

## Expected behavior and actual behavior

When I follow those steps, I see...
"Searchingâ€¦"

I was expecting...
Searching...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.2.2
- Select2 version: 4.0.2

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kevin-brown** [comment]
This sounds like an encoding issue somewhere, either on the page where you are displaying Select2 or in the translation file. We use the ellipsis character, which isn't part of the ASCII character set (I recommend `utf-8` when possible), so if you are using an encoding which doesn't support it you might see a different character there.

**Comment by leoshaw** [comment]
In case this helps anyone, I had this issue when I copy-pasted the script from the CDN, e.g. `https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.1/js/select2.js` rather than downloading from the release pages e.g. `https://github.com/select2/select2/releases/tag/4.0.5`, which is what the docs tell you to do 😜
