### ISSUE TITLE
Error when closing dropdown when select2 imported as a module

### ISSUE THREAD

**Issue by adambrenecki** [select2/select2#4327]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Import Select2 as a module, rather than as a jQuery plugin (eg using Webpack):
   
   ``` js
   var Select2 = require('select2')
   var $ = require('jquery')
   ```
2. Open a Select2 dropdown
3. Click outside of the dropdown to close it
## Expected behavior and actual behavior

When I follow those steps, I see the error `base.js:135 Uncaught TypeError: $element.select2 is not a function` in the JS console, and the dropdown stays open.

I was expecting the dropdown to close.
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System
- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries
- jQuery version: 2.2.2
- Select2 version: 4.0.2 (also happens in master)
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

---

This looks like it's a one-line fix, as soon as I can get the tests to run I'll file a PR.

**Comment by alexweissman** [comment]
Triggering events can lead to unintended side effects.  Are you sure this is the only way to handle the issue?

**Comment by adambrenecki** [comment]
This ticket and PR is nearly two years old, and since Select2 is no longer used on the project I was on when I came across this bug and I no longer work at the company that project was for, I haven't touched Select2 in a long while. So I have no idea, sorry :(

**Comment by alexweissman** [comment]
No problem, thanks for letting us know!
