### ISSUE TITLE
Integrate maximize-select2-height with select 2

### ISSUE THREAD

**Issue by ar-anvd** [select2/select2#4330]
I found this plugin really useful, so, I am thinking why not integrate this by default with select2?

https://github.com/panorama-ed/maximize-select2-height

**Comment by kevin-brown** [comment]
I can create a section in the README for plugins, like we have for integrations. But this project wouldn't be added right away...

- [ ] Missing a license
- [ ] Not bundled as a module

**Comment by DmonteiroD** [comment]
@kevin-brown The author of the plugin uses MIT License as you can see [here](https://github.com/panorama-ed/maximize-select2-height/blob/master/maximize-select2-height.min.js). 

thx

@JacobEvelyn

**Comment by JacobEvelyn** [comment]
@DmonteiroD thanks for the interest!

@kevin-brown I'll add a `LICENSE.txt` file to be clearer about the licensing. I don't have a ton of experience with JS modules—are you referring to an `npm` module or something else?

**Comment by spAnser** [comment]
Doesn't appear to work unless you define it with an ID selector.

**Comment by JacobEvelyn** [comment]
@spAnser if I remember correctly that limitation can be removed; it was just convenient for how it was initially written.
