### ISSUE TITLE
Cannot paste into select[multiple]

### ISSUE THREAD

**Issue by kjprice** [select2/select2#4333]
## Steps to reproduce the issue

Using the [demo page], right click (almost) anywhere in the `multiple select box` control and the option to _paste_ is not available.

![image](https://cloud.githubusercontent.com/assets/2319673/14930715/acb84b56-0e2b-11e6-8537-5f21a016f37f.png)
## Expected behavior and actual behavior

When right clicking within the `single select box` you are able to find the _paste_ option under the context menu.

![image](https://cloud.githubusercontent.com/assets/2319673/14930723/bfca7a16-0e2b-11e6-9aa7-6e09bf6a0712.png)

However, with the `multiple select box` there is no option for `paste`. The reason for this is that the actual `input` is very tiny and the chances of right-clicking on it are very slim.

![image](https://cloud.githubusercontent.com/assets/2319673/14930763/1616eea4-0e2c-11e6-9983-daa46f2c1743.png)
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System
- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

Libraries
- jQuery version: 1.11.2
- Select2 version: 4.0.2
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by pprins** [comment]
We have this problem, the input box has a 2 pixels width. Unless you can find the tiny input you paste on an UL element which is not possible of course.

You can make a workaround with some css:
`.select2-selection--multiple .select2-search--inline, .select2-selection--multiple .select2-search--inline input {
    width:100% !important;
}`

It's not beautiful but it works for us.

**Comment by kjprice** [comment]
Thanks for sharing @pprins, I forgot to show our implementation. 

We ended up doing something similar. It is not as effective as the snippet above, but it only makes `select2-search--inline` 100% width if it is the _only_ child of the surrounding `ul`. The `input` however, always fills the `select2-search--inline`, which seems to always make a lot of sense.

```
.select2-search--inline:first-child {
	width: 100%;
}

.select2-container li.select2-search--inline input {
	width: 100% !important;
	height: 100%;
	margin-top: 0px;
}
```
