### ISSUE TITLE
Add documentation on how to programmatically access a selection data

### ISSUE THREAD

**Issue by senotrusov** [select2/select2#4334]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue

I'm sending you the pull request containing a documentation on how to programmatically access a selection data.

As the current documentation lack that topic I'm not sure about the methods I use. Perhaps the internals was exposed and that can't be the part of public API.

Please let me know if I can improve that documentation topic.

Thank you.

**Comment by romgrk** [comment]
Hello,
My comment is essentially a +1 on this, but I'd like to insist on the fact that the current state of the documentation is totally horrific. You need to have a proper Reference section, where the API and it's implications are clearly defined. I've been struggling for hours to understand how to do this, and the most effective way is still to go through the full source; not cool.
Besides, most StackOverflow solutions are at best hacky, and the vast majority of them is pre 4.0. If you do maintain this, keep the documentation relevant.

**Comment by kevin-brown** [comment]
> but I'd like to insist on the fact that the current state of the documentation is totally horrific.

Please, I encourage you to work with us to make it better. Select2 is maintained on a volunteer basis, and there's only so much time in the day/week/month for all of us to volunteer.

> You need to have a proper Reference section, where the API and it's implications are clearly defined.

We would welcome a pull request which would start a movement in this direction. Ideally, we'd prefer an automated solution to API documentation, but we would entertain a manual solution as it's still a solution to the problem.

**Comment by SgtOddball** [comment]
Automated solution to API documentation? What madness is this? (Seriously, I've not come across any way of doing that sort of thing and would be genuinely intrigued as bad documentation is long term bugbear of mine since I learned my craft.... that and ie6 but we don't talk about ie6 anymore).

**Comment by alexweissman** [comment]
This is now available at our new docs site: https://select2.org/programmatic-control/methods#retrieving-the-selected-values
