### ISSUE TITLE
Wrong link in Documentation (tokenSeparator)

### ISSUE THREAD

**Issue by SimonRingeisen** [select2/select2#4341]
## Steps to reproduce the issue
1. Visit https://select2.github.io/examples.html#tokenizer
2. click on tokenSeperators options (https://select2.github.io/options.html#tokenSeparators)
## Expected behavior and actual behavior

Should show the documentation, but doesn't. There is even no reference on the page about 'token' or 'seperator'.
## Environment
- [x ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [ x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

**Comment by alexweissman** [comment]
Thanks - I think we can fix this by adding the new page suggested by #4692.

**Comment by alexweissman** [comment]
This is now covered on the new documentation site: https://select2.org/tagging#automatic-tokenization-into-tags
