### ISSUE TITLE
Select2 multiple box placeholder not showing on hide then make it visible case

### ISSUE THREAD

**Issue by sambsa** [select2/select2#4343]
I am using select2() in select multiple. What I have is a placeholder in that select. What I am doing is initially I am hiding the select containing div and then I am making it visible. In this case initially placeholder not showing.

If we are not doing this hide and block thing then it is working fine.

Please check the fiddle [http://jsfiddle.net/fyhsz9ra/447/](http://jsfiddle.net/fyhsz9ra/447/)

**Comment by kevin-brown** [comment]
This is a known issue in older versions of Select2. Select2 could not calculate the width of the placeholder because browsers can't calculate the size of hidden elements.

**Comment by sambsa** [comment]
Is it fixed in new version?

**Comment by Tuning-Soft** [comment]
+1 placeholder not showing!
