### ISSUE TITLE
templateResult gets stale "selected" flag

### ISSUE THREAD

**Issue by wirk** [select2/select2#4351]
When using a templateResult function in conjunction with an external setter on the select, the templateResult function is passed an outdated value of the `selected` flag if the option was programatically toggled in the meantime, even if the `change` event was properly triggered.

I have created a fiddle to demonstrate the issue.
https://jsfiddle.net/e1fy1chs/2/

**Comment by kevin-brown** [comment]
You should prefer the value of `data.element.selected` over the value of `data.selected`. The `data.selected` property is an internal value only used when we don't have access to `data.element`, and as a result it is not always up to date.

**Comment by wirk** [comment]
Cheers, that worked like a charm.
