### ISSUE TITLE
Window jumps when dropdown is closed

### ISSUE THREAD

**Issue by cdukes** [select2/select2#4353]
This is reproducible on any Select2 v4 instance, [for example](https://select2.github.io/examples.html):
- Click to open the example select2 box under "Single select boxes"
- Leave the dropdown open and scroll down, so that the dropdown is out of view
- Click anywhere on the page
- You get jumped back up to the select box, and the element you clicked on doesn't fire 

(I used Chrome 50, but I think this is the case everywhere)

I've seen other tickets about clicking outside dropdown, but none that pertain to v4 and have a solution.

I think it's not obvious to the user that leaving the dropdown open will cause issues for you down the page. I can think of a couple possible solutions:
- Show a background mask on everything but the select2 box and dropdown
- Allow clicks outside the dropdown to propagate normally
- Lock scrolling while the dropdown is open (like a normal <select> element does)

**Comment by prakal** [comment]
Thanks @cdukes for reporting this issue. I would side with either of these two possible solutions:

- If scrolling leads to the dropdown no longer being visible on the screen, it should be closed, and the view should **not** jump up to the dropdown
- Lock scrolling while dropdown is open (as per @cdukes suggestion)

**Comment by prakal** [comment]
Temporary fix in place (PR #4360 ) so that:
- the view does not jump to the destroyed dropdown container. 

We can huddle over another fix/option if this doesn't meet expectations.

**Comment by ysorin** [comment]
Was the demo updated with the fix? It is still not working properly on the demo page.

**Comment by prakal** [comment]
@ysorin : I submitted a pull request for this fix, just waiting on @kevin-brown to merge if its ok.

**Comment by Olefine** [comment]
@kevin-brown any progress about merging it?

**Comment by NeoGenet1c** [comment]
Still an issue. Is there any reason why this hasn't been merged?

**Comment by alexweissman** [comment]
I'm wary of merging the proposed fix...why was that one line there in the first place?

**Comment by f4ndor** [comment]
Temporary fix without modifying source:
`
$thissel.on("select2:closing", function (e) {
    $thissel.next('.select2').hide();
});
$thissel.on("select2:close", function (e) {
    $thissel.next('.select2').show();
});
`
