### ISSUE TITLE
  Select2#open() causes redundant Results#setClasses() before dataAdapter#query().

### ISSUE THREAD

**Issue by fengdh** [select2/select2#4359]
## My Environment

Browsers
- Google Chrome

Operating System
- Windows

Libraries
- jQuery version: 2.2.2
- Select2 version: 4.0.2

This issue will effect Select2 4.0.2 crossing different browser/OS.
## Steps to reproduce the issue

At first defining a SELECT element with Select2 default options. 
1. Open Developer Tools on Chrome.
2. Set break point at the beginning of `Results.prototype.setClasses`.
3. Click dropdown icon to open options list.
4. `Results.prototype.setClasses()` is called twice, where the first one is redundant.
## Expected behavior and actual behavior

Source code and call stack shows that:

**1.** `Select2.prototype.open()` will trigger `'query'` event.

```
Select2.prototype.open = function () {
  if (this.isOpen()) {
    return;
  }

  this.trigger('query', {});
};
```

**2.** Inside `Select2.prototype._registerEvents`, `query` event handler will 
  **(1)** first trigger `open` event,
  **(2)** and then call `this.dataAdapter.query()`.

```
this.on('query', function (params) {
  if (!self.isOpen()) {
    self.trigger('open', {});
  }

  this.dataAdapter.query(params, function (data) {
    self.trigger('results:all', {
      data: data,
      query: params
    });
  });
});
```

**3.** In `Results.prototype.bind`, the `open` event handler will call `self.setClasses()` redundantly.

```
Results.prototype.bind = function (container, $container) {
...
container.on('open', function () {
  // When the dropdown is open, aria-expended="true"
  self.$results.attr('aria-expanded', 'true');
  self.$results.attr('aria-hidden', 'false');

  self.setClasses();
  self.ensureHighlightVisible();
});
```

**4.** Because `dataAdapter.query()` is supplied with a callback triggering `result:all` event, which will call `self.setClasses()` finally after data being queried. 

```
Results.prototype.bind = function (container, $container) {
...
container.on('results:all', function (params) {
  self.clear();
  self.append(params.data);

  if (container.isOpen()) {
    self.setClasses();
  }
});
```
### My Conclusion

IMHO, `this.setClasses()` in **3.** is definitely redundant which can be removed safely.

**Comment by kevin-brown** [comment]
It makes sense for `setClasses` to be called in the `resullts:all` event, because the results probably changed in the process.

But I'm not sure about the `open` event. This may have been to ensure the first (selected) result was highlighted.

**Comment by fengdh** [comment]
Whether SELECT element is open or not,` results:all` event will be triggered anyway that ensures highlighting results correctly.

And `open` event is be triggered once only if SELECT element is **not open** inside `query` event handler. Is it really necessary to call setClasses() at this time? setClasses() calls dataAdapter#current(), which is what I concerned.
