### ISSUE TITLE
Browser navigates when clearing the selection using backspace

### ISSUE THREAD

**Issue by Stadly** [select2/select2#4365]
When clearing the selection using the backspace key, the browser navigates to the previous page. Tested on Windows, using Chrome, Firefox, IE, Vivaldi. Can easily be tested on the [examples page](https://select2.github.io/examples.html#placeholders).

**Comment by kevin-brown** [comment]
I was not able to reproduce this on Chrome 50 on Windows 10, though I was able to reproduce it in Edge 13. Using the delete key (which I thought was our only binding) does not cause any issues.

**Comment by tatesn** [comment]
I am definitely seeing this issue with the latest 4.0.3 build in IE 11 when tags are enabled. I also tested Chrome in Windows and OS X and did not see this issue.

**Comment by JiDai** [comment]
I reproduced the bug on chrome Version 53.0.2785.116 on OSX

**Comment by alexweissman** [comment]
Duplicate of #3168.
