### ISSUE TITLE
Combining a placeholder with an extra `<option>`-element and `allowClear` in a multiple-select

### ISSUE THREAD

**Issue by Stadly** [select2/select2#4367]
For single-selects, an extra `<option>`-element is required for the placeholder to work. When specifying such an extra `<option>`-element in a multiple select with `allowClear`, the select behaves strangely. When clearing the `<select>`, it spans over two lines, with the top line being blank and the second showing the placeholder text. When now adding an option after having cleared the select, the `<option>`-element is also selected.

```
<select multiple data-allow-clear="true" data-placeholder="Please select a value">
    <option value="">None</option>
    <option value="1">Something</option>
    <option value="2">Something else</option>
</select>
```

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by Stadly** [comment]
I have tested it using Windows 8 and IE11, Chrome 50 and Firefox 42.

Here is a [fiddle](https://jsfiddle.net/7xz0bugf/1/) using jQuery 3.0.0 beta and Select2 4.0.2.

The steps are as stated in the first post:

1. Add an option
2. Clear all -> The select spans two lines even though it is empty
3. Add an option -> "None" is added in addition to the selected option

**Comment by fk** [comment]
@kevin-brown As far as I can see everything works fine in terms of multi Select2, placeholder and `allowClear` as long as there _explicitly is no empty (without a `value`)_ `<option>` element.

When an empty `<option>` is provided, things are behaving like described by @Stadly (and also visible in the second part of the animated GIF shown in https://github.com/select2/select2-bootstrap-theme/issues/11#issuecomment-114944295).

**Comment by kevin-brown** [comment]
The reasoning behind why this happens is explained in https://github.com/select2/select2/issues/4366#issuecomment-220324441. For placeholders on multiple selects, if you set the `id` of the placeholder to `null` (during initialization, not on the `<option>` which shouldn't exist) then you can get around this issue.

**Comment by fk** [comment]
@kevin-brown Yup, everything makes sense – also the feature request by @Stadly.
Sidenote, also "to self": Documentation on placeholders probably needs to be clearer on this – there seems to be some [confusion](https://github.com/select2/select2-bootstrap-theme/issues/40#issuecomment-217455757) on how things are working.

**Comment by alexweissman** [comment]
Discussed in more depth in #4880 - please continue the discussion there.
