### ISSUE TITLE
Placeholder without redundant text in single-select

### ISSUE THREAD

**Issue by Stadly** [select2/select2#4368]
In a single-select, an `<option>` element with the same value as `placeholder`'s id (defaults to empty string, must be specified as an object) is required for the placeholder to work. Therefore I suggest to start using that `option`'s text as the placeholder text instead of specifying the text again using an attribute or when initializing Select2. Instead, `placeholder` could specify the value used for the placeholder (when other than the default empty string).

```
<select data-placeholder="-1">
    <option value="-1">Please select an option</option>
<select>
```

This will make the `placeholder` attribute different for single-selects than for multiple-selects, but I think this is ok, since placeholders are already different: Multiple-selects does not use the extra `<option>`-element, so here it makes sense to specify the placeholder text in `placeholder` instead of which `<option>` should act as a placeholder.

To make it backwards-compatible, the support for specifying an object in `placeholder` could be kept, and if no `<option>` with the value specified in `placeholder` is found, the value could be used as the placeholder text.

```
<select data-placeholder="Please select an option">
<!-- Fall back to using "Please select an option" as the placeholder text since no option with value="Please select an option" exists -->
    <option value="">Empty</option>
<select>
```

**Comment by kuzvac** [comment]
Yes, i double it! e can set option that will be used for [default selection](https://select2.org/placeholders#default-selection-placeholders), but text of this option not used for placeholder. It's confusing.
