### ISSUE TITLE
select2 4.0 width regressions

### ISSUE THREAD

**Issue by nachokb** [select2/select2#4370]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2 <sup>[3](#fn3)</sup>
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. visit the pens at <sup>[1](#fn1)</sup>
2. click on "show/hide" (also, try commenting out `$('select').select2()`); and resize the browser window
3. verify that the width of the select2 instances do not adjust nicely to the select

## Expected behavior and actual behavior

I've got an app using select2 v3.5.2; as I needed to add more functionality, I wanted to update first. So I did.

When I follow those steps, I see the widths do not behave nicely. This happens both for:

1. fields which start out hidden and show up depending on user's choices (I've got these in a lot of places);
2. every select2 instance on browser window resize (or zooming, or if a specific container resize due to a collapsing side bar menu)

This was working ok on v3.5.2. *Somehow I couldn't reproduce this correctly in my pen* <sup>[2](#fn2)</sup>, it breaks badly. I'm still trying to figuring out why this is.

I was expecting the width of the select2 instances to adjust correctly to the select they are replacing even if that select starts out hidden, and even after resizing the browser window.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.1.3, 2.2.2
- Select2 version: 3.5.2, 4.0.1, master

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/) -- oops I used CodePen, see below

<a name='fn1'>[1]</a> v4.0.1: http://codepen.io/nachokb/pen/xVopLm
<a name='fn2'>[2]</a> v3.5.2: http://codepen.io/nachokb/pen/ZWdvRj
<a name='fn3'>[3]</a> master: http://codepen.io/nachokb/pen/BKgOpK

**Comment by kevin-brown** [comment]
The default value for `width` changed from `style` to `resolve` in 4.0.0. You can manually override this and set it back to `style`, which will give you the old behaviour (of failing to guess the width).

http://codepen.io/anon/pen/PzZrXZ
