### ISSUE TITLE
Make the selected `<option>` available in the `select2:select` event

### ISSUE THREAD

**Issue by Stadly** [select2/select2#4371]
The `<option>` that was just selected does not seem to be available when listening to the `select2:select` event. In the `select2:unselecting` and `select2:unselect` events, the unselected `<option>` is available through `e.params.args.data.element`/`e.params.data.element`. I do not see a reason why the `<option>` should not be available in the `select2:select` event, since it is created at this time. For the `select2:selecting` event, however, the `<option>` is not yet created, and obviously cannot be available when the event is fired.

**Comment by cigaar** [comment]
Looks like a bug to me:
when using a select2 with the multiple option, `event.params.data` as well as `event.params.currentTarget` retain the last option selected before this selection, not the option that triggered this event.

**Comment by Stadly** [comment]
Any news on this?

**Comment by alexweissman** [comment]
It's possible that #5058 (released in 4.0.6-rc.0) has fixed this.  Would be helpful if everyone could try out the pre-release and see if it resolves this behavior!

**Comment by Stadly** [comment]
I just made a [CodePen](https://codepen.io/Stadly/pen/LOYePX) to test. But I can't seem to reproduce the issue now. Not even in version 4.0.2, which was the most recent version when this issue was created. In the CodePen everything seems to be working. Can you have a look, @cigaar? Maybe I've forgotten and misunderstood the original issue completely.
