### ISSUE TITLE
Dropdown List loses width settings when used in Bootstrap Tabs

### ISSUE THREAD

**Issue by DodoSerebro** [select2/select2#4373]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Create a Boostrap Tab with more than one tabs (2 minimum)
2. Create a Drop-down list with Select2 in all tabs
## Expected behavior and actual behavior

When I follow those steps, I see...

The drop-down list width in the first active tab which is loaded (Tab A), the width follows the bootstrap width settings set such as 'col-md-3'. The rest of the tabs do NOT follow the settings where all of them are resized to a random width size (col-md-x do not work) UNLESS the 'style' attribute is enforced. Some of the width sizes were the smallest possible and some had some slight 'trimming'

I was expecting...

The bootstrap width class setting given to be obeyed without having to use the 'style' attribute to force a certain width percentage
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [x] Edge
- [x] Opera 

Operating System
- [x] Windows

Libraries
- jQuery version: JQuery  2.2.4
- Select2 version: Select2 4.0.2
## Isolating the problem
- [x] The bug happens consistently across all tested browsers
- [x] I can reproduce this bug in [a jsfiddle](https://jsfiddle.net/7em4z1h8/2/)

**Comment by josaliba** [comment]
@DodoSerebro I am having the same issue too. Did you find any workaround?

**Comment by DodoSerebro** [comment]
@josaliba 

The only workaround that works is that when I intialise the select2 I give it a width property of 100% 

E.g. provided below (sorry if it's scruffy but am on my mobile phone)

$(document).ready(function ()
{ 
$("#ddl").select2({width : '100%'});
});

Hope this helps

**Comment by DodoSerebro** [comment]
Also I forgot to mention. Still use 'col-md-x' attributes if needed. If you use that property it automatically takes the 100% width of the parent
