### ISSUE TITLE
Drop-down area is not repositioned if still open when multi-select area changes size (e.g. closeOnSelect=false)

### ISSUE THREAD

**Issue by Loadmaster** [select2/select2#4377]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2 (4.0.2) - **Unknown**
- [x] This is not a usage question
- [x] I have attempted to find the simplest possible steos to reproduce the issue
## Steps to reproduce the issue
1. Enable tagging (`tags:true`), and do not close the drop-down on select/deselect actions (`closeOnSelect:false`).
2. Add and remove (select/deselect) choices to make the tags area change height.
3. When the tags area changes height, the drop-down element is not repositioned accordingly.
## Expected behavior and actual behavior

The drop-down element should be repositioned when the tags area changes size.

Here is a tagged selection area with a few tags already selected:

![bug-select2_1_03](https://cloud.githubusercontent.com/assets/10888408/15513018/661a1158-21a8-11e6-894e-4542b130d1f0.png)

This is what happens when one or more tags are selected and the tags area changes size (in this case, gets taller):

![bug-select2_1_04](https://cloud.githubusercontent.com/assets/10888408/15513020/6841c69c-21a8-11e6-8499-1a7b77d54e9b.png)

The newly selected choices have been added to the tags area, but their tags are hidden behind the drop-down element. The drop-down element is not repositioned (in this case, lowered) to expose the added tags.
## Work-Around

I used a work-around, catching the `"change"` event and forcing a resize of the drop-down element:

```
// Force drop-down list to resize upon select/unselect
select2Elem.on("change",
    function(evt) {
        select2Elem.resize();
    }
);
```
## Environment

Any browser.
Any O/S.
- Select2 version: 4.0.2
## External Links

The same bug was reported on StackOverflow at: [http://stackoverflow.com/questions/37198185](http://stackoverflow.com/questions/37198185)

**Comment by kevin-brown** [comment]
If you use the copy available from the current `master` branch, do you see this issue?

In the upcoming 4.0.3 release, a bit of work was put into fixing the re-positioning, and that may have affected this issue.

**Comment by Loadmaster** [comment]
Clarification:
I am using the publicly available version at [https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/js/select2.min.js](https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/js/select2.min.js).

I do not know if the master branch version exhibits the same behavior or not (so I have unchecked the Prerequisite box above).

**Comment by Loadmaster** [comment]
I just verified that the 4.0.2 dist build as of 2016-05-14 exhibits this problem.

I still have not checked the current master branch version.

**Comment by Lughino** [comment]
I confirm that the issue exist even in 4.0.3 version.

This is [http://plnkr.co/edit/pzN68xUMOt8wjlpGz9jh?p=preview](plunk)

**Comment by alexweissman** [comment]
jsbin that demonstrates this issue: http://jsbin.com/nolajupeco/1/edit?html,js,output

**Comment by alexweissman** [comment]
@kevin-brown explains the origin of this problem in #3373:

> This has to do with the fact that the `close` event is not triggered, and we don't position the container on the `select`/`unselect` event.

> You can also reproduce this issue by selecting the option while having the CTRL key held, as that behaves the same way as `closeOnSelect: false`.

**Comment by alexweissman** [comment]
Please note that this issue has nothing to do with _tagging_.  I believe OP is referring to "multiple selection mode", which is something entirely different.

**Comment by danielYaakov** [comment]
There is any solution to this bug?

**Comment by shahimclt** [comment]
any workarounds or fixes?

**Comment by Victor-Prodanov** [comment]
Hi, I think this issue should not be closed.
