### ISSUE TITLE
Can't select the option programmatically once removed.

### ISSUE THREAD

**Issue by arpitux** [select2/select2#4383]
Hi Folks,

I am programmatically selecting a item with below code.

```
$("#main-search option[value='123').attr('selected', true);
$("#main-search").trigger("change");
```

Which works fine. But once I remove the selected item manually and then try to add it back programmatically using the same above code. it doesn't work.

Please suggest the solution.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by smeagol82** [comment]
I'm facing this problem also. 
Goal: change selection in select2 by jquery
Method: add/remove attribute selected to the option in the original select
Bug: once removed attribute selected and reasigned by jquery select2 does not update the values (single add/remove works ok)
Browser: Firefox
Version jquery: 2.1.4

Thank you

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
