### ISSUE TITLE
Documentation for how to report dropdown positioning issues

### ISSUE THREAD

**Issue by jzabroski** [select2/select2#4387]
I would like to submit a PR to document how to report dropdown positioning issues, based on @kevin-brown 's comment here: https://github.com/select2/select2/issues/3970#issuecomment-160496724

Which explains why the dropdown is lining up fine there. This will allow me to confirm that the issue is actually with the offset caused by margins on the body (or the dropdown parent).

**Comment by alexweissman** [comment]
Ok, I will add this to the documentation on https://select2.org/dropdown.
