### ISSUE TITLE
Autofocus submit button after closing not working

### ISSUE THREAD

**Issue by dlewand691** [select2/select2#4388]
Updated to 4.0.3 and now when I close a dropdown the submit button that appears no longer autofocuses. Can this functionality be restored?

See example here and choose any dropdown. "Go" button should receive focus:
[http://www.paulrand.design/writing/articles/index.html](http://www.paulrand.design/writing/articles/index.html)

**Comment by alexweissman** [comment]
If this is the same issue as #4570, then it should be fixed as of v4.0.4.
