### ISSUE TITLE
Set value in program destroy the templateSelection

### ISSUE THREAD

**Issue by guitouts** [select2/select2#4396]
Hi !

There is a bug when program set the value of the select2 and the select2 have a custom templateSelection

this is my test code [https://jsfiddle.net/74urrhLh/](https://jsfiddle.net/74urrhLh/)

1: Select an option => the selection is display correctly with my custom templateSelection
2: Click on the button "Select Option 1" => the selection is not display with my custom templateSelection
3: Select again an other option => the selection is not display with my custom templateSelection

JQuery version: 2.2.3
Select2 version: 4.0.3

Thx :+1:

**Comment by kevin-brown** [comment]
Don't call `.select2()` on the element before changing the value, this is re-initializing Select2 without your `templateSelection` option.

https://jsfiddle.net/gLwfLfsd/
