### ISSUE TITLE
More control over width

### ISSUE THREAD

**Issue by cyphix333** [select2/select2#4399]
Just a suggestion that there should be more control over being able to set the width. At the moment it seems all you can do is get it to auto calculate the width OR get it to look at the width set for the element already.

I have a situation where I would prefer to not have to set a width for the element and for select2 to auto set the size, _but_ add a little extra to it.

If it was only one select field then you could easily just get the current width and then add the extra to it via javascript before instantiating select2 so that it would get the width you would like; however when you have more than one select this obviously won't work unless you do them all individually, but obviously if you have a lot then this isn't very ideal.

**Comment by cyphix333** [comment]
I guess you could loop through all the relevant selects and change their width like that; but it'd be better if select2 had an option to handle this properly.

**Comment by cyphix333** [comment]
Did this ever get implemented?

**Comment by cyphix333** [comment]
Anyone home?

**Comment by kevin-brown** [comment]
> I guess you could loop through all the relevant selects and change their width like that; but it'd be better if select2 had an option to handle this properly.

I would recommend doing this. We added a new "computedstyle" method for handling a few more edge cases, but ultimately Select2 attempts to defer to the browser to determine how large it is supposed to be.

Outside of Select2, you would need to do this manually by looping through all of the boxes and adjusting their widths just a little bit. Select2 doesn't make this easier, but it tries to not make it harder to do.
