### ISSUE TITLE
auto complete not work in tag design 

### ISSUE THREAD

**Issue by perspolise** [select2/select2#4400]
I work with select2 (v +4) plugin and have This code for fetch data from json file and show with tagging design/method:

```
$(".tags-select").select2({
  // enable tagging
  tags: true,

  // max tags is 3
  maximumSelectionLength: 3,

  // loading remote data
  // see https://select2.github.io/options.html#ajax
  ajax: {
    url: "https://api.myjson.com/bins/444cr",
    processResults: function (data, page) {
      return {
        results: data
      };
    }
  }
});
```

```
<select class="tags-select form-control" multiple="multiple" style="width: 200px;">
  <option value="tag1" selected="selected">tag1</option>
  <option value="tag2" selected="selected">tag2</option>
</select>
```

In action auto complete not work for me!!

[DEMO](https://jsfiddle.net/59Lbxvyc/)

how do fix this problem?!

**Comment by andenq** [comment]
But it does work (at least in Firefox 48.0.1), if you start typing 'tag' then the list will show all of the tags in https://api.myjson.com/bins/444cr

**Comment by Narfix** [comment]
I experience the same problem.
The autocomplete + tags doesn't work with IE11 but works well with Firefox & Chrome.
it seems IE goes mad since it doesn't find any matching items in the autocomple.

How can I fix this problem ?

**Comment by Narfix** [comment]
Here's the code I'm using : 

```
$("#ld").select2({
            ajax: {
                url: "/search.ashx",
                dataType: "json",
                delay: 250,
                data: function (params) {
                    return {
                        q: params.term
                    };
                },
                processResults: function (data) {
                    return {
                        results: data.items
                    };
                },
                cache: false
            },
            tags: true,
            escapeMarkup: function (markup) { return markup; },
            minimumInputLength: 3,
            templateResult: formatRepo,
            templateSelection: formatRepoSelection
        });
```

    function formatRepo(item) {
        if (item.loading)
            return item.text;
        if (!item.nom)
            return false;

        var markup = "<div class='select2-result-repository clearfix'>";
        markup += "<div class='select2-result-repository__avatar'><img src='/MiniAgent/" + item.identifiant + "' /></div>";
        markup += "<div class='select2-result-repository__meta'>";
        markup += "<div class='select2-result-repository__title'>" + item.prenom + " " + item.nom + "</div>";
        markup += "<div class='select2-result-repository__statistics'>" + item.id + "</div>";
        markup += "<div class='select2-result-repository__statistics'>";
        markup += "<div class='select2-result-repository__forks'>" + item.unite + "</div>";
        markup += "</div></div></div>";

        return markup;
    }

    function formatRepoSelection(item) {
        return item.id;
    }
```

**Comment by alexweissman** [comment]
When using a remote data source, you need to perform filtering on the server side.  This is clearly documented: https://select2.org/data-sources/ajax#transforming-response-data

> Select2 expects results from the remote endpoint to be filtered on the server side. If server-side filtering is not possible, you may be interested in using Select2's support for data arrays instead.
