### ISSUE TITLE
Many cancelled AJAX requests while typing

### ISSUE THREAD

**Issue by rossgardt** [select2/select2#4402]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Type away text within in a field (depending on resource retrieves via XHR)

## Expected behavior and actual behavior

In the network console, I see many requests that are being `cancelled` (by [this line](https://github.com/select2/select2/blob/4b9e02f02211248be25ac4c16d4635cf38237bb9/src/js/select2/data/ajax.js#L49)).

I was expecting some threshold of connections being cancelled within a minimum amount of time. Especially, since the `delay` option in the AJAX object ist zero by default.

Result: Multiple users using this component at once are flooding the web service with requests that's responses not even being processes.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.2.4
- Select2 version: 4.0.3

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in a jsbin -> see example pages

**Comment by kevin-brown** [comment]
> Especially, since the delay option in the AJAX object ist zero by default.

And you can increase this to prevent requests being sent out immediately, solving your issue.

https://select2.github.io/options.html#a-request-is-being-triggered-on-every-key-stroke-can-i-delay-th
