### ISSUE TITLE
Duplicate tags on Select with multiple

### ISSUE THREAD

**Issue by GitHubStig** [select2/select2#4404]
## Steps to reproduce the issue
1. go to https://select2.github.io/examples.html
2. scroll down to Tagging support example
3. type in `red`, yes with a space after.
   ![select2 double tags](https://cloud.githubusercontent.com/assets/9544391/15851281/b510f11a-2cce-11e6-95f2-5f90fa47ac4d.gif)
## Expected behavior and actual behavior

When I follow those steps, I see 2 `red` tags.

I was expecting only 1.
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox

Operating System
- [x] Mac OS X
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers

**Comment by alexweissman** [comment]
As of `4.0.6-rc.1`, I cannot seem to replicate this issue anymore.
