### ISSUE TITLE
Cannot unselect first option (with multiple and tags)

### ISSUE THREAD

**Issue by Loadmaster** [select2/select2#4406]
## The problem

I have a `<select>` element with `tags` and `multiple` enabled, that is displayed with one option already selected (i.e., it was previously selected as a default value for the field). However, once I unselect that option, its tag is removed from the tags area, but the corresponding `<option>` element is _not_ removed from the parent `<select>` element, and it still has its `selected="selected"` attribute set. So when the page posts back to the server, that option is still seen as being selected.

I can select and unselect many other values, but no matter what I do, when I unselect all tags, if I leave no tags selected (even if I click the `select2-selection__clear` clear all '×' button), one option (always the first child `<option>` of the `<select>` element) always remains marked as `selected`.

## Steps to reproduce the issue

1. Enable `multiple` and `tags`.
2. Render a `<select>` element with one `<option>` already selected.
3. Unselect all options, so that no tags are visible.
4. Post back to the server.

Just before the post, you can examine the `<select>` element and see that there is still one child `<option>` (apparently, it is always the first child element) with an attribute of `selected="selected"`. (There may be other `<option>` elements as well, but none of them have a `selected` attribute, so this is benign.)

**Figure 1: Empty tags area with all choices unselected**

![bug-select2_03_001](https://cloud.githubusercontent.com/assets/10888408/15902523/ece315ec-2d6d-11e6-89ff-5f5515afe1a4.png)

**Figure 2: DOM showing selected `<option>` element**

![bug-select2_03_002](https://cloud.githubusercontent.com/assets/10888408/15902518/e9516014-2d6d-11e6-90c7-5cb8be97ee06.png)

## Possible work-around

It might be possible to catch the `select2:unselect` event and explicitly reset the `selected` attribute of the affected `<option>` element, or to remove the `<option>` from its parent `<select>` element altogether.

## Environment

Browsers

- [X] Google Chrome (desktop)
- [X] Mozilla Firefox (desktop)

Libraries

- jQuery version: 1.8.2
- Select2 version: **4.0.3**

## Related issues

#2959 select2:unselect doesn't work properly
#3075 Android browser [Multiple select boxes] cannot remove the selected option

**Comment by Loadmaster** [comment]
**More Details**
Here are the options I'm using, i.e., passing the following `opts` object in the `selectItem.select(opts)` call:

```
var opts = {
    tags:                       true,       // Enable tagging mode
    ajax:                       undefined,  // Ajax service params
    minimumInputLength:         0,          // Show all choices
    maximumInputLength:         30,         // Disallow more than 30 entered chars
    minimumResultsForSearch:    1,          // At least 1 result must be displayed
    maximumSelectionSize:       0,          // Infinite selectable choices
    allowClear:                 true,       // Enable 'X' clear button to remove tags
    closeOnSelect:              false,      // Keep drop-down open after an option is selected
    openOnEnter:                true,       // Enter key opens the drop-down
    selectOnClose:              false,      // Do not select when drop-down is closed
    selectOnBlur:               false,      // Do not select choice on blur

    placeholder:                "Select one or more items",

    formatSearching:            "Searching...",
    formatLoadMore:             "Searching for more matches...",
    formatNoMatches:            "No matches found",
    formatAjaxError:            "Cannot load any matches from server",
    formatInputTooShort:        "Please enter more characters",
    formatInputTooLong:         "Too many characters entered",
    formatSelectionTooBig:      "Maximum number of choices selected",

    // Other parameters (not set)
//  debug:                      false,      // Enable debugs
//  separator:                  ',',        // Values delimiter
//  width:                      'off',      // Use <select> class for width
//  data:                       (not set)   // Fixed data choices (use <select> or Ajax instead)
//  query:                      (not set),  // Return query matches (use Ajax instead)
//  matcher:                    (not set),  // Type-ahead matching function
//  sortResults:                (not set),  // Ajax results sorter
//  insertTag:                  (not set),  // Places a selected option
//  templateSelection:          (not set),  // Render a selection tag
//  formatResultCssClass:       (not set),  // CSS classes added to result elements
//  initSelection:              (not set),  // Init the selection text
//  tokenizer:                  (not set),  // Parse each keystroke
//  tokenSeparators:            (not set),  // Tag/token separator chars
//  createSearchChoicePosition: (not set),  // Position to insert a created choice
//  containerCss:               (not set),  // Container styles
//  containerCssClass:          '',         // Select2 container class
//  dropdownCss:                (not set),  // Drop-down container styles
//  dropdownCssClass:           '',         // Select2 drop-down container class
//  dropdownAutoWidth:          false,      // Auto-size drop-down width
//  adaptContainerCssClass:     (not set),  // CSS class renamer
//  adaptDropdownCssClass:      (not set),  // CSS class renamer
//  escapeMarkup:               (not set),  // HTML escaper
//  loadMorePadding:            0,          // List bottom scroll padding for next load
//  nextSearchTerm:             (not set),  // Generate next search term

    dropdownParent:                         // Element to append drop-down to
        selectElem.parent(),

    createTag: function(term)   {           // Disallow unlisted choices to be created
        return null;
    },

    insertTag: function(data, tag) {        // Places a selected option
        // Insert the tag at the end of the list
        data.push(tag);
    },

    templateResult: function(data) {        // Format a drop-down choice
        // Create a checkbox element
        var span = document.createElement('span');

        var inner = document.createElement('span');
        inner.className = "multiTagUnselected";
        span.appendChild(inner);

        var img = document.createElement('img');
        img.setAttribute("src", "images/checkbox_no.png");
        img.className = "multiTagSelectImg";
        inner.appendChild(img);

        inner = document.createElement('span');
        inner.className = "multiTagSelected";
        span.appendChild(inner);

        img = document.createElement('img');
        img.setAttribute("src", "images/checkbox_yes.png");
        img.className = "multiTagSelectImg";
        inner.appendChild(img);

        // Add the choice text
        inner = document.createElement('span');
        inner.innerText = data.text;
        span.appendChild(inner);

        return span;
    }
};

if (useAjax) {
    opts.minimumInputLength = 1;    // Require at least 1 entered char

    opts.ajax = {                   // Ajax service params for each search keystroke
        url:            ajaxUrl,
        type:           "post",
        delay:          200,                // msec to wait before sending the Ajax query
        cache:          false,              // Disabled result caching
        contentType:    "application/json; charset=utf-8",    // Sent data format
        dataType:       "json",             // Received data format

        // Build the service request params for Assets.asmx
        data: function(params) {
            return JSON.stringify({
                contextKey: contextKey,     // Search context IDs
                count:      50,             // Max returned matches
                prefixText: params.term     // Search term
            });
        },

        // Process the results from the Ajax service call
        processResults: function(data): any {
            // Parse the results into the format expected by Select2 (4.0+);
            // Returned data looks like:
            //  { d: [
            //      "{\"First\":\"Bach\",\"Second\":\"777\"}",
            //      "{\"First\":\"Grieg\",\"Second\":\"785\"}",
            //      "{\"First\":\"Mozart\",\"Second\":\"775\"}",
            //      ... ]
            //  }
            var res = {
                results:    [],
                pagination: {
                    more:   false
                }
            };
            for (var i = 0;  i < data.d.length;  i++) {
                var item = JSON.parse(data.d[i]);
                res.results.push({
                    id:     item.Second,
                    text:   item.First,
                    locked: false
                });
            }
            return res;
        }
    };
}
```

**Comment by Loadmaster** [comment]
One thought: Can I use a default/empty `<option>` placeholder for when no options at all are selected? Or does this not work for multiple select?

**Comment by kevin-brown** [comment]
> Can I use a default/empty <option> placeholder for when no options at all are selected? Or does this not work for multiple select?

Nope, a multiple select typically uses null or a lack of a value sent to indicate that nothing was selected. The placeholder option is only required for a single select because it always has to send _some_ value.

**Comment by Loadmaster** [comment]
@kevin-brown - I appreciate the feedback.
Note as seen in Figure 2, I am creating the `<select>` element with a `multiple` attribute.

I am currently trying to isolate what exactly is being sent from client to server on postback. As I stated, it appears that an empty tags list (all choices unselected) still sends back a single `<option>` (the first) marked as `selected`.

My guess is that the `select` element's `option` children array is not getting properly sync'd up with the internal selected item list kept by Select2, perhaps in the `unselect` or `close` event handlers.

Also, I don't have experience with jsbin, so this make take some doing on my part.

**Comment by Loadmaster** [comment]
I have discovered that the problem is actually with the way ASP.NET receives postback data from `<select>` elements (compared to `<asp:ListBox>` elements). So it appears that this is not, in fact, a bug in Select2.

So I am closing this bug.

**Comment by giannik** [comment]
Hi ,
Im having the same issue using asp.net mvc and select2. Have you found a workaround you may share ?

**Comment by itajackass** [comment]
Still no solution?
