### ISSUE TITLE
Select2 initialize take over minutes when have many dropdown boxes.

### ISSUE THREAD

**Issue by Vuhuynh4** [select2/select2#4407]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))

Incase, my jsp page have a lot dropdown boxes ( over 100), so when the first time page loaded I used jQuery("[nameofClass]").select2(); to initialize all of it. 
The root cause I think is the select2 will redraw each select tag to select2 one by one, so if the number of select is over 100, the time to init is so long, and it make a bad performance. 

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System
- [x] Windows

Libraries
- jQuery version:
- Select2 version: 4.0.2

**Comment by kevin-brown** [comment]
This needs more information in order for it to be actionable.

What options are being passed to Select2 during initialization? How many `<option>` tags are in each `<select>`? Can you replicate the issue in a [jsbin](https://jsbin.com)?

**Comment by jzabroski** [comment]
@Vuhuynh4  Can you use Chrome and attach the Timeline log?  Open blank Chrome Tab.  Open Developer Tools. Go to Timeline tab. Ensure JS Profile is marked. Go back to blank Chrome Tab. Enter test url, hit enter to load website. Go back to Developer Tools -> Timeline.  Right-click in the colorful area -> "Save Timeline Data".

**Comment by lbearl** [comment]
This may be an effect of the recent chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=620142 which will be fixed in Chrome 52.

**Comment by kikonen** [comment]
I'm also seeing poor initialization performance from select2, not in the range of minutes however. Performance seems to be proportional to page size (not only amount of select2 widgets itself on page). I.e. if page is big, then some calculations by select2 are easily taking several seconds to render with multiple select2 widgets.

**Comment by anatoly-mytrucking** [comment]
JSBin for 100 selects with 30 options each. It makes initialization noticeable. 
https://jsbin.com/doliyupaki/edit?html,js,output

**Comment by vanboom** [comment]
This happens on simple pages as well...

![recorded](https://user-images.githubusercontent.com/251706/29781930-6b9ef56e-8be0-11e7-883e-285c40bf92f1.gif)

On the Examples page, the UI controls should appear as select2 initially, instead they appear as the native select control, then "flash" into select2.

**Comment by Ajay1432** [comment]
Is there any solution for this issue?

**Comment by prabhuvikas** [comment]
Do we have a better way to handle this?

**Comment by kikonen** [comment]
Lazy initialization? More specific selectors for querying DOM? Using directly JS DOM API instead of jQuery for finding elements?

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:
