### ISSUE TITLE
allowClear is extremely slow or non-functional for large numbers of items in a multi-select

### ISSUE THREAD

**Issue by cdaveb** [select2/select2#4413]
When I use allowClear in a multiple select menu and a large number of items are selected, the clear option takes forever or freezes up the browser.
## Steps to reproduce the issue
1. Create a multiple select with allowClear enabled
2. Select a large number of items
3. Use the clear option
## Expected behavior and actual behavior

When I follow those steps, I expected the items to all be deselected promptly (as occurs when I deselect them just using javascript)

Instead the browser just sits there, presumably trying to deselect them all and eventually the browser times out.
## Environment

I was able to reproduce this issue in both Chrome and Firefox on MacOS X.

Libraries
- jQuery version: 1.12.4
- Select2 version: 4.0.3
## Isolating the problem

I've created an example of the issue here:
https://jsbin.com/kigiqanoqa

After using the select census tracts button to select a large number of items, clearing the items using the x in the select menu freezes up the browser. Doing it via the remove selections button happens instantly.

**Comment by carlosabalde** [comment]
Same problem here. It seems all the event triggering & handling stuff in ``AllowClear.prototype._handleClear()`` is really slow for large lists of selected choices. Still looking for a quick way to clear those select2 widgets.

**Comment by carlosabalde** [comment]
Ok. Previous approach does not cover al cases. An even uglier monkey patch approach:

```
AllowClear = $.fn.select2.amd.require('select2/selection/allowClear');
var old_clear = AllowClear.prototype._handleClear;
AllowClear.prototype._handleClear = function (_, event) {
  if (event.target.className === 'select2-selection__clear') {
    if (this.options.get('disabled')) {
      return;
    }
    event.stopPropagation();
    this.$element.val(null).trigger('change');
  } else {
    old_clear.apply(this, arguments);
  }
};
```
