### ISSUE TITLE
clear data of select2

### ISSUE THREAD

**Issue by matiazar** [select2/select2#4421]
I had this line of code

$("#select").select2("val", null);

on version 4.0.2 it was working
i have updated to 4.0.3 and now it doesnt !

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by matiazar** [comment]
Hi. thanks 4 answer me. 
I need to blank a select2. Empty it.
I had used this line on version 4.0.2 and it works
Now I found another way to do this.

$(".js-example-basic-single").html('').select2();

**Comment by kevin-brown** [comment]
> Now I found another way to do this.

Awesome.

**Comment by jnandritsilavo** [comment]
Insert this code into your js file : 
```
$('.sgl').val('1');
$('.sgl').trigger('change');
```
