### ISSUE TITLE
can  inherit class from native select?

### ISSUE THREAD

**Issue by zhanghqgit** [select2/select2#4423]
in addition to the width in inline style,can select2 inherit a class from native select?  form example ,

```
<select class="form-control input-sm" >
   ....

</select>
```

I want that select2 can inherit `input-sm` class for control  select2's height;

**Comment by SgtOddball** [comment]
If memory serves you can't grab the styling from the native object but instead pass the classes through when initialising the select2 object. So you'd need something like this.

```javascript
$('select.form-control').select2({
    dropdownCssClass: 'input-sm', //Class of the drop down object
    containerCssClass: 'input-sm'   //Class of the select 2 object 
})
```
Should do the job (plus any further settings you wanted to pass through.

**Comment by kevin-brown** [comment]
You can use `:all:` as a value (along with other classes) in `dropdownCssClass` or `containerCssClass` to inherit all of the classes from the original `<select>`.

**Comment by zhanghqgit** [comment]
where to find these options? except `select2.github.io` and read the source code ,do you have a documentation for this ?  thanks

**Comment by zhanghqgit** [comment]
but, I get this error when use settings like previous   `Uncaught Error: No select2/compat/containerCss`

```
$('select.form-control').select2({
    dropdownCssClass: 'input-sm', //Class of the drop down object
    containerCssClass: 'input-sm'   //Class of the select 2 object 
})
```

**Comment by kevin-brown** [comment]
> Uncaught Error: No select2/compat/containerCss

https://github.com/select2/select2/issues/3302

You need to use the full build (`select2.full.js`).

**Comment by zhanghqgit** [comment]
thanks a lot!

**Comment by SgtOddball** [comment]
@kevin-brown Oooooooo I didn't know about the ```:all``` value, i'll have to remember that one in the future.
