### ISSUE TITLE
Add Angular 1.5.x compatibility

### ISSUE THREAD

**Issue by rbatllet** [select2/select2#4424]
Please, remove the restriction about Angular 1.5.x

```
$ bower list

...
├─┬ angular-select2#1.5.1
│ ├── angular#1.5.6 incompatible with ~1.4.0 (1.4.11 available, latest is 1.5.7-build.4877+sha.8cd9848)
...
```

**Comment by kevin-brown** [comment]
This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

https://github.com/rubenv/angular-select2

[ml]: https://github.com/ivaynberg/select2#mailing-list

**Comment by rbatllet** [comment]
I've already created it and was solved. Thanks!
