### ISSUE TITLE
dropdownAutoWidth still not working. 

### ISSUE THREAD

**Issue by arkgroup** [select2/select2#4429]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by arkgroup** [comment]
Here what I have , using Chrome, style :	.search { 	  width: 30%; 	  float: right; 	  margin-top: 50px; 	} 	js:  $("#search").select2({         data: select2_data,        containerCssClass: "search",         width: 'resolve',         dropdownAutoWidth: 'true',         theme: "classic",         placeholder: "Select an option"     }); Theme and dropdown don't work

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by arkgroup** [comment]
Here is test to reproduce:
<style>
.search {
	  width: 30%;
	  float: right;
	  margin-top: 50px;
	}
	

</style>
  <script type="text/javascript">
 $(document).ready(function () {

     var data = [{ id: 0, text: 'enhancement' }, { id: 1, text: 'bug' }, { id: 2, text: 'duplicate' }, { id: 3, text: 'invalid' }, { id: 4, text: 'wontfix'}];


     $("#search").select2({
         data: data,
         containerCssClass: "search",
         width: 'resolve',
         dropdownAutoWidth: 'true',
         theme: "classic",
         placeholder: "Select an option"
     });
  });
	</script>
<body>
 <div id="search"></div>
</body>
1. tested with Google Chrome
2. jQuery v1.10.2
3.  Select2 4.0.3

**Comment by kevin-brown** [comment]
Select2 is supposed to be used with a `<select>`, not a `<div>`. More than likely that's your issue.

**Comment by arkgroup** [comment]
I use code from [https://bl.ocks.org/jjzieve/a743242f46321491a950]
for d3 search box.
It use <div>. Anyway, thanks for your help.
