### ISSUE TITLE
There is no more highlight event

### ISSUE THREAD

**Issue by rvion** [select2/select2#4436]
in select2 4 master, there is no way to bind callback to highlight because the highlight event is gone.
the open event can not be used either to register event listening to select2-results__option, because select2-results__option don't exist yet when open is triggered.

that is quite annoying

**Comment by rvion** [comment]
well, here is how I work around the lack of simple to use highlight event:
```js
      RefPresenter = function(){}
      $.fn.select2.amd.require(['select2/results', 'select2/utils'], function (Result, Utils) {
        RefPresenter = function($element, options, dataAdapter) {
          RefPresenter.__super__.constructor.call(this, $element, options, dataAdapter);
        }
        Utils.Extend(RefPresenter, Result);
        RefPresenter.prototype.bind = function (container, $container) {
          container.on('results:focus', function (params) {
            console.log('HIGHLIGHT');
          });
          RefPresenter.__super__.bind.call(this, container, $container);
        };
        return RefPresenter;
      });
```

**Comment by kevin-brown** [comment]
This is something we might consider adding back, but we'd need to know what use cases it helps that cannot already be served by other methods.

So, what was your use case for the old `select2-highlight` event?

**Comment by rvion** [comment]
thanks for your answer.

I have a select2 input that allows to "pick" any div with an id in the page ( the completion shows the list of all elems with an id in the page). When I'm highlighting a result, I want to add red borders around the corresponding element, to visually see what I'm selecting.

**Comment by dlewand691** [comment]
I would also like to have this functionality back. Downgraded to 4.0.2 to get it back. 

When I select an option and the dropdown closes, the dropdown is higlighted, a button appears, I hit tab to jump to the button, then return to click the button.

Would be great to have this back in future releases.

**Comment by annamalaissh** [comment]
we have an use case for the highlight event where we would show an explanation to each item in a separate pop up near the dropdown upon hovering on the item. It would be nice to have the highlight event back.

**Comment by performatric** [comment]
somebody can submit a working example? Tks!

**Comment by annamalaissh** [comment]
i used the code that rvion has pasted above ! works like a charm ;-)

**Comment by performatric** [comment]
Which version? I got the error "this.results.render is not a function".

**Comment by annamalaissh** [comment]
i am using 4.0.3 
You will get this error if your code in the area **// DO STUFF** is wrong. so take care that your code in that area is error free.

**Comment by performatric** [comment]
I have nothing in // DO STUFF, the code is the same, only with console.log('HIGHLIGHT');
Maybe the version of jquery is the problem (1.6.2), but I don't know =/

**Comment by annamalaissh** [comment]
the js code is breaking for us as well.
Is there any update on how to use the old highlight event of select2 ?

**Comment by performatric** [comment]
Alternatively I used this code:

```javascript
$('body').on('hover', '.select2-results__option.select2-results__option--highlighted', function (ev){
	var highlighted = $('#selectID').data('select2').$dropdown.find('.select2-results__option--highlighted');
	if (highlighted) {
		// code
	}
});
```

**Comment by annamalaissh** [comment]
```javascript
$('body').on({
        mouseenter: function () {
             var highlighted_item = $(this).text();
         // CODE   
        },
        mouseleave: function () {
        // CODE
        }
    }, '.select2-results__option.select2-results__option--highlighted');
```

@performatric : Thanks for the hint, i tried this code and it works :-)

**Comment by achimha** [comment]
I use `select2-highlighting` in 3.5.4 to perform geocode lookups on geographic entries (say city names). I pass the lat/long of the highlighted element via AJAX to a Google API to determine the country and then I modify the item on the fly to add the country name.

I think this is an important hook, there are many situations where you want to handle mouse over. However, in a mobile device context, there is not much value.

**Comment by virgo79** [comment]
I also use the `select2-highlighiting `event in 3.5.4.

I 've a select2 dropdown with a list of google fonts and I use the highlighting event to preview the font in real time during the highlight event (moving mouse or using up/down arrows within the dropdown list). This is key for our system and we could not upgrade to version 4 until this event is missing.

Anyway, there could be many reason for adding back the `select2-highlighiting` event. It's a very useful event that could give many opportunities to all developers. Web developing is moving towards the real time actions.

Please, reconsider this event.

**Comment by laurentdinclaux** [comment]
I personally need it for live webfont loading and preview

**Comment by ogiermaitre** [comment]
I know the thread is a bit old but I found it yesterday, looking to get an event when the mouse was over an option in the list.

I manage to do something a bit different, and more appropriate for my usage. That is, using templating of the dropdown elements ([select2_dropdown#templating](https://select2.org/dropdown#templating), I was able to add an event listener directly to the right node.
More importantly for me, it’s then possible to get the data related to the node under the mouse.

Here is an example, based on select2 documentation.
```
function formatState(state) {
    if (!state.id) {
        return state.text;
    }
    var baseUrl = "/user/pages/images/flags";
    var $state = $('<span><img src="' + baseUrl + '/' + state.element.value.toLowerCase() + '.png" class="img-flag" /> ' + state.text + '</span>')
        .on({
            mouseenter:()=>{
                console.log('mouse enter',state)
            },
            mouseleave:()=>{
                console.log('mouse leave',state)
            }
        })


    return $state;
};

$(".js-example-templating").select2({
    templateResult: formatState
});
```

On the same principle, it is possible to catch mouseenter and mouseleave on selected elements.

Hopping this will help,
Ogier

**Comment by joaorsfonseca** [comment]
I have a similar issue. 
Highlight select2 dropdown when the values are refreshed from a selection in another dropdown (cascade dropdowns implementation).

**Comment by mobspyguy** [comment]
Highlight event is needed to show a popover with additional informations about highlighted value.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:

**Comment by loxK** [comment]
Why closing then ?
