### ISSUE TITLE
Extra blank line in dropdown

### ISSUE THREAD

**Issue by dariospadoni** [select2/select2#4437]
Hello
I'm using select2 inside a angular directive which create the select2 object and watches for options changes in order to update it, no multiple selection, empty placeholder. I've created a jsbin here: https://jsbin.com/pagucodubi/edit?html,js,output

What happens is that when the dropdown opens it shows some extra space on top which corresponds to an empty option; what I need is having no placeholder, no option  initially selected and showing in the dropdowns only valid options. 
I tried different ways:
- if I remove it with jquery ( with `$(selectize).find('option').remove()` before setting data again) the component automatically selects the first option
- I tried then to listen to the select2 _open_ event but when this is fired the options are still not there (see my question here: https://groups.google.com/forum/#!topic/select2/gYwazTxKMfg)
- if I remove ng-model from the html template then the problem is solved (but I lost the binding with my controller)

Is there a way to have an empty placeholder (which I read requires an empty option) but hide this empty option from the dropdown?

**Comment by RanjanSingh235** [comment]
Hello,
I am facing the same issue described above. Please help me to solve the problem.

Thanks

**Comment by felansu** [comment]
Same problem in the last version with ng-options.

**Comment by fearintino** [comment]
Hello,
Why issue is closed? Is problem resolved?
