### ISSUE TITLE
The results converts to [object Object] under templateSelection

### ISSUE THREAD

**Issue by HamzaLJ** [select2/select2#4438]
I using the latest version of select2 library; however, I am having an issue which I believe it's a bug.

I am using Select2 in order to fetch some data from a rest api, until now everything is fine I can see the data that I want when searching; however when I click on that result using the below lines:

```
templateSelection: function(results){
				return results.Name;
                               //the below works fine
                               //return 'This is a plain text'
			}
```
What I see is **[object Object]** knowing that 'results' is an array and 'results.Name' is a string, but when it goes under 'templateSelection' everything converts to **[object Object]**
For you notes, the same array works fine under 'templateResult', the issue is only in 'templateSelection'

Is anybody facing this issue too? Is this a bug? How can I solve it?

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by in-in** [comment]
https://css-tricks.com/reduced-test-cases/

**Comment by miguelsmuller** [comment]
I have the same problem. this is my return JSON:
```
{
    "results": [{
            "id": "1",
            "text": {
                "iua": "968448600731",
                "nomeCompleto": "Luciana Quintana",
                "cpf": "62291584421",
                "dtNascimento": "18/11/1976"
            }
    }]
}
```

my templateSelection option is this one: 
```
function customSelectText (optionSelected) {
  if (!optionSelected.id) {
    return item.text.nomeCompleto;
  }

  var $contentHTML = '<b>' + optionSelected.text.nomeCompleto + '</b> (' + optionSelected.text.dtNascimento + ')';

  return $contentHTML;
};
```

it's happening that my optionSelected being converted to  [object Object] . I am unable to access internal items.

The error does not happen in the templateResult option. the listing is displayed perfectly.

**Comment by miguelsmuller** [comment]
someone?

**Comment by miguelsmuller** [comment]
no one?
