### ISSUE TITLE
Multi select not working with js array

### ISSUE THREAD

**Issue by alexcroox** [select2/select2#4443]
When using a js array of options multiple select does not work correctly. It works fine when I don't include the multiple attribute.

Here is how I set it up:

```
var categories = [];

_.each(form.offlineData.categories, function(categoryData, categoryID) {

    var children = [];

    // We need the parent to be selectable, can't select opgroups
    children.push({
        id: categoryID,
        text: categoryData.text
    });

    _.each(categoryData.children, function(childData, childID) {

        children.push({
            id: childID,
            text: childData.text
        });
    });

    categories.push({
        id: categoryID,
        text: categoryData.text,
        children: children
    });
});

$('.category-input').select2({
    data: categories,
    width: '100%'
});
```

```
<select name="submission-category" class="category-input text-input--full-width" multiple></select>
```

This is it working without the multiple tag

![ss](http://cl.ly/gYws/d)

Here it is with the multiple tag, as you can see when I choose multiple options it only ever fills the `select2-selection__rendered` div with the last chosen selection. However as you can see from the gif you get a quick flash of it working as intended (mutliple green tags appearing) before it quickly reverts back to this.

![ss2](http://cl.ly/gYVB/d)

**Comment by SgtOddball** [comment]
Have you tried using the multiple tag as stated in the documentation? By which I mean.

```html
<select name="submission-category" class="category-input text-input--full-width" multiple="multiple"></select>
```
Gut instinct makes me think jQuery isn't catching the tag properly.

**Comment by alexcroox** [comment]
Yer I've tried multiple="multiple". Also tried "multiple: true" in the js init options

**Comment by alexcroox** [comment]
If you check the second gif you can also see it's applying the class `select2-selection--multiple` correctly too

**Comment by SgtOddball** [comment]
Humm I wonder if it's not being applied as the array could be causing a race condition? Have you tried delaying select2 being applied until the array has completed?

**Comment by alexcroox** [comment]
Worth trying, I've added a 5 second timeout before initialising select2 in the example above, but still no joy :(

**Comment by alexcroox** [comment]
It works in isolation so I'll have to assume it's something else in my app

https://jsfiddle.net/omzbrq6d/
