### ISSUE TITLE
Ability to add custom HTML elements (icons, captions, etc) possible?

### ISSUE THREAD

**Issue by dlewand691** [select2/select2#4444]
Is it possible to include custom HTML elements within a dropdown, similar to how it's done in the ddSlick plugin? 

[http://designwithpc.com/Plugins/ddSlick#demo](http://designwithpc.com/Plugins/ddSlick#demo)

<img width="285" alt="screen shot 2016-06-27 at 3 53 11 pm" src="https://cloud.githubusercontent.com/assets/1159913/16393599/6a214ae0-3c7f-11e6-94fb-ea3d44b5fde6.png">

Would be a great feature to have. Apologies if this is already there and I missed it.

**Comment by SgtOddball** [comment]
Your best bet would be to use the templating functionality as listed [here in the documentation](https://select2.github.io/examples.html#templating).

**Comment by kevin-brown** [comment]
Yup, templating is the way to go about this. [Here's an example using it](https://select2.github.io/examples.html#themes-templating-responsive-design)
