### ISSUE TITLE
Add possibility to insertBefore instead of insertAfter

### ISSUE THREAD

**Issue by rippersvk** [select2/select2#4445]
In function `Select2.prototype._placeContainer` 
there is code to insert select2 element after actual select tag
    `$container.insertAfter(this.$element);`

I would like to have option to insert it before actual select tag.
Mainly because of error handling when I am using bootstrap.
I set it to insert error texts after inputs (without select2), which using select2 and insertAfter displays error before input...

**Comment by Bmju** [comment]
I have the same problem. The problem applies to the jQuery Validation plugin as well. Once Select2 has been applied, the DOM order is: the orginal input element (hidden by Select2), then any form validation messages, then the inserted Select2 elements. So form validation messages display before the visible input element instead of after it.

**Comment by Bmju** [comment]
I have now understood that the correct solution, at least for jQuery validation, is to use the errorPlacement() callback instead (http://stackoverflow.com/questions/26498899/jquery-validate-custom-error-message-location).

**Comment by tanuj-github** [comment]
It is not only about errorPlacement in Query validation. I have same problem and I ended up finding no solution for such a small thing.

Can we just provide a setting in options to pass the value for insert before/after in cureent select 2 option?

**Comment by alexweissman** [comment]
@MikeBeaton has deleted his fork, so if we still want this as a feature it will need to be submitted as a new pull request.  Please note that a suitable test should be added for this feature as well, in order for it to be considered for a release.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.

**Comment by MikeBeaton** [comment]
I don't think I have permissions to re-open https://github.com/select2/select2/pull/4594 myself (?), but I'm happy to re-open it and add a test or two, if that would help.

**Comment by l10nelw** [comment]
I'd like to make a case that insertBefore should be default behaviour. Currently, browser validation on a select2 field produces an error message in this awkward position:

<img width="581" alt="image" src="https://user-images.githubusercontent.com/1300917/210480816-e1c9879b-2bdf-48d6-8d06-0b597959a072.png">

If the the select2 container was inserted before the select, the validation message would appear under the select2 container as you'd expect them to be.
