### ISSUE TITLE
Nice to have : have a different tooltip for the Clear icon 

### ISSUE THREAD

**Issue by lenamtl** [select2/select2#4456]
I'm using bootstrap (small input) and the clear option may not be user friendly on single-select,
so I added the color red to the Clear icon x so it's helping but can be consing with required file *
I'd like to add tooltip over the x, but right now it showing only the selected item title.
I'd like to keep both...

I have tried to add a tooltip to this span with no luck, I'm out of idea...

```
 var $remove = $(
      '<span class="select2-selection__clear"
     data-toggle="tooltip" title="Clear">' +
        '&times;' +
      '</span>'
    );
```

**Comment by pedrofurtado** [comment]
@lenamtl Send us a PR with this feature. You can base your code in this links:

https://github.com/select2/select2/issues/4530
https://github.com/select2/select2/pull/5291

I will be glad to review that. It's a nice feature, but I am focused now in fix some UI bugs :+1:
