### ISSUE TITLE
Search Dropdown doesn't appear after selecting an option in mobile/tablet

### ISSUE THREAD

**Issue by champsupertramp** [select2/select2#4458]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
## Steps to reproduce the issue
1. I use the following simple code:

``` javascript
jQuery(".um-s2").select2({
        allowClear: false,
        minimumResultsForSearch: 10
});
```
1. Highlighted elements before selecting an option. Search field is showing:
   ![select2-search--dropdown](https://cloud.githubusercontent.com/assets/12200688/16618874/2ee4a0d0-43be-11e6-806a-7543536d2535.png)
2. After selecting an option and trying to select again, the search field is gone.
   ![select2-search--dropdown-missing](https://cloud.githubusercontent.com/assets/12200688/16618978/ae267b0c-43be-11e6-9154-130804e6cea7.png)

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System
- [x]  Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 1.12.4
- Select2 version: 4.0.2 
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.

**Comment by champsupertramp** [comment]
Yeah, after 1 year.

**Comment by alexweissman** [comment]
?

There are still nearly 500 open issues.  I'm trying to rehabilitate the project on my own, I don't have time to try and decipher issues that don't make the problem extremely clear.
