### ISSUE TITLE
Spaces in search field

### ISSUE THREAD

**Issue by DeBr0glie** [select2/select2#4468]
Hello, I can't add spaces in the search field when working with single selects, but It works just fine with multiple selects. 

If I remove type="search", spaces work fine.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by alexweissman** [comment]
`type` is not a valid attribute for `<select>` controls.  See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select
