### ISSUE TITLE
More than one option flagged as selected in single-select matcher

### ISSUE THREAD

**Issue by jessehouchins** [select2/select2#4469]
## Steps to reproduce the issue
1. Create a single-select with a 4 options
2. Add custom matcher that filters out selected items (data.selected === true)
3. Select an option, then another option
## Expected behavior and actual behavior

I would expect to see a selected option in the picker box, and 3 more options in the dropdown. What I actually see is ALL previously selected items are removed from the dropdown... Making more selections just reduces the available options until there are none left.
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer (not tested)

Operating System
- [x] Mac OS X
  others not tested

Libraries
- jQuery version: ?
- Select2 version: 4.0.3

**Comment by kevin-brown** [comment]
Without seeing your code for the matcher, preferably in a jsbin so we can test it live, there isn't much we can do. You've narrowed it down to an issue when using a custom matcher, but that's about all we have to go on right now.

**Comment by jessehouchins** [comment]
@kevin-brown Here is a codepen showing the issue... If I'm doing something wrong in the matcher, let me know, but it seemed to match the examples: http://codepen.io/jessehouchins/pen/WxkjNa

**Comment by jessehouchins** [comment]
FYI, I see the same behavior (more than one option set to selected) when stepping through the built in matcher in v4.0.3.

**Comment by jessehouchins** [comment]
So, the `data.selected` property does get out of sync with the actual selection, but I can just as easily use `data.element.selected` for my purposes. If there cases where that is not an option though, it might be worth fixing.
