### ISSUE TITLE
allowClear will cause selections shifted to the next line in multiple select

### ISSUE THREAD

**Issue by JLHwung** [select2/select2#4470]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Add an array of seven 3-digit choices, use `allowClear` option and `multiple` option, set the parent width to 600px;
2. Select all the choices
## Snippet (Talk is cheap)

http://codepen.io/JLHwung/pen/YWAGjG
## Related issues
#3906
## Expected behavior and actual behavior

When I follow those steps, the 6th choice looks really bad.

I was expecting all the choices look good.
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Not tested on other operating system but I believe it is a general CSS problem.

Libraries
- jQuery version: 2.1.4
- Select2 version: 4.0.3
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a codepen](http://codepen.io/JLHwung/pen/YWAGjG)

**Comment by myDisconnect** [comment]
Having the same issue. Have anyone managed to find a workaround/fix?

**Comment by JLHwung** [comment]
I do find a CSS workaround (written in SASS for brevity) if you add `data-allow-clear` attribute to the `select` DOMNode.

```
<select data-allow-clear="true"></select>
<script>
$('select').select2()
</script>
```

This issue got no attention so I am not encouraged to give a PR.

```
select[data-allow-clear="true"] ~ .select2-container .select2-selection--multiple {
  .select2-selection__rendered {
    padding-right: 24px;
    .select2-selection__clear {
      position: absolute;
      right: 0;
    }
  }
}
&[dir="rtl"] {
  select[data-allow-clear="true"] ~ .select2-container .select2-selection--multiple {
    .select2-selection__rendered {
      padding-left: 24px;
      .select2-selection__clear {
        left: 0;
      }
    }
  }
}
```

**Comment by RobertDiebels** [comment]
Compiled the SASS into CSS:

```
select[data-allow-clear="true"] ~ .select2-container .select2-selection--multiple .select2-selection__rendered {
  padding-right: 24px;
}

select[data-allow-clear="true"] ~ .select2-container .select2-selection--multiple .select2-selection__rendered .select2-selection__clear {
  position: absolute;
  right:    0;
}

[dir="rtl"] select[data-allow-clear="true"] ~ .select2-container .select2-selection--multiple .select2-selection__rendered {
  padding-left: 24px;
}

[dir="rtl"] select[data-allow-clear="true"] ~ .select2-container .select2-selection--multiple .select2-selection__rendered .select2-selection__clear {
  left: 0;
}
```

**Comment by chrisNom** [comment]
I had the same issue and the solution was to give the select2-selection__clear a margin-bottom 5px:

`.select2-container--default .select2-selection--multiple .select2-selection__clear{
  margin-bottom: 5px;
}`

check this [here - jsfiddle](https://jsfiddle.net/cnom/pmoajqr3/)

**Comment by jpic** [comment]
That's funny, both fixes work:

    margin-bottom: 5px;
    margin-bottom: 10px;

**Comment by Cry0nicS** [comment]
Any updates?

**Comment by glen-84** [comment]
@kevin-brown Would it be possible for you to reopen this issue and to consider setting the `exemptLabels` option in `stale.yml`?

**Comment by kevin-brown** [comment]
I just spent a few hours narrowing down the problem here, and creating an automated test in the process, and this is what I found:

* Automated tests of CSS issues are hard
* The correct bottom margin is 2px, not 5px or 10px
* The 2px is because of the borders surrounding choices (removing the borders removes the issue)

I chose to go with a consistent 1px padding instead of a random 2px margin, since it also increases the click target of that icon which is always a plus.
