### ISSUE TITLE
A problem using language setting

### ISSUE THREAD

**Issue by singlebyted** [select2/select2#4473]
I tried set default language `zh-CN` by `$.fn.select2.defaults.set('language', 'zh-CN');`, but it doesn't work anyway. However, `$selector.select2({ language: 'zh-CN' });` is working. 
I checked the source code then I found a snippet like this:

``` javascript
if (this.options.language == null) {
    if ($e.prop('lang')) {
        this.options.language = $e.prop('lang').toLowerCase();
    } else if ($e.closest('[lang]').prop('lang')) {
        this.options.language = $e.closest('[lang]').prop('lang');
    }
}
```

Is that a bug? If its option language is setting by `lang` when we didn't initialize it, what meaning is default options?
Hope someone can help, thanks!

**Comment by yedajiang44** [comment]
哥们！你语言问题解决了吗？我也设置语言后没有任何反应。。。。

**Comment by Jazereg** [comment]
@yedajiang44 年代久远……我当时是在实例上加语言选项的`$selector.select2({ language: 'zh-CN' })`，提问里写了- -，或者你可以写`<html lang="zh-CN">`试试

**Comment by yedajiang44** [comment]
@single-byte 我也设置了，但是就不知道是为啥没起作用，我写的代码： [http://blog.csdn.net/yedajiang44/article/details/78417175](http://blog.csdn.net/yedajiang44/article/details/78417175)

**Comment by single-byte** [comment]
@yedajiang44 把`select2.full.js`的引用删掉

**Comment by yedajiang44** [comment]
@single-byte 确实可以！

**Comment by yedajiang44** [comment]
@single-byte 多谢
