### ISSUE TITLE
allowClear conflicts with selectOnClose

### ISSUE THREAD

**Issue by phazei** [select2/select2#4475]
Create select with a couple options and enable the options allowClear and selectOnClose

When the "x" is clicked on the clear, the select box opens with first item highlighted.  Close box, and now it's selected.

Basically, there's no way to clear if selectOnClose is on...

**Comment by phazei** [comment]
I think just not opening when the x is clicked should take care of it

**Comment by phazei** [comment]
Removing line 65:
```js
    this.trigger('toggle', {});
```
of allowClear.js fixes the issue.  If it's being cleared, it should go away, not open

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by phazei** [comment]
I'm using Select2 4.0.3, ubuntu 16.04, chrome

https://jsfiddle.net/phazei/mbsujhjn/5/

**Comment by phazei** [comment]
I have a temp fix with this:

s2Obj.$selection.on('mousedown', '.select2-selection__clear', function (evt) {
                        s2Obj.close();
                        s2Obj.$element.val(null).trigger('change');
                        evt.preventDefault();
                    });

**Comment by drvid** [comment]
+1 for a fix to this issue please... I use `selectOnClose ` to facilitate keyboard only input, using tab to select/close and move focus to the next form field.

IMHO the clear button should not toggle the select2 menu, as in it should be 'clear-able' with the menu open or closed.

**Comment by gravelld** [comment]
As far as I can see... it's impossible to submit an empty selection if `selectOnClose` is true isn't it?

**Comment by jophj** [comment]
@gravelld exactly

**Comment by gravelld** [comment]
Actually, looks like the remove icons are covered here: https://github.com/select2/select2/issues/3209#issuecomment-149663474

**Comment by boily-qubeos** [comment]
Is there any fix for this issue?
I'm facing the same problem.
Thanks a lot
Roger

**Comment by stesvis** [comment]
This is a very common scenario, is it gonna be fixed?
I definitely need this too.
THanks

**Comment by stesvis** [comment]
@phazei I am trying your temporary fix, but i am not sure I understand..
In **s2Obj.$selection** and **s2Obj.$element** I can guess that s2Obj is you actual dropdown (<select>), but what are **$selection** and **$element**?

**Comment by phazei** [comment]
Nope, $selection and $element are internal things to s2, they come with the object which is defined like so:
```
element.select2(options);
s2Obj = $(element).data('select2');
```

**Comment by DaJoBro** [comment]
I like to solve Problems like this using the options attributes, so I figured this out:
In options:
`                    minimumInputLength: 1,
                    language: {
                        inputTooShort: function () { return ''; }
                    }
`
Unfortunately, this will leave you with a small empty box at the bottom, which you can prevent by using CSS:
`.select2-results__option.select2-results__message:empty {
    display: none;
}
`
Depending on your browser you will still have a small shadow on the bottom of the box.
I thought this might help some people looking for an easy workaround.

But IMO it is strange that this issue isn't fixed yet, this is a common scenario in my applications too. There should be an option to disable opening the menu on clearing, as this is frequently requested and most workarounds will collide with selectOnClose. Alternatively, you should disable selectOnClose if there is no input.

**Comment by ghost** [comment]
This is still an issue in the latest 4.1.0-rc.0

With options.selectOnClose = true and options.allowClear = true it clears the selection the when you click the X but then selects whatever option is active in the list.
