### ISSUE TITLE
Doesn't work in iOS UIWebView

### ISSUE THREAD

**Issue by adam-lynch** [select2/select2#4482]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Use basic example in an iOS WebView
2. Tap on it
3. Nothing happens
## Expected behavior and actual behavior

Expected it to open but it doesn't.
## Environment

Browsers
- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [x] UIWebView (Safari kinda)

Operating System
- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile
- [x] iOS

Libraries
- jQuery version: 2.1.4
- Select2 version: 4.0.3
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

---

Works fine everywhere (including iOS Safari) but the `mousedown` event doesn't seem to get fired in the WebView at all. My workaround is to duck punch `$.fn.on` and `$.fn.off` mapping `mousedown` to `click`;

``` coffeescript
        if appIsCurrrentlyRunningInOurMobileApp
                convertMousedownEvent = (originalMethod) ->
                    return (event, callback) ->
                        if typeof event is 'string' and event.indexOf('mousedown') is 0 and
                        (event.indexOf('select2') isnt -1 or this.get(0)?.className?.indexOf('select2') isnt -1)
                            args = Array.prototype.slice.call arguments
                            args[0] = event.replace 'mousedown', 'click'
                            args[1] = (e) ->
                                e.which = 1 # pretend it's a left-click because they check in some places
                                return callback.call this, e
                        else
                            args = arguments

                        return originalMethod.apply this, args

                $.fn.on = convertMousedownEvent $.fn.on
                $.fn.off = convertMousedownEvent $.fn.off
```

I can't figure out why but tapping on a result still didn't do anything then, so I had to do the following in the `open` event callback (and unbind when the `close` event is fired):

``` coffeescript
        if appIsCurrrentlyRunningInOurMobileApp
            selectedClass = 'select2-results__option--highlighted'

            $nativeSelect.data('select2').$results.on 'touchend', '.select2-results__option', (e) ->
                $(e.target).siblings().removeClass selectedClass
                $(e.target).addClass(selectedClass).trigger 'click'

```

Sorry it's CoffeeScript 😄 

---
#2833 could've been related to this.

**Comment by ktemo** [comment]
I have the same problem using it in a cordova application. @adam-lynch so, the workaround works for you?

**Comment by Narretz** [comment]
Are you by any chance using ionic? Because I have the same problem, but only if the select is inside a `ion-content` directive.

**Comment by Narretz** [comment]
For the record, I've solved this for in the following way: 
```
// Init select2 on element

// Get the select container - this is probably different for multiple
var e = $(document.querySelector('.select2-selection--single'));

// Remove select2 mousedown listener from element
            e.off('mousedown');

// Implement toggle with click instead of mousedown
            e.on('click', function() {
              if (e.select2('isOpen')) {
                  e.select2('close');
              } else {
                  e.select2('open');
              }
            });

```

I believe mousedown was used because mobile browsers / webviews had the 300ms delay for clicks. However, this has been removed for a while, so using click is the way to go
