### ISSUE TITLE
Override events propagation

### ISSUE THREAD

**Issue by dariospadoni** [select2/select2#4486]
Hello

In my app I'd need to handle keys events (such as arrows keys or enter pressed); I see in the code that those are not propagated so I have no way to handle that. What would the best way to propagate/handle them?

Thanks

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
