### ISSUE TITLE
Suggestion: allowClear and BACKSPACE behavior change in multiple select 

### ISSUE THREAD

**Issue by evil-shrike** [select2/select2#4489]
Hi.

If we specified `allowClear` option for multiple select then we'll not get clear button (as for single select). But instead BACKSPACE will be handled as clearing all values. 
I think that removing all values at once on a BACKSPACE press is not very good solution. But I understand that multiple select should support `allowClear` in some way and it was chosen as that way. But why did you decide to not add clear button (cross) in the same way as for single select?

**Comment by alexweissman** [comment]
This is a duplicate of #3335.
