### ISSUE TITLE
Feature Request: easy way to replace AttachBody adapter

### ISSUE THREAD

**Issue by evil-shrike** [select2/select2#4491]
I want dropdown to be not absolutely positioned but placed right under selection input (i.e. under the span with `select2-selection` class).  
As I understand `AttachBody` adapter is responsible for dropdown positioning. And the only way to replace it - is specify `dropdownAdapter` option.  
But if we pass `dropdownAdapter` option when we'll have to repeat a lot of configuration on our own (add DropdownSearch, MinimumResultsForSearch, CloseOnSelect). It's pretty tedious.

I'd suggest to introduce a new option - `dropdownPositioningAdapter` which would contain `AttachBody` instance by default but could be easily overridden.

``` js
    if (options.dropdownAdapter == null) {
      if (options.multiple) {
        options.dropdownAdapter = Dropdown;
      } else {
        var SearchableDropdown = Utils.Decorate(Dropdown, DropdownSearch);

        options.dropdownAdapter = SearchableDropdown;
      }

      if (options.minimumResultsForSearch !== 0) {
        options.dropdownAdapter = Utils.Decorate(
          options.dropdownAdapter,
          MinimumResultsForSearch
        );
      }

      if (options.closeOnSelect) {
        options.dropdownAdapter = Utils.Decorate(
          options.dropdownAdapter,
          CloseOnSelect
        );
      }

      if (
        options.dropdownCssClass != null ||
        options.dropdownCss != null ||
        options.adaptDropdownCssClass != null
      ) {
        var DropdownCSS = require(options.amdBase + 'compat/dropdownCss');

        options.dropdownAdapter = Utils.Decorate(
          options.dropdownAdapter,
          DropdownCSS
        );
      }

      options.dropdownAdapter = Utils.Decorate(
        options.dropdownAdapter,
/// change: begin
        options.dropdownPositioningAdapter || AttachBody // currently it's: AttachBody
/// change: end
      );
    }
```

**Comment by evil-shrike** [comment]
Will you accept a PR with `dropdownPositioningAdapter` option?

**Comment by kevin-brown** [comment]
As you've noted, the easiest way (aside from modifying the core JS) is to repeat the necessary adapter combination such that you have the `dropdownAdapter` that you are looking for.

> Will you accept a PR with dropdownPositioningAdapter option?

There are (undocumented) plans in the work to better handle cases like this, where default adapters need to be swapped out.

**Comment by pedrofurtado** [comment]
Please, send us a complete JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
