### ISSUE TITLE
Data function of multiselect returning old removed data too

### ISSUE THREAD

**Issue by sgsmittal** [select2/select2#4493]
Hi there,

I have trying to retrieve selected object from multiselect control.
But it is giving me old removed objects too.

Steps:-

1.) I have selected three values "A1, A2, A3" .
2.) Then I have removed A2, A3 by clicking on their individual cross button.
3.) Now I have tried to get data from this dropdown using  $('#id').select2('data');

Expected:- It should return A1.
Actual:-    It is returning A1, A2 & A3 all three records.

Am I missing anything ?

**Comment by SgtOddball** [comment]
Which version does are you seeing this on and is it possible to produce a reduced test case?
