### ISSUE TITLE
Stop keyup event if keydown was handled

### ISSUE THREAD

**Issue by evil-shrike** [select2/select2#4495]
there's code which catches `keydown` event, converts it into `keypress` own event and stops its propagation:

```
    this.$selection.on('keydown', '.select2-search--inline', function (evt) {
      evt.stopPropagation();

      self.trigger('keypress', evt);
```

But `stopPropagation` in keydown's handler does not prevent `keyup` firing. So later there will be a `keyup` event bubbling outside Select2. 

`keyup` event is commonly used to close dialogs for example. So if I press ESC in select2 with open dropdown this dropdown will close but so does the dialog. 

What I want: if I press ESC with opened dropdown then only dropdown should close, but if I press ESC with closed dropdown then the event should bubble (e.g. dialog should close).

Currently to fix it I have to catch `keyup` on some Select2's element.  But it's tricky because it depends on the fact whether dropdown is opened or closed. But in `keyup` handler is hard to understand whether dropdown was opened or closed because it's already closed in any way:

```
            select2.$selection.on("keypress keyup keydown", function (e) {
                // if (select2.isOpen())  <- this does not work
                e.stopPropagation();
            });
```

What I suggest: beside 'keydown' add 'keyup' handler where stop propagation if `keydown` was handled:

```
    this.$selection.on('keyup', function (evt) {
        if (self._keyUpShouldPrevented) {
            evt.stopPropagation();
        }
    });
```

NOTE: there's `_keyUpPrevented` field already which would suite well but it's reset in `Search.prototype.handleSearch`.

**Comment by alexweissman** [comment]
Probably the cause of #2731, which I closed because it seemed to be a problem with Bootstrap, not Select2.

But, this is worth taking a closer look at - if the review comments in #4498 are addressed, we could consider merging the PR.
