### ISSUE TITLE
Remove support for legacy IE

### ISSUE THREAD

**Issue by lininu** [select2/select2#4496]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. https://select2.github.io/examples.html
2. go to "Loading remote data"
## Expected behavior and actual behavior

Search something like 'a' or anything else. 
Developer tool console show the error in line 3472 of "can't defined $request.status" and it can't display searching result.
## Environment

Browsers
- [ ] Google Chrome
- [ ] Mozilla Firefox
- [x] Internet Explorer 8 & Internet Explorer 9 & Internet Explorer 10

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: jQuery v1.11.2
- Select2 version: Select2 4.0.3
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by cxytomo** [comment]
Is your select2 inside bootstrap modal? I encountered the same the problem in modal. But it works when I initial it after page loaded.

**Comment by wiliam2015** [comment]
Hello this problem still in IE8 and I Encounter this problem。 This bug happens on the examples page, how to solve this problem,thanks.

**Comment by kevin-brown** [comment]
Changing the focus of this to just dropping older support for IE because it's old.
