### ISSUE TITLE
Horizontal collision detection with dropdownAutoWidth: true

### ISSUE THREAD

**Issue by andreyvolokitin** [select2/select2#4497]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Make select2 appear near right edge of the screen (`float: right` on wrapper will do it)
2. Put some moderate-length nonwrapping string inside an option (i.e. SomeOptionText)
3. Init select2 with `dropdownAutoWidth: true` and `width: 90` (width is just for example)
4. Open select2 and see how dropdown is overflowing body horizontally: http://output.jsbin.com/vulajaxaja
## Expected behavior and actual behavior

When I follow those steps, I see that opened select2 dropdown is overflowing body horizontally

I was expecting that there will be some sort of collision detection in case there is not enough space and dropdown will flip its direction to the opposite side
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System
- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 1.12.4
- Select2 version: 4.0.3
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](http://output.jsbin.com/vulajaxaja)

**Comment by thiagocoelho** [comment]
Same problem here. I opened a question in Stackoverflow about this.

https://stackoverflow.com/questions/45339207/wrong-position-when-using-select2-dropdownautowidth

**Comment by agrawalrohant** [comment]
Hi, is there any plan to fix this ?

**Comment by gadzhov** [comment]
Hi, is there any chance this to be fixed soon?
