### ISSUE TITLE
Chrome scroll up

### ISSUE THREAD

**Issue by sermatech** [select2/select2#4502]
Hi,
When we add a new element in select2 by typing special character (example "new value@") in Firefox is all right. 
In Chrome when we type "new value@" the item is added correctly but the page scroll up. 
Anyone know why?

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by svilupposermatech** [comment]
Hello Kevin 
In the test case attached you can check that adding new tag with "@" it jump always on the last select2 at the bottom. in our web site  it jump at the top but i suppose  the origin of the bug is the same. 

[esempio.txt](https://github.com/select2/select2/files/474207/esempio.txt)

thank you for the support

**Comment by svilupposermatech** [comment]
Hello Kevin 

any news about this issue?

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
