### ISSUE TITLE
Doesn't play well with jQuery 3.1.0

### ISSUE THREAD

**Issue by asantos** [select2/select2#4503]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. execute select2 code with jquery 3.1.0
2. error will be produced

## Environment

Libraries

- jQuery version: 3.1.0
- Select2 version: 4.0.1

## Isolating the problem

- [x] The bug happens consistently across all tested browsers

**Comment by morrow95** [comment]
Damn... I just came here to see if anyone had posted anything prior to testing out my site with jquery 3.  Guess I'll have to wait till there is an update, but at least I don't have to edit, upload, and test the site now.

**Comment by ypnos-web** [comment]
I don't see any issues here with this setup:

* jQuery version: 3.1.0
* Select2 version: 4.0.3

**Comment by kevin-brown** [comment]
We _really_ need a JSbin that demos the issues with jQuery 3 and Select2 4.0.3, or it's going to be impossible to track this down.

I'm going to close this off until the jsbin/jsfiddle comes in, after which I can reopen this.
