### ISSUE TITLE
Filtering for optgroups should show their contents

### ISSUE THREAD

**Issue by ypnos-web** [select2/select2#4505]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Go to https://select2.github.io/examples.html#select-boxes-with-labels
2. Enter "pac"
## Expected behavior and actual behavior

Currently, it will find the resp. optgroup and only show that. This is almost useless, as an optgroup cannot be selected anyways.

Instead, the optgroup with all its associated options should be shown, so that the user can filter for the group and then select the desired option.
## Environment

Browsers
- [x] Google Chrome

Operating System
- [x] Linux

Libraries
- jQuery version: 3.1.0
- Select2 version: 4.0.3
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)

**Comment by SgtOddball** [comment]
Thats not a bad idea, but how will it cope with having `pac` in a different group? 

I would propose that it's be better instead to completely ignore the optgroups instead.

**Comment by ypnos-web** [comment]
What I am suggesting is that whenever an optgroup matches, all its corresponding options are treated as being matched (and therefore shown under the optgroup). So there is no conflict with multiple matches in optgroups or options (which now and then shows the option under its by-itself nonmatching optgroup).

However I agree that for some scenarios people might want to disable matching of optgroups all together.

**Comment by SgtOddball** [comment]
But what if what you want to match on is a partial for an optgroup as well as match to an option in another optgroup?

It would be confusing for the users since they've got no way to select that they want to match the optgroup values or not.

**Comment by kevin-brown** [comment]
This can be handled through a custom `matcher`. It's very close to the [original matcher](https://github.com/select2/select2/blob/3f8492b62f72b34f6a25ed5ae8ffc9a6826cb69d/src/js/select2/defaults.js#L309-L352), just you wouldn't need to [strip out non-matching child objects](https://github.com/select2/select2/blob/3f8492b62f72b34f6a25ed5ae8ffc9a6826cb69d/src/js/select2/defaults.js#L327-L330).

**Comment by chrispcb** [comment]
Like jquery chosen plugin no ?
https://harvesthq.github.io/chosen/ <optgroup> support

**Comment by alexweissman** [comment]
This is now well-documented: https://select2.org/searching#matching-grouped-options

> Only first-level objects will be passed in to the `matcher` callback. If you are working with nested data, you must iterate through the `children` array and match them individually. This allows for more advanced matching when working with nested objects, allowing you to handle them however you want.

**Comment by elinfante** [comment]
Has this issue been resolved? I am having exactly the same problem, but what alexweissman is suggestion does not work

**Comment by markusweb** [comment]
what about pull request  https://github.com/select2/select2/pull/4722 this seems to do the trick?

**Comment by APerricone** [comment]
Really is it closed? this behaviour make groupopt unusable! It has no sense that show a group without the children, the group is unselectable!

**Comment by NicoxDJ** [comment]
Searching for the same thing too...
