### ISSUE TITLE
Selecting item goes "through" to the under lying elements

### ISSUE THREAD

**Issue by e11en** [select2/select2#4506]
When I am testing the select box on a iPhone 4 (os version 4.0) in the safari browser I get a strange thing. When ever I select an item the under lying button is being activated as well. (see gif)

![output](https://cloud.githubusercontent.com/assets/855939/17213922/d52b9862-54d6-11e6-8fff-cc89c94627ce.gif)

I don't get this when I'm using it in Chrome. 

I'm using the 4.0.2/js/select2.js and two language files 4.0.1/js/i18n/nl.js and 4.0.1/js/i18n/de.js
directly from cdnjs.cloudflare.com (I assume those are the latest from the master branch)
jQuery version is v1.11.3.

**Comment by alexweissman** [comment]
Can anyone confirm if this is still an issue in the latest version of Select2 and iOS?
