### ISSUE TITLE
Multi-select dropdown opens on almost any key pressed in contrast of single-select dropdown opens only on alt-down/enter/space

### ISSUE THREAD

**Issue by evil-shrike** [select2/select2#4512]
Create two similar controls but one is single-select and the other is multi-select. Tab into the first one and press DOWN (arrow). Nothing happens (window will be scrolled). Now do the same in milti-select. On pressing DOWN dropdown will be opened. But not only DOWN almost on any key pressed if ctrl/alt/shift is not pressed. 

If we look at `Select2._registerEvents` it's clear that dropdown should be opened on ALT+DOWN/Enter/Space.

So why dropdown is being opened in multi-select mode?

The reason is 'select2/selection/search', its keyup handler call `handleSearch`

```
  this.$selection.on(
    'keyup.search input.search',
    '.select2-search--inline', 
    function {
        var key = evt.which;

        // We can freely ignore events from modifier keys
        if (key == KEYS.SHIFT || key == KEYS.CTRL || key == KEYS.ALT) { return; }

        // Tabbing will be handled during the `keydown` phase
        if (key == KEYS.TAB) { return; }

        self.handleSearch(evt);
  });
```

it tries to filter out some key (Shift/Alt/Ctrl/Tab). But it's definitely not enough. Actually on any other key press dropdown will opened in multi-select.  
Btw it's very strange check forr a keyup handler - shift/alt/ctrl won't be as a value of `which` field, they are boolean fields of event object (shiftKey, altKey, ctrlKey). 

Expected behavior:
any symbol key triggers search and dropdown opening, any other don't. If I press arrows nothing should happens.

**Comment by VitaliyR** [comment]
Old one, and still exists.

Fixed temporary in my code via requiring `search`, and overriding `Search.prototype.bind`.

**Comment by alexweissman** [comment]
This issue is discussed in more detail in #3472 and #4586.
