### ISSUE TITLE
"Loading more results..." always displays, then results disappear in IE if scrolling down.

### ISSUE THREAD

**Issue by DERNERSERFT** [select2/select2#4518]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Populate results with AJAX.
2. Scroll to bottom, "Loading more results..." always displays.
3. Try to scroll past that, message changes to "The results could not be loaded." and all results disappear (Internet Explorer only).
## Expected behavior and actual behavior

When I follow those steps, I see...
"Loading more results..." then no results.

I was expecting...
No "Loading more results..." message when reaching the end, with applicable results still displaying.
## Environment

Browsers
- [ ] Google Chrome (Always displays "Loading more results..." even if end of results.)
- [ ] Mozilla Firefox (Always displays "Loading more results..." even if end of results.)
- [x] Internet Explorer (IE11 makes scrolling past "Loading more results..." message change to "The results could not be loaded." and all results disappear.)

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: Tried 1.9.1, 2.2.4, and 3.1.0 (same results).
- Select2 version: 4.0.3
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers (Sort of, explained above.)
- [x] This bug happens when using Select2 without other plugins (Only other plugin used is qTip2, tried removing it—same thing.)
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

`$('#search').select2({
            ajax: {
                url: 'ajax/ajSelect2.php?data=search',
                dataType: 'json',
                type: 'POST',
                delay: 250,
                data: function (params) {
                    return {
                        term: params.term,
                        page: params.page,
                        page_limit: 30,
                        year: $('#cboYear option:selected').val(),
                        type: $('#cboTicketType option:selected').val()
                    };
                },
                processResults: function (data, params) {
                    params.page = params.page || 1;
                    return {
                        results: data.items,
                        pagination: {
                            more: (params.page * 30) < data.total_count
                        }
                    };
                },
                cache: true
            },
            escapeMarkup: function (markup) { return markup; }
        });`

`<select id="search" name="cboSearch" style="width: 300px" onchange="this.form.submit();"></select>`

**Comment by alexweissman** [comment]
I cannot reproduce this issue in IE11, on the AJAX docs page.
