### ISSUE TITLE
select2-selecting firing multiple times 

### ISSUE THREAD

**Issue by bhalke** [select2/select2#4523]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by bhalke** [comment]
$('#myfootType').on("select2-selecting", function (e) {
                    scope.myfootType(e.choice.text);
                });
calling scope.myfootType()  method.. 11 times.

**Comment by SgtOddball** [comment]
What does the scope.myfootType do? If that triggers the select2-selecting listener then it will loop it's self.

You could always add a run listener to prevent it running after the initial trigger.

**Comment by kevin-brown** [comment]
There are three things here

1. `select2-selecting` is the old event name for the 3.x series of Select2, which is triggered whenever something is selected. The event was renamed to `select2:selecting` in Select2 4.0.
2. This event is triggered before any option is selected, even if multiple options are going to be selected at once. This is not like the `change` event, which fires every time the underlying value changes (which may include multiple changes).
3. You didn't include _any_ of the required information when creating this ticket. As a result, it's absolutely impossible for us to help out here.

----

Note that Select2 3.5.4 is no longer supported. We recommended that you upgrade to the latest Select2 4.x series when possible.
