### ISSUE TITLE
How to change z-index of one instance of select2?  

### ISSUE THREAD

**Issue by oshihirii** [select2/select2#4533]
`select2.full.min.js` @ `v4.0.3`. 

I want to change the z-index of `.select2-dropdown` to `99999` in only one instance of `select2`.  

I tried adding:
```
$('.myclass').select2({
    containerCssClass: "thisworksgreat"
});
```
as per:

http://stackoverflow.com/a/30789555

And the class is added here:
```
<span aria-expanded="true" aria-haspopup="true" role="combobox" class="select2-selection select2-selection--multiple thisworksgreat" tabindex="-1" aria-owns="select2-my_tags-results"><ul class="select2-selection__rendered"><li class="select2-search select2-search--inline"><input type="search" aria-autocomplete="list" role="textbox" spellcheck="false" autocapitalize="off" autocorrect="off" autocomplete="off" tabindex="0" class="select2-search__field" placeholder="" style="width: 2.25em;"></li></ul></span>
```
But that does not wrap around:

    <span class="select2-dropdown select2-dropdown--below" dir="ltr" style="width: 614px;">

Which appears towards the bottom of the DOM.  

How can I change the z-index of one instance of select2?

**Comment by oshihirii** [comment]
https://github.com/select2/select2/issues/3388

Show how you can change the z-index for all instances, but not for one.

**Comment by oshihirii** [comment]
Solution:

Use full version and this:
```
$('.myclass').select2({
dropdownCssClass: "increasedzindexclass",
...
```
CSS:
```
.select2-dropdown.increasedzindexclass {
  z-index: 999999;
}
```
from:

https://github.com/select2/select2/issues/2879

**Comment by shammlo** [comment]
+1 for the solution.
