### ISSUE TITLE
Mousewheel scrolling over results misbehaves when scrolling reaches bottom and horizontal scroll is visible 

### ISSUE THREAD

**Issue by ipap85** [select2/select2#4542]
Fixed by replacing this line:

`self.$results.get(0).scrollHeight - self.$results.height()`

with this:

`self.$results.get(0).scrollHeight - self.$results.get(0).clientHeight`

Tested on
Google Chrome, Mozilla Firefox
OS: Windows

Libraries
- jQuery version: 2.1.4
- Select2 version: 4.0.3

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
