### ISSUE TITLE
New Tags Numeric show options with that ID

### ISSUE THREAD

**Issue by matiazar** [select2/select2#4545]
Hi
I have a problem

I have made a multiple tag manager for selecting colors
Red, Green, Blue, Black, etc..

so, the user can select multiple of them. But i want to the user ADD new colors too.. so I used the tags=true option

but now i have a problem.

my default color are coming from DB with their IDs
1. Red
2. Green
3. Blue
4. Black

and if the user wants to add a color called 3 the Select2 add me to the select the option Blue automatically .

That is a bug or a problem.
Thanks

**Comment by ekahrovic** [comment]
Same thing here. Have you found any solution for the issue?

**Comment by ekahrovic** [comment]
This is definitely a bug: [https://github.com/select2/select2/issues/3681](url)

**Comment by matiazar** [comment]
yes. dont use numbers for id, elsewhere use the whole name, like Red, Green, Blue...

**Comment by alexweissman** [comment]
Closing this as a duplicate of #3681.
