### ISSUE TITLE
Setting selected value using select tag

### ISSUE THREAD

**Issue by jreason** [select2/select2#4546]
Hi,

Is it possible to set the selected value for each select menu using the select tag?
Example <select data-val="[1,2]">
So that when all the menu's are initiallized by a class, it picks up the correct value?

For new forms its not a problem, but when loading / editing forms again where you can have 10+ select menu's that are printed out using PHP, it would be really handy not to have to write the jquery for each select box that has a value. The select menu's are added dynamically by the user.

Cheers
James

**Comment by alexweissman** [comment]
If the dropdowns are being dynamically added by the user, you should have an event handler that initializes the control as desired.  You shouldn't need to have 10 different `.select2()` calls in your code.
