### ISSUE TITLE
inputting letters and selecting tags while using tagging refreshes/shakes/jolts/refocuses the screen in mobile but not on desktop 

### ISSUE THREAD

**Issue by manning626** [select2/select2#4548]
I have only tested this with an Iphone in Safari and Chrome but if you go to 

https://select2.github.io/examples.html#tags

if you select a tag or if you type a letter into the input box it results in the screen doing a weird shaking/jolting/refocusing motion from left to right back to left that is very distracting as it updates the search results. this does not exist on the desktop. 

just curious what causes this and if there is any work around?

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
