### ISSUE TITLE
Select2 retains values if the user navigates using Browser Back button

### ISSUE THREAD

**Issue by aalokm** [select2/select2#4549]
Hi,

First of all, I have used this plugin quite often & found it wonderful. Thank you for it. 

coming to the issue now. The issue I am facing here is pretty simple. I have the select2 dropdown on my screen which is initialized using the basic script.

`$('#dropDownId').select2();`
## Steps to reproduce the issue
1. Change  the value of select2 dropdown.
2.  Move to a new page using some other link on the page.
3. Once the page is loaded completely, click on Browser back button to navigate back to the old screen.
## Expected behavior and actual behavior

When I follow those steps, I see that the select2 will not be showing the first entry in the list but the last selected entry.

I was expecting it to show the first entry by in the list instead.

Browsers
- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [ ] Windows
- [ ] Mac OS X

Libraries
- jQuery version: 1.11.x
- Select2 version: 4.0.1

**Comment by vol7ron** [comment]
That seems consistent with browser behavior of forms and not a bug.  When the browser is refreshed (or loaded via the back button), form elements (check boxes, input, radio, select, textarea, etc) retain their values.

If you don't want sticky values, you should force the browser to reset form elements after DOM ready.

**Comment by abhishek77in** [comment]
I am facing an issue where select2 multiple does not (appear to) retain value after hitting the browser back button. But the value appears to be hidden and items are still in selected state.

When I select a new value the old selected values also appear. Any possible way I can debug this and fix.

I am using a multi selectbox, and I am using turbolinks.

**Comment by aslamzc** [comment]
$(document).ready(function () {
});
 add your code inside above function.

**Comment by abhishek77in** [comment]
@aslamzc That's doesn't seem to have an impact.

```
$(document).on('turbolinks:load', function() {
  function ignoreDotAndWhitespace(params, data) {
    params.term = params.term || '';

    term = params.term.toUpperCase();
    text = data.text.toUpperCase().replace(/\./g, '').replace(/\s+/g, '');

    if (text.indexOf(term) > -1 ) {
      return data;
    }
    return false;
  }

  $('.select2').select2({
    matcher: function(params, data) {
      return ignoreDotAndWhitespace(params, data);
    }
  });
});
```

**Comment by nikhilbhatia22** [comment]
@abhishek77in Manually triggering change on select2 when document-ready, seems to work, but I think better solution should be there. 

Also, this seems to be a problem only in chromium based browsers. With firefox, it seems to work perfectly, without doing anything.

**Comment by 96StanleyLee** [comment]
> I am facing an issue where select2 multiple does not (appear to) retain value after hitting the browser back button. But the value appears to be hidden and items are still in selected state.
> 
> When I select a new value the old selected values also appear. Any possible way I can debug this and fix.
> 
> I am using:
> 
> * multi select box
> * turbolinks.
> * Select2 4.0.3
> * jQuery v1.12.4

Did you ever happen to resolve this?

**Comment by TB-Development** [comment]
> > I am facing an issue where select2 multiple does not (appear to) retain value after hitting the browser back button. But the value appears to be hidden and items are still in selected state.
> > When I select a new value the old selected values also appear. Any possible way I can debug this and fix.
> > I am using:
> > 
> > * multi select box
> > * turbolinks.
> > * Select2 4.0.3
> > * jQuery v1.12.4
> 
> Did you ever happen to resolve this?

I am experiencing the same exact thing.  Has anyone come up wihth a solution?
