### ISSUE TITLE
cannot display the placeholder with the numbers

### ISSUE THREAD

**Issue by fannysispriadi** [select2/select2#4551]
I use this sccript:

` <select class = "form-control select2" placeholder data = "1" style = "width: 100%;">`

I have a problem displaying a placeholder number.

give me a solution. thank you

**Comment by holmes2136** [comment]
Do you mean when it initial by the following snippet , and it's not working ? 

 ```
$("#test").select2({
    placeholder:134
});
   
```
if it's the situation you mention , 
you can initial it by  add double quote like the following 
 ```
$("#test").select2({
    placeholder:"134"
});
   
```

**Comment by fannysispriadi** [comment]
its work. Thanks.
