### ISSUE TITLE
Default dropdown positioning for varying default/OS font sizes

### ISSUE THREAD

**Issue by vol7ron** [select2/select2#4553]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. In Windows (tested Windows 8), with screen resolution of 1920x1080 (MS Surface); set font-size to Medium (125%) [compare with behavior @ 100% font-size)
2. Load a webpage with Select2 options in Firefox
3. Give Select2 element focus
## Expected behavior and actual behavior

Actual Behavior:
- Options list appears above the element, despite plenty of space for it to appear below the element

Expected behavior:
- Options list should appear below the element of options - the same behavior @ 100% font-size
## Environment
- Windows 8 
- Surface Pro3 
- Native Resolution

Browsers
- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 1.12.4
- Select2 version: 4.0.3
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
  For the _placeholder with labels_ multi-select dropdown

**Comment by vol7ron** [comment]
I think this is related to https://github.com/select2/select2/issues/3303

**Comment by dvc** [comment]
works for me to restore this.trigger('open') in Select2.prototype.open():
```
  Select2.prototype.open = function () {
    if (this.isOpen()) {
      return;
    }

    this.trigger('query', {});
    this.trigger('open'); // !!!
  };
```

**Comment by vol7ron** [comment]
@dvc I'll test it again with the examples page when I have a moment.  Are you suggesting that there's been a fix?  If so could you link to the commit?
