### ISSUE TITLE
can not use the placeholder

### ISSUE THREAD

**Issue by xuezj** [select2/select2#4556]
my code：
<div class="col-xs-6 col-md-3 col-md-offset-5 option1" style="">
                <select id="sel_menu3" class="form-control " >

                </select>
            </div>
            <script>
                $("#sel_menu3").select2( {
                    minimumInputLength: 1,
                    language : 'zh-CN',
                    placeholder:"选择学校",
                    ajax: {
                        url: "{:U('Register/finds')}",
                        dataType: 'json',
                        delay: 250,
                        data: function (params) {
                            return {
                                name: params.term, // search term
                                page: params.page
                            };
                        },
                        processResults: function (data, params) {
                            params.page = params.page || 1;

                            return {
                                results: data.list,
                                pagination: {
                                    more: (params.page * 30) < data.count
                                }
                            };
                        },
                        cache: false
                    },
                    escapeMarkup: function (markup) {
                        return markup;
                    }, // let our custom formatter work
                    templateResult: formatRepoProvince, // omitted for brevity, see the source of this page
                    templateSelection: formatRepoProvince,
                });
                function formatRepoProvince(repo) {
                    if (repo.loading)
                        return repo.name;

                    var markup = "<div>" + repo.name + "</div>";
                    return markup;
                }
            </script>
or：

                <select id="sel_menu3" class="form-control " >
                     <option value="">选择学校</option>
                </select>

         
but the view show “undefined” 。How to add hintmessage。give me a solution. thank you

**Comment by Phibbs14** [comment]
You need to include an initial option for the placeholder to work:
`<select id="sel_menu3"><option value="">选择学校</option></select>`

http://stackoverflow.com/questions/21413241/how-to-use-placeholder-as-default-value-in-select2-framework

**Comment by xuezj** [comment]
still the view show “undefined”

**Comment by vol7ron** [comment]
Did you try adding it to the select:
```
<select id="sel_menu3" data-placeholder="选择学校">
  <option></option>
</select>
```

**Comment by xuezj** [comment]
@vol7ron not help ，the view still show “undefined” ，thank you

**Comment by xuezj** [comment]
ajax：            
                       templateResult: formatRepoProvince, 
                        templateSelection: formatRepoSelection,
             -----------------
              
            two function:
                    function formatRepoSelection (repo) {
                        return repo.name|| repo.text;
                    }
            function formatRepoProvince(repo) {
                if (repo.loading)
                    return repo.name;

                var markup = "<div>" + repo.name + "</div>";
                return markup;
            }
