### ISSUE TITLE
Fix commonjs support

### ISSUE THREAD

**Issue by pcfreak30** [select2/select2#4557]
You are using a half-baked/broken UMD shim that does not work in common JS. You do not set module.exports or return the factory.

**Comment by kevin-brown** [comment]
Our current wrapper is based on https://github.com/umdjs/umd, an older version than what is currently there.

It appears as though there was an update which fixed this issue in https://github.com/umdjs/umd/commit/2bbe19cc557fb1b99691932911e533cdc391d1f5.

**Comment by pcfreak30** [comment]
My PR uses the same I believe.
