### ISSUE TITLE
Ajax call aborted when click in window (select2 ajax and multiple)

### ISSUE THREAD

**Issue by EdouardTack** [select2/select2#4561]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. I use the select2 with ajax search in multiple mode
2. When i typing in the input, the ajax call start
3. When i click on my document or select2 input and the ajax call is not finish, the call is aborted
## Expected behavior and actual behavior

Can we tell select2 to not abort ajax call ?

Thanks
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 1.11.1
- Select2 version: 4.0.1
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
What is the use case for this?  Why is it a problem if the request is aborted?  Clicking outside of the dropdown is essentially a "cancel" type of action.

**Comment by EdouardTack** [comment]
Hello,
I don't remember this issue. I think it was a problem with a project of my old job.
I close this issue.
