### ISSUE TITLE
Prepopulate with "Recent searches"

### ISSUE THREAD

**Issue by marcesh** [select2/select2#4562]
Is it possible to pre-populate the select with data so one can e.g. make a list of "recent searches"? 
how could this be achieved?

**Comment by SgtOddball** [comment]
If you're wanting dynamic live data (regardless of when the page was last refreshed) then you need to look at making an ajax call and getting your backend to return the values (i.e. ajax call to server triggers a database call to return most recent searches). 

[Read here for more ](https://select2.github.io/examples.html#data-ajax)

P.S. This is more of a usage question than a bug or feature request so really shouldn't be asked here. You might be better served on Stackoverflow which would also have further various examples of using Ajax.

**Comment by alexweissman** [comment]
Agreed, this is likely a server-side concern.  If you wanted to implement this client-side, the best approach would be to attach a handler to one of Select2's [events](https://select2.org/programmatic-control/events) and then store a list of recent searches in `localStorage` or some other client-side storage mechanism.
