### ISSUE TITLE
What is the JSON I send supposed to look like?

### ISSUE THREAD

**Issue by cal97g** [select2/select2#4568]
Has it occurred to you lot that just by showing people the json we're supposed to send we could fix a lot of issues? I'm not a JavaScript expert and wouldn't really like to take a guess at what's supposed to be going on.

This is my Json

`{
  "results": [
    "Chemie", 
    "Erziehungswissenschaften", 
    "Politikwissenschaften", 
    "Sprach- / Kulturwissenschaften", 
    "Informatik", 
    "Volkswirtschaftslehre", 
    "Physik", 
    "Geowissenschaften", 
    "Geschichte", 
    "Biologie", 
    "Philosophie", 
    "Sozialwissenschaften", 
    "Psychologie", 
    "Mathematik", 
    "Medien- / Kommunikationswissenschaften", 
    "Betriebswirtschaftslehre", 
    "Kunst / Musik"
  ]
}`

Is it right or wrong?

**Comment by cal97g** [comment]
I'll do the honours of providing the correct JSON format somewhere relevant to this project.

it is:

`
{
    "results":[
         {
             "id":"X",
             "text":"X"
         }, 
         {
             "id":"Y",
             "text":"Y"
         }, 
    ]
}
`

**Comment by kevin-brown** [comment]
The section in the docs for that is not yet written:
https://select2.github.io/options.html#what-should-the-results-returned-to-select2-look-like

But it's equivalent to the array data adapter format:
https://select2.github.io/options.html#data
