### ISSUE TITLE
Lost focus after selecting a value with v4.0.3

### ISSUE THREAD

**Issue by CrazyTuna** [select2/select2#4570]
Using the v4.0.3 every time I select a new value, the component lose the focus.

I've create two JSFiddle:
- [select2 v4.0.0](https://jsfiddle.net/823azsnd/4/)
- [select2 v4.0.3](https://jsfiddle.net/L1sahbx9/2/)

Using the v4.0.3, the focus is lost after selecting a value using mouse click and keyboard.

Maybe related to this issue:
- [Autofocus submit button after closing not working](https://github.com/select2/select2/issues/4388).

Thanks.

**Comment by SgtOddball** [comment]
It's related to this issue #4384 and there's a couple of workarounds listed in there too.

**Comment by kikonen** [comment]
Encountering this issue also myself; have to try if those workarounds work

**Comment by almirb** [comment]
Hello,

It will be solved when merging this PR:
https://github.com/select2/select2/pull/4427/commits/294e7e664d95eafb7f41264c2b87412ad9aa48fc

I tested It and works!

**Comment by alexweissman** [comment]
@almirb it would appear that [#4958](https://github.com/select2/select2/pull/4958/files) also claims to fix this problem.  Could you please pull and test it when you get a chance?  It would appear that it fixes a few other problems with IE tagging as well.

**Comment by alexweissman** [comment]
This has been fixed as of 4.0.4.  See #4427.
