### ISSUE TITLE
Smooth scrolling issue for Apple devices for drop down

### ISSUE THREAD

**Issue by ShubhamLaad** [select2/select2#4571]
Scroll is not smooth on apple device
Device : iPad
Version : 4.0

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
