### ISSUE TITLE
Can't predefine multiple default values on multiple select

### ISSUE THREAD

**Issue by sscho** [select2/select2#4574]
## Steps to reproduce the issue

http://codepen.io/snipcademy/pen/zKvkGk

1. Initialize a select2() object.
2. type in $('#indications-select').select2('val', ['testoption', 'testoption2'])

## Expected behavior and actual behavior

When I follow those steps, I see... Only testoption is chosen as a value.
I was expecting... testoption2 should also be selected, but it's not.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System
- [x] Linux

Libraries

- jQuery version: 3.1.0
- Select2 version: 4.0.3

**Comment by sscho** [comment]
This did the trick!

`$('#el').select2().val(['val1','val2']).trigger("change")
`

**Comment by joginder89** [comment]
@sscho Hi, your trick work but now my Ajax stop working. Any other solution so that ajax also work ?

**Comment by sscho** [comment]
Hi, your ajax not working probably has nothing to do with the above.

**Comment by joginder89** [comment]
@sscho Hi, my Ajax not working have very much with the above. I have solved my problem by using `$("#select > option").prop("selected","selected"); $("#select").trigger("change");`
instead of above.

**Comment by EazazParvez394** [comment]
> @sscho Hi, my Ajax not working have very much with the above. I have solved my problem by using `$("#select > option").prop("selected","selected"); $("#select").trigger("change");`
> instead of above.

But it's selecting all the options.

**Comment by balkarappricott** [comment]
if you set default than ajax will not work
