### ISSUE TITLE
templateResult parameter is not being set to {selected: true} when adding new item (tags:true)

### ISSUE THREAD

**Issue by ian-r-johnson** [select2/select2#4577]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Create a select2 with tags:true and a formatResult handler
2. When a new item is added you can see that formatResult is executed
3. Consistently the new item has the attribute selected:false when the formatResult handler is executed
## Expected behavior and actual behavior

When I follow those steps, I see...
This can be seen here: 

**https://jsfiddle.net/r6zc1uLo/4/**

Notice that all added tags are blue (so the templateResult is executing) but a new tag will not be pink. 

I was expecting...
That a selected item, whether newly added or not, would have the attribute selected:true
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version:
- Select2 version:
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in https://jsfiddle.net/r6zc1uLo/4/

**Comment by alexweissman** [comment]
The linked fiddle no longer seems to work.  At any rate, I believe this is because OP is trying to reference the _attribute_ `selected`, rather than the _property_.  See http://api.jquery.com/prop/

**Comment by ian-r-johnson** [comment]
Alright...

Obviously it's been awhile so the fiddle isn't working because select2 has changed the location of the external files. Here's an updated version

https://jsfiddle.net/ewmhf434/

The parameter passed into templateResult is NOT a jquery object but a POJO that looks like this
```
{
id:"orange"
selected:true
text:"orange"
}
```

So there is no prop method.

The problem is very easy to reproduce. Select an item. It will be pink. Add an item. It will not be pink despite being selected. Subsequent fires of templateResult will return a javascript object for the newly added selected item with {selected:false}. It should be true.

**Comment by alexweissman** [comment]
Interesting - I wonder if this is related to one of the other issues surrounding tagging, namely #3498 and #4610?
