### ISSUE TITLE
Select2 does not respond to clicking the label

### ISSUE THREAD

**Issue by simivar** [select2/select2#4580]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Make a select with `<label>` for it.
2. Try clicking on label.
## Expected behavior and actual behavior

When I follow those steps, I see nothing. Select does not get focues.

I was expecting focused select.
## Environment

Browsers
- [x] Mozilla Firefox
- [ ] Google Chrome
- [ ] Internet Explorer

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 1.11.3
- Select2 version: 4.0.0
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/): https://jsbin.com/muhirunowi/edit?html,output
#2311 #198

**Comment by its2mc** [comment]
Happens to me too

**Comment by cyphix333** [comment]
I came here to ask about this exact issue - how can one make it focus so users can utilise the keyboard like they can with a standard select list?

**Comment by alexweissman** [comment]
Discussion continued in #5137.
