### ISSUE TITLE
Select2 Tokenisation not working when used with Back button

### ISSUE THREAD

**Issue by ramukmarkrish** [select2/select2#4581]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Load tokenization in drop down box
   2.proceed to some other page
   3.tokenisation will not work when you come back to page 
## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...
## Environment

Browsers
- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version:
- Select2 version:
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
If you believe this to be a bug, you must create a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example using our [JSBin template](http://jsbin.com/hojajiwoye/edit?html,js,console,output).

Please re-read the [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md) _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
