### ISSUE TITLE
If just a bit of the highlighted option is shown without scrolling, it is not scrolled to on first show. Bug is in ensureHighlightVisible method.

### ISSUE THREAD

**Issue by steedlem** [select2/select2#4582]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. Go here to reproduce: https://jsfiddle.net/fetaldew27/Lyx90u8d/10/
2. Click the dropdown once and notice the selected option is barely visible at the bottom
3. Click elsewhere to have the options go away
4. Click the dropdown again and notice the highlighted option is scrolled to
## Expected behavior and actual behavior

When I follow those steps, I see...

The selected option is barely visible at the bottom on first show, then clearly visible any time the options are shown after that.

I was expecting...

To see the selected option clearly shown every time.
## Environment

Browsers
- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Safari
- [ ] Internet Explorer (did not test)

Operating System
- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 2.2.1
- Select2 version: 4.0.3
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)
- [x] I can reproduce this bug in a jsfiddle (https://jsfiddle.net/fetaldew27/Lyx90u8d/10/)

I was able to figure out the bug by debugging it.  The reason it works after the first time is that on the first show, the following element is not added to the results, or disappears before the ensureHighlightVisible method is called, where as on any subsequent showing of the results, the following element is visible when ensureHighlightVisible is called:

```
<li class="select2-results__option loading-results" role="treeitem" aria-disabled="true">Searching…</li>
```

What this does on subsequent calls is that it adds offset to the "nextTop" variable in ensureHighlightVisible.  I fixed this locally by changing:

`var nextTop = $highlighted.offset().top;`

to 

`var nextTop = $('.select2-results__option.loading-results').length == 0 ? $highlighted.offset().top + $highlighted.outerHeight(false): $highlighted.offset().top;`

This ensures that the full selected option is shown on all showings of the results including the first.

**Comment by alexweissman** [comment]
Would you consider [submitting a pull request](https://help.github.com/articles/creating-a-pull-request/) for this fix?
