### ISSUE TITLE
selected items with long text need to overflow better or wrap

### ISSUE THREAD

**Issue by lmann4** [select2/select2#4585]
If you select an item, which has text that is wider than the width of the field, in a multi-value select2 field the item extends past the edge of the field. It makes more sense for the item to either wrap or get cut short.

What is currently happening:
![example1](https://cloud.githubusercontent.com/assets/11095021/18523252/035c0eca-7a79-11e6-8864-ab92286491af.png)

What would be better:
![example2](https://cloud.githubusercontent.com/assets/11095021/18523288/3b76bdf0-7a79-11e6-8388-ae76558d2423.png)
or
![example3](https://cloud.githubusercontent.com/assets/11095021/18523318/69df295c-7a79-11e6-96aa-08c348af077a.png)

I fixed this with the following CSS:

```
//select2: fixes word text wrap issues on long select values
li.select2-selection__choice {
    max-width: 100%;
    overflow: hidden;
    text-overflow: ellipsis; //use this if you want to shorten
}
ul.select2-selection__rendered {
    padding-right: 12px !important; //overrides select2 style
}
```

Replace `text-overflow: ellipsis;` with `white-space: normal;` to wrap instead of shorten.

Select2 version: 4.0.1

**Comment by Johnston524** [comment]
For word wrap I had to alter some of the css,

```
li.select2-selection__choice {
    max-width: 100%;
    overflow: hidden;
    /*Altered two below to make word wrap work */
    word-wrap: normal !important;
    white-space: normal;
}
ul.select2-selection__rendered {
    padding-right: 12px !important;
}
```

**Comment by alexweissman** [comment]
This seems pretty easy to integrate into core.  @lmann4 don't forget, you can always submit a PR instead of just posting your solution to the issue!  That way, it will more easily get on track to be integrated into the project, versus the risk of being forgotten in an issue.

**Comment by alexweissman** [comment]
Has anyone tested this with RTL languages?

**Comment by alexweissman** [comment]
The problem with:

```
ul.select2-selection__rendered {
    padding-right: 12px !important; //overrides select2 style
}
```

is that it pushes the `x` (clear button) over to the left when `allowClear` is set to true :-/

**Comment by MaxLap** [comment]
If you want to wrap, and the wrap to also work on long words, here is my minimal solution:
```
.select2-container .select2-selection--multiple .select2-selection__choice {
  max-width: 100%;
  box-sizing: border-box;
  white-space: normal;
  word-wrap: break-word;
}
```

![select2-long-word](https://user-images.githubusercontent.com/894561/34129406-041a08c2-e412-11e7-85f7-49c59e709bd9.png)

**Comment by slaFFik** [comment]
@pedrofurtado 
How unit tests can be applied to CSS changes?..

**Comment by kevin-brown** [comment]
> it would be nice to have a character limit of sorts so this kind of behavior could be controlled better. i am looking for a solution to a dropdown item that is like 50 characters long which is making the dropdown too wide. all the other options are less than 20 characters. would be nice to have an option to limit the characters in dropdown so anything longer gets chopped off with ... or gets wrapped into a new line

You may want to look into doing this with CSS and either overriding the CSS for Select2's classes, forking your own theme, or applying your own classes to the results.

https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow
https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by kevin-brown** [comment]
This has been officially fixed in https://github.com/select2/select2/pull/5964 and will be in the next beta/stable release of Select2.
