### ISSUE TITLE
calculated width not wide enough to display full values

### ISSUE THREAD

**Issue by dbeusee** [select2/select2#4588]
## Steps to reproduce the issue
1. Go to this jsbin to see the issue: https://jsbin.com/vikagicagu/edit?html,output
## Expected behavior and actual behavior

When I follow those steps, I see...
Rob Sulzin...

I was expecting...
Rob Sulzinger
## Environment

Browsers
- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 2.2.4
- Select2 version: 4.0.3
## Isolating the problem
- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [X] I can reproduce this bug in [a jsbin](https://jsbin.com/vikagicagu/edit?html,output)

I have several on my web page doing this.  Is there some way to work around it, or can you tell me how to change select2.js to fix it?

**Comment by santaclaus21** [comment]
Try this:

```
$(document).ready(function() {
    $('#myselect').select2({width: 'auto'});
});
```

**Comment by alexweissman** [comment]
@santaclaus21 is correct.
