### ISSUE TITLE
Extra whitespace from hidden <select> tags

### ISSUE THREAD

**Issue by schang933** [select2/select2#4602]
Browser: Safari 9 and Chromium 52
OS: OS X El Capitan
jQuery: 3.1
Select2: 4.0.3

I have select tags in a column in grid layout, and when select2 hides them they preserve their height. With a lot of select options, this creates whitespace at the bottom of the page. I haven't tested this enough, but I assume if your page is long enough you won't notice it.

I've fixed the problem with 1 line of CSS:

```css
.select2-hidden-accessible {
  display: none;
}
```

I believe this issue is similar to #3959, but it occurs on both single and multiple select tags and `display: inline-block` did not fix it for me.

**Comment by schang933** [comment]
Coming back to mention that I no longer see this issue. May have to do with switching CSS frameworks. Not sure which source was at fault, so I'll go ahead and close this.

**Comment by imPrashik** [comment]
Select2: 4.1.0-beta.1
Issue is still there.

My Fix:
.select2-hidden-accessible{
	position: fixed !important;
}

**Comment by Karagiannidis** [comment]
@imPrashik your solution worked for me, too. Thanks!
my version: Select2 4.1.0-rc.0
