### ISSUE TITLE
Alignment issue when opening select2 dropdown.

### ISSUE THREAD

**Issue by skumaresan** [select2/select2#4607]
Here is the tested page,

https://jsfiddle.net/skumaresan/47skokg5/
<img width="220" alt="screen shot 2016-09-27 at 5 34 17 pm" src="https://cloud.githubusercontent.com/assets/226659/18872554/b2e79fbc-84d8-11e6-9d51-2e306ad46f67.png">

JQuery Version: 3.1.0
Select2 Version : 4.0.3

**Comment by alexweissman** [comment]
It would appear that your example was actually using jQuery 1.x and Select 4.0.0.  This problem appears to be resolved as of Select2 4.0.4 and jQuery 2.2.4.  See https://jsfiddle.net/47skokg5/2/
