### ISSUE TITLE
When i click outside, the dropdown is not closed when i click in HTML tag.

### ISSUE THREAD

**Issue by skumaresan** [select2/select2#4608]
Here is the tested page: https://jsfiddle.net/skumaresan/2nc4kgpb/

![select2-dropdown-issue](https://cloud.githubusercontent.com/assets/226659/18872691/543cfb1e-84d9-11e6-8714-a6661dde911d.gif)

JQuery Version: 3.1.0
Select2 Version: 4.0.3

**Comment by Peinkillar** [comment]
Same problem here.

**Comment by alexweissman** [comment]
This appears to be the same issue as described in #2840.  jsfiddle is creating an iframe for your example, and clicking outside of the iframe has no effect.
