### ISSUE TITLE
Why dont you give the example code ?

### ISSUE THREAD

**Issue by murilolivorato** [select2/select2#4609]
Why dont you give the example code ?

**Comment by kevin-brown** [comment]
![image](https://cloud.githubusercontent.com/assets/1991850/19046849/4235282c-896d-11e6-9847-9cea5c003e52.png)

With a couple of minor exceptions (cases where large functions are referenced), all of the JS code necessary to run the examples is included right beneath the examples themselves. The HTML doesn't vary from the basic examples.
