### ISSUE TITLE
Duplicate values allowed when using tokenSeparator with tags on multi select list

### ISSUE THREAD

**Issue by craigh411** [select2/select2#4610]
You can check this out on this fiddle: https://jsfiddle.net/craig_h_411/04aaw7ys/
1. Select "foo" from dropdown box, the selected value is displayed as 1 (which is the id)
2. Now try typing in "foo" and pressing Enter - This works as expected, and doesn't allow the duplicate value
3. Now try typing "foo" and pressing comma. It's allowed "foo" twice and they selected values are [1,"foo"], so it looks like it is treating the value as a new tag when using a comma as a tokenSeperator.

The expected outcome here is that the token separator (comma in this case) should reproduce the behavior of pressing enter and not allow the duplicates.

**Comment by Ilya-Zhulin** [comment]
Hi to all! Also found this error. Very uncomfortable to disable this feature in tag system.
