### ISSUE TITLE
User is navigated to unexpected pages if press Backspace while entering text into textboxes

### ISSUE THREAD

**Issue by huydeny** [select2/select2#4620]
Issue with tagging option - TAGS: TRUE
## Steps to reproduce the issue
1. Navigate to https://select2.github.io/examples.html
2. Input text into select2 field, and then enter
3. Press Backspace

Expected Result:
- Characters will be deleted

Actual Result:
- User is navigated to unexpected page
## Environment

Browsers
- Internet Explorer 11

Operating System
-  Windows

Libraries
- jQuery version: 1.11.2 and 1.12.1
- Select2 version: 4.0.3

**Comment by NVasse** [comment]
Most likely linked to this issue : #4525

**Comment by Davidrl1000** [comment]
I'm also having this issue with jQuery version: 2.2.0,
with jQuery version: 3.1.1 the problem is not present (The page is not crashing), but when I press backspace the page load a new tab

**Comment by alexweissman** [comment]
I can't seem to replicate this in the new docs site: https://select2.org/tagging#tagging-with-multi-value-select-boxes

The new docs site uses jQuery v2.2.4.

**Comment by alexweissman** [comment]
#4525 has been resolved as of `4.0.6-rc.1`, so I'm going to guess that this issue has likely been resolved as well?

**Comment by kingwinchan** [comment]
Is there anyone knows the fix of this issue?
We are using 4.0.3 version and get a error of select2selectOnClose function if update to 4.0.6 rc.
So we have to fix this issue manually. Any information about it would be preferred.
