### ISSUE TITLE
Clear event

### ISSUE THREAD

**Issue by skabbit** [select2/select2#4630]
I was expecting, that there is event for click on a "Clear All" button , but there is only 'changed' and 'select2:unselecting' events, that fires multiple times when used with <select multiple="multiple">, once for every selected option removing.

I can add it by myself, and make Pull Request if you want. Do you?

Libraries
- jQuery version: 1.11.3
- Select2 version: 4.0.3

**Comment by nebehr** [comment]
I would upvote that PR. Clear event would be really useful if options change triggers an expensive operation.

**Comment by alexweissman** [comment]
@skabbit yes, please do!  We're moving the discussion about this feature request to #4929.
