### ISSUE TITLE
Missing text options

### ISSUE THREAD

**Issue by littlehawk** [select2/select2#4633]
Hi!

I have this problem when I init a select2 with one or more values.
Javascript is:

> ```
>   $('#exclude_products').select2({
>         width: 'off',
>         ajax: {
>             url: '....',
>             type: 'post',
>             dataType: 'json',
>             delay: 250,
>             data: function( params ) {
>                 return {
>                     q: params.term,
>                     notin1: $('#products').val(),
>                     notin2: $('#exclude_products').val()
>                 };
>             },
>             processResults: function( data ) {
>                 return {
>                     results: data
>                 };
>             },
>             cache: true
>         },
>         escapeMarkup: function(markup) {
>             return markup;
>         },
>         minimumInputLength: 3,
>         templateResult: formatProduct,
>         templateSelection: formatProductSelection
>     });
> ```

If select haven't options all works, but if select is not empty, i.e if select is like this:

`<select class="form-control" id="exclude_products" name="data[exclude_products][]" multiple>
   <option value="1">test1</option>
   <option value="2">test2</option>
   <option value="3">test3</option>
</select>`

select2 dont show tag label even if remote loading data works

Result is visible here: [http://www.quickoffice.it/Immagine.png](url)

**Comment by alexweissman** [comment]
It's unclear what this means:

> select2 dont show tag label even if remote loading data works

Unfortunately, without a working http://jsbin.com to replicate this problem, we cannot provide any support.
