### ISSUE TITLE
Multipleselect: deletion of one element is not possible when select box is higher than browser window

### ISSUE THREAD

**Issue by mobilutz** [select2/select2#4642]
## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)
## Steps to reproduce the issue
1. generate a long multiselect with all selected items
2. make window height greater than select box
3. try to delete any selected item

Example see here: https://jsfiddle.net/vwsg4tn5/
## Expected behavior and actual behavior

I was expecting that clicking on any items `x` would delete that item
## Environment

Browsers
- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries
- jQuery version: 3.1.1
- Select2 version: 4.0.3
## Isolating the problem
- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsfiddle](https://jsfiddle.net/vwsg4tn5/)

**Comment by kevin-brown** [comment]
I was able to reproduce the issue. As noted elsewhere, it happens because we are listening for the `mousedown` event to handle transitioning the focus and the `click` event (which is triggered after) to handle deleting options.

**Comment by mobilutz** [comment]
@kevin-brown This is exactly what I changed in my proposed PR #4644 - `click` to `mousedown`
