### ISSUE TITLE
[4.0.3] No way to update placeholder when data-placeholder is preset

### ISSUE THREAD

**Issue by santaclaus21** [select2/select2#4653]
I can't find a way to update placeholder. I have:
<select class="select2" data-placeholder="xxx">
...
</select>

I was trying: 
$("select[name='paid_by']").select2({ placeholder: "xxxxxxxxxx", allowClear: true }).attr("disabled", false);
$("select[name='paid_by']").attr("data-placeholder","bar").select2({ placeholder: "updated text..." });

It doesn't work when data-placeholder is preset in HTML. But everything is working fine when I remove data-placeholder...

**Comment by santaclaus21** [comment]
Ok, I've found the solution:
$("select[name='paid_by']").data('placeholder', 'updated text...').select2();

but, there should by any method to change placeholder without reinitialize select2.

**Comment by alkana** [comment]
Maybe I found a solution (it's not sure at all, so if you can test and told me if it's work):
```javascript
  // change placeholder in select2
  $el.data('select2').selection.placeholder.text = text;
  
  // change placeholder in dom
  $el.next("span.select2:first").find("span.select2-selection__placeholder").html(text);
```

**Comment by santaclaus21** [comment]
Even if that works, I was expected method or function in plugin 🔢 :)

**Comment by PatrikGuerra** [comment]
I'm using this for now..
`$.fn.Select2GetPlaceholder = function () {
    var $select2Container = $(this).data('select2').$container
    return $select2Container.find('.select2-selection__placeholder').text();
};`

also 

`$.fn.Select2UpdatePlaceholder = function (newPlaceholder) {
    // $(this).select2({
    //     placeholder: novoPlaceholder
    // });
    var $select2Container = $(this).data('select2').$container
    return $select2Container.find('.select2-selection__placeholder').text(newPlaceholder);
};`

**Comment by dearsina** [comment]
@avernet I'm not sure if your update addresses this feature request. I'm still not able to dynamically update the placeholder without re-initiating the select element.

@PatrikGuerra's extensions do the trick for now, but it feels hack-y.

**Comment by avernet** [comment]
@dearsina What update are you referring to, specifically?

**Comment by dearsina** [comment]
@avernet on the thread it says you "mentioned this issue" attached to this thread (that looks like an update): https://github.com/orbeon/orbeon-forms/issues/1433
Apologies if I've misunderstood!

**Comment by avernet** [comment]
@dearsina Got it, some time has passed, and my memory of this had faded ;). In Orbeon Forms, we're just reinitializing the Select2 when the placeholder changes, and using a `MutationObserver` to know when that attribute changes. In practice, this happens when users change the current language, and hence the placeholder changes. You can see the code updating the placeholder (`initOrUpdatePlaceholder`) being hooked to the `MutationObserver` [here](https://github.com/orbeon/orbeon-forms/blob/tag-release-2019.2-ce/form-runner/js/src/main/scala/org/orbeon/xbl/Select1Search.scala#L85). The code is in Scala.js, but I imagine you can get the gist of it. I hope this helps!

**Comment by dearsina** [comment]
Thanks! I was trying to find a way to update my select2 dropdown boxes without having to regenerate/reinitialise them, but it seems like that's the best/only way without resorting to hacking!

**Comment by HengJunXi** [comment]
Combination of @PatrikGuerra and @alkana approaches works well for me:
```
$.fn.Select2UpdatePlaceholder = function (newPlaceholder) {
    var $select2 = $(this).data('select2');
    $select2.selection.placeholder.text = newPlaceholder;
    return $select2.$container.find('.select2-selection__placeholder').text(newPlaceholder);
};
