### ISSUE TITLE
How could get val of an item removed ?

### ISSUE THREAD

**Issue by fernandopaiva** [select2/select2#4654]
I'm using select2 4.0.0, and I want to get the val of an item removed, to do this I'm trying use the event select2-removed but it doesn't works, it doesn't execute

How could I do this ?

trying.

```
$(document).ready(function () {
    $('#selectedItems').on('select2-removed', function (e) {
        console.log(e.val);
    }).select2({
        placeholder: "Select an option"
    });

});
```

**Comment by denis-n** [comment]
There is no such event. According to [this ](https://select2.github.io/examples.html#events)- you should be using `select2:unselect` or `select2:unselecting`

**Comment by voidsteed** [comment]
Hi @fernandopaiva , I had the same problem. and I found the solution. It is in the event.params

$(".js-example-basic-multiple").on("select2:unselect", (e) => {
      console.log("unselecting something", e.params)
    })

In the "e.params", you can get the id or text from just unselected option. 

Hope this is helpful!

**Comment by alexweissman** [comment]
This is now documented: https://select2.org/programmatic-control/events#event-data.
