### ISSUE TITLE
IE11 select option bug

### ISSUE THREAD

**Issue by landsman** [select2/select2#4655]
Hi,

I am suprised from IE10-11 behavior.
If I selected one of option, selected was another previous.
Here is a example: https://beta.bezhladoveni.cz/rezervovat.

Where can be problem?

I think, that i found a bug. Without this it works fine:

```
    select2element.on("select2:open", function(event)
    {
        $('input.select2-search__field').attr("placeholder", "Search ...");
    });
```

**Comment by alexweissman** [comment]
This appears to be the same issue as presented in #4684.
