### ISSUE TITLE
Empty remove box on first select in multiple

### ISSUE THREAD

**Issue by skrzeka** [select2/select2#4657]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Goto http://jsfiddle.net/k81hwwdb/

## Expected behavior and actual behavior
Select anything from the dropdown
On the first selection empty remove box will be included
## Environment

Browsers

- [ x] Google Chrome
- [ x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ x] Windows
- [ ] Mac OS X
- [ x] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by kayran** [comment]
I has the same problem and i use the version 4.0.3 full

In my case are inserted 3 tags when select one, two of then empty.  The 2 extra tags are inserted in data before the update is called. 

I 'solved' the problem verifying if the data is empty on all options, and ignoring it, but i want a solution on the plugin code, without need to alter your code
