### ISSUE TITLE
How to set the initial value and the text  when to edit the form after the value has been set

### ISSUE THREAD

**Issue by BinWu1989** [select2/select2#4659]
I  am new settler of the select2(using version 2.4.0.3) and comes to the problem that how to set the initial value , I googled and found many ways including to append the option and trigger the change event of the element , anyway,failed.

so if someone could share me a example detaily about how to set the initial value using ajax (the initial value will get at first ). Thanks

**Comment by sedrubal** [comment]
I think, this should work:

```js
  $('select').select2({
    ajax: {
      url: '/api/',
    },
  }).append('<option value="initial">initial</option>').val('initial').trigger('change');
```

**Comment by BinWu1989** [comment]
Thank you very much for your reply , this works for me ,

**Comment by alexweissman** [comment]
There is now an entire chapter in the docs devoted to this: https://select2.org/programmatic-control/add-select-clear-items
