### ISSUE TITLE
Misleading description "The jQuery replacement for select boxes"

### ISSUE THREAD

**Issue by Chealer** [select2/select2#4661]
[The homepage](https://select2.github.io/) describes Select2 as "The jQuery replacement for select boxes". "jQuery" is not an adjective, and it is unclear what that usage means. But most importantly, if there is a single "jQuery replacement for select boxes", that replacement is jQuery UI Selectmenu, not Select2.

I suggest replacing with "A JavaScript library to replace native HTML select fields".

**Comment by jakeNiemiec** [comment]
@Chealer see: https://github.com/select2/select2/issues/5367

**Comment by Chealer** [comment]
Thank you very much @jakeNiemiec

**Comment by kevin-brown** [comment]
I'm gong to maintain this as the description, mostly because the short description for this library has always been

> Select2 is a jQuery-based replacement for select boxes.

I agree that the grammar on the line in the docs could be improved. I'd probably suggest

> The jQuery-based replacement for select boxes

For some reason starting that with "A" looks odd.
