### ISSUE TITLE
Custom matcher doesn't work with placeholder and templates

### ISSUE THREAD

**Issue by andrewtrickett** [select2/select2#4668]
I've got a complicated dropdown using data, templates and a custom matcher. The matcher filters on all data elements.

Here is a fiddle: [https://jsfiddle.net/f7y813fn/1/](https://jsfiddle.net/f7y813fn/1/)

The problem is when I use a placeholder by adding an empty option tag, the search function stops working with the error `Cannot read property 'toUpperCase' of undefined`.

Is this a bug or is there a workaround for this?

**Comment by andrewtrickett** [comment]
I managed to fix this by modifying the matcher to ignore undefined values:

`if (typeof data.text !== "undefined" && data.text.toUpperCase().indexOf(params.term.toUpperCase()) != -1)`

[https://jsfiddle.net/f7y813fn/2/](https://jsfiddle.net/f7y813fn/2/)

**Comment by alexweissman** [comment]
Thanks, we'll add this to the example in the `matcher` docs.
