### ISSUE TITLE
Local data with ajax fallback

### ISSUE THREAD

**Issue by krazyjakee** [select2/select2#4671]
Since this project has become an over-engineered clusterfuck rather than a simple input component, some of those who live in the real world want a simple solution to combine rendered options with an ajax fallback should the user start typing. I read others suggestions about dataAdapters and neither the docs, issues here or stackoverflow issues either explained them well or provided working examples. Some displaying the short, quick "old" way of doing things alongside the 500 lines of code needed to do the same thing in the "new" way. Essentially transferring any bloat from the library to the developer.

Anyway, by putting the old "query" logic into the ajax transport, I was able to either return the rendered options or begin the ajax request.

```javascript
var initials = [];
var combobox = $('.select2');

combobox.find('option').each(function(index, elem) {
  elem = $(elem);
 initials.push({
    id: elem.val(),
    text: elem.text()
  });
});

var opts = {
  tags: false,
  multiple: true,
  allowClear: true,
  theme: "bootstrap",
  ajax: {
    url: url,
    dataType: 'json',
    type: 'get',
    transport: function(params, success, error) {
      if (params.data.term) {
        if (params.data.term.length > 2) {
          $.ajax({
            url: params.url,
            data: params.data,
            success: success,
            error: error
          });
        }
      }
      return success({
        results: initials
      });
    },
    data: function(params) {
      var queryParameters;
      return queryParameters = {
        term: params.term
      };
    },
    processResults: function(data) {
      return {
        results: $.map(data, function(item) {
          return {
            text: item.text,
            id: item.value
          };
        }).concat(initials)
      };
    }
  }
};

combobox.select2(opts);
```

**Comment by thinkh** [comment]
Thanks. Very helpful.

**Comment by legreco** [comment]
HI. My english is not very good, but i'll try to explain my problem as clear as possible.

I am using select2 v4 and I get the values of my select via ajax.
I want to be able to set the selected value only via the ID of the object.

Possible solution
1- Force select2 do ajax call after page finish loading ( Code needed)
2- when ajax data is get, find a way to search through the data objects the objet with the matching id (code needeed)
3- Set this object as selected value (code needed)

Like i say, my english is not very good.
