### ISSUE TITLE
Ajax is used when no url is specified

### ISSUE THREAD

**Issue by Stadly** [select2/select2#4675]
I declare the url to use when fetching results in the html (`<select data-ajax--url="...">`). Not all `<select>` has an ajax url specified, meaning that Select2 should just search in the `<option>`s declared in the html. If I specify the other options to use with ajax when initializing Select2, also the `<select>`s that have no ajax url specified attempt to load the options via ajax. When determining whether to use ajax or not, wouldn't it be better to check whether the url is specifed for the ajax option, and not only whether the ajax option is specified at all?

Example:

    <select id="foo" data-ajax--url="load-options.php"></select>
    <select id="bar">
       <option>One</option>
       <option>Two</option>
       <option>Three</option>
    </select>
    <script>
       $('select').select2({
          ajax: {
             delay: 250,
             processResults: function(data) {return data;}
          }
       });
    </script>

Expected behaviour:
`foo` loads results via ajax, using the url provided in html and options provided during initialization. `bar` uses the available `<option>`s.

Observed bahavioiur:
`foo` loads results via ajax, using the url provided in html and options provided during initialization. `bar` attempts to load results via ajax using the options provided during initialization, even though no ajax url is specified.

**Comment by CodingSamurai** [comment]
Just do two separate initializations:

```
<script>
   $('#foo').select2({
      ajax: {
         url: load-options.php,
         delay: 250,
         processResults: function(data) {return data;}
      }
   });

$('#bar').select2();
</script>
```

**Comment by Stadly** [comment]
Yes. Using separate initializations works fine, but it seems like it shouldn't be necessary. Does it really make sense to use ajax when there is no ajax url specified?

**Comment by SgtOddball** [comment]
If the attribute is present but not set then ajax should function as expected and call back to the parent page. This is normal default behavour for an ajax callback. If an ajax call is not desired then ensure that the attribute is not present and that your options are not implicly triggering ajax either.

**Comment by alexweissman** [comment]
Agree with @SgtOddball.  The behavior of the ajax property should reflect the normal behavior of jQuery's `.ajax` method.
