### ISSUE TITLE
Safari: dropdownAutowidth applied when activating same dropdown for second time

### ISSUE THREAD

**Issue by jw1981** [select2/select2#4678]
## Prerequisites

- [x] have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Select2 v4.0.3 in Safari 9.0.1 or 10.0.1
2. Data loaded via Ajax/JSON
3. Activate dropdown, first time (dropdownAutowidth: true is not applied)
4. Close and open same dropdown  (dropdownAutowidth: true is being applied).

Expected behavior and actual behavior

When I follow those steps, I see...
dropdownAutowidth: true is being applied only the second time I activate the dropdown.

I was expecting...
dropdownAutowidth: true is being applied on the **first** time I activate the dropdown.

## Environment

Browsers

- [x] Safari 9.0.1 and 10.0.1
- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.2.4
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by shuckster** [comment]
Also experiencing this one.

**Comment by shuckster** [comment]
Performing an open() and close() immediately after initialisation fixes it.

An ugly hack obviously, but it'll do for now. :P

**Comment by jw1981** [comment]
Nice work shuckster! I'll give your workaround a try.

**Comment by barttenbrinke** [comment]
For people who find this with Google and have no in-depth knowledge of Select2, this is the workaround in javascript:
```
$('select.select2').select2({dropdownAutoWidth: true}).select2('open').select2('close') // Safari workaround https://github.com/select2/select2/issues/4678
```

**Comment by alexweissman** [comment]
Confirmed this issue in Safari 10.1.2.  See this jsfiddle: https://jsfiddle.net/wphqwvLf/837/

**Comment by alexweissman** [comment]
All this effort to find workarounds, when people could be developing pull requests!

**Comment by shuckster** [comment]
Yes, I could. If I had the time and inclination to pour through the code and figure out the problem.

But since I don't have time, or maybe I don't have the inclination, I do the best I can with what I have. And in this instance it's a workaround.

I didn't have to come here and post it. I could have kept it to myself. But in the spirit of open-source, in a way that is not perfect but at least someone might find useful, I offered this hack.

So take it or leave it.

**Comment by alexweissman** [comment]
Fair enough.  Thanks for sharing!

**Comment by jdmerinor** [comment]
Humm this issue is still happening :(
I took a look at the code and to be honest I don't think it's a problem with how select2 is setting the dropdown dimensions. They are exactly the same for both the first and the other calls. I imagine maybe it's a bug of the rendering in safari?

**Comment by kevinpapst** [comment]
More than 5 years later this issue is still existing (it shouldn't be closed) ...

@shuckster thanks for sharing your solution, works for me 👍 

With a little update to make it self-contained / if you have many select2 instances on one page:
```javascript
        const element = jQuery(node);
        element.on('select2:open', function () {
            if (element.data('performing-reopen') === undefined) {
                element.data('performing-reopen', true);
                element.select2('close');
                element.select2('open');
            }
        });
```
