### ISSUE TITLE
Issue when try loading remote data, after search, select an item, then click the select2 for the first time

### ISSUE THREAD

**Issue by swtanggara** [select2/select2#4679]
Hi All,

This is the issue I found on the example page. I try to use the default "issue" template: 

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Open the select2 on the [examples page](https://select2.github.io/examples.html).
2. Pick the "Loading remote data" example, type whatever you want, e.g: "angular", then select one item.
3. Click once on the select2 control to open the dropdown.

## Expected behavior and actual behavior

When I follow those steps, I see... 

![image](https://cloud.githubusercontent.com/assets/16267423/20170607/9cada35a-a75f-11e6-9281-7d8f10cac9f2.png)
(remember, this is the first time I click the control after selecting it)

I was expecting...

![image](https://cloud.githubusercontent.com/assets/16267423/20170685/d4ad6ccc-a75f-11e6-96fe-bca5dd721a7f.png)
(this is the second-time click on to open the dropdown)

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version: 4.0.3 (assuming the example page using this version)

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
This happens because the search term is cleared when the dropdown is closed.  This is discussed in #3902.
