### ISSUE TITLE
Container won't close on select

### ISSUE THREAD

**Issue by mildlyfunctional** [select2/select2#468]
Problem:
When selecting an item in the single dropdown, the dropdown reopens in the same action (where I expect it to close).

Following the code the onSelect method calls this.selection.focus();
which in its turn calls the focus event handler around line 1546 where class .select2-container-active is set. This is fine but i suspect that something else is triggered too causing the dropbox to reopen in the same action.

I was able to stop this behaviour by adding e.preventDefault() in the focus event handler around line 1546.

I do not know exactly what causes the reopen (keydown, keyup?) 

Hope it helps, thanks for this great piece of work.

**Comment by pushkin-** [comment]
FWIW, I see this issue in my forked select2. I don't see it when pointing to the full select2.js script, but I see it when pointing to the entry-point (core.js I think) that loads all the other scripts. Very curious.
