### ISSUE TITLE
Odd highlighting of selected option when closeOnSelect is false

### ISSUE THREAD

**Issue by phazei** [select2/select2#4682]
Go here:
http://codepen.io/stephenbe/pen/zBrzYP

Click the second option, then click the 5th option.  The selection jumps back up to the second option.  If you click around, in whatever order, it seems to jump to the closest option or top option.  It should just stay under the mouse on the item that was just clicked.

**Comment by aristidesfl** [comment]
+1 this also makes the list scroll to the beginning which almost defeats the purpose.

**Comment by aristidesfl** [comment]
duplicate of #4584
