### ISSUE TITLE
options can not be selected when parameter 'data' has the second level 'children'

### ISSUE THREAD

**Issue by wxxcarl** [select2/select2#4685]
`data:[{`
           `   text: 'first level',`
            `  children:[`
            `    {`
            `      text:'second level',`
             `     children:[{`
             `         id:'1',`
              `        text:'third level'`
              `      }`
              `    ]`
              `  }`
            `  ]`
       `     }]`

**Comment by nelson6e65** [comment]
Read in the doc: [How many levels of nesting can there be?](https://select2.github.io/options.html#how-many-levels-of-nesting-can-there-be)
> Only a single level of nesting is allowed per the HTML specification. If you nest an <optgroup> within another <optgroup>, Select2 will not be able to detect the extra level of nesting and errors may be triggered as a result.

**Comment by alexweissman** [comment]
Thanks, and we'll add the data format information to the docs.
