### ISSUE TITLE
native change event not dispatched when change

### ISSUE THREAD

**Issue by kcm1700** [select2/select2#4686]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. create a select2 box and run the following code
```html
<select id="sel">
<option value="1">11</option>
<option value="2">22</option>
</select>
<script>
var elem = document.getElementById('sel');
elem.addEventListener('change', function() { alert('event listener'); } );
$("sel").select2();
</script>
```
Whatever you do here on the browser, alert does not show up.

## Expected behavior and actual behavior

I expect 'event listener' alert will show up when I change the selection.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.2.3
- Select2 version: 4.0.2

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by Drewyn** [comment]
Select2 uses jQuery's trigger function to handle events, which doesn't fire native DOM events. You can use a simple modification of the code to swap the jQuery trigger for a native DOM one:

```javascript
var change = new Event('change')
```

And replace every change event with:

```javascript
$element[0].dispatchEvent(change)
```

**Comment by alexweissman** [comment]
The reasons for this are discussed in #1908.
