### ISSUE TITLE
Available options list missing in docs

### ISSUE THREAD

**Issue by Karmalakas** [select2/select2#4687]
I believe it's a documentation issue - can't seem to find a straightforward list of all available options with their short descriptions and default values. I think [options' documentation page](https://select2.github.io/options.html) could be improved when you want to go through all the options.

**Comment by jpic** [comment]
What other options would you like to see in the documentation exactly ?

**Comment by Karmalakas** [comment]
Now [options' documentation page](https://select2.github.io/options.html) is more like a FAQ page, but not options docs. All I want is a list of all available options with their default values. In a current options docs you start from the info how to change default values, but nowhere to find which options are available at all.

**Comment by jpic** [comment]
"What are all the default options ?" seems like a FAQ and we should add it IMHO, @Karmalakas please let us know if you want this task assigned to you.

**Comment by Karmalakas** [comment]
I'd have no idea where to start :) What I mean by "Options docs" is like [Colorbox](http://www.jacklmoore.com/colorbox/) (just see _Settings_, _Methods_ and _Hooks_), [iCheck](http://icheck.fronteed.com/) (also scroll to _Options_, _Methods_ and _Callbacks_) and many other plugins has. That's it. Because theres no way to see all available optionsin one place in a current documentation. I really hope you'll understand the need to have these in one place explained as simple as possible.

**Comment by jpic** [comment]
I'm taking a wild guess here but perhaps you could start by opening a pull
request on [options docs](
https://github.com/select2/select2/tree/master/docs/_includes/options) with
a new example that shows the default value for every possible option that's
not documented elsewhere. Would that sound like a reasonable first step ?

**Comment by Karmalakas** [comment]
So where can I find these not documented options? And I think that FAQ page with it's examples should be left as is. Options docs should be one completely separate page, so you could find **absolutely all** available options, methods and events in one place.

**Comment by kevin-brown** [comment]
This was the goal of the old options page: https://select2.github.io/options-old.html

It's just that it was way too complex and overly technical, which 90% of users of Select2 aren't looking for (seriously). The newer FAQ-style page was aiming to be less technical, but easier to search, and went in a different direction.

Older versions of Select2 (pre-4.0) had a documentation section like what you're looking for: http://select2.github.io/select2/#documentation

**Comment by Karmalakas** [comment]
The second link is almost exactly what I'm talking about :) Simple, easy to read and understand, easy to see all options and their default and/or accepted values (a lot of times you want some feature and you have no idea what options are available and such list helps a lot)

**Comment by alexweissman** [comment]
I am working on this now - my plan is to integrate #4692, migrating the current "Options" page to an "FAQ" page and turning the "Options" page into a more traditional API reference.

**Comment by alexweissman** [comment]
This is now available at https://select2.org/configuration/options-api.
