### ISSUE TITLE
Uncaught TypeError: Cannot set property 'selected' of undefined

### ISSUE THREAD

**Issue by jprathore** [select2/select2#4688]
Hello ,
I am geeting this error when I am adding list of item in dopdown dynamically on edit mode.

and when i try to remove item without selecting other element of dopdownm , getting this error.

It's working when i select other element of dopdown.

Thank You

**Comment by anyexinglu** [comment]
If you want to test local, you can add  the code as below ,
  if (!$.fn) {
    $.fn = {}
  }
in this line(https://github.com/select2/select2/blob/563198a4a2e0eb9f7adbc4775d360db1037a13db/dist/js/select2.js#L5662 ).

Then this error disappear

**Comment by alexweissman** [comment]
Please provide a working http://jsbin.com example and steps to replicate this behavior.  Otherwise, we cannot provide any support.

**Comment by alexweissman** [comment]
Once you have provided this, we can re-open the issue.
