### ISSUE TITLE
i have a "select" , width with percentage, i got select2 with "pixed" .

### ISSUE THREAD

**Issue by hyjiacan** [select2/select2#4690]
i wrote like this:
`
<select id="select1" style="width: 50%;"></select>
`
`
$('#select1").select2();
`

then, select2 got a width "50px".

-----------------------

select2 version: 4.0.3

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on the examples page][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[examples]: https://select2.github.io/examples.html
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by ramusus** [comment]
+1 to fix this odd behavior

**Comment by hurrycaner** [comment]
Problem is probably at `Select2.prototype._resolveWidth` when element's style is not set...
at line 5160: `var elementWidth = $element.outerWidth(false);`
probably should be `var elementWidth = $element.css('width');` to get unit with it...
it should be very well tested..

**Comment by hyjiacan** [comment]
I have composed my own select-component [TinySelect](https://github.com/hyjiacan/TinySelect) **Chinese**, It's more flexible, but its not that good look. i am try to refactor it and dev with plugin-mode.

**Comment by kurdtpage** [comment]
In version 4.0.3, line 5164 specifies a regex `WIDTH`, but this is never used
