### ISSUE TITLE
iOS 10.x: Keyboard shows up no matter where to click, after searching in a non-multiple searchbox

### ISSUE THREAD

**Issue by duxthefux** [select2/select2#4691]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to the Examples page of select2 on an iOS 10.x (<= iOS 9 is fine) Device (Simulator also works) and try out the "Placeholder" example 
2. Search for something and then close the select2
3. Click somewhere else in the DOM and the keyboard will popup every single time

## Expected behavior and actual behavior

When I follow those steps, I see the keyboard popping up after using a select2-single-input every time I click somewhere in the DOM

I was expecting the keyboard not to popup.

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [x] Safari

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] Mobile
- [x] iOS 10.x

Libraries

- jQuery version: 1.11.1
- Select2 version: 4.0.3

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by duxthefux** [comment]
Workaround for now:
```
elem.on('select2:close', function (e) {
        setTimeout(function() {
            $("#someOtherInputField").focus().blur();
        },250);
    });
```

**Comment by abdullahseba** [comment]
I can confirm this on iOS 11.1.2 on Safari, Firefox and Chrome using https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox .

**Comment by abdullahseba** [comment]
Using `.blur()` seems to be a common fix for this problem.
https://stackoverflow.com/questions/2890216/hide-keyboard-in-iphone-safari-webapp

**Comment by alexweissman** [comment]
Possibly caused by the fact that we use `mousedown` instead of `click`, as explained in #4763?
