### ISSUE TITLE
select2 4.0.3 - search box not working with pagination

### ISSUE THREAD

**Issue by manoj-infrasssist** [select2/select2#4693]
[db8SXs.zip](https://github.com/select2/select2/files/605684/db8SXs.zip)

https://jsbin.com/kuvoket/edit?html,js,output

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by manoj-infrasssist** [comment]
Please anyone could help me in this

**Comment by lordpeppe** [comment]
I am also having this issue. Are there any known fixes to this issue?

**Comment by alexweissman** [comment]
Pagination is now properly documented here: https://select2.org/data-sources/ajax#pagination

There shouldn't be any need to create a custom `dataAdapter`.

**Comment by b2simpleman24** [comment]
it doesn't work, man...

**Comment by sumitdhiman1** [comment]
I am also having the same issue and I have fixed this by using this property.

Please use this property   dropdownParent: $(".select2WithPagination").parent();

See example below.
function getSkuOptions(){
  var customerId = $("#customerId").val();
  $(".select2WithPagination").select2({
  width: '100%',
  ajax: {
      url: '/getSkuOptionForCustomer',
      type: 'post',
      dataType: 'json',
      delay: 250,
      data: function(params) {
          var query = {
              search: params.term||'', // search term
              page: params.page || 1,
              customerId:customerId
          };

          // Query parameters will be ?search=[term]&page=[page]
          return query;
      },
      processResults: function(response) {
          return {
              results: response.results,
              pagination:{
                  more:response.pagination.more
              }
          };
      },
      cache: true
  },
  placeholder: 'Search for a item sku.',
  dropdownParent: $(".select2WithPagination").parent()


  });
}
