### ISSUE TITLE
Exact word matches should appear at top of results list

### ISSUE THREAD

**Issue by theMugician** [select2/select2#4694]
I have a JSON file filled with many science subjects.
When I search for 'Physics' for example I will get a results list like so in alphabetical order:

Applied Physics
Computation Physics
Engineering Physics
Mineral Physics
Particle Physics
Physics
Theoretical Physics

The only problem is when someone searches for 'Physics' it should appear at the very top of results since it is an exact match. 

Looking through the massive script I have no idea where I am able to implement this. 

Can anybody point me to the right area or does someone already have a solution

**Comment by tomimaen** [comment]
I had the same issue and when investigating this, in some other issue it was said that the search results are shown in the order that they are written in dom (can't find the ticket anymore).

So the way I solved this was to order the items directly to the dom first by ascending order (A - Z), and after that order the items again by the length of the item names (smallest - largest). This way the "perfect match" would always be the first selectable item in the list. So in your case the order of the items should be something like this:

```
Array
(
    [physics] => Physics
    [applied-physics] => Applied Physics
    [mineral-physics] => Mineral Physics
    [particle-physics] => Particle Physics
    [computation-physics] => Computation Physics
    [engineering-physics] => Engineering Physics
    [theoretical-physics] => Theoretical Physics
)
```

**Comment by alexweissman** [comment]
If the data is coming from the server-side, you can simply apply the desired ordering in your server-side code.

For non-remote data, it would appear that Select2 has a [`sorter` configuration option](https://github.com/select2/select2/blob/062c6c3af5f0f39794c34c0a343a3857e587cc97/src/js/select2/results.js#L94-L98), but this is not documented.  So, if someone could figure out how this works and submit a PR to the documentation repo, that would be appreciated.

**Comment by seabasss** [comment]
@tomimaen Exactly how did you make that sorting happen? I'm also looking for a perfect match as the default selection. Thanks!

**Comment by tomimaen** [comment]
@seabasss I only have PHP example of this, hope it helps!

```
$terms = array(
    'engineering-physics' => 'Engineering Physics',
    'computation-physics' => 'Computation Physics',
    'particle-physics'    => 'Particle Physics',
    'mineral-physics'     => 'Mineral Physics',
    'applied-physics'     => 'Applied Physics',
    'theoretical-physics' => 'Theoretical Physics',
    'physics'             => 'Physics',
);

// Sort array by value (a -> z)
asort($terms);

// Sort array by length of the value (lowest -> highest)
uasort($terms, function($a, $b) {
    return strlen($a) - strlen($b);
});
```

**Comment by jonahgreenthal** [comment]
Here's some stuff I wrote for "prefix-preferred sorting"; that is, if the result _begins_ with the search string, it's sorted higher than if it contains the search string somewhere other than the beginning. I don't have time to submit a PR right now, but maybe someone can adapt it.

```
// Before initializing Select2. I suspect this is not the right way to do this.
var activeSelect2Query;

// In the Select2 options

searching: function(params) {activeSelect2Query = params; return 'Searching...';},
sorter: function(results) {
	if (results && results.length > 0) {
		var searchString = activeSelect2Query.term || '';
		searchString = searchString.toLowerCase(); // case-insensitive
		
		if (searchString.length == 0) {
			return results;
		} else {
			return results.sort(
				function(a, b) {
					var displayA = a.text.toLowerCase(); // case-insensitive
					var displayB = b.text.toLowerCase(); // case-insensitive
					
					if (searchString == '') {
						return a.text.localeCompare(b.text);
					}
					
					if (displayA.indexOf(searchString) == 0) {
						if (displayB.indexOf(searchString) == 0) {
							// They're both in the top group; within-group order is normal
							return a.text.localeCompare(b.text);
						} else {
							// A goes to the top
							return -1;
						}
					} else {
						if (displayB.indexOf(searchString) == 0) {
							// B goes to the top
							return 1;
						} else {
							// They're both in the bottom group; within-group order is normal
							return a.text.localeCompare(b.text);
						}
					}
				}
			);
		}
	} else {
		return results;
	}
};
```

**Comment by seabasss** [comment]
@jonahgreenthal Thank you! I tried it, but got this error. Any ideas? Thanks! `Uncaught TypeError: Cannot read property 'term' of undefined`

**Comment by jonahgreenthal** [comment]
Not really. It probably has to do with the weird `activeSelect2Query` hack. Like I said, I don't think that's the right way to do things, but the way I have it set up works for me. Sorry!

**Comment by seabasss** [comment]
@tomimaen Thank you! Is it possible to do that right in the sql-query? Or can I do it in PHP but one level down in the array? $terms[n]['title_to_sort_by'] ? Thank you!

**Comment by seabasss** [comment]
@jonahgreenthal Would you mind sharing a complete example of your select2 code? Maybe I missed something. Thanks!

**Comment by jonahgreenthal** [comment]
Here you go.  Sorry for some archaic coding conventions (like prefixing local variables with `lcl` and arguments with `arg`).

```
var lclSelect2Query; // This is a global object rather than one per Select2 box, since only one can be queried at a time

var defaultSorter = function(argResults) {
	return argResults.sort();
}

var prefixPreferredSorter = function(argResults) {
	if (argResults && argResults.length > 0) {
		var lclSearchString = lclSelect2Query.term || '';
		lclSearchString = lclSearchString.toLowerCase(); // case-insensitive
		
		if (lclSearchString.length == 0) {
			return argResults;
		} else {
			return argResults.sort(
				function(argA, argB) {
					var lclDisplayA = argA.text.toLowerCase(); // case-insensitive
					var lclDisplayB = argB.text.toLowerCase(); // case-insensitive
					
					if (lclSearchString == '') {
						return argA.text.localeCompare(argB.text);
					}
					
					if (lclDisplayA.indexOf(lclSearchString) == 0) {
						if (lclDisplayB.indexOf(lclSearchString) == 0) {
							// They're both in the top group; within-group order is normal
							return argA.text.localeCompare(argB.text);
						} else {
							// A goes to the top
							return -1;
						}
					} else {
						if (lclDisplayB.indexOf(lclSearchString) == 0) {
							// B goes to the top
							return 1;
						} else {
							// They're both in the bottom group; within-group order is normal
							return argA.text.localeCompare(argB.text);
						}
					}
				}
			);
		}
	} else {
		return argResults;
	}
};

var lclSelect2BaseOptions = {
	placeholder: 'Choose...',
	// selectOnClose: true,
	templateSelection: function(argSelection) {return $.parseHTML(argSelection.name || argSelection.text);},
	language: {
		errorLoading: function() {return 'Results could not be loaded.';},
		inputTooLong: function(e) {var t = e.input.length - e.maximum, n = 'Please delete ' + t + (t == 1 ? ' character.' : ' characters.');},
		inputTooShort: function(e) {
			if (e.input.length == 0) {
				return '';
			} else {
				return 'Please enter at least ' + (e.minimum - e.input.length) + ' more ' + (e.minimum - e.input.length == 1 ? 'character.' : 'characters.');
			}
		},
		loadingMore: function() {return 'Loading more results...';},
		maximumSelected: function(e) {var t = 'You can only select ' + e.maximum + (e.maximum == 1 ? ' item.' : ' items.');},
		noResults: function() {return 'No results.';},
		searching: function(argParams) {lclSelect2Query = argParams; return 'Searching...';}
	}
};

var lclSelect2Options = $.extend({}, lclSelect2BaseOptions, {sorter: prefixPreferredSorter})
```

Then most Select2s are initialized in another file with `$('select.searchable').select2(lclSelect2Options);`. If we want a different sorter, we use `lclSelect2BaseOptions` instead.

**Comment by seabasss** [comment]
@jonahgreenthal Thanks, that worked! :)

**Comment by alexweissman** [comment]
@jonahgreenthal when you get a chance, since it sounds like you've cracked this nut, could you document the use of `searching` and `sorter`?  `searching` could go in https://select2.org/searching, and `sorter` sounds like it should go in https://select2.org/dropdown.  Thanks!

**Comment by jonahgreenthal** [comment]
I feel like I've only half-cracked it, but I'll see what I can do when I have some time. (I don't know when that will be.)

That said, I didn't (half-)crack it on my own; surely I found some other resource that helped me, so it might be better to backtrack there — if I had any idea what resource that was.

**Comment by alexweissman** [comment]
💪

**Comment by jschwartz73** [comment]
> Here you go. Sorry for some archaic coding conventions (like prefixing local variables with `lcl` and arguments with `arg`).
> 
> ```
> var lclSelect2Query; // This is a global object rather than one per Select2 box, since only one can be queried at a time
> 
> var defaultSorter = function(argResults) {
> 	return argResults.sort();
> }
> 
> var prefixPreferredSorter = function(argResults) {
> 	if (argResults && argResults.length > 0) {
> 		var lclSearchString = lclSelect2Query.term || '';
> 		lclSearchString = lclSearchString.toLowerCase(); // case-insensitive
> 		
> 		if (lclSearchString.length == 0) {
> 			return argResults;
> 		} else {
> 			return argResults.sort(
> 				function(argA, argB) {
> 					var lclDisplayA = argA.text.toLowerCase(); // case-insensitive
> 					var lclDisplayB = argB.text.toLowerCase(); // case-insensitive
> 					
> 					if (lclSearchString == '') {
> 						return argA.text.localeCompare(argB.text);
> 					}
> 					
> 					if (lclDisplayA.indexOf(lclSearchString) == 0) {
> 						if (lclDisplayB.indexOf(lclSearchString) == 0) {
> 							// They're both in the top group; within-group order is normal
> 							return argA.text.localeCompare(argB.text);
> 						} else {
> 							// A goes to the top
> 							return -1;
> 						}
> 					} else {
> 						if (lclDisplayB.indexOf(lclSearchString) == 0) {
> 							// B goes to the top
> 							return 1;
> 						} else {
> 							// They're both in the bottom group; within-group order is normal
> 							return argA.text.localeCompare(argB.text);
> 						}
> 					}
> 				}
> 			);
> 		}
> 	} else {
> 		return argResults;
> 	}
> };
> 
> var lclSelect2BaseOptions = {
> 	placeholder: 'Choose...',
> 	// selectOnClose: true,
> 	templateSelection: function(argSelection) {return $.parseHTML(argSelection.name || argSelection.text);},
> 	language: {
> 		errorLoading: function() {return 'Results could not be loaded.';},
> 		inputTooLong: function(e) {var t = e.input.length - e.maximum, n = 'Please delete ' + t + (t == 1 ? ' character.' : ' characters.');},
> 		inputTooShort: function(e) {
> 			if (e.input.length == 0) {
> 				return '';
> 			} else {
> 				return 'Please enter at least ' + (e.minimum - e.input.length) + ' more ' + (e.minimum - e.input.length == 1 ? 'character.' : 'characters.');
> 			}
> 		},
> 		loadingMore: function() {return 'Loading more results...';},
> 		maximumSelected: function(e) {var t = 'You can only select ' + e.maximum + (e.maximum == 1 ? ' item.' : ' items.');},
> 		noResults: function() {return 'No results.';},
> 		searching: function(argParams) {lclSelect2Query = argParams; return 'Searching...';}
> 	}
> };
> 
> var lclSelect2Options = $.extend({}, lclSelect2BaseOptions, {sorter: prefixPreferredSorter})
> ```
> Then most Select2s are initialized in another file with `$('select.searchable').select2(lclSelect2Options);`. If we want a different sorter, we use `lclSelect2BaseOptions` instead.

This worked great for me!  Thanks

**Comment by collimarco** [comment]
This issue is still valid today and should be kept open.

**Comment by kevin-brown** [comment]
Given that the focus is on fixing bugs at the moment, this still remains low on the list of future improvements.

**Comment by thedanbob** [comment]
For posterity, here's a cleaned-up version of above that only sorts exact beginning matches to the top, and otherwise leaves the order alone.

```js
var prefixSorter = function(results) {
  if (!results || results.length == 0)
    return results

  // Find the open select2 search field and get its value
  var term = document.querySelector('.select2-search__field').value.toLowerCase()
  if (term.length == 0)
    return results

  return results.sort(function(a, b) {
    aHasPrefix = a.text.toLowerCase().indexOf(term) == 0
    bHasPrefix = b.text.toLowerCase().indexOf(term) == 0

    return bHasPrefix - aHasPrefix // If one is prefixed, push to the top. Otherwise, no sorting.
  })
}

$('select.select2').select2({ sorter: select2sorter })
```

**Comment by Gildedter** [comment]
> For posterity, here's a cleaned-up version of above that only sorts exact beginning matches to the top, and otherwise leaves the order alone.
> 
> ```js
> var prefixSorter = function(results) {
>   if (!results || results.length == 0)
>     return results
> 
>   // Find the open select2 search field and get its value
>   var term = document.querySelector('.select2-search__field').value.toLowerCase()
>   if (term.length == 0)
>     return results
> 
>   return results.sort(function(a, b) {
>     aHasPrefix = a.text.toLowerCase().indexOf(term) == 0
>     bHasPrefix = b.text.toLowerCase().indexOf(term) == 0
> 
>     return bHasPrefix - aHasPrefix // If one is prefixed, push to the top. Otherwise, no sorting.
>   })
> }
> 
> $('select.select2').select2({ sorter: prefixSorter })
> ```

Will this work on array data sources (with option groups)?

**Comment by thedanbob** [comment]
Array data sources yes, don't know about the option groups. It depends on whether Select2 leaves option groups in the original order and just sorts results within each one, or moves the groups around based on overall results sorting. My guess would be the former, but I'd say just try it out and see what happens.
