### ISSUE TITLE
Enter key still works on disabled select when ID is set

### ISSUE THREAD

**Issue by Pompiedom** [select2/select2#4695]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a select with the "disabled" attribute
2. Init select2
3. Click with the mouse on the disabled select
4. Press the enter key
5. The dropdown doesn't open
6. Create a select with the "disabled" attribute and add an id attribute e.g. "id='test'"
7. Click with the mouse on the disabled select
8. Press the enter key
9. The dropdown does open

## Expected behavior and actual behavior

When I follow those steps, I see the dropdown open on a disabled select, that should never be possible.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [x] Internet Explorer 11

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.9.1
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin] https://jsfiddle.net/pompiedom/wz9uLehv/3/

**Comment by esl-douglas** [comment]
Still a bug.

I made a temporary fix.
$(document).on('select2:opening.disabled', ':disabled', function() {  return false; })

**Comment by ericmdantas** [comment]
Yup, also happened to me.

@esl-douglas's fix seems to do the trick. Thanks!

**Comment by ericmdantas** [comment]
By the way, these lines seem to be the ones forcing the opening: https://github.com/select2/select2/blob/062c6c3af5f0f39794c34c0a343a3857e587cc97/src/js/select2/core.js#L319-L353

Maybe just checking the state of the select should do the trick?

**Comment by alexweissman** [comment]
Sure, want to make the fix, write up a few tests, and submit a PR?

Looks like in other parts of the codebase, we use some simple logic to return early when the control is disabled:

https://github.com/select2/select2/blob/062c6c3af5f0f39794c34c0a343a3857e587cc97/src/js/select2/core.js#L448-L450

**Comment by Doolan** [comment]
This issue also exists in the examples app. 
https://select2.org/appearance 

Clicking on the disabled dropdown and hitting the space key will allow the user to chose a new option and change the value of the dropdown.

**Comment by JonBetts** [comment]
This still seems to be an issue in 4.0.5. I'm surprised more people haven't reported it!

**Comment by fr0z3nfyr** [comment]
Any plans to close this in next release?

I guess this is where the test has to be made and `return false` (on master)
https://github.com/select2/select2/blob/04fce559673684af8ec2912457a9d6380ea90314/src/js/select2/core.js#L348-L355

**Comment by VpocopocoV** [comment]
For anyone using select2.full.min.js, you may search for "a.open" and replace that part of the code with the one below:

this.options.get("disabled") ? b.preventDefault() : a.open()

This will inspect if the select2 element is disabled and prevent any further action.

**Comment by paxnovem** [comment]
I am going to reopen this issue for another stale cycle.

**Comment by kevin-brown** [comment]
This was fixed in 4.0.13 by https://github.com/select2/select2/pull/5751.
