### ISSUE TITLE
matcher not working

### ISSUE THREAD

**Issue by bonesoul** [select2/select2#4696]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Expected behavior and actual behavior

matcher should be running

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.2.4
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

Here is the jsfiddle sample: https://jsfiddle.net/bonesoul/6qsudL55/8/
with: select2/compat/matcher https://jsfiddle.net/bonesoul/6qsudL55/9/

**Comment by PeterShaws** [comment]
I can confirm that the problem still persists. Tested on Firefox 51.0.1.

**Comment by alexweissman** [comment]
`matcher` only works with data provided via an [array](https://select2.org/data-sources/arrays).  As of v4.0.3, you cannot use `matcher` with remotely-sourced data.
