### ISSUE TITLE
Tooltip is not cleared for empty value if placeholder is there

### ISSUE THREAD

**Issue by KarthikaMurugesh** [select2/select2#4700]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Enable placeholder for dropdown
2. select a value 
3. Clear the value and check tooltip

3.

## Expected behavior and actual behavior

When I follow those steps, I see...
Previous selected value is in tooltip
I was expecting...
No tooltip in that case
## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
#4746 has been merged into the 4.0.6-rc.0 pre-release.
