### ISSUE TITLE
Bad line endings in NPM package

### ISSUE THREAD

**Issue by danepowell** [select2/select2#4703]
The line endings for most files in the NPM package of select2 are CRLF. For instance, on Unix you can run `file dist/js/i18n/cs.js` to see that the file is CRLF.

I believe they should all be LF instead. They are (correctly) LF in the Github repo, but something in the NPM publishing process is converting them to CRLF. 

Probably related to https://github.com/npm/npm/issues/12371

**Comment by kevin-brown** [comment]
The latest push to NPM was done on Windows, which is why all of the line endings are CRLF.

With that being said, is this actually causing any issues?

**Comment by danepowell** [comment]
It does actually cause problems. If you commit the select2 library to Git (for instance as part of a build artifact), git will perpetually report the CRLF files in working checkouts to be overridden.

**Comment by danepowell** [comment]
This appears to no longer be an issue in 4.0.6-rc1 (not sure exactly when it got fixed.)

Used this command to confirm it:
`find -type f -execdir file {} \; | grep CRLF`

**Comment by carltongibson** [comment]
At lease `i18n/sq.js` made it's way into 4.0.7 will CRLF line endings. (Not necessarily an issue but...)

**Comment by kevin-brown** [comment]
This should be permanently fixed when we move to automatically building and pushing NPM tags from our CI.
