### ISSUE TITLE
Menu item to always show in fixed position on bottom

### ISSUE THREAD

**Issue by danielone** [select2/select2#4704]
hello, is there a way to get a menu item to always display in a fixed position at the bottom of the menu when it opens. See "Manage..." action at bottom of menu in example below:

>someMenuItem
>someMenuItem
>someMenuItem
>someMenuItem
>someMenuItem
>someMenuItem
>--------------------
>Manage...

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
