### ISSUE TITLE
Open Dropdown options are not refreshed when multiple select value changed programmatically

### ISSUE THREAD

**Issue by terryroe** [select2/select2#4705]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  Open a multiple select dropdown.
2.  Change the value programmatically: $('select').val('AK').change();

## Expected behavior and actual behavior

When I follow those steps, I see...  The options in the input area are updated.  The options in the dropdown are not updated.

I was expecting...  The options in the dropdown to be updated to reflect the new value of the select element / the items that have been selected programmatically.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.11.2, 3.1.1
- Select2 version: 4.0.3

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

## Notes

I've implemented a Select All / None feature in my custom dropdown.  I need the dropdown items to be updated immediately because the dropdown is open and the options are displayed at the time I change the select value programmatically.

I've searched for a report of this problem everywhere I can think of and I can't find a report of it, nor can I find a workaround.  I would really appreciate any help in finding a fix/workaround for this.

**Comment by SgtOddball** [comment]
The only way I can think of is to trigger the back end select toggle, reload Select2 (normal procedure after changing options programatically) and then trigger the open command again - It'd be a dirty way hacky way of doing it but it'd be the quickest method I can think of without having to rebuild parts of Select 2 to allow this .

**Comment by terryroe** [comment]
For those interested, I found a workaround.  After I change the value of the select element, I update the `aria-selected` attributes of the results, like so:  `$('select').data('select2').$results.children().attr('aria-selected', [true|false]);`

BTW, is this the best way to get a reference to the select2 instance: `$('select').data('select2')` ?
