### ISSUE TITLE
dropdown option values are not adjusting with the parent dropdown when scrolling on modal popup

### ISSUE THREAD

**Issue by ChanduSirigiri** [select2/select2#4708]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [x] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by ChanduSirigiri** [comment]
Currently, we are using bootstrap modal popup. On popup i have ten dropdown boxes, fifth dropdown box has ten three dropdown option values. On Click of fifth dropdown, am scrolling on modal popup. The dropdown option values related to fifth dropdown remains in static position, option vales are not scrolling with respect to the parent dropdown.

**Comment by alexweissman** [comment]
It is unclear what the issue is here.  Without a jsbin or screenshots, we cannot determine the problem.
