### ISSUE TITLE
How to programatically select values on Select2 which loads it's values through ajax on v 4.0.3

### ISSUE THREAD

**Issue by mehafi** [select2/select2#4709]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of Select2
- [X ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Described in 
http://stackoverflow.com/questions/30517128/how-to-programmatically-inject-search-queries-into-select2-v4#30552284

This solution works, but as mentioned in comments:
"This is not complete, how do you simulate an ENTER afterwards so the dropdown accepts the entered string and closes? "
 in version 4 the item is not selected and dropdown list is not closing

## Expected behavior and actual behavior

When I follow those steps, I see...
Select2 dropwdown with result of searched items

I was expecting...

...that first of founded items will be selected and dropdown is closed

## Environment

Browsers

- [X ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [X ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by dynasource** [comment]
confirmed locally & on the examples page

**Comment by dynasource** [comment]
looks like a Chrome issue

**Comment by alexweissman** [comment]
This is now documented here: https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2

I would recommend this approach over Kevin's approach of simulating the user's actions.
