### ISSUE TITLE
Is select2 considered WCAG compatible?

### ISSUE THREAD

**Issue by drauch** [select2/select2#4716]
* Is select2 considered WCAG compatible?
* If no, do you at least know which issues the current implementation has?

I would be interested in providing a PR that would make it WCAG compatible (if possible...). First, however, I'd like to gather all information you already have on the topic. Are there any existing PRs, are there any existing lists of issues, etc...

Best regards,
D.R.

**Comment by kevin-brown** [comment]
We're tracking accessibility issues at the following ticket: https://github.com/select2/select2/issues/3744

It has a lot of information located within it.
