### ISSUE TITLE
Ability to override AjaxAdapter

### ISSUE THREAD

**Issue by Lughino** [select2/select2#4718]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steos to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

With the new adapter system it is possible to implement customizations, such as `ResultAdapter`.
Unfortunately it can not do the `AjaxAdapter` override.
Implement the transport is not sufficient because some features such as the abort of the previous query is not possible in module that use calling the abort method.

Can you implement the ability to override also `AjaxAdapter`?
Thanks

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
