### ISSUE TITLE
Is Select2 Compatible with jQuery 3.x

### ISSUE THREAD

**Issue by cersos** [select2/select2#4721]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

On initial load, the The jQuery migrate plugin gives an error:
"jQuery.fn.offset() requires an element connected to a document"

The Select2 select boxes do not work the first time they are clicked.  It just starts highlighting everything on the page.  On subsequent clicks of the element, it works fine.

If I revert back to jQuery jquery-1.11.0 it works perfectly

Strangely enough, it works fine in IE11.

## Environment

Browsers

- [ ] Google Chrome
- [X] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

Libraries

- jQuery version: jquery-3.1.1
- Select2 version: 4.0.3

**Comment by cersos** [comment]
The fullerror reads: jQuery.fn.offset() requires an element connected to a document

**Comment by kevin-brown** [comment]
Based on the errors, my guess is no. Select2 is not currently tested against jQuery 3.x, and I believe we have a duplicate ticket open... somewhere, about this.

**Comment by cersos** [comment]
After the initial load, if you open and close the select2, it works fine.

**Comment by cersos** [comment]
One pretty cheesy work-around that does work in FF:
1. initialize the select2(s)
2. Pick one and: jQuery('#select2id').select2('open').select2('close');

**Comment by irobayna** [comment]
@cersos @kevin-brown I have upgraded to JQuery 3.1.1 and do **not** see the issue being reported.  Actually there are no errors, select2 is behaving as expected.

Could it be possible something else is the culprit as jQuery 3.1.1 changed the way some calls should be invoked?

For instance:
```javascript
$(window).unload(function(){ ...
```
should be 
```javascript
$(window).on('unload',function(){ ...
```

Any chance you can put together a [jsfiddle](https://jsfiddle.net/) reproducing the issue?

**Comment by cersos** [comment]
From what I can tell, everything is syntactically correct.  It works fine in IE, no errors (well, honestly I haven't checked the IE console for warnings).  It is just in the latest FireFox.  I don't have Chrome installed to test there.

**Comment by cersos** [comment]
I am astounded that this seems to be an issue with the Firebug Firefox extension.  That extension is no longer being developed or supported.  Once I removed it the usability problems vanished.  There are still warnings caused by select2 logged to the console, so there is work to do, but select2 seems to work fine.

**Comment by irobayna** [comment]
@cersos could you close this item?

**Comment by bernardotavares** [comment]
I'm trying to migrate from v1.12.4 to v3.2.1 using jQuery migrate plugin and I'm also experiencing the same "jQuery.fn.offset() requires an element connected to a document" error. Both in Firefox and Chrome.

I don't completely understand the issue, but I think it may be related to [this](https://github.com/jquery/jquery/pull/3487) jquery fix.

This is the error in the console:
![error](https://user-images.githubusercontent.com/25110465/34264684-94a8cf3a-e66b-11e7-84ab-fa0c7fbd4ff8.PNG)

I know this is a closed issue, but you guys think you have enough information to help me? Is the only thing stoping me from successfully migrating to jQuery 3.x. Thanks!

**Comment by alexweissman** [comment]
@bernardotavares my guess is a compatibility issue with the jQuery migrate plugin in particular, and not jQuery itself.  You should open a new issue for this.  Please be sure to follow the [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).
