### ISSUE TITLE
Generated elements have no name or ID for unittesting

### ISSUE THREAD

**Issue by chrisspen** [select2/select2#4723]
I'm attempting to write some Selenium unittests for forms that use Select2, and I'm finding this very difficult because the dynamically generated "fake" form fields have no Select2 name or ID that links them to the "real" form fields. Therefore, I can't write a test that does something like:

    browser.find_element_by_name('myfield')

Is there any way to add a name or custom class name to the dynamically generated elements so they could be programmatically clicked on by a simulated browser?

**Comment by kevin-brown** [comment]
You can find the logic that Select2 uses for generating unique ids for elements at https://github.com/select2/select2/blob/563198a4a2e0eb9f7adbc4775d360db1037a13db/src/js/select2/core.js#L91-L106. Basically, if you have an ID, then Select2 will prefix all of its elements with `select2-[form field id]`, but anything else isn't guaranteed to be unique.

You can always get the internal ID used by Select2 for an element by doing

```js
$element.data('select2').id
```

But note that this is an internal ID and how it's used may change in the future.
