### ISSUE TITLE
Events are not detached properly, causing memory leaks

### ISSUE THREAD

**Issue by muthuraja** [select2/select2#4725]
Hi,
Events not properly detached. Its eating lot of memory. I need the solution.   
![select2](https://cloud.githubusercontent.com/assets/26075/21353500/4db53982-c6ec-11e6-964e-966d650dd09b.png)

Muthuraja

**Comment by kevin-brown** [comment]
What event? And when is it supposed to be removed?

**Comment by derekm** [comment]
User also reported their error here: https://github.com/iStefo/ember-select-2/issues/143

**Comment by Dshoe** [comment]
We can reproduce listener leaks in an Angular 1.x app. What is proving difficult is root causing the issue. Any suggestions?

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:
