### ISSUE TITLE
Events not properly detached. Its eating lot of memory. I need the solution.

### ISSUE THREAD

**Issue by elakkuvan** [select2/select2#4726]
#Events not properly detached. Its eating lot of memory. I need the solution.Please check this

**Comment by elakkuvan** [comment]
Any update

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/4725.

**Comment by Dshoe** [comment]
@kevin-brown Did you ever find a solution or root cause the problem?
