### ISSUE TITLE
Disable dropdown & customize select

### ISSUE THREAD

**Issue by gnishimurabetalabs** [select2/select2#473]
How can I disable dropdown on a multiple select?
I dont understand how to use preventDefault() function so that it won't open.

Thanks in advance,

Gabriel

**Comment by metamaker** [comment]
@ivaynberg this is not the answer. Please, provide link to documentation entry or write code sample.

**Comment by alexweissman** [comment]
You should ask on the [forums](https://forums.select2.org), as this issue is quite old at this point.  It's also not clear which version of Select2 you need help with.
