### ISSUE TITLE
Update select2 display when selected option's HTML is changed

### ISSUE THREAD

**Issue by jpic** [select2/select2#4733]
## Steps to reproduce the issue

1. Select an option
2. Programmatically change the selected option's HTML text

## Expected behavior and actual behavior

When I follow those steps, I see that select2 displays the initial option name.

I was expecting select2 to update the display with the selected's option new HTML text.

**Comment by codingjoe** [comment]
This would be much appreciated since it's blocking [getting select2 into Django's admin](https://github.com/django/django/pull/6385)

**Comment by codingjoe** [comment]
Yes, I also managed to integrate Select2 into Django anyways. I don't remember how I solved this issue, sorry.
