### ISSUE TITLE
List alternates between open and closed when removing tags (closeOnSelect:false)

### ISSUE THREAD

**Issue by franciscolourenco** [select2/select2#4740]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a multiple select with {closeOnSelect:false}
2. Select multiple options
3. Remove options sequentially using the tags little delete button (x).

## Expected behavior and actual behavior

The list alternates between open and closed each time you remove an option.
I was expecting the list to remain either open or closed.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox

Operating System

- [x] Mac OS X

Libraries

- jQuery version: 1.12.4
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/zusomoside/1/edit?html,js,output)

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.

**Comment by franciscolourenco** [comment]
@pedrofurtado there is a jsbin in the description, please have a closer look. Do you have any other questions?
