### ISSUE TITLE
Firefox crashes when tagging with non-ASCII characters (Chinese/Japanese, diacritics, unicode, etc)

### ISSUE THREAD

**Issue by vitorlee** [select2/select2#4743]
## Steps to reproduce the issue

1. ONLY in Firefox browsers, no matter which version, which OS
2. Enable tagging 
3. Switch IME to Chinese/Japanese model, and try to input some tags
4. Never get the correct result

## Environment

Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html#tags)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by gejobj** [comment]
I can reproduce this error typing á or é or â in firefox 50.1.0 when tagging is activated.
I try to create tags like: camión or melón at example page and it crash on firefox.
Copy and paste words have same error.

Regards.

**Comment by gejobj** [comment]
Please @vitorlee, change issue title because Spanish, French, German... all languajes that use words with accents cannot work under firefox. It seems firefox send accent before character and it makes break javascript.

**Comment by Feuda** [comment]
Same issue, any solutions?

**Comment by kzkn** [comment]
Here is a small reproducing code (without select2).

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <ul>
      <li class="input"><input type="text"></li>
    </ul>

    <script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>
    <script>
     var items = [];
     var $ul = $("ul");
     var $liin = $("li.input");
     var $in = $liin.find("input");
     $ul.on("input", "li.input", function() {
       items.push($in.val());
       $ul.empty();
       for (var e of items)
         $ul.append($("<li class='choice'>" + e + "</li>"));
       $ul.append($liin);
       $in.focus();
     });
    </script>
  </body>
</html>
```

Firefox will confuse when the `<input>` disappears from DOM tree while inputing with IME.

Select2 is being affected by this behaviour. At here:
https://github.com/select2/select2/blob/ebf10c93db7d6d7a0d1330119d4c6f32cbd231d7/src/js/select2/selection/multiple.js#L58

and here:
https://github.com/select2/select2/blob/ebf10c93db7d6d7a0d1330119d4c6f32cbd231d7/src/js/select2/selection/search.js#L173-L174

**Comment by kzkn** [comment]
Same issue with Chrome (64.0.3282.119) on linux.

**Comment by kzkn** [comment]
In develop branch, bca6a503310a5e0c8b8030c63ff66ab52cd7885c is blocking the resolution of this problem.

**Comment by untidy-hair** [comment]
Hi, this is an issue for Chrome 70.0.3538 on MacOS X Sierra as well.
![image](https://user-images.githubusercontent.com/3161723/49331160-cfa84b00-f54d-11e8-9196-08050faa1b9c.png)

**Comment by rafadepaula** [comment]
Any solution to this? I'm having the same issue on any browser at Mac OS High Sierra.

**Comment by dgilperez** [comment]
Any solution or workaround? We just got hit buy this as well on MacOS.

**Comment by TeoMastro** [comment]
I have an issue with greek characters where:
Greek punctuation tone is inserted as separate character on select2 when using tagging and Multiple on same field. This happens only after the first letter. The first letter accepts the tone, if necessary, but after that tone is inserted as new character. Like this:

Actual greek word: Βοήθεια
How is inserted: Βο΄ηθεια

On first letter: Έλεγχος (Correctly inserted)
