### ISSUE TITLE
"TypeError: g._removeOldTags is not a function" when deleting selections with backspace in multi-select

### ISSUE THREAD

**Issue by Bllacky** [select2/select2#4747]
I am using the latest version of select2 from this repo.
I have a simple situation with a field which gets its data using ajax from a php page. Almost identical to the example "Loading remote data".
tags option is set to false and needs to be set to false in my situation.
multiple: true
firefox 50

Steps:
1. select an option from the list
2. use backspace to delete the option
3. get the error in console: TypeError: g._removeOldTags is not a function while deleting the option character by character with backspace

Nothing breaks, everything continues to work as it should, but it would be nice to avoid such errors. They may be an indication of more profound code problems. 

Thanks!

**Comment by tristancaron** [comment]
Same issue

I have a select2 with `multiple=true`, and when I want to delete an option with backspace it's throwing this same error.

Latest version of select2, on Chrome 56.

**Comment by ketangoyani** [comment]
Because of this console error, It is only matching only first word from options, fails to match from second word.

**Comment by oussjarrouse** [comment]
I am having this issue too.

**Comment by kangel5** [comment]
Same issue.

I can replicate with attribute:
tokenSeparators: [',', ' '],

The console errors won't occur with:
tags: true,

but if you:
tags: false,
then it gets that console error.

It's trying to: 
self._removeOldTags(); from select2.js (v4.0.4 line #3683)
Error: TypeError: self._removeOldTags is not a function

**Comment by Folrond** [comment]
+1
I have the exact same issue.
multiple: true
tags: false
Error: g._removeOldTags is not a function

**Comment by alexweissman** [comment]
It would be very helpful if someone could create a [JSBin](http://jsbin.com/goqagokoye/edit?html,js,output) that replicates this behavior.

**Comment by alexweissman** [comment]
I can't seem to replicate this issue.  I have a multi-select that pulls data from a remote source, and `tags:false`, but I don't get this error in my console when deleting a selection with backspace.

Do I need to have `tokenSeparators` set?

**Comment by Bllacky** [comment]
Used parameters:
    tags: false,
    multiple: true,
    tokenSeparators: [',', ' '],
    minimumInputLength: 0,
	searchType: "contains",
quietMillis: 100,
		cache: false,
		dataType: "json",
        type: "POST"

**Comment by alexweissman** [comment]
Ok, can you please use [this template](http://jsbin.com/befamijeqo/edit?html,js,output) to replicate the error and post a link?

**Comment by kangel5** [comment]
Replicated with the following Javascript in your jsbin Alex:

$(document).ready(function() {
    $('#example1').select2({
        multiple: true,
        tokenSeparators: [',', ' '],
        tags: false
    });
});

**Comment by alexweissman** [comment]
Odd - when I start using backspace in the jsbin, it first loses focus, then deletes the control entirely.

Could be related to #5161, in which case we'll need to resolve that issue before we can tackle this one.

**Comment by looqmaan** [comment]
I got the same error when I was using as:

```javascript
            // tags: false,
            tokenSeparators: [",", " "],
```

Fixed by removing the whitespace tokenSeparators:

```javascript
            // tags: false,
            tokenSeparators: [","],
```

**Comment by Bllacky** [comment]
Sorry,

Hasn't anyone fixed this issue when the space separator is enabled?

**Comment by ricvale** [comment]
Thank you
fixed as told:
... 
> that removing the white space from the tokenseparators list fixes the problem.

**Comment by JonathanSeguin** [comment]
Getting the error on 4.0.7 when pasting a comma separated list of values (without space as separator).
tokenSeparators: [","]

**Comment by peldax** [comment]
I have the same issue with non-multiple ajax select. Same exception was thrown while i entered space in search box. Dropping space from tokenSeparators solved the issue.

**Comment by FroggDev** [comment]
The bug seems to be related to removeTag when an item already exist or something like that. When the search has no result and you press a confirm ket it try to remove this "not existint" tag and try to removeTag on undefined, and trigger an error.
To get rid of it i edited the minified file and added :

`"function"===typeof r._removeOldTags && r._removeOldTags(`)

instead of 

`r._removeOldTags()`

**explaination :**
check if r._removeOldTags is a function, and if it is trigger it, else do nothing.

**Comment by devmonkey22** [comment]
As a follow-up to this, I am still able to reproduce the original `Uncaught TypeError: s._removeOldTags is not a function` error with the latest select2 as well as 4.0.13. It seems to stem from the `Tokenizer` trying to access methods from the `Tags` decorator, when `tags: false`, so the `Tags` decorator is not available.  It's not just backspace, but when trying to create a new tag thru the Tokenizer.

Environment:

- select2 4.1.0-rc.0 and 4.0.13
- jQuery 3.6.0 and 2.x

Reproduction Steps:

- Load the example at https://jsbin.com/corapat/edit?html,css,js,output (thanks to JonathanSeguin for the base codesnippet)
- In the Live View panel, focus into the select2 control
- Start typing "bug;" (without quotes)
- The Dev Console immediately pops up with the following error:

```
select2.js:3950 Uncaught TypeError: self._removeOldTags is not a function
    at createAndSelect (select2.js:3950)
    at DecoratedClass.Tokenizer.tokenizer (select2.js:4014)
    at DecoratedClass.tokenizer (select2.js:598)
    at DecoratedClass.Tokenizer.query (select2.js:3966)
    at DecoratedClass.query (select2.js:598)
    at Select2.<anonymous> (select2.js:5801)
    at Select2.Observable.invoke (select2.js:655)
    at Select2.Observable.trigger (select2.js:645)
    at Select2.trigger (select2.js:5939)
    at DecoratedClass.<anonymous> (select2.js:5753)
```

Seems like the [Tokenizer](https://github.com/select2/select2/blob/0a30b0b3e67843c09b0bcc4d01e65b72d9b1279f/src/js/select2/data/tokenizer.js#L34) needs to check for Tags and skip trying to select if needed:

```javascript
      // If an existing option wasn't found for it, create the option
      if (!$existingOptions.length) {
        // If tags, allow creating new options
        if (self.options.get("tags")) {
            var $option = self.option(item);
            $option.attr('data-select2-tag', true);

            self._removeOldTags();
            self.addOptions([$option]);
        }
        else {
            // Don't create new option or select item
            return;
        }
      }
```

I'll try to gather up to put this in a PR too.

I have a related feature request to add support for typing an option's text (for when text and value are not the same) and have the Tokenizer select it too.
