### ISSUE TITLE
Placeholder not shown with ajax option

### ISSUE THREAD

**Issue by soncemvo** [select2/select2#4748]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create select2 with ajax(autocomplete) option and "placeholder" option

## Expected behavior and actual behavior

When I follow those steps, I see blank placeholder

I was expecting respecting placeholder option

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:1.8.3
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by web-4-u** [comment]
I had the same bug, i was overwriting "templateSelection" function because my items were not using the text property. 

Try the following 

`templateSelection: function(item) {
			return item.name || item.text;
		}`

**Comment by soncemvo** [comment]
thank you. but its not working for me...

**Comment by web-4-u** [comment]
Do you overwrite templateSelection ? If yes, can you show me a sample of your ajax loaded data ? And maybe console.log item parameter

**Comment by soncemvo** [comment]
ajax data is: 

`{"searchContext":{"contentType":"city","regionId":"3700000000000","query":"\u0438\u0432\u0430\u043d\u043e\u0432\u043e","withParent":"1","limit":20},"result":[{"id":"3700000100000","name":"\u0418\u0432\u0430\u043d\u043e\u0432\u043e","zip":153032,"type":"\u0413\u043e\u0440\u043e\u0434","typeShort":"\u0433","okato":"24401000000","contentType":"city","parents":[{"id":"3700000000000","name":"\u0418\u0432\u0430\u043d\u043e\u0432\u0441\u043a\u0430\u044f","zip":153032,"type":"\u041e\u0431\u043b\u0430\u0441\u0442\u044c","typeShort":"\u043e\u0431\u043b","okato":"24000000000","contentType":"region"}]},{"id":"3701100003500","name":"\u0418\u0432\u0430\u043d\u043e\u0432\u043e-\u0418\u043b\u044c\u0438\u043d\u043e","zip":155629,"type":"\u0414\u0435\u0440\u0435\u0432\u043d\u044f","typeShort":"\u0434","okato":"24217808003","contentType":"city","parents":[{"id":"3700000000000","name":"\u0418\u0432\u0430\u043d\u043e\u0432\u0441\u043a\u0430\u044f","zip":153032,"type":"\u041e\u0431\u043b\u0430\u0441\u0442\u044c","typeShort":"\u043e\u0431\u043b","okato":"24000000000","contentType":"region"},{"id":"3701100000000","name":"\u041f\u0430\u043b\u0435\u0445\u0441\u043a\u0438\u0439","zip":155620,"type":"\u0420\u0430\u0439\u043e\u043d","typeShort":"\u0440-\u043d","okato":"24217000000","contentType":"district"}]},{"id":"3701200003600","name":"\u0418\u0432\u0430\u043d\u043e\u0432\u043e","zip":155650,"type":"\u0414\u0435\u0440\u0435\u0432\u043d\u044f","typeShort":"\u0434","okato":"24219840015","contentType":"city","parents":[{"id":"3700000000000","name":"\u0418\u0432\u0430\u043d\u043e\u0432\u0441\u043a\u0430\u044f","zip":153032,"type":"\u041e\u0431\u043b\u0430\u0441\u0442\u044c","typeShort":"\u043e\u0431\u043b","okato":"24000000000","contentType":"region"},{"id":"3701200000000","name":"\u041f\u0435\u0441\u0442\u044f\u043a\u043e\u0432\u0441\u043a\u0438\u0439","zip":155650,"type":"\u0420\u0430\u0439\u043e\u043d","typeShort":"\u0440-\u043d","okato":"24219000000","contentType":"district"}]},{"id":"3701500005700","name":"\u0418\u0432\u0430\u043d\u043e\u0432\u043e","zip":155233,"type":"\u0414\u0435\u0440\u0435\u0432\u043d\u044f","typeShort":"\u0434","okato":"24223840019","contentType":"city","parents":[{"id":"3700000000000","name":"\u0418\u0432\u0430\u043d\u043e\u0432\u0441\u043a\u0430\u044f","zip":153032,"type":"\u041e\u0431\u043b\u0430\u0441\u0442\u044c","typeShort":"\u043e\u0431\u043b","okato":"24000000000","contentType":"region"},{"id":"3701500000000","name":"\u0420\u043e\u0434\u043d\u0438\u043a\u043e\u0432\u0441\u043a\u0438\u0439","zip":155250,"type":"\u0420\u0430\u0439\u043e\u043d","typeShort":"\u0440-\u043d","okato":"24223000000","contentType":"district"}]}]}`

and my init code for that select is:
`
    $("#city_select").select2({

        ajax: {
            url: "/ajax/geo_sugest",
            type: "POST",
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    term: params.term,
                    type: 'city',
                    sub_id: $('#region_select').val()
                };
            },
            processResults: function (data) {


                return {
                    results: data.result
                }
            },
            cache: false
        },

        //escapeMarkup: function (markup) { return markup; },
        placeholder: "Город",
        minimumInputLength: 1,
        templateResult: formatCity,
        templateSelection: function(item) { return item.name || item.text; }
    });

    function formatCity(city) {

        var markup = city.typeShort + '. ' + city.name;

        if (city.parents) {

            city.parents.forEach(function (item, i, arr) {
                if (item.contentType == 'district') {
                    markup = item.name + ' ' + item.typeShort + ', ' + markup;
                }
            });
        }

        return markup;
    }
`

**Comment by scottjreece** [comment]
Any updates here? I'm having the same issue.

Thanks!
-Scott

**Comment by knguyen93** [comment]
I have the same problem when modify "templateResult" as well as "templateSelection", it seem like this modified block the "placeholder" attr.
You just need to add an empty option "<option></option>" and it will work.

**Comment by soncemvo** [comment]
it added but still not work

**Comment by knguyen93** [comment]
You might need to check the templateResult and templateSelection. They should return item.text item.html, i think. For sure, u can leave the function without override templateResult and templateSelection.

**Comment by alexweissman** [comment]
The requirement for an empty `<option>` element is now documented: https://select2.org/placeholders#text-placeholders

**Comment by karandocs** [comment]
> I had the same bug, i was overwriting "templateSelection" function because my items were not using the text property.
> 
> Try the following
> 
> `templateSelection: function(item) { return item.name || item.text; }`

Fixed! thanks

**Comment by nikriaz** [comment]
In my case, I used Select2 wrapper for Vue like this:
`<select2 :options="options" v-model="selected"/>`
and the bound model "selected" was a number type. Changing it to string type solved problem with placeholder. No any of solution above would further required - it starts to work like this `placeholder: "My Placeholder"` even without empty option.
