### ISSUE TITLE
ajax call at opening event

### ISSUE THREAD

**Issue by M0H3N** [select2/select2#4750]
how can I force the package  to send an ajax request  at opening event in remote data mode ?

**Comment by jpic** [comment]
do you mean an arbitrary ajax request or a search request ?

**Comment by M0H3N** [comment]
@jpic 
actually search request to show in select box

**Comment by jpic** [comment]
I don't know, let me take a wild guess, have you tried [minimumInputLength](
https://github.com/select2/select2/search?utf8=%E2%9C%93&q=minimumInputLength)
?​

**Comment by M0H3N** [comment]
No
 how can I use  minimumInputLength for this purpose ?

**Comment by alexweissman** [comment]
Is this question about being able to submit a specific search query when the dropdown is opened for the first time?  This could probably be handled with some logic in the `data` callback:

```
    data: function (params) {
      var query = {
        search: params.term ? params.term : 'default query',   // Set a default value for the search query
        type: 'public'
      }

      return query;
    }
```
