### ISSUE TITLE
optgroup for remote data / ajax

### ISSUE THREAD

**Issue by sajadghawami** [select2/select2#4752]
Hey gusy,

how would you create an optgroup for remote data that is being fetched. I am not sure where to put the "children part". Thats how my code looks like:

```javascript
$(".typeahead_term").select2({
            minimumInputLength: 0,
            placeholder: "Fach",
            allowClear: true,
            language: "de",
            ajax: {
                url: "{{ url('/searchTerm') }}",
                dataType: "json",
                type: "GET",
                data: function (params) {
                    var queryParameters = {
                        term: params.term
                    }
                    return queryParameters;
                },
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {
                                id:  item[1],
                                text: item[0]
                            }
                        })
                    }
                }

            }
        });
```

The Data is being displayed without a problem, i just cant get the optgroup working.

Thanks!

**Comment by korjavin** [comment]
The same here
```
//data copied from the server
// Does work

var data = '[{"id":0,"text":"\u041e\u0442\u0435\u043b\u0438","children":[{"id":"ru-Moscow","text":"\u041c\u043e\u0441\u043a\u0432\u0430, \u0420\u043e\u0441\u0441\u0438\u044f"},{"id":"us-Moscow","text":"\u041c\u043e\u0441\u043a\u0432\u0430, \u0421\u0428\u0410"}]},{"id":1,"text":"\u0413\u043e\u0440\u043e\u0434\u0430","children":[{"id":"ru-Moscow","text":"\u041c\u043e\u0441\u043a\u0432\u0430, \u0420\u043e\u0441\u0441\u0438\u044f"},{"id":"us-Moscow","text":"\u041c\u043e\u0441\u043a\u0432\u0430, \u0421\u0428\u0410"}]}]';
    
    var p=JSON.parse(data);

    $(".js-example-data-array").select2({
      data: p
    });
    
//the same data direct from the server
// Doesn't work

    $(".js-example-data-array1").select2({
    ajax: {
    url: function (params) { return 'https://cp.traveltheworld.com.ua/names1/' + params.term },
    data: function (params) {
         return {
         page: params.page
    };
    },
    dataType: 'json',
    delay: 250,
}
    });
```
https://jsfiddle.net/8odneso7/94/

**Comment by schealex** [comment]
having the same problem is there a fix?

**Comment by segsalerty2013** [comment]
Any luck with this please? Considering finding alternative using another library like twitter-typeahead

**Comment by alexweissman** [comment]
This is now documented: https://select2.org/data-sources/formats#grouped-data

**Comment by LennonCecere** [comment]
You need this structure to render grouped:

    $all = [
        // First Group
        [
            'id'        => 10,
            'text'      => 'Group_One',
            'children'  => [
                ['id' => 11, 'text' => 'Field_1_Group_One'],
                ['id' => 12, 'text' => 'Field_2_Group_One']
            ]
        ],
        // Second Group
        [
            'id'        => 20,
            'text'      => 'Group_Two',
            'children'  => [
                ['id' => 21, 'text' => 'Field_1_Group_Two'],
                ['id' => 22, 'text' => 'Field_2_Group_Two']
            ]
        ],
    ];

**Comment by LennonCecere** [comment]
You need this structure to render grouped:
(I make this struture in controller and send by json to front)

Exemple:

    $all = [
        // First Group
        [
            'id'        => 10,
            'text'      => 'Group_One',
            'children'  => [
                ['id' => 11, 'text' => 'Field_1_Group_One'],
                ['id' => 12, 'text' => 'Field_2_Group_One']
            ]
        ],
        // Second Group
        [
            'id'        => 20,
            'text'      => 'Group_Two',
            'children'  => [
                ['id' => 21, 'text' => 'Field_1_Group_Two'],
                ['id' => 22, 'text' => 'Field_2_Group_Two']
            ]
        ],
    ];
