### ISSUE TITLE
Using Select2 inside Jquery repeater not working

### ISSUE THREAD

**Issue by TnCoders** [select2/select2#4753]
## Prerequisites
Hi,  We have problem working with Select2 using jquery Repeater.

When clicking on button "Add" to repeat the form, the select2 dropdown is not working it's not initialised. how we can do this ?

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Using Select2 Ajax Dropdown inside a repeater Form using Jquery Repeater
2. When adding and clone the repeater the select2 dropdown bx cloned does not trigger and work
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: latest
- Select2 version: Select2 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
Unfortunately, without a working http://jsbin.com that replicates this issue, we cannot provide any support.  If you can add a working demonstration of the problem, we can re-open the issue.
