### ISSUE TITLE
data-ajax--url how display text with json

### ISSUE THREAD

**Issue by kleen** [select2/select2#4754]
<select name="enable" class="form-control" data-data-ajax--url="${S_URL}/ajaxService/getDict/11" data-ajax--cache="true">
                </select>
result: 
[{"id":"1","value":"1","label":"YES","description":null,"sort":null,"parentId":null,"type":null},{"id":“2”,"value":"2","label":"NO","description":null,"sort":null,"parentId":null,"type":null}]

**How to show it as** 

  <select>   
      <option value="1" > YES </option>
      <option value="2" > NO </option>
  <select>

**Comment by korjavin** [comment]
customformater for data, they have an example in examples

**Comment by alexweissman** [comment]
Sounds like you are looking for either [`templateResult`](https://select2.org/dropdown#templating) or [`templateSelection`](https://select2.org/selections#templating).
