### ISSUE TITLE
the request of a dependency is an expression - webpack

### ISSUE THREAD

**Issue by kl3sk** [select2/select2#4757]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. install select2 via npm
2. start node dev server (eg: npm run dev)

## Expected behavior and actual behavior

When I follow those steps, I see...
```
WARNING  Compiled with 1 warnings

 warning  in ./~/select2/src/js/select2/translation.js

Critical dependencies:
27:25-38 the request of a dependency is an expression

 @ ./~/select2/src/js/select2/translation.js 27:25-38
```

I was expecting...
`"no error"`
## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: NA
- Select2 version: master

## Proposal
This is due to webpack context
when i change
`var translations = require(path);`
to 
i have to remove the './' in path because sometimes it is set
`var translations = require('./' + path.replace('./',''));`

no errors occurs

**Comment by rohanc** [comment]
I found a hack to solve this issue without changing the source and wrote it up in a StackOverflow answer, [How can I using select2 with webpack?](https://stackoverflow.com/a/57000033/1140110). It involved using the imports-loader to neuter the `require(path)` call with `options: "require=>false"` and statically loading the language files by other means. See #5385.
