### ISSUE TITLE
Add select all option 

### ISSUE THREAD

**Issue by bantawa04** [select2/select2#4761]
Please add select all option [like](http://wenzhixin.net.cn/p/multiple-select/docs/#the-basics1), It will be tiring if all options are to be selected from the dropdown.

**Comment by William-H-M** [comment]
For this please refer to issue #195 and here is a more direct option made by @kevin-brown just go [here](https://github.com/select2/select2/issues/195#issuecomment-140241752)

**Comment by bantawa04** [comment]
Dear @William-H-M,
                                   Thank you for showing solution to my issue. I really would like to see this feature in upcoming version. Select2 has been really useful in my projects.
