### ISSUE TITLE
Select2 not closing on iPad (iOS 9.3.5)

### ISSUE THREAD

**Issue by sergemain** [select2/select2#4762]
I tap in control. Select2 is opened. But if I click(tap) somewhere outside, select2 not closing on iPad (iOS 9.3.5). This problem is reproduced in example https://select2.github.io/examples.html

**Comment by William-H-M** [comment]
This a know bug please refer to #4680 or #4536

**Comment by sergemain** [comment]
This bug also reproduced on mini iPad 4 (10.1.1 14B100) in Safari and Google Chrome (iPhone/iPad) 55.0.2883.79

**Comment by alexweissman** [comment]
This is a duplicate of #4013.  Please continue the conversation there.
