### ISSUE TITLE
mousedown/mouseup causes problems in making selections on mobile devices

### ISSUE THREAD

**Issue by mkmayer** [select2/select2#4763]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Stylize "select2-container--open" to stretch to whole page (mobile phone screen)
2. Click on select2 dropdownlist (mousedown). Results are displayed
3. Release mouse button (mouseup). Value is selected

## Expected behavior and actual behavior

When I follow those steps, the value is selected on one mouse click. It's because mousedown on dropdownlist shows results. It show results over whole page (which is wanted on mobile phones). On releasing mouse, it selects the value. But on mobile phone, are these events fired at once. So user can't choose from results.
If I don't use plugin closeOnSelect, results are shown, but the bug is still there (value is selected on touch)

I was expecting, that opening of results is bounded to mouse click, not to mouse down.
And selecting of results should be bounded to mouse click too.

This prevent using of select2 on mobile phones (after stylizing results to cover the select2 element).
Please could you **change the events from mouse down and mouse up to mouse click**?
Then it is usable on mobile phones too. It's ease to stylize results to whole page, but select2 is not usable then.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [x] Mobile

Libraries

- jQuery version: 1.11.3
- Select2 version: 4.0.3

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](http://jsbin.com/vacecikane/edit?html,css,js,output)

**Comment by kevinob11** [comment]
I love the idea of filling the screen on mobile, but I'm experiencing the same issue you are. I click to open the select and it immediately clicks the response located below the touch point.

**Comment by sleepydada** [comment]
@kevinob11 same here

**Comment by alexweissman** [comment]
It appears that PR #4536 addresses this problem.

**Comment by sleepydada** [comment]
Did you append the dropdown in a custom element, not the body? It was resolved when I removed the custom append element option.

**Comment by mkmayer** [comment]
I attached dropdown to body, because I had trouble with small parts of UI to ffit the dropdown. But I made my own dropdown, more features needed.

**Comment by paxnovem** [comment]
I am going to open this up for another stale cycle.

**Comment by kevin-brown** [comment]
De-milestoning this from 4.1.0 since this has gone through 4 stale cycles.
