### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by irobayna** [select2/select2#4765]
@kevin-brown  Are you still actively maintaining this project?  I noticed the last merge request was done about 26 days ago, together with a flurry of activity around that time.  It seems things have slowed down a bit in the last few months.  You mentioned somewhere that the project is not dead but rather in a slow release cycle.  Is this due to your schedule?  If so, would you be willing to assign a couple of project maintainers (seek for volunteers) that would carry your vision forward.

Please don't take this as a ding but rather I am trying to see if can get some visibility into what your plan for future updates, etc.  I would hate for this project to go away (not saying that I will and I hope it does not)

Thank you for all your hard work

**Comment by kevin-brown** [comment]
So, I saw this ticket rolled in and didn't respond to it (and then forgot that it was marked read), so... sorry for the delay.

I actually watch the activity on Select2 relatively closely, but I can say pretty definitively that it can't be managed alone by a single person. I wake up every day to [this in my GitHub inbox](https://cloud.githubusercontent.com/assets/1991850/22388640/6be401c8-e4af-11e6-88b1-00c946a61c40.png). A lot of people don't realize the activity around Select2, and [the pulse doesn't lie](https://github.com/select2/select2/pulse): getting 10 new tickets in a week is not unheard of.

> You mentioned somewhere that the project is not dead but rather in a slow release cycle.

Yup, I still stand by that.

> Is this due to your schedule?

Yes.

> If so, would you be willing to assign a couple of project maintainers (seek for volunteers) that would carry your vision forward.

I've extended the offer quite a few times, and from time to time someone agrees to join on. Triaging tickets is a problem of scale ("many hands make light work"), maintaining the code base is a problem of time and patience.

So, I ask you (and the many others reading this): are you interested in helping out with Select2?

**Comment by Cliff904** [comment]
I'm willing to help out and contribute to select2

**Comment by irobayna** [comment]
@kevin-brown yes, I would very happy to help out

**Comment by jonahgreenthal** [comment]
Could I be of use given that I have only basic JavaScript ability (though good programming ability more generally)? I'm thinking more in an organizational sense than a development sense.

**Comment by shivamgupta001** [comment]
@kevin-brown I would love to work , though more on development side. Was using select2 for past six months for a company project , overriding is easy with select2[ lot of power ]. Was able to put checkboxes after a day effort - 
http://htmlpreview.github.io/?https://github.com/shivamgupta001/select2multiple/blob/master/select2.html

But would love to see more enhancements from project side, overriding has its limitations.

**Comment by kevin-brown** [comment]
I tried to hunt down email addresses, but that wasn't proving particularly fruitful.

For those interested, can you send me an email at select2+github@kevin-brown.com and we can chat about what you're interested in helping with.

**Comment by alexweissman** [comment]
Just my two cents but - with my project at least - having an active chat room has helped us immensely in building an active community of contributors.  Whenever I sign in to #select2 in freenode IRC I notice that there isn't much activity, and a complete absence of the project's creator!  This gives the feeling (even if it's not true) that select2 isn't an active project.

If IRC isn't working out for you, have you considered using Gitter, or even setting up a dedicated chat server with Rocket?  You could easily set up a donations page to solicit the funds needed to maintain a chat server.

I'd also suggest a standalone server for documentation, so you're not limited by Github Pages and the Jekyll engine.  Again, a donations page would easily cover this expense!

**Comment by ajcastro** [comment]
Slack chat is good! I suggest using it. Do we have a slack chat for this already?

**Comment by penihel** [comment]
I want to help too. Count on me

**Comment by alexweissman** [comment]
At the very least, this is an issue that I can close :-)  Let's continue the discussion about "is Select2 abandoned, future of this project, etc" in #4953.
