### ISSUE TITLE
Sorting does not apply to selected options

### ISSUE THREAD

**Issue by rbu** [select2/select2#4769]
## Steps to reproduce the issue
1. Create a list with unsorted options
2. Define an alphabetical sorter for options
3. Review selected options

## Expected behavior and actual behavior

When I follow those steps, I see that options in the dropdown are sorted, but selected options are not.

I was expecting both dropdown options and selected options to be sorted.

## Environment

Libraries

- jQuery version: 1.10.2
- Select2 version: 4.0.3

## Isolating the problem

- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/makelimiwa/edit?html,output)

![ylonacj55b](https://cloud.githubusercontent.com/assets/65913/22434803/de0c0adc-e71d-11e6-84f4-047b18a2261f.png)

**Comment by alexweissman** [comment]
This is related to both #4694 and #3106.  Basically, the questions are:

1. Should selected options should always be displayed in the order in which they were selected?  Should this be configurable?
2. Should the `sorter` callback be coupled to the selections as well?  Or perhaps, like `templateResult` and `templateSelection`, we should have `sortResult` and `sortSelection` callbacks.

**Comment by alexweissman** [comment]
Please continue the conversation in #3106.
