### ISSUE TITLE
Hide feature of Search but rather show all results 

### ISSUE THREAD

**Issue by djangobotpython** [select2/select2#4770]
Hi  folks

Awesome library I must say. I have a very vague requirement for UX/UI. I know this might sound wierd but can it be possible ? 

I am using select2 type Loading Remote data. I make an ajax call return the data. Now the core feature is based on data that we return(from server) we need to type some characters in the search box and it display the results(based on minimum input length).

What i want, if the search is not matching the criteria(any characters not matching in the returned data) i want to populate everything which i returned from the server. 

Example:- my dataset which i returned is [{'id': 1, 'name': 'one', 'id': 2, 'name': 'two'}]
Now when i type special characters  . , & the search criteria does not match but still i want to populate the results one , two. 

Can this be possible ? 

Thanks

**Comment by jpic** [comment]
Did you try using character entities such as `&amp;` ?

https://dev.w3.org/html5/html-author/charref

**Comment by alexweissman** [comment]
This is something you need to handle with some logic in your server-side code.  Select2 cannot do this for you.

Another possibility would be, if we implemented #4906, to fire a second AJAX request that retrieves the "full" list whenever the filtered results are empty.  But for now, this is not possible.
