### ISSUE TITLE
Select2 not disable over form modal

### ISSUE THREAD

**Issue by manuelcalerosolis** [select2/select2#4771]
## Prerequisites

![image](https://cloud.githubusercontent.com/assets/3088246/22507611/a4552cf0-e886-11e6-98fd-defee32ae512.png)

The control not put disable, like the other controls.

This is a multiselect Select2

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [*] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [*] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.0/jquery-ui.min.js
- Select2 version:4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [*] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by jpic** [comment]
Hi, could you show how a fix would look like or try to provide more information ?

**Comment by manuelcalerosolis** [comment]
If I open a modal window on my web, "select2" is not disabled like the rest of the controls.

regards

**Comment by CodebyRay** [comment]
I am having the same issue as above. Is there a fix for this issue?

**Comment by alexweissman** [comment]
Why do you expect the controls to be disabled?  Do they have the `disabled` attribute?  See https://select2.org/appearance#disabling-a-select2-control

**Comment by alexweissman** [comment]
No jsbin that demonstrates this issue, so I am closing it.
