### ISSUE TITLE
select2 used within <form> tag brings up native select options on iOS

### ISSUE THREAD

**Issue by MildTomato** [select2/select2#4772]
## Prerequisites

The issue still exists against the latest `master` branch of Select2

## Steps to reproduce the issue

1. Use select2 on a `<select>` within a `<form>` tag
2. Open in either Safari or Chrome (v 55.0.2883.79) on iOS 10.2

## Expected behavior and actual behavior

Click on select2 `<select>` and native select picker is displayed as well as the select2 dropdown.

Clicking on one of the native picker options means that the select2 dropdown remains open even though an option has been selected. If I was to ignore the native picker and just select an option from the custom select2 dropdown then the option is selected and both select pickers are dismissed.

I was expecting... there to not be a native picker, instead having the select2 dropdown override the native one.

The issue only happens when `<select>` is inside a `<form>`

## Environment

Browsers

 Safari or Chrome (v 55.0.2883.79) on iOS 10.2

Operating System

Mobile
iOS 10.2

Libraries

- jQuery version: 2.2.2
- Select2 version: 4.0.3

## Isolating the problem

Haven't figured out a good way to isolate the problem, as it's on iOS. Could probably do it in JSBin and then load it on mobile...

![image-uploaded-from-ios](https://cloud.githubusercontent.com/assets/8291514/22519187/5c07dec2-e8a7-11e6-935e-d3a020b3f123.jpg)

**Comment by awalias** [comment]
it's not a problem that the ios menu shows, just that the other menu doesn't close when the ios one does

**Comment by kamlekar** [comment]
Guys, any update on this? I have the same problem.

**Comment by MildTomato** [comment]
we've disabled it on mobile devices for now.

```
// Destroy select2 if mobile device
        if ( /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) ) {
          $("select").select2('destroy');
        }
``

**Comment by kamlekar** [comment]
@MildTomato Thanks for that tip!! I think the better alternative would be to apply select2 only if the userAgent is not of the mentioned devices.

**Comment by MildTomato** [comment]
@kamlekar oh yea! good point. Don't know why I didn't think of that.

**Comment by aguy0612** [comment]
Im assuming there isnt a fix for this yet.  Up above it says that this only occurs if select2 is within the form.  Is there a way to take the select 2 out of the form?

here is where I have Select 2 -
   function Init(){
 
                     //Initialization function. Tells SF which Query String Variable
                     //has the ID of the form, and the name of the list to read data from
                     $("#clientEngRequest").StratusFormsInitialize({
                                queryStringVar: "0",
                                listName: "clientEngRequest",
                                completefunc: function() { 
                                    $('.select2 span').addClass('needsclick');
                                    $('#city').select2({tags:true});
                                    $('#state').select2({tags:true});
                                    $('#GMContact').select2({tags:true});
                                    $('#Office').select2({tags:true});
                                    $('#EngManager').select2({tags:true});
                                    $('#BDMManager').select2({tags:true});
                                    $('#BU').select2({tags:true});
                                    $('#CSMIssued').select2({tags:true});   
                                }
 
                     });
 
 
                               $("div.ms-cui-tabContainer").hide();

**Comment by warudin** [comment]
In my case I really need select2 to work, so destroying it is not an option. I need the iOS picker not to appear at all. I thought maybe this would work, but it's not.

```
jQuery(document).on('select2:open', function(e) {
	document.activeElement.blur();
});
```

**Comment by alexweissman** [comment]
It's worth noting that Apple's guidelines recommend against the native picker interface for longer lists: https://developer.apple.com/ios/human-interface-guidelines/controls/pickers/

So, this would seem to suggest that you should actually _prefer_ Select2 over the native picker.

In that case, it might be better to suppress the native picker with `readonly` on the `<select>` element - can someone confirm whether this works, and still permits the Select2 control itself to be used?

**Comment by miguelesquirol** [comment]
The solution is so stupid that made me mad...

Just add:

`select {
  visibility: hidden;
}`

**Comment by elieux** [comment]
Thanks, @miguelesquirol, that worked.

Or even better yet: `select.select2-hidden-accessible { visibility: hidden; }` This should probably be included in default styles, with an appropriate comment.

**Comment by cecilevarin** [comment]
The solution suggested by @miguelesquirol and @elieux indeed remove the picker however it prevents the creation of new options originally enabled thanks to `tags: true` select2 option. 
Does anyone have a solution to enable tagging on iOS including option to create new tags? 
Thanks!

**Comment by jdleonard** [comment]
This is still a problem in 4.0.5

**Comment by PWalkow** [comment]
Yes, still a problem, any chance to see it fixed?

**Comment by zapaza** [comment]
I fixed the error by adding styles to select
`form select {
  display: none !important;
  pointer-events: none;
}`

**Comment by waqas4346** [comment]
I think the best workaround is to use `select2:opening` and `select2:closing` events to show/hide the select.

Example code:
```
$('select2-selector').on('select2:opening', function (e) {
  $('select').attr("style", "display: none !important");
});

$('select2-selector').on('select2:closing', function (e) {
  $('select').attr("style", "display: block !important");
});
```

**Comment by Merlin-1D** [comment]
It would be great to have a solution in the plugin by default
