### ISSUE TITLE
Select not showing search

### ISSUE THREAD

**Issue by dontuta** [select2/select2#4773]
Hi, I added select2 to a project but my select tag still looks like a normal select. Even the search funcionality is not present. The css and the js files paths are correctly

Does anyone has any idea?

Thanks!

**Comment by William-H-M** [comment]
Hi, how are you initializing the select2 plugin or do you have aby fiddle where we can watch what is going on?

**Comment by dontuta** [comment]
Hi William, 
Acctually my problem was with the JQuery version I was using. Things are working now. Thanks!

**Comment by William-H-M** [comment]
Hi Dontuta, 
That's great!, now as this is solved please close de the issue.
Have a nice day coding :)

**Comment by dontuta** [comment]
Oops, sorry, forgot to close =P
