### ISSUE TITLE
Why tag has no title (Ajax)?

### ISSUE THREAD

**Issue by afuno** [select2/select2#4775]
The field of the form:
```ruby
= f.collection_select :tag_ids, Tag.all, :id, :title, {}, class: 'form-control', id: 'js-tags-ajax', multiple: true
```

CoffeeScript:
```coffeescript
$('#js-tags-ajax').select2
	placeholder: "Select the tags"
	minimumInputLength: 3
	ajax:
		url: '/ajax/element_bases/json_s2_tags'
		dataType: 'json'
		delay: 200
		data: (params) ->
		{
			q: params.term
		}
		processResults: (data, params) ->
		{
			results: data.results
		}
	templateResult: (result) -> result.title
	templateSelection: (result) -> result.text
```

If you load the page and select a tag, it will be displayed normally. The name of the tag will be.

But if you do the following steps:

1. Add a tag to the table.
2. Not updating the page enter the tag name in the field.

You can get the tag in the list: ![Screenshot](https://habrastorage.org/files/e10/9b9/755/e109b9755fcd4f6dbcac001856f8fa0b.png)

But as soon as you select it, you will receive the following: ![Screenshot](https://habrastorage.org/files/fc2/521/a95/fc2521a959cb44c299a195e015e15d8f.png)

What is the problem? In your documentation, I could not find a normal working example.

**Comment by jpic** [comment]
I've had some similar bugs too, did you manage to make a fix ?

**Comment by alexweissman** [comment]
This appears to be the same issue as #4880, probably due to having an empty `<option>` in your `<select>`.
