### ISSUE TITLE
Automatic tokenization with tags enabled has problems in IE browser when adding a new element

### ISSUE THREAD

**Issue by FloraLuca** [select2/select2#4778]
## About the issue

I try to use the newest select2 v4.0.3 library in a web page. I used the given example on this page for tagging and tokenization. I tested it in different browsers. It works fine, but in Internet Explorer v.11 it behaves strangely:

I tried to add a new element which was not among the options. After typing a few characters, the cursor was taken away and I was not able to finish the word I was typing in. When I clicked into the select box to gain back the cursor, the half-entered word disappeared. So it seems to be impossible to type in more then 3-4 characters. I experienced the same on select2.github.io/examples page when opening it in IE.
[see question on stackoverflow](http://stackoverflow.com/questions/42034740/select2-tags-limit-input-characters-in-ie-browser)

## Steps to reproduce the issue

1. Test select2 with the simpliest way according to the examples. Set tags and tokens. I used the following code:
```
<html>
<head>
    <link rel="stylesheet" href="css/select2.css" type="text/css" />
    <script src="js/jquery-2.1.0.js" type="text/javascript"></script>
    <script src="js/select2.full.js" type="text/javascript"></script>
</head>
<body>
    <script type="text/javascript">
    $(document).ready(function() {
        $(".js-example-tokenizer").select2({
          tags: true,
          tokenSeparators: [',', ' ']
        });
    });
    </script>
    <select class="js-example-tokenizer" multiple="multiple" style="width: 600px;">
      <option value="AL">Alabama</option>
      <option value="WY">Wyoming</option>
    </select>
</body>
</html>
```
2. Open page in IE
3. Try to add something to the list that is not among the options.

## Expected behavior and actual behavior

Expected: The input lets me enter the word I want to add
Result:  Caret is randomly taken away after 3-4 characters, cannot enter a longer word.

## Environment

Browsers

- [ ] Google Chrome - Working fine
- [ ] Mozilla Firefox - Working fine
- [x] Internet Explorer v11. - BUGGY!!!!

Operating System

-  Windows 10

Libraries

- jQuery version: jquery-2.1.0.js
- Select2 version: select2 v4.0.3

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html) at 'Automatic tokenization' section
- [x] The bug happens just in IE browser
- [x] This bug happens when using Select2 without other pluigns

**Comment by SebSob** [comment]
@FloraLuca I am having the same problem, have you found any solutions you are willing to share ?

**Comment by SebSob** [comment]
@FloraLuca reverting to 4.0.2 worked for me.

**Comment by FloraLuca** [comment]
@SebSob No, i tried a lot of different things but didn't find any solution. But if it worked with the earlier version, it means that this bug was introduced lately. 
Thanks for the info!

**Comment by sophiahawes** [comment]
Is anyone going to address this issue? We just encountered it as well in our project.

**Comment by sebpet** [comment]
Any news here? Is anyone going to address this issue?

**Comment by FloraLuca** [comment]
@sebpet I raised the issue on SO at the same time I opened this ticket, and recently got an answer with a good workaround: [see here](https://stackoverflow.com/a/52684063/5757830)
