### ISSUE TITLE
Select2 SearchBox displaces to far left corner in IE9-11

### ISSUE THREAD

**Issue by Eager-Learner** [select2/select2#4780]
The search button on the link http://demo.openatrium.com/sitemap#/  opens drop-down in the far left corner in Internet Explorer 9. Kindly see the attached screenshot.
The drop down links do not work in this case. When open atrium is deployed on local machine, the same issue occurs.
The Interface is working fine in Chrome and Firefox. The problem seems to be with select2 jQuery library.
Has someone faced a similar issue?
@select2 @OpenAtrium @kevin-brown

![openatrium_sitemap_error](https://cloud.githubusercontent.com/assets/22636940/22734301/fd27267c-ee16-11e6-98a2-e1687b494b1d.PNG)

**Comment by alexweissman** [comment]
Have you tried changing the `dropdownParent`?  See https://select2.org/dropdown#dropdown-placement

**Comment by alexweissman** [comment]
Please feel free to comment if you have any more insight, and we can reopen the issue.
