### ISSUE TITLE
Unable to reset values of multiple valued dropdowns prgrammatically

### ISSUE THREAD

**Issue by jchircop** [select2/select2#4782]
Select2  v4.0.3

I am currently clicking on a button to reset all multiple dropdowns. 

$('.select2Multiple').each(function (index, element) {

                           $(element).val([]).trigger("change");
                           $(element).val([]).trigger("change.select2");
                           $(element).val(null).trigger("change");
                           $(element).val(null).trigger("change.select2");             
                           $(element).val('').trigger("change");
                           $(element).val('').trigger("change.select2");      
 });

No instance of the above worked. The dropdowns remained with their value intact. I consulted several threads with multiple solutions yet none seems to work. Does the jQuery version affect this in any way?

I really need this for a current project, we were using the v3.5 before and it was working splendidly. Can anyone help me with this?

**Comment by William-H-M** [comment]
Hi there, mm not sure whats wrong I've used your script and is working for me even with a JQuery 1.11.2 fro an older fiddle of this elder issue #4749 so I'll leave this fiddle here updated maybe you overlooked something here the [fiddle](https://jsfiddle.net/205rfqmt/4/)

If anything goes wrong let us see a snipppet of your code after all a few eyes are better than two Good luck :)
