### ISSUE TITLE
Position static option similar to https://chmln.github.io/flatpickr/

### ISSUE THREAD

**Issue by iammary** [select2/select2#4783]
Is it possible to add a static positioning option it select2 args?

Same with [flatpickr](https://chmln.github.io/flatpickr/#options):

static | boolean | false | Position the calendar inside the wrapper and next to the input element. (Leave false unless you know what you're doing.)

Nice to have an option to have the dropdown use either **attachContainer** or **attachBody** to avoid changing of core js.

**Comment by pedrofurtado** [comment]
We dont have immediate plans to this. But if you open PR with unit tests, I will be glad to review that :+1:
