### ISSUE TITLE
Tags case sensitivity

### ISSUE THREAD

**Issue by loshose** [select2/select2#4784]
Well the problem is again with tags and case sensitivity. Select2 allows inserting tags with different cases, where (at least in my opinion) it should not allow it. If a list has a "purple" tag the user should not be able to add "PURPLE", "PuRPLe" and so on. Granted I now have to manually choose to input the duplicate tag by pressing UP on the keyboard, which makes it a little bit harder but not impossible, which is what I'd like to achieve.

This is the old bug report from 2015 july: https://github.com/select2/select2/issues/3566

In any case it's still possible to input duplicate tags:
![Example image of duplicate tags](https://i.snag.gy/bdDNaB.jpg)

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to https://select2.github.io/examples.html#tags
2. Input PURPLE
3. Press UP and ENTER
4. Input PuRPLe
5. Press UP and ENTER
6. Etc.

## Expected behavior and actual behavior

When I follow those steps, I see that the duplicate tags are being added to the list.

I was expecting Select2 to limit me from inputing duplicate tags.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: The one on the examples page
- Select2 version: The one on the examples page

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other pluigns
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
It looks like this issue was actually fixed in https://github.com/select2/select2/commit/cb9a90457867ffb14c7b1550bb67e872e0a5c2dd, but it just hasn't made it into a release yet.  I'm trying to get a new release out ASAP (and tighten the overall release cycle), so I would say that this issue is resolved.
