### ISSUE TITLE
How can I set value to a select2 with ajax

### ISSUE THREAD

**Issue by JianiYang** [select2/select2#4788]
$(".js-data-example-ajax").select2({
					minimumInputLength : 1,
					ajax : {						
						url : "/storyapp/rest/getw3forlist",
						type : 'GET',
						dataType : 'json',
						delay : 250,						
						data : function(params) {
							return {
								term : params.term,
							};
						},
						processResults : function(data, params) {
				                return {
				                    results: data.rows ,
				                };
				                cache: true
						},
						templateSelection:  function(data){return data.id},// 显示选中的对象				
					},										
				})

and I use
$("#assignee").val(value);
$("#assignee").change();
but not useful

**Comment by JianiYang** [comment]
And another question , my templateSelection's function also not useful

**Comment by alexweissman** [comment]
This is now documented here: https://select2.org/programmatic-control/add-select-clear-items
