### ISSUE TITLE
Upgrade from 3.5.4 to 4.0.* causes continous page refresh

### ISSUE THREAD

**Issue by krokodylowy** [select2/select2#4789]
## Prerequisites

- [y] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [y] The issue still exists against the latest `master` branch of Select2
- [n] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [yn] I have attempted to find the simplest possible steps to reproduce the issue
- [n] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Upgrade select2 from 3.5.4 to 4.0.*
2. Attach to page many select boxes (10 or much more)  with ajax sources

## Expected behavior and actual behavior
Actual behavior - navigation across pages with multiple select2 causes continous page refresh on some pages.
I cannot find root cause of this problem. Some pages with less number of combos are ok.
Profiling doesn't help and doesn't show which part of code start page refresh. 
Disabling of select2 initiation helps but this is no sulution.
Our code is too complex to make an example.
Is any better way to detect which part of select2 code is responsible for this behavior?

## Environment
IE,FF,Chrome

Operating System
- [x ] Windows , another not verified

- jQuery version: 2.2
- Select2 version: 4.0.*

- [ n] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other pluigns
- [n ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
Were you ever able to solve this problem?  It seems unlikely that Select2 itself would be triggering any page refreshes.

**Comment by krokodylowy** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Hi
 
I have no idea. I abandoned this component.  Next version was better but not backward compatibileFrom my point of view its to complex and frequent reflow is standard if you put select on javascript tables with resizing.
 
Dnia Niedziela, 24 Września 2017 19:06 Alex Weissman <notifications@github.com> napisał(a)

Were you ever able to solve this problem? It seems unlikely that Select2 itself would be triggering any page refreshes.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
 
// <![CDATA[
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/select2/select2","title":"select2/select2","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in 
GitHub","url":"https://github.com/select2/select2"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alexweissman in #4789: Were you ever able to solve this problem?  It seems unlikely that Select2 itself would be triggering any page refreshes."}],"action":{"name":"View Issue","url":"https://github.com/select2/select2/issues/4789#issuecomment-331724028"}}}
// ]]>

**Comment by alexweissman** [comment]
Ok, thanks for getting back to me!
