### ISSUE TITLE
The cursor acting wird when i open multiple select2 in the same page

### ISSUE THREAD

**Issue by linkstops** [select2/select2#4791]
i'm using select2 v3.4.8 coz i'm using angular ui.select, So when i open two select2 or more in the same time the cursor refreshing wirdly and the page go to down(footer),
Could someone help me out how to force select2 to close automaticly  when i open another one, or how to stop that wird acting or cursor when multiple select 2 are opened in the same page.

**Comment by alexweissman** [comment]
Unfortunately without a working demonstration (http://jsbin.com), we cannot provide any support for this issue.  Please create a working demonstration and we can reopen this issue.
