### ISSUE TITLE
Require("select2") in 4.0.3 not working anymore

### ISSUE THREAD

**Issue by Borming** [select2/select2#4796]
Hi all,

I am using 4.0.2 version and i upgraded using NPM to 4.0.3 yestarday. I am now getting an error "Select2 is not a function..."  which means Select2 is probably not attached to Jquery. 

I didnt look at the source to check whats wrong but obviously require() is broken in 4.0.3. 

Temp fix : Reverting back to 4.0.2

**Comment by soundasleep** [comment]
I've found you need to call `require` for select2 like so:

```javascript
$ = require('jquery');
select2 = require('select2')(); // note you're calling a function here!
```

**Comment by alexweissman** [comment]
See https://github.com/select2/select2/commit/45a877345482956021161203ac789c25f40a7d5e#commitcomment-24593031 and the [jQuery plugin boilerplate](https://github.com/umdjs/umd/blob/master/templates/jqueryPlugin.js) for an explanation.

**Comment by adamreisnz** [comment]
Or when using imports:

```js
import $ from 'jquery';
import select2 from 'select2';

select2($); //<-- necessary to get it to work
```

**Comment by dangvanthanh** [comment]
Hi @adamreisnz 

Working is charm. Thank you very much.

**Comment by luisgjb** [comment]
> Or when using imports:
> 
> ```js
> import $ from 'jquery';
> import select2 from 'select2';
> 
> select2($); //<-- necessary to get it to work
> ```
Utils.GetUniqueElementId = function (element)
Throws me Uncaught TypeError: Cannot read property 'getAttribute' of undefined

**Comment by powerbuoy** [comment]
Took me ages to find this but thank you. This should definitely be in the docs under installation instructions.

**Comment by jlherren** [comment]
WTF... Why such a breaking change in a point release? Why no mention whatsoever on the installation page?
