### ISSUE TITLE
AllowClear is not working on single entry select combo

### ISSUE THREAD

**Issue by revatiy26** [select2/select2#4798]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.Use select2 with multiple = true and allowClear = true you will not face any issue in clearing entries from select combo
2.Use select with only allowClear = true you will not be able to clear entry from your select combo
3.Try again step 1 and you will see you will be able to clear entries.

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows 
- [ ] Mac OS X

- [ ] Linux
- [ ] Mobile
Libraries

- Select2 version:4.0.3

**Comment by William-H-M** [comment]
Hi, Even when with multiple select this do a clear this throw an exception 'TypeError: this.placeholder is undefined' the same for a normal select but on a normal select this do nothing because of the error

so the solution is just to set the option `placeholder:true` and that's you don't even have to put an empty value for this to work.

Good luck!

**Comment by revatiy26** [comment]
It was throwing exception in both the case but with multiple option clear functionality was working .
Thanks! Works perfectly.

**Comment by alexweissman** [comment]
So, you're saying that you need to have the `placeholder` option set in order to use `allowClear`?  Hmm, that doesn't seem right...

**Comment by alexweissman** [comment]
The solution to this is described in #3497.  So, this is a duplicate.
