### ISSUE TITLE
Vietnamese character Ð not matching with D

### ISSUE THREAD

**Issue by coudrak** [select2/select2#4800]
1. A select with an option with Ð or đ (for example Ðắc Lắk or Ðà Nẵng)
2. Search with "D..." or "d..." (for example Dac Lak)

Version 4.0.3 / Chrome, Firefox...

When I follow those steps, no result because the characters D and d don't match with Ð and đ.
All other Vietnamese characters work ("ac Lak" or "à Nẵng" works).
You can try on this website : https://www.bannhay.vn/ the second select on the right.

**Comment by William-H-M** [comment]
Hi, that's weird rigth now it's working for me work either with D or Ð at least you tried something.
![captura de pantalla 27](https://cloud.githubusercontent.com/assets/24443241/23075763/acdb60ec-f50b-11e6-9247-e6ac3b23bc05.png)

![captura de pantalla 28](https://cloud.githubusercontent.com/assets/24443241/23075761/acd80e38-f50b-11e6-8978-88803cf9e7ae.png)

**Comment by coudrak** [comment]
Indeed, I worked only for the field "Đắk Nông" but not other ones.
I just copied/pasted the "Đ" from "Đắk Nông" to other fields in the MySQL table (Ðắc Lắk, Ðà Nẵng...) and it works now!
I don't explain why there is a good Đ and a bad Đ, but the problem is solved for me, thanks!
