### ISSUE TITLE
can't set value programmatically for single select2

### ISSUE THREAD

**Issue by arathra** [select2/select2#4801]
I use select2 in the wordpress ACF plugin. After a lot of trial and error I managed to set a value for a MULTIPLE select list programatically:

$('#mymultiplelist-input').select2("data", [{id: var1, text: var2}]);

However, I can't set the value for a SINGLE select list. For example, this doesn't work:

$('#mysinglelist-input').select2("data", [{id: var1, text: var2}]);

Nor does this:

$('#mysinglelist-input').val(var1).trigger("change");

Is there something I'm missing here? Thanks.

**Comment by William-H-M** [comment]
Hi, you just gotta do an append to the select itself and the update slect2
like what I've done in this [fiddle ](https://jsfiddle.net/5y39582a/), this one has JQuery 1.11.2 in there but I think it doesn't matter the version just try it if any error ocurs just tell 
Good luck!

**Comment by arathra** [comment]
Well, it took me bloody AGES to find the answer.

This clears the current (default) selection but doesn't put anything in its place
$('#s2id_acf-field_554f18ecbf60c-input').select2("data", [{id: "Spain", text: "Spain"}]);

But if I remove the square brackets at the end it works:
$('#s2id_acf-field_554f18ecbf60c-input').select2("data", {id: "Spain", text: "Spain"});

Such a small thing!

**Comment by alexweissman** [comment]
This is now documented: https://select2.org/programmatic-control/add-select-clear-items

Glad you were able to find your bug.

**Comment by tijokj** [comment]
var _dataVals = $("#ddlName").select2('data')[0];
//console.log(_dataVals);
console.log(_dataVals.element.dataset['empid']);
console.log(_dataVals.element.dataset['bu']);
console.log(_dataVals.element.dataset['designation']);
