### ISSUE TITLE
cannot add tag that is a substring of existing tag

### ISSUE THREAD

**Issue by jgabriels** [select2/select2#4805]
## Prerequisites

- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of Select2
- [ X] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.  Add the tag 'this'
2.  Try to add the tag 'is'
3.  It fails because 'is' is a substring of 'this'.

## Expected behavior and actual behavior

When I follow those steps, I see...

The tag 'is' fails to add.

I was expecting...

The tag 'this' and the tag 'is'
## Environment

Browsers

- [ ] Google Chrome
- [ X] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ X] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ X] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ X] The bug happens consistently across all tested browsers
- [ X] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by William-H-M** [comment]
It's weird for me it's working like usual even with data, so not sure what could be your problem I'm using Select2 V. 4.0.3 and JQuery 2.2.3 At [the fiddle](https://jsfiddle.net/Lauhs4bm/1/) is working for me, maybe a snippet of your code will show something else

**Comment by jgabriels** [comment]
Your fiddle doesn't work for me on either firefox or chrome.
I type 'this' and hit enter and then 'is' and hit enter and the 'is' never appears.
I am able to select 'is' from the dropdown though.

**Comment by jgabriels** [comment]
Your fiddle doesn't work for me on either firefox or chrome.
I type 'this' and hit enter and then 'is' and hit enter and the 'is' never appears.
I am able to select 'is' from the dropdown though.
It is also broke on this page:  https://select2.github.io/examples.html#tags

**Comment by William-H-M** [comment]
Ohh so you mean with Enter I thought you mean with the space or comma ',', because that's the way it's working for me right now. I'll look later for more documents about this, for now this should be labeled as a Bug

**Comment by William-H-M** [comment]
Hi @jgabriels I think I got it now the explenation is given by @kevin-brown at this issue #4093 the thing is that when you type he would look for the best coincidence an din this case "this" is the closet one but if you just type a space or a comma he will tag it, the other one is just select it with a click and will work I just tested it out and it does work either with the fiddle I gave earlier or with the one given by Kevin.

**Comment by jgabriels** [comment]
Awesome.  Thanks.  Yes, it looks to be a duplicate of that bug.
The patch https://github.com/select2/select2/pull/4622  fixed the problem.
