### ISSUE TITLE
Incomplete documentation

### ISSUE THREAD

**Issue by reidbiztech** [select2/select2#4806]
You wrote it, you document it. That's how it works.

You want me to analyse your code and document it for you? Not gonna happen.

**Comment by William-H-M** [comment]
Is this for real? Most of events, options, and examples are documented at https://select2.github.io/
And he's not asking you to document the code or anybody...

**Comment by reidbiztech** [comment]
Example:
https://select2.github.io/options.html#does-select2-include-extra-information-in-these-events

it used, but it does not anymore.

Look through the docs... there are **26** instances of:

> This answer to this question has not yet been written. You can improve this documentation by creating a pull request with an answer to this question.

So yes, this is for real.

**Comment by jonahgreenthal** [comment]
"You can", not "You should" or "Would you please", so you are not, in fact, being asked to analyze Select2's code and document it for "you" (whatever "you" may be).

It's reasonable to think this project should be more documented. Most of us do, including — I believe — its primary contributor(s). It's not reasonable to say "You wrote it, you document it. That's how it works." because (a) that's not, in fact, how it works; providers of free software can provide as much or as little documentation as they desire; and (b) it's incredibly rude and demanding.

**Comment by reidbiztech** [comment]
Yes, rude and demanding, acknowledged, but only because I have to deal with the new version being included in WooCommerce.

Skip the lectures, I know how oss works. Just because it is oss is no excuse to provide a broken product, then expect others to fix and document it for you. Not me. I have to make a living. I have no time for that.

I think I am just going to not use the select2 bundled in WooCommerce and move to chosen and include it in my extension so I am not trapped into this.

**Comment by William-H-M** [comment]
So for this you need to demand for this and say to everyone? You could 
1) Just do it for yourself the documentation 
or
2) Just move out to Chosen without need it to do this and do an totally unnecesary issue

**Comment by jonahgreenthal** [comment]
> Skip the lectures,

When you skip being rude and demanding!

> Just because it is oss is no excuse to provide a broken product, then expect others to fix and document it for you. 

No one is doing that. They are simply pointing out that contributing in that way is *a possibility*.

> I have to make a living. I have no time for that.

This is exactly the reason the documentation isn't as complete as it should be!

> I think I am just going to not use the select2 bundled in WooCommerce and move to chosen and include it in my extension so I am not trapped into this.

Great; do that and there's no need to whine over here.

**Comment by reidbiztech** [comment]
The issue is necessary. The change event no longer contains the value of the select, and the option elements in the dom marked as selected.

Select2 4.0.3 is broken and unusable.

I will do that, I have no time for undocumented and broken software.

**Comment by jpic** [comment]
Bitching open source software maintainers ? Shame on you ;)

**Comment by jpic** [comment]
Just use whatever works for you, that's how Open Source works.

If you want to contribute, please make a pull request ;)
