### ISSUE TITLE
What data is provided by events?

### ISSUE THREAD

**Issue by sanity** [select2/select2#4807]
Hi all, thanks for your great work on Select2.  I'm working on a select2 plugin for the [kweb](https://github.com/sanity/kweb) framework.

I'm trying to figure out what extra information is provided by select2 to events.  Specifically it would be useful if the selected item(s) were provided.  

Looks like the [documentation](https://select2.github.io/options.html#does-select2-include-extra-information-in-these-events) for this is not yet written, I tried splunking through the source code but couldn't find the relevant part.

If someone can point me in the right direction I'd greatly appreciate it.

**Comment by alexweissman** [comment]
@sanity does this help: https://select2.org/programmatic-control/events#event-data ?

**Comment by alexweissman** [comment]
Please let us know if you think there is anything that could added to this documentation.
