### ISSUE TITLE
When default/preselected options are replaced by options from a remote source, additional `data` properties are lost

### ISSUE THREAD

**Issue by jcagarcia** [select2/select2#4808]
I'm using a `select2` component in a create form. The `select2` component has been configured to load all the data using ajax. Also, I've customized my JSON response from the server to include an extra object (not only `id` and `text`) into the `option` data.  This is my JSON response:

````
{
  "pagination" : {
    "more" : false
  },
  "results" : [ {
    "id" : "1",
    "text" : "My name",
    "info" : {
      "id" : 1,
      "name" : "My name",
      "lastName" : "My lastName"
    }
  }, {
    "id" : "2",
    "text" : "My name 2",
    "info" : {
      "id" : 2,
      "name" : "My name 2",
      "lastName" : "My lastName"
    }
  }]
}
````

The info object will be used to show another field depending of the `lastName` value of the selected record.

When I select some record in the select component, a new `option` html element is created inside. If I inspect that option using `$("#selectId option[val=1]").data().data` I obtained the following object:

````
_resultId:"select2-allowedEntities-result-uedo-1"
disabled:false
element:option
id:"1"
info: Object
selected:false
text: "My name"
````

It contains the info element! That's great!! I'm able to do `$("select").select2("data")` and obtain the `lastName` value.

However, in an edit form where I have a preloaded `option` element because it has been loaded from the database , the option element doesn't contains the info object. 

This is ok because I'm not making the AJAX call that includes that extra information, but, here's is the problem:

If i change the selected option, a new option html element it's been created inside the select element. That one contains the `info` extra object. If after that, I select the initial selected option again, a new option element **is not beeing included** or the existing one **is not beeing replaced/updated**.

Would be great that the select2 prevent to include existing options **only** if the id is the same and if the data element is the same. If the value already exists but the data have been changed, replace it to prevent this.

I think that maybe here could be the issue https://github.com/select2/select2/blob/master/dist/js/select2.full.js#L3338

Regards,

**Comment by alexweissman** [comment]
Possibly related to/complements the issue in #5036.
