### ISSUE TITLE
Page Scrolls On Initial Click of Select2 element

### ISSUE THREAD

**Issue by BillFilterEasy** [select2/select2#4810]
## Prerequisites

- [yes] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [yes] The issue still exists against the latest `master` branch of Select2
- [yes] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [yes] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. I have 24 select2 elements on my page (i know its a lot, but a possible layout for me)
2. Clicking on any of the elements farther down the page (14 - 24) causes the page to jump up a certain amount.  For me it is about 500px or so.
3. I can scroll back down to see the drop down visible and that part will work as expected, but clicking on any other element near it will result in the page scrolling up again.

## Expected behavior and actual behavior

When I follow those steps, I see... the page instantly scroll up about 500px. I can scroll back down to see the drop down list is positioned correctly, but the initial scrolling up of the page is a problem for me.

I was expecting... the page to not scroll at all when i click on the select2 element.

## Environment

Browsers

- [yes] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [yes] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.1.1
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [not tested] The bug happens consistently across all tested browsers
- [yes] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

BEFORE I CLICK ON 'FILTER 4' - There is a whole other section above this (about 12 more select2 elements)
![screenshot](https://cloud.githubusercontent.com/assets/25303907/23290043/ecd7f5f6-fa1b-11e6-9ebb-d6aeb4cb4cb6.jpg)

AFTER I CLICKED ON 'FILTER 4' - the page scrolls up to a whole different section. Note where the scroll bar is. The original select2 element is no longer visible until i scroll down so it is back into view.
![screenshot-2](https://cloud.githubusercontent.com/assets/25303907/23290153/b3472f7c-fa1c-11e6-9283-bdce17c741a2.jpg)

**Comment by vaillancourtmax** [comment]
I'm getting the exact same behavior using 4.0.3, with two select2 instances on the page. One is a "multiple" select, the other is a "single" select. Both select2 dropdowns are below the fold, and clicking on the second dropdown bumps to page up to the top.

**Comment by maximevaillancourt** [comment]
I'm getting the exact same behavior using 4.0.3, with two select2 instances on the page. One is a "multiple" select, the other is a "single" select. Both select2 dropdowns are below the fold, and clicking on the second dropdown bumps to page up to the top.

**Comment by alexweissman** [comment]
Can you create a working demonstration of this issue in an http://jsbin.com?  Otherwise, we cannot help.

**Comment by alexweissman** [comment]
Closing, as this is now discussed more thoroughly in #5022.

**Comment by aminkariminasab** [comment]
find $dropdownContainer.remove() in select2.js and then change remove top in the manual style.

**Comment by Jigar6868** [comment]
### 

- [ ] @ #1. > [`_****_`](url)
