### ISSUE TITLE
Utils._convertData fails with empty data-attibutes

### ISSUE THREAD

**Issue by jlblcc** [select2/select2#4813]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add data attributes like this. The first example is a design pattern in some major frameworks, like Ember.
```html
<select data-foo data-foo-1>
<select data-foo data-foo--bar>
```
[https://jsfiddle.net/paot8m3g/](https://jsfiddle.net/paot8m3g/)

I monkey-patched it by just checking to make sure the dataLevel is truthy.

## Expected behavior and actual behavior

When I follow those steps, I see...

The [Utils._convertData method](https://github.com/select2/select2/blob/master/src/js/select2/utils.js#L195) throws an error.

I was expecting...

No errors

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

Libraries

- jQuery version:
- Select2 version: master(4.0.3)

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
The jsfiddle no longer seems to work at all.  Could you create a jsbin using our [template](http://jsbin.com/befamijeqo/edit?html,js,output)?
