### ISSUE TITLE
Consistant height between single and multiple select element

### ISSUE THREAD

**Issue by Alex360hd** [select2/select2#4815]
Hello,

First, congratulation to the author for this nice and useful plugin.

I'm testing it and, even if it can be easily fixed with CSS, I think it would be better to have single and multiple element of the same height. Actually, single element is smaller.

That's not pretty, especially when the 2 elements are on the same row, can be fixed using CSS but it would be even better to not be obliged to write 2 or 3 css rules to fix that each time you use this plugin.

Best regards,

**Comment by derekm** [comment]
I almost created this same bug two days ago! But I thought for sure someone has created the bug already, but I kept looking!

I'd love to help get the solution to this accepted into the codebase!

**Comment by alexweissman** [comment]
Yes, there appears to be a 4.9px difference in the default styling.
