### ISSUE TITLE
BUG !! Position of Message when drop down is above

### ISSUE THREAD

**Issue by rwx666888** [select2/select2#4816]
1. Have a select2 at the bottom of the browser where the dropdown will open above.
2. Limit the number of selections to 1.
3. Try to select again after you select the 1. The message will be way above the select because it is still using the old position and height of the dropdown.
4. I attached a screenshot of the bug from your own site. This is on all browsers on Windows.

 ![image](https://cloud.githubusercontent.com/assets/26128670/23490088/2ef20d40-ff31-11e6-9495-7f15c5beb858.png)

#4756

**Comment by alexweissman** [comment]
This bug has a working solution in https://github.com/select2/select2/issues/4614.  Closing as a duplicate.
