### ISSUE TITLE
TAB should select a result

### ISSUE THREAD

**Issue by jlrolin** [select2/select2#4820]
This was previously in issue #4578 and then closed and referred to #3472 but I do not see any code change behind it in the source.

When a user opens Select2 and TABs, can we have the result selected? TAB seems like it should select, not close.

**Comment by axelosorio** [comment]
yes we have the same problem? I tried with the events but cannot make to work.

**Comment by Copywright** [comment]
I figured out a workaround:

`
$(document).ready(function () {
    ...
    var $selects = $('select');
    if ($selects.length > 0) {
        for (var i = 0; i < $selects.length; i++) {
            $($selects[i]).parents('.form-group').attr('tabindex', '0');
        }
    }
});

`

**Comment by jlrolin** [comment]
OR... you could just add TAB to the results.select like the previous issues stated would occur.

**Comment by alexweissman** [comment]
This makes sense to me, since this is how a native Select element behaves.  It is unclear how this would translate to multi-select, however.

**Comment by ahmedali5530** [comment]
Even it does not work in official demo at [https://select2.org/getting-started/basic-usage](https://select2.org/getting-started/basic-usage)

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.

**Comment by paolobroccardo** [comment]
> We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.

Would you mind explaining why? It seems like a perfectly valid request, especially considering that normal selects work this way, and it shouldn't be a big fix to add.

**Comment by jakeNiemiec** [comment]
Paolo, see: https://github.com/select2/select2/issues/5367

**Comment by RLHawk1** [comment]
This seems like a critical problem and makes stock select2 unusable in my product. For data entry, people expect to be able to start typing, then hit tab to select the highlighted result.

**Comment by paxnovem** [comment]
I am not sure why this was originally closed. I am going to ping @kevin-brown  to get his opinion.

**Comment by kevin-brown** [comment]
I just confirmed that the behaviour of Chrome when you hit tab is to select the currently highlighted option and close. Right now we just close, but we do not select the currently highlighted option.

https://github.com/select2/select2/blob/48775d027c3e301b0bd2c4bfefbf1e1536e94cee/src/js/select2/core.js#L332-L334

Tab should behave more like the enter key rather than the esc key.

**Comment by RLHawk1** [comment]
I still very much want this.

**Comment by lindsaywebstudio** [comment]
Same. Wish selecting via tab was default functionality.

**Comment by Pagebakers** [comment]
Unfortunately the wait for this functionality is very long, users expect this to work by default.

I managed to create a workaround for it;

```
$.fn.select2.amd.define("select2/TabSelect",
  ['select2/core', 'select2/utils', 'select2/keys'],
  function(Select2, Utils, KEYS) {
    return function($el, options) {
      function TabSelect($element, options) {
        TabSelect.__super__.constructor.call(this, $element, options)
      }

      Utils.Extend(TabSelect, Select2)

      TabSelect.prototype._registerDomEvents = function() {
        this.on('keypress', (e) => {
          let key = e.which
          if (this.isOpen() && key === KEYS.TAB) {
            this.trigger('results:select', {});
          }
        })

        TabSelect.__super__._registerDomEvents.call(this)
      }

      return new TabSelect($el, options);
    }
  }
);

const TabSelect = $.fn.select2.amd.require('select2/TabSelect')

TabSelect($('select'), {/*options*/})
```

**Comment by natelowry** [comment]
check out the [selectOnClose](https://select2.org/dropdown#automatic-selection) option. it solved my issue.

[h/t KevinBrown on S/O](https://stackoverflow.com/questions/34517253/tab-doesnt-enter-with-select2#comment56815284_34517253)

**Comment by kevin-brown** [comment]
Implemented in https://github.com/select2/select2/pull/5759 to bring us more in line with standard browser behaviour.
