### ISSUE TITLE
select2('search', '') for latest version

### ISSUE THREAD

**Issue by arianjinx** [select2/select2#4822]
Hi all, I need help how to trigger clear search queries in search input like `select2('search', '')`. I can not find it in version 4.

Thank you

**Comment by sauy7** [comment]
As a workaround I have used this:

```
$('select.select2').select2(...).on('select2:select', function (e) {
    $(e.target).next('.select2-container').find('input.select2-search__field').val('');
    e.target.focus();
});
```

but I would also like to know if there is a better way.

**Comment by prirefi** [comment]
@sauy7 your workaround is clearing out the typed search result but not refreshing the options back to the original options list. Has this workaround solved this for you or am I missing anything?

**Comment by sauy7** [comment]
@prirefi You're asking 4 years after I did this, so I have no idea if my hack still works 😅
