### ISSUE TITLE
How to set  tabIndex for a select2 dropdown. It can only be set through HTML code. But if my form has dynamically created new controls, then tabindex must be changed. But right now there is no option for that. Any help will be greatly appreciated.

### ISSUE THREAD

**Issue by BIJINPALAKKAL** [select2/select2#4824]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

--<select style="width:100%;" class="form-control select2 select2-hidden-accessible" id="cmbTest"  aria-hidden="true" tabindex="21"> --

TabIndex set above remains the same for the entire session.

for a textBox ,  $('#textbox').prop('tabindex', tabIndex++) works 
But  for select2 element,   $('#cmbTest').prop('tabindex', tabIndex++) doesn't work. Even tried with DOM. Still No use.

          
## Environment 

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
