### ISSUE TITLE
Ajax doesn't call processResults even when a response is recieved

### ISSUE THREAD

**Issue by rhan-mentad** [select2/select2#4825]
Because Django sucks and requires form data for post, and due to various other reasons, we need to forward requests to a single endpoint with more data. We send a JSON blob back. 
```
ajax: {
        url: '/d/ajax/auth',
        type: 'POST',
        dataType: 'form',
        data: function(params) {
          return {
            'query': params.term,
            'requested_ajax': "product_catalog_autocomplete_request",
          }
        },
        processResults: function(data) {
          console.log("HELLO WORLD");  // THIS NEVER TRIGGERS
        }
      },
```

I verified in network tab in developer tools that a response was sent back. select2 never triggers processResults and just displays a could not read results error.

Honestly it would be much simpler for people if select2 just surfaced a callback function instead of Ajax with a configuration signature like:

```
getResults: function(params, callback) {}
callback(err, res)
```

With javascript libraries if something will go wrong it is almost always trying to define the ajax. Some libraries like typeahead assume you are using GET, others like select2 don't bother documenting things and then it's a question of what options does this take vs what options are available.

I tried to override transport for example and couldn't figure out what to pass to the stupid success and failure functions (success receives an undefined value for data even though I passed it the response.....). Not to mention I had to stare at the source code to even figure out what those functions wanted.

**Comment by cbichis** [comment]
I confirm the issue. Same problem here...

**Comment by seleenne** [comment]
I have a similar problem here, but when I use transport, not trigger processResults .

**Comment by nduarte** [comment]
Same here, processResults is never called.

**Comment by stepofweb** [comment]
Indeed, processResults is not called.

**Comment by seleenne** [comment]
Has someone probe without the last coma in the return of the data? 

```
data: function (params) { 
    return {
        'query': params.term,
        'requested_ajax': "product_catalog_autocomplete_request" <--
    }
},
```

**Comment by correlator** [comment]
+1

**Comment by alexweissman** [comment]
If you look at the documentation for [`$.ajax`](http://api.jquery.com/jquery.ajax/), `form` is not a valid option for `ajax.dataType`.  Your "could not read results error" is likely related to this.

It's also unclear why you are using a `POST` request to _retrieve_ data.  Are you familiar with [REST](https://en.wikipedia.org/wiki/Representational_state_transfer#Relationship_between_URL_and_HTTP_methods) and the basic principles of HTTP?

You should use a `GET` request, with a `dataType` of `json`.  See the docs on [remote data sources](https://select2.org/data-sources/ajax) for more information.

**Comment by lingtalfi** [comment]
Same problem here, using json dataType with GET request.
The options are correctly fetch via ajax, but the processResults callback is never called.

Using this:
`<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>`

```js
            $('#intervention_orators_id').select2({
              placeholder: 'Veuillez sélectionner les intervenants (5 max)',
              maximumSelectionLength: 5,
              multiple: true,
              processResults: function (data) {
                console.log("transforming results"); // never called
                return {
                  results: [
                    {id: 1, text: 'test'},
                  ]
                };
              },
              ajax: {
                url: "{{ route('ajax') }}",
                dataType: 'json',
                data: function(params) {
                  return {
                    q: params.term,
                    event_id: {{$event->id}},
                    action: 'select2Participants',
                  };
                },
              },
            });
```

**Comment by KZyred** [comment]
+1

**Comment by arcade84** [comment]
@seleenne https://damianreloaddata.github.io/s0qo5lrgAkZixDCahGYefjfC0IrpTxqaw6gvlF/
