### ISSUE TITLE
Multiple Tag select Height problem

### ISSUE THREAD

**Issue by minedun6** [select2/select2#4826]
Is there any way I can prevent the select from taking more vertical space past a certain point when using Select2 tag option ? Or maybe put a limit to how many elements can be select from the dropdown ?
Maybe I can set it using a condition ? If I select a certain element in the form, I need to limit the selected results to "n".

**Comment by alexweissman** [comment]
> put a limit to how many elements can be select from the dropdown ?

This exists.  It is the `maximumSelectionLength` configuration option.  See https://select2.org/selections#limiting-the-number-of-selections.

I believe the max-height of the select element itself can be restricted with CSS.
