### ISSUE TITLE
Limiting the number of selections - maximumSelectionLength - CTRL+ add

### ISSUE THREAD

**Issue by rasvi** [select2/select2#4827]
**Problem**
I limited the number of selection to 2. but still I can select more input by using CTRL key.

`$(".js-example-basic-multiple-limit").select2({
  maximumSelectionLength: 2
});`

**Steps to reproduce the issue**
1. set  maximumSelectionLength: 2
2. click on select2
3. Hold ctrl key 
4. click more than 2 input options

**Operating System**
Windows

**Browser**
Chrome
Firefox

Example
1. Open the link https://select2.github.io/examples.html
2. Got to the section "### Limiting the number of selections"
3.  try to reproduce the issue, as explained above

**Comment by Murilo2508** [comment]
this bug was not fixed? has anyone have a solution?

**Comment by Murilo2508** [comment]
> this bug was not fixed? has anyone have a solution?

For now my solution is:

    let select2Options = $.parseJSON($('.select2').attr('select2-options') || '{}');
    
    $('.select2').select2(select2Options);
    
    $("select").on("select2:selecting", function (e) {
        if ($(this).val() && $(this).val().length >= select2Options.maximumSelectionLength) {
            e.preventDefault();
        }
    });

I found this solution [here](https://stackoverflow.com/a/55825502).

**Comment by imolecule** [comment]
Thanks Murlio2508. The belo code worked for me perfectly.

`let $selCities = $(".select");
let count = 4;
$selCities.on("select2:selecting", function (e) {
        if ($(this).val() && $(this).val().length >= parseInt(count)) {
                e.preventDefault();
        }
});`
