### ISSUE TITLE
possible to store / send additional data with the plugin?

### ISSUE THREAD

**Issue by Zxurian** [select2/select2#483]
this may be beyond the scope of this plugin, and if so, that's ok, as I've developed a workaround for the time being.

Would it be possible to add the feature of additional data storage per choice?
ie. when handling choices, instead of just the traditional "id", & "text" attributes, also allow a "data" (or whatever) attribute that would store additional data, that could be retrieved via an added method.
ex. $('#foo').val() would return the traditional select values (ids separate by commas), but $('#foo').valwithdata() (or whatever) would return an object of selected choices along with the additional data of the choices.

Doable? or overkill?

**Comment by 4selin** [comment]
Very good functioanality:
var x = $('#foo').select2('data');

But it is not described on options page https://select2.github.io/options.html

You should definitely add that function to the options description.

**Comment by gidzr** [comment]
Hi - I'm a few years late to the convo, but this data() method isn't exactly the same thing as having extra data fields in the select2 results. 

Is it possible in the latest version to add extra variables to the select2('data') values attached to each select2 option **when setting up the select2 programmatically:**
`$(inputSelectId).select2({tags: true, multiple:true, allowClear: true, **data: selectsData**}); `
where selectsData = [{id:1, text:'stuff'}];

which returns: 
        "selected": true,
        "disabled": false,
        "text": "stuff",
        "id": "1",
        "title": "",
        "_resultId": "select2-_lifeCycleSelect-result-dvx1-2",
        "element": {}

I've tried adding new values in the data array (selectsData), but those elements don't appear via select2('data') call.
