### ISSUE TITLE
Missed option in documentation

### ISSUE THREAD

**Issue by roman4e** [select2/select2#4835]
## Prerequisites

Need to make tags being selected in input field using data provided with "data" option within plugin initialization.

## Steps to reproduce the issue

Read documentation and find nothing about.

## Expected behavior and actual behavior

Find an option in documentation

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

Libraries

- jQuery version: 2.2.4
- Select2 version: 4.0.3

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/)

## Solution
An object _data_ with options which you can supply with ajax request or by adding it into initialization object can also have `"selected":true` property. If you set it for each row of data object, given options will be automatically set as tags.

`{
     "data": [{"id":0, "text": "Sample1", "selected": true},
                  {"id":1, "text": "Sample2", "selected": true},
                  {"id":2, "text": "Sample3"}]
}`

In this case you will see Sample1 and Sample2 selected in the input field.

**Comment by alexweissman** [comment]
Thanks, this is now documented in https://select2.org/data-sources/formats.
