### ISSUE TITLE
Single-Level Child Nesting via Data Array does not show display text after selection

### ISSUE THREAD

**Issue by blimmer** [select2/select2#4836]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2

## Steps to reproduce the issue

1. Visit [this fiddle](http://jsfiddle.net/L0kpt3o1/15/) with Chrome (I tested with 57.0.2987.98 - current stable and 59.0.3042.0 - current canary)
2. Choose the nested element

## Expected behavior and actual behavior

When I follow those steps, I see...
The value of the select change

I was expecting...
The text associated with the selection to show up in the select2.

## Environment

Browsers

- [x] Google Chrome

Operating System

- [x] Mac OS X

**Comment by William-H-M** [comment]
I think this is related to #3866 
I did my own [fiddle ](http://jsfiddle.net/emmpsbs1/2/)to test it out and it's working the only differences is that I don't use a hidden but a select 
try to see what happens

**Comment by blimmer** [comment]
Thanks @William-H-M - that fixed it!
