### ISSUE TITLE
Fuzzy search

### ISSUE THREAD

**Issue by cyberhck** [select2/select2#4837]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))

This is more of a feature request rather than a issue.

I'd like to send a PR for a fuzzy search (like sublime text's search), I already have everything I need, will select2 be willing to integrate that within the library?

**Comment by William-H-M** [comment]
You can do a PR and integrate some test and if some member of team see that is useful and that the test does not give any problem or broke anything from the code, it could be integrate it.
Just try it some features had been added thanks to a PR

**Comment by karolyi** [comment]
+1ing this, fuzzy search is needed.

**Comment by cyberhck** [comment]
I'm a little held up right now, if you want, I'll just paste in the function and anyone can create a PR with tests :) should be fairly simple:
```JavaScript
/**
 *
 * @param pattern
 * @param str
 * @returns {[boolean,score,formatted]}
 */
function fuzzy_match(pattern, str) {

	// Score consts
	var adjacency_bonus = 55;                // bonus for adjacent matches
	var separator_bonus = 10;               // bonus if match occurs after a separator
	var camel_bonus = 10;                   // bonus if match is uppercase and prev is lower
	var leading_letter_penalty = -3;        // penalty applied for every letter in str before the first match
	var max_leading_letter_penalty = -9;    // maximum penalty for leading letters
	var unmatched_letter_penalty = -1;      // penalty for every letter that doesn't matter

	// Loop variables
	var score = 0;
	var patternIdx = 0;
	var patternLength = pattern.length;
	var strIdx = 0;
	var strLength = str.length;
	var prevMatched = false;
	var prevLower = false;
	var prevSeparator = true;       // true so if first letter match gets separator bonus

	// Use "best" matched letter if multiple string letters match the pattern
	var bestLetter = null;
	var bestLower = null;
	var bestLetterIdx = null;
	var bestLetterScore = 0;

	var matchedIndices = [];

	// Loop over strings
	while (strIdx != strLength) {
		var patternChar = patternIdx != patternLength ? pattern.charAt(patternIdx) : null;
		var strChar = str.charAt(strIdx);

		var patternLower = patternChar != null ? patternChar.toLowerCase() : null;
		var strLower = strChar.toLowerCase();
		var strUpper = strChar.toUpperCase();

		var nextMatch = patternChar && patternLower == strLower;
		var rematch = bestLetter && bestLower == strLower;

		var advanced = nextMatch && bestLetter;
		var patternRepeat = bestLetter && patternChar && bestLower == patternLower;
		if (advanced || patternRepeat) {
			score += bestLetterScore;
			matchedIndices.push(bestLetterIdx);
			bestLetter = null;
			bestLower = null;
			bestLetterIdx = null;
			bestLetterScore = 0;
		}

		if (nextMatch || rematch) {
			var newScore = 0;

			// Apply penalty for each letter before the first pattern match
			// Note: std::max because penalties are negative values. So max is smallest penalty.
			if (patternIdx == 0) {
				var penalty = Math.max(strIdx * leading_letter_penalty, max_leading_letter_penalty);
				score += penalty;
			}

			// Apply bonus for consecutive bonuses
			if (prevMatched)
				newScore += adjacency_bonus;

			// Apply bonus for matches after a separator
			if (prevSeparator)
				newScore += separator_bonus;

			// Apply bonus across camel case boundaries. Includes "clever" isLetter check.
			if (prevLower && strChar == strUpper && strLower != strUpper)
				newScore += camel_bonus;

			// Update patter index IFF the next pattern letter was matched
			if (nextMatch)
				++patternIdx;

			// Update best letter in str which may be for a "next" letter or a "rematch"
			if (newScore >= bestLetterScore) {

				// Apply penalty for now skipped letter
				if (bestLetter != null)
					score += unmatched_letter_penalty;

				bestLetter = strChar;
				bestLower = bestLetter.toLowerCase();
				bestLetterIdx = strIdx;
				bestLetterScore = newScore;
			}

			prevMatched = true;
		}
		else {
			// Append unmatch characters
			formattedStr += strChar;

			score += unmatched_letter_penalty;
			prevMatched = false;
		}

		// Includes "clever" isLetter check.
		prevLower = strChar == strLower && strLower != strUpper;
		prevSeparator = strChar == '_' || strChar == ' ';

		++strIdx;
	}

	// Apply score for last match
	if (bestLetter) {
		score += bestLetterScore;
		matchedIndices.push(bestLetterIdx);
	}

	// Finish out formatted string after last pattern matched
	// Build formated string based on matched letters
	var formattedStr = "";
	var lastIdx = 0;
	for (var i = 0; i < matchedIndices.length; ++i) {
		var idx = matchedIndices[i];
		formattedStr += str.substr(lastIdx, idx - lastIdx) + "<b>" + str.charAt(idx) + "</b>";
		lastIdx = idx + 1;
	}
	formattedStr += str.substr(lastIdx, str.length - lastIdx);

	var matched = patternIdx == patternLength;
	return [matched, score, formattedStr];
}
```
credit to sublime text authors and the author of this [blog](https://blog.forrestthewoods.com/reverse-engineering-sublime-text-s-fuzzy-match-4cffeed33fdb)

Anyone willing to create a PR is welcome :) we're using that code in production and it's working quite well :)

**Comment by stefanKuijers** [comment]
+1

**Comment by alexweissman** [comment]
No "+1" comments, please.  Just click the 👍  on the top comment.

**Comment by reypm** [comment]
Does any knows if this feature is already included in CORE? @cyberhck do you have any usage examples to post here? I would like to implement this but does not have a clue in how to use it

**Comment by cyberhck** [comment]
I'm adding a reminder to this issue to have a look on monday, we didn't patch select2, but we are using fuzzy search for our websites, I'll post the example soon, but unfortunately I can't create a PR as of now because I'm really swamped with tasks.

**Comment by cyberhck** [comment]
so, I'm looking at our source code, please keep in mind that we've got legacy code, I'll post the relevant parts:
I've a function declaration called `fuzzy_match`
I've also a function called matcher, which looks something like:
```javascript
function matcher(term, text){
	if(term.term === undefined){
		return {text: text, score: 1};
	}
	var match = fuzzy_match(term.term, text.text);
	return (match[0])?{text: text, score: match[1]}:false;
}
```
I also have a sorter, which sorts the matched elements, (so matching elements come at top)
```javascript
function sorter(data) {
	return data.filter(function(item) {
		return !!item;
	}).sort((a, b) => b.score - a.score)
          .map(item => item.text);
}
```
And whenever we're invoking a select2 on a element, we're passing this matcher as a matcher option, and sorter as sorter option, which looks something like:
```javascript
$("#element").select2({
  placeholder: 'select a name',
  matcher,
  sorter
})
```

**Comment by reypm** [comment]
@cyberhck excellent, thank you so much just one question, are you placing all that code in your own .js file or it goes into the select2js core files? I mean the functions

**Comment by cyberhck** [comment]
That doesn't belong to select2 core file, that'd be terrible, I'd rather not have feature than modify anything from library without directly creating PR first :)

Like I mentioned, I simply defined those function on my own codebase, because they don't have anything to do with select2 (those functions can be run completely in isolation), then I'm simply passing those two functions to select 2, saying, to match elements, use this function, and to sort, use my own sort function.

If someone has the time, they could add one more matcher to select2 core, then people could just use that from core, it'd be quite great.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
