### ISSUE TITLE
Select 2 - Problem displaying Reslults of AJAX Request

### ISSUE THREAD

**Issue by petmi627** [select2/select2#4840]
Hello Everyone,

I opened this issue because i have a little mind brooking problem.
I wrote a Script that make a Search over a LDAP Server to get the Users Full name and User ID.
Always when i start the AJAX request, i get the results but they are not displaying.
It can be that i'm an idiot but i don't find the problem.

For Example here is my JS Code
```
$(".js-data-example-ajax").select2({
     ajax: {
     url: "<?php echo $url ?>/bin/ajax/ldap_search.php",
     dataType: 'json',
     delay: 250,
     data: function (params) {
          return {
              q: params.term // search term
          };
      },
      processResults: function (data) {
          console.log(data);
          return {
                results: data
          };
       },
      cache: true
      },
     minimumInputLength: 4
});
```

And this is my JSON Respnse
`["Mike Crawford (NGIE113)", "Mike Preuss (NGIB956)", "Mike Weiller (NEN7992)", "Mike Theissen (AA10101)", "LDA1231 (lda1231)", "LDA1232 (lda1232)", "Mike Manant-CONT (ZENE413)", "Mike Breyer (NEND861)", "Mike Peiffer (AA05391)", "Mike Scholtes-CONT (ZA26077)", "Mike Peters (AA43681)", "Mike Mossong (AA28172)", "Mike Padilla (AA76273)", "Mike Denis-CONT (ZA34482)", "Mike Klein (AA82171)", "Mike Mathieu (AA91973)"]`

But Somehow when i type nothing displays but when i check the console log the data is there.

- [x] Tried to add success and results instant of  processResults but without success
- [x] Tried to add formatResult: formatResult, formatSelection: formatSelection, initSelection: initSelection but without success
- [x] Tried to add formatResult: ,formatSelection: but the problem is still there

I hope someone can help me because it's really frustrating
 
Thank you in advance

**Comment by ciprianmicutaru** [comment]
ajax is totally broken in 4+ - I couldn't get it to work either.

**Comment by petmi627** [comment]
Hi dear community,

I found a resolution for this problem, the problem was like every problem between the keyboard and the chair ;p,

I haven't defined the function for templateResult and templateSelection. This Fiddle helped a lot [http://jsfiddle.net/59p19q7z/3/](url)

**Comment by alexweissman** [comment]
>ajax is totally broken in 4+

@ciprianmicutaru this is simply not true.  You just need to transform your data appropriately (see https://select2.org/data-sources/formats), or use templating (https://select2.org/dropdown and https://select2.org/selections).

Glad you got this figured out.
