### ISSUE TITLE
Multiple select2 placeholder text cut on the bottom side when used with Bootstrap and displaye with IE11

### ISSUE THREAD

**Issue by tbrcrl** [select2/select2#4841]
When a **multiple** select2 is used in combination with **Bootstrap** and the browser is **Internet Explorer 11** the bottom part of the placeholder text is cut, as shown in the following JS Bin.
[demo](https://jsbin.com/veqogor/77/edit?output) (use IE11 to reproduce the issue)
One workaround is to add an height to the class .select2-search__field. e.g.
```css
.select2-search__field {
    height: 20px;
}
```
but this will affect also the height of the search box of the single select (also reported for convenience in the JS Bin) that make use of the same class..
Any other suggestion to solve this issue so that the other select2 features are not affected?
Thanks

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand what exactly problem this CSS solves and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
