### ISSUE TITLE
Choosing a new tag won't fire the change event if ajax is used

### ISSUE THREAD

**Issue by WolfBrawl** [select2/select2#4842]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Setup a select with enabled tags and ajax support
2. Type an option, preferably a short one (example: "a"). The point is to not let the select search more than once. If you're fast enough, you can use any word.
3. Choose the new option

## Expected behavior and actual behavior

I expect the select to trigger the change event, but nothing happens.

You can keep reproducing this if you clear the select, you don't need to refresh.

If you type an option, let the select search, type one or more characters and then choose this option, the select will trigger the event just fine.

As a side note, this bug doesn't happen if you set multiple to true.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.1.1
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsfiddle.net/y8onnnhr/)

**Comment by rodrigopeixotobr** [comment]
+1

**Comment by Seb33300** [comment]
+1

**Comment by dicearr** [comment]
+1

**Comment by renehamburger** [comment]
The issue seems to be, that Select2 adds the tag not only as a result but also as an option to the <select>:
```html
<select tabindex="-1" class="select2-hidden-accessible" aria-hidden="true">
  <option value="a" data-select2-tag="true">a</option>
</select>
```

Even though it's not selected, it appears as the selection in Chrome (and possibly other browsers). Probably because it's the only option of the <select>. The other issues are consequences of this, I would think.

**Comment by renehamburger** [comment]
I have created a [sample at CodePen](https://codepen.io/leanix/pen/gWywNZ?editors=1010) that demonstrates the issue. (I've got a workaround that works for us in our code base, but I couldn't get it to work in that sample.)

**Comment by dicearr** [comment]
I have implemented a workaround using the deprecated [DOMSubtreeModified ](https://developer.mozilla.org/en-US/docs/Web/Events/DOMSubtreeModified) event. This is the [CodePen ](https://codepen.io/anon/pen/LyvyLB?editors=1010) forked and modified.

**Comment by rodrigopeixotobr** [comment]
Its a very common and important feature. Is there a old version with this working?
Is there any idea of when it could be fixed? Im starting looking for other solutions like Chosen or Selectize.js. Do you know others alternatives?

**Comment by alexweissman** [comment]
Is this related to #4028?

**Comment by pklaparda** [comment]
+1
any progress on this issue?

**Comment by alexweissman** [comment]
If @renehamburger's theory is correct, then shouldn't adding an empty `<option></option>` to your `<select>` markup solve this?

**Comment by pklaparda** [comment]
awesome
thanks a lot!

**Comment by alexweissman** [comment]
That worked?

**Comment by pklaparda** [comment]
yeap

**Comment by alexweissman** [comment]
Alright, we should probably add this to the documentation for AJAX and/or dynamic option creation, then.

**Comment by alexweissman** [comment]
Also see https://github.com/select2/select2/issues/3553#issuecomment-119772829

**Comment by federico-66** [comment]
@renehamburger: thanks for workaround

**Comment by LrntL** [comment]
@renehamburger workround solves my problem (after an TypeScript to JavaScript conversion in my case).

I sometimes have random bug on first time click on created tag, click does nothing. I have to type again my search term to get it work.

Thanks !
