### ISSUE TITLE
Multiple tags added when selected and select->option html tag issue

### ISSUE THREAD

**Issue by ozc** [select2/select2#4843]
I have a select box with tags:true, tokenSeparators: [','], mulltiline defined. I use ajax to get data.

Bug:
The problem is when tags is true, if you add tags by separator or clicking the text written (returning variable.text on templateResult) after if you try to add options from ajax data, it adds the last tag along with the option you choose.

My test ajax data returns tag1,tag2,....,tag10
- write a starting text which will return some data, like "tag", add separator or if you enabled in templating select from the list
-there will be tag/option added with text example: "tag"
-now write the same text of few chars to populate list with ajax data, "tag"
- list will be populated again
-choose an option from ajax list
-now it will add two tags, second one same as the first and the one selected from ajax data. example: "tag", "tag","tag5"

Bug:
Another bug for the same select list is:
when some text entered but clicked outside the select box and list, entered text is still added as an option to select html tag. 
This will be a problem if the form is submitted directly.

Bug:
Option html tag is added for the search text and the option chosen from the list. But only the text entered has data-select2-tag="true" attribute defined. When tags are removed those chosen from the list are not removed, only the ones with data-select2-tag="true" are removed

**Comment by alexweissman** [comment]
See #4895.
