### ISSUE TITLE
Display a drop-down box to locate the problem. 

### ISSUE THREAD

**Issue by phphuan** [select2/select2#4846]
## Prerequisites

With the select2 plugin in the browser page to a different location ( switch at the top to the bottom ), the search results will display a drop-down box of positioning is not accurate

## Steps to reproduce the issue

1.Scroll the browser's scrollbar color option(html tag select) at the top of the page.Then click the input box Get search results
2.Scroll the browser's scrollbar color option at the bottom of the page
3.Then click the input box Get search results.Positioning is not accurate display of the results

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
版本 56.0.2924.87

Operating System

- [ ] Windows7

Libraries

- jQuery version:
1.9.1
- Select2 version:
4.0.2

**Comment by phphuan** [comment]
The color option is html tag . It is to use the select2 plugin.

**Comment by alexweissman** [comment]
The steps to reproduce this issue are not clear.  Without a jsbin and/or screenshots, it is impossible to determine the problem here.

**Comment by phphuan** [comment]
![seelct2](https://user-images.githubusercontent.com/12897599/31331553-5cced472-ad15-11e7-9b99-68ab5081ea21.jpg)
