### ISSUE TITLE
Issue with scrolling to highlighted element with disabled elements before it

### ISSUE THREAD

**Issue by EvgenyGaiduk** [select2/select2#4847]
## Prerequisites

- [ +] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ +] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ +] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Make a select with big amount of options
2. Make highlighted one in the bottom (like 6th from bottom)
3. Disable all the elements before highlighted
4. Trigger update event on changed select2 (or destroy-create)

## Expected behavior and actual behavior

Then ckick on select, and it's not scrolling to the highlighted element

It happens because options are selected by [area-selected] and there is condition if currentIndex <= 2 then scroll to top,

http://joxi.ru/LmGqNLqUeZZpqA

So disabled elements don't have [area-selected] attribute

So the solution is to grab all the elements by [role=treeitem] for example
var $options = this.$results.find('[role=treeitem]');

select2/dist/js/select2.full.js - file

## Environment

Browsers

- [ +] Google Chrome
- [+ ] Mozilla Firefox
- [ +] Internet Explorer

Operating System

- [+ ] Windows
- [+ ] Mac OS X
- [+ ] Linux
- [+ ] Mobile

Libraries

- jQuery version: 1.11.0
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ +] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
Please provide a http://jsbin.com that replicates this problem.  Otherwise, we will not be able to help.
