### ISSUE TITLE
Unable to re-add select2 in select2:unselect

### ISSUE THREAD

**Issue by multiwebinc** [select2/select2#4857]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

```
$('#supported_langs').on('select2:unselect', function (evt) {
    $('#supported_langs').select2();
});
```

This produces (in Chrome):

```
Uncaught TypeError: Cannot read property 'query' of null
    at Select2.<anonymous> (select2.full.js?v=1487024312:5347)
    at Select2.Observable.invoke (select2.full.js?v=1487024312:651)
    at Select2.Observable.trigger (select2.full.js?v=1487024312:641)
    at Select2.trigger (select2.full.js?v=1487024312:5489)
    at Select2.open (select2.full.js?v=1487024312:5509)
    at Select2.toggleDropdown (select2.full.js?v=1487024312:5500)
    at DecoratedClass.<anonymous> (select2.full.js?v=1487024312:5287)
    at DecoratedClass.Observable.invoke (select2.full.js?v=1487024312:651)
    at DecoratedClass.Observable.trigger (select2.full.js?v=1487024312:641)
    at HTMLSpanElement.<anonymous> (select2.full.js?v=1487024312:1612)
```

Note: the following works fine without any error (select instead of unselect):

```
$('#supported_langs').on('select2:select', function (evt) {
    $('#supported_langs').select2();
});
```

## Environment

Browsers

- [x] Google Chrome

Operating System

- [x] Linux

Libraries

- jQuery version: jquery-2.1.3. Also tested on jquery-3.2.1
- Select2 version: master

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/) https://output.jsbin.com/havoquyede

A possible solution might be to wrap the following in an `if (this.dataAdapter)` block, but I'm not sure if this would have negative consequences elsewhere or if there would be a better fix.

``` 
      this.dataAdapter.query(params, function (data) {
        self.trigger('results:all', {
          data: data,
          query: params
        });
      });
```

**Comment by multiwebinc** [comment]
One other thing. This works fine without any error:

```
$('#supported_langs').on('select2:unselect', function (evt) {
    $('#supported_langs').select2('open'); // <-- Add this line
    $('#supported_langs').select2();
});
```

**Comment by alexweissman** [comment]
What is the use case here?  This seems like kind of a pathological case - you're initializing the Select2 control inside a handler for an event fired from that same control?

**Comment by multiwebinc** [comment]
I was trying to reload the select2 to allow the selected options to not appear in the list (e.g. issues https://github.com/select2/select2/issues/4858 and https://github.com/select2/select2/issues/4831).

**Comment by alexweissman** [comment]
Ah, I see.  I believe the closest way to "reinitialize" the Select2 control is to destroy it first.  See https://select2.org/programmatic-control/methods#destroying-the-select2-control

**Comment by multiwebinc** [comment]
Same thing happens. In fact, I did some testing and you get the same error when calling `destroy` in several events.

https://jsbin.com/dimahevame/1/edit?html,js,console,output

**Comment by michaelrue** [comment]
I have had this same issue as well.  I have the same code in the select event as the unselect event but the error only occurs in the unselect event.  I noticed though that I only get the error if I unselect an option by clicking the x when the select2 has multiple: true.  If I open the select2 and unselect an option that way, I don't get the error.
