### ISSUE TITLE
select:unselecting option and active dialog box

### ISSUE THREAD

**Issue by tagx** [select2/select2#4862]
on my program when I hit the "x" icon to clear data a dialog will appear asking the user if she/he wants to clear the data. how do i prevent the clearing of data when the dialog is active incase the user wants to cancel. 

here's my code:

```
$('#mae_mic').on('select2:unselecting', function(e) {
				var sel = $("#mae_mic option:selected").val(); //getting the value of an option 

				BootstrapDialog.show({
				title: 'Removing Mechanic in-charge Record',
				type: 'type-primary',
				message: 'Do you want to remove this in-charge?',
				buttons: [{
					label: '  Yes',
					icon: 'glyphicon glyphicon-ok',
					cssClass: 'btn-primary',
					action: function(dialog) { 
								dialog.close(); 
								return true;
							}
					}, 
				{
					label: '  No',
					icon: 'glyphicon glyphicon-remove',
					cssClass: 'btn-danger',
					action: function(dialog) {
							e.preventDefault();
							dialog.close(); 
					}
				}]
			});	
			});
```

thanks in advance guys. hope I can find answer here!

**Comment by alexweissman** [comment]
In the future, please try to format your code properly, with proper indentation so that we can read it.

It sounds like #5058 and the `clearing` event would work for this situation.

**Comment by tagx** [comment]
$('#mae_mic').on('select2:unselecting', function(e) {
var sel = $("#mae_mic option:selected").val(); //getting the value of an option 
	BootstrapDialog.show({
		title: 'Removing Mechanic in-charge Record',
		type: 'type-primary',
		message: 'Do you want to remove this in-charge?',
		buttons: [{
			label: '  Yes',
			icon: 'glyphicon glyphicon-ok',
			cssClass: 'btn-primary',
			action: function(dialog) { 
						dialog.close(); 
						return true;
					}
			}, 
		{
			label: '  No',
			icon: 'glyphicon glyphicon-remove',
			cssClass: 'btn-danger',
			action: function(dialog) {
					e.preventDefault();
					dialog.close(); 
			}
		}]
	});
});

Actually I manage to answer my own question. I figure this out but not with the bootstrap dialog but the native dialog javascript. but if you can integrate with this is more helpful to us. thanks
