### ISSUE TITLE
Stuck with dropdown

### ISSUE THREAD

**Issue by pculka** [select2/select2#4864]
so I am on a project where for some reason this undocumented software is being used

Can somebody please UPDATE the documentation:
https://select2.github.io/options.html#can-i-change-how-the-dropdown-is-placed

because obviously

```
$('select').select2({
  dropdownParent: $('#my_amazing_modal')
});
```
doesn't work and there is just vague information on how to get this going

**Comment by orioljd** [comment]
Hi I tried to use this option and it worked, but when I tried to use it as data-... I don't know how to use it, perhaps true or false? or somthing like: 
    data-dropdown-parent="body"
??

**Comment by alexweissman** [comment]
Since this is such a common issue, I've added it to a "common problems" page: https://select2.org/troubleshooting/common-problems

One of those solutions should work for you.
