### ISSUE TITLE
Select2 v4.0.3 cant select option from list

### ISSUE THREAD

**Issue by wajdijurry** [select2/select2#4865]
I am using select2 version 4.0.3 and it is awesome.
I have a list of items, each item has childrens, and each children has childrens too, i applied select2 to <div> not to <select> element, the data comes like this:
[{
   id: 1,
   text: "Main Category",
   children: [{
        id: 23,
        text: "Sub Category1",
        children: [{
            id: 40,
            text: "Sub Category of Sub Category1"
        }],
        id: 25,
        text: "Sub Category2",
        children:[{
            id: 50,
            text: "Sub Sub Category2"
        }]
   }],
   id: 2,
   text: "Main Category 2",
   children: [{
       .....
   }],
   ....
}]

The problem is when I tell select2 to set this data to <div>, i can't select any option of them !!

See this screenshot:
![image](https://cloud.githubusercontent.com/assets/25797257/24841461/0f11224c-1d8e-11e7-97b7-8fe876483a0a.png)

**Comment by wajdijurry** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25797257/24841464/1d90de3e-1d8e-11e7-8958-ba6ac3504c13.png)

**Comment by William-H-M** [comment]
Hi, if not wrong this is related to #4836, there's an explanation about it

**Comment by malefice** [comment]
@William-H-M , i think you meant #3866.

@wajdijurry, I tested the fork listed in #3866, and it works, and entries beyond two levels of depth can be selected. the only con is that the fork is based on 4.0.1.

**Comment by William-H-M** [comment]
@malefice Hi, yeah it's true, but I linked to #4836  because there was listed a fiddle with version 4.03, to do it with a current version, but is right that I should have linked the original issue, though

**Comment by alexweissman** [comment]
Please see the documentation on [hierarchical options](http://localhost/select2-docs-new/options#hierarchical-options).

**Comment by William-H-M** [comment]
@alexweissman please edit link as in being redirected to localhost, should be https://select2.org/options#hierarchical-options
Side note: wow it looks quite different the page since last time...
