### ISSUE TITLE
select2 Move Group Labels on Top of Items

### ISSUE THREAD

**Issue by rezaya2938** [select2/select2#4866]
It would be nice to have group label on top of items when scrolling down. like this feature in Kendo Multiselect:
[Move Group Labels on Top of Items](http://docs.telerik.com/kendo-ui/controls/editors/dropdownlist/how-to/appearance/group-label-on-top-of-the-items#move-group-labels-on-top-of-items)

**Comment by alexweissman** [comment]
So, Select2 already supports grouped data via the `optgroup` tag.  See https://select2.org/options#dropdown-option-groups and some of the basic examples.

You can also generate this from external data sources: https://select2.org/data-sources/formats#grouped-data

So, I'm not quite sure how this would translate to Select2.
