### ISSUE TITLE
'The results could not be loaded.' message during typing when request was cancelled by select2

### ISSUE THREAD

**Issue by eternalfame** [select2/select2#4870]
During the typing in select2 searchbox with 'ajax' option on in Chrome browser, select2 sends requests to server, and some of them it cancels. When it happens, the message 'The results could not be loaded.' appears in dropdown, then gets replaced with results. Seems a bit confusing.

Haven't tested in other browsers.

This bug happens also on the examples page (https://select2.github.io/examples.html)

Found such code in select2.full.js:
```
        // Attempt to detect if a request was aborted
        // Only works if the transport exposes a status property
        if ($request.status && $request.status === '0') {
          return;
        }
```
The condition here could be replaced with `($request.status && $request.status === '0' || $request.status === 0)` condiiton, but I can't be sure than it doesn't break something else

**Comment by eternalfame** [comment]
bug appears also in Firefox

**Comment by BigChief45** [comment]
@eternalfame I started experiencing this all of a sudden. Seemed to work fine before.\

Did you find any solution?

**Comment by nelson6e65** [comment]
I'm having this issue too. Specially noticeable in slow connections.

**Comment by kikonen** [comment]
Seeing this also, and given workaround fixes it. It seems that in JQuery status is 0, not "0", which triggers issue.

**Comment by lordplagus02** [comment]
Is there a PR for this yet?

**Comment by alexweissman** [comment]
@lordplagus02 there is a fix in #4356, but it needs some test cases before it can be merged in.

**Comment by lordplagus02** [comment]
is it possible that there's also an issue with the `delay` option? It seems to actually ignore the delay for me, displaying the aforementioned "error" message before I'm done typing.

**Comment by lordplagus02** [comment]
My bad, just used the code from the PR, **definitely fixes the issue**.

**Comment by alexweissman** [comment]
#4356 has been merged into the 4.0.6-rc.0 pre-release.

**Comment by kikonen** [comment]
I just tried out "4.0.6-rc.0" and I'm still seeing these errors

**Comment by raptor235** [comment]
Hey guys, 

I'm still getting this issue... just downloaded latest version of ACF I'm seeing the following 

http://www.flowpress.com/screenshots/screenshot_2018-02-14_at_6.50.21AM.png

ajax call returns the data

http://www.flowpress.com/screenshots/screenshot_2018-02-14_at_6.50.56AM.png

Any thoughts?

**Comment by canilao** [comment]
@raptor235 according to this pull request, they will release in 4.0.6.  https://github.com/select2/select2/pull/4356.  It looks like the merged and have a release candidate out.  Check what version you're using.
