### ISSUE TITLE
<select> element in templateSelection and templateResult

### ISSUE THREAD

**Issue by Karmalakas** [select2/select2#4874]
On **non** AJAX calls for `templateSelection` and `templateResult` I get object, that contains not only `id` and `text`, but also `element`, which is an `<option>` element of the `<select>`. However on AJAX calls I get just the JSON data. I figured I get second parameter to these functions, which is a list item `<li>` element (again - not a word in documentation about that; [Reminder here](https://github.com/select2/select2/issues/4687)).

So my question is.. How do I get the bound `<select>` element in these two functions?

Windows Google Chrome Select2 4.0.3

**Comment by alexweissman** [comment]
So in the case of AJAX results, there is no `<option>` element created until a selection is actually made.  This is now documented: https://select2.org/data-sources/ajax

**Comment by Karmalakas** [comment]
But the question was how do I get the `<select/>` element :) On non AJAX calls I could get it with `$(option).parent()`. `<select/>` itself I believe is always present and should be available, right?

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
