### ISSUE TITLE
Select 2 4.0.3 UI Issue!!

### ISSUE THREAD

**Issue by jackryu** [select2/select2#4875]
Select 2 4.0.3

UI look like this 

![image](https://cloud.githubusercontent.com/assets/6933841/25235834/ef62ed3a-2603-11e7-938f-1f4d3e2958bf.png)

**Comment by Braunson** [comment]
Can you post the output html?

**Comment by jackryu** [comment]
this issue is resolved this is no a select2 problam this is my UI problam - Sorry.
