### ISSUE TITLE
Doc : No answer for "What should the results returned to Select2 look like?"

### ISSUE THREAD

**Issue by jy95** [select2/select2#4883]
Hello,

I have read the doc and I didn't find explaination about this : https://select2.github.io/options.html#what-should-the-results-returned-to-select2-look-like

There is a basic example about this : https://select2.github.io/examples.html#data-ajax but no example about how to format for templateSelection (for example to attach value for selection).

EDIT : I finally found a workaround to access my data, maybe good to say it inside the doc : 
```js
$searchUsersBox.select2('data')
```

(where $searchUsersBox is a Jquery selector)

PS: templateResult has already an doc for it : https://select2.github.io/examples.html#templating
 
PS2 : templateSelection has a little explanation here : https://select2.github.io/options.html#templateSelection

**Comment by alexweissman** [comment]
This is now explicitly covered: https://select2.org/data-sources/formats.  The formats used by `templateSelection` and `templateResult` are exactly the same.
