### ISSUE TITLE
I find a  mistake in official website

### ISSUE THREAD

**Issue by wintry** [select2/select2#4886]
in [https://select2.github.io/examples.html](url)
the 2nd example 
it should be 
`<script type="text/javascript">
$(document).ready(function() {
  $(".js-example-basic-multiple").select2();
});</script>`

**Comment by William-H-M** [comment]
The $(document).ready(...) it's totally unnecesary for this case, if you put the script at bottom it'll work aswell, that function was used before when the page where too heavy when loading with most of current frameworks do things faster you can get a [little article here ](https://modernweb.com/5-things-you-should-stop-doing-with-jquery/)

**Comment by wintry** [comment]
but it will beset newcomer

**Comment by William-H-M** [comment]
Hi, exactly in what that will help on the code? usually that function is do a hold for when the page get loaded most of the page do need it because are quick to load to the time when the is get to the bottom of the page every content will be there

**Comment by alexweissman** [comment]
I agree with @William-H-M, this is an aspect of jQuery and not of Select2.  It could potentially be _more_ confusing, and perhaps lead people to assume that they need to wrap every instance of Select2 in its own `$(document).ready` block 🙀
