### ISSUE TITLE
tags cannot have id === null or "" 

### ISSUE THREAD

**Issue by Spongman** [select2/select2#4888]
if a tag's id === "", then it's deemed to be the placeholder, and removed.
if a tag's id === null (or undefined), then it's not selectable.
if a tag's id is otherwise falsey (eg, 0, or false) then it doesn't appear correctly when selected.

**Comment by alexweissman** [comment]
This is actually covered in the documentation:

https://select2.org/data-sources/formats#automatic-string-casting

> Blank ids or an id with a value of 0 are not permitted.
