### ISSUE TITLE
Set position top for result list (on Smartphone) ?

### ISSUE THREAD

**Issue by trancaodung** [select2/select2#4889]
- I have 1 combobox using select2
- When click it, select2-dropdown--below is open, and I want to set position on top of Smartphone.
- Now, I set it is OK, but have a bug is not select again.
![1](https://cloud.githubusercontent.com/assets/7899174/25517255/bf8ace5a-2c18-11e7-943f-e3ad6d052890.PNG)
![2](https://cloud.githubusercontent.com/assets/7899174/25517261/c3980030-2c18-11e7-9eff-77619fa99189.PNG)
![3](https://cloud.githubusercontent.com/assets/7899174/25517270/c8e09f48-2c18-11e7-8e09-a87514bfddb1.png)

- I using event: open, opening, select, close and do everything but not.
Please support.

**Comment by alexweissman** [comment]
It is unclear what this issue is about.  Can you provide a jsbin to replicate this problem?
