### ISSUE TITLE
Option to disable or hide search

### ISSUE THREAD

**Issue by buste** [select2/select2#489]
Is there a way to disabled search inside select?

**Comment by maple-leaf** [comment]
For current version , you should set to a enough positive number, like 99999, to disable search box.

**Comment by almogdesign** [comment]
None of this seems to work with the latest version 4.0. I have a multiple select box and I'm still getting the search icon might be a bug. I tried different settings with  minimumResultsForSearch

```html
<select id="observationSelection" style="width: 75%" multiple="multiple" data-parsley-group="step3">
                                                        <optgroup label="Irrigación">
                                                            <option>aplicar riego</option>
                                                            <option>no aplicar riego</option>
                                                            <option>aumentar frecuencia del periodo de riego</option>
                                                            <option>disminuir periodo de riego</option>
                                                            <option>reducir caudal de agua</option>
                                                            <option>reformar boquilla</option>
                                                            <option>reformar muros</option>
                                                            <option>limpieza de drenaje</option>
                                                            <option>construcción de drenaje</option>
                                                        </optgroup>
                                                        <optgroup label="Sigatoka">
                                                            <option>hacer aplicación</option>
                                                            <option>hacer deshoje</option>
                                                            <option>hacer laminado y biselado</option>
                                                            <option>monitoreo</option>
                                                        </optgroup>
                                        
                                                    </select> 
```

```javascript
 $("#observationSelection").select2({
        minimumResultsForSearch: -1
    });
```

![screen shot 2015-05-10 at 11 43 22 am](https://cloud.githubusercontent.com/assets/169507/7553594/0db5eb46-f70a-11e4-93bb-2d270923b44d.png)

**Comment by kevin-brown** [comment]
@almogdesign There's two issues there, neither of which Select2 can reasonable control

1. You're trying to disable search on a multiple select, but the `minimumResultsForSearch` option only has control over single selects. This is because the search for a multiple select is built into the design, while the search for a single select is built into the dropdown.

2. The search icon doesn't exist in Select2 4.0, which you should be able to confirm by the fact that Select2 doesn't include a search icon at all. This might be the result of your browser, or other styles which just happen to be conflicting with Select2 because it is a search box (`<input type="search" />`).

**Comment by almogdesign** [comment]
@kevin-brown thanks, yea I saw that there is no search icon and checked the docs. Your right one of the CSS stylesheets was still loading. Thanks for the help

**Comment by capcom-r** [comment]
I edited the `select2.min.js` file to set the `select-2__search` input field that's generated to `readonly="true"`.

**Comment by selcet** [comment]
Is it possible to have attr to control this option (show/hide search for some of selects)?

**Comment by mokhtasatxyz** [comment]
i use this code:

                `$('#select').focus(function( event )
                {
                    var $searchfield = $( '#'+event.target.id ).parent().find('.select2-search__field');
                    $searchfield.prop('disabled', true);
                });
                
                $('#select').click(function( event )
                {
                    var $searchfield = $( '#'+event.target.id ).parent().find('.select2-search__field');
                    $searchfield.prop('disabled', true);
                });
                
                $('#select').change(function( event )
                {
                    var $searchfield = $( '#'+event.target.id ).parent().find('.select2-search__field');
                    $searchfield.prop('disabled', true);
                });`

**Comment by damianvadone** [comment]
how do I remove all options from a select2 control?
