### ISSUE TITLE
change.select causing onchange to trigger.

### ISSUE THREAD

**Issue by gborbonus** [select2/select2#4891]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of Select2
- [ x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. goto: https://jsfiddle.net/tLwcv6gx/

## Expected behavior and actual behavior

When I follow those steps, I see...
you'll see that even when the link A is clicked, it's triggering the onchange, despite change.select2.

When you click Link B, it only changes the value, and no triggering occurs, despite having the value changed.

I was expecting...
change.trigger to NOT trigger the onchange event at all.

## Environment

Browsers

- [x ] Google Chrome
- [x ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
I'm not sure this is an issue with Select2, but rather a behavior of jQuery.  Take a look at the documentation for [`.trigger`](http://api.jquery.com/trigger/):

> Note: As with .triggerHandler(), when calling .trigger() with an event name matches the name of a property on the object, prefixed by on (e.g. triggering click on window that has a non null onclick method), jQuery will attempt to invoke that property as a method.

It would seem that neither `.trigger` nor `.triggerHandler` respect event namespaces when it comes to `on*` properties.  In fact, you can see this is the case even without any Select2 elements at all.  See [this fiddle](https://jsfiddle.net/tLwcv6gx/3/).  You'll notice that the unscoped `.on('change'` handler does not get invoked by triggering `change.special` on an input, but triggering `change.special` _does_ invoke a callback provided via the `onchange` attribute.

**Comment by SebastianRoland** [comment]
Hello Alex,

I am encountering the exact same problem, firing the onchange event of the underlying select on initialization. We are using jQuery as well and cannot do without it.

Can you give me an advice on how to work around this incompatibility between select2 and jQuery?

Thank you in advance.

**Comment by alexweissman** [comment]
In general, my advice is to altogether avoid using HTML attributes (like `onchange`) to bind events.  This is not just good because of the issue described here, but in general as a design principle (separation of concerns).
