### ISSUE TITLE
there is no way to  add some request headers before ajax

### ISSUE THREAD

**Issue by frloopee** [select2/select2#4893]
as the title said, i need to add some request headers before sending ajax request to retreive data.
but i can not find any way to acheive my goal.
please help.
thanks.

**Comment by alexweissman** [comment]
All `$.ajax` options are exposed through the `ajax` key: https://select2.org/data-sources/ajax#jquery-ajax-options

So, you should be able to do this with the `headers` setting as described in the jQuery documentation: http://api.jquery.com/jquery.ajax/
