### ISSUE TITLE
Select2 dropdown list 'highlight' on iOS

### ISSUE THREAD

**Issue by typebrad** [select2/select2#4894]
Hello.

Apologies if this is an existing topic. I searched and could not find anything.

When clicking (or touching) my selection from a select2 dropdown on iOS, the focus feels as if it's not directly on the option I am touching, but on the entire dropdown. It makes for an odd experience on mobile. The correct selection is made, but the gray 'highlight' is on the list. 

Please see image.

Your feedback is much appreciated.

![select2](https://cloud.githubusercontent.com/assets/24847502/25723725/d45057a4-30de-11e7-9b69-16a9eebf8c71.jpg)

**Comment by Sunbuzz** [comment]
+1 in this, I would like this to be addressed, as this disqualifies the use of select2 on iOS.

**Comment by Sunbuzz** [comment]
I made this in the meanwhile, it takes care of it but it's not perfect.
Just place it after your select2 initialization.

  ```
$('body').on('DOMNodeInserted','.select2-results__options',function(e) {
    $(this).css({ '-webkit-tap-highlight-color': 'rgba(0,0,0,0)', '-webkit-touch-callout': 'none'});
}).on('touchstart touchmove','.select2-results__options',function(e) {
    var ev = $.Event('mouseover');
    ev.pageX = e.originalEvent.touches[0].pageX;
    ev.pageY = e.originalEvent.touches[0].pageY;
    $(e.target).trigger(ev);
});

```

**Comment by niteshmittal** [comment]
Any update on this ticket? I am also facing same type of issue in IPAD Landscape mode...first one overlay list is coming and when I click on that it removed and shows exact working one...and after clicking on that data is selecting...
