### ISSUE TITLE
Multi select should not return null on .val() call

### ISSUE THREAD

**Issue by doapp-ryanp** [select2/select2#4897]
v4.0.3

If using a select2 that is of type `multiple` calling `.val()` on the select should return `[]` if there are no items selected.  Consumers of a multi select are asserting that the data is a list.  This also keeps the behavior consistent with 3.X.

To reproduce, run this from the console on [the examples](https://select2.github.io/examples.html#multiple) page:

```javascript
$(".js-example-programmatic-multi").val(["AK"]);
$(".js-example-programmatic-multi").val([]);
$(".js-example-programmatic-multi").val();  //This is null
```

In my opinion, `.val()` should return `[]` if select2 is `multiple` under the following conditions:

*  select item has not yet been chosen
*  select is "cleared" by calling `.val(null)`
*  select is "cleared" by calling `.val([])`

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
