### ISSUE TITLE
issue with touchscreen and fullpage plugin

### ISSUE THREAD

**Issue by ClemLivy** [select2/select2#4904]
I'm unable to use select2 on touch iOS device (not tested on others) when I use the fullPage.js plugin with the scrollOverflow option set to true (this option use the iscroll.js plugin).

I have seen that a similar issue is caused when select2 is used with fastClick.

Any idea of what I could do to fix that?

Many thanks!

Clem

**Comment by alexweissman** [comment]
Please provide a jsbin or other working example that demonstrates your issue.
