### ISSUE TITLE
Async processResults callback 

### ISSUE THREAD

**Issue by loudadyassine** [select2/select2#4906]
I have to reprocess the data when received in the processResults callback, in my processResults function, I need to do an Ajax request based on the received result in order to add some missing informations ( an async ajax request, not a sync one ). The problem is that processResults doesn't provide an argument "callback".

Is there any possible way to achieve this requirement ?

Thank you,

**Comment by alexweissman** [comment]
This is a good question.  It could probably be solved if there was a way to manually trigger when Select2 populates the dropdown options, rather than relying on `processResults`.  Then you'd be able to nest your AJAX calls, and only trigger Select2 after both requests have completed.

**Comment by phpstudyone** [comment]
processResults 现在还不支持异步处理么?

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
