### ISSUE TITLE
Loading remote data with encoded parameters

### ISSUE THREAD

**Issue by hebe889900** [select2/select2#4907]
## Prerequisites

- [Yes] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [Yes] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [Yes] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
I want to generate result from a web service call through a proxy that using encoded format q%3searchword instead of "q=searchword" because the web service call is only available when using the proxy. Is there anyway I can pass this encoded parameter to get the remote data so the final ajax call url will be "url%3Fkw%3child" instead of "url?kw=child"

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ Yes] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ Yes] Windows
- [ Yes ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
You can modify the query that Select2 sends out by passing a callback to the `ajax.data` setting.  What happens if you try returning a string instead of an object from that callback?

See https://select2.org/data-sources/ajax#additional-request-parameters
