### ISSUE TITLE
Dropdown jiggling

### ISSUE THREAD

**Issue by enylin** [select2/select2#4910]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a \<div\> and set overflow: auto to make it scrollable
2. Put \<select\> (with select2) and other stuff inside the \<div\> created in step 1. Also make sure that the height of the elements inside is greater than the height of the \<div\>.
3. Click to expand the dropdown.
4. Scroll on \<div\>.

## Expected behavior and actual behavior

When I follow those steps, the <input> part keeps jiggling.

I was expecting that the whole dropdown scrolls upwards or downwards according to scrolling direction (as the example page).

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.1
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins(Only jQuery)
- [x] I can reproduce this bug in [https://jsfiddle.net/h89e9fue/](https://jsfiddle.net/h89e9fue/)

**Comment by alexweissman** [comment]
I can't replicate this problem in Firefox 52.3, OSX 10.12 with your jsfiddle.  When I click the overflow scrollbar after opening the Select2 dropdown, it simply closes the Select2 dropdown again.  Using the mousewheel to scroll simply scrolls inside the dropdown itself.  I don't see any jiggling.

**Comment by alexweissman** [comment]
Please feel free to comment if you have any more insight, and we can reopen the issue.
