### ISSUE TITLE
PreventDefault disabled "space" and "return" tokenSeparator

### ISSUE THREAD

**Issue by enylin** [select2/select2#4911]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add space (" ") token separator to select2.
2. Call preventDefault() on select2:opening event to prevent the dropdown opening.
3. Type some characters in the input field, and press "space" or "return" as a token separator.

## Expected behavior and actual behavior

When I follow those steps, nothing would happen after I press "space" or "return".

I was expecting that it would trigger token separation.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.1
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [https://jsfiddle.net/h89e9fue/2/](https://jsfiddle.net/h89e9fue/2/)

**Comment by alexweissman** [comment]
Interesting.  So `,` works fine in this case, but ` ` does not.

I should point out also that using `tags` in this manner is [deprecated](https://select2.org/data-sources/arrays#backwards-compatibility-with-the-tags-option).  You should use `data:` to pass in an initial array of options, and `tags: true` to enable [tagging](https://select2.org/tagging).
