### ISSUE TITLE
[Q] List of options and their meaning

### ISSUE THREAD

**Issue by szachara** [select2/select2#4912]
Is there any simple table with options and their descriptions / meaning? I can't find it in docs.

Simple table with option name ( sorted chronologically ) and his description would be really handful, may be i missed something.

**Comment by Dgc2002** [comment]
That's been my main complaint so far, the docs are pretty sub-par compared to other similar libraries.

**Comment by UziTech** [comment]
version 3.5.3 has great [documentation](http://select2.github.io/select2/#documentation)

I can't find anything like that for v4

**Comment by szachara** [comment]
That is exactly what every developer needs :-)

**Comment by samysadi** [comment]
I second this request. Right now, we need to google around or look through the code. This would save us a huge amount of time. Just a simple list of options and their meaning, no need for a fancy documentation.

**Comment by alexweissman** [comment]
This is now available: https://select2.org/configuration/options-api

**Comment by szachara** [comment]
that is absolutely amazing 🚀 thx
