### ISSUE TITLE
[QUESTION] Handle "keyup" event to compare with loaded elements

### ISSUE THREAD

**Issue by JuanWilde** [select2/select2#4917]
I want to show to the user a message like "it will be stored as a new type" if he writes a new option in the searchbox.

First of all (before using select2) I had a jQuery Autocomplete function to do this with the keyup event, but I don't know how to do this in the better way with select2.

Thanks in advance

**Comment by alexweissman** [comment]
Are you talking about the [tagging](https://select2.org/tagging) feature?

**Comment by JuanWilde** [comment]
Ups! Sorry. The issue is solved since I read the docs :) 
This can be closed.

**Comment by alexweissman** [comment]
No problem, the docs only recently became actually usable 😄
