### ISSUE TITLE
Dynamically add tags

### ISSUE THREAD

**Issue by piernik** [select2/select2#4918]
I want to use select2 multiple tags option that are fetch by ajax. Below select field I want to list mostly used ones. On click it should be added to select2. Something like https://select2.github.io/examples.html#programmatic (set to California and Alabama) but it's not working with tags and ajax.

If I append element to select `$(".select2").append("<option value='predefined' data-select2-tag='true'>predefined</option>");` all ajax functionality is disapearing - not working anymore

**Comment by piernik** [comment]
I figured it out.

**Comment by Jatapiaro** [comment]
@piernik How did you do that?
