### ISSUE TITLE
there any way to add a new option to selected options?

### ISSUE THREAD

**Issue by iamshen** [select2/select2#4919]
i wan to add a new option to the select, but when i using under code
var val='something'
 $("#search").val([val]).trigger("change");

the old selected option were clear, so  how to add a new option  .no clear and create new one .

**Comment by DVD27** [comment]
You could do like this add the new value without loose the old : https://jsfiddle.net/m0muaqet/1/

```
var oldValue = $('.select2').val() || []; // retrieve old value selected
oldValue.push($('.threeOpt').val()); // add the new val
$('.select2').val(oldValue).trigger('change'); // update the select and notify
```

**Comment by alexweissman** [comment]
If you're just adding a new option, you can create a new `Option` object and append it to your control: https://select2.org/programmatic-control/add-select-clear-items

The last two parameters of `new Option(...` control the selected status of the option.
