### ISSUE TITLE
Select 2 language not working on 4.0.3

### ISSUE THREAD

**Issue by meyacine** [select2/select2#4920]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
[See the fiddle](https://jsfiddle.net/yacmed/hov44u55/)

## Expected behavior and actual behavior
Should be in french
Libraries
- Select2 version: 4.0.3

**Comment by DVD27** [comment]
You should include the translate file after select2.min.js

This doesn't work : 
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/i18n/fr.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.min.js"></script>
```
However, this work perfectly : 
```
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.full.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/i18n/fr.js"></script>
```

See your example with only this two ressources inverted : https://jsfiddle.net/hov44u55/10/

**Comment by alexweissman** [comment]
This is documented here as well: https://select2.org/i18n#language-files

**Comment by ohvitorino** [comment]
Although the documentation states the way the translation files should be loaded (through a textual description), I think an improvement to the current documentation could be to show an example using some HTML.

```html
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.X.X/js/select2.full.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.X.X/js/i18n/fr.js"></script>
```
