### ISSUE TITLE
select2 ajax $request.then(success) can't run on android

### ISSUE THREAD

**Issue by jiuli** [select2/select2#4922]
select2 ajax $request.then(success) can't run on android

select2 ajax $request.then(success) can't run on android,straight do $request.fail(failure)

```
function request () {
      var $request = options.transport(options, function (data) { ####todo,even don't access here。
        var results = self.processResults(data, params);

        if (self.options.get('debug') && window.console && console.error) {
          // Check to make sure that the response included a `results` key.
          if (!results || !results.results || !$.isArray(results.results)) {
            console.error(
              'Select2: The AJAX results did not return an array in the ' +
              '`results` key of the response.'
            );
          }
        }

        callback(results);
      },function () {           **#### straight access here**
        // Attempt to detect if a request was aborted
        // Only works if the transport exposes a status property
        if ($request.status && $request.status === '0') {
          return;
        }

        self.trigger('results:message', {
          message: 'errorLoading'
        });
      });

      self._request = $request;
    }
```

**Comment by jiuli** [comment]
select2 ajax $request.then(success) can't run on android,straight do $request.fail(failure)
function request () {
      var $request = options.transport(options, function (data) { ####todo,even don't access here。
        var results = self.processResults(data, params);

        if (self.options.get('debug') && window.console && console.error) {
          // Check to make sure that the response included a `results` key.
          if (!results || !results.results || !$.isArray(results.results)) {
            console.error(
              'Select2: The AJAX results did not return an array in the ' +
              '`results` key of the response.'
            );
          }
        }

        callback(results);
      },function () {           **#### straight access here**
        // Attempt to detect if a request was aborted
        // Only works if the transport exposes a status property
        if ($request.status && $request.status === '0') {
          return;
        }

        self.trigger('results:message', {
          message: 'errorLoading'
        });
      });

      self._request = $request;
    }

**Comment by alexweissman** [comment]
It is unclear what this issue is asking.  OP appears to be quoting part of the codebase [in `/src/js/select2/data/ajax.js`](https://github.com/select2/select2/blob/062c6c3af5f0f39794c34c0a343a3857e587cc97/src/js/select2/data/ajax.js#L67-L95), but there is no explanation of OP's actual issue or how to replicate it in Android.

Closing as a low-quality issue.
