### ISSUE TITLE
Can't programmatically change the value of a select2 input that loads remote data.

### ISSUE THREAD

**Issue by m-ahmadi** [select2/select2#4923]
Is this normal?
what is going on?

https://codepen.io/mohammad-ahmadi/pen/ybZrbY

**Comment by onaralili** [comment]
following code works 
`$("#btn").click(e => {
  $newOption = $("<option></option>").val("1").text("what")
  $("#el").append($newOption).trigger('change');
});`

**Comment by m-ahmadi** [comment]
Yeah that works, nice.
I'm wondering is it a bug, or is it supposed to be this way?

**Comment by onaralili** [comment]
I don't think it is a bug, this is how you do it in select2 v4.

**Comment by m-ahmadi** [comment]
@onaralili If I change the multiple option to true:
`multiple: true`

then neither of the following will work:

`$("#el").val("what").trigger("change");`

`$("#el").append( $("<option></option>").val("1").text("what")  ).trigger('change');`

`$("#el").val(["CA", "AL"]).trigger("change");`

Am I missing something?

**Comment by m-ahmadi** [comment]
can anybody help?
