### ISSUE TITLE
Select2 list takes 2 clicks to open, when another select2 list is kept opened

### ISSUE THREAD

**Issue by NareshYendluri** [select2/select2#4924]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by NareshYendluri** [comment]
Hi, I am using 5 select2 lists as filters in a form.  When I open one list and try to open another (without closing former one), it wouldn't work. I have to click twice to open the second list. Could you please suggest me if there is any fix for this.

**Comment by William-H-M** [comment]
Hi, this is intended as usually you got to select something first this is done to avoid missclicking out the how to solved it part, not sure how to do it as has never been a problem for my clients.

**Comment by alexweissman** [comment]
This may have been caused by the issue with Select2 losing focus after making a selection (see #4419).  At any rate I cannot replicate this in 4.0.4, so I will assume that #4427 fixed it.
