### ISSUE TITLE
problem with append and Clone div that select 2 in it for multi select 2 with jquery clone

### ISSUE THREAD

**Issue by mamadza** [select2/select2#4925]
## Prerequisites

- I have two problems with select 2 at first on is , 
- I render my page it renderAjax at frist on when i jump from step1 to step2 select 2 is workin correctly but when i go back to step1 and again go to step2 all select 2 don't workin and just show loading with gif

![image](https://cloud.githubusercontent.com/assets/12842935/26527024/22402484-43a0-11e7-9a74-1723674414f8.png)

- the second promblem is , when i go to step4 i have div and there is one select 2 in it and work correctly but in my project i need to clone that div to have another div and select2 in it , but when i clone that div with jquery but the style of select 2 mess , and happen a lot problem in it 

![image](https://cloud.githubusercontent.com/assets/12842935/26526821/91f72bc4-439b-11e7-88e8-b6b39daf3074.png)

Browsers

- [.] Google Chrome
- [. ] Mozilla Firefox
- [. ] Internet Explorer

Operating System

- [. ] Windows

Libraries

- jQuery version: last
- Select2 version: last

**Comment by alexweissman** [comment]
It is unclear what the problem is, or what steps you have taken to debug your code.  Have you tried checking your [browser console](https://learn.userfrosting.com/troubleshooting/debugging#client-side-debugging) for errors?
