### ISSUE TITLE
Apply validation on custom tags

### ISSUE THREAD

**Issue by ankita-bhatt** [select2/select2#4928]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by ankita-bhatt** [comment]
https://select2.github.io/examples.html#tags

Here,The tags need  to be validated as per regex or the type of validation is required like number or text kind of validation

**Comment by jsopenrb** [comment]
There's no built-in validator, but it can be easily added.

In `SelectAdapter.prototype.select` before `if (this.$element.prop('multiple')) {` add this code:
```
    var tags = options.get('tags');
    var tval = options.get('tagValidator');
    if (tags && typeof tval === 'function' && !tval(data.id)) {
        return;
    }
```

Then you can use `tagValidator` option which must be a function that returns `true` if tag is valid.

**Comment by ankita-bhatt** [comment]
Can you please inform me where i need to add this code?

**Comment by jsopenrb** [comment]
src/js/select2/data/select.js

**Comment by ankita-bhatt** [comment]
Thank You.I will try above solution. 
One solution i got is :+1: 

$('select').select2({
  createTag: function (params) {
    var term = $.trim(params.term);

    if (term === '') {
      return null;
    }

    return {
      id: term,
      text: term,
      newTag: true // add additional parameters
    }
  }
});

**Comment by jsopenrb** [comment]
This approach is more correct because you don't have to modify the source. Still, the documentation sucks big time :(

**Comment by alexweissman** [comment]
@jsopenrb the documentation has been improved: https://select2.org

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
