### ISSUE TITLE
Event on clear

### ISSUE THREAD

**Issue by cipriancirstea** [select2/select2#4929]
When setting multiple to true `'multiple' => true` on a select2 widget allowClear is also set to true `'allowClear' => true`, there are two ways to deselect options: 

1. `.select2-selection__clear` which clears all options 
2. `.select2-selection__choice__remove` deselects a single choice

How can I tell the difference between the two? Currently they both trigger the `unselecting` and `unselect` events.

**Comment by ayyash** [comment]
I agree, there is a missed opportunity in not firing an event for the clear action, different from 'unselect'

**Comment by gronostajo** [comment]
Is this a duplicate of #4630?

**Comment by alexweissman** [comment]
@gronostajo yes.  Even though it is older, I will close that issue and leave this one open, as this explains the problem more clearly.

**Comment by alexweissman** [comment]
This has been implemented as of 4.0.6-rc.0.
