### ISSUE TITLE
Set default selection when using ajax select

### ISSUE THREAD

**Issue by sanderhahn** [select2/select2#493]
Is it possible to set the default selection {id: ..., text: ...} or another structure when using the Ajax dropdown? Tried setting both the data: and val: in the select2 jquery call to initial values (the initial value and one data record that contains its id and other values). However this doesn't seem to work... The placeholder seems to be available for the no current selection, or should i use it instead?

**Comment by Natumsol** [comment]
@brentan Thanks, it works for me!

**Comment by onet4** [comment]
In my case,

```
initSelection: function(element, callback) {
    callback({id: 1, text: 'default selection with id 1' });
},
```
had to be 
```
initSelection: function(element, callback) {
    return callback({id: 1, text: 'default selection with id 1' });
},
```
