### ISSUE TITLE
how to set multiple values  via js ?  version:select2-bootstrap-theme.

### ISSUE THREAD

**Issue by willkiy** [select2/select2#4931]
I download the latest version of select2, and I want to use bootstrap theme ,so I selected the version of select2-bootstrap-theme.but when I want to set multiple values for it ,it not work. 
my code:

```
$("#select2-button-addons-single-input-group-sm-1").select2("val",["2126244","3620194"]);
```

file I used:

```
bootstrap/css/bootstrap.css
//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css
bootstrap/css/select2-bootstrap.css
jquery/1.12.4/jquery.min.js
select2/4.0.3/js/select2.full.js
bootstrap/js/bootstrap.min.js
js/anchor.min.js
```

Who can tell me  what the reason is  ? thanks very much

**Comment by zhouDCC** [comment]
hey bro  can you set select2 input-sm

**Comment by Oussama-Tn** [comment]
`$("#your-select-input").val(["val1", "val2"]).trigger("change");`

Check the documentation: https://select2.github.io/examples.html#programmatic

**Comment by alexweissman** [comment]
Yes, the `select2('val', ...` method has been removed and replaced with `.val()`.  See the [documentation](https://select2.org/programmatic-control/add-select-clear-items).
