### ISSUE TITLE
maximum number of display options

### ISSUE THREAD

**Issue by jiuli** [select2/select2#4932]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## How to use

1. added maximumDisplayOptionsLength options in select2
$('#select_id').select2({
    		data:data_info,
    		placeholder:"请您选择",
    		minimumInputLength:1,
    		maximumDisplayOptionsLength:5,
    		language:"zh-CN",width:"349px",
    		templateResult:myTemplateResult,templateSelection:myTemplateSelection
    		});

## the url of changed source 
https://github.com/jiuli/select2

**Comment by alexweissman** [comment]
Hey, thanks for submitting this enhancement! To have this considered for inclusion in the Select2 source, you should [submit a pull request](https://github.com/select2/select2/blob/master/CONTRIBUTING.md#submitting-a-pull-request).

Thanks!
