### ISSUE TITLE
update tags of a select2 gives error (TypeError: b.dataAdapter is null)

### ISSUE THREAD

**Issue by PBrockmann** [select2/select2#4933]
After updating data of a select2, I get the error TypeError: b.dataAdapter is null.
Perhaps I have missunderstood something and would like to know the correct way to do it then.

I have checked this snippet on chrome and get an error as well: "Uncaught TypeError: Cannot read property 'current' of null'

Tested with last 4.0.3 release of select2

 * chrome Version 56.0.2924.87
Uncaught TypeError: Cannot read property 'current' of null

 * firefox 51.0.1 TypeError: b.dataAdapter is null

A jsfiddle is available from: https://jsfiddle.net/PBrockmann/74v2gzhe/

I have described this in a comment at http://stackoverflow.com/questions/41872930/jquery-select2-typeerror-b-dataadapter-is-null

**Comment by alexweissman** [comment]
It's unclear what your code is supposed to accomplish.  The `.change` event is a very generic event that Select2 triggers for just about anything.  You may want to rely on a more specific event like `select2:select`.  See the [events documentation](https://select2.org/programmatic-control/events).

**Comment by alexweissman** [comment]
If you're still having trouble, this question seems better suited to the [forums](https://forums.select2.org).
