### ISSUE TITLE
Trigger event when selecting current option?

### ISSUE THREAD

**Issue by seabasss** [select2/select2#4934]
Can I trigger an event when selecting the already selected option?

on('select2:select') doesn't seem to work for the highlighted option, it just closes the dropdown menu.

When I try on('select2:close') it executes before my on('select2:select') that works for the not highlighted options so I can't use that either. And an onclick on ".select2-results__option--highlighted" executes after it closes the dropdown so that didn't work either.

Ideas? Thanks!

**Comment by seabasss** [comment]
I solved it by putting everythingin a on close so it works for both selecting current and not current now.

But... Is there a way to trigger an event on selecting current anyway? I bet it can be handy.

Thanks

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
