### ISSUE TITLE
Accept HTML inside Options

### ISSUE THREAD

**Issue by GCSBOSS** [select2/select2#4937]
Hello, there!

With little code, I have allowed HTML inside Select2 options on my (company's) local copy. Though, the manager found it unwise to keep a local change to a "constantly updated" library such as Select2 (we do not git it).

So I thought, what about actually making this official?

Then my **feature request**: To add an option to select2 calls, allowing general HTML inside the options.

Just as a note: I accomplished it through... 
- Bypassing the `escapeMarkup` function.
- Removing the `title` attribute for selects with HTML enabled (stripping HTML elements could also work).

Hoping some feedback from the team/community, thanks for your time!

**Comment by alexweissman** [comment]
What would be the purpose of an additional configuration option?  It is already possible to override the `escapeMarkup` function.

**Comment by GCSBOSS** [comment]
What do you mean by "Override"?

**Comment by alexweissman** [comment]
You can simply define a custom `escapeMarkup` callback.  See this example: https://select2.org/data-sources/ajax#additional-examples

**Comment by GCSBOSS** [comment]
I don't know if this feature were available at the time I issued it. The request was fulfilled, anyway!
