### ISSUE TITLE
Cannot close Select2 by clicking outside its container.

### ISSUE THREAD

**Issue by AshboDev** [select2/select2#4939]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Put a select2 item in a container
2. Open the select2 item
3. You can close the select2 by clicking in the container, but not outside of it.

## Expected behavior and actual behavior

When I follow those steps, You're unable to close the select2 when clicking outside of the container (For example when the select 2 overflows the container it's in).

I was expecting the select2 to close if I clicked anywhere on the page.

## Environment

Browsers

- [x] Google Chrome (Version 59.0.3071.82 (Official Build) beta (64-bit))
- [x] Mozilla Firefox (Version 52.0.1)
- [x] Internet Explorer (Version 11)

Operating System

- [x] Windows
- [x] Mac OS X

Libraries

- jQuery version: 3.2.1
- Select2 version: 4.0.3

## Isolating the problem

- [x] The bug happens consistently across all tested browsers
- [x] The bug happens with just select2 and jQuery (See CodePen Below)
- [x] I can reproduce this bug in [a CodePen](https://codepen.io/AshboDev/pen/eRmWvP)
- [x] [Example GIF](https://gyazo.com/da1be3ec8dad8b1c00bb0959fe8b4a45)

**Comment by AshboDev** [comment]
Okay if anyone else is having this issue, it looks like you need to add:

```
html,
body {
  height: 100%;
}
```

I've updated the CodePen to show this too. Such a simple fix... I think it's time for lunch. Been a long day!

**Comment by crazyfree** [comment]
me too, seems the problem is serious

**Comment by lorro** [comment]
Got the same issue after updating to the latest version today ...

**Comment by estebanolm** [comment]
Me too, since upgraded today  4.0.6 version. HELP !!

**Comment by AshboDev** [comment]
Reopening following update which has broken it for others (I'm yet to try the new release)

**Comment by AshboDev** [comment]
Looks like a fix in issue #5499

**Comment by kevin-brown** [comment]
Does this issue still occur in Select2 4.0.8?

I tried reproducing the issue on the original CodePen and could not. And the newer CodePen has the known issue with 4.0.6 stealing focus and not being able to close (regardless of anything else).

The reason why Select2 needs the `<body>` to be the full height of the screen is because Select2 cannot reasonable assign click handlers outside of the `<body>` tag.

**Comment by tronghieu60s** [comment]
i using select2 in modal bs4, click outside not working, when i change position fixed -> relative (modal) everything ok, any solution?

**Comment by JWprogrammer** [comment]
Hi. I faced the same issue and solved it with:
```
html, body {
    height: 100%;
}
```

**Comment by avernet** [comment]
Still having this problem with Select2 4.0.13. Should this be reopened?

> The reason why Select2 needs the `<body>` to be the full height of the screen is because Select2 cannot reasonable assign click handlers outside of the `<body>` tag.

The following listener is triggered for clicks outside of the body. While the aforementioned CSS workaround functions, it shouldn't be necessary, should it? I feel like I am missing something here.

```
document.addEventListener('click', (event) => {
  console.log("Clicked");
});
```
