### ISSUE TITLE
`disabled` property should be added/removed to <option> element when item is disabled/enabled

### ISSUE THREAD

**Issue by UziTech** [select2/select2#4941]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of Select2
- [X] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [X] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Initialize and open select2 with a disabled option
2. change the option to not be disabled
3. Trigger change on select
3. open select2

[jsbin](https://jsbin.com/paquvib/edit?html,js,output)

## Expected behavior and actual behavior

Option should no longer be disabled but it is.

## Environment

Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer

Operating System

- [X] Windows
- [X] Mac OS X
- [X] Linux
- [X] Mobile

Libraries

- jQuery version: 1.12.4
- Select2 version: 4.0.3

## Isolating the problem

- [X] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using Select2 without other plugins
- [X] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by stevekennaird** [comment]
+1 I've been able to replicate this issue

**Comment by UziTech** [comment]
I think this is related to #2250

according to @kevin-brown a call to `.change` [should reload the options](https://github.com/select2/select2/issues/2250#issuecomment-39973381) but it doesn't seem to work

**Comment by alexweissman** [comment]
This is essentially the same issue as #4962, except for the `disabled` property.  The larger issue is that changes to the Select2 dropdown are not automatically reflected in the DOM.

**Comment by 3lue** [comment]
Any update?
