### ISSUE TITLE
"JavaScript runtime error: Object doesn't support property or method 'select2'" in IE11

### ISSUE THREAD

**Issue by nguyenthanhhien** [select2/select2#4947]
I am using latest Select2 4.0.3, jquery 1.10.2 and when I run my website in IE11, it show error "JavaScript runtime error: Object doesn't support property or method 'select2'". How can I fixed?

**Comment by alexweissman** [comment]
Is there a reason why you are still using such an old version of jQuery?

**Comment by nguyenthanhhien** [comment]
Thank for you reply!
I solved this problem on IE11

Thank you so much.

2017-09-11 9:28 GMT+07:00 Alex Weissman <notifications@github.com>:

**Comment by alexweissman** [comment]
No problem, glad you figured it out!

**Comment by nguyenthanhhien** [comment]
Hi Alex Weissman,
I have a problem with select2 html. The selected item is not in the box.
Can you help me solve this issue. I have attached a photo and hope you give
me the solution as soon as possible.
I look forward to replying from you

Thanks,
Hien

2017-09-11 10:51 GMT+07:00 Alex Weissman <notifications@github.com>:

**Comment by alexweissman** [comment]
Please join me on my [chat server](https://chat.userfrosting.com/channel/select2) for further support.  The issue tracker should be reserved for bug reports and feature requests.

**Comment by nguyenthanhhien** [comment]
Thanks for your rely. I have joined your chat server

2017-09-12 22:28 GMT+07:00 Alex Weissman <notifications@github.com>:
