### ISSUE TITLE
How to extends, custom content HTML of options, selection rendered?

### ISSUE THREAD

**Issue by tanobi92** [select2/select2#4948]
I want to use $.fn.select2.amd.require to extends, custom content options, selection rendered.
1. Options: I'm using templateResult option to rerender content, but I want to use $.fn.select2.amd.require to extends.
My code: https://jsfiddle.net/TaNoBi/znpmu81z/7/.

2.Selection rendered: I have so much options, if I select all then it isn't beautiful. I want to if witdh of the tags >= witdh of 'ul .select2-section_rendered' then replace by strings exg: "5 options selected/ 100 options" ...
It same the exg: http://jsfiddle.net/wasikuss/gx93rwnk/ of Vasil Popov.
(https://stackoverflow.com/questions/22918178/select2-with-a-checkbox-list-for-a-multiple-select). 
But he use old version (3.5.4), not sure with new version (4.0.3).
Help me, please! Thank you!

**Comment by xiaohulu** [comment]
+1

**Comment by alexweissman** [comment]
Actually, this has been a long-standing feature request for quite some time.  See #411 for the discussion on this.

There are some alternatives that may help you:

- [Bootstrap Multiselect](https://davidstutz.github.io/bootstrap-multiselect/)
- [select2-multi-checkboxes](https://github.com/wasikuss/select2-multi-checkboxes)
