### ISSUE TITLE
Symfony (3.2)  : TimeZoneType

### ISSUE THREAD

**Issue by rileyrg** [select2/select2#4950]
Applying select2 to a TimeZoneType in Symfony2 gives an empty field sayng  "no data"

```
            ->add('timeZone', TimezoneType::class, [
//                "label" => "person.timezone",
//                "expanded" => false,
//                "translation_domain" => "person",
                'multiple' => true,
                'attr'=>["class"=>"useselect2"],
//                'placeholder' => 'person.choosetimezone',
            ])

```

```
    $('.useselect2').select2({
        dropDownAutoWidth:true
    });

```

Other instances of select2 using a query or array of choices works fine.  (img link)

http://imgur.com/a/Tc2ag

Any pointers?

**Comment by alexweissman** [comment]
It's unclear how this issue relates to the Select2 package itself.  What does Symfony's `TimezoneType` do to the generated HTML?  How is Select2 expected to detect this?

**Comment by alexweissman** [comment]
Please feel free to comment if you have any more insight, and we can reopen the issue.
