### ISSUE TITLE
Facing performance issue in ios 10.3.1 & 10.3.2 - select2 4.0.3

### ISSUE THREAD

**Issue by neelsbr** [select2/select2#4951]
I am facing huge scrolling performance problem in ios 10.3.1 & 10.3.2. Using select2 plugin 4.0.3 version. Same code base working fine iOS 9.*. Can anyone help on this?

**Comment by alex2wong** [comment]
I want to know what huge performance problem, is it moving slowly and influently in large amount of items ??
 you can consider pagination, not display all items in one select. Too many dom elements will pull down the performance. You can refer to my custom [select](https://github.com/alex2wong/es6_module) without JQ dependency, in development.

**Comment by alexweissman** [comment]
I agree with @alex2wong.  You should use pagination to avoid rendering a large number of DOM elements (a common antipattern among new developers).  Other performance issues are likely addressed [elsewhere](https://github.com/select2/select2/issues?q=is%3Aissue+is%3Aopen+label%3Aperformance).
