### ISSUE TITLE
Tags Not Working

### ISSUE THREAD

**Issue by jackryu** [select2/select2#4952]
Tags setting is not working. But this is working with select.

But not possible to update my all control because many CSS bind with my text control.

**Ver : select2-4.0.3**

Data Source : Local Data.

Already used multiple property like : multiple='multiple'|multiple='true'|multiple

HTML

```
 <input id="ddlGroupUnit" type="text" class="form-control js-example-responsive" 
                                placeholder="+ Add Units For Filter" style="width: 100%" multiple />
```

Java Script

```
var defaults = {
                multiple: true,
                tags: true,
                placeholder: "[+] Add Units For Filter",
                allowClear: true,
                minimumInputLength: 2,
                tokenSeparators: [",", " "],
                data: jQuery.parseJSON(responce.d)
            };
```

**Comment by alexweissman** [comment]
Select2 should not be used on `input` controls anymore.  See https://select2.org/upgrading/migrating-from-35#no-more-hidden-input-tags
