### ISSUE TITLE
`selected` property should be added to <option> element when item is selected

### ISSUE THREAD

**Issue by janstieler** [select2/select2#4962]
Hi,

how can I set also the original HTML select option as selected if I select a select2 item?
I need this for saving this information inside an DB. 

I tried this:
```
        var selectBox = '.iconselectfield .selectbox';
        $(selectBox).on("select2:selecting", function(e) {
            $(this).prop('selected', true);
        });
```

But this doesn't add the property selected to the option.
But if I show the value of this in the console (`console.log($(this).val());`) I get the right option value displayed. But if I log only this I get only the selectbox-element displayed.
This is a little bit confusing me.

Cheers

**Comment by kutec** [comment]
Anyone looking into this? I am also facing same challenge.

Actually I am working on a web applicaiton where I have to convert default `<select>` tags with select2 custom dropdown and I did that. The only issue is I am facing is the SYNC.

Sync means, however, the select tag is hidden visually, that might be used for logocal purpose to avoid extra coding with custom one...

Make sense right?

Please do let me know if anyone looking to fix this...

Thanks.

**Comment by alexweissman** [comment]
I'm not sure why this doesn't happen automatically, but in the meanwhile @janstieler's solution should work with a bit of modification:

        var selectBox = '.iconselectfield .selectbox';
        $(selectBox).on("select2:select", function(e) {
            $(this).find(':selected').prop('selected', true);
        });

Note that `.find(':selected')` is needed to get the currently selected items.

**Comment by alexweissman** [comment]
Also related to #4705.  The general issue is that changes made via Select2's API are not consistently reflected in the DOM.
