### ISSUE TITLE
Mobile keyboard reverts to letters when trying to input numeric tag in multi-select

### ISSUE THREAD

**Issue by stdangerous** [select2/select2#4963]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to https://select2.github.com/examples.html in a _**mobile**_ browser
2. Scroll down to the "Tagging Support" section
3.Try to enter a 6 digit number as a tag

## Expected behavior and actual behavior

When I follow those steps, I see...
The numeric keyboard won't stay on numerics. It reverts to the default (lettered) keyboard after two keystrokes.

I was expecting...
to be able to enter in a numeric tag of any length without the keyboard reverting to letters

## Environment

Browsers

- [ x] Google Chrome for iOS
- [x ] Mozilla Firefox for iOS
- [x ] Safari for iOS

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [x ] Mobile

Libraries

- jQuery version: Latest on the select examples page
- Select2 version: Latest on the select examples page

## Isolating the problem

- [ x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ x] The bug happens consistently across all tested browsers
- [x ] This bug happens when using Select2 without other plugins
- [x ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by abdullahseba** [comment]
Having tried this with https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox on all 3 browsers, I could not reproduce the issue using the latest iOS 11.1.2.

**Comment by alexweissman** [comment]
Thanks @abdullahseba !

**Comment by LDVoldemort** [comment]
I have this problem too. But it will have when use multiple select with tag.
