### ISSUE TITLE
Programmatically unselect an option by value in multi-select

### ISSUE THREAD

**Issue by shaikhamir** [select2/select2#4964]
I have a two select2 multi-select field with ID selectOne and selectTwo respectively. I have a button clicking on which I want to change selected option status from selected to deselected.

Providing with the code for which solution is needed. I have mentioned the comment where the code logic is required. Please someone help me on ASAP basis.

**Note: Cosider that all options are selected**

Here is my html code:
<pre>
&lt;select id="selectOne" class="select2-field" multiple&gt;
&lt;option value="optionOne"&gt;Option One&lt;/option&gt;
&lt;option value="optionTwo"&gt;Option Two&lt;/option&gt;
&lt;/select&gt;

&lt;select id="selectTwo" class="select2-field" multiple&gt;
&lt;option value="optionThree"&gt;Option Three&lt;/option&gt;
&lt;option value="optionFour"&gt;Option Four&lt;/option&gt;
&lt;/select&gt;

&lt;button data-val="optionThree"&gt;&lt/button&gt;
</pre>

Here is my script code:
<pre>
<script>
$(".select2-field").select2({
  placeholder: "Select Option",
  allowClear: true
});
$("button").click(function(){
  var val = $(this).attr("data-val");
  /* Want code so that optionThree should get deselected */
});
</script>
</pre>

Libraries

- jQuery version: v2.2.4
- Select2 version: v4.0.3

**Comment by clone1524524** [comment]
I have this same problem as well. I can't seem to find any way to programmatically remove a specific value from the select2's currently selected values.

**Comment by zoltan-sule** [comment]
a solution like this works for me:

`<script>
$(".select2-field").select2({
  placeholder: "Select Option",
  allowClear: true
});
$("button").click(function(){
  var wanted_id = $(this).attr("data-val");
  var wanted_option = $('#selectTwo option[value="'+ wanted_id +'"]');
  wanted_option.prop('selected', false);
  $('#selectTwo').trigger('change.select2');
});
</script>`

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.

**Comment by todsaporn** [comment]
$("#any_select2_element").select2("val", "0");

**Comment by mehulj999** [comment]
> false

Thank you. The comment helped.
I used 
`wanted_option.prop('selected', false);`
