### ISSUE TITLE
minimumInputLength incorrect with Chinese input method

### ISSUE THREAD

**Issue by find1way** [select2/select2#4965]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
I set minimumInputLength 3, I want select2 to start load data when there are at least 3 Chinese characters,  but when I input the first character assume it is "林"，to input this character I need to input
"lin" with my Chinese input method. but when I input this, it start to load data with search term “lin” because "lin" is length is 3.

1.  set minimumInputLength to 3
2.  use chrome browser, use Chinese input method to input charaters. 
3.  when the first Chinese characters pinyin is reach 3 keyboard input, it starts to load data.

## Environment

Browsers

- [ ] Google Chrome
- [ ] Internet Explorer

Operating System

- [ ] Windows

Libraries

- jQuery version: 1.9.1
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
![image](https://user-images.githubusercontent.com/8433664/27326940-967f777c-55df-11e7-855d-c815b4c59da8.png)

this issue will not happen in FireFox browser.

**Comment by erwinyusrizal** [comment]
I have similar issue with @find1way when loading remote data, the `minimumInputLoad: 3` keep requesting ajax when I type 1 or 2 char

**Comment by erwinyusrizal** [comment]
Right now to prevent it keeps loading data everytime I type a char, I use `delay: 300,` to act like a throttle
