### ISSUE TITLE
Dynamic set data when lazy loading

### ISSUE THREAD

**Issue by liorwirt** [select2/select2#4970]
Hello

I am using SELELCT2 version 3.0.1 

I am trying to set data dynamically with javascript and i use 
$("#Field").select2();
$("#Field").val(DATA.trigger("change");

Its work fine with standard lov , but when i checked "Lazy loading" its dont work and i dont see any value.

I was expecting that it will set the value in the filed even when i checked "Lazy Loading".

## Environment

Browsers

- [ ] Internet Explorer

Operating System

- [ ] Windows

Libraries

- apex version:5.1
- Select2 version:3.0.1

## Isolating the problem

- [ ] The bug happens consistently across all tested browsers

**Comment by alexweissman** [comment]
What is "lazy loading"?  If you mean remotely-sourced data, this is now documented: https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2
