### ISSUE TITLE
I want use callback function after <select> has Rendered,how should I do?

### ISSUE THREAD

**Issue by shengpinghu** [select2/select2#4972]
$(id).select2({
			width: '100%',
		       allowClear: true,
			placeholder: "请选择",
			minimumResultsForSearch: Infinity,
		       data: data
		}) 
// callback 
 In here  I  want to  user select>option but select2 Rendered data is asynchronous；
How should I do?

**Comment by alexweissman** [comment]
It sounds like maybe we need some kind of `select2:init` event?
