### ISSUE TITLE
Smooth opening of the drop down menu

### ISSUE THREAD

**Issue by OrionPro** [select2/select2#4973]
I did not find anywhere, how you can make the effect of opening the pop-up menu. Can not I make any built-in tools?
 Type as select2-dropdown .show('fade', 500).

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
