### ISSUE TITLE
Select2 Search box height is broken when loading remote data, if the search box open upward

### ISSUE THREAD

**Issue by ajcastro** [select2/select2#4974]
#### Steps to reproduce

Go to https://select2.github.io/examples.html#data-ajax.
Then try scrolling the page so that select2 element will be on the lower portion of the screen. 
Then try typing/searching and it will open the search box upward. 
The select2 should open upwards. This issue happens only if it open upwards.
Then you will see the issue that when data is loading, the box height is sometimes broken.

**Comment by petlun** [comment]
@ajcastro Did you find a workaround for this issue?

**Comment by alexweissman** [comment]
Are you talking about this?

![screen shot 2017-09-11 at 12 58 36 pm](https://user-images.githubusercontent.com/5004534/30286835-fdf7e3b0-96f0-11e7-93c2-98d44eea60a7.png)

**Comment by alexweissman** [comment]
This is also covered in https://github.com/select2/select2/issues/4969

In the future, please search currently open issues before opening a new one 😄

**Comment by alexweissman** [comment]
This bug has a working solution in https://github.com/select2/select2/issues/4614.  Closing as a duplicate.
