### ISSUE TITLE
Attribute data-placeholder not working

### ISSUE THREAD

**Issue by rorc** [select2/select2#4975]
I cant see placeholder text by default (when nothing selected)
https://jsfiddle.net/rorc/ahhu8vzt/

**Comment by turbod** [comment]
`<select data-placeholder="Chose number" data-allow-clear="true" data-width="50%">
    <option></option>
    <option value="1">Number one</option>
    <option value="2">Number two</option>
    <option value="3">Number three</option>
</select>`

**Comment by rorc** [comment]
Ok, thanks.

**Comment by ashikjs** [comment]
if i add any placeholder on my select2 it say No data found why  !!!

**Comment by seetpalsingh** [comment]
> if i add any placeholder on my select2 it say No data found why !!!

I am facing the same issue.

using placeholder anyhow, that shows no options list


any help plz

**Comment by ashikjs** [comment]
> > if i add any placeholder on my select2 it say No data found why !!!
> 
> I am facing the same issue.
> 
> using placeholder anyhow, that shows no options list
> 
> any help plz

https://select2.org/placeholders did it work for you ?

**Comment by seetpalsingh** [comment]
> > > if i add any placeholder on my select2 it say No data found why !!!
> > 
> > 
> > I am facing the same issue.
> > using placeholder anyhow, that shows no options list
> > any help plz
> 
> https://select2.org/placeholders did it work for you ?


actually, I am using data-* configuration
https://select2.org/configuration/data-attributes

to achieve dynamic input specific placeholder . with version

/*!
 * Select2 4.0.7
 * https://select2.github.io
 *
 * Released under the MIT license
 * https://github.com/select2/select2/blob/master/LICENSE.md
 */

**Comment by alfonsrv** [comment]
This worked for me:

```javascript
  $('[data-toggle="select2"]').each(function(){
      var placeholder = $(this).attr('data-placeholder')
      placeholder = (placeholder === undefined) ? '' : placeholder;

      $(this).select2({
        theme: "bootstrap4",
        placeholder: placeholder,
        width: 'auto',
        inheritClass: true
      });
    });
```
