### ISSUE TITLE
tags flag in firefox webextension popup leads to unresponsive script

### ISSUE THREAD

**Issue by alebx** [select2/select2#4980]
i'm using select2 for tags in a firefox webextension popup, but somehow it ends up in an unresponsive script warning. when i remove the tags flag it works somehow.
these are the lines i use https://jsbin.com/lesukolidu/edit?html,js,output

## Environment

Browsers
- [x] Mozilla Firefox

Operating System
- [x] Mac OS X

Libraries

- jQuery version: 3.2.1
- Select2 version: 4.0.3

**Comment by alexweissman** [comment]
The jsbin you provided seems to work fine.  How can I replicate this?

**Comment by alebx** [comment]
Hey, as stated this concerns a Firefox Webextension Popup, I just created a git-repo with the example: https://github.com/alebx/webext-unresposive-select2-tags.
Thanks for your help!

**Comment by alexweissman** [comment]
Ok, I tried adding it as a "temporary add-on", but I don't see any issues:

![screen shot 2017-09-14 at 12 08 53 pm](https://user-images.githubusercontent.com/5004534/30440857-b85c5ca8-9945-11e7-8f12-a5f4daf54a4c.png)

No errors are showing up in the browser console.

**Comment by alebx** [comment]
Ok, that's strange, here's what I get:
![select2-1](https://user-images.githubusercontent.com/557141/30469887-d5227982-99f2-11e7-8c1d-c090963f7e5d.png)
![select2-2](https://user-images.githubusercontent.com/557141/30469888-d5233750-99f2-11e7-9a46-d7f1b780211c.png)
Looking at the output again I'm not entirely sure if it's just a select2 or even a jQuery issue...

**Comment by alexweissman** [comment]
Have you searched Firefox's knowledge base?  It could be an issue with your version of Firefox.  Or (and keep in mind I don't know that much about browser plugin development), could it be a conflict with some other plugins you have running?

**Comment by alebx** [comment]
Yes, I tried, didn't find anything useful...
Don't know if it's a version issue I've got this problem since my issue-creation and I've always updated the browser btw I'm running a "clean-install" version of Firefox.
I'll post my issue also in the Firefox support forum.
Thanks for your efforts.
