### ISSUE TITLE
On IE >= 11, when deleting the options from the select box on a multiple required field, I cannot submit the form

### ISSUE THREAD

**Issue by lonegro** [select2/select2#4982]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

This only pertain to IE. The features work as expected on Chrome and FF. To reproduce this, select a few options in select2, then delete them and try to submit the form. The required attribute must be present in the tag.

## Expected behavior and actual behavior

When I follow those steps, I see...

On IE >= 11, when deleting the options from the select box on a multiple required field, I cannot submit the form. Furthermore, sometimes the form will submit without an option being selected, even though the field is required.  Any help would be much obliged, thanks

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by igst** [comment]
I have the same issue in IE10. Chrome & FF is like expected.

https://jsfiddle.net/9h68eg6y/

Steps to reproduce scenario A (impossible to post a :valid select):
1. Load the page
2. Press "OK" without selecting an option. 
3. Select an option
4. Press "Ok" 

Result: 
The form will not be submitted anymore. A page refresh is required to be able to submit the form if an option is directly selected after the page refresh. 

Outside of jsfiddle you will get the browsers built-in validation error that the select is a required field. Although an option is selected...

Steps to reproduce scenario B (possible to post a :invalid select):
1. Load the page
2. Select an option
3. Press "OK". - everything is like expected
4. Remove the selected option
5. Press "OK" - 

Result: Form should not be submitted, but will be!

Hope, this will help to fix this issue :-)
