### ISSUE TITLE
Minor visual improvements to classic theme multiselect

### ISSUE THREAD

**Issue by cubiclesoft** [select2/select2#4984]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issues

https://select2.github.io/examples.html#themes

The multiselect example does not accurately mirror v3/classic theme.

The 'x' appears too close to the selected item.

Opening the select causes the rest of the page to jump up 1-2 pixels.  Closing the select causes the page to jump back down 1-2 pixels.

The selected items also have a flat background rather than a gradient.

The demo also has the off-by-one pixel issue but that appears to have been addressed by another, now closed, issue.

## Fixes for issues

```margin-right: 2px;``` is insufficient.  Somewhere around 6-7px is better.

```
.select2-container--classic .select2-selection--multiple .select2-selection__choice__remove {
    ...
    margin-right: 7px;
}
```

```border-bottom: 0 none;``` is the source of the page jump issue.

```
.select2-container--classic.select2-container--open.select2-container--below .select2-selection--multiple {
    border-bottom: 1px solid transparent;
    ...
}
```

Missing ```background-image``` for gradient.  Probably don't need all of the vendor-specific ```linear-gradient``` extensions these days.

```
.select2-container--classic .select2-selection--multiple .select2-selection__choice {
    ...
    background-image: linear-gradient(to bottom, #f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eee 100%);
}
```

**Comment by alexweissman** [comment]
I agree.  Could you submit these changes as a pull request?
