### ISSUE TITLE
what is the use of `loadMorePadding` property ?

### ISSUE THREAD

**Issue by muralishankar** [select2/select2#4987]
no proper sample available for the api. please explain the usecase??

**Comment by ontelo** [comment]
From v3 docs:

Defines how many pixels need to be below the fold before the next page is loaded. The default value is 0 which means the result list needs to be scrolled all the way to the bottom for the next page of results to be loaded. This option can be used to trigger the load sooner, possibly resulting in a smoother user experience.

**Comment by alexweissman** [comment]
Looks like this has been resolved.
