### ISSUE TITLE
Better translation for french language

### ISSUE THREAD

**Issue by Nhooxy** [select2/select2#4988]
In file select2/src/js/select2/i18n/fr.js
This is a better translation :
``` var message = 'Saisissez au moins ' + remainingChars + ' caractère'; ```

**Comment by foxalfabravo** [comment]
var message = 'Saisissez au moins ' + remainingChars + ' caractère(s)' + (remainingChars>1)'s':'';

**Comment by alexweissman** [comment]
Fixed in v4.0.5 (https://github.com/select2/select2/commit/ed24c340289cc952e625cb75adb9d4c0deb447c6).  Sorry we couldn't merge your commit in directly for attribution - there were too many conflicts so we had to use a recursive merge.
