### ISSUE TITLE
Select2 fails with & character in text

### ISSUE THREAD

**Issue by Jojoshua** [select2/select2#4989]
## Prerequisites
- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [X ] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. When using multi selection, a "&" character causes select2 to fail and not show the entry when loading

## Expected behavior and actual behavior

When I follow those steps, I see...the entry fails to add

I was expecting...it to show

## Environment

Browsers

- [X ] Internet Explorer 11

Libraries

- jQuery version: 2.2.4
- Select2 version: 4.0.2

**Comment by alexweissman** [comment]
Can you provide a minimal example of this behavior?

**Comment by Jojoshua** [comment]
Hi, I will close this issue because the problem was due to the way asp.net mvc was pulling in the data.

I fixed this by pulling in the raw value like so

          $("#Test").select2({
                tags: true
            });
			
	var Test_Values = new Array();			
	old: Test_Values.push(@modelValue); --failed when modelValue had & character		
	new: Test_Values.push(@Html.Raw(modelValue)); --works now
	$("#Test").val(Test_Values).trigger("change");
