### ISSUE TITLE
Select2 ajax call return complete page instead of webmethod

### ISSUE THREAD

**Issue by sbqureshi** [select2/select2#4990]
I have used select2 plugin
here is my HTML CODE 
<asp:ListBox ID="drpItemAssociation" SelectionMode="Multiple" size="5" runat="server" multiple CssClass="full-width">
</asp:ListBox>

and my Javascript Code is 

  $('#drpItemAssociation').select2(
{
    placeholder: 'Enter name',
    //Does the user have to enter any data before sending the ajax request
    minimumInputLength: 2,            
    allowClear: true,
    ajax: {
        //How long the user has to pause their typing before sending the next request
        quietMillis: 150,
        //The url of the json service
        url: "../Pages/AjaxWebMethods.aspx/Test",
     data: function (term) {
                     return {
                         term: term,
                     };
                 },
        type: "POST",
        //Our search term and what page we are on
         processResults: function(data) {alert(data)
            return { results: JSON.parse(data) };
        },
    }
});
 and my web method

   [WebMethod(EnableSession = true)]
             public static string Test(string term)
             {
                 string temp = "[{'id':'35','text':'Drew'}]";
                 return temp;
             }

When I entered more than 2 characters then select2 plugin call ajax request to call web method but in my case web method is call

**Comment by alexweissman** [comment]
This is most likely a problem with your API, not Select2.  Please check your server-side code.
