### ISSUE TITLE
autocapitalize should be "none" instead of "off"

### ISSUE THREAD

**Issue by Zodiac1978** [select2/select2#4994]
## Steps to reproduce the issue

See this link: 
https://github.com/select2/select2/search?utf8=%E2%9C%93&q=autocapitalize&type=

Browsers

Mobile Safari (since iOS 5)

`autocapitalize=off` is deprecated in iOS 5.0. Use none instead.

See: https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html

This is just deprecated at the moment, so it is still working. But to be future proof it should be changed.

**Comment by alexweissman** [comment]
Thanks, this should be pretty easy to fix!

**Comment by alexweissman** [comment]
Fixed in v4.0.5.
