### ISSUE TITLE
how is it customize 'No results found'?

### ISSUE THREAD

**Issue by lei159130** [select2/select2#4995]
Such as title.

**Comment by LiuZwen** [comment]
leave

**Comment by nbkjzv6** [comment]
The CSS property for it is .select2-results__message

**Comment by alexweissman** [comment]
Do you want to customize the message itself?  I'm not sure, but this might be handled by the [translation module](https://select2.org/i18n#translation-objects).  We should probably add this to the docs somewhere.

**Comment by alexweissman** [comment]
This might actually be a duplicate of #4088.

**Comment by alexweissman** [comment]
Yeah, this is definitely a duplicate of #4088.
