### ISSUE TITLE
$(selector).select2('close')  throw a error

### ISSUE THREAD

**Issue by MadSummer** [select2/select2#5004]
$(selector).select2('close')
if the selector is not init select2,this code may throw a error ,how can i handle the error with options?
i think this is a internal error，and no need to throw out ,bucause this may interrupt other code run

**Comment by peterw35** [comment]
https://stackoverflow.com/questions/29854022/is-there-any-way-to-check-if-an-element-has-jquery-select2-already-applied-to-it

**Comment by alexweissman** [comment]
This is now documented:

https://select2.org/programmatic-control/methods#checking-if-the-plugin-is-initialized
