### ISSUE TITLE
processResult回调函数中的params.page在哪里？

### ISSUE THREAD

**Issue by guowenwei** [select2/select2#5006]
你好，我在 `data: function (params) {},processResults: function (data, params) `这两个方法中打印了params.page，没有发现没有这个参数，为什么，我哪里写错了？谢谢告知。

**Comment by alexweissman** [comment]
A full example that includes pagination is here: https://select2.org/data-sources/ajax

But you are right, we probably need to document the pagination feature better.

**Comment by alexweissman** [comment]
Pagination is now fully-documented: https://select2.org/data-sources/ajax#pagination
