### ISSUE TITLE
Is there anything we can do about this glitch in multiple select boxes?

### ISSUE THREAD

**Issue by kasperhartwich** [select2/select2#5008]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

![image](https://user-images.githubusercontent.com/616231/29204461-74484614-7e77-11e7-83c2-aff334a626ae.png)

## Steps to reproduce the issue

1. Use Google Chrome
2. Head to the documentation
3. Reload

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by tholu** [comment]
@kasperhartwich Can you describe the glitch or what exactly is the problem?

**Comment by kasperhartwich** [comment]
@tholu See the gifv here:
http://recordit.co/3LSX0HNXtf

**Comment by alexweissman** [comment]
I can't seem to replicate this on the new documentation site (https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox).  I've tried several different versions of Chrome.
