### ISSUE TITLE
Why does the tab out does not work?

### ISSUE THREAD

**Issue by tnayanam** [select2/select2#5009]
So, ideal behaviour of a dropdown is that you tab to a drodown, and then use up and down arrow key to select the option you want and then tab out. And that last focussed drodpown option will be retained as selected. But it is not happening even in the basic example provided in the official web site. 

Let me know if I need to provide more clarity in my question. Why do I have to explicitly use mouse to select the dropdown option. The whole point of this dropdown is to type a keyword, and among the seach result use up and down arrow key to reach the option you want, and then tab out. But it does not work. Please guide me. Unless you explicitly click on the option it does not retain the value. It sets the first option all the time, irrespective of the last focused element.

Steps to reproduce. go to the basis example option, and use up and down arrow key to toggle between options. Now tab out from that dropdown, the last focussed element is not retained. it defaults to the first option all the time.

Also, as in the basic example you have provided a basic html dropdown to compare with. Try the same steps in that basic dropdown, and it will work as expected.
jquery-select2

**Comment by AnilKumar206** [comment]
BaseSelection.prototype.tabindex = function (container) {
                  var self = this;
                  var shiftPressed = false;
                  var clickedOutside = false;
                  //var keyPressed = 0;

                  $('select').on('keydown', function (e) {
                      var keyCaptured = (e.keyCode ? e.keyCode : e.which);
                      //shiftPressed = keyCaptured == 16 ? true : false;
                      if (keyCaptured == 16) { shiftPressed = true; }
                  });
                  $('select').on('keyup', function (e) {
                      var keyCaptured = (e.keyCode ? e.keyCode : e.which);
                      //shiftPressed = keyCaptured == 16 ? true : false;
                      if (keyCaptured == 16) { shiftPressed = false; }
                  });

                  $('select').on('mousedown', function (e) {
                      // remove other focused references
                      clickedOutside = false;
                      // record focus
                      if ($(e.target).is('[class*="select2"]')!=true) {
                          clickedOutside = true;
                      }
                  });

                  $('select').on('select2:opening', function (e) {
                      // this element has focus, remove other flags
                      clickedOutside = false;
                      // flag this Select2 as open
                      $(e.target).attr('data-s2open', 1);
                  });
                  $('select').on('select2:closing', function (e) {
                      var e = window.event;
                      if (e.type == "keydown") {
                          clickedOutside = false;
                      }
                      if (e.type == "mousedown") {
                          clickedOutside = true;
                      }
                      if (e.type == "mouseup") {
                          clickedOutside = false;
                      }
                      $(e.target).removeAttr('data-s2open');
                  });

                  $('select').on('select2:close', function (e) {
                      var elSelect = $(e.target);
                      elSelect.removeAttr('data-s2open');
                      var currentForm = elSelect.closest('form');
                      var othersOpen = currentForm.has('[data-s2open]').length;
                      if (othersOpen == 0 && clickedOutside==false) {
                          /* Find all inputs on the current form that would normally not be focus`able:
                           *  - includes hidden <select> elements whose parents are visible (Select2)
                           *  - EXCLUDES hidden <input>, hidden <button>, and hidden <textarea> elements
                           *  - EXCLUDES disabled inputs
                           *  - EXCLUDES read-only inputs
                           */
                          var inputs = currentForm.find(':input:enabled:not([readonly], input:hidden, button:hidden, textarea:hidden)')
                              .not(function () {   // do not include inputs with hidden parents
                                  return $(this).parent().is(':hidden');
                              });
                          var elFocus = null;
                          $.each(inputs, function (index) {
                              var elInput = $(this);
                              if (elInput.attr('id') == elSelect.attr('id')) {
                                  if ( shiftPressed) { // Shift+Tab
                                      elFocus = inputs.eq(index - 1);
                                  } else {
                                      elFocus = inputs.eq(index + 1);
                                  }
                                  return false;
                              }
                          });
                          if (elFocus !== null) {
                              // automatically move focus to the next field on the form
                              var isSelect2 = elFocus.siblings('.select2').length > 0;
                              if (isSelect2) {
                                  elFocus.select2('open');
                              } else {
                                  elFocus.focus();
                              }
                          }
                      }
                  });

                  $('select').on('focus', '.select2', function (e) {
                      var elSelect = $(this).siblings('select');
                      if (elSelect.is('[disabled]')==false && elSelect.is('[data-s2open]')==false
                          && $(this).has('.select2-selection--single').length>0) {
                          elSelect.attr('data-s2open', 1);
                          elSelect.select2('open');
                      }
                  });

          }


The above code will work for tab out but if i enable  BundleTable.EnableOptimizations = true its not working if i kept false its working strange behaviour.

**Comment by tnayanam** [comment]
@AnilKumar206 : I cannot believe no one has ever brought up this issue. tabbing out is one of the basic requirements for dropdown.

**Comment by younus93** [comment]
Users coming from VB based applications prefer a tab navigation. I hope this gets fixed in the coming releases.

**Comment by alexweissman** [comment]
@tnayanam this is simply not true:
> I cannot believe no one has ever brought up this issue

There are several relevant issues:
- https://github.com/select2/select2/issues/4820
- https://github.com/select2/select2/issues/4578
- https://github.com/select2/select2/issues/4419
