### ISSUE TITLE
Margin on .select2-container affects select2-dropdown

### ISSUE THREAD

**Issue by ghost** [select2/select2#501]
Master has introduced an unexpected behavior where the margin on the `.select2-container` causes additional padding to be placed on the dropdown.

You can see this reproduced here: http://jsfiddle.net/pivotaliex/Vt2A8/1/

The difference being that `.first` has no margin assigned, and `.second` does. The margin causes the dropdown size to become different to the `select2-container`.

We were able to rectify this on line 887

    width = this.container.outerWidth(true),

becomes

    width = this.container.outerWidth(false),

We've no idea of any side-effects of this change though.

Is there a documented testing strategy for select2?

Thanks.

**Comment by ThiRaBrTNK** [comment]
It seems, that this bug(or similar) is back: http://jsfiddle.net/Paul_Kozlovitch/j9Lqw0Lo/1/

**Comment by kevin-brown** [comment]
Doesn't actually appear to be a bug, as we don't set a margin on the container and one shouldn't be set manually.

The container class also wraps the dropdown, so there isn't much we can do to counteract the forced margin.
