### ISSUE TITLE
"Please enter 1 or more characters" message overlapping the input box

### ISSUE THREAD

**Issue by saurabhkpathak** [select2/select2#5012]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
         I am able to replicate it on your examples page.
- [x] This is not a usage question (Those should be directed to the [community]
        (https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue

## Steps to reproduce the issue

1. Go to [](https://select2.github.io/examples.html#data-ajax)
2. Reduce your browser window width till the message "Please enter 1 or more characters" appears in two lines.
3. Scroll the page up to the extent that the `select2-dropdown--above` is opened.
4. Now try clicking select2 - you will see the select2-dropdown overlapping the input box.

## Expected behavior and actual behavior

When I follow those steps, I see...
The select2 dropdown overlapping the input box of the component when the message "Please enter 1 or more characters" appears in two lines.

I was expecting...
The select2 dropdown to be placed above the input box and not overlap it.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Chrome Issue Capture**
When message appears in two lines

![chrome issue](https://user-images.githubusercontent.com/5318888/29310334-490a4368-81a5-11e7-9a73-77f5868e9881.gif)

**Firefox Issue Capture**
When message appears in two lines

![firefox issue](https://user-images.githubusercontent.com/5318888/29310597-3807bcca-81a6-11e7-9a8d-0f3d3566e673.gif)

**Expected behaviour**
When message appears in single line

![expected behavior](https://user-images.githubusercontent.com/5318888/29310618-499b2e86-81a6-11e7-98f5-8ad8df285793.gif)

**Comment by alexweissman** [comment]
Was this only happening on the old documentation site?  On the new documentation site, it seems to look OK:

![screen shot 2017-09-16 at 4 00 28 pm](https://user-images.githubusercontent.com/5004534/30515559-3b2818f8-9af8-11e7-87ba-f9d5751f69c5.png)

**Comment by saurabhkpathak** [comment]
No, this issue is replicable on the new website as well. Apart from this current issue, I found a new issue as well on the new website. When we search by entering any string and the ajax call is made, we then remove the string searched and the suggestion list placeholder jumps up. Please find attached gif for your reference
![select 2 issue](https://user-images.githubusercontent.com/5318888/30517146-9d9eeade-9b4d-11e7-9b11-bdcb0ac57b02.gif)
.

**Comment by alexweissman** [comment]
Ok.  The other issue you reference is actually an already known bug.  See #3905.
