### ISSUE TITLE
when i closed a modal with select2, the select2-drop don't disappear?

### ISSUE THREAD

**Issue by xiyanbox** [select2/select2#5013]
### my select2 version is 3.4.8  
![image](https://user-images.githubusercontent.com/18209483/29353792-fb1fe0d2-829d-11e7-8f68-c717b7c832bd.png)
### only in modal ,how can i do it ?

**Comment by alexweissman** [comment]
See https://select2.org/troubleshooting/common-problems#select2-does-not-function-properly-when-i-use-it-inside-a-bootst.
