### ISSUE TITLE
wrong Templating example in docs

### ISSUE THREAD

**Issue by mkarkachov** [select2/select2#5014]
Please check example http://select2.github.io/select2/#templating

$("#e4").select2({
    formatResult: format,
    formatSelection: format,
    escapeMarkup: function(m) { return m; }
});

Correct version
templateResult: format,
templateSelection: format,

thanks to https://codepen.io/SitePoint/pen/bELxVw

**Comment by alexweissman** [comment]
So http://select2.github.io/select2/#templating is actually the documentation for Select2 3.5.3.  Which version of Select2 are you using?

**Comment by alexweissman** [comment]
The documentation for templating is now available at:

- https://select2.org/dropdown#templating
- https://select2.org/selections#templating

Please let us know if this addresses your questions.
