### ISSUE TITLE
CSS Issue on mobile

### ISSUE THREAD

**Issue by Nadareh** [select2/select2#5017]
Hi, is there a way to fix this bug on mobile? When I open the select options then scroll down a bit the container moved down a bit. http://prntscr.com/gbop48

Thanks

**Comment by Nadareh** [comment]
I was able to fix the issue. I have a css like this: .select2-container { max-wdith: 360px; } and didn't thought there were 2 .selec-container class. So I specifically set the select2-container width and it fix the issue.

**Comment by alexweissman** [comment]
Glad you were able to figure this out.  We do need some documentation of the CSS classes that Select2 creates.  There is already an open issue about this at #2809, so I am closing this one.
