### ISSUE TITLE
How to put times icon after the option

### ISSUE THREAD

**Issue by viva11vidy** [select2/select2#5018]
I have added select2 to my project but that cross icon which is `times` is coming before the option like 
**x Option 1** but i want my option first then that `times` icon like this **Option 1 x** . Any kind of help would be appreciated.

**Comment by tomtobac** [comment]
one simple option is with css 
```
.select2-container--default .select2-selection--multiple .select2-selection__choice__remove {
   float: right;
   margin-right: 0;
   margin-left: 5px;
}
```

**Comment by alexweissman** [comment]
Thanks @tomtobac for the solution.  Everyone, for future help with general usage and troubleshooting, please discuss on the [forums](https://forums.select2.org) instead.
