### ISSUE TITLE
Performance compared to other libraries

### ISSUE THREAD

**Issue by isapir** [select2/select2#5020]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. run the tests on https://jsperf.com/chosen-select2-selectize

## Expected behavior and actual behavior

When I follow those steps, I see... that select2 is orders of magnitude slower than other libraries that offer similar solutions.  See screenshot showing the **other libraries 64 times faster than select2**.

I was expecting... select2 to have comparable performance.

Perhaps the test case is bad, but it's best if someone familiar with the inner workings of select2 will look into it.

![image](https://user-images.githubusercontent.com/885907/29752176-2629fa10-8b0e-11e7-948b-fc5647309649.png)

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by ggppdk** [comment]
Did you see this ?
https://github.com/select2/select2/issues/3854

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:
