### ISSUE TITLE
createTag Method Breaking When Setting 'id' Anything Other Than 'term'

### ISSUE THREAD

**Issue by clockwiseq** [select2/select2#5023]
It may sound crazy, but whenever I implement the *createTag* method, I can't get the *id* to be anything other than the term.  Here's the issue, I am performing a lookup in my database and if no result exists, I want to create a new tag, but I want to set the *id* to an empty GUID (00000000-0000-0000-0000-000000000000).  Here's the code:

```
$('#VendorSelect').select2({
        ajax: {
            url: vendorAPI,
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    partialName: params.term
                };
            },
            processResults: function (data) {
                return {
                    results: $.map(data, function (obj) {
                        return { id: obj.Value, text: obj.Text };
                    })
                };
            },
            cache: false
        },
        minimumInputLength: 3,
        tags: true,
        placeholder: 'Select Vendor',
        createTag: function (params) {
            var term = $.trim(params.term);

            if (term === '') {
                return null;
            }

            return {
                id: term, //'00000000-0000-0000-0000-000000000000',
                text: term,
                newTag: true
            }
        }
    });
```

The code above works, but when I change the `id: term` to `id: '00000000-0000-0000-0000-000000000000'`, the entire lookup/typeahead breaks.

**Comment by alexweissman** [comment]
Were you ever able to figure this out?

**Comment by clockwiseq** [comment]
I have to revisit that code today and I will let you know what I did.  It _did_ start working and I want to say all I did was comment-out some of the options.
