### ISSUE TITLE
Bug - selection on mobile Samsung Browser 5 with loaded remote data 

### ISSUE THREAD

**Issue by reficedev** [select2/select2#5024]
Hi,

this bug is really strange, I have it only on Samsung Browser. http://whatsmybrowser.org/b/JMA4Q7C 

When I click on the 5th element of a select2 option loaded in ajax, just like your exemple (Loading remote data / Select2 ) it select the previous element.

Even if I put this on my css, it select the previous element : 

```
.select2-dropdown{
  position:fixed;
  top:0;
  width: 100% !important;
}
.select2-results__option{
  padding-top: rem-calc(100);
  padding-bottom: rem-calc(100);
  background: #FFF;
  z-index: 100;
}
```

When I type a word, then a space, then I click on the 5th elements, it select the 5th element. no bug here ! Oô
Why is this working when I add a space ?

Samsung browser is the default brower on samsung phone, do you see what is going on ?
thank you

**Comment by alexweissman** [comment]
I don't have access to an Android device so I am unable to confirm this.  Could someone with an Android device please see if they can replicate this behavior?

Also, for the future, please try to use Markdown to format code snippets.  Thanks!

**Comment by kevin-brown** [comment]
This appears to be a duplicate of https://github.com/select2/select2/issues/5457.
