### ISSUE TITLE
When selected value is deleted the combo scale to top-left

### ISSUE THREAD

**Issue by IvoFacundo** [select2/select2#5027]
There is a normal combo with pre-selected values (The first)
![1](https://user-images.githubusercontent.com/13089746/30038799-04fb3b1e-919f-11e7-9038-cdcf904979a9.png)

So when im gonna delete some selected value, the actual combo goes to the top, and the next combo is selected (Deleted BANCO MACRO)
![2](https://user-images.githubusercontent.com/13089746/30038808-1feb52c4-919f-11e7-8206-a7db67afa53f.png)

Any help please? Why does this happen?

**Comment by alexweissman** [comment]
Have you tried changing the value of `dropdownParent`?  Please provide a working demo of this issue, if possible.

**Comment by IvoFacundo** [comment]
sorry, the issue was solved, was a error in jquery was used trigger instead of on function, this active all the controllers an behaviors with the same id :C
