### ISSUE TITLE
Вариант с чекбоксами

### ISSUE THREAD

**Issue by ZeroSteep** [select2/select2#5028]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

## Environment

Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version:
- Select2 version:

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

![image](https://user-images.githubusercontent.com/30858191/30066137-b077041c-925f-11e7-891a-5b20298b3475.png)

Интересует такой момент, можно как то настроить плагин так что бы выпадающий список был как на скриншоте? сразу выбирать несколько вариантов и после они добавлялись в инпут,а не каждый клик один вариант,потом опять кликать искать и т.д. так как вариант выбора может быть штук 50 а кликнуть надо будет 150 для выбора вариантов.

**Comment by alexweissman** [comment]
I'm not sure if I completely understand, as Google translate isn't perfect.  You want to be able to select multiple items from a checklist, without opening/closing the dropdown each time, right?  There is the `closeOnSelect` option:

```
$('select').select2({
  closeOnSelect: false
});
```

However, are you sure that Select2 is the best choice for this situation?  If they're making 50+ selections, the "pillbox" style of displaying selections might not be the best user experience.

**Comment by ZeroSteep** [comment]
Вы правильно поняли мой вопрос. В целом я по смотрел по документации к вашему плагину вполне подходит ваш плагин за исключением того что я писал ранее. про 50 раз это я образно, но вариантов может быть несколько и каждый раз открывать закрывать это конечно напрягает. С точки зрения пользователя это не очень удобно и понятно. когда есть чекбоксы как у меня на скриншоте это удобноее опять же для пользователя.(Пользователь видит что он нажал,что выбралось и сколько) при этом есть поиск опять же удобно.
Еще хотелось бы узнать рельно ли сделать несколько select в одной форме но выбранные варианты добавлялись и отображались в одном инпуте по принципу как на скриншоте ниже???

![image](https://user-images.githubusercontent.com/30858191/30096968-d22ccafe-92e3-11e7-90c9-33aede52fb49.png)

Надеюсь вы правильно поймете мой вопрос. Спасибо.

**Comment by alexweissman** [comment]
Well there is certainly a good chance that I am misunderstanding your question, since I do not speak Russian and am relying on Google Translate.  

So, does `closeOnSelect: false` address your use case?  If not, then we can mark this as a feature request for now.  I'm not a developer on this project (only a maintainer) so I won't be able to implement this for you.

**Comment by ZeroSteep** [comment]
closeOnSelect: false подходит но не на 100%. все же самих чекбоксов не хватает.
Плюс к этому возможность взаимодействия нескольких select с одним input в пределах одной формы было бы вообще идеально, и придало бы большей универсальности плагину)

**Comment by alexweissman** [comment]
Got it.  I'm just going to leave an English translation here, for future reference:

> `closeOnSelect: false` is appropriate but not 100%. all the same checkboxes are not enough. 
Plus, the possibility of interacting multiple select with one input within one form would be generally ideal, and would give a more versatile plug-in)

**Comment by alexweissman** [comment]
Actually, this has been a long-standing feature request for quite some time.  See #411.

There are some alternatives that may help you:

- [Bootstrap Multiselect](https://davidstutz.github.io/bootstrap-multiselect/)
- [select2-multi-checkboxes](https://github.com/wasikuss/select2-multi-checkboxes)
