### ISSUE TITLE
cannot get selected values if value come from initSelection with ajax 

### ISSUE THREAD

**Issue by temala** [select2/select2#5029]
when i use ajax for loading data I cannot use
.select2('val', [selectedId]);
to set init values

But if I use initSelection only and try to get selected values after that using 
.select2('data');
I got empty array but in the ui I see the selected values.

**Comment by alexweissman** [comment]
Both `.select2('val')` and `initSelection` have been deprecated in Select2 v4.  You should simply use `.val` to set the value.

**Comment by temala** [comment]
Hi,

This is what worked for me:

` for (var i = 0; i < interlocTechClientIds.length; i++) {
                    var $option = $("<option selected></option>").val(interlocTechClientIds[i].id).text(interlocTechClientIds[i].text);
                    $('#interlocTechClient').append($option);
                }`
And then just applu select2
` $("#interlocTechClient").select2({ajax: { url: 'xxx/eee'}})`

no need for .val() at all 
when select2 will find options in the target select it will fill init data.

All other combiniation will fail at some point. the best I got is to show the selected data but when trying to get value a got null.

thanks for reacting.

**Comment by alexweissman** [comment]
Great!  This is very similar to [the approach I use in my projects](https://stackoverflow.com/questions/25428361/dynamically-add-item-to-jquery-select2-control-that-uses-ajax/35386009#35386009).  You do need to call `.trigger('change')` on the control after `append`ing the new option, though.

**Comment by alexweissman** [comment]
This is now documented: https://select2.org/programmatic-control/add-select-clear-items
