### ISSUE TITLE
Images or icons

### ISSUE THREAD

**Issue by kurdtpage** [select2/select2#5031]
This is an awesome project, the only thing missing from this is support for images or icons. I have found that this is possible using [jQuery UI Selectmenu](https://jqueryui.com/selectmenu/#custom_render), but when integrating both it doesn't seem to work (see this [jsFiddle](https://jsfiddle.net/kurdtpage/af60nghy/4/))
Here is an example of what I mean:
![screenshot from 2017-09-06 19-36-06](https://user-images.githubusercontent.com/1308716/30099722-b33fcf5e-933a-11e7-848c-694e4425caf7.png)

**Comment by alexweissman** [comment]
This is supported using the `templateResult` option: http://docs.select2.org/dropdown#templating

**Comment by kurdtpage** [comment]
Oh sorry didn't see that. Thanks.
