### ISSUE TITLE
Unable to Add Data Attribute for Custom Value with Tag

### ISSUE THREAD

**Issue by clockwiseq** [select2/select2#5036]
When I manually add an option to the select, I need to include a custom data attribute.  How is that done?  When I use AJAX to get the items, this works fine:

```
processResults: function (data) {
    return {
        results: $.map(data, function (obj) {
            return { 
                id: obj.Id, 
                text: obj.LastName + ', ' + obj.FirstName, 
                company: obj.Company 
            };
        })
    };
}
```

But I need to load these results back into the select2 as tags upon load and I can't get the extra data property (company) added:

```
$.each(dtlPatients, function (index, patient) {
    $('#PatientListControl').select2().append('<option value="' + patient.Id 
           + '" data-company="' + patient.Company + '">' + patient.Name + '</option>');
});

$('#PatientListControl').val(selpatlist).trigger('change');
```

Am I adding the data attribute properly?  Is there a better way to manually add the tags to my select2?

**Comment by alexweissman** [comment]
What happens if you use the `.data` method on your newly created options, rather than setting them via HTML attributes?

**Comment by alexweissman** [comment]
Also, see https://github.com/select2/select2/issues/4877

**Comment by clockwiseq** [comment]
4877 doesn't help at all.  The links provided in the thread are just redirects to the new documentation (Configuration page).  I'll see if I can manually set the data attribute after creating the option and see if it's available afterwards.  My question is, is that the correct way to storing that custom bit of data?  When I create a tag via the ajax call, how is that stored on the option?  Is it a data-* attribute?

**Comment by clockwiseq** [comment]
After looking at the source after my items have loaded (via ajax), I don't see the data anywhere, so I'm assuming it's a value stored elsewhere.  So, manually adding the data-* attribute to my option isn't going to work anyway.

**Comment by alexweissman** [comment]
>  Is it a data-* attribute?

I'm actually not sure.  Can you try using your browser console to dump the contents of Select2's internal representation of an option?

**Comment by clockwiseq** [comment]
I'm not 100% sure on how to do that, but, I did inspect the element and didn't see any data attributes for the options.  So, I'm assuming the extra info I'm adding during the ajax call is being stored elsewhere and that's what I need to modify on load.

**Comment by alexweissman** [comment]
This might help: https://learn.userfrosting.com/troubleshooting/debugging#client-side-debugging

**Comment by alexweissman** [comment]
Actually, have you tried the approach given in the new docs?  See https://select2.org/programmatic-control/retrieving-selections

**Comment by clockwiseq** [comment]
This is how I'm retrieving the selections, `.select2('data')` and that works when I have selections that are made after I initialize the select2 with an ajax lookup.  The problem is, apparently I don't know how to preload the select2 with previous selections AND have it still perform the ajax lookup because I just tested it again, and when I manually preload the selections (via adding `<option>`) to the select, the select2 ajax lookup function doesn't work.  That might be the majority of my issue.  

Here is a screenshot of a debug session comparing what the `.select2('data')` results look like when it's a pure ajax lookup vs me preloading an option:

![image](https://user-images.githubusercontent.com/6662538/30330036-92c4d59a-9799-11e7-8283-1c27d3a09af7.png)

**Comment by clockwiseq** [comment]
@alexweissman , here's the question...when I initialize my select2, I do the following:

```
$('#PatientListControl').select2({
    ajax: {
        url: patientAPI,
        dataType: 'json',
        delay: 250,
        data: function (params) {
            return {
                lastName: params.term
            };
        },
        processResults: function (data) {
            return {
                results: $.map(data, function (obj) {
                    return { 
                        id: obj.Id, 
                        text: obj.LastName + ', ' + obj.FirstName, 
                        company: obj.Company 
                    };
                })
            };
        },
        cache: false
    },
    minimumInputLength: 3,
    tags: true,
    placeholder: 'Select Patient(s)'
});
```

Notice how in the `results: $.map(data, function (obj) {` call, I can add whatever I want to the object and it's appended as a new property to the option (native select2 option I'm assuming).  BUT, when I want to manually add options to the select2, I don't have any way of adding those extra properties because I only have the ability to add a `<option>` to the `<select>` itself.  Is there an API call I can make to select2 that will allow me to add a selection in an object format similar to that of the `$.map` method?

**Comment by alexweissman** [comment]
Thanks, the screenshot and code sample have cleared this issue up a lot for me.  Could you join me in my [chat server](https://chat.userfrosting.com/channel/select2) and we can discuss it further?

**Comment by clockwiseq** [comment]
I'm there.

**Comment by MikeMajara** [comment]
Any advances on this? Given select2 has the option to render the selected option with additional data it might bring from ajax, it would make sense to have some way to set this data too...

**Comment by bashmakovartur** [comment]
58

**Comment by tijokj** [comment]
var _dataVals = $("#ddlName").select2('data')[0];
//console.log(_dataVals);
console.log(_dataVals.element.dataset['empid']);
console.log(_dataVals.element.dataset['bu']);
console.log(_dataVals.element.dataset['designation']);

**Comment by tijokj** [comment]
> What happens if you use the `.data` method on your newly created options, rather than setting them via HTML attributes?

var _dataVals = $("#ddlName").select2('data')[0];
//console.log(_dataVals);
console.log(_dataVals.element.dataset['empid']);
console.log(_dataVals.element.dataset['bu']);
console.log(_dataVals.element.dataset['designation']);
