### ISSUE TITLE
Search a data field in addition?

### ISSUE THREAD

**Issue by seabasss** [select2/select2#5042]
Hey!

Is it possible to search an additional data field in Select2? Thinking something like this (just an example):

```
<option value="foo" data-extra-search="{'other':'bar'}">baz</option>
$(...).select2({
    dataAttr: 'data-extra-search',
    searchField: ['value','text','other']
});
```

**Comment by alexweissman** [comment]
Since the entire `data` object is passed in to a custom `matcher`, couldn't you just do this with a [custom matching callback](https://select2.org/searching)?  And of course if this is a remote data source, you can implement it on the server side.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
