### ISSUE TITLE
Click Input search

### ISSUE THREAD

**Issue by Triden** [select2/select2#5043]
Hey. Is it possible to split the click event by search and by the selected items? I want, that at "multiple", the window was not closed at a click on an <input>.

**Comment by alexweissman** [comment]
It is unclear what you are asking for.  Are you asking for a new type of event to be fired?

There are a number of [already open issues](https://github.com/select2/select2/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20event) that request new types of events.  Please check if any of these are already asking for what you want.

**Comment by Triden** [comment]
I changed the css. I need that, when clicking on the "input", the window will not close. I need to get the input focus and that's it. When you select an item. The window jumps to the top. How can I disable this?
![screenshot_5](https://user-images.githubusercontent.com/16622856/30775397-36888b7c-a09b-11e7-954d-a4c80c91eec9.png)

**Comment by alexweissman** [comment]
I'm really not sure what you're asking.  Have you searched the open issues?  There are a number of issues already open about:

- The search field losing focus
- The window jumping to the top after making a selection

**Comment by Triden** [comment]
Sorry, I do not speak English well. 2 point, yes. The first point, no. I will describe it later.

**Comment by Triden** [comment]
Sorry, I do not speak English well. 2 point, yes. The first point, no. I will describe it later.

**Comment by alexweissman** [comment]
Please feel free to comment if you have any more insight, and we can reopen the issue.
