### ISSUE TITLE
https://select2.org/ does not work

### ISSUE THREAD

**Issue by ctientcheu** [select2/select2#5044]
the site for select 2 4.x.x does NOT work
hence no documentation is available for select2 4.x.x

**Comment by jonahgreenthal** [comment]
It works fine, and the documentation is available other ways too, so your premise, reasoning, and conclusion are _all_ wrong.

**Comment by alexweissman** [comment]
@ctientcheu could you explain what you mean by "does not work"?  It seems to be working fine for me.  Are you getting a specific error message?

**Comment by ctientcheu** [comment]
This site can’t be reached

select2.org took too long to respond.
Try:
Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

**Comment by alexweissman** [comment]
Can you join me in chat (https://chat.userfrosting.com/channel/select2) so we can try to debug this further?

**Comment by holtkamp** [comment]
seems to work fine... https://select2.org

**Comment by jpic** [comment]
I <3 the new website, thank you so much @alexweissman !!

**Comment by jpic** [comment]
Ok, I think users are searching for a link to find the right documentation version on select2.org. Perhaps this is an issue we should open upstream on Upstream on Grav ?

**Comment by jpic** [comment]
Please, let us know your IP address if it doesn't work. You can get it from http://ifconfig.co

**Comment by alexweissman** [comment]
@jpic you mean for 3.5.x?  We should probably have a link from select2.org, I agree.

**Comment by ctientcheu** [comment]
Sorry was on vacation.
The issue seems to be resolved for me now. I can consistenly reach the web site.

**Comment by ctientcheu** [comment]
Thanks for your support @alexweissman and immediate response

**Comment by alexweissman** [comment]
No problem!  Maybe it was just a DNS propagation issue.  Glad it's resolved :-)

**Comment by AVANG003** [comment]
I have a problem with access to https://select2.org/
The error is ERR_SSL_VERSION_OR_CIPHER_MISMATCH.
The error appears under Chrom and Opera. But under FireFox all works fine.

**Comment by alexweissman** [comment]
@AVANG003 we had some brief downtime a few days ago.  Are you still having an issue with our SSL certs?
