### ISSUE TITLE
How to use it with Bower?

### ISSUE THREAD

**Issue by serhioV** [select2/select2#5047]
I tried to use it with bower, but there is any CSS files not release folder inside... Could someone update the documentation to reflect this point ?

More than that, bower does not detect (editing bower.json in Visual Studio) the latest version of the component, so it proposes the generic "*"...

**Comment by alexweissman** [comment]
We actually use Bower to load Select2 for [UserFrosting](https://www.userfrosting.com), and it works fine.  Have you tried:

```
    "dependencies": {
        "select2": "4.0.3"
    }
```

Relative paths should be `vendor/select2/dist/css/select2.css` and `vendor/select2/dist/js/select2.full.js`.

**Comment by alexweissman** [comment]
This is now documented: https://select2.org/getting-started/installation#installing-with-bower
