### ISSUE TITLE
select2:unselect fires before changing value in single-select dropdowns

### ISSUE THREAD

**Issue by gronostajo** [select2/select2#5049]
1. Create a single-select dropdown with `allowClear`
2. Subscribe to `select2:unselect` event
3. Select some option
4. Click the clear button (_X_)
5. `$(dropdown).val()` still returns the value in event handler
6. Now do the same with multi-select. When `select2:unselect` fires, the value is already removed.

## Expected behavior and actual behavior

This should be consistent for single-selects and multi-selects. Currently for single-selects `select2:unselect` event is fired before removing the value, but for multi-select value is already removed when the event fires.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [?] Internet Explorer

Operating System

- [x] Windows
- [?] Mac OS X
- [?] Linux
- [?] Mobile

Libraries

- jQuery version: 3.2.1
- Select2 version: 4.0.3, master (#c454407)

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a gistrun](https://gist.run/?id=033b9625607481e21d39e535c6487dab)

**Comment by alexweissman** [comment]
Does it even clear the value at all, for single select?  See #4845.

**Comment by gronostajo** [comment]
Yes, everything seems to work correctly except for the event which is sent too early. (see the gistrun)

As a workaround, the unselect callback can be wrapped in `setTimeout`.

**Comment by alexweissman** [comment]
Agreed, it should clear the value before triggering the event.  Can you please check the issues and open PRs carefully, to see if this has been mentioned before?  I'd be quite surprised as this is a pretty obvious bug.

**Comment by gronostajo** [comment]
I have looked at event- and unselect-related issues and haven't found anything similar.

I imagine that it could be useful to know what was just unselected, but it would be better to pass it as an event field.

**Comment by gronostajo** [comment]
Please see PR #5058 for a fix.

Actually, removed items are already sent as event data, so I have just reversed clearing and event emitting.

**Comment by Stadly** [comment]
If I understand correctly, the issue here was that `select2:unselect` fired too early. Maybe https://github.com/select2/select2/issues/4371 is similar, that `select2:select` fires too early as well, so the value is not populated? If that is the case, maybe it can be fixed in the same way?

**Comment by alexweissman** [comment]
It's possible.  #5058 has already been merged in and released in the 4.0.6-rc.0 pre-release.  So, you can try updating to the pre-release and see if that fixes your issue.  That would also help us test the pre-release and get it ready for a stable release!
