### ISSUE TITLE
Custom MultipleSelection adapter not firing events

### ISSUE THREAD

**Issue by danjac** [select2/select2#5050]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x ] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
Create a custom MultipleSelection adapter (not tried with SingleSelection adapter).

No events (select2:select etc) are being fired. Events are fired as normal when not using the custom adapter. 

```
    $.fn.select2.amd.require([
        "select2/utils",
       "select2/selection/multiple",
       "select2/selection/placeholder",
    ], function (Utils, MultipleSelection, Placeholder) {

      var CustomSelectionAdapter = Utils.Decorate(MultipleSelection, Placeholder);
      // we just want to display the number of results
   
      CustomSelectionAdapter.prototype.update = function(data) {
        this.clear();
        var html = '<div>' + data.length + ' RESULT(S)</div>';
        var $rendered = this.$selection.find('.select2-selection__rendered');
        Utils.appendMany($rendered, [html]);
      };

      var $select = $('#my-form select');

      $select.select2({
        closeOnSelect: false,
        selectionAdapter: CustomSelectionAdapter,
      });

      $select.on("select2:select", function(event) {
        console.log("select"); // THIS IS NOT BEING FIRED
    }); 
```

## Expected behavior and actual behavior

Expected: "select2:select" event to be fired
Actual: event not fired

## Environment

Browsers

- [x ] Google Chrome
- [x ] Mozilla Firefox
- [ ] Internet Explorer

Libraries

- jQuery version: 3.1.1
- Select2 version:4.0.3

**Comment by alexweissman** [comment]
I'm not sure if you pasted all of your code, but it looks like you're missing a closing `};` for the outer function definition.

At any rate, does _any_ code in that outer function get called?  Can you try placing a `console.log` outside of the `.on` callback?

**Comment by danjac** [comment]
Yes, closing } missing from paste, sorry about that.

Otherwise yes, code is working fine other than no events being called.

**Comment by alexweissman** [comment]
> There doesn't appear to be any documentation or examples on how events are handled with custom adapters.

Yes, we desperately need someone who knows how this works internally, to write some documentation/tutorials for implementing custom adapter/decorators.  Without good documentation, this powerful feature is not going to be very useful ☹️

**Comment by danjac** [comment]
Solution appears to be this:

Utils.Decorate only accepts 2 arguments (base class + decorator class).

So you can only add one class at a time:

```
    function (Utils, MultipleSelection, Placeholder, EventRelay) {

      var CustomSelectionAdapter = Utils.Decorate(MultipleSelection, Placeholder);
      CustomSelectionAdapter = Utils.Decorate(CustomSelectionAdapter, EventRelay);
```
Adding EventRelay in this way triggers all the required events.

**Comment by alexweissman** [comment]
Nice!  Any interest in maybe writing up a brief tutorial on custom adapters for the docs?  See https://github.com/select2/docs/tree/master/pages/14.advanced

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:

**Comment by krishna-suwal** [comment]
if anyone don't know the dependency path for `EventRelay`, here it is:
`select2/selection/eventRelay`
