### ISSUE TITLE
Select2 ajax init does nothing.

### ISSUE THREAD

**Issue by codeincolor** [select2/select2#5054]
I'm having an issue with the select2 (4.0.3) ajax call for the "type ahead" function. I originally had this as an input then changed it to a select to support the 4.0 requirement. I've confirmed its hitting the initialize for Select2.  I've also confirmed that the url passed is good. Everything I have should be working based on the documentation. What am I missing?
I appreciate a second set of eyes. Thanks for your help.

HTML

```
<select 
  id="medList2" 
  placeholder="Drug" 
  class="select2" 
  style="width: 200px;" 
  data-sequence="80" 
  data-parent-id="4" 
  data-id="80" 
  data-label="Drugs" 
  data-bind-0="4-80"></select>
```

Javascript

```
$('#medList2').select2({     
        ajax: {              
            url: '/path/todata/',
            dataType: 'json',
            delay: 250,
            type: "POST",
            // id: getUnid(),
           // contentType: "application/json",
            data: function (term) {                   
                return {
                    Prefix: term
                };
            },
            processResults: function (data) {                  
                return {
                    results: $.map(data, function (item) {
                        return {
                            text: item.Text,
                            id: item.ID

                        }
                    })
                };
            },
            cache: true
        },
        placeholder: 'Choose Meds',
        minimumInputLength: 2           

    });
```

**Comment by alexweissman** [comment]
@codeincolor you need to use three backticks, on their own line, to format code blocks in Markdown.  See [this guide](https://learn.userfrosting.com/troubleshooting/getting-help#use-markdown-to-format-blocks-of-code).  I've fixed it for you this time.

**Comment by alexweissman** [comment]
Are you getting any errors in your browser console?  Does it seem to be submitting the AJAX request?  If so, what are the contents of the request (including any query string parameters)?

**Comment by codeincolor** [comment]
Hi Alex, Thanks for responding.  Hoping a second set of eyes is all thats needed.
I'm getting no errors in my browser console, nothing in the network traffic. url is definitely not being hit.  Not even a 404.  It almost seems that select2 doesnt like my settings, or something is being skipped in the initialization.  (also confirmed it is initializing) 
using select2.full.js V: 4.0.3

**Comment by alexweissman** [comment]
Actually, the AJAX request should not be fired until the dropdown is actually opened.  Is it even adding the expected styling to the target element?

**Comment by codeincolor** [comment]
Right.  My test is expecting it to trigger after two characters are entered. yes the select2 shows the drop down with the "no results found"

**Comment by alexweissman** [comment]
Ah, ok.  The title of this issue is very misleading - it sounds like it is initializing just fine, but just not triggering the ajax request.  "Does nothing" doesn't tell me much.  Can you try to reproduce this issue in a jsbin please?

I also have a question for you - why are you using a POST method to retrieve your selection options?

**Comment by codeincolor** [comment]
yeah I guess it is from a point of view.  Sorry for that. My understanding was the initialization set the hook for the trigger.
I'm not sure if I can properly reproduce it as my url link is proprietary. 
I don't necessarily have to use post.  Its just a habit I formed from past experiences of not getting data to and from the server via ajax.

**Comment by alexweissman** [comment]
Ok, yes, you should definitely use a GET request.  This is part of the HTTP specifications and [RESTful design](https://en.wikipedia.org/wiki/Representational_state_transfer#Relationship_between_URL_and_HTTP_methods).  HTTP methods are all about the "verb" that describes how you are interacting with your resources.  A `POST` request should only be used when you are **creating** a new resource on the server.  Simple data retrieval is always a `GET`, regardless of the transport mechanism.  So, GET/POST have nothing to do with ajax.

Other than that, I'm not really sure.  You have `cache: true` set, so maybe your browser is caching a previous bad request?

I'm not really sure what a proprietary link is (unless it has some authentication token in it), but are you sure that it's a well-formed URL?

**Comment by codeincolor** [comment]
I'll replace the POST with a GET.  yeah my company has to strictly follow HIPAA standards. so makes for difficult public info sharing  :)
I am trying to make a jsbin with a public web service link just for testing purposes.
The link is good.  I've tested it with a straight ajax call and it works fine.
I'll get back to you with my results.  Thank you Alex

**Comment by codeincolor** [comment]
Hi Alex,
I've never used jsbin before I've attached my sample.  I am noticing different behavior from the sample verses my local project.  the control doesn't update the instructional text as the user types. (ie: please select 2 or more characters)
[jsbin.holuhifare.1.zip](https://github.com/select2/select2/files/1330912/jsbin.holuhifare.1.zip)

**Comment by alexweissman** [comment]
http://jsbin.com :-)

**Comment by alexweissman** [comment]
Yes, the sample you sent appears to be functioning properly.  I can see it making the AJAX requests as I type (though the URL itself is returning 404 errors), and updating the search results message accordingly.

**Comment by codeincolor** [comment]
That looks to be the same issue Alex.  As the user types the events should fire as well. (updating the display text based on the minimumInputLength variable  etc..)  Somehow none of the events are getting hooked.  II did confirm that the control's init was being hit

**Comment by alexweissman** [comment]
Is it working for you otherwise?  Maybe you should join me in my [chat room](https://chat.userfrosting.com/channel/select2) so we can investigate this in real-time.

**Comment by codeincolor** [comment]
Hi Alex, I'm in the chat room now
Thanks
Joe

**Comment by alexweissman** [comment]
Looks like we got this figured out in chat - it appears to have been an interaction with some other non-Select2 code.

**Comment by zschuessler** [comment]
For anyone hitting this issue: I ran into this when using Vue, separately. If Vue is anchoring to a container that your Select2 initialization is in, something breaks so that AJAX never triggers.

Moving my one-off script of Select2 initialization _after_ the Vue container worked beautifully.
