### ISSUE TITLE
Select2 doesn't work in jqueryUI dialog

### ISSUE THREAD

**Issue by kselax** [select2/select2#5055]
Hello!
When I open dialog jQueryUI I get there not active search field. 
I added this code 
```
open: function () {
      if ($.ui && $.ui.dialog && !$.ui.dialog.prototype._allowInteractionRemapped && $(this).closest(".ui-dialog").length) {
        if ($.ui.dialog.prototype._allowInteraction) {
          $.ui.dialog.prototype._allowInteraction = function (e) {
            if ($(e.target).closest('.select2-drop').length) return true;
            return ui_dialog_interaction.apply(this, arguments);
          };
          $.ui.dialog.prototype._allowInteractionRemapped = true;
        }
        else {
          $.error("You must upgrade jQuery UI or else.");
        }
      }
    },
```

and the select2 search field started work, But I get other errors in console namely 'undefined this function ui_dialog_interaction. 
Why select2 doesn't work and how to force it works?

**Comment by alexweissman** [comment]
Not sure why this is such a common mistake but, you need to use three backticks, on their own line, to format code blocks in Markdown.  See [this guide](https://learn.userfrosting.com/troubleshooting/getting-help#use-markdown-to-format-blocks-of-code).  I've fixed it for you this time.

**Comment by alexweissman** [comment]
So, it's unclear what this has to do with Select2.  You should try to create a full example in jsbin.com that demonstrates the issue and how it relates to Select2.

**Comment by alexweissman** [comment]
Please feel free to comment if you have any more insight, and we can reopen the issue.
