### ISSUE TITLE
Non Latin characters issue

### ISSUE THREAD

**Issue by d3sign3r** [select2/select2#5057]
Hi! i save values in Greek languages and when i use select2 it appears those weird characters  "Î Î¿ÏÏÏÎ·ÏÎ± ÎÎ¬ÏÎ±ÏÎ·Ï" in the dropdown list.

The words are saved with no problem in database in Greek language. The only problem is when i try to retrieve them using the select2 plugin !! :(

Any idea???

**Comment by alexweissman** [comment]
Do the characters appear to render normally on other parts of your web page (outside of the Select2 control)?

**Comment by d3sign3r** [comment]
@alexweissman yes everything outside the select2 control work just fine !! even in the database the words are stored without problem with the greek characters !!

**Comment by alexweissman** [comment]
> even in the database the words are stored without problem with the greek characters !!

Well yes, of course they need to be stored and returned properly from the server in the first place.

How are you retrieving your values?  From a remote data source, or via an [array source](https://select2.org/data-sources/arrays)?

Can you reproduce the problem in http://jsbin.com?

**Comment by alexweissman** [comment]
Please feel free to comment if you have any more insight, and we can reopen the issue.
