### ISSUE TITLE
The select can't work when it is in a fancybox

### ISSUE THREAD

**Issue by happytor** [select2/select2#506]
When i put the selector in a fancybox(with jquery.fancybox plugin), the style is ok, but i choose a item ,it does nothing

**Comment by jherman** [comment]
I'm not able to get it working fancybox as well:

http://jsfiddle.net/ej7hr909/7/

**Comment by jafaripur** [comment]
Same issue!

**Comment by rorc** [comment]
Try .select2-dropdown { z-index: 9999 }

**Comment by mjot** [comment]
Select to appends the dropdown before the closing body.

So it is better to append it to your modal window, using the parameter "**dropdownParent**" like this:

`$('select').select2({
    dropdownParent: $('#myOverlay')
  });`

**Comment by sweiguny** [comment]
@mjot This option seems promising, but it does not exist in version 2 of select2, does it?

**Comment by miladhamzelou** [comment]
thanks to @projct1 . works for me.

**Comment by iamtomjones** [comment]
This worked a treat for me.  Thanks, @mjot.
