### ISSUE TITLE
Placeholder usage should be consistent among single- and multi-selects

### ISSUE THREAD

**Issue by alexweissman** [select2/select2#5060]
As per the [documentation](https://select2.org/placeholders#text-placeholders), the usage of placeholders is different among single- and multi-selects:

> In order for a string placeholder value to appear, you must have a blank `<option>` as the first option in your `<select>` control. This is because the browser tries to select the first option by default. If your first option were non-empty, the browser would display this instead of the placeholder. Note that this issue does not apply to multiple selects.

So in single-select, placeholders won't work without the `<option></option>`.

However in multi-select mode, having an empty placeholder option actually _causes_ an issue where this empty value gets added as a selection whenever another item is selected.  See #4742, with an example [here](http://jsfiddle.net/k81hwwdb/).

What's more, this appears to be further complicated by the use of `allowClear`.  See #4367 and #4880.

I propose that Select2 should handle creating the empty `<option>` element internally when needed (or some other workaround), providing a consistent interface for placeholder usage in both single- and multi-select scenarios.

**Comment by kevin-brown** [comment]
I just want to note that this was proposed way back when in https://github.com/select2/select2/issues/3553.

The write up on there is 2 years old, so things very well may have changed, but it addresses the difficulties around creating the empty `<option>` element internally.
