### ISSUE TITLE
bug/feature:  select2 event handlers should not exist after destroy

### ISSUE THREAD

**Issue by dmitrykurmanov** [select2/select2#5064]
Hello, team. Thanks for your work!

## Prerequisites
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [x] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue
please see the clean plnkr example: https://plnkr.co/edit/jNrNfWC9JMXi37EGIxdy?p=preview (please open the console)

## Expected and actual behavior

**actual:** after destroy a DOM Element has select2 event handler 
**expected:** after destroy a DOM Element doesn't have any select2 event handlers

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: last
- Select2 version: 4.0.4

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/) - see [plnkr](https://plnkr.co/edit/jNrNfWC9JMXi37EGIxdy?p=preview)

**Comment by alexweissman** [comment]
This is expected.  See #4403.
