### ISSUE TITLE
combine multiple selections into a single summary (e.g., "3 items selected")

### ISSUE THREAD

**Issue by cromartie1984** [select2/select2#5065]
Hi,

Is it possible to have a multiple selection without tags ?

in the selection, we would have something like : 3 items selected.

**Comment by alexweissman** [comment]
Tagging and multi-select are two distinct features.  Please avoid using the term "tag" because that actually refers to [dynamic option creation](https://select2.org/tagging).

**Comment by alexweissman** [comment]
FWIW, it would appear that [Bootstrap multiselect](https://davidstutz.github.io/bootstrap-multiselect/) supports this feature.  It might already be doable in Select2 with `templateSelection` - I'm not really sure.

**Comment by WillemOpperman** [comment]
Have a look at my fiddle. I managed to put something together
https://jsfiddle.net/Lkkm2L48/7/

**Comment by alexweissman** [comment]
Nice!  Seems like we need some sort of place to organize community-contributed solutions like these.  Maybe this would be good to post in the new forums, under [Ecosystem](https://forums.select2.org/c/ecosystem)?

**Comment by alexweissman** [comment]
This appears to be a duplicate of #2965.
