### ISSUE TITLE
Strings as ID in multi-select input utilizing preselect won't get filled properly

### ISSUE THREAD

**Issue by sn0opy** [select2/select2#5066]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. have `multiple: true` enabled
2. have multiple pretty high `id`s. E.g. "304375898662150154" (must be string due to floating point issues in JS!)
3. use `data-preselect` to pre-fill input fields utilizing also pre-defined values in the `data` parameter of `select2()` initialization. 

## Expected behavior and actual behavior

All input fields are empty.

I was expecting to see them properly filled. One can actually force those fields to be filled, if you use actual numbers instead of strings as `id` parameter. Eventhough that is not an option, since that will result in wrong IDs later on in my backend code. 

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Safari

Operating System

- [x] Mac OS X

Libraries

- jQuery version: 2.2.4
- Select2 version: 4.0.4

## Isolating the problem

- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using Select2 without other plugins
- [x] I can reproduce this bug in [a jsbin](https://jsbin.com/lerinatabi/edit?html,js,output)

**Comment by alexweissman** [comment]
So actually, the `id` _should_ be a string.  See https://select2.org/data-sources/formats#automatic-string-casting:

> Because the `value` attribute on a `<select>` tag must be a string, and Select2 generates the `value` attribute from the `id` property of the data objects, the `id` property on each data object must also be a string.

I don't think Select2 is at fault here, though.  Are you sure that you're parsing the content from `data-preselect` properly?  When I replace your callback with a hardcoded `'183933567424941536'` in `.val()`, it works fine.

**Comment by sn0opy** [comment]
@alexweissman looks like I found a fix. The last one is the most interesting one which is probably not the actual way to go. The Third snippet works for me.

```js
// data-preselect="[ '183933567424941536' ]"
$('#test').data('preselect')
"[ '183933567424941536' ]"

// data-preselect="[ 183933567424941536 ]"
$('#test').data('preselect')
[183933567424941540]

// data-preselect='[ "183933567424941536" ]'
$('#test').data('preselect')
["183933567424941536"]

// data-preselect="[ &quot;183933567424941536&quot; ]"
$('#test').data('preselect')
["183933567424941536"]
```

**Comment by alexweissman** [comment]
Might be worth taking a look at the specifications for `.data` and how they parse `data-*` attributes: https://api.jquery.com/data/#data-html5
