### ISSUE TITLE
A multiple select box with CloseOnSelect: false jumps to top of dropdown list

### ISSUE THREAD

**Issue by fakeharxy** [select2/select2#5067]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [x] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Have a multiple select box
2. Have closeOnSelect set to false 
3. Scroll down and select something
4. You will jump to the top of the dropdown list

## Expected behavior and actual behavior

When I follow those steps, I see... a jump to the top of the dropdown list

I was expecting... not to jump to the top of the dropdown list, so that I can continue to select more items at the same point in my long dropdown list

## Environment

Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [X] Windows
- [X] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 3.2.1
- Select2 version: 4.0.3

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [X] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
I'm pretty sure that this is already a known issue.  Are you _certain_ that you:

> searched for similar issues in both open and closed tickets and cannot find a duplicate

?

**Comment by alexweissman** [comment]
Actually I'm gonna answer that for you.  No, because there is already an issue about this at #4417.

**Comment by fakeharxy** [comment]
Thanks for your help
