### ISSUE TITLE
Input box shrinks in multiselect AJAX mode

### ISSUE THREAD

**Issue by sslotsky** [select2/select2#507]
I am using a multiselect in AJAX mode, and there are some weird things that make the input box shrink. 

If I focus on the box, each character I type causes the width to shrink, until it is barely visible. I would not expect the box to change size at all as I'm typing in it.

If I select some options, the box will grow as expected. I'd also expect the box to shrink when options are removed. However, when I remove the last option, it again shrinks the width down to an unusable size. I would expect the box to return to its original state.

The input that the select2 functionality is attached to is pasted below:

`<input id="full_query_parent_id" type="text" placeholder="Select Some Options" name="full_query[parent_id]" multiple="multiple" style="display: none;">`

Here is the javascript that attaches the select2 functionality to this input:

```
$('#full_query_parent_id').select2({
  multiple: true,
  minimumInputLength: 1,
  ajax: {
    url: "/ces/organizations/search_by_name.json",
    dataType: 'json',
    data: function (term, page) {
      return {
        term: term
      }
    },
    results: function(data, page) {
      return { results: _.map(data, function(result) { return { id: result.id, text: result.name }; }) };
    }
  }
});
```

I would make a JSFiddle for this but that seems complicated given the AJAX component. If you have something I can fork that calls off to a server, or if you can recommend a public API that I can use for this, I will try to throw one together. But hopefully you can see my error by looking at my code above. 

Thanks!

**Comment by patmcgee1983** [comment]
Same issue as described above, however, using a select box instead of text. I was able to work around it by forcing a min width on the box after ajax requested data populated it.

```
$("#regions").append(output)
$('.multiselect').select2()
$(".select2-selection").css("min-width","300px")
```
