### ISSUE TITLE
Select2 with AJAX stopped working after update to jQuery 3.2.1 from 3.1.1

### ISSUE THREAD

**Issue by sharky98** [select2/select2#5070]
Hello,

Sorry to not use the expected template, I don't have the time to do everything required there.

Basically, I had working Select2 code for AJAX retrieval of some data, all looking similar to the following. I was using Select2 4.0.3 (from the nuget package) and jQuery 3.1.1. When I only updated jQuery to 3.2.1, the fields stopped working. The AJAX request works (seen from the developer tools), but nothing is shown to the client (not even the "no result found").

```javascript
$('#select2Field').select2({
    ajax: {
        url: '@Url.Action("SearchItem", new { area = "Ajax", controller = "SelectList" })',
        dataType: 'json',
        delay: 750,
        data: function (params) {
            return {
                q: params.term
            };
        },
    },
    minimumInputLength: 2,
    placeholder: 'Please select an item.'
});
```

The returned JSON look like:
```javascript
{"results":[{"Id":"500","Text":"Item A-2035"},{"Id":"563","Text":"Item B-2035"}]}
```

Libraries

- jQuery version: 3.2.1
- Select2 version: 4.0.3

Thank you for your help

**Comment by alexweissman** [comment]
> I don't have the time to do everything required there.

We're all busy.  If you don't have time to follow the requirements, then we don't have time to help you.  Create a jsbin that replicates this issue and we can reopen it.

**Comment by sharky98** [comment]
Ok, it seems that something else broke Select2 here. I've create two JSBin, one with jQuery 3.1.1 and one with jQuery 3.2.1 and both doesn't work on Chrome 61.0.3163.100 or on Firefox 56.0.

The same behavior occurs on my own project on both Firefox and Chrome. The only thing that changed that since last time it was working (that I'm aware of) is jQuery 3.1.1 to 3.2.1. But downgrading to jQuery 3.1.1 didn't resolve the issue. Note that on my project, this behavior occurs on different machines too.

On my server, I see that the AJAX request is sent correctly back to the form, only Select2 doesn't seem to parse it.

https://jsbin.com/tokiruyora/edit?html,js,output

https://jsbin.com/xokedecuze/edit?html,js,output

I'm kind of lost now...

**Comment by alexweissman** [comment]
So, I noticed that your mock data has `Id` and `Text` instead of `id` and `text`.  JSON, like most things in the programming world, is case-sensitive...

**Comment by sharky98** [comment]
Stupid me... Thank you! The update to the C# class that generate the JSON, but it was only "styling" changes (attributes `id` became property `Id`, same for text) and it was done at the same time of the jQuery update.
