### ISSUE TITLE
Add stopPropagation to remove choice handler

### ISSUE THREAD

**Issue by printercu** [select2/select2#5075]
Hi!

I've faced the problem using select2 with multiple=true inside bootstrap's dropdown: selecting new values worked fine but clicking on `x` to remove choice closed dropdown leaving select2's list.

It's suggested to add `stopPropagation` to click handlers to prevent dropdowns from closing, like it's done in bootstrap for forms: https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L428

I've ended with this monkey-patch to make everything work:

```js
  var MultipleSelection, old_bind;
  MultipleSelection = $.fn.select2.amd.require('select2/selection/multiple');
  old_bind = MultipleSelection.prototype.bind;
  MultipleSelection.prototype.bind = function() {
    old_bind.apply(this, arguments);
    return this.$selection.on('click', '.select2-selection__choice__remove', function(evt) {
      evt.stopPropagation();
      return false;
    });
  };
```

Do you think if this `stopPropagation` should be added to select2's default behaviour? Or this example to docs?

PS. Thanks for using prototypes instead of private local functions :)

**Comment by alexweissman** [comment]
Is this the information that is supposed to be covered in the "preventing events" section?  See https://github.com/select2/docs/issues/5

**Comment by printercu** [comment]
I'm not sure. Seems like that section is for preventing select2 internal events. But this one is about preventing click event. I have this for preventing dropdown close, but it works for everything except this `x` buttons:

```js
  $(document).on('click', '.dropdown-form', function(e) {
    e.stopPropagation();
    return false;
  });
```

I think this is because they got removed from document in select2 handler, and this delegated handler is not fired. So the question was more about adding `stopPropagation` to select2 implementation.

**Comment by printercu** [comment]
Or this snippet can be placed to cookbok, if there will be one.

**Comment by alexweissman** [comment]
Actually, did you know about the [`closeOnSelect`](https://select2.org/dropdown#forcing-the-dropdown-to-remain-open-after-selection) configuration option?  Maybe a `closeOnRemove` option would be a useful complement to this.

**Comment by printercu** [comment]
This options affects select2 dropdown behaviour, but i'm about bootstrap's dropdown which contains select2 input.

**Comment by printercu** [comment]
I hope we can close this one.
