### ISSUE TITLE
Using tags and tokenSeparators cause the last tag to be ignored when pasting a list of tags

### ISSUE THREAD

**Issue by lehmayr** [select2/select2#5076]
## Steps to reproduce the issue

1. Init select2 on select[multiple] with tags: true, tokenSeparators: [" "]
2. Paste a text with some spaces.
3. All tags except the last one are added directly.
4. The text of the final tag is entered in the text field. (But the input field width is much too small!)
5. Press enter.

You can actually test this behavior on the examples page: https://select2.org/tagging#automatic-tokenization-into-tags by pasting this text: red green blue

## Expected behavior and actual behavior

Actual: The dropdown opens without any "term" as if the input field was empty.

Expected: I was expecting that it would open the dropdown as if I had entered the text of the final tag.

## Environment

Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer

Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 1.12.4
- Select2 version: 4.0.4

## Isolating the problem

- [x] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
Looks like this was discussed in #3458 and partially fixed, but I can confirm that there is still a problem with the last selection.  Looks like others have [confirmed this as well](https://github.com/select2/select2/issues/3458#issuecomment-286138282).

**Comment by nino-s** [comment]
The last "word" is written to the search value, but select2 does not recognize this value. I am searching for a better solution atm, but if we explictly call an input event `this.$search.trigger('input');` after the focus event on line 61 in `tokenizer.js L:61`, the problem disappears.

**Comment by aleksblendwerk** [comment]
Are there any news on this or some kind of workaround?

**Comment by scottpchow23** [comment]
It _seems_ like a fence posting problem. If you take the reproduction steps above and instead drop "red green blue " (yes, trailing space), then the select2 picks up on all terms.

**Comment by aleksblendwerk** [comment]
So has this been fixed or just been buried?

**Comment by Neokyuubi** [comment]
Just letting you know that if you put a **space** at the end of you tags (or what ever is the **delimiter**)
It's gonna work

Ex : "one two three "

**Comment by taneung** [comment]
> Just letting you know that if you put a **space** at the end of your tags (or what ever is the **delimiter**)
> It's gonna work
> 
> Example : "one two three "
> 
> Edit :
> This is how i did as a workaround.
> 
> ```
> $('body').on('paste', '#myInput', function (event)
> {
> 	let delemiter = ' ';
> 	let clipboardData = event.clipboardData || window.clipboardData || event.originalEvent.clipboardData;
> 	let newTags = clipboardData.getData('text/plain');
> 	if (!newTags.endsWith(delemiter)) {
> 		newTags += delemiter;
> 	}
> 	event.preventDefault();
> 	event.target.value = newTags;
> 	return false;
> });
> ```

Thank you so much for update.

**Comment by lvalladares** [comment]
This is still happening in 4.0.13

**Comment by Apezdr** [comment]
Still happening on latest release.

**Comment by salehasadi** [comment]
> Just letting you know that if you put a **space** at the end of your tags (or what ever is the **delimiter**)
> It's gonna work
> 
> Example : "one two three "
> 
> Edit :
> This is how i did as a workaround.
> 
> ```
> $('body').on('paste', '#myInput', function (event)
> {
> 	let delemiter = ' ';
> 	let clipboardData = event.clipboardData || window.clipboardData || event.originalEvent.clipboardData;
> 	let newTags = clipboardData.getData('text/plain');
> 	if (!newTags.endsWith(delemiter)) {
> 		newTags += delemiter;
> 	}
> 	event.preventDefault();
> 	event.target.value = newTags;
> 	return false;
> });
> ```

this breaks the functionality of creating tags when I remove values of box by pressing backspace
on first paste works as expected
![image](https://user-images.githubusercontent.com/14921568/109658870-5066af00-7b7c-11eb-9bf0-b200b02b648d.png)

but after delete stuffs and try paste again not:
![image](https://user-images.githubusercontent.com/14921568/109658788-3927c180-7b7c-11eb-82e7-01de57e618e1.png)
