### ISSUE TITLE
Documentation of user-defined width option is confusing

### ISSUE THREAD

**Issue by aurovrata** [select2/select2#5078]
## Steps to reproduce the issue

1. enable a $('select').select2({
width:{100%}
});

## Expected behavior and actual behavior

expect select2 dropdown to use 100% of its parent container

**Comment by alexweissman** [comment]
I believe `width` is a scalar, not an object:

```
$('select').select2({
    width:'100%'
});
```

See the [docs](https://select2.org/appearance#container-width).  I believe you are confused because we are using `{}` to represent a placeholder.  Maybe this can be clarified somehow.

**Comment by alexweissman** [comment]
Ok, I have switched to the `<>` notation, which hopefully is more universally recognized as a placeholder indicator.
