### ISSUE TITLE
Trouble with multiple, allowClear and backspace clear option

### ISSUE THREAD

**Issue by subtronic** [select2/select2#5080]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of Select2
- [ ] This is not a usage question (Those should be directed to the [community](https://select2.github.io/community.html))
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to [here](https://select2.org/selections), for example.
2. Open console.
3. Write code  (from example): 
`$('select').select2({
  placeholder: 'This is my placeholder',
  allowClear: true
});` 
4. Go to the last select2 on the page
5. Select two option (without last focus) try to delete one item using backspace.
## Expected behaviour and actual behaviour

When I follow those steps, I see unexpected behaviour. One backspace removes all selected option. 

I was expecting to remove only last selected option or destroy tag and add text from tag to search input value.

## Environment

Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.2.4
- Select2 version: 4+

## Isolating the problem

- [ ] This bug happens [on the examples page](https://select2.github.io/examples.html)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using Select2 without other plugins
- [ ] I can reproduce this bug in [a jsbin](https://jsbin.com/)

**Comment by alexweissman** [comment]
I'm pretty sure this is a duplicate.  Are you _sure_ you searched the open issues?

**Comment by subtronic** [comment]
Yeah, I searched, and found bugs where people dislike remove tag method, then remove just by sing, not all tag. But I have a problem when for 1 backspace tap, removed all selected tag. And this bug repeated on the official documentation.

**Comment by William-H-M** [comment]
@alexweissman If not wrong this a duplicate [or at least the track] of #3335

**Comment by alexweissman** [comment]
@William-H-M thanks.  I have changed the title of #3335 to make it easier to find.  It seems like this issue is duplicated every few weeks!
