### ISSUE TITLE
Conflict with Bootstrap Dropdown

### ISSUE THREAD

**Issue by eSPiYa** [select2/select2#5086]
## Prerequisites

This should have been fixed in this issue: https://github.com/select2/select2/issues/2173

After updating to v4.0.4 it happens again. 

## Steps to reproduce the issue

[Here is the version using the v4.0.4](http://jsfiddle.net/a5dcwrvx/1/)
When you click the search box, the Bootstrap dropdown closes

## Expected behavior and actual behavior

Expecting the generated elements are siblings of the visible select control but the dropdown content of select2 was generated at the bottom as direct child of the <Body> element

## Environment

Browsers

- [ X] Google Chrome
- [ X] Mozilla Firefox
- [ ] Internet Explorer

Operating System

- [X ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

Libraries

- jQuery version: 2.1.3
- Select2 version: 4.0.4
- Bootstrap version: 3.3.7

**Comment by alexweissman** [comment]
This issue is well-documented:

https://select2.org/dropdown#dropdown-placement

You simply need to set a `dropdownParent` in your Select2 configuration: 

`dropdownParent: $('.dropdown-menu')`
