### ISSUE TITLE
Select2 the selector closes when click/enter on tag

### ISSUE THREAD

**Issue by pklaparda** [select2/select2#5087]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate

## The Problem

I was fetching all data from ajax but I recently added custom tags by:
`tags: true`
the problem is when clicking, or enter, on custom tags, sometimes work and get in the:
`.on("select2:select".. ` event and everything goes well, 
but sometimes the selector just closes

an example: searching "a"

- click on the selector
![1](https://user-images.githubusercontent.com/28009203/31773338-d3ebbcaa-b4b8-11e7-8f61-a9c7b008eeca.jpg)
- search "a"
![2](https://user-images.githubusercontent.com/28009203/31773352-dc5f1bc0-b4b8-11e7-9817-7abb352fb602.jpg)

- the selector closes after click or enter on "a"
![3](https://user-images.githubusercontent.com/28009203/31773356-e08d5cde-b4b8-11e7-8446-3cc497217c14.jpg)

but something even more odd happens if after trying to search "a" several times I search for "s" or any other word or letter.. it works

my code:
<pre>
buscador.select2({
    placeholder: "Ingrese el producto a buscar..",
    ajax: {
        url: window.getProductosBuscadorController,
        dataType: "json",
        delay: 250,
        data: function (params) {
            return {
                filtro: params.term, // search term
                page: params.page || 1,//params.page,
                pageSize: AutoCompletePageSize
            };
        },
        processResults: function (data, params) {
            params.page = params.page || 1;
            return {
                results: data,
                pagination: {
                    more: data.length >= AutoCompletePageSize
                }
            };
        }
    },
    minimumInputLength: 1,
    theme: "classic",
    templateResult: formatImage,
    tags: true
}).on("select2:select", function (e) {
    console.log(e);
});
</pre>
processResults, ajax and everything works great except this little weird problem with custom tags

hope you guys can give me a useful hand or a hint to get whats going on, thanks!
## Environment

Libraries

- jQuery version: "2.2.3"
- Select2 version: "4.0.2"

**Comment by alexweissman** [comment]
Have you looked at #4842?  This might be the same issue.

**Comment by pklaparda** [comment]
I've just checked.. it's exactly this same issue and seems there's no solution yet.
