### ISSUE TITLE
Virtual Keyboard not appearing for Select 2 search box for some devices

### ISSUE THREAD

**Issue by Azayro** [select2/select2#5090]
I have a select 2 element with a search box. When I tap it on iPhone 7 the keyboard opens and allows for typing into the search box without further tapping. With iPhone 6 and iPad Mini (these are just examples) it requires the user to tap the select 2 element and then to tap the search box to bring up the virtual keyboard. 

Is this a device limitation or is there some javascript that I could add to ensure the keyboard comes up when a select 2 w/ search is tapped/selected.

**Comment by alexweissman** [comment]
I believe this is already a known issue - have you searched the open issues?

**Comment by Azayro** [comment]
I have searched it but cannot find anything specifically related to this.

**Comment by alexweissman** [comment]
What OS are you using on the iPhone 6 and iPad Mini devices? The version of iOS is probably more relevant than the device itself.

**Comment by Azayro** [comment]
iPhone 6 - v8, also 6S - v9
iPad Mini 4 - v9.3

**Comment by abdullahseba** [comment]
All of the devices mentioned are up to iOS 11 so that probably doesn't help.
