### ISSUE TITLE
Preselecting options in an remotely-sourced (AJAX) Select2 with custom data atribute not work

### ISSUE THREAD

**Issue by TihomirS** [select2/select2#5091]
hi, i use:
https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js

my html:

> <select name="serv_id" id="serv_id" class="form-control select2s" style="width: 100%;"></select>

initilalization:

>$('.select2s').select2({
>	placeholder: 'Select an service',
>	ajax: {
>	  url: '_get_services.php',
>	  dataType: 'json',
>	  delay: 250,
>		/*
>	  processResults: function (data) {
>		  //console.log(data);
>		return {
>		  results: data
>		};
>	  },
>		*/
>		processResults: function (data) {
>           return {
>               results: $.map(data, function (obj) {
>                    return { 
>                       id: obj.id, 
>                        text: obj.text, 
>                        price: obj.price 
>                    };
>                })
>            };
>        },	
>	  cache: false
>	}
>});

both processResults work correct with:

>var data=$("#serv_id").select2('data')[0];
console.log(data.price);

when i try code from documentation - https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2

>var sSelect = $('.select2s');
>$.ajax({
>    type: 'GET',
>	dataType: 'json',
>    url: '_get_service.php?sid=<?=$row_p["serv_id"];?>'
>}).then(function (data) {
>	console.log(data);
>    // create the option and append to Select2
>    var option = new Option(data.text, data.id, data.price, true, true);
>    $('.select2s').append(option).trigger('change');
>    // manually trigger the `select2:select` event
>    sSelect.trigger({
>        type: 'select2:select',
>        params: {
>            data: data
>        }
>    });
>});

console log shows - correct values but select is not changed. 
I can find other case to set custom data attribute with Ajax on initialization.
This may be same but closed - https://github.com/select2/select2/issues/5036

Is this a bug or my mistake?

**Comment by TihomirS** [comment]
on-line page - view-source:http://offers.balkanecommerce.com/t.php

**Comment by alexweissman** [comment]
#5036 is actually still open, so you should post your link there if you think it is related.

Also, you have formatted your code blocks incorrectly.  You need to use a "code fence", not a quotation in your Markdown.

At any rate, this seems like a usage question, which you should post on the [forums](https://forums.select2.org).

**Comment by TihomirS** [comment]
when i use 'inser code' my blocks a not readable .. but this is my problem.
i spend one day to try this to work.. read many posts and materials .. when i use code from documentation and this not work .. for me is a problem.
i will post it again in forums.
best,T.

**Comment by alexweissman** [comment]
You need to use code fences (triple backticks), not single backticks.  See https://learn.userfrosting.com/troubleshooting/getting-help#use-markdown-to-format-blocks-of-code
