### ISSUE TITLE
Setting AJAX defaults causes select2 to always make requests regardless of data attributes (or lack thereof)

### ISSUE THREAD

**Issue by mseymour** [select2/select2#5092]
I am trying to keep things simple by having a single class to be used for creating all needed select2 dropdowns. However, I find that when I set up AJAX defaults, select2 wants to only use the current page (if the URL is not set)  as the source and not the options.

Example: http://jsbin.com/pefaqezabu/1/edit?html,js,output

Is this by design, should I instead have a separate class for non-AJAX dropdowns?

**Comment by alexweissman** [comment]
This is a support question, so you should be asking on the [forums](https://forums.select2.org).
