### ISSUE TITLE
Removing styling for `select2-selection__placeholder` class for multi-selects

### ISSUE THREAD

**Issue by alexweissman** [select2/select2#5094]
I noticed that there are some CSS rules for `select2-selection__placeholder` in the default theme's SCSS assets:

https://github.com/select2/select2/blob/master/src/scss/theme/default/_multiple.scss#L19-L25
https://github.com/select2/select2/blob/master/src/scss/theme/default/_multiple.scss#L66

But for multi-select, placeholders are always displayed using the `placeholder` attribute on the search control.  So, is there any point to these rules in `_multiple.scss`?

**Comment by kevin-brown** [comment]
As far as I can tell, this class should only ever be used with a single select. So those CSS rules can be safely dropped.

There was a point in time where the multi-select placeholder was not using the `placeholder` attribute, which would explain why this was necessary at one point.

**Comment by kevin-brown** [comment]
Fixed in https://github.com/select2/select2/pull/5508
