### ISSUE TITLE
initSelection is not being executed 

### ISSUE THREAD

**Issue by rudresh4** [select2/select2#5096]
I'm unable to get my select2 to pick an initial value. Below is the code I'm using, can anyone tell me what I'm doing incorrectly?

```javascript
    $("#customer")
        .select2({
            theme: "bootstrap",
            placeholder: "Select Customer",
            selectOnClose: true,
            initSelection: function (element, callback) {
                callback({id: 12, name: 'Chicken' });
            }
        })
```

My ERB being:
```erb
<%= load_form.select(:consignee_id, list_customers(), {}, class: 'form-control', id: 'customer') %>
```

With the function list_customers returning:
```ruby
>> list_customers()
 [ ["Chicken", 12], ["Cow, 14] ]
```

**Comment by alexweissman** [comment]
The issue tracker is not an appropriate place for general support, as per our [contribution guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help) _and_ the message that appears when you try to create a new issue.  The fact that you opened this issue indicates to me that you didn't bother to read either of these.

Please ask on our [forums](https://forums.select2.org/) instead.
