### ISSUE TITLE
Animate open/closeing

### ISSUE THREAD

**Issue by HawkonDK** [select2/select2#5097]
How do I animate the open/closing so its slide up/down ??

And can I change it so I click on a example a icon to open the selection ?

**Comment by alexweissman** [comment]
The issue tracker is not an appropriate place for general support, as per our [contribution guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help) _and_ the message that appears when you try to create a new issue.  The fact that you opened this issue indicates to me that you didn't bother to read either of these.

Please ask on our [forums](https://forums.select2.org/) instead.

**Comment by HawkonDK** [comment]
Oh sorry, total just ignore it because so many GitHub projects use the default issue guide, so I didn't read it

**Comment by HawkonDK** [comment]
maybe you will help me on https://forums.select2.org/t/animate-open-closeing-select/31?u=ranazomic ??
