### ISSUE TITLE
Add an option to determine focus on search field or not

### ISSUE THREAD

**Issue by m-jch** [select2/select2#5098]
I think we need an option to customize focus on search field after container is open.

In mobile browsers after container is open, suddenly keyboard appears and  this is a bad user experience because maybe the user does not need to search.

I can create a pull request for this.

**Comment by alexweissman** [comment]
Have you looked at #4425?

**Comment by m-jch** [comment]
Thanks.

**Comment by alexweissman** [comment]
Could you propose your solution in that thread, actually?  I'm reluctant to add more binary configuration options (there are so many already and they are very buggy), but we can at least consider it as one possible solution to the mobile keyboard issue.
