### ISSUE TITLE
Avoid DOM manipulation inside loops with jQuery

### ISSUE THREAD

**Issue by gemal** [select2/select2#5099]
using Select2 4.0.5

from a report on https://www.dareboost.com

Working directly with the DOM has a cost. If you have to add elements to a node, you should prefer to append them once rather than one by one.

```
    for(var b=[],d=0;d<a.length;d++){var e=a[d],f=this.selectionContainer(),g=this.display(e,f);f.append(g),f.prop("title",e.title||e.text),f.data("data",e),b.push(f)}

    for(var h=0;h<e.length;h++){var i=e[h],j=this._normalizeItem(i),k=this.option(j);this.$element.append(k)}
```

**Comment by alexweissman** [comment]
Could you please link to the specific lines of code in the (uncompiled, unminified) source?

**Comment by razh** [comment]
https://github.com/select2/select2/blob/ebf10c93db7d6d7a0d1330119d4c6f32cbd231d7/src/js/select2/data/tags.js#L22-L29

https://github.com/select2/select2/blob/ebf10c93db7d6d7a0d1330119d4c6f32cbd231d7/src/js/select2/selection/multiple.js#L89-L101

**Comment by alexweissman** [comment]
Awesome, thanks.  So it sounds like the solution is simply to append to an array, and then call `appendMany` on the array after the loop?

I'd accept a PR that addresses this!

**Comment by irenesalomo** [comment]
Hi @alexweissman  , has anyone worked on this?
Otherwise, I'm happy to try implementing the recommended solution.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:
