### ISSUE TITLE
How would I go about removing an option from the select2 arguments?

### ISSUE THREAD

**Issue by albertovasquez** [select2/select2#510]
I can't seem to find a way to remove an option.  For example if a dropdown has a list of countries and somewhere else on the screen we delete that country is there a way to remove the item from the dropdown without populating the entire thing?

Thanks in advance.

**Comment by memetolsen** [comment]
$("#selectBox").html("");  will remove all elements.

**Comment by lordaikins** [comment]
@albertovasquez thanks for the fix, searched all around for this (to remove an option) until I came across your post. Simple but works great!

**Comment by LeandroFranciscato** [comment]
It works very well here, thank you!

**Comment by timbogdanov** [comment]
doesn't seem to want to remove the first option, everything else works, but not the first one. Any come across this?

**Comment by orionokan** [comment]
@timbogdanov  after remove all you should add new empty option for your purpose

**Comment by call-graph-pending4** [comment]
I discerned the answer



https://outdoordictionary-compre.github.io/kristian24/
