### ISSUE TITLE
select2 added with jquery not focusable

### ISSUE THREAD

**Issue by hmkhafan** [select2/select2#5101]
hi
i add new select2 element with jquery to my html page.
and i want when pressed enter key on this select2 it be blur and focus moves to next select2.
but when pressed enter key on this select2, focus losing.

**Comment by alexweissman** [comment]
Hi @hmkhafan, and welcome to Select2!  It is unclear from your statement, whether you believe this to be a bug, or if you are asking for usage and implementation help.

If you are just looking for usage help, you should post to the [forums](https://forums.select2.org) instead.

If you believe this to be a bug, you must create a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example using our [JSBin template](http://jsbin.com/goqiqolete/edit?html,js,output).

Please re-read the [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md) _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
