### ISSUE TITLE
Select2 in a modal bugs when i scroll the page

### ISSUE THREAD

**Issue by RagAccGith** [select2/select2#5103]
I'm using the select2 in a Bootstrap Modal, its works fine on first modal open, but when i scroll the page, the select bugs hard.

I'll attach prints of the bug.

![printerror](https://user-images.githubusercontent.com/18520952/32183676-15d30b7a-bd81-11e7-9052-0f5c4d82ef10.png)
![printerror2](https://user-images.githubusercontent.com/18520952/32183677-15fe8930-bd81-11e7-91e3-c478ffe02579.png)

**Comment by alexweissman** [comment]
This is a known problem, and there is an issue already open.  Please be sure to search the open issues in the future before opening a new one.
