### ISSUE TITLE
Rendering issue with ParsleyJS

### ISSUE THREAD

**Issue by Baruch4413** [select2/select2#5104]
Hello, thanks for making such an amazing plugin, I use it everyday on my job, it's just amazing.

Aside from that, there is a thing that always causes me trouble when using Select2, and that's because I use along with parsley.js, which you can checkout here:
[http://parsleyjs.org/](http://parsleyjs.org/ "http://parsleyjs.org/")

As the `select` tag is printed before the actual plugin HTML, parsley puts its messages just above the selectbox, not below it, as it is expected; I include a screenshot as reference.

![screenshot from 2017-10-30 17-11-41](https://user-images.githubusercontent.com/6426009/32200083-6fecd5e6-bd95-11e7-8e4a-49e69e27dbbc.png)

Where the text in gray is the label, the text in red is the parsley validation message and the rounded rectangle is the selectbox.

If there is a configuration I can use to prevent this, could you please tell me how to use it?
Otherwise, if this is effectively a bug, I want to think that swapping the order of two tags shouldn't be much of a trouble.

Thanks for your time.

**Comment by alexweissman** [comment]
There is an open pull request for `insertBefore`, see #4445.

**Comment by Baruch4413** [comment]
Thanks for your answer, and sorry for the duplicate issue.

I would like to contribute to the #4445 issue, but I lack proper training in the matter of testing.

If I can help somehow please let me know.
