### ISSUE TITLE
dropdownCssClass for 'notranslate' not working on dropdown (google translate)

### ISSUE THREAD

**Issue by govardhanyadavAG** [select2/select2#5106]
hi,
 while working with google translator,i need to add "notranslate" class to the container and the dropdown.so that the content should not be translated in any language on change of the language change.

```
<asp:DropDownList ID="ddlOwner_Workgroup_Id" runat="server" CssClass="select2WithSearch">
                    <asp:ListItem>SELECT</asp:ListItem>
                    <asp:ListItem>hello</asp:ListItem>
                    <asp:ListItem>hi</asp:ListItem>
        </asp:DropDownList>
    <script type="text/javascript">
            $('.select2WithSearch').select2({
                containerCssClass: "notranslate",
                dropdownCssClass: "notranslate"
            });
        </script>
```

after doing this,the class **notranslate** has been added to both the container and the dropdown(select2-drop),but on the language change the dropdown options **select2-drop** has been still getting translated.

is there any thing i am missing here?

**Comment by alexweissman** [comment]
Can you link to the relevant documentation for this feature of Google Translate?  My guess is that Google Translate is reading the DOM before the class has been applied.

**Comment by govardhanyadavAG** [comment]
i had already posted same question at google translate forum,didn't got any response on it,as you said i tried adding the class in document.ready like

` $(document).ready(
        function () {
             $("#<%=ddlOwner_Workgroup_Id.ClientID%>").select2({
            containerCssClass: "notranslate",
            dropdownCssClass: "notranslate"
        });
        });
` 

it is adding the class properly,but the same issue is getting repeated.

**Comment by suryacaprice** [comment]
Hi 
I have the same issue

**Comment by ameer988** [comment]
Same issue 

How to resolve this issue
