### ISSUE TITLE
Programmatically set value in hidden input doesn't work

### ISSUE THREAD

**Issue by osroca** [select2/select2#5107]
Using select2 v4.0.0 and v4.0.4 I have defined a select2 input using an `input` hidden and when I try to set the value programmatically it doesn't work. It works just fine with a `select` element. This fiddle shows up the issue:

https://jsfiddle.net/7ectj5ua/7/

Is this feature available for hidden inputs?

**Comment by alexweissman** [comment]
The hidden `input` technique is [deprecated in v4](https://select2.org/upgrading/migrating-from-35#no-more-hidden-input-tags), which means that no additional effort will be expended on implementing any features related to it.
