### ISSUE TITLE
RTL indenting doesn't work

### ISSUE THREAD

**Issue by kabeda** [select2/select2#5108]
Hi,
I have a multilingual website. In ltr direction the select works good but in rtl one (arabic) there's no padding in the right.

![rtlexemple](https://user-images.githubusercontent.com/16399314/32446236-88d31354-c308-11e7-84bf-cb8b5a8b3e21.png)

I'm talking about these spaces (drawed in green)

![ltrexemple](https://user-images.githubusercontent.com/16399314/32446392-08c98b7e-c309-11e7-858c-c2de303785d2.png)

Any idea? Thanks

**Comment by alexweissman** [comment]
As the issue instructions state, please create a [JSBin](http://jsbin.com/goqagokoye/edit?html,js,output) so that we can replicate this issue.

**Comment by kabeda** [comment]
Hi, 
Here is what I done.

http://jsbin.com/piwicayuwi/edit?html,css,js,output

As you can see there's no indentation on the right.

**Comment by alexweissman** [comment]
Thanks.
