### ISSUE TITLE
[Fixed] Bootstrap Modal with Select2

### ISSUE THREAD

**Issue by nev3rmi** [select2/select2#5110]
Hi I just find the way to fix the compatible between Bootstrap and Select2, when the select2 cannot present, cannot clickable and when it scroll get problem.

Like this problem: https://jsfiddle.net/eL9d2pdL/3/
You cannot click into it.

First you need to do the dropdownparent:
This gonna allow you to do the input in the select.
https://jsfiddle.net/eL9d2pdL/4/

However if the modal is too high then like this the select2 will run away:
https://jsfiddle.net/eL9d2pdL/5/

And how I fixed it:
https://jsfiddle.net/eL9d2pdL/6/

First you need to find: 

`container.bottom` in `AttachBody.prototype._positionDropdown`

Original:
Line 4274:
`container.bottom = offset.top + container.height`
Line 4319:
`css.top = container.top - parentOffset.top - dropdown.height
`
Changed to:
4274:
`container.bottom = offset.top + container.height + $($(this)[0].$dropdownParent[0]).scrollTop();`
4319:
`css.top = container.top - parentOffset.top - dropdown.height + $($(this)[0].$dropdownParent[0]).scrollTop();
`

The new code doesn't affect the normal one.
https://jsfiddle.net/rLmztr2d/276/

:) Hope you enjoy :)

**Comment by Karmalakas** [comment]
https://github.com/select2/select2/issues/1436#issuecomment-21028474

**Comment by alexweissman** [comment]
While I appreciate the effort that went into writing this up, the issue tracker is not really an appropriate place for these kinds of hacks.  If you believe this is a bug and that you are submitting a fix, you should fork the repo and [submit a pull request](https://help.github.com/articles/about-pull-requests/) with your changes and some qunit tests that demonstrate how your code solves the problem.

**Comment by ShaurmaLab** [comment]
Amazing! You've made my day! 
Works perfect in Jquery dialog modal too!

**Comment by radioactiveboyx** [comment]
nev3rmi you're the best. Amazing this solved my problem with the select opening when i attempted to scroll down the modal.

**Comment by stupidoes** [comment]
@nev3rmi thank you so much ! you literally saved lives :) 👍 

IMO, This really should be integrated to main select2 since it'll happen to anyone that integrate Select2 inside long modal.

**Comment by okyisother** [comment]
Amazing !! great thought !! thank you so much

**Comment by LeonSuckow** [comment]
In my case, i was working on a legacy project where there were already $('.select2').select2(); settings that overrode this global definition

```
    $('#elementId').select2({
        ajax: {
            url: 'url',
            data: function (params) {
                return {
                    search: params.term
                }
            },
            processResults: function (data) {
                return {
                    results: data
                };
            }
        },
        placeholder: 'Search',
    });
```


I made a script that when a modal is opened identifies the 'select' fields and determines the dropdownParent without overwriting the previous options (ajax and placeholder, etc.)


```
	$('body').on('shown.bs.modal', '.modal', function () {
		$(this).find('select').each(function () {
			var dropdownParent = $(document.body);

			if ($(this).parents('.modal.show:first').length !== 0) {
				dropdownParent = $(this).parents('.modal.show:first');
			}

			if ($(this).data('select2')) {
				var select2Options = $(this).data('select2').options;

				$(this).select2('destroy');

				
				$(this).select2({
					...select2Options.options,
					dropdownParent: dropdownParent
				})
			} else {
				$(this).select2({
					dropdownParent: dropdownParent,
				});
			}
		});
	});
```
