### ISSUE TITLE
View error

### ISSUE THREAD

**Issue by liyunfei0302** [select2/select2#5111]
![1](https://user-images.githubusercontent.com/30078196/32478637-d1d56f26-c3c0-11e7-9386-95b38ab42471.png)

![2](https://user-images.githubusercontent.com/30078196/32478644-d9cd59a0-c3c0-11e7-9471-978ed8a9d00c.png)

**Comment by alexweissman** [comment]
This is not a good issue, as per our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).  For general usage questions, you must ask on the [forums](https://forums.select2.org).  I am disappointed that you did not read the guidelines.

**Comment by liyunfei0302** [comment]
Im sorry, I see
