### ISSUE TITLE
List scrolls to top after selecting another item.

### ISSUE THREAD

**Issue by paladin80** [select2/select2#5112]
Conditions options: { multiple: true, closeOnSelect: false }

To reproduce: Create a long select list (with scroll), open it and start to select every item from the top.

Result: After each select the list scrolls to the top and you have to scroll down manually each time to the previous scroll position.

Bug source: the call of 
self.highlightFirstItem(); 
in container.on('select',   
in results.js line 279

**Comment by alexweissman** [comment]
This is a duplicate issue.  You clearly did not search the open issues.
