### ISSUE TITLE
Cant get ajax respond

### ISSUE THREAD

**Issue by Faruk-Caliskan** [select2/select2#5113]
<div class="control-group">
        <label for="remote-load" class="control-label">Select2 custom data load</label>
        <div class="controls">
          <div class="input-prepend input-append">
            <button class="btn" type="button" data-select2-open="remote-load">
              <i class="icon-search"></i>
            </button>
            <input id="remote-load" type="hidden" class="select2-remote" style="width:400px;">
            <button class="btn" type="button" data-select2-open="remote-load">
              <i class="icon-search"></i>
            </button>
          </div>
        </div>
      </div>

$('remote-load').select2({
  ajax: {
    url: 'https://api.github.com/orgs/select2/repos',
    data: function (params) {
      var query = {
        search: params.term,
        type: 'public'
      }

      return query;
    }
  }
});

Hi i am new at select2 and frontend development. I cant gelt ajax respond and i am not sure where i should look. Thanks a lot.

**Comment by alexweissman** [comment]
This is not an appropriate issue, as per our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).  For general usage questions, you must ask on the [forums](https://forums.select2.org).  

**I am disappointed that you did not bother to read the guidelines for new issues.**
