### ISSUE TITLE
MultiSelect with closeOnSelect:false - Scrolls to the top of list on each selection

### ISSUE THREAD

**Issue by JordaniRozon** [select2/select2#5116]
Whe using select2 multi-select option with [closeOnSelect: false] as attribute each time I select an option the menu scroll to the first option or focus to the first option.

![capture](https://user-images.githubusercontent.com/3766995/32575083-061e986c-c4a1-11e7-8142-ae441a0f49ec.PNG)

Selected items:
![capture2](https://user-images.githubusercontent.com/3766995/32575131-2ecc653c-c4a1-11e7-845f-3ee7296f30c4.PNG)

Need help!!!!

Code using: 
`$("#id").select2({
     width: "100%",
     closeOnSelect: true,
     allowClear: false,
     minimumResultsForSearch: -1,
   });`

**Comment by alexweissman** [comment]
#4417
