### ISSUE TITLE
AJAX call not happening after initializing with new options after 'destroy'

### ISSUE THREAD

**Issue by Karmalakas** [select2/select2#5121]
I've ran into a problem where I need to change `<select>` from regular list to AJAX results. I manage to change options on `<select>`, but AJAX call never happens if I try to search. [Heres a (not) working example on Stackoverflow](https://stackoverflow.com/questions/47206995/selec2-ajax-call-not-happening-after-initializing-with-new-options-after-destro)

**Comment by alexweissman** [comment]
This appears to be a usage question, and as such does not comply with the [issue guidelines](https://github.com/select2/select2/blob/master/.github/ISSUE_TEMPLATE.md).  

**You must read these before opening an issue!!!**
