### ISSUE TITLE
Select advanced field sorting not working

### ISSUE THREAD

**Issue by WebHuntInfotech** [select2/select2#5128]
Hello,

I'm using metabox io for my project.

but when i using a "select_advanced" field sorting not working.

So please provide the best solution asap.

Thank You

**Comment by alexweissman** [comment]
Hi, and welcome to Select2!  It is unclear from your statement, whether you believe this to be a bug, or if you are asking for usage and implementation help.

If you are just looking for usage help, you should post to the [forums](https://forums.select2.org) instead.

If you believe this to be a bug, you must create a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example using our [JSBin template](http://jsbin.com/goqagokoye/edit?html,js,output).

Please re-read the [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md) _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
