### ISSUE TITLE
Docs site not work!

### ISSUE THREAD

**Issue by riartem** [select2/select2#5129]
After many times trying to get live version — result the same:

![image](https://user-images.githubusercontent.com/987517/32785400-79d44782-c962-11e7-8a8e-e94ee8e4cb30.png)

**Comment by alexweissman** [comment]
The data center where the site is hosted had some unexpected downtime.  The issue has since been resolved.  Please do not open up issues about temporary downtime, as this is unrelated to the Select2 codebase itself.

**Comment by riartem** [comment]
Dear Alex, this issue is just notification for you about troubles with docs site. I don't know another way to do this. And I don't knew: you informed about that issue already or not. 
Hope for your understanding.

**Comment by alexweissman** [comment]
https://github.com/select2/docs/issues
