### ISSUE TITLE
data-allow-clear and data-placeholder not working

### ISSUE THREAD

**Issue by projct1** [select2/select2#5133]
- Version 4.0.6-rc.0

### Description
When i try to use data-option notation, its not working:
```html
<select data-allow-clear="true" data-placeholder="Type ID or name" name="bar_id" class="select2">
</select>
```

**Comment by alexweissman** [comment]
Please create a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example using our [JSBin template](http://jsbin.com/goqagokoye/edit?html,js,output) and we can re-open this issue.

**Comment by projct1** [comment]
https://jsfiddle.net/rorc/sLkpy3hm/
Here no placeholder, no clear icon.

**Comment by IsmailM** [comment]
Temp Fix for data-placeholder: 

```javascript
$('select').select2({
    templateSelection: function (data) {
      var placeholder = $(data.element).closest('select').data('placeholder');
      if (placeholder !== undefined ) {
        return placeholder;
      }
      return data.text;
    }
});
```

**Comment by nphilipp** [comment]
NB: this works for me with 4.0.5: https://jsfiddle.net/nilsph/uL79f8fn/5/  
but doesn't with 4.0.6-rc.1: https://jsfiddle.net/nilsph/uL79f8fn/7/

**Comment by frdteknikelektro** [comment]
Nice @nphilipp ,
This should be fixed asap

**Comment by pedrofurtado** [comment]
Canonical issue -> https://github.com/select2/select2/issues/5320
