### ISSUE TITLE
How do i push content of selected element into multiple lines.

### ISSUE THREAD

**Issue by sandeepan** [select2/select2#5134]
I tried the solutions written [here](https://github.com/select2/select2/issues/4585
) and they won't work.

Basically, if text of an element is too long, it should wrap itself into multiple lines for better user experience. I commented out text-overflow and changed whitespace to normal. L

.select2-container .select2-selection--single .select2-selection__rendered {
    display: block;
    padding-left: 8px;
    padding-right: 20px;
    overflow: hidden;
    /*text-overflow: ellipsis;*/
    white-space: normal

}

Using  Select2 4.0.3

**Comment by alexweissman** [comment]
There is already an open issue about this.  Furthermore, as a usage question, this should be asked on the [forums](https://forums.userfrosting.com), not in the issue tracker.
