### ISSUE TITLE
tags and other options are not working if a custom data adapter is used

### ISSUE THREAD

**Issue by AchimKlotz** [select2/select2#5135]
For offline usage I'm using a custom data adapter fetching the data from the browser index db. This is working fine execpt that the tags and the settings for minimum or maximum length are not working if the custom adapter is used.

I took a look at the source code and it seems that if a custom data adapter is used, the tags and other settings are ignored and the data adapter will not be decorated with them

**Comment by yellow1912** [comment]
Im having the exact issue, trying to debug this on the latest 4.0.5 version.

**Comment by alexweissman** [comment]
The latest version is not 4.0.5, it's 4.0.6-rc.0.

If you believe you have found a bug, you must create a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example using our [JSBin template](http://jsbin.com/goqagokoye/edit?html,js,output).

Please re-read the [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md) _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
