### ISSUE TITLE
XHR request to query data triggered on SHIFT key press

### ISSUE THREAD

**Issue by kikonen** [select2/select2#5136]
Just noticed that at least with versions 4.0.3 and 4.0.6-rc.0, when SHIFT key is pressed down in searchbox then XHR request is triggered. This naturally causes undesired extra queries into backend.

Howto
0) reload page
1) Open select2 box (with XHR and searchbox)
2) When search field has focus, press SHIFT key down
=> XHR request is done on every press
3) type some letter and press SHIFT key
=> SHIFT key press does not generate extra XHR requests
4) Delete letter typed in step (3)
5) When search field has focus, press SHIFT key down
=> Redundant XHR requests are not generated
6) close and reopen select2 box
7) When search field has focus, press SHIFT key down
=> Redundant XHR requests are not generated

So it seems that issue occurs when box is opened first time. Seems to happen with various meta keys.

**Comment by alexweissman** [comment]
I can't seem to replicate this in the [docs](https://select2.org/data-sources/ajax).  Are you certain that this isn't due to some other interaction in your code?  Have you tried creating a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example?

**Comment by kikonen** [comment]
Based into simple trivial example, you decided that "issue does not exist"

**Comment by kikonen** [comment]
Just change example in https://select2.org/data-sources/ajax to be:
```
$('.js-data-example-ajax').select2({
  ajax: {
    url: 'https://api.github.com/search/repositories',
    dataType: 'json',
    minimumInputLength: 0,
    // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
  }
});
```
and issue is triggered

**Comment by alexweissman** [comment]
So the issue is because of `minimumInputLength: 0`?
