### ISSUE TITLE
Implement bot to automatically close non-conforming issues

### ISSUE THREAD

**Issue by alexweissman** [select2/select2#5138]
Triaging bad issues is exhausting, and makes it impossible to get any real work done on Select2.

Vue.js has an interesting solution - they force all issues to be submitted through a [structured web form](https://new-issue.vuejs.org/), which I assume then posts the issues to the tracker via web hooks.  Another bot comes along and automatically closes any issues which are not opened through this form.

See https://github.com/vuejs/vue-issue-helper and https://github.com/vue-issue-bot

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
