### ISSUE TITLE
Why data-placeholder ?

### ISSUE THREAD

**Issue by Alex360hd** [select2/select2#5139]
Hello,

I wonder why the plugin is looking at data-placeholder attribute in order to set a placeholder to the select field.

The plugin is already able to read the core html "multiple" attribute, why did you choose another logic for placeholder by using a data-attribute instead of the core one ?

Regards,

Alex

**Comment by jonahgreenthal** [comment]
Placeholders and `multiple` are not the same thing.

**Comment by alexweissman** [comment]
Hi @Alex360hd,

This issue does not seem to conform to the [issue guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md), so it is being closed.  Perhaps it would be better suited for discussion on the [forums](https://forums.select2.org)?

**Comment by Alex360hd** [comment]
"Placeholders and multiple are not the same thing."

Sure, I know the difference maybe I was misunderstood.

I talked about multiple because select2 read the "multiple" attribute in order to know if it have to render a single or multiple select checkbox, not "data-multiple"

So why using "data-placeholder" instead of just "placeholder" to read the placeholder, maybe there is a technical reason that I would like to understand, or maybe it's just an API inconsistency that can/should be fixed.

That's why I created an issue anot not a forum post.

**Comment by alexweissman** [comment]
So, [`select`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) controls do not natively support the `placeholder` attribute.  `data-placeholder` is really just an alternative way of specifying the [`placeholder` configuration option](https://select2.org/placeholders) on the Select2 control itself.

Overriding this fact about `select` controls (that `placeholder` is an invalid attribute for them) breaks semantics, will cause HTML validation errors, and could possibly cause accessibility issues as well.  (Note that `multiple`, on the other hand, _is_ a valid attribute for `select`).

I'll clarify this in the docs.

**Comment by Alex360hd** [comment]
Thanks for the info, it's more clear now.
