### ISSUE TITLE
Prevent select2 from clearing input-Field

### ISSUE THREAD

**Issue by iFlash** [select2/select2#5141]
By default, select2 seems to clear the input field every time the input loses the focus. How can I prevent this from happening?

**Comment by alexweissman** [comment]
Hi @iFlash,

This issue does not seem to conform to the [issue guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md), so it is being closed.  Perhaps it would be better suited for discussion on the [forums](https://forums.select2.org)?

**Comment by iFlash** [comment]
I don't think so. This is a bug in my book as the behavior is not what any given user would expect.

I reposted this issue with conforming wording.

**Comment by alexweissman** [comment]
Ok, but keep in mind that any bug report must also include a minimal, verifiable, and complete demonstration of the behavior in [jsbin](http://jsbin.com/goqagokoye/edit?html,js,output).

At any rate, this is a duplicate and has been asked many, many times before.
