### ISSUE TITLE
jquery select2 not working properly with datatable page limit change

### ISSUE THREAD

**Issue by mittultechnobrave** [select2/select2#5144]
I am using jQuery's [Select2][1] library as a replacement for select boxes with jQuery's Table plugin called as [DataTables][2].

I have integrated both plugins together and its working fine except for one issue. 

I have a Dropdown through which I can change the limit to show number of records per page. 

Say for example I have 15 records and default I am showing maximum 10 records per page. When I change it from **10** to **25** then my **Page** drop-down does not update from value **2** to **1**. 

Here below are the screenshots whats happening at the moment. 

[![enter image description here][3]][3]

[![enter image description here][4]][4]

As you can see in my second screenshot, even if I have 25 records to see, the **Page** option still saying **Page 1 of 2**.

This feature works well if I do not integrate *select2* in my pagination class using jQuery.

Below is the code What I have done so far to initialize **select2** in my DataTables. 

    "fnDrawCallback": function (oSettings) {
                $("#datatable_status").select2();
                $(".dataTables_length select").select2();
                $(".dataTables_paginate select").select2();     
               
            }

And if I comment the line `$(".dataTables_paginate select").select2();` then it works well but **select2** style wont be there anymore for my Pagination dropdown. 

[![enter image description here][5]][5]

Can someone guide me what I am doing wrong here ? What should I do to get valid count in my Pagination dropdown ? 

Thanks

  [1]: https://select2.org/
  [2]: https://datatables.net/
  [3]: https://i.stack.imgur.com/GsRee.png
  [4]: https://i.stack.imgur.com/HnaGY.png
  [5]: https://i.stack.imgur.com/3C2cD.png

**Comment by alexweissman** [comment]
This appears to be a usage question, and as such belongs on the [forums](https://forums.select2.org).

Please be sure to read the [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md) before opening issues in the future.
