### ISSUE TITLE
Function filter by first chars

### ISSUE THREAD

**Issue by Adeweb-it** [select2/select2#5145]
I have developed a function for Select2 4.0.5 to filter the search by first chars.

```
function matchFirstChar(params, data){
	if ($.trim(params.term) === '') {
		return data;
	}
	if (typeof data.text === 'undefined') {
		return null;
	}
	if (data.text.toLowerCase().indexOf(params.term.toLowerCase()) == 0) {
		var modifiedData = $.extend({}, data, true);
		return modifiedData;
	}
	return null;
}

$("select").select2({
	matcher: matchFirstChar
});
```

It would be nice to have it already integrated as an option ;)

**Comment by alexweissman** [comment]
Thanks, but this doesn't really fit into a GitHub issue (see the [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md)).  Could you post this on the [forums](https://forums.select2.org/c/ecosystem) instead?
