### ISSUE TITLE
Pagination has hidden bug!

### ISSUE THREAD

**Issue by Checkson** [select2/select2#5146]
Tonight I spend two hours to debug about pagination, but I found there are fix records  each page can't trigger the request, but  latter I switched to eight records each page be successful. So, by default, if there are not enough records in each page, I cant not trigger the request!

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
