### ISSUE TITLE
Issue when showing data from ajax, selected option is not shown as selected

### ISSUE THREAD

**Issue by andreidiaconescu** [select2/select2#5147]
for me,
this happens setting the data from ajax:
{
"results": [
{
"id": 1,
"text": "Option 1"
},
{
"id": 2,
"text": "Option 2",
"selected": true
}
]
}
the selected option is not shown as selected.
I tested in versions 4.0.6-rc.1, 4.0.5 and 4.0.3

Any idea what i could do ?
Thank you.

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
