### ISSUE TITLE
Cache ajax results v4

### ISSUE THREAD

**Issue by grekpg** [select2/select2#5148]
https://github.com/select2/select2/issues/110 - this is old alb now not working. 

How in v4 i can add my cache resolver (override query) ? 

(i need load all data one time from ajax source then show only cached data) cannot find example for v4+

**Comment by alexweissman** [comment]
Are you talking about something more than just jQuery's [support for browser caching](http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings)?
