### ISSUE TITLE
XHR request to query data triggered on SHIFT key press

### ISSUE THREAD

**Issue by kikonen** [select2/select2#5149]
Since issue reopening seems to be not possible, creating clone of #5136

Just noticed that at least with versions 4.0.3 and 4.0.6-rc.0, when SHIFT key is pressed down in searchbox then XHR request is triggered. This naturally causes undesired extra queries into backend.

Howto
0) reload page

Open select2 box (with XHR and searchbox)
When search field has focus, press SHIFT key down
=> XHR request is done on every press
type some letter and press SHIFT key
=> SHIFT key press does not generate extra XHR requests
Delete letter typed in step (3)
When search field has focus, press SHIFT key down
=> Redundant XHR requests are not generated
close and reopen select2 box
When search field has focus, press SHIFT key down
=> Redundant XHR requests are not generated
So it seems that issue occurs when box is opened first time. Seems to happen with various meta keys.

Just change example in https://select2.org/data-sources/ajax to be:
```
$('.js-data-example-ajax').select2({
  ajax: {
    url: 'https://api.github.com/search/repositories',
    dataType: 'json',
    minimumInputLength: 0,
    // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
  }
});
```
and issue is triggered

**Comment by alexweissman** [comment]
Please do not open a new issue - just edit your existing issue and we can reopen it.
