### ISSUE TITLE
Select2 multiple does select only one item when selecting items programmatically

### ISSUE THREAD

**Issue by KalvisUpitis** [select2/select2#5153]
Select2 multiple does select only one item when trying to select multiple items programmatically

Steps to reproduce:
* Go to select2 demo page (https://select2.org/getting-started/basic-usage)
* Scroll down to Multi-select boxes (pillbox)
* From JS console run:
`$('.js-example-basic-multiple').select2('val', ["AK", "HI"]);
$('.js-example-basic-multiple').trigger('change');` 

Expected result:
* Both Alaska and Hawaii selected in multi-option

Actual result:
* Only first item (Alaska) is selected

**Comment by KalvisUpitis** [comment]
Sorry, hadnt noticed changes in API. Works like this:
`$('.js-example-basic-multiple').val(["AK", "HI"]); 
$('.js-example-basic-multiple').trigger('change')`

**Comment by marcelogarbin** [comment]
@KalvisUpitis Can you tell me how I can solve this in Laravel?

I have the following code:
JS
```javascript
$(document).ready(function() {
    $('select.select2').select2({
        locale: 'pt-BR',
        placeholder: 'Selecionar', 
        width: '100%'
    });
});
```

```php
{!! Form::select('especialidade_id[]', $especialidades, [1,2,3], ['class' => 'form-control select2', 'multiple' => 'multiple']) !!}
```

Is returning only ID 1
![image](https://user-images.githubusercontent.com/9335588/37493224-06dd0fc2-2883-11e8-9a39-cce111942c04.png)

**Comment by gitspider** [comment]
I have same issue with @marcelogarbin
