### ISSUE TITLE
Feature Request: Support Filipino as language (fil)

### ISSUE THREAD

**Issue by simonfranzen** [select2/select2#5158]
I did not found any resources for filipino, or am I wrong ?
Does someone has translations for it ?

**Comment by alexweissman** [comment]
It doesn't look like we have either `tl` (Tagalog) or `fil` (Filipino), so please - submit a pull request!  Just make sure you check the [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#submitting-a-pull-request) first.

**Comment by simonfranzen** [comment]
@alexweissman OK, thanks for the info. I will make a PR, when we finished the translations for it.
