### ISSUE TITLE
Incorrect inputTooShort, inputTooLong, maximumSelected for "fr"

### ISSUE THREAD

**Issue by miksh7** [select2/select2#5159]
In "fr" localization a few items have the same bug (e.g. for inputTooShort):

`return "Saisissez au moins " + t + " caractère" + (t > 1) ? "s" : ""`
will return "s"

the fix:
`return "Saisissez au moins " + t + " caractère" + ((t > 1) ? "s" : "")`

See http://jsbin.com/bohoteqesa/1/edit?html,js,output
- click on select to see inputTooShort issue
- type 5 characters or more to see inputTooLong issue

**Comment by alexweissman** [comment]
This has already been fixed; see #5122.

For future reference, you MUST confirm your problem in the **latest** version of Select2 before opening an issue.
