### ISSUE TITLE
Update composer.json to remove deprecated dependency robloach/component-installer

### ISSUE THREAD

**Issue by rodrigoaguilera** [select2/select2#5164]
I am trying to pull this library from packagist and I noticed that it has a dependency on a deprecated package.

https://packagist.org/packages/robloach/component-installer

Can it be removed?

**Comment by alexweissman** [comment]
Hmm, yeah I'm not sure what that package was supposed to do.  In their README:

> Allows installation of Components via Composer.
> Component Installer has been depreceted. Use Asset Packagist or Component Installers Extender instead.

Can you figure out what this package was used for, and whether we need to replace it with one of these newer packages?

Btw, for client-side libraries like Select2, I recommend using Yarn+Webpack, rather than Composer, to manage them.  Composer is really geared towards server-side PHP packages.

**Comment by rodrigoaguilera** [comment]
Is there since the addition of the composer.json so I feel the dependency intention was to ease the managing of "components" (the packages from packagist with type: component) but with Asset packagist it makes no sense anymore, hence the deprecation.

I don't think select2 should have a dependency on [Composer Installers Extender](https://github.com/oomphinc/composer-installers-extender) (Not component installer extender) so any project can choose the destination of the component and also Asset Packagist already recommends it so is up to the developer.

Your recommendation is great but there is many ways of using composer and we should respect them meaning that we shouldn't force a deprecated dependency on the people who decide to manage select2 with composer instead of the mainstream of webpack.

**Comment by alexweissman** [comment]
Ok, makes sense.  Probably too risky to do this in a patch version, but we can slate this for v4.1.

**Comment by rodrigoaguilera** [comment]
Same as the related PR. This issue should be addressed
