### ISSUE TITLE
Focus is lost when user clicks clear button in multiple select with allowClear

### ISSUE THREAD

**Issue by drianoaz** [select2/select2#5166]
In a multiple select, when the user clicks on the `.select2-selection__clear` element, no focus is added on the `.select2-search__field` element, which does not allow the user to perform a textual search.

One example for this bug can localized at [link](http://jsbin.com/rarewav/edit?html,output).

I'm using Select2 4.0.5 on Google Chrome version 63.0.3239.84 64 bit on Ubuntu operating system 16.04 LTS

**Comment by alexweissman** [comment]
Yeesh, `allowClear` is [sooo broken](https://github.com/select2/select2/issues?page=1&q=is%3Aissue+is%3Aopen+allowclear&utf8=%E2%9C%93).
