### ISSUE TITLE
Disable focus when DDL is opened and not in visible area

### ISSUE THREAD

**Issue by bantikyan** [select2/select2#5171]
Hello I'm using 4.0.3 version. When select2 is opened, and I click outside, for example on some textbox, that textbox get focused and select2 ddl get closed automatically. But when textbox is far away from select2, and when clicking on textbox selec2 is not in visible are, it gets focus and I have to again scroll down to select my textbox. How can I ignore focus when select2 control is opened and  not in visible area? 
Thanks

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
