### ISSUE TITLE
Loading array data : one option auto selected

### ISSUE THREAD

**Issue by zeroone2005** [select2/select2#5174]
`    $("#unit_chan_id").select2({
        "placeholder"    : 'unit',
        "minimumResultsForSearch" : Infinity,
        "allowClear"              : true
    });`

when i reset options:
`                $("#unit").select2({
                    "data" : data.info
                });`

then, placeholder lost, one option auto selected.

When I reset is how to display placeholder, don't selected  option

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
