### ISSUE TITLE
data is undefined in Mozilla & Cannot read property 'slice' of undefined in Chrome

### ISSUE THREAD

**Issue by wichaksono** [select2/select2#5175]
Hi i have some trouble. some like this. 

![gambar](https://user-images.githubusercontent.com/11472981/34338289-c2faea86-e999-11e7-9f75-9e7118b43ae5.png)

then this is my code

![gambar](https://user-images.githubusercontent.com/11472981/34338311-00d5bcf0-e99a-11e7-8a8c-724d69032190.png)

JSON Output : 
`[{"id":39,"text":"PTC New"},{"id":34,"text":"PTC"}]`

oh yaa.. in my Chrome i got error like this
![gambar](https://user-images.githubusercontent.com/11472981/34338353-67a77040-e99a-11e7-879d-4fe15cfb57fe.png)

**Im Using Select2 4.0.5**

**Comment by alexweissman** [comment]
Welcome to Select2!  It is unclear from your statement, whether you believe this to be a bug, or if you are asking for usage and implementation help.

If you are just looking for usage help, you should post to the [forums](https://forums.select2.org) instead.

If you believe this to be a bug, you must create a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example using our [JSBin template](http://jsbin.com/hojajiwoye/edit?html,js,output).

Please re-read the [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md) _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.

**Comment by M-Yankov** [comment]
I had similar problems and the return object was in incorrect format.  
```js
processResults: function (data) {
    var select2Data = getSelect2Data(data);
    return select2Data ;
}
```

It should be:
```js
processResults: function (data) {   
    var select2Data = getSelect2Data(data);
    return { results: select2Data } ;
}
```
