### ISSUE TITLE
Problem with autocomplete with Django Rest API

### ISSUE THREAD

**Issue by SamsadSajid** [select2/select2#5176]
In my django project, I needed to use autocomplete with the search for the name of the products.
So I created a Rest API and wanted to use it just like you mentioned in your tutorial [https://select2.org/data-sources/ajax](https://select2.org/data-sources/ajax) . So i was using my rest API as a source to fetch data and I used the `javascript` code like you gave there just changed the url.
But it's not working.
I have a detailed question here in **StackOverflow**. Here is the [question](https://stackoverflow.com/questions/47953850/using-select2-autocomplete-with-django-project-does-not-work-while-fetching-the)
I still haven't got any reply.
If you kindly take a look at the question and give a solution it would help a lot. I have been working on it for many hours and couldn't solve it.

**Comment by alexweissman** [comment]
This appears to be a usage question, rather than a bug report or feature request.  Please see our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Usage questions should be discussed on the [forums](https://forums.select2.org) instead.

**Comment by SamsadSajid** [comment]
Hello, sorry, I should have gone through the guidelines before posting the problems.
I apologize for that. I have created this topic on the forums. Please kindly help.
