### ISSUE TITLE
When I call select2 after AJAX call search field doesn't work.

### ISSUE THREAD

**Issue by bagratzakaryan** [select2/select2#5178]
Hi to all I use select2 plugin after ajax call ( I open my modal content after ajax call and init select2 plugin), in this case, my select2 search field doesn't work.
How can I fix this bug?

![capture](https://user-images.githubusercontent.com/19146467/34374799-6d946bd0-eafc-11e7-8cac-7e06e12ddd6a.PNG)

I can't focus input field.

**Comment by bagratzakaryan** [comment]
this is solutions
https://github.com/select2/select2/issues/5062
https://stackoverflow.com/questions/46545729/cant-type-in-select2-dropdown-input-search-field-http-kevin-brown-com-select

**Comment by alexweissman** [comment]
This appears to be a usage question, rather than a bug report or feature request.  Please see our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Usage questions should be discussed on the [forums](https://forums.select2.org) instead.
