### ISSUE TITLE
Dynamic TR CLONE Not Working

### ISSUE THREAD

**Issue by DevkanKafkas** [select2/select2#5181]
Do You Have a Problem. I Have a Question For Select2;
Dynamic TR CLONE Please See You Sample

#Input Type="Button" onClick="CloneRow('LateNotCome')" Value=" + Add Row ">#Br>#Br>
#script src="https://code.jquery.com/jquery-1.10.2.js">#/script>
#link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
#script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js">#/script>

#Table>
#tbody Class='TRowStyle' Id='LateNotCome'>
#Tr id="LateNotComeRowToClone">#Td>
        #Select Style='Width:100px;' Name="DateOne[]" Class='js-example-basic-single'>
        #option value='1'>1#/option>
        #option value='2'>2#/option>
        #option value='3'>3#/option>
        #option value='4'>4#/option>
        #option value='5'>5#/option>
        #option value='6'>6#/option>
        #option value='7'>7#/option>
        #/Select>
#/Td>#/Tr>
#/tbody>
#/Table>

#Script>
$('.js-example-basic-single').select2();
function CloneRow(WriteName){
        var Table = document.getElementById(WriteName); 
        var Row   = document.getElementById(WriteName+"RowToClone");
        var Clone = Row.cloneNode(true);
        Table.appendChild(Clone);
}
#/script>

**Comment by alexweissman** [comment]
This issue does not appear to conform to our [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md).

Please re-read the contributing guidelines _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
