### ISSUE TITLE
Please add this comment to #1645 (Bootstrap 3 + Select2 + Modals + tabindex)

### ISSUE THREAD

**Issue by niftylettuce** [select2/select2#5189]
In issue <https://github.com/select2/select2/issues/1645> we mention use of `dropdownParent`, but we need to explicitly add that it needs to be inside `shown.bs.modal` event, otherwise the positioning of the select container will be incorrect.  For example:

```
$('body').on('shown.bs.modal', '.modal', function() {
  $(this).find('select').each(function() {
    var dropdownParent = $(document.body);
    if ($(this).parents('.modal.in:first').length !== 0)
      dropdownParent = $(this).parents('.modal.in:first');
    $(this).select2({
      dropdownParent: dropdownParent
      // ...
    });
  });
});
```

Example codepen working: https://codepen.io/anon/pen/KZZGNW

**Comment by alexweissman** [comment]
Sample code would be better added to the documentation (you can submit a PR), or posted on the official forums.  The issue tracker is not an effective way to share code snippets.

**Comment by niftylettuce** [comment]
@alexweissman see <https://github.com/select2/docs/pull/12>
