### ISSUE TITLE
Dropdown still showing after loosing focus

### ISSUE THREAD

**Issue by alantulais** [select2/select2#5191]
It didn't happen in previous version (4.0.5) but is present in 4.0.6.

If I click an Input (with a placeholder), then dropdown is shown with the message of "inputTooShort". Then I click another part of the website (unfocus) and dropdown message is still present (as well as placeholder text).

**Comment by alexweissman** [comment]
If you have found a bug, you must create a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example using our [JSBin template](http://jsbin.com/hojajiwoye/edit?html,js,output).

Please re-read the [contributing guidelines](https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md) _carefully_ and then edit your question.  Once your issue complies with the guidelines, we can reopen it.
