### ISSUE TITLE
Let user add tag before AJAX request is complete

### ISSUE THREAD

**Issue by alantulais** [select2/select2#5192]
When AJAX feature is enabled, users can't create a new tag before AJAX request retrieves results. Sometimes connection is slow and it will be nice to let users create a new tag. 

I can get it work if I SnappleMan's solution (making a 'fake' success call in transform function): `https://stackoverflow.com/questions/45067149/adding-tag-to-select2-before-ajax-search-is-complete?rq=1`

But when I do that, then if the user creates the tag after ajax response, tag is added twice in the input (in multiple selects).

I think it would be a good feature.

**Comment by alexweissman** [comment]
Is this really a good idea, though?  If the item already exists in the search results, then the end user would end up creating a new item when an existing option already exists.  In most use cases, it is preferable to select an existing option versus creating a new option.

**Comment by skn3** [comment]
I have just bumped into this issue. It becomes a problem when you quickly type your tag and hit enter before ajax has finished. It ends up selecting whatever was selected when the dropdown initially opens.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused now to fix UI bugs. But if you open a PR with unit tests, I will be glad to review and approve if everything is ok.
