### ISSUE TITLE
IE11: seach input on multiselect looses focus on list update from ajax 

### ISSUE THREAD

**Issue by quackes** [select2/select2#5193]
in IE11, if select2 multiselect options are supplied by ajax with search active, the search input box eventually looses focus when the list ist updated with the ajax results.

PR incomming

**Comment by alantulais** [comment]
Any update? This bug even causes IE11 going back if you press backspace when a tag suggestion appears.

**Comment by quackes** [comment]
After further testing I was not able to get it working in IE11. 

Although I was not able to reproduce this bug under Win 10. Neither IE11 nor Edge.

I‘m giving up. My client is moving to Win 10...





Bis dann
        Tobi

**Comment by pedrofurtado** [comment]
Discussion continues here -> https://github.com/select2/select2/pull/3394
