### ISSUE TITLE
X-Editable With select2 Remote Data send issues 

### ISSUE THREAD

**Issue by msnankit** [select2/select2#5200]
I am using x-editable with select2. I have completed data appending and display in dropdown, But once I select data and click on selected It shows some error like not sending selecting values in ajax

Please help me

**Comment by pedrofurtado** [comment]
we do not maintain our x-editable fork. But if this bug has root cause in select2, please send us a jsfiddle example and reopen the issue. Then, we will be able to provide some solution, workaround and understand better the situation.
