### ISSUE TITLE
Duplicate selection remove both values in Select2 autocomplete

### ISSUE THREAD

**Issue by dhaneesh** [select2/select2#5202]
I have autocomplete field with values getting from remote source using ajax. If I select same value twice, both values get removed. Same behavior observed in example provided in Select2 site,
https://select2.org/tagging#tagging-with-multi-value-select-boxes. If I select orange two times, both get removed. How can I retain one value ? 

I am using Select2 4.0.3 version.

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
