### ISSUE TITLE
select2:select event doesn't trigger for the first time when selecting a tag

### ISSUE THREAD

**Issue by bystrewsky** [select2/select2#5205]
I have select2 widget with tags allowed and ajax data loading. 
     
    $('#order_address_select').select2({
                placeholder: "Start typing...",
                ajax: {
                    url: '<?=Yii::app()->getBaseUrl(true)?>/order/getplacemarklist',
                    dataType: 'json',
                },
                tags: true,
            });

When i'm selecting a tag after reloading page, event `select2:select` does not trigger, but when i'm typing text again, and selecting it, it works. Also it works fine with elements loaded by ajax. Here's my event handler:
        
    $('#order_address_select').on('select2:select',function(e){
                console.log(e.params.data);
             });

**Comment by bystrewsky** [comment]
Found same issue [here](https://github.com/select2/select2/issues/4842)

**Comment by nehadhiman6** [comment]
Found same issue.
