### ISSUE TITLE
Allow dropdown with autowidth to align to right-hand-side of control

### ISSUE THREAD

**Issue by stevenharrap** [select2/select2#5208]
Is it possible to align the drop-down to the right hand side of the search box? This situation would appeal to scenario where the control is on the right hand-side of the screen and the drop-down has dropdownAutoWidth: true. The drop-down would be allowed to expand, leftwards, across the screen to suit the content.

Thanks for any help,
Cheers,
Steven.

**Comment by jgalley** [comment]
+1

**Comment by olegbraun2** [comment]
+1, it makes sense, if value is of type currency. 
The align position of value in select2 should be also aligned accordingly.
I could fix it with help of
https://stackoverflow.com/a/53243540/8219961

**Comment by samuelg0rd0n** [comment]
+1
