### ISSUE TITLE
RTL: wrong dropdown position

### ISSUE THREAD

**Issue by yustnip** [select2/select2#5209]
When RTL mode is enabled it looks like:

![screenshot from 2018-01-30 01-01-13](https://user-images.githubusercontent.com/9950871/35555518-781403f8-05b0-11e8-896b-3ef09fa395e3.png)

On the example - the button left offset is for example 100px and the dropdown offset is 100px too.

To manually fix it required to add to the dropdown left offset the width value of the button. Versions - lastest (including rc).

**Comment by yustnip** [comment]
Sorry. RTLCSS changed some styles of select2.

**Comment by mkhoudary** [comment]
If anybody is still facing this problem, I solved it by adding the following CSS to the RTL sheet without having to worry about any other conflicting CSS:

`.select2-container--open .select2-dropdown {
            transform: translate(100%, 0);
        }`
