### ISSUE TITLE
When the dropdown menu is displayed upwards there is a blank space.

### ISSUE THREAD

**Issue by dheeyi** [select2/select2#5212]
1.- It is required to have assigned minimumInputLength = 1;
2.- Open the menu and select an option.
3.- Back open the menu, find another option.
4.- A blank space appears. (
![errordropwdown](https://user-images.githubusercontent.com/7713859/35695024-9fa5e3c8-0759-11e8-8929-b72bfe5f6707.png)

It is necessary that the dropdown menu be displayed towards the top.

Occurs on the select2 page: https://select2.org/data-sources/ajax

**Comment by pgrunewald** [comment]
I can confirm this bug.

Additionally, I can report, that once the menu has opened that way, it never will appear below the input field anymore.

**Comment by pgrunewald** [comment]
This seems to be duplicate of #4614
