### ISSUE TITLE
How to disable caching of select2 search results?

### ISSUE THREAD

**Issue by ekr3peeK** [select2/select2#5213]
I have two select2 containers, which work together side-by-side. Both are ajax based selects, and the selected value of one of them, determines the results in the other.

My problem is the following: when I select the first of the two select boxes, and open up the second one, it is prepopulated with the correct search results. Yet, when I change the first select, and then reopen the second one, for a split-second, while the ajax request is sent for the new data from the second select option, the results that were shown previously are still visible and selectable.

For a concrete example, imagine the following two select boxes: one is for occupation, and the other contains names of persons. The intended use case would be, is to select an occupation in the first one, and then the second one will only list the persons with that occupation. If I select, for example doctor as the occupation, and then list the second one with all the doctors I get the correct result. But if I then reselect the first one, and change it to engineer, and re-open the second one, I will get the list of doctors for a split-second, before the ajax manages the load my engineers. I can even select a doctor, as an engineer, if I am quick enough.

Is there a way to disable this behaviour? IE: whenever I click on an ajax related select2, show me an empty list, or the "Searching" string, while the request to the server is made, and an answer is returned?

**RELATED STACKOVERFLOW QUESTION:** [LINK](https://stackoverflow.com/questions/48583459/how-to-disable-caching-of-select2-search-results)

**Comment by tangshuang** [comment]
I am facing the same problem.
I think select2.ajax option should provide a beforeSend option so that we can clear option items in this method.

**Comment by tangshuang** [comment]
And I tried to find a way:

```
let select2 = $el.data("select2");
// clear previous search results, only show 'Searching...'
select2.on("query", (e) => {
     select2.$results.find("li:not(:nth-child(1))").hide();
});
```

May help you.

**Comment by MikeMajara** [comment]
Select2 seems to "cache" its results inside the original <select></select> in the form of <option> tag. So I believe your best approach would be to clear all the options the moment you select a different occupation.

I answered your stackoverflow linked question with a little bit more of detail.

```
$('#select-occupation').select2({
  ...,
  ajax: {
      ...
  }
})
.on('select2:selecting', function(event){
  console.log('actual value: ' + $(event.target).val());
  $('#select-people').find('option').remove();
});
```

**Comment by itVico** [comment]
I have a similar problem, but in my case, the first one is a regular select and I can't access the `selecting` method. A `clear` method would be cleaner, imo (pun not intended).

**Comment by ygwain** [comment]
+1

**Comment by ekr3peeK** [comment]
iAmVico you could listen on the `change` event of the normal select also, and update the contents of the `select2` options when the previous one fires.
