### ISSUE TITLE
[BUG]: Wrong Positon, focus of select2 in modal - boostrap 4

### ISSUE THREAD

**Issue by locdhthtb** [select2/select2#5218]
my bug here:
https://jsfiddle.net/zhah9aob/
issue: 
- Click open Modal
- Roll page down 
- Click select  -> lost focus modal and wrong positon select2 

 +Chrome Version 64.0.3282.140 (Official Build) (64-bit)
+ libs:
bootstrap.min.css  
select2.min.css  
jquery-3.1.1.slim.min.js  
tether.min.js  
bootstrap.min.js  (4.0.0)
select2.full.min.js   (4.0.5)
select2-bootstrap.css

**Comment by lvillanne** [comment]
Try to use a dropdownparent closer to the select. For exemple $('#selectId').parent();

You can try on this fiddle : https://jsfiddle.net/azraelmonu/zhah9aob/4/

**Comment by shahimclt** [comment]
Using `.modal-body` instead of `.modal` as `dropDownParent solves the issue.

**Comment by locdhthtb** [comment]
Thank you everyone.
