### ISSUE TITLE
[BUG] The data('data') is missing on the li options

### ISSUE THREAD

**Issue by neverlose-lv** [select2/select2#5224]
The data('data') is missing on the li options since 4.0.6-rc0 release, but it was working until 4.0.5 inclusive
Example:
https://jsfiddle.net/zpnz60zx/
Look the line nr: 43 in JavaScript window.

It is a fork of multi-checkboxes extension for the select2 plugin. Originally it is provided, using select 4.0.3 version and it's working:
https://jsfiddle.net/wasikuss/7ak9skbb/

**Comment by lon9man** [comment]
+1
something was changed completely between **4.0.5** and **4.0.6-rc1**.

in **4.0.5** i got data from `$('select option').data('data')`
![image](https://user-images.githubusercontent.com/10497794/50441074-afc43700-0901-11e9-8841-d9d8822daf78.png)



in **4.0.6+** `data`-property is absent completely, only `select2Id`-property

![image](https://user-images.githubusercontent.com/10497794/50440747-3c6df580-0900-11e9-8c54-8d068016ab84.png)

**main question:**
how i can get my custom data for concrete select2-tag in **4.0.6+**?

**Comment by lon9man** [comment]
wow-wow, ticket is actual, should not be closed
