### ISSUE TITLE
css optimization 

### ISSUE THREAD

**Issue by webjohan** [select2/select2#5226]
https://github.com/select2/select2/blob/3fb9e4fceb43d4520f7a6fc7d842abeceb8ddf50/src/scss/theme/classic/_single.scss#L79

could be short handed?
border-radius: 4px 0 0 4px;

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand what problem this CSS will fix and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
