### ISSUE TITLE
Select event is not trigger if clicked on selected item

### ISSUE THREAD

**Issue by 0FilipK** [select2/select2#5229]
Hello,

I searched whole Internet and I didn't find any solution so I decided to make a new issue.

Here is example: https://codepen.io/FilipK/pen/xYWrYR

I'm using `select2:select` event and its triggers everytime when you select new value (that's obv) but it doesn't if selecting value is the same. In this example click on option with red border, close alert and then try to select this "red option" again. Event won't start. How can I trigger it again? I tried use `select2:close` event but there is a problem. If we click outside select2 event triggers too and it's not ok for me. I tried attach new event directly on select2 dropdown but it doesn't work because you blocked it (I used `$(document).on('click', '.select2-results__option', function(){});`)

Any ideas?

**Comment by 0FilipK** [comment]
Anyone?

**Comment by scarabdesign** [comment]
Well, it seems that the value of the select element itself is not important to you, right? In other words, you are taking the value you select and using it elsewhere (i mean, why else would you want to choose the same item twice). If that's true, add this:

`
.on('select2:close', function (event) {
     this.value = null
})
`

In the link to your example, I was able to use the select2:close to set the value to null and was able to select the item with the red border multiple times. Even if you open the dropdown and click outside, the select2:close event does trigger, but all it's doing is resetting the selector.

**Comment by 0FilipK** [comment]
@scarabdesign Thanks for answer. Value is important because it's size ID of product. Let me explain what I want to do. Select is used to select size of product and options have data-available set to false or true depends on stock. If data-available is set to false I have a little envelope (added by css) on right side of this option and if user clicks on that I'm displaying a Foundation dropdown with form to let user know when product will be available again. Problem is if i'm using `select2:select` and user already have already picked size for example by URL param or just by selecting before, so it won't work if he select again selected value. If I change event to `select2:close` and have selected option, clicking outside select2 causes displaying dropdown for a half of seconds. I want to prevent this "flickering". `select2:select` would be perfect but in source code of select2 is selecting event and it returns false if already selected. I'm using npm and I don't want to download sources and change it manualy.

**Comment by scarabdesign** [comment]
Ok, may I present a more hacky solution:
```
var prevselection = null;
 $('select')
    .select2({
         minimumResultsForSearch: Infinity, 
         templateResult: formatState,
         templateSelection: formatState
   })
   .on('select2:opening', function(event){
      prevselection = $(event.target).find(':selected');
      $('select').val(null);
   })
   .on('select2:select', function (event) {

      var _selection = $(event.target).find(':selected');
      var available = _selection.data('available');

      if(available === false){
         alert('ok')
      }
   }).on('select2:closing', function (event) {
      if(prevselection != null && $(this).val() == null){
         $(this).val($(prevselection).val())
      }
   });
```

**Comment by 0FilipK** [comment]
@scarabdesign It's working perfectly. Thank you so much :)

**Comment by 0FilipK** [comment]
@scarabdesign I noticed this solution has one defect. If we reset value so after open we don't have highlighted last selected item. I tried to foreach every `select2-results__option` and compare value to `prevselection` but it doesn't work. Code:

```
.on('select2:open', function(event){
                    var container = $('.select2-container--product-size.select2-container--open:not(.select2)');

                    container.find('.select2-results__option--highlighted').removeClass('select2-results__option--highlighted');

                    container.find('.select2-results__option').each(function () {
                        var $this = $(this);
                        
                        if($this.find('span span:first').text() === prevSelection.text().toLowerCase()) {
                                $this.addClass('select2-results__option--highlighted');
                        }
                    })
                })
```

**Comment by 0FilipK** [comment]
The interesting thing is if I run in console code

```$('.select2-container--product-size.select2-container--open:not(.select2)').find('.select2-results__option:eq(3)').addClass('select2-results__option--highlighted')```

it's working. Probably select2 build html later or something. I tried to use setTimeout for 3 sec but same result...

**Comment by scarabdesign** [comment]
Hmm, for some reason, your original example link (codepen.io) is not loading. I'll may have to set up another example somewhere to run some tests.

**Comment by 0FilipK** [comment]
I checked and my codepen link's working fine.

**Comment by scarabdesign** [comment]
So it is! Must have been temporarily out of order.
OK, so in the formatting function, I changed it slightly to add an identifying class to each item, then on open, change the highlight. Yes, wow, this is hacky, and there is a tiny flicker as the class switches, but I'm not sure now else to do it. Notice that the highlighting is happening after a zero second pause:
```
function formatState (state) {
   if (!state.id) { return state.text; }
   var el = $(state.element);
   var available = el.data('available');
   var $state = $('<span>')
      .addClass("option_" + state.id)
      .addClass(!available ? "not-available" : "")
      .append(
         state.element.text.toLowerCase(),
         $("<span>")
      );
   return $state;
};

var prevselection = null;
 $('select')
    .select2({
         minimumResultsForSearch: Infinity, 
         templateResult: formatState,
         templateSelection: formatState
   })
   .on('select2:opening', function(event){
      prevselection = $(event.target).find(':selected');
      $('select').val(null);
   })
   .on('select2:open', function(event){
      setTimeout(function(){
         var _optCont = $(".select2-results__option .option_" + $(prevselection).val()).parent();
         $("li", _optCont.parent()).removeClass("select2-results__option--highlighted");
         $(_optCont).addClass("select2-results__option--highlighted");
      }, 0);
   })
   .on('select2:select', function (event) {

      var _selection = $(event.target).find(':selected');
      var available = _selection.data('available');
      if(available === false){
         alert('ok')
         //console.log("ok")
      }
   }).on('select2:closing', function (event) {
      if(prevselection != null && $(this).val() == null){
         $(this).val($(prevselection).val())
      }
   });
```

**Comment by phpbg** [comment]
Hi, I experience the same issue.
I would expect at least a change event to be fired
I can see a change Event, but on internal input : `{isTrusted: true, type: "change", target: input.select2-search__field, currentTarget: body, eventPhase: 3, …}`

**Comment by DaTRiX25** [comment]
@phpbg I think this event is triggered when the search field is cleared after closing the dropdown. Maybe I'm wrong.

**Comment by NelGarbuzova** [comment]
This is a bug. Cause in docs says that select2:select 'Triggered whenever a result is selected.'. But when we select previously selected value, this event not triggered.

**Comment by akhunduqji** [comment]
the reason behind this issue is the 'focus' event. when ever you select an item from list, it triggers the on 'focus' event which opens the list. to get rid of this issue just right the following straight forward code and it will go away!
                               **var $selectList = $('#selectLanguage').select2({
					closeOnSelect: false,
                                        containerCssClass: 'fake-css'
				});
                                $('.fake-css').unbind('focus');
				$selectList.on("select2:select", function (e) {
						$selectList("close");
				});}**

**Comment by RomanBurunkov** [comment]
Why this was closed?
It's still the issue in the latest 4.0.12

**Comment by andreydro** [comment]
Having the same trouble in 4.0.6-rc.1 version

**Comment by klitsios** [comment]
It's still a bug.
Could you open it again?

**Comment by ridhorex** [comment]
strange enough 'cuz it's working fine with input type hidden when selecting selected option

**Comment by mylemans** [comment]
I also ran into this issue. I'd like to also, as documented, respond on item selection (click), even if it was 'selected' before.

**Comment by sivasingampalli** [comment]
I am trying to select a value from drop-down . Below are the different ways I have tried but the value is not getting selected from the drop-down or not even clicking on the drop-down field.

1st Method I tried :

    select('select[id=Name-dropDown-select]', 'Other') // Here I tried all the select options ex: ByVisible text, By Index, ByValue ,etc.

2nd Method I tried :

    script("document.getElementById('Name-dropDown-select').click()")

3rd Method I tried :

    def ele = locate("//select[@id='Name-dropDown-select']")
    ele.click()

4th Method I tried :

    mouse().move(506, 382.96875).click() // Here I gave X and Y co ordinates of the element.

5th Method I tried : 
 * input("//select[@id='Name-dropDown-select']", Key.ENTER).click()	

I tried in all the possible ways , and still it is not working , If there is a solution or workaround for this please help me.

**Comment by scarabdesign** [comment]
Hi! Couple of points for you.

1). Looks like you are having issues understanding javascript. The forums here are to discus problems with the program itself. If you need help using javascript, a place like StackOverflow (dot com) is probably a better place to ask your question.

2). Your question is unclear. Are you trying to get the value of the select element that has an option picked already, or are you attempting to programmatically select a value from the element?

3). Regardless of the answer to the above question, you should spend time reading the documentation. I'm sure what you are attempting to do is covered there:
https://select2.org/programmatic-control/add-select-clear-items



> I am trying to select a value from drop-down . Below are the different ways I have tried but the value is not getting selected from the drop-down or not even clicking on the drop-down field.
> 
> 1st Method I tried :
> 
> ```
> select('select[id=Name-dropDown-select]', 'Other') // Here I tried all the select options ex: ByVisible text, By Index, ByValue ,etc.
> ```
> 
> 2nd Method I tried :
> 
> ```
> script("document.getElementById('Name-dropDown-select').click()")
> ```
> 
> 3rd Method I tried :
> 
> ```
> def ele = locate("//select[@id='Name-dropDown-select']")
> ele.click()
> ```
> 
> 4th Method I tried :
> 
> ```
> mouse().move(506, 382.96875).click() // Here I gave X and Y co ordinates of the element.
> ```
> 
> 5th Method I tried :
> 
> * input("//select[@id='Name-dropDown-select']", Key.ENTER).click()
> 
> I tried in all the possible ways , and still it is not working , If there is a solution or workaround for this please help me.

**Comment by dimitriiBirsan** [comment]
took a inspiration from @scarabdesign  for a issue i had with `$(select).val(null).trigger('change')` that would make the text empty and set selected to false but still have the data leading to not being able to select the first option unless i selected another option

this was the `$(select).select2('data')[0]` format that was preventing me from selecting the first value

```
{
  _resultId: "select2-select-result-79vr-dev0LmVEVrF",
  disabled: false,
  element: <option value="someid" data-select2-id="17">,
  id: "someid",
  selected: false,
  text: "ItemText",
  value: "ItemText"
}
```


```
$('select')
  .on('select2:opening', function(event){
      const {selected }= $(select).select2('data')[0];
      if(!selected)
        $(id).val(null);
   })
```
   
   Posting this because i wasted over 10 hours over multiple days/weeks on this "small" issue .

**Comment by Niki1287** [comment]
1. Kishor Mafatlal Thakkar
