### ISSUE TITLE
Bulk selection with Shift key

### ISSUE THREAD

**Issue by tiagonicastro** [select2/select2#5231]
There is any way to bulk select with Shift key on multiple? Working with big lists is a difficult on massive selecion.

The result expected is:
-- item 0
-- item 1 (click holding shift key)
-- item 2
-- item 3
-- item 4 (click still holding shift key)
-- item 5

Itens 1 to 4 should been selecteds.

**Comment by scarabdesign** [comment]
Great suggestion! Would be handy, for sure.

But, I think the word you are looking for is "Shift"...

**Comment by tiagonicastro** [comment]
@scarabdesign hahahaha yes, ShiFt was the intended word. My bad! ahhahah i was reading and laughing here; just corrected the word.

Anyway, you know if there is a workaround for doind that?

**Comment by tiagonicastro** [comment]
For thouse who are looking for this featured. Here is:

`count_shift = 0;
shift_array = [];
options_selecteds = [];
$('.select2-shift').on("select2:select", function (e) {
	if (event.shiftKey) {
		shift_array.push(e.params.data.element.index);
		count_shift++;
	}
	if( count_shift == 2 ){
		for (var i = shift_array[0]; i <= shift_array[1]; i++) {
			var option_value = $('.select2-shift option').eq(i).val();
			options_selecteds.push(option_value);
		}
		$('.select2-shift').val(options_selecteds);
		$('.select2-shift').trigger('change');
		$('.select2-shift').select2('close');
		count_shift = 0;
		shift_array = [];
		options_selecteds = [];
	}
});`

**Comment by scarabdesign** [comment]
Nice! Thanks :)

**Comment by vignzpie** [comment]
Can we expect this feature built in? Also, CTRL+click is something that I'm looking for.

**Comment by ozkanozcan77** [comment]
Hi @tiagonicastro ,

How can I enable multiple selection with Shift key for my below select2 code? 
$j(".assigneeSelection").select2( { placeholder: "Select a User",
                allowClear: true});

Thanks,

**Comment by sridhargoshika** [comment]
Here is an example for remote data source,

`count_shift = 0;`
` shift_array = [];`
$j(".assigneeSelection").select2( 
{ placeholder: "Select a User",allowClear: true, closeOnSelect:false}
).on("select2:select", function (e) {
            if (event.shiftKey) {
                shift_array.push({ id: $(document).find('li.select2-results__option--highlighted').attr('data-select2-id'), data: e.params.data });                
                count_shift++;
            }
            if (count_shift == 2) {
                var lower = (shift_array[0].id < shift_array[1].id ? shift_array[0].id : shift_array[1].id);
                var higher = (shift_array[1].id > shift_array[0].id ? shift_array[1].id : shift_array[0].id);
                for (var i = lower; i <= higher; i++) {
                    $('.assigneeSelection option:contains("' + $('li.select2-results__option[data-select2-id='+i+']').text() + '")').prop("selected", true);               
                }                        
                $('select.assigneeSelection').trigger("change");             
                $('select.assigneeSelection').select2('close');
                count_shift = 0;
                shift_array = [];             
            }
        });

**Comment by mrtorks** [comment]
@sridhargoshika could you post a fiddle with your code on how it works?

**Comment by mrtorks** [comment]
For anyone to runs into this error
`the select2('close') method was called on an element that is not using Select2.`
Replace `$('select.assigneeSelection').select2('close');` with `$("select.select2-hidden-accessible").select2('close');`

Credit [https://stackoverflow.com/questions/38797207/how-to-handle-the-select2destroy-method-was-called-on-an-element-that-is-n](url).

`Select2 version: 4.06`

Further improvements on this would be with regards to allowing unlimited but not beyond the maximum amount of remote data. I would post that soon.

**Comment by mrtorks** [comment]
In case anyone has a hard time figuring this out for remote data. Here is my solution and how I implemented it.
Let say you have multiple dropdowns on a page, however you need bulk select on an active dropdown.
First make use of `select2:open` and `select2:close` and set a custom attribute eg: `active-dropdown` to `true`

```
$(function () {
       $(".select2").on("select2:open", function (evt) {
         $(this).attr("active-dropdown", true)
       });
  });

$(function () {
       $(".select2").on("select2:close", function (evt) {
         $(this).attr("active-dropdown", false)
       });
 });
```
This way you are always targeting the active dropdown

Then using your custom handler `on keydown`:

-  Grab the id attribute of the dropdown options then prop selected on the options between the selected options.

```
$(function () {
      var count_shift = 0;
      var shift_array = [];
      $(".select2").on("select2:select", function (evt) {
        if (bulkMode) {
          var id = parseInt(evt.params.data.id)
          shift_array.push(
            id
          );
          count_shift++;
        }
       
        if (count_shift == 2) {
          var lower =
            shift_array[0]< shift_array[1]
              ? shift_array[0]
              : shift_array[1];
          var higher =
            shift_array[1]> shift_array[0]
              ? shift_array[1]
              : shift_array[0];
          for (var i = ++lower; i < higher; i++) {
            var nonSelectedOptions = $(
              "select.disabled-dropdown[active-dropdown=true] option[id~=" +
                i +
                "]:not(:selected)"
            );
            nonSelectedOptions.prop("selected", true);
          }
          $(".select2").trigger("change");
          $("select.select2-hidden-accessible").select2("close");
          count_shift = 0;
          shift_array.length = 0;
        }
      });
});
```

Please note that I set an attribute `id` and targeted that. Feel free to @ me if you need more clarification.
