### ISSUE TITLE
Open select2 without <select> ?

### ISSUE THREAD

**Issue by l2aelba** [select2/select2#5232]
Just a quick question
Does it possible to **open** select2 **without** having **HTML** like `<select></select>` ?

**Example:**

``` javascript
$.select2({
   data: [{id: 0, text: 'Hello'}],
   positions: [x, y] // or target on some element
});
```

Can we do something like this ?

**Comment by scarabdesign** [comment]
Not that I can tell, but you should be able create a dynamic select element. As long as the element you create is added to the DOM before you call select2() on it, it should work:
```
var mySelect = $("<select>").appendTo("body"); 
setTimeout(function(){
	mySelect.select2({
		data: [{id: 0, text: 'Hello'}],
		position: [x, y]
	});
}, 0)
```

**Comment by l2aelba** [comment]
Thanks, @scarabdesign , I already did something like that also. :D
