### ISSUE TITLE
Two Values in only Select2

### ISSUE THREAD

**Issue by crisloliant** [select2/select2#5233]
Hi,

I Can have two values in a only select2, for example:

LIST 1: DataSource Category
LIST 2: DataSource Product depending LIST 1

In this gif show as can be

![video_1519407399](https://user-images.githubusercontent.com/4712954/36620335-812118fa-18c0-11e8-8f80-a533488ab44c.gif)

**Comment by pedrofurtado** [comment]
Currently, not.
