### ISSUE TITLE
Select2 with 'tag' option could not work on mobile

### ISSUE THREAD

**Issue by H0WARDDD** [select2/select2#5235]
I tried the official example(https://select2.org/tagging) on my iPhone, when I typing, it always bring up the native select options and block my typing

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
