### ISSUE TITLE
Bottom positioned multiple field using AJAX and minimum input positions search copy high up

### ISSUE THREAD

**Issue by copperseed** [select2/select2#5237]
Hello,

I've discovered an issue with select2 when a multiple field is placed near the bottom of a scrollable area. The example also uses AJAX and `minimumInputLength`. The bug occurs when the field is near the bottom of the viewport (when the search message appears at the top). The search copy and minimum input copy appear high up and not flushed to the field. This happens mostly on subsequent selections. One click in the field will display fine and the next won't. The JS Bin example is here: https://output.jsbin.com/cujamiv/ (scroll to the bottom)

Also important to note the positioning gets corrected on `scroll`.

I've done a temporary hack fix for my own app (didn't work without the `setTimeOut`):

             // Hack fix jumpy search
		{
			var triggerScroll = () => {
				var timer = setTimeout(() => {
					jQuery('html, body').trigger('scroll');
				}, 1);
			}
	
			jQuery('#budgetAdmins').on('select2:open', e => {
				triggerScroll();
			});
			
			jQuery('.budget-field').on('keyup', '.select2-search__field', e => {
				triggerScroll();
			});
		}

**Comment by AStoker** [comment]
Seems related to this: https://github.com/select2/select2/issues/4614
