### ISSUE TITLE
Update 3.5.3 github pages to say 3.5.4

### ISSUE THREAD

**Issue by PVince81** [select2/select2#5239]
We lost a few hours investigating an issue with select2 believing that 3.5.3 was the latest ever version (which we had in our package.json).

Some context here https://github.com/owncloud/core/pull/30645#issuecomment-369212434 where we discovered the fix by diffing the select2.js from the github-pages with the one we had from 3.5.3.

Please update the website to say 3.5.4 everywhere. Thanks.

**Comment by pedrofurtado** [comment]
https://github.com/select2/select2/issues/5360
