### ISSUE TITLE
Load data dynamically from function

### ISSUE THREAD

**Issue by mcanepa** [select2/select2#5244]
Is there a way to set a function as a datasource?

I'm in the need to do something like this:

```
$("#selector").select2({
    dataSource: my_function(param_text_from_searchbox)
});

```
Where `my_function()` receives what the user types and perform an AJAX request, besides other things.

If this can't be done right now, could it be considered for a future release?

**Comment by herbalite** [comment]
Check out this page from the documentation
https://select2.org/data-sources/ajax

**Comment by LeoLfL** [comment]
+1
