### ISSUE TITLE
Versions newer than v4.0.3 seem to have issues when destroy/cloning select2's

### ISSUE THREAD

**Issue by niftylettuce** [select2/select2#5247]
The preferred approach is to `.destroy('select2')` and then `.clone()` and then `.select2()` again.  However in versions of select2 > 4.0.3 this functionality is not working.

**Comment by KevinPeinado** [comment]
Yes, i was using the version 4.0.6-rc.1 and it was not working.

**Comment by cokeito** [comment]
i've posted a similiar situation on clone/duplicate

**Comment by niftylettuce** [comment]
bump

**Comment by multio** [comment]
Yep. No way to clone a select2 element now. When you destroy and re-add select2, the re-add does nothing. Also noticed there is a data-select2-id present in the destroyed select2 element, then the clone gets the same select2 id. also some class gets added by select2 and never removed on destroy.

**Comment by kevin-brown** [comment]
Can anyone create and link a jsbin that reproduces this issue?

The fact that a destroy does not fully clean up the select box is a strong indicator of where the problem lies.

**Comment by rohanc** [comment]
Yes: https://jsbin.com/nomikefuho/1/edit?html,js,output

**Comment by rohanc** [comment]
I experienced this using v4.0.7 also.

In addition to calling .select2("destroy"), it seems we need to remove the "data-select-id" attribute from both the SELECT and all its children. I guess these steps should be built into the destroy method itself.

https://jsbin.com/bomoyetilo/1/edit?html,js,output

Also note that if the original select has an ID attribute, then you need to give the clone its own ID. See also #5501.

**Comment by JonathanSeguin** [comment]
Also getting the same behavior with versions > 4.0.3.
