### ISSUE TITLE
After Emptying all options, how to reset it back. 

### ISSUE THREAD

**Issue by christopher64uz** [select2/select2#5251]
So I have two select2 field say field1 and field2. 

Initially I need to hide all options under field2 unless field1 has a value selected.
I achieve this by using .html()

$("#field2").html('<option></option>').select2({
        placeholder: "Select a field from filed1"
});

Once a field is selected in field1 I need to reset

$('#field1').on('select2:select', function (e) {
// None of the lines below are able to reset the field2
 
$("#field2").val([]).trigger('change');
$("#field2").select2('destroy').val("").select2();
$("#field2").select2();

Output: I am getting it blank after using .html()
NOTE: the option values are retrieved from DB so cannot define data in js.

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
