### ISSUE TITLE
in tags mode, when entering Chinese is always interrupted 

### ISSUE THREAD

**Issue by gagharv** [select2/select2#5252]
in **tags** & **multiple** mode, in the **chrome** browser, when entering Chinese is always interrupted and I can not enter the complete words.

![default](https://user-images.githubusercontent.com/186624/37505975-bcca1f42-2922-11e8-8e86-2e9aff84b324.gif)

os:mac os 10.13.3
browser:google chrome 65.0.3325.162(64bit)
select2 version:4.0.3/4.0.6-rc1

demo code: (it can be also reproduced in this page: https://select2.org/tagging#tagging-with-multi-value-select-boxes)
<select multiple></select>
<script>
    $("select").select2({
        tags: true
    });
</script>

**Comment by open2** [comment]
Korean has the same problems.

**Comment by zlx** [comment]
Yes, me too. Do you have any solution now?

**Comment by open2** [comment]
No solution. Only english input is possible.

**Comment by zlx** [comment]
After downgrade to 4.0.2, the problem is solved.
https://github.com/select2/select2/issues/4525
https://github.com/select2/select2/issues/4398

**Comment by lingceng** [comment]
I try to fix this problem with compositionstart and compositionend.
Only trigger search after the input Chinese word has commited.

Here's my commit:

https://github.com/lingceng/select2/commit/3b9a840ccb6639833fb0f61c8114267f53c4f93a

See https://github.com/facebook/react/issues/3926 for more information.

**Comment by gagharv** [comment]
> After downgrade to 4.0.2, the problem is solved.

it works. thank you :)

**Comment by pedrofurtado** [comment]
The discussion will continue in this PR -> https://github.com/select2/select2/pull/5268
