### ISSUE TITLE
Dropdown position on AJAX searches

### ISSUE THREAD

**Issue by mattalberon** [select2/select2#5253]
Version 4.0.5

Steps to reproduce the bug:

1. Open https://select2.org/data-sources/ajax and resize your browser height such that the 'search for a repository' box appears at the bottom the viewport, forcing the dropdown to appear above
2. Type a string e.g. 'matthew'
3. Wait for the results to display
4. Delete the string by selecting all, and pressing backspace
5. You should the advisory text label hanging where the top of the results list used to be i.e. not flush with the top of the search box - see attached screenshot.

![image](https://user-images.githubusercontent.com/13197991/37521654-67d86830-2919-11e8-9d10-0b17cf200a94.png)

**Comment by AStoker** [comment]
Has already been reported here: https://github.com/select2/select2/issues/4614

**Comment by luesak** [comment]
I got a video here: https://youtu.be/ykbAxAI6_k8

**Comment by 0lorak0** [comment]
Followed the trail from [#4616](https://github.com/select2/select2/issues/4614) (Closed Issue) to [#5196](https://github.com/select2/select2/pull/5196) (Open Pull Request)
