### ISSUE TITLE
Bug on IOS for tagging

### ISSUE THREAD

**Issue by ysarazin** [select2/select2#5254]
Version used : 4.0.6 rc1
It appears only on IOS.

When using the tagging support, after 2 characters typed, the native iOS select element is opened.
We can only enter 2 characters keywords.
![image1](https://user-images.githubusercontent.com/440829/37527656-d3e5581c-2932-11e8-9e7f-1c905ce545f4.png)

The bug is reproductible by loading this page on iPad : 
https://select2.org/tagging

This bug may be related to #5240

**Comment by PWalkow** [comment]
Why this one was closed if it is still a bug? Is there any chance to see it fixed?
