### ISSUE TITLE
Pressing enter to open select2 is making two data source calls

### ISSUE THREAD

**Issue by oazcurra** [select2/select2#5256]
Select2 version: 4.0.5.
Browser: Chrome Version 65.0.3325.162 (Official Build) (64-bit)
OS: Ubuntu 16.04

Having an text input and a select2 component with `ajax` configured and without a `minimumInputLength` you need to:
- Open browser's console in order to be able to see network requests. 
- Set focus on the text input and move to select2 component using `tab` key.
- Press enter to open select2 dropdown.

You will note that 2 requests are made to the configured data source.

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.

**Comment by oazcurra** [comment]
Here is the link to a jsfiddle to test it https://jsfiddle.net/oazcurra/qcayogxp/28/

You need to open browsers console to see network calls and then:
- focus on the input text and press `tab` on the keyboard to move to `select2`
- click `enter` to open `select2` component.

You will see that 2 requests are made to the data source.
![select2_5256](https://user-images.githubusercontent.com/20398458/48220427-fd92d900-e36d-11e8-8a30-ec0a6faabd17.gif)
