### ISSUE TITLE
Make new tags sentence case

### ISSUE THREAD

**Issue by seabasss** [select2/select2#5261]
Hey,

Three questions...

1) How can I make new tags sentence case automatically?

2) If I have a tag named "Blue" and start typing "blue " with a space at the end, it will act like it wants to create a new (lowercase) tag. Is it possible to trim this check and not switch to "blue" if it has spaces at the end?

3) When I open the select2 and start typing it acts like I want to create a tag, which is what I want. When that tag is added and I start to type a second time, the pre-selected option is an existing tag that time, instead of what I'm typing. Is it possible to only select a pre-existing option if it's written (case insensitive) the same as what you're typing, every time?

Thank you!

**Comment by seabasss** [comment]
I figured out 1. Just 2-3 left. Thanks for help.

1:
```
function ucfirst(str) {
	str += ''
	var f = str.charAt(0)
		.toUpperCase()
	return f + str.substr(1)
}
[...]
createTag: function (params) {
	return {
		id: ucfirst(params.term),
		text: ucfirst(params.term)
	}
}
```

**Comment by alexweissman** [comment]
Usage/support questions like these belong on the [forums](https://forums.select2.org).
