### ISSUE TITLE
Language NoResults option fails in FireFox

### ISSUE THREAD

**Issue by dmajor2400** [select2/select2#5263]
When running the below code in any version of firefox, the noResults return message is never displayed, and it looks like that's because event was undefined for some reason. Any help???

```
    $('#selector').select2({
            placeholder: "Select items",
            allowClear: true,
            language: {
                noResults: function(event) {
                    newMilestone = event.target.value;
                    return 'No results found. Add "' + event.target.value + '" as a new item?';
                }
            }
        });
```

In Chrome (working):

![capture1](https://user-images.githubusercontent.com/20462076/38429863-a93b86de-398d-11e8-84f1-85f3e25ea2b3.PNG)

In FireFox (not working): 

![capture2](https://user-images.githubusercontent.com/20462076/38429872-b35c189a-398d-11e8-8774-d86f35c94362.PNG)

**Comment by vmcruz** [comment]
I tested this on version 4.0.6-rc.0 and confirmed that on Firefox doesn't show the custom message. Additionally, the searchedTerm param isn't present within the context of "noResults" (Chrome nor Firefox).
