### ISSUE TITLE
select2 crash when using templateSelection

### ISSUE THREAD

**Issue by freshAztekKing** [select2/select2#5264]
Hey Guys i have a problem.

when using the templateSelection option my select2 field dosent load right. And the web-console says : TypeError: c is not a function select2.full.min.js:1:16621
Any ideas ? When removeing the option it works again.

```
function formatState(state) {
  return "test";
}

$field.select2({"enabled":true,"configs":[],"width":"resolve","placeholder":"","minimumResultsForSearch":0,"templateSelection":"formatState"});
```

**Comment by BhavinKhatri** [comment]
Because you have defined formatState as a string in an option.
