### ISSUE TITLE
Keeping focus in the multi value select as you keep typing & selecting options

### ISSUE THREAD

**Issue by aderpio** [select2/select2#5265]
I apologize if this was maybe asked before :( There is a "workflow scenario" for multiple selects in v3 (the Chosen plugin functions the same way) that seems to be missing in v4:

1. Click => opens control with focus in search element. 
2. Start typing => results are filtered as you type (and matches underlined) **(not in v4)**
3. Navigate with up/down arrows through matches. Hit enter to choose one
4. Search element keeps focus so you can repeat stept 2-3 **(not in v4)** Once you start typing again, the drop-down is opened and starts filtering as you type. 

Needless to say, this is very productivity oriented. You can practically add multiple options just by using the keyboard instead of clicking back to refocus every time. Or adding some extra code logic. Is this mentioned and some workarounds detailed somewhere?

**Comment by kaykyr** [comment]
Nice request! I'll subscribe on this discussion.

**Comment by kd8ssq** [comment]
I'm also seeing the same issue, but I'm using tagging.   I've tested in 4.0.2, .3 and .4 and they all have the same problem.  The select box loses focus once the tag is created by pressing the enter key.  You can hit the tab key once the new tag is created and it brings the focus back, but having the cursor automatically come back to the field once the tag is created is preferred for workflow.

**Comment by jpablom** [comment]
+1

**Comment by aderpio** [comment]
SAlso, Select2 v3, Chosen & Selectize disable (or remove) the selected options on multi-selects. This is fairly intuitive and you can remove the "tags" then. Select2 v4 keeps them in the options list, you can click on them and that removes that selected item's "tag". I'd say that is counter intuitive from two reasons:

- You already have the "x" button on each tag to remove the selected options

- The options list is cluttered with the already selected options that are clickable and prone to accidentally clicking on them.

**Comment by Akinzekeel** [comment]
I used a workaround that will re-open the dropdown immediately after selecting or de-selecting an option with the Enter key.

```
    var control = element.select2(options);
    
    if (control.first().prop("multiple"))
        control.next().keyup(function (e) {
            if (e.keyCode === 13)
                control.select2("open");
        });
```

**Comment by kd8ssq** [comment]
@Akinzekeel where did you place the code above?

**Comment by Akinzekeel** [comment]
@kd8ssq Please see my updated comment, it should be clearer now. This code will initialize the select2 plugin on all select elements and apply the workaround.

**Comment by flavienaudin** [comment]
+1 Thanks for the trick. 
Is an enhancement or fix is planed in future ?

**Comment by mariopro** [comment]
> +1 Thanks for the trick.
> Is an enhancement or fix is planed in future ?

It depends. This way is works like charm. I have it running on concurrent instances of select2 in the same form, without conflicts. One of te things I had to set was make use of a character (in my case the ; to allow for spacing on new Tags. Ex: "Design Thinking". If using the space it'll treat it as two separate tags, with "Design;Thinking" it'll save as "Design Thinking" => one only tag.

**Comment by jmalatia** [comment]
+1

**Comment by HeppyKarlsson** [comment]
+1

**Comment by qubis741** [comment]
+1

**Comment by thesilentonetoo** [comment]
+1

**Comment by lainosantos** [comment]
+1

**Comment by kevin-brown** [comment]
I'm either not understanding the workflow, or this was not doable because of a bug which has since been fixed in Select2.

When you create a new tag in Select2, it should maintain focus on the select box where the tag was being created. If the issue that you were seeing was with the focus being moved off of the search box and back to the selection element (specific only to single select elements), then this can be solved by specifying `closeOnSelect: false` (which will keep the search box open and focused).

If there is still an issue, can someone give a more detailed set of instructions for how to reproduce the issue they are seeing?

**Comment by tom-brown** [comment]
`closeOnSelect: false` partially works for me. The focus remains on the cell after selection, but the text that was entered also remains.  The user has to delete the text before continuing. I'm hoping there is a `clearOnSelect: true` option.

**Comment by lainosantos** [comment]
+1

**Comment by lainosantos** [comment]
+1
