### ISSUE TITLE
Error with Chinese Chracters input

### ISSUE THREAD

**Issue by littpi** [select2/select2#5267]
OS: Windows 10 Home Edition
Browser: Chrome 65.0.3325.181 (64-bit)
Version: 4.0.6-rc.1
JS Bin: http://jsbin.com/yosuxelove/1/edit?html,js,output
Snapshot:
![image](https://user-images.githubusercontent.com/17842734/38669800-bc68f606-3e79-11e8-89bb-751ab5406267.png)

How to re-produce the problem:
1. Setup multiple tagging function for the select tag of HTML.
2. Use Chinese input method "Cangjie" to input Chinese characters.
3. Each character requires maximum 5 codes to create. In the snapshot, I want to type "你好嗎" but the codes rendering the 3 characters are also shown, which is considered as bug.

**Comment by littpi** [comment]
I have also tried to use other browsers and getting different bug results...
Firefox:
![image](https://user-images.githubusercontent.com/17842734/38670545-a3b44c1c-3e7b-11e8-9753-2e63e692eac1.png)

The characters cannot be rendered out... It can only input maximum 3 codes and the codes cannot render a correct character.

**Comment by littpi** [comment]
For Microsoft Edge, it renders correctly without any bugs.
Edge 41.16299.371.0:
![image](https://user-images.githubusercontent.com/17842734/38670768-494d0060-3e7c-11e8-8727-4afeeb241558.png)

It is correct to get the chracters "你好嗎".

**Comment by lvxianchao** [comment]
Yeah, so am I.

OS: Mac OS

Browser: Chrome  65.0.3325.181

But, it seems to be related to the input methods software.

I use Chinese input method 'wubi', '清歌五笔输入法' and '百度五笔输入法', all of which have some problems.

And, it seems to be related to the browsers too!

More problems on Chrome than on Safari

**Comment by littpi** [comment]
Hello. Is there any updates?
