### ISSUE TITLE
Error on clone/duplicate a select2

### ISSUE THREAD

**Issue by cokeito** [select2/select2#5269]
Hello, i've been working on duplicate select2 on a couple of forms on ruby on rails, when i duplicate the select2 element, i destroy it and  the clone it. but the behavior is not the expected (this is only happening on 4.0.6-rc1 version).

this is the example using 4.0.6-rc1
http://jsbin.com/coweheliyu/2/edit?html,js,output

using the 4.0.0 version works without a problem.
http://jsbin.com/jixinelade/3/edit?html,js,output

i've noticied after version 4.0.0, new data-select2-id is being added to parent elements.

Hope you guys can take a look on this.
Thanks

**Comment by dasgib** [comment]
I ran into the same issue, looks like destroy() doesn't destroy everything. It works as expected with version 4.0.5

**Comment by vibonacci** [comment]
Yep, something is wrong with destroy. Very weird behavior after cloning. Can also confirm 4.0.5 works, 4.0.6rc1 does not.

In 4.0.6rc1 my parent span element gets a data-select2-id as well?

**Comment by rajakhoury** [comment]
I get the same behavior with V 4.0.6-rc.1 almost all the element's parent(s) get a "data-select2-id=X" attribute. Also when destroying the element and reinitializing.
