### ISSUE TITLE
Multiselect : Issue with internet explorer 

### ISSUE THREAD

**Issue by dhananjayrspl** [select2/select2#5270]
Environment : Internet Explorer 11
When we press backspace on first hit(backspace) remove selected css on second key press(backspace) browser navigate back to previous URL.

reference URL to reproduce :https://select2.org/getting-started/basic-usage  (Multi-select boxes (pillbox))

**Comment by jfeust** [comment]
We are also having this issue and are starting to get multiple complaints about it from our users.

**Comment by dhananjayrspl** [comment]
Please check below url.
https://adminlte.io/themes/AdminLTE/pages/forms/advanced.html 

It use Select2 4.0.5. Its working fine in said environment. No idea what solution they applied.

**Comment by vmcruz** [comment]
In current version (4.0.6-rc) this seems fixed. Tested on IE11 and works ok.

**Comment by pedrofurtado** [comment]
Discussion continues here -> https://github.com/select2/select2/pull/3394
