### ISSUE TITLE
in tags mode, when entering Chinese is always have the english alphabet

### ISSUE THREAD

**Issue by Fennay** [select2/select2#5271]
in tags & multiple mode, in the chrome browser, when entering Chinese is always have the english alphabet

[Test Url](https://select2.org/tagging#tagging-with-multi-value-select-boxes)

view:
![tags](https://user-images.githubusercontent.com/4941514/38845988-a08a8448-422c-11e8-9574-e21a06fc84fe.gif)
![1523932905](https://user-images.githubusercontent.com/4941514/38845990-a419aed6-422c-11e8-9eb3-6c0491f8df52.jpg)

what's the problem ?
How can I fix it ?

**Comment by FavorMylikes** [comment]
Have the same issue

**Comment by littpi** [comment]
I think it is the same issue with #5267. I am still waiting for updates.

**Comment by airan587** [comment]
Have the same issue

**Comment by Mileber** [comment]
Have the same issue

**Comment by Mileber** [comment]
Find a solution. Check this: https://blog.csdn.net/pintu274111451/article/details/80254340
