### ISSUE TITLE
templateSelection arguments do not contain data from select2:select trigger params data.

### ISSUE THREAD

**Issue by VictorioBerra** [select2/select2#5275]
## Bug reproduction
http://jsbin.com/dajexiraca/2/edit?html,js,console,output

## Issue
[The docs say you can trigger a select2:select event and pass data via params.data.](https://select2.org/programmatic-control/add-select-clear-items#preselecting-options-in-an-remotely-sourced-ajax-select2) However, my templateSelection code fails because additional data is missing. Consider the code sample below.

The [triggering events docs](https://select2.org/programmatic-control/events#triggering-events) seem to suggest this should be possible.

## Code
```javascript
  // manually trigger the `select2:select` event
  $('#example1').trigger({
      type: 'select2:select',
      params: {
        data: {
          customData: "Hello World" // NOT AVAILABLE INSIDE templateSelection function!!!
        }
      }
  });
```

**Comment by Toso82** [comment]
The same of me and not find solution  

https://github.com/select2/select2/issues/5449

**Comment by VictorioBerra** [comment]
The stale bot seems harmful to the issue tracker. So now, the maintainers or thereof don't get around to issues anymore and they all mysteriously close themselves after a short time. Then people come to this project and see it doesn't have many issues even though there are a huge number of them that have just gone unaddressed. My issue contains a full reproduction. How is it acceptable to close that?

My work would NEVER let me automatically close JIRA tickets.

**Comment by macowie** [comment]
I also have hit this bug. Loading an array from ajax with extra attributes, but the extra attributes not available inside the templating function (which is what I was including them for)

**Comment by kevin-brown** [comment]
I'm not entirely convinced that this ever worked, considering I don't see the jQuery event handler that would have received this.

We have an event relay which will trigger the `select2:select` event, but that relay doesn't listen for any events.

**Comment by joweste** [comment]
I have the same problem.

**Comment by dbarreraHS** [comment]
I have the same issue. Any possible solution for this one?

**Comment by soulshake** [comment]
Same issue here as well.

**Comment by avsdev-cw** [comment]
It would appear this issue still exists... and is not restricted to (manual) programmatic calls to the select() method but any trigger which results in the templateSelection method being called.
