### ISSUE TITLE
[BUG] When search items can be replaced

### ISSUE THREAD

**Issue by Tsyklop** [select2/select2#5276]
I download Select2 4.0.6-rc.1 and try configure search.

When i typing in serach input and close items list and open again, there is such trouble:

![default](https://user-images.githubusercontent.com/6783568/39010918-b2ecd5f8-4418-11e8-8b13-a87460516968.png)

Now, every reopened replace item name by "Searching...". Each opening of the list increases the number of such replacements. The elements themselves do not disappear. They just change the name.

In Select2 4.0.5 all fine.

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
