### ISSUE TITLE
I want to focus when tags selected

### ISSUE THREAD

**Issue by okancelik** [select2/select2#5278]
Hi guys,

I want to focus input (so continue typing) when tags selected.

I used normally this settings before 1-2 years ago. 

```
$("#select2").select2({
	width: "100%",
	placeholder: "Select",
	tags: true,
	closeOnSelect: true,
	tokenSeparators: [','],
}
```

But now not working. When i select a tag, i cant continue typing. For continue, i must to press tab button or click select area. What can i do?

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
