### ISSUE TITLE
Documentation's navigation is extremely unusable

### ISSUE THREAD

**Issue by aa21** [select2/select2#5279]
**Select2 is an excellent plugin** that has a **decent documentation** with a **_horrible navigation_**

Every time I need a functionality from my autosuggest-ajax-multiSelect box (e.g making sure that previously selected values are pre-loaded and rendered correctly):

When I don't know what I'm looking for .. the documentation does not provide any clues.
- The documentation is not easily searchable
- The data is hidden away in some obcure section or subsection accessible only through clicking through 3-4 pages and waiting for each of them to load .. it's basically depth-first search 
- The sidebar menu refreshes on each click(!)  
- I resort to Google and StackOverflow in order to find the functionality which are finally found in the documentation (which means the document navigation failed its job)

When I have a rough clue (from Google or SO or Github Issues):
- The documentation forces me to click from page to page to page. Each page has very little useful information
![screen shot 2018-04-23 at 8 39 45 am](https://user-images.githubusercontent.com/486730/39101929-e8aceb36-46d1-11e8-88f3-4ca8c0fb4840.png)
- The links are weird on some pages. Why are there clipboard / paste icons everywhere??

Suggestions:
- Reduce the number of clicks/pages a visitor has to go through. 
- The sidebar should not be refreshing on each click. I just want to scan the topics _very quickly_ until I find promising topics .. only THEN I want to load that article. I don't want to spend time waiting for every other article to load. It slows me down and frustrates me.
- Side bar should be fully open by default -- Everything shouldn't be hidden away. Show the information straight up please.
- The previous github based documentation where everything was on a single page is MUCH better. Single page documentation will be the BEST. I can search up and down the page without loading here and there. Even if you have 5mb worth of documentation, a single page that is sent gzipped from server will be fast to load and provide the BEST navigation to the user of this excellent plugin.

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:

**Comment by pedrofurtado** [comment]
https://github.com/select2/docs/issues/6
