### ISSUE TITLE
Placeholder changes selected order in multiselect

### ISSUE THREAD

**Issue by josephbiko** [select2/select2#5280]
When I create my select2 item with: 
```
 <select id="from_lang" name="native" class="select2-multi" multiple="multiple" style="width:100%;">

<script>
 sel = $(".select2-multi")
sel.select2({
                placeholder:"test"
            });
</script>
```
The selected items are appended at the front instead of the back.
I cannot imagine this is desired behaviour.
A quick fix I found was adding `data-placeholder="test" ` to the select2 tag

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
