### ISSUE TITLE
select2 in jquery trying to set a value in drop down

### ISSUE THREAD

**Issue by anujyadi** [select2/select2#5284]
I made  two drop down and trying to set selected value from second drop down in first one.
First Drop Down:
 $("#assignToPhysician").select2({
	ajax : {
	    url : "patient-physicians.action?action=loadListAll",
	    dataType : "json",
	    data : function(params) {
		return {
		    name : params.term,
		    callingPage : "CR",
	 	    companyNumber : rowData.companyNumber,
	 	    medicalRecordNumber : rowData.medicalRecordNumber,
	 	    patientNumber : rowData.patientNumber,
	 	    billNumber : rowData.billNumber,
		    page : params.page
		};
	    },
	    processResults : function(data) {
		return {
		    results : $.map(data, function(list) {
			return {
			    id : list.drnum,
			    text : list.name
			};
		    })
		};
	    }
	},
	minimumResultsForSearch : 50,
	allowClear : true,
	placeholder : {
	    id : '0',
	    text : 'Select a provider'
	}
    });

    $("#assignToPhysician").on("select2:select", function() {
	$("#assignToPhysician-id").val($(this).val());
   });

Second drop down:
 $("#addPhysician").select2({
	ajax : {
	    url : "physician-master.action?action=loadListSelect2",
	    dataType : "json",
	    data : function(params) {
		return {
		    name : params.term,
		    page : params.page
		};
	    },
	    processResults : function(data) {
		return {
		    results : $.map(data, function(list) {
			return {
			    id : list.id,
			    text : list.description
			};
		    })
		};
	    }
	},
	minimumResultsForSearch : 50,
	allowClear : true,
	placeholder : {
	    id : '0',
	    text : 'Select a provider'
	}
    });

    $("#addPhysician").on("select2:select", function() {
	selectedAssignPhysician = $(this).val();               //2
    });

when selecting any value in second drop down , this value is not setting in first drop down using id only.
Please check how this can be done.

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
