### ISSUE TITLE
Select2 not filtering items with keyboard input

### ISSUE THREAD

**Issue by deshpande89** [select2/select2#5285]
I am using Select2 version 4.0.5 and facing issue that Select2 is not filtering items with keyboard input.
Below is the scenario:

1. I am getting focus on Select2 dropdown (Country list) with tab.
2. With focus on, I am trying to press keyboard keys. But Items are not getting filtered out based on the key press.
e.g. If I press E then England should get selected.

3.We can only start searching after pressing space-bar or enter.

Please help to filter items based on keyboard input without needing to press space or enter.

**Comment by Deimoks** [comment]
Did you found a solution for this behaviour?
