### ISSUE TITLE
[Firefox] Non-printable keys will soon stop firing keypress event (Affecting)

### ISSUE THREAD

**Issue by brendonwatson** [select2/select2#5286]
[https://www.fxsitecompat.com/en-CA/docs/2018/non-printable-keys-will-soon-stop-firing-keypress-event/](url)

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.

**Comment by brendonwatson** [comment]
This change has been enabled on all the channels as of Firefox 65.
Since we using your library in our product, from what i can see, you're still using `keypress` rather than `keydown`, just checking that this behaviour does not affect us.
