### ISSUE TITLE
When clear selection, it gives error: Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by XBLDev** [select2/select2#5287]
Hi

When I set 'allowClear' to true and click on the 'x' button on the right, or click on the 'x' button of the last selection, it gives the error:

Uncaught TypeError: Cannot read property 'length' of null.

This error seems to be the reason I can update my variables, and I haven't found a viable solution for it after searching quite a while, it doesn't seem to be a regularly brought up question either.

Do I have to set in the configuration to prevent this error from happening?

Thanks in advance for any answers!

**Comment by camambeou** [comment]
Try to add "placeholder", something like:
```$('#yourselect).select2({
        placeholder: '-- Select your favorite --',
        allowClear: true,
        tags: true
    });```

**Comment by XBLDev** [comment]
hi @camambeou thanks for your reply! I do have placeholders, don't think that solves the problem. Does the format of placeholder matter? Like '-- Select your favorite --' works but 'Select your favorite' won;t work?

**Comment by camambeou** [comment]
Then I have no idear in this case, maybe you try debug your js
