### ISSUE TITLE
Reload\Refresh selected value clears off

### ISSUE THREAD

**Issue by yadavsonika** [select2/select2#5290]
Hi All,

I am facing an issue in select2, on reload/refresh of page the value selected previous clears off. 
I had added the following code snippet 

`$.ajax({`
` url: */searchById/?id=' + value`
`}).then(function (data) {`
` var option = new Option(data.text, data.id, true, true);`
`$('#'+id).append(option).trigger('change');`
` $('#'+id).trigger({`
`type: 'select2:select',`
  `   params: {`
`    	   data: data`
`    	        }`
    	    `});`

I want to add all the content of `data` to `option`. Please tells the solution to achieve so. 

Data in option is : "[{"selected":true,"disabled":false,"text":"1045435-Suspense ","id":"10382738","title":"","_resultId":"select2-investmentAccountId-result-vvkj-1036319","element":{"jQuery111109292144739536214":47}}]"
 
whereas, after selection data is : "[{"selected":false,"disabled":false,"text":"213111111-Test Account","createdBy":0,"creationDate":null,"updUserId":0,"lastUpdateDate":null,"createdByUserName":null,"updUserName":null,"approvedBy":0,"approvedByUsername":null,"investmentAccId":1019004,"investmentAccName":"Test Account","investmentAccNumber":"2131111111","investmentAccTypeCd":null,"investmentAccStatusCd":"IAS_ACT","customerName":"Holdings, WM - HSBC","customerId":XXX,"investmentAccTypeName":null,"allAccount":false,"customerSearchResult":{"createdBy":0,"creationDate":null,"updUserId":0,"lastUpdateDate":null,"createdByUserName":null,"updUserName":null,"approvedBy":0,"approvedByUsername":null,"customerId":5867,"customerTypeCd":null,"companyIndividualInd":null,"customerReferenceNumber":null,"name":"Holdings, WM - XXX","statusCd":null,"partial":null,"title":null,"subStatusCd":null,"id":"5867","text":"Holdings, WM - XXX","checkBoxKey":"XXX","actualId":0,"searchName":"Holdings, WM - HSBC","authId":XXX,"inTable":false},"id":"1019004","_resultId":"select2-investmentAccountId-result-88ok-XXX","element":{"jQuery111109292144739536214":60}}]"

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
