### ISSUE TITLE
Select2 to activate Bootstrap modal

### ISSUE THREAD

**Issue by OneOfA11** [select2/select2#5292]
Hello,
I have tried to search about this issue but wasn't able to find anything.

My questions is it possible to use Select2 for selects and when select option from the dropdown to show Bootstrap modal with 2 buttons ?

Thanks in advance.

**Comment by carlkyo** [comment]
I had this issue too. I searched a lot solutions and I found this works perfectly 
remove tabindex  and add style="overflow:hidden;" 
good luck

**Comment by Guoxweii** [comment]
@carlkyo 

remove tabindex and add style="overflow:hidden;"

that is not working for me!

the 'style="overflow:hidden;"  ' add which element?

**Comment by icecoldfire** [comment]
This fixed it for me: https://stackoverflow.com/questions/13649459/twitter-bootstrap-multiple-modal-error/19190216#19190216
