### ISSUE TITLE
can set value only by id in Ajax (remote data)

### ISSUE THREAD

**Issue by carlkyo** [select2/select2#5293]
I tried a lots and only this works
it is inconvenient and complicated
i am appreciated greatly your help
var option = new Option(data_text, data_id, true, true);
$('select').append(option).trigger('change');

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
