### ISSUE TITLE
Select2 doesn't work on 2nd modal opening

### ISSUE THREAD

**Issue by tgobira** [select2/select2#5297]
Hello there guys.

I'm getting a problem with Select2 use on Modal Box and haven't found at issues and foruns none like my issue.

Using Bootbox plugin to develop a modal "input form". In this form I'm using Select2 plugin for search/autocomplete a field that is "created" dynamically when the document is ready. At first opening of the modal box, the Select2 plugin works fine (as picture below).
![image](https://user-images.githubusercontent.com/23407525/40255409-66e4b2aa-5abd-11e8-87b7-f90e4092a145.png)

When I close the modal box and open it again, the DropDownList where Select2 is applied doesn't work and still return the last selected value.
![image](https://user-images.githubusercontent.com/23407525/40255463-a1a3bd28-5abd-11e8-9831-6321f7eb4e85.png)

If I reload the page (pressing F5, changing page or reload location through javascript) the "form" is reloaded and the JS is called and the script "re-executed", and then the component works as expected.

Down here I'm passing the code applied.

HTML
![image](https://user-images.githubusercontent.com/23407525/40255925-2edffb56-5abf-11e8-9ae2-394c74c741d7.png)

JS
![image](https://user-images.githubusercontent.com/23407525/40255952-42005ed8-5abf-11e8-8330-2bd65ba6d24a.png)
![image](https://user-images.githubusercontent.com/23407525/40255997-691cba0c-5abf-11e8-98ff-bf69ce413668.png)

The functions get_dados_incluir and set_dados_from are used to return Form Data into components.

So, there is anyone who passed through same problem?

**Comment by tjf9549** [comment]
I'm seeing a similar problem but on popovers. Looks like its receiving the change fine, but then the previous value is being resent.
