### ISSUE TITLE
[Feature Request] Way to have "recommended options" in the dropdown before searching

### ISSUE THREAD

**Issue by rreynier** [select2/select2#5298]
In the application I am coding for by the time a user gets to the select2 dropdown, we have a fairly good idea which options they may be interested in.  It would be nice to be able to click the drop down, and be presented with say "10 recommended options" and then if you start typing, it goes right into a search (in my case ajax). Is this already possible, or something that could be added?

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:
