### ISSUE TITLE
The default matcher should trim the term

### ISSUE THREAD

**Issue by EvgenyOrekhov** [select2/select2#5300]
In most cases it is desired to trim the search term before matching, therefore it should be done by default. The trimming would be especially useful when using tags in "multiple" mode, since it would prevent the adding of duplicate entries.

Steps to reproduce:

1. Go to https://jsbin.com/kinotukika/edit?html,js,output
2. Type "test " (with a space at the end) into the input

Expected: "test " should match "test".
Actual: nothing matches, "No results found" message is shown.

Select2 version: any
Browser version: any
OS version: any

**Comment by nikhilbarar** [comment]
Can i pick this up?

**Comment by nikhilbarar** [comment]
Any update on this? I'd like to send a PR for this

**Comment by pedrofurtado** [comment]
This discussion will continue inside PR -> https://github.com/select2/select2/pull/5318
