### ISSUE TITLE
Select2 with multiple

### ISSUE THREAD

**Issue by kimthangatm** [select2/select2#5301]
I use selected 2 with Angular 2, but get value `JSON.stringify( $('#edit_category_ids').val()` 

```html
<select id="edit_category_ids" multiple style="width:100%" class="form-control" name="edit_category_ids">
            <option value="1">1</option>
            <option value="2">2</option>           
          </select>
```

`Return`
```json
[
  "0: '1'",
  "1: '2'"
]
```

`Expected`: ['1','2']

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
