### ISSUE TITLE
Feature request: Multi-select with shift and Ctrl/Cmd keys functionality?

### ISSUE THREAD

**Issue by henrymorton** [select2/select2#5302]
Hi all,

I am a user rather than a coder, and I have a feature request - using multi-select with SHIFT and CTRL/CMD key functionality.

At the moment, with multi-select activated, you can only populate a box by making one selection per mouse click.

For example, if I have 100 entries, say ABC000 to ABC099 and I only want to select ABC000 to ABC049, I type ABC in the search box and then have to click on each of ABC000 to ABC049 individually to get them all to populate.

What I am suggesting, to greatly speed up the process (I have thousands of entries I need to categorise), is to add the standard functionality of SHIFT and CTRL/CMD keys, whereby if you are holding SHIFT, before you click, and then click on two search items, it will allow you to select and populate that range.

Similarly, with CTRL/CMD held down, you can click on multiple items in the search box, that will then populate, say, when you release the CTRL key.

Hoping this is possible as it seems sensible to me and would exponentially speed up my work and, I am sure, that of others.

If anything is unclear, please let me know.

Many thanks!

Henry

**Comment by pedrofurtado** [comment]
PR's are welcome :handshake: 
but dont open issues in github with caps lock :+1: it is very ugly.

**Comment by henrymorton** [comment]
Hi Pedro,

Do you think this functionality is something that could be added?

Cheers,

Henry

**Comment by henrymorton** [comment]
Is there any way to see if anyone is able to help on this?

**Comment by henrymorton** [comment]
Hi there,

I would still be very interested in a solution to this, as I am currently going through a very slow process without it.

**Comment by jamezrgomez** [comment]
Hi @henrymorton ,
What is the current status on this? Any workarounds, functionality-wise similar implementations?

To be fair, a selectAll button is what I'm trying to implement without breaking the adapter at the moment, so while not exactly what you were looking for if you were still looking for ways to populate the box this issue thread might be of interest: https://github.com/select2/select2/issues/195

**Comment by henrymorton** [comment]
Hi @jamezrgomez ,

Many thanks for your interest!!

So, I am a user, rather than a coder and nobody seems to have taken up the challenge, as yet.

The select all functionality may speed things up for me as well, but that also does not look like it has been resolved, is that correct?

**Comment by jamezrgomez** [comment]
Hi Henry,
I am a dev, albeit unfortunately a very junior one atm so I'm being somewhat slow digesting select2, will keep you updated if I have a breakthrough this decade.

Also, the thread I sent you contains Eric Zell's solution which does work as is, however integrating it with your code might prove to be a tentative thing, leaving it to your discretion: https://jsfiddle.net/hula_zell/50v60cm6/

**Comment by henrymorton** [comment]
Many thanks James!

**Comment by henrymorton** [comment]
Still hoping for some help on this, if anyone can?

**Comment by kevin-brown** [comment]
This is something which would still be useful, but at this time is not a high priority for us. This would require adding in "memory" for what was selected recently in the dropdown as well as what was displayed. While this is likely feasible, it's not a quick thing to implement.

With all that being said, I'm willing to review and assist on pull requests which work to get this feature implemented.

**Comment by henrymorton** [comment]
Hey Kevin, 

Just seen I forgot to say thanks for the note.

I am still slogging away with having to individually click things, so would be very happy and grateful if anyone felt like tackling this!

**Comment by kevin-brown** [comment]
I believe the CTRL + Click portion of this is already implemented, it's just the SHIFT + Click that is left. We would also need to implement keyboard shortcuts for doing these to remain consistent.

More than likely we would be implementing the following keyboard shortcuts provided by the [WAI-ARIA Authoring Practices for listbox](https://www.w3.org/TR/wai-aria-practices-1.2/#Listbox).

> Shift + Down Arrow (Optional): Moves focus to and toggles the selected state of the next option.
Shift + Up Arrow (Optional): Moves focus to and toggles the selected state of the previous option.
Shift + Space (Optional): Selects contiguous items from the most recently selected item to the focused item.

As far as I can tell, these do not impact the existing keyboard shortcuts that exist.

**Comment by saeedhmt** [comment]
Hi
I need this feature too. have you found any solution?

**Comment by mvid-servoy** [comment]
Shift + Click is requested by several of our clients. 
Any chance to have this implemented in the near future?

**Comment by sridhargoshika** [comment]
Here is an example for remote data source for Shift keys functionality,

count_shift = 0;
shift_array = [];
$j(".assigneeSelection").select2({ allowClear: true, closeOnSelect:false}
).on("select2:select", function (e) {
if (event.shiftKey) {
shift_array.push({ id: $(document).find('li.select2-results__option--highlighted').attr('data-select2-id'), data: e.params.data });
count_shift++;
}
if (count_shift == 2) {
var lower = (shift_array[0].id < shift_array[1].id ? shift_array[0].id : shift_array[1].id);
var higher = (shift_array[1].id > shift_array[0].id ? shift_array[1].id : shift_array[0].id);
for (var i = lower; i <= higher; i++) {
$('.assigneeSelection option:contains("' + $('li.select2-results__option[data-select2-id='+i+']').text() + '")').prop("selected", true);
}
$('select.assigneeSelection').trigger("change");
$('select.assigneeSelection').select2('close');
count_shift = 0;
shift_array = [];
}
});

**Comment by dande-sun** [comment]
Why does select2 still don't have a select all feature, I would very much like select2 to have this, I'm really reluctant to coding a other repository just for the select all feature. please make it, OK?
https://github.com/dande-sun/select2
