### ISSUE TITLE
It should be easier to use a remote AJAX source and filter locally.

### ISSUE THREAD

**Issue by VictorioBerra** [select2/select2#5304]
I would call this a bug, or maybe just poor design. If you use a remote ajax data source, and you do not use paging ([the default config](https://select2.org/data-sources/ajax#pagination)) you will get ALL results back from most regular APIs that don't implement paging. **So why then is all searching attempted to be done remotely?**

At the very least, I think it would be incredibly useful to have a way to force filtering locally, or use the data source as a one time initial pull and then treat it as an array DS the rest of its lifetime.

Right now, I am forced to either implement server side paging, or research for an hour how to hack this otherwise incredibly configurable library to do my bidding. Also, doing an initial ajax load and then populating the data via an array  is not an option for me as I only want my initial load to happen when a dropdown is first interacted with. I have way too many dropdowns on my page for that to be viable.

**Comment by pedrofurtado** [comment]
An rest API without pagination is a poor design. The filter and overhead of data transferred by internet should be avoided in the beginning of request, in server-side. The server must be "smart" to send only we want, filtered or not. Select2 only outputs this in HTML code, and allow integration with pagination. Load all records of an API and then filter locally (in browser) is bad.
For URL reference, check this: https://github.com/select2/select2/issues/5352

**Comment by VictorioBerra** [comment]
Many of my endpoints only return 10 records of lookup table data total. So if were talking about overhead, I have to have the overhead of maintaining a ton of extra server-side code now because instead of making Select2 more flexible you close issues as "Well your server side design is just bad!"
