### ISSUE TITLE
Multi select search is disabled

### ISSUE THREAD

**Issue by ellenhutchings** [select2/select2#5305]
On the creation of a select2 with multiselect and ajax source, no search is available. Only after selecting an option or deselecting, and causing a placeholder update does the input that search is done with get created.

https://stackoverflow.com/questions/50690803/multiselect2-initial-serach-is-disabled

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
