### ISSUE TITLE
Dropdown issue with assistive technology

### ISSUE THREAD

**Issue by vcardeal** [select2/select2#5310]
When I reach combobox screenreaders tell me that I'm in this kind of element. But when I enter the element and try to row down with arrow keys the list that select2 provide me don't alert any change on foccus elements. 

![image](https://user-images.githubusercontent.com/30213232/41259545-54ef41f0-6daa-11e8-867a-2ab1d310d23d.png)

**Comment by MinThaMie** [comment]
I've noticed a similar problem. Specifically when there is a filter box in the dropdown. The focus of the screenreader seems to go into that box instead of to the dropdown. By navigating to the combobox again you can kinda trick the system. But it would be nice if this would be fixed.

**Comment by akinhwan** [comment]
i have this problem too! do you know why it is generated as a <ul> with <li> elements?
the first paragraph here says that it should be a <select> with <options> 
https://select2.org/options
