### ISSUE TITLE
Select2 4.0.5, 4.0.6 select2:select select2:selecting events are not triggered correctly for the first option only

### ISSUE THREAD

**Issue by Thomas-Webber** [select2/select2#5311]
Hello, I noticed a bug when listening for the select2:select or select2:selecting event.
**When we select the first option the select2:select event is not triggered correctly**

https://jsfiddle.net/hwuscr0t/10/
http://jsbin.com/ruhozag/edit?html,js,output

The bug also shows up on the documentation page for the first select2 input.
https://select2.org/programmatic-control/events#limiting-the-scope-of-the-change-event

I think its because of the highlighted option. It seems that we can't select the highlighted option.
This highlighted option is selected in the first place. I can retrieve the data using
`$('#select2').val()`

I was expecting the text to be shown on the input, when we select the first option, even if it is already highlighted and if the data is already set. It would be nice to have the input to display the text when we select this option. 
At the moment the user doesn't know if the option is really selected, he has to select the second option, then the first one again to have the input set with the proper text. 

I am using Chrome Version 66.0.3359.181 (Official Build) (64-bit), and Firefox 60.0.2 (64-Bit)

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
