### ISSUE TITLE
[multiselect] Cannot prevent of Dropdown opening when clicking on a selected option

### ISSUE THREAD

**Issue by Ragash** [select2/select2#5312]
Hi guys, 

The problem is in the default behaviour of Select2.
im trying to ovverride the opening of dropdown on click of a "tag", but it seems to do not like any configuration that were already finded for, as exemple, closing the dropdown when removing a selection.

an example is pretty clear: http://jsbin.com/jojamokehu/1/edit?html,js,output
there's something i miss or there arent feature that permit that kind of behaviour?

thanks and sorry for my english

**Comment by adamwirth** [comment]
is this what you're looking for? [select2.org/dropdown#forcing-the-dropdown-to-remain-open-after-selection](https://select2.org/dropdown#forcing-the-dropdown-to-remain-open-after-selection)

it would look like the following in your provided snippet's javascript: ```$(document).ready(function() {
    $('#example1').select2({
      closeOnSelect: false
    });
});
```

**Comment by Ragash** [comment]
Hi! and thanks for the reply! i was trying to obtain exactly the opposite 😄 

by the way, i solved issue in a wacky way, but well... it works, and maybe i will change if i'll find a better solution:

Scenario: 
- i have a bunch of Select2 items,
- i want to click on current selected "tags" and open a modal with an ajax request to get the details of the item

Solution:
- Select2 items are initialited as normal, (see example)
- then via a document listner i add a seTimout function which call a simple "close" on the Item clicked (found via class name).


```
 $(document).on('click', '.feat-item', function(e) {
        e.preventDefault();
        setTimeout(function() {
            $('.select2entity').select2('close');
        }, 2);

       //Ajax call and my other logic
});
```

- modal is loaded using bootstrap, overriding the `templateResult` and `templateSelection` as usual.

Hope this will help others 😄 
p.s. i can say issue could be closed
