### ISSUE TITLE
How to handle more than 1 column of data

### ISSUE THREAD

**Issue by rekotc** [select2/select2#5313]
Is it possible to have multiple columns of data inside a select2 widget?
For example with 3 columns;

col1              col2    col3
Italy               IT       2005 
Germany     GER     1996

thanks in advance.

**Comment by samsiu2014** [comment]
I faced the same problem and followed the steps [here](https://stackoverflow.com/questions/16556261/display-multiple-columns-in-select2).
However, i couldn't get the expected result.
I would like to ask if there is anyone has ideas on it.
