### ISSUE TITLE
templateSelection for multiple selection not working on chrome for Android

### ISSUE THREAD

**Issue by EhabSherif** [select2/select2#5319]
I'm writing a small templateSelection script to render the label of the optgroup right beside my selection text, it works fine on chrome for desktop but on chrome for android it doesn't render, when I click an option the options dropdown doesn't even close.

I'm using Android 6.0
Chrome 65.0.3325.109

here's my code..

> 
	$('#select2_multiple_selection').select2({
		templateSelection: function(item){
			var optgroup_label = $('select[name="' + item.element.offsetParent.name + '"] option[value="' + item.id + '"]').parent('optgroup').prop('label');
			if(typeof optgroup_label !== 'undefined') {
				return optgroup_label + ' \u00bb ' + item.text;
			} else {
				return item.text;
			}
		}
	});

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code and steps described there, to allow us to follow this steps and check the situation). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
