### ISSUE TITLE
Adding new options to AJAXized Select2 does not work as described in docs

### ISSUE THREAD

**Issue by Voyteck** [select2/select2#5322]
I have used SELECT2 as an entry for email addresses. They can be either typed-in (and then they are validated against email address regexp) or chosen from addressbook (queries retrieved from AJAX).
Now I need to put some of the addresses programmatically and have no luck adding them correctly as the docs describes.

The configuration for Select2 is following:

```
{
	ajax: 					{
		url				: ajaxAddress_searchContacts,
		dataType			: 'json',
		method			: 'POST',
		delay			: 250,
		cache			: true,
	},
	minimumInputLength		: 3,
	tags						: true,
	tokenSeparators			: [';', ','],
	templateResult			: function(address) {
		if (address.address_name)
			return address.address_name + ' <' + address.email_address + '>';
		return address.text;
	},
	templateSelection		: function(address) {
		if (address.address_name) {
			return $('<span/>')
				.attr({
					'data-addressid'		: address.id,
					'data-address_name'	: address.address_name,
					'data-email_address'	: address.email_address
				})
				.text(address.address_name)
				.popover({
					content				: address.email_address,
					html					: true,
					placement			: 'bottom',
					trigger				: 'hover',
				})	
		}
		else {
			var emailRegexp = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
			if (emailRegexp.test(String(address.text)))
				return address.text;
			else
				return $('<span/>').addClass('mail-invalid').text(address.text);
		}
	},	
}
```

The <select> is within HTML following: <select id="select2" multiple></select2>

Now the code to add new option is following:

```
var option = new Option('Jan Kowalski', '180', true, true);
$('#select2').append(option).trigger('change').trigger({
	type: 'select2:select',
	params: {
		data: {
			id: '180',
			text: 'Jan Kowalski',
			address_name: 'Jan Kowalski',
			addressid: 180,
			email_address: 'test@test.com.pl'
		}
	}
});
```

Any idea what might be wrong there ?
The entry is actually added, but it is immediatelly wrongly validated and the data such as address_name is not available on $('#select2').select2('data')

**Comment by seanpoulter** [comment]
Change the last `*` to a `+` in your `emailRegexp`.

**Comment by pedrofurtado** [comment]
Please, send us a JSFiddle example code simulating this scenario (with runnable code). It is much more easy to understand and help to provide some solution or workaround. You are free to reopen when the JSFiddle are done.
