### ISSUE TITLE
Is still actively maintained?

### ISSUE THREAD

**Issue by pedrofurtado** [select2/select2#5323]
Is still actively maintained? There are many old open issues and pull requests. If you guys are looking for contributors, I can help. The latest version is in "release candidate" since 2017.

Thanks!

**Comment by Zombaya** [comment]
Pinging @alexweissman and @kevin-brown since they seem to have been maintaining previously.

**Comment by danreg** [comment]
simply no.

**Comment by elchristo** [comment]
any news on this matter ?

**Comment by ivaynberg** [comment]
@pedrofurtado if you want to help us maintain 4.x i will be happy to add you to the team

**Comment by pedrofurtado** [comment]
@ivaynberg Yes, I want. Add me to the team as soon as possible. Then, I will reserve some time during this week or next week to review PR's and giving feedback for issues, to decrease the number of them :+1:

**Comment by ivaynberg** [comment]
@pedrofurtado you are added, you should have an invite waiting. I am also starting a slack org to make it easier for devs to collaborate. which email do you want me to send you an invite to?

**Comment by pedrofurtado** [comment]
@ivaynberg pedro.felipe.azevedo.furtado@gmail.com

**Comment by ivaynberg** [comment]
invite sent.
