### ISSUE TITLE
Remove items from results when selected.

### ISSUE THREAD

**Issue by abbottmw** [select2/select2#5324]
I am currently working with 3.5.1 version of Select2 and looking at updating it to the latest 4.x version.   While playing around with 4.0.6, I noticed it doesn't do one thing that the earlier version did out of the box.  

In 4.0.6, when you have a multi select field, and you choose a selection, it still remains in the results.  Selecting that same result will remove the item.  I understand this is similar to how the multi select works in standard select fields, but I need it to work like 3.5.1.

I added in a templateResult in the setup which  checks if that option is selected to return null, otherwise return the option.text.   This works, but a key missing piece is that it doesn't fire the No Results Found if you have selected all the items and there are no more items in the results.    Here is a [jsfiddle](http://jsfiddle.net/abbottmw/and30qoj/) of this example.  When you try to search for an item by typing in the field, it will show the No Results message, but clicking the down arrow in the select field will not.

I modified this same fiddle and pointed it to 3.5.1 which shows the "No results found" message when you have selected all the items.   Here is a  [jsfiddle](http://jsfiddle.net/abbottmw/b098r513/) of this example.

I realize I can hack my way through and get it to work in 4.0.6, but I feel this should be available as a configuration option of some kind to allow this behavior that was found in 3.5.1.

Here is a [forum post](https://forums.select2.org/t/remove-option-from-results-when-selected/341) that I created asking about this too.

**Comment by pedrofurtado** [comment]
sorry, the 3.x version is not maintained anymore. But if still happens in 4.x version, reopen the issue and send a JSFiddle example and a PR to fix it.
