### ISSUE TITLE
How to show images or icons to individual items after selection in single and multiple select2 box

### ISSUE THREAD

**Issue by rerraw** [select2/select2#5328]
As we know by using the `templateResult` option we can add icons or images next to select box option texts. but I want after selection the single or multiple values also show the icon or image with text like this photo below.

![s21](https://user-images.githubusercontent.com/6832360/42478771-a8ed982a-83de-11e8-8dcc-13ef9543c892.jpg)

I added some images to select dropdown I used this function below based on [Select2 Documentation](https://select2.org/dropdown#templating). Also, I want to show the images after selection with text how can do this?

    function formatGrid (grid) {
        if (!grid.id) {
            return grid.text;
        }
        var baseUrl = hpemenu_ajax_object.gridImageFolder;
        var gridName = grid.element.value.toLowerCase();
        var $grid = $(
      '<span><img src="' + baseUrl + '/' + parseInt(gridName) + '.png" class="img-flag" /> ' + grid.text + '</span>'
        );
        return $grid;
    };

    $(".bsnselectgrid").select2({
        placeholder: "Select ...",
        width: '100%',
        templateResult: formatGrid,
    });

**Comment by BhavinKhatri** [comment]
https://select2.org/selections. I guess you are looking for something like this. Like same function with different option as 'templateSelection'
