### ISSUE TITLE
Cannot get JSON data into select2 statement

### ISSUE THREAD

**Issue by raghurocky123** [select2/select2#5330]
$(document).ready(function(){

            $("#selUser").select2({
                ajax: {
                    url: "http://thingtronics.co.in/testproject/trainnamedetails",
                    type: "post",
                    dataType: 'json',
                    delay: 250,
                    data: function (params) {
                        return {
                            searchTerm: params.term // search term
                        };
                    },
                    processResults: function (response) {
                        return {
                            results: response
                        };
                    },
                    cache: true
                }
            });
        });

**Comment by raghurocky123** [comment]
Can anyone help me with this issue please

**Comment by pedrofurtado** [comment]
send a jsfiddle example. reopen when ready
