### ISSUE TITLE
Select2, modal, multiple keeps loading 

### ISSUE THREAD

**Issue by mati950708** [select2/select2#5333]
I know that there already is an issue of this and that it´s already solve, but I just CAN´T find it anymore... The issue is that when I use select2 in a multiple, except for the first one, the rest keep loading forever... I know that there is a way of solving it changing something in the vendor? or somewhere but I just can´t find the subject... not even remember if that subject was here thought... And really need it... There may be a new solution, it´s really been a long time since I last found something like that...
The next image shows how it is with the Estado value
![1](https://user-images.githubusercontent.com/37123090/43030320-3ebce1d0-8c54-11e8-8e10-13ddaefee510.PNG)

And this one shows how is expected... I already tried copy/paste a good part of my previous project but it didin´t work XD With the Order information
![2](https://user-images.githubusercontent.com/37123090/43030340-651d84f6-8c54-11e8-87ea-42522449cb5b.PNG)

**Comment by pedrofurtado** [comment]
send us a jsfiddle example code, describing the scenario. it is much more easy to really understand and provide some solution. reopen when ready
