### ISSUE TITLE
Scroll Bars in browser

### ISSUE THREAD

**Issue by wings77** [select2/select2#5334]
I have a problem with the select2, when it is displayed the scroll bars appear in the browser, I have tried it with chrome, firefox and edge, it happens in localhost and on the internet.

Select2 4.0.3
jquery 3.3.1

Thank you.

![select2_scrollbars](https://user-images.githubusercontent.com/30241218/43272532-d07677ac-90bf-11e8-887b-26297fdb5acf.gif)

**Comment by gammalogic** [comment]
Are you using Bootstrap? I have just added this plugin to a Bootstrap web site and noticed the same problem in Firefox and Safari.

**Comment by gammalogic** [comment]
Try adding the following CSS code to your select2 theme:

    .select2-container--mytheme {
        display: block;
    }

This seems to fix the problem although I'm not sure how/why it works. Setting display:block is equivalent to setting width:100% so if you're using Bootstrap and want the select menu to be set to the full width of the column you could use that.

**Comment by wings77** [comment]
it does not work!

**Comment by tameroski** [comment]
Got the very same issue with version 4.0.5. 
I'm not using Bootstrap, but Foundation. Adding a `display:block;` to the container does not help.

**Comment by tameroski** [comment]
Nevermind, someone (i'm probably gonna fire) added a `width:100%;` on the `select2-container` element ...
