### ISSUE TITLE
Multiple Select Drop Down Box Resets to First Value Selected

### ISSUE THREAD

**Issue by greenfrogs** [select2/select2#5337]
When using a multiple select element the list will reset to the first one selected; this can be seen in [the documentation](https://select2.org/appearance) under appearance using the multiple select element by selecting Alaska then another (such as Montana) and then when the drop down box is opened again it will default to Alaska instead of Montana (not just the top of the list as if Montana is selected first it will be default).

**Comment by pedrofurtado** [comment]
send us a jsfiddle example code, describing steps there. it is much more easy to understand and provide some solution. reopen when ready
