### ISSUE TITLE
Copy+Paste multiple mail addresses at once

### ISSUE THREAD

**Issue by guettli** [select2/select2#5338]
Feature Request:

I use select2 for mail-adresses. There can be added multiple addresses in the "to" field.

The mail addresses are no strict foreign keys, the user can create a new adress if the syntax is correct.

It would be great if you could copy+paste (and create) several addresses at once.

I hope you can understand my use case. If not please ask.

Before creating the issue, I asked here to be sure this is a new feature: https://forums.select2.org/t/copy-paste-three-mail-addresses-jsfiddle-included/370/3

**Comment by pedrofurtado** [comment]
We are focused now in UI bug fixes. But if you create a PR with unit tests that implement this feature, I would be glad to review that and merge (if tests passed).
