### ISSUE TITLE
:close event fires after :open when switching between two different select2 boxes

### ISSUE THREAD

**Issue by librisius** [select2/select2#5339]
1. https://select2.org/programmatic-control/events#examples
2. Screenshot:  ![screenshot_21](https://user-images.githubusercontent.com/7526050/43955698-00fc26ba-9caa-11e8-8ad1-b70acbfef28b.png)
3. 
    1. Open "Examples" block on this page: https://select2.org/programmatic-control/events#examples
    2. click on the second one selectbox (#2)
    3. don't close it and click on the first one (#1)
    4. Check event log

You can see that close event of selectbox #2 fires after open event #1. This is very bad because a function that is supposed to be triggered after closing actually work after opening.

4. Version: the latest one

**Comment by librisius** [comment]
to fix it add:

>   BaseSelection.prototype._closeOpenedHandler = function () {
>     var self = this;
> 
>     $('.select2.select2-container--open').each(function () {
>       Utils.GetData(this, 'element').select2('close');
>     });
>   };

above: `BaseSelection.prototype._attachCloseHandler`

**AND**

`self._closeOpenedHandler();` above `self._attachCloseHandler(container);`

**Comment by pedrofurtado** [comment]
@librisius Thanks for feedback! Could you open a PR adding this fix? I will glad to review that and merge if is ok :+1: So, other users can have this bug fixed on next versions.

**Comment by librisius** [comment]
@pedrofurtado **Done:** https://github.com/select2/select2/pull/5368
