### ISSUE TITLE
minimumInputLength UPDATE

### ISSUE THREAD

**Issue by srburton** [select2/select2#5340]
Ola I would like to add something that can identify when the user stopped typing as action he sends the request only when identified that stopped typing

```
        $(".select2").select2({
            minimumInputLength: 4,
            stoppedTypingRequest: true,
            ajax: {
```

**Comment by pedrofurtado** [comment]
@renatoprogramer You can combine two options for this: `minimumInputLength` and ajax `delay` property. So, a example code could be like this:

```javascript
$('#mySelector').select2({
  minimumInputLength: 3,
  // other select2 options ...
  ajax: {
    delay: 250,
    // other ajax options ...
  }
});
```

By this way, the ajax is only triggered when user types at least 3 character and the plugin still wait 250ms to start the request.

Documentation for reference: https://select2.org/data-sources/ajax#rate-limiting-requests
