### ISSUE TITLE
Select2 with Dragon NaturallySpeaking software

### ISSUE THREAD

**Issue by abhrodipgit** [select2/select2#5344]
I have implemented a select2 multiselect for list of states in a application, and it works file using typing the state names. But with Dragon NaturallySpeaking software if you speak in select2 to select a state, it only show the last char of what you spoke and do not autosearch, you have to press space to see the whole text and then press backspace to start the search, looks like some event does not fire when you speak than type. Not sure if there is any solution that I can try. Thank you !

**Comment by pedrofurtado** [comment]
@abhrodipgit We don't have plans to integrate select2 with Dragon NaturallySpeaking. But you are free to fork the repo and make the integration yourself, and open a PR to include this integration to select2 official repo.
