### ISSUE TITLE
Problem when pasting in select2 with tags

### ISSUE THREAD

**Issue by mujoh** [select2/select2#5346]
Hi,

I am using select2 and user can create tags for emails. There are token separators like comma, space, tab and user is also allowed to paste emails in select2 input. Issue is when there are lots of emails, for example 300-400, select2 causes whole page crash. Is there any way to solve this problem.

Thanks in advance for reply

**Comment by pedrofurtado** [comment]
@mujoh Please, send a JSFiddle example simulating this scenario. It will be more easy to understand and think about a solution/hotfix for it. :+1:
