### ISSUE TITLE
Option from first character of typed text is created

### ISSUE THREAD

**Issue by awiech** [select2/select2#5348]
When you start typing text in the box, the first typed character is shown as an option.

![auswahl_020](https://user-images.githubusercontent.com/8133544/44729275-c044dc00-aade-11e8-8608-a966eddef5e5.png)

A snippet that demonstrates the issue: http://jsbin.com/lilutejaha/1/edit?html,js,output

If you change the Select2 version to 4.0.2, it works correctly.

**Comment by pedrofurtado** [comment]
@awiech PR's are welcome 🤝

**Comment by C3maLi** [comment]
+1
