### ISSUE TITLE
Is there a way to remove a selected item programmatically?

### ISSUE THREAD

**Issue by aj7** [select2/select2#535]
Hi,
Is there a way to remove an item programmatically? something like $('myselect').select2('deselect',val) ???

**Comment by mak5** [comment]
@Snogo i've the same problem can you give me the solution you found ? thanks alot

**Comment by Snogo** [comment]
@mak5 I dont know the exact solution to the problem any more but I could send you some code if that helps via email.

**Comment by mak5** [comment]
yes if you want my mail is "dalliii@hotmail.com" thank you so much

**Comment by mak5** [comment]
Here a [link](http://stackoverflow.com/questions/37997872/update-jquery-select2-available-choices-for-multiple-instances) to the solution I found on stackoverflow

**Comment by alex1007** [comment]
`$('#my_input').select2('data', new_data);`

assign new data to `data` won't work anymore. V4.00 Chrome

**Comment by lbm-trentm** [comment]
@alex1007 you should be able to refresh data.

To reset it completely.
`$('#my_input').select2({data: [{id: '', text: ''}]});`

To populate it:
`$('#my_input').select2({data: dataArrayVariable});`

If you don't want the dropdown to keep adding records, you will need to reset it first.

**Comment by sineld** [comment]
This is how I do:

`$('#my_input').select2('destroy').val('').select2();`

**Comment by kul1010** [comment]
$('#selEmployeeName').on('select2:select', function (e) {
    var data = e.params.data;
selected_emp_id=data.id; //if data object has id and text then use data.id
// you can pass data object to other function also according to your need like below
// abc(data);
$("#selEmployeeName option[value='"+selected_emp_id+"']").remove();
});

**Comment by mohan201** [comment]
This is how I solved it.

``let newArray = [];
let newData = $.grep($('#select2').select2('data'), function (value) {
     return value['id'] != value_to_remove;
 });
 
newData.forEach(function(data) {
      newArray.push(+data.id);
 });

 $('#select2').select2('destroy').val(newArray).select2();``

**Comment by kul1010** [comment]
use below code in place of line $('#select2').select2('destroy').val(newArray).select2();

$('#select2').val(newArray).trigger('change');

**Comment by mohan201** [comment]
@kul1010 Yes you are right. I updated my answer. Thanks
