### ISSUE TITLE
Not much examples about pagination results

### ISSUE THREAD

**Issue by Abdulmanan0315** [select2/select2#5352]
The ajax remote data works fine for a limit,but i want to have load more data so that if user does not find he can scroll and get more data to select from,i am struggling very hard to get this working, does not found much examples about the pagination usage ,on the website it is documented about the usage but not a real world example is present out there. **i WOULD LOVE TO GET A WORKING EXAMPLE**
I am trying the following code but it is showing the 10 results and no pagination (loading more data)
**using select2(4.0.6rc.1)**
**JS:**

      $('#compose_username').select2({
			dropdownParent: $("#modal-compose") ,
			placeholder: "Search Username...",
			minimumInputLength: 1,
			ajax: {
				url: "username.php",
				dataType: 'json',
				delay: 250,
				cache: false,
				data: function (params) {
					return {
						term: params.term,
						page: params.page						
						//a: params.term, // search term
						//psf: params.page
					};
				},			
				processResults: function (data, params) {
				  // parse the results into the format expected by Select2
				  // since we are using custom formatting functions we do not need to
				  // alter the remote JSON data, except to indicate that infinite
				  // scrolling can be used
				  params.page = params.page || 1;
				  console.log(params.page);
					console.log(data);
					var result = $.map(data, function (item) { return { id: item.id, text: item.username, total_count: item.total_count }});
					//var s = $.map(data, function (item) { return { total_count: item.total_count }});
				  
				  return {
					results: result,
					pagination: {
					  more: (params.page * 1) > data.total_count
					},
				  };
				  					console.log(more);

				},				
				// processResults: function(data) {
					// console.log(data);
					// var result = $.map(data.results, function (item) { return { id: item.id, text: item.username }});
					// return { results: result };
				// }
			}
      });

**php**
```
	try{
		$stmt = $db_con->query("SELECT id,first_name FROM datatables_demo WHERE first_name LIKE '%".$_GET['term']."%' LIMIT 10 OFFSET 10");
		$stmt->execute();
		$count = $stmt->rowCount();
			$json = [];
			while($row = $stmt->fetch(PDO::FETCH_ASSOC)){
				 $json[] = ['id'=>$row['id'], 'username'=>$row['first_name'], 'total_count'=>$count];
			}
			echo json_encode($json);
	}
	catch(PDOException $e){
		echo $e->getMessage();
	}
```

**JSON DATA:**

Array(10)
0
:
{id: "19", username: "Rhoda", total_count: 10}
1
:
{id: "20", username: "Rashad", total_count: 10}
2
:
{id: "22", username: "Laurie", total_count: 10}
3
:
{id: "24", username: "Travon", total_count: 10}
4
:
{id: "26", username: "Charlene", total_count: 10}
5
:
{id: "27", username: "Alice", total_count: 10}
6
:
{id: "28", username: "Joaquin", total_count: 10}
7
:
{id: "33", username: "Emelia", total_count: 10}
8
:
{id: "34", username: "Tiara", total_count: 10}
9
:
{id: "35", username: "Walker", total_count: 10}
length
:
10
__proto__
:
Array(0)

**Comment by pedrofurtado** [comment]
https://select2.org/data-sources/ajax
https://stackoverflow.com/questions/32533757/select2-v4-how-to-paginate-results-using-ajax
https://stackoverflow.com/questions/49632012/select2-local-pagination-infinite-scrolling

and much more.

**Comment by b2simpleman24** [comment]
the same issue, finding solution right now~

**Comment by Abdulmanan0315** [comment]
In case someone wants a proper solution, here is the question and answer i provided:
[](https://stackoverflow.com/questions/52106550/paginate-result-using-select-2-ajax-remote-data/52130077#52130077)
