### ISSUE TITLE
Publish select2 version 3.5.4 on NPM repository

### ISSUE THREAD

**Issue by fbaligand** [select2/select2#5360]
Currently, select2 last 3.x version is not available on NPM repository.
There is no version published since version 3.5.1.

=> Could you publish select2 last 3.x version (3.5.4) on NPM repository ?

**Comment by pedrofurtado** [comment]
@fbaligand The version 3 is not maintained anymore. You could add the dependency in you package.json getting directly from branch `stable/3.5`.

**Comment by fbaligand** [comment]
Well, it is not an evolution request.
I just ask to publish on npm, the existing 3.5.4 released version.

**Comment by pedrofurtado** [comment]
Example package.json to include the latest 3.x version:

```json
{
  "dependencies": {
    "select2": "https://github.com/select2/select2#3.5.4"
  }
}
```

**Comment by fbaligand** [comment]
ok, thanks.
