### ISSUE TITLE
Select2 css script doesn't get loaded when hosting

### ISSUE THREAD

**Issue by LouBNielsen** [select2/select2#5364]
Hi!
I'm using select2 and I have imported these scripts in my html:

````
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
````

The styling works on localhost, it works on the docker image I have created, and it works in different browsers, but as soon as the docker image gets hosted, the styling disappears..

**Comment by DavidCarl** [comment]
Did you forget a 's' in your jquery script src on a secure page maybe? :sunglasses:
