### ISSUE TITLE
Name of the primary key is not id

### ISSUE THREAD

**Issue by yedajiang44** [select2/select2#5365]
Ajax result if the primary key is not "id"(lowercase) cannot choose
example
```json
[
    {
        "Id":1,
        "UserName":"jay1",
        "Age":"18"
    },{
        "Id":2,
        "UserName":"jay2",
        "Age":"18"
    },{
        "Id":3,
        "UserName":"jay3",
        "Age":"18"
    },{
        "Id":4,
        "UserName":"jay4",
        "Age":"18"
    },{
        "Id":5,
        "UserName":"jay5",
        "Age":"18"
    }
]
```
Just like the above example, if does not contain the attribute "id"(lowercase), select2 will not be able to work, how do I custom primary keys, or when there is no attribute "id" how to make select2 work normally

**Comment by pedrofurtado** [comment]
@yedajiang44 Sorry, I did not understand well. Please, send a JSFiddle example code simulating this scenario. Then, we will be able to help you.

**Comment by yedajiang44** [comment]
@pedrofurtado [http://jsfiddle.net/rvt81kpq/19/](http://jsfiddle.net/rvt81kpq/19/)

**Comment by pedrofurtado** [comment]
@yedajiang44 Ok, now I got. Well, the format expected by select2 in data sources, in order to able to convert it in <option> tags, is something like this below:

```json
{
  id: 1,
  text: 'dfd'
},
{
  id: 1,
  text: 'dfd'
},
...
```

So, the keys `id` and `text` are required to be lowercase. You may pre-process you data source to provide data with "Id" to "id" in server-side, for example.

**Comment by pedrofurtado** [comment]
URL for reference: https://select2.org/data-sources/formats

**Comment by yedajiang44** [comment]
Since the server uses Pascal nomenclature and involves more code, it can only be changed from me.
```javascript
$([{Id:1,Text:1},{Id:2,Text:2}]).each(function(){
    this["id"]=this.Id;
    this["text"]=this.Text;
});
```
if select2 provides api settings, that would be great, like
```javascript
$("#test").select2({
    //...
    id:"Id",
    text:"Text"
    //...
});
```

**Comment by pedrofurtado** [comment]
@yedajiang44 That is a possible alternative workaround. Thanks for posting the code :+1: It can be used for more users later

**Comment by yedajiang44** [comment]
@pedrofurtado That's great！Very looking forward to

**Comment by yedajiang44** [comment]
@pedrofurtado hey guy.Has this program been adopted?
