### ISSUE TITLE
How cancel (clear) current value ( for not multiple )

### ISSUE THREAD

**Issue by Denschik** [select2/select2#5369]
Hello everybody!
I honestly read the documentation and searched for issues. But I haven't found the answer.

I have select2 with params - "multiple: false". How can I cancel selected value?
I choose some value, but I want to cancel value and set the field empty (for not multiple select2).
Is it really possible to do this?

**Comment by pedrofurtado** [comment]
Could you add a JSFiddle example code simulating this? Then, we could help with another JSFiddle derived from yours.

**Comment by Denschik** [comment]
@pedrofurtado, hmm... May be I incorrectly explained.
1. Initially, I have the empty field ( with placeholder ).
2. I select some value ( preferably steak ).
3. But then I remember that I have a diet. And I want to cancel my choice and set the field empty ( to again see the placeholder).

I didn't think that the concrete example is required, but if it is so simpler:
https://jsfiddle.net/91nfcguq/12/

**Comment by jakeNiemiec** [comment]
@Denschik You just need to set the value to null (just like a normal select): https://jsfiddle.net/h4vcrf70/8/

More info in docs: https://select2.org/programmatic-control/add-select-clear-items#clearing-selections

**Comment by Denschik** [comment]
@jakeNiemiec, thank you for solution!
@jakeNiemiec, I'm not saying that your solution is wrong ( I'm happy that someone helped me ).
But I think this not right - such a simple action should be able to make the selet2 itself (by init-options).

Multiselect is able to cancel chosen, but singleselect  isn't able to do it. It is not right, and I think that there is a need to ask developers to add this functionality.

**Comment by mlt** [comment]
Alternatively, use `allowClear: true` https://jsfiddle.net/91nfcguq/24/.

It is unfortunate that empty line disappears when using a placeholder. The behavior should be consistent.

**Comment by guaicaiboshi** [comment]
How did you deal with it later?

**Comment by kevin-brown** [comment]
I believe you are looking for the `allowClear` option. There is an example in the docs: https://select2.org/placeholders#single-select-placeholders
