### ISSUE TITLE
Select2 tags can't write correctly Japanese, Korean, Chinese

### ISSUE THREAD

**Issue by jiny90** [select2/select2#5370]
BUG!!!

I can't type correct words Japanese, Chinese, Korean in Select2 v4.0.5 tagging support.
Any advice or solution?

**Comment by jiny90** [comment]
Downgrade 4.0.2, then it works.

**Comment by newbaner** [comment]
> Downgrade 4.0.2, then it works.

Thanks!

**Comment by onesup** [comment]
Thanks @jiny90 
Currently select2 4.0.8 still doesn't work type Korean.
4.0.2 work for me.
감사합니다 jini90 님
