### ISSUE TITLE
[Bug] Select2 initialization breaks already initialized ajax select2 elements

### ISSUE THREAD

**Issue by pedro-lb** [select2/select2#5379]
Hey, 

We ran into a problem where we have some select2 elements with ajax - each of them have their own ID and name, and they don't have the `select2` class before initialization. In the beggining of the page, we initialize them one by one using:

`$('#element-id').select2({
    width: '100%',
    ajax: { .... }
});`

And this initialization automatically adds the `select2` class to these elements. Then, when another part of the page is loaded and it contains some generic select2 elements (without ajax, using pre-loaded options), and we initialize them by using the code below, that initialization breaks the first one in the ajax select2 elements, removing the ajax from them (because they also have the `select2` class, which was added automatically).

`$('.select2').select2({
    width: '100%'
});`

Kind Regards.

Pedro.

**Comment by pedro-lb** [comment]
Update:

We solved the issue with a little hack, by immediately removing the `select2` class from the next element (the select2 itself) that is created after each select2 ajax initialization with:

`$('#element-id').next('.select2').removeClass('select2');`

Then, we can initialize generic select2 elements with the same code previously mentioned without any problems:

`$('.select2').select2({ width: '100%' });`

It works for now but we don't know if this will create any issues with the ajax select2 elements.

**Comment by mlt** [comment]
I agree it should be safe to initialize all at once multiple times safely. If that is what this bug report is about.

Nevertheless can't you just use `select.select2:not(.select2-hidden-accessible)` selector to initialize the rest as a better "workaround"?

**Comment by azhar316** [comment]
@pedro-lb I spent a day trying to figure out what the issue is. Finally by God's grace stumbled on this. Thank you so much.
