### ISSUE TITLE
Alternative transport methods: Exception when calling the `failure` callback

### ISSUE THREAD

**Issue by m0uneer** [select2/select2#5380]
Adding the following config causes exception `Cannot use 'in' operator to search for 'status' in undefined`
```javascript
transport: (params, success, failure) => {
  // ...
  failure(err); // err object that has a `status` property.
}
```

I looked into the lib to find where the problem is. It's exactly here

https://github.com/select2/select2/blob/develop/src/js/select2/data/ajax.js#L85

Where the `$request` will always be undefined.

**Fix**: Allow receiving an error param which we should check against.

```javascript
function (err) { // <- Receive an error param here
  if ('status' in err && (err.status === 0 || err.status === '0')) {
    return;
  }
// ...
```

By the way, the docs says:

```
request.on('failure', failure);
```

that indicates that the `failure` call back accepts parameters. 

If this issue and the fix are confirmed, I'm ready for the pull request!

-----
**Update**: My current workaround:

```javascript
transport: (params, success, failure) => {
  // ...
  setTimeout(() => failure(err)); // <-- #1
  // ...

   return { };  // <-- #2
}
```

**Comment by m0uneer** [comment]
is it fixed or in the plan?

**Comment by kevin-brown** [comment]
I believe the best solution would be to check if `$request` is not null first, before checking that it has the `status` property.

https://github.com/select2/select2/blob/d0ddab6cebc69e37fe51dfc287c3e3aa37b5cd1d/src/js/select2/data/ajax.js#L85

It's an optional, undocumented feature of transports where you can have it detect an aborted request. We should be fully supporting the case where a transport doesn't provide the status property.

**Comment by brianwfl88** [comment]
the transport option is expecting a return from function call.

Instead of:
```javascript
$('#mySelect2').select2({
  ajax: {
    transport: function (params, success, failure) {
      var request = new AjaxRequest(params.url, params);
      request.on('success', success);
      request.on('failure', failure);
    }
  }
});
```

Do this:
```javascript
$('#mySelect2').select2({
  ajax: {
    transport: function (params, success, failure) {
      var request = new AjaxRequest(params.url, params);
      request.on('success', success);
      request.on('failure', failure);
      return request;
    }
  }
});
```
