### ISSUE TITLE
How to properly import lang with webpack/babel?

### ISSUE THREAD

**Issue by xorock** [select2/select2#5385]
I've tried many variants and the only one working is:

```js
import 'select2'
import langpl from 'select2/src/js/select2/i18n/pl'

$('field').select2({
            language: langpl,
...
```

Importing a language directly from the "dist" directory, then `language: 'pl'` has no effect.

`Select2: The language file for "./i18n/pl" could not be automatically loaded. A fallback will be used instead.`

 Is there a better way to do it?

**Comment by rohanc** [comment]
I've posted a answer about importing select2 language files to a StackOverflow question, [How can I using select2 with webpack?](https://stackoverflow.com/a/57000033/1140110). This was with select2 v4.0.7 and webpack 4.32.2.
