### ISSUE TITLE
onchange event not dispatched

### ISSUE THREAD

**Issue by YglesEyes** [select2/select2#5390]
Hello,
In recent browser (ex: Chrome 69) select2 doesn't trigger onchange event (when use vanillaJS addEventListener) of linked select element.

The documentation states that onchange event is dispatched when user clicks and not necessary on set value by JS.

https://developer.mozilla.org/en-US/docs/Web/Events/change#Description

**Comment by os1r1s110** [comment]
I was about to open a new issue to report the exact same problem, so +1 on this one for me too.

**Comment by MonsieurNerd** [comment]
I face this issue too, a fix would be great.

**Comment by JiriCepelkaFirstLineSoftware** [comment]
I created a [new issue](https://github.com/select2/select2/issues/5420) for this bug with details and sample.
