### ISSUE TITLE
Dropdown continues to open upwards even with space below

### ISSUE THREAD

**Issue by admrwe** [select2/select2#5393]
## Bug Description
When screen placement causes the dropdown to open upwards it will continue to open upwards even when you scroll to provide adequate space below. It will continue to open upwards until it is close enough to the top edge of the viewport to be forced back below.

## Steps to Reproduce
1. Navigate to [this page](https://select2.org/appearance#labels) and position one of the Label examples close enough to the bottom of the viewport to cause it to open upwards
1. Scroll up to provide enough space for it to open downwards
1. Click and notice that it continues to open upwards
1. Scroll up until there is no longer space for it to open upwards, click and notice that it switches back to downwards.

## Expected Behavior
As the visual affordance (down caret icon) of the element indicates that it will open downwards, I would expect the dropdown to always open downwards when there is adequate space.

## Screen Cap
![select2-bug](https://user-images.githubusercontent.com/31149539/46769893-d8e60b80-ccb2-11e8-8dd2-bf2b4838c8c2.gif)

**Comment by dvtan** [comment]
Lol the issue still exists as of today. Bump.

**Comment by programmaticsoftware** [comment]
I still have this issue.
Can this be opened again?
