### ISSUE TITLE
Select2 Multiple Select Tags ( AJAX ) Bug

### ISSUE THREAD

**Issue by yelnyaface** [select2/select2#5397]
Steps to produce the Bug:

1. Create a new tag 'm':
http://prntscr.com/l65ziu
http://prntscr.com/l65zrl

2. Select another tag ( 'm tag 1 test'):

http://prntscr.com/l660ds

3. 'm' tag will be duplicated and added again, repeat the step of adding another tag ( selected or not ) will add in more 'm' tag duplicates:

http://prntscr.com/l660zc

The log console shows this:

http://prntscr.com/l6620v

This is my Multiple Select Tags Enabled JS:

```
    <script type="text/javascript">

        $(function () {
            //Initialize Select2 Elements
            $("#tags").select2({

                tags: true,
                allowClear: true,
                ajax: {
                    url: '{{ route("admin.ajax.gettagoptions") }}',
                    dataType: 'json',
                    data: function (params) {
                        return {
                            query_string: $.trim(params.term)
                        };
                    },
                    processResults: function (data) {

                        console.log(data);

                        return {

                            results: data
                        };
                    },
                    cache: false
                }

            });
        });

    </script>

```

**Comment by johnmbaughman** [comment]
A https://jsbin.com/?html,output example would be more helpful. Some image storage sites are blocked by corporate filters.
