### ISSUE TITLE
Feature request: Cache ajax requests

### ISSUE THREAD

**Issue by felixmaier1989** [select2/select2#5400]
Feature request: Cache ajax requests

# Use case (in short)
I want to asynchronously load the dropdown's options, only once, and I dont want to implement a search on my server endpoint.
- option minimumInputLength is set to 0
- option ajax is configured

# Use case (detailed)

When the users clicks the dropdown for the first time, an ajax call is made to the server endpoint, with an empty search term (?term=&q=...). This means ALL possible options will be returned. Later, if the user searches for e.g. "re", instead of an ajax call, we could, on client side, filter the list of options previously obtained. This would save some load on the server endpoint.

This would additionally allow the server endpoint not to implement a search functionality. This would be very valuable as depending on your data model, implementing a search on the server may not always be easy. 

Right now, if you dont implement it, your dropdown will behave weird: whatever you type in, the options stay the same.

# Desired implementation

- A boolean option to cache ajax calls
- If this option is enabled and an ajax call is made with an empty searched term, cache the results
- If this option is enabled and results have been cached, no more ajax calls, and filter the cached results by the searched term

**Comment by benc153** [comment]
I was looking for pretty much exactly this feature, but changed it a bit when implementing it to just always cache everything on the first call and then search locally.

In the case where term=null means "fetch everything" (which is normally how people implement it) there's really no point ever doing anything else.
