### ISSUE TITLE
Not focused on search input when using label

### ISSUE THREAD

**Issue by rizqinizamil** [select2/select2#5402]
Hello,
It also happened on the doc https://select2.org/appearance#labels, select2 doesn't automatically focus on search input when using label.

Any suggestion?

**Comment by Sh1n1x** [comment]
hi,
Use the version 4.0.3 the bug isn't present.

**Comment by rizqinizamil** [comment]
It shouldn't be happened on the latest release, right?

**Comment by Sh1n1x** [comment]
See https://github.com/select2/select2/pull/5140

It will be resolved on 4.0.6

**Comment by rizqinizamil** [comment]
Cool! Thank you!

**Comment by glen-84** [comment]
Duplicate of #5137.
