### ISSUE TITLE
Add dynamic option inside existing optgroup to a select2

### ISSUE THREAD

**Issue by itajackass** [select2/select2#5403]
I've a select2 like this:

    <select id="example">
     <option value=""> - </option>
     <optgroup label="Public folders">
      <option value="3">Folder 1 public</option>
      <option value="4">Folder 2 public</option>
      </optgroup>  
    </select>

I use select2 plugin to add new foldels dynamically if needed. I need to insert new folders inside optgroup "Private folders" (actually doesn't exist).

    $('#example').select2({
       tags: true,
       createTag: function (params) {
        return {
            id: params.term,
            text: params.term,
            newOption: true
        }
    },
    templateResult: function (data) {
      var $result = $("<span></span>");
      $result.text(data.text);

        if (data.newOption) {
              $result.append(" <em>(new)</em>");
        }

        return $result;
     }
    }).on('select2:select', function (e) {

        var data = e.params.data;

        var text = data.text;

        if (data.newOption) {

          if ( $('#example optgroup[label="Private folders"]').length > 0 ) {

               var option = $("<option></option>");     
               option.val(data.ID);
               option.text(text);
               $('#example optgroup[label="Private folders"]').append(option);
               $('#example').val(data.ID).trigger('change');

          } else {

                var optgroup = $('<optgroup>');
                optgroup.attr('label',"Private folders");
                var option = $("<option></option>");
                option.val(data.ID);
                option.text(text);
                optgroup.append(option);
                $('#example').append(optgroup);
                $('#example').val(data.ID).trigger('change');

        }

     }

     });

So for example if I write "New folder", i need to append it inside optgroup with label="Private folders".

See my fiddle: https://jsfiddle.net/rLmztr2d/4054/

First new insert works (It create an optgroup with label = Private folders).

But others new insert doesn't work...

**Comment by StefanJanssen95** [comment]
I have a similar issue, did you solve this?

**Comment by arunavachowdhury** [comment]
i have same issue also.. is any one fix this??

**Comment by StefanJanssen95** [comment]
Unfortunately I haven't, sorry.

**Comment by horatiua** [comment]
Someone did it. Please check this answer: https://stackoverflow.com/a/52872687/4518190
