### ISSUE TITLE
Issue with release cycle

### ISSUE THREAD

**Issue by ntalidou** [select2/select2#5418]
There seems to be an issue with the release cycle.
In https://github.com/select2/select2/tags latest is 4.0.6-rc.1 on Nov 21, 2017 and same untill today, Nov 21, 2018

**Comment by jonahgreenthal** [comment]
What exactly is the issue? That is, indeed, the last release.

**Comment by brunnopleffken** [comment]
I believe he stated that the latest version is a Release Candidate, not a final release. This may be confusing for someone who looks for final/stable releases. Perhaps just promoting this version RC-1 to v4.0.6 Final should be nice.

**Comment by jonahgreenthal** [comment]
It should not be released, as it contains at least one serious bug (#5320), maybe more. Furthermore, this project doesn't really have a maintainer at the moment, so there is no one to do that promotion.

You should probably use 4.0.5 or a different library.
