### ISSUE TITLE
How to show rightside arrow icon when in multiple mode?

### ISSUE THREAD

**Issue by wufeng87** [select2/select2#5424]
I would try to add some doms and styles to achieve this. Any help would be appreciated.

Some related issues: 
https://github.com/select2/select2/issues/760

**Comment by wufeng87** [comment]
add `<span class="select2-arrow" role="presentation"><b role="presentation" style="
    /* display: none; */
"></b></span>` into `class="select2-choices"`

change `class="select2-choices"` to `class="select2-choices select2-choice"`

It seems work fine.

![image](https://user-images.githubusercontent.com/1686808/49484782-317cf380-f873-11e8-9d01-cc540216e91f.png)

![image](https://user-images.githubusercontent.com/1686808/49484713-fa0e4700-f872-11e8-82b2-4eaa8ba9253e.png)

**Comment by cawa-93** [comment]
+1

**Comment by aman1792** [comment]
Try it this way:

```
.select2-container--default .select2-selection--multiple {
    position: relative;
    padding-right: 20px;
}

.select2-container--default .select2-selection--multiple:after {
    content: '';
    border-color: #888 transparent transparent transparent;
    border-style: solid;
    border-width: 5px 4px 0 4px;
    position: absolute;
    top: 50%;
    right: 5px;
    transform: translateY(-50%);
    pointer-events: none;
}

.select2-container--default.select2-container--open .select2-selection--multiple:after {
    border-color: transparent transparent #888 transparent;
    border-width: 0 4px 5px 4px;
}
```
