### ISSUE TITLE
[Feature request] Render event

### ISSUE THREAD

**Issue by JonGarbayo** [select2/select2#5431]
Hi Select2 team,

I think a ``select2:render`` event on the current Select2 version (4.0.5) could be very useful.
In my case, I would like to add a custom class on the ``.select2-container`` element depending on the placeholder display state. It would let me style some siblings elements with the ``+`` and the ``~`` CSS operators.

Of course I can add this class on the ``change.select2`` event, but if an ``<option>`` is selected in the original ``<select>`` tag, this class won't be present after the Select2 DOM rendering.

For example, if that class is ``has-value``, the event listener could look like this:

```js
$(document).on('select2:render change.select2', '.select2-hidden-accessible', function()
{
  var $select2Tag = $(this);
  var $select2Container = $select2Tag.next('.select2-container');
  var $select2Selection = $select2Container.find('.select2-selection__placeholder');

  $select2Container.toggleClass('has-value', !$select2Selection.length);
});
```

Hope you liked the idea!

Regards.

**Comment by JonGarbayo** [comment]
I think this issue deserves a look and shouldn't be closed :)

**Comment by muhamed87** [comment]
+1
