### ISSUE TITLE
Choosing an option by pressing ENTER not working as expected

### ISSUE THREAD

**Issue by randomd00d** [select2/select2#5432]
I'm using Select2 v 4.0.6, and have encountered the following.

1. Select2 element is open, and all the available options are there to choose from.

2. After trimming down the possible choices (by typing in the `.select2-search__field` input), I navigate through what's left with arrow keys.

3. I locate the option I want, and **press Enter** to select it. Selectbox closes, and the selected option is **visually selected**.

4. I submit the form (AJAX), but the value of the selected option is not present among the other POST / GET parameters.

If I repeat steps 1-2, **click** on the desired option, and then submit the form, the value of the selected option is there. The interesting thing is that, after I try the same thing again with Enter (without reloading the page), everything works fine.

Can anyone tell me why Enter isn't working correctly the first time I try it?

**Comment by JohnRostislavovich** [comment]
Have the same problem

**Comment by sheamusb** [comment]
Is the ajax form submitting upon hitting the enter key? My guess is that the form isn't updated with the selected value from the select2 component by the time the ajax request fires. You might try triggering your ajax request on the select2:select.
