### ISSUE TITLE
Select field gets too narrow when there are no options

### ISSUE THREAD

**Issue by adityasharma7** [select2/select2#5435]
When there are no options, the select box shrinks to too narrow width & even "No results found" appears distorted.

![image](https://user-images.githubusercontent.com/15027245/50557378-af190f80-0d0a-11e9-9e14-431148e0ec1a.png)

![image](https://user-images.githubusercontent.com/15027245/50557384-bcce9500-0d0a-11e9-9a42-928fda31f754.png)

Refer [fiddle](https://jsfiddle.net/iamaditya/1sfrweqk/)

```
$('#example').select2({
    placeholder: 'Select a month'
});

<select id="example" multiple="multiple"></select>

```

**Comment by adityasharma7** [comment]
Any updates?

**Comment by kevin-brown** [comment]
This isn't far off from being a "wontfix", but ultimately the solution here is to allow the dropdown to have a minimum width set and design it so it looks nice when the minimum width is larger than the selection area.

The other solution is to just set a width on the select box itself, so it never gets this small.

**Comment by adityasharma7** [comment]
Thanks @kevin-brown for looking into it

**Comment by kevin-brown** [comment]
The `dropdownAutoWidth` is the option I was imagining. I knew we used to have it, and when looking around at the code the other day I confirmed we still had it.

https://jsfiddle.net/5nb2ordx/

It's still recommended to set a width on the original `<select>` box, so it never gets that small in the first place.

**Comment by adityasharma7** [comment]
Great. Thanks @kevin-brown  for sharing the fiddle :)
