### ISSUE TITLE
A disabled control opened by keypress

### ISSUE THREAD

**Issue by Moreplusmas** [select2/select2#5440]
Hi,

When you disabled a control, you can open it with a keypress event (focus it, and press intro). I solved the issue with this modification:

in "this.on('keypress', function (evt)"

change the last else:

                        if (self.options.options.disabled == false)
                        {
                            if (key === KEYS.ENTER || key === KEYS.SPACE ||
                                (key === KEYS.DOWN && evt.altKey)) {
                                self.open();

                                evt.preventDefault();
                            }
                        }
Thank you for your library, greetings.

**Comment by fr0z3nfyr** [comment]
Consider pushing a PR if you think this solves the issue.

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/4695.
