### ISSUE TITLE
İ want only change noResult text. İts not working

### ISSUE THREAD

**Issue by Kneenipper** [select2/select2#5443]
Hello to everyone ; 

[https://jsbin.com/kelalub/1/edit?html,js,output](https://jsbin.com/kelalub/1/edit?html,js,output)

in my example I just want to change the value of "noResults". Because I use a special language option. However, if you specify "noResults" after specifying the language, the language is automatically English.

**Comment by fr0z3nfyr** [comment]
Don't know exactly what you are trying! Did you try [forums](https://forums.select2.org/)? I don't think this is an issue but rather a support request which must go on forums.

**Comment by CanerDumanoglu** [comment]
please look my jsbin example. i set **language** **tr** but select2 continue in english.

**Comment by fr0z3nfyr** [comment]
I still couldn't figure out exactly what you are trying but lloking at the code in jsbin I see that you had set the `language` attribute twice in `select2` options. From what I understand, You want the internationalization set for `tr` while you want to specify a particular string/HTML for `noResults`. Try something like this:
```
$.fn.select2.defaults.set('language', $.fn.select2.amd.require("select2/i18n/tr"));
$('.js-example-basic-single').select2({
    width: 300,
    minimumInputLength: 1,
    escapeMarkup: function (markup) { return markup; },
    language: {
        noResults: function() {
            return '<button id="no-results-btn" onclick="noResultsButtonClicked()">İ Want Only Here Change</a>';
        },
    }
});
```

By the way, a simple search also showed #3799 (discussion on) which I believe will give you a better idea of how to do the this in different ways

**Comment by fjqtp** [comment]
Hello @canerd7u 
I think I found solution that will work for you, at least it works for me :)

https://jsbin.com/pipeposuha/edit?html,js,output
