### ISSUE TITLE
[security issue!] Documentation change needed to prevent accidental XSS

### ISSUE THREAD

**Issue by etipton** [select2/select2#5448]
The documentation and examples for the `template(Result|Selection)` functions (and possibly others?) should warn that `.nodeValue` -- and therefore jQuery's `.text()` -- **and therefore select2's `item.text`** -- [can return unescaped (valid) HTML](https://stackoverflow.com/a/15419777/1938879).

See https://jsbin.com/zosigigece/edit?html,js,output **using Chrome**

The code there is just a slightly-modified version of the example in the [current documentation](https://select2.org/selections#templating) in order to show the vulnerability.

Select2 version: latest (4.0.6-rc.0)
Chrome version: 71.0.3578.98
OS: macOS 10.14.2

**Comment by cybernet** [comment]
this project may be abandoned ...

**Comment by kevin-brown** [comment]
This can be fixed by not string concatenating the result into the HTML element, and instead escaping it as it's inserted into the wrapper.

**Comment by etipton** [comment]
If it helps, here's the html-escaping functionality I've used for awhile now, when needed: http://shebang.brandonmintern.com/foolproof-html-escaping-in-javascript/

**Comment by kevin-brown** [comment]
Fixed in https://github.com/select2/docs/commit/1c394a421b76f26b8923a9634437b99fb6bffec3 and https://github.com/select2/docs/commit/1f79acbe5ffa651dfdbed70d6c955c2ee4447cfa. This will go out in the next docs push.
