### ISSUE TITLE
Select2 3.3.2 Search box disabled issue

### ISSUE THREAD

**Issue by khasman** [select2/select2#5455]
I have an issue that once drop down is clicked the search box remains disabled and cannot type to search options, but option can be selected from drop down. 
How can the search box disabled issue can be fixed.

Your time and help are highly appreciated.

Screenshot is attached for details

Thanks
![addleave](https://user-images.githubusercontent.com/12763428/52662442-09220d00-2f26-11e9-8685-d3f467ab659e.png)

**Comment by ProgrammingTestGitHub** [comment]
Do you have added the dropdownParent to the dropdown? 

```
<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
    ...
    <select id="mySelect2">
        ...
    </select>
    ...
</div>

...

<script>
    $('#mySelect2').select2({
        dropdownParent: $('#myModal')
    });
</script>
```

Above code example comes from the following page: https://select2.org/troubleshooting/common-problems

**Comment by khasman** [comment]
@ProgrammingTestGitHub  thanks for your response.

Below is my script which auto generates via javascript, but it did not enable search box. 

<div class="division" id="myModal">
<div class="select2-container selectoption" id="s2id_employeeid" tabindex="0"><a href="javascript:void(0)" onclick="return false;" class="select2-choice" tabindex="-1">   
<span>Select Employee</span><abbr class="select2-search-choice-close" style="display:none;"></abbr>   <div><b></b></div></a>
<input class="select2-focusser select2-offscreen" type="text" id="s2id_autogen6">
</div>
<select name="employeeid" id="employeeid" class="selectoption select2-offscreen" tabindex="-1">
    <option value="" label="Select Employee">Select Employee</option>
    <option value="14" label="Antony">Antony</option>
    <option value="17" label="Assil">Assil</option>
    <option value="16" label="HR Manager">HR Manager</option>
    <option value="7" label="Gul John">Gul John</option>
    <option value="4" label="Khasman">Khasman</option>
    <option value="21" label="HR Attendant">HR Attendant</option>
    <option value="18" label="Maray Cronje">Maray Cronje</option>
    <option value="19" label="Soshan">Soshan</option>    
</select>
<span class="errors" id="errors-employeeid">Please select employee.</span></div>

<script>
    $('#employeeid').select2({
        dropdownParent: $('#myModal')
    });
</script>

**Comment by kevin-brown** [comment]
Select2 no longer officially supports the 3.x version line, and will no longer be accepting pull requests to correct issues present in it. It is highly recommended to upgrade to the [latest version of Select2](https://select2.github.io/) if you can, as that is the version which will continue to be supported in the future.

If this issue is still present in the latest version of Select2, or the feature has not yet been added, we encourage you to submit a new pull request against the `master` branch.
