### ISSUE TITLE
Can't type in Select2 input search field when fancybox open

### ISSUE THREAD

**Issue by samithEb** [select2/select2#5458]
I have found this issue only when i open fancybox popup i cannot type in search input field but Dropdown works well and it shows the select box options as well,
after close the fancybox pop up search feild become typeable.

**Comment by cesc1989** [comment]
I see this too happening in version `4.0.7` while using a bootstrap `v4.3.1` modal.

In the modal window the search box won't work but once the modal is closed(pressing `esc` key) it will work.

**In this example, the modal is open, search box won't work**
![image](https://user-images.githubusercontent.com/1375981/58581121-66f80d80-8214-11e9-9e8b-4db21d19862a.png)

**Here, the modal is closed and the search box allows typing**
_weirdest is that it moves to the top left corner_
![image](https://user-images.githubusercontent.com/1375981/58581185-8b53ea00-8214-11e9-9988-8213a7705d48.png)

**Comment by cesc1989** [comment]
And just after sending my comment I found the solution in https://github.com/select2/select2/issues/5455#issuecomment-463088164
