### ISSUE TITLE
selectOnClose scrolls up after selection

### ISSUE THREAD

**Issue by johan-smits** [select2/select2#5469]
Tested with version 4.0.5

https://select2.org/dropdown#forcing-the-dropdown-to-remain-open-after-selection

With a multiselect it stays open but scrolls back up after making a selection. Now I need to scrollback again to the position I made the selection if I want to select a second one.

**Comment by Zohaad97** [comment]
Its probably an issue with the library, I tried it with multi select and it works like the order of `<option>` in your HTML page. it doesn't follow the user selection order.

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/4417.
