### ISSUE TITLE
Custom arrow icon

### ISSUE THREAD

**Issue by florianajir** [select2/select2#5471]
Feature request:

Actually select2 plugin do not allow to customize the icons (clear and arrows).

If I'm wrong please tell me, we really need this feature for our project.

Thanks.

**Comment by Zohaad97** [comment]
@florianajir for arrows your need to over ride this CSS class and write your own.
 `.select2-container--classic .select2-selection--single .select2-selection__arrow b`

**Comment by florianajir** [comment]
Ok thank you, this is the way I do actually but I was hoping for an alternative via scss variable or something like that to be able to pass unicode, font, etc like most lib actually does.
