### ISSUE TITLE
Error: No select2/compat/query

### ISSUE THREAD

**Issue by yanuas123** [select2/select2#5472]
$(".select-age").select2({
	dir: "rtl",
	placeholder: "טקסט",
	width: "100%"
});

console:
Uncaught Error: Error: No select2/compat/query

**Comment by Zohaad97** [comment]
@yanuas123 I tried your example on JsFiddle and it works fine with no errors. Please check that [Fiddle](https://jsfiddle.net/zohaad/0s8bh2yp/1/), It works fine according to your configuration.

**Comment by kevin-brown** [comment]
This is caused by a different `<select>` on your page using the `query` option, most likely from an old plugin or something written for Select2 3.x. You need to include the `select2.full.min.js` version in order to have greater compatibility with the older version.
