### ISSUE TITLE
Placeholder is not displayed

### ISSUE THREAD

**Issue by yanuas123** [select2/select2#5473]
Placeholder is not displayed.

js:
$(".select-age").select2({
	dir: "rtl",
	placeholder: "טקסט",
	width: "100%"
});

html:
<select class="form-control select-age">
	<option>1</option>
	<option>2</option>
	<option>3</option>
	<option>4</option>
	<option>5</option>
</select>

![image](https://user-images.githubusercontent.com/36739828/55411832-03809500-556f-11e9-8359-a1c318527fa0.png)

**Comment by crabnky** [comment]
do you have a blank `<option>` as the first option in your `<select>`?
