### ISSUE TITLE
Update select2 to vanillajs to remove jquery dependency 

### ISSUE THREAD

**Issue by dacoto** [select2/select2#5482]
Due bootstrap 5 will be released at the end of the year and the dependence on jquery will be eliminated, it would be advisable to also removed it from select2.
- https://sdtimes.com/webdev/bootstrap-5-expected-to-completely-replace-jquery/
- https://github.com/twbs/release
- https://github.com/twbs/bootstrap/projects/11

**Comment by kevin-brown** [comment]
See https://github.com/select2/select2/issues/3652.

This is something we'd love to see a pull request for, but it's ultimately not on the books for us in the near future.

**Comment by alvarotrigo** [comment]
Meanwhile, you can use Choices, seems to be quite a good replacement without jQuery! :)
https://joshuajohnson.co.uk/Choices/
