### ISSUE TITLE
select2-4.0.5 doesn't seem to work well with jquery-3.4.0

### ISSUE THREAD

**Issue by kikonen** [select2/select2#5485]
Tried select2-4.0.5 with jquery-3.4.0 and started to encountered strange bug with focus logic. Especially multiselect widget was behaving very oddly (input focus disappeared, keyboard up/down started to change selected value in the field (no popup selector shown)).

Reverted back to jquery-3.3.1 and strange behaviours seemed to fix themselves. So I concluded that there might be some compatibility problem going on.

**Comment by herbalite** [comment]
There are at least 2 bugs in jquery 3.4.0. Probably best to wait until 3.4.1
https://github.com/jquery/jquery/issues

**Comment by JamoCA** [comment]
This is a pretty bad bug... Every advanced integration on my form worked perfectly (muliple data sources, ajax, etc) except for the "tag" function.  We hadn't rolled 3.4.0 out fully in production, so I was the only one encountering the issue. It was frustrating trying to troubleshoot and I finally figured I'd check the issues reported on GitHub.  Thanks for reporting this!

**Comment by kevin-brown** [comment]
I can confirm that if I run the tests under 3.4.0, it throws a ton of errors. Unfortunately those errors appeared to have been introduced in 3.2/3.3 and make it a bit difficult to trace the exact issues at play.

Any chance someone can generate a quick jsbin which demonstrates the problems under 3.4.0?

**Comment by neerone** [comment]
Same thing with focus logic. jQuery 3.4.1

**Comment by fydelio** [comment]
Closing my other issue and moved it here. Here is a phenomenon I encountered using jQuery 3.4.0 and the latest select2 4.0.7

For my select2 box I have multiple and tagging enabled. Interestingly with this setup I can only create new tags with max 2 characters. Selecting an existing option with a longer text-value no problem. If I revert to jQuery. 3.3.1 the problem disappears!

Please see the JSFiddle [here](https://jsfiddle.net/rqyzupjv/2/)

Is this a bug or am I doing something wrong?

**Comment by devkral** [comment]
is there a way to hack a workaround?

**Comment by mariuszkrzaczkowski** [comment]
When can we expect the error to be fixed?

**Comment by zero24x** [comment]
hello, jquery 3.3.1 has 1 medium level security vulnerability, please check out https://snyk.io/test/npm/jquery/3.3.1 

so just downgrading to this jquery version (like done in https://github.com/YetiForceCompany/YetiForceCRM/pull/10408) is a bad idea and not a "bugfix", please make it work with newer jquery also,thanks!

**Comment by borisson** [comment]
@kevin-brown you asked for an example. I found this issue trough https://stackoverflow.com/questions/56046676/select2-cant-create-new-options-longer-than-2-characters-tag-true the jsfiddle there demonstrates the problem https://jsfiddle.net/rqyzupjv/2/

**Comment by mariuszkrzaczkowski** [comment]
What is the problem to fix it? This is a serious bug

**Comment by blikblum** [comment]
Hi, instead of coming here and blame developers, i take a time and investigated.

The issue is caused by a change in a change how jquery handle focus event: https://github.com/jquery/jquery/commit/669f720edc4f557dfef986db747c09ebfaa16ef5

The affected code is:

```
  if (searchHadFocus) {
      var isTagInput = this.$element.find('[data-select2-tag]').length;
      if (isTagInput) {
        // fix IE11 bug where tag input lost focus
        this.$element.focus();
      } else {
        this.$search.focus();
      }
    }
```

Changing this.$element.focus(); to this.$element[0].focus(); fixes the issue.

BTW seems that call to this.$element.focus(); is necessary not only in IE11 but also with at least Firefox

**Comment by devkral** [comment]
thanks, I hope it is fixed soon.
For information: the code snippet is in
src/js/select2/selection/search.js
and most probably the dist equivalent

**Comment by fydelio** [comment]
@blikblum , @borisson : I tried your solution with fixing the function in search.js. Your solution doesn't seem to solve the tagging problem yet (check this JSFiddle(https://jsfiddle.net/rqyzupjv/2/). Therefore not quite sure whether the solution (which for sure is valid) fixes ALL compatibility issues.

Not trying to complain, I'm just not good enough in JS to debug this issue as you did, @blikblum.

**Comment by blikblum** [comment]
> (check this JSFiddle(https://jsfiddle.net/rqyzupjv/2/)

I tested with this exact code and is working with the fix

**Comment by devkral** [comment]
where is the fix applied? I see in the jsfiddle only dependencies to the upstream cdn libraries

**Comment by blikblum** [comment]
I tested in my local machine. Seems is not released yet

**Comment by kevin-brown** [comment]
So, now I'm in a tough spot with this one. I got the tests running on jQuery 3.4.1 and they are all passing (see https://github.com/select2/select2/pull/5531).

Is anyone interested in creating a failing test case for this? The jsfiddle should be a solid place to start, since we have a guess as to what features might be broken.

**Comment by ahmedali5530** [comment]
> There are at least 2 bugs in jquery 3.4.0. Probably best to wait until 3.4.1
> https://github.com/jquery/jquery/issues

i have jquery 3.4.1 and this issue still exists!

**Comment by devkral** [comment]
$(...).selectize({
    create: true,
    delimiter: null,
    plugins: {
      'remove_button': {}
    }
  });

is a fine workaround ;-). It configures selectize to behave like select2 with tags but without this bug.

**Comment by kevin-brown** [comment]
Just going to copy the comment from https://github.com/select2/select2/issues/5516#issuecomment-500401680 over to here, for visibility:

> We have a jsbin for this, which is why we know the issue exists. Unfortunately we can't reproduce this issue in our current test suite, which explains why it wasn't caught earlier. If someone is willing to donate some of their time to making a unit test that reproduces this issue, I'll willing to donate some time to fixing whatever is causing the issue.

**Comment by blikblum** [comment]
@kevin-brown here you have: #5550

**Comment by collimarco** [comment]
@kevin-brown Can you please merge @blikblum pull request and release the new version?

**Comment by blikblum** [comment]
@collimarco 
You can try install select2-lite package. It contains the recent PRs i sent. In the future will got other changes: https://github.com/blikblum/select2-lite/issues
