### ISSUE TITLE
Clicking in text while adding dynamic tags clears out text

### ISSUE THREAD

**Issue by kverfaille** [select2/select2#5491]
- [x] Feature (could be bug too, but not sure)
- [x] Related issues checked
- [x] Latest version: (used: 4.0.6)
- [x] Demo (see below)

Steps to reproduce (using: https://jsbin.com/hukeravete/edit?html,js,output)

- Start typing next to "DemoText1" to start creation of new dynamic tag
- Type "Demo Text2" (don't enter nor select the entry)
- Click between "Demo" & "Text" to attempt to remove the space
- Field will be cleared rather than remain in edit mode to be able to remove the space

![DemoGif](https://thumbs.gfycat.com/JovialSimplisticIrishterrier-small.gif)

Remarks:
- This behavior is expected when clicking outside the textarea, not when clicking inside the text. 
- Workaround is to only use the arrow keys to get to the space. (but our users aren't a big fan of that)

Cheers,
Kevin

**Comment by flaushi** [comment]
Confirm!

**Comment by kevin-brown** [comment]
This appears to be occurring because the click within the search box is propagating back to the selection area, which is causing the dropdown to be closed and the search box to be cleared as a result.

**Comment by flaushi** [comment]
The new version 4.7-rc0 does still have this bug.

**Comment by masciugo** [comment]
same experience with 4.0.7. Any chance to be fixed in the nearly future? thanks a lot

**Comment by marcolong** [comment]
same issue here with 4.0.7

**Comment by blikblum** [comment]
> This appears to be occurring because the click within the search box is propagating back to the selection area, which is causing the dropdown to be closed and the search box to be cleared as a result.

@kevin-brown 

I looked the code and confirm this. Before i do a PR, what should be the correct behavior?

 - Should not close the dropdown at all
 - Should close the dropdown but not clear the text

I think the former is the correct.

Also should the dropdown close on click even if not searching?

**Comment by masciugo** [comment]
@blikblum I would prefer the first one

**Comment by blikblum** [comment]
> I would prefer the first one

Done at #5551
