### ISSUE TITLE
Holding Ctrl/Cmd while using multi-selects bypasses maximumSelectionLength

### ISSUE THREAD

**Issue by Hlsgs** [select2/select2#5495]
This was introduced in #5222

**Comment by kevin-brown** [comment]
This is a known bug because of how `closeOnSelect` interacts with `maximumSelectionLength`. The latest release just expanded it to also affect Cmd (while before it only affected Ctrl).

Closing this off as a duplicate of https://github.com/select2/select2/issues/3514.
