### ISSUE TITLE
RC releases should not be tagged as latest on npm

### ISSUE THREAD

**Issue by stof** [select2/select2#5496]
Currently, the `latest` npm tag gets updated each time a RC release is done. This lead to `yarn outdated` showing Select2 as outdated (as a `^4.0.5` constraint for the dependency will not use the RC release and will stay on 4.0.6) and `yarn add` installing the RC release.
The common convention (at least as far as I'm aware of) is to update the `latest` tag only for stable releases.

**Comment by kevin-brown** [comment]
Any suggestions on how to not update the latest npm tag on every RC release?

I've just been doing an `npm publish` and expecting it to handle the tagging correctly from there.

**Comment by glen-84** [comment]
https://docs.npmjs.com/cli/dist-tag

> Publishing a package sets the `latest` tag to the published version unless the `--tag` option is used. For example, `npm publish --tag=beta`.

> The `next tag` is used by some projects to identify the upcoming version.

`npm publish --tag=next`

**Comment by kevin-brown** [comment]
Awesome, thanks!

I'll try to fix this when I move to automating the NPM builds in the near future.

**Comment by kevin-brown** [comment]
When we migrate to something like GitHub Actions or Azure Pipelines, I'm going to look into how to do this.
