### ISSUE TITLE
Disabled Data Attribute

### ISSUE THREAD

**Issue by qkdreyer** [select2/select2#5497]
Select2 doesn't respect `data-disabled="true"`data attribute but the disabled configuration is.

It looks like a bug to me, since as stated in the [docs](https://select2.org/configuration/data-attributes) :

```
However, you may also define your configuration options by using the HTML5 data-* attributes, which will override any options set when initializing Select2 and any defaults.
```

Reproduction links :
- Using Disabled Data Attribute : https://jsbin.com/gicapebiju/edit?html,js,output
- Using Disabled Configuration Option : https://jsbin.com/tutodiwune/edit?html,js,output

**Comment by kevin-brown** [comment]
Looks like this is actually a bug in the docs. The `disabled` option doesn't actually exist as a JavaScript option, it only exists as the HTML attribute/property.

https://jsbin.com/gicapebiju/edit?html,js,output

You disable a `<select>` in Select2 using the same way that you do it with a normal `<select>`. You add the `disabled` attribute to get `<select disabled>`.

**Comment by tan31989** [comment]
@kevin-brown I was looking for building the application and fix some tickets. It was hard to find out the CONTRIBUTOR's guideline in this repository. Is this open for anyone to contribute?

**Comment by kevin-brown** [comment]
> Is this open for anyone to contribute?

Yes.

The contributing guide was moved, but it looks like the docs weren't updated to reflect that. It's still in the repository, just it's now located at https://github.com/select2/select2/blob/develop/.github/CONTRIBUTING.md.

**Comment by tan31989** [comment]
Thanks @kevin-brown

**Comment by tan31989** [comment]
@kevin-brown can you please review this PR?

**Comment by kevin-brown** [comment]
The related PR was merged in, so I believe this can be closed.
