### ISSUE TITLE
Select2 and CSS Transforms: dropdown menu is off position

### ISSUE THREAD

**Issue by kayzee** [select2/select2#550]
I am using CSS transforms to increase the zoom level on my site.

Production site with zoom buttons (but no Select2 menus):
http://goo.gl/NGA7S

My jsFiddle Test 1 (with default zoom):
http://jsfiddle.net/ugPmm/1/

My jsFiddle Test 2 (with a larger zoom):
http://jsfiddle.net/wCALL/2/

In the Test 2, you can see the dropdown menu does not position itself correctly.  Does anyone have any suggestions or can this be fixed in the select2 project itself?

The page modifications that I'm making in CSS are:

```
.zoom-largest {
      font-size: 18px; }

body.zoom-largest {
    -o-transform: scale(1.25);
    -moz-transform: scale(1.25);
    -ms-transform: scale(1.25);
    -webkit-transform: scale(1.25);
    transform: scale(1.25);
}
```

**Comment by shazzad** [comment]
I have been using select2 on WordPress wp admin area. One thing i have found that, if the html itself have any padding, select2 search input field position is displaced. And if i force the html padding attribute to 0, every placement is perfect.

html.wp-toolbar {
    padding-top: 32px;
}

Is there a way i can modify offset calculation without modifying the select2.js file ?

**Comment by whooehoo** [comment]
Reopen the issue plz, i have a pull request to fix this.
