### ISSUE TITLE
Wrong width calculation of empty search input

### ISSUE THREAD

**Issue by karakum** [select2/select2#5517]
Now search input width calculate as parent `innerWidth()`:
```
    if (this.$search.attr('placeholder') !== '') {
      width = this.$selection.find('.select2-selection__rendered').innerWidth();
```
This is wrong, because `ul.select2-selection__rendered` has left&right padding. 
So search input makes select2 container grows up.
To fix that it just need to calculate width by `width()`, that not count paddings.

JS fiddle: https://jsfiddle.net/karakum/2o6xzupe/

Empty select:
![изображение](https://user-images.githubusercontent.com/12033941/58268408-97245400-7daf-11e9-881b-236b740e180a.png)

Not empty:
![изображение](https://user-images.githubusercontent.com/12033941/58268505-bfac4e00-7daf-11e9-96da-f07aa2b020f2.png)

**Comment by kevin-brown** [comment]
It's not entirely clear to me how switching this from `innerWidth` to `width` would fix the issue (since `width` should return a larger value than `innerWidth`), but I can confirm that this bug exists.

**Comment by karakum** [comment]
@kevin-brown, This pictures from jQuery's documentation:

![изображение](https://user-images.githubusercontent.com/12033941/58799887-a7022a80-8630-11e9-8f98-3db2bd777d09.png)

![изображение](https://user-images.githubusercontent.com/12033941/58799904-b97c6400-8630-11e9-8447-f541c0f04969.png)

`innerWidth` include node paddings, `width` - does not.

**Comment by kevin-brown** [comment]
That's pretty convincing, looks like I was getting the two mixed up. :+1:
