### ISSUE TITLE
render 50+ select2 items on same time is very slow[performance]

### ISSUE THREAD

**Issue by nevernet** [select2/select2#5519]
version 4.0.7

![Snip20190524_223](https://user-images.githubusercontent.com/4110538/58299203-fe262500-7e10-11e9-9555-501b51860e27.png)

please review above image and advise how to optimize it.

thank you

**Comment by aiqiao** [comment]
Hi, I encounter a issue that the select will become normal select when I add follow select2, I use the same class to render them. from your pictures ,you seem not to have the question,how do you render the follow select? thank you!

**Comment by aiqiao** [comment]
你好，我们的需求类似你这样的，用相同的class去渲染select2的时候，之前渲染的select变成了普通的了，请问你是怎样渲染的呢？

**Comment by cwm0103** [comment]
那你就用都用select2好了，只不过单选的你就设置成单选的，多选的你就设置成多选的


------------------ 原始邮件 ------------------
发件人: "aiqiao"<notifications@github.com>;
发送时间: 2019年5月27日(星期一) 中午12:25
收件人: "select2/select2"<select2@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [select2/select2] render 50+ select2 items on same time is veryslow[performance] (#5519)




你好，我们的需求类似你这样的，用相同的class去渲染select2的时候，之前渲染的select变成了普通的了，请问你是怎样渲染的呢？

**Comment by aiqiao** [comment]
我3.X 版本的没这个问题，用了4.0.7的就会有这个问题。
![image](https://user-images.githubusercontent.com/29449411/58395827-a25fd400-807c-11e9-92fa-0e397f3cae09.png)
上面那一行与下面那一行是是一样的，可以动态添加，当新增行时，执行完select2这个方法后，新增行的变成select2渲染的样式，上面那一行就变成了普通的了。

**Comment by kevin-brown** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Comment by nevernet** [comment]
@kevin-brown  i am so sorry for delay response. the current issue is about how to optimize select2, i am not sure it's related to the usage of select2 :)
