### ISSUE TITLE
multiple select input search Safari

### ISSUE THREAD

**Issue by ZhuBobi** [select2/select2#5522]
When I use multiple select on Ipad,I set minimumResultsForSearch: Infinity,but I get the kwyboard stand when I focus the select,it seems like a search input. I wonder how to slove it.I don't need the input to scan any word.I'm sorry to bother you.

**Comment by ZhuBobi** [comment]
And I set closeOnSelect:false.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
