### ISSUE TITLE
Event data in 4.0.7

### ISSUE THREAD

**Issue by kioskemploi** [select2/select2#5523]
Hello,

I came across a little problem switching from 4.0.6-rc.1 to 4.0.7 using the 'select2:close' event.
In the 4.0.6-rc.1 version, I was able to access some information in the variable I'm logging below when I was selecting one option in my select : 
```javascript
$('#forward_email').on('select2:close', function (e) {
    console.log(e.params);
});
```
I used to see and using in my code stuff like "e.params.originalSelect2Event" or "e.params.originalEvent", now in 4.0.7 "e.params" seems to be always empty. Is it supposed to be like that ?

Thanks for your help.

**Comment by kevin-brown** [comment]
Do you have a jsbin that reproduces this issue?

If this affected all events, I would have expected to see a few more tickets created about it.
