### ISSUE TITLE
4.0.5 -> 4.0.7 select2.close event regresssion

### ISSUE THREAD

**Issue by drees** [select2/select2#5532]
Upgrading from 4.0.5 to 4.0.7 and ran into an issue where this code no longer works:

```javascript
$(document).ready(function() {
  $("#select1").select2().select2("focus");
  $("select").on("select2:close", function (e) {
	 $("#checkbox1").focus();
	});
});
```

The goal is to auto-select the select2 on page load, then after the select2 is closed, focus on the next element. With 4.0.5 it works, with 4.0.7, the select2 element remains focused.

Example w/4.0.5 which works:
https://jsfiddle.net/bvL2wejz/

Example w/4.0.7 which doesn't work:
https://jsfiddle.net/4b0zy1hd/

**Comment by blikblum** [comment]
It is caused by this commit: https://github.com/select2/select2/commit/933189b92e352d62373b7739a28c266a129f97c9

I will prepare a PR with according test

**Comment by blikblum** [comment]
> I will prepare a PR with according test

Done in #5552
