### ISSUE TITLE
RTL not working when apply theme bootstrap 4

### ISSUE THREAD

**Issue by pixieaka** [select2/select2#5535]
When enable bootstrap 4 theme on latest version of select 2 with rtl direction it return to ltr and when disable theme it working great again.

**Comment by kevin-brown** [comment]
I would recommend posting this bug report on the tracker for select2-bootstrap4-theme: https://github.com/ttskch/select2-bootstrap4-theme

----

This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

[ml]: https://select2.org/troubleshooting/getting-help
