### ISSUE TITLE
Bootstrap Modal closes, when select2 element is selected with holding mouse

### ISSUE THREAD

**Issue by MR4online** [select2/select2#5539]
I do have select2 in Bootstrap 3 modal running with the following:

When I select the select2 with **holding the left mouse button** and select an option/item from the list releasing the mouse button, the modal closes.
It closes only in this case. Normal short click works. Hold Mouse Button on any other element or selecting nothing works, too.

Can anybody help me solving this, please?
Thanks!

**Comment by kevin-brown** [comment]
https://select2.org/troubleshooting/common-problems#select2-does-not-function-properly-when-i-use-it-inside-a-bootst

You need to set the `dropdownParent` option to the modal, and then it should no longer have issues with selecting results closing the modal.
