### ISSUE TITLE
Dropdown getting *--below class on first click (after page loads)

### ISSUE THREAD

**Issue by attila-albert** [select2/select2#5540]
Hey guys!

While using your library, I have noticed a weird behavior on the dropdown when opening it the first time after page loads.
The dropdown first always opens with the class *--below on the first click, without checking if there is enough space or not on below. Going through your code, I have found on line 4411 the following:

`if (!isCurrentlyAbove && !isCurrentlyBelow) {
    newDirection = 'below';
}`

Which means, if the dropdown is not having a class *--above or *--below, then it will be given the class *--below by default on first load, no matter if there is enough space below or not.

In order to resolve this issue, please consider replacing the above code with the one below to do some additional checks:

`if (!isCurrentlyAbove && !isCurrentlyBelow) {
    if(!enoughRoomAbove) {
        newDirection = 'below'; }
    else { newDirection = 'above'; }
}`

This would solve the issue mentioned above.

Thanks!

**Comment by kevin-brown** [comment]
It's unclear what version of Select2 you are running, but when I tested this in the documentation examples I could not reproduce this behaviour.

https://github.com/select2/select2/blob/2fce8ae6c4937b88c332ad3e30e135cf24504cf1/src/js/select2/dropdown/attachBody.js#L173-L181

In the source, we definitely prefer having the dropdown be displayed below, but we do display it facing upwards if there isn't enough space below.
