### ISSUE TITLE
IE multiselect problem

### ISSUE THREAD

**Issue by mdotcom123** [select2/select2#5544]
I am using Multiselect with Select 2. The problem is with IE. I have several select2 dropdowns , so by the multiselect(required) if the field is empty and i click on Submit button it takes me back to the multiselect(required)  to select an item first, but then when i choose some items Submit button doesn't work, it takes me back to choose item again in the multiselect but there are already items selected.That's only in  IE  in the others browsers i have no problem . And i can't find the problem when someone knows it would help a lot. Thanks

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
