### ISSUE TITLE
Why is disabled select2 dropdown still focusable?

### ISSUE THREAD

**Issue by fbengo** [select2/select2#5549]
Hi,

I was wondering why select2 dropdown is still focusable when it is disabled? I have never seen this behaviour with other disabled elements (i.e. bootstrap elements) before. What's the idea behind this?

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/4695.

**Comment by davidabsilva** [comment]
Hi,

I've dealt with that same question. @kevin-brown the issue you linked is about being able to open the select when disabled. The issue @fbengo is reporting, is about granting the focus class when the select is disabled.

Is this the desired behaviour?
