### ISSUE TITLE
Select2 stops working or starts working on rescale

### ISSUE THREAD

**Issue by xl3lackkikx** [select2/select2#5572]
Hi!

I have been using select2 v4.0.3. There was the following bug:
**_Fix "the results could not be loaded" displaying during AJAX request (#4356)_**
 So i upgraded to version 4.0.7 to get this fixed. Now i found the following problem.
Sometimes the select2 doesn't work. But when i rescale the browser or the block where the select2 element is in, the select2 will work again. I provided two sceenshots to show the problem:

In this picture you can see the select2 is not working:
![image](https://user-images.githubusercontent.com/9801187/61351425-f6ac5680-a86a-11e9-980c-8446afb64e9c.png)

In this picture you can see it started working again after a rescale of the browser
![image](https://user-images.githubusercontent.com/9801187/61351341-b0ef8e00-a86a-11e9-9d14-ae17c35b5bfc.png)

Does someone how to fixes this or can this be updated?

This problem only occurs in version 4.0.6 and version 4.0.7.
In multiple browsers:
IE v11.5
Chrome v75.0.3770.100
Firefox v68.0

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by xl3lackkikx** [comment]
Thank you for your respond!
After testing again I found out that I am using the same id attribute value multiple times.
I have now fixed it!
