### ISSUE TITLE
select2:select and select2:unselect are firing twice

### ISSUE THREAD

**Issue by nalumachurakesh** [select2/select2#5573]
I'm using :select and :unselect events to capture the data and noticed that they are firing twice. Here's my code 

    $('#ddlGP01Attending').on('select2:select', function (e) {
        debugger;
    });

    $('#ddlGP01Attending').on('select2:unselect', function (e) {
        debugger;
    });

I'm using 4.0.5 version of select2.

Could you please suggest to fix this issue. Thanks.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
