### ISSUE TITLE
Placeholder not showing

### ISSUE THREAD

**Issue by Jojoshua** [select2/select2#5585]
The placeholder text is not showing when the select element is not initially visible AND it is a "multiple" type select AND using jquery 3.4.1

See the fiddle for example. 

Click the button to show the select2 to reproduce.
https://jsfiddle.net/tmw4z7eb/1/

**Comment by kevin-brown** [comment]
This is a regression in jQuery 3.3.0 (does not occur in jQuery 3.2.1). I suspect they "fixed" an issue and it caused the width calculation to no longer return anything for elements which are not visible.

Until we trace what exactly changed in jQuery, it's unclear if this is a bug in Select2 or a bug in jQuery.

**Comment by Jojoshua** [comment]
Thanks for confirming @kevin-brown . Is the select2 code for generating multiple much different? As soon as I remove multiple, even using jquery 3.4.1 it works.

**Comment by kevin-brown** [comment]
> Is the select2 code for generating multiple much different? As soon as I remove multiple, even using jquery 3.4.1 it works.

Yes, Select2 generates an actual placeholder for a single select and uses the `placeholder` attribute for a multiple select. The reason why it is not visible for a multiple select is because we automatically size the `<input>` which contains the `placeholder` attribute.

https://github.com/select2/select2/blob/6645ffd4bddcc178c8c1c8588c6b2a93290a4cca/src/js/select2/selection/search.js#L211-L225

And for some reason, jQuery 3.3.0 and up is setting it to `0` when the Select2 is not visible.

**Comment by Jojoshua** [comment]
Please keep open

**Comment by jayaddison** [comment]
@benoitongit I found a reasonable workaround in https://github.com/openculinary/frontend/pull/10 which might work for you too.

Once your select element becomes visible, if you can call `$(element).trigger('change')` on it, that will internally call the `resizeSearch` method that Kevin linked to, and it should now pick up the correct element width and display the placeholder text.

Will be nice once this is fixed but that might work in the meantime.

**Comment by kevin-brown** [comment]
Keeping this open with the plan to bisect this later to identify the actual change in jQuery that caused it.

**Comment by jayaddison** [comment]
Can we keep this open please?  There's a workaround ( https://github.com/openculinary/frontend/pull/10 ) but it'd be great to identify the root cause so that we can fix the underlying issue.

**Comment by jayaddison** [comment]
Thank you @kevin-brown!

**Comment by brazenvoid** [comment]
With width set to 100%, the input gets rendered at correct width but placeholder for some reason still doesn't.

**Comment by kevin-brown** [comment]
This has been fixed in the upcoming 4.1.0 release. You can test it out for yourself by using the 4.1.0-beta.1 release which came out a few weeks ago.

**Comment by OussamaKhoubran** [comment]
If anyone still need a workaround the issue, you can use this code:

Css
`.select2-search--inline {
	display: contents;
}
.select2-search__field:placeholder-shown {
	width: 100% !important;
}`

JS
` 
jQuery('select').on("change", function (e) {
        const self = jQuery(this);
        const field = self.parent().find('.select2-search--inline'); 
        
        // Update
        field.css('display', (self.val().length == 0 ? 'contents' : 'block'));
        field.find('input').css('width', (self.val().length == 0 ? '100%' : 'auto'));
 });
`

**Comment by hilock** [comment]
> If anyone still need a workaround the issue, you can use this code:
> 
> Css `.select2-search--inline { display: contents; } .select2-search__field:placeholder-shown { width: 100% !important; }`
> 
> JS ` jQuery('select').on("change", function (e) { const self = jQuery(this); const field = self.parent().find('.select2-search--inline');
> 
> ```
>     // Update
>     field.css('display', (self.val().length == 0 ? 'contents' : 'block'));
>     field.find('input').css('width', (self.val().length == 0 ? '100%' : 'auto'));
> ```
> 
> }); `

it works!!! thanks man, you are the genius!
