### ISSUE TITLE
Grunt version upgrade for fixing vulnerabilities

### ISSUE THREAD

**Issue by tan31989** [select2/select2#5596]
When we build the latest master code for `npm install` we see that there are some 25 `high` vulnerabilities:

Here is the error from `npm install`:

```sh
mymac:select2 usern$ npm install

> node-sass@4.12.0 install /Users/nagaraj/Projects/os/select2/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.12.0/darwin-x64-64_binding.node
Download complete  ⸩ ⠋ :
Binary saved to /Users/usern/Projects/os/select2/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Caching binary to /Users/usern/.npm/node-sass/4.12.0/darwin-x64-64_binding.node

> node-sass@4.12.0 postinstall /Users/usern/Projects/os/select2/node_modules/node-sass
> node scripts/build.js

Binary found at /Users/usern/Projects/os/select2/node_modules/node-sass/vendor/darwin-x64-64/binding.node
Testing binary
Binary is fine
npm notice created a lockfile as package-lock.json. You should commit this file.
added 99 packages from 77 contributors and audited 2409 packages in 12.655s
found 25 vulnerabilities (5 low, 6 moderate, 14 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Fix is very simple:
`sudo npm install --save-dev grunt@1.0.4`

I tested the grunt commands and its working as expected with the following tests:

`grunt compile`
`grunt minify`
`grunt test`

I can raise a PR with the tested items.

**Comment by kevin-brown** [comment]
> I can raise a PR with the tested items.

Please do. I'll gladly review it, but making and testing the actual changes is not high on my priority list right now.

Note that all of our dependencies are dev dependencies, which is why this isn't the very first thing I'm looking to correct.
