### ISSUE TITLE
Enhancement: Warn on dimension discrepancy

### ISSUE THREAD

**Issue by mcandre** [select2/select2#5607]
Developers may find subtle glitches in their Web applications when users submit a single string field entry where the form POST receiving endpoint expects an array of strings entry. This can happen when the developer makes a mistake in the dimensionality of their OPTION (e.g. omitting the `[]` suffix for the `name` attribute when using `multiple="multiple"`, or supplying the `[]` suffix when not using `multiple="multiple"`).

Could select2 present a warning for this erroneous configuration in the JS console?

**Comment by kevin-brown** [comment]
> Could select2 present a warning for this erroneous configuration in the JS console?

Unfortunately the `[]` convention is limited to like 2 languages and isn't a standard, so there isn't much Select2 can do here.
