### ISSUE TITLE
focus problem with jquery 3.4.1 and select2 4.0.8

### ISSUE THREAD

**Issue by kikonen** [select2/select2#5612]
Howto

1) Simple select2 box
2) select value from the box
3) focus "disappears"
4) press arrow key down
=> plain html select dropdown is shown in web page

**Comment by kikonen** [comment]
![Screenshot 2019-08-21 16 31 37](https://user-images.githubusercontent.com/478935/63436480-6fd23700-c431-11e9-87c6-cce021b9b3ae.png)

**Comment by kevin-brown** [comment]
This should have been fixed in the 4.0.9 release that just happened.

**Comment by kikonen** [comment]
Just tested with select2-4.0.9 and it does not fix problem
