### ISSUE TITLE
Select2 error in documentation site

### ISSUE THREAD

**Issue by limeric29** [select2/select2#5615]
There's an error in the documentation site and examples aren't working.

`Uncaught TypeError: $(...).select2 is not a function`

<img width="1552" alt="Screen Shot 2019-08-22 at 4 23 38 PM" src="https://user-images.githubusercontent.com/4938254/63499187-ef2b3d80-c4f9-11e9-873c-86fe4d7f3c4e.png">

Thanks.

**Comment by kevin-brown** [comment]
Fixed.

Grav is a pain and appears to be caching the cache miss from cdnjs, so it wasn't rendering the Select2 JS/CSS on the docs site.
