### ISSUE TITLE
Validation issue on scss / js

### ISSUE THREAD

**Issue by ngagestudios** [select2/select2#5618]
While validating scss and js we have to change few classes used on js and css and replace "__" with "--".

Can we have this updated so we can use script with npm and can validation using lint-sass

I can help and submit PR if needed

**Comment by kevin-brown** [comment]
Sorry, I'm going to have to reject this ticket. Doing this would destroy any existing themes and would be a major backwards-incompatible change.

If sass-lint or lint-sass is claiming that the classes are invalid... well, they aren't. They're valid BEM using a less-commonly-used syntax of SASS to generate them. Add an exclusion for the Select2 files if you need to.
