### ISSUE TITLE
Inconsistent behaviour in "closeOnSelect: false" with mouse and keyboard

### ISSUE THREAD

**Issue by kikonen** [select2/select2#5626]
jquery 3.4.1
select2 4.0.9

Trying to use "closeOnSelect: false" with multiselect select2 box

Problem:
Behaviour of flag is not consistent with keyboard and mouse access.

With mouse:
1) open select dropdown
2) select value from dropdown list with mouse
3) click selected value from dropdown with mouse
4) Value is deselected from list

With keyboard:
1) open select dropdown
2) select value from dropdown list with ENTER
3) try to deselect value from dropdown with ENTER
=> dropdown closes and values is not delected
=> Thus it seems that it's not possible to do similar "select/deselect" logic in dropdown as with mouse

Can be seen in https://jsfiddle.net/kikonen/pc50daj2/8/

**Comment by kevin-brown** [comment]
The keyboard command used to select/deselect options is CTRL + SPACE, not ENTER.

For more information on why this was done, see https://github.com/select2/select2/commit/017c20109471fa5b835603faf5dc37f7c2c2ea45.

**Comment by kikonen** [comment]
CTRL + SPACE appears to somewhat unfortunate default since it's shortcut key used by my web browser for searching open tabs.
