### ISSUE TITLE
Add the ability to set a custom "autocomplete" html attribute

### ISSUE THREAD

**Issue by fmonts** [select2/select2#5628]
The "autocomplete" attribute is now hardcoded to `off` here:

https://github.com/select2/select2/blob/develop/dist/js/select2.js#L1964
https://github.com/select2/select2/blob/develop/dist/js/select2.js#L4064

Unfortunately, the off value is ignored in Chrome (see here: https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c164)

And this is what happens if you have addresses saved in Chrome and you have forms with a name, address, country etc., the Chrome autocomplete UI goes above the Select2 and it's impossible to see the options:

![image](https://user-images.githubusercontent.com/8755314/63998413-b696ef80-cb09-11e9-9e65-5a312ed8bf1f.png)

To fix this, we need to set a custom `autocomplete` value, ex. `autocomplete="campaign-countries"`. 
I think Select2 should implement a way to set a custom value, with an option or by reading it from the original select.

**Comment by kevin-brown** [comment]
More than likely this will be done by copying the `autocomplete` attribute that is placed on the original `<select>` and moving it to the search box, similar to what we do with the `disabled` attribute.

Unfortunately since development is currently being focused on bugs, this isn't immediately on the roadmap.

**Comment by adrichey** [comment]
@kevin-brown Do you take pull requests from the public? If so, I would be willing to knock this out quickly this week in a fork and knock it out for you.

**Comment by adrichey** [comment]
Went ahead and put in a PR for this: https://github.com/select2/select2/pull/5670
