### ISSUE TITLE
Bug in select2 drop down when browser back batten is used.

### ISSUE THREAD

**Issue by timamara** [select2/select2#5629]
All,
I wanted to thank the select2 developers. It is a great library and used it in couple of applications. 

### **The issue I wanted to report is, when the select 2 drop down is open with or without selecting any values and then the browser back button is pressed, the open dialog box is carried to the next screen and dragged to each page until you refresh the current page.** 

**Proposed solution:** select 2 should close and clear when the browser back button is pressed.

**Comment by timamara** [comment]
I see this behavior in following versions. 
select2 - version : 4.0.6-rc.1
jquery  - version : 3.1.13
------------------------
select2 -version : 4.0.8
jquery - version :3.4.1

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
