### ISSUE TITLE
Show dropdown for small resultsets

### ISSUE THREAD

**Issue by antonio-petricca** [select2/select2#5630]
I have a resultset which maybe very small, often less than 10 items.

How could I show the dropdown like a standard **select** input when resultsets are so small?

Thank you so much!

**Comment by kevin-brown** [comment]
Select2 does not natively support this, but this is something you should be able to do prior to the initialization of Select2.

```js
$('<select>').each(function () {
  if ($(this).children().length >= 10) {
    $(this).select2();
  }
});
```
