### ISSUE TITLE
Replace AMD with ES6 modules

### ISSUE THREAD

**Issue by cowwoc** [select2/select2#5631]
Looking at https://caniuse.com/#feat=es6-module and https://caniuse.com/#feat=es6-module-dynamic-import ES6 module support is currently at 83-87% worldwide. Anyone caring about the remaining 13-17% will simply use a transpiler like Rollup or Webpack.

I assert that AMD is harder to use than ES6. https://stackoverflow.com/q/32884564/14731 shows that users are finding it difficult as well.

Please consider using ES6 modules instead of AMD.

**Comment by cowwoc** [comment]
You can use https://github.com/buxlabs/amd-to-es6 to automate the conversion.

**Comment by kevin-brown** [comment]
> Please consider using ES6 modules instead of AMD.

This has been considered, but because of how much of a breaking change this would be, we would have a hard time doing this without rolling a new major version.

**Comment by cowwoc** [comment]
So roll out a new major version... No one says a lot of time has to pass between major versions. The usability of this library would improve quite a bit. I also suspect the library size would drop quite a bit as you remove the embedded AMD loader.

On a related note, the whole concept of custom data adapters would be easier to understand with ES6 modules and `extends ArrayData` instead of what is found at https://select2.org/upgrading/migrating-from-35#custom-data-adapters-instead-of-query.

**Comment by LarsStegman** [comment]
Not stale

**Comment by raulpopadineti** [comment]
+1 for this.

**Comment by raulpopadineti** [comment]
bump

**Comment by kevin-brown** [comment]
My goal is likely going to be to go to TypeScript at the same time that we switch away from AMD. The only thing currently holding me back (aside from having other things to do than migrate this entire project) is trying to get native class decorators to work instead of our current solution.

**Comment by shakhzodkudratov** [comment]
still actual

**Comment by gingerlime** [comment]
Also bumped into this. How can I import `ArrayData` and `Util` with webpack?

The migration doc uses this

```javascript
$.fn.select2.amd.require([
'select2/data/array',
'select2/utils'
], function (ArrayData, Utils) { .. })
```

But it's not working for me. I'm using `import Select2 from "select2/dist/js/select2.full"` and could not figure out how to get access to `ArrayData` or `Utils` ...

**Comment by KirtashW17** [comment]
Hi! I like Select2, but the fact that isn't using ES6 Modules in 2024 is a big downside for me. Any chance that this will be implemented in the future? Can this issue be reopened?

Thanks.
