### ISSUE TITLE
can't search in safari

### ISSUE THREAD

**Issue by ikak0nek0chanpanda** [select2/select2#5633]
I can search correctly by searching for “l” in the example of this site.
https://select2.org/selections

However, I can't search correctly if I do the following:
1. by searching for "aaaaa" in the example of same site in safari.
2. delete "aaaaa".
3. key press ↓or↑key.
4. by searching for “I” again.
5. I can't search it.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by ikak0nek0chanpanda** [comment]
>What browser(s) and Operating System have you tested with?
 this bug appears only mac+safari.

>Does the bug happen consistently across all tested browsers?
 safari.

>Can you reproduce this issue on any of the examples in the docs?
>What version of jQuery are you using? And what version of Select2?
>Are you using Select2 with other plugins?

As described in the report above, it occurs on the following demo sites:
https://select2.org/selections

1. by searching for "aaaaa" in the EXAMPLE under templating.
2.delete "aaaaa".
3.key press ↓or↑key.
4.by searching for “I” again.
5.I can't search it.
