### ISSUE TITLE
multiselection with keyboard works badly loosing "current focus" randomly

### ISSUE THREAD

**Issue by kikonen** [select2/select2#5635]
Continuation of #5626

So CTRL + SPACE, which actually should be CMD + SPACE if running in OSX environment is used for multiselection (I shall report that as another bug).

Problem:
If trying to quickly select multiple items CTRL + SPACE, then focus is very often suddenly stolen. Thus focus jumps back to first item in dropdown list, which is very irritating if user is trying to select items which are very far in the end of list.

There is two variants with this focus problem

(a) If mouse is hovering over dropdown, then focus is stolen generally into point where is mouse is hover

(b) if mouse is not hovering around dropdown (nor select2 widget itself) then focus is generally stolen randomly into beginning of list. Especially if user is trying to do selections "too fast".

**Comment by kevin-brown** [comment]
For what it's worth, I just tried to reproduce this for about 10 minutes through different methods and I couldn't. So I'm probably trying to do it wrong.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
