### ISSUE TITLE
Dropup position not being re-evaluated if there is enough space above

### ISSUE THREAD

**Issue by susiekims** [select2/select2#5640]
You can see this behaviour in the examples from the documentation (tested with https://select2.org/getting-started/basic-usage#multi-select-boxes-pillbox)

1. On your screen, position the field in so that the dropdown will be rendered above the field.
2. Click out of the field so the dropdown will close. 
3. Re-position the select field on your screen so that there is enough space both above and below the field to render the dropdown. 
4. Click into the field again to open the dropdown. 

**Result:** The dropdown will be shown above the field still, even though there is enough space to be a dropdown.

If there is enough room below, I think it should set the new direction to 'below' regardless of if there is still enough room above. I think the logic in `AttachBody.prototype._positionDropdown ` should be modified as 'below' is the natural position for dropdowns.

**Recording of the issue here:** https://recordit.co/n2iaBC5TEU

**Comment by kevin-brown** [comment]
This is done for consistency. Select2 will "stick" with a position for as long as it possibly can, because otherwise you would see it "flapping" between both directions during times where messages are displayed or the dropdown position is recalculated.
