### ISSUE TITLE
German translation: de.js wrong translation

### ISSUE THREAD

**Issue by Kingside88** [select2/select2#5641]
Hi, just a wrong translation:

Now the translation is: "Bitte XXX Zeichen mehr eingeben"
But its not common. Better is "Bitte mindestens XXX Zeichen eingeben".
For: Please enter XXX or more characters.

Also:
Now: Sie können nur XXX Element auswählen
Should be: Sie können maximal XXX Elemente auswählen

And:
Now: Bitte XXX Zeichen weniger eingeben
Schould be: Bitte weniger als XXX Zeichen eingeben

Corrected file in the attachmend
[de.zip](https://github.com/select2/select2/files/3615468/de.zip)

**Comment by kevin-brown** [comment]
We welcome pull requests to the repository.

Unfortunately we can't apply translations from an attached ZIP file on your behalf, but if you make a pull request through GitHub we will gladly review it for inclusion in the next release.
