### ISSUE TITLE
Allowing new inputs on 4.0.10

### ISSUE THREAD

**Issue by sh4dowb** [select2/select2#5643]
People have suggested a few solutions to allow new inputs from user:

```
createSearchChoice:function(term, data) {
  if ( $(data).filter( function() {
    return this.text.localeCompare(term)===0;
    }).length===0) {
      return {id:term, text:term};
 }
```

`tags: true,`
`selectOnClose: true,`
`selectOnBlur: true,`

Unfortunately I couldn't get any of them work with 4.0.10. I've tried a lot of examples and combinations of these attributes.
It always shows this:

![image](https://user-images.githubusercontent.com/12783710/65171430-8335e980-da53-11e9-8a7b-0d3473caf050.png)

Could anyone make it work in 4.0.10?

**Comment by kevin-brown** [comment]
It's called "dynamic option creation" in the docs (formerly "tagging"):

https://select2.org/tagging

**Comment by sh4dowb** [comment]
Ah, my bad. I accidentally created the element as `<input>`, and when I used select2 it worked, but `tags: true` wasn't working. It works now after making it `<select>`.
