### ISSUE TITLE
selected: false ignored, Clear selection ignored

### ISSUE THREAD

**Issue by mcandre** [select2/select2#5645]
Non-multiselect inputs are picking the first option by default, even when all data rows explicitly set `selected: false`. Which is not what many applications would want to happen. Rather, applications often want to not select anything by default.

This used to be configured with the `initSelection` callback, but this was deprecated:

https://select2.org/configuration/options-api

... but the documentation does *not* say what syntax to use to replace this with. There is some mention of data adapters, with no examples for actually effecting the desired behavior.

I'm trying to make sense of the example snippet:

```js
$.fn.select2.amd.require([
    'select2/data/array',
    'select2/utils'
], function (ArrayData, Utils) {
    function CustomData ($element, options) {
        CustomData.__super__.constructor.call(this, $element, options);
    }

    Utils.Extend(CustomData, ArrayData);

    CustomData.prototype.current = function (callback) {
        var data = [];
        var currentVal = this.$element.val();

        if (!this.$element.prop('multiple')) {
            currentVal = [currentVal];
        }

        for (var v = 0; v < currentVal.length; v++) {
            data.push({
                id: currentVal[v],
                text: currentVal[v]
            });
        }

        callback(data);
    };

    $("#select").select2({
        dataAdapter: CustomData
    });
}
```

Which is a very long way to accomplish this. There's actually too much documentation and I don't know which of many snippets I should be using.

I also tried the following snippet:

```js
placeholder: {
    id: '',
    text: 'e.g., asa'
}
```

With ID `''` blank string, zero, and -1. No success for any of these.

Same story for:

```js
templateSelection: function(data) {
    if (data.id === '') {
        return 'e.g., asa';
    }

    return data.text;
}
```

And I tried:

```js
$('#budgetProject').val(null).trigger('change');
```

And `-1` and `''` blank string, with no luck. The browser keeps selecting the first item.

In fact, the browser JS console reports that the select value is already mistaken to be `aqua`, the first item, rather than the empty value it's supposed to be.

So what exactly do we type to STOP select2 from selecting the first element, when `selected` is already set to `false` for every record?

**Comment by mcandre** [comment]
Finally, got select2 working for placeholders, by modifying the *HTML*:

```html
<select
    class="select2"
    id="budgetProject"
    name="project"
>
    <option></option>
</select>
```

Somehow, select2 messes up and forgets to implicitly include an empty `<option></option>` placeholder element when no entry is selected.

**Comment by kevin-brown** [comment]
As noted in the giant "info" box right below the example for placeholders in a single select

https://select2.org/placeholders#single-select-placeholders

You need an empty `<option></option>` element in order for placeholders to work.

> Somehow, select2 messes up and forgets to implicitly include an empty `<option></option>` placeholder element when no entry is selected.

This is a limitation of JavaScript, the DOM, and lots of other things outside of the control of Select2: https://github.com/select2/select2/issues/3553#issuecomment-119772829

It's not possible for us to do that implicitly.
