### ISSUE TITLE
Serious lag when creating a select2 multiple with hundreds preselected options

### ISSUE THREAD

**Issue by hhoweson** [select2/select2#5657]
I have heavily annotated the code in the following bin to illustrate and explain my problem. It made more sense to explain it from within the code than from here so please check it out: 
https://jsbin.com/teyujikaka/edit?js,output

**Comment by kevin-brown** [comment]
This looks like an issue and the description given within the jsbin was helpful. I'm open to reviewing a pull request about this, since I am aware that the listeners we have at the moment are very broad.

**Comment by gorrilla10101** [comment]
I took a look at @hhoweson  jsbin and it was appending each option individually. I modified the script to store the options in an array and pass them all at once. It improved it to where it would handle 1200 records, and the performance on 100 was drastically improved.
Here is the modified jsbin
https://jsbin.com/yivefom/edit?js,output

**Comment by hhoweson** [comment]
Hi there, sorry for not ever following up on this.

Nice spot @gorrilla10101, that was one of the solutions I tried however it still won't work with 2000+ records and will cause the whole page to hang.

I didn't have time to create a fix so I created the following rather hacky workaround with the intention of coming back to this when I have time. The following will execute almost instantly with 2000 records and has worked for me thus far. I just copied this straight in from my code base so you may have to play around with it to get it to behave how you like.

```
function createSelect2Options($select, options) {

	// This function is a workaround for an issue with the select2 library: https://github.com/select2/select2/issues/5657
	// Options should be an array of option objects: option = {id: 'optionId', text: 'Option Name'}
	// $select should be the jquery object for the select box

	options.forEach(function (option) {

		var optionElement = new Option(option.text, option.id); // Do not make the option selected here
		$select.append(optionElement);

		// Due to a bug in select2 it will cause severe lag if the options are selected during creation
		// See the githib issue here: https://github.com/select2/select2/issues/5657
		window.setTimeout(function () {
			// This will delay the selection process until after select2 has viewed the dom change
			// select the option after the dom event for creation has been viewed by select2
			$(optionElement).prop('selected', true);
		}, 0);

	});

	// inform select 2 of the change after the options have been selected later on
	window.setTimeout(function () {
		$select.trigger('change');
	}, 1);

}
```
