### ISSUE TITLE
abandon the use of jquery 

### ISSUE THREAD

**Issue by arcanisgk** [select2/select2#5662]
Any project to abandon the use of jquery as a dependent bookstore? or some other project like select2?

**Comment by ivaynberg** [comment]
see https://github.com/select2/select2/tree/select2-5.x

**Comment by alvarotrigo** [comment]
So far you can use Choices, seems to be quite a good replacement without jQuery:
https://joshuajohnson.co.uk/Choices/

**Comment by arcanisgk** [comment]
> So far you can use Choices, seems to be quite a good replacement without jQuery:
> https://joshuajohnson.co.uk/Choices/

thank but this is not compatible with BS4/datatable.net plg CSS
