### ISSUE TITLE
Missing event: on rendered

### ISSUE THREAD

**Issue by simplenotezy** [select2/select2#5674]
I would like an event to be fired when select2 has been rendered. Currently people suggest to fire after "xx" milliseconds, but that's not a pretty solution.

I was surprised not to find a "on select2:rendered" or "select2:init" event.

**Comment by kevin-brown** [comment]
Generally speaking, Select2 will finish the initial rendering as soon as the call to `$(element).select2()` returns. We don't do much (if any) delayed rendering for the initialization. So we haven't had a real near to implement our own event saying that things have finished initializing.

I would recommend [triggering your own jQuery custom event](https://learn.jquery.com/events/introduction-to-custom-events/) if you need this. It would also be useful to know what use cases this could support, so we can keep track of them and see if there might be a better way to support them.
