### ISSUE TITLE
Can we please re-open this: Feature request: Multi-select with shift and Ctrl/Cmd keys functionality?

### ISSUE THREAD

**Issue by henrymorton** [select2/select2#5675]
Could we please re-open my previous request - #5302 

I hope this is the correct way to make this request - I could find no information otherwise.

Many thanks!

Henry

**Comment by henrymorton** [comment]
Hi there,

I am guessing this was closed because it was a repeat of another pull request.

My question is, how do I request the other pullrequest to be re-opened?

Cheers,

Henry



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by henrymorton** [comment]
Sorry, ignore that, the re-open email has just come through.

Many thanks!



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by kevin-brown** [comment]
The other one was reopened. :)
