### ISSUE TITLE
Pre-select doesn't work 

### ISSUE THREAD

**Issue by ruslankrivoshein** [select2/select2#5679]
I use **select2** in conjunction with **datatables editor**.

```
let editor = new $.fn.dataTable.Editor({
  fields: [{
    label: label,
    name: name,
    type: 'select2',
    opts: {
      multiple: true,
      data: (params) => ({ search: params.term, type: 'public' }),
      ajax: {
        url: url,
        dataType: 'json',
      }
    }
  }]
})
```

Response from server:
```
{
  "results": [
    {
      "id": 1,
      "text": "Option 1",
      "selected": true // not even "selected": "selected"
    }
  ]
}
```

but it's not pre-selected. I believe, it's not due to **datatables editor**, cause it uses **select2** render.

**Comment by kevin-brown** [comment]
The server response only indicates that it's selected in the dropdown that shows the results, it does not "pre-select" it for you on the front end. You need to actually select it within the dropdown in order for that to work.

I believe this is ultimately a datatables editor issue if it does not provide a way to pre-select items in a select box, much less Select2.

----

This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

[ml]: https://select2.org/troubleshooting/getting-help
