### ISSUE TITLE
Choice box does not close when click outside

### ISSUE THREAD

**Issue by ayberkcal** [select2/select2#5680]
I open form in [fancybox ](http://fancyapps.com/fancybox/3/) modal via ajax loading and I have two select2 select box. When I click select box and choice box opened. If I do not select any options and try to click out side of choice box, choice box does not closed (or click any input on fancybox modal). I expected close choice box. I think it is related to fancybox modal. 
I have some search in google and I found similar [issue](https://github.com/select2/select2/issues/1623) like my issue. And I try to add click listener to my form but it did not work because it is called also when I try to selectbox. Also I think **dropdownParent** should resolve this problem but it does not solve.

So, How can I resolve this issue? Any suggestions?

Fancybox JS:
```
$.fancybox.open({
	type: 'ajax',
	ajax: {
		// Object containing settings for ajax request
		settings: {
			// This helps to indicate that request comes from the modal
			// Feel free to change naming
			data: {
				fancybox: true
			}
		}
	},
	touch : {
		vertical : true,  // Allow to drag content vertically
		momentum : true   // Continuous movement when panning
	},
	src: '/profile/addaddress?type=1',
	opts : {
		afterShow : function( instance, current ) {

		}
	},
	closeClick	: false,
	maxWidth: 400
});
```
Select2 JS:
`$('#new-address').find('select.city-selectpicker').select2({dropdownParent: $('#new-address')});`

Form HTML:
```
<form id="new-address" validate>
    <div class="row">
		......
		<div class="col-md-12">
			<div class="form-row">
				<div class="form-group col-lg-6 col-md-12">
					<label>City</label>
					<select class="form-control city-selectpicker" name="city-selectpicker" data-placeholder="Select City" required>
						<option value="...">A</option>
						<option value="...">B</option>
						<option value="...">....</option>
					</select>
				</div>
			</div>
		</div>
		......
	</div>
</form>
```
My workaround test about [issue](https://github.com/select2/select2/issues/1623)
```
$('#new-address').on('click', function(){
	$(".city-selectpicker").select2("close");
	$(".county-selectpicker").select2("close");
});
```

**Comment by kevin-brown** [comment]
Fairly confident this is related to fancybox capturing the click event and stopping it, similar to the issues we see with Bootstrap.

This issue suggests you can get it to work with `dropdownParent`: https://github.com/select2/select2/issues/506
