### ISSUE TITLE
Select2 inside ShadowRoot Broke In 4.0.11

### ISSUE THREAD

**Issue by OJMichael** [select2/select2#5682]
#5584 breaks the usage of Select2 inside a ShadowRoot, because `$.contains()` returns false, even though the Node is actually connected to the document.

I'd propose changing the following code:
```javascript
    if ($.contains(document.body, $offsetParent[0])) {
      parentOffset = $offsetParent.offset();
    }
```

To this:
```javascript
    if ($offsetParent[0].isConnected) {
      parentOffset = $offsetParent.offset();
    }
```

**Comment by lazka** [comment]
Since 4.0.11 (4.0.10 works) I also get wrong offsets for the popup:

![select2-bug](https://user-images.githubusercontent.com/991986/67678042-e9345b80-f985-11e9-8ce6-38c7bc1df5e4.png)

This is also inside a Shadow DOM.

**Comment by kevin-brown** [comment]
Probably going to switch this to

```js
    if ($.contains(document.body, $offsetParent[0]) || $offsetParent[0].isConnected) {
      parentOffset = $offsetParent.offset();
    }
```

Just to handle IE/Edge/older browsers when they aren't using the shadow DOM (because let's be honest, they won't be using the shadow DOM if they're old enough to not support `isConnected`).

**Comment by paxnovem** [comment]
I have made the change locally, looking into how to get proper test coverage for this

**Comment by knlshnd** [comment]
I am still not able to get it working inside the shadowDOM. I am trying to use it inside an angular element. It gives me an error: Please add Select2 library (js file) to the project. I am using view encapsulation in this. I do not know how to use dropdownParent properly, so have not tried that

**Comment by lazka** [comment]
I have it working with a dropdownParent referencing an element in the shadow dom, if that helps.

**Comment by knlshnd** [comment]
Can you give me a reference as to how exactly to do it?

**Comment by sergotail** [comment]
Hi, issue still persists for multiple shadow DOM subtrees having select2 elements. I have a custom element, and i initialize select2 for elements inside shadow DOM, in connectedCallback. And when i add second, third and so on custom elements, all select2 forms nested in existing custom elements are become broken.
My version of select2 is 4.0.13.
