### ISSUE TITLE
width resolve calculated width is too small

### ISSUE THREAD

**Issue by tainewoo** [select2/select2#5683]
https://jsbin.com/deyajay/edit?html,output

the width 57px is calculated with resolve mode.
but actually the width didn't consider the boarder and dropdown button, and caused some character can not be shown.

**Comment by kevin-brown** [comment]
If your select box is resolving to be 57px and that's too small, then I would recommend making your original select box larger with CSS or by another styling means.

This isn't something which we can reasonably fix.

**Comment by tainewoo** [comment]
Hi @kevin-brown ,

Mostly the original CSS fits the original select box.
But, for select2, same width or resolved width would be quite narrow because of normally select2 style will need more width.

And if the "allowClear" option is applied, there will be a "x" append to the right of the box, it makes the width left to display characters more narrow, most of time the charachters will be covered or overflow.

So, if the formula used to calculate the width and add 5-10 percent plus to the current result, it would be better, especially if the "allowClear" option is enabled.
