### ISSUE TITLE
Circumflex accent bug in tags mode

### ISSUE THREAD

**Issue by Fl0ux** [select2/select2#5684]
In tags mode, typing a word containing a circumflex accent produce a weird result. I made an example linked below to show you what's wrong. Try typing a work like "plutôt".

[https://jsfiddle.net/FauconNoir/njh0qxwb/2/](https://jsfiddle.net/FauconNoir/njh0qxwb/2/)

It seems to be fine in the "normal" mode.

**Comment by kevin-brown** [comment]
I have no idea what a "weird result" is, but copying that into the search field produced the standard response.

![image](https://user-images.githubusercontent.com/1991850/68352265-e2b78980-00d3-11ea-8884-bdeaea7b98ab.png)

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by Fl0ux** [comment]
Copy/paste works fine, but if you type it manually you will have the weird result.

**Comment by kevin-brown** [comment]
Is there any chance you can give an example of what this "weird result" is? This ticket isn't immediately actionable and I'm not seeing anything out of the ordinary when testing this locally.

**Comment by Fl0ux** [comment]
I start typing the word, everything is fine so far.
![Capture d’écran du 2019-11-12 09-37-31](https://user-images.githubusercontent.com/545615/68655475-61775100-0530-11ea-94fb-256f7db3cee7.png)
I press the key corresponding to the accent, OK
![Capture d’écran du 2019-11-12 09-38-13](https://user-images.githubusercontent.com/545615/68655477-61775100-0530-11ea-8103-70f9f9f8cd03.png)
I press "o" to set the letter under the accent and this letter disappear.
![Capture d’écran du 2019-11-12 09-38-42](https://user-images.githubusercontent.com/545615/68655478-61775100-0530-11ea-8cdd-895f59137b14.png)
If I try to add more letter they all disappear
![Capture d’écran du 2019-11-12 09-39-03](https://user-images.githubusercontent.com/545615/68655480-620fe780-0530-11ea-8c72-a937a63f6a7a.png)

**Comment by bilua-xiaolei** [comment]
Hello, I have same issue, but instead of "dissapearing" the letter, its written as separated character
![image](https://user-images.githubusercontent.com/19576899/70993570-99902780-20cc-11ea-9b10-23f540aab951.png)

**Comment by bilua-xiaolei** [comment]
I think this should be closed and try to be fixed

**Comment by kevin-brown** [comment]
I'm going to reopen this for one more stable cycle. This isn't a bug that's easy for me to reproduce which makes it difficult for me to fix.

If someone is willing to provide a pull request that identifies the issue and fixes it, I'm willing to review it.

**Comment by chuchiperriman** [comment]
I'm not a javascript expert but I've modified select2 by hand to do a workaround for this problem (.js distribution file, 4.0.13 version):

```javascript
this.$selection.on(
      'keyup.search input.search',
      '.select2-search--inline',
      function (evt) {
        // IE will trigger the `input` event when a placeholder is used on a
        // search box. To get around this issue, we are forced to ignore all
        // `input` events in IE and keep using `keyup`.
        if (disableInputEvents && evt.type === 'input') {
          self.$selection.off('input.search input.searchcheck');
          return;
        }

        var key = evt.which;

        // We can freely ignore events from modifier keys
        if (key == KEYS.SHIFT || key == KEYS.CTRL || key == KEYS.ALT) {
          return;
        }

        // Tabbing will be handled during the `keydown` phase
        if (key == KEYS.TAB) {
          return;
        }

        // ----------------- Workaround (spanish) ----------------------
        var lastChar = self.$search.val().slice(-1);
        if ("^´`¨".indexOf(lastChar) != -1){
          return
        }
        // ----------------- End workaround ----------------------

        self.handleSearch(evt);
      }
    );
```

**Comment by TeoMastro** [comment]
Hello, I have the same issue with greek. 
For example: when I type: καλημέρα, I see: καλημ'ερα.
I already tried the suggested workaround and it did not work.
This is how I use the plugin (we work with the yii2 framework, which should not matter since the issue is in the core plugin and not the wrapper: https://demos.krajee.com/widget-details/select2)

```
                   <div class="col-12">
                        <?= $form->field($model, 'tagIds')->widget(Select2::class, [
                            'data' => QuestionTag::mapAllModels(),
                            'value' => $model->tagIds,
                            'maintainOrder' => true,
                            'options' => [
                                'placeholder' => '',
                                'multiple' => true,
                                'id' => 'question-tag-select',
                            ],
                            'pluginOptions' => [
                                'allowClear' => true,
                                'tags' => true,
                                'createTag' => new JsExpression("
                                    function(params) {
                                        var term = $.trim(params.term);
                                        var exists = $('#question-tag-select option').filter(function() {
                                            return $(this).text().toLowerCase() === term.toLowerCase();
                                        }).length > 0;
                                        if (!exists) {
                                            return {
                                                id: term + tempTagNameSuffix,
                                                text: term,
                                            };
                                        }
                                        return null;
                                    }
                                "),
                            ],
                        ]) ?>
                    </div>
``` 

I get the problem inside the createTag function of the plugin.
