### ISSUE TITLE
Options with empty value will not be shown

### ISSUE THREAD

**Issue by tainewoo** [select2/select2#5688]
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet"/>
  <script src="https://code.jquery.com/jquery-3.4.0.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>  

</head>
<body>

  
<select name="SSS" id="SSS">
<option value="">&nbsp;</option>
<option value="1">S0</option>
<option selected="selected" value="2">S1</option>
<option value="3">S2</option>
</select>

<script>
  $(document).ready(function () {
    $("#SSS").select2({
      placeholder: "",
      width: "resolve"
    });
  });
</script>
  
</body>
</html>
```

**Comment by tainewoo** [comment]
https://jsbin.com/sibecisigi/edit?html,output

**Comment by kevin-brown** [comment]
This is fully intentional and cannot be overridden. Here's the code where we hide it:

https://github.com/select2/select2/blob/e809aa0fee8a1be34cb01fc85037791b3927c012/src/js/select2/dropdown/hidePlaceholder.js

An empty placeholder option would look strange in the results list, so we hide it. If you need a way for users to reset to the placeholder, look into using the `allowClear` option.

https://select2.org/selections#clearable-selections

It occurs to me that this could use some better docs, so I'm going to leave this open as a documentation enhancement.

**Comment by tainewoo** [comment]
Hi @kevin-brown ,

Yes now I use the allowClear to allow users to clear the selected values, because usually we need to clear the value of some fields and update it to be empty.
For select, this option will be shown as an option with empty value, for uses to set the value as blank/empty:
`<option value="">&nbsp;</option>`
But after it's replaced as select2, this option is just ignored(hided). So later I added the "allowClear" option in my code, to allow users to clear the selected values and save it as empty values.

Thank you for your comments.

**Comment by tainewoo** [comment]
Hi @kevin-brown ,

https://jsbin.com/qoxeney/edit?html,output
option empty value even with text placehold, will not be shown too.

is it better that we only call the hidePlaceholder for multi-selection but not single?

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet"/>
  <script src="https://code.jquery.com/jquery-3.4.0.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>  

</head>
<body>

  
<select name="SSS" id="SSS" style="width: 100px;">
<option value="">testplacehold</option>
<option value="1">S0</option>
<option selected="selected" value="2">S1</option>
<option value="3">S2</option>
</select>

<script>
  $(document).ready(function () {
    $("#SSS").select2({
      placeholder: "",
      width: "resolve",
      allowClear: true
    });
  });
</script>
  
</body>
</html>
```

**Comment by kevin-brown** [comment]
If you do not want the placeholder option to be hidden, and instead for it to appear and function like another option, we recommend not using placeholders. It sounds like you're looking for a default selected option, like one you would see in a normal dropdown.

> is it better that we only call the hidePlaceholder for multi-selection but not single?

No, because then it would be inconsistent.

**Comment by tainewoo** [comment]
Hi  @kevin-brown ,
And if there is no placeholders, the allowClear will not work too.
https://jsbin.com/dezaras/edit?html,output

So seems it's better to generate the placeholder dynamically according to the original select options, or is this the issue of allowClear?

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.0.11/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.0.11/dist/js/select2.min.js"></script>


</head>
<body>

  
<select name="SSS" id="SSS" style="width: 200px;" multiple="multiple";>
<option value="">Empty</option>
<option value="1">S0</option>
<option value="2">S1</option>
<option value="3">S2</option>
</select>

<script>
  $(document).ready(function () {
    $("#SSS").select2({
      //placeholder: "",
      width: "resolve",
      closeOnSelect: false,
      allowClear: true
    });
  });
</script>
  
</body>
</html>
```

**Comment by morganarnel** [comment]
An empty placeholder option is unlikely to contain a value="" attribute, whereas null options will include this. It's not hard to distinguish between the two.

I think this should be looked into again, as the current implementation requires someone to write more code to initialise select2 on elements that should show these options.
