### ISSUE TITLE
hided empty option will be selected too after clear the value in a multiple select2 when allowClear enabled

### ISSUE THREAD

**Issue by tainewoo** [select2/select2#5695]
https://jsbin.com/cikihafuka/edit?html,output

Original select box: multiple, first value is "" (empty value).
select2 option: allowClear enabled.
steps:
1. click on the "x" on the right corner of the select2 box (clear value).
2. click in the box, and select any value.
3. in additional to the selected value, there would be another item shown as selected, seems it's the hided empty placehold, comes from the empty option of the original select box.

![emptyoption](https://user-images.githubusercontent.com/13391232/68202523-ddd4d600-fffe-11e9-8c81-4c757841c62e.png)

```
code:

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css" rel="stylesheet"/>
  <script src="https://code.jquery.com/jquery-3.4.0.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>  

</head>
<body>

  
<select name="SSS" id="SSS" style="width: 100px;" multiple="multiple";>
<option value="">&nbsp;</option>
<option value="1">S0</option>
<option value="2">S1</option>
<option value="3">S2</option>
</select>

<script>
  $(document).ready(function () {
    $("#SSS").select2({
      placeholder: "",
      width: "resolve",
      // closeOnSelect: false,
      allowClear: true
    });
  });
</script>
  
</body>
</html>
```

**Comment by tainewoo** [comment]
also tried 4.0.11:
https://jsbin.com/diculepobe/edit?html,output


```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.0.11/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.0.11/dist/js/select2.min.js"></script>


</head>
<body>

  
<select name="SSS" id="SSS" style="width: 200px;" multiple="multiple";>
<option value="">&nbsp;</option>
<option selected="selected" value="1">S0</option>
<option value="2">S1</option>
<option value="3">S2</option>
</select>

<script>
  $(document).ready(function () {
    $("#SSS").select2({
      placeholder: "",
      width: "resolve",
      closeOnSelect: false,
      allowClear: true
    });
  });
</script>
  
</body>
</html>
```

**Comment by kevin-brown** [comment]
https://select2.org/placeholders#single-select-placeholders

> **For single selects only**, in order for the placeholder value to appear, you must have a blank <option> as the first option in your <select> control. This is because the browser tries to select the first option by default. If your first option were non-empty, the browser would display this instead of the placeholder.

You should not be using a placeholder option for a multiple select.

**Comment by tainewoo** [comment]
Thank you @kevin-brown , i will update my codes accordingly.
