### ISSUE TITLE
can't get current value on clear

### ISSUE THREAD

**Issue by nmase88** [select2/select2#5702]
On clearing the select2 (when allowClear is enabled) it is not possible to get the current selected value using select2:clearing or select2:unselecting. I would expect this to be the way it behaves given it is how it behaves for select2:selecting,

**Comment by kevin-brown** [comment]
We pass in the previously deleted data as parameters to the `select2:clear` event. You should be able to access it within your event handler.

I honestly can't remember why we don't do those consistently, but looking around at other tickets leans towards `select2:select` being the odd one out that isn't consistent.
