### ISSUE TITLE
showLoading() do not show loading spinner in UI 

### ISSUE THREAD

**Issue by LVDuong** [select2/select2#5703]
Before I upgraded Bootstrap and Jquery to lastest version, my website using showLoading() in select2.full.js had run nomarlly and it had also show loading spinner below when loading the page. But when I upgraded Bootstrap to version 4.3.1 and version 3.4.1 with jQuery, the loading spinner was not show in the view of page although it ran hidden. 
![showLoading](https://user-images.githubusercontent.com/32818804/68667532-c8b8f380-0578-11ea-9375-c1cffa0485fa.PNG)
Anyone can help me show loading spinner? Thanks!

**Comment by kevin-brown** [comment]
Select2 doesn't have a full page loading spinner 🤔 

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
