### ISSUE TITLE
Select2: Alternating Auto-Focus between two Dropdown Menu / or select other textbox then it only focus on select2 dropdown

### ISSUE THREAD

**Issue by kingaj** [select2/select2#5704]
Please Help i have Problem with select2 dropdown and ill add video link below
https://www.loom.com/share/8bcc774640504abd922715ee6c27e878

- when i click on select2 dropdown then i select other textbox or any other filed in my form focus redirect to select box from my selected attribute 

Bootstrap version v3.3.6 
Select2 version  4.0.1

**Comment by kevin-brown** [comment]
The version of Select2 that you are using is from a few years ago. Please upgrade to the latest version and let us know if this issue persists.
