### ISSUE TITLE
How to get the select search value?

### ISSUE THREAD

**Issue by Jatapiaro** [select2/select2#5709]
Hey I want to know what is the value of the search when there are no results.
Is there a way to know that value in this part of the code?
```
        language: {
            noResults: function() {
                return "No results <a href='http://google.com'>Add new value</a>";
            }
        },
```

**Comment by kevin-brown** [comment]
> Is there a way to know that value in this part of the code?

Nope, we don't pass this information into the renderer when there are no results.
