### ISSUE TITLE
On createTag, customize the value of the new option

### ISSUE THREAD

**Issue by Jatapiaro** [select2/select2#5710]
Is there a way to customize the value of a new tag? For example I want to create something like this:
`<option value="myCustomValue">The New Created Tag</option>`

I'm trying to do this, but is not working, and I can't find something on the documentación about this:
```
        createTag: function (params) {
            var term = $.trim(params.term);

            if (term === '') {
                return null;
            }

            return {
                id: term,
                text: term,
                newTag: true, // add additional parameters,
                value: "myCustomValue"
            }
        }
```

**Comment by tracerTres** [comment]
id represents what will be put as value.
   `createTag: function(params) {
			return {
      id: "myCustomValue",
      text: params.term
    	}}`

**Comment by kevin-brown** [comment]
You can find more information on how Select2 generates options from the data objects, which might help you with getting things right.

https://select2.org/data-sources/formats
