### ISSUE TITLE
Select2 full prevent left and right arrow keys from any input field on a form why?

### ISSUE THREAD

**Issue by connecttosunil** [select2/select2#5713]
I am using select 2 as full version. And I found an issue with this.

      <script src="{{ asset('bower/select2/dist/js/select2.full.min.js') }}"></script>

Its preventing LEFT & RIGHT arrows key to work / function on any input where I am using select box.

But I remove the included plugin above (select2.full.min.js  ) then let & right key start working on each input on my form.
![bug](https://user-images.githubusercontent.com/29477434/69782973-85958c00-11d8-11ea-81bc-30c2a2d76c18.png)

Any one face this issue ? or I am wrong with this

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by connecttosunil** [comment]
Q: What steps can be used to reproduce the issue?

**Ans:**    Just add select 2 any select box in a form , and then see the other input element that form stopped the arrows keys working. Suppose I have 2 element on my form one select 2 box and other is simple input box.

So other simple input box also do not allows the left&right arrows to work.

Q: What is the bug and what is the expected outcome?

**Ans:**  Bug is it should prevent other input to use arrow keys. and outcome should be alble to use arrow keys in other input in the form.

Q: What browser(s) and Operating System have you tested with?

**Ans:** Chrome & Ubuntu 16.04


Q: What version of jQuery are you using? And what version of Select2?

Ans: j query is latest and select 2 is 4.0.11

**Comment by kevin-brown** [comment]
Select2 doesn't capture the input anywhere, so this sounds _a lot_ like a bad interaction with a plugin. This is backed up by the fact that we can't reproduce this in the documentation site.

* Are you using Select2 with other plugins?

If you can't narrow this down to a plugin on your side (even when you strip them all out), we're going to need [an isolated test case](https://css-tricks.com/reduced-test-cases/) to be able to debug this.
