### ISSUE TITLE
Cannot pre-select options dynamically (multiselect). Pillbox not showing.

### ISSUE THREAD

**Issue by yenyeeeen** [select2/select2#5715]
I have initialized Select2 element inside jquery ready function.

I want to preslect data based on my ajax call, I already have selected options to be marked as selected. But pillbox not showing only search box.

Based on the inspect element, select2-choices is empty, pillbox is not rendered. but options meant to be selected have the selected attribute. 

![image](https://user-images.githubusercontent.com/6956641/69844459-539f2b00-12a7-11ea-8d01-a4028e9b85e3.png)

please see code:

![image](https://user-images.githubusercontent.com/6956641/69844414-1dfa4200-12a7-11ea-93b5-28fece7a043c.png)

How do I get the pillbox to show pre-selected data? thanks

**Comment by kevin-brown** [comment]
Based on the rendered HTML, the version of Select2 that you're using is _at least_ 4 years old and appears to be the 3.5.x line. Please upgrade to the 4.x line of Select2.

**Comment by yenyeeeen** [comment]
thanks. updating the version works!
