### ISSUE TITLE
select2 optgroup and set active option programmatically

### ISSUE THREAD

**Issue by jujo-1** [select2/select2#5718]
Tried several different ways to set a select2 dropdown option active when it belongs to one of many optgroups. The only one partially working is as follows

```
$("#select_id").find("optgroup[label='target_label'] option[value='target_value']").attr("selected", "selected")
$("#select_id").trigger("change")
```
however, though it displays the wanted option, it doesn't actually select the target option within the dropdown and it also messes up with the "selected" attribute which must be reset later

**Comment by kevin-brown** [comment]
> however, though it displays the wanted option, it doesn't actually select the target option within the dropdown and it also messes up with the "selected" attribute which must be reset later

You need to set the `.prop('selected', true)` instead of setting the attribute. Select2 pays attention to the internal JS property instead of the HTML attribute, and you'll find quite often that these two don't actually match at all.
