### ISSUE TITLE
select2 positioning problem

### ISSUE THREAD

**Issue by AdvanceOrange** [select2/select2#5722]
Hello,
I am using Select2 v4.0.6-rc.1
I encountered a problem when I set minimumInputLength to 2
When I enter a keyword in the search box up to 2 characters, the result of select2 is displayed above the control. As I gradually delete characters, the result of select2 changes, but the position property of select2 is not recalculated, causing the position display error

**Comment by kevin-brown** [comment]
4.0.6-rc.1 is pretty old and I believe had positioning issues specific to it. I would recommend upgrading to the latest version of Select2 which should fix the issues you're seeing.
