### ISSUE TITLE
Microsoft Edge Detects Certain Values as Telephone Numbers and this Causes the First Enabled Element to be Hidden

### ISSUE THREAD

**Issue by Python-Regius** [select2/select2#5724]
Microsoft Edge will automatically recognize text that matches certain patterns as a phone number. This clashes with select2 because the first element under the disabled element will be invisible. Also even if the invisible issue did not exist making phone numbers clickable in a menu may be unwanted behavior.

To reproduce this issue do the following:

1 Visit the URL below using the EdgeHTML version of Edge. (Chromium-based version untested may or may not have the same issue)
https://jsbin.com/huminegapo/edit?html,js,output

2. Click on the generated menu on the output pane. The options starting with 1-800 should all be blue and underlined.

3. Hover your mouse over "1-800-0064-001"

4. You will notice that "1-800-0064-000" will be invisible.

One possible solution is to add:
```
<meta name="format-detection" content="telephone=no"/>
```
to pages using select2 as a child of the head tag.

Another option is to use the x-ms-format-detection attribute for impacted elements. The attribute is documented here: https://docs.microsoft.com/en-us/previous-versions/dn337007(v=vs.85)

The purpose of creating this issue is ask if select2 should be setting the x-ms-format-detection attribute on its elements when needed since Microsoft Edge does not normally recognize phone numbers in native select menus.

**Comment by kevin-brown** [comment]
As an official answer, the recommended solution is to set the `<meta>` tag since Select2 does not plan to set the unofficial attribute on elements.
