### ISSUE TITLE
Option allowClear dosen't work

### ISSUE THREAD

**Issue by pinocc01** [select2/select2#5725]
Options allowClear dosen't work if no placeholder set

**Comment by kevin-brown** [comment]
Yup, because `allowClear` resets it back to the placeholder value.

https://select2.org/selections#clearable-selections

There isn't much we can do to change that here.

**Comment by sabat24** [comment]
> There isn't much we can do to change that here.

Why not just check if placeholder exists and if not set empty value?

**Comment by goozak** [comment]
It works if you set an empty string for `placeholder`.
> `placeholder:''`

**Comment by sabat24** [comment]
I know that. My point is that a library should never throw an unexpected error.
In this case there should be an additional `if` statement which should check if user provide placeholder and set it as `''` if not. My post refers directly to "kevin-brown" answer that nothing can be done to solve such issues.

**Comment by usbhub** [comment]
I also ran into this bug and do not understand the reasoning to not fix as it seems like such a basic default behavior. Why would adding the ability to clear selections require a placeholder and silently fail if one is not provided? That is quite unintuitive, and it is very easy to fix, one would just have to replace [this](https://github.com/select2/select2/blob/181170f8a4d5c7eb4670ccd3926add33391b6b2d/src/js/select2/selection/allowClear.js#L50)
`this.$element.val(this.placeholder.id);`
with something like
```
let defaultVal = this.placeholder != null ? this.placeholder.id : "";
this.$element.val(defaultVal);
```

**Comment by jmalatia** [comment]
@kevin-brown Why can't something like @usbhub suggestion be implemented for those of us who do not use the `placeholder` option and instead rely on an already existing first option as a placeholder?

**Comment by diesl** [comment]
@kevin-brown I am also interested for the reason why you think "there isn't much we can do to change that here".
It seems like the proposed solution is quite easy to implement.
