### ISSUE TITLE
NOT AN ISSUE Multiple selector separated by comma data attr placeholder not rendering correctly

### ISSUE THREAD

**Issue by afsheen1** [select2/select2#5730]
Hello, 
this is not an ISSUE but maybe future feature.

html5 data* attr placeholder for element for multiple selector not rendering their own placeholder.

example:
`<select class="example_1" data-placeholder="example_1">
<select class="example_2" data-placeholder="example_2">
 `
active select2
`$(function() {
$('.example_1, example_2').select2();
});`

now both select box shows the first select box placeholder...

**Comment by kevin-brown** [comment]
If you're intending for the first select box's specific options to override those in the second, that's something that we can't/won't do (because they are separate boxes). If you're seeing this right now though, that's a bug and I'd love to see a jsbin which demonstrates that issue.
