### ISSUE TITLE
Destroy select2 component can throw: Uncaught TypeError: Cannot read property 'query' of null

### ISSUE THREAD

**Issue by RomanBurunkov** [select2/select2#5743]
Hi,

My usecase is dynamically create a select element and then I need to remove it from the page after it has been changed(user selected something or cleared selection) or user just click on another element.

For such case select2:close event suits pretty well.
But I'm getting the following error with latest chrome and latest select2 version: 4.0.12:

> Uncaught TypeError: Cannot read property 'query' of null
>     at d.<anonymous> (select2.full.min.js:2)
>     at d.e.invoke (select2.full.min.js:2)
>     at d.e.trigger (select2.full.min.js:2)
>     at d.trigger (select2.full.min.js:2)
>     at d.open (select2.full.min.js:2)
>     at d.toggleDropdown (select2.full.min.js:2)
>     at o.<anonymous> (select2.full.min.js:2)
>     at o.e.invoke (select2.full.min.js:2)
>     at o.e.trigger (select2.full.min.js:2)
>     at o.e._handleClear (select2.full.min.js:2)

It appears only when I'm trying to clear selection by clicking on the clear all icon.
I've created codepen snippet for this issue: https://codepen.io/romanburunkov/pen/gObjJRP

Steps to reproduce:

1. Create a select2 with the following options:
```
{
  minimumResultsForSearch: Infinity,
  placeholder: 'Select option...',
  allowClear: true
}
```

2. Select any option.
3. Click clear icon and an error will be showed in browser console. 

The workaround for this issue is to use 

`setTimeout(() => { destroySelect(); }, 0);`

But I think that it;s still the issue with a select2 component.

**Comment by kevin-brown** [comment]
You are trying to destroy Select2 in the middle of a Select2-initiated event cycle. The reason why setting a small delay fixes the issue is because that ensures the event cycle is completed.

I'm honestly not sure I feel like solving this issue, since it would require constantly checking that Select2 hasn't been destroyed mid-cycle.

**Comment by RomanBurunkov** [comment]
Hi @kevin-brown ,

Thanks for clarification.
I got what you mean but is it possible to trigger events like 'close' or 'open' after Select2-initiated event cycle done? Or probably create additional events: 'closed', 'opened' etc?
