### ISSUE TITLE
select2 maximized and pagination fails (stuck with loading)

### ISSUE THREAD

**Issue by nbelley** [select2/select2#5744]
I'm using select2 with maximized height and paginated ajax data. When the first page is loaded, when the select2 is resized, the «load more results» appear. And if the the scrollbar is removed because all the first page results are showed, its impossible to fix the state.

**Comment by kevin-brown** [comment]
I swear we fixed this in https://github.com/select2/select2/pull/5575.

---

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
