### ISSUE TITLE
Original select gets destroyed when reinitialize a cloned select

### ISSUE THREAD

**Issue by rubengc** [select2/select2#5745]
There is a strange issue I'm facing that I can't find the way to solve and to identify from where the issue could come

The steps to reproduce:

1) I have a form with a select element
2) Turns this select into a select2
3) The forms includes the ability to duplicate the entire form
4) When the forms get cloned I have a function to reinitialize the select2 element to make them work again (thourh using the` .select2('destroy').select();`
5) The cloned select2 work correctly and as expected
6) But, the strange things happens that the previous select2 (the original from the first form) gets destroyed

I was checking it in several ways and I can't find the issue, some of my checks and security workflows I tried to follow are:

1) I ensure to append the cloned element first, and before query it again through the jQuey selector
2) I tried to separate the destroy function from the reinitialization as this:
```
$cloned.select2('destroy');
$cloned.select2();
```
Instead of process everything in the same line:
```
$cloned.select2('destroy').select2();
```
3) Both functions (destroy and reinitialization) destroys the original element, I tried to run only one of the functions and both continues destroying the original one

So, Is possible there is some internal link between those elements that causes the destruction of the original one?

Thanks in advance for any help on this

**Comment by kevin-brown** [comment]
This has to do with you cloning the `<select>` element when Select2 is still initialized. Select2 holds a reference to the original element, so when you clone it Select2 doesn't realize there are 2 now. I would recommend destroying Select2 prior to cloning it.

If you call `select2()` on an element with Select2 already attached, it will re-initialize it.

I'm going to keep this open as it should be documented how to clone Select2.

**Comment by mrsoftware** [comment]
same issues.

**Comment by rubengc** [comment]
Found the solution

Issue comes that both selects has the same id attribute

Updating the cloned element id to another different solves the issue

Thanks for your help!
