### ISSUE TITLE
The container's scroll-bar auto-scrolling to bottom when it has focus.

### ISSUE THREAD

**Issue by cnxinan** [select2/select2#5747]
I have used select2 and need the scroll bar as below pic.
![image](https://user-images.githubusercontent.com/4035333/72675306-936edb80-3abc-11ea-84e4-140f90aba18d.png)

But found the scroll bar will auto-scrolling to bottom when I click it or open options. Debugging the source found the root cause is when container close/open/focus, the "search" will be focused.
![image](https://user-images.githubusercontent.com/4035333/72675358-6c64d980-3abd-11ea-93a6-6f6cfd02cc95.png)

My question is why the "search" should be focused automatic?

Select2 : 4.0.3
Jquery : 2.2.3
browser: Chrome Version 79.0.3945.130

Cheers.

**Comment by kevin-brown** [comment]
> Select2 : 4.0.3

I'm 99% sure we fixed this in a version that was released in the last 5 years.
