### ISSUE TITLE
Need a way to programmatically add a new tag

### ISSUE THREAD

**Issue by matpowel** [select2/select2#5748]
Feature request, I'm currently running Select2 4.0.6-rc.1

Quite simply, I've searched high and low and can't find a simple way to programmatically insert a new tag in a way that executes the createTag method and therefore appears just like any user created tag. The documentation at https://select2.org/tagging shows how to override createTag, which works great when a users types a new tag and allows me to highlight new tags a certain way and then scan for them before submitting a form.

The problem is that sometimes when I've loaded a page that previously had user tags created and I want to re-insert those tags and have them be obviously new tags rather than pre-selected database options. 

I've tried following best practice of adding new options and also triggering select events with the extra data attached per here: https://select2.org/programmatic-control/events#triggering-events, however all of these treat it as if I'm appending a new pre-existing option rather than creating a new tag.

I could be missing something, but based on a fairly extensive search it seems like a fairly obvious missing feature, similar to the data('search', term) method from 3.5.x or whatever it was?

**Comment by kevin-brown** [comment]
> I'm currently running Select2 4.0.6-rc.1

Update, please. Especially because that version has hidden bugs and is from 2017.

> The problem is that sometimes when I've loaded a page that previously had user tags created and I want to re-insert those tags and have them be obviously new tags rather than pre-selected database options.

I usually recommend marking the `<option>` itself in these cases, if you want to differentiate a pre-existing option from a pre-existing tag.

> however all of these treat it as if I'm appending a new pre-existing option rather than creating a new tag.

Any chance you can expand on this. What's the difference?

---

I think there might be a hidden bug here, so I'm not closing this off as a usage question.

**Comment by matpowel** [comment]
Thanks for the response @kevin-brown 

> Update, please. Especially because that version has hidden bugs and is from 2017.
Will work on that today.

> I usually recommend marking the <option> itself in these cases, if you want to differentiate a pre-existing option from a pre-existing tag.
Hmm, I _think_ this is actually how we semi-hacked around it. We ended up with the following code:
`$(function() {
  $("select[data-create-tag]").each(function() {
    var value = $(this).data('create-tag');
    var option = '<option value="'+value+'" data-select2-tag=true selected="selected">'+value+'</option>';
    $(this).append(option).trigger("change");
  })
})`
And to make it all work together, createTag calls this method:
`_createItem = function(params) {
  var term = $.trim(params.term);
  if (term === '') {
    return null;
  }
  return {
    id: term,
    text: term,
    newTag: true // add additional parameters
  }
};`
And then templateResult and templateSelected both call this function:
`_formatItem = function(item) {
  if (item.newTag || (
       item.element &&
       item.element.attributes &&
       item.element.attributes["data-select2-tag"] &&
       item.element.attributes["data-select2-tag"].nodeValue == "true"
     ))
    return $('<span class="new-item-tag">'+item.text+'</span>');
  else
    return item.text;
};`

I think it would be so much cleaner to have a method we can call, something like: $x.select2('createTag', 'new tag') which mimicked the user typing "new tag" into the input (so it would go through the chain and trigger the createTag function. That way all the messing around with the option element and testing for it in the formatter function wouldn't be needed.

> Any chance you can expand on this. What's the difference?
Sorry I probably didn't word this very well, by "pre-existing option" I meant the list of options loaded into the select (non tags). Everything you can find on the inter webs as an example just shows how to add a new option, not a new tag.

**Comment by sonichandni** [comment]
you can try this one:

**Comment by matpowel** [comment]
This adds an option to the select but doesn't add it as a tag, doesn't call the createTag callback etc that adding a new tag manually would normally do. The goal is to be able to identify which options have been created as a new tag so we can highlight them differently and warn the user they're adding a new tag. My solution above solves it, but it's a painful solution for anyone else starting from scratch.
