### ISSUE TITLE
How to preselect value when using ajax

### ISSUE THREAD

**Issue by ccssmania** [select2/select2#5749]
Hello, first thank you for your great work,
When I validate the form fields in the controller it goes back when some error appears and I can fill the fields with the old values and show the error, but using select2 I cannot use this old value.

```
        $('#selectCities').select2({
		placeholder: "Seleccionar una ciudad",
		ajax: {
			url : '/getCities',
			processResults: function(data){
				return{
					results : data
				}
			}
		}
	});
```

**Comment by felipe7229** [comment]
See below example in official website

// Set up the Select2 control
$('#mySelect2').select2({
    ajax: {
        url: '/api/students'
    }
});

// Fetch the preselected item, and add to the control
var studentSelect = $('#mySelect2');
$.ajax({
    type: 'GET',
    url: '/api/students/s/' + studentId
}).then(function (data) {
    // create the option and append to Select2
    var option = new Option(data.full_name, data.id, true, true);
    studentSelect.append(option).trigger('change');

    // manually trigger the `select2:select` event
    studentSelect.trigger({
        type: 'select2:select',
        params: {
            data: data
        }
    });
});
