### ISSUE TITLE
Add regex validation before making the ajax request

### ISSUE THREAD

**Issue by niloy369** [select2/select2#5756]
Hi all,

I'm in need of a feature that will search for users using their email using ajax request. But I can make the request if the input format is valid. So is there any way that i can make the request to server after validating the input using a regex. If the input is not a valid email format then the web request will not happen.

**Comment by kevin-brown** [comment]
Your best bet is to define a custom AJAX transport and do the filtering before that.

https://select2.org/data-sources/ajax#alternative-transport-methods

You would need to trigger an error response (or a custom response that's processed by your templating) if you don't want to trigger the request for whatever reason.
