### ISSUE TITLE
IE11: Invalid required multiselect never gets valid again

### ISSUE THREAD

**Issue by jbollacke** [select2/select2#5757]
Example: https://output.jsbin.com/giyozanuge/1

Steps to reproduce:
1. Open example in Internet Explorer 11
2. Press Send to submit form -> focus changes to select box
3. Select a value
4. Press Send again -> form is **not** submitted and focus changes to select box again

Should just submit the form after step 4.

**Comment by jbollacke** [comment]
#5544 #5114 seem to be related

**Comment by kevin-brown** [comment]
Reopening #5114 and merging this ticket into it.
