### ISSUE TITLE
Search casing problem on TR characters

### ISSUE THREAD

**Issue by emregulerr** [select2/select2#5760]
Hello,

I can explain the problem with an example: 
When there is an option named "İzmir" that contains "İ" (the uppercase "i" in TR lang) , if I wrote "i" for search, it doesn't match. Also the same result for inverse of example.

**Comment by kevin-brown** [comment]
This is a feature and not a bug.

https://select2.org/i18n#transliteration-support-diacritics

You should be able to disable it by creating your own custom `matcher` function which does not strip out the diacritics.

**Comment by kevin-brown** [comment]
I'm marking this as a documentation ticket because we could benefit from making it more clear how to disable this behavior and maybe make it easier to override how Select2 strips diacritics.

**Comment by emregulerr** [comment]
First of all, thanks for your attention.
I get overed the problem myself. The code is below for anyone who needs.

`function modelMatcher(params, data) {
            var c, child, matches, match, original, term;
            data.parentText = data.parentText || "";

            // Always return the object if there is nothing to compare
            if ($.trim(params.term) === '') {
                return data;
            }

            // Do a recursive check for options with children
            if (data.children && data.children.length > 0) {
                // Clone the data object if there are children
                // This is required as we modify the object to remove any non-matches
                match = $.extend(true, {}, data);

                // Check each child of the option
                for (c = data.children.length - 1; c >= 0; c--) {
                    child = data.children[c];
                    child.parentText = data.parentText + " " + data.text;

                    matches = modelMatcher(params, child);

                    // If there wasn't a match, remove the object in the array
                    if (matches == null) {
                        match.children.splice(c, 1);
                    }
                }

                // If any children matched, return the new object
                if (match.children.length > 0) {
                    return match;
                }

                // If there were no matching children, check just the plain object
                return modelMatcher(params, match);
            }

            // If the typed-in term matches the text of this term, or the text from any
            // parent term, then it's a match.
            original = (data.parentText + ' ' + data.text).replace("İ", "i").toUpperCase();
            term = params.term.replace("İ", "i").toUpperCase();

            // Check if the text contains the term
            if (original.indexOf(term) > -1) {
                return data;
            }

            // If it doesn't contain the term, don't return anything
            return null;
        }`

Just add `matcher: modelMatcher` option to your select2 with the function above.

**Comment by iwasherefirst2** [comment]
> When there is an option named "İzmir" that contains "İ" (the uppercase "i" in TR lang) , if I wrote "i" for search, it doesn't match.

I cannot reproduce this. If I have an option named "İzmir" and if I search for "izmir" then it does match:
![image](https://user-images.githubusercontent.com/1765602/76778288-da6e0a00-67a9-11ea-8615-4206abc6e223.png)
