### ISSUE TITLE
On Bootstrap 4 on modal programmatic select2("open") is broken

### ISSUE THREAD

**Issue by LocalHeroPro** [select2/select2#5763]
I used Bootstrap 4 with Select2 with select2-bootstrap4-theme.

The issue is showing smal input in top left browser window.

Issue occur when I try programmatically open dropdown on showed modal.
To open dropdown I used:
```javascript
$('#selector').select2('open');
```
on:
```html
<div class="input-group">
    <select class="custom-select" id="selectCategory" name="category_id" required>
            <option value="{{ $item->id }}">{{ $item->name }}</option>
    </select>
    <div class="input-group-append" data-toggle="tooltip" data-placement="top" title="...">
        <span class="input-group-text"><i class="fas fa-question"></i></span>
    </div>
</div>
```

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by LocalHeroPro** [comment]
1. As mentioned: programmatic open dropdown with: `$('#selector').select2('open');`\
2. As mentioned: when programmaticly openned dropdown are showing unknown input in top left window corner. Expected outcome: absence of bug.
3. Tested with: Chrome, Chromium, Opera, FireFox. OS: Centos 7.
4. Yes.
5. Only with first method: https://select2.org/programmatic-control/methods
6. jQuery 3.4.1., Select2 4.0.13.
7.As mentioned: with select2-bootstrap4-theme
