### ISSUE TITLE
[DOCS] placeholders page has W3C-invalid markup in example

### ISSUE THREAD

**Issue by Tilogorn** [select2/select2#5764]
As you can see on https://select2.org/placeholders, `<option></option>` is suggested as single select placeholder.

According to W3C `<option></option>` is no valid html. See a few examples:

```
<option></option>
Element “option” without attribute “label” must not be empty.

<option value=""></option>
Element “option” without attribute “label” must not be empty.

<option label="foo"></option>
Document is valid

<option value="">Foo</option> <!-- overwrites select2 placeholder config, is visible -->
Document is valid
```

As this depends on an external tool ([W3C Validator](https://validator.w3.org/)) and the placeholder doc page has too many other errors (see [W3C report](https://validator.w3.org/nu/?doc=https%3A%2F%2Fselect2.org%2Fplaceholders)) and I have currently no access to a public accessible web server, I can not present a live visualization of the problem.

**Comment by kevin-brown** [comment]
Considering the W3C validator is saying that there are multiple `<head>` and `<body>` tags (there aren't), I honestly can't trust it to be accurate.

With that being said, the error in the title is accurate: https://stackoverflow.com/a/31800584/359284

But considering how prevalent this is, I really don't feel like fixing this in the documentation. In theory we can just set placeholder text here and there shouldn't be any issues. If someone wants to fix this in the documentation, feel free to submit a pull request.

**Comment by Tilogorn** [comment]
The W3C validator is a very powerful tool. I have been teached to use it in my computer science studies. If you remove the completely out of place `<select>...</select>` in the `<head>` of the page, it works. Thats maybe so out-of-specification that they didn't considered it in their validation.

I just uploaded your site source via "text input", removed the `<select>` in the `<head>` and filtered out warnings in the output. This is the result:

![Bildschirmfoto vom 2020-02-05 08-52-54](https://user-images.githubusercontent.com/7524854/73821829-14d0a880-47f5-11ea-9673-701623c0a197.png)

As you can see, the validator is pretty helpful, as it detected two closing `</p>` tags in series beside the issue mentioned here.

But anyway, thanks for your suggestion. I just wasn't sure if and how extending the suggested `<option></option>` with value/label/text affects the internal placeholder handling of select2.
