### ISSUE TITLE
Multiple select2 selects in separate modals on the same page, only last one works.

### ISSUE THREAD

**Issue by kehollin** [select2/select2#5767]
Using select2 version 4.0.15, Bootstrap 4.3.1 and the latest jQuery. Testing in Chrome (Mac Mojave and Windows 10)

I have a page for researcher profiles that contains sections for their projects, papers and other work. Each of these sections allows the user to add a new item by selecting it from a dropdown that's contained in a Bootstrap modal popup, one popup per section. I'm trying to apply select2 to all of these popups, but only the last call to select2() works. I'm using the dropdownParent as required, with the parent being a jquery selector by ID for the modal, and the selector for the select element is a compound selector for the select element within the modal.  I've verified that the selectors do indeed yield the desired elements.

JSBin Snapshot: [https://jsbin.com/vaqovaf/9/edit?html,css,js,output](https://jsbin.com/vaqovaf/9/edit?html,css,js,output)

In the JSBin simply click on the "+" buttons and you'll see the popups. You can verify only the last registered select works by switching the order of the calls in the JavaScript pane.

I've searched issues and looked at those listed below this box as I type, and do not see anything relevant.

**Comment by kevin-brown** [comment]
This issue is caused by the same ID being used for multiple Select2 elements. Select2 expects that IDs are unique, because per the HTML spec they are supposed to be, so it ends up destroying any other elements that exist with the same ID will be destroyed. This is expected behavior and the solution is to not reuse IDs on the same page.

**Comment by kamleshwebtech** [comment]
> This issue is caused by the same ID being used for multiple Select2 elements. Select2 expects that IDs are unique, because per the HTML spec they are supposed to be, so it ends up destroying any other elements that exist with the same ID will be destroyed. This is expected behavior and the solution is to not reuse IDs on the same page.

Thank you very much @kevin-brown , your suggestion solved my issue :) :)
