### ISSUE TITLE
4.0.13 not on cdnjs

### ISSUE THREAD

**Issue by jonahgreenthal** [select2/select2#5768]
Version 4.0.13 does not appear on https://cdnjs.com/libraries/select2 . Do we have any idea why or when it will appear?

Thanks!

**Comment by kevin-brown** [comment]
Yeah, cdnjs is a mess which is why we now recommend using jsdelivr. It took them months to get recent versions online, while jsdelivr gets them online within minutes.

Raise a ticket over at cdnjs and I'm sure they will manually pull in the new versions again.
