### ISSUE TITLE
Nuget install creates ~/content/css directory, conflicts with default css bundle

### ISSUE THREAD

**Issue by kehollin** [select2/select2#5770]
Not sure a mock-up would help you here. The Visual Studio MVC5 website template creates a default bundle for css that it accesses with the URL ~/content/css, but when the Nuget package for select2 is installed it puts its own css in a directory with the same path. 

The suckiest thing about this is that it doesn't show up in dev because the css bundle is well cached, so it's only after deployment, and when users caches start timing out.

**Comment by kevin-brown** [comment]
Unfortunately we do not officially maintain the NuGet package for Select2.

https://www.nuget.org/packages/Select2.js/

@splattne may be able to speak more to this, since they appear to be the current owner of the NuGet package.
