### ISSUE TITLE
Document the right way to trigger a selection with a data object

### ISSUE THREAD

**Issue by dbarreraHS** [select2/select2#5772]
select2:select trigger won't correctly pass the data to a select2 component.

Here is a code snippet:

```
$(document).ready(function() {
  $('#cboPractitioner').select2({
    width: '100%',
    placeholder: 'Select user(s)',
    cache: true
  });

  $('#cboPractitioner').on('select2:select', function(e) {
    if (e) {
      var args = JSON.stringify(e.params, function (key, value) {
        if (value && value.nodeName) return "[DOM node]";
        if (value instanceof $.Event) return "[$.Event]";

        return value;
      });
      console.log(args);
    }
  });

  var data = {
    id: "1134596828",
    text: "",
    npi_type: 1,
    replacement_npi: null,
    first_name: "Jane",
    middle_name: "",
    last_name: "Doe",
    prefix: "",
    suffix: "",
    credential: "PA-C"
  };

  var cboPractitioner = $('#cboPractitioner');

  var option = new Option('', data.id, true, true);
  cboPractitioner.append(option).trigger('change');

  cboPractitioner.trigger({
    type: 'select2:select',
    params: {
      data: data
    }
  });

  var currentData = $('#cboPractitioner').select2('data');

  console.log(currentData);
});
```
Attaching another handler `$('#cboPractitioner').on('select2:select', function(e) {})` does print the data pass in the 'select2:select' trigger.

```
{"data":{"id":"1134596828","text":"","npi_type":1,"replacement_npi":null,"first_name":"Jane","middle_name":"","last_name":"Doe","prefix":"","suffix":"","credential":"PA-C"}}
```
But when I get the data from a select2 component it doesn't properly apply the data that I pass in.

```
var currentData = $('#cboPractitioner').select2('data');
console.log(currentData);
```
Data looks like this:

```
selected: true
disabled: false
text: ""
id: "1134596828"
title: ""
_resultId: "select2-cboPractitioner-result-i3hv-1134596828"
```
This problem also happens when I setup the option for `templateSelection`, I need to display different format in the multi select box and I get missing properties in the parameter.

**Comment by harawata** [comment]
It would be a nice if this worked as documented.
The same issue has been reported twice at least.
#5275  #5449

**Comment by kevin-brown** [comment]
This is honestly a documentation problem more than anything, since it does not work at all the way it is documented (and it's not possible for it to). We need to expose and document and actual way to trigger this event through the internal Select2 event system, which is independent from the jQuery event system.

**Comment by OJMichael** [comment]
It would be ideal if an API could be exposed where you could do something simple like:

```javascript
const option = new Option(text, id, true, true);
$.fn.select2.setData(option, data);
selectInput.append(option).trigger('change');
```
