### ISSUE TITLE
Cursor position for RTL text between browsers

### ISSUE THREAD

**Issue by cimfalab** [select2/select2#5773]
I'm using select2 with 'rtl' direction.
But the cursor position for input text is weird between browsers.

You can simply check it here: https://select2.org/i18n#rtl-support
When I input a -> b -> c,

(In Firefox - expected)
a| -> ab| -> abc|

(In Chrome)
|a -> |ab -> |abc

Is it the issue of Chrome or the implementation/style of select2?

**Comment by kevin-brown** [comment]
> Is it the issue of Chrome or the implementation/style of select2?

This is a Chrome issue. We don't customize the cursor position at all, we just defer to the browser to handle rendering the search box.
