### ISSUE TITLE
change "x" icon in clearable section

### ISSUE THREAD

**Issue by imunisasi** [select2/select2#5777]
Is there any option to change "x" for clear selection
since i used non regular font, select2 "x" showing nothing
thanks

for now i do it like this :
```
$('.select2').on('select2:select', function (e) {
  $('.select2-selection__choice__remove').html('x');
});

```

**Comment by kevin-brown** [comment]
Unfortunately no. And given the complexity around keeping things accessible, we probably aren't going to implement this.

**Comment by JoseMariadosSantosMachado** [comment]
Edit select2.js
find `<span class="select2-selection__clear" title="'+n()+'">&times;</span>` 
change to: `<span class="select2-selection__clear" title="'+n()+'"><span class="btn btn-xs"><i class="fa fa-times"></i></span></span>;`
