### ISSUE TITLE
Display search box only if the list has 10 items or more ?

### ISSUE THREAD

**Issue by mcunha98** [select2/select2#5779]
It is possible to create a option to show the search only in cases where the select has 10 or more items (for example), because doesn't make sense show a search box for 3 items .

![](https://i.postimg.cc/Zn7rCzsr/screenshot-142.png)

I saw replys about set a property to negative number, but it hide the search box without check the number of items on list

**Comment by kevin-brown** [comment]
https://select2.org/searching#limiting-display-of-the-search-box-to-large-result-sets

"Select2 minimum results for search"

That same option that you can set to Infinity to hide the search box permanently, you can also set to a reasonable number to only hide the search box for small numbers of options.
