### ISSUE TITLE
Cannot copy value from select2 editor

### ISSUE THREAD

**Issue by godshades** [select2/select2#5780]
Hi, I'm using handsontable 6.2.2 with custom config select2
everything work OK, but when I select cell use " editor: 'select2' " I can't copy paste this cell value
does anybody have same problem

**Comment by kevin-brown** [comment]
This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

[ml]: https://select2.org/troubleshooting/getting-help
