### ISSUE TITLE
select2('open') not working after add a new optgroup

### ISSUE THREAD

**Issue by rubengc** [select2/select2#5789]
Hi there

I'm facing a really strange issue with the select2('open') function

There is my scenario:
1) I have a select with `optgroups` (with options inside) that I turned into a `select2`
2) I have a **button** that on get clicked I call to the` select2('open')`
3) Based on user actions, some **optgroups get added** (using the `.append()` jQuery function) or **removed** (using the` .remove()` jQuery function) to the select element

When I remove optgroups, everything works correctly , I can open the select2 from my button that has the select2('open') function without any issue

The issue comes when I add a new optgroup, I can't open the select2 from my button, but, I can open it clicking directly to the select2 element

There could be a bug on the select2('open') function?

Important note, optgroups has the `data-id` attribute, can this attribute enter in conflict with select2?

Thanks in advance

**Comment by kevin-brown** [comment]
We definitely need a jsbin that reproduces this issue.
