### ISSUE TITLE
first option not selected

### ISSUE THREAD

**Issue by vaishnavhiren1993** [select2/select2#5797]
![image](https://user-images.githubusercontent.com/11805630/76623154-f3cc4780-6558-11ea-8651-2b6a52ec3ea4.png)

**ISSUE:**
In multiple select2 options 
after disable a first options is not able to select

**Solution**
Edit in select2.full.min.js 
Search for "i.prototype.setClasses = function()" function
add one line code
" i.prototype.setClasses = function() { var t = this; this.data.current(function(e) { var i = h.map(e, function(e) { return e.id.toString() });  t.$results.find(".select2-results__option[aria-selected]").each(function() { var e = h(this)  , t = f.GetData(this, "data")  , n = "" + t.id; null != t.element && t.element.selected || null == t.element && -2 < h.inArray(n, i) ? e.attr("aria-selected", "true") : e.attr("aria-selected", "false");  **if (t.id == -1) { e.attr("aria-selected", "true")  }** }) })  }"

highlited is added.

Now you can  use is disable and unselecteble
<option value="-1">Please select</option>

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
