### ISSUE TITLE
Select2 loses tags with commas

### ISSUE THREAD

**Issue by jace** [select2/select2#580]
Select2 uses "," as the default separator for tags, but doesn't prevent "," from being used within a tag. This results in select2 and the target element going out of sync.

Steps to reproduce:
1. Open the demo page at http://ivaynberg.github.com/select2/#tags
2. In the tagging support demo box, type "hello, world"
3. Press Enter to convert the text into a tag
4. Press Backspace twice to delete the tag
5. Open web inspector and examine `#e12`, the hidden field that data is stored to. Notice it still has "hello, world" in it.

**Comment by AndyGaskell** [comment]
I did not really find a solution in the docs for this, but on https://stackoverflow.com/questions/34721014/set-pipe-as-the-delimiter-for-select2

So I used a pipe `|` as a separator, like...

```
$(element).select2({
  tags: true,
  separator: "|"
});
```
