### ISSUE TITLE
Select2 inside long modal with scrolling - won`t scroll when input is focused

### ISSUE THREAD

**Issue by rbloone** [select2/select2#5800]
Using Select2 plugin inside position: fixed modal (Bootstrap, for example) causes annoying Bug with scrolling long modals. When Select2 input is focused page can`t be scrolled, it looks like select2 is preventing scrolling somehow. Check the fiddle: 
http://jsfiddle.net/khac91n8/5/

Up to date Chrome 80, 4.0.13 Select2.

The main problem is on mobile: you can`t scroll the window with an active keyboard to see a dropdown content

**Comment by kevin-brown** [comment]
This unfortunately is a feature, not a bug.

See https://github.com/select2/select2/commit/003d6053a9fff587c688008397e7d5824463fe99 and https://github.com/select2/select2/issues/2975 for why we do this in modals.

**Comment by KodyKendall** [comment]
Is there anything that can be done about this? It's super annoying for users on mobile devices.

**Comment by temo-o** [comment]
For mobile devices, I use this:

`document.addEventListener('touchmove', function(e) {
  $("#select2_element").select2("close");
}, false);`

You can simulate similar behavior on mouse clickStart and just close the select2
