### ISSUE TITLE
Transliteration support does not work for cyrillic alphabet?

### ISSUE THREAD

**Issue by iwasherefirst2** [select2/select2#5802]
Hi,

I am using select2 version 4.0.13 on Firefox Ubuntu.

It seems that the [transliteration support](https://select2.org/i18n#transliteration-support-diacritics) does not work for cyrillic alphabet.

For example, Никита are the cyrillic letters for Nikita (see https://de.wikipedia.org/wiki/Kyrillisches_Alphabet#/media/Datei:Cyrillicalphabet.jpg).

However, searching for **Nikita** will not match **Никита**, see this [jsfiddle](https://jsfiddle.net/Elenktik/rkt3y01L/2/).

**Comment by kevin-brown** [comment]
We maintain a giant list of supported transliterations within the repository. It's a giant JSON-like map and we would entertain pull requests that continue to enhance it.
