### ISSUE TITLE
Multiple select2 (array) submits the only ones that has values

### ISSUE THREAD

**Issue by vousys** [select2/select2#5803]
Version:  https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.min.js
Guys I'm having an issue:

If you have multiple select with the same name, ex:

```
<div>
  <p>
    DEMO 1
  </p>  
  <select name="cmb_demo[]" id="cmb_demo_1">
      <option value="1">OPT 1</option>
      <option value="2">OPT 2</option>
      <option value="3" selected>OPT 3</option>
      <option value="4">OPT 4</option>
  </select>

  <p>
    DEMO 2
  </p>  
  <select name="cmb_demo[]" id="cmb_demo_2">
      <option value="1">OPT 1</option>
      <option value="2">OPT 2</option>
      <option value="3">OPT 3</option>
      <option value="4">OPT 4</option>
  </select>

  <p>
    DEMO 3
  </p>  
  <select name="cmb_demo[]" id="cmb_demo_3">
      <option value="1">OPT 1</option>
      <option value="2">OPT 2</option>
      <option value="3" >OPT 3</option>
      <option value="4">OPT 4</option>
  </select>
</div>

```
And you submit the form, in the POST received you only get the select2 with values insted of returning the array (with the positions) of the inputs

Instead of receiving this
```
[cmb_demo] => Array
        (
            [0] => 
            [1] => 10999
            [2] => 
            [3] => 
        )
```
You get this
```
[cmb_demo] => Array
        (
            [0] => 10999
          )
```

**Comment by kevin-brown** [comment]
Your example should always send the values because you don't have a placeholder option.

This sounds like an issue with your backend server not properly receiving the empty values from the placeholder options. Select2 behaves the same way as a normal select when it is sending the form data along, so there isn't anything that Select2 is doing to break this for you.
