### ISSUE TITLE
Control won't resize if browser window is resized after rendering.

### ISSUE THREAD

**Issue by giovani-luigi** [select2/select2#5809]
The control won't resize if you use it inside any responsive layout and then resize the browser's window.

Steps to reproduce:
1. Maximize your browser (Firefox/Chrome) window
2. open the page: https://select2.org/dropdown
3. "Restore" the browser window and resize it
4. The dropdown will remain with its width as when the page was initially loaded.

![dropdown](https://user-images.githubusercontent.com/25188251/77255612-7f279600-6c47-11ea-923f-5fa1f775bddd.jpg)

**Comment by Ahmaddahshan** [comment]
I had this issue before, I added my own CSS to fix this issue. 

Here is my HTML code:
<div id="searchDropdown">
     <label `for="hsSchoolName">Search` School Name *</label>
     <select id="hsSchoolName" name="hsSchoolName">
            <option value="">-- Select --</option>
      </select>
</div>

Here is my CSS code:
#dropdownSearch {
    width: 100%;
    margin: 0 auto 20px auto;
}
.select2 { 
    width: 100% !important;
    height: 40px !important;
    overflow: hidden !important; 
}

<img width="770" alt="Screen Shot 2020-03-22 at 7 50 52 PM" src="https://user-images.githubusercontent.com/25114395/77269309-74d0c080-6c76-11ea-891c-58eed1e03384.png">

**Comment by Ahmaddahshan** [comment]
I had this issue before, I added my own CSS code to fix this issue. 

Here is my CSS code:
#dropdownSearch {
    width: 100%;
    margin: 0 auto 20px auto;
}
.select2 { 
    width: 100% !important;
    height: 40px !important;
    overflow: hidden !important; 
}

<img width="770" alt="Screen Shot 2020-03-22 at 7 50 52 PM" src="https://user-images.githubusercontent.com/25114395/77269516-16581200-6c77-11ea-9ac9-40b9fa022e90.png">

**Comment by Ahmaddahshan** [comment]
I had this issue before, I added my own CSS to fix this issue.

Here is my CSS code:
#searchDropdown{
    width: 100%;
    margin: 0 auto 20px auto;
}
.select2 { 
    width: 100% !important;
    height: 40px !important;
    overflow: hidden !important; 
}

<img width="770" alt="Screen Shot 2020-03-22 at 7 50 52 PM" src="https://user-images.githubusercontent.com/25114395/77269603-59b28080-6c77-11ea-9691-ac301c548454.png">

**Comment by kerog** [comment]
try add this
```
$('#select').select2({
width: auto
});
```

**Comment by kevin-brown** [comment]
Select2 will calculate the dimensions on page load to match the original select. It is not able to dynamically detect every case when the width is dynamic, so we expose a few options to control how the width is calculated.

https://select2.org/appearance#container-width

A few of the methods handle percentages, which it sounds like is what you're going for.
