### ISSUE TITLE
Website down.

### ISSUE THREAD

**Issue by TorreyGarland** [select2/select2#5813]
select2.org is down

**Comment by csandreas1** [comment]
Hopefully, it will come back soon

**Comment by Porthorian** [comment]
yep getting cloudflare errors

**Comment by kevin-brown** [comment]
We are aware that the website is down. The server which hosts the Select2 documentation had maintenance done on it early yesterday and that appears to have taken down the Select2 website.

We are working to bring it back online.

**Comment by csandreas1** [comment]
Since you guys are using WordPress, go ahaid and install [wp-fastest-cache](https://wordpress.org/plugins/wp-fastest-cache/). It will make the website super fast and trust me it's super easy to setup.

**Comment by kevin-brown** [comment]
> Since you guys are using WordPress

We aren't using WordPress. Awkward.

----

The Select2 docs are heavily cached and are behind Cloudflare, that's why the docs are still shown right now event though the docs server is down. We're still working to get it back online.

**Comment by csandreas1** [comment]
Oh okay my bad. What you are using? html only?

**Comment by kevin-brown** [comment]
Fairly certain it's back up now. Going to leave this open for a little while we figure out why the cache didn't kick in right away.
