### ISSUE TITLE
Update for API docs

### ISSUE THREAD

**Issue by flip111** [select2/select2#5816]
The API documentation at http://select2.github.io/select2/ scroll down to "Documentation" is a great page to get an overview of the API. Could it be updated to the latest select2 version?

**Comment by flip111** [comment]
I had trouble to access the documentation before. Now i see some parts are there. It's not as complete as the select 3 docs though.

https://select2.org/configuration/options-api has options where type, default and description are not given

https://select2.org/programmatic-control/events doesn't specify which values are passed to the callback

**Comment by flip111** [comment]
functions to call on select2 spread out over more pages

https://select2.org/programmatic-control/methods

https://select2.org/programmatic-control/retrieving-selections

**Comment by kevin-brown** [comment]
The first link you provided is for Select2 2.5.x, which isn't supported and that link will be removed from the main docs site with time.

The second link you provided is the link to all of the supported options for Select2.

https://select2.org/configuration/options-api

That should be considered up to date. If you find an option not documented there, it should not be treated as public API and thus is not subject to deprecation patterns.

**Comment by flip111** [comment]
> Because Select2 has a giant API scope, it does not make sense to condense it down into a single page.

I respectfully disagree. I don't see the value of scattering API docs through other types of documentation out over several pages.

Writing bindings to select2 is very difficult this way, the select2 v3 docs were much better for this.
