### ISSUE TITLE
How to use with a form validator?

### ISSUE THREAD

**Issue by wheaties** [select2/select2#584]
If there's a forum for select2 I appologize in advance for not posting this here. However, when using the basic jquery.validation library, I can not "focus" on the various drop downs that select2 has chosen to rerender. How would you suggest working with a form validator? Is there a library that works cleaner with select2?

error: "An invalid form control with name='tags' is not focusable. "

**Comment by chrisjacob** [comment]
Here's an idea worth trying out (from the Chosen): https://github.com/harvesthq/chosen/issues/515#issuecomment-33214050

**Comment by chrisjacob** [comment]
@shtumi @ivaynberg @kevin-brown I've applied the fix to @stephanvierkant's fiddle: http://jsfiddle.net/q7kxsf17/10/

I had to wrap the select in a container div with the following styles.

```css
.select2-wrapper {
    display: inline-block;
    position: relative;
}
```

I also added ```bottom: 0; left: 0;``` to the Chosen fix... this lines up the hidden select with the bottom of the select2.

```javascript
.attr('style','display:block; position:absolute; bottom: 0; left: 0; clip:rect(0,0,0,0);');
```

Also note, you need to apply the ```.attr()``` styles to the original select AFTER the select2 call i.e. ```$('select').select2()attr()```.

**Comment by chimos** [comment]
chrisjacob's previous post worked great for me. Tab-navigation works also as expected. Thanks!
