### ISSUE TITLE
selectionCssClass in 4.1.0 beta

### ISSUE THREAD

**Issue by timkirtley** [select2/select2#5843]
So from what I can see in the Changelog, I should just update my previous code from using `containerCssClass` to `selectionCssClass` ?   Because I'm not getting any additional classes added anywhere using `select2.full.js 4.1.0-beta.0`

`dropdownCssClass` still works correctly, but have I misunderstood the new option or is there something not right with it in the current beta?

**Comment by petrinecp** [comment]
Same behavior, the `selectionCssClass` doesn't work for me either.

**Comment by kevin-brown** [comment]
Whoops, I can see in the code that the way the defaults are applied was never updated. Strangely if you use both options it works, but that's a side effect of the change not being fully made.

We'll get this fixed for the next beta release.
