### ISSUE TITLE
Blank Space when opening search2 js dropdown

### ISSUE THREAD

**Issue by gatenzteam** [select2/select2#5845]
Please help me to fix this problem, when I open the dropdown the page will have more blank space and when I close it the page will return to normal

when thee dropdown is open it will appear
![Screenshot_103](https://user-images.githubusercontent.com/59316866/80513084-1ef7e280-89b1-11ea-82f7-a02294315f6a.png)

then I close it
![Screenshot_104](https://user-images.githubusercontent.com/59316866/80513128-2dde9500-89b1-11ea-8b27-ea42f1734f47.png)

I already adding overflow-x: hidden; in body {} but its just work in desktop mode, when I test in my phone or mobile view the problem will appear as above

**Comment by gatenzteam** [comment]
this when i open the web in desktop mode
![Screenshot_105](https://user-images.githubusercontent.com/59316866/80513327-7b5b0200-89b1-11ea-8588-975d6a1ad1fb.png)

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by gatenzteam** [comment]
Q : What steps can be used to reproduce the issue?
A : I'm already add overflow-x : hidden; to body but its just solved on desktop version

Q : What is the bug and what is the expected outcome?
A : the bug is that when making select2 the form will have a web page overflow-x and there will be more space than my website wrapper, and my real goal is to remove the overflox-x and unwanted space like the first picture above

Q : What browser(s) and Operating System have you tested with?
A : Firefox Mobile, Chrome Mobile device is android

Q : Does the bug happen consistently across all tested browsers?
A : yep

Q : Can you reproduce this issue on any of the examples in the docs?
A : I cant because this still in localhost and I'm don't have web hosting

Q : What version of jQuery are you using? And what version of Select2?
A : 
Select 2 JS https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js
Jquery https://www.gatenz-panel.com/assets/js/vendors/jquery-3.2.1.min.js

Q : Are you using Select2 with other plugins?
A : Morris Chart, Datatables

**Comment by gatenzteam** [comment]
![Screenshot_115](https://user-images.githubusercontent.com/59316866/80791983-d9603300-8bc5-11ea-9ff9-60e01933b3ce.png)

![Screenshot_114](https://user-images.githubusercontent.com/59316866/80792001-e846e580-8bc5-11ea-9e68-164991f525e9.png)

**Comment by gatenzteam** [comment]
![Screenshot_116](https://user-images.githubusercontent.com/59316866/80792817-09a8d100-8bc8-11ea-97bd-9d91631e0cf8.png)

**Comment by kevin-brown** [comment]
It looks like a lot of this shouldn't be influenced much by the plugins that you have installed on the page. It might be influenced by the styling, but that's really tough to tell without being able to see.

Are you able to reproduce this issue in a jsbin or jsfiddle?
