### ISSUE TITLE
Bug: Customizing how results are matched not working with jquery 3.5.0

### ISSUE THREAD

**Issue by Daijobou** [select2/select2#5851]
https://select2.org/searching#customizing-how-results-are-matched

Line `if ($.trim(params.term) === '') {` is not working, because $.trim() is removed in jquery 3.5.0
https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

> Deprecations
It wouldn’t be a jQuery release without some deprecations. In jQuery 3.5.0, we’ve put jQuery.trim on the list. JavaScript’s own String.prototype.trim() is an easy replacement for it.

Unfortunately $.trim() does much more than String.prototype.trim(). It checks for empty objects and can work with arrays. 

Its now needed to check `params.term` is not undefined, when using `if (params.term.trim() === '')`

**Comment by kevin-brown** [comment]
I'm fairly certain this issue in fixed in the beta releases of 4.1.0, now that we are bumping up our browser support version and can actually rely on the trim method existing on strings.
