### ISSUE TITLE
Documentation improvement: add a working example of createTag

### ISSUE THREAD

**Issue by viktorsmari** [select2/select2#5852]
This is a **feature request** for a minor documentation improvement on the `createTag`

A common use case is to create a new item via AJAX, and then add it to a list. I was not able to do this after hours of research in the docs, issues and the forum.

### Problem
It looks like the documentation is a bit short on how to use the `createTag`.
* There is confusion on why the `createTag` fires on every keypress, and not when the tag is created.
* Related discussion
   * https://forums.select2.org/t/createtag-fires-before-tag-is-selected/159
   * https://forums.select2.org/t/create-new-tags/942
* Do we also have to add `.on("select2:selecting")` to check if it was a newTag or an old tag and then decide if it should be created via Ajax? If it is always needed, should it be in the docs?
* Should there perhaps be another function for creating new tags?

I have been using a mixture of Select2 and Selectize.js and I would like to stop using Selectize.js -The only reason I was using Selectize.js is because it was really simple to add new tags using their `create` function which fires when a new tag is created.

Here is a working Selectize.js `create` function:
```javascript
create: function(input, callback){
  $.ajax({
    method: "POST",
    dataType: "json",
    url: '/inventories',
    data: {inventory: {name: input}},
    success: function(response){
      callback({value: response.id, text: response.name});
    },
    error: function(err){
      callback()
    }
  })
}
```

Can we add an example like this for the same use case for Select2?

## Solution
1. Is anyone who knows how to do this easily, and has the time, willing to help improve the documentation on [tagging](https://select2.org/tagging) a little bit?

2. Should there (in the future) maybe be a function that **only fires** when the tag is being created, instead of asking the user to create a custom `newTag` property (like the docs recommend), and than having to check for that custom property?
I guess this has been thought of and there might be technical reasons it's not possible at this time.

**Comment by kevin-brown** [comment]
Tagging this as a documentation request. We're willing to entertain pull requests that improve the documentation in this area.

> 2\. Should there (in the future) maybe be a function that **only fires** when the tag is being created, instead of asking the user to create a custom `newTag` property (like the docs recommend), and than having to check for that custom property?

This is something that is not likely to be implemented directly into Select2, just because we know it can be done through event handlers. It's possible that someone might package up the logic that says "attach an event handler, add the 'new tag' flag, and trigger this function when it's added" but it's unlikely to be in the core.
