### ISSUE TITLE
How do I set the global language

### ISSUE THREAD

**Issue by xumoqiu** [select2/select2#5853]
$.fn.select2.defaults.set("language", "en")  This doesn't work
$.fn.select2({ language:'en' }) This doesn't work

**Comment by kevin-brown** [comment]
English is the default language, so if you're actually trying to set it globally then you don't need to worry.

Otherwise we need a jsbin or jsfiddle where we can reproduce the issue you're seeing with it not working.

**Comment by Navds** [comment]
Maybe the documentation needs improvement because on https://select2.org/i18n it is said that you need to load language files but there is no indication on where you can get them.

 $.fn.select2({ language:'fr' }) This doesn't work
