### ISSUE TITLE
No select2/compat/dropdownCss

### ISSUE THREAD

**Issue by preservance717** [select2/select2#5854]
- select2 version: 4.0.2

I want to add class in dropdownCss. my usage:
`$('.js-select2').select2({dropdownCssClass: 'select-dropdown'});` 
and 
`import 'select2/dist/js/select2.full.js';
import 'select2/dist/js/i18n/zh-CN';`

**result**
in web page(pc), it works fine. However in H5(mobile) it have Uncaught Error.
![image](https://user-images.githubusercontent.com/18299850/81382889-b099e980-9141-11ea-9e88-a43579646a91.png)
 how can i fix this?

**Comment by kevin-brown** [comment]
You're going to need to upgrade to a newer version of Select2, preferably one released this year. Try out 4.0.13.

**Comment by preservance717** [comment]
> You're going to need to upgrade to a newer version of Select2, preferably one released this year. Try out 4.0.13.

I try to upgrade select2@4.0.13, but it still have error in H5 mobile.
![image](https://user-images.githubusercontent.com/18299850/81462713-24da9880-91e7-11ea-8208-f9c41d741400.png)

**Comment by rh0** [comment]
I am also on 4.0.13 and experiencing the same issue.
`No select2/compat/dropdownCss`

**Comment by rh0** [comment]
Just saw #3302 and that solved the issue.  For anyone stumbling on this in the future, be sure you are using the full version `select2.full.js`.
Apologies for the noise.

**Comment by kevin-brown** [comment]
Your code shows the full bills of Select2 but your error logs show the normal build of Select2. The good news is that these options are built into the regular build of Select2 4.1.0-beta.1 which is currently available.

**Comment by peteruithoven** [comment]
This really should be documented on: https://select2.org/configuration/options-api

**Comment by preciado04** [comment]
Thanks @rh0,

Adding "select2.full.js" file, fixed the issue.

**Comment by ColedonProjects** [comment]
Thanks @rh0, 2 years later but this helped me out.

Guess I'll only be using the full version from now on
