### ISSUE TITLE
Problem with @types/requirejs dependency

### ISSUE THREAD

**Issue by rafaelytakei** [select2/select2#5855]
Hi, I'm currently trying to compile a typescript file with Select2, and I'm getting the following error:

ERROR in C:/xampp/htdocs/webpack_test-1/node_modules/@types/node/module.d.ts(2,5):
TS2300: Duplicate identifier 'mod'.
ERROR in C:/xampp/htdocs/webpack_test-1/node_modules/@types/requirejs/index.d.ts(38,11):
TS2300: Duplicate identifier 'mod'.
ERROR in C:/xampp/htdocs/webpack_test-1/node_modules/@types/requirejs/index.d.ts(422,13):
TS2403: Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'NodeRequire', but here has type 'Require'.

Which is being caused by select2 requiring the @types/requirejs

**Comment by kevin-brown** [comment]
Sounds like you are depending on a different package than the Select2 one on NPM. We don't require any TypeScript types and also do not currently export any, so I'm not sure how you're seeing that import as being from us.
