### ISSUE TITLE
jQuery.isFunction() has been deprecated

### ISSUE THREAD

**Issue by Victor-Prodanov** [select2/select2#5857]
**Description:**
As of jQuery 3.3, jQuery.isFunction() has been deprecated. In most cases, its use can be replaced by typeof x === "function".
[https://api.jquery.com/jQuery.isFunction/](url)

**Select2 version used**
4.1.0-beta.1

**jQuery version used**
3.5.1

**Comment by kevin-brown** [comment]
Yup, this was necessary in 4.0.x because we supported ancient browsers where typeof was inconsistent. Now that we're dropping them, we can also stop using that function.

**Comment by kevin-brown** [comment]
This was handled by https://github.com/select2/select2/pull/5955 and can now be closed.
