### ISSUE TITLE
Select2 not working properly if surrounded by empty label

### ISSUE THREAD

**Issue by Thallius** [select2/select2#5866]
Hi,

I am not sure if this is already known but there is a strange behavior on select2 if you surround it by an emtpy label. Because my IDE is giving me an codesmell warning when I use a select without a label I have done just the following:

` <label><select id = "mainPageOwnerSearch" class = "editSelect"></select></label>`

This leeds into the issue, that if you click on the select2, it opens as usual but it directly takes of the focus from the search field so I cannot enter any text. I have to click again on the search field to be able to use the search field for text input.

Otherwise. thanks for this phantastic piece of software

Claus

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
