### ISSUE TITLE
Select 2 - Multiple selection back space key is not working

### ISSUE THREAD

**Issue by DivyaSoftura** [select2/select2#5868]
Select 2 - Multiple selection back space key is not working

for example : To Email text box back space give means it will delete smoothly but using this plugin backspace is not smooth. 
and need to use it in modal popup JQuery it should be work in all browsers

Expecting solution as early as possible.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by DivyaSoftura** [comment]
Hi Kevin,

I am using this select2 Jquery plugin in customize mail modal popup window. If selected multiple mail id’s and using delete or back space key given means need to delete that text but it is not properly working.
It should be work in all browsers.

Expected Outcome:
For Example – any mail compose window works smooth delete when backspace given like gmail, outlook and etc.,

Thanks and Regards,
Divya Vadivelu

**Comment by DivyaSoftura** [comment]
Hi Kevin,


Kindly fix this issue as soon as possible

Thanks and Regards,
Divya Vadivelu

From: Divya V<mailto:Divyav@Softura.com>
Sent: 29 May 2020 10:22
To: select2/select2<mailto:reply@reply.github.com>
Cc: Sampath Kumar<mailto:SampathS@Softura.com>; Maria Antony J<mailto:MariaJ@Softura.com>
Subject: RE: [select2/select2] Select 2 - Multiple selection back space key is not working (#5868)

Hi Kevin,

I am using this select2 Jquery plugin in customize mail modal popup window. If selected multiple mail id’s and using delete or back space key given means need to delete that text but it is not properly working.
It should be work in all browsers.

Expected Outcome:
For Example – any mail compose window works smooth delete when backspace given like gmail, outlook and etc.,

Thanks and Regards,
Divya Vadivelu
