### ISSUE TITLE
Select2 style/css/theming

### ISSUE THREAD

**Issue by gusarg81** [select2/select2#5874]
Hi,

Is there a way to respect original/parent input style? I my site I have all widget styled with my own css and using select2 does not fit at all and does not respect select original css style at all.

Thanks in advance.

**Comment by kevin-brown** [comment]
Unfortunately it's not possible for Select2 to look at the original CSS being applied to a `<select>` box and determine what styles need to be copied over to the generated Select2 instance. Instead we allow you to theme Select2 to meet your needs.

https://select2.org/appearance#themes

There isn't much in the way of documentation around how to configure your own theme, so we usually recommend cloning the default theme, giving it a new name, and tinkering from there until it looks how you want it to.

https://github.com/select2/select2/issues/3272
