### ISSUE TITLE
Feature request to support copy paste multiple values

### ISSUE THREAD

**Issue by wpsumo** [select2/select2#5880]
Right now you can only:

Click => select
Copy-paste 1 value or label

The workflow bottleneck appears once you have plenty of options and allow multiple fields to select from, and you want to add 50+. Copy-paste one by one or search and select one by one is not convenient.

Therefore I wondered if a feature improvement to allow copy-paste more than 1 into the select field and all will be detected as separated values.

So copy-paste into the select field 50 values separated with “,” and all will be detected if correct spelling and format are inserted.

label 1, label 2, label 3, label 4, label 5, label 6… etc

It would improve the workflow of the select field in the tool that uses select2 JS (in my case ACF for WordPress) once you have more than just several values to pick from and select field is set to allow more than one.

**Comment by kevin-brown** [comment]
It sounds like you are looking for [automatic tokenization](https://select2.org/tagging#automatic-tokenization-into-tags) but to have that applied to regular searches and not just tags?

I suspect the biggest hang up for this is going to come from the handling of these searches with remote datasets as well as the right way to handle when "B" and "C" in "A,B,C" is not found.
