### ISSUE TITLE
Documentation improvement: Add what jquery version is needed in order to run this

### ISSUE THREAD

**Issue by TaridaGeorge** [select2/select2#5883]
Add what jquery version is needed in order to run select2 v4.

**Comment by kevin-brown** [comment]
If you're using a jQuery version from the last few years, Select2 works with it. In Select2 4.0.x, we supported back to jQuery 1.7.x, which is ancient and nobody should be using.

Let us know if you find any compatibly issues.

**Comment by dublue** [comment]
Since we upgrade JQuery to 3.4.1 and above, that "cannot type in chars more than minimumInputLength" comes back, similar to this: https://github.com/select2/select2/issues/5485. Tried latest JQuery 3.5.1, same issue. Currently we can only use JQuery 3.3.1
