### ISSUE TITLE
Select2 lose focus in tags: true mode

### ISSUE THREAD

**Issue by Awilum** [select2/select2#5884]
Hello! 

I have a strange behaviour of Select2 in my project. 

I have 

    "select2": "^4.0.13"

this is how it is initialised 

    $('.js-select-tags').select2({tags: true, multiple: true, tokenSeparators: [',', ' ']});

And I am losing focus, when I writing tags 

I have recode a 500kb video
https://we.tl/t-2MFa0RUmRT

any ideas why this issue may be ?

**Comment by kevin-brown** [comment]
Possible duplicate of https://github.com/select2/select2/issues/4398.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by Awilum** [comment]
issue gone somehow by it self
