### ISSUE TITLE
Dropdown always opens upwards if near the bottom of the page, even if there's enough space in the browser window below.

### ISSUE THREAD

**Issue by ghost** [select2/select2#589]
Dropdown always opens upwards if near the bottom of the page, even if there's enough space in the browser window below.

The way viewportBottom is calculated below seems to work fine in my case, but I haven't tested it extensively. The change is at line 873 in select2.js version select2-release-3.2:

```
    positionDropdown: function() {
        var offset = this.container.offset(),
            height = this.container.outerHeight(),
            width = this.container.outerWidth(),
            dropHeight = this.dropdown.outerHeight(),
            viewportBottom = $(window).scrollTop() + Math.max($(document).height(), $(window).height(), document.documentElement.clientHeight),
```

**Comment by valkyr-** [comment]
In Firefox, if the body has no height(99% of cases) it will open upwards, all the time.
