### ISSUE TITLE
Theme parameter error

### ISSUE THREAD

**Issue by Shou-nen** [select2/select2#5892]
Is it intentional in the new version of select2 that you can't set several classes in the theme parameter?
Like this:
```
$(".select2").select2({
  theme: "default myclass"
});
```
-> "Uncaught DOMException: String contains an invalid character"

I've used it on 4.0.6 and now it doesn't work.

**Comment by kevin-brown** [comment]
The `theme` option was always supposed to be for setting the theme used by Select2, not for setting classes on elements. If you are looking to set classes, then I would recommend using the `dropdownCssClass` and `selectionCssClass` options that will allow you to add classes to those Select2 elements.
