### ISSUE TITLE
Search field focus prevents dropdown list scrolling with mouse wheel

### ISSUE THREAD

**Issue by CraftyDlx** [select2/select2#5894]
I am using select2@4.1.0-beta.1 in a modal window for a dropdown list with search field. Everything works great except that the focus remains on the search field and prevents (at least I guess that's the reason) the mouse from scrolling the dropdown list -- which is very nice in longer lists. Even when I click on the scroll bar the focus remains on the search field. How can I make Select2 let me use the mouse wheel for scrolling the dropdown list? Thanks.

**Comment by kevin-brown** [comment]
Very curious if this is an issue with Select2 4.0.13 or if it was newly introduced with the beta.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by CraftyDlx** [comment]
I just found an example where the mouse wheel is not working either: https://codepen.io/uzmaW/pen/NMrgGO

-What browser(s) and Operating System have you tested with?
Firefox and Opera, both latest versions

-Does the bug happen consistently across all tested browsers?
yes

-What version of jQuery are you using? And what version of Select2?
jQuery v3.2.1, jQuery Ui 1.12.1, select2@4.1.0-beta

-Are you using Select2 with other plugins?
bootstrap 4, bootstrap notify, sweetalert 2, moment.js, popper, jquery datatables

I am using Select2 in a Laravel7 application with a Bootstrap 4 theme.
