### ISSUE TITLE
set language,but it's not working.   4.X

### ISSUE THREAD

**Issue by jiayuxiaochaoren** [select2/select2#5896]
$('.test_select2').select2({
        placeholder : '请输入或者选择热门标签（选填）',
        language: "zh-CN",
        tags : true,
        multiple : true,
        minHeight: '450px',
        width:'550px',
        maximumSelectionLength : 3,
        maximumInputLength:10,
        allowClear : false,
        data : itemList,   // 获取数组的数据
    });

When I set language:"zh-CN",but its not working!

**Comment by CraftyDlx** [comment]
Did you import the language file?
https://github.com/select2/select2/tree/develop/src/js/select2/i18n

**Comment by kevin-brown** [comment]
It's most likely the language files are missing, as noted in the previous comment.

**Comment by muffetlab** [comment]
`n.define("select2/i18n/zh-CN",[],function(){return{errorLoading:function(){return"无法载入结果。"},...}}),`
When `alert('aaa');` being added after `function(){`, it did show the alert. But the return functions don't work!
