### ISSUE TITLE
Setting selection in multiple dropdowns is non-deterministic

### ISSUE THREAD

**Issue by CraftyDlx** [select2/select2#5898]
I am using several Select2@4.1.0-beta dropdowns in a Laravel 7 blade view with DataTable. There is at least 1 select option in the dropdowns. Everything works great except setting the selection. There are no errors on the console and the result, which dropdown gets a selection and which not, is different with each page load. The collections I am using have numeric ids, nothing unusual. Here's my code:
```
$('.mySelect').each(function(){
   var $sel = $(this), process_id = $sel.data('id');// from attribute
   $.get(processUrl, {processId:process_id}).then(function(response){
   	
    var fData = $.map(response, function (obj){
      obj.id = obj.id;
      obj.text = obj.text || obj.name;
      obj.disabled = true;
      return obj;
    });

         $sel.select2({
           width: '95%',
           language: 'de',
           data: fData,
           minimumResultsForSearch: Infinity,
           dropdownAutoWidth: true,
           sorter: data => data.sort((a, b) => a.text.localeCompare(b.text)),
         });
         $sel.val($('.mySelect option:eq(1)').val()).trigger('change.select2');  // THE ISSUE
              
   }).catch(function(err){ 
         alert(textStatus + " : " + jqXHR.status + " : " + errorThrown);
   });
});
```

To show the dropdowns:
```
<select class="mySelect" data-id="{{$process->id}}" name="state"><option></option></select> 
```
More info:
-What browser(s) and Operating System have you tested with?
Firefox and Opera, both latest versions

-Does the bug happen consistently across all tested browsers?
yes

-What version of jQuery are you using? And what version of Select2?
jQuery v3.2.1, jQuery Ui 1.12.1, select2@4.1.0-beta

-Are you using Select2 with other plugins?
bootstrap 4, bootstrap notify, sweetalert 2, moment.js, popper, jquery datatables

**Comment by kevin-brown** [comment]
> There are no errors on the console and the result, which dropdown gets a selection and which not, is different with each page load.

This is a giant red flag telling me that your anonymous function that you use for the result is not binding the value of the `$sel` the right way, which you should be able to verify by setting a breakpoint or logging it to the console. The alternative issue is that you have multiple options with the same value, but more likely it's the reference not being held properly.
