### ISSUE TITLE
Placeholder not working for multi select.

### ISSUE THREAD

**Issue by TahmidFarzan** [select2/select2#5899]
I have searched for similar issues in both open and closed tickets and cannot find a duplicate
 The issue still exists against the latest master branch of Select2.
 This is not a usage question (Those should be directed to the community)
 I have attempted to find the simplest possible steps to reproduce the issue
![Multiselect isnot working 2](https://user-images.githubusercontent.com/30841715/87877792-1fc57100-ca02-11ea-8f16-3e8cf2789cf3.PNG)
![Multiselect isnot working](https://user-images.githubusercontent.com/30841715/87877794-218f3480-ca02-11ea-99dc-534ecd63f858.PNG)

Expected behaviour and actual behaviour--
 --- Expected behaviour ---
 Show the placeholder value.

 --- Actual behaviour ---
Does not show the placeholder value.

Browsers ---
 Google Chrome

Operating System ---
 Windows

Libraries ---
 jQuery version: jquery-3.5.1
 Select2 version: 4.0.3

Isolating the problem  ---
  The bug happens consistently across all tested browsers
  This bug happens when using Select2 without other plugins

Placeholder not working for multi select.

**Comment by kevin-brown** [comment]
There is an issue with the HTML/CSS here for sure, but none of that was provided in the original question. If I were to take a guess, based on people who have reported this issue in the past and the issues we have solved around it, upgrading to 4.1.0-beta will solve your issue. The reported version, 4.0.3, is many years old at this point and we have come a long way.

**Comment by jeffg2k** [comment]
I can confirm that the placeholder is visible in the beta, however I do see formatting issues with the beta.  But for anyone searching for a resolution with regard to the release version 4.0.3, here was the issue for me.  The class `select2-search__field` can get set to a 0 width and doing something like `$("#select2").val(null).trigger('change');` causes that to happen.  I had to run this after the trigger to fix it. `$('.select2-search__field').css('width', '100%');`

**Comment by jeffg2k** [comment]
There is too much effort in creating a new issue for me at the moment (stackoverflow and all), so I'm just going to drop 4.1.0-beta-1 issue here and hope that someone doing dev sees it.  The top box what I see for a placeholder on 4.1.0-beta for multiselect.  I don't have that issue on 4.0.3.
<img width="271" alt="Screen Shot 2020-11-09 at 9 24 58 AM" src="https://user-images.githubusercontent.com/161904/98554071-4daf1980-226e-11eb-9b43-3157c6bb21ec.png">
