### ISSUE TITLE
CSS  plug in Select2 Inside scrollable division

### ISSUE THREAD

**Issue by bbajwa9366** [select2/select2#5900]
I'm trying to use this plugin inside a container  with  overflow: scroll but when I scroll the div and click on the last drop down,
it flicker and not opening

Is there some way to fix it?

Layout CSHTml:

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/3.2/select2.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/3.2/select2.min.js"></script>

View File Cshtml File

<script type="text/javascript">

    $(document).ready(function () {
        var count = '@Model.PageImages.Count()';
       
        var i;
        for (i = 0; i < count; i++) {
            var elem = 'PageImages_' + i + '__orderby';
            //alert(elem);
            $("#" + elem).select2();
        }
        

    });
    @foreach (var PageImage in Model.PageImages)
                {

                    <div class="row">
                        <div class="col-md-2">
                            <img src="@(PageImage.ImgUrl)" width="40" height="50">
                        </div>
                        <div class="col-md-2">
                            @Html.DisplayFor(m => m.PageImages[i].Desc)
                            @Html.HiddenFor(model => model.PageImages[i].Container)
                            @Html.HiddenFor(model => model.PageImages[i].Desc)
                            @Html.HiddenFor(model => model.PageImages[i].HomePageId)

                        </div>

                        <div class="col-md-1">

                            @Html.DropDownListFor(model => model.PageImages[i].orderby, new List<SelectListItem>
                         {
                            new SelectListItem{ Text="0", Value = "0" },new SelectListItem{ Text="1", Value = "1"},
                            new SelectListItem{ Text="2", Value = "2" },new SelectListItem{ Text="3", Value = "3"},
                            new SelectListItem{ Text="4", Value = "4" },new SelectListItem{ Text="5", Value = "5"},
                            new SelectListItem{ Text="6", Value = "6" },new SelectListItem{ Text="7", Value = "7"},
                            new SelectListItem{ Text="8", Value = "8" },new SelectListItem{ Text="9", Value = "9" } },
                            new
                            {
                                style="width:60px;",
                                onchange = "callChangefunc(this.value,this.id);"
                            })

                        </div>
                        <div class="col-md-5">

                            @Html.TextBoxFor(m => m.PageImages[i].File, new { type = "file" })
                        </div>
                        <div class="col-md-1">
                            <input type="submit" value="Update" class="btn btn-primary btn-rounded" formaction="UploadHomePageImages" />
                        </div>
                    </div>

                    i = i + 1;

                          
                }

CSS:
.select2-results .select2-highlighted {
    background: #ff5500!important; /*this is responsible to change the bg color*/
    color: WHITE!important; /*this is responsible to change the font color*/
}

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
