### ISSUE TITLE
Searching for German umlauts (üöä) brings incorrect results 

### ISSUE THREAD

**Issue by CraftyDlx** [select2/select2#5907]
I tested this with latest versions of Firefox and Chrome and I am using select2@4.1.0-beta.1 with the german language pack which is working well, except finding values with german umlauts. For instance entering 'ö' brings up the name 'Götz' but also any other name containing just an 'o'. The same with 'ü', 'ä', 'ß'. Any collation in my database is `utf8mb4_unicode_ci` which is supposed to work with any unicode char.  My Select2 code is

```
$("#dispo").select2( {
  width: '100%',
  language: 'de',
  data: fData,
  sorter: data => data.sort((a, b) => a.text.localeCompare(b.text)),
  dropdownAutoWidth: true,
  closeOnSelect: false,
  allowClear: false
}); 
```
I found a Select2 codepen and modified the options. In "Select One" you can search and see that 'ö ü ä ß' are treated equally like 'o u a s' : https://codepen.io/craftydlx/pen/OJNPwwp

If it's of any help: I am also using DataTables.net in my web app and their search function works flawlessly with german umlauts, just bringing up this one name 'Götz' when searching for 'ö'.

**Comment by kevin-brown** [comment]
https://select2.org/i18n#transliteration-support-diacritics

Select2 will automatically strip diacritics as a part of the internationalization support. This is built into the default matcher, so if you are interested in having a different matching ability then we would recommend you customize it to meet your needs.

https://select2.org/searching#customizing-how-results-are-matched

I would recommend taking a look at the default mapper and removing the portions where we strip out diacritics as a good reference.

https://github.com/select2/select2/blob/develop/src/js/select2/defaults.js#L244-L287

**Comment by CraftyDlx** [comment]
Thanks. Now that I know the term 'diacritics' I found this thread you answered almost 5 years ago: https://github.com/select2/select2/issues/4007

So according to your answers here and there I copied the function `matcher (params, data)` and removed `stripDiacritics`. The result stays the same as with the original matcher, still 'üöäß' are equal to 'uoaß'. What am I missing?

```
<script>
(function(){ 
    function matcher (params, data) {
      if (params.term == null || params.term.trim() === '') {
        return data;
      }

      if (data.children && data.children.length > 0) {
        var match = $.extend(true, {}, data);
        for (var c = data.children.length - 1; c >= 0; c--) {
          var child = data.children[c];
          var matches = matcher(params, child);
          if (matches == null) {
            match.children.splice(c, 1);
          }
        }

        if (match.children.length > 0) {
          return match;
        }
        return matcher(params, match);
      }

      var original = data.text.toUpperCase();
      var term = params.term.toUpperCase();

      if (original.indexOf(term) > -1) {
        return data;
      }
      return null;
    }

   $("#dispo").select2({
        matcher: matcher
    });
})();
</script>
```

**Comment by kevin-brown** [comment]
Are you able to turn that code snippet into a jsbin (or comparable live runner) where it shows the matcher not working? That code snippet should be enough to turn it off so if it doesn't then we have other issues.

**Comment by CraftyDlx** [comment]
I updated the codepen from above, should apply to the first form field now: https://codepen.io/craftydlx/pen/OJNPwwp

**Comment by CraftyDlx** [comment]
Found something. I am not allowed to
```
(...)
   $(".js-select2").select2({
        matcher: matcher
    });
})();
  
  $(".js-select2").select2();
```
because then my custom matching method is overwritten by the standard method(?). Not sure if this is the issue in my code but will check.

**Comment by CraftyDlx** [comment]
Yeah that was the issue. I declared my Select2 by
```
          $("#dispo").select2( {
         	  width: '100%',
         	  language: 'de',
            data: fData,
          	sorter: data => data.sort((a, b) => a.text.localeCompare(b.text)),
            dropdownAutoWidth: true,
            closeOnSelect: false,
            allowClear: false
          }); 
```
and wanted to declare the matcher afterwards with
```
   $("#dispo").select2({
        matcher: matcher
    });
```
but that's obviously not okay for Select2.
Thanks for your help!
