### ISSUE TITLE
Internal cache not cleared properly after destroying select2

### ISSUE THREAD

**Issue by hdplampert** [select2/select2#5912]
Property __cache from module Utils still retains DOM element from destroyed select2 instance.

Reproducible here: https://jsfiddle.net/wgnmvfbj/2/
Click on create then destroy, cache size will not go back to 0.

I've tracked down the issue to the following line adding to cache an item that is never removed: https://github.com/select2/select2/blob/ef33f4be110f5154c11b49d73e7b15921e143398/src/js/select2/core.js#L600

I didn't find any reason for caching $container, so I assume the fix could be simply removing that line.

**Comment by kevin-brown** [comment]
Yup, that's been an issue for a while apparently. Looks like it is no longer cleaned up after we moved away from `$.fn.data()` and we never noticed it.

The original need for it was added in https://github.com/select2/select2/commit/130358e8ae26e632146674ab06e90e4ada36d027.
