### ISSUE TITLE
Is there any way to clear cached results from the select2 dropdown?

### ISSUE THREAD

**Issue by ekr3peeK** [select2/select2#5918]
Creating a JSBin would be rather hard for my problem, but I will try to explain it the best as I can, and later will try to get a JSBin example together also.

Basically, I have two select2 instances on a page, an ajax sourced one, and a simple one. The two are connected, meaning that when I use the ajax sourced one, it fetches the data selected in the simple select2, and sends it with the ajax request, so that only a subset of the data is returned by the ajax (the data that is relevant to the situation).

My problem is, that when I open the ajax sourced select2, for a split second, before loading starts, the previously displayed result set is visible. But if in the meantime, the simple select2 was changed, the data displayed for that split second is not relevant any more. Worse by this, the data is not only displayed, but if I am quick enough (or if my server is slow enough to retrieve the data from the ajax), the irrelevant data can still be selected.

Is there any way, on how I could clear those cached results from the ajax sourced select box? I could hook an event listener to the simple select, that when it changes data, this clearing function should run, but I didn't find any method in the docs, that deals with clearing the data from the dropdown.

**Comment by ekr3peeK** [comment]
up

**Comment by almuth** [comment]
have the same issue and use `results.clear()` work for me

on simple select change clear the select ajax select2 results

```
...
$('#simple-select').on('change', function(){
    $('#select2Ajax').data('select2').results.clear()
})
...
```
