### ISSUE TITLE
Removing an item from the top of the dropdown list causes moving the scroll moves to the end of the list 

### ISSUE THREAD

**Issue by alekskushchik** [select2/select2#5919]
Version: Select2 4.0.13

What happens:
I have a long list (more than 20 items) and when I remove an item from the top of the list, the scroll moves me to the end of the list.

What is expected:
Is there any solution so that when elements are deleted, the scroll does not move and user sees the same view area?

Also, when I'm trying to delete a selection, scroll of the dropdown moves me to the end, and when I move back to my selection, I notice, that it is not deleted. Only for the second time clicking on clear button it removes successfully.

**Comment by kevin-brown** [comment]
This sounds a lot like you either have a selection towards the bottom of the list, and it's the next available selection, or you have an interaction with events that isn't mentioned in the ticket. We don't see this on the main Select2 documentation site.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by alekskushchik** [comment]
Thanks for your answer. I have screen capture of my issue. https://drive.google.com/file/d/1udp63F6EcWg6aW9GyvarSMSbiq_5tCQV/view?usp=sharing

I am using Select2 v.4.0.13, and jQuery v.1.12.4
