### ISSUE TITLE
setting tags: false will not eliminate the tags being displayed in the container 

### ISSUE THREAD

**Issue by almtorres** [select2/select2#5929]
I am currently using this version of select2 4.1.0-beta.1. I want to get rid of the tags displayed when options are being selected. I referred to this documentation (https://select2.org/tagging) and realized it mentions no way to get rid of these tags. I did set tags: false yet the tags are still displayed. Why is this happening?

**Comment by kevin-brown** [comment]
> I did set tags: false yet the tags are still displayed.

This sounds like you aren't referring to tags, the ability for people to be able to create their own options, and instead you are referring to the list of options that you have provided in your `<select>` which Select2 will always display when the dropdown is opened. This is expected functionality.

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/
