### ISSUE TITLE
when click select2 box . page scroll up

### ISSUE THREAD

**Issue by SupunSpera** [select2/select2#5930]
When I click a select2 box its scrolling the page to up.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by berkayoruc** [comment]
I'm not sure it's the same problem but I have similar problem. There are some selectbox and selectbox with checkbox. If select2 is applied to widget, page is expanded with white area which is unwanted behavior. When select2 is not applied there is no white area.

Unwanted page
![img1](https://user-images.githubusercontent.com/22800134/99942169-3ef15800-2d80-11eb-96d5-21697b7ed9b1.png)

Desired page
![img2](https://user-images.githubusercontent.com/22800134/99942196-4a448380-2d80-11eb-96c0-0e8736895e27.png)
