### ISSUE TITLE
First option gets automatically selected with tags=true

### ISSUE THREAD

**Issue by edu2004eu** [select2/select2#5931]
This issue was originally posted here: https://github.com/select2/select2/issues/5516#issuecomment-630942043

To make this easier to follow, I'll also post the original [JSFiddle](https://jsfiddle.net/wolfteam20/2pwkLq6j/2/).

The bug is that the first option automatically gets selected if `tags: true` **and you don't have an empty option in the `select` element**.

This behaves similarly when an empty `select` is used with AJAX, with the main difference being that if there are no returned results from the AJAX endpoint, the actual tag is being selected (as that is the first and only option). Events (like `select2:select` or `change`) are not triggered.

The workaround I've found is to have an empty `option` in the select and a placeholder text.

**Comment by kevin-brown** [comment]
As is mentioned in the [documentation for single selects and placeholders](https://select2.org/placeholders#single-select-placeholders)

> For single selects only, in order for the placeholder value to appear, you must have a blank <option> as the first option in your <select> control. This is because the browser tries to select the first option by default. If your first option were non-empty, the browser would display this instead of the placeholder.

This behaviour of selecting the first option by default, which in this case is the tag option that Select2 automatically creates for you, is not something which Select2 can prevent. The easy solution is to either have an option in your `<select>` that is empty, which you've noticed already.

For AJAX selects, this empty option should be ignored even when you're not using the placeholder option.
