### ISSUE TITLE
Missing suport for long search input

### ISSUE THREAD

**Issue by Temepest74** [select2/select2#5939]
The select2 multibox does not work well with a large text into the input field. Please help me with this bug. The screenshot was took from here https://select2.org/getting-started/basic-usage.
![image](https://user-images.githubusercontent.com/28103890/97020437-3aa40600-155a-11eb-8cc7-dbb62661de79.png)

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/5863.
