### ISSUE TITLE
No list of themes to choose from

### ISSUE THREAD

**Issue by Wuelle** [select2/select2#5943]
I was unable to find a list containing all available themes for a Select2 Box in the ![Docs](https://select2.org/). The only way to know which themes you can choose from is to go to `select2/src/scss/theme/` and look at the folder names. (Even if there is another way which i missed there definetely should be a list of themes under the ![themes Section](https://select2.org/appearance#themes))

I will add a PR that fixes this

**Comment by Wuelle** [comment]
I must have accidentally closed this, nvm. The PR related to this Issue is #5944

**Comment by kevin-brown** [comment]
So this is challenging because Select2 comes with the two themes you have noted, but we also support third party themes, some of which are listed in the README: https://github.com/select2/select2#integrations
