### ISSUE TITLE
Updating the selected item visually on update

### ISSUE THREAD

**Issue by Jeje2201** [select2/select2#5946]
Hi

Changing the value of the select from javascript / jquery doesn't change it visually.

What I mean is, I have a select, if I want to get the value I use `$('#example1').val()` and it work like a charm
But if I change its value `$('#example1').val(2)` then it doesn't change visually, the user still see the previous choice selected even if the value of the select indeed changed.

The only solution I found so far is to execute `$('#example1').select2()` after the change for the select to change the label to the one selected.

I created a codepen to show you directly
https://codepen.io/MrJeje_/pen/xxOJKpm

**Comment by katzmo** [comment]
Having the same issue (using 4.0.13). After `$('#example1').val(2)` the `aria-selected` in the results dropdown list is updated correctly but the select2-selection container is not.

Using 4.0.13 right now, but I also checked out 4.1.0-beta.1 for testing and can reproduce it there too.

**Comment by kevin-brown** [comment]
It looks like you are not triggering the `change` event after you are setting the value.

https://select2.org/programmatic-control/add-select-clear-items#selecting-options

**Comment by torotil** [comment]
In our case this was indeed caused by the change event not being triggered, because of multiple jQuery instances (see https://github.com/jquery/jquery/issues/4815)

**Comment by kevin-brown** [comment]
The cause of the jQuery ticket being closed off is basically covered by https://github.com/select2/select2/issues/1908 here on this tracker.
