### ISSUE TITLE
CreateTag dupplicate the same value

### ISSUE THREAD

**Issue by WebCimes** [select2/select2#5949]
I have a problem when I try to use CreateTag option, when I type the same term that already exist in the select I see it in double.

For exemple I have this code : 

	$("select").select2(
	{
		allowClear: true,
		tags: true,
		createTag: function (params)
		{
			var term = $.trim(params.term);
			term = parseFloat(term.replace(/,/g,'.').replace(/ /g,'')).toFixed(2).replace(/\./g, ',')+" %";
			if(term === '')
			{
				return null;
			}
			return {
				id: term,
				text: term,
				newTag: true // add additional parameters
			}
		}
	});

In my select I have this default option : 
![image](https://user-images.githubusercontent.com/43851969/99240118-523e7980-27fc-11eb-8fd8-5d71fc1938f8.png)

And when I type "10" I get :
![image](https://user-images.githubusercontent.com/43851969/99239943-0d1a4780-27fc-11eb-95d7-d068678b8632.png)

But the "10,00 %" already exist so I doesn't want to see him in double in the search box, I have try to set the "id" of the `<option>` html tag with the text of my term "10,00 %" but it doesn't work, have you an idea of the problem ?

Thanks

**Comment by kevin-brown** [comment]
Select2 will only duplicate tags if the `id` returned does not match an `id` already present in the option list. For cases where you are using `<option>` tags, the `id` that is checked is the `value` of the `<option>` tag.

You can see an example of this in the documentation: https://select2.org/tagging
