### ISSUE TITLE
The Select2 Translation library does not include translation for "Remove Item"

### ISSUE THREAD

**Issue by TukuToi** [select2/select2#5954]
Just check https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/i18n/fr.js or any other translation even EN will not feature the translation options for the single remove item string "Remove Item"

The only it translates is the removeAllItems option

How can we translate the single remove item string?
There is no option for it in any of the files so it is probably just not supported?

**Comment by kevin-brown** [comment]
Select2 is translated by the community, which means you can help us out and provide translations for languages you know! See more at https://github.com/select2/select2#internationalization-i18n.

When translations are missing strings, we have to fall back to English since it's the one we define the base translations for.

**Comment by TukuToi** [comment]
@kevin-brown - the problem is not even the English source file has a string offered for it.
see what I mean here https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/i18n/en.js

Search for "Remove Item". You can't find it, only a `removeAllItems ` is there, no string for single `Remove Item` is there.
So how can we translate it?
I'd immediately offer my translations if there would be a place to add them, but it seems to me that particular string isn't localised.

**Comment by kevin-brown** [comment]
The current translation target was added in https://github.com/select2/select2/commit/181170f8a4d5c7eb4670ccd3926add33391b6b2d which landed in 4.1.0-beta.1 which explains why it is not present in 4.0.13.

I can't find where in 4.0.13 we would have been displaying "Remove item" and looking in https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.js I don't see that string.

**Comment by TukuToi** [comment]
I am loading the wrong version? I load what is documented on the Select2 Page here:
https://select2.org/getting-started/installation
```
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
```

Indeed, it says beta, and I wondered why that is and it should have jumped to my eyes that I load a older translation instead.
So I should load the same vs of translation and when I do that, I can see the word in https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/i18n/en.js, but not in French https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/i18n/fr.js

Hence, I guess, I'll amend my script, load the proper file, create a translation for `removeItem` and generate a pull request in the Select2 Project.

Thanks @kevin-brown and sorry the misunderstanding!

**Comment by TukuToi** [comment]
I've made the changes here https://github.com/TukuToi/select2/commit/9739b69a9646434e7fb61a9313e8d38b40c7bf36
I hope I did this correctly and it will automatically be pushed to stable once it is merged?
Or is there something missing from my end?
