### ISSUE TITLE
Invalid ARIA attribute value : aria-activedescendant

### ISSUE THREAD

**Issue by pank05** [select2/select2#5962]
When the values are pre-selected the aria-activedescendant generated is not proper. I can  see an aria-activedescendant="ui-select-choices-row-0--1". So far  I can see the "-1" is appended instead of "1".

![ca301c20-09ab-445e-a8fe-797536714979](https://user-images.githubusercontent.com/30679501/103256949-285ca300-49b5-11eb-9a44-4bf158de96f1.png)

**Comment by kevin-brown** [comment]
[angular-ui/ui-select](https://github.com/angular-ui/ui-select) is a project that takes the Select2 styles and gives you a native AngularJS select to use. It is not affiliated with the Select2 project and does not actually use the Select2 renderer.

It also hasn't been updated for a few years.

----

This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

[ml]: https://select2.org/troubleshooting/getting-help
