### ISSUE TITLE
Select2 field .value property doesn't change inside .onchange function

### ISSUE THREAD

**Issue by kuipumu** [select2/select2#5966]
I'm having this very specific issue of which I have not been able to find a solution.
I have a Select2 field on which after selecting a specific company it will auto fill with it's corresponding country based on values fetch from an API on a [.onchange][1] function triggered on a Select2 field from which you select the corresponding company to fetch from.

All other auto-filled fields apart from this one, get populated with it's corresponding value, except for the Select2 field for the country value that only gets selected but not displayed has chosen.

However, if I try to change the .value property outside the .onchange function, the field does change completely and display the currently selected country on the list.

I already tried executing the function either by changing the .value property with vanilla JavaScript and using the .val method with JQuery following the recommendations on the [Select2 documentation][2], but the same result occurs, here I attach the code and some screenshots.

```
const countryField = document.querySelector(
    'select[name=' + country + ']'
)

selectField.onchange=function() {
    const apiUrl = new URL(url)
    const params = {q: $(this).val()}
    apiUrl.search = new URLSearchParams(params).toString();
    fetch(apiUrl)
        .then((response) => response.json())
        .then(function(data) {
            const fieldsToUpdate = [
                {field:addressLine1Field,value:data.address_line1},
                {field:addressLine2Field,value:data.address_line2},
                {field:cityDistrictField,value:data.city_district},
                {field:stateProvinceField,value:data.state_province},
                {field:postalCodeField,value:data.postal_code},
                {field:countryField,value:data.country},
            ]
            for (const { field,value } of fieldsToUpdate) {
                if (!!field) {
                    field.value = ''
                    if (!!value) {
                        field.value = value
                    }
                }
            }
        })
        .catch(function(error) {
           console.log(error);
        });
}
```
[![Country is only selected on list but not display has selected.][3]][3]

While changing the property outside the function results in this:

```
const countryField = document.querySelector(
    'select[name=' + country + ']'
)
countryField.value = 'Canada'
```
[![Country is selected on the list and displayed has selected.][4]][4]

So far I'm still not sure what makes the property change works different on the DOM while executing it inside the .onchange method.
If anyone out there might have any idea what it could be, any help would be appreciated.
Thank you all.

  [1]: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onchange
  [2]: https://select2.org/programmatic-control/events#limiting-the-scope-of-the-change-event
  [3]: https://i.stack.imgur.com/1CDPK.png
  [4]: https://i.stack.imgur.com/5jgZ5.png

**Comment by kevin-brown** [comment]
Are you able to reproduce this issue in a jsbin (doesn't need to be a fancy example) so we can use it for an isolated test case? That should make it easier to trace the issue, since it sounds specific to how the browser binds to this event.

**Comment by kuipumu** [comment]
Here is a sample, https://jsbin.com/zazakawuba/edit?html,js,output it does work in this isolated test case, I'm not able to reproduce the bug, it happens only inside my app, I'm not sure how to properly show any log on how to DOM is behaving.

**Comment by kuipumu** [comment]
Also, neither using $('#field_id').addEventListener('change', (event) => {} or $('#field_id').change(function() {} works on the company field, which is also a Select2 field, at this point I'm not sure what is interfering with the event to get triggered.

**Comment by kevin-brown** [comment]
Unfortunately without being able to reproduce it in isolation it's hard for us to determine if this is an issue in Select2. I would check for any other `change` event handlers you have that may be in place to ensure they don't call `stopPropagation()` or otherwise affect the propagation of the event and the event handling process.

I'm going to leave this ticket open for a bit in case you're able to discover a potential cause.
