### ISSUE TITLE
Documentation doesn't work

### ISSUE THREAD

**Issue by fabgg** [select2/select2#5976]
impossible to see examples in action on documentation select2.org. In browser console i get 
**Uncaught TypeError: $(...).select2 is not a function**
on all pages with firefox or chrome the résult is similar.

Maybe webpack config ...

**Comment by Jelle-S** [comment]
Can confirm, same issue here

**Comment by kevin-brown** [comment]
We're aware of the issue with the documentation site not loading in the main JS file and we're working to clear the internal cache on the documentation server.

**Comment by kevin-brown** [comment]
After connecting in to the documentation server and manually cache busting the CSS and JS assets, the documentation site should be up to date. We are aware of styling issues that appear in the release candidate that conflict with the documentation site theme and will address those independently.
