### ISSUE TITLE
Browser crashes when use select2 there are too many select box

### ISSUE THREAD

**Issue by ThanSau1105** [select2/select2#5978]
In a form I have thousands of records to update and in each record I have a select box(each select box have 20-30 options) so there are total thousand of select boxes. When I apply Select2 on these all select boxes using same class Its freeze my browser. If I don't use select2 then it works fine.

Please give me the solution

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by McFcologne** [comment]
i have the same issue. There is a select with about 3500 options. When i apply select2 the browser is completely freezing. After about 5 minutes it comes back to life and all is working fine. Is there an option like: max_shown_results (available in the chosen component) i don't need the full list to be rendered, but searchable

**Comment by dathacky** [comment]
+1
