### ISSUE TITLE
select2.org is not working

### ISSUE THREAD

**Issue by fxamauri** [select2/select2#5989]
Hello guys. I tried access select2.org to view the documentation, but i get connection timeout message.

**Comment by Seb35** [comment]
In the meantime you can use https://web.archive.org/web/20210220210734/https://select2.org/

**Comment by kingIZZZY** [comment]
+1 need documentation please 🙏

Thanks @Seb35 for workaround

**Comment by fxamauri** [comment]
Good Job 💯  
Thanks @Seb35

**Comment by toitzi** [comment]
Seems like it works now!

**Comment by fxamauri** [comment]
it works now!

**Comment by kevin-brown** [comment]
Didn't even notice this ticket. We ran into a DNS resolution issue that was handled. We are still looking in to longer-term solutions that make better use of the Cloudflare cache to keep our docs online at all times.
