### ISSUE TITLE
Select2 - No effect on after .trigger('change') when using ajax data

### ISSUE THREAD

**Issue by edcaron** [select2/select2#5990]
I’m trying to programmatically change a value from a select2 that uses remote data but it has no effect, the value is not changed.

The code i use is the one bellow:

` $("#example1").val('39840932').trigger('change');`

The value `‘39840932’` represents the **google/googletest** option from the select.

Full code is there https://jsbin.com/qirixah/edit?html,js,console,output

Steps to reproduce the problem:
1. Go to the full code https://jsbin.com/qirixah/edit?html,js,console,output
2. Click on the button "changeVal" or paste the same code above
3. See that no change is made.

Other thing I noticed that this code above works only if you follow the steps:

1. manually select the google/googletest option from the select
2. manually change for any other option
3. run the code above

It looks like it needs the data to come from the server and then you can programmatically change its value, but it should not be this way.

**Comment by mario-amazing** [comment]
Same with jQuery 3.6.0
select2 - 4.1.0-rc.0
