### ISSUE TITLE
Failed to bind with the same id in the select2

### ISSUE THREAD

**Issue by chorar** [select2/select2#5999]
npm jQuery JavaScript Library v3.5.1
npm select2@4.1.0-rc.0

HTML snippet:
```html
<select id='select' class="select2" style="width: 100%">
  <option>test1</option>
  <option>test2</option>
</select>

<select id='select' class="select2" style="width: 100%">
  <option>test3</option>
  <option>test4</option>
</select>
```
JS:
```javascript
$('select').select2({
  placeholder: 'This is required',
  allowClear: true
})
```
result
![1234](https://user-images.githubusercontent.com/17961800/110820581-33438600-82ca-11eb-8c86-61a0e0f31ad4.png)

**Comment by martinbarilik** [comment]
You should not have two identical IDs in DOM.

**Comment by kevin-brown** [comment]
As has been noted, IDs should be unique per the HTML specification so using duplicate IDs is out of spec and unsupported as a result.
