### ISSUE TITLE
Cannot interact with dropdown within Bootstrap modal

### ISSUE THREAD

**Issue by JasonRodman** [select2/select2#600]
In IE 8 or 9 i cannot get the typeahead to work when shown in a modal dialog. I created a jsfiddle to repro the issue below, but its slightly different than the behavior I was seeing in my own project. In my project, when I clicked on the dropdown, the textbox would not get focus. When I clicked the box again, the cursor would show up and then disappear. Typing did nothing, it bahaved as if the input didnt have focus anymore. When I built the jsfiddle to show you, it did get focus and I was allowed to type, but it did not search at all as if it didnt detect the keystrokes. I suspect both behaviors are related. Try it out here: One select is inline, the other in a modal dialog triggered by a button.
http://jsfiddle.net/5AbC2/37/

**Comment by kevin-brown** [comment]
The `enforceFocus` fix still works with 4.0.0, just as it did with older versions.

```js
$.fn.modal.Constructor.prototype.enforceFocus = $.noop;
```

Alternatively you can specify an actual function that checks if the focus is going to a Select2 element.
