### ISSUE TITLE
select2 set fixed width to main span and not resizing 

### ISSUE THREAD

**Issue by aaburlaka** [select2/select2#6000]
When page loads i see
`<span class="select2 select2-container select2-container--bootstrap select2-container--focus" dir="ltr" data-select2-id="1" style="width: 688.203px;">`
and width not changing when wrapping block resizes. I'm not sure you need to use width there. I tried to remove it from code and it works excellent for me

**Comment by crodrigueza16** [comment]
Same problem here... On same versions of Chrome, differents computers, assigns auto width in oner and fixed in the other and i dont know why.
@aaburlaka what code are you removed?

**Comment by aaburlaka** [comment]
I've found that I can change size and now it is not fixed
`
		$('select.combobox').select2({
			width: 'style'
		});
`

**Comment by kevin-brown** [comment]
Yup, width option should be able to solve any problem:

https://select2.org/appearance#container-width

**Comment by haroon26** [comment]
I had the same issue when I placed the select2 inside a table cell. The only solution that worked for me was to add following style to select2-container:
```css
  .select2-cell > .select2-container {
    display: table;
    table-layout: fixed;
  }
```
After this, the width will only get fixed to the parent element. Hope this will work for you as well :)
