### ISSUE TITLE
Add JSON data adapter

### ISSUE THREAD

**Issue by AndrolGenhald** [select2/select2#6002]
I had the same issue as #236 and #390.

In my case I have many (could be 100) select2 elements with identical options, with thousands of options. Loading all of the options once as JSON on page load results in a better user experience since searching is near-instant and results in much less load on the server due to duplicate searches (admittedly better caching could partially solve this).

Loading the JSON is fairly quick, but select2 doesn't currently provide any way to load JSON data as options without putting them all in the DOM immediately, which is incredibly slow.

I used the following to add a new adapter to select2 that acts like the AjaxAdapter but uses a `deferredData` option populated with JSON for the data instead of making AJAX requests:

```
$.fn.select2.amd.define('DeferredLoad', [
  'select2/utils',
  'select2/data/array',
  'select2/dropdown/infiniteScroll',
], function (Utils, ArrayAdapter, InfiniteScroll) {
  function DeferredLoad($element, options) {
    this._deferredData = options.get('deferredData');
    this._previousOffset = 0;
    this._previousIndex = 0;
    this._previousTerm = undefined;

    options.set('resultsAdapter', Utils.Decorate(
      options.get('resultsAdapter'),
      InfiniteScroll
    ));

    DeferredLoad.__super__.constructor.call(this, $element, options);
  }

  Utils.Extend(DeferredLoad, ArrayAdapter);

  DeferredLoad.prototype.query = function (params, callback) {
    var data = [];
    var more = false;
    var offset = 0;
    const pageSize = 100;
    var startingIndex = 0;

    if (typeof params.page !== 'undefined') {
      offset = (params.page - 1) * pageSize;
    }

    // Offset of data in data array to use
    var dataOffset = offset;

    if (params.term === this._previousTerm && offset === this._previousOffset + pageSize) {
      // Continue search where previous left off
      startingIndex = this._previousIndex;
      // Since we're starting the search where we previously left off, we don't need to ignore results up to the offset
      dataOffset = 0;
    }

    var i = startingIndex;
    for ( ; i < this._deferredData.length; ++i) {
      var matches = this.matches(params, this._deferredData[i]);
      if (matches !== null) {
        data.push(matches)
        if (data.length > dataOffset + pageSize) {
          more = true;
          break;
        }
      }
    }
    this._previousIndex = i;
    this._previousOffset = offset;
    this._previousTerm = params.term;

    data = data.slice(dataOffset, dataOffset + pageSize);

    callback({
      results: data,
      pagination: {"more": more}
    });
  };

  return DeferredLoad;
})

var DeferredLoadAdapter = $.fn.select2.amd.require('DeferredLoad');
```

Usage:
```
$('selector').select2({
    deferredData: data, // JSON in select2 data format (https://select2.org/data-sources/formats)
    dataAdapter: DeferredLoadAdapter,
});
```

If this is something that would be useful to integrate into select2 I'd be happy to clean it up a bit and do a pull request.

**Comment by kevin-brown** [comment]
> If this is something that would be useful to integrate into select2 I'd be happy to clean it up a bit and do a pull request.

Unfortunately we aren't accepting new data adapters at this time (we have a lot to maintain already), but we would gladly link to a GitHub repository or Gist in the README if you released this in one.
