### ISSUE TITLE
focus() doesn't work with new jquery 3.6.0

### ISSUE THREAD

**Issue by itajackass** [select2/select2#6005]
automatic focus inside input search field, doesn't work after upgrade to latest jqeury 3.6.0.

**Comment by MoreMeng** [comment]
https://github.com/select2/select2/issues/5996

**Comment by tagliala** [comment]
Duplicate of #5993

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/5993.
