### ISSUE TITLE
Select2 lost focus with JQUERY 3.6.0

### ISSUE THREAD

**Issue by dorathoto** [select2/select2#6034]
Select2 version 4.1.0-rc.0 loses the automatic focus in the search with Jquery 3.6.0, when I return to jquery version 3.5.1 it works.

Example:
https://jsfiddle.net/dorathoto/1q5L4cab/1/

**Comment by webjohan** [comment]
https://github.com/select2/select2/issues/5993

**Comment by kevin-brown** [comment]
Closing as a duplicate.
