### ISSUE TITLE
Typings problem with title property

### ISSUE THREAD

**Issue by xxxKOTxxx** [select2/select2#6036]
Problem caused by next definition:
```ts
export interface DataFormat {
    id: number | string;
    text: string;
    selected?: boolean;
    disabled?: boolean;
}
```
As mentioned in [this issue](https://github.com/select2/select2/pull/3988) we can handle dropdown title by adding according property `title`. But currently it causes conflict with interface (same for `html` property). `OptionData` and `OptGroupData` are not suitable because has other semantic and contains required props like `disabled`, etc..

Please, update DataFormat interface by adding optional properties `title?: string;` and `html?: string;`. Possibly it has other undocumented properties?

If I need to use another interface, please mention it in comments.

Reproducing on "@types/select2": "^4.0.53"

Best regards, Borys

**Comment by kevin-brown** [comment]
Unfortunately we do not maintain the Select2 typings for Typescript. They are maintained by DefinitelyTyped.

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/select2
