### ISSUE TITLE
Typing with Select2 focused doesn't open panel in Firefox and Edge (Chromium)

### ISSUE THREAD

**Issue by killerrin** [select2/select2#6046]
I've noticed that in 4.1.0.rc0 when you tab into the select2 input in Firefox or Edge, the select2 panel isn't being opened with your input put into search.

This behavior is functioning properly with Chrome

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/3279, I think? Also maybe https://github.com/select2/select2/issues/5996?

-----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by killerrin** [comment]
So looking at those two, Yes to #3279, No to #5996. 

So I guess this is a duplicate. That said, I'll fill this out anyways just because its a strange omission given most browsers at minimum allow a select to be tabbed through with key input on focus

**What steps can be used to reproduce the issue?**
Using your keyboard on Firefox or Edge (Chromium). Tab to the Select2 Input box that replaces your <Select>. Begin typing with your keyboard

**What is the bug**
The Select2 Does not open and the Search Pane does not contain typed text

**What is the expected outcome?**
The Search Pane opens up and begins searching for your typed input automatically. At the very least, it should operate just how a standard select works in most browsers, which is just tab through the items that start with the key you hit.

What browser(s) and Operating System have you tested with?
Edge (Chromium) - v90.0.818.39
Firefox - v88.0
Chrome - v90.0.4430.85

Windows 10

Does the bug happen consistently across all tested browsers?
It works properly in Chrome. It does not work in Edge and Firefox

Can you reproduce this issue on any of the examples in the docs?
Yes, both in the examples and on the official Select2 Website. In addition, I also noted that on the Examples and Select2 Website, the limited support in Chrome stops functioning as well leaving it broken in all browsers.

What version of jQuery are you using? And what version of Select2?
On my site: 
Jquery: 2.2.4 
Select2 4.1.0.rc0
