### ISSUE TITLE
Allow the selection of the same value multiple times

### ISSUE THREAD

**Issue by sphuber** [select2/select2#6048]
The current behaviour is that if a value is already selected, if it is selected again from the drop down menu, it will be deselected instead of being a tag being added another time to the selected values. I searched online and the documentation for mention of this functionality but it seems this feature does not exist. How could this be implemented? I am using select2 v4.0.13.

Not sure if this feature request requires an MVE but here goes: https://jsfiddle.net/45fmnoyz/
As you can see, I can only select `A` once but I would like it to be possible for `A` to be selectable multiple times.

**Comment by kevin-brown** [comment]
Duplicate of https://github.com/select2/select2/issues/4472. Going to reopen that one and let it go through a stale cycle to see if there's still enough interest.
