### ISSUE TITLE
When Dropdown is open in Bootstrap model can not able to scroll 

### ISSUE THREAD

**Issue by pixlogix** [select2/select2#6056]
We have used select2 in Contact form 7's  select box as a dropdown in the modal popup of Bootstrap, but when we open the dropdown then we can not scroll the model up or down 
 in page work fine but not working on a model
[Video](https://share.florianmatthias.com/z8uOOkjm) 

Select2 version > Select2 4.1.0

We have also removed all `tabindex=-1` from the modal.

https://www.harrys-home.com/service/harrys-home-tour/

**Comment by PaolaRuby** [comment]
What version of jquery are you using? 
I had similar problems with jquery 3.6 but downgrading to 3.5.1 makes select2 work again

**Comment by pixlogix** [comment]
@PaolaRuby > We are using  jQuery version >  jQuery v3.5.1

**Comment by kevin-brown** [comment]
Most likely a duplicate of https://github.com/select2/select2/issues/5800.
