### ISSUE TITLE
When select2 is open in Bootstrap Modal can not focus for write and search on jquery 3.6

### ISSUE THREAD

**Issue by PaolaRuby** [select2/select2#6057]
**Steps needed to reproduce**
After open a modal, open the select2 component, and try to write on search box
**Versions**
Jquery 3.6
Twitter Bootstrap 4.6
Select2 4.0.13(and also 4.1.0.rc)
**--**
Chrome on windows

[https://jsfiddle.net/c81swavr/](https://jsfiddle.net/c81swavr/)
![image](https://user-images.githubusercontent.com/79208489/122939819-91581e80-d339-11eb-81ad-e1d4e9d36e8e.png)

Example with Twitter Bootstrap 5.0.1:
[https://jsfiddle.net/5whmoe9f/](https://jsfiddle.net/5whmoe9f/)

**Comment by fredsal** [comment]
I had the same problem, +1

**Comment by alexv96** [comment]
Were you able to fix it? I have the same problem

**Comment by PaolaRuby** [comment]
@alexv96 #6044

**Comment by manishsxnaa** [comment]
check this 

https://github.com/select2/select2/issues/5993#issuecomment-1030629245
