### ISSUE TITLE
option is not binding when select2 ajax is used.

### ISSUE THREAD

**Issue by pramodDesign** [select2/select2#6058]
Hi,
I used 4.0.3 version early at that time this function worked properly after updated to 4.0.13 has some issue.
**Issue is:**
1. Ajax success its not calling templateResult. When I search for result I get the searching in templateResult but after success its not entering.
2. After ajax success early option from db is adding but now its not adding any result. When I debug I can see the result is returning.

**Adding the code I using:** 

function changeunderlyingCommon(){
	$(".select2").select2({
		minimumInputLength: 2,
		placeholder: 'Select a option',
		ajax: {
			url: 'com/PricingToolQuote.cfc?method=searchUnderlyingAssets',
			type: 'post',
			data: function(key,page){
				return {
					query:key.term,
					type:key._type
				}
			},
			dataType: 'json',
			processResults: function (data) {
				return {
				  results: data
				};
			}
		},
		templateResult: appendFullName
	});
}

//templateResult
function appendFullName (data) {
	if (!data.id) {
	  return data.text;
	}
	var $data='';
	if(data.element.dataset.name !=''){
		$data = $('<span>' + data.text + ' | '+ data.element.dataset.name +'</span>');
	}else{
		$data = $('<span>' + data.text + '</span>');
	}
	return $data;
};

**Comment by pramodDesign** [comment]
response from the ajax call is:
[
   {
      "element":{
         "dataset":{
            "requestedIssuerID":"1234",
            "registrationType":"6",
            "actionname":"REQUESTQUOTEREFRESH",
            "issuershortcode":"x",
            "optlock":3,
            "tradeDate":"June, 22 2021 00:00:00",
            "requestID":"223334",
            "issuerName":"xxxxx",
            "issuerid":708963
         },
         "metadata":{
         }
      },
      "keyName":"REQUEST_QUOTE_REFRESH",
      "text":"Request Refresh",
      "title":"",
      "id":445,
      "class":""
   }
}

**Comment by PaolaRuby** [comment]
Hard to read, why don't use **insert code** like this:
```
{
     "test1" : 1,
     "test2" : 2,
}
```
Also make a example and link to a [minimal, complete, and verifiable](https://stackoverflow.com/help/mcve) example by cloning [http://jsbin.com template](http://jsbin.com/goqagokoye/edit?html,js,output) or using [https://jsfiddle.net/](https://jsfiddle.net/) .

**Comment by pramodDesign** [comment]
@PaolaRuby Got issue its something related to response got from backend. In backend "element":  is adding so it conflict with select2 some conditions. 

Thanks @PaolaRuby  for responding. Closing this issue.
