### ISSUE TITLE
Greek punctuation tone as separate character when using Tagging and Multiple 

### ISSUE THREAD

**Issue by decodernt** [select2/select2#6063]
Greek punctuation tone is inserted as separate character on select2 when using tagging and Multiple on same field. This happens only after the first letter. The first letter accepts the tone, if necessary, but after that tone is inserted as new character. Like this:

Actual greek word: Βοήθεια
How is inserted: Βο΄ηθεια

On first letter: Έλεγχος (Correctly inserted)

https://stackoverflow.com/questions/65644486/select2-problem-with-new-tag-on-greek-punctuations

**Comment by TeoMastro** [comment]
Hello, I have the exact same problem with greek accents. Can this issue be re-opened?
