### ISSUE TITLE
Instructions for manual installation do not work

### ISSUE THREAD

**Issue by roschler** [select2/select2#6066]
I tried the `npm` method for installing _select2_ manually as per the docs on the GitHub repo for the newest release candidate that I could find:

https://github.com/select2/select2/packages/33875?version=4.1.0-rc.0

But it fails:
```
$ npm install @select2/select2@4.1.0-rc.0 --save

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@select2%2fselect2 - Not found
npm ERR! 404 
npm ERR! 404  '@select2/select2@4.1.0-rc.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

As you can see there doesn't seem to be a package like that in the NPM registry.  I'll try downloading the source directly and using the "dist" directory.

**Comment by kevin-brown** [comment]
The package is available at `@select2/select2` on the GitHub Package Manager and at `select2` on NPM. The GitHub docs mention how to install from GPM at https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry which is linked on the page you provided.
