### ISSUE TITLE
Option 'ajax' is not allowed for Select2 when attached to a <select> element

### ISSUE THREAD

**Issue by ammasum** [select2/select2#6074]
HTML
`<select class="select-2">`

JS
`$('.select-2').select2({placeholder: '....', ajax: {...some code}})`

Showing error
"Option 'ajax' is not allowed for Select2 when attached to a <select> element"

Basically it means you can't use select2 ajax in select element. But what im using is yii widget, it's default rendering select element.

**Comment by kevin-brown** [comment]
The version of Select2 that you are using is from the 3.x line which is _at least_ 6 years old if not more. Please upgrade.
