### ISSUE TITLE
Select2 jumps/moves around on screen when clearing selected value

### ISSUE THREAD

**Issue by amilo2003** [select2/select2#6080]
Please see below for screenshots. When running in screen resolution 1366x768 the behavior manifests. On higher resolutions it does not occur.

Using Bootstrap 4.6, jQuery 3.5.1, select2 4.0.13

Data is loaded via Ajax

Running this command trigger the change: 
$("#item").val(null).trigger('change')

Before:
![image](https://user-images.githubusercontent.com/22910072/129721551-434c1411-9099-4e5a-b0a3-c473ff28cdd7.png)

After:
![image](https://user-images.githubusercontent.com/22910072/129721657-680e7938-6028-4686-ae7c-a57469d73c43.png)

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by amilo2003** [comment]
We can longer simulate behavior after changing $("#item").val('').trigger('change') to $("#item").val(null).trigger('change').
