### ISSUE TITLE
Only a subset of options are being added as tag

### ISSUE THREAD

**Issue by antonioaltamura** [select2/select2#6098]
Maybe this is not a proper bug, yet I think it is something you want to take a look at.
I'm struggling with the integration in LitElement of Select2. The problem is too often you get caught into inconsistent states when the UI shows a list of tags and the underlying state of the component is different. 

This is one of those cases.
I have the main component that renders a `SelectTokenFilter2` (`select2` select) component. The main component sends a list of default values to the child component.
You can see by clicking on the button "default values", only four of them are rendered as tokens.
https://stackblitz.com/edit/rqoqkl-3hjdi5?file=select-token-filter2.js
Why is that?

Video:
https://www.awesomescreenshot.com/video/5300246?key=530caf8fb35ed3a0c75ca18a73be1584

**Comment by kevin-brown** [comment]
This has to do with your use of `.val()` to select the option which only works if you pass in all options that need to be selected. Since you're already querying for the `<option>` to see if it exists, you can just set the `selected` property on it which will get the job done.
