### ISSUE TITLE
Screen resize via media queries or manually makes Select2 go crazy

### ISSUE THREAD

**Issue by hn1** [select2/select2#6103]
We are trying to use Select2 with Bootstrap in a Modal. We have specified the parent attribute but when the screen is resized 

1. Select2 will not stay open for a user to tyoe in the search box.
2. The positioning of the dropdown goes all over the place and gets hidden from view

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by hn1** [comment]
hi
All you need to do is palace a Select2 in a Bootstrap 3 Modal. If the
content of the modal is scrollable and you scroll, the Select2 loses its
positioning.
We are using the latest of everything and testing in Chrome.
Thanks

**Comment by hn1** [comment]
Hi
S|orry, we cannot show this issue on any examples in the doc as the docs do
not include an example using a BS3 Modal Dialog.

**Comment by hn1** [comment]
Hi
I am sorry to have to say this, but although I appreciate that this widget
is free, the developer community expects open source software to be of a
high quality.

We spent several hours trying to make this widget work, but it was
completely useless in many scenarios.

How long has this widget been under development? It seems for a long time
and if it cannot do a simple thing as maintaining its correct position on
an HTML page, then it's time to Dump it and not waste people's time - even
if it is free.

Please print in big letters that this widget is *NOT FIT* for production
scenarios and should only be used by amateurs who are trying to learn
programming.
