### ISSUE TITLE
templateSelection executes again after triggering change, wiping the custom attributes set by it earlier.

### ISSUE THREAD

**Issue by github-rage** [select2/select2#6104]
Hi,

I'm using select2-4.0.13. My goal is to display the selected options with colors assigned to them by an id from elsewhere. My code works manually, during browsing the page, but fails after loading, populating the select programmatically, setting the selected ones and triggering a change event.

I found out that the 'templateSelection' code block executes first, then the 'change', and for some reason after that the 'templateSelection' again, this time resetting all my previously added formatting.

I've condensed down the code and added console.log messages and an alert message for blocking, to visualize what's happening. It's all fine up until the alert, but clicking ok lets the templateSelection function run again. I experience this behaviour only after page load, then it's fine manually.
You can see a demo here: http://dev.rage.xyz/select2issue/

My only solution was to create and reset a timer in the templateSelection function to color the tags after the last iteration of the function call is finished.

This doesn't feel like desired behaviour to me. Is there something I'm missing or is this a bug? Any help would be welcome.

Thank you!

<img width="1036" alt="mid" src="https://user-images.githubusercontent.com/49040481/135868223-80308643-f135-4e44-90c8-f9d6f80b568b.png">
<img width="933" alt="post" src="https://user-images.githubusercontent.com/49040481/135868232-47ed0eae-c4d4-4e4a-8933-cbf82fe99cac.png">

**Comment by kevin-brown** [comment]
If you're looking to add templating and styling to your elements, that's exactly what `templateSelection` is for. Don't try to add it on after the fact, you're doing twice the work for no extra gain.

**Comment by github-rage** [comment]
Thank you for your time!

I agree with you that it's not a nice approach. My reason for that is I could only set a background color for the added **span** and not it's parent **li** from there, which leads to a colored box around the text. My solution is to assign ids to the options in templateSelection and then look up the rendered **li** elements containing those ids after in the onChange to set the backgrounds.
But that does not work well for some reason, given that it executes twice and resets my changes.

Could you point me in the direction where I can find info about how to color the displayed select options' backgrounds entirely, individually, like the yellow in my original post's screenshot?  Can't seem to find anything on it, neither a way to accomplish this from templateSelection.

My goal would be to have them colored by their category id in the database. Won't bother you again with this, thanks a lot again.

<img width="945" alt="Screenshot 2021-12-05 at 16 27 22" src="https://user-images.githubusercontent.com/49040481/144752902-75d20b14-7060-4b3d-b877-277e1d6e8b8a.png">

**Comment by kevin-brown** [comment]
> Could you point me in the direction where I can find info about how to color the displayed select options' backgrounds entirely, individually, like the yellow in my original post's screenshot? Can't seem to find anything on it, neither a way to accomplish this from templateSelection.

I believe there is a second parameter passed into `templateSelection` which contains a reference to the `<li>` that you're looking to style. This is probably the best way to do what you're trying to do.

https://github.com/select2/select2/blob/5c38f186c98d793c7d396442986191ca05634d0a/src/js/select2/selection/multiple.js#L83

**Comment by github-rage** [comment]
There indeed is - works like a charm! I didn't get into browsing the source, sorry for missing that. My only remaining question is where is the donate link to get you a beer, because I can't seem to find that either :D 

Thanks again for everything.
