### ISSUE TITLE
Selecting Existing Tag With Mouse Removes It

### ISSUE THREAD

**Issue by jcampbell05** [select2/select2#6108]
1. See example here https://select2.org/tagging#tagging-with-multi-value-select-boxes
2. When typing a tag which already exists and hitting enter then it won't be added. But if you type a tag and click with the mouse it will remove the existing tag rather than doing the same thing as the keyboard.
3. Ideally clicking the tag in list of tags should do same thing as the keyboard

**Comment by kevin-brown** [comment]
Clicking the item in the results list toggles it, just like what happens if you toggle using the keyboard (CTRL + SPACE). This is by design to align with WAI-ARIA accessibility standards for how select boxes should work.
