### ISSUE TITLE
Allow for dynamically disabling options in custom matcher

### ISSUE THREAD

**Issue by philipboeken** [select2/select2#6109]
I have a usecase where I want to match certain options, but make them disabled. This does not work when using a custom matcher callback which may mutate an option by setting `disabled: true`:

```
function matchCustom(params, data) {
    if ($.trim(params.term) === '') {
        return data;
    }

    if (typeof data.text === 'undefined') {
        return null;
    }

    if (data.text.indexOf(params.term) > -1) {
        return data;
    } else if (someOtherCondition(data)){
        return Object.assign({}, data, {disabled: true})
    }
}
```

A possible workaround is spoofing an external data source, and apply the custom matcher like so:
```
const dataArray = [ ... ]

$('#foo').select2({

//  This is what you want ideally:
//  data: dataArray,
//  matcher: matchCustom, 

//  Workaround:
    ajax: {
        transport: (params, success, failure) => {
            success({
                results: data.map((option) => matchCustom(params.data, option)).filter(x => x)
            })
        }
    }
 })
```

However, this isn't ideal.

**Comment by kevin-brown** [comment]
The issue here is that your data options will have an element set, so Select2 defers to that element to determine the disabled status. I would recommend setting `option.element.disabled` in addition to `option.disabled`.
