### ISSUE TITLE
Custom id property in local array

### ISSUE THREAD

**Issue by andriijas** [select2/select2#611]
Hi

Copied this example from documentation

 $("#e10_2").select2({
            data:{ results: data, text: 'tag' },
            formatSelection: format,
            formatResult: format
        });

would be cool if it could be extended to something like this:

 $("#e10_2").select2({
            data:{ results: data, text: 'tag', id: 'customId'},
            formatSelection: format,
            formatResult: format
        });

thanks

**Comment by gsouf** [comment]
It appears that this does not work anymore in version 4
