### ISSUE TITLE
Jumping form after click when select is out of view

### ISSUE THREAD

**Issue by knollengewaechs** [select2/select2#6115]
In a scrollable form with the select field at the top of the page: 
If I select an option in the select (the select is thus focused), scroll down in the form until the select is out of view and then click anywhere, the view jumps back to the select which has now lost focus.
https://output.jsbin.com/cosocudiqe (seen in Chromium)
I would expect the view not to jump.

**Comment by dmmishchenko** [comment]
Me too meet this problem. @kevin-brown can you investigate this?

**Comment by dmmishchenko** [comment]
problem still existed

**Comment by Garnet-Fox** [comment]
Problem is here
// This needs to be delayed as the active element is the body when the
      // key is pressed.
      window.setTimeout(function () {
        self.$selection.trigger( 'focus' );
      }, 1);

**Comment by dmmishchenko** [comment]
> Problem is here // This needs to be delayed as the active element is the body when the // key is pressed. window.setTimeout(function () { self.$selection.trigger( 'focus' ); }, 1);

interesting, can you create a pull request?

**Comment by richardebeling** [comment]
@kevin-brown this bug is still present in 4.1.0-rc.0 and, judging by commit messages since then, also in current develop. Could you please reopen?
