### ISSUE TITLE
Select2 always adds an empty value

### ISSUE THREAD

**Issue by heaven** [select2/select2#6117]
My options are `["one", "two"]`, when I submit the form on the server I get `["", "one", "two"]`, when nothing is selected I get `[""]`. Should not add an empty option and if nothing is selected should submit an empty array.

Select2 version 4.0.13.

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- Can you reproduce this issue [on any of the examples in the docs][examples]?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/.github/CONTRIBUTING.md#asking-for-help
[examples]: https://select2.org/
[test-case]: https://css-tricks.com/reduced-test-cases/

**Comment by mhabsaoui** [comment]
I Think I had similar issue => Maybe your declaration of Select in HTML file isn't right : You added an empty option inside your select tag like this ?
![image](https://user-images.githubusercontent.com/18755135/146539013-ed3462f8-6510-425b-9360-b5f5b9a0ad55.png)

If yes, you shouldn't for Multiple Select2 type according to Documentation...

**Comment by amfriedman** [comment]
This StackOverflow answer will solve your issue, for both single and multi-selects. Basically, when using a multi-select, you do remove the empty `<option>` but you need to ensure you add the `multiple` attribute to the `<select>` tag. Then this bug will go away.
https://stackoverflow.com/a/52297523/640113

**Comment by akhil-maddukuri** [comment]
> This StackOverflow answer will solve your issue, for both single and multi-selects. Basically, when using a multi-select, you do remove the empty `<option>` but you need to ensure you add the `multiple` attribute to the `<select>` tag. Then this bug will go away. https://stackoverflow.com/a/52297523/640113

Ran into this issue today, I'm getting my options from a ajax source and I've checked that there are no empty options coming in, so i just added the `multiple ` attribute to the `select ` tag as suggested in the StackOverflow solution but still I'm unable to get this resolved. Below is my code, any help would be appreciated

```
$("#selectBrands").select2({
    placeholder: 'Brands',
    width: '100%',
    multiple: true,

    ajax: {
        url: 'myurl',
        dataType: 'json',
        type: "GET",
        data: function (params) {

            var queryParameters = {
                term: params.term
            }
            return queryParameters;
        },

        processResults: function (data) {

            return {
                results: $.map(data, function (item) {
                    return {
                        text: item.BrandName,
                        id: item.BrandId

                    }
                })
            };
        }
    }

});

$('#selectBrands').attr('multiple', 'multiple');
```

**Comment by Tressa-Sanders** [comment]
> > This StackOverflow answer will solve your issue, for both single and multi-selects. Basically, when using a multi-select, you do remove the empty `<option>` but you need to ensure you add the `multiple` attribute to the `<select>` tag. Then this bug will go away. https://stackoverflow.com/a/52297523/640113
> 
> Ran into this issue today, I'm getting my options from a ajax source and I've checked that there are no empty options coming in, so i just added the `multiple ` attribute to the `select ` tag as suggested in the StackOverflow solution but still I'm unable to get this resolved. Below is my code, any help would be appreciated
> 
>
>




I have this issue as well using Ruby on Rails 8 and the Simple_Form gem. I'm just using an options_for_select for the data and still keep getting a blank ["","Basque","English","French"]

`<%= f.input :languages_spoken, collection: language_options, input_html: { class: "select2 form-control select2-multiple", data: { toggle: "select2"} }, label: false %>`

`jQuery().select2 && $('[data-toggle="select2"]').select2({
    multiple: true,
    maximumSelectionLength: 6,
    selectOnClose: false,
    placeholder: "Select or search languages...",
    allowClear: true,
    tags: false,  // prevents custom entries
    width: '100%'
});`

I'm using simple_form with Rails 8. I have also added include_blank: false and include_hidden: false to my input field and still I get the blank.


UPDATE: I fixed it. I had to change my input to this:
<%= f.input :languages_spoken, collection: language_options, input_html: { multiple: true, class: "select2 form-control select2-multiple", data: { toggle: "select2" } }, include_hidden: false, label: false %>
