### ISSUE TITLE
Scrolling dropdown selects wrong option

### ISSUE THREAD

**Issue by aarontgrogg** [select2/select2#6121]
`select` has multiple `optgroup` elements, each with at least one `option`.

When the dropdown opens, I select an option, works fine.

When I open the dropdown again, if I scroll to see other options, and select one that is now in the same "position" as the previously-selected option (i.e. third from the top in the scroll view), sometimes the selection is not recognized (as if the code thinks there was no change), and other times the item that _was_ in that location, before the scroll, is selected (as if the code doesn't realize the scroll happened).

Not sure how to better explain this, but the issue can be seen on this URL:
https://www.finditguide.com/properties
Check "Near Installation", then use the "Choose an Installation" dropdown.

Quick video:
https://user-images.githubusercontent.com/366755/141261597-8338111f-cb08-4a60-a936-dfaf675f3e92.mov

Screenshots:
<img width="707" alt="fig-select2-1" src="https://user-images.githubusercontent.com/366755/141261328-50cb0058-dd1e-4169-a45d-6e674ada4a98.png">
<img width="711" alt="fig-select2-2" src="https://user-images.githubusercontent.com/366755/141261331-209213b3-478f-4ec1-bbad-69e639218cf9.png">
<img width="709" alt="fig-select2-2b" src="https://user-images.githubusercontent.com/366755/141261336-11664e57-5c1b-41a9-b9a2-cb1e67514bf8.png">
<img width="709" alt="fig-select2-3" src="https://user-images.githubusercontent.com/366755/141261344-bfcf1579-648c-46c5-96e4-c85c12f92dbd.png">
<img width="710" alt="fig-select2-3b" src="https://user-images.githubusercontent.com/366755/141261346-6c9554fc-7118-4e86-bfad-3bb28aa5e040.png">

**Comment by kevin-brown** [comment]
If you long press (don't release the mouse wheel) you can see that something is interacting with Select2 and forcing the dropdown to smoothly scroll up. This is what is causing the wrong option to be selected. I'd check out any other plugins you may be using to see what one is causing this.
