### ISSUE TITLE
Trigger paginated AJAX results when selections are hidden

### ISSUE THREAD

**Issue by CameronKolick** [select2/select2#6125]
To preface, we are getting our data for the select2 via AJAX.

Our users do not want to see the options they already have selected to show up in the drop down. For years, we've had the following in our CSS file.
`.select2-results__option[aria-selected=true] {
    display: none;
}`

This has never been a problem until we started allowing paginated results. For instance, if we have the paginated results set to 15 items per pages, you scroll down to the bottom of the first 15 and it loads the next 15. This works great until the user selects the first 15 items and wants to select more. When clicking the select2, it opens the dropdown with "Loading More Results..." but it never actually fired the AJAX call. My guess is that the code doesn't know that we are at the bottom because maybe the event to load the next page wasn't triggered because there isn't a scroll bar? I'm not entirely sure. 

All-in-all, it would be nice if there was an option for multiple selects that will allow already selected items to be hidden but let the AJAX still fire when at the bottom of the list. 

I noticed there are some old issues in here that are similar to this but couldn't pin point one that would resolve my issue. If I'm simply missing something that was already answered, can you please link me to the fix? In the meantime, we've increased the results per page to a number that minimizes our users from running into this but would like to have a permanent fix.

TIA!

**Comment by kevin-brown** [comment]
This is an existing duplicate of this issue somewhere, even though I thought we've fixed it a few times.

> My guess is that the code doesn't know that we are at the bottom because maybe the event to load the next page wasn't triggered because there isn't a scroll bar?

Yup, that's the exact reason. We only check for more results on scroll (or keyboard move) so if you don't do either of those then it won't know to get the next page.
