### ISSUE TITLE
Cannot unselect by clicking selected when using dataAdapter

### ISSUE THREAD

**Issue by atay** [select2/select2#6128]
When using select2 with `dataAdapter`, the selected option cannot be deselected by clicking it again on list.
If no `dataAdapter` option is used, it works fine, option can be deselected by clicking it second time.

Here's example with a bug I described, you can select any option and then try to deselect it by clicking it again.
http://jsfiddle.net/o53fLqum/

**Comment by kevin-brown** [comment]
I can reproduce the behaviour that you're seeing, I'm trying to trace it down to a bug or something missing in the custom adapter.

----

I upgraded your jsfiddle to use the latest release (4.1.0-beta) and the issue still exists. If I log the value of each result when it is displayed, I can see a few interesting things:

1. When the results are selected, the `<option>` element is properly injected but it isn't being associated with the data option as the `element` property
2. As a result of the above issue, the `selected` property is instead being set on the data object to `true`

And when you try to unselect it

1. The previously created `<option>` still persists (as expected) but is not unselected (unexpected)
2. The `selected` property that was set on the data object is set to `false`
3. An `unselect` event is properly triggered but that is also not attached to the `<option>` but it does have the modified `selected` property

And if you try to select it again

1. The `selected` property that is set on the data object continues to show as `false`

**Comment by kevin-brown** [comment]
Figured out the issue.

The `id` property on data objects _must_ be a string or it won't be able to match up with the `<option>` that is created (since `<option>.value` is always a string). This is why the `element` property isn't getting set as expected on the data object which leads to pretty much the rest of the issues we were seeing. Setting the `id` property to a string in the example jsfiddle solves these issues.

https://select2.org/data-sources/formats#automatic-string-casting

I'm still leaving this open since Select2 _should_ handle this case and automatically cast it, but it looks like something isn't consistently doing that which is causing issues.

**Comment by jonahgreenthal** [comment]
The project maintainer deliberately chose to leave this open, so it should be left open

**Comment by jayaddison** [comment]
@kevin-brown I was taking a look into this separately, and arrived at the same conclusion that the cache lookups for item data fail, resulting in a missing `data.element` property to apply effects to.

At least for a small repro case, there's an alternative solution that doesn't rely on `id` type-casting -- although it could be a bit hacky (particularly the assumption regarding a single `option` element per container?).

See: https://github.com/select2/select2/commit/82585672888eead67610556baa46bd7d7b35fdcf

Edit: update link to unbreak the commit hyperlink -- please note that it originated from a forked repository, though (not this repository)

**Comment by jayaddison** [comment]
> See: https://github.com/select2/select2/commit/82585672888eead67610556baa46bd7d7b35fdcf

Sorry, ignore this attempt at a fix.  I was testing it again using a hand-written `select2` example, and this time it isn't working (the `option` elements do not exist), so I don't think it's valid.

Edit: update link to unbreak the commit hyperlink -- please note that it originated from a forked repository, though (not this repository)
