### ISSUE TITLE
Add variables to your SASS files

### ISSUE THREAD

**Issue by macmichael01** [select2/select2#6133]
The purpose of writing SASS is to give you the flexibility of quickly adjusting styles through variables. Without those variables it makes it incredibly difficult to adjust style settings.

**Comment by jonahgreenthal** [comment]
I don't care whether Select2 starts using variables in its SASS files (though I think it should be a low priority at best), but that's a very overly reductive view of "the purpose of writing SASS". SASS has plenty of other benefits, like nesting selectors, other syntax extensions like `&`, mix-ins, imports, and calculations—and not caring about one of the benefits does not mean the purpose is missed.

**Comment by macmichael01** [comment]
I used this library on a project recently and found that it was very difficult to stylize. I ran into css selector hell where the solution was to override the default classes and selectors defined in the SASS files. Not ideal. I am a firm believer in templatizing SASS through the use of variables for projects like these. My overly reductive view on SASS was to point out what was missing. I have to imagine this is a widely used project. Thanks for the response and the project!

**Comment by kevin-brown** [comment]
This is something we've considered and as far as I know, nobody is particularly opposed to it. Just it's so low on our priority that it's more likely to be done by a contributor (maybe you!) via a pull request than the core team.

So with that said, we welcome pull requests that add reasonably named variables (Bootstrap used to be the one to align with, no idea who nowadays) and I'll gladly review them.
