### ISSUE TITLE
Unselect by X AllowClear, is not catched by originalEvent / single selection

### ISSUE THREAD

**Issue by lenamtl** [select2/select2#6138]
Hi,

I'm looking for a way to detect user action vs programmed action.
How can I catch if the user click on the X to unselect an item (AllowClear)?
Note I'm using single selection

```
$('#myfield').on('select2:select', function(e) {
	   
	   if(e?.params?.originalEvent?.originalEvent) {
		  console.log('user action');
	   } else {
		  console.log('program action');
	   }
});
```

I have also tried the following with no luck as program action is the result for both case and I trigger the AllowClear manually
si this mean no originalEvent evt is attached to it
```
$('#myfield').on('select2:select', function(e) {               
  if(e?.params?.originalEvent?.originalEvent) {                     
      console.log('user action');               
} else {         console.log('program action'); }   });

```

This is similar to this fix 
https://github.com/select2/select2/pull/6079/commits/0909d8c8f3656ceb8508dbfacb30138dd029e609

**Comment by uh-zz** [comment]
I have same problem...
