### ISSUE TITLE
disabled select2 still applying select2-container-active class when clicked

### ISSUE THREAD

**Issue by Zxurian** [select2/select2#614]
if you set a select2 element to disabled using $(element).select2('disable'), it will disable the select2 box, however you can still "click" the box, and the container gains the class "select2-container-active".

if a select2 box is disabled, then clicking in it should not do anything and just return false from the click handler.

My temporary fix was to apply the following line at ~1533

``` javascript
selection.bind("focus", this.bind(function() {
    // if the container is disabled, then intercept the click and return false
    if (this.container.hasClass('select2-container-disabled')) return false;
    this.container.addClass("select2-container-active");
    // hide the search so the tab key does not focus on it
    this.search.attr("tabIndex", "-1");
}));
```

**Comment by fbengo** [comment]
Why is this still not solved?
