### ISSUE TITLE
Select2 tag field will add duplicate characters when typing double byte characters on Chrome

### ISSUE THREAD

**Issue by Firedust** [select2/select2#6144]
Hi,

I'm seeing an issue with my select2 fields that also have tags enabled. 

The input is a bit laggy and will cause duplicate entries when you switch from English to Japanese keyboard (Hiragana IME options).

Steps are:
1. Type English characters in the field
2. Change keyboard to Japanese 
3. Type different Double Byte characters and alternate between them
4. Notice duplicate characters being entered.

This only happens with Chrome. Firefox is quick and free of issues.

Select2 4.0.7

Thanks.

**Comment by kevin-brown** [comment]
> Select2 4.0.7

Please try using the latest version of Select2 and let us know if this issue still exists. Select2 4.0.7 is many years old now.
