### ISSUE TITLE
Select2.org unavailable

### ISSUE THREAD

**Issue by OscarKolsrud** [select2/select2#6152]
Hi,

Documentation (https://select2.org/) and forums (https://forums.select2.org/) are currently giving error 523 in Cloudflare which causes them to be unavailable due to to web host not being reachable by the Cloudflare proxy.

![image](https://user-images.githubusercontent.com/30559109/161524572-932d14ef-6fc6-4ca5-aa75-0c6f8ccd9abf.png)

**Comment by TheRichCourt** [comment]
Fro anyone who needs the docs now, theys do seem to also be in this repo, though they're a little trickier to navigate here https://github.com/select2/select2/tree/develop/docs/pages

**Comment by kevin-brown** [comment]
They're back up. Server went offline for a little overnight.

**Comment by whiplashoo** [comment]
Docs page is now failing with 522 and 523 errors:

![image](https://github.com/select2/select2/assets/9117427/c01ccc03-7f19-45de-b30d-23a5b55507fd)

**Comment by kevin-brown** [comment]
Appears to be back online for me.

**Comment by gioy** [comment]
Hi, there.

~the website is unreachable since a few days (at least).~

Now it's working!
