### ISSUE TITLE
Typing in the search input causes creation and selection of a new option

### ISSUE THREAD

**Issue by filzy** [select2/select2#6206]
### jsFiddle:
https://jsfiddle.net/6fo372ju/

### Description:
Typing in the search-field, when `tags` is enabled and no option exists, causes the creation and selection of a new option with the first typed character as value. 

![select2](https://user-images.githubusercontent.com/117441045/206186075-6193550e-494c-447c-b490-2f0d6fe1044d.gif)

### Steps to reproduce
1. Initialize `select2` with `tags: true` and without options or see the [jsFiddle](https://jsfiddle.net/6fo372ju/)
2. Write something into the search-field

**Comment by kevin-brown** [comment]
This unfortunately is not a bug, it's a side effect of how the browser handles options being created under the hood. If you make use of a placeholder option then this doesn't happen.

**Comment by JacobLuckhardt** [comment]
If it is a side effect of the browser, why was the behavior different in older versions of Select2?
The above fiddle ( https://jsfiddle.net/6fo372ju/ ) is using Select2 version 4.0.13.
I forked the fiddle ( https://jsfiddle.net/r3kuvt0c/ ) and moved back to Select2 version 4.0.0. As you can see, the behavior was different there.
![Peek 2022-12-08 09-04](https://user-images.githubusercontent.com/48831673/206392381-1355603d-5f28-45e8-8493-acb68ea311f9.gif)
