### ISSUE TITLE
Multiselect input field does not prevent xss input of html event

### ISSUE THREAD

**Issue by kunkav** [select2/select2#6220]
I am using select2 version 3.4.2 when I enter <img src=x onerror=alert("")>ff x , the multiselect accepts the input and an alert box is displayed once I submit the form

**Comment by kevin-brown** [comment]
The version of Select2 you are using is at least 7 years old if not a decade old. Please upgrade.

**Comment by kunkav** [comment]
Hey Kevin, thanks for the reply, I actually updated the version to 4.0.13 but couldn't get this issue solved. I guess it's the latest stable version but that did not resolved the issue and I can still get the html event executed.
