### ISSUE TITLE
The dropdown above the position display is incorrect on the first click

### ISSUE THREAD

**Issue by GalaxyTea1** [select2/select2#6235]
The position display dropdown above is incorrect on the first click, but it works properly on the second click.

![image](https://user-images.githubusercontent.com/66195006/225870387-d6511cce-2d8f-4937-98ef-6c263675140f.png)

I think it's a similar problem to issue 4614, but those workarounds didn't work for me.

Environment

Select2 4.0.13
Edge latest version

Thank you for your help !

**Comment by GalaxyTea1** [comment]
Include: It works fine in the IE environment, but Edge is throwing an error.

**Comment by very-random-man** [comment]
I am also seeing this happening and the workarounds mentioned in https://github.com/select2/select2/issues/4614 don't work for me either.

I've had a play with it and it seems like it is initially working out the top position as if the dropdown was fully populated. I noticed that if you set a fixed height on `.select2-container--default .select2-results>.select2-results__options` then it positions correctly to start with. There is a `max-height: 200px` already set on there which corresponds directly to where the dropdown is positioned I would guess that something is filling the dropdown to start with that is removed after the first use.

**Comment by very-random-man** [comment]
Ok. I've managed to work out what is happening in my situation, so I'll put this up in case it's handy for the OP or anyone else.

The problem was when I applied a `transition-all` to `.select2-dropdown`. The position calculation happens when the dropdown is at the starting width, which was pushed to the max-height value due to the minimum input length message getting squashed into a column of the individual letters.

I fixed this with hidden overflow and fixed width wide enough to handle the message.

```
.select2-dropdown--above {
  overflow-x: hidden;

  .select2-results__options {
        width: 55rem;
   }
}
```

That snippet was extract from other code so you might need some more selectors maybe.

**Comment by GalaxyTea1** [comment]
> Ok. I've managed to work out what is happening in my situation, so I'll put this up in case it's handy for the OP or anyone else.
> 
> The problem was when I applied a `transition-all` to `.select2-dropdown`. The position calculation happens when the dropdown is at the starting width, which was pushed to the max-height value due to the minimum input length message getting squashed into a column of the individual letters.
> 
> I fixed this with hidden overflow and fixed width wide enough to handle the message.
> 
> ```
> .select2-dropdown--above {
>   overflow-x: hidden;
> 
>   .select2-results__options {
>         width: 55rem;
>    }
> }
> ```
> 
> That snippet was extract from other code so you might need some more selectors maybe.

Yep, I fixed the error, but it seems to only apply to certain specific cases. I using display and set width it.
