### ISSUE TITLE
select2 fallback to select default after saving

### ISSUE THREAD

**Issue by mcfaith9** [select2/select2#6248]
I am trying to store my selected options/value using this `@this.call('storeSelectedTag');` and when this trigger and successfully save, my select2 fallback or being reverted to default select state.
```
$('#select').select2({
        placeholder: 'Select an tag\'s',
        templateResult: formatState,
        templateSelection: formatState
}).on('change', function (e) {
       @this.set('tag', $(this).val());
       @this.call('storeSelectedTag');
});
```

**Comment by kevin-brown** [comment]
This appears to be an issue that is not directly related to Select2, but instead is related to an integration or downstream project that is not officially supported by Select2.  It is recommended that you create a ticket at the downstream repository or send a message to the [mailing list][ml] for help.

[ml]: https://select2.org/troubleshooting/getting-help
