### ISSUE TITLE
Bug report: select2-4.0.13 have problem with typing Chinese, plz fix it.

### ISSUE THREAD

**Issue by 016** [select2/select2#6264]
Hi, select2 is good, I am using it for my web project, but I found that when I am using select2-4.0.13 and open tags, after that if I try to typing with Chinese, it's not working. after hours searching and testing, I found that 4.1.0-rc.0 already fixed it, but it's not a pub version, so is it possible live it? or make a new version like 4.0.14?

thx.

**Comment by kevin-brown** [comment]
> I found that 4.1.0-rc.0 already fixed it, but it's not a pub version, so is it possible live it

Just use it. It's been out and in the world for over a year now, you're safe to use it.

**Comment by jonahgreenthal** [comment]
If it's "safe to use", why not release it for real?
