### ISSUE TITLE
Support dynamic container width

### ISSUE THREAD

**Issue by SassNinja** [select2/select2#6271]
Currently the container width is bound to the native select element and only computed on init.

I want the select's width to match the selected option's width so that the container isn't bigger than necessary just because of some long option. There are two possible solutions I can imagine:

1. select2 implements the whole logic, meaning there's a new option (e.g. `containerAutoWidth`) that automatically updates the container's (and native select's?) width whenever the selected option is changed. However I'm aware this might be a bit tricky regarding multi-select.
2. select2 provides access to the rendered container, so that I can update its width on change myself.

The latter would be much easier and simply makes the container accessible (so that you don't need to rely on certain order in DOM). However the former would cover an use case that might be relevant for many people. 

What do you think?

Demo: https://codepen.io/elmerdigital/pen/abPBKyv

**Comment by kevin-brown** [comment]
There's a `width` option that's well documented that I think handles your request? Unfortunately I'm not in a state where I can link to that part of the docs but I'm pretty sure there's a couple demos dedicated to it.

**Comment by SassNinja** [comment]
I've read the [width docs](https://select2.org/appearance#container-width) though it doesn't cover my use case. It just describes how to resolve the width - not a dynamic approach (see my initial codepen)

However I've found a way that works for me (which is NOT described in the docs): I just need to pass an invalid value as width which prevents setting an inline width style. The result is exactly what I need (the container shrinks now when selecting a short option). It doesn't affect the native select though that's not a problem for me.

Solution: https://codepen.io/elmerdigital/pen/KKbazJY

Might be worth adding this to the docs, unless you call it a hack.

**Comment by perpil** [comment]
Setting the width to `style` has this behavior for me and works in your codepen.  Does that work for you?

**Comment by SassNinja** [comment]
@perpil it works implicitly as it falls back to `null` if no inline style is set

Nevertheless the docs don't describe my use case. The point is you could pass "anythingYouLike" and it'll work for me because it falls back to not setting any container width.

Not sure if that's intended though. Since my problem is solved I'm closing this issue.
