### ISSUE TITLE
[FEATURE REQUEST] Mark select2 element with red color when base select element has required attribute

### ISSUE THREAD

**Issue by interduo** [select2/select2#6273]
On first look at the select2 elements You dont know that selection is required or just an option to select.
This is UX regresion comparing to HTML select with required attribute.

I found solution at StackOverflow for this - simple CSS code:
```
select.select2:required + .select2-container .select2-selection--single {
  border-color: #FF0000;
}

select.select2:required:valid + .select2-container .select2-selection--single {
  border-color: black;
}
```

DEMO: https://jsfiddle.net/z2k5roLy/1/

Please add this to dists CSS in propper place.

**Comment by kevin-brown** [comment]
This is exactly what themes are for. Last I checked, the default drop-down for browsers does not have a red border all of the time when it's marked as required, therefore the default theme also doesn't have it.
