### ISSUE TITLE
REQUEST: Select2 identity based on node element or full node address, not on id attribute only.

### ISSUE THREAD

**Issue by gidzr** [select2/select2#6307]
Hi 

I've got a stack of pages with bootstrap tabs.

Each tab repeats code, and each tab has a ```<select id="selectName">``` with the same id name.

### Issue
I've discovered by accident that this interferes with the creation of select2 elements, even when I initiate on a unique selector combination. 

eg. I initiate using a full address like this:
$("#tabA #selectName").select2()
$("#tabB #selectName").select2(). 

I expected that by specifying the combination of ids in a unique address, select2 would 
a) find the correct unique address and initiate select2 (which it does)
b) use the entire unique path $("#tabB #selectName") for internal referencing in the select2 codebase (which it doesn't).

Per page, every select2 select element must have a unique id, even if it's hierarchy/address is different

Because I'm using tabs with repeated code, and have a lot of code, and sharing functions built on this naming convention, I'm hoping not to refactor every select id name and then all the scripts built on select2 values.

### Issues Research
This is a known issue / behavior: 
https://github.com/select2/select2/issues/5767
https://github.com/select2/select2/issues/5501

### Request
Is there a workaround or can you amend the select2 addressing approach so it uses the full address of the element and not just the id of each individual select?

I do understand there's a best practice not to duplicate ids within an html page. I generally follow this 100%, except that it's not practical with tabs which are effectively virtual pages and tend to repeat sections of code, even though the main common code is preferred to be in the header outside of tabs, sometimes if you have 10 tabs, but only 5 have select2 fields, then it's easier to have the same code pasted the select2 into those 5 tabs.

Would it shift the use of the singular id on the select2, to the full node address that's given in the select2 initiator?

ie. $("#tabA #selectName").select2() ----> "#tabA#selectName" becomes the select2 internal id?

The secondary benefit of this approach, is that the naming convention of the select2 becomes transparent to the coder, so when the code is handed over to other coders, and they copy paste code it won't take them half a day to track down the issue. My very first assumption wasn't the lack of unique id, because the id I gave to the select2 method was unique (taken as a whole).

### Testing
Messing around, and after removing ids entirely from the select elements, I no longer have any issues with using the same address for select2 initiation. ie. if I use the same classname on the same page the select2 works as expected. This is  inconsistent with comments from the select2 that select2 internal id needs the select id. If it works with no id, and resolves the issue entirely (ie. I can use the same classname with no conflicts), then it seems that select2 codebase would benefit from abandoning the use of the select attribute id altogether, and allow coders to use select id attributes for other things.

Many thanks

**Comment by kevin-brown** [comment]
> Each tab repeats code, and each tab has a `<select id="selectName">` with the same `id` name.

This is not valid HTML and as such is not something Select2 can properly guard against. The reasoning is outlined in https://github.com/select2/select2/issues/5501#issuecomment-515725611.

I would encourage you to make use of classes to identify different selects instead of IDs if they must be duplicates. Otherwise I would recommend generating unique IDs for all of your form elements. This directly impacts accessibility.

---

I've read your reasoning and while I empathize with the annoyance of the situation, this is not something that we can realistically support, especially because Select2 has to handle cases where it is not yet been inserted into the DOM and thus has no "full path".
