### ISSUE TITLE
[select2 3.2] : bug with many levels with optgroup

### ISSUE THREAD

**Issue by fperie** [select2/select2#631]
Hello,

I use the select2 API in version 3.2.

I would like using many levels (at least 3) and writing as in the example attached with this issue (cf. ![optgroup_with_three_levels.png](https://f.cloud.github.com/assets/1265267/1798/673fdb64-413a-11e2-8d7d-2f17ec4df42e.png))

You can see the result on the screen shoot attached with this issue : ![$RW75L84.png](https://f.cloud.github.com/assets/1265267/1794/fd68a5a4-4139-11e2-9f9b-ddf82dce438b.png).

I found this commit on github : https://github.com/lisandropuzzolo/select2/commit/da414577e8cd52470c16860e3e8c26a2577a8bc8 but it doesn't work !

Have you got an idea ?

Thanks a lot,
F.

**Comment by prajapriya** [comment]
Is there any body who was success in this code
