### ISSUE TITLE
3.5.4 version not on npm (while 3.4.3, 3.4.5, 3.5.1, etc are there)

### ISSUE THREAD

**Issue by rafalsatl** [select2/select2#6319]
As a bit of a follow up to: https://github.com/select2/select2/issues/4040

I'm currently seeing these pre 4. versions on NPM:
3.5.2-browserify
3.5.1-browserify-fix
3.5.1-browserify
3.5.1
3.4.5
3.4.3

While the project I'm currently working on, and would want to manage our dependency on properly, uses 3.5.4

Would it be possible to publish it to NPM to avoid us from keeping it locally (before we upgrade etc - can't afford it now, make breaking changes etc)?

It would help us a lot and would expose the "latest bugfix" of the 3.5 thread via NPM (it would be reasonable given we have 3.5.1 and 3.5.2 there already)

**Comment by kevin-brown** [comment]
3.x is not supported. I'm sorry that you're still making use of it, but the juice isn't worth the squeeze to get it released on NPM.

**Comment by rafalsatl** [comment]
I understand, it's just that the migration is not always easy and to the point a bit... 3.5.1 had 30k downloads just last week and all of these people could benefit from releasing what's already there under 3.5.4 - if you'd be able to reconsider I'm sure it would help out at least a bit before/until all of "us" can upgrade.
