### ISSUE TITLE
jScrollPane

### ISSUE THREAD

**Issue by artemryzhov** [select2/select2#653]
How to combine Select2 with jScrollPane?
http://jscrollpane.kelvinluck.com/

**Comment by sunalive** [comment]
It used to be a simple `$(".select2-choices").niceScroll();` but now `$(".select2-results").niceScroll();` does not work in the same context.

**Comment by StefanHoutzager** [comment]
Anyone tried to get the new select2 4.0.0 to work with nicescroll? http://jsfiddle.net/wpdt3m16/3/ does not apply anymore, eventname select2-open has changed to select2:open (don't know if it occurs at the same moment, anyway the remote data I'm getting have not been put in the list and the normal scrollbar does not yet exist at the moment of this event). class select2-drop-active seems not used anymore (changed to select2-dropdown?).

**Comment by tonvanalebeek** [comment]
@StefanHoutzager Just do this:

$('.classname-of-your-selectbox').on("select2:open", function (e) {
        // bind niceScroll to dropdowns
        $(".select2-results__options").niceScroll({
            cursorborder: 'none' // optional
        });
});

**Comment by StefanHoutzager** [comment]
Thanks Ton, it works!

**Comment by schuma7** [comment]
I'm also using select2 together with nicescroll in my current project. I'm dynamically destroying and recreating select2s based on various criteria and came across the following error once in a while: 

Uncaught TypeError: Cannot read property 'delaylist' of null

I spent a couple of hours tracking this one down and managed to solve it by adding the following listener in addition to the one @tonvanalebeek  mentioned:

```
$('.classname-of-your-selectbox').on("select2:closing", function (
	$(".select2-results__options").getNiceScroll().remove();
});
```

Hope it helps!

**Comment by cromartie1984** [comment]
you don't really need it to remove it (for nicescroll)
