### ISSUE TITLE
select2-2.0 not working, throws no method error

### ISSUE THREAD

**Issue by nstulasi** [select2/select2#66]
I downloaded the new version and  tried to use it but I get the error 

```
     Uncaught TypeError: Object [object Object] has no method 'select2'
```

I am using rails 3.1 and jQuery 1.7.1 . I double-checked the that the right javascript files are included but still nothing. It was working fine with the previous release of Select2 i.e. Select2-1.0

**Comment by mrxrsd** [comment]
[.NET MVC SCOPE]
If you are adding minified version of select2 in your bundle, you need to set "BundleTable.EnableOptimizations = false;"
