### ISSUE TITLE
$.trigger('change') causes e.val to be "undefined"

### ISSUE THREAD

**Issue by bartgloudemans** [select2/select2#678]
Hi there,

There seems to be a difference between triggering the `change` event via the user interface (clicking on the dropdown etc...) and triggering the event by code `$('#select-field').trigger('change');`

The first situation acts as described in the documentation: `e.val` in the change-event callback has a proper value. The latter situation causes `e.val` to be `undefined`.

Here a jsFiddle http://jsfiddle.net/bartg/4f8nj/ demonstrating the difference.

Is this intentional or not supposed to happen?

kind regards,
Bart

On a sidenote:
I can think of a workaround which involves to never rely on `e.val` but instead to always call `$('#select-field').val()`. Though that results in a string and not a nice array which, has my personal preference.

**Comment by malballah** [comment]
Thank you "AndrewEastwood" your solution works
