### ISSUE TITLE
OPtion ajax is not allowed for Select2 when attached to a <select> element

### ISSUE THREAD

**Issue by zopyx** [select2/select2#679]
I am receiving the error above with Select2 3.2 while calling select2() with the 'ajax' option
specified. I found another issues related to Select2 with a multi select widget but this is not the case here. I have multiple select elements with a pretty long option list and now I am trying to move the code to ajax.

**Comment by suraj04081993** [comment]
For more information refer this link http://itfrustration.in/jquery-select2-ajax/

**Comment by Pushkraj19** [comment]
```
<div class="m-b-15">
    <input id="users" class="select2" name="user">                            
</div>

<script>
$('#users').select2();
</script>
```

This way you can use the select2 without error. Then you can use `templateResult: formatRepo,` and `templateSelection: formatRepoSelection` inside select2() to customize the select2 looks.
