### ISSUE TITLE
Trigger blur when click on a select2 multi-select (input text) if dropdown-results are displayed and searchTerm is empty [and selectOnBlur:true]

### ISSUE THREAD

**Issue by Lytho** [select2/select2#695]
Hi everyone,

Long title for something quite simple to understand...

I'm in a tagging configuration... And I use selectOnBlur:true. Problem is: user cannot hide the dropdown without selecting an option, see http://jsfiddle.net/Lyth_o/8Yea5/2/

It would be cool to add the following behaviour : the user can hide the dropdown if "the input is empty && the dropdown is displayed && he clicks on the input [&& selectOnBlur is true]".

It should not be really hard to implement, I'm not sure though. Don't you think it would be more comfortable?

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
