### ISSUE TITLE
Slow load on large dataset…

### ISSUE THREAD

**Issue by hedefalk** [select2/select2#713]
Hi, sorry to post this as a bug, but I didn't find any mailing list or anywhere to ask.

Anyway, I have quite large datasets on page load, around 5000-10000 elements to select from. I have used Chosen before in similar cases so I figured I could use this one which seems real nice. However, when clicking the select I have to wait around 5-10 seconds before the search input loads (seems about linear to data size). The search is then ok speedwise, but the initial load time makes it unusable for my use case.

Is there any settings or anything that I can do to speed it up?

Thanks

**Comment by webivation** [comment]
I have to agree that as "The jQuery replacement for select boxes" it should be able to be implemented both client and server side regardless of dataset size.  Especially as the web moves more and more to heavily client side development which can partially be seen by the focus in HTML5 on client side data storage.

But regardless of all of that, if it was a "that's not possible" we would be understanding that its a limitation which just hasn't been overcome.  But if it HAS been overcome as can be seen with Chosen, it seems strange that the developers of Select2 would be so resistant to implementing it.

**Comment by kevin-brown** [comment]
Merging into https://github.com/select2/select2/issues/781.
