### ISSUE TITLE
Collapse/expand optgroups

### ISSUE THREAD

**Issue by smartcorestudio** [select2/select2#730]
It's not an issue - just a feature request.
I think, adding support for expandable optgroups can be useful in some situations. With this feature enabled we'll see only optgroup labels at first. And after clicking the optgroup header it will expand to show all it's options

**Comment by pdwjun** [comment]
add the function under below. $(document).ready is not working
$(window).load(function() {
    $('.select2-results').on('click', 'li', function(){
        if($(this).find('li').is(":visible"))
            $(this).find('li').hide();
        else
            $(this).find('li').show();
    });
});

**Comment by pirasterize** [comment]
$('.select2-results').on('click', 'li', function(){
        $(this).find('li').toggle();
    });

**Comment by dannyxu2015** [comment]
@pirasterize Great!

**Comment by lonlie** [comment]
Hi guys, This is my solution, Hope it's useful.
https://github.com/lonlie/select2tree

**Comment by ledes** [comment]
Toggling works, but if you keep the dropdown open after a selection(`closeOnSelect: false`), the group toggles when selecting one of the options.
Any idea about how to toggle the children ONLY when click on the group name?

**Comment by hackartisan** [comment]
This would be a nice option to add to the core library.

Adding collapsed options on the open event does work, but the scrolling behavior (when the dropdown is reopened after one or more values have been selected) is confusing and much more difficult to override.
