### ISSUE TITLE
Dropdown closes on window resize

### ISSUE THREAD

**Issue by Saturate** [select2/select2#776]
It is a feature that select2 closes all open windows on resize. I really don't get why it does this, and I am having a problem with this feature.

I need to have select2 in a iframe, this is due to Sharepoint - and there is no way around this. Sometimes select2 might make the page taller when opened, and as it is a iframe it needs to resize it self. This works great with the system I build, but it will trigger the resize event, when I change the height of the iframe.

Right now I just unbind the event on the open event, but why is this feature there in the first place? Everything works excellent without it. What would you think about a setting boolean that could disable this?

**Comment by fagnerdireito** [comment]
something new to solve this problem dropdow because in my app still happens this problem, for example, when the dropdown is closer than it closes footer alone and does not open.

I'm using version Version: 3.4.5

**Comment by kevin-brown** [comment]
> I'm using version Version: 3.4.5

Update your version and see if we fixed it, 3.4.5 is _really old_.
