### ISSUE TITLE
readonly != disabled

### ISSUE THREAD

**Issue by mvrhov** [select2/select2#778]
The PR #293 introduces a bug by disabling a parent select. By disabling a select we are also instructing a browser to not include the value of that select/input into the data submitted to the server.
Which also means that if you validate all inputs on the server side that validation will fail!

**Comment by Gutek** [comment]
its time to reopen it as this is not working in 4.0

**Comment by coscho** [comment]
This is a very big issue indeed, DATA IS NOT SUBMITTED IF DISABLED ... any solved by now? 

Thank you.

**Comment by kikonen** [comment]
I was jus hit by this, i.e. field is supposed to be readonly (not disabled) in UI, but for select2 it doesn't work.

**Comment by tstrijdhorst** [comment]
I'm also having the same problem. Readonly is not working and disabled is not sending the data.

**Comment by kevin-brown** [comment]
> its time to reopen it as this is not working in 4.0

It was dropped in 4.0 because a `<select>` has no concept of "read-only".
