### ISSUE TITLE
Multiple select + search

### ISSUE THREAD

**Issue by bjeanes** [select2/select2#78]
I can't see anything in the docs or the examples that show how you can have a multi-select box that still has a keyboard-searchable list. Is this possible?

**Comment by sngrl** [comment]
How can I make it with v.4.0?

**Comment by PlippiePlop** [comment]
Try to add option: minimumResultsForSearch:  1,
or change from -1 to 1

**Comment by vimalvaghasiya** [comment]
how to enable search box not only searching ?

**Comment by KodyKendall** [comment]
> yes, see here: http://ivaynberg.github.com/select2/#multi

This link is broken
