### ISSUE TITLE
Select2 is slow on opening

### ISSUE THREAD

**Issue by MgSam** [select2/select2#781]
I'm finding Select2 is quite slow when opening its dropdown menu if the underlying select has a fair number of items. Am I right in guessing it is (re)creating the HTML/DOM for this dropdown each time it is invoked? Wouldn't it make more sense to cache this and only redraw it if the underlying select changes?

Here's an example:
http://jsfiddle.net/48wFG/1/

Thanks in advance.

**Comment by webivation** [comment]
Still seeing a slowdown (4.0) on over even a thousand datasets (using templates for results, which i'm sure adds to overhead).

What about a user friendly loading view?  As soon as the user clicks show the dropdown with a loading gif, then when the data loads replace said gif with the data?

If would support large amounts of data being a little sluggish without confusing the user as to if anything is actually happening or not.

**Comment by kevin-brown** [comment]
I'm a fan of the idea of displaying some sort of "loading" message when Select2 is processing the results, I'd even be willing to make it the default behaviour when Select2 is running slow.

If someone gets a pull request going for it, we can discuss the idea in more detail.

> As soon as the user clicks show the dropdown with a loading gif, then when the data loads replace said gif with the data?

Right now we have a "Seaching..." string which we use for this (with AJAX, usually) that I wouldn't mind bringing to a standard `<select>` if possible.

We dropped the old spinner gif while removing external image dependencies from Select2, and I'd rather keep it out.

**Comment by webivation** [comment]
That sounds ideal, keeping the two UI experiences the same regardless of datasource.  I'll look into that with my changes and make a pull request for it once I'm done for you to review.

**Comment by fk** [comment]
Here's an issue tracking the missing loading image/spinner GIF: #3227 – I'll add my (incomplete) thoughts regarding the loading image over there.

**Comment by gos-sebastian** [comment]
I saw you jsfiddles like (http://jsfiddle.net/uLqc9/4/) however I have problem with <select>. How to implement this lady load with <select> and >100 options. I have issue when trying to test by emulate IE<11 in IE Developer Tools. For IE 11 works fine

**Comment by Sohorev** [comment]
Select2 slowly on 1000+ items
But chosen not slowly

**Comment by sirNemanjapro** [comment]
+1

**Comment by galeroy** [comment]
It looks like upgrading to Select2 Version 3.5.3 improves speed for large lists.

What's not easy for me to find by looking around on the web:
What is the minimum version of AngularJS needed to support Select2 Version 3.5.3?

Thanks!

**Comment by JonathanVandal** [comment]
I got 2000+ item in my select and I got this lag again.
I upgraded from 4.0.3 to 4.0.13.
Do you have a solution for this ?
