### ISSUE TITLE
Set selected items before ajax data is loaded

### ISSUE THREAD

**Issue by MelvinSE** [select2/select2#786]
Forgive me if I'm missing something in the documentation about using the Ajax functionality, but I haven't been able to figure this out.

On my invoice web page, a user can select multiple items from a list.  Each item has an ID and a name (text).  The selected items are stored in the invoice database record as an array of IDs (no related text).  When loading an existing invoice into the page, all I have in the data is the array of item IDs when setting the value of the select2 control.

I have the select2 control hooked to a hidden input that uses an ajax call to populate the items.

```
$('#item_list').select2({
    placeholder: 'Choose items',
    allowClear: true,
    multiple: true,
    ajax: {
      url: "/api/lists/items.json",
      dataType: 'json',
      data: function (term, page) {
        return {
          type: $('#itemType').val(),
          term: term,
          page_limit: 10
        };
      },
      results: function (data, page) {
        return { results: data };
      },
      formatSelection: function(item) {
        return item.text;
      }
    },
    initSelection: function (element, callback) {
      var data = [];
      $(element.val().split(",")).each(function () {
          data.push({id: this, text: this});
      });
      callback(data);
    }
  });
```

The select2 control is nicely populated with item names (text) once the ajax call is invoked on user interaction.

Also, I can use val to set the selected items correctly:

```
// items is an array of IDs [1001, 1002, 1003, etc...]
$('#item_list').select2('val', items);
```

The select2 control displays the item IDs, but it is not showing name of each item.  I understand why, since in the initSelection method it specifically sets the text to the ID

```
 data.push({id: this, text: this});
```

"text: this" is setting the text to the ID because "this" is an element from the array of IDs.
Plus, the ajax call hasn't been made yet so select2 doesn't yet now any of the names of the items.

Storing the names of the items in the database along with the IDs is not preferred since the names can change.  If the names change in the source data, they wouldn't match the stored data and not be selected properly anyway.

After all that, my question is: Is there a way to populate the select2 control (force the ajax call) and then set the selected items (using the IDs) in code?

Thanks for the great library.

**Comment by enginardic** [comment]
I want to select first item by default after ajax loading. So, I must using InitSelection but how to do this ?
