### ISSUE TITLE
Option to auto-select second entry when adding new tag is enabled?

### ISSUE THREAD

**Issue by hailwood** [select2/select2#794]
When creating a new tag is enabled unless a direct match is typed in for a tag the option to create the new tag is the automatically selected option.

We are getting a lot of bogus entries in the database due to users expecting the nearest-match tag to be auto-selected.

I propose the option `autoSelectClosestMatch` which defaults to `false`.
This option will automatically select the second choice in the menu when typing if set to `true` and a direct match has not been typed.

This is what I expect to appear when typing in "scrum" when the "scrums" tag already exists:

![optimal choice][1]

  [1]: http://i.stack.imgur.com/KIkJm.png

**Comment by kevin-brown** [comment]
Closing this off because of the lack of activity. If this is not fixed in 4.0, and you are interested in seeing it fixed, add a :+1: to the ticket to bring it to our attention.

If you can add additional details, that would also be useful.
