### ISSUE TITLE
Hierarchical multiple select - parent items are completely removed from drop down, cannot add their children

### ISSUE THREAD

**Issue by ni-ka** [select2/select2#795]
Hey,

in earlier versions it was possible to select a parent element in multiselect, and its children elemen where still selectable. The parent element was disabled and could not be selected anymore but its children were not removed from the drop down.

Now the behavior has changed and items are removed completely upon selection, so if you select a parent item you can't select any of its children anymore.

See http://plnkr.co/edit/UQ3ur38TC6uVxLv8xvUr?p=preview

compared to http://plnkr.co/edit/a6rrYHYbLDtEB27K3j77?p=preview (version 3.2, has another issue though).

Maybe the behavior should be configurable?

Best,

Nils

**Comment by chrisVillanueva** [comment]
+1

**Comment by alexweissman** [comment]
As of v4: https://select2.org/options#hierarchical-options

> Only a single level of nesting is allowed per the HTML specification. If you nest an `<optgroup>` within another `<optgroup>`, Select2 will not be able to detect the extra level of nesting and errors may be triggered as a result.

> Furthermore, `<optgroup>` elements cannot be made selectable. This is a limitation of the HTML specification and is not a limitation that Select2 can overcome.

> If you wish to create a true hierarchy of selectable options, use an `<option>` instead of an `<optgroup>` and change the style with CSS. Please note that this approach may be considered "less accessible" as it relies on CSS styling, rather than the semantic meaning of `<optgroup>`, to generate the effect.
