### ISSUE TITLE
Maximum number of results in drop down list

### ISSUE THREAD

**Issue by ghost** [select2/select2#813]
In case of using Select2 for tagging, there should be an option to limit numbers of results in drop down list.

I've made up my own solution for this issue, hope somebody can improve it

``` js
populateResults: function(container, results, query) {
    ...
    // get maxResults from user defined parameters
    var maxResults = this.opts.maxResults;
    ...
    populate = function(results, container, depth, maxResults) {
        // maximum number of loop iteration must be smaller than (or equal to) actual number of results
        maxResults = (maxResults === null) ? results.length : Math.min(results.length, maxResults);

        var i, l, result, selectable, compound, node, label, innerContainer, formatted;
        for (i = 0, l = results.length; i < maxResults; i = i + 1) {
            ...
        }
    };
    populate(results, container, 0, maxResults);
}
```

**Comment by siccovansas** [comment]
Chosen has such an option called `max_shown_results`. It is quite useful if you have a lot of options and don't use AJAX. Can this option be reconsidered for inclusion?

**Comment by davidjb** [comment]
Found this issue when loading 2000+ items via JSON (without AJAX).  It's more efficient to load the data one time, minified into the JS of the page, because I have various fields with the same data.  However, the performance is crushed because select2 renders all the items each time the select menu appears.

As @siccovansas suggests, an option to limit the number of shown results would be the solution, so +1 to that.

**Comment by bradly** [comment]
This is especially problematic when using an image in the templateResult. If you have 200 items, 200 images try to load at the same time.

**Comment by farshidahmadianpin** [comment]
> FYI I found this to work better:
> 
> ```
>                 if (data.results.length > opts.maximumResultsForSearch) {
>                       render("<li class='select2-no-results'>Please enter more characters</li>");
>                       if (initial && this.showSearch) this.showSearch(true);
>                       return;
>                 }
> //just before this existing code
>                 if (data.results.length === 0 && checkFormatter(opts.formatNoMatches, "formatNoMatches")) {
>                     render("<li class='select2-no-results'>" + opts.formatNoMatches(search.val()) + "</li>");
>                     return;
>                 }
> ```

hi bro
how i can use this code?
