### ISSUE TITLE
Select2 doesn't remove selection from ajax loaded multi-select

### ISSUE THREAD

**Issue by bradrobertson** [select2/select2#839]
I _think_ this is a bug, at least I couldn't find any doco to suggest you can configure this, but I have [an example typeahead app](http://peaceful-waters-7931.herokuapp.com/) to search for contacts. When you actually select the contact, they aren't removed from the dropdown list, but _are_ added to the selected items.

Am I missing something here? btw I can un-minify the JS if that makes things easier, but the config is pretty bog standard according to the docs

**Comment by foxontherock** [comment]
It's still present in 4.0 RC2, when we reload data from ajax. 
We tried to "hack it by removing the selected data from the datasource in the "processResults" event, but see the "old" html component drawn with the selected item for a few milliseconds, before it is redrawn without that selected item.

**Comment by rodmarzavala** [comment]
I know it's been a while since someone wrote to this thread, but just in case someone else goes through this problem, what I did to solve it was remove this event:

```
.off('change')
```
