### ISSUE TITLE
Deleting an item from multi select2 doesn't change the value

### ISSUE THREAD

**Issue by bradrobertson** [select2/select2#840]
Check out [this typeahead](http://peaceful-waters-7931.herokuapp.com/) example. If you select a few people and check the input's value, it looks ok. Delete one person and check the value again, it doesn't change:

```
 // Select a few contacts
$("#q").val()
=> "2,9,15"
// delete the last selected contact
$("#q").val()
=> "2,9,15"
```

**Comment by Nguyenchathien** [comment]
nothing to say
