### ISSUE TITLE
Select2 Changes Form Submit Behaviour

### ISSUE THREAD

**Issue by nkenneweg** [select2/select2#841]
If you submit a form with a select and nothing is selected there is no value for said select.
With select2, it has an empty string as value.
This behaviour change can lead to problems if you expect a key to be absent if nothing is selected.

**Comment by iraklisg** [comment]
2016 and the problem is still there....

**Comment by Bighamster** [comment]
2017 and the problem is still there....

**Comment by alexweissman** [comment]
@Bighamster Select2 no longer uses the hidden `<input>` in v4.  Have you upgraded to v4 and started using a `<select>` element instead?

**Comment by Bighamster** [comment]
@alexweissman The problem is that Select2 (in multiple mode) returns  an array (i.e. ["1","2"]). To get a string on form submit  (like "1,2") I have to use the jQuery hack:
```js
$.valHooks[ 'select-multiple' ] = {
  get:  function( elem ) {
          var $this = $( elem );

          if ($this.hasClass("select2-hidden-accessible")) {

            return $.map($this.select2('data'), function(e){ return e.id;}).join(',');
          } else {

            return $.valHooks['select'].get( elem );
          }
        },
  set:  function(elem, value) {

          return $.valHooks['select'].set( elem, value);
        }
  };
```
It would be nice to have to switcher to a string mode.

**Comment by alexweissman** [comment]
When you say "Select2 (in multiple mode) returns an array", what do you mean by "returns"?  Are you talking about the way the values are encoded in the request body?  Or, are you talking about the return value of [`.val()`](http://api.jquery.com/val/)?

If it's the latter, then an array _is_ consistent with the way `.val` is supposed to work, according to jQuery's documentation:

> When the first element in the collection is a select-multiple (i.e., a select element with the multiple attribute set), .val() returns an array containing the value of each selected option.

**Comment by Bighamster** [comment]
@alexweissman You are right. There is no problem. I'm just a little confused in the settings of simple_form and select2.
