### ISSUE TITLE
using the disable or enable method with select2 doesn't change the disabled property of the element that it's replicating

### ISSUE THREAD

**Issue by Zxurian** [select2/select2#850]
if I have select2 on an input hidden, and then use the select2 method to disable, the input hidden still remains enabled.

my thinking says that if your disabling / enabling select2, then whatever element it's attach to should also be disabled / enabled.

this came up when I was running a check to determine if the element itself was disabled. If there's a different way to check if select2 is either enabled or disabled for a particular element, I could use that as well.

**Comment by notflip** [comment]
Blowing the dust of this topic, It's still happening for me, anyone else experiencing issue's?

**Comment by code-atom** [comment]
@notflip, As of Select2 4.1, they've removed support for .enable
`$("select").prop("disabled", true); // instead of $("select").enable(false);`

**Comment by GeraElem** [comment]
Hello
 I found this way.

$('#descJugador').select2('val', this.id);
$('#descJugador').select2('data').disabled = false;
$('#descJugador').select2('data', null);

If you do that, the select2 refresh the value dynamically
