### ISSUE TITLE
id: callback function doesn't work with AJAX

### ISSUE THREAD

**Issue by emersonthis** [select2/select2#852]
I've figured out that I need to add the id: callback function to the constructor in order to submit the value (text:) from my selection instead of the selected object's ID. However, when I add this to a <select> that uses the ajax: helper, it doesn't work.

**Comment by allenwlee** [comment]
wanted to comment that `id` values must still be strings, not integers, in the version I am using (3.5.2), which is still the latest version available in the `select2-rails` gem.

**Comment by expient** [comment]
Hi I've been trying this, but it's not working for me.

I have it set up just like emersonthis commented on Feb 13, 2013 above.

I've tried passing in "data" and "object". It still submits the id.

Any suggestions??

id: function(data) {
    return data.text;
},

**Comment by snimavat** [comment]
Doesnt work for me either on 4.x.x version

**Comment by kevin-brown** [comment]
The `id` callback was dropped in 4.0.0, but there are still ways to handle this.

https://select2.github.io/options.html#my-objects-dont-use-id-for-their-unique-identifiers-what-can-i

**Comment by luchorengo** [comment]
Same issue here. I can not figure out how to submit text instead of IDs using ajax tags.

**Comment by Dinduks** [comment]
Thanks @luchorengo!
