### ISSUE TITLE
AJAX multi-select with Ruby on Rails: value with brackets

### ISSUE THREAD

**Issue by smoil** [select2/select2#860]
This may be framework dependent so feel free to ignore.

With Rails an input field for multiple values is expect to set value to an array

```
<input class="multi-select" id="model_field[]" multiple="multiple" name="model[field][]" type="hidden" value="[1,2,3]" style="display: none;">
```

select2 AJAX multi-select with multiple values expects `value` to not include brackets (will treat the bracketed contents as a single element) `value="1,2,3"`

I'm not sure which if any way is more correct but was wondering if select2 provides a mechanism I can easily tap into that allows me read/set `value` before processing.

Thanks for creating such a solid tool and providing some of the best documentation I've had to pleasure to work with.

**Comment by abrambailey** [comment]
Hey, just wanted to add my solution:

I was getting the following:

So I did

**Comment by lesliev** [comment]
@abrambailey haha, bizarre that I should be looking at this today. I did likewise Abram (though I might change the model if I have to do this more often). Hope you are well!

**Comment by abrambailey** [comment]
@lesliev Somehow I missed this message until now! Glad too see I am approaching your level of hacking skills! I'll be visiting NZ soon, and hope to see you at a meetup :)
