### ISSUE TITLE
possible to hide search drop down in tags mode when working with a blank data set?

### ISSUE THREAD

**Issue by Zxurian** [select2/select2#861]
For a basic tagging use with no data set. ex.

``` javascript
    .select2({
        multiple: true,
        allowclear: true,
        tags: [],
        tokenSeparators: [',', ' ']
    });
```

can it be possible to hide the search dropdown that appears when starting to type since it will never match anything due to the blank dataset?

**Comment by Saeven** [comment]
+1 for disabling on blank tags, it has very little valid semantic.

**Comment by nwalters512** [comment]
+1. It's hard to believe this still isn't an option after more than two years.

**Comment by MattyBearBytes** [comment]
+1 so I don't have to use another tag library when I already have select2 at my disposal

**Comment by tanmad21** [comment]
+1 for option to hide dropdown

**Comment by dlydiard** [comment]
+1 tags mode should be configurable to behave like http://xoxco.com/projects/code/tagsinput/.
i.e. add token on blur, suppress the drop down, tab/enter key can add tokens. i think this behavior is easier to use and more ideal.

**Comment by mmikkel** [comment]
+1

**Comment by pablo-meyer** [comment]
+1

**Comment by raffw7912** [comment]
+1

**Comment by pgifford** [comment]
Here's what worked for me (Select2 4.0.2).  This is based on what @alexlopezit wrote above.

##### CSS
```css
.hideSearch .select2-search,
.hideSearch .select2-results,
.hideSearch .select2-dropdown {
    display: none;
}
```

##### JavaScript
```javascript
var tagMatcher = function(searchParams, data) {
  // This bit taken from Select2's default matcher
  var match = $.extend(true, {}, data);
  if (searchParams.term == null || $.trim(searchParams.term) === '')
    return match;
  // Don't partial match tags, otherwise if a user has a tag 'abc' it is
  // impossible to then create a tag 'ab'.
  if (searchParams.term === data.text)
    return match;
  return null;
}

var opts = {
  allowClear = true,
  dropdownCssClass: 'hideSearch',
  matcher: tagMatcher,
  multiple: true,
  selectOnClose: true,
  tags: true
};

var $myEl = $('#myEl');
$myEl.select2(opts);

// When a tag is created an underlying option is created but
// when the tag is removed the option is not removed.  The lingering
// option combined with selectOnClose: true make it impossible to
// remove the last tag. Since the dropdown is hidden there's no reason
// to keep the options around anyway.
$myEl.on('select2:unselect', function(e){
  $(e.params.data.element).remove();
});
```

**Comment by TheFabio** [comment]
Loved @pgifford answer, nice and simple.

I would live to have it as a parameter though...
+1 to @Saeven commented on 23 Jan 2015

**Comment by nrohler** [comment]
After fooling with tons of non-working solutions, here's what I ended up with (much cleaner IMHO, and works with latest versions that don't support `dropdownCssClass`):

**JavaScript:**
```
$('#select2').on('select2:opening select2:close', function(e){
    $('body').toggleClass('kill-all-select2-dropdowns', e.type=='select2:opening');
});
```

**SCSS:** 
(Also includes styling to round the bottom corners when the dropdown is disabled.)
```
body.kill-all-select2-dropdowns {
  .select2-dropdown {
    display: none !important;
  }
  .select2-container--default.select2-container--open.select2-container--below .select2-selection--single, .select2-container--default.select2-container--open.select2-container--below .select2-selection--multiple
  {
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
  }
}
```

**Comment by RadioWorkflowInc** [comment]
$('#emails','.bootbox').select2({
		tags: true,
		allowClear: false,
		tokenSeparators: [';', '	', ' ']
	}).on('select2:open', function (e) {
	   $('.select2-container--open .select2-dropdown--below').css('display','none');
	});

**Comment by stileinverso** [comment]
@ghost Your solution is the best for my purposes. Thanks!
