### ISSUE TITLE
No Documentation on Json/Ajax response/Request format

### ISSUE THREAD

**Issue by AaronLS** [select2/select2#920]
The ajax example is the Rotten Tomatoes one that formats the results with functions.  But there is no documentation that I can see on what the default json format should be.  I would guess it would include some metadata like page number, that would be needed for virtual scrolling/paging.  What does the request look like that it generates?  I see parameters listed for when you use a function and format the request yourself, but if I don't provide a query function, what is the structure the default ajax request?  I think a simple ajax example that doesn't use functions would be nice, so one can see what the default json response format should be, and what the default request looks like.

{
   count: 10
   pageNumber: 
   rows : [{id:... value:},{id:..., value:sdfsdf
}

or just an array?

[{id:... value:},{id:..., value:sdfsdf

**Comment by salarmehr** [comment]
Please add some info regarding expected server response format.

**Comment by kevin-brown** [comment]
Reopening this for tracking the 4.x branch, this was never really done for the 3.x branch.

**Comment by hquadrat** [comment]
Honestly that was severe effort for me aswell, cost like 2 hours to solve:

that link http://stackoverflow.com/q/16598549/359284

and this code
```
{ results: [choice1, choice2, ...], more: true/false }
```

with this example
```
{ results: [ {id:'CA', text:'California'}, {id:'CO', text: 'Colarado' ]  , more: false }
```

is all that was needed.

I copy it here to save somebody else time for searching. And it's not in the docs at the moment, did I see that correctly? (I hope, maybe just didn't find)

**Comment by kevin-brown** [comment]
There's a section in the docs for it, it just isn't written yet.

https://select2.github.io/options.html#what-should-the-results-returned-to-select2-look-like

Note that the `more` key has been moved under `pagination` in 4.0.0.

**Comment by svigne1** [comment]
It saved me time. Thank You all for the comments! select2 is awesome!

**Comment by hg8** [comment]
It's working great but how can I create groups ?

I tried : 

    {
        "results": {
            "text": "Property Reference",
            "children": [
                {
                    "id": "1",
                    "text": "5742"
                },
                {
                    "id": "2",
                    "text": "5788"
                },
                {
                    "id": "3",
                    "text": "5762"
                },
                {
                    "id": "4",
                    "text": "5711"
                }
            ]
        }
    }

As seen [here](http://stackoverflow.com/a/31482049) in hope to get this : 

    <optgroup label="Property Reference">
         <option value="1">5742</option> 
         <option value="2">5788</option>
         <option value="3">5762</option>
         <option value="4">5711</option>
    </optgroup>

But it is not working. Anyone know the correct format then ?

**Comment by hg8** [comment]
Oh my bad, I forgot `[]`... Correct format is : 

     {
        "results": [
            {
                "text": "Mountain Time Zone",
                "children": [
                    {
                        "id": "CA",
                        "text": "California"
                    },
                    {
                        "id": "CO",
                        "text": "Colarado"
                    }
                ]
            }
        ]
    }
```
