### ISSUE TITLE
Focus not working in jQuery UI 1.10 with modal dialog

### ISSUE THREAD

**Issue by wok** [select2/select2#940]
When creating a modal dialog, the input field which select2 creates cannot be focused.
Works normally with jQuery UI 1.9.

![Screen Shot 2013-02-26 at 20 10 43](https://f.cloud.github.com/assets/445800/197622/0676c71c-8040-11e2-9e49-cc4d07bd90b0.png)

The reason seems to be a changed behavior in jQuery UI dialog which now discards all focus events on elements which are not part of a dialog ( `ui.dialog` function `_createOverlay`. )

I could fix this temporarily by adding a custom CSS class to the drop down:

`$("select").select2( { dropdownCssClass: 'ui-dialog' } );`

However this does not feel like a permanent solution.

Example: https://gist.github.com/wok/5040447

**Comment by hmnshuagarwal** [comment]
Thanks @wok  your solution works for me!!

**Comment by vmarcelo** [comment]
Thanks @wok your solution works for me!!

Note: use select2 version 3.4.5

**Comment by ganholete** [comment]
@wok solution not worked for me, but work just add this in dialog init:

```
open: function () {
  $.ui.dialog.prototype._allowInteraction = function (e) {
  if ($(e.target).closest('.select2-drop').length) return true;
    return ui_dialog_interaction.apply(this, arguments);
  };
  $.ui.dialog.prototype._allowInteractionRemapped = true;
},
_allowInteraction: function (event) {
  return !!$(event.target).is(".select2-input") || this._super(event);
}
```

**Comment by brutaldesign** [comment]
@ganholete Thanks a ton!!!

**Comment by NaveenDA** [comment]
The following code will help you for **all dialog** in your application
```

if (!jQuery.ui.dialog.prototype._allowInteractionModifed) {
    jQuery.ui.dialog.prototype._allowInteraction = function(e) {
        if (typeof e !== "undefined") {
            if (jQuery(e.target).closest('.select2-drop').length) {
                return true;
            }
            jQuery.ui.dialog.prototype._allowInteractionModifed = true;
            return (typeof this._super === "function") ? this._super(e) : this;
        }
    }
}
```
