### ISSUE TITLE
Select2, Bootstrap Modal and IE

### ISSUE THREAD

**Issue by peinearydevelopment** [select2/select2#942]
If you create a very basic application and try to render a single select dropdown in a Bootstrap Modal on an IE browser, when you click on the dropdown, the typeahead and search functionality doesn't work. The multiselect works just fine. I created a sample project(jsfiddle doesn't work with ie8) which I sent to friends with IE9 and IE10 and the issue still exists in them. I'm unable to attach the project to this bug report though.

This is a great library and would love to fully utilize it, but unfortunately a lot of my user base utilizes IE for their browsing.

**Comment by johnnyoshika** [comment]
Like @peinearydevelopment, I was only having this problem in Internet Explorer when using select2 in Bootstrap 3's modal. This answer that was proposed in  #1645  worked for me:

`$.fn.modal.Constructor.prototype.enforceFocus = function () {};`

Source:
http://stackoverflow.com/a/15856139

**Comment by marcoslourinho** [comment]
if someone is still having problems:

.select2-container {
    z-index: 9999 !important;
}
