### ISSUE TITLE
formatSelection and formatResult should accept strings

### ISSUE THREAD

**Issue by ProLoser** [select2/select2#977]
Similar to the `id` property, if you pass a string to `formatSelection` or `formatResult` instead of a function, THAT property will be used instead of `text`.

This covers 90% of use cases without the need to declare a new function.

**Comment by kevin-brown** [comment]
I'm closing this off for two reasons:

1. There hasn't been that much interest in it, and I'd rather keep low-interest feature requests closed for now.
2. Select2 4.0.0 now _requires_ the `text` and `id` options.
