### ISSUE TITLE
Avoid FOUC?

### ISSUE THREAD

**Issue by yongfook** [select2/select2#98]
Great plugin - found uses for it immediately!

However is there any way to avoid the flash-of-unstyled content before the script takes the <select> tags and turns it into the Select2 dropdown? It somewhat spoils an otherwise very nice UX.

**Comment by rthbound** [comment]
We had this problem. Just add `display:  none;` to your select element. Select2 will do this anyway when you initialize it.

**Comment by fahmilatib** [comment]
`display: none` doesn't work well for me. The rendered select2 width goes past its container (maybe it conflicts with my app CSS I'm not sure). I'm using `visibility: hidden` instead. It works really well.

**Comment by dagoss** [comment]
`visibility: hidden` worked for me. In addition, I also needed to specify `size="1"` on `<select multiple>` elements to avoid the element changing shape.
