### ISSUE TITLE
How to fetch data resource from remote using ajax in createSearchChoice

### ISSUE THREAD

**Issue by elbbub** [select2/select2#987]
I'm building a multiple tags field using select2. In case it need to fetch tags from remote through ajax:{...} by querying what user inputed if which matched certain existed tags, or add itself being a new tag. I found a thread of issues which has a pertty same question and the solution looks like to use createSearchChoice, but it not work for me. It work if data from a local array, but not from remote json. Anybody knows why?

**Comment by absin1** [comment]
I think, I have a similar issue. I will try to eloquently express it. I am making ajax calls to get the search results from my database. If the searched item is not there in my db (total_count = 0 in the response), I would want to give option to my users to add the search string as an entry in my database. How do I accomplish this? I am ready to share code (if needed).  All the demonstrations I see online are based on static data. If you know any stack-overflow or forum entry where something similar has been raised, kindly share that.
Thanks a lot for your time! Much appreciated.

**Comment by absin1** [comment]
OK, for the community, I found [this](http://stackoverflow.com/questions/14577014/select2-dropdown-but-allow-new-values-by-user/30021059) post which caters to exactly what I wanted. So consider this closed. 
`$("select").select2({
  tags: true,
  createTag: function (params) {
    return {
      id: params.term,
      text: params.term,
      newOption: true
    }
  }
});`
PS: This is valid for select2 4.0.0 onward.
